### ISSUE TITLE
Memory Leak in Java/Destructor calling not possible

### ISSUE THREAD

**Issue by thargor** [google/or-tools#100]
It is not possible to call ``MPSolver.delete()``, because the destructor is private.
The exception thrown is:
```
java.lang.UnsupportedOperationException: C++ destructor does not have public access
	at com.google.ortools.linearsolver.MPSolver.delete(MPSolver.java:30)
```
Finalizers in java fail silently. Therefore without explicitly calling delete() the native memory leak is invisible to the user.

I don't know the or-tools codebase sufficiently to provide a pull request, but a naive fix should be to make the destructor virtual & public?

**Comment by loehndorf** [comment]
I second this one. Models that are in memory once, stay there until the JVM is shut down.

**Comment by manuelRiel** [comment]
I'm observing the same thing. Memory consumption exploded in some of the previous versions. This concerns all solvers.

**Comment by lperron** [comment]
Strange, nothing has changed.
And I would expect SWIG to be correct, that is to call the C++ dtor when
garbage collecting the java object.

--Laurent

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2015-10-15 12:20 GMT+02:00 Manuel Riel <notifications@github.com>:

**Comment by thargor** [comment]
Maybe it is required to ```%unignore``` the dtor in ```linear_solver.swig```?

Currently SWIG only generates a destructor stub, which is hardcoded to throw the Exception.
This stub is called, but fails silently, because exceptions thrown by destructors/finalize are ignored by the JVM.

You can test if its working by calling ```delete()``` on MPSolver manually. It shouldn't throw ```UnsupportedOperationException```.

**Comment by lperron** [comment]
I pushed the fix.

**Comment by galonsky** [comment]
@lperron we've been having issues with running out of memory when running or-tools with CBC in long running processes

out of curiosity, I tried testing the issue described here:
```
    @Test
    public void testdelete() {

        MPSolver mpSolver = new MPSolver("", MPSolver.OptimizationProblemType.CBC_MIXED_INTEGER_PROGRAMMING);
        mpSolver.delete();
    }
```

and I get the same `java.lang.UnsupportedOperationException: C++ destructor does not have public access` as the reporter. Have tried on both the latest released jnilib, and building from latest master.

**Comment by galonsky** [comment]
disregard above. used the latest jar, and it is no longer throwing.
