### ISSUE TITLE
Expression 

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1002]
Hello,
Shame, I did not get to be #1000     ( :

Is there a way to embed several variables into one expression and then use that expression in a Solver condition. Example:
```python
Var X =              VehicleVar(Node_1_Index)
Var X = Var X + VehicleVar(Node_2_Index)
 ....
```
And then use the final Var X -- which embeds all VehicalVars  -- in a condition?

**Comment by GuyBenhaim** [comment]
Alternatiely, define a sum of several variables in advance, for exampe
VehicleVar(Node_1_Index) + VehicleVar(Node_2_Index) + VehicleVar(Node_3_Index)
and in case only the first 2 are actually needed, use VoidIndex in Node_3_Index that guaranties that  VehicleVar(VoidIndex) is 0 - and does not change the sum.

**Comment by jmarca** [comment]
Not trying to be pedantic, but I can't see any *meaning* behind adding vehicle numbers so I can't think of a simple test to check it out.  Is there another variable you'd like to add together?  

In general, it should be possible to do "math" operations on variables.  I've summed the result of booleans in the past (as in (VehicleVar(A) == VehicleVar(B)), as well as multiplied the result of booleans, both to implement a poor-man's boolean logic.  And I've also performed "regular sums" as in 

```
delivera = time_dim.CumulVar(A)
deliverb = time_dim.CumulVar(B)
solver.AddConstraint(delivera + 3600 <= deliverb)
```

**Comment by GuyBenhaim** [comment]
Thx.
The aim is to generate a condition when the set of variables is not known in advance. That's why we 'loop' to create the full expression:
Var X = VehicleVar(Node_1_Index)
Var X = Var X + VehicleVar(Node_2_Index)
Var X = Var X + VehicleVar(Node_3_Index)

Possible?

**Comment by GuyBenhaim** [comment]
Any tips? (see two options above)

**Comment by jmarca** [comment]
I for one don’t have much to say, because I’m not sure what the issue is. As I said above, it should be possible. 

Have you tried and hit a snag?  Can you give details on what is going wrong?

**Comment by GuyBenhaim** [comment]
Hello,
Code with such loop builds and runs. We still need to validate that it functions as expected.
Thx

**Comment by lperron** [comment]
I would just say this is outside of what we are testing. 
I follow James, I do not understand the semantic you want to achieve with this.

Still, these are integer variables, and you can use them in the solver.
