### ISSUE TITLE
TSP bug (Python): Calculation of distances wrong

### ISSUE THREAD

**Issue by itsmi** [google/or-tools#1003]
Hi, it looks like the TSP algorithm (Python) can't deal with small numbers. 

When I set the locations to
```
    locations = [[0,0], [1,0], [2,0], 
                 [0,1], [1,1], [2,1], 
                 [0,2], [1,2], [2,2]]
```

the result I get is
```
Total distance: 9

Route:

0 -> 1 -> 5 -> 2 -> 4 -> 8 -> 7 -> 6 -> 3 -> 0
```

However, this is not the optimal route and the total distance should be

`1+sqrt(2)+1+sqrt(2)+sqrt(2)+1+1+1+1 = 10.24`

This is a problem as it calculates non-optimal solutions. Is this a known bug and/or is there a fix for this?

[TSP_bug.txt](https://github.com/google/or-tools/files/2725278/TSP_bug.txt)

**Comment by lperron** [comment]
Distances are rounded to integer as the tsp solver is integer only.
If you want to keep some precision, you need to scale them up.
