### ISSUE TITLE
FileNotFoundException when using net472 (or other full net)

### ISSUE THREAD

**Issue by Vito2102** [google/or-tools#1004]
I am attaching simple example project for net472 and netcoreapp2.1. 

[TestOrTools.zip](https://github.com/google/or-tools/files/2725331/TestOrTools.zip)

Run under netcoreapp2.1 is ok, run under net472 throws exception.

There is a problem is with copying dlls to output for net472 (netcoreapp2.1 doesn't need them in output, on publish runtime folder is created).

Does it mean that net472 is no longer supported or it is a bug?

**Comment by lperron** [comment]
https://github.com/google/or-tools/issues/900#issuecomment-432944651

**Comment by Vito2102** [comment]
I tried that solution and it doesn't work.

**Comment by Vito2102** [comment]
Even if I add NuGet package Google.OrTools.runtime.win-x64 manualy, it doesn't work.
