### ISSUE TITLE
Passing parameters to CBC solver

### ISSUE THREAD

**Issue by rlloretb** [google/or-tools#1006]
Could anyone type down a short example on how to pass parameters to CBC solver, preferably under python? Is it not clear to me based on the issues threads.
Is there any official list of CBC parameters currently callable from ortools?

Answering myself the first question:
```python
p1 = pywraplp.MPSolverParameters()
p1.SetDoubleParam(p1.RELATIVE_MIP_GAP, 0.05)
sol1 = solver.Solve(p1)
```

**Comment by Mizux** [comment]
You could pass any parameters using:
https://github.com/google/or-tools/blob/dcfb59bced4fc42e46663f163c2f1ccc3253de93/ortools/linear_solver/linear_solver.h#L483-L493

unfortunately CBC backend wrapper ([cbc_interface.cc](https://github.com/google/or-tools/blob/master/ortools/linear_solver/cbc_interface.cc)) seems to not support it... 

On C++, it seems you can get a pointer to the underlying solver see:
https://github.com/google/or-tools/blob/dcfb59bced4fc42e46663f163c2f1ccc3253de93/ortools/linear_solver/linear_solver.h#L564-L575



note: here an example in C++ with CPLEX backend using `SetSpecific..` https://github.com/google/or-tools/issues/603#issuecomment-427298167

**Comment by ckuehl** [comment]
I believe I have a related issue: I'm trying to adjust the allowable gap for CBC as mentioned here:

https://www.coin-or.org/Cbc/cbcuserguide.html#setGet

If I understand this thread correctly, there is currently no way to do so. Please let me know if I misunderstood.

**Comment by Mizux** [comment]
@ckuehl I would say maybe for GAP it's ok
https://github.com/google/or-tools/blob/0ef6121de1c468e87afd835d07c81dc386a0c858/ortools/linear_solver/cbc_interface.cc#L490-L492
and
https://github.com/google/or-tools/blob/0ef6121de1c468e87afd835d07c81dc386a0c858/ortools/linear_solver/cbc_interface.cc#L374-L376

**Comment by rlloretb** [comment]
Are there any plans to include general parameter passing for CBC solver in 7.2?

**Comment by lperron** [comment]
No. CBC is a not a great solver, the API is really unfriendly.
