### ISSUE TITLE
SetAllowedVehiclesForIndex missing in Python Wrapper

### ISSUE THREAD

**Issue by maxpohlmann** [google/or-tools#1009]
The method `SetAllowedVehiclesForIndex` from the C++ `RoutingModel` is not available in the `pywrapcp.py` file.

**Comment by Mizux** [comment]
AFAIK, this method should be the SWIG wrapper
https://github.com/google/or-tools/blob/581bd2e751ac2185252354aa69b7c65679ca7518/ortools/constraint_solver/routing.h#L598-L603

i.e. I didn't see `SWIG` guard or `%ignore` in https://github.com/google/or-tools/blob/master/ortools/constraint_solver/python/routing.i

**Comment by Mizux** [comment]
On master i got:
```sh
%grep --color "SetAllowed" ortools/gen/ortools/constraint_solver/pywrapcp.py
    def SetAllowedVehiclesForIndex(self, vehicles: 'std::vector< int > const &', index: 'int64') -> "void":
        return _pywrapcp.RoutingModel_SetAllowedVehiclesForIndex(self, vehicles, index)
```

@maxpohlmann are you sure about your statement ?

**Comment by Mizux** [comment]
Found ! `SetAllowedVehiclesForIndex()` is a **new** method API in v7.X and since master is currently v7.0-beta that's why you find it.

I guess run `python -m pip show ortools` you'll see a `v6.10` installed version.

**Comment by maxpohlmann** [comment]
Thank you very much! I was indeed on v6.10. I installed the beta version and it seems to work. Again, thank you! :)
