### ISSUE TITLE
Minizinc card/set_card function not implemented

### ISSUE THREAD

**Issue by skosch** [google/or-tools#101]
Hi,

I'm trying to use the `card` function (which should return the number of elements in a set variable). If I understand correctly, it is turned into the FlatZinc `set_card` function.

After a long while, or-tools spits out `Unknown predicate: set_card` and stops. Does ortools not provide `set` functions, or am I using them incorrectly?

**Comment by skosch** [comment]
Ah, I see. I accidentally had two directories for globals passed to `mzn2fzn`, and that messed it up somehow.

**Comment by skosch** [comment]
Turns out this seems to be an actual issue. I'd be grateful if someone could shed some light on this.

**Comment by lperron** [comment]
Hi,

sets are simply not supported in or-tools.
I only support the minimum for the challenge, that is not floats and no
sets.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2015-10-12 12:11 GMT-07:00 Sebastian Kosch <notifications@github.com>:

**Comment by skosch** [comment]
Ah okay, gotcha. Thanks for the quick reply Laurent!
