### ISSUE TITLE
Use routing for android

### ISSUE THREAD

**Issue by svshishkina** [google/or-tools#1012]
I'd like to use routing in android application. Is it possible to use or-tools on android devices with 32-bit architecture?

**Comment by Mizux** [comment]
1) OR-Tools does not support 32-bit architecture anymore (ed. it may work but we won't officially support it)
2) Android platform (using NDK) is not yet supported.

**Comment by lperron** [comment]
32 bit -> no
Compiling on android -> technically possible, but the makefiles must be heavily tweaked.
