### ISSUE TITLE
[Question] SatSolver: how to chain complex expressions to constraints

### ISSUE THREAD

**Issue by ptr1120** [google/or-tools#1016]
Hello,

I am trying to use the SatSolver for a satisfiability problem which consists
of arbitrarily long expressions with mostly boolean variables connected by the logical operators: and, or, implies, greater, less, not...
So an expression may look like `a => not(b or c and d xor f) ...`.

My problem is when using the `CpModel` in C# that I do not find any method to chain all the single expressions to a single constraint. 
I can add for example binary expressions via `var expressionPart = model.AddImplication(a,b)`, but I do not find a way to chain the resulting expression with the following expressions to one single constraint.

Before I used the ConstraintSolver and was able to dynamicaly create `IntExpr` out of variables and expression parts and these `IntExpr` could ultimately be combined into a single constraint and added to the ConstraintSolver.

Is there any similar functionality for the SatSolver?
Any help would be appreciated.

Best regards,
Peter

**Comment by lperron** [comment]
https://github.com/google/or-tools/blob/master/ortools/sat/doc/channeling.md
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 16 janv. 2019 à 16:42, Peter Bruch <notifications@github.com> a
écrit :

**Comment by ptr1120** [comment]
Hello  lperron,

thank you. I already had a look at this example. What's the essence here, should I create 1 Boolean reified variable for each constraint and connect the binary terms by this reified variable?

Best regards
Peter

**Comment by lperron** [comment]
Yes.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 16 janv. 2019 à 17:49, Peter Bruch <notifications@github.com> a
écrit :

**Comment by ptr1120** [comment]
thanks  lperron,

please give me one more hint. Is there any way to negate a constraint with this approach without the need for converting the expression (as said I have arbitrarily long expressions e.g. `a => !(b || c && d ...)`).
My not working approach for the example ` !(x or y)` is:

```
var x = model.NewBoolVar("x");
var y = model.NewBoolVar("y");
var b = model.NewBoolVar("b");
var b1 = model.NewBoolVar("b1");

model.AddBoolOr(new[] {x, y}).OnlyEnforceIf(b);
model.Add(b==0).OnlyEnforceIf(b1);

model.Add(b1 == 1);
```

**Comment by lperron** [comment]
!(x or y) -> !x and !y
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 17 janv. 2019 à 19:14, Peter Bruch <notifications@github.com> a
écrit :

**Comment by ptr1120** [comment]
Thanks
