### ISSUE TITLE
macos source installation instructions: add `pkg-config` as a prerequisite?

### ISSUE THREAD

**Issue by jbizzle** [google/or-tools#1017]
I recently got a new macbook with mojave 10.14.2 and tried to follow [the build instructions](https://developers.google.com/optimization/install/cpp/source_mac) but got errors configuring the Osi library due to not having installed `pkg-config`:
```
checking for pkg-config... no
checking for COIN-OR package CoinUtils... skipped check via pkg-config, redirect to fallback
checking for COIN-OR package CoinUtils (fallback)... no, dependency coinutils not available
configure: error: Required package CoinUtils not available.
configure: error: /bin/sh './configure' failed for Osi
make: *** [dependencies/install/lib/libOsi.dylib] Error 1
```
Installing it (via macports) fixed everything and `make third_party cc` succeeded. Should `pkg-config` be mentioned as a prerequisite along with `cmake` and `wget`?

**Comment by Mizux** [comment]
Doc has been updated accordingly.

note: I also rework it a little bit to have the swig install in its own step so I can reuse the internal snippet code for each languages...
