### ISSUE TITLE
Time limits not working in the routing library in v7 beta 1

### ISSUE THREAD

**Issue by danmarinescu** [google/or-tools#1018]
In version 6.10 I am able to set the a time limit on the search parameters as described in the documentation https://developers.google.com/optimization/routing/routing_options#search-limits by setting something like

```
search_parameters = pywrapcp.DefaultRoutingSearchParameters()
search_parameters.time_limit_ms = 2000
```

In v7.0-beta1 this option seems to be be gone, as I am getting 
`AttributeError: Assignment not allowed (no field "time_limit_ms" in protocol message object)`

Is this intentional or a bug? If intentional, is there an alternative way to set the time limit?

**Comment by Mizux** [comment]
Proto seems to have change:
Now it use a `google.protobuf.Duration`...
https://github.com/google/or-tools/blob/bac6b7efb67e1f23effd1a39a68f34cecc6435ae/ortools/constraint_solver/routing_parameters.proto#L324-L325

**Comment by danmarinescu** [comment]
Thanks @Mizux! Unfortunately it's a bit unclear to me how I'm supposed to use it. I tried:

```
duration = duration_pb2.Duration()
duration.seconds = 10
search_parameters.time_limit = duration
```

but that resulted in 
`AttributeError: Assignment not allowed to field "time_limit" in protocol message object`

**Comment by danmarinescu** [comment]
@lperron thanks, that worked! Not familiar with protocol buffers at all so I got a bit confused, I appreciate the prompt help from both of you.
