### ISSUE TITLE
MakeEquality for Python

### ISSUE THREAD

**Issue by snkas** [google/or-tools#1027]
I have a large LP for a multi-commodity flow problem. It consists primarily of equality constraints to match the sum of inbound to the outbound flow. In Python right now it is impossible to express equality constraints directly, so I resorted to translating "a = 5" into "5 <= a <= 5", which results in the GLOP solver returning incorrectly UNBOUNDED for the larger problems (e.g. > 1000 equality constraints, I can post an example if desired). Using the solve.cc / solve() binary executable, I am able to solve it though -- presumably because the equality constraints are more efficiently encoded using the MakeEquality, which is not present in the pywraplp.Solver.

Is there already a way to encode equality constraints in Python that I've overlooked?

**Comment by hklarner** [comment]
what happened? Is there a MakeEquality in Python?

**Comment by snkas** [comment]
There is not, but if you define a Constraint with lb=ub it translates it
into an equality constraint.

The reason the flow problem was not being solved was that the
flow-over-edge variables were not explicitly declared positive via the
variable bounds, so OR-tools interpreted them as FR (free-range) instead of
PL (positive). This should theoretically still converge (given that the
objective/constraints do enforce it), but with large cases it did not. This
is fair: I observed the same in other solvers when I input the intermediary
MPS file that OR-tools can output. It is purely in the translation of the
problem to something numerically stable.

**Comment by lperron** [comment]
use ==
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
