### ISSUE TITLE
Python reference API available?

### ISSUE THREAD

**Issue by lihuiknight** [google/or-tools#1029]
Dear author:

Is there a full python API available? I only found C++ API from https://developers.google.com/optimization/reference/.

**Comment by Mizux** [comment]
currently , we can't generate an API reference from the swig generated code.
note: Python API should match the C++ API since it is generated from it...

**Comment by lperron** [comment]
The CP-SAT python reference manual is here:

https://github.com/google/or-tools/blob/master/ortools/sat/doc/reference.md

As said my mizux@, the other solvers are generated by SWIG, and getting the API is complex.

**Comment by orwant** [comment]
There are also examples of the Python API in our documentation:
https://developers.google.com/optimization/introduction/python
