### ISSUE TITLE
Difference between IntVar and NumVar

### ISSUE THREAD

**Issue by lihuiknight** [google/or-tools#1031]
There are two different ways to define variable types, i.e., IntVar and NumVar,

Because there is lack of the detailed references for python, i read the source code of these two types, which are defined as following:
    
def NumVar(self, lb: 'double', ub: 'double', name: 'std::string const &') -> "operations_research::MPVariable *":
        return _pywraplp.Solver_NumVar(self, lb, ub, name)

    def IntVar(self, lb: 'double', ub: 'double', name: 'std::string const &') -> "operations_research::MPVariable *":
        return _pywraplp.Solver_IntVar(self, lb, ub, name)

**Is IntVar used to define for integer variable while NumVar used to define for double variable ?**

**Comment by gtfuhr** [comment]
''' python
I'm using the CBC_MIXED_INTEGER_PROGRAMMING, and finding an Error while executing the second example.

    cost = 2  #Just an example 
    potency = s.NumVar(0,10,'potency') #Defining a continuos variable
    on_State = s.IntVar(0,1,'on_State') #Defining a Integer variable

#### This example work
    solver.Add(objective_function == on_State *  -1000 + pot_Bat_Pos)
#### If i try to minimize the function, obvially it will give me a -1 for the on_State


#### This example does not work, but why?
    solver.Add(objective_function == on_State * pot_Bat_Pos * cost )
# I need to know the actual state of the on_State(If its either zero or one in other restrictions of the program to treat when the pot_Bat is greater than zero)

ERROR ->

--> 109      solver.Add(objective_function == on_State * pot_Bat_Pos * cost )
    110 

~/anaconda3/lib/python3.7/site-packages/ortools/linear_solver/pywraplp.py in <lambda>(self, *args)
    609 def setup_variable_operator(opname):
    610   setattr(Variable, opname,
--> 611           lambda self, *args: getattr(VariableExpr(self), opname)(*args))
    612 for opname in LinearExpr.OVERRIDDEN_OPERATOR_METHODS:
    613   setup_variable_operator(opname)

~/anaconda3/lib/python3.7/site-packages/ortools/linear_solver/linear_solver_natural_api.py in __mul__(self, cst)
    115 
    116   def __mul__(self, cst):
--> 117     return ProductCst(self, cst)
    118 
    119   def __rmul__(self, cst):

~/anaconda3/lib/python3.7/site-packages/ortools/linear_solver/linear_solver_natural_api.py in __init__(self, expr, coef)
    177       self.__coef = coef
    178     else:
--> 179       raise TypeError
    180 
    181   def __str__(self):

TypeError: 


'''

**Comment by lperron** [comment]
This is a linear solver. A product of two variables is not linear.

**Comment by gtfuhr** [comment]
Hello lperron, thanks for the answer, do you know any other solver to solve this, or do you know a way to create constraints accordingly to the assumed value of a variable in a linear problem? Like, if pot_bat_pos > 0  then pot_bat_neg needs to be 0.

**Comment by gtfuhr** [comment]
I guess a better question would be to know if its possible to give a constraint like this one to the Solver:
Its like saying to the model to just utilize one of the variables. Thanks in advance!

A rudimentary example of this constraint:
solver.Add((pot_Bat_Pos >= 0 and pot_Bat_Neg == 0) or (pot_Bat_Pos == 0 and pot_Bat_Neg <= 0))

**Comment by lperron** [comment]
This is standard big-M modeling.

Please look it up.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
