### ISSUE TITLE
Link to Binary Installation is broken

### ISSUE THREAD

**Issue by Muhammad-Altabba** [google/or-tools#1034]
The link to[ Windows Binary Installation ](https://developers.google.com/optimization/install/cs) that is shown in [this web page](https://developers.google.com/optimization/install/dotnet/source_windows), is broken. 

The page https://developers.google.com/optimization/install/cs, shows 404 Page Not Found.

**Comment by Mizux** [comment]
Hi, thanks for the feedback it should point to https://developers.google.com/optimization/install/dotnet/windows
