### ISSUE TITLE
bugs? routing.GetArcCostForVehicle(previous_index, index, vehicle_id)

### ISSUE THREAD

**Issue by lihuiknight** [google/or-tools#1035]
Dear Authors,

It seems that there is a bug in https://github.com/google/or-tools/blob/master/ortools/constraint_solver/samples/vrp_pickup_delivery.py.

In the print_solution function, it seems that the underlying program has encoded each original node id into a new index, which can transfer them by manager.IndexToNode(index) or manager.NodeToIndex(raw_node_id). 

In the program, when we invoke
`index = assignment.Value(routing.NextVar(index))`
the returned index could be larger than the max original node_id. I think it is reasonable because the underlying logic in or-tools may reindex each node.

Despite that, I think a right logic should be maintain the following conclusion, however in my data, it doesn't. So I think there is a potential bug in the logic. 
Note that, in the example data, this bug doesn't occur.
```
pre_node = manager.IndexToNode(previous_index)
cur_node = manager.IndexToNode(index)
distance_1 = routing.GetArcCostForVehicle(previous_index, index, vehicle_id)
distance_2 = data['distance_matrix'][pre_node][cur_node]
assert distance_1 == distance_2

```

**Comment by Mizux** [comment]
How did you define your transit callback, register it, and setup it ?
I mean you may have something like this:
```python
def distance_callback(previous_index, index):
        """Returns the manhattan distance between the two nodes."""
        # Convert from routing variable Index to distance matrix NodeIndex.
        pre_node = manager.IndexToNode(previous_index)
        cur_node = manager.IndexToNode(index)
        return data['distance_matrix'][pre_node][cur_node]

transit_callback_index = routing.RegisterTransitCallback(distance_callback)
routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)
```

`routing.GetArcCostForVehicle(previous_index, index, vehicle_id)` is just calling your callback...

**Comment by lihuiknight** [comment]
Yes. I code my program according to your example.
```

previous_index = index
prefix_city = cur_city
index = assignment.Value(routing.NextVar(index))
cur_city = city_names[manager.IndexToNode(index)]
pre_node = manager.IndexToNode(previous_index)
cur_node = manager.IndexToNode(index)
# dist = routing.GetArcCostForVehicle(previous_index, index, vehicle_id) # bug, will lead 0 sometimes.
dist = data['distance_matrix'][pre_node][cur_node]  # in my code, i use this sentence.

```

**Comment by Mizux** [comment]
Can you add a "print" to check if your callback is call in the second test ?

Also currently, the SWIG wraping doesn't keep alive the callback, so if python gc.collect() is call...., you could try to keep a reference to the callback directly
```python
def distance_callback(previous_index, index):
        """Returns the manhattan distance between the two nodes."""
        # Convert from routing variable Index to distance matrix NodeIndex.
        pre_node = manager.IndexToNode(previous_index)
        cur_node = manager.IndexToNode(index)
        return data['distance_matrix'][pre_node][cur_node]

callback = distance_callback;
transit_callback_index = routing.RegisterTransitCallback(callback)
routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)
....
printer_function(...., callback) # keep callback alive
// try to check if the callback is working properly
print("test callback:{}".format(callback(63, 14)))
// test using routing.GetArcCost....
print("test callback:{}".format(routing.GetArcCostForVehicle(63, 116, 0)))
```

Note: i'm working on C# (done), Java (in progress) and Python (todo) so solve this ownership issue...

**Comment by Mizux** [comment]
one more question, does your distance_matrix is using int ?

Routing Solver is based on top of CP solver which does not support floating point...
maybe the convertion from double to int make the callback always returning `0.0`

**Comment by lihuiknight** [comment]
The type of distance_matrix is double, as shown in our above discussion.

**Comment by Mizux** [comment]
then it's a bug, you must return an int...

**Comment by Mizux** [comment]
Does this fix your issue ?

**Comment by lihuiknight** [comment]
Yes, you can close this issue.

**Comment by hovjr** [comment]
Hi I am getting zero with routing.GetArcCostForVehicle(previous_index, index, vehicle_id).

I changed my distance matrix to integer form however it hasn't resolved the issue.

`
def print_solution(data, manager, routing, solution):
    total_distance = 0
    total_load = 0
    final_df = pd.DataFrame()
    count = 1

    for vehicle_id in range(data['num_vehicles']):
        index = routing.Start(vehicle_id)
        route_distance, route_load = 0, 0
        sequence, load_sequence, dist_from_prev_sequence = [], [], []

        while not routing.IsEnd(index):
            node_index = manager.IndexToNode(index)
            sequence.append(node_index)
            node_demand = data['demands'][node_index]
            # print('vid:', vehicle_id, 'node_id', node_index, 'data id: ', data['ids'][node_index])
            # print(node_demand, data['vehicle_seed_id'], index)
            load_sequence.append(node_demand)
            route_load += node_demand

            previous_index = index
            index = solution.Value(routing.NextVar(index))
            print(previous_index, index, vehicle_id)
            route_distance += routing.GetArcCostForVehicle(previous_index, index, vehicle_id)
            print(routing.GetArcCostForVehicle(previous_index, index, vehicle_id))
`
prints example return:
vid: 2 node_id 12 data id:  28
83.0 [1, 2, 5, 6] 12
12 18 2
0
