### ISSUE TITLE
Any published papers available?

### ISSUE THREAD

**Issue by lihuiknight** [google/or-tools#1036]
Dear Authors, 

I just wonder whether there are some published papers available for the excellent or-tools. 
I want to go deep for routing optimization and details.

**Comment by lperron** [comment]
There are none.

This old paper roughly describe the routing architecture of or-tools.

**Comment by Mizux** [comment]
@lihuiknight  look at https://github.com/google/or-tools/issues/920#issuecomment-435880431

**Comment by lihuiknight** [comment]
looks pretty good. Thank you.
