### ISSUE TITLE
AttributeError RoutingIndexManager

### ISSUE THREAD

**Issue by TuVieja** [google/or-tools#1038]
Hi, 
All Python  routing examples from or-tools-master\ortools\constraint_solver\samples give the same AttributeError:

 - AttributeError: 'module' object has no attribute 'RoutingIndexManager'

Installed from python -m pip install --user ortools.
Thanks, 
![image](https://user-images.githubusercontent.com/6950949/52063876-bafb2a00-2573-11e9-9925-b33aa3ee1870.png)

**Comment by Mizux** [comment]
`master` branch is our development branch using the future API v7.0

pip install the latest stable version aka 6.10
you can check the version using
```sh
python -m pip show  ortools
```

You can get Python routing examples for v6.10 using this url: https://github.com/google/or-tools/tree/v6.10/examples/python
Please note the `v6.10` in the url...

**Comment by hcordioli** [comment]
python -m pip install ortools==7.3.7083 fix both issues (RoutingIndexManager and DefaultRoutingSearchParameters)
