### ISSUE TITLE
Document that Java standard infinity is allowed

### ISSUE THREAD

**Issue by oliviercailloux** [google/or-tools#1039]
As discussed in #736, if indeed `MPSolver.infinity();` is the same thing as [POSITIVE_INFINITY](https://docs.oracle.com/javase/9/docs/api/java/lang/Double.html#POSITIVE_INFINITY), please update the [sample codes](https://developers.google.com/optimization/introduction/java). It makes it officially supported and clearly visible that they are the same thing.

**Comment by lperron** [comment]
Fixed in the source. 
Should propagate to devsite when 7.0 is out.
