### ISSUE TITLE
Vehicle Variable Cost python 

### ISSUE THREAD

**Issue by shashanktrivedi2018** [google/or-tools#1045]
Hi, 
I have to use variable cost as per vehicle, i used the code as following. Solver is giving error. Any help is deeply appreciated. Here is my code:

```python
    # Add Variable Cost as per Vehicle
    for i in range(num_veh):
        cost_callback = create_cost_callback(data,i)
        routing.SetArcCostEvaluatorOfVehicle(cost_callback,i)

def create_cost_callback(data,vehindex):
    """Created call back to get total cost between locations """
    def service_cost(node):
        """ Gets the service cost for the specified location."""
        return data["demands"][node]*data["cost_per_demand_unit"]
    def travel_cost(from_node,to_node,vehindex):
        """Gets the travel cost between two locations  """
        travel_cost = data["distances"][from_node][to_node] * data["vehicle_varcost"][vehindex]
    def cost_callback(from_node,to_node,vehindex):
        """ Returns the total costs between the two nodes """
        serv_cost = service_cost(from_node)
        trav_cost = travel_cost(from_node,to_node,vehindex)
        return serv_cost + trav_cost

    return cost_callback

  data["cost_per_demand_unit"]=0
  data["vehicle_varcost"] = [1,2,3,4]
```

**Comment by Mizux** [comment]
Can you provide the error message as well ?

**Comment by shashanktrivedi2018** [comment]
SystemError: <built-in function RoutingModel_SolveWithParameters> returned a result with an error set

Moment i take out the above code, error also goes. 

Thanks. 
Shashank

**Comment by 270ajay** [comment]
I think your `cost_callback` should take only 2 parameters, not 3. 
```python
def cost_callback(from_node,to_node)
```

Variable cost is working for me... I used something like:
```python

def create_distance_callback(data):
  """Creates callback to return distance between points."""
  distances = data["distances"]

  def distance_callback(from_node, to_node):
    """Returns the manhattan distance between the two nodes"""
    return distances[from_node][to_node]

numberOfVehicles = 5
distance_callback = create_distance_callback(data)

evaluatorList = [distance_callback]* numberOfVehicles
for vehicle_id, evaluator in enumerate(evaluatorList):
    routing.SetArcCostEvaluatorOfVehicle(evaluator, vehicle_id)
```
[https://developers.google.com/optimization/routing/cvrp#entire_program]()

**Comment by shashanktrivedi2018** [comment]
> I think your `cost_callback` should take only 2 parameters, not 3.
> 
> ```python
> def cost_callback(from_node,to_node)
> ```
> 
> Variable cost is working for me... I used something like:
> 
> ```python
> def create_distance_callback(data):
>   """Creates callback to return distance between points."""
>   distances = data["distances"]
> 
>   def distance_callback(from_node, to_node):
>     """Returns the manhattan distance between the two nodes"""
>     return distances[from_node][to_node]
>   return distance_callback
> 
> numberOfVehicles = 5
> distance_callback = create_distance_callback(data)
> 
> evaluatorList = [distance_callback]* numberOfVehicles
> for vehicle_id, evaluator in enumerate(evaluatorList):
>     routing.SetArcCostEvaluatorOfVehicle(evaluator, vehicle_id)
> ```
> 
> https://developers.google.com/optimization/routing/cvrp#entire_program

Thanks for your reply.
Is it because of routing solver constraint or python language constraint, However i tried your solutions too, u have constant cost from one node to other node across all vehicles, which is equivalent to use: 
routing.SetArcCostEvaluatorOfAllVehicles(dist_callback)

**Comment by shashanktrivedi2018** [comment]
> ```c++
>  // Sets the cost function of the model such that the cost of a segment of a
>   // route between node 'from' and 'to' is evaluator(from, to), whatever the
>   // route or vehicle performing the route.
>   // Takes ownership of the callback 'evaluator'.
> void SetArcCostEvaluatorOfAllVehicles(NodeEvaluator2* evaluator);
> ```
> 
> [source](https://github.com/google/or-tools/blob/554cbccaa95b4c11eced13f145de1bf468e1f919/ortools/constraint_solver/routing.h#L635)
> 
> _evaluator(from, to)_ : I think it is because of routing solver constraint.
> evaluator/`cost_callback` should have only `from_node` and `to_node` as parameters
> 
> * Is this not working?
> 
> ```python
> def create_cost_callback(data,vehindex):
>     """Created call back to get total cost between locations """
>     def service_cost(node):
>         """ Gets the service cost for the specified location."""
>         return data["demands"][node]*data["cost_per_demand_unit"]
> 
>     def travel_cost(from_node,to_node,vehindex):
>         """Gets the travel cost between two locations """
>         travel_cost = data["distances"][from_node][to_node] * data["vehicle_varcost"][vehindex]
> 
>     def cost_callback(from_node,to_node): # Changed this
>         """ Returns the total costs between the two nodes """
>         serv_cost = service_cost(from_node)
>         trav_cost = travel_cost(from_node,to_node,vehindex)
>         return serv_cost + trav_cost
> 
>     return cost_callback
> 
> data["cost_per_demand_unit"]=0
> data["vehicle_varcost"] = [1,2,3,4]
> 
> for i in range(num_veh):
>     cost_callback = create_cost_callback(data,i)
>     routing.SetArcCostEvaluatorOfVehicle(cost_callback,i)
> ```

Thanks ajay, as per your suggestion i tried and it worked, below is the code-

    for vr in range(num_veh):
        print(data["vehicle_varcost"][vr])
        dist_callback1 = create_distance_callback1(dist_matrix,data["vehicle_varcost"][vr])
        evaluatorList.append(dist_callback1)
    for vehicle_id, evaluator in enumerate(evaluatorList):
        routing.SetArcCostEvaluatorOfVehicle(evaluator, vehicle_id)

def create_distance_callback1(dist_matrix,v):
  # Create a callback to calculate distances between cities.

  def distance_callback(from_node, to_node):
    return int(dist_matrix[from_node][to_node])*(v)

  return distance_callback
