### ISSUE TITLE
Use OR-Tools to solve Synchronized Vehicle Routing problem

### ISSUE THREAD

**Issue by Muhammad-Altabba** [google/or-tools#1047]
Can OR-Tools be used to solve Vehicle Routing and Scheduling with Time Windows  combined together? 
(i.e. Can OR-Tools solve "Synchronized Vehicle Routing" problem which is the combination of the  Vehicle Routing Problem with Resource Scheduling?)

The problem is to arrange visits of single worker or a group of workers depending on the site.
The case is that some sites needs 1 worker and some others need many workers. For example, one site visit needs 1 field technician with skill A. While some others need: 2 field technicians, one with skill A and the other with skill B. The third site needs 1 field technician with skill B.

I do not want to assign workers to groups; Because it will involve time wasting in some cases.

The case is very generic that suppose to handle all cases of any complexity. However, the current number of locations are hundreds of thousands sites, current workers are in hundreds or thousands, and the number of skills are above 10.

**Comment by lperron** [comment]
Do you know which workers will do each assignment?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 4 févr. 2019 à 14:10, Muhammad Altabba <notifications@github.com> a
écrit :

**Comment by Muhammad-Altabba** [comment]
Sorry your question is not clear to me.
The tasks need to be assigned dynamically to each worker based on the skills needed at each site as described above.

**Comment by Muhammad-Altabba** [comment]
Yes, there are multiple workers that can perform the same visit. This is based on therer skills that match the skill needed at each location.

**Comment by lperron** [comment]
Do you have time windows on the visits?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 5 févr. 2019 à 10:13, Muhammad Altabba <notifications@github.com> a
écrit :

**Comment by Muhammad-Altabba** [comment]
Yes

**Comment by lperron** [comment]
Next question, is travel time relevant? Do you want to minimize traveled
distance or to maximize the number of visits performed?

Does travel time and distances forbid you certains chains of visits for one
worker?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 5 févr. 2019 à 10:55, Muhammad Altabba <notifications@github.com> a
écrit :

**Comment by Muhammad-Altabba** [comment]
Yes, travel time is relevant. There is also expected visit duration and reward for each visit. And the solution should maximize the rewards collected from the visited sites. 
And yes, there is time limits for workers (6 hours a day). So, the solution has to assign the visits to sites that maximize the reward collected during the working day.

**Comment by lperron** [comment]
And how many visits per day in general for one worker?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 5 févr. 2019 à 11:37, Muhammad Altabba <notifications@github.com> a
écrit :

**Comment by Muhammad-Altabba** [comment]
This depend on how much visits he can make. It could be 5 to 10 visits for example.

**Comment by Muhammad-Altabba** [comment]
Any ideas or hints?
Many thanks,

**Comment by lperron** [comment]
Creates all the nodes, create 1 copy per skill, restrict the vehicle var per copy to the persons that have this skill, and force all cumul vars of these copies to be in sync.

**Comment by Muhammad-Altabba** [comment]
Thank you @lperron,

And how exactly to "force all cumul vars of these copies to be in sync"?

**Comment by lperron** [comment]
get the solver from the routing model,
solver->Add(solver->MakeEquality(cumul_var1, cumul_var2)); (in C++)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 9 sept. 2019 à 05:07, Muhammad Altabba <notifications@github.com> a
écrit :

**Comment by Muhammad-Altabba** [comment]
This seems great!
And it would be great if you can document this case and add it to the website.
Many thanks,

**Comment by bsombekke** [comment]
@Muhammad-Altabba Was wondering if you had any success implementing this idea. I was interesting in building something similar. Would love to hear from you...

**Comment by lperron** [comment]
Please do not revive dead issues.
