### ISSUE TITLE
Build flatzinc solver from source

### ISSUE THREAD

**Issue by AnnaSchmitt** [google/or-tools#1048]
I build the flatzinc solver from source using the following gitrepo: [https://github.com/google/or-tools/archive/v6.10.zip](https://github.com/google/or-tools/archive/v6.10.zip)

I run the following commands:
`make third_party`
`make cc fz`

On an `ubuntu 16.04`

But after copying the binary into the bin folder it can't find the required libraries.
Is there a possibility to invoke the makefile to make sure the libraries can be found?

**Comment by Mizux** [comment]
Which bin folder ? did you also copy the lib folder ?

BTW not sure our binary are intended to be relocatable from where they have been built...

**Comment by AnnaSchmitt** [comment]
Yes the bin folder from my system.
I copied the two libraries `libfz.so` and `libortools.so` from the `ortools/lib` folder to the lib folder from my system.
The flatzinc solver returns the following error:
`fz: error while loading shared libraries: libgflags.so.2.2: cannot open shared object file: No such file or directory`

**Comment by lperron** [comment]
you need to copy all libraries from dependencies/install/lib

Just run ldd on fz
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 4 févr. 2019 à 15:10, AnnaSchmitt <notifications@github.com> a
écrit :

**Comment by AnnaSchmitt** [comment]
Yes this fixed my problem.
Thanks for your help!

**Comment by AnnaSchmitt** [comment]
I have another question about the flatzinc solver.
Does it use the original CP solver, or the new CP-SAT solver?

Thank you for your help.

**Comment by Mizux** [comment]
Both, while the solver is the CP solver


it also use the CP-SAT for boolean propagation:
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/flatzinc/solver.cc#L33

**Comment by lperron** [comment]
No no no :-)

The flatzinc solver dropped the original CP solver 2 or 3 releases ago.
It uses the CP-SAT solver.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Please note that if you only need the flatzinc solver, the easiest way is
to use bazel (bazel.io).

Checkout the source
install the latest version of bazel

in the root directory, type

bazel build -c opt ortools/flatzinc/fz

in the end, you will get a stand alone binary (no dependencies except the
system libraries) in bazel-bin/ortools/flatzinc/fz


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
My bad solver.h/solver.cc are dead code the binary fz use sat instead:
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/flatzinc/fz.cc#L173-L190

**Comment by glebbelov** [comment]
Cannot compile with bazel as above, neither with cmake. For both master and stable on Kubuntu 20.04, Bazel says

`ERROR: .../git/ortools/sat/BUILD:344:11: C++ compilation of rule '//ortools/sat:cp_model_expand' failed (Exit 1): gcc failed: error executing command ...`

Observing something buggy with current binary FlatZinc and wanted to check with master/stable

**Comment by lperron** [comment]
You need to specify c++17.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
see https://github.com/google/or-tools/tree/stable/bazel#compilation
