### ISSUE TITLE
Posting constraints based on values of a variable

### ISSUE THREAD

**Issue by lalithsuresh** [google/or-tools#1050]
I'm trying to migrate some models from Minizinc to or-tools in python.

A recurring pattern in my Minizinc code looks like this:
```python
array[1..5] of int: x1 = [1,2,3,4,5];
array[1..5] of var {1, 2}: x2;

array[1..2] of int: y1 = [1,2];
array[1..2] of int: y2 = [10,5];

constraint forall(g in 1..2) (sum([x1[i] | i in 1..5 where x2[i] == y1[g]]) <= y2[g]);

solve satisfy;
```
Here, the constraint extracts out subsets from the array x2 based on the values it might take (in this case, the domain for vars in x2 is y1), and posts a sum constraint on that subset of variables.

In trying to rewrite the above program using python-or-tools, this is how far I got:

```python
from __future__ import print_function
from ortools.sat.python import cp_model

model = cp_model.CpModel()

x1 = [1,2,3,4,5]
x2  = [model.NewIntVar(1, 2, "var%i" % i) for i in range(len(x1))]

y1 = [1,2]
y2 = [10, 5]

for g in range(len(y1)):
   # XXXXX: I think the next line is wrong
   model.Add(sum([x1[i] for i in range(len(x1)) if x2[i] == y1[g] ]) <= y2[g])

solver = cp_model.CpSolver()

status = solver.Solve(model)
if status == cp_model.FEASIBLE:
   for x in x2:
        print('x = %i' % solver.Value(x))
print (solver.StatusName(status))
```

I'm pretty sure the "if" statement within that comprehension shouldn't work, which is why the solver says INFEASIBLE. What's the right and efficient way to mimic the constraint in my Minizinc code?

Thanks a lot!

**Comment by lperron** [comment]
Just look at the generated flatzinc.
The mapping from flatzinc to CP-SAT is pretty straightforward.

Le mer. 6 févr. 2019 à 03:45, Lalith Suresh <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
Here is working code.
You need to create boolean variables corresponding to x2[i] == y1[g]

See:

https://github.com/google/or-tools/blob/master/ortools/sat/doc/channeling.md

```
from __future__ import print_function
from ortools.sat.python import cp_model

model = cp_model.CpModel()

x1 = [1,2,3,4,5]
all_vars = range(len(x1))

y1 = [1,2]
y2 = [10, 5]

x2 = [model.NewIntVar(1, 2, "var%i" % i) for i in all_vars]

for g in range(len(y1)):
    boolvars = [model.NewBoolVar('') for i in range(len(x1))]
    for i in all_vars:
        model.Add(x2[i] == y1[g]).OnlyEnforceIf(boolvars[i])
        model.Add(x2[i] != y1[g]).OnlyEnforceIf(boolvars[i].Not())
    model.Add(sum(boolvars[i] * x1[i] for i in all_vars) <= y2[g])

solver = cp_model.CpSolver()

status = solver.Solve(model)
if status == cp_model.FEASIBLE:
   for x in x2:
        print('x = %i' % solver.Value(x))
print (solver.StatusName(status))
```

**Comment by lalithsuresh** [comment]
Thanks!
