### ISSUE TITLE
Multi Depot and Multi drop with capacity routing

### ISSUE THREAD

**Issue by tk120404** [google/or-tools#1054]
How do we address the multi depots and multi drops with capacity and time window routing problem with cvrptw.py? I have multi demands from drops for two depots in various routes, so the same vehicle can address the pickup goods from the two depots and deliver to the drops in the same route.

**Comment by lperron** [comment]
duplicate nodes at pickup and delivery, make sure the distance is 0 between duplicated nodes, add pickup and delivery constraints.

It should work.
