### ISSUE TITLE
Vehicle Routing Problem with Time Windows:or-tools Example 

### ISSUE THREAD

**Issue by elouali2015** [google/or-tools#1055]
Hello,
I am tring to excute the code below:
https://developers.google.com/optimization/routing/cvrptw#program
I found the error:
from ortools.constraint_solver import pywrapcp
File" /or-tools-6.10/ortools/constraint_solver/../gen/ortools/constraint_solver/pywrapcp.py", line 112
def value(self) -> "PyObject *":
Please help

**Comment by lperron** [comment]
The code is most likely using the 7.0 API.
