### ISSUE TITLE
CP-SAT: Boolean constraints

### ISSUE THREAD

**Issue by tinde19** [google/or-tools#1056]
I have boolean variables and I'm trying to write:

**if x and y then c = true**

I came up with:
```
x = model.NewBoolVar('x')
y = model.NewBoolVar('y')
c = model.NewBoolVar('c')

model.AddBoolOr([x.Not(), y.Not()]).OnlyEnforceIf(c.Not())
model.AddBoolAnd([x, y]).OnlyEnforceIf(c)
```
This actually works, in a simple model it gives the output
x=1 y=0 c=0 
x=0 y=0 c=0 
x=0 y=1 c=0 
x=1 y=1 c=1 

However, when I use this syntax in a more complicated model with a lot more variables it looks like it is overconstrained and it doesn't find a solution.

Any idea on how to write it better?

**Comment by lperron** [comment]
a and b   imply c

is

not(a and b) or c

is

not(a) or not(b) or c

a simple bool or

thus
  model.AddBoolOr([a.Not(), b.Not(), c])



Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
If you need the equivalence, you need the enforce bool and.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by tinde19** [comment]
Thanks!
