### ISSUE TITLE
EnableOutput broken?

### ISSUE THREAD

**Issue by SapphireBrand** [google/or-tools#106]
The following lines seem inconsistent in linear_solver.cc:

void MPSolver::EnableOutput() { interface_->set_quiet(false); }

void MPSolver::SuppressOutput() { interface_->set_quiet(false); }

**Comment by lperron** [comment]
Indeed, I fixed it.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2015-10-15 18:41 GMT+02:00 SapphireBrand <notifications@github.com>:
