### ISSUE TITLE
Java: Create copy of CpModel

### ISSUE THREAD

**Issue by Dignitas** [google/or-tools#1063]
Hello guys,

I've got a short question related to the CpModel. Each time a build a CpModel only a very small number of constraints differ from model to model. So is there any possiblity in Java to create a copy from the CpModel?

I got basically the same problem as [this guy](https://groups.google.com/forum/#!topic/or-tools-discuss/99p6XXvI4Fg)

Thanks alot!

**Comment by lperron** [comment]
You can create the initial model manually, then copy the underlying proto manually, and edit manually.

You need to understand the proto structure:

    https://github.com/google/or-tools/blob/master/ortools/sat/cp_model.proto

and how to manipulate it:

    https://github.com/google/or-tools/blob/master/ortools/sat/doc/model.md
