### ISSUE TITLE
pickup & delivery in one point and AddPickupAndDelivery

### ISSUE THREAD

**Issue by morruth** [google/or-tools#1064]
pickup & delivery in one point seems not working when called AddPickupAndDelivery

f.e if i have depot , 3 points A,B,C and 2 pickup/delivery tasks
 (pickup from B, delivery to C and pickup from C and delivery to A)

what i try to do:
```python
solver.Add(routing.VehicleVar(B_index) ==  routing.VehicleVar(C_index) ) 
solver.Add(time_dimension.CumulVar(B_index) <= time_dimension.CumulVar(C_index))
routing.AddPickupAndDelivery(B_index,C_index)
```
and
```python
solver.Add(routing.VehicleVar(C_index) ==  routing.VehicleVar(A_index) )
solver.Add(time_dimension.CumulVar(C_index) <= time_dimension.CumulVar(A_index))
routing.AddPickupAndDelivery(C_index,A_index)
```

solution in this case should be depot→B→C→A→depot,

but ortools don't find solution

BUT, if I remove calls to `routing.AddPickupAndDelivery`, it can solve problem

what exactly doing AddPickupAndDelivery?
because needed constraints(pickup and delivery points on same vehicle and pickup time < delivery time) is setted in two lines before it

As far as i understand it's documentation, it do some internal tunings for speedup solution
is it correct?
will be any drawbacks, if this method is not called? (other than slower calculations)

**Comment by Mizux** [comment]
`AddPickupAndDelivery()` force the solver to add both nodes at a time so the constraints are true.
i.e. by default solver add node one by one but doing this this will break the constraint on two node.

**Comment by morruth** [comment]
«doing this» - mean «add both nodes at a time»?

**Comment by Mizux** [comment]
i mean if solver only add the node A first, then the constraint `Vehicle(A) == Vehicle(B)` is not respected -> the solver hang.
Take a look at https://github.com/google/or-tools/issues/847#issuecomment-420608114 to have this constraint only enabled if both node are active, in this case you should be able to get rid of the `AddPickupAnddelivery()` function...

**Comment by lperron** [comment]
you can duplicate node c. Add a 0 distance between C and C'. Then add PDP B -> C and C' -> A
