### ISSUE TITLE
How to use routing solver to schedule the delivery along with planning shortest path?

### ISSUE THREAD

**Issue by Abhi001vj** [google/or-tools#1065]
We were thinking about how to use delivery time windows and one question came up is that what if we can  recommend some time windows to the customer when they placed the order.

 My idea on this is to have the unfulfilled orders in a a list and when we start  we will plan the cvrptw with full time windows for every location, so after first iteration we will have time windows to recommend for the customer. Then when another order is placed we will have time windows for all orders but the new one, so we do cvrptw with time windows calculated earlier and but the new order will have the full window, After this iteration we will have the time windows for this order too. By this logic we will run the cvrptw on each new order.

Is there a better way or should we even do recommend schedule to customers or just plan routes given a time window as we do now, I am asking this because I don't have the industry experience in this area and so not so much aware of the business process and I hope someone here will have a better idea of these areas and if it is capable with this library.

Thank you.

**Comment by lperron** [comment]
Do not add a time window at first, plan with all the promised deliveries and this possible delivery.
And suggest the solution to the customer.

Bonus: try a few scenarios with large time windows on the delivery (8-12, 12- 16, 16-20), and get 3 suggestions.
