### ISSUE TITLE
ExportModelAsLpFormat Performance Issues

### ISSUE THREAD

**Issue by chq-matteo** [google/or-tools#1067]
On Linux ExportModelAsLpFormat method used to serialize a problem is slower than expected, it takes often more time to export a model than to find a solution for it.

This is probably related to [https://groups.google.com/forum/#!msg/or-tools-discuss/ykX6m5trSuM/vXtuJqxqBQAJ](https://groups.google.com/forum/#!msg/or-tools-discuss/ykX6m5trSuM/vXtuJqxqBQAJ)

The author of the thread suggests a patch to speed things up

Example of running time for ExportModelAsLpFormat
Number of variables = 40007
Number of constraints = 6017
Time to export = 82.76872015 seconds
Resulting file size = 17 kB

Time to solve on CPLEX Total (root+branch&cut) =   77.94 sec. (66375.23 ticks)

**Comment by lperron** [comment]
Could you try with 7.0 beta? We switched to a different implementation of
the string library, that should be optimized.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 14 févr. 2019 à 23:06, chq-matteo <notifications@github.com> a
écrit :

**Comment by chq-matteo** [comment]
Candidate rects: 40007
Number of variables = 40007
Number of constraints = 6017
Time to export = 0.442540168762 seconds

Amazing, that's more than 180x speedup
I also measured similar speedups exporting other problems

**Comment by chq-matteo** [comment]
Just to clarify, I tested on ortools==7.0b6150 and it has a huge speedup over the stable version.

So this is fixed in 7.0 beta

**Comment by lperron** [comment]
Great.

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 15 févr. 2019 à 08:57, chq-matteo <notifications@github.com> a
écrit :

**Comment by 326623** [comment]
Just have the same issue. The main problem should be the implementation of **void absl::StrAppend()** in or-tools/base/join.cc where you use std::string::reverse() before appending. 

From the documentation of std::string::reverse(): _If new_cap is less than the current capacity(), this is a non-binding shrink request.

This causes the capacity growth to disappear. After I commented out the std::string::reverse() calling in absl::StrAppend(), it goes from 30s to 0.2s.

**Comment by lperron** [comment]
This is fixed in 7.0 as all this code was replaced by the real absl
implementation, aka the optimized one.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
