### ISSUE TITLE
Using OptimizeVar with RoutingModel

### ISSUE THREAD

**Issue by jlcastillo** [google/or-tools#1070]
I would like to know what is the right way to maximize/minimize an IntVar in a routing problem. I.e. a SlackVar, TransitVar or an IntExpr like Sum(Transit(i)*Active(i), Transit(m)*Active(m)). 

My understanding in pseudo code is:

1) OptimizeVar = solver.MakeOptimize()
2) DecisionBuilder = solver.MakePhase(OptimizeVar)
3) routing.Solve(DecisionBuilder)

However RoutingModel doesn't have a way to pass a DecisionBuilder to Solve() in any of its variants. And using routing.solver().Solve(DecisionBuilder) may not be a good idea because RoutingModel will not have a chance to initialize stuff when invoking Solve().

One option could be using routing.AddSearchMonitor(), since OptimizeVar inherits from SearchMonitor.

Other would be using use routing.AddVariableMaximizedByFinalizer().

Any hints?

**Comment by jlcastillo** [comment]
After some testing, it seems the reason why it crashes is that OptimizeVar::AcceptSolution() tries to call IntVar::Value() for a variable that is not bound. This variable is routing.TransitVar(i). However, routing.ActiveVar(i) is actually bound and I can get its value. How can that be possible?

**Comment by lperron** [comment]
use the AddVariableMaximizedByFinalizer()
