### ISSUE TITLE
What is the hardware requirements for Vehicle Routing Problem with Multiple Time Windows

### ISSUE THREAD

**Issue by Muhammad-Altabba** [google/or-tools#1071]
I need to calculate the hardware requirements for using OR-Tools. I could not find this on the website. The problem I am planning to solve with OR Tools is Vehicle Routing Problem with Multiple Time Windows. I need an equation; That is something like, for example:

`RAM_Size = (Vehicles_Coefficient * Vehicles_Count) * (Sites_Coefficient * Sites) * (Time_Windows_Coefficient * Average_Number_of_Time_Windows)`

And if possible, the same for CPU speed, and cores if applicable.

In addition to the time needed roughly. And an approximation of how far the solution is from the optimal.

Many thanks,

**Comment by Muhammad-Altabba** [comment]
And is there any limitations other than the hardware?
Many thanks,

**Comment by lperron** [comment]
Hi,

I am not sure how to answer.

There are no hard constants in the solver, unless obvious ones (max int 32,
max int 64...).
About memory and CPU consumption, the routing solver is currently single
thread. I can only encourage you to try it.

About gaps, the local search technology does not give any meaningful gap.
We do have assignement and lk lower bounds, but they are only useful on
pure problems, to time windows, to precedences...

--Laurent
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
