### ISSUE TITLE
It seems a buggy in linear_solver.cc

### ISSUE THREAD

**Issue by ryuhwanju** [google/or-tools#1075]
Line 469 of linear_solver.cc seems to be a bug.
https://github.com/google/or-tools/blob/554cbccaa95b4c11eced13f145de1bf468e1f919/ortools/linear_solver/linear_solver.cc#L469-L472

I think USE_CBC is correct instead of USE_GUROBI.

**Comment by Mizux** [comment]
Seems to have been fixed internally, on my way to export the fix
