### ISSUE TITLE
JobShop: intervals with stop

### ISSUE THREAD

**Issue by maurosg** [google/or-tools#1076]
I would like to know if there is a way for manage a stop in a job shop without use an interval like the stop time.
I need that an interval can start before the start of stop and can finish after the end of stop. In this case the duration of the intervals can't be a constant because the one that cross the stop is equal to the duration of intervall + duration of stop. 
Any hints?

**Comment by lperron** [comment]
There are multiple versions of this in the mailing list.
See: https://groups.google.com/forum/#!searchin/or-tools-discuss/cp-sat$20breaks%7Csort:date/or-tools-discuss/DA_4Pniwhn8/BH2vO5K1BgAJ

**Comment by maurosg** [comment]
I've solved with your suggest.
I had to create a lot of variables becasue I have a lot of workcenters and tasks but the performance are good.
thanks

**Comment by lperron** [comment]
Good :-)
