### ISSUE TITLE
vehicle start time is not satisfied

### ISSUE THREAD

**Issue by subasgiri** [google/or-tools#1082]
I am using the resource constraints link and made some modification in the link for my project. I am using vehicle load time as vehicle start time [120,180,240] in a list format for 3 vehicles and when i checked the start time of each vehicle in the output, it is [0,120,300]. could you please explain how solver is working internally as the output start time is not same as input start time?

**Comment by Mizux** [comment]
How did you check the StartTime in the solution ? I mean did you read the `CumulVar()` of start node of each vehicles in the dimension you set the StartTime constraint ?

**Comment by subasgiri** [comment]
here is the code where i have given the start time


    vehicle_start_time = [120,180,240]
#     vehicle_unload_time = 0
    solver = routing.solver()
    intervals = []
    for i in range(num_vehicles):
      # Add time windows at start of routes
      intervals.append(solver.FixedDurationIntervalVar(routing.CumulVar(routing.Start(i), time),
                                                     vehicle_start_time[i],
                                                     "depot_interval"))



here is the output i am seeing

Route 0: 0 Load(0) Time(0, 0) ->  0 Load(0) ->  3 Load(0) Time(0, 0) ->  3 Load(0) ->  45 Load(420) Time(4, 4) ->  45 Load(0) ->  49 Load(490) Time(4, 4) ->  49 Load(0) ->  58 Load(810) Time(7, 7) ->  58 Load(0) ->  42 Load(1060) Time(9, 9) ->  42 Load(0) ->  44 Load(1200) Time(10, 10) ->  44 Load(0) ->  63 Load(1970) Time(17, 17) ->  63 Load(0) ->  64 Load(3370) Time(31, 31) ->  64 Load(0) ->  32 Load(4140) Time(38, 38) ->  32 Load(0) ->  31 Load(4350) Time(40, 40) ->  31 Load(0) ->  29 Load(5290) Time(49, 49) ->  29 Load(0) ->  20 Load(5740) Time(53, 53) ->  20 Load(0) ->  26 Load(6140) Time(57, 57) ->  26 Load(0) ->  14 Load(7190) Time(67, 67) ->  14 Load(0) ->  9 Load(7330) Time(68, 68) ->  9 Load(0) ->  7 Load(7470) Time(69, 69) ->  7 Load(0) ->  1 Load(7680) Time(71, 71) ->  1 Load(0) ->  38 Load(7960) Time(73, 73) ->  38 Load(0) ->  55 Load(8030) Time(73, 73) ->  55 Load(0) ->  48 Load(8170) Time(74, 74) ->  48 Load(0) ->  50 Load(8310) Time(75, 75) ->  50 Load(0) ->  47 Load(8380) Time(75, 75) ->  47 Load(0) ->  39 Load(8520) Time(76, 76) ->  39 Load(0) ->  0 Load(8590) Time(76, 76)Load of the route: 8590



Total Load of all routes: 8590
Total Time of all routes: 76min
Total Distance of all routes: 39m
Dropped visits:  [2, 4, 5, 6, 8, 10, 11, 12, 13, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 27, 28, 30, 33, 34, 35, 36, 37, 40, 41, 43, 46, 51, 52, 53, 54, 56, 57, 59, 60, 61, 62, 65, 66, 67, 68]


Route 1: 0 Load(0) Time(403, 403) ->  0 Load(0) ->  36 Load(0) Time(428, 428) ->  36 Load(0) ->  4 Load(70) Time(453, 453) ->  4 Load(0) ->  13 Load(840) Time(485, 485) ->  13 Load(0) ->  21 Load(885) Time(510, 510) ->  21 Load(0) ->  16 Load(955) Time(510, 510) ->  16 Load(0) ->  17 Load(1025) Time(510, 510) ->  17 Load(0) ->  24 Load(1095) Time(510, 510) ->  24 Load(0) ->  15 Load(1235) Time(511, 511) ->  15 Load(0) ->  23 Load(1375) Time(512, 512) ->  23 Load(0) ->  18 Load(1515) Time(513, 513) ->  18 Load(0) ->  25 Load(1655) Time(514, 514) ->  25 Load(0) ->  22 Load(2845) Time(525, 525) ->  22 Load(0) ->  19 Load(3245) Time(529, 529) ->  19 Load(0) ->  66 Load(3315) Time(529, 529) ->  66 Load(0) ->  65 Load(3744) Time(533, 533) ->  65 Load(0) ->  67 Load(3814) Time(533, 533) ->  67 Load(0) ->  28 Load(4514) Time(540, 540) ->  28 Load(0) ->  30 Load(4654) Time(541, 541) ->  30 Load(0) ->  27 Load(4724) Time(541, 541) ->  27 Load(0) ->  37 Load(4974) Time(543, 543) ->  37 Load(0) ->  56 Load(5394) Time(547, 547) ->  56 Load(0) ->  53 Load(5604) Time(549, 549) ->  53 Load(0) ->  40 Load(5744) Time(550, 550) ->  40 Load(0) ->  46 Load(6304) Time(555, 555) ->  46 Load(0) ->  0 Load(6654) Time(558, 558)Load of the route: 6654



Total Load of all routes: 15244
Total Time of all routes: 634min
Total Distance of all routes: 81m
Dropped visits:  [2, 5, 6, 8, 10, 11, 12, 33, 34, 35, 41, 43, 51, 52, 54, 57, 59, 60, 61, 62, 68]


Route 2: 0 Load(0) Time(130, 130) ->  0 Load(0) ->  2 Load(0) Time(155, 155) ->  2 Load(0) ->  12 Load(70) Time(180, 180) ->  12 Load(0) ->  8 Load(630) Time(185, 210) ->  8 Load(0) ->  5 Load(840) Time(187, 237) ->  5 Load(0) ->  11 Load(1260) Time(191, 266) ->  11 Load(0) ->  10 Load(1540) Time(193, 270) ->  10 Load(0) ->  6 Load(1610) Time(193, 290) ->  6 Load(0) ->  61 Load(1960) Time(196, 293) ->  61 Load(0) ->  60 Load(2060) Time(219, 294) ->  60 Load(0) ->  34 Load(2560) Time(249, 299) ->  34 Load(0) ->  59 Load(2700) Time(275, 300) ->  59 Load(0) ->  62 Load(2770) Time(300, 300) ->  62 Load(0) ->  33 Load(3170) Time(304, 304) ->  33 Load(0) ->  57 Load(3240) Time(304, 304) ->  57 Load(0) ->  54 Load(3380) Time(305, 305) ->  54 Load(0) ->  52 Load(3520) Time(306, 306) ->  52 Load(0) ->  51 Load(3940) Time(310, 310) ->  51 Load(0) ->  35 Load(4780) Time(318, 318) ->  35 Load(0) ->  41 Load(4920) Time(319, 319) ->  41 Load(0) ->  43 Load(5130) Time(321, 321) ->  43 Load(0) ->  68 Load(5210) Time(322, 322) ->  68 Load(0) ->  0 Load(5210) Time(322, 322)Load of the route: 5210

**Comment by Mizux** [comment]
I think that, if you want to force the start time of each vehicle, then simply use:
```python
vehicle_start_time = [120,180,240]
for vehicle_id in range(num_vehicles):
        index = routing.Start(vehicle_id)
        time.CumulVar(index).SetRange(vehicle_start_time[i], vehicle_start_time[i])
```

Your sample, is when you want no overlap between vehicles at start node...

**Comment by subasgiri** [comment]
I  tried using the above code but I am getting the below error. could you please suggest?
'str' object has no attribute 'CumulVar'

**Comment by Mizux** [comment]
You must use your time dimension object not the name so if `time` only contains the name of the dimension, you should use:
```python
time = 'Time'
...
time_dimension = routing.GetDimensionOrDie(time)
...
    time_dimension.CumulVar(...)
```

**Comment by subasgiri** [comment]
Can you please check it?

**Comment by subasgiri** [comment]
When I am using the below code I am able to see the vehicles starting at the given time but the time constraints are not satisfied. 

    vehicle_start_time = [0,180,270]
    for vehicle_id in range(num_vehicles):
            index = routing.Start(vehicle_id)
            time_dimension.CumulVar(index).SetRange(vehicle_start_time[vehicle_id], vehicle_start_time[vehicle_id])

how can we add time constraint with different vehicle start times?

**Comment by lperron** [comment]
Have you seen https://groups.google.com/d/msgid/or-tools-discuss/774ef2d6-b3ee-4b40-8d50-e0c4a1de1d48%40googlegroups.com ?
