### ISSUE TITLE
Including or-tools in an existing C# project

### ISSUE THREAD

**Issue by afader** [google/or-tools#1083]
Hi, I have an existing C# project in Visual Studio 2017. I'd like to include OR Tools in the project. I can't figure out how to include it as a dependency in my project.

I've looked at the installation guide here and was able to validate the code. However, there are no instructions on how to use the library from outside of the examples directory. https://developers.google.com/optimization/install/dotnet/windows 

I've also tried to install OR Tools using the NuGet Package Manager in Visual Studio. The package successfully installs in my project. However, VS cannot find the package when I include `using Google.OrTools.LinearSolver;` at the top of a file.

Am I missing something basic?

**Comment by stuarthillary** [comment]
Read the comments on this closed issue 
https://github.com/google/or-tools/issues/900

**Comment by afader** [comment]
@stuarthillary Thanks. Your suggestion here https://github.com/google/or-tools/issues/900#issuecomment-432944651 did the trick.
