### ISSUE TITLE
unable to find Google.OrTool.ConstraintSolver

### ISSUE THREAD

**Issue by WeiChun0723** [google/or-tools#1086]
I install the nuget but unable to find dependency for OrTool.ConstraintSolver, is there any other thing need to install ?

**Comment by Mizux** [comment]
What is the problem ? Can we have some log, the command you run etc... ?

FYI, we have a meta package https://www.nuget.org/packages/Google.OrTools which depends on three runtime packages (linux-x64, osx-x64, win-x64).

**Comment by stuarthillary** [comment]
Do the comments on this issue solve your problem 
https://github.com/google/or-tools/issues/900 ?
