### ISSUE TITLE
Taking too much time to solve

### ISSUE THREAD

**Issue by ankitgupta0310** [google/or-tools#1087]
Dear all,

I managed to make an algorithm using the google OR tools, however, for some of the variables I input, it is not showing any output, as it is running for ages. Do you guys recommend to either use another solution method (Like Simulated annealing) instead of the standard Greedy Descent? Or put a time limit in the code? In any case, how would I manage any of these? 

Any help would be nice.

**Comment by Mizux** [comment]
Which solver ?

**Comment by ankitgupta0310** [comment]
I downloaded the OR tool from Binary, and then updated it to v7.0

**Comment by ankitgupta0310** [comment]
Or sorry, do you mean the packages Im using with my code with google OR tools. They are 
`from ortools.constraint_solver import pywrapcp
`

**Comment by ankitgupta0310** [comment]
@Mizux or by solver, Im currently adapting the VRPCW routing solver. I can post my code if needed

**Comment by Mizux** [comment]
1) Yes you can set a time limit to avoid solver to "hang" infinitely. 
2) For the first solution strategy usually which works best (according to Google internal problem data) is
`PATH_CHEAPEST_ARC` for \*VRP\* problems.

see: 
https://github.com/google/or-tools/blob/554cbccaa95b4c11eced13f145de1bf468e1f919/ortools/constraint_solver/routing.cc#L4251-L4261

**Comment by ankitgupta0310** [comment]
@Mizux, Hey! Thanks for the help. I added these lines in my code

```
  search_parameters.time_limit_ms = 60000
    search_parameters.local_search_metaheuristic = (routing_enums_pb2.LocalSearchMetaheuristic.GUIDED_LOCAL_SEARCH)

```
However, I'm getting that there is no solution found. Even when I extend the time to 20 minutes, I cant find a solution. Im just trying to get a heuristic solution

**Comment by ankitgupta0310** [comment]
Hey @Mizux, thanks for your help. However, when I add these lines, Im getting no solution found. Im trying to get a heuristic solution for my problem. Im getting the same problem when I run it for 20 minutes too. I guess, it's not converging, but I dont know how to make it work. Any help would be nice

```
   search_parameters.time_limit_ms = 60000
   search_parameters.first_solution_strategy = (routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)
```

**Comment by ankitgupta0310** [comment]
I tried using other First solution strategy in the time limit, and it still doesn't output a solution for the desired locations :/

**Comment by ankitgupta0310** [comment]
It works with CHRISTOFIDES. To anyone reading this, try using different first solution strategy when you have big datas. AUTOMATIC also works sometimes.

**Comment by Mizux** [comment]
@ankitgupta0310  Thx for the feedback ! And yes there is no universal set of parameters which just work for any kind of problem.
