### ISSUE TITLE
Visit a node as n-th station in the solution path of a vehicle 

### ISSUE THREAD

**Issue by maxpohlmann** [google/or-tools#1089]
First and foremost: Thank you very much for your work on this awesome tool!

I have a simple TSP with a single vehicle and N nodes that all need to be visited. Is there a way to tell the solver that NodeX should be the n-th node in the solution path of the vehicle (NodeY the m-th, and so on), so that the unconstrained nodes are routed around the constrained ones?

The only possibility I see (and just came up with while writing this) is using a time dimension, where the total horizon is N, the service time for each node is 1, the travel time always 0, and the constrained nodes get time windows of size 1.
Is there a more elegant solution, or is this the only way?

**Comment by lperron** [comment]
I would do service time = 0, travel time always 1, but yes, this is the way
to do it.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 25 févr. 2019 à 12:25, maxpohlmann <notifications@github.com> a
écrit :
