### ISSUE TITLE
CP solver - Reset model 

### ISSUE THREAD

**Issue by FlowT101** [google/or-tools#1090]
Hi, 
I am trying to use the CP-SAT solver for a blocks in boxes problem.
I handle a model with a many integer variables and constraints in order to fit blocks in a box with specific size.

What I am looking for is to clear or reset the model and change the size of box  when the solver's status is INFEASIBLE.

Can we reset the model or do I need to create another one ?

Best regard 
Florian.

**Comment by lperron** [comment]
Currently, you need to create one.
Please note that the solver is actually stateless.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by FlowT101** [comment]
Thank you very much.
