### ISSUE TITLE
time overlap between the vehicle but no time overlap between different routes                                                        

### ISSUE THREAD

**Issue by abhiagra94** [google/or-tools#1095]
Hello,
Currently, I am working on google or tools and I want to put time constraints, demand constraints and new dumping point into the solver and I want my output in such a way that there is no time overlap if a particular vehicle is doing multiple trips and there can be time overlap between the different vehicle doing different trips.
Currently I am able to do these things:

1. Adding time and demand constraint into the solver
2. Incorporating dumping point into the solver
3. Starting different vehicle at different time.
4. Using only one vehicle for the entire trip(in this one vehicle doing multiple trips)

So now how can I put constraints on vehicles(that this vehicle is allowed for multiple trips) and these vehicles can only do one trip into one script?. So that I can optimize the entire route network and also take care of time overlap
Kindly help me with this.

**Comment by abhiagra94** [comment]
@Mizux any comments on this?

**Comment by Mizux** [comment]
You make add Fixed Cost to each vehicle so solver will have incentive to reuse the same vehicle.
Do you want to forbid a vehicle to do a multi-trip **OR** do you want to limit the duration of a vehicle ?

you can add a dimension "count" which add one at each node visited (see Capacity example) and then limit the cumulVar of a vehicle to 1 so it can only visit on node.
