### ISSUE TITLE
Constraint Programming c#

### ISSUE THREAD

**Issue by Mithubiii** [google/or-tools#1099]

**Comment by Mizux** [comment]
You could take a look at:
https://github.com/google/or-tools/blob/master/examples/dotnet/ShiftSchedulingSat.cs
https://github.com/google/or-tools/blob/master/examples/dotnet/TaskSchedulingSat.cs
https://github.com/google/or-tools/blob/master/examples/dotnet/NursesSat.cs

**Comment by Mithubiii** [comment]
How do i add the 4 condtion ??

4\. Over a 3-day period, an employee cannot work with an employee that they have previously worked
    i.e. if they work with S1 Employee 1 on Day 1 then they are unable to work with that Employee on any
    of the other 2 days. This extends to the other positions as well so each employee will work with 9
    distinct other employees over the 3-day period.

**Comment by Mizux** [comment]
you want something like this (not tested at all!):
```cs
 // Exactly one mutual shift 
 foreach (int e1 in Range(numEmployees)) 
 { 
     foreach (int e2 in Range(numEmployees)) 
     { 
        if (e1 == e2) continue; // pseudo code
        var temp = new IntVar[numShifts*numDays]; 
        foreach (int d in Range(numDays)) { 
           foreach (int s in Range(numShifts)) { 
             temp[d*numShifts+s] = work[e1, s, d] * work[e2, s, d]; // one if both employees works together
           }
        }
        // only one shift together allowed 
        model.Add(temp.Sum() == 1); 
     } 
 }
```
close to:
https://github.com/google/or-tools/blob/77be330c0536933f5fda98eb75638b356e56e1e0/examples/dotnet/ShiftSchedulingSat.cs#L143-L156

**Comment by lperron** [comment]
Oops, no multiplication please. 

I would go full Boolean.  One for each employee, shift, day.
One for each pair of employees, day indicating if these two employees work together on that day.
Add implications to link employee shift/day with pair of employees work together.

Then sum() <=1 to make sure the same pairs are not repeated.

**Comment by Mithubiii** [comment]
> you want something like this (not tested at all!):
> 
> ```cs
>  // Exactly one mutual shift on the three days 
>  foreach (int e1 in Range(numEmployees)) 
>  { 
>      foreach (int e2 in Range(numEmployees)) 
>      { 
>         if (e1 == e2) continue;
>         var temp = new BooleanVar[numShifts*numDays]; 
>         foreach (int d in Range(numDays)) { 
>            foreach (int s in Range(numShifts)) { 
>              // True if both employees works together.
>              temp[d*numShifts+s] = (work[e1, s, d] + work[e2, s, d] == 2);  // pseudo code
>            }
>         }
>         // Maximum one shift by employees pair allowed.
>         model.Add(temp.Sum() <= 1); 
>      } 
>  }
> ```
> 
> code inspired by:
> [or-tools/examples/dotnet/ShiftSchedulingSat.cs](https://github.com/google/or-tools/blob/77be330c0536933f5fda98eb75638b356e56e1e0/examples/dotnet/ShiftSchedulingSat.cs#L143-L156)
> 
> Lines 143 to 156 in [77be330](/google/or-tools/commit/77be330c0536933f5fda98eb75638b356e56e1e0)
> 
>  // Exactly one shift per day. 
>  foreach (int e in Range(numEmployees)) 
>  { 
>      foreach (int d in Range(numDays)) 
>      { 
>          var temp = new IntVar[numShifts]; 
>          foreach (int s in Range(numShifts)) 
>          { 
>              temp[s] = work[e, s, d]; 
>          } 
>   
>          model.Add(temp.Sum() == 1); 
>      } 
>  }

Hi Mizux,
Thank you so much. But i have a doubt how will declare my decision variable for the above logic??

**Comment by Mizux** [comment]
did you try:
```cs
// True if both employees works together.
// temp[d*numShifts+s] = (work[e1, s, d] + work[e2, s, d] == 2);  // pseudo code

model.AddImplication(temp[d*numShifts+s], work[e1, s, d]);
model.AddImplication(temp[d*numShifts+s], work[e2, s, d]);
```


ref: https://github.com/google/or-tools/blob/stable/ortools/sat/doc/boolean_logic.md#c-code-5
