### ISSUE TITLE
CP-SAT: member or exists constraint

### ISSUE THREAD

**Issue by Moisan** [google/or-tools#1100]
I am struggling to work around the lack of `member` global constraint that would check if a value occurs in a list of variables. Is there any plan to add it to CP-SAT or is there any efficient workaround currently available?

**Comment by lperron** [comment]
https://github.com/google/or-tools/blob/stable/ortools/sat/doc/channeling.md

along with the fact that you can pass arbitrary complex domains as bounds:

see
https://github.com/google/or-tools/blob/stable/ortools/sat/doc/reference.md#newenumeratedintvar


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 1 mars 2019 à 16:44, Thierry Moisan <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
If you want a count, just sum the boolean variables equivalent to x == value
This was how it was implemented in the original CP solver anyway,
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
