### ISSUE TITLE
AttributeError: 'RoutingModel' object has no attribute 'SetCumulVarSoftLowerBound'

### ISSUE THREAD

**Issue by hagilemha** [google/or-tools#1105]
Is `SetCumulVarSoftLowerBound` no longer supported in python? I am using 6.10.6025. The similar method for UpperBound works fine. 

My use case is to try and shorten the time between a pickup and delivery node, as much as possible.

**Comment by Mizux** [comment]
This method seems still here on master.
```sh
%make python
...
%grep --color -Hn "def SetCumulVarSoftLowerBound" ortools/gen/ortools/constraint_solver/pywrapcp.py
ortools/gen/ortools/constraint_solver/pywrapcp.py:3660:    def SetCumulVarSoftLowerBound(self, index: 'int64', lower_bound: 'int64', coefficient: 'int64') -> "void":
```
