### ISSUE TITLE
SpanCost coefficient

### ISSUE THREAD

**Issue by TeodoraB21** [google/or-tools#1107]
Can someone explain me, on an example, how is the cost calculated if I set global span cost coefficient over the distance dimension?

**Comment by Mizux** [comment]
>  You can then set a cost equal to the maximum of the total distances along each route.

https://developers.google.com/optimization/routing/vrp#distance_dimension

which is computed as:

> max({cumul(end1),...,cumul(endk)}) - min({cumul(start1),...,cumul(startk)})

https://developers.google.com/optimization/routing/vrp#dimension_details

**Comment by TeodoraB21** [comment]
And if I have a time matrix and I add it as a new dimension and I set a span cost coefficient, how will influence the final cost?

**Comment by Mizux** [comment]
the final cost will be `the sum of all arc cost used + coef * (max(EndTime) - min(StartTime))`
