### ISSUE TITLE
Bugged reification of element constraint in CP-SAT?

### ISSUE THREAD

**Issue by jacopoMauro** [google/or-tools#1108]
I am half reifing the element constraint b -> element(x,y,z) but when element(x,y,z) is false b is not set to false.

In the following program, the variable diff should be set to 0 since the element constraint is false.
When executed the cp solver says that is unsat.
If you uncomment the constraint that forces diff to be 0 (model.Add(diff == 0)) then the solver says that is sat. Clearly adding a constraint should not make a problem satisfiable if it is unsatisfiable before.

```python
from ortools.sat.python import cp_model

def reif(model, constraint, neg_constraint):
    bvar = model.NewBoolVar("")
    model.Add(constraint).OnlyEnforceIf(bvar)
    model.Add(neg_constraint).OnlyEnforceIf(bvar.Not())
    return bvar


model = cp_model.CpModel()
solver = cp_model.CpSolver()

ls = [0]

i = model.NewBoolVar("")
j = model.NewBoolVar("")

diff = reif(model, i > j, i <= j)

# model.Add(diff == 0)

model.AddElement(0, ls, 1).OnlyEnforceIf(diff)

status = solver.Solve(model)
print("Status: {}".format(status))
if status == cp_model.FEASIBLE:
    print("diff {} - aux_i {} - aux_j {}".format(
        solver.Value(diff),
        solver.Value(i),
        solver.Value(j)))
```
Am I doing something wrong or is this a bug?

Jacopo

**Comment by lperron** [comment]
The only constraints that can be reified at the moment are:
  - bool or
  - bool and
  - linear constraints
  - interval constraints.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
