### ISSUE TITLE
Build dependencies

### ISSUE THREAD

**Issue by saosebastiao** [google/or-tools#111]
I found two dependency issues with the build instructions:

1) Using Ubuntu 15.04, I found as I built or-tools with make third_party that the build required subversion in order to download some third party code for compilation. This dependency should be listed on the build dependencies. 

2) Using Ubuntu 12.04, I found a build dependency on CMake >= 2.8.12. The default CMake on 12.04 is 2.8.7, which required that I install a ppa to get the dependency. Would it be possible to include a CMake source/binary in the third_party build?

**Comment by lperron** [comment]
I fixed the documentation for 1)

For 2, unfortunately, 12.04 is too old to justify the effort of adding cmake to dependencies as source.
As of binary, it creates a new set of legal/engineering issues. So I will not fix it.
