### ISSUE TITLE
How AddDisjunction works?

### ISSUE THREAD

**Issue by TeodoraB21** [google/or-tools#1110]
I have 9 nodes and 2 vehicles. Vehicle 1 has start 0, end 0 and vehicle 2 has start 4, end 0.  
The cost of these routes is 50.
If I set this: `routing.AddDisjunction(data.GetNodes(), 1000, 9)` (because I want that all of them to be part of the solution if is possible), all the orders are dropped.  
**Why ?**  
The cost to take them all is 50, which is less than 1000.
* `data.GetNodes()` - returns all nodes, except for start and stop of each vehicle.

If I set `routing.AddDisjunction(data.GetNodes(), 1000, 5)`, there is a solution returned with orders `1` and `3` dropped and the cost is `23`.

Can someone explain me what is happening?

**Comment by TeodoraB21** [comment]
I replace that setting with this:
for (int i = 0; i < data.GetNodes().size(); i++)
{
	std::vector<RoutingModel::NodeIndex> orders(1, data.GetNodes().at(i));
	routing.AddDisjunction(orders, 10);
}

Now it works very good, but I still don't understand why.

**Comment by Mizux** [comment]
Did you take a look at the c++ comment ?
https://github.com/google/or-tools/blob/fb80249158c1e56144edf068e716af4ecb332031/ortools/constraint_solver/routing.h#L522-L539

**Comment by TeodoraB21** [comment]
Yes, without 0 and 4, there are 7 nodes.

**Comment by Mizux** [comment]
Then in this case `routing.AddDisjunction(data.GetNodes(), 1000, 9)` is ill formed since `data.GetNodes()` contains 7 nodes but you request `9` as max cardinality.

**Comment by TeodoraB21** [comment]
If I set routing.AddDisjunction(data.GetNodes(), 1000, 7), all the orders are dropped

**Comment by Mizux** [comment]
what is the output of `data.GetNodes()` ? (ed. should be `{1, 2, 3, 5, 7, 8, 9}`)

**Comment by TeodoraB21** [comment]
Dropped orders: 1, 2, 3, 5, 6, 7, 8

**Comment by TeodoraB21** [comment]
I have another problem:
Stops
10
Vehicles
2
StartEndIndex
0 7
2 9
MinDistance
0
0
MaxDistance
2000
2500
MinNumberOfStops
2
3
MaxNumberOfStops
6
8
Distances
0 1875 1584 1648 429 112 1404 123 1893 1390
1875 0 600 302 369 685 1473 873 506 1818
1584 600 0 861 1012 263 993 260 987 213
1648 302 861 0 1843 1813 1244 1491 1090 619
429 369 1012 1843 0 820 1073 1882 1411 1582
112 685 263 1813 820 0 1381 299 1994 125
1404 1473 993 1244 1073 1381 0 1235 725 110
123 873 260 1491 1882 299 1235 0 38 1949
1893 506 987 1090 1411 1994 725 38 0 358
1390 1818 213 619 1582 125 110 1949 358 0
Times
0 20 19 129 98 65 174 75 39 103
20 0 99 90 117 162 188 69 81 163
19 99 0 7 198 94 33 22 164 22
129 90 7 0 161 44 47 158 97 16
98 117 198 161 0 42 115 200 104 46
65 162 94 44 42 0 129 112 124 27
174 188 33 47 115 129 0 99 7 161
75 69 22 158 200 112 99 0 24 16
39 81 164 97 104 124 7 24 0 108
103 163 22 16 46 27 161 16 108 0

If I don't set a disjunction, this is the output:
Total cost:4060
Dropped orders:
Route nr:0
Index:0 distance:0
Index:5 distance:112
Index:4 distance:932
Index:1 distance:1301
Index:8 distance:1807
Index:7 distance:1845
Route nr:1
Index:2 distance:0
Index:3 distance:861
Index:6 distance:2105
Index:9 distance:2215

And if I set the disjunction to be 4000 for every stop (without the start and ends stops of every vehicle), this is the output:
Total cost:10289
Dropped orders: 3 4
Route nr:0
Index:0 distance:0
Index:7 distance:123
Route nr:1
Index:2 distance:0
Index:5 distance:263
Index:1 distance:948
Index:8 distance:1454
Index:6 distance:2179
Index:9 distance:2289

Why does it prefer to drop the orders and take the penalty, instead of adding them? The cost will be smaller if it will add the stops to the route.

**Comment by Mizux** [comment]
Well, if the order are not drop the objective cost will be increased by the arc cost added in the route to pass by them, also you horizon (i.e. max vehicle distance) can make them out of reach for any vehicle.

**Comment by TeodoraB21** [comment]
It will be better if it adds the arc cost of passing by them, because the total cost will be smaller (look at the first output). Also, the horizon is big enough to let them reach each stop.
