### ISSUE TITLE
RegisterUnaryTransitCallback() in C++

### ISSUE THREAD

**Issue by TeodoraB21** [google/or-tools#1112]
I want to set the maximum and minimum number of stops that each route should have, but i don't want to create a new dimension which will only return 1 for each added stop, and I saw that there is this function in python. Does anyone knows if something equivalent exists in C++?
```python
routing.RegisterUnaryTransitCallback(lambda index : 1)
```

**Comment by Mizux** [comment]
1) Why you don't want to create a dimension ?
2) yes on master you have:
https://github.com/google/or-tools/blob/842d1a4d24273acd3a091037eefcf545cc5a1ad1/ortools/constraint_solver/routing_types.h#L40
https://github.com/google/or-tools/blob/842d1a4d24273acd3a091037eefcf545cc5a1ad1/ortools/constraint_solver/routing.h#L230
https://github.com/google/or-tools/blob/842d1a4d24273acd3a091037eefcf545cc5a1ad1/ortools/constraint_solver/routing.h#L362-L363

BTW python is a WRAPPER on C++ (i.e. `ortools` is a **native** python package)
