### ISSUE TITLE
SOS constraints in or-tools?

### ISSUE THREAD

**Issue by rlloretb** [google/or-tools#1113]
Is it possible to specify SOS constraints in the linear programming module? Many MILP solvers are compatible with such specification.

**Comment by Mizux** [comment]
seems related to  #1084 #1085

**Comment by rlloretb** [comment]
Actually CBC solver is also compatible with SOS. :)

**Comment by rlloretb** [comment]
FYI, since version 2.10.0, CBC includes new handling of SOS constraints. It would be nice if SOS constraints in or-tools also worked for CBC.

Release 2.10.0
Improved handling of SOS, starting point, and symmetries.
https://github.com/coin-or/Cbc

**Comment by lperron** [comment]
I just pushed limited support for SOS:

You need to use the protobuf API
It is currently only supported for SCIP and Gurobi.

**Comment by rlloretb** [comment]
Can you please point out how to indicate ortools that a constraint is of the SOS type?

**Comment by lperron** [comment]
Look at linear_solver.proto on master

**Comment by lperron** [comment]
You need to use the linear solver protobuf interface 

http://google.github.io/or-tools/python/ortools/linear_solver/pywraplp.html#pywraplp.Solver.SolveWithProto

It takes a response proto as input (not used), and will return the computed solution proto.

Please note that currently, this is only supported for SCIP and Gurobi.
