### ISSUE TITLE
CVRPTW solved with varied vehicle speed

### ISSUE THREAD

**Issue by daoducminh** [google/or-tools#1118]
I'm trying to use ORTools to solve Capacity VRP with Time Windows (CVRPTW) with some sample records from [VRP World Records](https://www.quintiq.com/optimization/vrptw-world-records.html). So here is a part of 1 record
````
c1_4_1

VEHICLE
NUMBER     CAPACITY
 100          200

CUSTOMER
CUST NO.  XCOORD.    YCOORD.    DEMAND   READY TIME  DUE DATE   SERVICE TIME
 
    0     100        100          0          0       1501          0
    1     181        172         10        348        419         90
    2     154         31         10        795        860         90
    3     123        106         20        747        797         90
    4      23        137         20        703        763         90
    5     190         28         20        115        177         90
    6       8         71         10        713        783         90
    7     103        130         20        369        426         90
    8      62         50         20        486        555         90
    9      89        161         10        309        385         90
   10     117         91         20        446        513         90
   11      12        156         30        540        580         90
   12      88        165         30        220        286         90
   13     107        125         10        657        697         90
   14       8         74         20        535        595         90
   15     105        125         10        746        793         90
   16     118        192         30        243        309         90
   17     146         11         10        100        160         90
   18      93         13         30        525        595         90
   19     188        125         10        426        484         90
   20      87        117         10        832        881         90 
   ````
And I used this example to solve: [CVRPTW Python Example](https://github.com/google/or-tools/blob/stable/examples/python/cvrptw.py).
The problem is: this sample record doesn't have information about vehicle speed, which make it can't be solved with time window constraint. I have tried lots of different vehicle speeds, but it didn't work. Therefore, I'm searching for a way to make vehicle speed varies from a min value to a max value.
Can I have some advises?

**Comment by stuarthillary** [comment]
Take a look at this thread https://groups.google.com/forum/?fromgroups#!searchin/or-tools-discuss/Adding$20dimension$20with$20individual$20vehicle$20performance%7Csort:date/or-tools-discuss/IfbHoUyh56o/Ryw32Mg7AQAJ

**Comment by daoducminh** [comment]
> Take a look at this thread https://groups.google.com/forum/?fromgroups#!searchin/or-tools-discuss/Adding$20dimension$20with$20individual$20vehicle$20performance%7Csort:date/or-tools-discuss/IfbHoUyh56o/Ryw32Mg7AQAJ

Thanks for your help. But that is not what I'm looking for.

**Comment by Mizux** [comment]
According to the documentation:
> The value of time is equal to the value of distance.

https://www.sintef.no/projectweb/top/vrptw/homberger-benchmark/documentation/

BTW this has nothing to do with OR-Tools source code issue (which is the purpose of github issue tracker list at first).

Otherwise your transit callback must be determinist and return a fixed value for a fixed set of inputs. OR-Tools does not support varying speed aka varying Arc Cost....

**Comment by daoducminh** [comment]
> According to the documentation:
> 
> > The value of time is equal to the value of distance.
> 
> https://www.sintef.no/projectweb/top/vrptw/homberger-benchmark/documentation/
> 
> BTW this has nothing to do with OR-Tools source code issue (which is the purpose of github issue tracker list at first).
> 
> Otherwise your transit callback must be determinist and return a fixed value for a fixed set of inputs. OR-Tools does not support varying speed aka varying Arc Cost....

Thanks for your help, @Mizux . I really have missed that.
