### ISSUE TITLE
[Need Help] VRP with condition between node count and max distance

### ISSUE THREAD

**Issue by thucnc** [google/or-tools#1121]
Hello,

I have a VRP problem that needs to set a condition for each vehicle based on its number of visit and its max distance, for example, if a vehicle visits 10 nodes, its travelling distance can not exceed 30 kms, if it visits 9 nodes, it can not travel over 27 kms, etc.... The motivation of such condition is to ensure driver performance/productivity. I've read many existings issues and examples but couldn't find any similar problem.

So may any of you advise ?
Thanks.

**Comment by Mizux** [comment]
You would need to create a dimension counting node, and using a distance Dimension dependent on it.
https://github.com/google/or-tools/blob/2b36515b43e6ce11d26e3a8ac8e97f30d66a3ccf/ortools/constraint_solver/routing.h#L452-L482

**Comment by thucnc** [comment]
Thanks @Mizux , is this api ready in Python ?

**Comment by thucnc** [comment]
Thanks @Mizux . Is this api ready in Python ?

**Comment by Mizux** [comment]
AFAIK not yet please see #339

**Comment by thucnc** [comment]
Hi @Mizux ,
I still don't know how to build a distance Dimension (d) dependent on a node-counting Dimension (c) in such rule that: `if cumvar(c) = 9 then cumvar(d) must < 27, cumvar(c) = 8 then cumvar(d) must < 24 etc...` (so in general, cumvar(d) < cumvar(c)*constant ) May you help ?
