### ISSUE TITLE
VRP: Diluted Matrix

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1123]
Hello,
When many edges (i.e. Node to Node combinations) are irrelevant or are forbidden, is there a scheme to make the solver "ignore" these edges and not 'waste' time on these?

Will feeding a very high value in the distance matrix do the job?   The old documentation 9.6.3 mentions using "M" in the matrix to achieve this; will that work?

**Comment by lperron** [comment]
I do not even know which solver you are talking about :-)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
As the subject hints, it's the Routing library. ( :

**Comment by lperron** [comment]
Sorry :-)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
if you return max value for this edge since the solver can't have a cost above this value , it will forbid the solver to use it in its solution (i.e. forcing it to back track...)

**Comment by GuyBenhaim** [comment]
thx, what is this max value?  Is it the highest possible integer?

**Comment by Mizux** [comment]
should be "int64 max", seems no wrapped in Python AFAIK

**Comment by GuyBenhaim** [comment]
C#  ?

Basically, this way Solver skips that arc and wastes no time on dimensions, constraints, costs, etc?

**Comment by lperron** [comment]
you have cp_model.INT
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
cp_model.INT_MAX

https://github.com/google/or-tools/blob/stable/ortools/sat/python/cp_model.py#L37
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Forget it, wrong solver :-(

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
ok

**Comment by lperron** [comment]
Back to your original question, I would say yes. Return something large,
like 1e6.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
And this way the Solver immediately skips that arc, wasting wastes no time on dimensions, constraints, costs, etc?

**Comment by thucnc** [comment]
> should be "int64 max", seems not wrapped in Python AFAIK

Hi @Mizux can I use max int64 = 9223372036854775808 in python ? (According to this https://www.quora.com/What-is-the-maximum-value-for-an-int64)

**Comment by lperron** [comment]
Yes you can.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le dim. 4 août 2019 à 22:54, Thuc Nguyen Canh <notifications@github.com> a
écrit :

**Comment by thucnc** [comment]
Thank you @lperron,

On the other hand, do we have any way to make the solver prefer nearest edges first, suppose that we will set time limit for the solver ? (such as we can determine some probability or score to nearest edges ?)
