### ISSUE TITLE
Type or Namespace 'System' Could not be Found

### ISSUE THREAD

**Issue by Draco18s** [google/or-tools#1124]
I've downloaded and installed the OR Tools following the directions at https://developers.google.com/optimization/install/
All of the samples available from that installation work correctly and reference OR Tools v6.10.

However, downloading this repo and attempting to open its samples tells me that the Type or Namespace 'System' cannot be found (among others). The solution explorer tells me that there is a problem with the dependencies (it won't tell me what) and shows that it is trying to use OR Tools v7 as well as a warning involving the .NET Core SDK (I have 2.1 and it wants 2.1). I don't know how I can acquire a version of the tools ahead of the publicly available one.

Attempting to run `make` (same command, different folder as what's listed on the install instructions page) on the repo gives me this error:

```
PS C:\Users\Major\Documents\or-tools-master> .\tools\make test_dotnet
makefiles/Makefile.port.mk:138: "Unrecognized visual studio version"
Makefile:57: Makefile.local: No such file or directory
tools\win\which.exe: no cmake in (.;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python37\Scripts\;C:\Python37\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\Users\Major\AppData\Local\Microsoft\WindowsApps;C:\Users\Major\AppData\Local\GitHubDesktop\bin;C:\Users\Major\.dotnet\tools)
makefiles/Makefile.win.mk:91: *** Please add "cmake" to your PATH.  Stop.
```

I did not have this issue on the standard examples.

I added the repo's cmake directory to my PATH environment variables and tried again (same error, including an identical PATH list).

**Comment by Mizux** [comment]
Few questions (to help us to help you):
* Are you using a binary archive ? If yes can you provide the link to avoid any ambiguity
* Which version of Visual Studio do you use ? (we only support VS 2015 and VS 2017 on v6.10)
* You must have cmake installed and added to your path, please take a look at:
https://developers.google.com/optimization/install/cpp/source_windows#prerequisite-cmake
you can test cmake is correctly installed AND in your PATH running the following command in a Windows command prompt:
```sh
cmake --version
```

**Comment by Draco18s** [comment]
Sorry yes, I downloaded the Windows .NET binaries matching my installation of Visual Studio 2017.

https://github.com/google/or-tools/releases/download/v6.10/or-tools_VisualStudio2017-64bit_v6.10.6025.zip

I am interested in one of the examples that's on Github that is not present in the binary.

**Comment by Draco18s** [comment]
Trying to do this from source, because apparently that's what I have to do.

Running `make third_party` resulted in *this* error:

```
PS C:\Users\Major\Documents\or-tools-master> .\tools\make third_party
makefiles/Makefile.port.mk:138: "Unrecognized visual studio version"
tools\win\mkdir.exe -p dependencies\\archives
tools\win\mkdir.exe -p dependencies\\install
tools\win\mkdir.exe -p dependencies\\install\\bin
tools\win\mkdir.exe -p dependencies\\install\\lib
tools\win\mkdir.exe -p dependencies\\install\\lib\\coin
tools\win\mkdir.exe -p dependencies\\install\\include
tools\win\mkdir.exe -p dependencies\\install\\include\\coin
tools\win\wget.exe --quiet -P dependencies\\archives http://zlib.net/zlib1211.zip
tools\win\unzip.exe -q -d dependencies\\sources dependencies\\archives\\zlib1211.zip
tools\win\touch.exe dependencies\\sources\\zlib-1.2.11\\zlib.h
copy dependencies\\sources\\zlib-1.2.11\\zlib.h dependencies\\install\\include\\zlib.h
        1 file(s) copied.
copy dependencies\\sources\\zlib-1.2.11\\zconf.h dependencies\\install\\include\\zconf.h
        1 file(s) copied.
cd dependencies\\sources\\zlib-1.2.11 && set MAKEFLAGS= && nmake -f win32\\Makefile.msc zlib.lib
'nmake' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\Major\Documents\or-tools-master\tools\make.exe: *** [dependencies/install/lib/zlib.lib] Error 1
```

**Comment by lperron** [comment]
You are not using the correct 'terminal' from the visual studio tools.

See pre-requesite:

https://developers.google.com/optimization/install/cpp/source_windows
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Draco18s** [comment]
One, I want to install for C# / .NET, not C++
Second, what do you mean the "correct terminal"? All that page (and the .NET page) says is "First, open a terminal..."

Which I am doing. I am on Windows 10, so that's the Power Shell. If this is not sufficient, then your instructions are wrong.

**Comment by lperron** [comment]
Prerequisite: Visual Studio

To install and run OR-Tools on Windows, you must have Visual Studio 2015 or
later installed on your computer with the C++ toolset for Visual Studio. We
recommend Visual Studio 2017. You can find more details here
<https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017>
.

Then to build OR-Tools programs from the command line you must *always* use
a *x64 Native Tools Command Prompt*(*not* the Developer Command Prompt).
You can find more details here
<https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line#how-to-get-the-command-line-tools>
.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Draco18s** [comment]
Alright then.

```
<6000 other lines>
include/google/protobuf/wrappers.pb.h
include/google/protobuf/wrappers.proto
tools\win\rm.exe -rf dependencies/sources/abseil-cpp-93d155b
git clone --quiet https://github.com/abseil/abseil-cpp.git dependencies\sources\abseil-cpp-93d155b
process_begin: CreateProcess((null), git clone --quiet https://github.com/abseil/abseil-cpp.git dependencies\sources\abseil-cpp-93d155b, ...) failed.
make (e=2): The system cannot find the file specified.
.\tools\make: *** [dependencies/sources/abseil-cpp-93d155b] Error 2
```

Now what?

**Comment by lperron** [comment]
is git installed and available on the PATH ?

From the command line, you should be able to launch 'git' manually.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Draco18s** [comment]
Yes.

```
C:\Users\Major\Documents\or-tools-master>git
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```

**Comment by Draco18s** [comment]
Any further information? As a reminder, here is the error I am currently getting:

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 3/13/2019 7:09:52 PM.
Project "C:\Users\Major\Documents\or-tools-master\dependencies\sources\Cbc-2.9.9\Cbc\MSVisualStudio\v10\Cbc.sln" on nod
e 1 (cbc target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
ValidateProjects:
  The project "cbcCInterfaceDll" is not selected for building in solution configuration "Release|x64".
  The project "cbcCSosDllSample" is not selected for building in solution configuration "Release|x64".
Project "C:\Users\Major\Documents\or-tools-master\dependencies\sources\Cbc-2.9.9\Cbc\MSVisualStudio\v10\Cbc.sln" (1) is
 building "C:\Users\Major\Documents\or-tools-master\dependencies\sources\Cbc-2.9.9\Cbc\MSVisualStudio\v10\cbc\cbc.vcxpr
oj" (2) on node 1 (default targets).
Project "C:\Users\Major\Documents\or-tools-master\dependencies\sources\Cbc-2.9.9\Cbc\MSVisualStudio\v10\cbc\cbc.vcxproj
" (2) is building "C:\Users\Major\Documents\or-tools-master\dependencies\sources\Cbc-2.9.9\Cgl\MSVisualStudio\v10\libCg
l\libCgl.vcxproj" (3) on node 1 (default targets).
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets
(46,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change
 the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:
\Users\Major\Documents\or-tools-master\dependencies\sources\Cbc-2.9.9\Cgl\MSVisualStudio\v10\libCgl\libCgl.vcxproj]
Done Building Project "C:\Users\Major\Documents\or-tools-master\dependencies\sources\Cbc-2.9.9\Cgl\MSVisualStudio\v10\l
ibCgl\libCgl.vcxproj" (default targets) -- FAILED.
```

**Comment by lperron** [comment]
You are most likely using visual studio 2017 community edition.

As written in the error message above, you need to install sdk 8.1.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
> error MSB8036: The Windows SDK version 8.1 was not found.

@Draco18s did you install it ?

According to your previous comment, I would say not...

> I still think the instructions are bad, as the fact that the VS tools are needed are under a header saying Visual Studio is needed. Having VS already, that section looked skippable.

**Comment by Draco18s** [comment]
I have now installed the Windows SDK 8.1 (which, I'll note, is _not_ mentioned in the install instructions, it says "Windows 10" with no references to "8.1" or "SDK").

I now have this error.

```
  c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\crtdefs.h(10): fatal
error C1083: Cannot open include file: 'corecrt.h': No such file or directory [C:\Users\Major\Documents\or-tools-master
\dependencies\sources\Cbc-2.9.9\Cbc\MSVisualStudio\v10\libCbc\libCbc.vcxproj]

    0 Warning(s)
    225 Error(s)
```

(There's 225 instances of the same error, as far as I can tell).

> You are most likely using visual studio 2017 community edition.

I have both installed. Community is automatically installed along side Unity, but I also have VS Professional installed.

![image](https://user-images.githubusercontent.com/1750680/54644812-4d925280-4a68-11e9-95a5-293e93bd951a.png)

**Comment by Mizux** [comment]
in the doc I wrote:

>  you must have Visual Studio 2015 or later installed on your computer **with the C++ toolset for Visual Studio.** 

src: https://developers.google.com/optimization/install/cpp/source_windows#prerequisite-visual-studio

**Comment by Mizux** [comment]
Do you have the "Windows Universal CRT SDK" ?
src: https://stackoverflow.com/questions/38290169/cannot-find-corecrt-h-universalcrt-includepath-is-wrong

**Comment by Draco18s** [comment]
> Do you have the "Windows Universal CRT SDK" ?
> src: https://stackoverflow.com/questions/38290169/cannot-find-corecrt-h-universalcrt-includepath-is-wrong

That one did it. Definitely do update those install instructions, because the way Microsoft packages things all the downloaded files do is open the same installation wizard and don't auto-select specific things.

However while that finally has OR Tools compiling, the specific project I was interested in is throwing its own errors:

`RoutingIndexManager` (class), `RoutingModel` (class), and `operations_research_constraint_solver.DefaultRoutingSearchParameters()` (specific method) are all not found.

I can find the .cc files for these classes, but I am not sure what I need to do in order for the C# project to be able to reference them.

**Comment by Mizux** [comment]
> However while that finally has OR Tools compiling, the specific project I was interested in is throwing its own errors:
> 
> `RoutingIndexManager` (class), `RoutingModel` (class), and `operations_research_constraint_solver.DefaultRoutingSearchParameters()` (specific method) are all not found.
> 
> I can find the .cc files for these classes, but I am not sure what I need to do in order for the C# project to be able to reference them.

@Draco18s  these are class which are on master branch only, if you compile the v6.10 you won't have access to it.
It is likely you are trying to build master samples with a ortools v6.10 build...

**Comment by Draco18s** [comment]
Ah ha, I see. I'll try compiling the master branch then. I'm not used to a repo defaulting to a branch *other* than Master when its downloaded (and other branches have to be selected intentionally). I realize that's a setting you have control of, I've just rarely seen it used.

**Comment by Mizux** [comment]
@Draco18s  IIRC a `git clone` without any branch specified should also bring you to the stable branch...
