### ISSUE TITLE
Unknown status when context of model increases

### ISSUE THREAD

**Issue by cellelo** [google/or-tools#1126]
Hi,

I'm just introducing myself to this library which looks amazing and looking if it could be suitable for requirements. On same time I have to say that I'm not very familiar with science of behind of constraint programming. I would appreciate any advises to my problem which I haven't found any properiate solution and cannot figure to which way to go... 

On small dataset my model perform well and results looks good. On larger dataset result are feasible and solving start solving almost immeadiately. But when going over some step there is not coming any results. 

On problem I try to maximize weighted average of densities of against of maximum density of demand from inventory of stock (kind of blending) with maximized cost. Attached abstracted model from my actual code and mimimal output. On below is point where not getting results with 10 min time limit:
> **Demands: 36**
CpSolverResponse:
status: FEASIBLE
objective: 2.56774e+07
best_bound: 2.56774e+07
booleans: 60163
conflicts: 462057
branches: 10774113
propagations: 857924294
integer_propagations: 79373830
walltime: 600.017
usertime: 599.993
deterministic_time: 115.57

> **Demands: 37**
CpSolverResponse:
status: UNKNOWN
objective: 8240
best_bound: 2.58798e+07
booleans: 39717
conflicts: 56336
branches: 6583910
propagations: 105801161
integer_propagations: 58263393
walltime: 600.002
usertime: 599.993
deterministic_time: 63.9835

Thank you

[Program.txt](https://github.com/google/or-tools/files/2963386/Program.txt)
[satSolvertTestOutput.txt](https://github.com/google/or-tools/files/2963240/satSolvertTestOutput.txt)

**Comment by lperron** [comment]
The problem becomes bigger, harder. And the solver does not find a solution in 10 minutes.

Nothing unexpected.
