### ISSUE TITLE
Question on CVRP constraints

### ISSUE THREAD

**Issue by exilef** [google/or-tools#1128]
Hi, and thank you for providing this great library! I looked into the examples, but could not find any hints whether it can be used for the following variant of a pickup & delivery CVRP. The setting is the following:

- The problem is a CVRP, where each of K>=1 vehicles has a maximal capacity C>0 for items
- At each of N locations either a positive or a negative demand of items has to be satisfied (positive = pick items up and load on vehicle, negative = unload items from vehicle)
- Demands at different locations are weighted by an importance factor
- Only item counts matter, not the items' identity (this is where my case differs from the new [pickup & delivery example](https://github.com/google/or-tools/blob/master/ortools/constraint_solver/doc/pdp.md) here in the repo)
- Loading and unloading operations have to respect capacity, in particular vehicle capacity cannot become negative along the route
- Starting load for a vehicle might be >0 (non empty vehicle at starting point)
- Two cases: (1) all vehicles' starting points are at a defined depot and should be cycles (the easy case, I assume), (2) vehicles' starting points are independent of a depot and do not have to be circles (harder case?)
- At a later point I might want to add time window constraints, but only after the case without time constraints is solved satisfactorily

Any help is appreciated!

**Comment by Mizux** [comment]
seems closer to the capacity example with positive and negative demand.

then you can use the drop node example (disjunction constraints) for weighted nodes...
