### ISSUE TITLE
ist index (0) out of range

### ISSUE THREAD

**Issue by Leungfranklin** [google/or-tools#1129]
I have encountered following errors. Any ideas how to get around it ?
```sh
File "C:\Users\leung\AppData\Roaming\Python\Python36\site-packages\ortools\sat\python\cp_model.py", line 1430, in Value
    return EvaluateLinearExpression(expression, self.__solution)
  File "C:\Users\leung\AppData\Roaming\Python\Python36\site-packages\ortools\sat\python\cp_model.py", line 1349, in EvaluateLinearExpression
    value += coef * solution.solution[expr.Index()]
IndexError: list index (0) out of range
```

**Comment by lperron** [comment]
Please send us some code I can run to reproduce the issue.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 15 mars 2019 à 09:39, Leungfranklin <notifications@github.com> a
écrit :

**Comment by Leungfranklin** [comment]
Please see attached.
You may like to change the directory in os.chdir to the directory you run your program.
 if I comment the statement 'model.AddBoolOr([shifts[(n, d, 2)].Not(),shifts[(n, yesterday, 0)]])', the error will not `appear`

[nursesV1.txt](https://github.com/google/or-tools/files/2970187/nursesV1.txt)

[April2019nursedutytuned.txt](https://github.com/google/or-tools/files/2970215/April2019nursedutytuned.txt)

``

**Comment by lperron** [comment]
Yes, you should check the return status of the solve() before reading the solution.
