### ISSUE TITLE
Error in Make cc on windows

### ISSUE THREAD

**Issue by rhubley** [google/or-tools#113]
cliques.cc
src\graph/cliques.h(296) : error C2144: syntax error : 'double' should be preceded by ';'
        src\graph/cliques.h(356) : see reference to class template instantiation 'operations_research::BronKerboschAlgorithm<NodeIndex>' being compiled
src\graph/cliques.h(296) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
make: *** [objs/graph/cliques.obj] Error 2

It appears 'static constexpr double' isn't supported in windows

link to a related SO question: http://stackoverflow.com/questions/23454507/initializing-a-static-constexpr-double

**Comment by lperron** [comment]
It should be fixed.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2015-11-05 23:42 GMT+01:00 Richard Hubley <notifications@github.com>:
