### ISSUE TITLE
Force a visit time

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1132]
Hi,
Is it possible to force a vehicle to visit its N point within a desired time-window?
(w/o using ADDDWVC ...)

E.g. the vehicle's 4th visit must be within 120-180 mins from starting its journey.

**Comment by GuyBenhaim** [comment]
Any tips here?

**Comment by GuyBenhaim** [comment]
Thx. 
Not sure I fully follow but, seems that you assumed that we wanted a certain Node to be the N-th visit of the vehicle.  The ambition is to have the N-th visit to be at any Node, as long as it meets the required time-window.

**Comment by lperron** [comment]
The only way to do it would be a dimension that ranks visit, and a side constraint using the underlying solve that does the implication: rank == 4 implies the time window.
