### ISSUE TITLE
Linear Solver - API to get infeasible constraint or generate partial solution

### ISSUE THREAD

**Issue by RajmohanKathiresan** [google/or-tools#1133]
Am using a Linear solver for a allocation problem, and it pretty much works as expected.
But at few cases it doesn't yield any response as it couldn't satisfy all constraints.

1. Is there any way to get the infeasible constraint from the solver object ?
2. How to generate the partial solution and compute efficiency of the partial solution ?

Language : Python wrapper

**Comment by lperron** [comment]
1) Not in the C++ API, and you cannot access the underlying solvers from Python.
2) You can do search hinting, but you cannot evaluate partial solutions.
