### ISSUE TITLE
Any reports about the efficiency and memory? 

### ISSUE THREAD

**Issue by lihuiknight** [google/or-tools#1135]
Dear authors,

It seems that this package can achieve suboptimal solution efficient for VRP in small datasets. I wonder 
(1) whether there are some reports about the efficiency and memory used in datasets of different number of nodes and arcs.
(2) Does this package support sparse distance matrix. Specifically, if the distance between two nodes is larger than one threshold, we can suppose there is no an arc between such two nodes. I think it will make the algorithm more efficient.
(3) Does this package support distributed system on multi-machines.

**Comment by lperron** [comment]
1) I have no good answer for you. Please try if it fits your need. It does fit ours, for large models.
2) No, because the way we use it, the graph is nearly always dense.
3) No.

**Comment by lihuiknight** [comment]
It seems that when solving VRP with hunderds of nodes, the algorithm will cost 5GB memory. 
I am not testing this package on the VRP with millions of nodes yet.

**Comment by lperron** [comment]
You have a VRP problem with millions of nodes ? A real problem ?

Interesting.

I would not expect anything for OR-Tools on this without decomposition.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lihuiknight** [comment]
Yes. 
There are millions of logistics each day and we need to make to plan to deliver such large number of goods.

I think we can use hybrid approach to solve such large VRP, such as cluster some nodes as a super node, despite this approach is somehow an approximation of original problem.

**Comment by lperron** [comment]
Rest assured, solving a million node VRP to optimality is completely
unreachable :-)

Every VRP solution first decomposes by date and by region.  You should
target a few 100s of nodes per solve.

Please note that in the context of VRPs, the graph between visits is dense.
So your original question do not apply.
And furthermore, you need to give a distance matrix, which is quadratic in
the number of nodes, so millions :-)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lihuiknight** [comment]
Does or-tools support decomposition? Or I need to decompose the problem specifically?

**Comment by lperron** [comment]
You need to decompose.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
