### ISSUE TITLE
Balance vehicle activity

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1140]
Hello,
What is the best way to balance between the vehicles actually allocated, so each used vehicle serves the same (or a very similar) number of tasks?
Specifically when we do not know in advance how many vehicles would be allocated, and cannot just force an equal share of all tasks to each vehicle.

Is there a way to balance distances traveled? Again, we do not know the total in advance.

**Comment by Mizux** [comment]
GlobalSpan on dimension with unaryTransitCallback returning 1

**Comment by GuyBenhaim** [comment]
Thx. This will 'compress' the difference between the routes/vehicles.
I guess this would also work with time or distance as the base dimension, right?

**Comment by Mizux** [comment]
yes, you are right !

But as you mention it try to compress the longest path, not try to evenly dispatch node (i.e. not minimize the dispersion).
i.e. for the solver these assignments are equivalents (number represent the number visited in each route)
```
[6, 6, 0, 0] == [6, 2, 2, 2]
```

**Comment by GuyBenhaim** [comment]
Does GlobalSpan 'compress'  Max-Min for a certain dimension across all vehicles, like:
(Max( Max(v1), Max(v2), Max(v3), ... ) - Min( Min(v1), Min(v2), Min(v3), ... )

or the sum over each the dimension psan for each vehicle:
Sum( Max(v1) - Min(v1 ), Max(v2) - Min(v2 ), Max(v3) - Min(v3 ), ... )

Note: when Mins are typically 0 the formula becomes simpler
 ?

**Comment by Mizux** [comment]
first proposal, the second one is like setting a coef `1` to makeSpan for each vehicles

**Comment by GuyBenhaim** [comment]
... if GlobalSpan would compress the difference between the higher and lowest end values, like this:
     (Max( Max(v1), Max(v2), Max(v3), ... ) - Min( Max(v1), Max(v2), Max(v3), ... ) 
it might balance between vehicle them.

Also, could this do the trick, and penalize each vehicle with a short route:
void SetCumulVarSoftLowerBound(int64 index, int64 lower_bound, int64 coefficient);
  Does this apply per dimension?  Does "int64 index" point to a specific Node?

**Comment by d0nker420** [comment]
Hello,

I'm looking to solve an issue with the route distance not being evenly distributed among each vehicle. 
This is my current implementation from the [VRP tutorial](https://developers.google.com/optimization/routing/vrp):
```
dimension_name = "Distance"
routing.AddDimension(
    transit_callback_index,
    0, 
    6 * len(data_model['distance_matrix']), #Max distance for my task
    True,  # start cumul to zero
    dimension_name)
distance_dimension = routing.GetDimensionOrDie(dimension_name)
distance_dimension.SetGlobalSpanCostCoefficient(1000)
```
This could potentially have to do with the fact that as per line 175 on [cvrp_reload example](https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/samples/cvrp_reload.py) implementing this doesn't imply that the standard deviation will be minimized. Even with the globalspancost quite high I'm getting distances: 9, 41, 35 across all of the three vehicles the program manages. Increasing the coefficient doesn't affect the result. I know that 3 vehicles will be used and the exact number of tasks is also known, however there are two types:
1. Can be done by vehicles 0,1,2
2. Can be done by vehicles 1,2 

I'm not entirely sure what is meant by 
> GlobalSpan on dimension with unaryTransitCallback returning 1
@Mizux could you please provide a code snippet in python?
