### ISSUE TITLE
Maximum and minimum number of locations per route

### ISSUE THREAD

**Issue by TeodoraB21** [google/or-tools#1142]
I don't have the latest version of the code (I have the version 6), so I can't use `RegisterUnaryTransitCallback(lambda index : 1)`.
So I made a class:
```cpp
class VehicleStops
{
public:
int64 Run(operations_research::RoutingModel::NodeIndex FromNode, operations_research::RoutingModel::NodeIndex ToNode)
{
return 1;	//add 1 for each stop added
}
};
```
and I added a new dimension:
```cpp
VehicleStops vehStops;
routing.AddDimensionWithVehicleCapacity(
  NewPermanentCallback(&vehStops, &VehicleStops::Run),
  /*max_slack=*/0,
  m_vehicles->GetMaxNumberOfStopsForVehicles(),
  /*start_cumul_var_to_zero=*/true,
  "NrStops");

const operations_research::RoutingDimension& nrStopsDimension =
  routing.GetDimensionOrDie("NrStops");

std::vector<pair<int32, int32>> nrStopsRange = m_vehicles->GetNrStopsRange();

for (int32 i = 0; i < routing.vehicles(); i++) {
  nrStopsDimension.CumulVar(routing.End(i))->SetMin(nrStopsRange.at(i).first);
  nrStopsDimension.CumulVar(routing.End(i))->SetMax(nrStopsRange.at(i).second);
}
```
And in the input I specified that:
```
MinNumberOfStops: 2, 3, 1
MaxNumberOfStops: 3, 7, 3
```
But the solution is this:
```
Route nr:0
index 0 distance 0
index 1 distance 58
index 8 distance 1154
index 9 distance 1963
Route nr:1
index 6 distance 0
index 7 distance 351
index 5 distance 1009
index 2 distance 1327
Route nr:2
index 4 distance 0
index 3 distance 957
```
So why for the first vehicle it puts 4 stops, if I set the maximum to be 3?

**Comment by Mizux** [comment]
you add one during transit so 4 nodes three transit: 0->1, 1->8, 8->9

**Comment by TeodoraB21** [comment]
So I have to put whatever I want -1, Right?

**Comment by Mizux** [comment]
I would say yes

**Comment by TeodoraB21** [comment]
I doesn't work, when I put maximum 1 (2 stops), it doesn't find any solution :(

**Comment by Mizux** [comment]
Are you sure there is a solution ?

**Comment by TeodoraB21** [comment]
Yes

**Comment by TeodoraB21** [comment]
If I set another vehicle max number of stops to 1 it works...so it probably didn't found any solution earlier.
But I still don't understand why, I mean I set some big values for max distance of every vehicle, so they should pass through the left stop.

**Comment by lperron** [comment]
As good practice. You can set hard  upper limit on cumul vars, but you should always set soft lower limits.
