### ISSUE TITLE
Dropping Visits example contains error

### ISSUE THREAD

**Issue by Apo-** [google/or-tools#1143]
Not sure if this the correct place to report this, but I think the example for [dropping visits](https://developers.google.com/optimization/routing/penalties) for the routing library has an error.

Concretely, it seems to me that the line `routing.AddDisjunction([routing.NodeToIndex(i)], penalty)` should be `routing.AddDisjunction([i], penalty)`.

For one,
https://github.com/google/or-tools/blob/554cbccaa95b4c11eced13f145de1bf468e1f919/ortools/constraint_solver/routing.h#L516
 So `AddDisjunction()` accepts a `NodeIndex`, but
https://github.com/google/or-tools/blob/554cbccaa95b4c11eced13f145de1bf468e1f919/ortools/constraint_solver/routing.h#L951
`NodeToIndex()` accepts a `NodeIndex` and returns `int64`.

In the example on the website `i` and `routing.NodeToIndex(i)` will be equal, so the potential problem is not apparent there, but in this [example](https://gist.github.com/Apo-/86c6a7212e20b9127a2585b0d80583a3#file-drop_visits_example_issue-py-L36) that line would cause an issue.

**Comment by Mizux** [comment]
Yes you are right for v6.10.

But soon we will release v7.0 which behave differently.
https://github.com/google/or-tools/blob/72fccd63983b93c655558ca1bdc9ece1d055d7a1/ortools/constraint_solver/routing.h#L555-L557
and you'll need to use:
https://github.com/google/or-tools/blob/72fccd63983b93c655558ca1bdc9ece1d055d7a1/ortools/constraint_solver/routing_index_manager.h#L62

So I would say, documentation is a little bit ahead of the release.

I'm sorry for the inconvenience and confusion
