### ISSUE TITLE
Build is failing in ubuntu

### ISSUE THREAD

**Issue by tk120404** [google/or-tools#1144]
Unable build the master branch in ubuntu 16.04 

`make third_party stopped` at 

-- Installing: /home/ubuntu/or-tools-master/dependencies/install/lib/libabsl_optional.a
-- Installing: /home/ubuntu/or-tools-master/dependencies/install/lib/libabsl_bad_optional_access.a
-- Installing: /home/ubuntu/or-tools-master/dependencies/install/lib/libabsl_bad_variant_access.a
_

> make[1]: Leaving directory '/home/ubuntu/or-tools-master/dependencies/sources/abseil-cpp-bf29470/build_cmake'

_

` make python failed at
`
fails with  -c ortools/gen/ortools/algorithms/knapsack_solver_python_wrap.cc \
 -o objs/swig/knapsack_solver_python_wrap.o
g++: error: ortools/gen/ortools/algorithms/knapsack_solver_python_wrap.cc: No such file or directory
g++: fatal error: no input files
compilation terminated.

> makefiles/Makefile.python.mk:123: recipe for target 'objs/swig/knapsack_solver_python_wrap.o' failed
> make: *** [objs/swig/knapsack_solver_python_wrap.o] Error 1

**Comment by tk120404** [comment]
@Mizux With same master branch we are able to build without any issue in mac OS

**Comment by lperron** [comment]
Did you install swig ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 21 mars 2019 à 11:53, Arjunkumar <notifications@github.com> a
écrit :

**Comment by tk120404** [comment]
@lperron  No, I didnt. Should we do that in linux? it builds perfectly without it in mac

**Comment by lperron** [comment]
because xcode installs swig.

https://developers.google.com/optimization/install/python/source_linux
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 21 mars 2019 à 12:04, Arjunkumar <notifications@github.com> a
écrit :

**Comment by tk120404** [comment]
Got it Tx. Installed swig and building it now 🤞

**Comment by tk120404** [comment]
`make test_python` failed 
Traceback (most recent call last):
  File "ortools/constraint_solver/samples/cvrptw_break.py", line 329, in <module>
    main()
  File "ortools/constraint_solver/samples/cvrptw_break.py", line 325, in main
    print_solution(data, manager, routing, assignment)
  File "ortools/constraint_solver/samples/cvrptw_break.py", line 214, in print_solution
    for i in xrange(intervals.Size()):
  File "/home/ubuntu/or-tools-master/ortools/constraint_solver/../gen/ortools/constraint_solver/pywrapcp.py", line 2553, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, IntervalContainer, name)
  File "/home/ubuntu/or-tools-master/ortools/constraint_solver/../gen/ortools/constraint_solver/pywrapcp.py", line 74, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "/home/ubuntu/or-tools-

> master/ortools/constraint_solver/../gen/ortools/constraint_solver/pywrapcp.py", line 69, in _swig_getattr_nondynamic
>     return object.__getattr__(self, name)
> AttributeError: type object 'object' has no attribute '__getattr__'
> makefiles/Makefile.python.mk:484: recipe for target 'rpy_cvrptw_break' failed
> make: *** [rpy_cvrptw_break] Error 1

**Comment by Mizux** [comment]
found: code have bee nreverte during the last export form google3
https://github.com/google/or-tools/commit/814935dab7554273b3d6988c64b1d00f530414f1#diff-f745f826960b07eded785fe30b2d7ffd

**Comment by tk120404** [comment]
👍 It is fixed now
