### ISSUE TITLE
C# Android Xamarin version

### ISSUE THREAD

**Issue by tetri** [google/or-tools#1147]
Hello there,
Is it possible use OrTools on Android devices?
I'm trying solve Linear Programming problem on Android 4.4+.

My solution is composed by: 
- 3 _.NETStandar2.0_ projects, 
- 2 deprecated _Portable Profile111_ projects,
- and 1 main project targeted _Android 4.4_ project.

I've installed current version of OrTools nuget package on .NETStandard2.0 project **without errors**.
I've installed current version of OrTools nuget package on main project (due to its dependency) **without errors**, but when the solution is compiled, an error occurs.

**Comment by lperron** [comment]
Not with the distributed archives as they contain native C++ libraries.
We do not compile for arm.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 21 mars 2019 à 14:33, Tetri Mesquita <notifications@github.com> a
écrit :

**Comment by tetri** [comment]
Thank you Laurent,
Despite this, OrTools is really awesome!

**Comment by Senso4sLab** [comment]
Is any progress for using OrTools on Android phones?

**Comment by lperron** [comment]
using cmake, we have a working arm64 build (maybe without SCIP)

see
https://github.com/google/or-tools/runs/4048484413?check_suite_focus=true
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
Our CMake **should** support an Android NDK Toolchain (for C++) BUT it is still not tested on our side.
Our Java/.Net wrapper still not support arm64/aarch64 platform

Any feedback/PR will be welcome, this is on our todo list to have CI workflow to test and support this but is not ready yet and I don't have any ETA to provide...
