### ISSUE TITLE
Is it not adapter for python2.7 ? I just can not import model "pywraprcpsp" and "cp_model".

### ISSUE THREAD

**Issue by qiqishuang** [google/or-tools#1149]
```python
from ortools.data import pywraprcpsp
from ortools.sat.python import cp_model
```

**I import those two model in my rcpsp_ortool.py by python2.7, but it is not ok, errors shows as below. Not only for model "pywraprcpsp", but also for model "cp_model". However,  it is ok when I use python3.6.** 

**Could any one solve this question? Thanks, good luck.**

---------------------------------------------------------------------------
```
D:\ProjectX\rcpsp_code\rcpsp_ortools1.0>python rcpsp_ortool.py
Traceback (most recent call last):
  File "rcpsp_ortool.py", line 24, in <module>
    from ortools.data import pywraprcpsp
  File "C:\Python27\lib\site-packages\ortools\data\pywraprcpsp.py", line 17, in <module>
    _pywraprcpsp = swig_import_helper()
  File "C:\Python27\lib\site-packages\ortools\data\pywraprcpsp.py", line 16, in swig_import_helper
    return importlib.import_module('_pywraprcpsp')
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _pywraprcpsp
```

**Comment by Mizux** [comment]
Which OS ?
Which version of ortools did you use ?

**Comment by qiqishuang** [comment]
> Which OS (64bits ?) ?
> Which version of ortools did you use ?

OS: win10 64bit
Version:  "ortools-6.10.6025-cp27-cp27m-win_amd64.whl" from website: https://pypi.org/project/ortools/#files

And I have also try ortools 7.0.  The question shows again.

**Comment by Mizux** [comment]
Both wheel package cp27 and cp37 for windows contains the file `ortools\data\_pywraprcpsp.pyd` (1.8MB)

need to figure out why it is not working...

Can you give me your exact python version ?

**Comment by qiqishuang** [comment]
```
D:\ProjectX\or-tools-master>python
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ortools
>>> from ortools.data import pywraprcpsp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name pywraprcpsp
>>> from ortools.sat.python import cp_model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ortools\sat\python\cp_model.py", line 28, in <module>
    from ortools.sat import cp_model_pb2
ImportError: cannot import name cp_model_pb2
>>>
```

**Comment by qiqishuang** [comment]
> Both wheel package cp27 and cp37 for windows contains the file `ortools\data\_pywraprcpsp.pyd` (1.8MB)
> 
> need to figure out why it is not working...
> 
> Can you give me your exact python version ?

Could you get some solutions?
Look forward to your favourable reply.  ^o^

**Comment by qiqishuang** [comment]
### **I got the solution! No matter python2.7 or python3.0+.**

My windows10 is still the old version DLL file "vcredist_x64.exe" of 2010.
It would be OK when I change the version from 2010 to 2017 [vc_redist.x64 2017.zip](https://github.com/google/or-tools/files/3079869/vc_redist.x64.2017.zip).
