### ISSUE TITLE
Vehicle Routing Node Windows based on other Node Windows

### ISSUE THREAD

**Issue by Inevitable-Marzipan** [google/or-tools#1150]
Hi all, I need some help modelling a particular constraint within the vehicle routing library within python. The problem is as follows:

- There is a location that must be visited twice so I have made them seperate nodes in the model

-   The location has a time window (say 10am to 5pm), and the first location can be visited Monday or Tuesday and the second location can be visited Thursday or Friday

- If the first location is visited on a Monday, then I want the second location to be visited on the Thursday. Similarly if the first location is visited on the Tuesday then the second location should be visited on the Friday

I have already read about using NotMemberCt to allow a single node to have multiple time windows and can get that to work. I have seen within the cpp example of incorportating vehicle breaks the use of creating IntervalVars and then using the PerformedExpr along with MakeEquality to link two intervals together, but I am not sure how to then link these IntervalVars to the location windows.
Any thoughts on whether this is possible?

**Comment by Inevitable-Marzipan** [comment]
This might be a possible solution:

- Make seperate nodes for all 4 days (Mon, Tues, Thurs, Fri)

- Add hard disjunctions between the pairs (Mon, Tues), (Thurs, Fri), (Mon, Fri) and (Tues, Thurs)

**Comment by lperron** [comment]
Yes it should.
