### ISSUE TITLE
VRP FirstSolutionStrategy.Types.Value.Savings works well until 4 vehicles are use

### ISSUE THREAD

**Issue by educunarro** [google/or-tools#1151]
Hi,

When using the following code (see the image). It works just fine, until it start searching for a solution with 4 or more vehicles. An exception with the following error mesage: "Attempted to read or write protected memory. This is often an indication that other memory is corrupt." is thrown in "routing.SolveWithParameters(searchParameters)". Any idea what could it be?

Thanks!

![image](https://user-images.githubusercontent.com/2915277/54850943-3f8e3d00-4cc7-11e9-9f47-cfdaa1a6529f.png)

![image](https://user-images.githubusercontent.com/2915277/54851218-f985a900-4cc7-11e9-9358-2ed7a49ad676.png)

**Comment by lperron** [comment]
GC.KeepAlive() keeps the object alive until this call. Therefore, it can be deleted the line after.

You need to have KeepAlive() after the Solve().

**Comment by educunarro** [comment]
Laurent,

Thanks for your response. I made the change, however, it still fails.

![image](https://user-images.githubusercontent.com/2915277/54935554-4c957100-4eff-11e9-8bc2-a01b9fb523f2.png)

Any other idea?

Regards

**Comment by lperron** [comment]
Can you try using java lambdas instead of NodeEvaluator2.

See https://github.com/google/or-tools/blob/4a0e9b1860276a021335aacb8b69e10a0d08942c/ortools/constraint_solver/samples/Vrp.java#L107
