### ISSUE TITLE
VRP Is there any function in python which return total number of assigned node for each vehicle

### ISSUE THREAD

**Issue by NinjaKing** [google/or-tools#1153]
Hello, I am trying to get a var (for each vehicle) that describes total number of nodes visited by this vehicle. Is there any function in the package return that var? Or do you know how to create a var like that?
Thanks so much.

**Comment by Mizux** [comment]
no vars AFAIK, but you can add a dimension which add one at each node visited then simply look at the value of the CumulVar at the end node...

**Comment by Mizux** [comment]
related to https://github.com/google/or-tools/issues/958#issuecomment-470010900
