### ISSUE TITLE
Best way to represent varying constraints over intervals

### ISSUE THREAD

**Issue by DHerls** [google/or-tools#1157]
Hello, I am modeling a problem where the total scheduled jobs at a given time must be under some value X, but X varies with the time i.e. from time 0-5 10 jobs can be running, but from 5-8 only 6 jobs can be running.

I'm having trouble finding examples of this kind of cumulative constraint and I was hoping someone could point me in the direction of an example or relevant documentation.

Thank you!

**Comment by lperron** [comment]
Just add fixed rectangles (interval * demand) to your cumulative.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by DHerls** [comment]
Thank you for your help!  This really helped to visualize my problem better.
