### ISSUE TITLE
Building or-tools 7.0 from Cmake error

### ISSUE THREAD

**Issue by AxelDelsol** [google/or-tools#1159]
When building or-tools v7.0 using CMake, an error occured saying cbc-src does not have a CMakeLists.txt.

I checked https://github.com/Mizux/Cbc (the git repo where Cbc is downloaded) and indeed, there is no CMakeLists.txt.

I didn't have this issue when building or-tools v.610 using CMake 2 months ago so I assume it is a recent issue.

**Comment by Mizux** [comment]
sorry you need to use https://github.com/Mizux/coinor-cbc instead
