### ISSUE TITLE
OnlyEnsureIf seems to be ignored in AddNoOverlap in C#

### ISSUE THREAD

**Issue by crypto-rsa** [google/or-tools#1165]
Consider the following example:
```cs
var cpModel = new CpModel();
var a = cpModel.NewIntVar(0, 3, "a");
var b = cpModel.NewIntVar(2, 5, "b");
var same = cpModel.NewBoolVar("a==b");
cpModel.Add(a == b).OnlyEnforceIf(same);
cpModel.Add(a != b).OnlyEnforceIf(same.Not());

var s1 = cpModel.NewIntVar(0, 5, "s1");
var e1 = cpModel.NewIntVar(0, 5, "e1");
var s2 = cpModel.NewIntVar(0, 5, "s2");
var e2 = cpModel.NewIntVar(0, 5, "e2");
var i1 = cpModel.NewIntervalVar(s1, 2, e1, "i1");
var i2 = cpModel.NewIntervalVar(s2, 2, e2, "i2");

cpModel.AddNoOverlap(new IntervalVar[] { i1, i2 }).OnlyEnforceIf(same);
```

Two intervals, `i1` and `i2` are not supposed to overlap but only if `a == b`. However, when I search for all solutions, I don't get _any_ where `i1` and `i2` do overlap, even when `a != b`. I only get the 96 solutions where the intervals do not overlap. It seems the `same` condition gets ignored.

**Comment by lperron** [comment]
OnlyEnforeIf is only supported on bool_or, bool_and, linear and intervals.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 29 mars 2019 à 15:42, Pavel Kotrč <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
For no overlap, add it on the intervals.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by crypto-rsa** [comment]
What exactly do you mean by _For no overlap, add it on the intervals_? How should the example above be solved?

**Comment by lperron** [comment]
make sure that for all intervals, one boolean forces them to be inactive

The setting this boolean deactive the no overlap.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 29 mars 2019 à 22:45, Pavel Kotrč <notifications@github.com> a
écrit :

**Comment by crypto-rsa** [comment]
Hmm, I am still not sure how do you mean it. But I found an (example)[https://github.com/google/or-tools/blob/master/examples/dotnet/GateSchedulingSat.cs] where the condition for no overlap is "simulated" using copies of optional intervals. Is that what you suggest? But I wonder whether it wouldn't be better simply to manually add a condition for each pair of intervals that one ends before the other starts.

**Comment by lperron** [comment]
You will lose a lot of propagation doing that.

Anyway, you need to experiment.

I will close the issue now as the answer of the original question is that it is not supported.

**Comment by crypto-rsa** [comment]
Yeah, from the examples I've seen it seems the convention is to use optional intervals and only enforce rules on their governing bool variables.

**Comment by asett0** [comment]
I'm also having this same problem. The `OnlyEnforceIf` method doesn't seem to be working with `AddNoOverlap` yet. But it does work for `Add`. If the implementation doesn't work what is an alternative? To get it to work I used the big M method to replace the time intervals but this is considerably slower.

**Comment by asett0** [comment]
I also had this same issue. For anyone that is also stuck on this consider looking at `NewOptionalIntervalVar` (assuming you are using the python bindings). The method allows you to define an interval only if some literal is true. You can then use these optional intervals within `AddNoOverlap` to achieve the same effect as `OnlyEnforceIf`

**Comment by lperron** [comment]
As documented, onlyenforceif is only supported on bool_or, bool_and and
linear constraints.

For scheduling problems, optionality has to be defined at the interval
level.

Next version will actively check that only supported constraints use
OnlyEnforceIf.

Le mer. 18 sept. 2019 à 05:41, Amit Sett <notifications@github.com> a
écrit :
