### ISSUE TITLE
Minimize number of vehicles while maximizing each vehicle route

### ISSUE THREAD

**Issue by educunarro** [google/or-tools#1166]
Hi,

I'm having problem to enforce the route of the vehicles to be as "big" as possible.

The following constrain is use:

![image](https://user-images.githubusercontent.com/2915277/55242146-65fa2e00-521b-11e9-93b6-dff548659c17.png)

However, this works fine as a maximum, but not as a maximizer. For example: if the solution found consist on two routes, 1 should be as "big" as possible, and the other one the remaing points.

Thanks for you time,

Regards

**Comment by lperron** [comment]
Minimize the number of vehicles ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 29 mars 2019 à 16:10, educunarro <notifications@github.com> a
écrit :

**Comment by educunarro** [comment]
Hi Laurent,

Thanks for your response. Basically, to solve the problem, I'm start trying to solve with 1 vehicle with the constrain define above (the image) and If I do not find a solution with that amount of vehicles, I increase the number of vehicles (+1) and try again. From 1 to n, until I find a solution using that constrain. 

However, when a solution is found, the problem is that the constrain (the image) works fine as a limit for the route maximum time, but do not works for "the minimum" or maximizer of a route.

For example, imagine I solve the problem with 2 vehicles/routes and the constrain is 8 hours maximum. Sometimes the algorithm find solutions like: 1 route 5 hours and 1 route 5 hours. What I will prefer is to have one of this routes to be closer to 8 hours (the constrain). I just want to optimize the usage of the vehicle. 

Thanks for your time,

**Comment by Mizux** [comment]
My 2 cents,
Did you try to give a different cost matrix for each vehicle basically the same distance matrix but with an increased scaling factor, so solver should first try to add the node to the first vehicle if possible otherwise try with the second one and so on...

**Comment by educunarro** [comment]
Hi Mizux

Thanks for you response. I will give it a try.

Thanks

**Comment by TrungTDD** [comment]
Hello @educunarro, Have you found any solution ? I am solving the problem as your problem description.
