### ISSUE TITLE
Add customized constraints for VRP

### ISSUE THREAD

**Issue by FrancescoAntonini** [google/or-tools#1168]
I'm using google OR tools (python) to solve a vehicle routing problem in which the delivery points belong to a zone. What is the most effective way to consider into routing model the constraint that each vehicle can cross at most N zones?

Thank you very much!

**Comment by lperron** [comment]
Maybe one dimension per zone, +1 on each visit on its given dimension.
Count the number of dimensions > 0.

Something like that.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by danpat** [comment]
If your zoning needs aren't strict, then one thing that's worked for me is to use `AddSoftSameVehicleConstraint` - this lets you group your locations, then penalize crossing into another zone.  You can tune the penalty as low or as high as you like.

The effect here is to allow "stealing" of deliveries across zones - sometimes, it's a better plan overall if some delivery points are served by different drivers.

If your zoning requirements are strict, you could still use this feature, just set the coefficient value very high.

**Comment by lperron** [comment]
I have no good solutions.

You can always have 1 dimension per zone, and then add a constraint

MakeIsGreaterThanCstCt(cumul_at_end, 0) for each dimension, and restrict the sum of these to be less than your constant.

Performance of the local search will be degraded though.
