### ISSUE TITLE
AWS Lambda or Firebase Cloud Functions for mobile back-end with Google OR-tools

### ISSUE THREAD

**Issue by samalpys** [google/or-tools#1171]
After figuring out it's impossible to embed my scheduling algorithm (used Google OR-tools) into my Android application, I decided to put it on a server.

I am looking for a quick solution to build a server.
Available options are AWS Lambda (Amazon) and Firebase Cloud Functions (Google).My server should receive some info about today's date, task id and task's due date, then do calculations and send the result back.

I wonder what is the best choice for using with Google OR-tools? 

P.S. I understand this might be a bit irrelevant, but I'm sure it will help some other developers too!

**Comment by lperron** [comment]
I will only comment that I have multiple reports of crashes using python or java on Azure.
I have not investigated them. I just know the programs worked well on workstations, and crashed on the cloud. 

AWS, and Google, AFAIK are good options. 

I will be a bit more motivated to fix issues if they happen on Google cloud :-)
