### ISSUE TITLE
[CP-SAT] Search strategy to find all solutions, but fixing only some variables

### ISSUE THREAD

**Issue by lnikkila** [google/or-tools#1174]
Hello! I really like CP-SAT, however there’s one scenario I haven’t been able to crack yet. I have a problem where I’d like to get all solutions, but only in terms of some of the variables. In other words: once a solution is found, the solver shouldn’t consider any other solutions having the same values for certain variables.

I’m currently using the protobuf interface directly so I’ve been going through the model and parameter definitions. Based on the comments there I’ve been thinking I might be able to use a combination of `search_strategy` and `instantiate_all_variables` set to false, so that the solver fixes the variables I’m interested in and solves only the lower/upper bounds of others.

However, despite trying a number of different combinations of model and search parameters, I haven’t been able to get the solver to return anything else than precise solutions, i.e. `solution` is always set and the `solution_{lower,upper}_bounds` are always empty.

I don’t think there’s a sample that uses `instantiate_all_variables`, so I’d like to know what the requirements for using that parameter are. If it’s any help, here are the parameters I’ve tried so far:

```cpp
// in the protobuf model
// domain_reduction_strategy: SELECT_MIN_VALUE
// variable_selection_strategy: CHOOSE_FIRST
// variables: [small subset of defined variables]

parameters.set_search_branching(SatParameters::FIXED_SEARCH);
parameters.set_instantiate_all_variables(false);
parameters.set_enumerate_all_solutions(true);
```

An obvious workaround would be to run the solver individually for all combinations of the variables I’m interested in as constants and find any feasible solution, but this seems a little wasteful as the number of fixed variables is relatively small and I’m guessing the solver is able to utilise previous knowledge when finding all solutions.

I’m using OR-Tools 6.9.

Any tips would be greatly appreciated!

**Comment by lperron** [comment]
I would say enumerate_all_variables = true.
+ callback that stops the search when some values should not be explored
anymore.

modify the model to forbid certain values,

and loop.

Still, if your number of fixed variables is small, generate all
combinations and explore them in parallel.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 5 avr. 2019 à 14:50, Leo Nikkilä <notifications@github.com> a
écrit :

**Comment by lnikkila** [comment]
Thank you, that’s a possibility I haven’t considered yet.

> Still, if your number of fixed variables is small, generate all combinations and explore them in parallel.

The number of variables is small, but unfortunately their domains may be large. In the event a callback-and-restart approach is too heavy, would `instantiate_all_variables` be a realistic alternative at all?

Unfortunately I haven’t been able to figure out when it affects the results yet.

**Comment by lperron** [comment]
don't use instantiate all variables.  It just adds a search strategy that
will scan all variables and fix them.
I do not believe it will help you.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 5 avr. 2019 à 15:03, Leo Nikkilä <notifications@github.com> a
écrit :
