### ISSUE TITLE
Multiple trips

### ISSUE THREAD

**Issue by yuranov** [google/or-tools#1176]
Is there a working solution to solve problem with multiple trips?
Trip can contains pickups and deliveries.
I found examples with reload and refueling, but seems it's not working properly for this case.

**Comment by Mizux** [comment]
What do you mean by not working properly, do you have simple sample not working so we can reproduce it ?

**Comment by Skyien** [comment]
@Mizux  I already deleted, but tried to do it again. 
I understand correctly that or-tools can that solve this problem?

**Comment by lperron** [comment]
Duplicate of #976
