### ISSUE TITLE
CP-Original to CP-Sat conversion

### ISSUE THREAD

**Issue by sprytnylisek** [google/or-tools#1178]
Hi,

I've just started with CP and CP SAT development. I am trying to convert crew.cs example from CP to CP-SAT. I understand CP model, but have problems with CP-SAT:

// this is classic CP
// number of working persons
    IntVar[] nw = new IntVar[num_persons];
    for(int p = 0; p < num_persons; p++) {
      IntVar[] tmp = new IntVar[num_flights];
      for(int f = 0; f < num_flights; f++) {
        tmp[f] = crew[f,p];
      }
      nw[p] = tmp.Sum() > 0;
    }
    solver.Add(nw.Sum() == num_working);

In CP CP.IntVar is easily assignable from expression: nw[p] = tmp.Sum() > 0;
In CP-SAT I can't do that since can't convert BoundIntegerExpression to Sat.IntVar.
How should I approach this?

**Comment by lperron** [comment]
https://github.com/google/or-tools/blob/stable/ortools/sat/doc/channeling.md
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 8 avr. 2019 à 20:36, sprytnylisek <notifications@github.com> a
écrit :

**Comment by sprytnylisek** [comment]
Thank you
