### ISSUE TITLE
Multiple constraints in VRP

### ISSUE THREAD

**Issue by daoducminh** [google/or-tools#1180]
Hi everyone,
I have been reading the ORTools' documentation about Routing Problem, which has been updated recently. And there are 2 articles I'm focusing on: [Capacity Constraints](https://developers.google.com/optimization/routing/cvrp) and [Vehicle Routing with Pickups and Deliveries](https://developers.google.com/optimization/routing/pickup_delivery).

I was trying to combine these 2 constraints to solve the problem, using Python 3.7. And this is the code which I have combined: [pdp.py](https://gist.github.com/daoducminh/1dfa78d2885cadefa267c63c1de8c8a3)
Here is the main part of the code:
```python
# Create and register a transit callback.
def distance_callback(from_index, to_index):
    """Returns the distance between the two nodes."""
    # Convert from routing variable Index to distance matrix NodeIndex.
    from_node = manager.IndexToNode(from_index)
    to_node = manager.IndexToNode(to_index)
    return data['distance_matrix'][from_node][to_node]

transit_callback_index = routing.RegisterTransitCallback(distance_callback)
routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

# Add Distance constraint.
dimension_name = 'Distance'
routing.AddDimension(
    transit_callback_index,
    0,  # no slack
    3000,  # vehicle maximum travel distance
    True,  # start cumul to zero
    dimension_name)
distance_dimension = routing.GetDimensionOrDie(dimension_name)
distance_dimension.SetGlobalSpanCostCoefficient(100)

# Add Capacity constraint.
def demand_callback(from_index):
    """Returns the demand of the node."""
    # Convert from routing variable Index to demands NodeIndex.
    from_node = manager.IndexToNode(from_index)
    return data['demands'][from_node]

demand_callback_index = routing.RegisterUnaryTransitCallback(demand_callback)
routing.AddDimensionWithVehicleCapacity(
    demand_callback_index,
    0,  # null capacity slack
    data['vehicle_capacities'],  # vehicle maximum capacities
    True,  # start cumul to zero
    'Capacity')

# Define Transportation Requests.
for request in data['pickups_deliveries']:
    pickup_index = manager.NodeToIndex(request[0])
    delivery_index = manager.NodeToIndex(request[1])
    routing.AddPickupAndDelivery(pickup_index, delivery_index)
    routing.solver().Add(
        routing.VehicleVar(pickup_index) == routing.VehicleVar(delivery_index))
    routing.solver().Add(distance_dimension.CumulVar(pickup_index) <=
        distance_dimension.CumulVar(delivery_index))
```
So, my problem is: This code had been executed for 10 minutes, and returned nothing except `Process finished with exit code -1`.
Can I have some advises?

**Comment by Mizux** [comment]
Are you sure  solution exist ?
You can also,  first you try to increase the max distance from `3000` to `100000` to "disable" the distance 
 constraint and see if the solver can find a solution and how long each routes are.
(ed since you have the GlobalSpanCost on distance solver still have incentive to avoid one long route...)

**Comment by daoducminh** [comment]
Thanks for your help, @Mizux. After increasing the max distance from `3000` to `100000`, I got a result very easily. But when adding time constraint to this code, I got a solution after 30 minutes. It's pretty slowly, but the tool has done perfectly. I very appreciate your works and your helps.
Thank you, again.

**Comment by Khev** [comment]
Hi there,

@daoducminh  could you post your full solution? I am trying the same things, but keep getting a SystemError. My full code is:

```

from __future__ import print_function
from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp


def create_data_model():
    """Stores the data for the problem."""
    data = {}
    data['distance_matrix'] = [
        [
            0, 548, 776, 696, 582, 274, 502, 194, 308, 194, 536, 502, 388, 354,
            468, 776, 662
        ],
        [
            548, 0, 684, 308, 194, 502, 730, 354, 696, 742, 1084, 594, 480, 674,
            1016, 868, 1210
        ],
        [
            776, 684, 0, 992, 878, 502, 274, 810, 468, 742, 400, 1278, 1164,
            1130, 788, 1552, 754
        ],
        [
            696, 308, 992, 0, 114, 650, 878, 502, 844, 890, 1232, 514, 628, 822,
            1164, 560, 1358
        ],
        [
            582, 194, 878, 114, 0, 536, 764, 388, 730, 776, 1118, 400, 514, 708,
            1050, 674, 1244
        ],
        [
            274, 502, 502, 650, 536, 0, 228, 308, 194, 240, 582, 776, 662, 628,
            514, 1050, 708
        ],
        [
            502, 730, 274, 878, 764, 228, 0, 536, 194, 468, 354, 1004, 890, 856,
            514, 1278, 480
        ],
        [
            194, 354, 810, 502, 388, 308, 536, 0, 342, 388, 730, 468, 354, 320,
            662, 742, 856
        ],
        [
            308, 696, 468, 844, 730, 194, 194, 342, 0, 274, 388, 810, 696, 662,
            320, 1084, 514
        ],
        [
            194, 742, 742, 890, 776, 240, 468, 388, 274, 0, 342, 536, 422, 388,
            274, 810, 468
        ],
        [
            536, 1084, 400, 1232, 1118, 582, 354, 730, 388, 342, 0, 878, 764,
            730, 388, 1152, 354
        ],
        [
            502, 594, 1278, 514, 400, 776, 1004, 468, 810, 536, 878, 0, 114,
            308, 650, 274, 844
        ],
        [
            388, 480, 1164, 628, 514, 662, 890, 354, 696, 422, 764, 114, 0, 194,
            536, 388, 730
        ],
        [
            354, 674, 1130, 822, 708, 628, 856, 320, 662, 388, 730, 308, 194, 0,
            342, 422, 536
        ],
        [
            468, 1016, 788, 1164, 1050, 514, 514, 662, 320, 274, 388, 650, 536,
            342, 0, 764, 194
        ],
        [
            776, 868, 1552, 560, 674, 1050, 1278, 742, 1084, 810, 1152, 274,
            388, 422, 764, 0, 798
        ],
        [
            662, 1210, 754, 1358, 1244, 708, 480, 856, 514, 468, 354, 844, 730,
            536, 194, 798, 0
        ],
    ]
    data['pickups_deliveries'] = [
        [1, 6],
        [2, 10],
        [4, 3],
        [5, 9],
        [7, 8],
        [15, 11],
        [13, 12],
        [16, 14],
    ]
    data['num_vehicles'] = 4
    data['depot'] = 0
    data['vehicle_capacities'] = [15, 15, 15, 15]
    return data



# Instantiate the data problem.
data = create_data_model()

# Create the routing index manager.
manager = pywrapcp.RoutingIndexManager(len(data['distance_matrix']),
                                       data['num_vehicles'], data['depot'])

# Create Routing Model.
routing = pywrapcp.RoutingModel(manager)


# Create and register a transit callback.
def distance_callback(from_index, to_index):
    """Returns the distance between the two nodes."""
    # Convert from routing variable Index to distance matrix NodeIndex.
    from_node = manager.IndexToNode(from_index)
    to_node = manager.IndexToNode(to_index)
    return data['distance_matrix'][from_node][to_node]

transit_callback_index = routing.RegisterTransitCallback(distance_callback)
routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

# Add Distance constraint.
dimension_name = 'Distance'
routing.AddDimension(
    transit_callback_index,
    0,  # no slack
    10**7,  # vehicle maximum travel distance
    True,  # start cumul to zero
    dimension_name)
distance_dimension = routing.GetDimensionOrDie(dimension_name)
distance_dimension.SetGlobalSpanCostCoefficient(100)

# Add Capacity constraint.
def demand_callback(from_index):
    """Returns the demand of the node."""
    # Convert from routing variable Index to demands NodeIndex.
    from_node = manager.IndexToNode(from_index)
    return data['demands'][from_node]

demand_callback_index = routing.RegisterUnaryTransitCallback(demand_callback)
routing.AddDimensionWithVehicleCapacity(
    demand_callback_index,
    0,  # null capacity slack
    data['vehicle_capacities'],  # vehicle maximum capacities
    True,  # start cumul to zero
    'Capacity')

# Define Transportation Requests.
for request in data['pickups_deliveries']:
    pickup_index = manager.NodeToIndex(request[0])
    delivery_index = manager.NodeToIndex(request[1])
    routing.AddPickupAndDelivery(pickup_index, delivery_index)
    routing.solver().Add(
        routing.VehicleVar(pickup_index) == routing.VehicleVar(delivery_index))
    routing.solver().Add(distance_dimension.CumulVar(pickup_index) <=
        distance_dimension.CumulVar(delivery_index))

# Setting first solution heuristic.
search_parameters = pywrapcp.DefaultRoutingSearchParameters()
search_parameters.first_solution_strategy = (
    routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)

# Solve the problem.
assignment = routing.SolveWithParameters(search_parameters)

# Print solution on console.
if assignment:
    print_solution(data, manager, routing, assignment)

```
And the error is:

```

---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-8-0e92227487b5> in distance_callback(from_index, to_index)
     15     # Convert from routing variable Index to distance matrix NodeIndex.
---> 16     from_node = manager.IndexToNode(from_index)
     17     to_node = manager.IndexToNode(to_index)

~/anaconda3/lib/python3.7/site-packages/ortools/constraint_solver/pywrapcp.py in IndexToNode(self, index)
   3170     def IndexToNode(self, index: 'int64') -> "operations_research::RoutingIndexManager::NodeIndex":
-> 3171         return _pywrapcp.RoutingIndexManager_IndexToNode(self, index)
   3172 RoutingIndexManager_swigregister = _pywrapcp.RoutingIndexManager_swigregister

OverflowError: in method 'RoutingIndexManager_IndexToNode', argument 2 of type 'int64'

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/ortools/constraint_solver/pywrapcp.py in <lambda>(self, name, value)
   2135         __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
-> 2136     __setattr__ = lambda self, name, value: _swig_setattr(self, Assignment, name, value)
   2137     __swig_getmethods__ = {}

~/anaconda3/lib/python3.7/site-packages/ortools/constraint_solver/pywrapcp.py in _swig_setattr(self, class_type, name, value)
     70 def _swig_setattr(self, class_type, name, value):
---> 71     return _swig_setattr_nondynamic(self, class_type, name, value, 0)
     72 

~/anaconda3/lib/python3.7/site-packages/ortools/constraint_solver/pywrapcp.py in _swig_setattr_nondynamic(self, class_type, name, value, static)
     54     if (name == "this"):
---> 55         if type(value).__name__ == 'SwigPyObject':
     56             self.__dict__[name] = value

SystemError: <class 'type'> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-8-0e92227487b5> in <module>
     63 
     64 # Solve the problem.
---> 65 assignment = routing.SolveWithParameters(search_parameters)
     66 
     67 # Print solution on console.

~/anaconda3/lib/python3.7/site-packages/ortools/constraint_solver/pywrapcp.py in SolveWithParameters(self, search_parameters, solutions)
   3471 
   3472     def SolveWithParameters(self, search_parameters: 'operations_research::RoutingSearchParameters const &', solutions: 'std::vector< operations_research::Assignment const * > *'=None) -> "operations_research::Assignment const *":
-> 3473         return _pywrapcp.RoutingModel_SolveWithParameters(self, search_parameters, solutions)
   3474 
   3475     def SolveFromAssignmentWithParameters(self, assignment: 'Assignment', search_parameters: 'operations_research::RoutingSearchParameters const &', solutions: 'std::vector< operations_research::Assignment const * > *'=None) -> "operations_research::Assignment const *":

SystemError: <built-in function RoutingModel_SolveWithParameters> returned a result with an error set

```

**Comment by daoducminh** [comment]
> Hi there,
> 
> @daoducminh could you post your full solution? I am trying the same things, but keep getting a SystemError. My full code is:
> 
> ```
> 
> from __future__ import print_function
> from ortools.constraint_solver import routing_enums_pb2
> from ortools.constraint_solver import pywrapcp
> 
> 
> def create_data_model():
>     """Stores the data for the problem."""
>     data = {}
>     data['distance_matrix'] = [
>         [
>             0, 548, 776, 696, 582, 274, 502, 194, 308, 194, 536, 502, 388, 354,
>             468, 776, 662
>         ],
>         [
>             548, 0, 684, 308, 194, 502, 730, 354, 696, 742, 1084, 594, 480, 674,
>             1016, 868, 1210
>         ],
>         [
>             776, 684, 0, 992, 878, 502, 274, 810, 468, 742, 400, 1278, 1164,
>             1130, 788, 1552, 754
>         ],
>         [
>             696, 308, 992, 0, 114, 650, 878, 502, 844, 890, 1232, 514, 628, 822,
>             1164, 560, 1358
>         ],
>         [
>             582, 194, 878, 114, 0, 536, 764, 388, 730, 776, 1118, 400, 514, 708,
>             1050, 674, 1244
>         ],
>         [
>             274, 502, 502, 650, 536, 0, 228, 308, 194, 240, 582, 776, 662, 628,
>             514, 1050, 708
>         ],
>         [
>             502, 730, 274, 878, 764, 228, 0, 536, 194, 468, 354, 1004, 890, 856,
>             514, 1278, 480
>         ],
>         [
>             194, 354, 810, 502, 388, 308, 536, 0, 342, 388, 730, 468, 354, 320,
>             662, 742, 856
>         ],
>         [
>             308, 696, 468, 844, 730, 194, 194, 342, 0, 274, 388, 810, 696, 662,
>             320, 1084, 514
>         ],
>         [
>             194, 742, 742, 890, 776, 240, 468, 388, 274, 0, 342, 536, 422, 388,
>             274, 810, 468
>         ],
>         [
>             536, 1084, 400, 1232, 1118, 582, 354, 730, 388, 342, 0, 878, 764,
>             730, 388, 1152, 354
>         ],
>         [
>             502, 594, 1278, 514, 400, 776, 1004, 468, 810, 536, 878, 0, 114,
>             308, 650, 274, 844
>         ],
>         [
>             388, 480, 1164, 628, 514, 662, 890, 354, 696, 422, 764, 114, 0, 194,
>             536, 388, 730
>         ],
>         [
>             354, 674, 1130, 822, 708, 628, 856, 320, 662, 388, 730, 308, 194, 0,
>             342, 422, 536
>         ],
>         [
>             468, 1016, 788, 1164, 1050, 514, 514, 662, 320, 274, 388, 650, 536,
>             342, 0, 764, 194
>         ],
>         [
>             776, 868, 1552, 560, 674, 1050, 1278, 742, 1084, 810, 1152, 274,
>             388, 422, 764, 0, 798
>         ],
>         [
>             662, 1210, 754, 1358, 1244, 708, 480, 856, 514, 468, 354, 844, 730,
>             536, 194, 798, 0
>         ],
>     ]
>     data['pickups_deliveries'] = [
>         [1, 6],
>         [2, 10],
>         [4, 3],
>         [5, 9],
>         [7, 8],
>         [15, 11],
>         [13, 12],
>         [16, 14],
>     ]
>     data['num_vehicles'] = 4
>     data['depot'] = 0
>     data['vehicle_capacities'] = [15, 15, 15, 15]
>     return data
> 
> 
> 
> # Instantiate the data problem.
> data = create_data_model()
> 
> # Create the routing index manager.
> manager = pywrapcp.RoutingIndexManager(len(data['distance_matrix']),
>                                        data['num_vehicles'], data['depot'])
> 
> # Create Routing Model.
> routing = pywrapcp.RoutingModel(manager)
> 
> 
> # Create and register a transit callback.
> def distance_callback(from_index, to_index):
>     """Returns the distance between the two nodes."""
>     # Convert from routing variable Index to distance matrix NodeIndex.
>     from_node = manager.IndexToNode(from_index)
>     to_node = manager.IndexToNode(to_index)
>     return data['distance_matrix'][from_node][to_node]
> 
> transit_callback_index = routing.RegisterTransitCallback(distance_callback)
> routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)
> 
> # Add Distance constraint.
> dimension_name = 'Distance'
> routing.AddDimension(
>     transit_callback_index,
>     0,  # no slack
>     10**7,  # vehicle maximum travel distance
>     True,  # start cumul to zero
>     dimension_name)
> distance_dimension = routing.GetDimensionOrDie(dimension_name)
> distance_dimension.SetGlobalSpanCostCoefficient(100)
> 
> # Add Capacity constraint.
> def demand_callback(from_index):
>     """Returns the demand of the node."""
>     # Convert from routing variable Index to demands NodeIndex.
>     from_node = manager.IndexToNode(from_index)
>     return data['demands'][from_node]
> 
> demand_callback_index = routing.RegisterUnaryTransitCallback(demand_callback)
> routing.AddDimensionWithVehicleCapacity(
>     demand_callback_index,
>     0,  # null capacity slack
>     data['vehicle_capacities'],  # vehicle maximum capacities
>     True,  # start cumul to zero
>     'Capacity')
> 
> # Define Transportation Requests.
> for request in data['pickups_deliveries']:
>     pickup_index = manager.NodeToIndex(request[0])
>     delivery_index = manager.NodeToIndex(request[1])
>     routing.AddPickupAndDelivery(pickup_index, delivery_index)
>     routing.solver().Add(
>         routing.VehicleVar(pickup_index) == routing.VehicleVar(delivery_index))
>     routing.solver().Add(distance_dimension.CumulVar(pickup_index) <=
>         distance_dimension.CumulVar(delivery_index))
> 
> # Setting first solution heuristic.
> search_parameters = pywrapcp.DefaultRoutingSearchParameters()
> search_parameters.first_solution_strategy = (
>     routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)
> 
> # Solve the problem.
> assignment = routing.SolveWithParameters(search_parameters)
> 
> # Print solution on console.
> if assignment:
>     print_solution(data, manager, routing, assignment)
> ```
> 
> And the error is:
> 
> ```
> 
> ---------------------------------------------------------------------------
> OverflowError                             Traceback (most recent call last)
> <ipython-input-8-0e92227487b5> in distance_callback(from_index, to_index)
>      15     # Convert from routing variable Index to distance matrix NodeIndex.
> ---> 16     from_node = manager.IndexToNode(from_index)
>      17     to_node = manager.IndexToNode(to_index)
> 
> ~/anaconda3/lib/python3.7/site-packages/ortools/constraint_solver/pywrapcp.py in IndexToNode(self, index)
>    3170     def IndexToNode(self, index: 'int64') -> "operations_research::RoutingIndexManager::NodeIndex":
> -> 3171         return _pywrapcp.RoutingIndexManager_IndexToNode(self, index)
>    3172 RoutingIndexManager_swigregister = _pywrapcp.RoutingIndexManager_swigregister
> 
> OverflowError: in method 'RoutingIndexManager_IndexToNode', argument 2 of type 'int64'
> 
> The above exception was the direct cause of the following exception:
> 
> SystemError                               Traceback (most recent call last)
> ~/anaconda3/lib/python3.7/site-packages/ortools/constraint_solver/pywrapcp.py in <lambda>(self, name, value)
>    2135         __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
> -> 2136     __setattr__ = lambda self, name, value: _swig_setattr(self, Assignment, name, value)
>    2137     __swig_getmethods__ = {}
> 
> ~/anaconda3/lib/python3.7/site-packages/ortools/constraint_solver/pywrapcp.py in _swig_setattr(self, class_type, name, value)
>      70 def _swig_setattr(self, class_type, name, value):
> ---> 71     return _swig_setattr_nondynamic(self, class_type, name, value, 0)
>      72 
> 
> ~/anaconda3/lib/python3.7/site-packages/ortools/constraint_solver/pywrapcp.py in _swig_setattr_nondynamic(self, class_type, name, value, static)
>      54     if (name == "this"):
> ---> 55         if type(value).__name__ == 'SwigPyObject':
>      56             self.__dict__[name] = value
> 
> SystemError: <class 'type'> returned a result with an error set
> 
> The above exception was the direct cause of the following exception:
> 
> SystemError                               Traceback (most recent call last)
> <ipython-input-8-0e92227487b5> in <module>
>      63 
>      64 # Solve the problem.
> ---> 65 assignment = routing.SolveWithParameters(search_parameters)
>      66 
>      67 # Print solution on console.
> 
> ~/anaconda3/lib/python3.7/site-packages/ortools/constraint_solver/pywrapcp.py in SolveWithParameters(self, search_parameters, solutions)
>    3471 
>    3472     def SolveWithParameters(self, search_parameters: 'operations_research::RoutingSearchParameters const &', solutions: 'std::vector< operations_research::Assignment const * > *'=None) -> "operations_research::Assignment const *":
> -> 3473         return _pywrapcp.RoutingModel_SolveWithParameters(self, search_parameters, solutions)
>    3474 
>    3475     def SolveFromAssignmentWithParameters(self, assignment: 'Assignment', search_parameters: 'operations_research::RoutingSearchParameters const &', solutions: 'std::vector< operations_research::Assignment const * > *'=None) -> "operations_research::Assignment const *":
> 
> SystemError: <built-in function RoutingModel_SolveWithParameters> returned a result with an error set
> ```

Hi @Khev ,
Since my code used [ORTools 7.0](https://github.com/google/or-tools/releases/tag/v7.0), there would be some problems when you execute it with higher version. I really sorry that I can't help you much, but I think @Mizux might have ideas to solve this.
Good luck!

**Comment by Khev** [comment]
Hi @daoducminh,

Thanks for sharing, I have everything working now!

**Comment by Nikhil-Vashishtha** [comment]
Hello all,
I know it's closed thread, but I had a doubt.

In pickup delivery model, the demand makes sense in delivery nodes, but the demand callback created has considered all nodes, including pickup nodes.
How does it fit into the picture in practical sense?

Please elaborate if possible.

Thanks and Regards

**Comment by vilumaa** [comment]
@Nikhil-Vashishtha might be late, but I solved it the following way:

In my demand matrix I have a positive value for each pickup node and a negative value for each dropoff. When a vehicle arrives at a pickup node, the demand dimension for that vehicle will increase. Similarly, each dropoff node will reduce the amount of "demand" that's currently on the truck.

So, if you have a delivery from A to B then your demand would look something like 
`demand['A'] = 5`
`demand['B'] = -5`

**Comment by RadhuKS** [comment]
Hi All,

I am running the exact code for route optimization with pick up and delivery, but The code doesnt generate any solution at all.


def create_data_model():

    data = {}
    data['distance_matrix'] = [
        [0, 22722, 16299, 13388, 9625, 8082, 21738, 24642, 11389, 10438, 16649, 24499, 26711, 24512, 1256, 1312, 25882, 1672, 2713, 1420, 22034, 5002], 
        [20716, 0, 11935, 12779, 18858, 15957, 8272, 9001, 15522, 19340, 23530, 18987, 18774, 8221, 21916, 21975, 44784, 24327, 23645, 23017, 40577, 24116], 
        [13762, 14905, 0, 4349, 13167, 10266, 17944, 20647, 12394, 13697, 26869, 24979, 33884, 20516, 14962, 15020, 37830, 17372, 16691, 16062, 33623, 17161], 
        [10335, 13960, 3249, 0, 9741, 6839, 13414, 16318, 8065, 9368, 23442, 20649, 29554, 16187, 11535, 11594, 34403, 13946, 13264, 12636, 30197, 13735], 
        [10513, 20267, 14497, 10732, 0, 3771, 14230, 13087, 4817, 2623, 6663, 12697, 18855, 14851, 10890, 11182, 36485, 9750, 9945, 10830, 26783, 15769], 
        [8532, 17386, 11616, 7851, 4632, 0, 11844, 12475, 3230, 3240, 10459, 12321, 17621, 12464, 8228, 8520, 36216, 8879, 8367, 8168, 26690, 13673], 
        [23890, 9043, 16537, 15953, 13809, 11848, 0, 3787, 10254, 11957, 16187, 8996, 11258, 3046, 25090, 25148, 47958, 27500, 26819, 26190, 43751, 27290], 
        [24425, 9725, 19399, 16487, 12537, 12066, 4610, 0, 9671, 10685, 14915, 7708, 9970, 2332, 28523, 28816, 48493, 28035, 26947, 28464, 44364, 27824], 
        [11263, 18717, 10968, 8057, 4462, 2927, 10144, 9719, 0, 2610, 11957, 9565, 14865, 10765, 11548, 11841, 37120, 12199, 11687, 11489, 29190, 16404], 
        [10198, 19872, 12225, 9313, 2262, 2892, 12017, 10874, 2604, 0, 9757, 10720, 17464, 12638, 10575, 10867, 38531, 11226, 10714, 10516, 28829, 17815], 
        [19338, 23712, 27680, 24769, 6678, 10457, 15802, 14658, 11963, 9769, 0, 10804, 13016, 20758, 17145, 17437, 43520, 16465, 15569, 17085, 32986, 22803], 
        [26371, 19751, 23719, 20808, 12454, 11942, 11841, 7794, 9812, 10560, 10569, 0, 7239, 16797, 24177, 24470, 50552, 23498, 22601, 24118, 40018, 29836], 
        [27820, 20113, 29031, 26120, 15962, 17254, 11246, 10084, 15124, 16555, 12018, 7083, 0, 12720, 25626, 25919, 52001, 24947, 24050, 25567, 41467, 31285], 
        [23744, 8693, 18718, 15807, 14330, 12369, 2980, 2369, 10775, 12478, 16709, 9517, 11779, 0, 24944, 25003, 47812, 27355, 26673, 26044, 43605, 27144], 
        [1956, 24667, 18244, 15333, 9758, 8180, 23683, 26587, 11486, 10535, 16747, 24596, 26808, 26456, 0, 330, 25530, 893, 1454, 832, 20163, 6037], 
        [1271, 23422, 16999, 14087, 9765, 8222, 22438, 25342, 11528, 10577, 16789, 24638, 26851, 25211, 472, 0, 26219, 1365, 1926, 635, 20635, 5338], 
        [25972, 46650, 40227, 37316, 37416, 35358, 45666, 48570, 38018, 37787, 44001, 51850, 54063, 48439, 26676, 25439, 0, 24489, 25835, 26839, 19134, 13720], 
        [2454, 26271, 19848, 16936, 9578, 8879, 25287, 28191, 12186, 11235, 17446, 25296, 27508, 28060, 969, 955, 24678, 0, 1420, 1599, 20361, 5307], 
        [3230, 25320, 18897, 15986, 8717, 8391, 24336, 26586, 11698, 10747, 14882, 22731, 24943, 27110, 1265, 1548, 25736, 1192, 0, 1768, 19476, 6133], 
        [1968, 24678, 18255, 15344, 9769, 8191, 23694, 26599, 11497, 10546, 16758, 24607, 26820, 26468, 309, 561, 26929, 1124, 1469, 0, 20393, 6049], 
        [20782, 41460, 35037, 32126, 26793, 27246, 40476, 43380, 29735, 28784, 33021, 40871, 43083, 43249, 20579, 20863, 18988, 20477, 19815, 22238, 0, 22919], 
        [4909, 25562, 19139, 16228, 16330, 14273, 24578, 27482, 16933, 16702, 22916, 30765, 32977, 27351, 5613, 5944, 14439, 5915, 7070, 5776, 22936, 0]
    ]
    data['pickups_deliveries'] = [
        [14, 1],
        [15, 2],
        [14, 3],
        [16, 4],
        [17, 5],
        [16, 6],
        [18, 7],
        [19, 8],
        [15, 9],
        [15, 10],
        [20, 11],
        [15, 12],
        [21, 13]
    ]
    data['num_vehicles'] = 5
    data['depot'] = 0
    return data


def print_solution(data, manager, routing, solution):

    print(f'Objective: {solution.ObjectiveValue()}')
    total_distance = 0
    for vehicle_id in range(data['num_vehicles']):
        index = routing.Start(vehicle_id)
        plan_output = 'Route for vehicle {}:\n'.format(vehicle_id)
        route_distance = 0
        while not routing.IsEnd(index):
            plan_output += ' {} -> '.format(manager.IndexToNode(index))
            previous_index = index
            index = solution.Value(routing.NextVar(index))
            route_distance += routing.GetArcCostForVehicle(
                previous_index, index, vehicle_id)
        plan_output += '{}\n'.format(manager.IndexToNode(index))
        plan_output += 'Distance of the route: {}m\n'.format(route_distance)
        print(plan_output)
        total_distance += route_distance
    print('Total Distance of all routes: {}m'.format(total_distance))


# def main():

# Instantiate the data problem.
data = create_data_model()

# Create the routing index manager.
manager = pywrapcp.RoutingIndexManager(len(data['distance_matrix']),
                                       data['num_vehicles'], data['depot'])
# Create Routing Model.
routing = pywrapcp.RoutingModel(manager)

# Define cost of each arc.
def distance_callback(from_index, to_index):
#     print("inside distance_callback")
    # Convert from routing variable Index to distance matrix NodeIndex.
    from_node = manager.IndexToNode(from_index)
#     print("from_node", from_node)
    to_node = manager.IndexToNode(to_index)
#     print("to_node", to_node)
    return data['distance_matrix'][from_node][to_node]

transit_callback_index = routing.RegisterTransitCallback(distance_callback)
routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

# Add Distance constraint.
dimension_name = 'Distance'
routing.AddDimension(
    transit_callback_index,
    0,  # no slack
    90000,  # vehicle maximum travel distance
    True,  # start cumul to zero
    dimension_name)
distance_dimension = routing.GetDimensionOrDie(dimension_name)

distance_dimension.SetGlobalSpanCostCoefficient(100)

# Define Transportation Requests.
for request in data['pickups_deliveries']:
    pickup_index = manager.NodeToIndex(request[0])
    delivery_index = manager.NodeToIndex(request[1])
    routing.AddPickupAndDelivery(pickup_index, delivery_index)
    routing.solver().Add(
        routing.VehicleVar(pickup_index) == routing.VehicleVar(
            delivery_index))
    routing.solver().Add(
        distance_dimension.CumulVar(pickup_index) <=
        distance_dimension.CumulVar(delivery_index))

# Setting first solution heuristic.
search_parameters = pywrapcp.DefaultRoutingSearchParameters()
search_parameters.first_solution_strategy = (
    routing_enums_pb2.FirstSolutionStrategy.PARALLEL_CHEAPEST_INSERTION)
# print("search",search_parameters)
# Solve the problem.
solution = routing.SolveWithParameters(search_parameters)

# Print solution on console.
if solution:
    print("inside")
    print_solution(data, manager, routing, solution)


# if __name__ == '__main__':
#     main()

This is my code
