### ISSUE TITLE
Google or-tools installation on .netframework 4.6.1

### ISSUE THREAD

**Issue by KeramatHasani** [google/or-tools#1183]

**Comment by KeramatHasani** [comment]
Hi, I cannot install google or-tools on visual studio 2017 c# .net framework 4.6.1. Would you help how to solve the problem?

**Comment by Mizux** [comment]
please note, now OR-Tools use the `net standard 2.0` as framework which seems fully supported by .Net Framework `4.7.2`

According to https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

> 2 The versions listed here represent the rules that NuGet uses to determine whether a given .NET Standard library is applicable. While NuGet considers .NET Framework 4.6.1 as supporting .NET Standard 1.5 through 2.0, there are several issues with consuming .NET Standard libraries that were built for those versions from .NET Framework 4.6.1 projects. For .NET Framework projects that need to use such libraries, we recommend that you upgrade the project to target .NET Framework 4.7.2 or higher.

note: if you are tuck with 4.6.1 you may try to use the old version https://www.nuget.org/packages/Google.OrTools/6.7.4973 which should be compatible...

**Comment by KeramatHasani** [comment]
Thanks. Now I changed the target to framework4.7.2. It's apparently installed but the "google or-tools" is not seen references and the problem still exists.

**Comment by KeramatHasani** [comment]
Thanks. Now I changed the target to framework4.7.2. It's apparently installed but the "google or-tools" is not seen in references and the problem still exists.

**Comment by Mizux** [comment]
What do you mean by `not seen in references` ?

note: maybe related to #1185
