### ISSUE TITLE
How to cite OR-Tools in my thesis

### ISSUE THREAD

**Issue by 326623** [google/or-tools#1184]
Hello. I want to cite or-tools in my thesis and I haven't found any information on the subject yet. Thanks!

**Comment by Mizux** [comment]
@orwant  related to https://groups.google.com/forum/#!searchin/or-tools-discuss/or-tools$20cite%7Csort:date/or-tools-discuss/D_feD-YJ3ew/pLkjVH2tQAwJ

**Comment by 326623** [comment]
Thanks for such a quick reply!

**Comment by orwant** [comment]
Please use this: Google's OR-Tools, https://developers.google.com/optimization/.

**Comment by 326623** [comment]
How about this in BibTex?
The generated pdf looks like [this](https://imgur.com/xWbplrx)
Plain text: Google’s OR-Tools[EB/OL]. . https://developers.google.com/optimization/.

@online{ortools,
title = {Google's OR-Tools},
date = {2019},
urldate = {2019-4-11},
organization = {Google},
url = {https://developers.google.com/optimization/}
}

**Comment by lperron** [comment]
Maybe you can add the version you are using.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by 326623** [comment]
Added. Thanks!
