### ISSUE TITLE
Google.OrTools exception C# framework 4.7.2

### ISSUE THREAD

**Issue by KeramatHasani** [google/or-tools#1185]
I have installed the package Google.OrTools via NuGet but running the test program Visual Studio see this exception:
System.BadImageFormatException: 'Could not load file or assembly 'Google.OrTools, Version=7.0.6546.0, Culture=neutral, PublicKeyToken=53dbb1ea090cbef7' or one of its dependencies. An attempt was made to load a program with an incorrect format.'

**Comment by Mizux** [comment]
Which test program ? Are you using a Windows 64bits ?

**Comment by KeramatHasani** [comment]
I tried to run ShiftScheduling.cs
Yes it is 64 bit

**Comment by Mizux** [comment]
note on windows Google.OrTools depends on [Google.OrTools.runtime.win-x64](https://www.nuget.org/packages/Google.OrTools.runtime.win-x64/)

does it works if using the dotnet cli directly ?
note: on my way to test too

**Comment by KeramatHasani** [comment]
I tried many times. But each time I see this exception:
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Google.OrTools, Version=7.0.6546.0, Culture=neutral, PublicKeyToken=53dbb1ea090cbef7' or one of its dependencies. The system cannot find the file specified.

**Comment by lperron** [comment]
Can you check that visual studio c++ redistributables are installed.
Maybe they are not if you just install the C# layer.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by KeramatHasani** [comment]
Visual Studio C++ redistributables 2017 (x64) are installed.

**Comment by Mizux** [comment]
Create a pet project to "consume" Google.OrTools package
src: https://github.com/Mizux/or-tools-demo
log:  https://ci.appveyor.com/project/Mizux/or-tools-demo

**Comment by KeramatHasani** [comment]
The problem solved at last through migration to a new project on .Net Framework 4.7.2  and installing the latest version of google or-tools and running x64.  Thanks @lperron  @lperron

**Comment by zohaibdhukka** [comment]
I am facing the same problem and it gives me warning "There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Google.OrTools, Version=7.4.7247.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxxx, processorArchitecture=AMD64", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	App"

**Comment by zohaibdhukka** [comment]
> The problem solved at last through migration to a new project on .Net Framework 4.7.2 and installing the latest version of google or-tools and running x64. Thanks @lperron @lperron

i have the VS 2019 with .Net Framework 4.7.2 but i am having the same issue i don't know how to resolve it.

![Capture](https://user-images.githubusercontent.com/34459143/67401485-d8927880-f574-11e9-9eee-8eeda17e732e.PNG)

**Comment by Eudaemonic** [comment]
Have you tried to remove Prefer 32 Bit in Project Properties / Build / Platform Target?

**Comment by abeham** [comment]
@zohaibdhukka Maybe you are referencing an assembly (Google.OrTools.dll) that was signed with no key or a different one. If you open the .csproj file with a text editor you should find the reference to the or-tools. Try to remove PublicKeyToken from this reference and see if that works. That option is used to guarantee that you're loading the assembly against which you built the application. Otherwise check the assembly that is in the bin folder and which is tried to be loaded. Is it the same? In general, this should not be an or-tools specific problem.

**Comment by eric-yehl-ff** [comment]
> Have you tried to remove Prefer 32 Bit in Project Properties / Build / Platform Target?

@Eudaemonic thanks legend

**Comment by Kaiju1997** [comment]
VS 2019 with .Net Framework 4.7.2 but i am having the same issue and I tried fixing of everyone's advice, but I still can't. i don't know how to resolve it.     
![1](https://user-images.githubusercontent.com/31384231/108039039-27b7c300-706e-11eb-8f19-32e9596bab49.PNG)

**Comment by eleviness** [comment]
@Kaiju1997 Unsure if you're still having issues, for anyone else with this issue though, IIS Express needs to be set to run on 64 bit as well. This is in Tools -> Options -> Projects and Solutions -> Web Projects.
