### ISSUE TITLE
How to set time window in google or-tools vrptw?

### ISSUE THREAD

**Issue by sploitfun** [google/or-tools#1187]
I am new to Vehicle Routing Problem. I was going through the tutorial at https://developers.google.com/optimization/routing/cvrptw. For my use case I created the below data model.

```python
 def create_data_model():
     """Stores the data for the problem."""
     data = {}
     #Obtained from Google Maps Distance Matrix API - Duration Value in Mins
     data['time_matrix'] = [
          [0, 15, 22, 16, 14],
          [14, 0, 15, 7, 7],
          [23, 17, 0, 14, 19],
          [14, 7, 14, 0, 10],
          [13, 7, 17, 10, 0]
     ]
     #Dummy Data 
     data['time_windows'] = [
          (0, 100), #Depot
          (25, 70), #Loc1
          (25, 60), #Loc2
          (80, 120),#Loc3
          (0, 60),  #Loc4
     ]
     data['num_vehicles'] = 1
     data['depot'] = 0
     return data
 ```
My time dimension is:
```python
 time = 'Time'
 routing.AddDimension(
     transit_callback_index,
     30,  # allow waiting time
     100,  # maximum time per vehicle
     False,  # Don't force start cumul to zero.
     time)
``` 
When I run the above program I get the below output:
```sh
 Route for vehicle 0:  0 Time(0,0) -> 4 Time(14,38) -> 1 Time(25,45) -> 2 Time(40,60) -> 3 Time(80,80) - 0 Time(94,94) Time of the route: 94min
 
 Total time of all routes: 94min
```
Here I have three questions:

1. I am having trouble in understanding the output. At location 4, Time(14,38) is the solution window. As said in the tutorial link - It means the vehicle must arrive there between times 14 and 38 to stay on schedule. The solution window starts at time 14 because it takes 14 units of time (the 0, 4 entry of the time matrix) to get from the depot to location 4. However why the end time is 38? I am unclear of all the end times shown in output. How is end time derived?
2. As shown in my data model I am trying to solve a problem where a person from depot needs to reach Locations 1 through 4 within certain time limit.However what should be the value of 'time_windows' for the below case. Service time in each stop is 45 mins.
```
Depot - Time Window (4:30 AM to 9:30 AM) 
Loc1 - Time Window (5:00 AM to 9:00 AM)
Loc2 - Time Window (5:00 AM to 7:00 AM)
Loc2 - Time Window (5:00 AM to 7:00 AM)
Loc4 - Time Window (5:00 AM to 6:00 AM)
```

3. I am also unclear of AddDimension's allow waiting time value.

It would be really helpful if someone can help me out here. It will help me to learn more about or-tools. As its my first attempt with or-tools I have such a basic question, please bear with me here. Thanks!!

**Comment by Mizux** [comment]
1) this is the time range for the **arrival** time.
to understand the `38`, we know `travel(/*from*/4, /*to*/1) == 7` (see your time matrix), and we can see that in node `1` the max arrival time is `45` (to be on time for the next node) -> so we have `45 - 7 = 38` or `last allowed arrival time for next node - travel time from current to next node == last allowed arrival time for current node`.

2) I suppose your `time_windows` are the arrival time i.e. vehicle can arrive at Loc1 at 9:00am and start its work for 45min.
Transform all you date in duration (minutes) from 4:30am as reference i.e.
```
Depot: (0, 300)
Loc1: (30, 270)
Loc2: (30, 150)
Loc3: (30, 150)
Loc4: (30, 90)
```
and your service time is 45 to add to your transit callback
To incorporate service time please see https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/samples/cvrptw.py#L138-L171
note: service time must be added to the output edge. i.e. `transit_time(A, B) = service_time(A) + travel_time(A, B)` so time are still the arrival time.

3) this may help you: https://github.com/google/or-tools/issues/1051#issuecomment-461033132

**Comment by sploitfun** [comment]
@Mizux - Thanks a lot for the answers!! Your reply along with [cvrptw.py](https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/samples/cvrptw.py#L138-L171) cleared lot of my doubts. Neways I have couple more questions.

1. How to enable multiple different depots? My requirement is all my locations needed to be visited by two vehicles whose starting point is different from each other.
2. Can cvrptw skip some nodes when it cant be visited with the added time window constraints. If so how to enable it?

**Comment by Mizux** [comment]
1. https://developers.google.com/optimization/routing/routing_tasks#setting-start-and-end-locations-for-routes
(based on https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/samples/vrp_starts_ends.py)
-> https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/doc/VRP.md#multiple-starts-ends

2. You must need to add a `Disjunction` constraint
-> https://developers.google.com/optimization/routing/penalties
-> https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/samples/vrp_drop_nodes.py
-> https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/doc/VRP.md#drop-nodes-constraints

**Comment by sploitfun** [comment]
@Mizux Cool thanks a lot for the links!! Made things easier and clear for me.

One more question. Hopefully final one ;)

1. How to restrict number of nodes visited by a certain vehicle when using multiple vehicles.

```python ... ```
    for vehicle_id in range(data['num_vehicles']):
        index = routing.Start(vehicle_id)
        if vehicle_id == 0:
                time_dimension.CumulVar(index).SetMax(3)

I tried setting max limit to a vehicle node, however it didnt work out.

**Comment by Mizux** [comment]
1) create a "add plus one at each location" dimension instead
https://github.com/google/or-tools/issues/958#issuecomment-470010900

2) See the point 1) here https://github.com/google/or-tools/issues/1202#issuecomment-484268978

**Comment by sploitfun** [comment]
@Mizux - Thanks for the timely answers. It helped a lot, [except #1202( comment)](https://github.com/google/or-tools/issues/1202#issuecomment-484268978) production-zed every code!!

**Comment by Mizux** [comment]
@sploitfun in your example 1 you should have put the constraint on EndNode
```python
    for vehicle_id in range(data['num_vehicles']):
        index = routing.End(vehicle_id)
        if vehicle_id == 0:
                count_dimension.CumulVar(index).SetMax(3)
```

**Comment by sploitfun** [comment]
Hmm will try it out. Thanks!!

**Comment by lavanyanooka** [comment]
I am using the code from the documentation for vrptw problem. But, if I change any parameter for example  public int VehicleNumber = 4 to 1, the following code is giving Solution as null and hence the code is failing.
 
https://developers.google.com/optimization/routing/vrptw

  RoutingSearchParameters searchParameters =
          operations_research_constraint_solver.DefaultRoutingSearchParameters();
        searchParameters.FirstSolutionStrategy =
          FirstSolutionStrategy.Types.Value.PathCheapestArc;
        Assignment solution = routing.SolveWithParameters(searchParameters);

Can you please help me here

**Comment by rajshikhar007** [comment]
@Mizux hello , i read your all reply, and its very explaining.
while solving VRP via or_tools  it has solved by optimizing only **single objective.**  
can u please help me in   How to add multiobjective  problem (minimize vehicle number)?
it would be very grateful
thanks

**Comment by alexfdo** [comment]
Hello.
Is it possible to combine conditions for two tasks and solve them as one common task? For example, the task  "Vehicle Routing with Pickups and Deliverie" and the task "Vehicle Routing Problem with Time Windows".

**Comment by lperron** [comment]
I am pretty sure there is a pdptw example.

**Comment by Mizux** [comment]
Please avoid necro posting, for this kind of help, prefer to use the mailing list or the  discord chat...

@rajshikhar007 You should try to add a fixed cost for each vehicle used so solver will have incentive to avoid to use to much vehicle
see: https://github.com/google/or-tools/blob/45770b833997f827d322e929b1ed4781c4e60d44/ortools/constraint_solver/routing.h#L844-L848

@alexfdo 
yes, samples are just here to present each feature one by one for better understanding but you can mix as you want.
e.g.  https://github.com/google/or-tools/blob/stable/examples/cpp/cvrptw_with_stop_times_and_resources.cc

**Comment by rootpy2** [comment]
Hello,
How can I set constraint on departure time for every location?

For Example,
if Time window for location A is [2, 4] and B is also [2, 4] and T(A, B)  = service(A) + transit time(A, B) = 1.5 (using float just for example)
then vehicle will reach location B at 3.5 which is well within the time window of B, but service(B) = 1 then it exceeds the time window. Desired output is that, it should send two different vehicles.
But it is using single vehicle to serve both the Location and I know that's correct because the range of Cumul var at location is only for arrival.

Is there a way to implement departure constraint?

Thanks

**Comment by Mizux** [comment]
@rootpy2  please:
* use the mailing list or our discord channel
* avoid necro posting in a github issue

otherwise:
* a location can only be visited once i.e. by only one vehicle
* If you want to have the service time inside the Time windows then simply change the Time windows accordingly i.e. make TimeWindows(B) = [2, 3] i.e; 3 + service_time(B) <= 4 since service_time(B) = 1 in your example

**Comment by rootpy2** [comment]
My bad @Mizux 
Can you give me the discord link.

I don't think I was able to explain my problem correctly.

**Comment by kazitanvirahsan** [comment]
@Mizux - I am trying to match delivery time window to locations opening and location closing hour. For example the requested pickup time is 9am but location opens at 10am then it will not able to pick up from that location because location has not been opening yet. Is there any way to achieve this scenario??

**Comment by lperron** [comment]
Please do not revive old bugs.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le jeu. 6 mai 2021 à 08:56, Kazi Tanvir Ahsan ***@***.***> a
écrit :
