### ISSUE TITLE
OR-Tools + SCIP -> make cc dotnet -> Windows 10, VS 2017 Pro

### ISSUE THREAD

**Issue by TornadoJo** [google/or-tools#1188]
Hi all,

just my very first issue on github - so have some patience ;-)

- building SCIP worked.
- building OR-Tools with SCIP worked (at the end somehow....)

but I had to overcome several hurdles:
1.)
* in the subdirectory `ortools/base` **status_macros.h** is missing
* defining `VLOG_EVERY_N_SEC` e.g.:
https://github.com/google/or-tools/blob/4477092d8d38854b19b577bd586fd2829d0e8838/ortools/linear_solver/scip_interface.cc#L225
 and
* defining `RETURN_IF_ERROR` e.g.:
https://github.com/google/or-tools/blob/4477092d8d38854b19b577bd586fd2829d0e8838/ortools/linear_solver/scip_interface.cc#L169-L171
 needed by "scip_interface.cc" where it includes "ortools/base/status_macros.h" - the same that is excluded in linear_solver.cc#38
  -> I couldn't find it anywhere (on github) so I created a header file defining this two things to make "make cc" work...

2.) In several first tries I added the compilerflag "c++latest" to "CFLAGS = -nologo c++latest....in "Makefile.win.mk#166" to get rid of compiler warnigns in several "make cc"-compiles  --result-> several (7) linker errors at the end with added "c++latest"-flag - see attached complete log of the compile...

[make.dotnet.log](https://github.com/google/or-tools/files/3072220/make.dotnet.log) -> (log file represents a "make dotnet" with added status_macros.h and "c++latest" compiler flag added)

This lead to "make dotnet" to fail...

- After creating a (compile compatible) "status_macros.h" on my own and **_especially_** removing "c++latest" again from CFLAGS "make cc" and "make dotnet" went okay so far...

Question: What would the content of status_macros.h exactly be to get a valid and complete compile? (or am I missing something else?)

Another minor detail: changed CFLAGS /D__WIN32__  to /D__WIN64__ .... hmm.

**Comment by Mizux** [comment]
Hi,

Thanks a lot for your feedback ! 

To be honest the SCIP is not tested on CI (which are public Travis-CI , Appveyor) since SCIP license doesn't allow us to use it (ed you must download it from their website...).

AFAIK status_macros.h is a extract of what we have in the internal abseil-cpp, which is still not available publicly (i.e. abseil/abseil-cpp is trunked compared to the internal version) so we can "safely" export scip_interface.cc without making any change when exporting the file to github.
But as you have  noticed it seems we missed few macros (which are only use by SCIP) so we dind't spot it through the others non optional third party solvers (e.g. cbc_interface) ...

I'll try to fix it for v7.1 as well as test the SCIP 6.0.1 against windows build.

note: related to #1115

**Comment by TornadoJo** [comment]
Hi,

that would be wonderful! 

I read #1115 

Many tx!

**Comment by TornadoJo** [comment]
One additional minor bug while creating the Google.OrTools.runtime.win-x64.csproj - file

* <AssemblyOriginatorKeyFile>../../../bin/or-tools.snk</AssemblyOriginatorKeyFile> --should be-> <AssemblyOriginatorKeyFile>../../bin/or-tools.snk</AssemblyOriginatorKeyFile>

* I don't exactly remember: could it be that I had to create the root-"or-tools/bin" - directory by hand to get "or-tools.snk"-file and "scip.dll" copied/created there by make correctly

**Comment by Mizux** [comment]
@TornadoJo strange, it should be created automatically
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/makefiles/Makefile.dotnet.mk#L68
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/makefiles/Makefile.dotnet.mk#L276-L282

**Comment by TornadoJo** [comment]
@Mizuk U r amazing - never seen such a speed in answering!

- Creating "bin" - I saw it but I'm fine with that - could be something on my side - but I'm sure there was an errror moaning about ../bin... on the root-level of "or-tools-7.0" - could not.....

Btw, any chance to get the "original" code of status_macros.h posted here - just for the better feeling :)

kind regards

**Comment by Mizux** [comment]
@TornadoJo just check the internal source code, status object has a little bit diverged since so status_macros.h just won't work but I can try to simulate a similar method.

Actually, it's barely the same than the GLOP custom method ->
https://github.com/google/or-tools/blob/4477092d8d38854b19b577bd586fd2829d0e8838/ortools/glop/status.h#L69-L74

**Comment by Mizux** [comment]
For `VLOG_EVERY_N_SEC` need some time since OSS Glog know nothing about time management (there is abseil::time now need to check few things...)

**Comment by TornadoJo** [comment]
Okay, got it - tx!

Going to start compile test with Gurobi meanwhile for cc and dotnet....

**Comment by Mizux** [comment]
?
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/Makefile#L142

**Comment by TornadoJo** [comment]
Sorry - it was a reflex action to add it - didn't even look wheter it was in the makefile before,

Tested the original makefile -> works of course as intended^^

**Comment by Mizux** [comment]
Should be fixed on master

**Comment by TornadoJo** [comment]
Couldn't get it to work with master actually - right now:

Doing: make detect -> [detect.log](https://github.com/google/or-tools/files/3112135/detect.log)
Doing: make third_party -> [third_party - coin_wget_fail#1767.log](https://github.com/google/or-tools/files/3112138/third_party.-.coin_wget_fail.1767.log) -> easy to get done....

Doing: make third_party again -> [third_party.log](https://github.com/google/or-tools/files/3112142/third_party.log)
Doing: make cc: [cc.log](https://github.com/google/or-tools/files/3112145/cc.log) -> see last lines

so.... fall back to my original OR-Tools-folder with scip =>

Some remarks there - posted that on the commit already:
@regarding .\bin-folder problem: remember my report on that? Sometimes it happens (don't ask me why) that "bin" gets created as a file instead of a directory leading to other problems of course at "make test"... currently found a "bin"-!file! in the "or-tools-7.0" - root directory: exactly 40,140,800 bytes (38.2 MB) large -> exactly the size of scip.dll that should result... (whille looking for suspicious files in the root-folder I found an empty "NUL"-!file! (neither open nor delete works on this "special name" file under windows) and a WORKSPACE file (seems legit^^)) --workaround-> delete "bin"-folder, run "make clean cc" and while doing that, create a "bin" folder in root (and .\ortools if necessary)

@regarding make check_cc with the updates given here (5+1) and a commit by hand of scip_interface and status_macros.h ('cause an actual compile with SCIP+OR-master didn't work...) : everything works fine, after or-tools+scip get compiled now ->even integer_programming.exe example with SCIP works just fine beside the nerve racking MS Visual C++ Runtime Library debug error that several variables have not been initialized :) - but that one is on my side....^^
