### ISSUE TITLE
Package the .proto files with the NuGet package

### ISSUE THREAD

**Issue by mwpowellhtx** [google/or-tools#1190]
A little while back we discussed package the *CSharp* example code in a separate package. Actually, now, I think it would be beneficial to include the actual ``.proto`` files informing the *NuGet* assets. I have a specific use case for at least one of them, but may as well include them all while we're there. I can look into a *Pull Request* along these lines if necessary.

**Comment by Mizux** [comment]
Since `assets` means [something](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#includeassets-excludeassets-and-privateassets) in Microsoft Language, I guess you mean add **ContentFiles** to the Meta package `Google.OrTools` ?

src: https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#contenttargetfolders
src: https://docs.microsoft.com/en-us/nuget/reference/nuspec#including-content-files

@mwpowellhtx  Do you have any advice for content path etc ?

Otherwise since we generate API from the `.proto` why do you still need them directly, just curious

**Comment by mwpowellhtx** [comment]
@Mizux Yes, I really need the ``.proto`` files. Well, one of them for sure, but may as well include a ``**\*.proto`` while we're there. I will be parsing and code generating language level *Sat* parameters.

I would *git* extract a single file from the repository, but I think there are *Github* limitations where that's concerned. Git supports it, Github does not, I think, and cloning or even updating a local repository is overkill.

For paths, I believe that's accurate, yes, **ContentFiles** and so forth. Perhaps paths mirroring the source tree, perhaps akin to ``ortools\**\*.proto``.

**Comment by Mizux** [comment]
I would remove `ortools` prefix IMHO
e.g.
```
Source file:
    ortools\sat\cp_model.proto

.nuspec entry:
    <file src="..\..\sat\cp_model.proto" target="Content\sat" />

Packaged result:
    content\sat\cp_model.proto
```

**Comment by mwpowellhtx** [comment]
@Mizux Sounds reasonable to me.

**Comment by mwpowellhtx** [comment]
I should also clarify while I am here, *OrTools* maintains [*version 2*](http://developers.google.com/protocol-buffers/docs/reference/proto2-spec) ``.proto`` files today, correct?

**Comment by Mizux** [comment]
I would say it depends ^^; I can't even promise all proto will stick with their respective syntax version, i can just say that even in the Google monorepo, it's also a pain to update a .proto so they tend to be relatively "stable" (**BUT** without any warranty)

FYI:
```sh
[0]─[~/work/master]
[^v^]─mizux@mizux %find . -type f -iname "*.proto" -exec grep --color=always -Hin "proto[23]" {} \;  
./ortools/glop/parameters.proto:21:syntax = "proto2";
./ortools/sat/sat_parameters.proto:14:syntax = "proto2";
./ortools/sat/boolean_problem.proto:16:syntax = "proto2";
./ortools/sat/cp_model.proto:16:syntax = "proto3";
./ortools/bop/bop_parameters.proto:14:syntax = "proto2";
./ortools/graph/flow_problem.proto:36:syntax = "proto2";
./ortools/data/rcpsp.proto:68:syntax = "proto3";
./ortools/data/jobshop_scheduling.proto:40:syntax = "proto3";
./ortools/util/optional_boolean.proto:14:syntax = "proto3";
./ortools/linear_solver/linear_solver.proto:30:syntax = "proto2";
./ortools/linear_solver/linear_solver.proto:141:// To support 'unspecified' double value in proto3, the simplest is to wrap
./ortools/constraint_solver/demon_profiler.proto:15:syntax = "proto3";
./ortools/constraint_solver/assignment.proto:15:syntax = "proto3";
./ortools/constraint_solver/routing_enums.proto:16:syntax = "proto3";
./ortools/constraint_solver/routing_parameters.proto:18:syntax = "proto3";
./ortools/constraint_solver/solver_parameters.proto:16:syntax = "proto3";
./ortools/constraint_solver/search_limit.proto:17:syntax = "proto3";
```

**Comment by mwpowellhtx** [comment]
@Mizux Understood, fair enough. Thanks so much for responding to that so quickly. When it's committed I'll pull and build local so I can slot that into my build pipeline.

**Comment by mwpowellhtx** [comment]
@Mizux Did a brief analysis of the current code base and did not find any **.nuspec*. You may need to update ``*.proto``. You may need to update your *csproj* or analog output. Something like,

```Xml
<ItemGroup>
  <Content Include="contentFiles/**/*.*" copyToOutput="true">
    <IncludeInPackage>true</IncludeInPackage>
    <CopyToOutput>true</CopyToOutput>
    <BuildAction>Content</BuildAction>
    <copyToOutput>true</copyToOutput>
    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
  </Content>
</ItemGroup>
```

**Comment by Mizux** [comment]
Thank ! seems we already have
https://github.com/google/or-tools/blob/4477092d8d38854b19b577bd586fd2829d0e8838/ortools/dotnet/Google.OrTools/Google.OrTools.csproj.in#L160-L166

**Comment by mwpowellhtx** [comment]
@Mizux :+1: Perfect, rinse and repeat, then?

**Comment by mwpowellhtx** [comment]
@Mizux Just circling around and counting my ducks so to speak when I noticed. Should the ``Condition`` above be ``AND`` or ``OR``? i.e.

```
Exists('@(RuntimeLinux)') OR Exists('@(RuntimeOsx)') OR Exists('@(RuntimeWin)'
```

**Comment by Mizux** [comment]
when you build locally (i.e. on your one host), you just have/need a runtime and the meta which is automatically added to your local nuget package install so we don't need the runtime.json file at all...

When building the release which will have support for the three platforms (Linux, macOS, Windows) you need a runtime.json so .Net can select the right "backend" (containing the C# .dll and C++ native lib) associated to the Google.OrTools meta package (frontend containing the symbols list see the ref copy few line above)

So it must be a `AND` while ref above are `OR` since I just need one (and hope their are identical for all platforms)

**Comment by Mizux** [comment]
FYI (tested on Linux):
```sh
$ unzip -l packages/Google.OrTools.7.0.6686.nupkg           
Archive:  packages/Google.OrTools.7.0.6686.nupkg
  Length      Date    Time    Name
---------  ---------- -----   ----
      504  2019-05-06 09:14   _rels/.rels
     1213  2019-05-06 09:14   Google.OrTools.nuspec
   601088  2019-05-06 06:51   ref/netstandard2.0/Google.OrTools.dll
     3004  2018-11-27 12:36   content/graph/flow_problem.proto
    18608  2019-05-03 13:05   content/linear_solver/linear_solver.proto
    13693  2019-04-02 09:26   content/bop/bop_parameters.proto
    19687  2018-11-27 12:36   content/glop/parameters.proto
     1763  2019-05-03 13:05   content/constraint_solver/assignment.proto
      988  2019-04-02 09:26   content/constraint_solver/demon_profiler.proto
     6464  2019-04-02 09:26   content/constraint_solver/routing_enums.proto
    19927  2019-05-03 13:05   content/constraint_solver/routing_parameters.proto
     1371  2019-05-03 13:05   content/constraint_solver/search_limit.proto
     3856  2019-04-02 09:26   content/constraint_solver/solver_parameters.proto
     4591  2019-04-02 09:26   content/sat/boolean_problem.proto
    22777  2019-05-03 13:05   content/sat/cp_model.proto
    36224  2019-05-03 15:07   content/sat/sat_parameters.proto
     1347  2019-03-26 13:37   content/util/optional_boolean.proto
     6687  2019-04-02 09:26   content/data/jobshop_scheduling.proto
     6527  2018-11-27 12:36   content/data/rcpsp.proto
      523  2019-05-06 09:14   [Content_Types].xml
      734  2019-05-06 09:14   package/services/metadata/core-properties/44965c9a518c42a390d2e230e7ffb989.psmdcp
---------                     -------
   771576                     21 files
```

**Comment by mwpowellhtx** [comment]
@Mizux :+1: Beautiful, thanks for doing that. Can we expect that in the next monthly roll up?

**Comment by Mizux** [comment]
to be honest v7.1 release was planned for last week but is little bit late due to #1247 (Release SWIG 4.0 break the build and macOS homebrew already ship it...) and few things to clean (e.g. number version, release note...), so I hope to have it by the end of this week with a good confidence...

**Comment by mwpowellhtx** [comment]
@Mizux Is that a SWIG thing? Maybe don't update SWIG until it's been rinsed out a bit?

**Comment by Mizux** [comment]
We would like to be able to have the v7.1 (incoming stable) to compile from source out of the box for macOS users with a brew up to date etc...

**Comment by mwpowellhtx** [comment]
Right, I understand. I have a temporary stop gap workaround in place at the moment. Will stand poised to receive the package update when the issue is resolved.
