### ISSUE TITLE
Cannot make an AbsEquality on a scalar subtracted from a sum of variables 

### ISSUE THREAD

**Issue by jchillerup** [google/or-tools#1192]
Hi

I'm trying to schedule volunteers on a festival. I'm interested in people having equal work load, so I want to look at the error between _expected_ load vs. _actual_ load.

Getting the actual load involves summing a boolean vector denoting work yes/no relations to shifts. I multiply an integer vector on to that with the duration of the different shifts. Multiplying those vectors piecewise and summing them will give me the number of hours that volunteer is working.

I have the expected load from a division earlier (it is about 0.24), which I multiply with the amount of hours available to the festival for that volunteer. I want to minimize the error between those two numbers for all volunteers.

```python
loads = []
errors = []
for v, volunteer in enumerate(volunteers):
    error = model.NewIntVar(0, 1000, 'error_%i' % v)
    hours_worked = sum((shift_loads[s] * work[v, s]) for s in range(len(shifts)))

    if volunteer.load_multiplier == 1:
        devtol = load_deviation_tolerance
    else:
        devtol = load_deviation_tolerance / volunteer.load_multiplier
    
    model.Add(1000 * hours_worked >= int(volunteer.hours_present() * volunteer.load_multiplier * ((expected_load - devtol) * 1000) )) 
    model.Add(1000 * hours_worked <= int(volunteer.hours_present() * volunteer.load_multiplier * ((expected_load + devtol) * 1000) ))

    model.AddAbsEquality(error, 100000 * hours_worked - int(100000 * expected_load))
    errors.append(error)
```

The first two constraints function as a sanity check (we want to keep the load within ±0.015 of the expected, which turns out to be an easy constraint to satisfy).

I don't care about the sign of the error, so ideally I want a sum of absolute values to be minimized (so volunteer errors cannot cancel each other out). I get the following error:

```
TypeError: NotSupported: model.GetOrMakeIndex(((100000 * (((((((((((((((((((((((((((((((((((((((((((((((((((((((((((12 * work0_0)) + (5 * work0_1)) + (6 * work0_2)) + (6 * work0_3)) + (4 * work0_4)) + (3 * work0_5)) + (6 * work0_6)) + (2 * work0_7)) + (6 * work0_8)) + (5 * work0_9)) + (6 * work0_10)) + (6 * work0_11)) + (6 * work0_12)) + (4 * work0_13)) + (3 * work0_14)) + (6 * work0_15)) + (2 * work0_16)) + (6 * work0_17)) + (5 * work0_18)) + (6 * work0_19)) + (6 * work0_20)) + (6 * work0_21)) + (4 * work0_22)) + (3 * work0_23)) + (6 * work0_24)) + (2 * work0_25)) + (6 * work0_26)) + (5 * work0_27)) + (6 * work0_28)) + (6 * work0_29)) + (6 * work0_30)) + (4 * work0_31)) + (3 * work0_32)) + (6 * work0_33)) + (2 * work0_34)) + (6 * work0_35)) + (5 * work0_36)) + (6 * work0_37)) + (6 * work0_38)) + (6 * work0_39)) + (4 * work0_40)) + (3 * work0_41)) + (6 * work0_42)) + (2 * work0_43)) + (6 * work0_44)) + (5 * work0_45)) + (6 * work0_46)) + (2 * work0_47)) + (6 * work0_48)) + (6 * work0_49)) + (4 * work0_50)) + (3 * work0_51)) + (6 * work0_52)) + (2 * work0_53)) + (6 * work0_54)) + (5 * work0_55)) + (12 * work0_56)) + (4 * work0_57))) + -24224))
```

It seems the model is unable to put the absolute value of a sum into another variable. That's a bug, right? I'll try to rewrite the rule using channeled constrants on whether the actual load is less than or higher than the expected load.

Thanks!

**Comment by jchillerup** [comment]
So I tried this instead... It feels kinda hacky, and it doesn't work either ;). The linear inequalities in the OnlyEnforceIf clauses cannot be used as booleans.

```python
model.Add(
        error == 10000 * hours_worked - int(10000 * volunteer.hours_present() * volunteer.load_multiplier * expected_load)
    ).OnlyEnforceIf(
        10000 * hours_worked > int(10000 * volunteer.hours_present() * volunteer.load_multiplier * expected_load)
    )
    
    model.Add(
        error == int(10000 * volunteer.hours_present() * volunteer.load_multiplier * expected_load) - 10000 * hours_worked
    ).OnlyEnforceIf(
        10000 * hours_worked <= int(10000 * volunteer.hours_present() * volunteer.load_multiplier * expected_load)
    )
```

Error message: 
```
AttributeError: 'LinearInequality' object has no attribute 'Index'
```

**Comment by lperron** [comment]
OnlyEnforceIf takes a Boolean variable, not an expression, not a constraint.

MakeAbsEquality takes an array of integer variables, not expressions.

 t = abs(x - y) should be encoded as

z = x - y
t = abs(z)

I know it is verbose, but we like to the API to be without surprises like
creating intermediate variables and adding constraints silently.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by jchillerup** [comment]
Thans a lot, Laurent!
