### ISSUE TITLE
setTimeLimit example

### ISSUE THREAD

**Issue by hklarner** [google/or-tools#1195]
I am having trouble setting the time limit value of the search parameters in Java. I would like to pass an int at "XXX" below but `setTimeLimit` expects a `com.google.protobuf.Duration`. A new instance of that Duration object can not be created with an integer either. It requires a "builder", something like `com.google.protobuf.GeneratedMessageV3.Builder`. Surely I am overcomplicating things here.

Can you please give a Java example of setting the time out?

```java
RoutingSearchParameters searchParameters =
 main.defaultRoutingSearchParameters()
  .toBuilder()
   .setFirstSolutionStrategy(FirstSolutionStrategy.Value.PATH_CHEAPEST_ARC)
   .setTimeLimit(XXX)
   .build();
```

**Comment by Mizux** [comment]
First import Duration
```java
import com.google.protobuf.Duration;
```

then you can use:
```java
    RoutingSearchParameters searchParameters =
        main.defaultRoutingSearchParameters()
            .toBuilder()
            .setFirstSolutionStrategy(FirstSolutionStrategy.Value.PATH_CHEAPEST_ARC)
            .setLogSearch(true)
            .setTimeLimit(Duration.newBuilder().setSeconds(10).build())
            .build();
```

Using builder:
src: https://developers.google.com/protocol-buffers/docs/javatutorial#builders
src: https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Duration#newBuilder--

**Comment by hklarner** [comment]
thank you!

**Comment by Mizux** [comment]
For the record adding the sample: https://github.com/google/or-tools/blob/master/ortools/constraint_solver/samples/VrpWithTimeLimit.java
