### ISSUE TITLE
Solving VRP timewindows for connected Arks(help needed)

### ISSUE THREAD

**Issue by chakravarthiKalyan** [google/or-tools#1197]
**Ark** = corresponds to one independent route. It starts with a "Depot" and ends with a "Depot". And it has multiple waypoints.  There are timewindow constraints at each Depot.

**The structure of the network:**

	1.  An Ark is dependent on other Arks
	    1.  Arks form a DAG. eg:
	        1.  Ark1 → Ark2
	        2.  Ark1 → Ark3
	    2.  Which means, Ark2 should be completed before Ark1 and Ark3 should be completed before Ark1
	    3.  There can not be a cyclic dependency when modelling this way, so the arks form a DAG 
	2.  Parent Ark gets connected by a "Depot" in the child Ark
		 eg:   So Ark1 is connected to Ark2 at Ark2's depot

**Example**:
	
	 Ark2 =  depot(d1) --> c1 --> c2 --> c3 ---> depot(d1)
	 Ark3 = depot(d2) --> c4 --> c5 --> depot(d2)

	Ark1 ---> Ark2
	   |
	   |
	   V
	Ark3 

	Ark1 = depot(d3) --> d1 --> d2 --> depot(d3)

 The time window constraints at d1 and d2 for Ark1 will be derived once we have solved each of the child Arks(Ark2 and Ark3)

**The Problem:**
    
   There can be multiple routes from a VRP solution.
   eg:
   
		Ark2 = d1 (t1) --> c1 --> c2 --> d1
		         and d1(t2) --> c3 --> d1
		Ark3 = d2(t3)--> c4 --> d2
		        and d2(t4) --> c5 --> d2
 (t1  to t4 are time windows at a location)

So to solve Ark1, we have to consider all such possible child-routes.

I have started to build something on my own to solve the parent Ark.
But I am sensing, there are too many choices for larger networks and it feels a particular kind of algorithm methodology should be used.

Can I get some help if OR tools currently solves this sort of problem or is there some area of OR theory that I need to look into?

**Comment by Mizux** [comment]
Are you trying to find the shortest path in a DAG ?

**Comment by chakravarthiKalyan** [comment]
No, Not at all.

A waypoint in the parent ark's will have a time window, which gets derived from its child's solution.

Was the question not easy to understand?

**Comment by chakravarthiKalyan** [comment]
No, Not at all.

A waypoint in the parent ark's will have a time window, which gets derived from its child's solution.

Was the question not easy to understand?

**Comment by chakravarthiKalyan** [comment]
No, Not at all.

A waypoint in the parent ark's will have a time window, which gets derived from its child's solution.

Was the question not easy to understand?

**Comment by chakravarthiKalyan** [comment]
I shall reopen with a pictorial representation of my network. Thanks.
