### ISSUE TITLE
How to add setup time to jobshop - similar problem as issue 945 (not answered)

### ISSUE THREAD

**Issue by tuosor** [google/or-tools#1198]
Hello,

I'm working on a similar problem as below (thread https://github.com/google/or-tools/issues/945) . In this case, there is a setup time in each machine that is dependent on both the current job and the previous one that was done on the machine. And, as lperron commented, there is "a zero setup time between jobs of the same 'family'".

How am I able to accomplish this kind of addition? This was not answered in the linked thread.

I'm working with the Python interface.

-----------------------------------------------------------------------------------------------

Thanks for your quick reply, and thanks for you helping me make this problem become more specific and clear.  You are so skillful on this.

**Here is the explaination to the questions**:

> 8) Setup time depends on the job, or on the job and its predecessor? If it
depends on both, it complicates the problem. If it depends just on the job,
just extend the duration of the job by its setup time.

Setup time depends on the job that about to start and its predecessor.

> Cost depends on which jobs are assigned to which machine?

Yes, because a machine has a cost rate per seconds and a job have a running duration(every job has a fixed running duration, but different job have different running duration), the cost of executing one job will be `machine cost rate per second` * `job running duration(seconds) + setup time(depends on the job that about to start and its predecessor)`

> What is profit? how it is used in the code?

A job has a `profit rate per second` and running duration, the profit of one job will be `profit rate per second` * `running duration(seconds)`.  Same with the job running duration, every job has a fixed profit rate, but the different job has a different profit rate.

> I still miss the objective part.

The objective part is:  
1. There is a limited machine number(e.g: 100 machines) can be used to schedule at the same time.
2. There are a lot of jobs waiting to run(e.g: 3000),  finished all of the jobs with those 100 machines above may take years.
3. The objective is: Try to pick as much as possible jobs from all the jobs and put them to all the machines for one month(30days),  Try to get a 30day's schedule sequence that maximizes the 30day's total profit(30day's total job profit - 30day's total cost).

_Originally posted by @maxnilz in https://github.com/google/or-tools/issues/945#issuecomment-443395586_

**Comment by lperron** [comment]
Please have a look at:

https://github.com/google/or-tools/blob/stable/examples/python/jobshop_ft06_distance_sat.py
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by tuosor** [comment]
Thanks for the swift response, I will be looking into it thoroughly. Does the approach outlined in the example also work if there are alternatives for tasks as well?

**Comment by lperron** [comment]
This example implements transitions with alternative

https://github.com/google/or-tools/blob/stable/examples/contrib/scheduling_with_transitions_sat.py
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by tuosor** [comment]
Thanks a bunch, this worked fine for my problem as well!
