### ISSUE TITLE
Problems with the decimals of the restrictions of the model created for CBC_MIXED_INTEGER_PROGRAMMING

### ISSUE THREAD

**Issue by raulctas** [google/or-tools#1199]
I'm using the graper for c#, the solver type is CBC_MIXED_INTEGER_PROGRAMMING.

When i adding restrictions with double type values, the Solver rounds up all the constants to 6 decimals, this causes errors (in some cases) in the final result, generating solutions that do not meet the initial restrictions by a small margin.

I'm normalizing the objective function, dividing by the total each coefficient. These roundings cause some coefficients of the objective function to be made 0, which affects the final result.

How can i established decimal numbers that will be used by de model to round up the constant values?

Is there a way to normalize the objective function without divide each coefficient by the total?

Any help will be very useful.
Thank you.

**Comment by lperron** [comment]
This is a property of all MIP solver.
All the arithmetic operations are done with an epsilon prevision (between
1e-4 and 1e-6).
Furthermore, the range of coefficients (max coeff / min coeff) shoud stay
bonded (something like < 1e9).
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by raulctas** [comment]
Thank you very much for your answer.

I understand what you are saying about decimals, I did not remember it.

Related to this other doubts:
In the solutions returns values with a number of decimals greater than 6 (in some cases up to 16), in these cases does not apply rounding?

The solver returns solutions that do not strictly comply with the restrictions of the model, the margin is very small but sometimes very striking for returning negative values, is this normal?

**Comment by lperron** [comment]
Yes, we returns the value given by the solver. It would be tricky to round
them and still be within the epsilon precision, because of accumulated
errors.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by raulctas** [comment]
Thank you again, your answer clarifies several things.

One last clarification: in your first answer you commented that: "(max coeff / min coeff) shoud stay bonded (something like <1e9)"
It mean the ratio between the maximum and minimum coefficient?
In that case, is there a recommended maximum for the max coeff or for the min coeff?

**Comment by lperron** [comment]
https://www.ibm.com/support/knowledgecenter/SSSA5P_12.6.1/ilog.odms.cplex.help/CPLEX/UsrMan/topics/discr_optim/mip/troubleshoot/60_ill_conditioned_MIP_kappa.html

Less than 1e7.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by raulctas** [comment]
I have been reviewing and in "or-tools" there is the ComputeExactConditionNumber method but it is not implemented for CBC_MIXED_INTEGER_PROGRAMMING.

Is there any other way to get this report for CBC_MIXED_INTEGER_PROGRAMMING?
