### ISSUE TITLE
CVRP set Minimum of vehicles to be used in solution

### ISSUE THREAD

**Issue by HeadhunterXamd** [google/or-tools#1201]
Is it possible to add a constraint to the overall model where there is a minimum amount of vehicles to use? I am using the dotnet nuget package for c#.
One suggestion I got from a colleague was:

```cs
for (int i = 0; i < minvehicles; i++)
{
    start = model.NextVar(model.Start(i));
    var end = model.End(i);
    start.RemoveValue(end);
}
```

but I don't think this should work...

**Comment by lperron** [comment]
Do not use hard constraint, use soft constraint on the min travelled time per vehicle to encourage the solver.
