### ISSUE TITLE
advice on trouble shooting

### ISSUE THREAD

**Issue by hklarner** [google/or-tools#1203]
I am going through the routing solver examples and sometimes the solver fails to find a solution for one of my toy examples. Usually it is because there is a bug in my code or because my data defines an infeasible problem. I often spend a lot of time trying to figure out what is going wrong because all I see is that no assignment was found or the program ran out of memory (even for small routing problems with only 5 stops).

Is there a debugging mode that allows me to see what the solver is doing? how many variables there are, how many constraints, how many partial assignments, how many feasible assignments, the current objective value, etc.

**Comment by Mizux** [comment]
half answer you have for the underlying CP solver:
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/solver_parameters.proto#L61-L90

https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/routing_parameters.proto#L364-L373

example usage here: https://github.com/google/or-tools/issues/1195#issuecomment-484045795

**Comment by hklarner** [comment]
I can set solver parameter values like this
```
Solver solver = routing.solver();
 solver.parameters().toBuilder()
  .setPrintAddedConstraints(true)
  .setPrintModel(true)
  .setProfilePropagation(true)
  .build();
```
but how do I pass the parameters back to the solver?

**Comment by Mizux** [comment]
take a look at:
https://github.com/google/or-tools/blob/3c0dd832c99c2f7acf5e53a1a669331590c664b2/ortools/constraint_solver/samples/VrpWithTimeLimit.java#L109-L121

**Comment by hklarner** [comment]
I was talking about the parameters for the CP solver that is used by the routing solver, i.e., `ConstraintSolverParameters` that I have to pass to `solver = routing.solver()`

**Comment by Mizux** [comment]
my bad you must pass it when building the Routing object
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/routing.h#L359-L360

**Comment by Mizux** [comment]
In python it is
```python
def main():
    data = create_data_model(...)
    manager = pywrapcp.RoutingIndexManager(
      len(data['distance_matrix']),
      data['num_vehicles'],
      data['start_locations'],
      data['end_locations'])

    parameters = pywrapcp.DefaultRoutingModelParameters()
    parameters.solver_parameters.trace_propagation = True
    parameters.solver_parameters.trace_search = True

    routing = pywrapcp.RoutingModel(manager, parameters)
```

**Comment by hklarner** [comment]
I am failing at

```
ConstraintSolverParameters solverParameters = ???
RoutingModelParameters modelParameters = ???
RoutingModel model = new RoutingModel(manager, modelParameters);
```

**Comment by hklarner** [comment]
is this the preferred way?

```
ConstraintSolverParameters solverParameters = ConstraintSolverParameters.newBuilder()
 .setPrintModel(true)
 .setProfilePropagation(true)
 .setPrintAddedConstraints(true)
 .build();
RoutingModelParameters modelParameters = main.defaultRoutingModelParameters();
modelParameters.toBuilder()
 .setSolverParameters(solverParameters)
 .build();
```

**Comment by Mizux** [comment]
I use
```java
...
import com.google.ortools.constraintsolver.Solver;
import com.google.ortools.constraintsolver.RoutingModel;
import com.google.ortools.constraintsolver.RoutingModelParameters;
import com.google.ortools.constraintsolver.RoutingSearchParameters;
import com.google.ortools.constraintsolver.ConstraintSolverParameters;
import com.google.ortools.constraintsolver.main;
...

   RoutingModelParameters modelParameters =
      main.defaultRoutingModelParameters()
      .toBuilder()
      .setSolverParameters(
          Solver.defaultSolverParameters()
              .toBuilder()
              .setTracePropagation(true).
              build())
      .build();

    // Create Routing Model.
    // [START routing_model]
    RoutingModel routing = new RoutingModel(manager, modelParameters);
    // [END routing_model]
```

**Comment by hklarner** [comment]
ah, that's where the default solver parameters are. I was looking in `main`

**Comment by GuyBenhaim** [comment]
Hello,
Did I set the relevant parameters correctly under **RoutingModelParameters**  or do I need also a **ConstraintSolverParameters** with the "message" mechanism like described below? 
Any example in C# ?

RoutingModelParameters model_parameters = RoutingModel.DefaultModelParameters();
model_parameters.ReduceVehicleCostModel = false;
model_parameters.MaxCallbackCacheSize = 2000;
// Final model
RoutingModel model = new RoutingModel(number_of_locations, number_of_vehicles, vehicle_starts_, vehicle_ends_, model_parameters);


 // Parameters which have to be set when creating a RoutingModel. 
 message RoutingModelParameters { 
   // Parameters to use in the underlying constraint solver. 
   **ConstraintSolverParameters** solver_parameters = 1; 
   // Advanced settings. 
   // If set to true reduction of the underlying constraint model will be 
   // attempted when all vehicles have exactly the same cost structure. This can 
   // result in significant speedups. 
   bool reduce_vehicle_cost_model = 2; 
   // Cache callback calls if the number of nodes in the model is less or equal 
   // to this value. 
   int32 max_callback_cache_size = 3; 
 }

**Comment by JacobenVosloo** [comment]
I also managed to configure the solver to print out the model, trace propagation and added constraints.... but I am unable to gain insights from the result... I was hoping I could gather what is preventing my model from outputting a result even though it seems just by looking at the problem that a result should be easy to find... I am providing more than enough trucks to solve every pickup and delivery yet when adding a `setSpanUpperBoundForVehicle()` the algorithm is unable to get a solution...

Here is an example of a part of the (very long) output
```
I0623 09:37:07.740763 107094016 utilities.cc:328]   CastExpressionIntoVariable
I0623 09:37:07.740767 107094016 utilities.cc:339]     expression: Product
I0623 09:37:07.740772 107094016 utilities.cc:363]         left: VehicleCostsConsidered98(0 .. 1)
I0623 09:37:07.740777 107094016 utilities.cc:363]         right: Time238(0..26372)
I0623 09:37:07.740782 107094016 utilities.cc:339]     target_variable: Product
I0623 09:37:07.740785 107094016 utilities.cc:363]         left: VehicleCostsConsidered98(0 .. 1)
I0623 09:37:07.740790 107094016 utilities.cc:363]         right: Time238(0..26372)
I0623 09:37:07.740795 107094016 utilities.cc:328]   CastExpressionIntoVariable
I0623 09:37:07.740799 107094016 utilities.cc:339]     expression: Product
I0623 09:37:07.740803 107094016 utilities.cc:363]         left: VehicleCostsConsidered99(0 .. 1)
I0623 09:37:07.740808 107094016 utilities.cc:363]         right: Time239(0..26372)
I0623 09:37:07.740813 107094016 utilities.cc:339]     target_variable: Product
I0623 09:37:07.740818 107094016 utilities.cc:363]         left: VehicleCostsConsidered99(0 .. 1)
I0623 09:37:07.740823 107094016 utilities.cc:363]         right: Time239(0..26372)
I0623 09:37:07.740828 107094016 utilities.cc:328]   MaxEqual
I0623 09:37:07.740831 107094016 utilities.cc:441]     variables: [
I0623 09:37:07.740835 107094016 utilities.cc:339]       Product
I0623 09:37:07.740839 107094016 utilities.cc:363]         left: VehicleCostsConsidered0(0 .. 1)
I0623 09:37:07.740844 107094016 utilities.cc:363]         right: Time140(0..26372)
I0623 09:37:07.740849 107094016 utilities.cc:339]       Product
I0623 09:37:07.740854 107094016 utilities.cc:363]         left: VehicleCostsConsidered1(0 .. 1)
I0623 09:37:07.740859 107094016 utilities.cc:363]         right: Time141(0..26372)
```

@hklarner did you manage to make sense of your output and did it actually help you debug and solve your problem?

@Mizux any documentation available to better understand the output?
