### ISSUE TITLE
Can not run OR tools on Azure

### ISSUE THREAD

**Issue by sereyly** [google/or-tools#1204]
I have been working on building a web API with .net core with Google OR tools and hosting it on Azure. I installed OR tools as Nuget package. But For some reason it doesn't work. I always get 500 Internal Error. It works wonderfully when I run it locally, but the moment I publish it to Azure, it stops working. Please help!

**Comment by Mizux** [comment]
please note Google OR tools is a **native**  package which depends on runtimes packages.

Are you sure Azure is one of the supported RID (win-x64, osx-x64 or linux-x64) ?

**Comment by lperron** [comment]
no news. Please reopen if needed.

**Comment by hollowback** [comment]
I was facing the same problem on Azure x64 funtion app - Could not load assembly Google.OrTools.
That assembly is located after build in "runtimes\win-x64\lib\.netstandard2.0\" and not in "bin\" folder where is searched for in Azure.
Unfortunatelly usage of original Google.OrTools.dll manually copied into "bin\" folder still throws an error "Could not load assembly...".

What helped me - this link: link http://codeingaddiction.blogspot.com/2011/06/how-to-add-strong-name-to-existing-dll_16.html
1) dissasembly Google.OrTools 
2) add strong name to assembly
3) build a new assembly with strong name included
4) manually copy new Google.OrTools into bin\ folder

**Comment by hollowback** [comment]
I was facing perhaps similar problem on Azure x64 funtion app - Could not load assembly Google.OrTools.
That assembly is located after build in "runtimes\win-x64\lib\ .netstandard2.0" and not in "bin" folder where is searched for in Azure.
Unfortunatelly usage of original Google.OrTools.dll manually copied into "bin" folder still throws an error "Could not load assembly...".

What helped me - this link: link http://codeingaddiction.blogspot.com/2011/06/how-to-add-strong-name-to-existing-dll_16.html

dissasembly Google.OrTools
add strong name to assembly
build a new assembly with strong name included
manually copy new Google.OrTools into bin\ folder

**Comment by ss-markmontesa** [comment]
Still experiencing this error "Could not load file or assembly 'Google.OrTools, Version=8.1.8487....".
It was build smoothly but when trying to run the OrTool it return the error above.
Any help are welcome.
Thanks

**Comment by apavelm** [comment]
Tried to Run or-tools on Azure function as well (windows-x64). 
Crashes on execution with "Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt."
