### ISSUE TITLE
Max distance traveled by vehicle

### ISSUE THREAD

**Issue by PritambhatYoryo** [google/or-tools#1206]
I am using VRP with C# and like to know how to put a constraint on max distance traveled by vehicle for each route.
Any help is appreciated.

**Comment by Mizux** [comment]
When creating a *distance* dimension you can use the overload method method where you can set a capacity (i.e. max distance) for each vehicle....
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/routing.h#L409-L412
