### ISSUE TITLE
AddVariableMinimized/MaximizedByFinalizer

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1207]
Hello,
Can you please explain the role/effect of `AddVariableMinimizedByFinalizer()` or `AddVariableMaximizedByFinalizer()`  vs.  `SetSpanCostCoefficientForAllVehicles(int64 coefficient)` ?

Is the first scheme more generic and can affect any variable we provide and not just dimension CumulVars?

**Comment by lperron** [comment]
// Adds a variable to minimize in the solution finalizer. The solution
// finalizer is called each time a solution is found during the search and
// allows to instantiate secondary variables (such as dimension cumul
// variables).
void AddVariableMinimizedByFinalizer(IntVar* var);
// Adds a variable to maximize in the solution finalizer (see above for
// information on the solution finalizer).
void AddVariableMaximizedByFinalizer(IntVar* var);

// Sets a cost proportional to the dimension span on a given vehicle,
// or on all vehicles at once. "coefficient" must be nonnegative.
// This is handy to model costs proportional to idle time when the dimension
// represents time.
// The cost for a vehicle is
// span_cost = coefficient * (dimension end value - dimension start value).
void SetSpanCostCoefficientForVehicle(int64 coefficient, int vehicle);
void SetSpanCostCoefficientForAllVehicles(int64 coefficient);

The documentation in the source file seems complete. What do you find hard
to understand ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
Hi,
The only text regarding the role of Finalizer was this, which was very hard to understand its input, function, output. 
These were used in the example VrpTimeWindows, and enabling/disabling these changed some of the solution Node time spans [t1, t2], but it was hard to understand how this works.

**Any text that you can provide?**

****** In ROUTING.H line 1183:**
  // The next few members are in the public section only for testing purposes.
  // TODO(user): Find a way to test and restrict the access at the same time.
  // MakeGuidedSlackFinalizer creates a DecisionBuilder for the slacks of a
  // dimension using a callback to choose which values to start with.
  // The finalizer works only when all next variables in the model have
  // been fixed. It has the following two characteristics:
  // 1. It follows the routes defined by the nexts variables when choosing a
  //    variable to make a decision on.
  // 2. When it comes to choose a value for the slack of node i, the decision
  //    builder first calls the callback with argument i, and supposingly the
  //    returned value is x it creates decisions slack[i] = x, slack[i] = x + 1,
  //    slack[i] = x - 1, slack[i] = x + 2, etc.
  DecisionBuilder* MakeGuidedSlackFinalizer(
      const RoutingDimension* dimension,
      std::function<int64(int64)> initializer);

***** In  VrpTimeWindows.cs**

  // Instantiate route start and end times to produce feasible times.
    // [START depot_start_end_times]
    for (int i = 0; i < data.VehicleNumber; ++i) {
      routing.AddVariableMinimizedByFinalizer(
          timeDimension.CumulVar(routing.Start(i)));
      routing.AddVariableMinimizedByFinalizer(
          timeDimension.CumulVar(routing.End(i)));
    }
    // [END depot_start_end_times]

**Comment by lperron** [comment]
The finalizer is a sub-solve() method that will instantiate variables not
covered by the pure routing model.
This is the case for scheduling extensions (platform usage) for instance.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
Thx Laurant,
So sub-solve() runs after only a compliant solution is found by solver?   (I'm speculating here, as I did not find mention of sub-solve() )

It then checks different possible values of slackvar to minimize/maximize the value of the target IntVar variable, while still satisfying the constraints that apply or use this target variable?

If the target var (E.g. Time at a certain Node) has a cumulvar associated with it (E.g. time) will sub-solve() play with slackvar values for all the active Nodes (for min/max) and also ensure that all Nodes satisfy their constraints?
 
Guy

**Comment by lperron** [comment]
yes, compliant = compliant for the routing model.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
ok, 
I'll play with the example some more and see what I can learn.

**Comment by walelo9787** [comment]
Hey, I was following this discussion to try to understand the roles of routing.addVariableMinimizedByFinalizer. So, what I got, and not sure if this is right, is that for the TW example, it is being passed the routing.start and routing.end for the vehicles and this would minimize the waiting time aka slack, at all nodes that these vehicles would potentially pass through right ? Is that the case ? If so, how can the start and end indices be sufficient to cover all nodes in between ? is it minimizing the duration of the path all together and that would turn in minimizing slack of each node ?
