### ISSUE TITLE
Time dependent pickup amount at node

### ISSUE THREAD

**Issue by Zylatis** [google/or-tools#1210]
I would like to model a routing system where the amount of stuff to be picked up at each location is time dependent, is this possible in OR Tools? I.e. an empty truck might begin moving towards node A even though there is nothing there, because it knows by the time it gets there it will have things to pick up. The only other way i can think of doing this is a full time dependent simulation, so I would be very interested to learn if there are better ways

Thanks!
Z.

**Comment by Mizux** [comment]
seems related to the use of `AddDimensionDependentDimension()` (only available in C++)
With a time dimension and a capacity dimension depending on it...

see https://github.com/google/or-tools/issues/574#issuecomment-430203076 for a v6.10 API example

note: very slow currently...

**Comment by Zylatis** [comment]
Thanks for the swift reply! I will look into it. Perhaps a bit out of scope of the question but, do you think it is reasonable to pursue this as a true time dependent sim with something like simulated annealing? (i know it's all 'how long is a piece of string' but say for a small to medium sized system, < 50 nodes)

**Comment by lperron** [comment]
Just duplicate the visit, one per time window. Change the time at each visit, and add a disjunction on all the copies.

Time dependent dimensions are not ready to be used.

**Comment by Chabbou7** [comment]
@Mizux , Is AddDimensionDependentDimension still only available in c++ ?

**Comment by lperron** [comment]
yes, and it still does not work, even in C++.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by jose-joaquim** [comment]
Hi Laurent, 

Is there any specific reason for why this feature does not work as expected?
Can we model a workaround or make a collaboration in the source code?
