### ISSUE TITLE
P&D without using AddPickupAndDelivery

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1211]
Hello,
Is there a way/constraint to force Pick and Drop to be both included or both dropped but without using AddPickupAndDelivery element?

i.e. is there an expression to use in addition, to the same vehicle v(p)=v(d) constraint and visit-order t(p)< t(d) constraint that will guarantee this?

**Comment by Mizux** [comment]
Did you try to use a `AddDisjunction()` with a cardinality of 2 and the pickup and delivery nodes ?

https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/routing.h#L540-L557

**Comment by GuyBenhaim** [comment]
No, but now I will !

**Comment by GuyBenhaim** [comment]
Neat. Indeed adding it seems to motivate serving both P and D however, it does not seem gurantee that if one cannot be served (e.g. insufficient time) the other will be dropped as well.

**Comment by GuyBenhaim** [comment]
So, this is helpful but not compatible with simultaneous insertion.
