### ISSUE TITLE
FIFO / LIFO

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1212]
For v7 VRP:  Does the pick drop order policy (FIFO or LIFO) actually implements a visit order condition over visit time for each combination of two Nodes?
E.g.   for FIFO for any P&D pair of Nodes A: pick_A, drop_A  and P&D pair of Nodes B: pick_B, drop_B we require that t(pick_A) < t(pick_B) then t(drop_A) < t(drop_B) 
 (remember  **jmarca**'s commet for #922)

Or does it use a scheme that saves so many conditions to define and check?

**Comment by GuyBenhaim** [comment]
Any conclusion regarding expected performance with v7 Pick and Drop Policy, as opposed to using v6 and applying multiple constraints?

**Comment by Mizux** [comment]
you have:
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/routing.cc#L1969-L1984
and
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/constraint_solver.h#L1625-L1645
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/graph_constraints.cc#L1619-L1634
which is
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/graph_constraints.cc#L1598-L1609
and the class `PathTransitPrecedenceConstraint`
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/graph_constraints.cc#L1437
as a custom `nextBound()` method
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/graph_constraints.cc#L1509

So I would say, it may be faster to use this Ad hoc constraints of the solver...
But I didn't do any measurement nor I'm aware of.

**Comment by GuyBenhaim** [comment]
ok, thx. 
I will also consider these.
