### ISSUE TITLE
Have a vehicle from group visit a certain Node

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1215]
Hello,
How can we constrain such that one vehicle from or a pre-determined group of vehicles serves a certain pre-determined Node?   (Nicest is to group these as a vector).
E.g. Node 14 must be served only by one of the vehicles: 2, 7 or 10

Actually, cleanest would be if the vehicles in the group can be assigned a certain type, and allow only that e type to visit the Node. This can be implemented outside the model, but require multiple constraints, or by adding a dedicated dimension.

Thanks

**Comment by Mizux** [comment]
duplicate of https://github.com/google/or-tools/issues/334#issuecomment-484781754
