### ISSUE TITLE
node disjunction constraints or optional nodes not supported

### ISSUE THREAD

**Issue by hklarner** [google/or-tools#1216]
I have added penalties for dropping stops via

```
long penalty = 1000;
    for (int i = 1; i < data.distanceMatrix.length; ++i) {
      routing.addDisjunction(new long[] {manager.nodeToIndex(i)}, penalty);
    }
```
and now I see new warnings
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> W0424 17:03:04.942909 19191 routing.cc:2941] Node disjunction constraints or optional nodes not supported.

Should I worry about these?

**Comment by Mizux** [comment]
seems to comes from:
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/routing.cc#L2940-L2944

Never saw this, which FirstStrategy and local search did you use ?

**Comment by hklarner** [comment]
will get back to you asap

**Comment by lperron** [comment]
No worry, this is just a spurious message.
