### ISSUE TITLE
num_search_workers does not work on windows x64

### ISSUE THREAD

**Issue by adihe** [google/or-tools#1217]
The num_search_workers does not seem to work on Windows 10 x64.

When executing the solver with "num_search_workers:8" it will either **run forever** or it will return **Infeasible**.

Without this parameter the solver returns a **feasible** solution without problems.

I am using the latest version of or tools from nu-get.

Is this a known issue?

Thank you

**Comment by lperron** [comment]
Please write useful feedback.

Without a source code source or a protobuf output of the model, I cannot do anything.

**Comment by adihe** [comment]
Sorry. I will attempt to get the protobuf output. Cannot share the source unfortunately.

**Comment by adihe** [comment]
Dear Laurent

I exported the value of model.Model.ToString() (C#) here:
https://www.dropbox.com/s/c0qj7wn36xug55e/proto_1.txt?dl=0

Is this what you meant by "protobuf output of the model" ?

When solving this model with "num_search_workers:8" and with "max_time_in_seconds:240.0" then the solver does not stop after 240 seconds and just keeps running.

When solving this model only with "max_time_in_seconds:240.0" then the solver stops correctly after timeout and yields a feasible result.

Is this of value?

Thanks,
Adrian

**Comment by lperron** [comment]
Thanks. I will have a look.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
OK,
it runs fine on master. I get a solution with value 638300 quite easily.
I believe that if you restrict to 6 threads (no LNS, it should be OK).

We will soon release 7.1 that corrects the problem.

Thanks for the report.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by adihe** [comment]
Thank you. With 6 threads it works like a charm for now.
Once v7.1 is released I'll restest again with 8 threads.

**Comment by adihe** [comment]
Hi again
I can confirm that the issue is resolved with latest code from master.
Thanks
