### ISSUE TITLE
What are big routing problems and how to solve them?

### ISSUE THREAD

**Issue by hklarner** [google/or-tools#1219]
I am working on vehicle routing problems with
- a time dimension
- a distance dimension
- a vehicle capacity dimension
- pickup and delivery relations
- and penalties for dropping stops

Soon I will be interested in problems with 2,000 - 10,000 stops. To me these problems appear to be hard optimization problems but I am not sure what the or-tools solver and modern CSP solvers in general are capable of. But, even constructing the distance / duration matrix for such problems takes tens of minutes (millions of entries) so I expect long waiting times and I am interested in you experience with or-tools.

What are large problems and how to solve them?
- should I think about adding constraints?
- which solution strategies are relevant here?
- should I try to compute good partial solutions?
- etc

**Comment by lperron** [comment]
So, for these constraints, I would target below 1000 stops. It could scale up, but you will get better results w.r.t. running time if you decompose into smaller problems and solve them independently.

The question to ask is whether there is a natural decomposition schema in your problem (time, type of trucks, geographical).

**Comment by Mizux** [comment]
@hklarner off topic you have http://www.math.uwaterloo.ca/tsp/concorde.html for solving "pure" TSP up to  85,900 nodes but OR-Tools has been designed to deal with several constraints (capacity, TW etc...) and real world issue than only solving TSP.

**Comment by GuyBenhaim** [comment]
Yes, quickly looking, I could find any mention of real aspects in Concord ...
I need to keep considering speed-up options with Or-Tools

**Comment by GuyBenhaim** [comment]
Aiming to speed-up the solution, I tried assigning only half of the vehicles to half of the Nodes, and the other half to the other half of the Nodes. Used routing.VehicleVar(index).SetValues(new int[] {-1, v1, v2, v3, ...});
I was hoping that artificially splitting the problem (via these constraints) would speed it up, but several tests in different configurations showed solver run times change -10% - +10% - i.e. no improvement.

Any idea?

**Comment by hklarner** [comment]
Do you know of a parameter setting, i.e., a solution strategy or meta heuristics etc., that is more likely to find at least a feasible solution?
