### ISSUE TITLE
HELP: Load balancing tasks in duplicated machines in JobShop like problem

### ISSUE THREAD

**Issue by gustavo-barros** [google/or-tools#1224]
Hi,

I'm trying to solve a jobShop like problem for a factory floor operations scheduling. I'm using CPSolver.

I have a lot of machines running in the factory, some of them are duplicated and grouped. I also have a lot of tasks that are distributed to these machines, normal proceding for jobShop. The difference is that I can assign a task to a group instead a specific machine. So what I need to happen is somehow a task need to be assigned to a machine contained inside the group. Is there a best way to do this using the solver? Or do I have to mannually pick one random machine in the group and set to the task?

**Comment by lperron** [comment]
Random won't work. Change the objective to favor equal load.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 26 avr. 2019 à 21:39, gustavo-barros <notifications@github.com> a
écrit :

**Comment by EduSikora** [comment]
Hi Perron,

Our objective is to find the optimal solution to complete all tasks in the least amount of time.

Does the solver have any way (or method name) of grouping same machines? 
So the solver does the balancing in the optimal way..?

Or should we pre-balance something like 50/50 of the tasks to each machine?

Thanks!!

**Comment by lperron** [comment]
with a pure makespan objective, the solver can do whatever it wants on the
machines with some slack.

I suggest you do it in two phases:
  - one solve which compute the optimal makespan
  - freeze it, and change the model to maximize fairness, and reoptimize.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Closing, Reopen if needed.
