### ISSUE TITLE
HELP: Resource constraint in JopShop like problem

### ISSUE THREAD

**Issue by gustavo-barros** [google/or-tools#1225]
Hi,

I'm trying to solve a jobShop like problem for a factory floor operations scheduling. I'm using CPSolver.

I have a task that only can run at a time if it have a resource available for it's use. So if I have two tasks of this kind, only one can run at same time. I saw there is a example using something similar in this link: 

https://developers.google.com/optimization/routing/cvrptw_resources

However, I'm using a different solver. How can I achieve this kind of behaviour?

**Comment by lperron** [comment]
https://github.com/google/or-tools/blob/stable/ortools/sat/doc/scheduling.md

and

https://github.com/google/or-tools/blob/stable/examples/python/flexible_job_shop_sat.py

Do not use the CPSolver, use the CP-SAT one.


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 26 avr. 2019 à 21:46, gustavo-barros <notifications@github.com> a
écrit :
