### ISSUE TITLE
Help: Warm starts with Gurobi MIP solver

### ISSUE THREAD

**Issue by Bionic-Matt** [google/or-tools#1226]
Hi,

I've constructed a MIP allocated problem in python using the Gurobi MIP solver, which is working well. I am aware that Gurobi itself allows for a warm start to be implemented through the use of an MIP start vector. Is there a way to implement this under the or-tools framework?

Regards,

Matt

**Comment by lperron** [comment]
Yes, look at the SetHint API.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le dim. 28 avr. 2019 à 20:14, Bionic-Matt <notifications@github.com> a
écrit :

**Comment by Bionic-Matt** [comment]
Hi again.

How is this parsed in python?
`std::vector<std::pair<const MPVariable*, double> > hint`

I would guess if I have an array, Arr, of pairs containing Variable names and hint values: 

SetHint(Arr) hint?

Thanks again

Matt

**Comment by Mizux** [comment]
Easy, it is not parsed...

`SetHint()` is **not** wrapped in Python, it is not in `or-tools/ortools/linear_solver/python/linear_solver.i` i.e. not generated in the `pywraplp.py`.

**Comment by rlloretb** [comment]
Does/will this SetHint also work for CBC and SCIP?

**Comment by lperron** [comment]
It works with SCIP. Not CBC.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



*De : *Roger Lloret-Batlle <notifications@github.com>
*Date : *lun. 13 mai 2019 à 09:20
*À : *google/or-tools
*Cc : *Laurent Perron, Comment

Does/will this SetHint also work for CBC and SCIP?

**Comment by omalleyt12** [comment]
Hi, is anyone working on this? This would be very helpful for my project as well

**Comment by lperron** [comment]
hinting is supported with SCIP and Gurobi.
I have just pushed support for python/java/C#.
