### ISSUE TITLE
RoutingModel multi-core support

### ISSUE THREAD

**Issue by EPronovost** [google/or-tools#1227]
According to https://github.com/google/or-tools/issues/417, `CP-SAT` supports parallelism.  However, it seems that RoutingModel is implemented with the original `SAT` solver.  Is there a way to utilize multiple CPU cores with the RoutingModel?  If not, is there a plan to implement this feature in the future?

**Comment by lperron** [comment]
original CP solver and no. and no.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 29 avr. 2019 à 21:21, Ethan Pronovost <notifications@github.com> a
écrit :

**Comment by memchk** [comment]
@lperron Is there currently any plans to switch the routing engine to the new parallel solver? If someone wanted to do that, given the code that is there, would you have an estimate in the undertaking of such a project?

**Comment by GuyBenhaim** [comment]
Indeed, interesting if there was a feasible way to make progress in this.

**Comment by lperron** [comment]
See the response in another thread.
The goal of the local search is to avoid calling the CP solver. So the gain
would be minimal, and the investment is large.

**Comment by Mizux** [comment]
For the record, it has been also discussed on the ortools-discuss list

> For the parties interested in routing and thinking about CP-SAT. Basically routing library is the way to go for VRP problems (which is actively maintained) and upgrading the solver under routing library (from CP to CP-SAT) wouldn't bring much performance since local search is already geared towards avoiding it (so upgrade is not a priority).
https://groups.google.com/forum/m/#!topic/or-tools-discuss/HDObICP7UHw
https://groups.google.com/forum/m/#!msg/or-tools-discuss/Pa5eQUoLnow/QpphaeLHBAAJ

src: https://groups.google.com/forum/#!msg/or-tools-discuss/z0ffWC8FJFw/ghDhWfJ3AwAJ

**Comment by Mizux** [comment]
Closing since there is no plan for the foreseeable future to do it...
