### ISSUE TITLE
XNOR Logic

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1229]
This is s syntax question:
With conditions A and B could you suggest a compact/efficient expression that applies XNOR logic?
I.e. output True/1 only when both conditions are True/1 or when both conditions are False/0?

Can this scale to 3 or more conditions?

**Comment by lperron** [comment]
bool_xor is equivalent to sum(bool_vars) is odd.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
I didn't get this, will sum give 0 when both inputs are 1?

**Comment by lperron** [comment]
It will give 2, which is even

**Comment by GuyBenhaim** [comment]
So use the output%2 ?
Thx

**Comment by lperron** [comment]
It could. 
I have a dedicated propagator for it.

x = sum(bool_vars)
result = x - 2 * x // 2

with the right intermediate variables.

Closing the issue now.
