### ISSUE TITLE
Condition Syntax in Routing/CP Solver

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1230]
I need to modify a Constraint using a `condition_b` whose value I can set to `0` or `1`.
Worked well with only `condition_a` but fails when I add `condition_b`:

```cpp
IntExpr condition_a = (
  model.CumulVar(model.NodeToIndex((int)order1), "load") >=
  model.CumulVar(model.NodeToIndex((int)order2), "load"));

IntExpr  condition_b = null; 
condition_b.SetValue(1) ; 

model.solver().Add((condition_a + condition_b) >= 1));
```

**Comment by Mizux** [comment]
Did you try https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/constraint_solver.h#L1132-L1136

**Comment by GuyBenhaim** [comment]
I'm trying to decrypt this...
We are adding a constaint that is created by MakeIfThenElseCt() where condition_b is checked vs. 0
model.solver().Add(model.solver().MakeIfThenElseCt( condition_b==0, condition_a, **??**, **??**));

What is needed in the last parameter "IntVar target_var" ?

**Comment by lperron** [comment]
You can create a constant var.
