### ISSUE TITLE
Attend service points with uniform time windows

### ISSUE THREAD

**Issue by karandeepakkanwar** [google/or-tools#1234]
Mine is more of question that an issue:
* I have service points throughout the day which have windows like 8 am - Noon and then from Noon until 4 pm.
* I can use the time windows but there is only 1 vehicle which can attend these service orders. Is there a way to do that using the time window constraint?
EDIT : There are multiple service points which have the same time windows : 8 - Noon and Noon to 4.

**Comment by Mizux** [comment]
Is it similar to this https://github.com/google/or-tools/issues/1202#issuecomment-484268978 ? (question 1)

note or-tools allow you to:
- remove value(s)/intervals from a TW
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/constraint_solver.h#L3980-L3988
- Force a node to be visited by a vehicle using `dimension.VehicleVar(index).SetValues(....)`

**Comment by karandeepakkanwar** [comment]
@Mizux I think it is pretty much the same. I'll can follow those instructions. 
Thanks a lot.
