### ISSUE TITLE
Check if custom solution is FEASIBLE

### ISSUE THREAD

**Issue by pedroprates** [google/or-tools#1235]
I am new to or-tools and I am trying to have a multi-agent optimization using `cp_model`. I have two different models that are running on series, and I want to check if the resulting scenario of the last model does not violate any constraints of the first model, but I don't see to figure out how to only validate the variables (check if the variables are not violating any constraints, i.e., this solution is feasible) without running the solver on the first model again. 

Do you guys know if there is a way to check if a previously known solution is feasible or not? 

Best regards,

Pedro

**Comment by lperron** [comment]
I need to document that.

here is the idea

use the cp_model class (CpModelBuilder in C++, CpModel in java, c#, python).
Get the proto from it. Record the number of constraints().
then go back to the cp_model class, and add var == value constraints for
all decision variables.

Solve(). It should not actually solve, mostly presolve everything away.

Then go back to the model proto, and delete the extra constraints.


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 30 avr. 2019 à 21:43, Pedro Prates <notifications@github.com> a
écrit :

**Comment by routemapper** [comment]
Laurent, do you have a code sample of what you just described?

**Comment by lperron** [comment]
Not yet.

Le jeu. 16 mai 2019 à 03:06, routemapper <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
Still not yet, but it is explained here:

https://github.com/google/or-tools/blob/stable/ortools/sat/doc/model.md

Get the underlying proto, record the number of constraints.
For each variable x, add a new x == value_in_solution

Check, 

then reduce the number of constraints in the model to the recorded value, effectively removing the new constraints.

Alternatively, keep the extra constraints and manipulate the domain field of the linear constraints to change the value, before checking a new solution.
