### ISSUE TITLE
HELP: Setting CumulVar SoftUpperBound for multiple vehicles

### ISSUE THREAD

**Issue by danpat** [google/or-tools#1237]
I'm trying to model a multi-vehicle delivery problem with several constraints:

  1. There's a single depot, with limited resources for loading packages - I've got this modelled just fine.
  2. Some packages have soft service end windows - modelling this with `SetCumulVarSoftUpperBound` works as expected.
  3. Vehicles have shift start/end times, but overtime is allowed at the discretion of the driver - thus far I've used `AddDimensionWithVehicleTransitAndCapacity` to set the end constraint (infinity if overtime is permitted), and `SetRange` on the vehicle cumulvar to set the star time.
  4. Packages have a "priority" value - plans should try to place high priority deliveries earlier in the plan, so they do not end up the overtime window, if one exists - but a plan should still be made even if this isn't possible.  No disjunctions.

(4) is what I'm having trouble figuring out how to model.  What I'd *like* is to apply some kind of penalty coefficient like `SetCumulVarSoftUpperBound`, *but* the trouble is that the penalty is depending on which vehicle the package is on.  If I had a global "end of day" value, I could simply set the soft upper bound to this, and move on - but the upper bound is dependent on the vehicle in use, as different vehicles have different start/end shift times.

Is it possible to model this?  Anyone got any ideas how?

**Comment by lperron** [comment]
Each vehicle has its end node, with associated cumul var.
add the soft constraint on this one.
