### ISSUE TITLE
python SAT, add numeric if..else, bool logic or implication 

### ISSUE THREAD

**Issue by abduakhatov** [google/or-tools#1239]
According to these examples [bool](https://github.com/google/or-tools/blob/master/ortools/sat/doc/boolean_logic.md), [channeling](https://github.com/google/or-tools/blob/master/ortools/sat/doc/channeling.md):  

`NewBoolVar` is always used to add add if..else, bool logic or implication, but how to add numeric implication(checking for numeric condition to be true)?

e.x: 
```
a = model.NewIntVar(0, 10, 'a')
b = model.NewIntVar(0, 100, 'b')

# ""how to check:""
# if a equals 6:
# then b = b - 30

...
```

Maybe I missed something in above-mentioned examples, so apologies if question is a bit dummy. 

Thank you beforehand

**Comment by lperron** [comment]
Create a boolvar bv

bv implies a == 6
not bv implies a != 6

then use bv in your implication.

Note that b = b - 30 will returns infeasible.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by abduakhatov** [comment]
Thank you for your instant reply, the approach is clear. Could you please, make a hint what to do to add constraint for ```b == b - 30```, as u mentioned it returns infeasible.

**Comment by abduakhatov** [comment]
I suppose, one way could be to create another model int var but, is there any other option?

**Comment by lperron** [comment]
b == b - 30 will be simplified to 0 == -30
Which is always false.

**Comment by lperron** [comment]
This is not an imperative language, you are writing equations

**Comment by abduakhatov** [comment]
yes, but for my case it is required to assign b, so ```b==b-30```, means ```b=100-30``` (explicitly). So, I added constraint from other side. ```model.Maximize(y)``` And  INFEASIBLE disapeared
