### ISSUE TITLE
Global Span cost elements

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1240]
Hi,
What does this do/acheive:
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/routing.h#L2058-L2060

Guy

**Comment by Mizux** [comment]
I would say it is the (internal) method used to effectively apply the `GlobalSpanCostCoefficient` ?

ref:
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/routing.cc#L6269-L6309

**Comment by lperron** [comment]
/// Sets a cost proportional to the dimension span on a given vehicle,
  /// or on all vehicles at once. "coefficient" must be nonnegative.
  /// This is handy to model costs proportional to idle time when the dimension
  /// represents time.
  /// The cost for a vehicle is
  ///   span_cost = coefficient * (dimension end value - dimension start value).
  void SetSpanCostCoefficientForVehicle(int64 coefficient, int vehicle);
  void SetSpanCostCoefficientForAllVehicles(int64 coefficient);
