### ISSUE TITLE
Routing solver with breaks fails if vehicle is not used

### ISSUE THREAD

**Issue by jmarca** [google/or-tools#1243]
I am having some success with implementing breaks, but it appears that if a break is set on a vehicle that is not used, the solver "fails fast" with no solution found.

Edit: forgot to say, I'm on v7.0, (Version: 7.0.6546 installed via pip install) and solving a variant of PDPTW. 

Without breaks the solver runs fine.

I set a minimal break on each vehicle, for just one minute each, as follows:

```python
    breaks = {}
    for i in range(0,len(vehicles.vehicles)):
        breaks[i]=[]
        first_break_time = solver.FixedDurationIntervalVar(
            0,
            horizon,
            1,     # duration of break is 1 minute
            True,  # optional
            'start of driving timing break for vehicle {}'.format(i))
        breaks[i].append(first_break_time)

        print('breaks for vehicle',i,' are:',breaks[i])
        time_dimension.SetBreakIntervalsOfVehicle(
            breaks[i], i, node_visit_transit)

```

Running with just a few demands, my program will run fine for 1 or 2 vehicles, but crash every time with 3 vehicles or more with the solver very quickly returning no assignment.

With a much larger data set, the solver works with 3 vehicles, but fails on 4 or more.

My *guess* is that the first trial solution does not use all of the vehicles, but since all vehicles have breaks (even though they are optional) the solver sees a conflict (must have break, but vehicle is not used) and quits.

I tried running 
https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/samples/cvrptw_break.py

but I noticed only one break being used, because [line 309 is commented out](https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/samples/cvrptw_break.py#L309)

When I uncommented that line to apply breaks to all vehicles, not just vehicle 0, the example program goes away and works forever so I killed it---which is perhaps a separate bug to file?

**Comment by jmarca** [comment]
Banging around on this issue some more, it appears that although I can get breaks to work beautifully for one vehicle, two is dicey and three is out of the question.  

My understanding is that a break should be interpreted as time that the vehicle cannot use for visiting a node.  So as long as there is flexibility in the dimension to accommodate the break(s) between node visits, then the break should be slotted in.

What I am not sure about is the whole concept of optional versus required.  It appears to me that optional breaks will be inserted by the solver if it works, but otherwise will be skipped.  It also appears to me that setting optional to 0 or False, the break will not be skipped, and the schedule of node visits will be accommodated accordingly.

I'm also unclear on the use of IntVar* PerformedVariable in:

```
  // Creates an interval var with a fixed duration, and performed_variable.
  // The duration must be greater than 0.
  IntervalVar* MakeFixedDurationIntervalVar(IntVar* const start_variable,
                                            int64 duration,
                                            IntVar* const performed_variable,
                                            const std::string& name);
```

I'm using the related function:
```
  // Creates a performed interval var with a fixed duration. The duration must
  // be greater than 0.
  IntervalVar* MakeFixedDurationIntervalVar(IntVar* const start_variable,
                                            int64 duration,
                                            const std::string& name);
```
to successfully create a "starting break" that occurs N hours after the start of the route. But it would be nice to understand what "performed_variable" means in order to make this initial break optional (say if the route is shorter than N hours + Break Hours.  In other words, if a route is 6 hours long, and the between break time is 8 hours and the break time is 8 hours, how do I make the initial break optional, and yet still use an IntVar type expression to sync it with the start of the route?

**Comment by jmarca** [comment]
Updating, my current solution is to create nodes at which breaks happen.  This works better than breaks, although the problem complexity goes up quite a bit.  With 100 OD pairs each requiring multiple breaks between pickup and delivery (so about 4000 total nodes for the problem), I find the only way to get the solver to work is to generate a set of feasible solutions (pickup and delivery pair) per vehicle.  With that starting point, the solver can get a result, but without it it gets stuck.

Needless to say, using breaks as intended might be nicer, but in the end might be just as complex for any problem of significant size, and it might be harder to generate an initial feasible route.

**Comment by danmarinescu** [comment]
I seem to have run into the same issue running OR-Tools 7.1 (6720). Setting breaks works well for one vehicle, but as soon as I add a second vehicle (with some pre-assigned nodes) it quickly returns without finding a solution. This suggests that the resulting set of constraints has no feasible solution. If I remove the breaks everything works fine. 

@jmarca I tried the same approach of creating nodes at which the breaks happen. However I ran into the issue of computing the transit cost between two "real" nodes with a "break" node in the middle. How did you define the distance between a "real" node and the "break" node? Setting it to 0 effectively allows "teleporting" between two nodes with a break in the middle.

**Comment by jmarca** [comment]
I put in a reasonable time. That is, if the break rule is break after 8 hrs driving, then distance from start to break is 8hrs, from break to dest is d(o,d)-8hrs, and trips to all other nodes are forbidden (very large distance). I had two kinds of breaks, which made it complicated, and edge case needing to allow for a break based on earlier travel. But yes, there has to be a realistic travel time to the dummy break node or the solver results will be wrong. 

Code is in my repo, esp in https://github.com/jmarca/initial-solution/blob/master/src/breaks.py

James

**Comment by danmarinescu** [comment]
Thanks James, I'll have a look at your repo to understand this better. That said, I don't think this approach would work for me, as in my case breaks can take place within a certain time window, meaning there is no fixed distance between start and break.

**Comment by jmarca** [comment]
The devil’s in the details as usual, but the way I set things up for my application was pretty flexible. The breaks needed to be timed based on total elapsed driving time. 

If you have a requirement that a break has to happen at a certain time, you could probably insert dummy nodes (probably per vehicle) and then use a disjunction to allow visiting only one of them at the correct break time. 

James

**Comment by matthewrj** [comment]
I am also experiencing similar issues when trying to use breaks. I have upgraded to 7.2 and I am getting more success than 7.1 but still not reliably getting solutions.

It is fine with one vehicle and many breaks. Eg. After 12 hours of working you must take a 12 hour break but you can take the breaks at any time of the day. I can build a route for a whole week with 6 breaks that are less than 12 hours apart for a single vehicle.

When I try using multiple vehicles, I can get some cases to work with 3 vehicles and one break per vehicle but never two breaks and can't do more than 3.

**Comment by braktar** [comment]
I met a similar behaviour with 7.0 and 7.3. 

With vehicles working from 0:00 to 16:00 and one break of 1 hour between 12:00 and 16:00.
147 nodes to visit (In this scenario 2 vehicles are enough to serve all of them)
With 3 vehicles it works well. With 4, in my case it still works. But with a higher number of vehicles it the resolution didn't find any solution. Some heuristics instantaneously return no solution.
In version 7.3, GLOBAL_CHEAPEST_ARC runs until the time-out is reached.

**Comment by braktar** [comment]
I fixed the issue by my side. The std::vector<int64> node_visit_transits wasn't defined for the nodes corresponding to the depots.

I should return saying that the array size of node_visit_transits is incorrect, but only fail to find a solution.

Pretty strange it works until 5 vehicles.

**Comment by jmarca** [comment]
Can you elaborate a bit more on your fix?  I’m not sure I understand.

**Comment by braktar** [comment]
node_visit_transits is supposed to contains visit duration for each node. By my side, the nodes are organized the following way: 
node1, node2, node3, node4, start_node1, start_node2, end_node1, end_node2

I've only defined node_visit_transits on the nodes to visit, because I didn't imagine that the visit duration at start and end nodes could anything but 0. So node_visit_transits was : [1,1,1,1]. This returns no error, which is strange because the array size is 4 but the total number of nodes here is 8.

So the fix was simply to add zero to service duration for the missing nodes. Which gives [1,1,1,1,0,0,0,0].
