### ISSUE TITLE
Soft constraint for a vehicle to serve a certain order/node

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1245]
Hello,
Is there a way for a **soft**-constraint for a certain vehicle to serve a certain node?
Thx

**Comment by Mizux** [comment]
did you try
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/routing.h#L608-L612

giving your node and the vehicle start node ?

**Comment by GuyBenhaim** [comment]
Thx, actually this is exactly why I asked ...

I already did this and the **Solver gets stuck forever** when one of the nodes the start node of the vehicle:
 **model.AddSoftSameVehicleConstraint(new int[] { 0, (int)model.Start(0)}, 600000);**

And, as you probably recall, I also obsevd un-expected behavior with multiple nodes (there are spread over two vehicles ).

**Comment by Mizux** [comment]
so again the good old https://github.com/google/or-tools/issues/847#issuecomment-420608114

**Comment by GuyBenhaim** [comment]
Thx,
How do I do it with a soft constraint?   Where do I use ActiveVar, multiply the NodeIndex ?

**Comment by qemtek** [comment]
This would be great to know.. I am trying this with multiple nodes, including the driver start node, and it doesnt seem to have any effect
