### ISSUE TITLE
Multiple Visits of same node VRP

### ISSUE THREAD

**Issue by PierreHamoir** [google/or-tools#1246]
Dear All,

I am trying to solve a Waste Collection VRP in which there are Collection Plants (CP) one the one hand and Treatment Plants (TP) on the other hand. The trucks start (and end) at the depot and must take waste from the CP and deliver it to the TP. As there are much more CP as TP, some of The TP can be visited several times during a single trip for each vehicle.

By default the or tools VRP Solver doesn't like it , and I was wondering if there is a solution to allow multiple visits of the same node with this package.

**Comment by Mizux** [comment]
short answer: no at first routing is a tsp/vrp solver i.e. you can only visit each node one time.

workaround: If you want to be able to visit several time the same node you'll need to split your node in several nodes.

note: there is already few issues on the same subject...

**Comment by PierreHamoir** [comment]
Thank you @Mizux for your answer and sorry for the duplicate.

As I don't know how many visits there will be on the same node, is there a way to tell the solver that it is not compulsory to visit some nodes ?

**Comment by Mizux** [comment]
take a look at https://developers.google.com/optimization/routing/penalties
