### ISSUE TITLE
Constrain Routing Problem to use Subset of Vehicles

### ISSUE THREAD

**Issue by memchk** [google/or-tools#1250]
Hello,

I am trying to constrain the solver to optimize for some subset of the defined vehicles. In other words, given vehicles A,B,C,D,E, each with their own capacities / costs, I want the solver to minimize the routing cost while being able pick up to 3 of the defined vehicles to handle the route.

Thanks.

**Comment by memchk** [comment]
Also, I believe my only option is to use the AllUnperformed first solution, otherwise it always attempts to use all vehicles. Is that assumption correct?

**Comment by lperron** [comment]
AllUnperformed talks about visits, not vehicles.
