### ISSUE TITLE
CP-SAT: Model returns different optimum values in consecutive runs

### ISSUE THREAD

**Issue by marbuttner** [google/or-tools#1251]
I'm experimenting with OR-Tools for scheduling problems. When I try to solve a 15 x 20 instance from ORLib (Instance abz7 from [here](http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/jobshop1.txt)), I get a different optimal makespan on each run.
I'm using OR-Tools 7.0.6546 with the Python API and set num_search_workers = 8.

[The model proto](https://github.com/google/or-tools/files/3148364/abz7.txt.zip); I get "optimum" values between 664 and 672

**Comment by lperron** [comment]
Yes, this is fixed on the master branch.
The LNS threads caused problems with over-enthusiastic presolve :-)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by marbuttner** [comment]
Thanks for the quick response. I guess I'll try the master branch then :)

**Comment by lperron** [comment]
7.1 is out, which fixes the problem.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



*De : *marbuttner <notifications@github.com>
*Date : *lun. 6 mai 2019 à 16:46
*À : *google/or-tools
*Cc : *Laurent Perron, Comment

Thanks for the quick response. I guess I'll try the master branch then :)
