### ISSUE TITLE
GUIDED_LOCAL_SEARCH on trivial VRP (4-node) problem runs forever

### ISSUE THREAD

**Issue by danpat** [google/or-tools#1253]
While debugging some hanging test cases in our codebase, I noticed that some trivial cases were timing out.

It seems that using:

```
searchParameters.set_local_search_metaheuristic(LocalSearchMetaheuristic::GUIDED_LOCAL_SEARCH);
```

can cause even small problems to search forever.  In my test case, there are only 4 nodes (1 depot, 3 locations to visit) and 1 vehicle.  I would've expected this to return quickly, regardless of the metaheuristic, it should be brute forceable.

I took `ortools/constraint_solver/samples/vrp.cc` and modified it into a reproducible test case:

```c++
#include "ortools/constraint_solver/routing.h"
#include "ortools/constraint_solver/routing_enums.pb.h"
#include "ortools/constraint_solver/routing_index_manager.h"
#include "ortools/constraint_solver/routing_parameters.h"
#include <vector>

namespace operations_research 
{
struct DataModel
{
    const std::vector<std::vector<int64>> distance_matrix{
        {0, 10, 20, 30}, {10, 0, 10, 20}, {20, 10, 0, 10}, {30, 20, 10, 0}};
    const int num_vehicles = 1;
    const RoutingIndexManager::NodeIndex depot{0};
};

void PrintSolution(const DataModel &data,
                   const RoutingIndexManager &manager,
                   const RoutingModel &routing,
                   const Assignment &solution)
{
    LOG(INFO) << "Objective: " << solution.ObjectiveValue();
    // etc, etc
}

void Vrp()
{
    DataModel data;
    RoutingIndexManager manager(data.distance_matrix.size(), data.num_vehicles, data.depot);
    RoutingModel routing(manager);
    const int transit_callback_index = routing.RegisterTransitCallback(
        [&data, &manager](int64 from_index, int64 to_index) -> int64 {
            // Convert from routing variable Index to distance matrix NodeIndex.
            auto from_node = manager.IndexToNode(from_index).value();
            auto to_node = manager.IndexToNode(to_index).value();
            return data.distance_matrix[from_node][to_node];
        });
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index);
    RoutingSearchParameters searchParameters = DefaultRoutingSearchParameters();
    searchParameters.set_first_solution_strategy(FirstSolutionStrategy::PATH_CHEAPEST_ARC);
    searchParameters.set_local_search_metaheuristic(LocalSearchMetaheuristic::GUIDED_LOCAL_SEARCH);
    const Assignment *solution = routing.SolveWithParameters(searchParameters);
    PrintSolution(data, manager, routing, *solution);
}
}

int main(int argc, char **argv)
{
    operations_research::Vrp();
    return EXIT_SUCCESS;
}
```

I notice that:

```
W0507 15:45:57.950053 283653568 routing.cc:4744] GUIDED_LOCAL_SEARCH specified without sane timeout: solve may run forever.
```

is logged in this case, but for such a trivial problem, why does `GUIDED_LOCAL_SEARCH` never (apparently) complete?  I would expect the search space to be completely exhausted quite quickly.

**Comment by lperron** [comment]
Gls , tabu, sa never terminates. You need a time limit.

Le mer. 8 mai 2019 à 00:58, Daniel Patterson <notifications@github.com> a
écrit :

**Comment by Mizux** [comment]
You can take a look at:
https://github.com/google/or-tools/blob/master/ortools/constraint_solver/samples/vrp_with_time_limit.cc
or the in doc https://developers.google.com/optimization/routing/routing_tasks#search_limits

**Comment by danpat** [comment]
@lperron @Mizux Yes, I'm aware of the solver time limit setting, and setting it definitely avoids the problem.  My question was more about whether the solver should be *expected* to exit if it's able to exhaustively search the solution space.

I gather that the implication here is that GLS, Tabu, and SA have no way to track whether they're revisiting already seen solution space?  I can understand how that may be infeasible for most problems, but it seems like there may be an optimization here for "small" problems.

It seems to me that a nice feature might be a new metaheuristic, say `BRUTE_FORCE`, which can be chosen by the client if it knows the problem space is small.

**Comment by lperron** [comment]
By definition GLS, Tabu, and SA cannot exhaust the search space.

There is a parameter that force the use of tree search
(use_depth_first_search).
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 8 mai 2019 à 16:31, Daniel Patterson <notifications@github.com> a
écrit :

**Comment by danpat** [comment]
@lperron ah-ha, that's perfect, thank you!

**Comment by Mizux** [comment]
For the record
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/routing_parameters.proto#L326-L330
