### ISSUE TITLE
Build error with `make third_party`

### ISSUE THREAD

**Issue by cjdrake** [google/or-tools#126]
I have been having trouble with using `make third_party`. I'm using an Ubuntu Trust 14.04 with all the dependencies listed [here](https://developers.google.com/optimization/installing) installed (eg bison, flex, texlive, etc).

When I run `make third_party`, it *sometimes* works, but usually I get this:

```
/home/cjdrake/src/github.com/cjdrake/or-tools/dependencies/sources/bison-3.0.4/./tests/bison: line 28: /home/cjdrake/src/github.com/cjdrake/or-tools/dependencies/sources/bison-3.0.4/src/bison: No such file or directory
Can't open y.tab.[ch]: No such file or directory.
make[1]: *** [src/parse-gram.c] Error 127
make[1]: Leaving directory `/home/cjdrake/src/github.com/cjdrake/or-tools/dependencies/sources/bison-3.0.4'
make: *** [dependencies/install/bin/bison] Error 2
```

I'm guessing maybe there's a dependency missing in the gmake recipe?, or something that causes non-deterministic behavior.

Have you ever seen this problem before?

**Comment by lperron** [comment]
I do not understand why you have bison304 in the path, it is bison-3.0.4 in
mine.

And sometimes last week, the bison server was down.

--Laurent

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2015-12-13 22:23 GMT+01:00 Chris Drake <notifications@github.com>:

**Comment by cjdrake** [comment]
I think I can explain (sort of) the part about bison-304 vs bison-3.0.4.

When I look at the GitHub web UI, I'm seeing `bison-3.0.4`, but when I look at my email, I see `bison-304`. Must be some kind of github bug.

**Comment by cjdrake** [comment]
As for the other problem, I just did an experiment. After failing with `make third_party`, I ran `make -j third_party` to see if I could get gmake to shake the order up a bit--and it worked! What I think happened is that the build for `flex` was allowed to go ahead of the build for `bison`, and as a result the dependency was satisfied. So my *guess* is that there's an ordering dependency from flex to bison that's not currently specified in the Makefile.

**Comment by lperron** [comment]
No,

I believe the bison server was down, and just needed a retry.

--Laurent

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2015-12-16 8:39 GMT+01:00 Chris Drake <notifications@github.com>:

**Comment by cjdrake** [comment]
Yes, you're right. I tried to reproduce, and ran into some other connection problems, but couldn't reproduce. Also, I looked at Bison 3.0.4 independently, and it doesn't depend on flex, so that was wrong.

Going to close this bug now, but would like to get your thoughts on how [grpc](https://github.com/grpc/grpc/tree/master/third_party) does their third_party directory. At least a couple of your dependencies are from Git repositories, so it might work out better for them.

**Comment by lperron** [comment]
I would love to get all dependencies in github directly.

Let's see, on unix, we depend on:
  - gflags
  - protobuf
  - sparsehash
  - coin
  - swig
  - pcre
  - bison
  - flex
  - autoconf, automake, libtool

github: gflags, protobuf, sparsehash, swig, git
svn: coin, pcre, 
source only: bison, auto tools

It would be nice to have the first two lines (git, svn) directly as automatic dependencies.
I just do not know how to do it :-(

On windows, 
  - zlib
  - gflags
  - protobuf
  - sparsehash
  - coin cbc
  - swig
  - flex, bison

Last 2 are binary release (easy), all the first one are available from github or svn.

So definitely, this would be a huge improvement.

Thanks

**Comment by lperron** [comment]
On unix, I changed swig, and pcre to use git.
Flex chokes on missing autopoint :-(
coin is hard because svn tracks dependencies automatically, while git does not.
