### ISSUE TITLE
HELP: Performance Issues in JobShop like problem

### ISSUE THREAD

**Issue by gustavo-barros** [google/or-tools#1261]
Hi,

I'm trying to solve a jobShop like problem for a factory floor operations scheduling. I'm using CP-SAT solver.

Now we are facing a performance problem. Seems we spotted a weird behaviour in the solver that we are trying to understand whats is happening under the hood. So maybe you can help me.

We are reading chunks of data from a CSV file like this, each time in larger pieces always starting from the first task (excluding the header) to the length defined:
![image](https://user-images.githubusercontent.com/36746102/57456624-46a3e700-7244-11e9-8085-ca0be1cbc6f5.png)

So for example if I run a chunk of length 25, means I read from the file the range (2, 26) of tasks and so on.
![image](https://user-images.githubusercontent.com/36746102/57458053-10b43200-7247-11e9-960f-6856c37a345a.png)

The weird behaviour I noticed is that, when I run the first 200 or 800 tasks the average time is 00:02:30 minutes before I stop the solver without completion. But then when I run the first 900 or 1200 the solving time is 00:00:19.11 and 00:00:42.81 respectively. That's shorter than the 00:02:30 as the average for the above example that not even finished. 

So the solver solved faster a large amount of data. That make me wonder if there is something related to the composition of data, some sort of intrinsic order or dependency that must be preprocessed before sending it to the solver. You have any idea of what can be causing this?

Other issue is, I handled to solve 8.000 tasks running with 2 workers in my dual core cpu. It was solved in time 03:30:36.20. How can we solve this in 2 minutes instead of 3 hours? You think running this in a server with 20 - 40 cores could improve the solving time? Or maybe applying some other strategy? 

Below I show some of the results I had. 

# 150 tasks
![image](https://user-images.githubusercontent.com/36746102/57452613-aac1ad80-723a-11e9-8d53-c3e3138384fd.png)
![image](https://user-images.githubusercontent.com/36746102/57452633-b614d900-723a-11e9-8ff4-df33744fa4dc.png)

# 200 - 800 tasks
Solving Time >~ 00:02:30

#  900 tasks
![image](https://user-images.githubusercontent.com/36746102/57454654-bc598400-723f-11e9-883b-2b8e7304f371.png)
![image](https://user-images.githubusercontent.com/36746102/57454669-c5e2ec00-723f-11e9-968b-98a871c0179f.png)

# 1.000 tasks
![image](https://user-images.githubusercontent.com/36746102/57452539-7f3ec300-723a-11e9-8649-9ed4987747f5.png)

![image](https://user-images.githubusercontent.com/36746102/57452525-73530100-723a-11e9-9960-b4ca2cd471a9.png)

# 1.200 tasks
![image](https://user-images.githubusercontent.com/36746102/57454765-ff1b5c00-723f-11e9-8bfa-99f2f23dc996.png)
![image](https://user-images.githubusercontent.com/36746102/57454782-09d5f100-7240-11e9-8b8e-31f03cfba553.png)

# 1.500 tasks
![image](https://user-images.githubusercontent.com/36746102/57452838-2cb1d680-723b-11e9-8bbe-741cc7e76d23.png)
![image](https://user-images.githubusercontent.com/36746102/57452854-35a2a800-723b-11e9-8c42-e40afb1e06e3.png)

# 1.700 tasks
![image](https://user-images.githubusercontent.com/36746102/57455390-684f9f00-7241-11e9-9110-77397fb1c8ee.png)
![image](https://user-images.githubusercontent.com/36746102/57455372-61c12780-7241-11e9-870e-427ee184b6b8.png)

**Comment by lperron** [comment]
I would say it depends on the data.

Imagine a simple jobshop with one very large job. Without this job, proving optimality is hard.
With this job, just pack it with the highest priority, All the other jobs are easier to pack around the long job (before or after the tasks of the long job), and the optimal is found easily.

I am not sure this is what is happening, but I know the for the same size of problem, data sets can make them ridiculously hard or trivial to solve.

**Comment by gustavo-barros** [comment]
Ok, I'll try to do some analysis and find a way to deal with the data. How about the speedups? There is something I can do to speedup the calculation time? Maybe something built-in inside ORTools? Like the GPU enable in TensorFlow for example.

I tried to use multiple workers. But that only replicates the solver with different start seeds over the multi-threads right? Increasing the chance to find a optimal solution faster in some of the threads. But not actually speedup the calculation process. Correct? 

I imagine that internally, at the end, you guys end up with several matrices operations right? Maybe it could be made in parallel multicores or even in GPUs?

Please, give me some light on this issue.

**Comment by lperron** [comment]
The workers in // are vastly different.
worker 0: default search
worker 1: fixed search if defined, else pseudo cost search
worker 2: simplex off
worker 3: maximum linearization
worker 4: core based search
then lns with different seeds for each additional worker.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



*De : *gustavo-barros <notifications@github.com>
*Date : *lun. 13 mai 2019 à 13:43
*À : *google/or-tools
*Cc : *Laurent Perron, Comment

Ok, I'll try to do some analysis and find a way to deal with the data. How

**Comment by gustavo-barros** [comment]
Hmmm I see, so the workers actually refer to the way they will search? Thats no multi-threading then?
How can I speedup my application then?

**Comment by lperron** [comment]
This is multithreading, but not search tree splitting.
As proved here in the parallel section:
https://www.minizinc.org/challenge2018/results2018.html

I believe this is the best way to speed up search.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



*De : *gustavo-barros <notifications@github.com>
*Date : *mer. 15 mai 2019 à 13:36
*À : *google/or-tools
*Cc : *Laurent Perron, Comment

Hmmm I see, so the workers actually refer to the way they will search?

**Comment by gustavo-barros** [comment]
Hey Laurent,

Could you explain to me how each worker works? 

> - worker 0: default search
> - worker 1: fixed search if defined, else pseudo cost search
> - worker 2: simplex off
> - worker 3: maximum linearization
> - worker 4: core based search

Or give me some reference to the mathematical/algorithm theory?

**Comment by lperron** [comment]
You are presuming much.

0 is a variation over vsids.
1 is fixed search if defined, or pseudo cost search from the MIP world
2 is like 0, but with the linearization off,
3 is like 0, but with a maximum linearization
4 is core based search from the sat world.
Actually there is one more called lp_branching.

You can look them up.

I would suggest you look at the code.
Thread specific parameters are defined in cp_model_search.cc, linearization
in the linear* files. Search is in integer_search and in optimization.

These are our theory. We use them because it seems to work.


Le ven. 24 mai 2019 à 19:37, gustavo-barros <notifications@github.com> a
écrit :
