### ISSUE TITLE
Export model in python

### ISSUE THREAD

**Issue by CaselIT** [google/or-tools#1264]
Up to version 7.0 to export a model in lp or mps format the following could be used
```py
slv = pywraplp.Solver('name', type )
# create model
slv.ExportModelAsMpsFormat(True, False)
slv.ExportModelAsLpFormat(False)
```

Version 7.1 no longer exports these two functions.
I've tried using the new `pywraplp.ExportModelAsLpFormat` or `pywraplp.ExportModelAsMpsFormat` using the following:
```py
pywraplp.ExportModelAsLpFormat(slv)
pywraplp.ExportModelAsMpsFormat(slv)
```
But I get a not implemented error. Both function seem to require an `MPModelProto`
What is the recommended way to use these new export functions or to export the model in version 7.1?
Thanks

**Comment by lperron** [comment]
options = pywraplp.ModelExportOptions()
model_as_string = solver.ExportModelAsLpFormat(options)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



*De : *Federico Caselli <notifications@github.com>
*Date : *ven. 10 mai 2019 à 12:32
*À : *google/or-tools
*Cc : *Subscribed

Up to version 7.0 to export a model in lp or mps format the following could

**Comment by CaselIT** [comment]
I get
`AttributeError: 'Solver' object has no attribute 'ExportModelAsLpFormat'`

**Comment by lperron** [comment]
Sorry we messed up. We forgot to add the compatibility layer for Python.
It is available in Java and C#.

I just pushed the fix to master.

Can you build from source while waiting for 7.2 (could take some time).

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



*De : *Federico Caselli <notifications@github.com>
*Date : *ven. 10 mai 2019 à 12:51
*À : *google/or-tools
*Cc : *Laurent Perron, Comment

I get

**Comment by CaselIT** [comment]
Thanks for fixing this

**Comment by JanaPerednia** [comment]
you haven't fixed it still, have you?

**Comment by CaselIT** [comment]
It's working fine for me with 9.3.10497

**Comment by lperron** [comment]
1) the tone is not nice. Please be careful.
2) do not revive 3 years old thread, especially when they are marked as
closed
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le ven. 5 août 2022 à 13:44, JanaPerednia ***@***.***> a
écrit :
