### ISSUE TITLE
Linker problems

### ISSUE THREAD

**Issue by cjolinla** [google/or-tools#1267]
I'm using Visual Studio 2017. I get the following errors when I try to run the code below:

E2512	the argument to a feature-test macro must be a simple identifier

LNK2019	unresolved external symbol "public: __cdecl operations_research::MPSolver::MPSolver(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum operations_research::MPSolver::OptimizationProblemType)" (??0MPSolver@operations_research@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4OptimizationProblemType@01@@Z) referenced in function "void __cdecl operations_research::RunTest(enum operations_research::MPSolver::OptimizationProblemType)" (?RunTest@operations_research@@YAXW4OptimizationProblemType@MPSolver@1@@Z)	

`#define USE_GLOP
#include "ortools/linear_solver/linear_solver.h"
#include "ortools/linear_solver/linear_solver.pb.h"

namespace operations_research {
	void RunTest(
		MPSolver::OptimizationProblemType optimization_problem_type) {
		MPSolver solver("Glop", optimization_problem_type);
		// Create the variables x and y.
		MPVariable* const x = solver.MakeNumVar(0.0, 1, "x");
		MPVariable* const y = solver.MakeNumVar(0.0, 2, "y");
		// Create the objective function, x + y.
		MPObjective* const objective = solver.MutableObjective();
		objective->SetCoefficient(x, 1);
		objective->SetCoefficient(y, 1);
		objective->SetMaximization();
		// Call the solver and display the results.
		solver.Solve();
		printf("\nSolution:");
		printf("\nx = %.1f", x->solution_value());
		printf("\ny = %.1f", y->solution_value());
	}

	void RunExample() {
		RunTest(MPSolver::GLOP_LINEAR_PROGRAMMING);
		//GLOP_LINEAR_PROGRAMMING
	}
}

int main(int argc, char** argv) {
	operations_research::RunExample();
	return 0;
}`

**Comment by lperron** [comment]
can you try running the C++ examples from the distribution ?

**Comment by cjolinla** [comment]
I am not sure what "running from the distribution" means?

**Comment by lperron** [comment]
If you download the binary archive,

you can cd into the or-tools directory and type

tools\make test_cc

Tell me if it works
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by cjolinla** [comment]
Oh yes I have done this when I installed or-tools following the instructions. It produces solutions for all the examples.

**Comment by lperron** [comment]
So look at the compilations and linking options, and replicate them in your
project

*De : *cjolinla <notifications@github.com>
*Date : *sam. 11 mai 2019 à 22:30
*À : *google/or-tools
*Cc : *Laurent Perron, Comment

Oh yes I have done this when I installed or-tools following the

**Comment by cjolinla** [comment]
Ok I will try this.

Thanks
