### ISSUE TITLE
path to cmake hardcoded in OS build instructions. 

### ISSUE THREAD

**Issue by mjfwest** [google/or-tools#127]
This will break for example if cmake is installed via homebrew when it will be located in:
`which cmake`
`/usr/local/bin/cmake`
The offending line is:
https://github.com/google/or-tools/blob/e3bfbac67694ca9fb9c94c7581369a5c563dd61e/makefiles/Makefile.unix#L221

**Comment by lperron** [comment]
Can you try with 
  CMAKE=/usr/local/bin/cmake make third_party
?

**Comment by mjfwest** [comment]
Do you mean like this?
``` bash
MacBook-Pro:or-tools username$ CMAKE=/usr/local/bin/cmake make third_party
cd dependencies/sources/gflags-2.1.2 && \
	/Applications/CMake.app/Contents/bin/cmake -D BUILD_SHARED_LIBS=ON \
		 -D BUILD_STATIC_LIBS=ON \
	         -D CMAKE_INSTALL_PREFIX=../../install \
		 -D CMAKE_CXX_FLAGS=-fPIC \
	         .
/bin/sh: /Applications/CMake.app/Contents/bin/cmake: No such file or directory
make: *** [dependencies/install/bin/gflags_completions.sh] Error 127
```
it still seems to look for the one in `/Applications/CMake.app/Contents/bin/cmake`

**Comment by lperron** [comment]
Can you try changing CMAKE =  into CMAKE ?=  in the Mac section of
makefiles/Makefile.unix ?
