### ISSUE TITLE
Combination of Disjunction and RemoveValue leads to no VRP solution

### ISSUE THREAD

**Issue by PierreHamoir** [google/or-tools#1272]
Hello,

I am trying to solve a VRP where some of the nodes (called NCP in the code) don't have to be all visited. I therefore use a disjunction :
```python
# Allow to drop nodes.
penalty = 1000
for node in NCP:
    routing.AddDisjunction([manager.NodeToIndex(node)], penalty)
```

On the other hand, I don't want two NCP nodes to be visited in a row, and I would like to use the RemoveValue function ; 
```python
for i in NCP:
    for j in NCP:       
        if routing.NextVar(i).Contains(j):
            routing.NextVar(i).RemoveValue(j)
```
The problem is that if a use both functions, the solver finds no solution.
I found out that it works if I only use the Remove.Value function on a few nodes that are (by luck) visited.

Any idea how to solve this issue ? 

Thanks a lot !

**Comment by lperron** [comment]
Don't remove values. Just make sure that the distance between two NCP nodes
is too large.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



*De : *PierreHamoir <notifications@github.com>
*Date : *lun. 13 mai 2019 à 11:55
*À : *google/or-tools
*Cc : *Subscribed

Hello,

**Comment by PierreHamoir** [comment]
Thank you for your answer @lperron, I have already tried it and it works. However, I was hoping that I could decrease the complexity with the RemoveValue function, do you know if it possible ?

**Comment by lperron** [comment]
I believe so, but remember to use the RoutingIndexManager to remove the
correct value from the domain.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



*De : *PierreHamoir <notifications@github.com>
*Date : *lun. 13 mai 2019 à 15:56
*À : *google/or-tools
*Cc : *Laurent Perron, Mention

Thank you for your answer @lperron <https://github.com/lperron>, I have

**Comment by GuyBenhaim** [comment]
Q:  Is such Node removal dynamic and takes place during running the solver, or just an administrative step before running the solver?

**Comment by PierreHamoir** [comment]
@GuyBenhaim it is done before running the solver
