### ISSUE TITLE
How to give a name to a node

### ISSUE THREAD

**Issue by anis-coding** [google/or-tools#1274]
Hello,

I have a problem, I need that several vehicles can pass by a given node, but I saw on previous issues that this is not possible, but there's a workaround where you would split the node to how many times you need a vehicle to pass by.

So I decided to use this workaround, for example Node A, require 3 vehicles to pass through it, so I need to create three node A1,A2,A3 (with the same distance data). I don't know if there's a way to attribute such labels to Nodes like A1,A2,A3,B1,B2,C1,C2,C3,C4... (so node A require 3 vehicles, B require 2 vehicles, and  C 4 vehicles)  

I'm using ortools with python

Thank you for the help

**Comment by lperron** [comment]
As answered on stackoverflow, this has nothing to do with or-tools. Use a
dict when modeling to store the relevant info.
Personally, I use named tuples (see the python jobshop examples).
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



*De : *Souames Annis <notifications@github.com>
*Date : *mar. 14 mai 2019 à 03:05
*À : *google/or-tools
*Cc : *Subscribed

Hello,
