### ISSUE TITLE
SequenceVar.ComputePossibleFirstAndLast missing in .NET since 7.0.6546

### ISSUE THREAD

**Issue by supermihi** [google/or-tools#1275]
The method `SequenceVar.ComputePossibleFirstAndLast` is not available in C# when using version 7.0.6546 and above of the ortools package. It was available until, including, 7.0.6510-beta.

Without that method, the sequence var is practically useless in custom decision builders. Is there a deeper reason for its removal, or was this by accident?

ref:
https://github.com/google/or-tools/blob/d7a33542a20cc60f2c55669e295c7cf8966e3467/ortools/constraint_solver/constraint_solver.h#L4535-L4538

**Comment by lperron** [comment]
I would say accident.
You should switch to CP-SAT though for scheduling.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



*De : *Michael Helmling <notifications@github.com>
*Date : *mar. 14 mai 2019 à 10:42
*À : *google/or-tools
*Cc : *Subscribed

The method SequenceVar.ComputePossibleFirstAndLast is not available in C#

**Comment by Mizux** [comment]
https://github.com/google/or-tools/blob/d7a33542a20cc60f2c55669e295c7cf8966e3467/ortools/constraint_solver/constraint_solver.h#L4535-L4538

**Comment by supermihi** [comment]
@Mizux thanks for the effort

@lperron I know, but migrating a large code base is not a trivial task. :-) Also, I have a lot of custom decision builders (and custom decisions), and could not find a method in the documentation on how to use them with CP-SAT - is it possible at all? Black-box search won't work for my problem.
