### ISSUE TITLE
[CP-SAT] Developing custom decision strategies (C++)

### ISSUE THREAD

**Issue by bendeguz-modli** [google/or-tools#1279]
Hi!

Is there any guide or example solutions about developing custom `VariableSelectionStrategies` or `DomainReducionStrategies`?

I want to implement domain specific heuristics to speed up the search. I imagine something like choosing variables in an order which depends on other variables (e.g. classrooms has a capacity and the scheduling of their id-s is in the order of decreasing capacity).

Thanks!

**Comment by lperron** [comment]
There are none :-) There are static strategies, and you can sort the
variables beforehand.
In general, using a black-box solver, I would solver sub-models in a
russian doll way, hinting the solution of the smaller doll when solving the
bigger doll.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



*De : *Bendegúz Módli <notifications@github.com>
*Date : *mer. 15 mai 2019 à 16:55
*À : *google/or-tools
*Cc : *Subscribed

Hi!

**Comment by bendeguz-modli** [comment]
Okay, thanks for the answer, I figure out something on the lines what you said.
