### ISSUE TITLE
No solution found though it exists, using synced intervals + cumulative constraints

### ISSUE THREAD

**Issue by supermihi** [google/or-tools#128]
I am facing a problem using or-tools for scheduling in the presence of synchronized intervals and cumulative constraints with variable demands. In my example (attached as python file: [cumulativeBug.zip](https://github.com/google/or-tools/files/61346/cumulativeBug.zip)) there are 2 tasks that are allowed to start between time 0 and 5. To each task, a "post task" is attached which starts at the respective task's end.

There are 2 resources available; each post task has a demand of 1 and can use any of the resources. I use binary indicator variables to model if task i uses resource j, and two cumulative constraints to model the "capacities" of 1 per resource. The objective minimizes the makespan.

Now, when I run this example, no solution is found, though both tasks could obviously start at 0 if their respective post tasks use different resources. However, when I change the upper bound on the starting time of both tasks from 5 to, say, 100, this solution is found. This sounds like a bug (because the same solution wolud also be feasible for the first model), or am I missing something fundamental here?

**Comment by supermihi** [comment]
Update: the bud seems to be located in the cumulative edge finder. If I compile the library with edge finding disabled, the solver works as expected.

**Comment by lperron** [comment]
Thanks. I will have a look.

**Comment by lperron** [comment]
Hi,

I am still debugging.
In the meantime, I rewrote the code in examples/tests/issue128.py (along
the original code)

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2015-12-15 15:34 GMT+01:00 Michael Helmling <notifications@github.com>:

**Comment by supermihi** [comment]
Okay, thanks a lot for taking care of this issue! BTW I think it would be good to turn the flags in resource.cc into solver parameters. Because I am using C# and/or Python, I needed to recompile the .NET assembly in order to turn off edge finding (the flags also didn't show up in python-gflas though *some* of the ortools-flags do ... is it because these aren't specified in any header files?).

Michael

**Comment by lperron** [comment]
I pushed the fix to github.

Thanks for the bug report.

**Comment by supermihi** [comment]
Thanks - however, I don't see the commit. :-) Did you perhaps forget to push?

**Comment by lperron** [comment]
Indeed :-(

Done

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2015-12-17 17:44 GMT+01:00 Michael Helmling <notifications@github.com>:

**Comment by supermihi** [comment]
:-) Thank you! By the way, I noticed that, in the test file, you have used an alternative modelling approach with optional interval copies (in test_v1). Is this a "better" (in terms of performance) way to model resources needed by tasks?

**Comment by lperron** [comment]
I prefer this approach, as it allows different copies to have different
start time, especially if you do not decide first hand to decide which
resource to use.
And the disjunctive constraint is much faster. So disjunctive with optional
is much better than cumulative with 0-1 demands.

--Laurent



Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2015-12-18 9:44 GMT+01:00 Michael Helmling <notifications@github.com>:

**Comment by supermihi** [comment]
Thanks for that hint - works like a charm! :)
