### ISSUE TITLE
Start nodes number is less than vehicle number

### ISSUE THREAD

**Issue by TeodoraB21** [google/or-tools#1282]
Hello!

Can I have something like, 10 vehicles and only 2 start nodes A and B? I mean every vehicle can start from A or B, it doesn't matter. (I know that I can set one start node for all the vehicles, or one start and one end point for each vehicle.)

**Comment by Mizux** [comment]
I would create a `C` node which is the merge of `A` and `B` taking the minimum distance so you can simulate a "start from A or B" then in the assignment knowing the next node after the vehicle start you can deduce if the vehicle should start form `A` or `B` i.e. the closest depot from the first visit...

**Comment by TeodoraB21** [comment]
By "the merge of A and B", you mean the middle of the segment AB?

**Comment by Mizux** [comment]
no  I mean in your "distance matrix" transit callback something like this pseudocode:
```cpp
int transit(int64 from_index, int64 to_index) {
 from_node = manager.IndexToNode(from_index);
 to_node = manager.IndexToNode(to_index);
 if (from_node == C_index)
   return std::min(data[A_index][to_index], data[B_index][to_index]);
else
  return data[from_index][to_index];
}
```

**Comment by TeodoraB21** [comment]
Oh. Now I understand, thank you very much :)

**Comment by TeodoraB21** [comment]
What do I do when I declare the RoutingIndexManager? I mean I have to set a vector with the same size as the number of vehicles. What do I do?

manager = operations_research::RoutingIndexManager(stopsSize, vehiclesSize, startNodes, startNodes);

vehiclesSize=10
startNodes.size()=2

**Comment by lperron** [comment]
you need to have 10 dummy nodes for the start node, and 10 for the second node.
Then tweak the distance matrix to have a 0 distance between the depot, and each dummy node.
Then reduce the domain of the vehicle var of each dummy node to be either -1 (not used), or its corresponding vehicle.
