### ISSUE TITLE
Writing your own constraint routine

### ISSUE THREAD

**Issue by cjolinla** [google/or-tools#1283]
I am wondering if or-tools allows its users to write their own constraints for CP-SAT solver. Preferably in C#.

I want to be able to write my own version of _all-different_ and more.

I know you can do this with IBM ILOG CPLEX in C++, but I want to migrate my work to or-tools.

Thanks

**Comment by lperron** [comment]
You cannot write a propagator.
Still, the language of constraints, especially with reified constraint is
very expressive.

For instance, the reservoir constraint has no propagator and is expanded
internally.
