### ISSUE TITLE
Can I create a dimension over all my vehicles?

### ISSUE THREAD

**Issue by EliasBA** [google/or-tools#1286]
Hello, I hope you can help me.
I am searching for a way to call the current CumulVar in my demandCallBack .
Or create an overallDimension.

I have a number of refuelStations which have each a maximum capacity.

My vehicles have a maximum capacity too, so I duplicated the refillStations and gave them a smaller capacity, depending on the divisor before.
For example
vehicle_a= 110liter; vehicle_b=150liter
refillStationOneCapacity = 1000liter;
refillStationTwoCapacity = 5000liter;
-> I duplicated the refillStationOne 99 times and thus I get 100 refillStationOne nodes each with a capacity of 10liters.
-> at nodes I leave my fuel (negative capacity). Each node has a certain amount of fuel spend on hit.
My problem occurs if I have nodes which might need 149liter and vehicle_b went over it one liter would be left, when I return to the refillstation, and I would love to refill it up to 150liter not just 149.
The best way to do that, is to have a constraint for the refillLocationCapacity I guess.

My thinking first was to create n (= two in my example above) originalCapacity-dimensions and n different callbacks-> when I am reaching refillNode x with a certain capacity.
My cumulVar in dimension One would rise if I reach a node which is a copy of refillStationOne and I will simply set a maximum fuelcapacity from 1000liter in that dimension.
But how would that work? How could I set a dimension not only depending on one vehicle instead depending on all of them. Since I could refuel with both vehicles on refillStationOne.
If this would work somehow, I could add extra refuelNodes which I can later drop, when I don't need them. refuelNodes with a size of the restOvers of fuel after visiting a node.
From my previous example 1liter for example.

-> this doesn#t work since the dimension are depending on the vehicles. Could I change that?
```cpp
//Add refillLocation constraint -> each originalLocation has a capacity which has to be overseen, //since more refuellNodes
// then actually exists might be created to avoid hard fuelCapacity constraints
   for(int i = 0;i< data.getRefuelLocationCapacityOriginal().size();i++){
        addDimensionsWith(data,
        routing,
        routing.registerUnaryTransitCallback((long fromIndex) -> {
// Convert from routing variable Index to user NodeIndex.
       int fromNode = manager.indexToNode(fromIndex);
       if(data.getRefuelLocations().contains(fromNode)) {
              return data.getNodeFuelDemands()[fromNode];
       }else return 0;
}),
i);
}*/
     // Allow to drop nodes
        long penalty = 99999999;//largePenalty
        System.out.println( data.getRefuelLocations().size());
        for (int i = 0; i < data.getTimeMatrix().length; ++i) {//refuelNodes -> all get DefaultPenalty
            if (data.getRefuelLocations().contains(i)) {
                routing.addDisjunction(new long[]{manager.nodeToIndex(i)}, penalty);
            }
        }
private static void addDimensionsWith(DataModel data, RoutingModel routing, int demandCallback, int i) {
      routing.addDimension (demandCallback, 0, // null capacity slack
     data.getRefuelLocationCapacityOriginal().get(i), // maximum capacity of refillStation
      true, // start cumul to zero
     "FuelStation"+i);
}
```
My other thinking was, if I could return the cumulVar during the callBack I could create a global CumulVar which I update each callBack to see what amount of fuel is already used from a refuelStation.

Kind regards,
Elias

**Comment by lperron** [comment]
I believe you can add a constraint on the sum of cumulvars of each vehicle
at their end of route to be less than a constant.
Then adding one dimension per refill node, with a special distance function
that just count the visit to that station.

my 2 cents
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by EliasBA** [comment]
> Then adding one dimension per refill node, with a special distance function
that just count the visit to that station.


 This  works!

>I believe you can add a constraint on the sum of cumulvars of each vehicle
at their end of route to be less than a constant.

This on the other hand I don't know how. Because my solver now just use this maximum refillAmount on each vehicle. And not over all of them. How could I add a constraint on the sum of the cumulVar of **all** vehicles?
Kind regards,
Elias

**Comment by lperron** [comment]
You can query the cumulvar for the end of all vehicles. Then add a global sum on those.
