### ISSUE TITLE
MakeCumulative

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1288]
Does applying this constraint slow things down substantially, as the solver needs to validate across all integer-domain values (?), or does it do it more efficiently?

Constraint* MakeCumulative(const std::vector<IntervalVar*>& intervals,
                             const std::vector<int64>& demands, int64 capacity,
                             const std::string& name);

**Comment by lperron** [comment]
I believe you are using this in the context of the routing library.

MakeCumulative is not efficiently treated by the local search, and will slow down the search.
Still, the constraint itself is quite efficient in its implementation, but order or magnitude slower than the usual treatment of routing constraints by the LS.

**Comment by GuyBenhaim** [comment]
Thx,
An example was provided in Developers: https://developers.google.com/optimization/routing/cvrptw_resources

When saying "order of magnitude slower" you mean it's independent of the domain span of the variable this constraint is applied to? 
E.g. for a total time of 4 hours, it will not be affected if time is in seconds or in hours?

Guy
