### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by karandeepakkanwar** [google/or-tools#1289]
I have been trying to import ortools 7.1.6720 but when I try to import : 
from ortools.constraint_solver import routing_enums_pb2, I keep getting the following error : 

ImportError                               Traceback (most recent call last)
<ipython-input-1-a787043fd149> in <module>
     22 from __future__ import print_function'''
     23 from ortools.constraint_solver import pywrapcp
---> 24 from ortools.constraint_solver import routing_enums_pb2

~\AppData\Roaming\Python\Python36\site-packages\ortools\constraint_solver\routing_enums_pb2.py in <module>
      5 import sys
      6 _b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
----> 7 from google.protobuf import descriptor as _descriptor
      8 from google.protobuf import message as _message
      9 from google.protobuf import reflection as _reflection

c:\users\kkanwar\appdata\roaming\python\python36\site-packages\google\protobuf\descriptor.py in <module>
     45   import binascii
     46   import os
---> 47   from google.protobuf.pyext import _message
     48   _USE_C_DESCRIPTORS = getattr(_message, '_USE_C_DESCRIPTORS', False)
     49 

ImportError: DLL load failed: The specified procedure could not be found.

I have been trying to get some documentation on this issue but I couldn't find anything. I have working on Windows 10 using Python 3.6.0

**Comment by Mizux** [comment]
which version of python protobuf do you have ?

**Comment by karandeepakkanwar** [comment]
I have protobuf 3.7.1. I had Python 3.6.6 on my base environment and then I made a seprate environment with Python verison 3.6.0 and it worked perfectly. I think there was Python version issue.
