### ISSUE TITLE
Cost/Distance Matrix

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1292]
Is it important to respond to callbacks with minimal latency, not to slow down the solver? 
Or, does the solver first cache all Node-combinations using callbacks, and then executes searches using its cache?

Naturally, we do not the cache-fill process to take too long, but if it's done once it should not be much of an issue ...

**Comment by lperron** [comment]
It uses a dynamic cache, not a full one.

**Comment by GuyBenhaim** [comment]
Thx.
Would any **relevant** NodeA-NodeB combination be fetched once, and remain in cache until a solution is found? or could there be re-fetches?

At least from what I've seen, the solver systematically iterates through all Node-index values and calls the NE2;  but maybe things change later...

**Comment by lperron** [comment]
The cache has a fixed size.

**Comment by GuyBenhaim** [comment]
So with large data sets there would be re-caching?

**Comment by GuyBenhaim** [comment]
Can I set the cache size such that the solver always runs from it?

**Comment by lperron** [comment]
// Parameters which have to be set when creating a RoutingModel.
message RoutingModelParameters {
  // Parameters to use in the underlying constraint solver.
  ConstraintSolverParameters solver_parameters = 1;
  // Advanced settings.
  // If set to true reduction of the underlying constraint model will be
  // attempted when all vehicles have exactly the same cost structure. This
can
  // result in significant speedups.
  bool reduce_vehicle_cost_model = 2;
  // Cache callback calls if the number of nodes in the model is less or
equal
  // to this value.
  int32 max_callback_cache_size = 3;
}
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
thx

**Comment by GuyBenhaim** [comment]
ReduceVehicleCostModel=true  seems to be the default setting. Using this (by default) with different vehicle costs did consider vehicle costs, and did not ignore/override the different costs. Makes sense?

For a model with 20 identical vehicles, toggling ReduceVehicleCostModel between true/false did not show a difference in calculation time. Makes sense?
 (actually, false was ~10% faster, but too few trials to really determine this).

**Comment by GuyBenhaim** [comment]
For increasing cache and a few tests, there is an improvement; maybe 25%.
Does the increased cache apply to all callbacks? or just for ArcCost?

**Comment by GuyBenhaim** [comment]
Can you pls, calrify

**Comment by GuyBenhaim** [comment]
Hello Laurent,
Can you please clarify whether the cache setting automatically applies to all callbacks used in the model or just for ArcCost callback?
Can it be applied selectively to certain callbacks?

**Comment by lperron** [comment]
Cache is per callback.
