### ISSUE TITLE
P & D 

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1294]
Hello,
If we use:
AddPickupAndDelivery(A_idx, B_idx) ;  AddPickupAndDelivery(B_idx, C_idx) ; 
Will the solver try to insert **all:  A, B, C**  Nodes at the same time, while checking all contraints at the same time?

Can we apply AddPickupAndDelivery(A_idx, B_idx)  but **not require** VehicleVar(A_idx) == VehicleVar(B_idx)  effectively requireing simultentous insertion **but for two seperate routes**?

**Comment by lperron** [comment]
AddPickupAndDelivery forces the vehicle vars to be equal.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
Is there a way to force simultaneously inserting tasks of different vehicles?
Is there a way to condition to mandate two tasks, which might use different vehicles, to be included or both to be skipped?

**Comment by GuyBenhaim** [comment]
Can you pls clarify?

**Comment by lperron** [comment]
1) duplicate nodes, force cumul variables to be equal.
2) extract active variables on the two nodes, force them to be equal
