### ISSUE TITLE
google/or-tools GUROBI

### ISSUE THREAD

**Issue by TornadoJo** [google/or-tools#1295]
compiling ortools with gurobi currently fails because of:
ortools\linear_solver\gurobi_interface.cc#178

with the following error:
cl /EHsc /MD /nologo -nologo  /D__WIN32__ /DPSAPI_VERSION=1 /DNOMINMAX /DWIN32_LEAN_AND_MEAN=1 /D_CRT_SECURE_NO_WARNINGS /O2 -DNDEBUG /I. /Iortools/gen /I"dependencies\\install\\include" /I"dependencies\\install\\include" /DGFLAGS_DLL_DECL= /DGFLAGS_DLL_DECLARE_FLAG= /DGFLAGS_DLL_DEFINE_FLAG= /I"dependencies\\install\\include" /DGOOGLE_GLOG_DLL_DECL= /I"dependencies\\install\\include" /I"dependencies\\install\\include" /I"dependencies\\install\\include\\coin" /I"dependencies\\install\\include" /I"dependencies\\install\\include\\coin" /I"dependencies\\install\\include" /I"dependencies\\install\\include\\coin" /DUSE_CLP /I"dependencies\\install\\include" /I"dependencies\\install\\include\\coin" /I"dependencies\\install\\include" /I"dependencies\\install\\include\\coin" /DUSE_CBC /DUSE_GLOP /DUSE_BOP   /I"C:\msys64\home\andreas\gurobi810\win64\include" /DUSE_GUROBI  -c .\\ortools\\linear_solver\\gurobi_interface.cc /Foobjs\\linear_solver\\gurobi_interface.obj
gurobi_interface.cc
.\\ortools\\linear_solver\\gurobi_interface.cc(178): error C2143: Syntaxfehler: Es fehlt ";" vor "*"
.\\ortools\\linear_solver\\gurobi_interface.cc(178): error C4430: Fehlender Typspezifizierer - int wird angenommen. Hinweis: "default-int" wird von C++ nicht unterstützt.
.\\ortools\\linear_solver\\gurobi_interface.cc(178): error C2238: Unerwartete(s) Token vor ";"
tools\make: *** [objs/linear_solver/gurobi_interface.obj] Error 2

first guess: could it be that this code/variable declaration line is not really needed?

I commented this line and so far everything works fine....

**Comment by lperron** [comment]
A mistake. Please comment the line.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by TornadoJo** [comment]
As I wrote before - have done so and it works .... just wanted to let u know!

**Comment by lperron** [comment]
I checked the line :-)

I pushed the fix on master.

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
