### ISSUE TITLE
Serializing current solver state in unreliable compute environment

### ISSUE THREAD

**Issue by danpat** [google/or-tools#1296]
I'd like to run some large VRP models for many hours in an unreliable compute environment (specifically AWS using Spot priced EC2 instances).

The issue, of course, is that the machine running the solver could be terminated at any time.  The probability of termination increases as the amount you pay per CPU second decreases.

Is it possible to serialize the current state of the CP solver at arbitrary points, then possibly deserialize and continue from that point?

I have seen the methods for serializing the model and assignments, but these don't seem to help capture search state at arbitrary points.

**Comment by lperron** [comment]
Don't do that.
Serialize the data used to build the model, and the best solution found so
far.
Then restart by rebuilding the model and feeding in the stored solution.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 21 mai 2019 à 00:25, Daniel Patterson <notifications@github.com> a
écrit :

**Comment by danpat** [comment]
@lperron Yes, that was my initial thought too, except what do you do in the case where no solution has been found yet?  In that case, from what I can see, there is no state available to continue computation from.
