### ISSUE TITLE
Nurse scheduling CpSolver stuck in some solutions

### ISSUE THREAD

**Issue by YLTsai0609** [google/or-tools#1300]
I'm implement a complex nurse scheduling problem. I want the nurse work a continuous shifts and match minimum nurses required in every shift. Struggling searching stackoverflow and github.

**specifically, the problem hit me is I got feasible but stuck solution like:**

Solution 0 
Day 0

Nurse 0 works from shift 0 to 3 

Nurse 1 works from shift 4 to 7

Solution 1 
Day 0

Nurse 0 works from shift 0 to 3 

Nurse 1 works from shift 4 to 7

**the cp_model.CpSolver just gave me the same solution 200 times.**

I want my solution is something like: 
Solution 0
 Day 0

Nurse 0 works from shift 0 to 3

 Nurse 1 works from shift 4 to 7

Solution 1 
Day 0

Nurse 0 works from shift 0 to 2 

Nurse 1 works from shift 3 to 7

Solution 2 
Day 0

Nurse 0 works from shift 5 to 7

 Nurse 1 works from shift 0 to 4

and more other feasible solutions.

I already take a look document about [cp_model](https://github.com/google/or-tools/blob/master/ortools/sat/python/cp_model.py) and [cp_model.CpSolver](https://github.com/google/or-tools/blob/master/ortools/sat/doc/reference.md) 

but none of above mentioned some choice when using CpSolver. 
I'm wondering is there some method I can choose when using CpSolver? 
Or anything I missed?
here is my code : 
```
from ortools.sat.python import cp_model
num_nurses = 2    
num_shifts = 8    
num_days = 1      
all_nurses = list(range(num_nurses))
all_shifts = list(range(num_shifts))
all_days = list(range(num_days))
start_shift = list(range(num_shifts))
end_shift = list(range(num_shifts))
RESEARCH_model = cp_model.CpModel()


# Creates shift variables.
RESEARCH_shifts = {}
for n in all_nurses:
    for d in all_days:
        for start in start_shift:
            for end in end_shift:
                RESEARCH_shifts[(n, d, start, end)] =\
                RESEARCH_model.NewBoolVar('shift_n{}d{}start{}end{}'.format(n, 
                d, start, end))

# constraint with minimum required nurse equal to 1
for d in all_days:
    for s in all_shifts:
        RESEARCH_model.Add(sum(RESEARCH_shifts[(n, d, start, end)] 
        for n in all_nurses
        for start in start_shift  for end in range(start , num_shifts ) 
        if start <= s <= end) == 1)

# the callback
class RESEARCH_NursesPartialSolutionPrinter(cp_model.CpSolverSolutionCallback):
    """Print intermediate solutions."""

    def __init__(self, shifts, num_nurses, num_days, num_shifts ,start_shift, end_shift, sols):
        cp_model.CpSolverSolutionCallback.__init__(self)
        self._shifts = shifts
        self._num_nurses = num_nurses
        self._num_days = num_days
        self._num_shifts = num_shifts
        self._solutions = set(sols)
        self._solution_count = 0
        self._start_shift = start_shift
        self._end_shift = end_shift

    def on_solution_callback(self):
        self._solution_count += 1
        if self._solution_count in self._solutions:
            print('Solution %i' % self._solution_count)
            for d in range(self._num_days):
                print(' Day {}'.format(d))
                for n in range(self._num_nurses):
                    for start in self._start_shift:
                        for end in range(start, self._num_shifts):
                            if self.Value(self._shifts[(n, d, start, end)]) == True:
                                print('  Nurse {} works from shift {} to {}'.format(n, start, end))

# create solver and solve it 

solver = cp_model.CpSolver()

# Display the first n solutions.
a_few_solutions = range(200)
RESEARCH_solution_printer = RESEARCH_NursesPartialSolutionPrinter(RESEARCH_shifts, 
                                                                  num_nurses, 
                                                                  num_days, 
                                                                  num_shifts, 
                                                                  start_shift, 
                                                                  end_shift,  
                                                                  a_few_solutions)


solver.parameters.max_time_in_seconds = 2.0
solver.SearchForAllSolutions(RESEARCH_model, RESEARCH_solution_printer)
                          
                               
```
Please help me out. thanks!

**Comment by lperron** [comment]
# Creates shift variables.
RESEARCH_shifts = {}
for n in all_nurses:
for d in all_days:
for start in start_shift:
for end in end_shift:
if end < start:
continue
RESEARCH_shifts[(n, d, start, end)] =\
RESEARCH_model.NewBoolVar('shift_n{}d{}start{}end{}'.format(n,
d, start, end))

You are creating a lot of Boolean variables that are not linked to any
constraints (shifts with end < start).
Enumerating all solutions will explore all combinations of these
unconstrained variables.

I added the 2 lines with the continue above. Now all solutions are different
Solution 1
 Day 0
  Nurse 0 works from shift 0 to 7
Solution 2
 Day 0
  Nurse 0 works from shift 0 to 1
  Nurse 0 works from shift 2 to 7
Solution 3
 Day 0
  Nurse 0 works from shift 0 to 2
  Nurse 0 works from shift 3 to 7
Solution 4
 Day 0
  Nurse 0 works from shift 1 to 2
  Nurse 0 works from shift 3 to 7
  Nurse 1 works from shift 0 to 0
Solution 5
 Day 0
  Nurse 0 works from shift 2 to 7
  Nurse 1 works from shift 0 to 1
Solution 6
 Day 0
  Nurse 0 works from shift 1 to 2
  Nurse 0 works from shift 3 to 5
  Nurse 0 works from shift 6 to 7
  Nurse 1 works from shift 0 to 0
Solution 7
 Day 0
  Nurse 0 works from shift 1 to 2
  Nurse 0 works from shift 3 to 5
  Nurse 1 works from shift 0 to 0
  Nurse 1 works from shift 6 to 6
  Nurse 1 works from shift 7 to 7
Solution 8
 Day 0
  Nurse 0 works from shift 1 to 2
  Nurse 0 works from shift 3 to 5
  Nurse 0 works from shift 6 to 6
  Nurse 1 works from shift 0 to 0
  Nurse 1 works from shift 7 to 7

I do believe that in your model, you should add a constraint saying that a
nurse can only do 1 shift in a day, sor something to forbid:
  Nurse 0 works from shift 1 to 2
  Nurse 0 works from shift 3 to 7



Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 23 mai 2019 à 09:27, Yu-Long Tsai <notifications@github.com> a
écrit :

**Comment by YLTsai0609** [comment]
Thanks a lot, problem solved!
However, I just wondered why the CpSolver did that?
Is there any explanation on document or would you mind to share it, please?
thanks again.

**Comment by lperron** [comment]
The solver does nothing wrong. 
Let's take a small model x between 0 and 10, b Boolean. You enumerate all solutions, but only display x in the callback. Each value of w will be displayed twice.

**Comment by YLTsai0609** [comment]
Maybe I'm lack of imagination. Could you describe more specifically?

**Comment by lperron** [comment]
from __future__ import absolute_import
    from __future__ import division
    from __future__ import print_function

    from ortools.sat.python import cp_model


    class VarArraySolutionPrinter(cp_model.CpSolverSolutionCallback):
        """Print intermediate solutions."""

        def __init__(self, variables):
            cp_model.CpSolverSolutionCallback.__init__(self)
            self.__variables = variables
            self.__solution_count = 0

        def on_solution_callback(self):
            self.__solution_count += 1
            for v in self.__variables:
                print('%s=%i' % (v, self.Value(v)), end=' ')
            print()

        def solution_count(self):
            return self.__solution_count


    def DuplicateEnumerate():
        model = cp_model.CpModel()
        x = model.NewIntVar(0, 10, 'x')
        b = model.NewBoolVar('b')
        solver = cp_model.CpSolver()
        solution_printer = VarArraySolutionPrinter([x])
        status = solver.SearchForAllSolutions(model, solution_printer)


    DuplicateEnumerate()

outputs

    x=0 
    x=1 
    x=2 
    x=3 
    x=4 
    x=5 
    x=6 
    x=7 
    x=8 
    x=9 
    x=10 
    x=10 
    x=9 
    x=8 
    x=7 
    x=6 
    x=5 
    x=4 
    x=3 
    x=2 
    x=1 
    x=0

**Comment by pointer** [comment]
Hi There,
Any idea on how to add new constraint like **location** or **site** to the nurse problem?? Thanks in advance

**Comment by lperron** [comment]
Start by writing down the semantic of the constraint.  Then introduce the
right Boolean variables, and the relevant constraints that implement the
semantic of it.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 5 oct. 2020 à 17:34, Kateb Ghemari <notifications@github.com> a
écrit :

**Comment by pointer** [comment]
Hi 
i did it like this

```
    num_nurses = 30
    num_shifts = 3
    num_days = 7
    num_pcr_test_stands = 4
    all_nurses = range(num_nurses)
    all_shifts = range(num_shifts)
    all_days = range(num_days)
    all_pcr_test_stands = range(num_pcr_test_stands)
```
    # Creates the model.
`    model = cp_model.CpModel()`
    # Create the variables
    # The following code an array of variables for the problem.
    # shifts[(n, d, s, l)]: nurse 'n' works shift 's' on day 'd' at pcr test stand l.    
```
    shifts = {}
    for n in all_nurses:
        for d in all_days:
            for s in all_shifts:
                for l in all_pcr_test_stands:                
                    shifts[(n, d, s, l)] = model.NewBoolVar('shift_n%id%is%il%i' % (n, d, s, l))
```
And i get the following output...

> Statistics
>   - conflicts       : 26
>   - branches        : 5079
>   - wall time       : 0.063825 s
>   - solutions found : 0

**Comment by lperron** [comment]
Just an empty model with no constraints ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 7 oct. 2020 à 09:26, Kateb Ghemari <notifications@github.com> a
écrit :

**Comment by pointer** [comment]
Here they are....thanks

   # Assign nurses to shifts
    # Next, we show how to assign nurses to shifts subject to the following constraints:
        # Each shift is assigned to a single nurse per day.
        # Each nurse works at most one shift per day.
    # Here's the code that creates the first condition.

```
    for d in all_days:
            for s in all_shifts:
                for l in all_pcr_test_stands:                
                    model.Add(sum(shifts[(n, d, s, l)] for n in all_nurses) == 1)     
```                           

# The last line says that for each shift, the sum of the nurses assigned to that shift is 1.

# Next, here's the code that requires that each nurse works at most one shift per day.

```
    for n in all_nurses:
            for d in all_days:
                for l in all_pcr_test_stands:
                    model.Add(sum(shifts[(n, d, s, l)] for s in all_shifts) <= 1)               
```        

# For each nurse, the sum of shifts assigned to that nurse is at most 1 ("at most" because a nurse might have the day off).

# Next, here's the code that requires that each nurse works at one pcr_test_stand per shift per day.

```
    for n in all_nurses:
            for d in all_days:
                for s in all_shifts:                
                    model.Add(sum(shifts[(n, d, s, l)] for l in all_pcr_test_stands) == 1)
```

# Assign shifts evenly
    # Next, we show how to assign shifts to nurses as evenly as possible. 
    # Since there are nine shifts over the three-day period, we can assign two shifts to each of the four nurses. 
    # After that there will be one shift left over, which can be assigned to any nurse.
    
# The following code ensures that each nurse works at least two shifts in the three-day period.
    # min_shifts_per_nurse is the largest integer such that every nurse can be assigned at least that many shifts. 
    # If the number of nurses doesn't divide the total number of shifts over the schedule period,
    # some nurses have to work one more shift, for a total of min_shifts_per_nurse + 1.

```
    min_shifts_per_nurse = (num_shifts * num_days) // num_nurses
    max_shifts_per_nurse = min_shifts_per_nurse + 1
    for l in all_pcr_test_stands:
        for n in all_nurses:
            num_shifts_worked = sum(shifts[(n, d, s, l)] for d in all_days for s in all_shifts)
            model.Add(min_shifts_per_nurse <= num_shifts_worked)
            model.Add(num_shifts_worked <= max_shifts_per_nurse)
```

**Comment by Mizux** [comment]
Do you really need a pcr "l" variable in the tuple ? I mean, it seems you only want to have at max 4 "nurses" each day each shift.
i.e. having some constraints (sum(...) <= num_pcr_test_stands)
unless you have some constraints on the stand itself ?

**Comment by pointer** [comment]
the number 4 nurses is just for testing  ...there can be much more nurses....

**Comment by Mizux** [comment]
La contrainte trois ne doit pas être une égalité,
>  model.Add(sum(shifts[(n, d, s, l)] for l in all_pcr_test_stands) == 1)

si la nurse ne travail pas durant ce shift la somme est nul...

**Comment by Mizux** [comment]
for constraint (2), isn't this instead ?
```python
for n in all_nurses:
    for d in all_days:
        model.Add(sum(shifts[(n, d, s, l)] for s in all_shifts for l in all_pcr_test_stands) <= 1)   
```

**Comment by pointer** [comment]
Mercis....je vais l'essayer....and revert....
