### ISSUE TITLE
Mapping an Interval to an Array of Booleans

### ISSUE THREAD

**Issue by white54503** [google/or-tools#1304]
I'm working with the new SAT solver to do some scheduling.  I have a question about mapping out an array of booleans according to some variable start / stop indices.  My question is:

Given an array of boolean variables _X_ and any two integer variables _I < len(X)_, how can I set the truth values of _X_ such that _x[i] == True_ if _I1 <= x[i] <= I2_...?  For example:

```
X = [model.NewBoolVar("boolean %d" % i) for i in range(10)]
i1 = model.NewIntVar(0, 10, "i1")
i2 = model.NewIntVar(0, 10, "i2")
model.Add(i2 > i1)
model.Add(i1 == 2)
model.Add(i2 == 6)
...
Out: [0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0]
```

I think I can reason out some convoluted approaches, but as a new user of the library I feel like I'm missing something simple. I'd appreciate any help.  Thanks.

**Comment by lperron** [comment]
Please have a look at https://github.com/google/or-tools/blob/master/ortools/sat/doc/channeling.md

**Comment by DragonGawain** [comment]
The link that Iperron posted no longer works. In particular, doc should be docs. For those in the future looking at this, here's an updated link:
https://github.com/google/or-tools/blob/master/ortools/sat/docs/channeling.md
