### ISSUE TITLE
CVRPTW special capacity constraints on nodes

### ISSUE THREAD

**Issue by tiggr09** [google/or-tools#1306]
I am working on a VRP project where I have trucks picking up produce from farms. These trucks have a base weight along with a capacity for the produce they are picking up.
Some of the farms cannot be accessed if the trucks are too heavy as the routes will have bridges with weight limits.
I was wondering if there was a way to achieve this as I have not come across any examples or documentation of constraints being applied to the nodes.

An example of what I want to achieve
Farm 1 has no weight limit and 5units of produce
Farm 2 has no weight limit and 3units of produce
Farm 3 has a weight limit of 7units and 1unit of produce.
The base weight of the truck is 2unit and it has capacity of 15units.

At the start, the truck would be able to go to any farm.
But if it goes to farm 1 first, it will no longer be able to service farm 3 as it will weigh 2units+5units(from farm 1) = 7 units which is equivalent to the weight limit to access farm 3 so the truck would not be able to get to the farm because of the bridge.

**Comment by Mizux** [comment]
did you try to add a constraint on the CumulVar of node Farm 3 ?

**Comment by jmarca** [comment]
Maybe something like (pseudo python):

```python
# assume a magical farm object, with node, pickup and weight_limit properties...
for farm in farms:
    farm_index = manager.NodeToIndex(farm.node)
    farm_incoming_limit = farm.weight_limit - farm.pickup
    routing.solver().Add(produce_dimension.CumulVar(farm_index) <= farm_incoming_limit) 
```
