### ISSUE TITLE
Update documentation to use v7.1 CP-SAT api

### ISSUE THREAD

**Issue by brycearden** [google/or-tools#1307]
As of [v7.1](https://github.com/google/or-tools/releases/tag/v7.1) the `Solve` methods and its variations now take a `CpModelProto` as input. These changes should be reflected in the documentation / examples found here:

https://developers.google.com/optimization/cp/cp_solver

**Comment by lperron** [comment]
Thanks

**Comment by paultrow** [comment]
Republished doc.
