### ISSUE TITLE
Help needed: setting limits to consecutive work time

### ISSUE THREAD

**Issue by erma07** [google/or-tools#1309]
I have tried to implement a schedule based on the CP-SAT solver and intervals but I need some help to implement the following constraints:
1) Workers have to take as much consecutive non overlapping tasks as possible
2) Each worker has 1 dynamic shift defined by the recurring job plan limited by up to x hours of working time in 24 hours and up to y hours in z days
3) There has to be at least x hours of rest time between shifts

**Comment by Mizux** [comment]
https://github.com/google/or-tools/blob/master/examples/python/bus_driver_scheduling_sat.py may help you for few constraints IMHO

**Comment by erma07** [comment]
You are quite right I have to look into it. bus_driver_scheduling_sat.py has an error:  AttributeError: module 'ortools.sat.python.cp_model' has no attribute 'LinearExpr'.

**Comment by lperron** [comment]
Are you using 7.1 ?
I forgot if I have added this API before or after 7.1.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by erma07** [comment]
I am using 7.1

python -m pip install --upgrade --user ortools
Requirement already up-to-date: ortools in python3.7/site-packages (7.1.6720)
Requirement already satisfied, skipping upgrade: protobuf>=3.7.1 in python3.7/site-packages (from ortools) (3.7.1)
Requirement already satisfied, skipping upgrade: six>=1.10 in /anaconda3/lib/python3.7/site-packages (from ortools) (1.12.0)
Requirement already satisfied, skipping upgrade: setuptools in /anaconda3/lib/python3.7/site-packages (from protobuf>=3.7.1->ortools) (40.8.0)

**Comment by lperron** [comment]
Ok, use sum() instead of cp_model.LinearExpr.Sum()
use sum(vars[i] * coeffs[i]) instead of cp_model.LinearExpr.ScalProd(vars,
coeffs)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by erma07** [comment]
You mean like model.Minimize(sum(delay_weights[j]*delay_literals[j] for j in range(len(delay_weights))))?
