### ISSUE TITLE
Arbitrary start time

### ISSUE THREAD

**Issue by TeodoraB21** [google/or-tools#1310]
Hello! I have an example with 10 vehicles and only 2 start times, how can I set the algorithm to arbitrarily choose witch start time should be set to each vehicle?

**Comment by lperron** [comment]
Create dummy optional visits with a fixed schedule that must be visited
first ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by TeodoraB21** [comment]
I don't know how to do that. Can you please explain me a little bit more?

**Comment by jmarca** [comment]
I for one don't understand your question...can you please explain your problem a little bit more?

**Comment by TeodoraB21** [comment]
Well if I have 2 start times: 1000 and 1500, and 10 vehicles, and I want the algorithm to decide which start time is the best for each vehicle.
Like for example, vehicle 1,3,5 to start at time 1000 and the rest at 1500.

**Comment by jmarca** [comment]
Are there any other restrictions?  Can all the veh start at one time or the other, if that is best?  

You can set up N dummy nodes for each vehicle, one for each potential start time. Each dummy node has a fixed time window that forces the vehicle to hit the designated time, say arrive at t-1, depart at t. Only depot can get to dummy nodes with zero travel time, and dummy nodes can get to all other nodes with depot to node travel time. 

For each set of dummy nodes set two constraints

First require the vehicle in question serve the nodes. 

Second set a disjunction across all the nodes in the vehicle’s set such that only one can be active. 

You also might be able to require that vehicle start time is equal only to the set of start times, but that can be fiddly, depending on slack etc at the depot. 

James
