### ISSUE TITLE
CP-SAT LNS threads

### ISSUE THREAD

**Issue by poroale** [google/or-tools#1314]
I'm using the CP-SAT solver with the following parameter settings:
```
solver = cp_model.CpSolver()
solver.parameters.use_lns = True
solver.parameters.lns_num_threads = 4
```
But when I'm viewing the processes from htop I can only see one thread in use. How should the parallelization be done?

**Comment by marbuttner** [comment]
There is an additional setting `num_search_workers` (https://github.com/google/or-tools/blob/stable/ortools/sat/sat_parameters.proto#L649), but I don't know whether it is required for LNS.

**Comment by lperron** [comment]
1) LNS only works with optimization models.
2) num_search_workers uses the first 6 workers with different search parameters, and assign additional workers to LNS.
3) Prefer num_search_workers over lns_threads.

**Comment by poroale** [comment]
I have an optimization model, but the lns_threads do not seem to have an effect.

Is it expected that if I set num_search_workers > 1 and use_lns = True, then nothings seems to happen. When viewing from htop the process is not using the cpu at all, but the process is still running.

**Comment by lperron** [comment]
1) You should use num_search_workers=4 (8 is better)
2) It currently launches the LNS threads once a solution has been found.

**Comment by poroale** [comment]
But having num_search_workers = 4 and use_lns = True does not seem to work. The process is not doing anything, not using any resources nor finding solutions. Running the same without lns works fine.

**Comment by lperron** [comment]
use_lns is ignored if num_search_workers > 1
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Or it should :-)

Just do not use use_lns.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by poroale** [comment]
Yeah not using lns is a quick fix. :D

Should this issue remain open if there's a bug with num_search_workers > 1 and lns, namely the one that the process seems to do nothing?

**Comment by lperron** [comment]
Yes, we will fix it.
Or document not to use use_lns :-)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by kangjieHong** [comment]
when I set num_search_workers=16. I found 
`*** starting parallel search at 1.50s with 16 workers: [ auto, lp_br, pseudo_cost, no_lp, max_lp, quick_restart, lns_1, lns_2, lns_3, lns_4, lns_5, lns_6, lns_7, lns_8, lns_9, lns_10 ]
`
 how can i improve the speed by add more workers with different search parameters?

**Comment by lperron** [comment]
If you are using the binary, you can't. We control how to diversify search
parameters.

If you compile from source, you can experiment with the function
DiversifySearchParameters in ortools/sat/cp_model_search.cc

This being said, the best option is to decompose the problem, or create
independent sub-problems by exploring different options, and then run those
in parallel.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 12 juil. 2019 à 03:48, kangjieHong <notifications@github.com> a
écrit :
