### ISSUE TITLE
Initialize Value for Load/Demand dimension

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1315]
Is there a way to **directly initialize** (i.e. force) the value of Capacity, to a certain value, on the start node or the first node?

**Comment by lperron** [comment]
?? Which solver? I guess routing. But it is not clear.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
Routing library with CP Solver. Refers to a cumulvar that represents a Dimension

**Comment by jmarca** [comment]
Isn't capacity a property of a vehicle, not a cumulvar of a dimension?

**Comment by GuyBenhaim** [comment]
Sorry for vague phrasing, I meant the staring value of the vehicle's load. Is this possible?

**Comment by GuyBenhaim** [comment]
Any conclusion possible? impossible?

**Comment by Mizux** [comment]
did you try to add a constraint on the capaticy dimension the cumulVar of the vehicle start node ? this should force the solver to set the value to the desired value IMHO

**Comment by GuyBenhaim** [comment]
Thx @Mizux, I will check.
