### ISSUE TITLE
How to feed LP files to the GLOP solver of or-tools?

### ISSUE THREAD

**Issue by hklarner** [google/or-tools#1317]
Sorry if you already saw this on [stackoverflow](https://stackoverflow.com/questions/56395430/how-to-feed-lp-files-to-the-glop-solver-of-or-tools). I am not sure where to post.

I would like to use or-tools and the [GLOP](https://developers.google.com/optimization/lp/glop) solver to solve linear programming problems.

I already have another program that creates [LP files](http://lpsolve.sourceforge.net/5.0/CPLEX-format.htm) which are, as far as I know, fairly standard for defining linear programs.

Has anyone managed to pass those files directly to GLOP? What file format das GLOP understand and how do I pass them to GLOP?

Example lp file:
```
maximize 2x1 + 3x2 - x3
subject to
 x1 + x2 <= 1
 x1 + x2 + x3 <= 0
 x2 - 2x3 <= 2
bounds
 x1 free
 x2 free
 x3 free
end
```

* I am looking for a Java solution
* `LoadLinearProgramFromModelOrRequest` seems to be the way. See [here](https://developers.google.com/optimization/reference/lp_data/model_reader/). I don't know how to use it

**Comment by lperron** [comment]
Answered by the negative on SO.

https://stackoverflow.com/questions/56395430/how-to-feed-lp-files-to-the-glop-solver-of-or-tools/56396478#56396478
