### ISSUE TITLE
How to make multiple depot with same start being the end ? 

### ISSUE THREAD

**Issue by anis-coding** [google/or-tools#1318]
I have a vrp problem where I need to have several depots, but if a vehicle start at that depot, the route must end at that depot, for example: if 1, 2 are depot then the route 1->4->5->1 is allowed but 1->4->5->2 is not allowed.

In order to achieve this with 450 vehicle available and 3 depots I used the following piece of code in create_data_model function

```
    l = []
    for i in range(150):
        for j in range(3):
            l.append(j)
    data["starts"] = l
    data["ends"] = l 
```

So the list l contains 0,1,2 repeated 150 times so it has 450 entry (a start and end for each vehicle) , then I assigned l to both starts and ends so for a vehicle v, it will have the same start and end.

This gives the same start and end for most vehicle but for some unused vehicles in the solution (unused vehicles so should be 0->0, or 1->1 or 2->2) it returns 1->2 which is not allowed.

How can I achieve that each vehicle should have the same start and end (if vehicle 1 starts at 2 then it must end at 2) ?

**Comment by jmarca** [comment]
You show how you are generating data["starts"] and data["ends"], but you haven't said how are you telling the solver about starts and ends of vehicle routes.  Can you explain that part too?

**Comment by lperron** [comment]
See: https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/doc/VRP.md#multiple-starts-ends
