### ISSUE TITLE
CoinError Uncaught Exception in Java

### ISSUE THREAD

**Issue by loehndorf** [google/or-tools#132]
The following code throws error 'terminating with uncaught exception of type CoinError' in Java. 
```
MPSolver solver = new MPSolver("CoinError",MPSolver.OptimizationProblemType.CLP_LINEAR_PROGRAMMING);
double infinity = MPSolver.infinity();
MPVariable x0 = solver.makeNumVar(0.0, 1.0, "x0");
MPVariable x1 = solver.makeNumVar(0.0, 0.3, "x1");
MPVariable x2 = solver.makeNumVar(0.0, 0.3, "x2");
MPVariable x3 = solver.makeNumVar(-infinity, infinity, "x3");

MPObjective obj = solver.objective();
obj.setCoefficient(x1, 2.655523);
obj.setCoefficient(x2, -2.70917);
obj.setCoefficient(x3,1);
obj.setMaximization();

MPConstraint c0 = solver.makeConstraint(-infinity, 0.302499);
c0.setCoefficient(x3, 1);
c0.setCoefficient(x0, -3.484345);

MPConstraint c1 = solver.makeConstraint(-infinity, 0.507194);
c1.setCoefficient(x3, 1);
c1.setCoefficient(x0, -3.074807);

MPConstraint c2 = solver.makeConstraint(0.594, 0.594);
c2.setCoefficient(x0, 1);
c2.setCoefficient(x1, 1.01);
c2.setCoefficient(x2, -0.99);

System.out.println("Number of variables = " + solver.numVariables());
System.out.println("Number of constraints = " + solver.numConstraints());

solver.enableOutput();
System.out.println(solver.exportModelAsLpFormat(false));
System.out.println(solver.solve());
```

**Comment by lperron** [comment]
This is a Clp bug.

I suggest you switch to our own linear solver (GLOP_LINEAR_PROGRAMMING) while I send this bug report to the coin team.

Thanks

**Comment by loehndorf** [comment]
Even if it's a bug in CLP, it would be good, if I could catche the exception in Java. Is that possible?

**Comment by lperron** [comment]
Yes, I will wrap the Solve() method.

--Laurent

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2015-12-18 10:12 GMT+01:00 loehndorf <notifications@github.com>:

**Comment by lperron** [comment]
I have fixed the issue. Solve() will return with an ABNORMAL status.
I sent the problem to John Forrest. He fixed it in the source. Hopefully, it will be available in the next stable release.

Thanks again for the bug report.
