### ISSUE TITLE
Limit number of districts touched by each vehicle in VRP - Solved

### ISSUE THREAD

**Issue by madolmo** [google/or-tools#1320]
Need help:

I have to solve a simple VRP on a city with multiple districts and I want to limit the maximum number of ditricts touched by each vehicle/route.

Orders=[(x1,y1),(x2,y1),(x3,y3)...(xN,yN)] # each order is identified by its coordinates

Districts=[1,2,3] # only 3 districts for simplicity

Order_district=[2,3,2,...1] # orders belong to one of three districts

My first thought was to add a penalty for each "touched district", but it's hard for me to define a correct Disjunction.

Another option would be to define a dimension based on the length of the Set of touched districts (ie the number of distinct district the route touches), but again how to define such a Dimension?

Then I realized that it must be a hard constraint and tried with the following:

`

traversed_zones=[]

for v in all_vehicles:

	traversed_zones.append([[]]*len(all_zones))

	for p in all_points:

		z=zones[p]

		traversed_zones[v][z].append(model.VehicleVar(manager.NodeToIndex(p))==v) #True if the vehicle v serves the point p

	# sum 1 for all zones with at least one point served by the vehicle v

	solver.AddConstraint( solver.Sum(1 for z in traversed_zones[v] if solver.Sum(z)>0) < 3)

`

but running it I get no solution.
I tried a lot of variation of this approach but with no success

Any help or usefull example of using such a derived constraint?
Thank you all!

**Comment by lperron** [comment]
There was already a discussion on this subject.
I have no good answers.

You could imagine a distance matrix that is mostly 0, except on arcs
crossing districts.
Then setting a maximum on the associated dimension is a proxy for this.
Especially if the limite is strong.

limit of 0 + 0 distance from depot to any district -> forces you to stay in
1 district
limit of 1 -> you can cross 1, but you cannot come back to your first
district visited
limit of 2 -> one back and forth between 2 districts, or 3 districts
visited.

I have no better ideas that fit nicely in the framework.

If the problem is small (less than 30-40 visits), we can try to solve it
with the CP-SAT solver. But it will be slower than the routing library.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by madolmo** [comment]
Thank you for your immediate reply :)
I got it to work in the way you suggest adding a dimension that cumuls the district crossed between first and last service point (the depot's district doesn't matter), but it's slightly different, in this way the vehicles can't do more crossing between the same 2 zones and this could lead to a bad optimization in strange cases when the service points are located along the borders.
I really would like to use the constraint the way I designed it or at least understand why it doesn't work! :)

**Comment by madolmo** [comment]
Maybe it's worth mentioning that my sample problem does have solutions with all vehicles touching less then 3 districts

**Comment by madolmo** [comment]
I think I did a little step forward, now I can see the constraint I would expect but it's still not working.

`    traversed_zones=[]
    limit=3
    for v in all_vehicles:
                              
        traversed_zones.append([[]]*len(all_zones))
        for p in all_points:
            z=zones[p]
            traversed_zones[v][z].append((model.VehicleVar(p)==model.VehicleVar(model.Start(v))))

        #sum(max([True if this vehicle serves a point in this zone])) -> counts the served zones
        constraint=(solver.Sum(solver.Max(z) for z in traversed_zones[v])<=limit )

        print(constraint.DebugString())

        solver.AddConstraint(constraint)`

When I run it this is the output:

`(BooleanSum([, , , ])(0..4) <= 3)` 

Which is exactly what I want, but no solutions!    
   
If I run it with a limit of 4 (the total number of zones in this sample) the output changes in:

`TrueConstraint()`

(And I think this was another confirm that I'm writing the correct constraint because (0..4)<=4 and the solver semplifies it!)

and in this case I get the solution with 2 to 3 zones touched by each vehicle!

I'm going crazy!

**Comment by madolmo** [comment]
I found my error.
It was a stupid bug in the way my collection was initialized!
I'm reporting it here just in case anyone was interested in (one) correct solution of the problem:

```
        traversed_zones={}
        for v in all_vehicles:                           
            traversed_zones[v]={}
            for p in all_points:
                if p>=data['cluster_depots']: # depot's zone doesn't matter
                    z=data['cluster_zones'][p]
                    zone_list=traversed_zones[v].get(z,None)
                    if zone_list==None:
                        zone_list=[]
                        traversed_zones[v][z]=zone_list
                    # vehicle(p)==v -> v serves p in zone z
                    zone_list.append(model.VehicleVar(manager.NodeToIndex(p))==v)

            #sum(max([True for p in points of zone z if vehicle v serves p])) -> counts the served zones
            constraint=(solver.Sum(solver.Max(z) for z in traversed_zones[v].values())<=conf['zones_limit'])
            solver.AddConstraint(constraint)`
