### ISSUE TITLE
PDP with capacity

### ISSUE THREAD

**Issue by TeodoraB21** [google/or-tools#1322]
Hello!

I have pickup and delivery with capacity example, and at the end of the route the vehicle has all the capacity collected, it didn't dropped the capacity at each drop-off location. How do I set it to drop-off the capacity collected?

stops: 8
vehciles: 1
capacities: 1 2 1 0 2 3 4 6 1
start point: 0
end point: 3
pickup-delivery:
   0 1
   1 2
   4 3
   2 3
   5 7

I made this settings for every pickup-delivery pair:
```
operations_research::RoutingIndexManager::NodeIndex pickupNode = manager->IndexToNode(m_vPickups[i]);
operations_research::RoutingIndexManager::NodeIndex deliveryNode = manager->IndexToNode(m_vDeliveries[i]);
int64 pickup_index = manager->NodeToIndex(pickupNode);
int64 delivery_index = manager->NodeToIndex(deliveryNode);
routing.AddPickupAndDelivery(pickup_index, delivery_index);
solver->AddConstraint(solver->MakeEquality(routing.VehicleVar(pickup_index), routing.VehicleVar(delivery_index)));
solver->AddConstraint(solver->MakeLessOrEqual(distanceDimension.CumulVar(pickup_index), distanceDimension.CumulVar(delivery_index)));
solver->AddConstraint(solver->MakeLessOrEqual(timeDimension.CumulVar(pickup_index), timeDimension.CumulVar(delivery_index)));
```

**Comment by jmarca** [comment]
Hard to understand what is going on from what you've posted.  

What does your list "capacities" mean if you only have 1 vehicle?  If you mean that this is the demand/supply at each node, then why are there 9 entries but only 8 stops?

What do you mean by pickup-delivery list? If you mean there is a pickup at 0, delivery at 1, then a pickup at 1, delivery at 2, then that is very confusing, as nodes can only be visited at most once.  

Also, you don't need to specify that both the distance dimension and the time dimension have MakeLessOrEqual constraints---one of them should work all by itself, adding both probably just gives the solver more busy work.

Can you post your complete program?

**Comment by TeodoraB21** [comment]
Sorry, there are 9 stops, my mistake.
The capacities, are the demands.
The vehicle picks the demand from stop 0 and delivers it at stop 1, and at stop 1 also it picks a different demand that will be delivered at stop 2, so stop 1 won't be visited twice.

**Comment by jmarca** [comment]
You should renumber your nodes to have no repeats. Easy enough after the fact to re-translate 1 and 8 to both mean 1 in the real world. 

It is unclear what is being demanded the way you have it now. All drop off points have negative demand, which reduces the vehicle load. Node 1 cannot be easily modeled as both a pick up and a delivery point
