### ISSUE TITLE
how to deal with the situation one point can be visited by many vehicles? 

### ISSUE THREAD

**Issue by colacolalove** [google/or-tools#1323]

**Comment by colacolalove** [comment]
@Mizux

**Comment by jmarca** [comment]
You need to actually ask a question by explaining what you are trying to do, what you have tried already, what is breaking, etc.

**Comment by colacolalove** [comment]
> You need to actually ask a question by explaining what you are trying to do, what you have tried already, what is breaking, etc. But make dummy nodes is the answer.

ok，i will describe it in detail.  Just like takeaway delivery，a merchant have many orders so that need many vehicles to finish. However,there are some questions:
1,first,it is a pickup and delivery problem.Different from before, a pickup point matches mutilple delivery points and one vehicle cannot finish the mechant's task needing multiple vehicles.
2、i thought it before that adding  dummy nodes, but how to split demands for vehicles. In other words, a pickup point matches a delivery points before, now a pickup point matches many points and how to create dummy nodes (don't know need how many vecicles) and each node matches which delivery nodes
thank you and looking forward to your reply

**Comment by colacolalove** [comment]
@jmarca @turadg @andersk @ambasta

**Comment by colacolalove** [comment]
@jmarca

**Comment by lperron** [comment]
There are multiple threads on how to duplicate nodes (basically you increase the number of visit, and you tweak the distance callback to make it consistent with the added nodes).

You should start from there.
