### ISSUE TITLE
P&D with multiple drop-offs: allow to drop only full delivery, not just a single drop-off

### ISSUE THREAD

**Issue by vbodnia** [google/or-tools#1327]
Hi
I have a Pickup & Delivery problem with time windows and where might be several drop-offs for a single delivery:
Delivery 1: `Pickup(1) - Dropoff(2) - Dropoff(3)`
Delivery 2: `Pickup(4) - Dropoff(5) - Dropoff(6)`

Model:
```java
 // Pickup-delivery pairs
 final int[][] pickupsDeliveries = {
        {1, 2},
        {1, 3},
        {4, 5},
        {4, 6},
};
```

Then allowing to drop nodes:
```java
long penalty = 100;

for (int i = 1; i < data.timeMatrix.length; ++i) {
     routing.addDisjunction(new long[] {manager.nodeToIndex(i)}, penalty);
}
```

The problem is that this disjunction allows to drop only single pairs regardless of their type and connections. In other words, it just results with "partial" deliveries instead of dropping them completely. 

Example:
Let's say, drop-off **3** can't be added to the final solution due to time window limit.
Current result: `Pickup(1) - Dropoff(2) - Pickup(4) - Dropoff(5) - Dropoff(6)`
Expected result: `Pickup(4) - Dropoff(5) - Dropoff(6)`

**Question: is there any way to set whole delivery to be dropped if solver can't add it to the solution completely?**

Thanks!

**Comment by jmarca** [comment]
First of all, the solver cannot visit the same node twice.  You need to make dummy nodes for the repeated nodes.  So if you really have a map location 1 with a pickup to 2 and another pickup to be delivered to 4, then you need to create two "solver space" nodes for the pickups.  So your pickupsDeliveries variable should not have any repeats, but rather should be something like
{1,2},{7,3},{4,5},{8,6}

Second, if you read the pickup and delivery examples, there is the "same vehicle" constraint there---if a node is not served, then its "vehicle" is by definition -1, which means that the "same vehicle" constraint will require that the delivery node must also have a vehicle of -1 (be unserved).

Hope that helps.

**Comment by vbodnia** [comment]
@jmarca That was helpful, thanks!
