### ISSUE TITLE
Different cost for different Time windows

### ISSUE THREAD

**Issue by shravanchaudhary** [google/or-tools#1328]
I was thinking of adding different profits for different time windows, like scoring 100 if it is visited between 1pm to 4pm, and 50 if it is visited between 4pm to 10pm, etc. So is it possible to access TimeDimension's CumulVar (time_dimension.CumulVar) while calculating a solution so that I could add different cost to the total cost according to time period the node is being visited at?

**Comment by sghb** [comment]
You could use a separate node per individual time window, with all these nodes in a disjunction.

Not exactly what you want, but there are also functions like [SetCumulVarSoftUpperBound](https://github.com/google/or-tools/blob/f3fd201e68cf75b7720ff5c3cadc599a1d02b54b/ortools/constraint_solver/routing.h#L1995), of course.

**Comment by lperron** [comment]
This looks like the correct approach.
