### ISSUE TITLE
NodeToIndex returned values don't cover the whole codomain

### ISSUE THREAD

**Issue by Apo-** [google/or-tools#1329]
ortools for python version: 7.1.6720
python version: 3.6.7
Platforms: linux, darwin

In the following example even though the number of nodes is 3, the NodeToIndex returns correct values only for nodes 1 and 2, but not for 0.

```python
from ortools.constraint_solver import pywrapcp


def main():
    number_of_locations = 3
    number_of_vehicles = 1
    start_nodes = [1]
    end_nodes = [0]

    index_manager = pywrapcp.RoutingIndexManager(number_of_locations, number_of_vehicles, start_nodes, end_nodes)
    i = index_manager.NodeToIndex(0)

    print("Number of nodes: ", index_manager.GetNumberOfNodes())    # Prints 3
    print("NodeToIndex: ", i)   # Prints -1
    print("IndexToNode: ", index_manager.IndexToNode(i))    # Should not give correct result (sometimes it does)


if __name__ == "__main__":
    main()
```

**Comment by lperron** [comment]
The mapping is not specified for start and end nodes.

Here is how to scan a route:

    index = routing.Start(0)
    while not routing.IsEnd(index):
        plan_output += ' {} ->'.format(manager.IndexToNode(index))
       ...
