### ISSUE TITLE
Choose the .Net version to build with

### ISSUE THREAD

**Issue by kostadin24** [google/or-tools#133]
Here I see only .Net 4.0 dll.
Is there a .Net 3.5 dll for download?

**Comment by lperron** [comment]
No.

Can you build from source?

**Comment by kostadin24** [comment]
Yes. The only problem is - because there is no VisualStudio solution file - where to find target version of .Net?

**Comment by tboby** [comment]
I've been struggling with this myself, trying to build for a different .net target framework, but I can't find any obvious place to set this in the csharp make.

**Comment by lperron** [comment]
Same for me.


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2015-12-29 18:52 GMT+01:00 tboby <notifications@github.com>:

**Comment by lperron** [comment]
Actually, I believe you need to change csc.exe in Makefile.windows to point to the one in the correct .NET framework.

I am trying to find the exact reference.

**Comment by lperron** [comment]
We are moving to dotnet core to build everything.
Thus minimum requirement is netstandard2.0
