### ISSUE TITLE
PDP not working without set_solution_limit

### ISSUE THREAD

**Issue by TeodoraB21** [google/or-tools#1332]
Hello!

I am running a PDP example, and it gives me a solution only if I set the solution limit to 1, otherwise it will return an error. 
As first_solution_strategy I am using PARALLEL_CHEAPEST_INSERTION. Also I tried to set a time limit, 60 seconds, but it doesn't search for solutions for 60 seconds, it returns the error before the 60 seconds pass.

I also tried to make the problem without many constraints, to be more easy for resolving.

This is the error message:
Exception thrown at 0x00007FF7191FCC13 in VRP.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.
And this is where it appears:
`const operations_research::Assignment* solution = routing.SolveWithParameters(searchParameters)`;
And the status is ROUTING_NOT_SOLVED. (But why did it stopped if is not solved?)

If i set searchParameters.set_solution_limit(1); it works fine, but only if it is set to 1, if I put 2 or anything else it returns the previous error.

**Comment by jmarca** [comment]
Can you post your code?  Not much to go on here

**Comment by atisnz** [comment]
Hi, I saw, that you built Vroom on Windows. Would you be able to help me with that? Pls contact attila@augview.net. Thanks!

**Comment by lperron** [comment]
No news.

Closing
