### ISSUE TITLE
Matching algorithm

### ISSUE THREAD

**Issue by anvar3** [google/or-tools#1333]
Hi,

I am a complete beginner when it comes to LP and OR-Tools, so to gain a better understanding I am trying to model a simple market that has buyers and sellers of `n` goods. Essentially the following scenario:

Participants:
* 1 buyer of 100 apples at $10 per apple.
* 1 buyer of 20 pears at $15 per pear.
* 1 buyer of 15 apples at $12 per apple

* 1 seller of 100 apples at $10 per apple.
* 1 seller of 10 pears at $15 per pear.

The algorithm should try to maximise the number the of goods sold, but in the future I would like to understand more about how to tweak the solver so that for instance in addition to maximising the number of goods it would prioritise maximising the seller's profit or minimising the number of buyers per seller.

So far I have managed to use OR-tools to satisfy simpler variations of this problem, but I am struggling to figure out how to bring it all together. For instance, how do I model that a buyer can only buy from a seller properly?

Any pointers would be much appreciated, even just pointing me to a book or paper would help.

Thanks!

**Comment by lperron** [comment]
Starts by writing the math description of your problem.
 I do not understeand what is 'a buyer can only buy from a seller properly'.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by anvar3** [comment]
Yes, I think I have managed to do that, but I am struggling with how to manifest it in code.

Sorry, I just saw I completely botched that sentence, what I meant was that if a buyer is also a seller they should not be able to buy off themselves.

Thanks!

**Comment by lperron** [comment]
How do you specify that A is buying 2 apples from B ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by anvar3** [comment]
I split the sellers and buyers, and add `model.addGreaterOrEqual(sellerSize, buyerSize)`

**Comment by lperron** [comment]
Why don't you have one var per pair seller, buyer and write some flow conservation with all these variables?

**Comment by anvar3** [comment]
First off, thanks a bunch for helping out, much appreciated! I am not sure I follow, mostly as I completely new to this. Is there any way you could elaborate?

**Comment by fuglede** [comment]
Depending a bit on where you want to go with your objective function, this is a special case of the [minimum-cost flow problem](https://en.wikipedia.org/wiki/Minimum-cost_flow_problem) where the underlying graph is bipartite (split into buyers and sellers). (See the [section on minimum weight bipartite matchings](https://en.wikipedia.org/wiki/Minimum-cost_flow_problem#Minimum_weight_bipartite_matching) to see how to reduce your problem to one with a single source/sink.) As such, what @lperron is saying is that you could introduce variables for each edge; the corresponding constraints (such as flow conservation) are those listed on the Wikipedia page.

**Comment by lperron** [comment]
Please start reading some modeling course on MIP solving.
This is not the forum for that.
