### ISSUE TITLE
Does max_time_in_seconds guarantee the best feasible?

### ISSUE THREAD

**Issue by stradivari96** [google/or-tools#1334]
Hi everyone,

I would like to know if the max_time_in_seconds parameter takes into account the objective function when returning a feasible solution or if I should do as suggested in  #926 to get the best of all found solutions.

Thanks!

A small piece of code to illustrate my use case:
```python
def solve(self):
    self.model.Minimize(self._calculate_cost())
    # parameters
    self.solver.parameters.max_time_in_seconds = 5
    self.solver.parameters.num_search_workers = 8
    status = self.solver.Solve(self.model)

    if status in [cp_model.OPTIMAL, cp_model.FEASIBLE]:
        if status == cp_model.FEASIBLE:
            print('Time limit reached!!!!')
        print('Branches', self.solver.NumBranches())
        print('Time', self.solver.WallTime())
        return Solution(self)
```

**Comment by lperron** [comment]
short answer: yes
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
