### ISSUE TITLE
Combine two constraints for people, groups and rooms

### ISSUE THREAD

**Issue by tr00mb** [google/or-tools#1336]
Hi,
My goal is to mix children from different classes in different groups for a special event where children have to work with children from other classes.
Then each group will be assigned to available classroom.

The main constraints for the groups are that groups are composed from children from different classes, there are also some skill level constraint.
The constraint for assigning the group to the classroom is the capacity of each classroom but also that some child (very few, we marked them with '*') must be in their classroom (indeed to be under the surveillance of their teacher !!)

I managed to have a correct list of groups.
I managed to have the correct number of groups per classroom, but I cannot figure out how to have the groups with '*' children in the right classroom.

My data contains the list of children:
 for e in all_eleves , e[0] is the pupil name, e[1] is its class, e[2] is its skill level, e[3] ='*' for the marked children who should stay in their classroom

I defined the groups as 
```
groups = {}
    for e in all_eleves:
        for g in all_groups:
            groups[(e,g)] = model.NewBoolVar('group_e%sg%i' % (e[0],g))
```

Adding some constraint such as (there are much more)
``` 
for e in all_eleves:
        model.Add(sum(groups[(e,g)] for g in all_groups) == 1)
for c in range(num_classes):
        for g in all_groups:
            model.Add(sum(groups[(e,g)] for e in all_eleves if e[1] == c ) <= 1)
```

Then for the classroom assignment I defined rooms as
```
rooms={}
    for r in all_classes:
        for g in all_groups:
            rooms[(r,g)] = model.NewBoolVar('room_r%sg%i' % (r,g))
```

I added one constraint which use a calculated num_groups_per_room
```
for r in all_classes:
        model.Add(sum(rooms[(r,g)] for g in all_groups) <= num_groups_per_room[r])
```

Until there, everything works well. Now I would like to add the constraint that when a marked children (e[3]='*') is in a group, this group should be in the room of the children class (e[1])

I tried 
```
for e in all_eleves:
        if e[3] == '*':
            for r in all_classes:
                if e[1] == r:
                    model.Add(sum(rooms[(r,g)]*groups[(e,g)] for g in all_groups) == 1)
                else:
                    model.Add(sum(rooms[(r,g)]*groups[(e,g)] for g in all_groups) == 0)
```
But I get the following error:
 raise TypeError('Not an integer linear expression: ' + str(arg))
TypeError: Not an integer linear expression: group_eSéraphineg0

How should I link groups[(e,g)] and rooms[(r,g)] so that a condition on e (e[3]=='*') triggers g to be the classroom r ?

**Comment by lperron** [comment]
What is the faulty line?
What are the types of the arguments ?

Le ven. 7 juin 2019 à 01:11, Yohann Agostini <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
OK, Add() expects linear constraints.
Clearly you rooms[(r, g)] * groups[(e, g)] is quadratic.

You need to create intermediate variables

See

https://github.com/google/or-tools/blob/master/ortools/sat/doc/boolean_logic.md#product-of-two-boolean-variables

**Comment by tr00mb** [comment]
Thanks a lot,
I set up 

```
# link the pupils, the groups and the room (groups[(e,g)] and rooms[(r,g)] <=> same_room[(e,r,g)])
    same_room={}
    for r in all_classes:
        for g in all_groups:
            for e in all_eleves:
                same_room[(e, r, g)] = model.NewBoolVar(
                    "eleve %s is in group %i in classroom %s" % (e[0], g, r))

    for e in all_eleves:
        for g in all_groups:
            for r in all_classes:
                model.AddBoolOr([groups[(e,g)].Not(),rooms[(r,g)].Not(),same_room[(e,r,g)]])
                model.AddImplication(same_room[(e,r,g)],groups[(e,g)])
                model.AddImplication(same_room[(e,r,g)],rooms[(r,g)])

    # pupils marked with a * seat in their classroom
    for r in all_classes:
        model.Add(sum(same_room[(e,r,g)] for g in all_groups
            for e in all_eleves if (e[1] != all_classes.index(r)) and (e[3] == '*')) == 0)
```

It works well
