### ISSUE TITLE
depending start time

### ISSUE THREAD

**Issue by KaramallahG** [google/or-tools#1337]
For me it is clear how to make min_start and max_start constraint of routes 

```
for vehicle_id in range(numOfVehicles):
        index = routing.Start(vehicle_id)
        timeDimension.CumulVar(index).SetRange(minStartTime, maxStartTime])
        routing.AddToAssignment(timeDimension.SlackVar(index))
```

What I'm trying to know is how to make a constraint that two vehicles should not run at the same time. Meaning:

```
minStartTime_1 < Start_1 < End_1 < maxStartTime_1
minStartTime_2 < Start_2< End_2< maxStartTime_2

```

then
Start_2 should be after End_1: 

```
End_1 < Start_2
```
Thanks

**Comment by lperron** [comment]
It looks awfully like a single driver making two routes.
Should be doable with a node representing the stop between the two routes.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 7 juin 2019 à 10:50, KaramallahG <notifications@github.com> a
écrit :

**Comment by KaramallahG** [comment]
Yes, it is single driver problem. For example:
In many countries you can rent a bicycle 30 minutes for free. You start in position A and Go to next position B within 30 minutes. You return the bicycle and take a new one (30 minutes for free) and so on ....

**Comment by KaramallahG** [comment]
> It looks awfully like a single driver making two routes. Should be doable with a node representing the stop between the two routes. Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53 00 Le ven. 7 juin 2019 à 10:50, KaramallahG <notifications@github.com> a écrit :
> […](#)

Thanks for your reply. Is there any reference or related example?

**Comment by Mizux** [comment]
My 2 cents, try to use the the vrp with fuel constraint sample (here fuel is in reality your 30 minute free rent).
i.e./
* your vehicle has a 30min **fuel** capacity
* all bycicle depot are "refuel stations" and are optional (i.e. don't have to visit all !!!)
* the solver should try to find the minimum refuel station (i.e. bycicle change station) to reach your goal (the mandatory end node)

ref: 
https://github.com/google/or-tools/blob/stable/examples/cpp/cvrptw_with_refueling.cc
