### ISSUE TITLE
Obvious typo in flatzinc/presolve.cc

### ISSUE THREAD

**Issue by dimbleby** [google/or-tools#134]
Duplicated conditions in `if` tests [here](https://github.com/google/or-tools/blob/404580ff0eb6098324970307a4ebae4b16d13f57/src/flatzinc/presolve.cc#L1010-L1017).

Loos like classic cut-and-paste.  Presumably the second pair should be going `if ge, then le` rather than repeating the first pair.

**Comment by lperron** [comment]
Fixed. Thanks!
