### ISSUE TITLE
CVRP - Vehicle Order

### ISSUE THREAD

**Issue by DMXS33** [google/or-tools#1340]
I'm testing your CVRP example. I'm testing with vehicles with different capacities. 
        public long[] Demands = { 0, 1, 1, 2, 4, 2, 4, 8, 8, 1, 2, 1, 2, 4, 4, 8, 9 };
        public long[] VehicleCapacities = { 30, 30, 20, 20, 10, 10 };
        public int VehicleNumber = 6;
It seems that the order of VehicleCapacities influences the result of your algorithm. If the order is: 
 10, 10, 20, 20, 30, 30 - the algorithm returns vehicles 3,4,5 and the total distance is 5092
If the vehicle order is 30, 30, 20, 20, 10, 10, the algorithm returns vehicles 1,2,3 and distance 5844. 
Could you explain why the vehicle order matters ? 
It seems that the algorithm always starts from the last vehicle to the first one ? If this is true , can I rely on this ? Should I first sort my vehicles ?

**Comment by sghb** [comment]
The routing solver is heuristic in nature and fairly complex, thus it is best not to assume anything about the solutions it returns (other than that they are legal).  If, for example, you _require_ some vehicles to be used before others are then additional constraints are the way to go.
