### ISSUE TITLE
Same vehicle requirement is not enforced with high-cost

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1341]
Hello,
Setting AddSoftSameVehicleConstraint(Nodes, Cost) works well with a small number of Nodes, and the desired vehicle serves all these Nodes on time.  However, after adding Nodes to the problem (but not to the condition) the solver also assigns another vehicle which **serves the majority of the Nodes** listed in the condition - even when an **extra-high Cost** is set in the condition. 
The desired vehicle should have easily served all these Nodes and save that cost, but the solver assigns it to other Nodes.  FSS is ParalleChepaerInsertion.

Any exlpanation?

**Comment by GuyBenhaim** [comment]
Hello,
Any prior observations of this behavoir?

**Comment by lperron** [comment]
Maybe this is the only feasible solution.

**Comment by lperron** [comment]
Any news? Please reopen if needed.
