### ISSUE TITLE
Logging on Windows VS2017 (C++)

### ISSUE THREAD

**Issue by bendeguz-modli** [google/or-tools#1342]
Hello!

I am using the SAT-CP solver with C++ on Windows 10 with Visual Studio 2017. I downloaded the latest compiled release of OR-Tools today (7.1). I want to print the detailed solver logs to somewhere (to a file or to the console, it doesn't matter).

I use the `set_log_search_progress()` function to set this parameter to true, but nothing appears on the output console nor any file is written with the detailed information. How can I get the solver's debug information?

Thanks!

**Comment by lperron** [comment]
Logging uses the glog library.
If using C++, you can use command line flags to redirect output

See:
https://stackoverflow.com/questions/27919877/redirect-google-log-glog-to-file

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 11 juin 2019 à 11:49, Bendegúz Módli <notifications@github.com> a
écrit :

**Comment by bendeguz-modli** [comment]
Also, if I use `LOG(WARNING)` in my own code, I receive a warning on the console:
_WARNING: Logging before InitGoogleLogging() is written to STDERR_ 
and my own log messages are appearing on the console. But nothing from inside the solver.

**Comment by lperron** [comment]
As seen in the StackOverflow link

::google::InitGoogleLogging(argv[0]);

before creating the model.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 11 juin 2019 à 13:21, Bendegúz Módli <notifications@github.com> a
écrit :

**Comment by bendeguz-modli** [comment]
Okay, I think I fixed it, thanks.

I initializes the logging in my main at the first lines with: `::google::InitGoogleLogging(argv[0])`
And than used `FLAGS_logtostderr` and `FLAGS_minloglevel` inside my main too, because VS treats command line flags somewhat strangely.

But now it works, thank you for the help!
