### ISSUE TITLE
VRP with disjunctions is very slow

### ISSUE THREAD

**Issue by TuurDutoit** [google/or-tools#1345]
I have a small VRP model that performs very badly from the moment I add time windows.

Some basic info:
* 18 nodes
* 1 depot
* 1 vehicle
* Arc cost calculated as:
    * driving_time(from, to) + service_time(from) in seconds
    * driving time to/from depot is always 0 (as suggested [here](https://developers.google.com/optimization/routing/routing_tasks#allowing-arbitrary-start-and-end-locations))
    * Some nodes don't have a known location; in that case, a default driving time of 30 min to/from this location is used
* A time dimension
    * Using the same transit callback
    * Horizon: 1 full working day (9 am to 6 pm)
    * Slack: 1 full working day (I don't care about slack times atm.)
    * Start cumul at 0
* A few disjunctions
    * Some clients have multiple locations; I only want to visit at most one of those (per client) in a given route
* A few nodes with fixed time windows
    * This model also takes into account reps' existing schedules. In order to do so, I create a node for every calendar event with a service time corresponding to the duration and a small time window around the start time
    * This seems to cause the problem

If I remove either the disjunctions or the time windows, solutions are typically found in 0.02-0.03s. If both features are used, it suddenly takes around 13-14 seconds to come up with a solution...  
The disjunctions are probably part of the problem, but I *just* added them and I've had this problem plague me seemingly randomly way before I did so.  
I also tried making the time windows for the calendar events larger and that seems to alleviate the problem: if I leave 30 mins of waiting time before each event, the model finds a solution in about 0.6s, even with disjunctions. That leads me to believe there is a performance problem when using very small time windows, though I don't really know how to solve or work around that.  
The only potential solution I can think of is to include nodes with a smaller transit time (service times are 1h+ now); maybe that way the solver can fill up the waiting times with those, instead of relying on the slack of the time windows?

**Comment by TuurDutoit** [comment]
Hmm, it looks like the disjunctions might be the problem after all. I just added some more disjunctions (I only had 3 hard-coded ones to test, I now have 8) and calculation times shot to ~27 seconds. This figure doesn't really change when enabling/disabling time_windows in the model.

**Comment by lperron** [comment]
Can you try without start_cumul_at_zero ?

**Comment by lperron** [comment]
Any news ?

**Comment by TuurDutoit** [comment]
I haven't worked on this project for several weeks now and in the meantime I've switched to a new machine, so I'm afraid I won't be able to follow up. I'll close the issue.
