### ISSUE TITLE
Should ortools (7.1) be working with PyPy (3.6)?

### ISSUE THREAD

**Issue by ael-g** [google/or-tools#1346]
I'm trying to use ortools with PyPy interpreter. Ortools is not instalable with pip so I tried to build it from source following this guide https://developers.google.com/optimization/install/python/source_linux
I'm building within a pypy:3.6 container which is based on Debian 9.9.
The sources built and I can import ortools modules from pypy3.6.
But I have some unexpected runtime errors compared with running the same source code with CPython.
I started debugging and it seems that some null pointers pop up from within pywrapcp.so code.
Same code executed with CPython works fine.
Would you have some directions to ensure ortools should work with PyPy?
Best regards,

**Comment by lperron** [comment]
We do not support cython or pypy, only the official python interpreters.

Any feedback is welcome though.

**Comment by ael-g** [comment]
Thanks for your answer.

My null pointer comes from this call:
`res = ((PyTypeObject*) data->newargs)->tp_new((PyTypeObject*) data->newargs, Py_None, Py_None);`
L2542 of file `./ortools/gen/ortools/constraint_solver/constraint_solver_python_wrap.cc` which is generated by Swig.
-> `data` is not null, but `res` is. 
Do you think of a workaround for this?
Or fixing that is just the tip of the iceberg anyway and I'll have other problems later.

**Comment by lperron** [comment]
This looks like a nasty problem as the python allocation fails.

**Comment by Mizux** [comment]
@ael-g may i know why you can't install `ortools` using pip since we provide manylinux 3.6 packages...

see: https://pypi.org/project/ortools/7.1.6720/#files

**Comment by lperron** [comment]
Short answer then, no.

**Comment by stonebig** [comment]
Any hope for PyPy-3.9 ? Pyodide ?

**Comment by lperron** [comment]
1) We will not touch any code/release except the head branch.
2) We use a lot of swig/pybind11. Not sure this is compatible with pypy.
3) We have added some numpy support in the library.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
