### ISSUE TITLE
NotImplementedError: Wrong number or type of arguments for overloaded function

### ISSUE THREAD

**Issue by CognitiveClouds-Prasad** [google/or-tools#1347]
```
File "/home/x/.local/lib/python2.7/site-packages/ortools/constraint_solver/pywrapcp.py", line 3150, in __init__
    this = _pywrapcp.new_RoutingIndexManager(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_RoutingIndexManager'.
  Possible C/C++ prototypes are:
    operations_research::RoutingIndexManager::RoutingIndexManager(int,int,operations_research::RoutingIndexManager::NodeIndex)
    operations_research::RoutingIndexManager::RoutingIndexManager(int,int,std::vector< operations_research::RoutingIndexManager::NodeIndex > const &,std::vector< operations_research::RoutingIndexManager::NodeIndex > const &)

```

I am frequently getting the following error from pywrapcp.RoutingIndexManager(). It happens when I remove the data['depot'] = 0 and/or when I experiment with different constraints. This is _not_ the same as routing.status().

This is fairly reproducible and I would appreciate any insights/suggestions.

**Comment by CognitiveClouds-Prasad** [comment]
https://developers.google.com/optimization/reference/constraint_solver/routing_index_manager/RoutingIndexManager/ I cannot use both data['depot'] and data['starts'] and data['ends'] simultaneously.

**Comment by Ordgod** [comment]
I meet the same problem!!!

**Comment by Asratum** [comment]
You can't, but if your depot is at 0,0 you can just input:
```
manager = pywrapcp.RoutingIndexManager(len(data['distance_matrix']),
                                       data['num_vehicles'], data['starts'], data['ends'])
```
and to make sure you start at the depot, you will need to put zeroes in data['starts'] and data['ends'] and deviate from those zeroes if you want to start or end somewhere different.

**Comment by tom-goodacre-chowagiken** [comment]
In my experience, this error can occur as the result of having numpy types as arguments (either scalar or inside an array), rather than base python types. They're supposed to be aliased, but the wrapper has difficulty parsing them, it appears. Or something.

Anyway, in my case I fixed this error by converting all my arrays' objects types to python's int.

**Comment by olalakul** [comment]
@tom-goodacre-chowagiken This solved my problem. Thanks
