### ISSUE TITLE
Failure with minizinc 2DPacking example

### ISSUE THREAD

**Issue by dimbleby** [google/or-tools#135]
I'm about to raise a handful of bugs from trying to run or-tools with the examples packaged with the binary distribution of minizinc.  I believe they're the ones that can be found [here](https://github.com/MiniZinc/libminizinc/tree/master/tests/examples).

It may be that you're just not terribly interested in flatzinc, in which case you'll treat these issues with suitably low priority... fair enough!

    [build@home-pc-vm ~]$ minizinc -G or-tools -f ~/or-tools/bin/fz minizinc-2.0.10/doc/examples/2DPacking.mzn
    Check failed: (emin) == (emax)Expression (X_INTRODUCED_0(0 .. 1) + X_INTRODUCED_1(0 .. 1)) is not fixed to a single value at a solution

**Comment by lperron** [comment]
I fixed it.

Thanks for the report.
