### ISSUE TITLE
Help: Setting specific start for a task in JobShop like problem

### ISSUE THREAD

**Issue by gustavo-barros** [google/or-tools#1353]
Hi,

How can I set to a task a fix start? I already have the control where the task should start, but when happen to some other task to have dependencies, the solver don't allow my task to start before it, even if I tell it so.

The way I'm actually doing that is:
![image](https://user-images.githubusercontent.com/36746102/59384852-8a08de00-8d39-11e9-9e1a-c3f247c89a94.png)

That way I can set the start. But won't work if have dependencies.

How could I force the start regardless of other things?

**Comment by lperron** [comment]
I do not understand the question.
You need an integer variable to build the interval.

Why not work with this? why not add model.Add(start_var == fixed_start);

**Comment by gustavo-barros** [comment]
Hi Laurent, 
Yes I already did that, and dealing with other issues I managed to solved it. Now is working. Thank you :)
