### ISSUE TITLE
A typo in shift_scheduling_sat.py

### ISSUE THREAD

**Issue by zhanzhan** [google/or-tools#1354]
It should be the "first" Friday, rather than the "third" Friday in the last request in the code below:

requests = [
        # Employee 3 wants the first Saturday off.
        (3, 0, 5, -2),
        # Employee 5 wants a night shift on the second Thursday.
        (5, 3, 10, -2),
        # Employee 2 does not want a night shift on the third Friday.
        (2, 3, 4, 4)
    ]

**Comment by lperron** [comment]
Thanks.
