### ISSUE TITLE
undefined reference to `absl::container_internal::ShouldInsertBackwards(unsigned long, signed char*)

### ISSUE THREAD

**Issue by Vincent-bin** [google/or-tools#1355]
When I use linear range as constraint
`    
operations_research::LinearExpr weight_distribution = front_distribution - back_distribution;
operations_research::LinearRange (-800, distribution, 800);`
I got this:
`/usr/lib/ccache/g++ -pipe -Lobj  -pthread -lrt -lm -pthread -lpthread -L/usr/local/lib -lglog -lortools -lprotobuf   -o or-tools-demo obj/or-tools-demo/src/main.o /usr/lib/gcc/x86_64-linux-gnu/6/libgcc.a
obj/or-tools-demo/src/main.o: In function `absl::container_internal::raw_hash_set<absl::container_internal::FlatHashMapPolicy<operations_research::MPVariable const*, double>, absl::container_internal::HashEq<operations_research::MPVariable const*, void>::Hash, absl::container_internal::HashEq<operations_research::MPVariable const*, void>::Eq, std::allocator<std::pair<operations_research::MPVariable const* const, double> > >::find_first_non_full(unsigned long)':
/usr/local/include/absl/container/internal/raw_hash_set.h:1621: undefined reference to `absl::container_internal::ShouldInsertBackwards(unsigned long, signed char*)'
collect2: error: ld returned 1 exit status`

**Comment by lperron** [comment]
Can you send me a code that reproduces the problem ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 13 juin 2019 à 07:14, vince-zibin <notifications@github.com> a
écrit :

**Comment by Vincent-bin** [comment]
`    MPSolver solver ("simple_mip_program", MPSolver::OptimizationProblemType::CBC_MIXED_INTEGER_PROGRAMMING);

    const LinearExpr a = solver.MakeVar (0, 1, true, "a");
    const LinearExpr b = solver.MakeVar (0, 1, true, "b");

    const LinearExpr e1 = a - b;`
if I remove the line ` const LinearExpr e1 = a - b;`, it will be ok

**Comment by lperron** [comment]
#include "ortools/base/logging.h"
#include "ortools/linear_solver/linear_solver.h"

namespace operations_research {

void Issue1355() {
  MPSolver solver("Issue1355", MPSolver::GLOP_LINEAR_PROGRAMMING);

  const LinearExpr a = solver.MakeVar (0, 1, true, "a");
  const LinearExpr b = solver.MakeVar (0, 1, true, "b");

  const LinearExpr e1 = a - b;
  for (const auto term : e1.terms()) {
    LOG(INFO) << term.first->name() << " * " << term.second;
  }
}
}  // namespace operations_research

int main(int argc, char** argv) {
  google::InitGoogleLogging(argv[0]);
  FLAGS_logtostderr = 1;
  operations_research::Issue1355();
  return EXIT_SUCCESS;
}

runs and outputs:

I0617 07:40:12.652860  8477 issue1355.cc:27] a * 1
I0617 07:40:12.653023  8477 issue1355.cc:27] b * -1
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 17 juin 2019 à 05:01, vince-zibin <notifications@github.com> a
écrit :

**Comment by Vincent-bin** [comment]
I tried your code, but still get the same error, I installed or-tools from sources, used the branch stable v7.1
And this is my compile command:
 `g++  -L/usr/local/lib -lglog -lortools -lprotobuf   -o or-tools-demo obj/or-tools-demo/src/main.o`
Do I need to link libabsl?

**Comment by Vincent-bin** [comment]
ps: I tried gcc-6.3 and gcc-8.2 and clang-7.0, but I got the same problem, it seems the link error, but I can't find any instructions about this. I tried to link everything include third_party libraries, it didn't work.

**Comment by lperron** [comment]
absl is linked inside libortools.so.

Are you sure you do not have an old libortools.so laying around ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 17 juin 2019 à 08:44, vince-zibin <notifications@github.com> a
écrit :

**Comment by Vincent-bin** [comment]
I just installed last week, it is the first time I used c++ version.

**Comment by lperron** [comment]
Can you check that the compiler used when compiling absl is the same used
to compile or-tools ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 17 juin 2019 à 09:03, vince-zibin <notifications@github.com> a
écrit :

**Comment by Vincent-bin** [comment]
Yes, I used gcc-6.3 to compile the whole or-tools, include libraries and or-tools itself, I just used the different compiler to compile the demo project

**Comment by Vincent-bin** [comment]
I tried to reinstall the ortools and I got this:
`mkdir -p "/usr/local"
mkdir "/usr/local/include"
mkdir: cannot create directory ‘/usr/local/include’: File exists
makefiles/Makefile.cpp.mk:572: recipe for target 'install_dirs' failed
make: [install_dirs] Error 1 (ignored)
mkdir "/usr/local/lib"
mkdir: cannot create directory ‘/usr/local/lib’: File exists
makefiles/Makefile.cpp.mk:572: recipe for target 'install_dirs' failed
make: [install_dirs] Error 1 (ignored)
mkdir "/usr/local/bin"
mkdir: cannot create directory ‘/usr/local/bin’: File exists
makefiles/Makefile.cpp.mk:572: recipe for target 'install_dirs' failed
make: [install_dirs] Error 1 (ignored)
rm -rf "/usr/local/include/ortools"
mkdir "/usr/local/include/ortools"
mkdir "/usr/local/include/ortools/algorithms"
mkdir "/usr/local/include/ortools/base"
mkdir "/usr/local/include/ortools/bop"
mkdir "/usr/local/include/ortools/constraint_solver"
mkdir "/usr/local/include/ortools/glop"
mkdir "/usr/local/include/ortools/graph"
mkdir "/usr/local/include/ortools/linear_solver"
mkdir "/usr/local/include/ortools/lp_data"
mkdir "/usr/local/include/ortools/port"
mkdir "/usr/local/include/ortools/sat"
mkdir "/usr/local/include/ortools/util"
mkdir "/usr/local/include/ortools/data"
cp LICENSE-2.0.txt "/usr/local"
cp ortools/algorithms/*.h "/usr/local/include/ortools/algorithms"
cp ortools/base/*.h "/usr/local/include/ortools/base"
cp ortools/constraint_solver/*.h "/usr/local/include/ortools/constraint_solver"
cp ortools/gen/ortools/constraint_solver/*.pb.h "/usr/local/include/ortools/constraint_solver"
cp ortools/bop/*.h "/usr/local/include/ortools/bop"
cp ortools/gen/ortools/bop/*.pb.h "/usr/local/include/ortools/bop"
cp ortools/glop/*.h "/usr/local/include/ortools/glop"
cp ortools/gen/ortools/glop/*.pb.h "/usr/local/include/ortools/glop"
cp ortools/graph/*.h "/usr/local/include/ortools/graph"
cp ortools/gen/ortools/graph/*.h "/usr/local/include/ortools/graph"
cp ortools/linear_solver/*.h "/usr/local/include/ortools/linear_solver"
cp ortools/gen/ortools/linear_solver/*.pb.h "/usr/local/include/ortools/linear_solver"
cp ortools/lp_data/*.h "/usr/local/include/ortools/lp_data"
cp ortools/port/*.h "/usr/local/include/ortools/port"
cp ortools/sat/*.h "/usr/local/include/ortools/sat"
cp ortools/gen/ortools/sat/*.pb.h "/usr/local/include/ortools/sat"
cp ortools/util/*.h "/usr/local/include/ortools/util"
cp ortools/gen/ortools/util/*.pb.h "/usr/local/include/ortools/util"
cp ortools/data/*.h "/usr/local/include/ortools/data"
cp ortools/gen/ortools/data/*.pb.h "/usr/local/include/ortools/data"
cp lib/libortools.so "/usr/local/lib"
cp -R dependencies/install/include/gflags "/usr/local/include"
cp -R dependencies/install/lib*/libgflags* "/usr/local/lib"
cp -R dependencies/install/bin/gflags_completions.sh "/usr/local/bin"
cp -R dependencies/install/include/glog "/usr/local/include"
cp -R dependencies/install/lib*/libglog* "/usr/local/lib"
cp -R dependencies/install/include/google "/usr/local/include"
cp -R /home/vince/Sandbox/dev-tools/or-tools/dependencies/install/lib//libproto* "/usr/local/lib"
cp dependencies/install/bin/protoc* "/usr/local/bin"
cp -R dependencies/install/include/absl "/usr/local/include"
cp -R /home/vince/Sandbox/dev-tools/or-tools/dependencies/install/lib//libabsl* "/usr/local/lib"
cp -R /libabsl* "/usr/local/lib"
cp: cannot stat '/libabsl*': No such file or directory
makefiles/Makefile.cpp.mk:624: recipe for target 'install_third_party' failed
make: [install_third_party] Error 1 (ignored)
cp -R dependencies/install/include/coin "/usr/local/include"
cp -R dependencies/install/lib*/libCbc* "/usr/local/lib"
cp -R dependencies/install/lib*/libCgl* "/usr/local/lib"
cp -R dependencies/install/lib*/libClp* "/usr/local/lib"
cp -R dependencies/install/lib*/libOsi* "/usr/local/lib"
cp -R dependencies/install/lib*/libCoinUtils* "/usr/local/lib"
cp -R dependencies/install/bin/cbc "/usr/local/bin"
cp -R dependencies/install/bin/clp "/usr/local/bin"
mkdir -p "/usr/local/share/doc/ortools"
mkdir "/usr/local/share/doc/ortools/sat"
mkdir: cannot create directory ‘/usr/local/share/doc/ortools/sat’: File exists
makefiles/Makefile.cpp.mk:678: recipe for target 'install_doc' failed
make: [install_doc] Error 1 (ignored)
mkdir "/usr/local/share/doc/ortools/sat/doc"
mkdir: cannot create directory ‘/usr/local/share/doc/ortools/sat/doc’: File exists
makefiles/Makefile.cpp.mk:678: recipe for target 'install_doc' failed
make: [install_doc] Error 1 (ignored)
cp ortools/sat/doc/*.md "/usr/local/share/doc/ortools/sat/doc"
`
seems something wrong about absl

**Comment by lperron** [comment]
Which using platform are you using ?
Can you tell me in which directory under dependencies/install/lib are the absl libraries installed ?

**Comment by senhalil** [comment]
@lperron  I have the same error when I compile with the `DEBUG` flag. Do you have any pointers why and how I can fix it?

```
../or-tools_Ubuntu-18.04-64bit_v7.5.7466/include/absl/container/internal/raw_hash_set.h:1654: 
undefined reference to `absl::container_internal::ShouldInsertBackwards(unsigned long, signed char*)' 
```

I am using the pre-compiled or-tools asset v7.5.7466 on Ubuntu 18.04 and compiling with gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) with the following flags ` g++ -std=c++11 -I ../or-tools/include -O0 -DDEBUG -ggdb3 -Wall -isystem../or-tools/. -isystem../or-tools/include -g tsp_simple.o vrp.pb.o -L ../or-tools/lib -Wl,-rpath ../or-tools/lib -lortools -lprotobuf -lglog -lgflags -o tsp_simple`

**Comment by Mizux** [comment]
@senhalil Could you try to use a more recent version e.g. the v8.0 release, did you try to also link libabsl_raw_hash.a supposing the symbol is defined here...

**Comment by senhalil** [comment]
@Mizux thanks a lot! `-labsl_raw_hash_set` did the trick on v7.5.

I checked with v8.0 as well and the same linker error exists (when compiled with `-DDEBUG`) and linking with libabsl_raw_hash_set.a fixes it.

Also to compile with `-fkeep-inline-functions` option, one needs to link with the following two libraries `-labsl_time -labsl_time_zone` (both on v7.5. and v8.0). 

Is this the expected behavior (i.e., needing to manually add libraries to compile with `-DDEBUG` and/or `-fkeep-inline-functions` options) or should I create another ticket?
