### ISSUE TITLE
Minimize the number of vehicles

### ISSUE THREAD

**Issue by TeodoraB21** [google/or-tools#1356]
Hello!

I want to minimize the number of vehicles used. Does anyone know what constrain should I use?

I try to solve the c1_8_1 example from here https://www.sintef.no/projectweb/top/vrptw/homberger-benchmark/800-customers/ and the best solution uses 80 vehicles and the total distance is 25030.36. But my algorithm returns a solution with 96 vehicles and a total distance of 35012.73

**Comment by lperron** [comment]
are you using GLS ?

**Comment by orwant** [comment]
In case it's unclear, Laurent is asking whether you're using the
GUIDED_LOCAL_SEARCH
routing option
<https://developers.google.com/optimization/routing/routing_options#local_search_options>
.

Jon

**Comment by TeodoraB21** [comment]
Yes, I am using GUIDED_LOCAL_SEARCH and I set the time-limit even to 500 seconds, and the solution is the same.

**Comment by niangjunchen** [comment]
My approach is to add a fixed cost to each vehicle use:  

routing.SetFixedCostOfVehicle(penalty, vehicle_idx) 

and set the penalty parameter to be some large number, not sure if this is the best possible approach though.

**Comment by TeodoraB21** [comment]
Ok, I will try it. Thank you!

**Comment by TeodoraB21** [comment]
It worked!
Is there a setting to minimize the total distance? Or what first solution strategy and local search options should I use?

**Comment by niangjunchen** [comment]
You can use SetArcCostEvaluatorOfAllVehicles(transit_callback_index) to minimize total distance. From my experience, parallel_cheapest_insertion seems better in most cases, but not always though.

**Comment by TeodoraB21** [comment]
I used SetArcCostEvaluatorOfAllVehicles(int distanceCallback) and the solution doesn't have the shortest distance.

**Comment by niangjunchen** [comment]
> I used SetArcCostEvaluatorOfAllVehicles(int distanceCallback) and the solution doesn't have the shortest distance.

Well, the vehicle routing problem is NP-hard, which means there is no efficient algorithm that can guarantee to find the optimal solution. The ortools routing library implemented a lot of heuristic and local search algorithms, but it does not always find the optimal solution.

**Comment by GuyBenhaim** [comment]
Hello,
If your "penalty" in routing.SetFixedCostOfVehicle(**penalty**, vehicle_idx) is lower than the penalty of dropping any single Node, do you see the solver totally skips this vehicle?

**Comment by niangjunchen** [comment]
If the cost of dropping a single node is higher than the cost of using a vehicle, ideally the solver would try to use more vehicles to meet all the demands rather than dropping some nodes to reduce the number of vehicles used.

**Comment by TeodoraB21** [comment]
I forgot to set the service times, and that's why my solution was so different than the one from benchmark.

**Comment by GuyBenhaim** [comment]
Yes, but seems that if vehicle FixedCost is higher than the cost of dropping any **single node**, but is much lower than the combined cost of dropping say **10 nodes** -  the solver still does not use the vehicle and drops all 10 nodes.   **Have you observed that?**

**Comment by GuyBenhaim** [comment]
?

**Comment by Roosjeva** [comment]
I implemented this part in my code. 

Only still the problem is using to much vehicles, how can this happen? 

time = 'Time'
    routing.AddDimension(
        time_callback_index,
        1000,  # allow waiting time
        250,  # maximum time per vehicle
        False,  # Don't force start cumul to zero.
        time)
    time_dimension = routing.GetDimensionOrDie(time)
    # Add time window constraints for each location except depot.
    for location_idx, time_window in enumerate(data['time_windows']):
        if location_idx == data['depot']:
            continue
        index = manager.NodeToIndex(location_idx)
        time_dimension.CumulVar(index).SetRange(time_window[0], time_window[1])
    # Add time window constraints for each vehicle start node.
    depot_idx = data['depot']
    for vehicle_id in range(data['num_vehicles']):
        # Set fixed cost of vehicle 
        routing.SetFixedCostOfVehicle(1000, vehicle_id)
        index = routing.Start(vehicle_id)
        time_dimension.CumulVar(index).SetRange(
            data['time_windows'][depot_idx][0],
            data['time_windows'][depot_idx][1])

**Comment by lperron** [comment]
Please do not use closed issues. Open a discussion instead.

**Comment by Amarjeet0890** [comment]
> It worked! Is there a setting to minimize the total distance? Or what first solution strategy and local search options should I use?

Could you please tell me where can I use the function routing.SetFixedCostOfVehicle(penalty, vehicle_idx) in my VRPPDTW code to minimize the number of vehicles



# Data Definition #
def create_data_model():
    """Stores the data for the problem"""
    data = {}
    _capacity = 50
    data["distance_matrix"]= []
    print("Travel Time matrix=",data["distance_matrix"])
    data['num_locations'] = len(data["distance_matrix"])
    data["demands"]= [ ]   
    data['pickups_deliveries'] = []
    print("PD pairs=",data['pickups_deliveries'])
     data['num_vehicles'] = 160
    data['time_windows'] = []
    print("Time Windows=",data['time_windows'])
       data['vehicle_max_distance'] = 900
     data['vehicle_capacity'] = _capacity
    # Max_Vehicle_Waittime = Maximum time a Vehicle can wait at a location
    data['vehicle_max_time'] = 900
    # Vehicle_load_unload_time = Time to load or Unload a Vehicle at a location
    data['vehicle_load_unload_time'] = 5
    # Depots = The start and end location of vehicles for the Route
    data['depot'] = 0
    return data

def print_solution(data, manager, routing, solution):
  """Prints solution on console."""
  print(f"Objective: {solution.ObjectiveValue()}")
  time_dimension = routing.GetDimensionOrDie("Time")
  total_time = 0
  total_distance = 0
  total_load = 0

  for vehicle_id in range(data["num_vehicles"]):
    index = routing.Start(vehicle_id)
    plan_output = f"Route for vehicle {vehicle_id}:\n"
    route_distance = 0
    route_load = 0

    while not routing.IsEnd(index):
      node_index = manager.IndexToNode(index)
      route_load += data["demands"][node_index]
      time_var = time_dimension.CumulVar(index)
      plan_output += (
          f"{manager.IndexToNode(index)}"
          f"Load({route_load}) "
          f"Time({solution.Min(time_var)},{solution.Max(time_var)})"
          " -> "
      )
      previous_index = index
      index = solution.Value(routing.NextVar(index))
      time_var = time_dimension.CumulVar(index)
      route_distance += routing.GetArcCostForVehicle(
          previous_index, index, vehicle_id
      )
    plan_output +=(
      f"{manager.IndexToNode(index)}"
      f"Load({route_load})"
      f"Time({solution.Min(time_var)},{solution.Max(time_var)})\n"
    )

    plan_output += f"Vehicles travel time on the route: {route_distance}m\n"
    plan_output += f"Remaining load on the route: {route_load}\n"
    plan_output += f"Total Time spent by the Vehicle on the route: {solution.Min(time_var)}min\n"
    print(plan_output)

    total_distance += route_distance
    total_load += route_load
    total_time += solution.Min(time_var)
  print(f"Total Travel time of all routes: {total_distance}min")
  print(f"Total load of all routes: {total_load}")
  print(f"Total time of operation on all routes: {total_time}min")

 
def main():
    """Solve the CVRP problem."""
    # Instantiate the data problem.
    data = create_data_model()
    # The inputs to RoutingIndexManager
    # Create the routing index manager.
    manager = pywrapcp.RoutingIndexManager(
        len(data["distance_matrix"]), data["num_vehicles"], data["depot"]
    )

    # Create Routing Model.
    routing = pywrapcp.RoutingModel(manager)

      #The callback accepts two indices, from_index and to_index, and returns the corresponding entry of the distance matrix.
    def distance_callback(from_index, to_index):
        """Returns the distance between the two nodes."""
        # Convert from routing variable Index to distance matrix NodeIndex.
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return data["distance_matrix"][from_node][to_node]
    #The following function creates the callback and registers it with the solver as transit_callback_index.
    transit_callback_index = routing.RegisterTransitCallback(distance_callback)

    # Define cost of each arc.
    # The arc cost evaluator tells the solver how to calculate the cost of travel between any two locations — in other words, the cost of the edge (or arc) joining them in the graph for the problem.
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

      # Add Distance constraint.
    dimension_name = "Distance"
    routing.AddDimension(
        transit_callback_index,        # The index for the callback that returns the quantity
        0,  # no slack # Specifies Maximum for the slack varaible (usually used in waiting time or demands)
        data['vehicle_max_distance'],  # maximum distance per vehicle #Maximum for the total quantity accumulated along each route.
        True,  # start cumul to zero #Boolean value. If true, the cumulative value of the quantity starts at 0.
        dimension_name, # Dimension name- String for the name for the dimension which you can use to access the variables elsewhere in the program
    )
    distance_dimension = routing.GetDimensionOrDie(dimension_name)
    distance_dimension.SetGlobalSpanCostCoefficient(100)
    # Define Transportation Requests.
    for request in data["pickups_deliveries"]:
        pickup_index = manager.NodeToIndex(request[0])
        delivery_index = manager.NodeToIndex(request[1])
        routing.AddPickupAndDelivery(pickup_index, delivery_index)
        routing.solver().Add(
            routing.VehicleVar(pickup_index) == routing.VehicleVar(delivery_index)
        )
      
        routing.solver().Add(
            distance_dimension.CumulVar(pickup_index)
            <= distance_dimension.CumulVar(delivery_index)
        )

    # Add Capacity constraint.
    def demand_callback(from_index):
        """Returns the demand of the node."""
        # Convert from routing variable Index to demands NodeIndex.
        from_node = manager.IndexToNode(from_index)
        return data["demands"][from_node]

    demand_callback_index = routing.RegisterUnaryTransitCallback(demand_callback)

    # But AddDimensionWithVehicleCapacity handles the more general case in which different vehicles have different capacities.
    routing.AddDimension(
        demand_callback_index,
        0,  # null capacity slack
        data["vehicle_capacity"],  # vehicle maximum capacities
        True,  # start cumul to zero
        "Capacity",
    )

    # Create and register a transit callback.
    def time_callback(from_index, to_index):
        """Returns the travel time between the two nodes."""
        # Convert from routing variable Index to time matrix NodeIndex.
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return data["distance_matrix"][from_node][to_node] + data['vehicle_load_unload_time']

    time_callback_index = routing.RegisterTransitCallback(time_callback)

    # Add Time Windows constraint.
    time = "Time"
    max_time = data['vehicle_max_time']
    routing.AddDimension(
        time_callback_index,
        max_time,  # allow waiting time
        max_time,  # maximum time per vehicle
        False,  # Don't force start cumul to zero since we are giving TW to start nodes.
        time,
    )
    time_dimension = routing.GetDimensionOrDie(time)
    # Add time window constraints for each location except depot.
    for location_idx, time_window in enumerate(data["time_windows"]):
        if location_idx == data["depot"]:
            continue
        index = manager.NodeToIndex(location_idx)
        time_dimension.CumulVar(index).SetRange(time_window[0], time_window[1])
    # Add time window constraints for each vehicle start node.
    depot_idx = data["depot"]
    for vehicle_id in range(data["num_vehicles"]):
        index = routing.Start(vehicle_id)
        time_dimension.CumulVar(index).SetRange(
            data["time_windows"][depot_idx][0], data["time_windows"][depot_idx][1]
        )


    search_parameters = pywrapcp.DefaultRoutingSearchParameters()
    # The code below shows how to set a solution limit of 100 for a search.
    #search_parameters.solution_limit = 100
    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC
    )
    search_parameters.local_search_metaheuristic = (
        routing_enums_pb2.LocalSearchMetaheuristic.GUIDED_LOCAL_SEARCH
    )
    search_parameters.time_limit.FromSeconds(120)

    # Solve the problem.
    solution = routing.SolveWithParameters(search_parameters)

    # Print solution on console.
    if solution:
        print_solution(data, manager, routing, solution)
    def get_routes(solution, routing, manager):
    # Get vehicle routes and store them in a two-dimensional array
    # i,j entry is the jth location visited by vehicle i along its route.
        routes = []
        for route_nbr in range(routing.vehicles()):
            index = routing.Start(route_nbr)
            route = [manager.IndexToNode(index)]
            while not routing.IsEnd(index):
                index = solution.Value(routing.NextVar(index))
                route.append(manager.IndexToNode(index))
            routes.append(route)

        # Print the route for debugging
        print(f'Route {route_nbr}: {route}')

        return routes

    routes = get_routes(solution, routing, manager)
    # the variable "routes" contains the list that was output from the VRP

# Display the routes.
    for i, route in enumerate(routes):
        print('Route', i, route)

if __name__ == "__main__":
    main()
