### ISSUE TITLE
Combining multiple Routing problems [help]

### ISSUE THREAD

**Issue by rishabhdeepsingh** [google/or-tools#1358]
I am trying to solve the following problem using OR-Tools.

Initially we have n jobs and m vehicles available to us. Each Job and vehicle falls under a category with some constraints applied to it accordingly.

**For Vehicles:-**
Each vehicle will have the following parameters
- **Load Capacity:-** Max load capacity of the vehicle.
- **Availability Time Slot:-** Time window in which this particular vehicle is available for use.
- **Start & End Points:-** Locations at which the truck will start and end its trip.  

**For JOBS:-**
- Each Job has some volume.
- Each Job has some service time that is required to do the job once it reaches its destination.
- Each Job has to be completed with a given time-window which can be different for each job.
- Each Job belongs to one of the 4 categories which are as follows :-
  - **Delivery :-** Something is loaded in the vehicle at the warehouse before the trip starts and then it delivers it somewhere before returning back.
  - **Pickup:-** During the trip, vehicle can pick up one or more things which are to be brought back to the warehouse.
  - **Pickup+Delivery:-** Here the vehicle will pick up something during the trip after leaving the warehouse and will deliver the same to some location before returning back. Here Nothing will be loaded at or brought back to the warehouse.
  - **Delivery+Pickup:-** Here the vehicle will deliver something at a location that was loaded into it before the trip started and will pick up some other things from the same location that will be brought back to the warehouse.

**Exception cases:-**
- If the job cannot be done by given vehicles it is left as unassigned.

How do I make this work using OR Tools?

**Comment by jmarca** [comment]
This will take some careful thought to model what is going on.  There is no off the shelf answer.  If you are asking someone else to do the hard work of setting up the model, you'll probably be waiting a long time!

My advice is to think about things in terms of events: pickup, delivery, leave depot, return to depot, etc.  then constraints just pair up the events, and other constraints dictate other relationships between events.
