### ISSUE TITLE
CP-SAT: Always return Constraint in model.Add()

### ISSUE THREAD

**Issue by Phibedy** [google/or-tools#1360]
My case:
```
greater = model.NewBoolVar("")
list = [<some IntVars>]
model.Add(sum(list)> 0).OnlyEnforeIf(greater)
```
This code fails if the list is empty. Of course I could check it before but maybe returning a dummy constraint which does nothing would be nice. What do you think about it?

https://github.com/google/or-tools/blob/master/ortools/sat/python/cp_model.py#L731

**Comment by lperron** [comment]
feasible. The bad news is that sum([]) > 0 is directly transformed into
False by python
but we could check this.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Actually

def Add(self, ct):
"""Adds a BoundedLinearExpression to the model."""
if isinstance(ct, BoundedLinearExpression):
return self.AddLinearExpressionInDomain(ct.Expression(),
Domain.FromFlatIntervals(
ct.Bounds()))
elif ct and isinstance(ct, bool):
pass # Nothing to do, was already evaluated to true.
elif not ct and isinstance(ct, bool):
return self.AddBoolOr([]) # Evaluate to false.
else:
raise TypeError('Not supported: CpModel.Add(' + str(ct) + ')')

We are already doing some of it.
So the pass should be a return of a True constraint.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Phibedy** [comment]
Yes, like in the self.AddBoolOr([]) case :+1:

**Comment by Phibedy** [comment]
Great thank you :+1:
