### ISSUE TITLE
CP-SAT: incomplete minimisation

### ISSUE THREAD

**Issue by sghb** [google/or-tools#1361]
Hi,

This is for CP-SAT in the OR-Tools 7.1.6722 via Python.

The minimisation problem below can be run as is or with variable b fixed to zero.  With b = 0, the solution is [0, 1, 10] with cost -19, which is indeed the minimum.

Without fixing b, the very same minimal solution should be found.  However, [0, 1, 1] with cost -1 is produced, far worse.

Is this a bug?  Am I doing something wrong here?

Cheers

```python
model = cp_model.CpModel()

b = model.NewBoolVar('b')
x = model.NewIntVar(1, 10, 'x')
y = model.NewIntVar(1, 10, 'y')

# b implies x == y  via linear inequations
model.Add(x - y >= 9 * (b - 1))
model.Add(y - x >= 9 * (b - 1))

##  model.Add(b == 0)  ## <-----

obj = 100 * b + x - 2 * y
model.Minimize(obj)

solver = cp_model.CpSolver()
status = solver.Solve(model)

print(list(map(solver.Value, [b, x, y])))
print(solver.ObjectiveValue())
```

**Comment by lperron** [comment]
Definitely a bug.

Please note that the best way to write this is:

model.Add(x == y).OnlyEnforceIf(b)

**Comment by sghb** [comment]
Okay; thank you.

**Comment by lperron** [comment]
Ok, fixed in the last code push.
