### ISSUE TITLE
Getting the Slack value for a Node

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1362]
Hello,
After the Solver provides a solution I'm trying to get the value of SlackVar but get a "memory access violation" runtime exception. Am I doing this right? 
IntVar local_slack = model.SlackVar(index, "time"); 
double task_slack = solution.Value(local_slack);

BTW: Getting the CumulVar Min and Max for the same index works fine.

**Comment by sghb** [comment]
Have you added the slack variable to the assignment using `AddToAssignment`, as done [here](https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/samples/cvrptw.py#L192) for example?

**Comment by GuyBenhaim** [comment]
No.
I will check whether this helps.
Thx  sghb
