### ISSUE TITLE
Build OR-tools python API against system libraries

### ISSUE THREAD

**Issue by elmuz** [google/or-tools#1364]
As far as I understood, building OR-tools with Python API automatically enables compilation routines for all dependencies, regardless the fact that these routines may be disabled through CMake options. I refer in particular to ZLIB, ABSL, GLOG, GFLAGS, etc.. Even though I install the exacted version requested by OR-tools, eventually it will build his own.

- Can you confirm that it is the expected behavior?
- Is there any chance that OR-tools could link against system libraries? Maybe some kind of "small hacking".

Thank you

**Comment by lperron** [comment]
You need to define the correct paths in Makefile.local. This is written in
the file:

## REQUIRED DEPENDENCIES ##
# By default they will be automatically built -> nothing to define
# Define UNIX_GFLAGS_DIR to depend on external Gflags dynamic library
#   e.g. UNIX_GFLAGS_DIR = /opt/gflags-x.y.z

# Define UNIX_GLOG_DIR to depend on external Glog dynamic library
#   e.g. UNIX_GLOG_DIR = /opt/glog-x.y.z

# Define UNIX_PROTOBUF_DIR to depend on external Protobuf dynamic library
#   e.g. UNIX_PROTOBUF_DIR = /opt/protobuf-x.y.z
# Define UNIX_PROTOC_BINARY to use a custom version.
#   e.g. UNIX_PROTOC_BINARY = /opt/protoc-x.y.z/bin/protoc
#   (default: UNIX_PROTOBUF_DIR/bin/protoc)

# Define UNIX_CBC_DIR to depend on external CBC dynamic library
#   e.g. UNIX_CBC_DIR = /opt/cbc-x.y.z
#   If you use a splitted version of CBC you can also define:
#     UNIX_CLP_DIR, UNIX_CGL_DIR, UNIX_OSI_DIR, UNIX_COINUTILS_DIR
#   note: by default they all point to UNIX_CBC_DIR

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by elmuz** [comment]
Thank you very much!

**Comment by Mizux** [comment]
As laurent said, the Makefile based build allow you to use your provided (system wide) version of most dependencies by tweaking the Makefile.local generated.

On the cmake-based build this is currently not possible yet, also to be able to easily redistribute python package I would like to build the python package with all dependencies as static libraries which should reduce the package size and avoid the issue to deploy a python package depending on missing shared library on the target machine...
