### ISSUE TITLE
MODEL_INVALID on Windows

### ISSUE THREAD

**Issue by stradivari96** [google/or-tools#1365]
Hi!

This simple model:
```python
from ortools.sat.python import cp_model

model = cp_model.CpModel()

a = model.NewIntVar(0, 10, 'a')
b = model.NewIntVar(0, 10, 'b')

model.Add(a+b >= 5)

solver = cp_model.CpSolver()
status = solver.Solve(model)
````

Is giving this Proto on Windows:
````
variables {
  name: "a"
  domain: 0
  domain: 10
}
variables {
  name: "b"
  domain: 0
  domain: 10
}
constraints {
  linear {
    vars: 1
    vars: 0
    coeffs: 1
    coeffs: 1
    domain: 5
    domain: -1  ## Possible bug
  }
}
````
windows 10 64bit
python version: 3.7.3 (64 bits)
ortools==7.1.6720

**Comment by stradivari96** [comment]
Digging a bit I found that something is working with int32 instead of int64.
Setting `INT_MAX = 2147483647` on cp_model.py gives the correct domain but setting it to `2147483648` overflows and gives the following Proto:
```
constraints {
  linear {
    vars: 1
    vars: 0
    coeffs: -1
    coeffs: 1
    domain: 5
    domain: -2147483648
  }
}
```

**Comment by lperron** [comment]
Thanks, I will check the swig code.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 20 juin 2019 à 02:28, Xiang Chen <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
Actually, this is before the SWIG code is called. Looks like a python protobuf issue :-(

**Comment by lperron** [comment]
I cannot reproduce it.
Can you check which version of protobuf is installed ?

**Comment by stradivari96** [comment]
ortools==7.1.6720
protobuf==3.8.0
six==1.12.0

**Comment by lperron** [comment]
Can you try with a downgraded  version of protobuf (3.7.1) ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 20 juin 2019 à 13:08, Xiang Chen <notifications@github.com> a
écrit :

**Comment by stradivari96** [comment]
Still the same, gonna investigate a bit to give you more details later, will test it with different versions of python and/or pip

**Comment by lperron** [comment]
It works fine with me. With both 3.7.1 and 3.8 for protobuf.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 20 juin 2019 à 14:22, Xiang Chen <notifications@github.com> a
écrit :

**Comment by stradivari96** [comment]
Hmm, updated to `ortools==7.1.6722` and everthing works fine, so I guess it was already fixed lol.
Thanks for everything!
