### ISSUE TITLE
[Question] How to set the minimum number of nodes visited by each vehicle or set the minimum traveling time for each vehicle

### ISSUE THREAD

**Issue by keyingchen** [google/or-tools#1368]
Hello everyone, I am working on a vehicle routing problem. I have formulated it as a CVRP problem and the objective is to minimize the total time (no time window constraints, I just used the CVRP example code from https://developers.google.com/optimization/routing/cvrp and replaced the distance matrix with the travel time matrix between each node). The problem I am facing is: In the solution there is a significant difference between the total time each vehicle travels. (eg. vehicle 1 travels 300 mins but vehicle 2 travels 150 mins) Is there any way to decrease such difference? I am thinking of adding a constraint to the model and I have tried adding dimension for each vehicle by using routing.AddDimension() However, I think AddDimension() only allows me to set the maximum. How should I approach this problem?? 
Like is there a way for me to set the minimum number of nodes visited by each vehicle or set the minimum traveling time for each vehicle?
Thanks in advance!!

**Comment by niangjunchen** [comment]
You can create a time dimension and use time_dimension.SetGlobalSpanCostCoefficient(c) to add a cost of ( c * the longest time spent for all vehicles). Larger c will lead to more evenly distributed time across vehicle at the expense of potentially longer total time.

**Comment by stradivari96** [comment]
Is it the same question as https://github.com/google/or-tools/issues/515 ?

**Comment by lperron** [comment]
Hard lower bound limits are problematic.
Please prefer soft ones.
