### ISSUE TITLE
How to use AbsEquality on two BoolVars

### ISSUE THREAD

**Issue by YLTsai0609** [google/or-tools#1369]
Hi,

I'm struggling in an employee scheduling problem. **And I wanna to make employee works as continuous as possible. Which means that instead of use IntervalVar, I wanna use an objective function to do this.** Considering the absolute value of  subtraction two boolean variables :

`abs(shifts[(n, d, s + 1)] - shifts[(n, d, s + 1)])`

It will give us 0 if the two are the same, otherwise we will get one.
Let me define the variable I need to explain first:
```
# The printer
from ortools.sat.python import cp_model

class NursesPartialSolutionPrinter(cp_model.CpSolverSolutionCallback):
    """Print intermediate solutions."""

    def __init__(self, shifts, num_nurses, num_days, num_shifts, sols):
        cp_model.CpSolverSolutionCallback.__init__(self)
        self._shifts = shifts
        self._num_nurses = num_nurses
        self._num_days = num_days
        self._num_shifts = num_shifts
        self._solutions = set(sols)
        self._solution_count = 0

    def on_solution_callback(self):
        self._solution_count += 1
        if self._solution_count in self._solutions:
            print('Solution %i' % self._solution_count)
            for d in range(self._num_days):
                print('Day %i' % d)
                for n in range(self._num_nurses):
                    is_working = False
                    for s in range(self._num_shifts):
                        if self.Value(self._shifts[(n, d, s)]):
                            is_working = True
                            print('  Nurse %i works shift %i' % (n, s))
                    if not is_working:
                        print('  Nurse {} does not work'.format(n))

    def solution_count(self):
        return self._solution_count


# The num_nurse, num_days, num_shift, and some constraint

num_nurses = 6
num_shifts = 6
num_days = 2
all_nurses = range(num_nurses)
all_days = range(num_days)
all_shifts = list(range(num_shifts))
# Creates the model.
model = cp_model.CpModel()

shifts = {}
for n in all_nurses:
    for d in all_days:
        for s in all_shifts:
            shifts[(n, d, s)] = model.NewBoolVar('shift_n%id%is%i' % (n, d, s))

# Each shift is assigned to exactly four nurse in the schedule period.
for d in all_days:
    for s in all_shifts:
        model.Add(sum(shifts[(n, d, s)] for n in all_nurses) == 4)

# Each nurse works at most 4 shift per day.
for n in all_nurses:
    for d in all_days:
        model.Add(sum(shifts[(n, d, s)] for s in all_shifts) <= 4)

```
### Then I wanna define the objective function below:

```
obj_bool_vars = list()
for n in all_nurses:
    for d in all_days:
        for s in all_shifts[:-1]:
            obj_bool_vars.append(abs(shifts[(n, d, s + 1)] - shifts[(n, d, s)]))

objective_function = sum(obj_bool_vars[i] for i in range(len(obj_bool_vars)))

model.Minimize(objective_function)
```
 After doing research the reply on:

1.  [github issue # 1192](https://github.com/google/or-tools/issues/1192) 
2.   [Absolute difference in Minimization in NSP on stackoverflow](https://stackoverflow.com/questions/55082024/absolute-difference-in-minimization-in-nsp)
3. [doc](https://github.com/google/or-tools/blob/master/ortools/sat/doc/reference.md)

It might use Model.AddAbsEquality is the solution. But after tried several times, I just still don't know how to make it work.

### Here is I tried : 
```
obj_bool_vars = list()
for n in all_nurses:
    for d in all_days:
        for s in all_shifts[:-1]:
            obj_bool_vars.append(
                                    model.AddAbsEquality(target, 
                                                var = shifts[(n, d, s + 1)] - shifts[(n, d, s + 1)]))

```
And I got the error : 

`NameError: name 'target' is not defined`

I know this problem could be solve. I just miss something.

Any help/input would be appreciated.

Thanks

**Comment by lperron** [comment]
AddAbsEquality(x, y) --> x = abs(y)
x needs to be defined, and y needs to be a variable.
In your code, target is not defined in python, and the second argument is
not a variable.

I would write it:

b0 = model.NewBoolVar('b0')
b1 = model.NewBoolVar('v1')
xor = model.NewBoolvar('xor')

Short version:

model.Add(b0 == b1).OnlyEnforceIf(xor.Not())
model.Add(b0 != b1).OnlyEnforceIf(xor)

Boolean version

model.AddBoolOr([b0, b1, xor.Not()])  # b0.Not() && b1.Not() => xor.Not()
model.AddBoolOr([b0.Not(), b1.Not(), xor.Not()])  # b0 && b1 => xor.Not()
model.AddBoolOr([b0, b1.Not(), xor])  # b0.Not() && b1 => xor
model.AddBoolOr([b0.Not(), b1, xor])  # b0 && b1.Not() => xor
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 20 juin 2019 à 18:12, Yu-Long Tsai <notifications@github.com> a
écrit :

**Comment by YLTsai0609** [comment]
Hi @lperron 
I followed your reply and [doc](https://github.com/google/or-tools/blob/master/ortools/sat/doc/reference.md) about method OnlyEnforceIf
Does it work as I imagined?
the code from your short version
```
b0 = model.NewBoolVar('b0')
b1 = model.NewBoolVar('v1')
xor = model.NewBoolvar('xor')

model.Add(b0 == b1).OnlyEnforceIf(xor.Not())
model.Add(b0 != b1).OnlyEnforceIf(xor)
```
`model.Add(b0 == b1).OnlyEnforceIf(xor.Not())`
when xor == 1 --> xor.Not() == 0 --> b0 == b1                              .................(1)
when xor == 0 --> xor.Not() == 1 --> b0 == b1 will be ignored     .................(2)

`model.Add(b0 != b1).OnlyEnforceIf(xor)`
when xor == 1 --> b0 != b1                                                              .................(3)
when xor == 0 --> b0 != b1 will be ignored                                     .................(4)

Do I missed something?
Thanks a lot

**Comment by lperron** [comment]
OnlyEnforceIf is an implication. (one direction).

You did not miss anything. See documentation:
http://google.github.io/or-tools/python/ortools/sat/python/cp_model.html#cp_model.Constraint.OnlyEnforceIf
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 21 juin 2019 à 03:55, Yu-Long Tsai <notifications@github.com> a
écrit :

**Comment by YLTsai0609** [comment]
@lperron 
Thanks a lot, problem solved!
