### ISSUE TITLE
SetCumulVarSoftLowerBound for route duration

### ISSUE THREAD

**Issue by KaramallahG** [google/or-tools#1372]
It seemed that one can set a soft constraint on the start and the end of the route using SetCumulVarSoftLowerBound
```
index= routing.End(1)
time_dimension.SetCumulVarSoftLowerBound(index,60*60, 5)

```
Instead of limiting the beginning and the end, I want to make it more flexible by limiting the duration (end-start) 
something like 
```
index = routing (End(1) - Start(1))
time_dimension.SetCumulVarSoftLowerBound(index,60*60, 5)
```
is there such a method that can do that?
Many Thanks

**Comment by lperron** [comment]
Actually not, there is a soft span upper bound in C++.
Nothing for the lower bound.

**Comment by Mizux** [comment]
Why not using a "duration" dimension instead of a "time" dimension and make it start a zero so you can use `SetCumulVarSoftLowerBound()` on end node....
