### ISSUE TITLE
Doubt: The best way to calculate horizon

### ISSUE THREAD

**Issue by gustavo-barros** [google/or-tools#1373]
Hi Laurent,

Wich one is the best way to calculate the horizon? The summation of all tasks durations?

**Comment by lperron** [comment]
It depends on the objective.
If you have no earliness cost, sum of durations.
If you have setup times between tasks, you need to add those.

Best method, use a heuristic to build a first solution by packing all jobs
and use that.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 21 juin 2019 à 19:01, gustavo-barros <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
There is one rather complete method at the beginning of examples/cpp/jobshop_sat.cc
