### ISSUE TITLE
SetNumThreads option in Python?

### ISSUE THREAD

**Issue by lpsinger** [google/or-tools#1374]
Is it possible to expose MPSolver.SetNumThreads in the Python wrapper? It would be nice to be able to run parallel solvers from Python.

**Comment by ConstantinoSchillebeeckxSimpleRose** [comment]
Looks like it was implemented with https://github.com/google/or-tools/commit/dbef2bb42f56930e568420f6e8abd702b40af917 but is not part of stable release. See also https://github.com/google/or-tools/pull/1280

**Comment by lperron** [comment]
Yes development occurs on the master branch.
Then, when a release is created, it is pushed to stable.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
