### ISSUE TITLE
Error building ortools python "unexpected argument syntax" and invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by rlloretb** [google/or-tools#1376]
I am building ortools 7.1 for python2, MacOS 10.12.6. Swig 4.0.0, CPLEX.
Everything goes well, until I do make test_python

Traceback (most recent call last):
  File "ortools/constraint_solver/samples/simple_routing_program.py", line 18, in <module>
    from ortools.constraint_solver import routing_enums_pb2
  File "/Users/didi/or-tools-7.1/ortools/constraint_solver/../gen/ortools/constraint_solver/routing_enums_pb2.py", line 23, in <module>
    serialized_pb=_b('\n-ortools/constraint_solver/routing_enums.proto\x12\x13operations_research\"\x8c\x03\n\x15\x46irstSolutionStrategy\"\xf2\x02\n\x05Value\x12\t\n\x05UNSET\x10\x00\x12\r\n\tAUTOMATIC\x10\x0f\x12\x15\n\x11PATH_CHEAPEST_ARC\x10\x03\x12\x1d\n\x19PATH_MOST_CONSTRAINED_ARC\x10\x04\x12\x16\n\x12\x45VALUATOR_STRATEGY\x10\x05\x12\x0b\n\x07SAVINGS\x10\n\x12\t\n\x05SWEEP\x10\x0b\x12\x10\n\x0c\x43HRISTOFIDES\x10\r\x12\x13\n\x0f\x41LL_UNPERFORMED\x10\x06\x12\x12\n\x0e\x42\x45ST_INSERTION\x10\x07\x12\x1f\n\x1bPARALLEL_CHEAPEST_INSERTION\x10\x08\x12!\n\x1dSEQUENTIAL_CHEAPEST_INSERTION\x10\x0e\x12\x1c\n\x18LOCAL_CHEAPEST_INSERTION\x10\t\x12\x17\n\x13GLOBAL_CHEAPEST_ARC\x10\x01\x12\x16\n\x12LOCAL_CHEAPEST_ARC\x10\x02\x12\x1b\n\x17\x46IRST_UNBOUND_MIN_VALUE\x10\x0c\"\xae\x01\n\x18LocalSearchMetaheuristic\"\x91\x01\n\x05Value\x12\t\n\x05UNSET\x10\x00\x12\r\n\tAUTOMATIC\x10\x06\x12\x12\n\x0eGREEDY_DESCENT\x10\x01\x12\x17\n\x13GUIDED_LOCAL_SEARCH\x10\x02\x12\x17\n\x13SIMULATED_ANNEALING\x10\x03\x12\x0f\n\x0bTABU_SEARCH\x10\x04\x12\x17\n\x13GENERIC_TABU_SEARCH\x10\x05\x42I\n#com.google.ortools.constraintsolverP\x01\xaa\x02\x1fGoogle.OrTools.ConstraintSolverb\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
make: *** [makefiles/Makefile.python.mk:531: rpy_simple_routing_program] Error 1

And if I do make install_python:
cd temp_python2.7/ortools && "/opt/local/bin/python2.7" setup.py bdist_wheel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
make: *** [makefiles/Makefile.python.mk:1084: pypi_archive] Error 1

**Comment by rlloretb** [comment]
I will proceed to do a clean install of the OS, update to Mojave and try again...

**Comment by rlloretb** [comment]
BTW, if I build ortools based on Python3, will I still be able to use it in a Python2 code?

**Comment by lperron** [comment]
It is not based on python3. There could be some examples that have not been
tested with python2.
Still, python2 will be obsolete by the end of 2019. So the next release
or-tools will mark python2 support as deprecated.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by rlloretb** [comment]
Problem solved. Mojave + Anaconda3 worked like a charm. I should have done this earlier...
