### ISSUE TITLE
is it possible to solve two or more cp-sat problems in one process ?

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#1377]
Hello,
  I experienced problems with InitGoogleLogging (called twice in utilities.cc) and crashes of jvm when two parallel threads executed CpSolver.solveWithSolutionCallback.
  Question is whether it is planned behaviour (one execution of cp-sat solver per process) or experienced problems are bugs.

Thanks,
Jan

**Comment by lperron** [comment]
InitGoogleLogging should only be called once. but is is protected by a
boolean flag.
So please make a dummy solve one in the main thread.

I will fix this in the next release.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
I have pushed the fix on master.
