### ISSUE TITLE
Specify starting location but end at any depot VRP

### ISSUE THREAD

**Issue by vedantlodha** [google/or-tools#1378]
Hi,
I am using ortools for VRP in python. 
I want to specify starting positions of each vehicles but I want vehicles to end their routes at any location in a given list of locations. Since the RoutingIndexModel either takes depots or starting and ending locations, how can i not fix end locations but allow it to end at a set of given locations

**Comment by sghb** [comment]
You could create a dummy end node per vehicle.  Then have the real end locations of the vehicle be the only nodes that can reach the dummy end node  - that is, remove the dummy end node from all other locations' `NextVar()` domain.  Also, any dimensions would have zero transit to the dummy end node.  Perhaps also set a `Disjunction` on the real end locations so only one of them is active.

**Comment by lperron** [comment]
Indeed, thanks
