### ISSUE TITLE
Help: How to allow task overlap in JobShop like problem?

### ISSUE THREAD

**Issue by gustavo-barros** [google/or-tools#1379]
Hi,

I have a set of machines that can do tasks on parallel, how can I allow these tasks to overlap?
I tried this:
![image](https://user-images.githubusercontent.com/36746102/60121925-87a37c80-975a-11e9-97e0-c6e45634dee5.png)
Applying this way the NoOverlap constraint only to the normal machines and ignoring the parallel ones. At first it seemed to work. But because some unkown reason some taks simply dissappear. Any Ideas?

**Comment by lperron** [comment]
Use a Cumulative constraint.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 25 juin 2019 à 20:06, gustavo-barros <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
Can you start reading the doc ?

Le mar. 25 juin 2019 à 20:16, gustavo-barros <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
http://google.github.io/or-tools/python/ortools/sat/python/cp_model.html#cp_model.CpModel.AddCumulative

I have no documentation for C# currently.

**Comment by gustavo-barros** [comment]
Thank you for the link Laurent. 

The problem is I don't understand how that will help me to make the tasks overlap with each other in the chosen machine. Maybe I don't  have the knowledge required to understand what that function actually does, despite I understand the code it expresses. 

I made some tests here, but I was not able to extract some sense of it.

**Comment by gustavo-barros** [comment]
All that I need is to tell the solver, "hey, in this machine the tasks can run free and wildly as they want to". My first idea was simply remove the NoOverlap constraint, but that seems not to work.

**Comment by lperron** [comment]
Here is another explanation on the cumulative constraint:

http://www.emn.fr/x-info/sdemasse/gccat/Ccumulative.html
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 27 juin 2019 à 16:36, gustavo-barros <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
I propose that for each interval 'i', you create an optional interval 'i_c' using the start, duration and end variable of the interval 'i', and an new Boolean variable 'p'.

Then you add all 'i_c' to the no_overlap.

Now to enforce the no_overlap, just set the 'p' variables to true.
