### ISSUE TITLE
Lazy constraints in CPLEX and Gurobi

### ISSUE THREAD

**Issue by bernalde** [google/or-tools#1381]
According to the documentation the only MIP solver that implements lazy constraints is SCIP:
https://github.com/google/or-tools/blob/f3fd201e68cf75b7720ff5c3cadc599a1d02b54b/ortools/linear_solver/linear_solver.h#L971
But reading through the code of `linear_solver.cc` it looks as if the condition is passed in the `MakeRowConstraint` function:
https://github.com/google/or-tools/blob/f3fd201e68cf75b7720ff5c3cadc599a1d02b54b/ortools/linear_solver/linear_solver.cc#L616
Is there any reason for it not to work with the other solvers?
My application relies on Lazy constraints and not being able to use them with these solvers may lead me not to use the or-tools interface.

**Comment by lperron** [comment]
Just not the time to implement it.
we welcome pull requests :-)
