### ISSUE TITLE
[Question] How to set the parameters for this special VRP problem with pickup and delivery?

### ISSUE THREAD

**Issue by hashfury42** [google/or-tools#1382]
Hi, if we want to cancel the distance from the last node to the depot （does not return to the depot） in the VRP problem with pickup and delivery, which is the best solution to set the parameters? 

just like this: 
![image](https://user-images.githubusercontent.com/42166756/60334755-c9d4f400-99ce-11e9-82e9-62a2c2a3dafe.png)

 We're using the Python api, and we're referring to this example ：
https://developers.google.com/optimization/routing/pickup_delivery

Thank you very much ~

**Comment by lperron** [comment]
Do not set a parameter, change the distance matrix to have a zero distance
between any node to the depot.

Le ven. 28 juin 2019 à 12:05, hashfury42 <notifications@github.com> a
écrit :
