### ISSUE TITLE
clean_java target doesn't clean ortools/gen directory

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#1384]
Hello,
  for building of ortools for java I use following sequence ...
  tools\make third_party
  tools\make java

  for cleaning of working directory I use following sequence ... 
  tools\make clean_third_party
  tools\make clean_java

  During movement on commit tree between 7.1 and current master branch I experienced several times information about incompatible sources of protoc. Cleaning of ortools/gen directory helped but should be probably part of clean_java target.

Jan

**Comment by lperron** [comment]
Which part of ortools/gen java code is not cleaned ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Just checked

make cc
make java
make clean_java

no java artifacts are left in ortools/gen.

**Comment by gregy4** [comment]
sources generated by protoc. for example
             gen/ortools/glop/parameters.pb.[h|cc]

so no java artifacts but code used by 'make java', I checked that it is cleaned by clean_cc target.
right sequence is in this case is
clean_third_party
clean_cc
clean_java

installation instructions should probably be updated to mention clean_cc target.

**Comment by lperron** [comment]
Each clean_xx target cleans the artifacts created by make_xx.
I do not believe it depends on the order.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by gregy4** [comment]
You are partially right. 'make java' calls internally 'make cc' and I didn't realized it. make 'make clean' target that cleans everything (useful when you move between commits) would be helpful.

**Comment by lperron** [comment]
'make clean' cleans everything.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by gregy4** [comment]
Great, I didn't notice that it is already present.
