### ISSUE TITLE
CP-SAT  RoutingModel problem using the latest commits

### ISSUE THREAD

**Issue by aloumpas** [google/or-tools#1387]
Hello community, 

I am trying to solve a tsp with cp-sat using the latest commits. The problem I faced is that when the cp-sat is enabled it seems that the solution returned is only feasible and not optimal. It seems that the solver does not try to make any iterations in order to optimize the solution and stops before time out is reached. In contrary when I run with cp-sat disabled the old solver does many  iterations and returns a much more optimal solution when reaching the timeout. 

I observed that cp-sat's objective value is always 0.

Also the first parameter 'arc' on the `objective.AddTerm(arc, cost)`  on file routing_sat.cc
```
const BoolVar arc = builder->NewBoolVar();
circuit.AddArc(tail, head, arc);
objective.AddTerm(arc, cost);
```
on method LinearExpr::AddTerm(IntVar var, int64 coeff)  seems to need an IntVar but on this file is BoolVar. Does this maybe impose problems?

Kind regards,
tasloum

**Comment by lperron** [comment]
CP-SAT support for the routing library is experimental.

Please do not use it.
