### ISSUE TITLE
Wrong answer in 'gang warfare' problem

### ISSUE THREAD

**Issue by dimbleby** [google/or-tools#139]
This problem is taken from the recent Coursera course on modelling with minizinc.  The set up is a bit elaborate:

-  A school principal needs to interview a group of students to establish who is responsible for some bad thing.
-  The task is to choose an order in which to interview the students.
-  Students are grouped into gangs.  Each gang has a leader.
-  Some gangs are rivals with other gangs.
-  Points are scored as follows:
  -  For interviewing a non-leader: 1 point if before interviewing his leader, else no points.
  -  For interviewing the leader of a gang g1: 
     - if there exists some rival gang g2, all of whose members have already been interviewed, then 3 + 2 * l points, where l is the number of members of gang g1 not yet interviewed.  (The idea is something like: this gang leader feels that the principal and the rival gang are collaborating and as a result sells out the rest of his own gang).
     - else if the gang-leader is interviewed in the morning ('when the principal is fresh') 3 points
     - else no points
-  (there are some constraints about not allowing members of the same gang, or of rival gangs, to be interviewed consecutively.  I've omitted them for the purposes of this bug report).

This [gist](https://gist.github.com/anonymous/b7609e3f483f9d37dafc) encodes this in minizinc, and also forces a solution which I know to be optimal for 38 points - confirmed with several other solvers.

But solving via or-tools mis-scores this solution as reaching only 20 points.  

In particular, it gives a score of -1 points for one of the individual interviews - although this is certainly impossible by the above rules.

    [build@home-pc-vm gangwarfare]$ minizinc -G or-tools -f /data/build/or-tools/bin/fz or-tools-bug.mzn
    order = [18, 8, 17, 3, 16, 7, 12, 4, 15, 6, 14, 5, 13, 9, 1, 11, 2, 10];
    points = [-1, 0, 1, 1, 0, 0, 3, 1, 1, 0, 0, 9, 0, 0, 0, 3, 1, 1];
    obj = 20;
    ----------
    ==========

Here's the correct scoring:

    [build@home-pc-vm gangwarfare]$ minizinc or-tools-bug.mzn
    order = [18, 8, 17, 3, 16, 7, 12, 4, 15, 6, 14, 5, 13, 9, 1, 11, 2, 10];
    points = [5, 0, 1, 7, 0, 0, 3, 1, 7, 0, 0, 9, 0, 0, 0, 3, 1, 1];
    obj = 38;
    ----------
    ==========

**Comment by lperron** [comment]
Thanks, I fixed the bug.

**Comment by dimbleby** [comment]
Thanks!  

(I'm going to edit the issue report to remove the link to the gist - I expect Coursera would prefer me not to share even this fragment of a solution).
