### ISSUE TITLE
Using dependencies installed in system

### ISSUE THREAD

**Issue by LesserBabka** [google/or-tools#1390]
My understanding is that I should be able to use dependencies already installed in my system by modifying Makefile.local. However, if I set for instance
 
UNIX_PROTOBUF_DIR = /usr

it seems protobuf is still being built by make third_party. Do I need to have all the dependencies to use this option?

**Comment by lperron** [comment]
Look at all the targets in makefiles/Makefile.third_party.{win/unix}.mk

and launch the missing installers manually.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 2 juil. 2019 à 12:37, LesserBabka <notifications@github.com> a
écrit :

**Comment by LesserBabka** [comment]
I see, thank you.
