### ISSUE TITLE
Generated Makefile.local missing abseil

### ISSUE THREAD

**Issue by LesserBabka** [google/or-tools#1391]
The generated Makefile.local is missing abseil. If setting the dependency dirs that are included in the auto generated Makefile.local and building cc. Obviously the user will know what to do though. 
 
$ make cc -j12
GFLAGS: found
GLOG: found
PROTOBUF: found
PROTOC: found
makefiles/Makefile.third_party.unix.mk:48: *** Third party Abseil-cpp files was not found! did you run 'make third_party' or set UNIX_ABSL_DIR ?.  Stop.

**Comment by lperron** [comment]
did you run make third_party ?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 2 juil. 2019 à 13:08, LesserBabka <notifications@github.com> a
écrit :

**Comment by LesserBabka** [comment]
No, I did not. My point is just that the generation of Makefile.local seems to be done so that the user can easly specify the paths to all dependencies if already installed in the system and the generated Makefile.local already includes UNIX_GFLAGS_DIR, UNIX_GLOG_DIR, UNIX_PROTOBUF_DIR and UNIX_CBC_DIR, but not UNIX_ABSL_DIR. Just wanted to mention this as maybe it could be fixed.

**Comment by lperron** [comment]
you mean the comment that lists possible variables?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 2 juil. 2019 à 14:59, LesserBabka <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
This being said, abseil has no install rules, and we patch it to make it happen.
So most likely, it will not be installed.
