### ISSUE TITLE
How to specify installation directory

### ISSUE THREAD

**Issue by LesserBabka** [google/or-tools#1392]
How do I specify in which directory to install or-tools when built from source? I would like to install or-tools and preferably its dependencies (which are built by target third_party) in /opt/or-tools-7.1.0.

**Comment by lperron** [comment]
Only install_cc and install_python are implemented

for C++:
  make install_cc DESTDIR=<path>

For python, it will add the wheel to the python user wheels.



Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 2 juil. 2019 à 13:12, LesserBabka <notifications@github.com> a
écrit :

**Comment by LesserBabka** [comment]
Thanks!
(If possible, could this be added to the installation instructions as I think many might be interested in this option?)

**Comment by plvincenti** [comment]
Hello or-tools community,

for C++ installation on a specific directory, I used the existing cmake configuration by doing : 

Configuration through cmake (you might want to modify some options) : 

```
cmake -S . -B ./builds -DBUILD_DEPS=ON \
 -DBUILD_DOTNET=OFF \
 -DBUILD_JAVA=OFF \
 -DBUILD_PYTHON=OFF \
 -DBUILD_EXAMPLES=OFF \
 -DBUILD_SAMPLES=OFF \
 -DUSE_COINOR=ON \
 -DUSE_SCIP=ON \
 -DUSE_GLPK=OFF \
 -DUSE_CPLEX=OFF \
 -DUSE_XPRESS=OFF \
 -DCMAKE_BUILD_TYPE=Release \
 -DCMAKE_INSTALL_PREFIX=path/to/install_dir
```

Build through cmake : 
`cmake --build ./builds -j12`

Then the install : 
`cmake --build ./builds --target install`

@lperron, @Mizux, do you confirm it's a correct way to install or-tools ? If it's the case, it could be insteresting to add those instructions in the installation documentation. 

Thank you, have a good day.
