### ISSUE TITLE
Makefile.local is overwritten by make cc

### ISSUE THREAD

**Issue by LesserBabka** [google/or-tools#1393]
I have specified paths to all dependencies in Makefile.local. However, make cc will overwrite this file (as part of target install_deps_directories I belive). The next time I build I will have to modify Makefile.local again. I think Makefile.local should only be generated if it doesn't exist.

**Comment by lperron** [comment]
a bit tricky.
Normally, it is re-generated if you modify the various .mk files.

I agree with your point though.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 2 juil. 2019 à 15:05, LesserBabka <notifications@github.com> a
écrit :
