### ISSUE TITLE
Linking fails building from source and using system protobuf

### ISSUE THREAD

**Issue by LesserBabka** [google/or-tools#1394]
In v7.1 make cc fails when linking libortools with the following error message

`/bin/ld: /usr/lib/: file not recognized: Is a directory`
`collect2: error: ld returned 1 exit status`
`make: *** [makefiles/Makefile.cpp.mk:179: lib/libortools.so] Error 1`

when having set

`UNIX_PROTOBUF_DIR = /usr`

The reason is in this line (Makefile.third_party.unix.mk)

`DYNAMIC_PROTOBUF_LNK = -L$(_PROTOBUF_LIB_DIR) -lprotobuf`

which on my system becomes becomes

`-L/usr/lib64/ /usr/lib/ -lprotobuf`

**Comment by lperron** [comment]
Normally, it should be robust to this

_PROTOBUF_LIB_DIR = $(dir $(wildcard \
 $(UNIX_PROTOBUF_DIR)/lib*/libprotobuf.$L \
 $(UNIX_PROTOBUF_DIR)/lib*/libprotobuf.$L@ \
 $(UNIX_PROTOBUF_DIR)/lib/*/libprotobuf.$L))
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 2 juil. 2019 à 15:15, LesserBabka <notifications@github.com> a
écrit :

**Comment by LesserBabka** [comment]
The problem is that _PROTOBUF_LIB_DIR will contain both /usr/lib64 and /usr/lib, but only the latter is prepended with -L.

**Comment by lperron** [comment]
and both contains a libprotobuf ?
They are the same ?

I guess we should use $firstword here.

Which platform are you using?

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 3 juil. 2019 à 09:17, LesserBabka <notifications@github.com> a
écrit :

**Comment by LesserBabka** [comment]
Ahh, I see your point now. Yes, they both do, but that is probably wrong, I agree. The one I have installed by package manager is in /usr/lib and the other one is probably from installing or-tools before actually. I should remove the one installed by or-tools before as they are both protobuf-3.7.1.
Thanks!
