### ISSUE TITLE
Is it posible to constrain tcp/vrp posible next move ?

### ISSUE THREAD

**Issue by 515orestis** [google/or-tools#1395]
Is it possible to constrain the algorithm, that it can move from a node, to only a few specific others, in a tcp or vrp problems ?
and if yes how?

For examples if i have 7 nodes and i am correctly  at node with id:1, I want the algorithm to move to one of the nodes with id 2 ,3  or 4 and not any other

**Comment by lperron** [comment]
Yes, just reduce the domain of the Next() variables.

beware that the value in a domain represents an index (and not a node), so
you need to use the RoutingNodeManager.NodeToIndex() to compute the reduced
domain.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 3 juil. 2019 à 01:06, 515orestis <notifications@github.com> a
écrit :
