### ISSUE TITLE
"Linear solver not recognized" when built w/ SCIP6.0.1 from master

### ISSUE THREAD

**Issue by omalleyt12** [google/or-tools#1396]
I was able to successfully build or-tools from source w/ master branch with the SCIP library, but running the examples in `make test_python` shows that

```
---- Integer programming example with SCIP (natural language API) -----
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0702 23:12:24.394408 218482112 linear_solver.cc:397] Linear solver not recognized.
*** Check failure stack trace: ***
make: *** [rpy_integer_programming] Abort trap: 6
```

This is strange because `USE_SCIP` is clearly being set bc I can call

```
from ortools.linear_solver import pywraplp
print(pywraplp.SCIP_MIXED_INTEGER_PROGRAMMING)
```

just fine, but when I pass this as the ProblemType to a Solver I get the "Linear solver not recognized" error

**Comment by Mizux** [comment]
did you make clean_python, make build_python ?

Maybe a previous version has been built without the support ?

does it work in C++ ?

**Comment by omalleyt12** [comment]
Ah, that worked thanks!

I had to run `make clean` and rebuild the python and C++, and then `make python` again
