### ISSUE TITLE
ortools cp_solver conflicting constraints

### ISSUE THREAD

**Issue by abduakhatov** [google/or-tools#1398]
I am using `from ortools.sat.python import cp_model` and sometimes I get conflicts on my constraints, which returns `INFEASIBLE`. According to docs: `solver.NumConflicts` returns number of conflicts. 

How to identify/receive/get which specific constraints are conflicting? 

In docs I found solve callback methods, but if I am not mistaken they return something if any solution if found.

**Comment by abduakhatov** [comment]
I suppose @Mizux and @lperron are on vacation ))

**Comment by lperron** [comment]
No, just very busy. Please remember that or-tools is not my main job, and I
do answer questions mostly on my free time.

1) Num conflicts returns the number of conflicts generated during search.
Roughly, a conflict equals to a dead end in the search tree.
2) Callback are called at each feasible solutions.

It is a hard problem to find a meaningful reason for a infeasible problem.
Try removing constraints, enlarging domains.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by abduakhatov** [comment]
@lperron bro, I and others here do really appreciate your help, and we are really thankful to you all guys. I was just joking in above post, lol)). 

As you suggest: 
> Try removing constraints, enlarging domains
The matter is that sometimes the system needs to receive what particular constraint is conflicting, so that dynamically decide what to do next depending on the type of constraint.

**Comment by sayedIbrahimIvadoLabs** [comment]
is this implements?

**Comment by sayedIbrahimIvadoLabs** [comment]
Thanks @lperron for the reply, where can I find them?

**Comment by lperron** [comment]
Search assumptions or reification in the mailing lists.
