### ISSUE TITLE
Trivial problem is infeasible in cpp, but works in python

### ISSUE THREAD

**Issue by gte620v** [google/or-tools#1400]
I have run into an issue in an optimization problem where trivially feasible constraints cause my cpp program to return  "infeasible" when trying to solve.

To demonstrate, I have created a nurse schedule optimization program with 3 nurses and 5 slots.  

I have two trivial constraints: 1) that the first nurse takes the first slot and 2) that at most one nurse is allowed in each slot.  

When engaged one at a time, these constraints cause or-tools to return a feasible solution, but when I engage both constraints, I get an infeasible solution.  The exact same problem works fine in the python API even with both constraints engaged.  

I suspect I am misusing `AddEquality` somehow when I set the first constraint (`cp_model.AddEquality(LinearExpr(slots[0][0]), 1);`), but I cannot figure out what the problem is.  

Please help.

```c++
#include <iostream>
#include <vector>

#include "ortools/sat/cp_model.h"
#include "ortools/sat/sat_parameters.pb.h"

namespace operations_research {

namespace sat {
void slots(bool add_sum, bool add_const) {

  CpModelBuilder cp_model;

  const int num_nurses = 3;
  const int num_slots = 5;

  std::vector<std::vector<IntVar>> slots(num_nurses);

  for (int n = 0; n < num_nurses; n++) {
    for (int d = 0; d < num_slots; d++) {
      const IntVar var = cp_model.NewIntVar({0, 1});
      slots[n].push_back(var);
    }
  }

  if (add_const) {
    // trival constraint
    cp_model.AddEquality(LinearExpr(slots[0][0]), 1);
  }

  if (add_sum) {
    // make the first row sum to one; should be trivial too
    std::vector<IntVar> this_nurse_vals(num_nurses);
    for (int n = 0; n < num_nurses; n++) {
      const IntVar var = slots[n][0];
      this_nurse_vals.push_back(var);
    }
    cp_model.AddEquality(LinearExpr::Sum(this_nurse_vals), 1);
  }

  // solve
  const CpSolverResponse response = Solve(cp_model.Build());
  LOG(INFO) << CpSolverResponseStats(response);

  for (int d = 0; d < num_slots; d++) {
    for (int n = 0; n < num_nurses; n++) {
      std::cout << SolutionIntegerValue(response, slots[n][d]);
    }
    std::cout << std::endl;
  }
  std::cout << std::endl;

  // [END solve]
}

} // namespace sat
} // namespace operations_research

// ----- MAIN -----
int main(int argc, char **argv) {
  operations_research::sat::slots(false, true); // works
  operations_research::sat::slots(true, false); // works
  operations_research::sat::slots(true, true);  // infeasible

  return EXIT_SUCCESS;
}
// [END program]
```

The same program that works fine in python:

```python
from ortools.sat.python import cp_model
num_nurses = 3
num_slots = 5

model = cp_model.CpModel()

# make vars
slots = {}
for n in range(num_nurses):
    for d in range(num_slots):
        slots[(n, d)] = model.NewIntVar(0, 1, "slot")


model.Add(slots[(0, 0)] == 1)

model.Add(sum(slots[(n, 0)] for n in range(num_nurses)) == 1)

solver = cp_model.CpSolver()

solver.Solve(model)

solution = []


for d in range(num_slots):
    solution.append([])
    for n in range(num_nurses):
        solution[d].append(solver.Value(slots[(n, d)]))
        
print(solution)
```

**Comment by gte620v** [comment]
What is stranger still is that by slightly changing the constraint from `    cp_model.AddEquality(LinearExpr(slots[0][0]), 1);` to `    cp_model.AddEquality(LinearExpr(slots[1][0]), 1);`, the solution comes back feasible and things work as expected.  Any other value works as well. Somehow the first element of the vector seems to be sacred.

**Comment by lperron** [comment]
if (add_sum) {
    // make the first row sum to one; should be trivial too
    std::vector<IntVar> this_nurse_vals(num_nurses);
    for (int n = 0; n < num_nurses; n++) {
      const IntVar var = slots[n][0];
      this_nurse_vals.push_back(var);
    }
    cp_model.AddEquality(LinearExpr::Sum(this_nurse_vals), 1);
  }


You create the vector, then use push back. So the first 3 elements of
the vector are default variables.

We will make the solver crash in this case.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 4 juil. 2019 à 06:23, Bob Baxley <notifications@github.com> a
écrit :

**Comment by gte620v** [comment]
I don't really understand the problem, but if i replace `this_nurse_vals.push_back(var);` with `this_nurse_vals[n] = var;` then it works.  Thanks for your help! 

(feel free to close)
