### ISSUE TITLE
Routing - driver / vehicle 

### ISSUE THREAD

**Issue by nechamam** [google/or-tools#1402]
Hi,
Is it possible to assign driver to vehicle during routing optimization,
or should I calculate it before optimization? (using cp solver or something like that)

**Comment by Mizux** [comment]
What do you mean by driver ? the routing library only deal with node (to visit) and vehicle.

Otherwise it's an assignement problem and you should look at the SAT solver samples

**Comment by nechamam** [comment]
thanks @Mizux  you answered my question.
