### ISSUE TITLE
Acquiring cumul in transit callback

### ISSUE THREAD

**Issue by mariamatz** [google/or-tools#1404]
Hello!
I'm solving a VRP and trying to aquire the cumul (total travel cost) in dimention's transitCallback function without success so far.
Can someone help me access it?
Thank you!

**Comment by lperron** [comment]
You can use the method in this example:
https://developers.google.com/optimization/routing/vrp#printer

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by mariamatz** [comment]
I'm trying to access it during the search/solving process.
The PrintSolution function requires a const Assignment& solution.
Is there a way to access this const during the search/solving process?

**Comment by lperron** [comment]
Get the variable, use Min() or Max()., Or Value() on it.

How do you run your code during search ?

**Comment by mariamatz** [comment]
I used the RoutingModel::AddDimension() and gave the required callback.
```
MyData::getCost(NodeIndex from,NodeIndex to) {
    const operations_research::RoutingDimension *time_dim = _routing.GetMutableDimension( "time"  );
     _routing.ActiveVar(0)->Value();
    return costs[from.value()][to.value()];
}
routing.AddDimension(
	routing.RegisterTransitCallback(
		[&myData, &manager](int64 i, int64 j) {
			return myData.getCost(manager.IndexToNode(i), manager.IndexToNode(j));
		}
	),
	time_horizon,
	time_horizon,
	/*fix_start_cumul_to_zero=*/true,
	"time"
);
```
Here (getCost) is where I want to access the current total cumul.

When I try to access Value() it says that it is unbound.
`F0704 16:50:14.465070 32334 constraint_solveri.h:1700] Check failed: value_ != kUnboundBooleanVarValue (2 vs. 2) variable is not bound`

**Comment by lperron** [comment]
Yes, during search, the variables do not yet have a fixed value.

**Comment by mariamatz** [comment]
So is there any other way to access this? How can I get the temporary assignment (the order of nodes for this stage of search)?

**Comment by lperron** [comment]
During search, the order is not fixed, nor totally computed.
Each variable as a set of possible values.

I wonder what you are trying to achieve. It you want to use the current
cumul to compute a different transition between two nodes, this is strictly
forbidden.
On the one hand, it will break solver assumptions, and on the other hand,
as the solver caches the result of the transition calls, you will not be
called when you expect it.

Was it your goal ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by paultrow** [comment]
See also
https://devsite.googleplex.com/optimization/routing/vrp#distance_dimension.
The first paragraph has a link to this page:

https://devsite.googleplex.com/optimization/routing/dimensions

**Comment by mariamatz** [comment]
Thank you for all your replies.
Yes actually this is my goal. I am trying this instead of using the dependent dimension because dependent dimension is EXTREMELY slow.
Is there any other way to achieve that?

**Comment by lperron** [comment]
No. Sorry.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by mariamatz** [comment]
Ok! Thank you so much for your time, I really appreciate your help! Have a good one!

**Comment by lperron** [comment]
Actually, it depends on how many nodes are impacted.

If you have one node where traffic depend on the time, you could imagine
duplicating this node, adding time windows on these, and changing the
dimension matrix to penalize rush hour.
It may work, but it will not scale if the matrix changes dramatically.

Another way would be to use an average distance matrix, get the solution
from this one, then analyze it.
If you have 2 rush hour period (morning 7 to 9), evening (4 to 7).
force all visits to stay inside their computed period (rush hour 1, non
rush-hour, rush-hour 2) and change the matrix to have better distances.
Then reoptimize. Most likely it will drop some nodes that becomes
impossible in rush hour, but you will get a better plan.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
