### ISSUE TITLE
Runtime error : SWIG std::function invocation failed, in azure databricks

### ISSUE THREAD

**Issue by gayatripadhi** [google/or-tools#1406]
https://stackoverflow.com/questions/56900196/runtime-error-swig-stdfunction-invocation-failed-in-azure-databricks

**Comment by gayatripadhi** [comment]
#or-tools #1330 #1022 
@Mizux , kindly help.

**Comment by lperron** [comment]
Can you reproduce outside of azure ?

**Comment by gayatripadhi** [comment]
@Iperron, I made a sample csv dataset to check in Jupyter notebook, and I am getting the results there.

**Comment by lperron** [comment]
Does it work in python on a workstation, outside of custom environment.

Le sam. 6 juil. 2019 à 09:11, Gayatri Padhi <notifications@github.com> a
écrit :

**Comment by gayatripadhi** [comment]
I am using Jupyter notebook on Anaconda

**Comment by lperron** [comment]
Can you try it outside of Jupiter ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le sam. 6 juil. 2019 à 09:27, Gayatri Padhi <notifications@github.com> a
écrit :

**Comment by gayatripadhi** [comment]
Laurent, I used Azure Databricks, which is throwing the mentioned error. and in Jupyter its giving me the result. its not throwing error.

**Comment by gayatripadhi** [comment]
I have added the distance matrix as mentioned over stackoverflow.

**Comment by lperron** [comment]
Then I cannot help you, sorry.

Le sam. 6 juil. 2019 à 09:44, Gayatri Padhi <notifications@github.com> a
écrit :

**Comment by gayatripadhi** [comment]
![image](https://user-images.githubusercontent.com/26744707/61268402-f489bf80-a7b8-11e9-80d8-5c9373635eda.png)
![image](https://user-images.githubusercontent.com/26744707/61268415-fe132780-a7b8-11e9-89ef-ddf42bc54f09.png)

**Comment by gayatripadhi** [comment]
The issue is resolved, thank you everyone!
