### ISSUE TITLE
#1330 #1022

### ISSUE THREAD

**Issue by gayatripadhi** [google/or-tools#1407]
#1330 #1022 
https://github.com/paulgb/penkit/issues/2
@Mizux , kindly help.

_Originally posted by @gayatripadhi in https://github.com/google/or-tools/issues/1406#issuecomment-508702489_

**Comment by lperron** [comment]
Why are you linking unrelated issues ?

**Comment by gayatripadhi** [comment]
Closing the issue. Apologizes.
