### ISSUE TITLE
ortools/gen/ortools/util/sorted_interval_list_python_wrap.cc file

### ISSUE THREAD

**Issue by DennisYurichev** [google/or-tools#1409]
Pardon be...
Cloned git repo today ( f3fd201e68cf75b7720ff5c3cadc599a1d02b54b )
Then "make third_party" and "make all":

`I/home/dennis/tmp/or-tools/dependencies/install/include -I/home/dennis/tmp/or-tools/dependencies/install/include -I/home/dennis/tmp/or-tools/dependencies/install/include -I/home/dennis/tmp/or-tools/dependencies/install/include -I/home/dennis/tmp/or-tools/dependencies/install/include/coin -I/home/dennis/tmp/or-tools/dependencies/install/include -I/home/dennis/tmp/or-tools/dependencies/install/include/coin -I/home/dennis/tmp/or-tools/dependencies/install/include -I/home/dennis/tmp/or-tools/dependencies/install/include/coin -DUSE_CLP -I/home/dennis/tmp/or-tools/dependencies/install/include -I/home/dennis/tmp/or-tools/dependencies/install/include/coin -I/home/dennis/tmp/or-tools/dependencies/install/include -I/home/dennis/tmp/or-tools/dependencies/install/include/coin -DUSE_CBC -DUSE_GLOP -DUSE_BOP -DABSL_MUST_USE_RESULT     -I. -c++ -python -py3 -DPY3 \
 -o ortools/gen/ortools/util/sorted_interval_list_python_wrap.cc \
 -module sorted_interval_list \
 ./ortools/util/python/sorted_interval_list.i
make: I/home/dennis/tmp/or-tools/dependencies/install/include: Command not found
makefiles/Makefile.python.mk:470: recipe for target 'ortools/gen/ortools/util/sorted_interval_list.py' failed
make: [ortools/gen/ortools/util/sorted_interval_list.py] Error 127 (ignored)
sed -i -e 's/< long long >/< int64 >/g' \
 ortools/gen/ortools/util/sorted_interval_list_python_wrap.cc
sed: can't read ortools/gen/ortools/util/sorted_interval_list_python_wrap.cc: No such file or directory
makefiles/Makefile.python.mk:470: recipe for target 'ortools/gen/ortools/util/sorted_interval_list.py' failed
make: *** [ortools/gen/ortools/util/sorted_interval_list.py] Error 2
make: *** Waiting for unfinished jobs....
`

Some additional dependency should be installed?

**Comment by lperron** [comment]
You miss the swig binary

**Comment by DennisYurichev** [comment]
Thanks!
