### ISSUE TITLE
Python examples are not Python 3 compatible, yet.

### ISSUE THREAD

**Issue by mjfwest** [google/or-tools#141]
This is known, and mainly due to print statements/functions but also some lists/range issues.

**Comment by mjfwest** [comment]
I've fixed most of them and will submit a pull request when finished.

**Comment by mjfwest** [comment]
See pull #142 .

**Comment by mjfwest** [comment]
I believe all examples are now updated to work in Python 2.7 and 3.5.

**Comment by lperron** [comment]
Thanks,

I fixed the remaining 3 examples in python 2.7



Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-01-20 10:56 GMT+01:00 Martin West <notifications@github.com>:
