### ISSUE TITLE
CP-Sat Python speed up model building

### ISSUE THREAD

**Issue by Phibedy** [google/or-tools#1410]
My model needs about 200 seconds to build and 30 to solve. A lot of time is lost in ortools input type checks (created a flamegraph). Afterwards I "monkey-patched" the check methods which reduced the time by about 20-30%. Do you have any experience if it is worth porting it to C++/some other language?

**Comment by lperron** [comment]
If performance is critical, do not use python :-)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Phibedy** [comment]
Of course, I just hoped that you have some benchmarks around so I don't have to create them on my own :ice_cream:

**Comment by gregy4** [comment]
Maybe jython (python implementation over java) could be candidate to test it with minimal effort on porting. In result you will of course you java api but code written in python :-)

**Comment by lperron** [comment]
Just a comment, we do not support any non official python implementation (Cython, Pypy, jython...).
They may work, but I will not debug issues with them :-)

**Comment by PriyatamNayak** [comment]
Any support for cython or jython?

**Comment by lperron** [comment]
No. Contributions are welcome though :-)

Le mer. 2 déc. 2020 à 02:50, PriyatamNayak <notifications@github.com> a
écrit :

**Comment by gregy4** [comment]
For jython no action is probably needed since you can use java binding and
jython is very good as one to one replacement to java code.

st 2. 12. 2020 v 2:50 odesílatel PriyatamNayak <notifications@github.com>
napsal:
