### ISSUE TITLE
"make test_cc" failing with undefined reference errors in libortools.so 

### ISSUE THREAD

**Issue by ForrestBurt** [google/or-tools#1411]
I'm attempting to build the latest release for C++ per the instructions on this page:

https://developers.google.com/optimization/install/cpp/source_linux

When I try to run "make test_cc", I get the output in the attached file. I'm using gcc 7.2.0 on CentOS 7 Linux. It seems to compile fine, no obvious errors there. Attached is the terminal output I get when trying to run "make test_cc".

[ortools.txt](https://github.com/google/or-tools/files/3363358/ortools.txt)

**Comment by lperron** [comment]
Fresh checkout ? or upgrade from an older version ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 5 juil. 2019 à 17:50, ForrestBurt <notifications@github.com> a
écrit :

**Comment by ForrestBurt** [comment]
Fresh checkout.

**Comment by lperron** [comment]
I just build 7.2 on centos without any issue

Is gcc 7.2 the default compiler ?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 5 juil. 2019 à 17:58, ForrestBurt <notifications@github.com> a
écrit :

**Comment by ForrestBurt** [comment]
which gcc gives me 7.2.0. This is being built in a cluster environment, so once the module for gcc is loaded, it'll use it. Also, apparently we've got different versions, I was under the impression that the included file on that page was the latest; I'm trying to build 7.1, though I'll give 7.2 a try.

**Comment by ForrestBurt** [comment]
Update, I've tried 7.2, but found that it throws about the same errors. I'm trying it locally with some updated packages, and I'll post again once I get the results.

**Comment by lperron** [comment]
No news, closing.
