### ISSUE TITLE
Get sequential solution or run until a better solution is not found

### ISSUE THREAD

**Issue by TeodoraB21** [google/or-tools#1414]
Hello!

I am using PARALLEL_CHEAPEST_INSERTION and GUIDED_LOCAL_SEARCH and I set the time for 10 minutes. But if after 2 minutes, a better solution is not found I want it to stop searching and return me the best one found so far. Is there a way I can do this?

I mean it searches for 2 minutes, then for another 2 minutes, and then for another 2 minutes and if the last one is not better than the previous one, I want it to stop searching.

If I search for a solution for 2 minutes, and then that solution to give it as a parameter for the next one and to let it search for 2 minutes, the last solution will not be the same as if I would have left it search for 4 minutes straight. So I can't do it this way.

**Comment by lperron** [comment]
Search for 2 minutes. Store the best solution, if not restart search with the previous best solution for 2 more minutes...

In another words, do it externally.

Would that work ?
