### ISSUE TITLE
Problem load initial assignment to solver when using dependent dimension 

### ISSUE THREAD

**Issue by aloumpas** [google/or-tools#1415]
Hello,

I am trying to use the save/load assignment methods in order to give an initial solution to the solver. In my problem I am using the dependent dimension methods of routing model. The code that loads the assignment is the following

```C++
std::vector<std::vector<int64>> initial_routes = {  {1,3,2,4,...} }
routing.CloseModelWithParameters(parameters);
initial_solution = routing.ReadAssignmentFromRoutes(initial_routes, false);
```
and next i call the solver like this
```C++
// Solve
const operations_research::Assignment *solution = routing.SolveFromAssignmentWithParameters(
    initial_solution,
    parameters
);
```
The problem is that the solver, depending on the order of the initial assignment, sometimes continues and try to solve the problem and some others doesn't(Stops immediately - timeout is 15s). When solver doesn't try to solve the problem the output is the following
```
Loading...
I0710 07:49:28.216702  2608 search.cc:252] Start search (memory used = 58.97 MB)
I0710 07:49:28.217578  2608 search.cc:252] Root node processed (time = 0 ms, constraints = 1034, memory used = 59.10 MB)
I0710 07:49:28.560524  2608 search.cc:252] Solution #0 (10026417, time = 343 ms, branches = 1284, failures = 637, depth = 647, memory used = 65.04 MB)
I0710 07:49:28.675071  2608 search.cc:252] 10000 branches, 458 ms, 9357 failures, tree pos=0/9262/9262 minref=1 max=9262
I0710 07:49:28.837050  2608 search.cc:252] 20000 branches, 620 ms, 19357 failures, tree pos=9262/19262/19262 minref=1 max=19262
I0710 07:49:28.978796  2608 search.cc:252] 30000 branches, 762 ms, 29357 failures, tree pos=19262/29262/29262 minref=1 max=29262
I0710 07:49:29.169302  2608 search.cc:252] 40000 branches, 952 ms, 39357 failures, tree pos=29262/39262/39262 minref=1 max=39262
I0710 07:49:29.323110  2608 search.cc:252] 50000 branches, 1106 ms, 49357 failures, tree pos=39262/49262/49262 minref=1 max=49262
I0710 07:49:29.727479  2608 search.cc:252] Solution #1 (10026372, objective maximum = 10026417, time = 1510 ms, branches = 57009, failures = 56360, depth = 12, memory used = 86.31 MB)
I0710 07:49:30.772680  2608 search.cc:252] Finished search tree (time = 2555 ms, branches = 58152, failures = 57513, memory used = 90.48 MB)
I0710 07:49:30.773061  2608 search.cc:252] End search (time = 2556 ms, branches = 58152, failures = 57513, memory used = 90.48 MB, speed = 22751 branches/s)

Solving...
I0710 07:49:30.773146  2608 search.cc:252] Start search (memory used = 90.48 MB)
I0710 07:49:30.773921  2608 search.cc:252] Root node processed (time = 0 ms, constraints = 1034, memory used = 90.48 MB)
I0710 07:49:30.877794  2608 search.cc:252] Finished search tree (time = 104 ms, branches = 58910, failures = 57896, memory used = 90.48 MB)
I0710 07:49:30.878343  2608 search.cc:252] End search (time = 105 ms, branches = 58910, failures = 57896, memory used = 90.48 MB, speed = 561047 branches/s)
Took: 0.105262s
Routing Fail!
```

**Comment by jmarca** [comment]
Which version of OR Tools are you using?  And is the issue something that comes and goes with identical inputs, or does the call to `routing.SolveFromAssignmentWithParameters` work every time with input A, and fail every time with input B?  That is, can you show an input/problem set that exhibits the behavior?

**Comment by aloumpas** [comment]
Hello,

I am using or-tools 7.1.

No, identical inputs give the same results every time.

After some experiments I found out that the dimension's capacity(horizon) plays a significant role to this problem. For example for a certain sequence 1,2,3 with a certain horizon 10 hours, I have the problem I described above. But if I start to lower down the horizon at some point the solver starts searching and finds some solutions.

**Comment by jmarca** [comment]
If you show some code and data I can help you more, otherwise there's not much to go on here.  It is true that if you have a demand that falls outside of the horizon for the dimension, then the solver will bail out right away.  Perhaps that is the problem?  I always scan both vehicle operating hours and node pickup/delivery time windows to make sure they fall inside the modeled time period.

**Comment by aloumpas** [comment]
Hello,

Thank you for your help, 

I don't have an example right now. I will work on it and look at it further and if I found something more specific to show and describe i will come back. Also, i will consider what you are suggesting.

**Comment by jmarca** [comment]
Okay good luck.

One thing to keep in mind is that a dimension isn't really a thing.  All the various flavors of calling [add dimension](https://developers.google.com/optimization/reference/constraint_solver/routing/RoutingModel/#AddDimension) are really just setting up a variable with some rules on its behavior.  

So a time dimension isn't really "time" per se.  It is just a number that is incremented or decremented according to rules you've set up, including increasing value every time the vehicle "moves" from point to point, and increasing every time the vehicle dwells at a point.  The "slack" part just tells the model if the variable has to be strictly continuous, or whether it can "jump" to a new value.  

So the "horizon" should be understood to be the maximum value that the accumulating variable is allowed to reach.  If a candidate route forces a violation of that maximum, or if it requires a waiting time that is large than the slack you've given, or if any other aspect of any of the dimensions you've set up are violated by your candidate route, then the solver will fail.

I had an issue with generating candidate routes once.  Actually, it was a case where I could construct a candidate route analytically very quickly, but the solver would spend days spinning its wheels not finding that initial solution.  Anyway, there was some possibility that the candidate route I set up would be impossible, so I set up a short loop that would drop parts of the candidate route if the initial solution failed.  By inspecting those parts of the route that failed, I discovered things like a delivery time that was impossible given the corresponding pickup time, etc...in other words, the input data was impossible.

**Comment by lperron** [comment]
Please do not use dependent dimensions. 
They are slow and not ready for prime time.  Personally, as you mostly rely on forecasted traffic, the error rate is high, and you will get solutions of equivalent qualities by solving in two phases:

  - solve with peak hour traffic.
  - Freeze visits in peak hour.
  - solve the residual visits with off hour traffic.

My 2 cents.
