### ISSUE TITLE
Is there a search strategy of ALNS for VRP?

### ISSUE THREAD

**Issue by mmanishh** [google/or-tools#1416]
Is there a search strategy of ALNS for VRP ?
If no, how can we implement ALNS with or tools. I have found here https://developers.google.com/optimization/routing/routing_options that there is the options of 

- Greedy Descent
- Guided Local Search
- Tabu Search 
- Stimulated Annealing

but not ALNS , will the option of ALNS will be added in future ?

**Comment by lperron** [comment]
There is a LNS parameters, but no adaptative version.
We have no plan to implement it. Usually LNS approaches are way slower that standard LS.
