### ISSUE TITLE
Return value of routing.GetDimensions: SwigPyObject not iterable

### ISSUE THREAD

**Issue by sghb** [google/or-tools#1417]
Hi,

in version 7.2 via Python, there is a call `routing.GetDimensions()`.  How does one use it?  Let's say
```python
r = routing.GetDimensions()
```
For `list(r)` I get
```
TypeError: 'SwigPyObject' object is not iterable
```
and for `r[0]` it is
```
TypeError: 'SwigPyObject' object is not subscriptable
```

Same for `routing.GetAllDimensionNames()`.  Is there something missing?

**Comment by lperron** [comment]
These functions are not correctly wrapped, and thus should be removed from
the API.

**Comment by lperron** [comment]
For the time being, as you are creating the dimensions, you can store them in the python program.
