### ISSUE TITLE
Help needed in creating shifts

### ISSUE THREAD

**Issue by erma07** [google/or-tools#1418]
What I'm trying to do is the following:

for all t:
    sum(demands[i]
        if (start(intervals[t]) <= t < end(intervals[t])) and (t is present)) >= capacity
   

I have created the following python code, that has some logic faults, so it does not work as expected. Could someone help me figuring out how to do this? The end result should look smth like that at the end:
<img width="1154" alt="Screenshot 2019-06-30 at 20 08 03" src="https://user-images.githubusercontent.com/16502919/61051397-94c69980-a3f1-11e9-9a09-c1685300b258.png">
`times=[0,60,120,240,300,330,360,420,480,540,720,900,960,1110,1200,1290]
needed = [0,4,3,9,9,16,16,8,12,15,20,17,20,12,14,12]
max_time = 240
min_time = 60
i=0
possible_shifs=[]
shifs=[]
for t in range(len(times)):
    shift_need = needed[t]
    start = model.NewIntVar(t, t, 'start_%i' % (t))
    end = model.NewIntVar(t+min, t+max_time, 'end_%i' % (t))
    duration = model.NewIntVar(min_time, max_time, 'duration_%i' % (t))
    presence = model.NewBoolVar('presence_%i' % (t))
    interval = model.NewOptionalIntervalVar(start, duration, end, presence, 'interval_%i' % (t))
    capacity = model.NewIntVar(0, 99, 'capacity_%i' % (minute))
    model.Add(capacity == 0).OnlyEnforceIf(presence.Not())
    model.Add(capacity > 0).OnlyEnforceIf(presence)

    shifts.append(s_struct(start=start,end=end,startt=t,presence=presence,interval=interval))
    possible_shifs.append(i)

    if shift_need > 0:
        capacity_list=[]
        for item in possible_shifs.copy():
            if shifts[item].endd < minute:
                possible_shifs.remove(item)
            else:
                usable_end = model.NewBoolVar('usable_end_%i_%i' % (t,item))
                model.Add(shifts[item].end >= minute).OnlyEnforceIf(usable_end)
                model.Add(shifts[item].end < minute).OnlyEnforceIf(usable_end.Not())
                model.Add(usable_end == shifts[item].presence)

                capacity = model.NewIntVar(0, 99, 'capacity_%i_%i' % (minute,item))
                model.Add(capacity <= shifts[item].capacity).OnlyEnforceIf(usable_end)
                model.Add(capacity == 0).OnlyEnforceIf(usable_end.Not())

                capacity_list.append(capacity)

        model.Add(sum(capacity_list) >=  shift_need)

    i += 1`

**Comment by erma07** [comment]
I have created another version of the script, but still not working, now it's only giving me 13 hour shifts and the acceptable need vs shift capacity ratio is also off. Could anyone help me figure out what i'm doing wrong?

[shifts.py.zip](https://github.com/google/or-tools/files/3388758/shifts.py.zip)

**Comment by lperron** [comment]
Can you start by explaining the data and the constraints ?

**Comment by erma07** [comment]
The "times" and "needed" arrays contain the change of workers need in time. Times 0,60,120, needs 0,4 means 0-60 need of workers 0, 60-120 workers 4 etc.
shift_min_duration = 6 hours
shift_max_duration = 13 hours
shift_preferred_duration = 8 hours
shift_max_capacity = 15 workers

Need to create x amount of shifts with y amount of worker capacity and with the other described constraints so that the amount of workers at any point of time would be min(worker_count>=worker_need)

A next version that works a bit better because the durations are fixed, but not good enough.
[shifts.py.zip](https://github.com/google/or-tools/files/3394201/shifts.py.zip)

**Comment by lperron** [comment]
Why don't you create all possible valid shifts (start - end) and select the
number of each type in the optimization model ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by erma07** [comment]
What do you mean by "select the number of each type in the optimization model"? The amount of shifts  len(6-13) is not fixed. I need to find the amount of shifts with the length of 360-780 minutes and preferred length 480 so that at any point of time there would be min(worker_count>=worker_need). In the best scenario it would be worker_count==worker_need.

**Comment by lperron** [comment]
Create all possible shifts. There aren't that many.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
