### ISSUE TITLE
parameter num_search_workers doesn't work when great then 8

### ISSUE THREAD

**Issue by mojinfu** [google/or-tools#1420]
my project is running on an 48-logic-core computer 

when I set parameter num_search_workers = 6   , it works perfectly. ( takes 600% cpu )
''' pyhton
        self.solver.parameters.search_branching = self.rule.search_branching
        self.solver.parameters.max_time_in_seconds = 10000
        self.solver.parameters.log_search_progress = True
        self.solver.parameters.num_search_workers = 6
'''

but  when I set parameter num_search_workers = 7 or > 7   , it  still works with 600% cpu 

Are there any additional parameters that need to be set ?

**Comment by lperron** [comment]
I currently does not use more that  threads until it has found a first
feasible solution for the LNS to kick in.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Please note that this is completely changing for the next version.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by mojinfu** [comment]
i understand the reason is that “This tool contains only six algorithms for finding solutions，and every algorithm to another is can run on different thread  .  
but single algorithm can not run on two thread “
is that correct?

**Comment by lperron** [comment]
Yes and yes.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Shared search tree does not work on SAT, and is usually bad in general for
other solvers.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by mojinfu** [comment]
The next version of ortools , will it be changed ?
or it is still can not be ...

**Comment by lperron** [comment]
We are working very actively on this part.
But we will never implement search tree sharing.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
