### ISSUE TITLE
[dotnet] How to identify the Google.OrTools assembly itself

### ISSUE THREAD

**Issue by mwpowellhtx** [google/or-tools#1422]
Hello,

I am making some decisions about how to accurately identify the path for the ``proto`` file distributed with the Google.OrTools package.

However, when I probe ``typeof(Google.OrTools.Sat.CpSolver).Assembly.Location``, perhaps half-expectantly, finding instead:

```
G:\Source\path\to\packages\google.ortools.runtime.win-x64\7.1.6720\runtimes\win-x64\...
```

Instead of, let's say:

```
G:\Source\path\to\packages\google.ortools\7.1.6720\ref\netstandard2.0\...
```

I've tried a couple different ways to identify the assembly reference, including ``GetType().Assembly.GetReferencedAssemblies.Where(/*names are Google.OrTools*/)``, yet when I attempt to *see* the reference assembly via name, the name of the reference is correct, ``Google.OrTools``, but when I ask for its location, it tells me the run-time location.

So... My bottom line here is, I'd like to identify the path of the assembly in order to better leverage the ``proto`` content. If possible, can these be factored into the run-time assembly *content*, as contrasted with the top-level API surface area?

For now, my workaround is to embed the API surface area *content* as resources, but this does not respond very well to updated in *Google.OrTools*, now does it? Rather, I'd like to respond seamlessly with updates and just use the referenced assembly location itself. But for the described snafu identifying the ``Assembly.Location``.

**Comment by mwpowellhtx** [comment]
One approach we could take:

1. Given the referenced ``AssemblyName``, 
1. Assuming the Google versioning convention, *Major.Minor.Build*, literally dropping the *Build* element of the *System.Version* from the string, i.e. ``7.1.6720`` versus what the ``Version`` actually tells us, i.e. ``7.1.6720.0``.
1. Then inferring the top-level API surface area, ``Google.OrTools``.

We could do that, but I like to work directly with the elements at my disposal and not second guess names that have any chance whatsoever to change in the future, however remote.

**Comment by lperron** [comment]
Can you list all resources in the assembly, and record proto files ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by mwpowellhtx** [comment]
@lperron At the moment, the sufficient path forward for me is to infer some path decisions based on the current directory layout, however, this does not seem especially robust. Not that I expect the directory structure should change overnight, but with Microsoft in these things, one never truly knows for certain.

I start from the referenced assembly, which happens to be the runtime assembly (first assumption), literally based on, ``typeof(Google.OrTools.Sat.CpSolver).Assembly``, decide what its path is; then infer a content directory based on that (second assumption); which includes the first two dot delimited words from the assembly name ``google.ortools.runtime.win-x64`` (third assumption); which also includes an interpolation of the assembly's version's first three values, literally, ``version.ToString(3)`` in *dotnet* terms (fourth assumption); and then calculate a path relative to the currently executing assembly.

That being said, it is possible to probe embedded resources in an assembly manifest, but I think that would need to land in the runtime assembly (or assemblies), not the API surface area, if possible. Or at least, attempts to reference the API surface area have been met with that being the likelihood.

Assuming many of those parts are fairly stable, I can work with the current path and we have a fairly robust path forward, I think, that can respond to updates in the package fairly seamlessly. It would be stronger, I think, to probe the assembly manifest embedded resources.

**Comment by lperron** [comment]
Closing the issue now. Please reopen if Microsoft decides to change thing.
