### ISSUE TITLE
Support pairs with disjunctions

### ISSUE THREAD

**Issue by matthewrj** [google/or-tools#1423]
I am using pickup and delivery sets where each pickup and delivery set is a disjunction between 2 alternatives with max_cardinality of 1 and a penalty cost. The solver does not seem to be able to move away from the initial solution found by the FirstSolutionStrategy significantly. It does eventually on small toy examples but it takes an excessive amount of time. I noticed here https://github.com/google/or-tools/blob/v7.1/ortools/constraint_solver/routing_neighborhoods.cc#L105
https://github.com/google/or-tools/blob/f3fd201e68cf75b7720ff5c3cadc599a1d02b54b/ortools/constraint_solver/routing_neighborhoods.cc#L103-L105
and in other places in the file pickup and delivery sets are not yet supported.

I am willing to try implement this support but need guidance.
Here https://github.com/google/or-tools/blob/v7.1/ortools/constraint_solver/constraint_solveri.h#L1226 it says you only need to override MakeNeighbor() and you should not override MakeOneNeighbor() or MakeNextNeighbor() however they are overridden in MakePairActiveOperator. Is there a reason for this?
My plan for implementing the support in MakePairActiveOperator is to instead of just producing a neighbor for each inactive pair (with the pair activated), produce a neighbor for each combination of pickup-delivery indicies (with them activated and any other indicies deactivated). 
With MakeNeighbor(), is the idea to produce the next neighbor each time it is called and return true if there may be more to come and false if you cannot produce any more for the current set of BaseNodes?

**Comment by matthewrj** [comment]
I am working on this here #1426

**Comment by lperron** [comment]
Thanks. Closing the issue.
As I said in the PR, we are looking and we are going to integrate it or rewrite it.

Thanks again!
