### ISSUE TITLE
How to optimize the task allocated to the vehicles so that distance travelled by each vehicle is same or equivalent?

### ISSUE THREAD

**Issue by gayatripadhi** [google/or-tools#1427]
I want to uniformly distribute the task in a way, each vehicle travel equivalent distance.
For eg. : 
Vehicle 1 : 50 miles
Vehicle 2 : 45 miles 
Vehicle 3 : 55 miles

Each vehicle need to travel a maximum distance of 50 miles.

![image](https://user-images.githubusercontent.com/26744707/61364675-eebcd880-a8a3-11e9-853a-2f78f9f92b77.png)

**Comment by gayatripadhi** [comment]
@lperron @Mizux

**Comment by lperron** [comment]
There are no good solution. I would use soft bounds on the span of each vehicles to try to constrain it.
But any hard constraint will likely produce infeasible solutions.
