### ISSUE TITLE
[help] Garbage truck: Capacity , Pickup&Delivery, Time Window VRP.

### ISSUE THREAD

**Issue by pietrucha** [google/or-tools#1428]
Garbage trucks have capacity (i.e.: 100), start from depot, drive through points (weight i.e.: 2) where collect garbage bins, when it is full (or at the end of the day) drive to garbage dump.

This problem is complex. I try model this in ORTools but i cannot figure it out. How combine Capacity and Pickup & Delivery in my scenarion (there is single delivery point and multiple pickups)? Could You can help me?

I assume that Time Window Constraint should have each visited points from (i.e. 8-16).
Thanks

**Comment by neeman1** [comment]
Any updates?

**Comment by pietrucha** [comment]
No

**Comment by jmarca** [comment]
I think this is straightforward to model as a pickup and delivery problem, once you wrap your head around how to think about pickup and delivery nodes.  

Model it like this.  Each location `i` has a certain number of bins with some weight W.  The bin origin is the location `i`, and the destination is the dump, but it has to be a unique node, so lets call it `d_i`.  Your demand callback takes a single parameter for the node, and if the node is a pickup location `i`, it replies with the appropriate weight.  If the node is the dump node for i, `d_i`, then the callback function replies with the negative of the pickup weight at `i`, reflecting that the load is dropped off and the occupied capacity is restored.

The dump trucks can have the same capacity, or a vector of capacities, following the usual approach.  When the total picked up weight exceeds the capacity, the truck must "deliver" each of its garbage loads to their destinations at the dump.  These dummy nodes are all the same location, of course, so the travel cost from `d_1` to `d_2` is zero, but the "demand" at `d_1` is the negative of the pickup at `1`; the demand at `d_2` is the negative of the pickup at `2`, and so on.

You can set time windows on both pickups (the `i` nodes) and the dump (the `d_i` nodes), again following the usual way to set time windows.

The trick is to get over the fact that the dump is one location in the real world, and instead recognize that it is many nodes in model space.

Some other fun wrinkles might be requiring that the truck completely empty all of its garbage when visiting the dump, minimizing the weight carried per mile so as to reduce fuel costs, etc etc.

**Comment by pietrucha** [comment]
@jmarca thank You very much. 
My conclusion: for simple model Pickup and Delivery problem, solving works quiet good.
I have some wired feeling that I have to split collecting garbage bins to two or more days. In time window there is no chance to model it. Am I right?

**Comment by pietrucha** [comment]
in case:
```python
search_parameters.first_solution_strategy = (routing_enums_pb2.FirstSolutionStrategy.PARALLEL_CHEAPEST_INSERTION)
```
finished immediately with status : 2 -> ROUTING_FAIL

**Comment by jmarca** [comment]
On Mon, Aug 19, 2019 at 01:07:25AM -0700, pietrucha wrote:
> @jmarca thank You very much. 
> My conclusion: for simple model Pickup and Delivery problem, solving works quiet good.
> I have some wired feeling that I have to split collecting garbage bins to two or more days. In time window there is no chance to model it. Am I right? 

Yes you can model it I'm sure.  You can require that the vehicles
return to depot overnight (so even though the time window at the
pickup location is active, the vehicles are all "busy" serving their
"sleep overnight" "pickup" task.  Or you can split the track bin into
multiple logical (dummy) pickups and deliveries to the dump, but link
all of them with a disjunction such that only one of the logical set
can be served.  Then each of the N bins can have its own time window
tailored to the needs of the day (say Saturday pickup must be later
than weekday pickup, etc).


> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/google/or-tools/issues/1428#issuecomment-522460146

-- 

James E. Marca

**Comment by jmarca** [comment]
As to your second question, you can't parallel search in transportation problems in OR Tools.  Single thread only.

Without seeing a lot more of your code, I can't really hazard a guess as to why your solver run is failing for such a small problem.  And that *is* a small problem: 

>  (12 nodes - 1 depot, 11 bins, 1 dump - so I have distance & time matrix 24x24 ) 

is tiny, you should have no trouble solving it.  My guess is you've messed up the specification of the time windows in the dimensions definitions.

As to the solution strategy questions, the first solution strategy is variable---I usually go with parallel cheapest insertion as a first try, but in almost every non-trivial case I've ever set up, at some point I'll try almost all of the initial solutions to see what works the best.  Very problem dependent.  For example, I just cut and paste this from an old project:

```python
    search_parameters.first_solution_strategy = (
        # routing_enums_pb2.FirstSolutionStrategy.LOCAL_CHEAPEST_ARC)  # works
        routing_enums_pb2.FirstSolutionStrategy.GLOBAL_CHEAPEST_ARC) # works
        # routing_enums_pb2.FirstSolutionStrategy.SAVINGS)    # works
        # routing_enums_pb2.FirstSolutionStrategy.FIRST_UNBOUND_MIN_VALUE)    # crazy suboptimal
        # routing_enums_pb2.FirstSolutionStrategy.AUTOMATIC)    # suboptimal
        # routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)   # suboptimal
        # routing_enums_pb2.FirstSolutionStrategy.PATH_MOST_CONSTRAINED_ARC) # suboptimal
        # routing_enums_pb2.FirstSolutionStrategy.PARALLEL_CHEAPEST_INSERTION) # no assignment
        # routing_enums_pb2.FirstSolutionStrategy.LOCAL_CHEAPEST_INSERTION)    # no assignment
        # routing_enums_pb2.FirstSolutionStrategy.ALL_UNPERFORMED) # no assignment
        # routing_enums_pb2.FirstSolutionStrategy.BEST_INSERTION)    # no assignment
        # routing_enums_pb2.FirstSolutionStrategy.CHRISTOFIDES)    # no assginment
        # routing_enums_pb2.FirstSolutionStrategy.SWEEP)    # no assignment
        # routing_enums_pb2.FirstSolutionStrategy.SEQUENTIAL_CHEAPEST_INSERTION) # no assignment
```

**Comment by pietrucha** [comment]
@jmarca 

> As to your second question, you can't parallel search in transportation problems in OR Tools. Single thread only.

OK.
>is tiny, you should have no trouble solving it. My guess is you've messed up the specification of the time windows in the dimensions definitions.

I made mistakes making travel time limitation. Even though, **CHRISTOFIDES** strategy return 2.

After testing on matrix 580x580 I found out that truck does'n fully unload. **Load** with `**` is when truck deliver trashes
`
Route for vehicle 3:
 0 Load(0) ->  288 Load(110) ->  289 Load(220) ->  579 Load(**110**) -> 286 Load(220)  -> 276 Load(**110**)  ->  578 Load(**0**) ->  0 Load(0)
`

Questions: 
 1. In my model each node have different numbers of bin and the load time is different. I add load time in RegisterTransitCallback like that. Does my aproach is correct?
```python
return data['time_matrix'][from_node][to_node]+ data['load_time_demands'][from_node]
```
2. How add unload time on a dump when I have multiple virtual `d_i`? It costs me only first delivery `d_i`.
3. I am also facing situation when I have to visit some node 2 times in a week. Should I create 2 virtual nodes for that kind? Complexity will be very high!!!

**Comment by jmarca** [comment]
On Wed, Aug 21, 2019 at 09:09:42AM -0700, pietrucha wrote:
> @jmarca 
> 
> > As to your second question, you can't parallel search in transportation problems in OR Tools. Single thread only.
> 
> OK.
> >is tiny, you should have no trouble solving it. My guess is you've messed up the specification of the time windows in the dimensions definitions.
> 
> I made mistakes making travel time limitation. Even though, **CHRISTOFIDES** strategy return 2.
> 
> After testing on matrix 580x580 I found out that truck does'n fully unload. **Load** with `**` is when truck deliver trashes

It will only "fully unload" if you require it to do so.

If you have one unload node for each load node, then you can forbid
travel from unload nodes to load nodes unless truck is empty, using a
conditional constraint.  Something like (I'm just typing this in, it
is not real code):

```python
for unload_node in unload_nodes:
    unload_idx = manager.NodeToIndex(unload_node)
    for possible_load_node in load_nodes:
        possible_load_idx = manager.NodeToIndex(load_node)
        if routing.NextVar(unload_idx).Contains(possible_load_idx):
            # the routing model has a possible link from unload node to load node
            # the condition: must be emtpy when arriving at pickup node
            empty_at_load = my_dimension.CumulVar(possible_load_idx) == 0
            # going from memory on this, you must double check

            # check if the next node planned really is this pickup node
            next_node_condition = routing.NextVar(unload_idx) == possible_load_idx
            # formulate a conditional expression
            expression = solver.ConditionalExpression(next_node_condition,
                                                      empty_at_load,
                                                      1)
            # apply the conditional expression to the model
            solver.AddConstraint( expression >= 1 )
```

The conditional is saying *if* the vehicle moves from unload node to
load node ( the next_node_condition is true), then the constraint that
the truck is empty at the pickup node (the empty_at_load constraint)
must also be true (must be enforced).

If it cannot be true for whatever reason, then next_node_condition
must also be false, and the truck cannot go from the unload node to
the potential load node.  Instead it must visit another unload node to
empty more trash, and try again.


> `
> Route for vehicle 3:
>  0 Load(0) ->  288 Load(110) ->  289 Load(220) ->  579 Load(**110**) -> 286 Load(220)  -> 276 Load(**110**)  ->  578 Load(**0**) ->  0 Load(0)
> `
> 
> Questions: 
>  1. In my model each node have different numbers of bin and the load time is different. I add load time in RegisterTransitCallback like that. Does my aproach is correct?
> ```python
> return data['time_matrix'][from_node][to_node]+ data['load_time_demands'][from_node]
> ```

That seems fine to me.  Try it on a tiny problem and check the timings by hand.

> 2. How add unload time on a dump when I have multiple virtual `d_i`? It costs me only first delivery `d_i`.

You'll have to be clever.

> 3. I am also facing situation when I have to visit some node 2 times in a week. Should I create 2 virtual nodes for that kind? Complexity will be very high!!! 

Yes you must create dummy nodes.  The solver can only visit a node *at
most* one time.  Once the node is visited, it is checked off the list
of places that must be visited.

And yes the complexity is going to go up with the more nodes you have
to visit in a week.  That's why these problems are fun to solve and
why I do this for my job.

> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/google/or-tools/issues/1428#issuecomment-523528629

-- 

James E. Marca

**Comment by pietrucha** [comment]
>> 3. I am also facing situation when I have to visit some node 2 times in a week. Should I create 2 virtual nodes for that kind? Complexity will be very high!!!

>Yes you must create dummy nodes.  The solver can only visit a node *at
most* one time.  Once the node is visited, it is checked off the list
of places that must be visited.

@jmarca Example nodes:
```
- 0 - depot
- 1 - visited twice a week, TW (mon-fri: 6-7 day of the week doesn't matter, this node shouldn't be visited day by day), I create 5 virtual node representing 5 days like this:
    1' mon 6-7
    1'' tue 6-7
    1''' wed 6-7
    1'''' thu 6-7
    1''''' fri 6-7

- 2 - visited once a week, TW (mon-fri: 6-14, day of the week doesn't matter),
    2' mon 6-14
    2'' tue 6-14
   
- 3 - ...

1000 - ...
```
When truck visit node 2'', other 2 nodes should be marked as visited. How to mark those nodes?

**Comment by jmarca** [comment]
> When truck visit node 2'', other 2 nodes should be marked as visited. How to mark those nodes?
> 

you make a disjunction.  read up on the exact semantics in the docs, but essentially

for duplicate_nodes in big_list_of_lists:
    duplicate_indices = [manager.NodeToIndex(c) for c in duplicate_nodes
    routing.AddDisjunction(duplicate_indices, some_big_penalty)


On Fri, Sep 13, 2019 at 02:23:38AM -0700, pietrucha wrote:
> >> 3. I am also facing situation when I have to visit some node 2 times in a week. Should I create 2 virtual nodes for that kind? Complexity will be very high!!!
> 
> >Yes you must create dummy nodes.  The solver can only visit a node *at
> most* one time.  Once the node is visited, it is checked off the list
> of places that must be visited.
> 
> @jmarca Example nodes:
> ```
> - 0 - depot
> - 1 - visited twice a week, TW (mon-fri: 6-7 day of the week doesn't matter, this node shouldn't be visited day by day), I create 5 virtual node representing 5 days like this:
>     1' mon 6-7
>     1'' tue 6-7
>     1''' wed 6-7
>     1'''' thu 6-7
>     1''''' fri 6-7
> 
> - 2 - visited once a week, TW (mon-fri: 6-14, day of the week doesn't matter),
>     2' mon 6-14
>     2'' tue 6-14
>    
> - 3 - ...
> 
> 1000 - ...
> ```
> When truck visit node 2'', other 2 nodes should be marked as visited. How to mark those nodes?
> 
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/google/or-tools/issues/1428#issuecomment-531167026

-- 

James E. Marca
