### ISSUE TITLE
SetSolverSpecificParametersAsString cannot delete temporary parameters file

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckxSimpleRose** [google/or-tools#1429]
I'm running or-tools (v7.1) in Python with CPLEX and am setting solver specific parameters per [here](https://github.com/google/or-tools/issues/603) with

```
solver.SetSolverSpecificParametersAsString(f"CPLEX Parameter File Version 12.8.0.0 \n CPXPARAM_Threads  {threads}")
```

It looks to be working but I can a non-stop log of the following errors:
> E0717 09:40:35.100229 209319360 linear_solver.cc:1640] Couldn't delete temporary parameters file: /tmp/parameters-tempfile-7b-56877-15b238c3ff0cc20c.prm

What is the correct way of silencing this errors (besides commenting out [this](https://github.com/google/or-tools/blob/4a0e9b1860276a021335aacb8b69e10a0d08942c/ortools/linear_solver/linear_solver.cc#L1652)) or what is the fix so these parameter files get properly deleted?

**Comment by stradivari96** [comment]
What does `ls -ld /tmp` return?

**Comment by ConstantinoSchillebeeckxSimpleRose** [comment]
![image](https://user-images.githubusercontent.com/44036468/61396316-118fc280-a88d-11e9-92e2-7e1299ddb0d6.png)

**Comment by lperron** [comment]
Silly mistake. Fixed on master.
