### ISSUE TITLE
Export LP file in Python does not support options anymore?

### ISSUE THREAD

**Issue by andreacassioli** [google/or-tools#1432]
I have just upgraded from 6.7 to 7.2 and the following code odes not work anymore:

`
content = self.solver.ExportModelAsLpFormat(obfuscated=False)
`

Now I get an exception

`
E           TypeError: ExportModelAsLpFormat() got an unexpected keyword argument 'obfuscated'
`

Same goes for `fixed_format` for MPS files. What am I missing?

**Comment by stradivari96** [comment]
Maybe related to:
https://github.com/google/or-tools/issues/1264

**Comment by lperron** [comment]
content = self.solver.ExportModelAsLpFormat(False) ?

**Comment by lperron** [comment]
Anyway, I fixed on master.

**Comment by andreacassioli** [comment]
Hi @lperron not sure what you mean `I fixed on master`. Version 7.2 seems not support named parameters as well. Is it by design? I could not find any docs on that.

**Comment by lperron** [comment]
master is post 7.2
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 22 juil. 2019 à 05:05, Andrea Cassioli <notifications@github.com> a
écrit :
