### ISSUE TITLE
New feature request: quadratic programming

### ISSUE THREAD

**Issue by rlloretb** [google/or-tools#1434]
Would it be possible to add quadratic programming as a new feature?
Most already-integrated solvers are capable of solving (SCIP, Gurobi, CPLEX, and CBC it seems as well)

**Comment by lperron** [comment]
It is being done, with the same API as the sos.  Not sure if it is usable
for now.

**Comment by rlloretb** [comment]
Thank you. I could not find an open feature on this.

**Comment by rlloretb** [comment]
Will it work on CPLEX?
When will the next major version be released? (i.e. 8.0?)

**Comment by lperron** [comment]
Cplex, most likely not without user contributions.

With the next version (7.4), we will have quadratic support for SCIP and
Gurobi (I believe) using a proto 2 input. Because it is a proto2, C# will
not be supported.

With 8.0, I intend to replace the proto2 by a proto3, breaking
compatibility. But we have not yet started implementation, so do not hold
your breath.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by rlloretb** [comment]
Now that 8.0 has been released, and SCIP comes with the binary, can quadratic programming be considered?

**Comment by lperron** [comment]
It is available if you use the protobuf API for Gurobi and SCIP.
It is still proto2, so no .NET though.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by poying** [comment]
Is there any example or documentation talk about the proto API?

**Comment by rlloretb** [comment]
Any news on QP with proto3?

**Comment by lperron** [comment]
None :-(
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by JannikDroegemueller** [comment]
Hi everyone, 
is there any progress on support for quadratic programming?
Particularly for the support of cplex?
As poying mentioned, it is quite hard to find any documentation.
The only example i found is [this java example](https://github.com/ogunheper/google-or-tools-sample/blob/55bc62064db87e33194ce3cd200a0f3a5c15b1e9/src/test/java/com/ortools/OrToolsDemoApplicationTest.java#L237).
Thanks in advance!

**Comment by lperron** [comment]
A few answers:
  - we do not support/touch/modify cplex interface. You can send a PR to
support it.
  - genuine quadratic support is implemented in math_opt. Currently it is
C++ bazel only. We will soo add other languages and cmake.

Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
