### ISSUE TITLE
Extend OR-Tools CMake Build Instructions

### ISSUE THREAD

**Issue by provinzio** [google/or-tools#1435]
It took me quite a while to figure out how I can include OR-Tools to my c++ project using CMake.

Using the code below fixed my problem finally (described earlier [here](https://github.com/google/or-tools/issues/1236#issuecomment-493370811)).

It might be worth to add a hint to the [build instructions page](https://github.com/google/or-tools/blob/stable/cmake/README.md), if this isn't considered a bug.

```
list(APPEND CMAKE_PREFIX_PATH "<>/or-tools/build/dependencies/install/")

set(GFLAGS_USE_TARGET_NAMESPACE TRUE)
find_package(ortools CONFIG REQUIRED)

add_executable(project main.cpp)
target_link_libraries(project ortools::ortools)
```

**Comment by lperron** [comment]
Not sure,

You can build or-tools using cmake and not make.
In that case, the dependencies will be built, but not in
dependencies/install/.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by provinzio** [comment]
I had to build it with `cmake -DBUILD_DEPS:BOOL=ON -H. -Bbuild -G "Unix Makefiles"`.

Only using `cmake -H. -Bbuild -G "Unix Makefiles` gave me missing dependency errors.

**Comment by lperron** [comment]
I am not the expert at all, but I believe you should do make install. This will package everything in one place.

**Comment by provinzio** [comment]
I followed the build instruction page ending with `cmake --build build --target install`. I am still not able to find the dependencies anywhere in /usr/local. They only are in `/dependencies/install/`.

**Comment by lperron** [comment]
OK. Unfortunately, Corentin is unavailable until early September.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by apmanol** [comment]
with `BUILD_DEPS=ON` the  
`cmake/ortools/ortoolsTargets.cmake` created after the installation has the following entry:
```
set_target_properties(ortools::ortools PROPERTIES
  COMPATIBLE_INTERFACE_STRING "ortools_MAJOR_VERSION"
  INTERFACE_COMPILE_DEFINITIONS "USE_BOP;USE_GLOP;USE_CBC;USE_CLP"
  INTERFACE_COMPILE_FEATURES "cxx_std_11;cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ZLIB::ZLIB;absl::base;absl::random_random;absl::raw_hash_set;absl::hash;absl::memory;absl::meta;absl::str_format;absl::strings;absl::synchronization;absl::any;gflags::gflags_static;glog::glog;protobuf::libprotobuf;Coin::CbcSolver;Coin::OsiCbc;Coin::ClpSolver;Coin::OsiClp;Threads::Threads"
  INTERFACE_POSITION_INDEPENDENT_CODE "ON"
  INTERFACE_ortools_MAJOR_VERSION "7"
)

```

which means that there are dependencies to external `cmake` targets (`absl::base`, ... ). But those targets are *not* installed with the `make install` procedure!

**Comment by jjacobsohn** [comment]
I've been using cmake and concur that the proposed change worked for me (Clang 11.1 x86, Debian).

I would also like to see appropriate .gitignore entries present by default. These are the recommended ones from github/gitignore - in my case they reduce the spurious git differences from ~6000 to 343:

CMakeLists.txt.user
CMakeCache.txt
CMakeFiles
CMakeScripts
Testing
Makefile
cmake_install.cmake
install_manifest.txt
compile_commands.json
CTestTestfile.cmake
_deps

**Comment by Mizux** [comment]
@jjacobsohn did you use "build*" as build directory ?
`cmake -S. -Bbuild ...`

FYI:
https://github.com/google/or-tools/blob/b37d9c786b69128f3505f15beca09e89bf078a89/.gitignore#L59-L62

**Comment by jjacobsohn** [comment]
no, I built in local. when I add -SBuild I get a failure in absl build. I use cmake 3.21

jeremy@toolbox-dev:~/Development/or-tools$ cmake -S. -DBUILD_DEPS=ON -Bbuild
...
[100%] Built target zlib-populate
-- Fetching ZLIB - fetched
-- Fetching Abseil-cpp
--   Populating absl
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jeremy/Development/or-tools/build/_deps/absl-subbuild
[ 12%] Performing patch step for 'absl-populate'
error: patch failed: CMakeLists.txt:41
error: CMakeLists.txt: patch does not apply
make[2]: *** [CMakeFiles/absl-populate.dir/build.make:119: absl-populate-prefix/src/absl-populate-stamp/absl-populate-patch] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/absl-populate.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
CMake Error at /usr/local/share/cmake-3.21/Modules/FetchContent.cmake:1017 (message):
  Build step for absl failed: 2
Call Stack (most recent call first):
  /usr/local/share/cmake-3.21/Modules/FetchContent.cmake:1146:EVAL:2 (__FetchContent_directPopulate)
  /usr/local/share/cmake-3.21/Modules/FetchContent.cmake:1146 (cmake_language)
  /usr/local/share/cmake-3.21/Modules/FetchContent.cmake:1189 (FetchContent_Populate)
  cmake/dependencies/CMakeLists.txt:71 (FetchContent_MakeAvailable)

**Comment by Mizux** [comment]
Try to remove the previous build directory if any `rm -rf build`, usually if config has been already run when fetch content try to reapply git patch on an already patched repo you may get this error

**Comment by jjacobsohn** [comment]
thank you, that was the problem. with a fresh clone of master the command line recommended above by @provinzio  (and is proposed to add to instructions) was successful and there are only 27 spurious diffs due to the existing .gitignore content.

**Comment by Mizux** [comment]
https://github.com/google/or-tools/tree/stable/cmake#dependencies

**Comment by jjacobsohn** [comment]
read that before I started, and that brought me to
  cmake . -DBUILD_DEPS=ON
but until this interaction I didn't understand that the .gitignore assumed building into ./build
  cmake -DBUILD_DEPS:BOOL=ON -H. -Bbuild

I agree it's best practice to build into subdirectory.

**Comment by jjacobsohn** [comment]
I tried adding the recommended cmake .gitignore entries from gitHub/gitignore, and brought the number of spurious diffs down from 27 to 3 (plus the actual diff of the .gitignore of course!).

I could do further experiments to find a minimal entry set that drives to 3 or less, if that would be interesting to anyone.

------------------

jeremy@toolbox-dev:~/Development/or-tools/build$ git status
On branch stable
Your branch is up to date with 'origin/stable'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   ../.gitignore
        modified:   ../or-tools.code-workspace

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        ../.cmake/
        ../DartConfiguration.tcl

no changes added to commit (use "git add" and/or "git commit -a")
