### ISSUE TITLE
is it possible to have capacity constraint at a depot？

### ISSUE THREAD

**Issue by JinYaan** [google/or-tools#1436]
Is it possible to give constraint to the capacity of a depot? For example this depot should serve as least 10 kg as most 100kg cargo?

**Comment by lperron** [comment]
Not sure
 Create a last node with the capacity constraint, and one arc to the depot.

**Comment by JinYaan** [comment]
@lperron thx!
I decided to set a lower bound to the capacity of some vehicles, according to #261, capacity_dimension.CumulVar(routing.End(vehicle)).RemoveInterval(0, minimum_allowed_capacity),  I want to use RemoveInterval. However, in this issue only the cumulative loading at the last node is considered. I have a pickup and delivery problem so no matter how, the loading at the last node should be 0, removing interval for the last node only makes the model infeasible. What I want to do is to set the lower bound to the sum of the absolute value of loading at every node, to ensure the vehicle fulfill enough orders. But I dont know how to code and also I am wondering is it possible..

**Comment by Mizux** [comment]
you can create a secondary dimension where at each pickup you increase by one and do nothing a drop off then you can set your `counting_dimension.CumulVar(routing.End(vehicle)).RemoveInterval(0, minimum_allowed_order)` on it...
