### ISSUE TITLE
Control over when routing search terminates

### ISSUE THREAD

**Issue by routemegood** [google/or-tools#1439]
I absolutely love the or-tools routing package, it's a really good solver! I was wondering if there are more sophisticated ways of terminating the search early than the current time and solution limits. Is there a way to, say, terminate after an amount of time or number of solutions where the best found solution hasn't changed?

I've found that for a large number of my problems the objective value will decrease monotonically until it finds a certain solution, then it'll cycle through the operators and the objective value will jump up to a higher value, slowly decrease to the found minimum, before jumping up again and repeating. The issue is that in some cases this happens after 30 seconds, and for other cases it's more like 2 minutes. It would be nice to be able to spot when the solver has hit the wall and break out of the search.

I know the constraint solver has a SearchMonitor, is there (or will there be) something similar for the routing package?

**Comment by routemegood** [comment]
So after a lot of digging through the source code and experimenting, I found out how to do this! The documentation is very sparse and not particularly helpful on this issue, I mostly pieced it together from the existence of various functions. Basically I needed to create a callback that could be passed to the solver using `routing_model.AddAtSolutionCallback(routing_monitor)`. The callback is just a class where the `__call__` function is what is executed at each solution. This function defines a class with a tolerance for the number of consecutive failures, and if those failures occur, it tells the solver to finish and return what it has.

```
def make_routing_monitor(routing_model: pywrapcp.RoutingModel, failure_limit: int) -> callable:
    class RoutingMonitor:
        def __init__(self, model: pywrapcp.RoutingModel):
            self.model = model
            self._counter = 0
            self._best_objective = inf
            self._counter_limit = failure_limit

        def __call__(self):
            self._best_objective = min(self._best_objective, self.model.CostVar().Max())
            if self._best_objective == self.model.CostVar().Max():
                self._counter = 0
            else:
                self._counter += 1
                if self._counter > self._counter_limit:
                    self.model.solver().FinishCurrentSearch()
    return RoutingMonitor(routing_model)
```

**Comment by lperron** [comment]
Nice.

**Comment by MichalGabonay** [comment]
How can be done the exact same thing in C++?

**Comment by Mizux** [comment]
I think, we need to provide a sample on how to use the solution callback.

@routemegood Thanks for your feedback and the solution provided, it's very appreciated !

**Comment by ugurakkurt** [comment]
I have the same problem @Mizux, I know it has been a long time, but could you provide a sample in Java language?

**Comment by Mizux** [comment]
@ugurakkurt https://github.com/google/or-tools/commit/2e97e4319b54dd9edf290dd66c2127cfa9d5da0e#diff-d9c1a32c4eccb35dcf8e6df9c2a13259a71e2dd01355ab43cdac4773f62d3fdaR88-R120

**Comment by ArmoredPony** [comment]
Is it possible to stop the solver from a separate thread in Java? I'm trying to initialize a timer after finding the initial solution, which, upon running out, would stop the solver. I spawn this timer in a `Thread` instance from inside of `atSolutionCallback` `Runnable` and I make sure this thread is created and run only once. The code in this thread gets run, but it has no effect on the solver. `Runnable` alone only allows me to terminate the solver immediately upon finding a solution, which means that it is possible to get stuck for an indefinite time.

**Comment by behnazak** [comment]
Is there a similar functionality in the .Net version?
