### ISSUE TITLE
Parsing chained inequality constraints

### ISSUE THREAD

**Issue by tommyod** [google/or-tools#1441]
First things first: I love the software, and I apologize if there's already an issue for this.

### What is the issue

Python users might be familiar with chaining comparison operators, e.g. `4 <= 6 <= 8` would evaluate as `True`. Adding constraints in this way does not seem to work, but it does not raise any errors either. This confused me a little bit. I suggest raising an error if it's not supposed to be possible.

### Code to produce the issue

```python
from ortools.linear_solver import pywraplp

solver = pywraplp.Solver("solver", pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING)
x = solver.NumVar(0, 10, "x")

# The solver is not aware of this constraint
solver.Add(4 <= x <= 8)

solver.Minimize(x)
solver.Solve()
print(x.solution_value()) # prints 0.0, not 4.0 as I would expect

print((x <= 10)._LinearConstraint__lb) # prints -inf
print((x <= 10)._LinearConstraint__ub) # prints 10

print((4 <= x <= 8)._LinearConstraint__lb) # prints -inf, but should print 4
print((4 <= x <= 8)._LinearConstraint__ub) # prints 8
```

Interestingly, if I replace the constraint with `8 >= x >= 4`, then `4.0` is returned. It seems as if only the second part of the chained inequality is parsed.

### Versions and platform

- ortools==7.2.6977
- Python 3.7.3
- Ubuntu 16.04

**Comment by lperron** [comment]
Yes, the second comparison operator is ignored.

For the time being, do not use this API. It is accepted by python because somewhere, it is converted to True of False.

(3 <= x) -> creates a constraint
(constraint <= 10) -> most likely evaluates to True of False.

Note that the order of evaluations may be reversed.

**Comment by lperron** [comment]
From what I can see, 

3 <= x <= 8 is parsed by python into 3 <= x and x <= 8,
Overloading and operator is not possible. Thus it will be ignored silently.

The best I can do is:

solver.Add((3 <= x0) <= 10)
