### ISSUE TITLE
Catching solver errors to py logging

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckxSimpleRose** [google/or-tools#1442]
I'm using the python API (v7.1) to solve MIPs with CPLEX; is there a way to use the Python logging library to also catch errors from linear_solver.cc such as the one shown below?

```
E0722 16:43:13.275576 17668 linear_solver.cc:1511] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_ABNORMAL
```

I've got python setup to log all STDERR but the message above doesn't seem to get caught.

**Comment by lperron** [comment]
This is cplex output. I do not know where it is send.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Sorry, answered too fast.

Do you see some comments about InitLogging not called ?

**Comment by ConstantinoSchillebeeckxSimpleRose** [comment]
> Do you see some comments about InitLogging not called ?

I do yes, but wasn't sure what to do with it. I couldn't find much documentation on it.

**Comment by lperron** [comment]
So, in python, I do not yet call InitLogging automatically with the linear solver. It is done with the CP-SAT. So it outputs the first error message. Now, there is no easy way to change the output of the glog library from python. 

This being said, this is an error message. You are trying to access the solution, while (1) you have not called Solve(), or (2) the solve did not find a solution, and you forget to check the return status before querying the solution.
