### ISSUE TITLE
Warm start CPLEX using google or tools SetHInt()

### ISSUE THREAD

**Issue by pal471** [google/or-tools#1444]
Hi, 
I have been trying to use the SetHint Api in python to warm start MIPs and solve it using CPLEX. It looks like my hints are accepted by the SetHint function but I am not sure whether CPLEX is actually using the warm start, the CPLEX output log has nothing related to warm start. 

I have set the following parameters in CPLEX through or-tools
`solver.SetSolverSpecificParametersAsString(f"CPLEX Parameter File Version 12.8.0.0 \n CPXPARAM_Advance 1 \n CPXPARAM_MIP_Display 3 \n  CPXPARAM_MIP_Limits_RepairTries 100 ")
`
Does the SetHint Api work with CPLEX? Is there a way to warm start CPLEX using or-tools?

Thanks!

**Comment by lperron** [comment]
This is not implemented.
I welcome pull requests. :-)

You can have a look at the code in the gurobi or Scip interface files.

**Comment by lperron** [comment]
Duplicate with https://or.stackexchange.com/questions/1069/warm-start-cplex-using-google-or-tools/1075#1075

**Comment by qtbgo** [comment]
Just wonder if cplex hint implemented in v8.0 ?

**Comment by lperron** [comment]
No. We do not work on cplex interface but accept PR for it. And nobody sent
us a PR for it.

**Comment by Mizux** [comment]
could be related to https://github.com/google/or-tools/pull/2901 which is adding parameter support.
