### ISSUE TITLE
Java Examples addDifferent fails

### ISSUE THREAD

**Issue by RobinKamps** [google/or-tools#1448]
Cannot get the 
`Constraint com.google.ortools.sat.CpModel.addDifferent(IntVar left, IntVar right)`
to work.

https://github.com/google/or-tools/blob/554cbccaa95b4c11eced13f145de1bf468e1f919/ortools/sat/samples/SearchForAllSolutionsSampleSat.java

Under Win10Pro 64-bit
`make run SOURCE=examples\java\SearchForAllSolutionsSampleSat.java`
returns
` 0 solutions found.`

If line 67 `model.addDifferent(x, y);`  is commented out, the program prints out all 27 solutions in detail and `27 solution found`.

If the constraint `model.addDifferent(x, y);`  is replaced by a different constraint e.g. `model.addGreaterOrEqual(x, 2);`  the program prints out all 9 feasable solutions in detail and `9 solutions found.`

**Comment by lperron** [comment]
Which version of or-tools ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 24 juil. 2019 à 07:15, Robin Kamps <notifications@github.com> a
écrit :

**Comment by RobinKamps** [comment]
Latest from https://developers.google.com/optimization/install/java/windows

Google.OrTools.runtime.win-x64.7.2.6977

**Comment by lperron** [comment]
Ok, another int/int64 miscast.
I fixed it in C#, I will track it down in java.

Thanks

**Comment by lperron** [comment]
Fixed on the master branch.

Thanks for the bug report.
