### ISSUE TITLE
CBC_MIXED_INTEGER_PROGRAMMING unable to find optimal solution when there is one?

### ISSUE THREAD

**Issue by UgurYavuz** [google/or-tools#1450]
I tried to detail the context of the bug and the expected result in [this notebook](https://github.com/UgurYavuz/DO-Practice/blob/master/VaryingBudgets.ipynb). The code and the outputs are also provided.

I was essentially trying to calculate the optimal profit that could be earned from selling products to customers (at most one per each), that are to be communicated with through three different channels (each with a minimum usage quota) of different costs and success rates, given a fixed budget (not to be exceeding). 

I consequently set three types of constraints, and tried to solve the problem using both CPLEX and OR-Tools. In one specific scenario, when the budget is set to 22500, OR-Tools curiously is unable to find the solution whereas CPLEX can. I didn't encounter any issues with any other values. Am I setting up the problem incorrectly or may there be a bug?

**Comment by lperron** [comment]
MIP problems can be hard computationaly, or numerically.

Most likely, if the solution found by cplex is valid, you have hit a limit
of CBC.

Le jeu. 25 juil. 2019 à 04:58, Ugur Yavuz <notifications@github.com> a
écrit :
