### ISSUE TITLE
Sequence of different Local Search Operators in Guided Local Search

### ISSUE THREAD

**Issue by julesrow** [google/or-tools#1454]
Hi all,

I'm using or-tools to solve a VRPTW with Guided Local Search in Python. My idea to solve it is quite similar to https://www.researchgate.net/publication/2886283_Guided_Local_Search_for_the_Vehicle_Routing_Problem.
I've figured out how to enable or disable specific Local Search Operators (see #233 or #235). So I'm enabling 2-opt, exchange, cross and relocate in my problem.

My questions: How does the GLS decide which Operator to use next during the search process? Is there a way to change the default behavior?

I've been also reading the whole user's manual in http://www.lia.disi.unibo.it/Staff/MicheleLombardi/or-tools-doc/user_manual/manual/metaheuristics.html and the paper in https://www.researchgate.net/publication/226021015_A_Constraint_Programming_Toolkit_for_Local_Search but could not find any answers to my questions.

Thank you very much for your help!

**Comment by lperron** [comment]
The order is given at construction.

Look for ConcatenateOperators in routing.cc and local_search.cc

you cannot change it.

**Comment by selting** [comment]
For anyone looking at this in the future
What I found in **local_search.cc** is this:

MAKE_LOCAL_SEARCH_OPERATOR(**TwoOpt**)
MAKE_LOCAL_SEARCH_OPERATOR(**Relocate**)
MAKE_LOCAL_SEARCH_OPERATOR(**Exchange**)
MAKE_LOCAL_SEARCH_OPERATOR(**Cross**)
MAKE_LOCAL_SEARCH_OPERATOR(**MakeActiveOperator**)
MAKE_LOCAL_SEARCH_OPERATOR(**MakeInactiveOperator**)
MAKE_LOCAL_SEARCH_OPERATOR(**MakeChainInactiveOperator**)
MAKE_LOCAL_SEARCH_OPERATOR(**SwapActiveOperator**)
MAKE_LOCAL_SEARCH_OPERATOR(**ExtendedSwapActiveOperator**)
MAKE_LOCAL_SEARCH_OPERATOR(**MakeActiveAndRelocate**)
MAKE_LOCAL_SEARCH_OPERATOR(**RelocateAndMakeActiveOperator**)
MAKE_LOCAL_SEARCH_OPERATOR(**RelocateAndMakeInactiveOperator**)


and the special **routing operators** seem to be in the following order:

CP_ROUTING_ADD_OPERATOR2(**EXCHANGE, Exchange**);
CP_ROUTING_ADD_OPERATOR2(**CROSS, Cross**);
CP_ROUTING_ADD_OPERATOR2(**TWO_OPT, TwoOpt**);
CP_ROUTING_ADD_OPERATOR(**OR_OPT, OROPT**);
CP_ROUTING_ADD_CALLBACK_OPERATOR(**LIN_KERNIGHAN, LK**);
local_search_operators_[MAKE_ACTIVE] = CreateInsertionOperator();
CP_ROUTING_ADD_OPERATOR2(**RELOCATE_AND_MAKE_ACTIVE, RelocateAndMakeActiveOperator**);
CP_ROUTING_ADD_OPERATOR2(**MAKE_ACTIVE_AND_RELOCATE, MakeActiveAndRelocate**); local_search_operators_[MAKE_INACTIVE] = CreateMakeInactiveOperator();
CP_ROUTING_ADD_OPERATOR2(**MAKE_CHAIN_INACTIVE, MakeChainInactiveOperator**);
CP_ROUTING_ADD_OPERATOR2(**SWAP_ACTIVE, SwapActiveOperator**);
CP_ROUTING_ADD_OPERATOR2(**EXTENDED_SWAP_ACTIVE, ExtendedSwapActiveOperator**);
CP_ROUTING_ADD_CALLBACK_OPERATOR(**TSP_OPT, TSPOPT**);
CP_ROUTING_ADD_CALLBACK_OPERATOR(**TSP_LNS, TSPLNS**);
CP_ROUTING_ADD_OPERATOR(**PATH_LNS, PATHLNS**);
CP_ROUTING_ADD_OPERATOR(**FULL_PATH_LNS, FULLPATHLNS**);
CP_ROUTING_ADD_OPERATOR(**INACTIVE_LNS, UNACTIVELNS**);

**Comment by Mizux** [comment]
@selting updated and fixed your list...
