### ISSUE TITLE
Defining intervals by linear combination of variables

### ISSUE THREAD

**Issue by 23pointsNorth** [google/or-tools#1457]
I have issues defining an intervals start/end domain as a summation of a `IntVar` and a constant. (the example below can be seen as an extension to the [cover_rect example](https://github.com/google/or-tools/blob/stable/examples/python/cover_rectangle_sat.py) by adding a buffer between the squares)

What feels intuitive is writing something like 
```
start_y = model.NewIntVar(0, size_y, 'sy_%i' % i)
end_y = model.NewIntVar(0, size_y, 'ey_%i' % i)
interval_y = model.NewIntervalVar(start_y, size, end_y, 'iy_%i' % i)
# ...  later in code
min_border = 10
border_interval_y = model.NewIntervalVar(start_y-min_border, size[0], end_y+min_border, 'b_iy_%i' % i)
```
However, it can be rewritten as below.
```
border_start_x = model.NewIntVar(-min_border, MAX_X+min_border, 'b_sx_%i' % i)
model.Add(x_starts - min_border == border_start_x)
border_end_x = model.NewIntVar(-min_border, MAX_X+min_border, 'b_ex_%i' % i)
model.Add(x_ends - min_border == border_end_x)
interval_x = model.NewIntervalVar(border_start_x, sizes[1], border_end_x, 'b_ix_%i' % i)
```
The error raised is 
```
TypeError: NotSupported: model.GetOrMakeIndex((sy_0 + -10))
```
It this as expected and the alternative rewrite should be used?

**Comment by lperron** [comment]
I do not want the modeling layer to create new variables and constraints
implicitly, which is the case of your proposal.

The python API to create new interval variables expect integer variables or
constants.

You can add a method to create shifted intervals if you wish.

--Laurent

Le lun. 29 juil. 2019 à 04:16, Daniel Angelov <notifications@github.com> a
écrit :
