### ISSUE TITLE
GLPK reports ABNORMAL instead of INFEASIBLE

### ISSUE THREAD

**Issue by syxolk** [google/or-tools#1459]
Hi, I'm using OR-Tools 7.2 (Python 3) with GLPK 4.65. When running the following code, I receive a result status of `ABNORMAL` instead of `INFEASIBLE` (as observed with Gurobi 8.1 and CBC):

```python
from ortools.linear_solver import pywraplp

solver = pywraplp.Solver('test', pywraplp.Solver.GLPK_MIXED_INTEGER_PROGRAMMING)
solver.EnableOutput()
x = solver.IntVar(0, 10, "")
solver.Add(x >= 20)

result_status = solver.Solve()
print(result_status) # outputs: 4
```

GLPK output:

```
Scaling...
 A: min|aij| =  1.000e+00  max|aij| =  1.000e+00  ratio =  1.000e+00
Problem data seem to be well scaled
Constructing initial basis...
Size of triangular part is 1
GLPK Simplex Optimizer, v4.65
1 row, 1 column, 1 non-zero
Preprocessing...
PROBLEM HAS NO PRIMAL FEASIBLE SOLUTION
```

Is this expected behavior?

**Comment by lperron** [comment]
I do not trust glpk or CBC results.

So I would say yes.

Even gurobi and cplex can disagree. It comes with the technology.

**Comment by syxolk** [comment]
Ok, I thought this a mapping problem of GLPK status codes to OR-Tools status codes.

**Comment by lperron** [comment]
Status code are very different across solvers.
I believe GLOP returns ABNORMAL if the problem is proved infeasible during
presolve, and INFEASIBLE is proved during search.
Something like that.

Your code should check for both abnormal or infeasible.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by syxolk** [comment]
> Your code should check for both abnormal or infeasible.

Thanks for the suggestion! I thought `ABNORMAL` is some kind of unknown state of the solver itself.

**Comment by syxolk** [comment]
Just for the record, I found some relevant information in the glpk_interface code:

https://github.com/google/or-tools/blob/b027e57e95e2f70d17c28d6f6319e57dcbbd46b2/ortools/linear_solver/glpk_interface.cc#L552-L556

This is probably what was happening in my minimal example, especially since it stops directly after "Preprocessing..."

**Comment by marianneke** [comment]
> I do not trust glpk or CBC results. So I would say yes. Even gurobi and cplex can disagree. It comes with the technology. Le lun. 29 juil. 2019 à 05:49, Hans <notifications@github.com> a écrit :

Are there open source solvers you would trust?
