### ISSUE TITLE
cp_model in Job Shop Scheduling lags really bad upon solver.Solve(model) [URGENT]

### ISSUE THREAD

**Issue by replicantdeca** [google/or-tools#1466]
Hello I am wondering why the flexible_jobshop() suddenly lags tremendously upon just adding a few workers to the database.

It lags when it reaches solver.Solve(model)

Attached are my code and data. Thank you so much
[git.zip](https://github.com/google/or-tools/files/3451684/git.zip)

**Comment by lperron** [comment]
Duplicate with https://groups.google.com/forum/#!topic/or-tools-discuss/S9tSaVv1Dj8
