### ISSUE TITLE
Segmentation fault on Azure DevOps instance

### ISSUE THREAD

**Issue by SirCipher** [google/or-tools#1468]
I'm using 2018b to run a Delaunay triangulation script which I have then built using the Compiler SDK and packaged for Java. From this, I then feed in my function arguments, obtain the result and then solve using Google OR-Tools. This workflow works well and on both my Ubuntu 18.04 machine and Mac laptop I encounter no issues. 

I'm using an Azure DevOps instance to build my code and I run two jobs: an Ubuntu 16.04 instance and a macOS X Mojave (10.14) instance. Before compiling the code, a script runs which fetches the MATLAB Runtime 9.5 release and OR-Tools library, unpacks it and sets the environment variables. Unit tests then run successfully - which tests the MATLAB/OR-tools code - and occasionally (1/5 builds) the process fails after the tests have finished - it appears to be when the environment is shutting down. 

After the build failing I am presented with the following segmentation fault:

 ```
   --------------------------------------------------------------------------------
           Segmentation violation detected at Wed Jul 31 18:59:14 2019 +0000
    --------------------------------------------------------------------------------
    Configuration:
      Crash Decoding           : Disabled - No sandbox or build area path
      Crash Mode               : continue (default)
      Default Encoding         : ISO-8859-1
      Deployed                 : true
      Graphics Driver          : Unknown software 
      MATLAB Architecture      : maci64
      MATLAB Entitlement ID    : <redacted>
      MATLAB Root              : /Users/vsts/agent/2.154.3/work/1/s/libraries/MATLAB/v95
      MATLAB Version           : 9.5.0.944444 (R2018b)
      OpenGL                   : software
      Operating System         : Mac OS Version 10.14.6 (Build 18G84)
      Process ID               : 14437
      Processor ID             : x86 Family 6 Model 58 Stepping 9, GenuineIntel
      Session Key              : <redacted>
      Window System            : None
    Fault Count: 1
    Abnormal termination
    Register State (from fault):
      RAX = 00007fe0cb600000  RBX = 0000000000000029
      RCX = 00007000056ae5b0  RDX = 00007fff68631282
      RSP = 0000000000000002  RBP = 0000000000000002
      RSI = 00007fe0d1efc080  RDI = 0000000000000000
       R8 = 00007000056ae5e0   R9 = 00007fff68631282
      R10 = 0000001800000000  R11 = 00007fe0cb6fc080
      R12 = 00007fe000000003  R13 = 00007fe0d1e52f20
      R14 = 00007fe0cb417678  R15 = 00007fe0cd975250
      RIP = 00007000056ae5d0  RFL = 0000000104c8148b
       CS = 00007fe0cb6f7400   FS = 0000000000000000   GS = 00007fe0d1854a80
    Stack Trace (from fault):
    [  0] 0x000000010cf8fdd1                           bin/maci64/libmwfl.dylib+00007633 _ZN10foundation4core4diag15stacktrace_base7captureERKNS1_14thread_contextEm+00000049
    [  1] 0x000000010cf954b5                           bin/maci64/libmwfl.dylib+00029877 _ZN10foundation4core4test17terminate_handledEv+00006181
    [  2] 0x000000010cf939f5                           bin/maci64/libmwfl.dylib+00023029 _ZN10foundation4core4diag13terminate_logEPKcPK17__darwin_ucontext+00000149
    [  3] 0x000000012311d67b                          bin/maci64/libmwmcr.dylib+00632443 _Z19mnPrintErrorMessageRKNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE+00012635
    [  4] 0x000000012311b207                          bin/maci64/libmwmcr.dylib+00623111 _Z19mnPrintErrorMessageRKNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE+00003303
    [  5] 0x0000000123118d64                          bin/maci64/libmwmcr.dylib+00613732 mnFatalSignalHandler+00000148
    [  6] 0x00007fff6866eb5d           /usr/lib/system/libsystem_platform.dylib+00019293 _sigtramp+00000029
    [  7] 0x00007000056ae090                                   <unknown-module>+00000000
    [  8] 0x0000000104c8148b /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/server/libjvm.dylib+03286155 jni_DeleteGlobalRef+00000053
    [  9] 0x000000010d1d55d3 /Users/vsts/agent/2.154.3/work/1/s/libraries/repo/ortools/libjniortools.jnilib+00435667 _ZN14GlobalRefGuardD2Ev+00000019
    [ 10] 0x000000010d1d5785 /Users/vsts/agent/2.154.3/work/1/s/libraries/repo/ortools/libjniortools.jnilib+00436101 _ZNSt3__114__shared_count16__release_sharedEv+00000037
    [ 11] 0x000000010d1d573e /Users/vsts/agent/2.154.3/work/1/s/libraries/repo/ortools/libjniortools.jnilib+00436030 _ZNSt3__119__shared_weak_count16__release_sharedEv+00000014
    [ 12] 0x000000010d21c1e2 /Users/vsts/agent/2.154.3/work/1/s/libraries/repo/ortools/libjniortools.jnilib+00725474 _ZNSt3__110__function6__funcIZ86Java_com_google_ortools_constraintsolver_mainJNI_RoutingModel_1registerTransitCallbackE4$_95NS_9allocatorIS2_EEFxxxEE18destroy_deallocateEv+00000018
    [ 13] 0x000000010e734728 /Users/vsts/agent/2.154.3/work/1/s/libraries/repo/ortools/libortools.dylib+04912936 _ZN19operations_research12RoutingModelD2Ev+00001272
    [ 14] 0x000000010d1b5a86 /Users/vsts/agent/2.154.3/work/1/s/libraries/repo/ortools/libjniortools.jnilib+00305798 Java_com_google_ortools_constraintsolver_mainJNI_delete_1RoutingModel+00000022
    [ 15] 0x0000000111ab1407                                   <unknown-module>+00000000
    [ 16] 0x0000000111aa0ffd                                   <unknown-module>+00000000
    [ 17] 0x0000000111aa0ffd                                   <unknown-module>+00000000
    [ 18] 0x0000000111e928cc                                   <unknown-module>+00000000
    ** This crash report has been saved to disk as /Users/vsts/matlab_crash_dump.14437-1 **
    MATLAB is exiting because of fatal error
    FAILURE: Build failed with an exception.

```
What I am unsure about is whether or not this is an issue with MATLAB or the OR-Tools library. It appears to be in the format of a MATLAB segmentation fault, however, the stack trace contains references to the OR-Tools libraries as well - so I apologise if I'm wrong. These OR-Tool references `_ZNSt3__110__function6__funcIZ86Java_com_google_ortools_constraintsolver_mainJNI_RoutingModel_1registerTransitCallbackE4`, for example, were called far earlier on than when the segmentation fault presents itself.

**Comment by lperron** [comment]
Most likely a callback object GC'd away in the azure environment.
Make sure to keep a reference to any callbacks passed to the solver, and
make sure they are still alive for the whole duration of the solve.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 31 juil. 2019 à 14:09, Thomas Klapwijk <notifications@github.com> a
écrit :

**Comment by SirCipher** [comment]
Hi, lperron. I'm using one of the older samples as a starting point and the callbacks are defined here: https://github.com/SirCipher/UNDERSEA/blob/6d85d2986811700f9f0d9084c3c1ae2fc7ba91f5/undersea-agent/missionplanner/src/main/java/com/type2labs/undersea/missionplanner/planner/vrp/VehicleRoutingOptimiser.java#L116

I'll try keeping a reference to these and run a few jobs on the CI server and see if anything changes. That file is where I use the library and what results in the entries in the stack trace above.

**Comment by SirCipher** [comment]
I have stored references to the callbacks and they were available for the duration of the solving but this has not solved the problem. Do you have any further suggestions?

**Comment by lperron** [comment]
No, this is not the first reported crash on azure.
Each time, it works fine on other environments.
 (last time was a python bug in the routing library).
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 31 juil. 2019 à 15:07, Thomas Klapwijk <notifications@github.com> a
écrit :

**Comment by SirCipher** [comment]
Ok. Thank you for the information. I will try using another CI provider.
