### ISSUE TITLE
MIP Solver set solution hints from already calculated solution

### ISSUE THREAD

**Issue by Phibedy** [google/or-tools#1469]
Hi,

we are having troubles setting the solution hints from an already calculated solution.
In the Cp-Sat solver one can just iterate over the solution and set the variables using the index + value. The MP-interface does not expose the built model, neither the solution proto.

At the moment we get the get the proto -> call SolveWithProto -> fillSolutionProto -> set the hints manually in the proto -> call SolveWithProto again.

Is this the way to go or are we missing something? :)

**Comment by lperron** [comment]
There are two parts

you have hints, you build the proto with hints, then you call
SolveWithProto().

This is the same as with the CP-SAT. Except that we do not have a nice
working interface to build the proto.

Now, you can iterate over the solution proto, and fill the model proto in
the same way.



Short answer, yes, this is the expected way.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Phibedy** [comment]
ok thanks :+1:

**Comment by syxolk** [comment]
If anyone else looks for this: here is a nice helper function that sets hints for all variables from the previous solution:

```python
from ortools.linear_solver import pywraplp
from ortools.linear_solver import linear_solver_pb2

def set_hint_for_all_variables(solver):
    # Get all variable assignments
    solution = linear_solver_pb2.MPSolutionResponse()
    solver.FillSolutionResponseProto(solution)

    # Get model and set solution hint
    model = linear_solver_pb2.MPModelProto()
    solver.ExportModelToProto(model)
    model.solution_hint.Clear()
    for index, value in enumerate(solution.variable_value):
        model.solution_hint.var_index.append(index)
        model.solution_hint.var_value.append(value)
    solver.LoadModelFromProto(model)
```
