### ISSUE TITLE
Empty assignment when pickup/delivery times not viable

### ISSUE THREAD

**Issue by calatian** [google/or-tools#1470]
I am working on a vehicle routing system with pickups and deliveries, where locations are sometimes only available for pickups/deliveries at certain times. It has been thoroughly tested and works fine in most cases but I am running into a problem.

The following two scenarios return empty assignments:

First scenario:
Pickup at location 1, with location 1 only available from 3-4pm.
Delivery at location 2, with location 2 only available from 1-2pm.

Of course, it is impossible to schedule this pickup and delivery. However, this is just one out of many pickups and deliveries and many other locations, but instead of just dropping the impossible combination, the system returns an empty assignment.

Second scenario:
Pickup at location 1, with location 1 only available from 3-4pm.
Delivery at location 2, with location 2 available anytime.

Pickup at location 2, with location 2 available anytime.
Delivery at location 3, with location 3 only available from 1-2pm.

Of course, doing 1 -> 2 -> 3 is impossible. But if one of these two pickup/delivery pairs was dropped, the rest of pickups/deliveries would be possible. However, the algorithm returns an empty assignment. This is a big problem for my system.

The second scenario is sometimes a more complicated combination of pickups and deliveries, so it is very hard for me to track down if an impossible combination is entered. 

I have a penalty system implemented (as described [here](https://developers.google.com/optimization/routing/penalties)) with minimal changes, and the pickup/delivery system described [here](https://developers.google.com/optimization/routing/pickup_delivery), also with minimal changes. The penalty system works fine in other situations, only giving me this problem if any impossible pickup/delivery combinations are present.

Is there anything that can be done on my side so that locations would be dropped in the above cases, instead of returning an empty assignment?

Any advice is very appreciated.

**Comment by lperron** [comment]
can't you filter them out before adding them as P&D

**Comment by calatian** [comment]
Hi Laurent,

As mentioned, trying to handle it on my side would not be easy as there might be many pickup/delivery pairs and I might not always catch the incompatible ones.

 Catching the problem would mean finding the pickup/delivery routes on my side first and then trying to identify unviable situations, which is why I am checking if it is something the algorithm itself can do.

**Comment by calatian** [comment]
For example, imagine there are 10 pickup/delivery pairs and 5 of them have to deliver in the same location (among others that would fall in the same route). Which order should they follow? I would have to figure out any possible combinations and try to identify if any of them is not feasible, then repeat the same process for all other pickup/delivery route combinations. 

I would have to go through this process of finding the routes myself (and probably missing some unviable combinations) and determine which locations need to be dropped, with this process done before sending it to the solver. It seems like this task should be handled by the solver instead.

**Comment by lperron** [comment]
Are these pickup-delivery optional ?
If not, the given model is optional, and you cannot expect the solver to change the model you have created.

**Comment by calatian** [comment]
Laurent,

I am not expecting the solver to change the model; I am expecting it to drop the locations that result in an unfeasible situation by using the penalty system instead of returning an empty assignment. Is there a way it can do this?

Thanks!

**Comment by lperron** [comment]
If you give an unfeasible problem to the solver, I expect the solver to
return unfeasible.

If you want the solver to drop the visit, you need to use the add
disjunction feature.
