### ISSUE TITLE
How does the Routing Solver assign orders to vehicles?

### ISSUE THREAD

**Issue by HeadhunterXamd** [google/or-tools#1471]
I would like to understand why sometimes there are empty vehicles between used vehicles.
In one of our usecases we found that the assigned vehicles where 1,4,5,6 while 2,3 where empty.
We are trying to implement a minimum amount of vehicles required and we think we have a solution, except we need to know (I think) how the algorithm chooses which vehicle to use.

**Comment by lperron** [comment]
By local search exploration. It will start building local routes, then try to consolidate them.
There is no way to force used vehicles to be the first ones.
