### ISSUE TITLE
Nurse scheduling using shifts with different lengths

### ISSUE THREAD

**Issue by j3r3mias** [google/or-tools#1472]
I'm trying to adapt `shift_scheduling_sat.py` to include different shift lengths at the same shift. This means that in the same morning, I have needs with different lengths, so instead of 
```
    weekly_cover_demands = [
        (2, 3, 1),  # Monday
        ...
    ]
```
that has the demand of 2 workers in the morning, I want to differentiate those 2 in different shifts lengths like 1 working 6 hours, 0 working 7 hours and 1 working 8 hours. Something like that:

```
    weekly_cover_demands = [
        ([1, 0, 1], [2, 1, 0], [0, 0, 1]),  # Monday
        ...
    ]
```
How can I adapt the constraints to deal with the shifts using this approach?

**Comment by lperron** [comment]
Create more types of shifts. Morning-6, Morning-7, Morning-8.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
