### ISSUE TITLE
CP-SAT: stopSearch() does not work if called before presolve is finished

### ISSUE THREAD

**Issue by prissky** [google/or-tools#1474]
It seems like the Search can be stopped only after it has started. Is there a way to terminate solving even in case of lengthy pre-solve phase?

**Comment by lperron** [comment]
Thanks for the bug report.

**Comment by lperron** [comment]
From our tests, it seems it is fixed with master.

I am closing the bug for now. Do not hesitate to reopen it.

**Comment by prissky** [comment]
Unfortunately, I do not see an improvement with current master. Will you, please, reopen the issue or should I create a new one? I can attach a proto model, but the situation seems pretty clear: if the delay of stopSearch() is set shorter than the time needed for the Search to be started, it never stops.

**Comment by lperron** [comment]
I just fixed it.

Thanks
