### ISSUE TITLE
CP-SAT: Crash when constraining is_present variable on optional intervals in NoOverlap2D constraint

### ISSUE THREAD

**Issue by PistonMiner** [google/or-tools#1477]
When attempting to solve the model with [the attached proto file](https://github.com/google/or-tools/files/3473548/reproduce_interval_bug.zip) (using the Python bindings, version 7.3.7083; I did not test other languages), the solver crashes with the following error:
```
Check failed: intervals_[i] != kNoIntervalVariable (-1 vs. -1)
*** Check failure stack trace: ***
    @   00007FFD4D018C45  PyInit__pywrapsat
    @   00007FFD4D016F82  PyInit__pywrapsat
    @   00007FFD4D292629  PyInit__pywrapsat
    @   00007FFD4D2B27B9  PyInit__pywrapsat
    @   00007FFD4D2ADA4B  PyInit__pywrapsat
    @   00007FFD4D249077  PyInit__pywrapsat
    @   00007FFD4D239C40  PyInit__pywrapsat
    @   00007FFD4D23E285  PyInit__pywrapsat
    @   00007FFD4D0B5E0C  PyInit__pywrapsat
    @   00007FFD4D00D15D  (unknown)
    @   00007FFD4D005ECF  (unknown)
    @   00000000592AADE2  _PyCFunction_FastCallDict
    @   00000000592AA4F3  PyObject_CallFunctionObjArgs
    @   0000000059288979  _PyEval_EvalFrameDefault
    @   00000000592AA6CE  PyObject_CallFunctionObjArgs
    @   0000000059288979  _PyEval_EvalFrameDefault
    @   00000000592AA6CE  PyObject_CallFunctionObjArgs
    @   0000000059288979  _PyEval_EvalFrameDefault
    @   00000000592AB35B  _Py_CheckFunctionResult
    @   00000000592AA95F  PyObject_CallFunctionObjArgs
    @   0000000059288979  _PyEval_EvalFrameDefault
    @   00000000592AB35B  _Py_CheckFunctionResult
    @   00000000592B6143  PyEval_EvalCodeEx
    @   00000000592B60A1  PyEval_EvalCode
    @   00000000592B604B  PyArena_Free
    @   000000005940A661  PyRun_FileExFlags
    @   000000005940AE01  PyRun_SimpleFileExFlags
    @   000000005940A53F  PyRun_AnyFileExFlags
    @   000000005935B268  _Py_hashtable_size
    @   00000000592FA044  Py_FatalError
    @   000000001C58126D  (unknown)
    @   00007FFDB3827974  BaseThreadInitThunk
```
I've attempted to narrow down the repro model as much as possible; should the Python code that generated the proto be necessary to reproduce the issue, I can supply that too.

**Comment by lperron** [comment]
Currently, NoOverlap2D does not support optional variables.

To implement what you want, have the size be variable, and is_present =>
x_size == 0 and y_size == 0.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 6 août 2019 à 11:11, PistonMiner <notifications@github.com> a
écrit :

**Comment by PistonMiner** [comment]
Thanks a lot for the quick response!

I was going off of https://github.com/google/or-tools/blob/stable/ortools/sat/python/cp_model.py#L1324 which states that

> A NoOverlap2D constraint ensures that all *present* rectangles do not overlap [...]

Might be worth rewording that a bit to clarify this limitation? It was additionally confusing seeing as NoOverlap2D *did work* with optional intervals for the most part.

At any rate, just constraining the size to zero works fine, thanks.

**Comment by lperron** [comment]
Yes. I will update the doc.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 6 août 2019 à 13:21, PistonMiner <notifications@github.com> a
écrit :
