### ISSUE TITLE
C# example for School Scheduling 

### ISSUE THREAD

**Issue by KeramatHasani** [google/or-tools#1478]
Hi. I'm looking for an example with C# for the school scheduling problem but didn't find anything among the exsiting examples. Would you please provide me a link to that example(if exists) or any related ones which can be helpful?
Thanks.

**Comment by lperron** [comment]
There are none :-)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
You can have a look at the ShiftSchedulingSat.cs which explains some of the concepts.

But you will need to do write your own model.

**Comment by KeramatHasani** [comment]
Thanks.
Dosn't exist even for other languages?
Aren't you going to prepare such example with  C# or Java ?
