### ISSUE TITLE
No maximization version of `AddWeightedVariableMinimizedByFinalizer`

### ISSUE THREAD

**Issue by VitamintK** [google/or-tools#1479]
Hi, I noticed that there is `AddWeightedVariableMinimizedByFinalizer`, but no `Maximized` version, like there is for `AddVariableMaximizedByFinalizer` and `AddVariableMaximizedByFinalizer`.

Is there a reason for this?  Can we safely use `AddWeightedVariableMinimizedByFinalizer` with variables we want to maximize by multiplying the variables by `-1`?

**Comment by lperron** [comment]
replace
  model.AddWeightedVariableMaximizedByFinalizer(var, cost);

with

model.AddVariableMaximizedByFinalizer(model.solver()->MakeProd(var,
cost)->Var()));
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
