### ISSUE TITLE
Help: Job Shop problem, how can I give priority to operations that are feed first to the model?

### ISSUE THREAD

**Issue by gustavo-barros** [google/or-tools#1480]
Hello there,

How can I say to the solver to give preference and schedule first those operations that are fed first to the model? For example, if I feed in order A , B, C and D, I want that ,if possible, the solver will give preference to A, starting with it. And then B, then C. I don't want always that A have preference and set always first. But if it is fed first, then it should come first, if possible. Being that, if I change the order to D, C, B and A. Now D should have preference.

How can I do that?

**Comment by jschelbert** [comment]
you probably could add some precedence constraints to your model, but then the order of your operations is strictly enforced.

**Comment by stradivari96** [comment]
maybe create boolvars that are true if A before B, B before C etc and maximize their sums?

**Comment by lperron** [comment]
What does it means for the model: being feed first ?

**Comment by gregy4** [comment]
If I understand it correctly, you want to instantiate operations in an order in which they are created in a model. In cp-sat solver it works probably already this way if we ignore that order is affected also by activity of variables in sat branching strategy. My experiments showed always better results when I created variables corresponding to operations in an order that should be instantiated. In constraint solver it is more direct, an order in which are variables instantiated is defined by branching strategy.

**Comment by lperron** [comment]
Yes but nothing guarantees it.

There are two solutions:
1) Try/enforce an exact order.
2) change the objective to penalize violation of this order.

1) can work, but when it does not, you need to write heuristic code to remove some of these constraints.
2) works, but (a) it slows down solving, and (b) you need to balance the weights w.r.t. the other weights of your problem (like tardiness)

In the end, there are two use cases for this:
  - client priorities -> most likely solved by weights on the tardiness of the delivery
  - physical constraints when changing the order (need a robot, need inventory). I would go with option 1) first.

I hope this helps.
