### ISSUE TITLE
BIBD implementation using Python CP-SAT solver: Dot prod of BoolVar list

### ISSUE THREAD

**Issue by Shishir-Suman** [google/or-tools#1483]
Hi,

I am new to OR tools and trying to implement BIBD using CP-SAT solver through Python API. As part of the code, have two lists: each of form [model.NewBoolVar("i") for i in range(k)].

The constraint to be specified is that dot product of the two lists has to be a constant. Using model.Add gives an error "Not an Integer Linear expression". Is there a way to implement this.

Thanks,

**Comment by stradivari96** [comment]
I think you have to create a intermediate var, for each i in range(k) using
AddProdEquality and then compute its sum

**Comment by Shishir-Suman** [comment]
AddProdEquality seems to require a target value which will be varying in this case depending on the values.

**Comment by stradivari96** [comment]
You have to create k new vars so that AddProdEquality(new[i], [x[i], y[i]])

**Comment by lperron** [comment]
Use model.AddMultiplicationEquality

Le sam. 10 août 2019 à 15:41, Shishir Suman <notifications@github.com> a
écrit :
