### ISSUE TITLE
VRP - Preassign Node to Vehicle Very Slow

### ISSUE THREAD

**Issue by aunahale** [google/or-tools#1484]
Hi,

I have a vehicle routing problem where some nodes are preassigned to certain vehicles while some nodes can't be visited by certain vehicles. 

Right now i'm attempting to solve this using `routing.VehicleVar(index).SetValues()` but the solver is running for hours without producing any result. The problem I'm dealing with has about 200-300 nodes, 50-60 nodes with vehicle constraints, and 6 vehicles.

I've tried experimenting with different first solution strategy but they all take hours to run without any results. Any tips on how to speed this up? or how should I model this problem differently?

**Comment by lperron** [comment]
It means the problem you created has no solution.

Please check your code.
