### ISSUE TITLE
CoverConstraint over-propagating for StartVarIntervalVar

### ISSUE THREAD

**Issue by supermihi** [google/or-tools#149]
In the scheduling example below, a fixed-duration task is created in two different ways: either by creating a FixedDurationPerformedIntervalVar with lower/upper bound on its start time, or as StartVarIntervalVar with a (previously created) IntVar as start time. Then, a two unary resources are modeled of which the task demands one; this is done by creating optional copies of the task and adding a cover constraint. Again, the copies are created in two different ways.

All four combinations of the variants should result in a clearly feasible model. However, when the task is created as StartVarIntervalVar, no solution is found. I suspect the CoverConstraint to wrongly over-propagate in this case, because without it, a soultion is found for every combination.

``` python
from ortools.constraint_solver import pywrapcp

def test(taskVariant, resourceVariant):
    solver = pywrapcp.Solver('')
    taskDuration = 3
    if (taskVariant == 0):
        # create start var, construct StartVarIntervalVar from it
        startVar = solver.IntVar(0, 50, "start")
        task = solver.FixedDurationIntervalVar(startVar, taskDuration, "task")
    else:
        # create FixedDurationIntervalVar, get start time from its StartExpr()
        task = solver.FixedDurationIntervalVar(0, 50, taskDuration, False, "task")
        startVar = task.StartExpr().Var()


    # somewhere else in the code ... create copies for unary resource allocation
    if (resourceVariant == 0):
        # create optional FixedDurationIntervalVar with same start bounds as original task
        startMin = task.StartMin()
        startMax = task.StartMax()
        duration = task.DurationMin()
        copies = [solver.FixedDurationIntervalVar(startMin, startMax, duration, True, "copy") for _ in (0,1)]
        performedVars = [c.PerformedExpr().Var() for c in copies]

    else:
        # use the start expression from original variable, create StartVarIntervalVar
        performedVars = [solver.IntVar(0, 1, "performed") for _ in (1,2)]
        copies = [solver.FixedDurationIntervalVar(startVar, taskDuration, performedVars[i], "copy") for i in (0,1)]

    solver.Add(solver.Cover(copies, task)) # this is redundant for resourceVariant == 1, but should nevertheless work
    solver.Add(solver.Sum(performedVars) == 1)

    resourcePhase = solver.Phase(performedVars, solver.INT_VAR_DEFAULT, solver.INT_VALUE_DEFAULT)
    taskPhase = solver.Phase([task], solver.INTERVAL_DEFAULT)
    copyPhase = solver.Phase(copies, solver.INTERVAL_DEFAULT)
    cpo = solver.Compose([resourcePhase, taskPhase, copyPhase])
    solver.NewSearch(cpo)
    print(solver.NextSolution())

for taskVariant in (0, 1):
    for resourceVariant in (0, 1):
        print("task variant {}, resource variant {}".format(taskVariant, resourceVariant))
        test(taskVariant, resourceVariant)
```

**Comment by lperron** [comment]
I know that IntervalVars built from 2 int vars are not performing correctly.
This comes from the non atomic behavior of modifications on those variables.

Thanks for the bug report. I will have a look.

**Comment by supermihi** [comment]
Thanks. Note that taskVariant == resourceVariant == 1 works as expected when the (then redundant) cover constraint is removed. That's the way I am using in my implementation right now.

**Comment by supermihi** [comment]
Do you have any updates on this – in particular, is it still buggy to use IntervalVars built from 2 int vars? I am observing strange behavior in my models and I wonder if this could again be the reason for it.

**Comment by lperron** [comment]
No, I have not updated the code. So it is a definitive possibility.
Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-09-06 14:25 GMT+02:00 Michael Helmling <notifications@github.com>:

**Comment by supermihi** [comment]
Okay, thanks for the update. Is there a way I could help to solve the issue? Can you narrow down what exactly causes the problem?

Thanks,
Michael

**Comment by lperron** [comment]
I will close this issue as will not fix.

Please use the CP-SAT solver for scheduling. The new API is much clearer.
