### ISSUE TITLE
VRP: Pickup and Deliveries to or from Depot (preloading) C#

### ISSUE THREAD

**Issue by jackawatts** [google/or-tools#1491]
The problem is as follows:
As per the title I have a VRP with pickups and deliveries where on occasion a job may need to remain on the vehicle for the next day.

*In scenario 1*: It is unimportant when the job is picked-up, so long as it ends up at the depot at the end of the day (ie. it _must_ be guaranteed to be on a vehicle at the end of the day)
*In scenario 2*: The vehicle needs to leave the depot with a job 'pre-loaded'  (ie it _must_ be already 'picked-up' on a vehicle at the start of the day)

The problem I run into when attempting to solve this is as follows:
1. Any code I come up with attempting to add the depot end location as a delivery location, hangs the routing model:
```C#
if (data.VehicleEndIndexes.Contains(pickupDeliveryNode.Item2))
{
    var vehicleEnd = data.VehicleEndIndexes.IndexOf(pickupDeliveryNode.Item2);
    deliveryIndex = routingModel.End(vehicleEnd);
}
else
{
    deliveryIndex = manager.NodeToIndex(pickupDeliveryNode.Item2);
}

routingModel.AddPickupAndDelivery(pickupIndex, deliveryIndex);
```

2. Any of the ApplyLocks methods on the routingModel seem to not want to have a depot as part of the 'lock chain'

I am happy to admit both approaches may be incorrect, but how can I fulfill the criteria I outline above?
(Scenario 1: A job can be guaranteed to be on a vehicle at the end of the day
Scenario 2: A job can be guaranteed to to be already 'picked-up' on a vehicle at the start of the day)

**Comment by jmarca** [comment]
My suggestion would be to add a dummy node before the depot for these requirements.  You cannot deliver to the depot, but you can deliver to the "dummy_depot" and then have the travel time/distance from that node to the depot node be zero.

For the opposite constraint, have a dummy pickup node located zero distance from the depot, plus require that the node be served (do not add it to any disjunction)
