### ISSUE TITLE
IntervalVarContainer within SearchMonitor

### ISSUE THREAD

**Issue by braktar** [google/or-tools#1494]
Hello,

Following the break exemple for the routing library : 
https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/examples/cpp/cvrptw_with_breaks.cc#L209

I now try to monitor those values for intermediates solution using a SearchMonitor or a SearchLimit.
It seems that the assignement doesn't carry those values or don't expose them.
Is it possible to monitor the IntervalVarContainer from an intermediate assignment ? And how ?

Thanks

**Comment by lperron** [comment]
I guess you misunderstand how local search works. 
The assignment is not managed, changed during search. At a leaf, all neighborhoods are created, tested, and successful ones are propagated back to the variables.

This only happens there, and the purpose of the search monitor (and search limit), this is an atomic operation.

**Comment by braktar** [comment]
If I understand well, when we are within the scope of AtSolution() All constraints are propagated to the variables. So has I can access the intermediate solution even if some still have unfixed values, but a reduced set. Why couln't I access the IntervalVar ?

**Comment by lperron** [comment]
Why do you need the container ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 13 août 2019 à 08:26, Gwénaël Rault <notifications@github.com> a
écrit :

**Comment by braktar** [comment]
The use case is the following : 

We are monitoring the improvement of the best solution. So every time a new best solution is found we store it. The detail is not really important but we need to know the order of the nodes and the IntervalVar Container is needed to get an estimation of where are placed the breaks in the solution.

**Comment by lperron** [comment]
You are at a leaf, you need to look at the IntervalVar variables, not at
the assignment container, which, IMO, will not contain anything useful.

Still, I am only vaguely familiar with that code.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 13 août 2019 à 09:06, Gwénaël Rault <notifications@github.com> a
écrit :

**Comment by braktar** [comment]
Ok, I was assuming that the IntervalVarContainer would avoid me to define some redundant variables. That was the point of my misunderstood. Thank you for the clarification !
