### ISSUE TITLE
7.3 running too slow

### ISSUE THREAD

**Issue by binnympaul** [google/or-tools#1495]
7.3 is running significantly slow compared to 7.2.

**Comment by lperron** [comment]
Please, this is not useful at all.

**Comment by lperron** [comment]
At least provide a context, some code, some experiments you did.

All our internal tests show the contrary.

**Comment by binnympaul** [comment]
I'm sorry for not providing enough info. I'm a basic user of a population synthesis software - https://github.com/RSGInc/populationsim

populationsim uses ortools as a dependency to solve LPs. During a single run of popualtionsim, thousands of LPs are solved, so I cannot tell you the exact run time for each LP. However total runtime for populationsim on a Windows Server 2012 with 160GB RAM used to be around 60 minutes with the last version of ortools - 7.2.6. Now, with 7.3, the runtime have has increased almost 5-6 times. We see a lot more logging from ortools with the new version. 

It is great if your tests do not show any increase in runtimes. Perhaps, there are some settings that we are not aware of? I'm just guessing at this point. Any help will be appreciated!

**Comment by lperron** [comment]
Interesting.

The lp code was touched, but all our experiments on the netlib did not show
any slowdown

Can you send us a model that exhibits the slowdown ?

**Comment by binnympaul** [comment]
The slower runtime was due to inconsistency in versions of other dependencies. I possible please delete the issue. Thanks!
