### ISSUE TITLE
Help: Strange error on referencing IntVar variable

### ISSUE THREAD

**Issue by gustavo-barros** [google/or-tools#1502]
Hello there,

anyone has any clue what is happening for me to have this error?

![image](https://user-images.githubusercontent.com/36746102/63053419-13629b00-beb8-11e9-9489-2bb53fc9eb27.png)
 
I'm using these namespaces
![image](https://user-images.githubusercontent.com/36746102/63053465-2aa18880-beb8-11e9-8e7f-d194c03ea264.png)

**Comment by lperron** [comment]
Does the code still work ?

Most likely an editor error.

In my version of visual studio code, it needs a dotnet restore to start
loading the symbols, and it is error prone.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 14 août 2019 à 13:24, gustavo-barros <notifications@github.com> a
écrit :

**Comment by gustavo-barros** [comment]
yes the code still works

**Comment by gustavo-barros** [comment]
Hey Laurent, you used the last version of dotnet core?

**Comment by lperron** [comment]
Yes, but as I said, symbol lookup, include lookups.is inconsistent, in all
languages.

This is a vs code bug to me.

Le jeu. 15 août 2019 à 05:59, gustavo-barros <notifications@github.com> a
écrit :
