### ISSUE TITLE
Building issues with make and Cmake

### ISSUE THREAD

**Issue by ChengeYang** [google/or-tools#1503]
Sorry I'm new to make / cmake building systems. I'm trying to build **or-tools v7.3** on my **Ubuntu 18.04** PC. After building with both make and cmake, I got the following issues:

1. Build with make:
I downloaded the binary version and followed the instructions from https://developers.google.com/optimization/install/cpp/linux. After extraction, I did  `make cc` to build .o files. 
But what next? I tried `make install_cc` but there is no rule to make target 'install_cc'.
I want to know how to install it as dependency into my system directory like /usr/include. Also how to include it into my project folder (copy /include and /lib folders?)

2. Build with CMake:
I followed the steps at https://github.com/google/or-tools/blob/stable/cmake/README.md.
I did the following:
`git clone`
 `cmake -DBUILD_DEPS:BOOL=ON -H. -Bbuild -G "Unix Makefiles"`
I expect the second one to build all dependencies. But I got the error below at the end of compiling:
```
CMake Error at cmake/cpp.cmake:74 (add_library):
  Target "ortools" links to target "gflags::gflags_static" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:95 (include)
```
I think `gflags` seems to be built successfully.

Thank you!

**Comment by lperron** [comment]
1) There are no install rules. You can copy everything where you want.
2) Cmake support is experimental, and most propably broken now. Please use the instruction to build with make.
