### ISSUE TITLE
Java: read MPS or LP file format ? 

### ISSUE THREAD

**Issue by CharlieXu** [google/or-tools#1505]
I am using Java Google Or-tools.
is there any method to read MPS and LP file format  ? 
It would be very handy to try or-tools with MPS or LP files to test. 
Thanks.

**Comment by lperron** [comment]
If you download the binary archive, and run make bin/solve, you have a
binary that can read MPS files and can use the default solver (I
believe GLOP, BOP, CBC,CLP).
Do you have another use case ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by weedkiller** [comment]
Can you please provide an API to read in C# as well

**Comment by lperron** [comment]
Once again, what is the use case ?

Using the solution will be problematic, as you do not have variables are
hand.

The only thing you can do is run the problem.and look at the log, or get
the status, optimal value ?

I have always believed that a single like all the ones provided with the
solvers will fulfill the same function.

Please tell me.where I am wrong.



Le mer. 4 sept. 2019 à 23:18, weedkiller <notifications@github.com> a
écrit :

**Comment by CharlieXu** [comment]
Thanks for your reply. 
the problem is when we want to test the data from other program. 
And, by the way, I figured out another solution with a self-made JNI to the local CBC.
