### ISSUE TITLE
How to set special variables in a nurse scheduling problem ?

### ISSUE THREAD

**Issue by StarWithRain** [google/or-tools#1507]
Under normal circumstances，we set the variables like this:
 shifts = {}
    for n in all_nurses:
        for d in all_days:
            for s in all_shifts:
                shifts[(n, d, s)] = model.NewBoolVar('shift_n%id%is%i' % (n, d,
                                                                          s))
How could we add this kind of constraint:
`model = cp_model.CpModel()

num_city = 4
num_kind = 3
num_plane_a = 12
num_plane_b = 14
num_palne_c = 3
# Create flight_1 ijk: with kind = 0: the number of times the Kth aircraft returned to Wuhan from Wuhan
flight_1 = {}
j = 0
for i in range(num_city):
    for k in range(num_plane_a):
        flight_1[(i, j, k)] = model.NewBoolVar('flight_1 i%ij%ik%i' % (i, j, k))

flight_2 = {}
j = 1
for i in range(num_city):
    for k in range(num_plane_b):
        flight_2[(i, j, k)] = model.NewBoolVar('flight_2 i%ij%ik%i' % (i, j, k))

flight_3 = {}
j = 2
for i in range(num_city):
    for k in range(num_plane_b):
        flight_3[(i, j, k)] = model.NewBoolVar('flight_3 i%ij%ik%i' % (i, j, k))

# How could we add this kind of constraint ?
model.Add(sum(flight_1[(4, 0, k)] for k in range(num_plane_a))+sum(flight_2[(4, 1, k)] for k in range(num_plane_b)) +
          sum(flight_3[(4, 0, k)] for k in range(num_palne_c)) == 2)`

**Comment by lperron** [comment]
What is the problem ? It should work as you have written, unless there is a syntax error.

**Comment by StarWithRain** [comment]
Here is the problem:
E:\python\python_install\python.exe E:/文档/研一/python学习笔记/数模大赛/Print1.py
Traceback (most recent call last):
  File "E:/文档/研一/python学习笔记/数模大赛/Print1.py", line 31, in <module>
    model.Add(sum(flight_1[(4, 0, k)] for k in range(num_plane_a))+sum(flight_2[(4, 1, k)] for k in range(num_plane_b)) +
  File "E:/文档/研一/python学习笔记/数模大赛/Print1.py", line 31, in <genexpr>
    model.Add(sum(flight_1[(4, 0, k)] for k in range(num_plane_a))+sum(flight_2[(4, 1, k)] for k in range(num_plane_b)) +
KeyError: (4, 0, 0)

Process finished with exit code 1

It seems we cannot set a fixed value for i and j。

**Comment by StarWithRain** [comment]
I tried '   i = 3    print(sum(flight_1[(i, j, k)] for k in range(num_plane_a))) ', it's ok.
when i tied to sum  flight_1[(i, j, k)], flight_2[(i, j, k)], and flight_3[(i, j, k)], it arose problem:
KeyError: (3, 2, 0).
It seems that these three parts cannot be added together.

`from ortools.sat.python import cp_model


model = cp_model.CpModel()
num_city = 4
num_kind = 3
num_plane_a = 12
num_plane_b = 14
num_plane_c = 3
# Create flight_1 ijk: with kind = 0: the number of times the Kth aircraft returned to Wuhan from Wuhan
flight_1 = {}
j = 0
for i in range(num_city):
    for k in range(num_plane_a):
        flight_1[(i, j, k)] = model.NewBoolVar('flight_1 i%ij%ik%i' % (i, j, k))

i = 3
print(sum(flight_1[(i, j, k)] for k in range(num_plane_a)))

flight_2 = {}
j = 1
for i in range(num_city):
    for k in range(num_plane_b):
        flight_2[(i, j, k)] = model.NewBoolVar('flight_2 i%ij%ik%i' % (i, j, k))

flight_3 = {}
j = 2
for i in range(num_city):
    for k in range(num_plane_c):
        flight_3[(i, j, k)] = model.NewBoolVar('flight_3 i%ij%ik%i' % (i, j, k))


print(sum(flight_3[(i, j, k)] for k in range(num_plane_c))+sum(flight_1[(i, j, k)] for k in range(num_plane_a))+
      sum(flight_2[(i, j, k)] for k in range(num_plane_b)))

`
Here is the problem:
Traceback (most recent call last):
((((((((((((flight_1 i3j0k0) + flight_1 i3j0k1) + flight_1 i3j0k2) + flight_1 i3j0k3) + flight_1 i3j0k4) + flight_1 i3j0k5) + flight_1 i3j0k6) + flight_1 i3j0k7) + flight_1 i3j0k8) + flight_1 i3j0k9) + flight_1 i3j0k10) + flight_1 i3j0k11)
  File "E:/文档/研一/python学习笔记/数模大赛/Print1.py", line 33, in <module>
    print(sum(flight_3[(i, j, k)] for k in range(num_plane_c))+sum(flight_1[(i, j, k)] for k in range(num_plane_a))+
  File "E:/文档/研一/python学习笔记/数模大赛/Print1.py", line 33, in <genexpr>
    print(sum(flight_3[(i, j, k)] for k in range(num_plane_c))+sum(flight_1[(i, j, k)] for k in range(num_plane_a))+
KeyError: (3, 2, 0)

**Comment by lperron** [comment]
This is an error in your code.
Make sure you have consistent key access.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 21 août 2019 à 06:09, StarWithRain <notifications@github.com> a
écrit :

**Comment by StarWithRain** [comment]
I found my fault. Here is a right code:
`for i in range(num_city):
    for k in range(num_plane_b):
        for j in range(num_kind):
            flight_1[(i, j, k)] = model.NewIntVar(0, 100, 'flight_1 i%ij%ik%i' % (i, j, k))

model.Add((sum(flight_1[(3, 0, k)] for k in range(num_plane_a)) + sum(flight_1[(3, 1, k)] for k in range(num_plane_b))
       + sum(flight_1[(3, 2, k)] for k in range(num_plane_c))) == 2)
# 飞往城市4的A型飞机， 飞往城市4的B型飞机， 飞往城市4的C型飞机。`
