### ISSUE TITLE
How does the CP-SAT solver works?

### ISSUE THREAD

**Issue by tanishqvyas** [google/or-tools#1508]
Could anyone provide with an explanation on how does the CP-SAT solver (used in constraint programming) works or any leads to the underlying algorithms and principles.

**Comment by stradivari96** [comment]
https://stackoverflow.com/questions/57123397/which-solver-do-googles-or-tools-modules-for-csp-and-vrp-use/57125734#57125734

**Comment by lperron** [comment]
Duplicate of #920
