### ISSUE TITLE
Linear Programming: MPVariable sensitivity

### ISSUE THREAD

**Issue by ylmzkaan** [google/or-tools#1510]
I have a project where the GLOP Linear Solver MPVariable's value should have a minimum increment of 0.05 between bounds 0 and 1. Which MPSolverParameters::DoubleParam should I specify for this?

**Comment by lperron** [comment]
Seems like an integer variable between 0 and 20.
You can use a MIP solver, or the CP-SAT solver.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 22 août 2019 à 11:44, Kaan Yilmaz <notifications@github.com> a
écrit :
