### ISSUE TITLE
CP model AddBoolAnd produces SIGSEV

### ISSUE THREAD

**Issue by woopsix** [google/or-tools#1511]
```
model = cp_model.CpModel()
    solver = cp_model.CpSolver()

    x = model.NewBoolVar('x')

    model.AddBoolAnd([x])

    status = solver.Solve(model)
```

This simple example produces SIGSEV
The constraint is added to the model but when it comes the time to solve it, it breaks.

printing the model results to this: 
```
 variables {
  name: "x"
  domain: 0
  domain: 1
}
constraints {
  bool_and {
    literals: 0
  }
}
```
python 3.7.4
OS: arch

**Comment by lperron** [comment]
from ortools.sat.python import cp_model

model = cp_model.CpModel()
solver = cp_model.CpSolver()
x = model.NewBoolVar('x')
model.AddBoolAnd([x])
status = solver.Solve(model)
print(solver.StatusName(status))

outputs

FEASIBLE

Therefore my question is which version ? which platform ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by woopsix** [comment]
i edited my comment but here they are
platform: Arch Linux
python: 3.7.4
or-tools:  6.10.6025

**Comment by lperron** [comment]
Please use 7.3
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by woopsix** [comment]
upgrading ortools fixed the issue,
Thanks.
