### ISSUE TITLE
How to assign a specific subject to specific level

### ISSUE THREAD

**Issue by DeejaySKL** [google/or-tools#1512]
Making any curriculum to zero leading to status 3(INFEASIBLE) of solver.Solve() in https://github.com/google/or-tools/blob/stable/examples/notebook/school_scheduling_sat.ipynb
For example let 
curriculum = {
    ('1-', 'English'): 3,
    ('1-', 'Math'): 3,
    ('1-', 'History'): 2,
    ('2-', 'English'): 4,
    ('2-', 'Math'): 2,
    ('2-', 'History'): 2,
    ('3-', 'English'): 2,
    ('3-', 'Math'): 4,
    ('3-', 'History'): 2
}
Now suppose level '1-' doesn't have Math class so making `('1-', 'Math'): 0` is leading to INFEASIBLE status.
How to fix this?

**Comment by stradivari96** [comment]
I think you have to check
```
self.problem.curriculum[self.problem.levels[
              level], self.problem.subjects[subject]] > 0
```
before
```
          self.model.Add(
              sum(teacher_courses[course, subject, t]
                  for t in all_teachers) == 1)
```

**Comment by DeejaySKL** [comment]
Thank you @stradivari96 
Can anyone tell actually what the below constraint means?

    # Teacher makes all the classes of a subject's course
    teacher_courses = {}
    for level in all_levels:
      # for section in all_sections:
        course = level #* self.num_sections + section
        for subject in all_subjects:
          for t in all_teachers:
            name = 'C:{%i} S:{%i} T:{%i}' % (course, subject, teacher)
            teacher_courses[course, subject, t] = self.model.NewBoolVar(name)
            temp_array = [
                self.assignment[course, subject, t, slot] for slot in all_slots
            ]
            self.model.AddMaxEquality(teacher_courses[course, subject, t],
                                      temp_array)
          self.model.Add(
              sum(teacher_courses[course, subject, t]
                  for t in all_teachers) == 1)

**Comment by stradivari96** [comment]
Looks like it is assigning a a course and subject to a teacher, eg:
('1-', 'English') -> Mario

Something along the lines of this pseudocode:
```
if any self.assignment['1-', 'English', 'Mario', slot] for slot in all_slots:
    teacher_courses['1-', 'English', 'Mario'] == True
```

And then makes a course and subject assigned to only one teacher:
```
self.model.Add(
          sum(teacher_courses[course, subject, t]
              for t in all_teachers) == 1)
```

**Comment by DeejaySKL** [comment]
And what this line about?
`
self.model.AddMaxEquality(teacher_courses[course, subject, t],
                                  temp_array)
`

**Comment by stradivari96** [comment]
(teacher_courses[course, subject, t] is true) if and only if any self.assignment[course, subject, t, slot] is true.

So a teacher is assigned to a (course, subject) iff it is assigned to a slot of that (course, subject)

**Comment by lperron** [comment]
Closing. Please reopen if needed.
