### ISSUE TITLE
How to use AddDivisionEquality with sum of bool variables 

### ISSUE THREAD

**Issue by ywein** [google/or-tools#1513]
So, I want to maximize relations between two sets of bool variables.
Something like that

```model.Maximize(sum(x[d] for d in data) / sum(y[d] for d in data2))```

It tells me, that I need to use AddDivisionEquality.
So, I do something like that
```
relations = model.NewIntVar(0, 99999, 'relations')
sumX = sum(x[d] for d in data)
sumY = sum(y[d] for d in data2)
model.AddDivisionEquality(relations, sumX, sumY)
model.Maximize(relations)
```

But I get an error:
```TypeError: NotSupported: model.GetOrMakeIndex```

As far as I understand model.AddDivisionEquality expects to get variables directly, not a sum. 
So, I probably need to create an intermediate variables that contains a sum.
But how?

Thanks

**Comment by stradivari96** [comment]
short snippet:

```
from ortools.sat.python import cp_model

model = cp_model.CpModel()

relations = model.NewIntVar(0, 99999, 'relations')

sumX = model.NewIntVar(0, 10, '')
sumY = model.NewIntVar(1, 10, '')
model.Add(sumX == sum([model.NewBoolVar('') for _ in range(10)]))
model.Add(sumY == sum([model.NewBoolVar('') for _ in range(10)]))
model.AddDivisionEquality(relations, sumX, sumY)
model.Maximize(relations)

solver = cp_model.CpSolver()
status = solver.Solve(model)

print(solver.StatusName(status))
```

**Comment by lperron** [comment]
Thanks
