### ISSUE TITLE
Missing assembly reference Immediate Window C#

### ISSUE THREAD

**Issue by kwhite401** [google/or-tools#1514]
When trying to debug, I get: error CS0012: The type 'Solver' is defined in an assembly that is not referenced. You must add a reference to assembly 'Google.OrTools, Version=7.3.7083.0, Culture=neutral, PublicKeyToken=XXXXXXXXXXXXXXXX'.

The assembly is referenced and runs as expected but I cannot use the immediate window. Even when trying to access elements from other assemblies, it throws this error.

**Comment by lperron** [comment]
The usual suspects:
  Have you run the examples in the distrib ?
  Are you using visual studio 2017 (or more) 64 bit ?
  Have you installed vs2017 64bit redistributable?
  If you are using dotnet core, did you run dotnet restore ?
  Is your project a netstandard 2.0  project ?

**Comment by lperron** [comment]
Any news ?
