### ISSUE TITLE
Cannot stop a search (too) prematurely

### ISSUE THREAD

**Issue by Blackhol3** [google/or-tools#1515]
I was investigating the issue #1474 and came across the following problem on the `master` branch: when trying to stop a search prematurely, the following error occurs and the program exits:

> WARNING: Logging before InitGoogleLogging() is written to STDERR
F0823 22:50:38.903817 18376 sorted_interval_list.cc:179] Check failed: !IsEmpty() 
*** Check failure stack trace: ***

I'm using the following code:

	std::atomic<bool> shouldComputationBeStopped(false);

	CpModelBuilder modelBuilder;
	createVariables(modelBuilder);
	createConstraints(modelBuilder);

	Model model;
	model.GetOrCreate<TimeLimit>()->RegisterExternalBooleanAsLimit(&shouldComputationBeStopped);

	switch (0) {
	    case 0:
	        break;
	    case 1:
	        QTimer::singleShot(50, this, [&]() { shouldComputationBeStopped = true; });
	        break;
	    case 2: 
	        QTimer::singleShot(500, this, [&]() { shouldComputationBeStopped = true; });
	        break;
	}

	auto response = SolveCpModel(modelBuilder.Build(), &model);
	qDebug() << lastResponse.wall_time() << "s";

For information, `QTimer::singleShot()` executes the lambda after the given number of milliseconds has passed.

- The switch case `0` prints `1.75s`.
- The switch case `1` failed with the error previously mentioned.
- The switch case `2` prints `1.80s` (which is another problem).

Disabling `cp_model_presolve` does not help.

**Comment by lperron** [comment]
master is unstable. I am trying to fix it.

**Comment by lperron** [comment]
I pushed a tentative fix. Please retry.

**Comment by lperron** [comment]
Seems fixed on my tests. Closing. Please reopen if needed.

**Comment by Blackhol3** [comment]
Fixed indeed, thank you.
