### ISSUE TITLE
externalBooleanAsLimit internally modified when more than one worker is used

### ISSUE THREAD

**Issue by Blackhol3** [google/or-tools#1516]
The value of the atomic boolean passed to the `RegisterExternalBooleanAsLimit()` method is internally set to `true` when the model use more than one worker.

	for (int numWorker = 1; numWorker <= 2; ++numWorker)
	{
		CpModelBuilder modelBuilder;
		auto x = modelBuilder.NewIntVar({0, 5});
		auto y = modelBuilder.NewIntVar({0, 5});
		modelBuilder.AddLessThan(x, y);

		SatParameters parameters;
		parameters.set_num_search_workers(numWorker);

		std::atomic<bool> shouldComputationBeStopped(false);

		Model model;
		model.Add(NewSatParameters(parameters));
		model.GetOrCreate<TimeLimit>()->RegisterExternalBooleanAsLimit(&shouldComputationBeStopped);

		auto response = SolveCpModel(modelBuilder.Build(), &model);
		qDebug() << QString::fromStdString(CpSolverStatus_Name(response.status())) << shouldComputationBeStopped;
	}

This code prints:
> "FEASIBLE" false
"FEASIBLE" true

Given the method name, one can expect that the boolean will not be modified internally.

**Comment by lperron** [comment]
Thanks. We will modify the documentation to specify that it may be modified
by the solver.
