### ISSUE TITLE
Stopping search prematurely and immediately

### ISSUE THREAD

**Issue by Blackhol3** [google/or-tools#1517]
A search can be stopped by setting the external boolean registered with `RegisterExternalBooleanAsLimit()` to `true`. But with a heavy model, it can still take some times.

	CpModelBuilder modelBuilder;
	for (int i = 0; i < 10000; ++i)
	{
		auto x = modelBuilder.NewIntVar({0, 1000});
		auto y = modelBuilder.NewIntVar({0, 1000});
		modelBuilder.AddLessThan(x, y);
	}

This code is solved, in average, in:
- `0.523544s` by default;
- `0.501957s` when the external boolean is set to `true` after 50 ms;
- `0.386621s` when the presolve is disabled;
- `0.417718s` when the presolve is disabled and the external boolean is set to `true` after 50 ms.

Is there any way to stop the search (almost) immediately? Why does the solving time sometimes increases when the external boolean is set to `true`?

**Comment by lperron** [comment]
Because we do not check the limit after every instruction. Checking the
limit is expensive, and we limit the rate of checks.

Furthermore, be careful with user time and wall time. It could explain the
difference between 47 ms and 50 ms.

We will try to improve precision, but a few Ms of delay is not worth
slowing down the solver for.

**Comment by Blackhol3** [comment]
I understand checking is expensive, but we are talking about a solving time of **500 ms** here, despite the boolean being set after **50 ms**. That's one order of magnitude of difference.

**Comment by Blackhol3** [comment]
I've just tried the same experiment with a real model, and stopping takes **20 s**, despite being requested to stop after **50 ms**. That makes pretty much any parallelization impossible, for instance. Is there any other solver step or options, that could be the cause and need to be disabled?

**Comment by lperron** [comment]
Can you send me the proto of the model ?

**Comment by Blackhol3** [comment]
I can't seem to find again the parameters leading to the model with a stopping time of 20 s. [Here](https://github.com/google/or-tools/files/3547567/model.zip) is one needing around 2 s for that, if it helps.
