### ISSUE TITLE
adding more than 10 vehicles results in no solution

### ISSUE THREAD

**Issue by davide-malagoli** [google/or-tools#1518]
Hi,

I found a strange behaviour, apparently.
I wrote a script ( [vrptw.zip](https://github.com/google/or-tools/files/3538554/vrptw.zip) ) to solve a routing problem with:

- different vehicle capacities
- time windows
- different vehicle costs

The strage thing is: if add 1 more vehicle after the tenth, the algorithm fails to find a solution ( I'd expect a similar thing removing a vehicle, not adding it).

To reproduce this issue just change the line

`
data['vehicle_capacities'] = [30, 30, 30, 30, 30, 30, 50, 50, 50, 50]
data['vehicle_varcost']=[1,2,3,4,5,6,11,12,13,14]
`

in something like this

`
data['vehicle_capacities'] = [30, 30, 30, 30, 30, 30, 50, 50, 50, 50, 50]
data['vehicle_varcost']=[1,2,3,4,5,6,11,12,13,14,15]
`

and launch the script

The answer I get is

> Nessun soluzione trovata
>Tempo totale di calcolo del programma: 0h 0min 30sec

What could cause this?

My version of ortools is 7.3.7083

Thanks in advance

**Comment by lperron** [comment]
From a quick glance, are you sure the scheduling constraints at the depot
and at the end can be satisfied with 11 vehicles ?
The optional are not optional, even if the vehicles are not active.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le dim. 25 août 2019 à 22:05, davide-malagoli <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
Any news ?

**Comment by davide-malagoli** [comment]
I think the depot constraints where the key, thank you
