### ISSUE TITLE
How to use cumulative constrain option inside job shop scheduling problem?

### ISSUE THREAD

**Issue by YooTimmy** [google/or-tools#1519]
Hello All,

Now I am trying to further develop the Job Shop Scheduling problem, by considering that there is a max capacity for each of the machines. The sum of time needed for tasks assigned on each machine cannot exceed it overall capacity.
During my search, I came across the term "Cumulative constraint", which I think solves the problem I have. But however, I could not find a working example or available sources. May I know if  anyone can give me some suggestions?
Below is the link I found explaining the basics including "Cumulative constrains", but there are no example codes given(looks not finished yet). 
https://github.com/google/or-tools/blob/master/ortools/sat/doc/scheduling.md#cumulative-constraint

**Comment by lperron** [comment]
Search for rcpsp_sat in examples/python.

**Comment by YooTimmy** [comment]
Thank you for your quick reply!
