### ISSUE TITLE
Create constraints based on previous shifts assignments?

### ISSUE THREAD

**Issue by hichiaty** [google/or-tools#1520]
Hi,

I am following the Example on the nurse scheduling problem in the docs (https://developers.google.com/optimization/scheduling/employee_scheduling), but have been stuck on this for a while now.

My data is in the same structure with shifts[(n,d,s)] being a key to the boolvar. I have 3 shifts per day (0,1,2). How do I implement a constraint such that a nurse cannot be assigned for shift 0 if they have been assigned to either shifts 1 or 2 the day before?

**Comment by stradivari96** [comment]
There are many ways, take a look at https://github.com/google/or-tools/blob/stable/ortools/sat/doc/boolean_logic.md#reified-constraints

One way could be:
model.AddBoolAnd([a.Not(), b.Not()]).OnlyEnforceIf(c)

**Comment by lperron** [comment]
Please have a look at:

https://github.com/google/or-tools/blob/stable/examples/python/shift_scheduling_sat.py
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 27 août 2019 à 08:36, Xiang Chen <notifications@github.com> a
écrit :
