### ISSUE TITLE
intermediate_solutions_program results mismatch with docs

### ISSUE THREAD

**Issue by abduakhatov** [google/or-tools#1523]
According to this [intermediate_solitions_program](https://developers.google.com/optimization/cp/cp_solver#intermediate_solutions_program) the intermediary solution should be printed. But when I run exactly the same code on my machine the number of solutions is one, while in this reference there are seven optimal solutions. What`s wrong?

**Comment by stradivari96** [comment]
Looks like the solver improved and doesn't need those intermediate solutions anymore in this case.
You can see that by hinting wrong values and creating more intermediate solutions:

```
model.AddHint(z, 0)
model.AddHint(y, 0)
```

So, not really a issue.

**Comment by abduakhatov** [comment]
@stradivari96 thanx for instance reply!

**Comment by lperron** [comment]
Yes, now we branch directly in the direction of the objective.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 27 août 2019 à 14:59, Xiang Chen <notifications@github.com> a
écrit :

**Comment by abduakhatov** [comment]
@stradivari96 what will happen if I call another cp_model solver, with seperate constraints and logic, from intermediary callback method?

**Comment by lperron** [comment]
It should works. But is would be fairly expensive.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by abduakhatov** [comment]
@stradivari96 @lperron even after AddHint(...) it returned few solutions - 2 or 3 max. Could you explain,why it is so, ?

**Comment by stradivari96** [comment]
The real question is, why do you need those intermediate suboptimal solutions?

**Comment by lperron** [comment]
Because the problem  is so trivial it will converge towards the optimal
very fast.

BTW, the best possible solver only returns one solution.

Le mar. 27 août 2019 à 17:40, Xiang Chen <notifications@github.com> a
écrit :

**Comment by abduakhatov** [comment]
@stradivari96 for my case I am using two level solver(), as ortools is not imperative. So, one solver calls another solver within callback. I know this is really heavy but this approach is suitable for my case. That is why suboptimal solutions are rather helpful for my case, as the most optimal solution of the upper solver can not optimal for the inner one.

**Comment by abduakhatov** [comment]
By the way, which ortools version is supporting what I need?

**Comment by lperron** [comment]
I do not understand. Any version should work. You should use the latest.
