### ISSUE TITLE
MIP: setting permitted values for MPVariable

### ISSUE THREAD

**Issue by ylmzkaan** [google/or-tools#1524]
I have a mixed integer programming problem where my variable can take integers between 0-100 but not 1 and 2. Is it possible to embed this logic to MIP?

To solve this problem I am thinking about setting the variable boundaries to 3 and 100 and running the optimization multiple times for every single combination of variables (variables left out of the optimization will be logically set to zero). Finally I will take the combination that leads to lowest cost function value. This is certainly not efficient and I am looking for other ideas.

**Comment by lperron** [comment]
Yes with Big-M formulations.
You can also look at CP-sat if you problem does not have continuous
variables.

Le mar. 27 août 2019 à 16:37, Kaan Yilmaz <notifications@github.com> a
écrit :
