### ISSUE TITLE
getting "Error 128" in: tools\make third_party

### ISSUE THREAD

**Issue by Beh83** [google/or-tools#1527]
Hi,
When I enter >>tools\make third_party via x64 Native Tools this is what I get after a minute or two:
...
include/google/protobuf/wire_format_lite.h
include/google/protobuf/wrappers.pb.h
include/google/protobuf/wrappers.proto
tools\win\rm.exe -rf dependencies/sources/abseil-cpp-bf29470
git clone --quiet https://github.com/abseil/abseil-cpp.git dependencies\sources\abseil-cpp-bf29470
cd dependencies\sources\abseil-cpp-bf29470 && git reset --hard bf29470
HEAD is now at bf29470 Export of internal Abseil changes. -- bdce7e57e9e886eff1114d0266781b443f7ec639 by Derek Mauro <dmauro@google.com>:
cd dependencies\sources\abseil-cpp-bf29470 && git apply "C:\\Users\\Arvin\\Documents\\VisualStudio2017\\ORTsource\\or-tools-stable\patches\abseil-cpp-bf29470.patch"
error: can't open patch 'C://Users//Arvin//Documents//VisualStudio2017//ORTsource//or-tools-stable/patches/abseil-cpp-bf29470.patch': No such file or directory
make: *** [dependencies/sources/abseil-cpp-bf29470] Error 128

But the patch file exists there. Any idea?

**Comment by lperron** [comment]
Maybe a different for client ?

**Comment by Beh83** [comment]
Sorry, I didn't get your point.
You mean I change the path?
Install from somewhere other than Documents folder of a user?

**Comment by lperron** [comment]
The path does not contains spaces. Still, git cannot patch it. Maybe you
have an older version of git.

**Comment by Beh83** [comment]
Ok, so good, so far!
Now I've got that the problem is about swigwin-4.0.0
swigwin-4.0.0.zip is not located in \dependencies\archives\
Where can I find the file to copy it manually?

**Comment by lperron** [comment]
It seems swigsin just released a new version. Can you bump SWIG_TAG to
4.0.1 in makefiles/Makefile.thid_party.win.mk ?

**Comment by lperron** [comment]
And it should be downloaded automatically. Maybe it failed to do so. You
can check the logs.

**Comment by Beh83** [comment]
OK, now Cbc-2.10.3.zip is missing!
I will try to find and copy it manually also.
The things are getting very interesting!!

**Comment by Beh83** [comment]
Solved it too!
Now: Windows SDK version 8.1 was not found.
Going to fix it...

**Comment by lperron** [comment]
Are you sure the downloads are working fine ? Can you check the logs ?

**Comment by Beh83** [comment]
I've checked the logs, downloads failed and I tried them manually.
Apparently, the manual operations are fine. Now, I am installing Windows SDK version 8.1 to get rid of some red line errors! 
I will definitely let you know the outcome, thank you Laurent.

**Comment by Beh83** [comment]
Ok, after installing the SDK 8.1 a lot of errors showed up which forced me to also update Windows Universal CRT SDK. Then I've got a lot of warnings in yellow but fortunately no error!
However, when I try: tools\make dotnet this error shows:
makefiles/Makefile.third_party.win.mk:63: *** Third party SCIP files was not found! please check the path given to WINDOWS_SCIP_DIR.  Stop.
Please note that "WINDOWS_SCIP_DIR=c:\Program Files\SCIPOptSuite 6.0.2" already exists in Makefile.local
What may cause the problem?

**Comment by lperron** [comment]
The space in the path can cause problems.
What is the exact line in the makefile ?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Beh83** [comment]
I changed it to:
WINDOWS_SCIP_DIR=C:/Program Files/SCIPOptSuite-6.0.2
but no success

**Comment by Beh83** [comment]
The test failed.
Knapsack.csproj build was successful but after that:
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Google.OrTools.Algorithms.operations_research_algorithmsPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'Google.OrTools.runtime.win-x64.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by lperron** [comment]
You need to add SCIP dll to your path

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Beh83** [comment]
Would you please explain more?
which .dll should I add and where to add it?

**Comment by lperron** [comment]
Make sure the path to scipoptsuite6.0.2/lib is in your PATH variable.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Beh83** [comment]
OK, going for that...
