### ISSUE TITLE
Is there any data volume limitation of or-tools?

### ISSUE THREAD

**Issue by Thomas-Lei** [google/or-tools#1528]
We got 2000 jobs and 10 machines flow shop problem every day. It seems over the capacity of or-tools. I always run into the program errors with such big data volume.

**Comment by lperron** [comment]
There are no data volume.maybe a 2 GB size limit on the protobuf.

Which solver are you using ?

Le mer. 28 août 2019 à 10:37, Thomas Lei <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
And we load very large minizing models without problems.
