### ISSUE TITLE
SCIP does not take effect from MIP relative gap

### ISSUE THREAD

**Issue by Beh83** [google/or-tools#1529]
Hi,
A C# code calls OR Tools to solve a MIP problem.
The following section tries to change some default values for the solver (SCIP):

MPSolverParameters RG = new MPSolverParameters();
MPSolverParameters.DoubleParam Foo = new MPSolverParameters.DoubleParam();
RG.SetDoubleParam(Foo, 0.002);
solver.SetTimeLimit(20000);                        
Solver.ResultStatus resultStatus = solver.Solve(RG);

However, apparently, the solver returns the first solution found (almost immediately).
The result status is OPTIMAL.
When you substitute the place of constraints in the constraint matrix the result changes.
For example, put the 7th constraint as the 3rd one and the 3rd as the 7th and you will get a new solution (also with OPTIMAL status).
There should be a problem in the above code that the MIP relative gap does not take effect. But what?
The same problem has been observed with CBC solver, previously.

**Comment by Beh83** [comment]
It seems that setting a large gap (e.g. 0.99) has some effects since the objective function will become very large. 
But small values do not serve as expected. For example, the result with 0.01 is better than that of 0.001.

**Comment by lperron** [comment]
Then it is a scip bug, not an or-tools one.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Beh83** [comment]
If it is the solver bug, CBC and SCIP have it both.
I believe it worth further investigation by the solvers developers.
