### ISSUE TITLE
What does solver.EnableOutput() do?

### ISSUE THREAD

**Issue by Beh83** [google/or-tools#1531]
Hi,
I have used solver.EnableOutput() to trace SCIP log during optimization.
However, nothings happen. I mean the process is the same with and without the command. 
Is there any way to see the solver log during the optimization process?

**Comment by lperron** [comment]
It does. Scip prints output on stdout.

**Comment by Beh83** [comment]
Where can I find this output? Is it printed in an specific .txt file?

**Comment by lperron** [comment]
As I said, stdout, sandard console output

**Comment by Beh83** [comment]
I've tried to see that standard console output by the following code just after the solve.solve statement:
Console.WriteLine("Standard Output Stream: {0}",  Console.Out);
but nothings happen. With or without the above code no console output shows up.
Am I missing something obvious?

**Comment by lperron** [comment]
I do not know.
SCIP is a C program that uses the C version of stdout.

I do not know the link between Console.Out and stdout.

I believe that in Visual Studio, stdout is captured.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Beh83** [comment]
Thank you. If I solve this problem, I will share the solution here.

**Comment by lperron** [comment]
Thanks. Closing in the meantime.

**Comment by Beh83** [comment]
I have found the solution:
You should add console to your winform application (if it is a winform application, as mine).
One easy way for the debugging case is to go to the project properties --> Application --> Output type --> Console Application.
There are other ways to add console, however in my application I do not need the console permanently so I added it in the above explained manner and I will finally remove that console by going to project properties --> Application --> Output type --> Windows Application.
