### ISSUE TITLE
[HELP] How to add vehicle assignment order constraint?

### ISSUE THREAD

**Issue by xXcoronaXx** [google/or-tools#1532]
Hi,

I would like to know if it is posible to assign routes to each vehicle by the order we want.

I mean first all to vehicle 2, then 1, then 3 ....

thanks

**Comment by lperron** [comment]
Not directly. This should be in the cost function.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 29 août 2019 à 18:36, Antonio Acevedo <notifications@github.com> a
écrit :

**Comment by xXcoronaXx** [comment]
Could you share an example of cost function?

**Comment by lperron** [comment]
Add a fixed cost per vehicle that reflects the priorities.
If you make them small, they will not interfere with the routes.

See: http://google.github.io/or-tools/python/ortools/constraint_solver/pywrapcp.html#pywrapcp.RoutingModel.SetFixedCostOfVehicle

**Comment by xXcoronaXx** [comment]
Hi again,

i'm still trying this...

when i add this line to my program 
            routing.SetFixedCostOfVehicle((vehicle_id+1),vehicle_id)
the route dist change drasticaly. I'm not sure why? Can someone give a full example using SetFixedCostOfVehicle()?

thanks
