### ISSUE TITLE
[Help] VRP - Find optimal location for depots

### ISSUE THREAD

**Issue by thucnc** [google/or-tools#1533]
Given a number of delivery locations with vehicle capacity, how to find optimal locations for depots ? I have 2 scenarios:
- Given N depots with fixed locations, how to find other M depots locations to minimize traveling distance of whole fleet.
- We have to find all optimal depots.

With VRP I can find optimal routes based on current depots, but I don't know how to place more depots to make the system more optimal.

**Comment by lperron** [comment]
From what I understand, this is a completely different problem.
It is called something like logistic network design.
