### ISSUE TITLE
No effect of MPSolverParameters on the solution in C#

### ISSUE THREAD

**Issue by Beh83** [google/or-tools#1534]
Hi,
The following code tries to set MIP gap on 0.0001:
...
MPSolverParameters RG = new MPSolverParameters();            
RG.SetDoubleParam(MPSolverParameters.DoubleParam.RELATIVE_MIP_GAP, 0.0001);
Solver.ResultStatus restatus = Slvr.Solve(RG);
...
If you change 0.0001 to 0.1 or 0.9 it has no effect on the final solution, nevertheless what the solver is. It seems that MPSolverParameters is not passed to the solver at all.
I have traced the code via breakpoint and found that RG contains some default values which is independent of the user code.
Is the above code wrong for setting MPSolverParameters?

**Comment by lperron** [comment]
Which solver ?

**Comment by Beh83** [comment]
SCIP and CBC both.

**Comment by Beh83** [comment]
The above mentioned code works for the both solvers.
The problem was some where in my code.
I have changed the value and checked the effect. It is interesting to mention that SCIP is almost 4 times faster than CBC in my case study.
