### ISSUE TITLE
SCIP 6.0.1/6.0.2 does not work with OR-Tools 7.3

### ISSUE THREAD

**Issue by syxolk** [google/or-tools#1536]
Hi, I'm currently trying to use SCIP together with OR-Tools v7.3.

## SCIP 6.0.1
First, I tried this version because it worked with well with OR-Tools v7.2. I compiled SCIP using the SCIP Optsuite and the Optsuite Patch. I took the cmake command from here https://github.com/google/or-tools/issues/1115

```shell
tar -xvf scipoptsuite-6.0.1.tgz
tar -xvf scipoptsuite-6.0.1_patch01.tgz -C ./scipoptsuite-6.0.1
cd scipoptsuite-6.0.1

cmake -H. -Bbuild -DSHARED=OFF -DGMP=OFF -DGCG=OFF -DSYM=none -DIPOPT=OFF -DREADLINE=OFF -DZIMPL=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX=$HOME/scip
cmake --build build --target install
```

Then I did the usual compile steps for OR-Tools:
```shell
make third_party
echo "UNIX_SCIP_DIR=/home/your-user-name/scip" >> Makefile.local
make python
make install_python
```

However, when importing `from ortools.linear_solver import pywraplp` I get the following error:

```
    from ortools.linear_solver import pywraplp
../../../.local/lib/python3.7/site-packages/ortools-7.3.7083-py3.7-linux-x86_64.egg/ortools/linear_solver/pywraplp.py:13: in <module>
    from . import _pywraplp
E   ImportError: /home/user/.local/lib/python3.7/site-packages/ortools-7.3.7083-py3.7-linux-x86_64.egg/ortools/linear_solver/../../ortools/.libs/libortools.so: undefined symbol: _ZTIN6soplex6SoPlexE
```

**Relevant error:** `libortools.so: undefined symbol: _ZTIN6soplex6SoPlexE`

## SCIP 6.0.2
Then I saw another compile command for SCIP 6.0.2 in OR-Tools' `Makefile.local`, so I tried that as well. Since there is no Optsuite Patch for that version, I compiled without it.

```
make install scipoptlib GMP=false ZIMPL=false READLINE=false INSTALLDIR=<path>/scipoptsuite-6.0.2 TPI=tny USRCFLAGS=-fPIC USRCXXFLAGS=-fPIC USRCPPFLAGS=-fPIC
```

I cleaned and recompiled OR-Tools, put the other path in `Makefile.local` and again imported the python package to get this error:

```
    from ortools.linear_solver import pywraplp
../../../.local/lib/python3.7/site-packages/ortools-7.3.7083-py3.7-linux-x86_64.egg/ortools/linear_solver/pywraplp.py:13: in <module>
    from . import _pywraplp
E   ImportError: /home/user/.local/lib/python3.7/site-packages/ortools-7.3.7083-py3.7-linux-x86_64.egg/ortools/linear_solver/../../ortools/.libs/libortools.so: undefined symbol: _threadnumber
```

**Relevant error:** `libortools.so: undefined symbol: _threadnumber`

**My questions**:
- What is the currently supported SCIP version?
- What compile command I should use?

**Comment by lperron** [comment]
https://developers.google.com/optimization/install/cpp/source_linux

I use cmake on linux

**Comment by syxolk** [comment]
It finally works with SCIP 6.0.2 and the following build commands:

```shell
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=scip/install/dir -DGMP=false -DZIMPL=false -DTPI=tny -DPARASCIP=true ..
make
make install
```

Thanks!
