### ISSUE TITLE
CP-SAT StopSearch() does not work in java 

### ISSUE THREAD

**Issue by prissky** [google/or-tools#1537]
(issue #1474 did not reopen)
If the delay of stopSearch() is set shorter than the time needed for the Search to be started, it never stops. Current Master is unstable and so far I can not see any improvement. Are the aforementioned tests public?
[proto.zip](https://github.com/google/or-tools/files/3565894/proto.zip)

**Comment by lperron** [comment]
Which version ?

master is stable now,

**Comment by prissky** [comment]
Latest (unsuccessful) test was performed yesterday (after commit 88054f79e687174ea67ebc95dca7c06b35659b06).

**Comment by lperron** [comment]
how are you using stopSearch() ?

**Comment by lperron** [comment]
because if I use Ctrl-C during presolve, which should do the same, the solver stop, a bit slowly I agree. But search never starts, and it ends with status UNKNOWN.

**Comment by gregy4** [comment]
I tried small example with attached proto file, at first I thought that it works on version 7.3 but later I found that when you call stopSearch method too early - for this data on my computer between 0-1.6s after start of solve, it doesn't work.

Visually line "Parameters: log_search_progress: true num_search_workers: 8" is displayed after my text informing me that stopSearch method was called.

[TestStopSearch.zip](https://github.com/google/or-tools/files/3578388/TestStopSearch.zip)

**Comment by lperron** [comment]
Thanks a lot.

Fixed on master.
