### ISSUE TITLE
Issue with vehicle maximum travel distance for a route - python script

### ISSUE THREAD

**Issue by shanuu1809** [google/or-tools#1538]
Hi,

I have added a below-mentioned piece of code to my python script for not allowing a vehicle to travel more than 500km in a single route. But I can see even if I have implemented the max distance constraint to 500 I am getting routes where total distance is greater than 500km.

*CODE*
def distance_callback(from_index, to_index):
        """Returns the distance between the two nodes."""
        # Convert from routing variable Index to distance matrix NodeIndex.
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return data['distance_matrix'][from_node][to_node]

    transit_callback_index = routing.RegisterTransitCallback(distance_callback)

    routing.AddDimension( transit_callback_index,
        0,  # no slack
        MAX_DISTANCE,  # vehicle maximum travel distance 500km
        True,  # start cumul to zero
        'Distance')

    distance_dimension = routing.GetDimensionOrDie('Distance')

Please let me know what I am missing or what I have to add in here.

**Comment by lperron** [comment]
an error in your code, maybe in the computation of the final distance.

WIthout any code, we cannot debug anything.
