### ISSUE TITLE
SimpleMinCostFlow to take floating costs in pywrapgraph

### ISSUE THREAD

**Issue by AntixK** [google/or-tools#1539]
It had been pointed out in #687 that this problem has been resolved in v6.9. However, I am still facing this problem in version 7.3. I am using the python wrapper pywrapgraph.

I could definitely use some help with dealing with floating costs for this problem. 
Thank you!

P.S. Also mentioned in #687 to reformulate the problem and use LPsolver. I am afraid I don't know how to do that. Could anyone please help me with that? 
Any help is appreciated.

**Comment by lperron** [comment]
you can scale all coefficients to be integer (multiply by 1000 and round to
integer) ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by AntixK** [comment]
Yes, that is precisely what I am doing now. I was just wondering if there was another proper way as this issue was moved to Done in Kanban.
