### ISSUE TITLE
Adding non-linear contsraint on variable interdependence

### ISSUE THREAD

**Issue by genuinelucifer** [google/or-tools#154]
I don't know if it can be done or not. I tried but could not find a method/way to do this.
.
The basic problem that I have is:
If I have 3 variables say x1, x2, x3 satisfying some constraints. All the variables are integers in the range of [0, inf)
I also want to add one constraint that says that ATLEAST 1 out of these 3 MUST be zero. 
I can write the constraints mathematically as:
   x1 * x2 * x3 = 0
But how do I put such constraint in my program. ( I'm using Java)
Please help

**Comment by jneuhaus** [comment]
I believe you must make another variable that is the result of your 
calculation below.
------------------------------------------------------------------------
Joe Neuhaus <http://ca.linkedin.com/in/josephneuhaus> | 514-484-6713
------------------------------------------------------------------------

**Comment by genuinelucifer** [comment]
I just stumbled upon or-tools via a google search a couple of days ago.
.
I don't know which functions to use to create the product variable and most
importantly how to put it in the constraints while invoking the solver.
I've seen a few examples but couldn't understand.

**Comment by supermihi** [comment]
In C++, this would be
`Solver.Add(Solver.MakeProd(x1, Solver.MakeProd(x2, x3)))`
Don't know the exact Java Syntax but it's probably very similar. There might even be overloaded operators, such that you can write
`Solver.Add(x1 * x2 * x3)`
This seems to work in C#, at least.

**Comment by genuinelucifer** [comment]
Thanks a lot. It worked!

**Comment by genuinelucifer** [comment]
Just one more question though. I want to minimise an objective function too along with finding a solution (local minima would do).
```MPSolver``` can solver linear integer problems minimising an objective function but doesn't have the flexibility to add non linear constraints such as this one.
On the other hand, the simple constraint ```Solver``` can solve problems with such constraints but doesn't have an option to add an objective function to minimise.
Although, I could loop through all the solutions from constraint solver and minimise the objective function, is there any other way to do this?

**Comment by lperron** [comment]
Hi,

The cp solver supports optimization. See Solver.MakeMinimize() and
Solver.MakeMaximize().


To support the original constraint, in the CP solver, I would do the
following

IntVar* const x1_non_zero = solver.MakeIsGreaterVar(x1, 0);
IntVar* const x2_non_zero = solver.MakeIsGreaterVar(x2, 0);
IntVar* const x3_non_zero = solver.MakeIsGreaterVar(x3, 0);
IntVar* const sum_non_zero = solver.Sum({x1_non_zero, x2_non_zero,
x3_non_zero})->Var();

solver.AddConstraint(solver.MakeLessOrEqual(sum_non_zero, 2));

This should be a little faster.

Thanks




Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-02-09 16:03 GMT+01:00 Abhinav Tripathi <notifications@github.com>:

**Comment by genuinelucifer** [comment]
@lperron Thanks a lot! It really helped.

**Comment by genuinelucifer** [comment]
Sorry for closing and re-opening this.
.
I was looking into ```makeMinimise``` but couldn't understand what the second argument is for.
Is there any method-wise documentation where I could see all these stuff.
If not, then it would be extremely helpful if someone could explain the syntax for this.

**Comment by lperron** [comment]
The second argument is the step.

with a step of n, when finding a solution with objective value = o, then
you will search for a solution value <= o - n.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-02-09 16:24 GMT+01:00 Abhinav Tripathi <notifications@github.com>:

**Comment by genuinelucifer** [comment]
Thanks.
.
I couldn't find many java examples. But, the C++ examples helped a lot as the names of the functions and classes are same in both.
Thanks everyone.
