### ISSUE TITLE
CP-SAT/Python how to save an initial solution and use it for next stage optimization

### ISSUE THREAD

**Issue by YooTimmy** [google/or-tools#1542]
Hello everyone,

I am trying to solve a multi-objective issue on top of the current flexible job shop scheduling problem. After searching in the forum, I noticed that there are several topics on this (#1344 and #1152 ). However, I tried to follow the codes and seems they are not working anymore. 
More specifically, I have tried the following:
```
model.Minimize(cost1)
solver.Solve(model)
for i,field in enumerate(model._CpModel__model.variables):
    model._CpModel__model.solution_hint.vars.extend([i])
    model._CpModel__model.solution_hint.values.extend([solver._CpSolver__solution.solution[i]])
    print("{} has value {}".format(field.name,solver._CpSolver__solution.solution[i]))
```
and seems the CpSolver__solution is depreciated. I am not able to find what is the proper alternatives after searching. Could anyone help to provide an updated code sample?

Many thanks in advance.

**Comment by stradivari96** [comment]
On the issue I opened there is this piece of code:
```
model.Proto().solution_hint.Clear()
for i in range(len(model.Proto().variables):
    model.Proto().solution_hint.vars.append(i)
    model.Proto().solution_hint.values.append(solver.ResponseProto().solution[i])
```

**Comment by YooTimmy** [comment]
Thank you for getting back.

Yes I have tried your code as well, but for me it is not working with following error code:
AttributeError: 'NoneType' object has no attribute 'solution'
so it other words solver.ResponseProto() is not returning anything in my case.

**Comment by stradivari96** [comment]
Is the solver status feasible or optimal?
```
status = solver.Solve(model)
print(solver.StatusName(status))
```

**Comment by lperron** [comment]
for var in all_vars:
  model.AddHint(var, solver.Value(var))

You need to keep a list of variables to iterate on.

You need to make sure that the solver found a solution (as said above).
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 3 sept. 2019 à 11:10, Xiang Chen <notifications@github.com> a
écrit :

**Comment by YooTimmy** [comment]
Hello All,

Sorry for my late reply.
Seems I did not clear up my code during my previous trails, and when I tried @stradivari96 's code sample again, now it is working normal :)
Just a few follow up questions to understand about this method more:
1) As we are trying to solve a multi-objective question, when solving the problem in separate stages, will it lead some less optimal results? I dont have any evidence on this, but it just seems to me that solving 2 objectives in 2 separate stages is different from considering the 2 objectives in 1 stage. Would appreciate it if you could elaborate more.
2) Say we have 3 objectives with different priority, it is true that we should solve the high priority first, followed by medium and lastly low priority? I actually tried to play around this part, and seems sometimes the output schedule is similar when I switch the sequence of objectives. Maybe that is because my problem is quite simple, just wanna to double confirm on this.

Thank you again!

**Comment by lperron** [comment]
1) You could emulate 2 stages with 1 stage and a weighted objective with very big coefficients on the first part, and small ones on the second part. But, (a) we are limited to int64, so there is a limit on the number of objective in your multi-objective problems, and (b), adding more coefficients and more penalties complexify the models and can make it unsolvable.

2) it is true, and yes, your model is too simple.

**Comment by YooTimmy** [comment]
Thank you Laurent, for your comments. Appreciated!
