### ISSUE TITLE
[HELP] How to get distance matrix without setting depot

### ISSUE THREAD

**Issue by TheBigRed** [google/or-tools#1545]
I want to find the best route with given addresses however I just want a starting point and no depot

**Comment by lperron** [comment]
Answered on the mailing lists.

Create one dummy node per vehicle, with distance 0 from any node, and one
out arc to the depot (with distance 0 too).
Bonus, you can get the vehicle var of each dummy node and restrict it to
{-1, id_of_vehicle}.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
