### ISSUE TITLE
Feature Request: Allow capacity in cumulative constraint in CP solver to be time dependent

### ISSUE THREAD

**Issue by jschelbert** [google/or-tools#1546]
Hi,
at the moment the cumulative constraint in the CP solver is defined as follows
```
for all t:
  sum(demands[i]
    if (start(intervals[t]) <= t < end(intervals[t])) and
    (t is present)) <= capacity
```
As you can see, the capacity is "static", i.e. not dependent on the time $t$. My request would be to also allow a time dependent capacity. The definition would then be
```
for all t:
  sum(demands[i]
    if (start(intervals[t]) <= t < end(intervals[t])) and
    (t is present)) <= capacity[t]
```
with 
```
capacity: The maximum capacity of the cumulative constraint. It must be a
  positive integer value or variable, or list of length t of positive integer values or variables.
```

**Comment by lperron** [comment]
Just create fixed intervals with fixed demands to shape the capacity.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 4 sept. 2019 à 08:49, Jakob Schelbert <notifications@github.com> a
écrit :

**Comment by jschelbert** [comment]
Hi Laurent,
Thank you for the hint. This will will work for fixed capacity.
It will, however, not work if you have a variable capacity for each time bucket. Any suggestions how to model this?

**Comment by lperron** [comment]
Fixed intervals with variable capacity.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 4 sept. 2019 à 10:36, Jakob Schelbert <notifications@github.com> a
écrit :

**Comment by jschelbert** [comment]
Thanks :)
