### ISSUE TITLE
Use mypy-protobuf to enable type hinting and autocompletion

### ISSUE THREAD

**Issue by stradivari96** [google/or-tools#1547]
https://github.com/google/or-tools/pull/1544 makes more sense as an feature request.
EDIT: #1544 has been dropped

This allows some IDEs such as PyCharm to autocomplete and infere types:

![Screenshot from 2019-09-03 22-38-33](https://user-images.githubusercontent.com/19752586/64207252-8c905500-ce9c-11e9-8839-cf1a754554e0.png)
![Screenshot from 2019-09-03 22-38-52](https://user-images.githubusercontent.com/19752586/64207261-9023dc00-ce9c-11e9-9587-811cdfa8854a.png)

To enable this:
* [x] CMake
  * [x] Add pip install mypy-protobuf
  * [x] Use protoc with --mypy_out= option
  * [x] Add mypy-protobuf in ci docker
* [x] Make
  * [x] Add pip install mypy-protobuf
  * [x] Use protoc with --mypy_out= option
  * [x] Add mypy-protobuf in ci docker
* [x] Add mypy-protobuf in Travis CI
* [x] Add mypy-protobuf in Appveyor CI
* [x] Add mypy-protobuf in tools/docker
* [x] Package `*.pyi` files (see: https://github.com/google/or-tools/pull/1640/commits/2515e62c87af7533d56ec4a081c5cf90500d0277)

Source:
https://github.com/dropbox/mypy-protobuf

**Comment by Mizux** [comment]
The *.pyi files are used by PyCharm and other development tools to provide
more information, such as PEP 484 type hints, than it is able to glean from
introspection of extension types and methods.  They are not intended to be
imported, executed or used for any other purpose other than providing info
to the tools. If you don't use use a tool that makes use of .pyi files then
you can safely ignore this file.

See: https://www.python.org/dev/peps/pep-0484/
     https://www.jetbrains.com/help/pycharm/2016.1/type-hinting-in-pycharm.html

**Comment by Mizux** [comment]
I reopen it since #1544 have been dropped...

**Comment by Mizux** [comment]
Last comment on it
https://github.com/google/or-tools/pull/1544#issuecomment-721703458

**Comment by Mizux** [comment]
now should be fixed, still need to verify release script are working as expected I.e. double check we generating the incoming v8.1
