### ISSUE TITLE
How to realize the push-pull strategy with Google OR Tools?

### ISSUE THREAD

**Issue by YooTimmy** [google/or-tools#1548]
Good Day.

For push-pull strategy for manufacturing, I am referring to here. [https://en.wikipedia.org/wiki/Push–pull_strategy](url)

For the current (flexible) work shop scheduling example available, I think it is more like the push strategy, meaning that the tasks are started as early as possible to shorten the make-span. (Kindly correct me if I am wrong though, still new in this domain.)

However, there are also cases where the pull strategy is favorable, where the schedule is planned based on the deadline in a just in time manner. May I know if there are already existing examples for JSC follow the pull strategy? If not, any advice on the key considerations to use Google OR Tools to make a pull plan schedule?

Thanks and cheers,
Timmy

**Comment by lperron** [comment]
OR-Tools is flexible. You can use different objective. 
A common one is the makespan, but you can try to minimize the distance between the job ends and their deadlines.

You just need to code all this.
