### ISSUE TITLE
Help for VRPTW (Setting a minimum slack time) 

### ISSUE THREAD

**Issue by teddyywj** [google/or-tools#1549]
Hi, 
I am new to Google OR-Tools and am trying to solve a VRPTW problem. 
I have been looking at this [link](https://developers.google.com/optimization/routing/vrptw) and how to set the dimension for travel times of the vehicles. 
```
 time = 'Time'
    routing.AddDimension(
        transit_callback_index,
        30,  # allow waiting time
        30,  # maximum time per vehicle
        False,  # Don't force start cumul to zero.
        time)
```
From the Link:

> The dimension is created using the AddDimension method, which has the following arguments:
> 
> - The index for the travel time callback: transit_callback_index
> - An upper bound for slack (the wait times at the locations): 30. While this was set to 0 in the CVRP example, the VRPTW has to allow positive wait time due to the time window constraints.
> - An upper bound for the total time over each vehicle's route: 30
> - A boolean variable that specifies whether the cumulative variable is set to zero at the start of each vehicle's route.
> - The name of the dimension.

From the description given in the link, there is a way to set the upper bound for slack (waiting time) at locations. Was wondering if there is a way to set the **lower bound for slack** at the location? (Simulating a vehicle having to wait for a certain amount of time before it would be allowed to move off from the location)

Thank you for your kind advice.

**Comment by lperron** [comment]
Just at that waiting  to the distance of all arcs going out from that visit.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by teddyywj** [comment]
Thank you :)
