### ISSUE TITLE
release tar file owners can cause problems

### ISSUE THREAD

**Issue by skarger** [google/or-tools#155]
Using GNU tar, if you extract the v20150-12 release as root, it will preserve the file UID/GID from the compressed files:
```
$ sudo su -
# wget https://github.com/google/or-tools/releases/download/v2015-12/Google.OrTools.cc.Linux64.3393.tar.gz
# tar xvf Google.OrTools.cc.Linux64.3393.tar.gz
# ls -l
drwxr-x---  7 81951 5000    4096 Dec  8 12:39 or-tools.Linux64
```

Notice that the file UID/GID are 81951/5000.

I discovered this while trying to install OR Tools on a Docker image for use on a CI server:
- By default the user inside a Docker container is root. Unlike with normal users, tar preserves file ownership when extracting as root.
- The CI service I'm using will not allow "large" user IDs for security reasons.
- Therefore it broke when applying the `tar xvf`step.

The workaround I used was to pass the ` --no-same-owner` option to tar, which will set the file permissions to the extracting user even when that user is root. It was quite a challenge to figure out the problem though.

I suggest that to avoid confusion, OR Tools releases be built with UID/GID 0 (i.e. root). There should be no change for the case of extracting as a normal user. For root users it will work like the normal user case, which seems OK, and desirable in situations like the above.

Alternatively maybe you could use a different low UID/GID. 500 and 1000 are common start sequences for normal users, varying by Linux distro. I'm not sure if there's a true "standard" base user ID or user ID intended for this purpose.

**Comment by lperron** [comment]
I pushed the change to github.
Next round of archive will be fixed.

Thanks
