### ISSUE TITLE
[Help] Scheduling, number of employees

### ISSUE THREAD

**Issue by stradivari96** [google/or-tools#1550]
In a scheduling problem I need to minimize the employees that are needed (among other things). I have two options:
1. Let the model return infeasible and increase the number of employees + retry.
2. Solve with a large number of employees and then minimize it in the objective.

I have been going by option 2, but maybe because my model is overly complicated and it creates too many variables per employee it takes too long to solve.

Should I try option 1 or is there a better approach to this? Either way I guess I should keep optimizing (simplifiying) the model...

**Comment by lperron** [comment]
It depends totally on how good propagation is w.r.t. the objective. Meaning, is it easy to prove infeasibility ? Normally, the closer to the optimal, the harder it becomes.

At least with option 2, you have feasible solutions.

**Comment by stradivari96** [comment]
Thanks!
