### ISSUE TITLE
allow to pause and resume calculation in cp-sat solver

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#1553]
Since cp-sat solver works by default with 8 parallel threads it would be helpful possibility to be able to interrupt calculation and later resume it. My problem contains multiple sub-problems and it makes sense (due to limited number of cpu cores) to switch between calculations based on calculated solutions or given timelimit.

**Comment by lperron** [comment]
The default is single thread. You have to specify multiple threads.

And to answer your question, no there is not simple mechanism for that. You could imagine a solution callback that wait. But nothing come to my mind.

Note that if you are compiling from sources (on master), you can use interleave_search() (it may be there on 7,3 too) that gives good performance with 1 thread.

**Comment by stradivari96** [comment]
I think using this may work:
```
kill -SIGSTOP [pid]
kill -SIGCONT [pid]
```
Equivalent of pressing Ctrl+Z and `fg` to resume.

**Comment by lperron** [comment]
Everything is possible at the OS level. Even vms that you pause, resumes...

Thanks for the suggestion.

Le ven. 6 sept. 2019 à 23:52, Xiang Chen <notifications@github.com> a
écrit :
