### ISSUE TITLE
Suggestion about limits of constraint solver

### ISSUE THREAD

**Issue by genuinelucifer** [google/or-tools#156]
This is not exactly an issue. I have a project from a client in which the number of non linear constraints shoot upto 10^20 or may even exceed that. I wanted to know if suggesting them to buy a Xeon would help the cause? That is, **if given proper resources, would the constraint solver of or-tools (in java) be able to solve such a huge problem within atleast a time frame of 24 hours?**
.
.
If you would like to know more about the problem, here it is (why there are so many constraints-)
I have many sets of variables and in each set at-max 3 variables can be non zero. Each set has thousands of variables and the sets are NOT mutually exclusive. Currently what we have thought is that if the sets have N1, N2, ...... number of variables then the number of constraints required for each set will be (N1C4, N2C4, ....) to make product of any 4 variables zero . Total number of constraints will be their sum.
I know this is purely mathematical problem and I don't expect the solution to this problem here. I just put it to provide more info.

**Comment by lperron** [comment]
Err,

even if 1 constraint takes 1 byte, it does not fit in memory, it does not
fit in 64 bit, so no.



Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-02-14 8:50 GMT+01:00 Abhinav Tripathi <notifications@github.com>:
