### ISSUE TITLE
How to provide both arc cost and node cost constraints in capacitated vehicle routing problem (CVRP)?

### ISSUE THREAD

**Issue by hanuhyd** [google/or-tools#1560]
How to minimize the cost and path in routing problem when we have variable costs for each capacity at the location(node)?
Cost for delivery at each location is different and is not directly proportional to the distance. Objective is to optimize the route and number of vehicles while considering the cost at the nodes.

Example:

Let's say I have 5 locations with depot A.(A,B,C,D,E)

num_vehicles = 5
vehicle_capacities = {20,20,20,20,20}
demand_at_location = {10, 20, 5, 15, 10}
demand_cost_at_location = {50, 100, 200, 100, 200}
distance_matrix = { 
{0, 20, 40, 30, 10},
{20, 0, 60, 50, 30},
{40, 60, 0, 70, 50},
{30, 50, 70, 0, 40},
{10, 30, 50, 40, 0}
}

Based on the cvrp ortools example, it optimizes the route and capacities and assigns route to the vehicles. In the example vehicle only considers arc cost (which is distance) to the nodes and minimizes for the route. However, there is no way we can give cost constraints to the nodes. How do we provide node cost for the location so that route is optimized both for cost and the distance along with vehicle capacities.

Please help in providing cost constraint to the nodes.

Thanks,
Hanu

**Comment by lperron** [comment]
You can duplicate each node into an in_node and an out_node.
 With all incoming arcs going to the in_node, and all outgoing coming from the out_node, and only one arc from in_node to out_node.

Then you add the node cost on this arc.

**Comment by hanuhyd** [comment]
Thanks Laurent for the quick response.
Is there any example that we can refer to for this kind of implementation?
Please let me know.

Thanks,
Hanu

**Comment by lperron** [comment]
Not this directly, but duplicating node has been explained a lot in the
mailing list.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
