### ISSUE TITLE
[Help] VRPTW - starting time window seems to be ignored

### ISSUE THREAD

**Issue by pumpknhd** [google/or-tools#1562]
I have the following:

time_matrix:
[0, 0, 630, 1459] <- set as ending location
[0, 0, 630, 1459] <- set as starting location
[2408, 2408, 1800, 3155]
[5056, 5056, 4976, 3600]

time_windows:
(0, 9999999)
(0, 9999999)
(18000, 43200)
(0, 43200)

I would expect the results be: [1] -> [3] -> [2] -> [0]
However, I am getting: [1] -> [2] -> [3] -> [0] 

It seems to ignore that [2]'s time window starts at 18000 and that it would make more sense for it to route to [3] first.

Here's the code, pretty much exactly like example given for VRPTW and changed to allow starting/ending location. I've also edited out a few output lines. 

```
def create_data_model():
    query = json.loads(sys.argv[1])
    data = {}
    data['time_matrix'] = query['time_matrix']
    data['time_windows'] = query['time_windows']
    data['num_vehicles'] = 1
    data['starts'] = [1]
    data['ends'] = [0]
    return data

def print_solution(data, manager, routing, assignment):
    time_dimension = routing.GetDimensionOrDie('Time')
    total_time = 0
    for vehicle_id in range(data['num_vehicles']):
        index = routing.Start(vehicle_id)
        plan_output = ''
        while not routing.IsEnd(index):
            time_var = time_dimension.CumulVar(index)
            plan_output += '{0}, '.format(
                manager.IndexToNode(index))
            index = assignment.Value(routing.NextVar(index))
        time_var = time_dimension.CumulVar(index)
        plan_output += '{0} \n'.format(
            manager.IndexToNode(index))
        print(plan_output)
        total_time += assignment.Min(time_var)

def main():
    data = create_data_model()
    manager = pywrapcp.RoutingIndexManager(
        len(data['time_matrix']), data['num_vehicles'], data['starts'], data['ends'])
    routing = pywrapcp.RoutingModel(manager)

    def time_callback(from_index, to_index):
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return data['time_matrix'][from_node][to_node]

    transit_callback_index = routing.RegisterTransitCallback(time_callback)
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)
    time = 'Time'
    routing.AddDimension(
        transit_callback_index,
        60,  # allow waiting time
        999999,  # maximum time per vehicle
        False,  # Don't force start cumul to zero.
        time)
    time_dimension = routing.GetDimensionOrDie(time)
    for location_idx, time_window in enumerate(data['time_windows']):
        if location_idx == 0:
            continue
        index = manager.NodeToIndex(location_idx)
        time_dimension.CumulVar(index).SetRange(time_window[0], time_window[1])
    for vehicle_id in range(data['num_vehicles']):
        index = routing.Start(vehicle_id)
        time_dimension.CumulVar(index).SetRange(data['time_windows'][0][0],
                                                data['time_windows'][0][1])
    for i in range(data['num_vehicles']):
        routing.AddVariableMinimizedByFinalizer(
            time_dimension.CumulVar(routing.Start(i)))
        routing.AddVariableMinimizedByFinalizer(
            time_dimension.CumulVar(routing.End(i)))
    search_parameters = pywrapcp.DefaultRoutingSearchParameters()
    search_parameters.time_limit.seconds = 30
    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)
    assignment = routing.SolveWithParameters(search_parameters)
    if assignment:
        print_solution(data, manager, routing, assignment)

if __name__ == '__main__':
  main()
```

I have tried changing the "allow waiting time" and "maximum time per vehicle" but didn't seem to make a difference. I hope I gave you all the information needed.
 
Thanks in advanced for your help.

**Comment by lperron** [comment]
most likely a problem with index and node correspondances.

**Comment by pumpknhd** [comment]
Could it be that it's still finding the shortest route, even if it makes you wait 18000 at node 3?

If so, how do I assign a cost to waiting time so that at some point, it's not worth waiting compared to the distance saved?

**Comment by jmarca** [comment]
I think it is waiting at the depot---you are not requiring the starting value of the accumulator to be zero, so my guess is the solver is just starting the accumulator at whatever it needs to be such that the solution is [1] -> [2] -> [3] -> [0]

What happens if the time dimension call is changed to 

```python
    routing.AddDimension(
        transit_callback_index,
        18000 - 1459 - 4975,  # allow enough waiting time
        999999,  # maximum time per vehicle
        True,  # Don't force start cumul to zero.
        time)
```

(Seems like if you don't let the vehicle "wait" for "enough" time, the solution will be impossible if you force the start cumulative value to zero)

You can check out what is happening at each node by printing value of the accumulator and the slack value at each node, rather than just summing them up.  Try printing `assignment.Min(time_var)` and ` assignment.Max(time_var)`, and add the Slack var to the model and see the Min and Max of that in the final assignment (check the examples for how to do that).

**Comment by pumpknhd** [comment]
@jmarca When I changed the time dimension call as you suggested, it gave me the correct solution [1] -> [3] -> [2] -> [0]

However, when I change the waiting time to longer (too much waiting time), it reverts to [1] -> [2] -> [3] -> [0]. 

I don't think it's possible for me to set the perfect "waiting time" for each use case though. My goal is to optimize the routes so that the driver gets to go home as early as possible (taking into consideration driving time + waiting time).

Thanks for your help.

**Comment by pumpknhd** [comment]
When I set:
time_dimension.SetGlobalSpanCostCoefficient(100)
it seems to give me the correct solution as well. I'm uncertain why that is.

**Comment by jmarca** [comment]
I don't know either...I've never used that function.  Explore and find out why!
