### ISSUE TITLE
unsat cores

### ISSUE THREAD

**Issue by lalithsuresh** [google/or-tools#1565]
Is there any way to extract out an unsat core or MUS from an unsatisfiable model? I'm working with the CP-SAT Java interface. I'm used to debugging models in the Minizinc world with findMUS, and was wondering if something similar is possible with the CP-SAT solver.

**Comment by lperron** [comment]
Currently no.

Le mar. 10 sept. 2019 à 04:44, Lalith Suresh <notifications@github.com> a
écrit :
