### ISSUE TITLE
Could not find a packge configuration file provided by "absl" with any of the following names: 

### ISSUE THREAD

**Issue by stmtk1** [google/or-tools#1566]
Hi. I wanna build this library with [this instruction](https://github.com/google/or-tools/blob/stable/cmake/README.md). But I could not build becourse `cmake -H. -Bbuild -G "Unix Makefiles"`.
Terminal shows this error.

---
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- version: 7.3.7083
-- Build C++ library: ON
-- Build Python: OFF
-- Build Java: OFF
-- Build .Net: OFF
-- Build all dependencies: OFF
-- Build ZLIB: OFF
-- Build abseil-cpp: OFF
-- Build gflags: OFF
-- Build glog: OFF
-- Build protobuf: OFF
-- Build CoinUtils: OFF
-- Build Osi: OFF
-- Build Clp: OFF
-- Build Cgl: OFF
-- Build Cbc: OFF
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11")
CMake Error at cmake/cpp.cmake:11 (find_package):
  Could not find a package configuration file provided by "absl" with any of
  the following names:

    abslConfig.cmake
    absl-config.cmake

  Add the installation prefix of "absl" to CMAKE_PREFIX_PATH or set
  "absl_DIR" to a directory containing one of the above files.  If "absl"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:88 (include)

---

Could you help me, please?

**Comment by lperron** [comment]
can you try installing pkg-conf ?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 10 sept. 2019 à 10:45, Motoki saito <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
CMake is build regularly on travis on mac, and it works.
You can have a look at the travis config at the root of or-tools sources.

**Comment by stmtk1** [comment]
Thanks.

 And I have one more question. I want to be a contributor of this repository. I filled Contributor Licence Agreement Form. After this, what should I do?

**Comment by lperron** [comment]
Send pull requests to GitHub.
Make sure you are on the master branch
And read https://github.com/google/or-tools/blob/master/CONTRIBUTING.md

Le lun. 23 sept. 2019 à 13:32, Motoki saito <notifications@github.com> a
écrit :

**Comment by stmtk1** [comment]
Thanks a lot.

**Comment by Mizux** [comment]
simply add `-DBUILD_DEPS=ON`

**Comment by chenxuanhanhao** [comment]
> simply add `-DBUILD_DEPS=ON` see #1630

TAHNKS MAN
