### ISSUE TITLE
Optimise route on basis if both vehicle cost and cost assigned to nodes

### ISSUE THREAD

**Issue by shanuu1809** [google/or-tools#1567]
Hi,

Currently, I have optimised the route on the basis of several constraints but I am actually stuck with something where I need to optimise my routes based on cost given to every node (destinations).

Is there any way to do it?

If needed I can post my code here.

Thanks,
Shantam

**Comment by lperron** [comment]
I replied to that in another issue. Search for in_node and out_node in the
closed GitHub issues.

Le mar. 10 sept. 2019 à 11:14, shanuu1809 <notifications@github.com> a
écrit :
