### ISSUE TITLE
Different ProtoResults

### ISSUE THREAD

**Issue by abduakhatov** [google/or-tools#1568]
I have two models using `from ortools.sat.python import cp_model`. 
There following variables used:
> Method 1: A=NewIntVar, B=NewBoolVar, C=NewBoolVar
> Method 2: A=NewIntVarFromDomain, B=NewBoolVar

As you can see, in new Method 2 C type boolean vars are removed. So here is the output of the proto:
 
```
// Method 1:
objective_value: 353 311 600.0
best_objective_bound: 187 826 000.0
num_booleans: 186
num_conflicts: 93 575
num_branches: 284 178
num_binary_propagations: 2 513 946
num_integer_propagations: 4 672 584
wall_time: 10.010841777000001
user_time: 10.010841693000001
deterministic_time: 25.35660364
solution_info: "lp_br"
``` 

```
//Method 2
objective_value: 277 051 600.0
best_objective_bound: 105 526 000.0
num_booleans: 230
num_conflicts: 141 409
num_branches: 610 841
num_binary_propagations: 5 703 002
num_integer_propagations: 9 241 822
wall_time: 10.008543676
user_time: 10.00854353
deterministic_time: 14.92037573
solution_info: "lp_br"

```

Well from my knowledge, I suppose the proto results should be replaced. shouldn`t they? Could you please expain why this happens?

**Comment by lperron** [comment]
How can you expect me to comment ?
I do not know the model, the types of constraints...
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
