### ISSUE TITLE
How to invoke ValidateCpModel?

### ISSUE THREAD

**Issue by VitamintK** [google/or-tools#1569]
I'm probably just dumb, but I can't figure out how to invoke ValidateCpModel in C++.

when I trying `operations_research::sat::ValidateCpModel(routingModel)`, I get `error: no member named 'ValidateCpModel' in namespace 'operations_research::sat'`

**Comment by lperron** [comment]
Are you mixing the routing library and the CP-SAT solver ?

Le mer. 11 sept. 2019 à 03:41, Kevin Wang <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
If not, you need to include cp_model_checker.h
