### ISSUE TITLE
Compiling or-tools with swig - change of swig version to 3.0.7

### ISSUE THREAD

**Issue by ThomasMasuth** [google/or-tools#157]
Currently the installation of Swig for Windows will be installed for the version 3.0.7.
In the file Makefile.third_party.win and in the Makefile.third_party.unix file defined 'SWIG_TAG = 3.0.5'.
I have tested the change for Windows (Version 10) with Visual Studio, 2013. It is working.
My suggestion: change the files Makefile.third_party.win, Makefile.third_party.unix.

Thomas

**Comment by ThomasMasuth** [comment]
I have tested the Change of swig to Version 3.0.7 With a more or less complex vrp Problem. I can compile and run it.

Thomas

**Comment by lperron** [comment]
This is already pushed to github AFAICT.

Thanks
