### ISSUE TITLE
Restricting route to defined maximum distance is working abruptly

### ISSUE THREAD

**Issue by shanuu1809** [google/or-tools#1570]
Hi,

I have created a python script to optimise my route of vehicles on the basis of the cost of vehicle, the capacity of vehicle and load on every node.

I have added max distance constraint to my code which does work ok when the number of vehicles are in excess but as soon as I reduce the quantity of vehicle it starts picking up the higher end cost vehicles and also the max distance of the routes increase significantly.

Please let me know what's wrong with my code.
[workfile.pdf](https://github.com/google/or-tools/files/3599776/workfile.pdf)
[vehicledetails_csvdata.pdf](https://github.com/google/or-tools/files/3599777/vehicledetails_csvdata.pdf)
[LocationData_csv.pdf](https://github.com/google/or-tools/files/3599778/LocationData_csv.pdf)

**Comment by lperron** [comment]
Are you sure the solution produced is not a good one ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 11 sept. 2019 à 10:41, shanuu1809 <notifications@github.com> a
écrit :

**Comment by shanuu1809** [comment]
Yes... Ideally, the max distance for all individual routes should not exceed more than 500km but it does exceed for few routes if I reduce no. of vehicles.

Example:-
Case 1
Lets say I have 20 vehicles whose capacity is 50 and cost of every vehicle is between 80 to 100. Optimise solution picks up 18 vehicle and leave 2 with highest cost.
This case is correct
Case 2
If I remove 2 vehicles and increase the cost of one vehicle to 500. I do get an optimised solution but one of the route distance becomes more than 1000km and thats not correct.
This is incorrect

**Comment by lperron** [comment]
So, you are trading the cost of a new vehicle against the cost of the
extended route ?

500 vs 500km seems a good tradeoff.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 11 sept. 2019 à 10:57, shanuu1809 <notifications@github.com> a
écrit :

**Comment by shanuu1809** [comment]
Yes. How can we fix the route to less than 500 in this scenario

**Comment by shanuu1809** [comment]
Max distance constraint doesn't work if I increase the cost of a few
vehicles and decrease the no. of vehicle.

**Comment by lperron** [comment]
These constraints are heavily tested. I doubt they are wrong. I could be
wrong :-)

Please simplify  your model and check it thoroughly.


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 11 sept. 2019 à 11:12, shanuu1809 <notifications@github.com> a
écrit :
