### ISSUE TITLE
.NET debugging does not work; CS0012

### ISSUE THREAD

**Issue by JasperNL** [google/or-tools#1572]
I am using OrTools in C#.NET at Visual Studio 2019 with a new .NET core 2.2 project (running with 64 bits). I'm using the latest version 7.3.7083.0 as downloaded from the nuget package repository.

My compiled code runs smoothly and without any issues. However, when I'm debugging I can't look up any variables (whether they are from OrTools, another package, or even system types) in the debugger. In all cases, the debugger returns the following information:

> CS0012: The type 'Variable' is defined in an assembly that is not referenced. You must add a reference to assembly 'Google.OrTools, Version=7.3.7083.0, Culture=neutral, PublicKeyToken=77370d3086a71853'.	

With version 7.2.6977 from nuget there is no problem.

This problem seems similar to two issues of last year: #904 and #984 .

**Comment by vgrudenic** [comment]
I have the same weird problem with VS2019, .NET core 3.0, OrTools 7.3.7083, it seems like a Visual Studio debugger issue.

The weird thing is that it is resolved (on my machine at least) by wrapping the `Solver` in a different class, i.e.

This does **not** work:

    class Program 
    {
        static void Main(string[] args)
        {
            using (var solver = new Solver("test", 
                  Solver.OptimizationProblemType.CBC_MIXED_INTEGER_PROGRAMMING))
            {
                Debugger.Break();
                var x = solver.MakeNumVar(0, 100, "x");
            }
        }
    }

While this works:

    class Program 
    {
        static void Main(string[] args)
        {
            var c = new DummyWrapper();

            // note that the breakpoint must happen after the wrapper constructor,
            // at this point 'c' can be inspected and c._solver is visible

            Debugger.Break();
        }
    }
        
    public class DummyWrapper : IDisposable
    {
        Solver _solver;

        public DummyWrapper()
        {
            _solver = new Solver("Model",
                   Solver.OptimizationProblemType.CBC_MIXED_INTEGER_PROGRAMMING);
        }

        public void Dispose()
        {
            _solver?.Dispose();
            _solver = null;
            GC.SuppressFinalize(this);
        }
    }

**Comment by mikkelxyz** [comment]
I have the same issue and can reproduce the same behaviour as @vgrudenic. If I try to do a Solve(), I am again asked to add a reference to assembly 'Google.OrTools, Version=7.3.7083.0, Culture=neutral, PublicKeyToken=77370d3086a71853'.

**Comment by JasperNL** [comment]
When debugging with nuget dependencies, VS checks the provided public key of the package with the actual public key of the executed package and these do not coincide. I think for security reasons VS then doesn't show the debug information.

We decided to stick with 7.2.6977, hoping it's solved with a later release. Building 7.3 from source was a solution to run locally at my pc, but it wasn't a workable solution with our buildservers.

**Comment by lperron** [comment]
Thanks for the info.
7.4 should be fixed.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
Hello,
Or-Tools 7.2.6 seems to execute also with .NetCore 2.1 and 3.0.

Still, the debugger seems a bit slow, and in this line, the debugger shows 10 digit (!) numeric value for "order" : 
route += order + " Load(" + solution.Value(load) + ") " + "Time(" + solution.Min(time) + ", " + solution.Max(time) + ")";

I hope this is fixed soon.
Thx
