### ISSUE TITLE
PDP - Don't pickup until all the delivery has been made

### ISSUE THREAD

**Issue by plantatree** [google/or-tools#1575]
Hi!,
I'm trying to find a way to model a pickup and delivery problem in where once the delivery has started, It must not finish until the load in the vehicle is 0.
The model have Depo, Pickup Nodes and Delivery Nodes.

The model add at every pickup location a demand of +1, and at every delivery location a demand of -1.

It's posible to do multiple pickups previusly the delivery, but once the delivery has started, It has to completely finish before the pickups can start again.

So currently the solution I'm having looks something like this:
Route for vehicle 0:
0 -> 1 Load(1) -> 2 Load (2) -> 3 Load (1) -> 4 Load (2) -> 5 Load (1) -> 6 Load (0) -> 0
 
And Im trying to get something like this:
Route for vehicle 0:
0 -> 1 Load(1) -> 2 Load (2) -> 3 Load (1) -> 5 Load (0) -> 4 Load (1) -> 6 Load (0) -> 0

I have allready add a cost in order to maintaing this condition low:
time_dimension.SetCumulVarSoftUpperBound(delivery_index, 0, 2)
But Im looking for a hard constraing.

I'ts is posiblible to add such a constraing in the model, if so can you help my with a tip how to manage this?

I'm using Python 3.6.8 and Or Tools 7.3.7083

**Comment by plantatree** [comment]
Thinking about this, 
If such a constrain it's too difficult for the solver.. It's is possible to create a cost that penalize the time that has passed between the pickup and the delivery of a passenger?
So with this cost, tell the solver to keep the pickups and delivery as close as possible (without making this a FIFO Delivery problem)

**Comment by ttlbds** [comment]
Hi, plantatree!

I would try to use a constraint stating that pickup can be after a delivery if and only if the dimension is 0. This could be something like this:
forall (i,j): if (i is delivery and j is pickup and next(i)==j) ==> cumul(i)==0

I hope this idea helps.

All the best,
Attila

**Comment by jmarca** [comment]
I answered a similar question in detail here: https://github.com/google/or-tools/issues/1428#issuecomment-523607485

This is more or less what @abodis-dev  suggests, except with a little more detail on how to do it.

I've actually done this in practice a few times, so the approach does work.  Try it, and if it fails post what you try and I can give more advice.
