### ISSUE TITLE
How to use OrTools with Shapely?

### ISSUE THREAD

**Issue by rahulmoorthy19** [google/or-tools#1576]
I have been recently working with a project using Ortools in which there is a need to integrate Shapely with the Objective Function which needs to be minimized. Whenever I try to pass the Ortools Intvar Variable to the shapely point Function, it always gives an error that **IntVar cannot be interpreted as Int** . So is there a way in which Shapely can be integrated with the Ortools where the run time value of the variables can be passed to a custom created objective function which uses shapely and the net value of the function is minimized?
 Thank You

**Comment by lperron** [comment]
You can't add constraints during search. Once the model is loaded, you cannot change it.

**Comment by rahulmoorthy19** [comment]
Ok,Thanks a lot for the help!!!Have got a good clear picture now.
