### ISSUE TITLE
Ordering in JobShop problem

### ISSUE THREAD

**Issue by gustavo-barros** [google/or-tools#1577]
Hello there, 

I'm trying to create a preferencial order of execution of my jobs. The order is defined by the order of a job list. So for example, I have a list in the following order:

jobs 
112
172
161
164
170
160
163
159
162

Each of these jobs is composed of 1 or more tasks.

To define this order I say to the solver:
`Model.Add(ModelIntervals.OdfIntervals.OdfToStarts[operation.OdfId][0] <=
ModelIntervals.OdfIntervals.OdfToStarts[nextOperation.OdfId][0]`

Using that I got the order to work, see the image below:
![image](https://user-images.githubusercontent.com/36746102/64887229-8c334f00-d63e-11e9-97db-2490e71b60de.png)

But if you see, the job 163/1-4 has no dependencies, it could be put between jobs 164/1-4 and 161/3-5. So how could I define a order, that if possible it could be ignored?

I would like to say to the solver, the first task_1 of this job_0 should start before or at same time of the task_1 of job_1, but if possible, it should start even before.

**Comment by lperron** [comment]
Create an enforced precedence:

model.Add(end_of_job_1 <= start_of_job_2).OnlyEnforceIf(new_literal);

then minimize sum(new_literals)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 13 sept. 2019 à 20:58, gustavo-barros <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
Sorry. maximize sum(literals)
