### ISSUE TITLE
MSVC 2015 support?

### ISSUE THREAD

**Issue by supermihi** [google/or-tools#158]
Hi,
is there any schedule for adding [VS 2015](https://groups.google.com/forum/#!searchin/or-tools-discuss/visual$20studio$202015/or-tools-discuss/BWqEiA0PfRQ/sr_QGQAXCgAJ support)? Is anyone aware of what could be the main issues preventing a port?

**Comment by lperron** [comment]
Hi,
One if the dependencies (protobuf) was not ported yet.
Le 29 févr. 2016 08:04, "Michael Helmling" <notifications@github.com> a
écrit :

**Comment by supermihi** [comment]
Thanks for your answer. I'll stick with 2013 for now, then. Perhaps we can leave this ticket open to track the progress of VS2015 support, though?

**Comment by lperron** [comment]
yes please.



Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-03-01 2:22 GMT-08:00 Michael Helmling <notifications@github.com>:

**Comment by lperron** [comment]
As of today, visual studio 2015 is supported. 
Make sure you clean everything, get the latest sources, before compiling.

**Comment by supermihi** [comment]
Awesome, thanks a lot!
