### ISSUE TITLE
How to Include 2D interval back to search space?

### ISSUE THREAD

**Issue by rahulmoorthy19** [google/or-tools#1580]
Hello,
I am a beginner in ORTOOLS and recently started using it.

I am using the constraint optimization library to solve a particular problem of fitting boxes efficiently in a particular area.
During programming this I am facing one Problem which is depicted in below image.
![cage](https://user-images.githubusercontent.com/32005497/64937742-1666f780-d879-11e9-8784-98e36fa7b93d.PNG)
If the solver has decided the interval in which the outer box is present and I can also program and present the solver where the inner box is present. Is there any way in which i can remove the inner box and present it again to the search space so that it can fit small boxes inside the extracted box. It would be very helpful if a way is present.

Thank you

**Comment by lperron** [comment]
If you use CP-SAT and the no_overlap_2d constraint, just create a fixed box
for the yellow part, and add it to your constraint.

Le lun. 16 sept. 2019 à 08:31, rahul moorthy <notifications@github.com> a
écrit :
