### ISSUE TITLE
Computing Entropy

### ISSUE THREAD

**Issue by joegaudet** [google/or-tools#1581]
Hey,

I'm trying to do something like the nurse scheduling problem, and what I'd like to maximize is the entropy of the solution. Which is to say I'd like to ensure that given n buckets of potential assignments, that they are chosen from as evenly as possible.

I've got about this far:

```python
    @property
    def entropy(self):
        entropy = 0

        for cluster_id, restaurants in self.clustered_restaurants.items():
            restaurant_ids = seq(restaurants).map(lambda r: r.id)

            p_m_id = self.model.NewIntVar(0, 1000, "cluster entropy %s" % cluster_id)

            # sum of boolean vars
            usage = sum(self.vars_for_restos(restaurant_ids))

            # p_m_id = usage / slot_count
            self.model.AddDivisionEquality(p_m_id, usage, self.slot_count)

            # TODO is this even possible
            log_p_id = math.log(p_m_id, len(self.clustered_restaurants))

           # TODO move this to a map and sum operation
             entropy = entropy + round(100 * entropy + (-1 * (p_m_id * log_p_id)))

        return entropy
```

And I get this type of error: ```TypeError: NotSupported: model.GetOrMakeIndex(((((((((((((((((((((((((((((((((((((((((((((((((((r105 d1 m0 s0)``` this appears to be the result of passing usage sum to AddDivisionEquality.

So I have two questions:

1) I something like this even possible, I feel like I'm going to run into another problem when I try to perform the logarithm?

2) Is there another approach I might be able to take in order to ensure that the assignment variables (groups of nurses) are chosen from as evenly as possible?

Thanks so much!

.joe

**Comment by lperron** [comment]
CP-SAT is integer only, and for the division equality, you need to create a
variable equal to the sum.

Le lun. 16 sept. 2019 à 19:05, Joe Gaudet <notifications@github.com> a
écrit :

**Comment by paultrow** [comment]
How about minimizing the variance of the number of assignments in each
bucket?

**Comment by lperron** [comment]
Or just the max - min number of elements pee buckets.  This is simpler to
compute.

**Comment by joegaudet** [comment]
I've been having some success with imposing a max usage from each bucket proportional to the bucket sizes and the number of assignments. 

Which is I think what your hinting at @lperron 

@paultrow how would you express a minimization of variance?

**Comment by paultrow** [comment]
Define variables b_i equal to the number of assignments in bucket i. You
can compute the variance of b_i as a sum of terms of the form (b_i - b_j)^2
(see https://en.wikipedia.org/wiki/Variance) times 1/n^2 (n being the
number of buckets). That's not an integer, but you can just minimize n^2
times the variance - the solution will be the same.

As for minimizing max number of assignments  - min number of assignments,
I'm not sure that works if there are constraints in the problem that force
the number of assignments in two buckets to differ by at least 2. For
example, suppose there are 4 buckets and buckets 1 and 2 have to differ by
2, but buckets 3 and 4 do not.  Then you could have two solutions  4 | 2| 4
| 2  and 4 | 2 | 3 | 3. In both cases, max - min is 2, but solution two is
more evenly distributed than solution 1.

**Comment by joegaudet** [comment]
@paultrow thanks for the response! 

So, in this case, b_j is the expected value? (The idealized even distribution between the buckets)

**Comment by joegaudet** [comment]
Thinking further on that, can't be right because I'd need to minimize the variance in each bucket from the idealized even distribution.

**Comment by lperron** [comment]
Fairness is a very complex issue in or.

Variance is expensive to compute I would suggest you start with something
simple first.

Le mar. 17 sept. 2019 à 03:43, Joe Gaudet <notifications@github.com> a
écrit :

**Comment by joegaudet** [comment]
I've gone with this, early tests seem to indicate it does a reasonable job at maximizing entropy (fairness):

```python
        # dictionary of cluster key to restaurant list, restaurants are POPOs
        number_of_clusters = len(self.clustered_restaurants)
        # slots are potential assignments
        max_cluster_use = math.ceil(self.slot_count / number_of_clusters)

        if enforce_variety:
            for restaurants in self.clustered_restaurants.values():
                restaurant_ids = seq(restaurants).map(lambda r: r.id)

                # Since clusters do not have a uniform size.
                # if at first we cannot assign clusters evenly, we can try again with 
                # scaled maximums
                if scale_usage_by_cluster_size:
                    relative_cluster_size = len(restaurants) / self.restaurants.len()
                    max_cluster_use = max(max_cluster_use, math.ceil(relative_cluster_size * self.slot_count))

                model.Add(sum(self.vars_for_restos(restaurant_ids)) <= max_cluster_use)
```

**Comment by joegaudet** [comment]
Thanks for your help!

**Comment by paultrow** [comment]
No, I meant that b_j is a variable in the code, not a random variable. And
I meant the variance of a set of numbers, not in the random variable sense.
Minimizing the variance is just a way to get the most distribution.

To go back to my previous example, if you want to put 12 objects in 4
buckets, and you require bucket 1 to have at least 4 objects, and bucket 2
two have at most 2 objects, then the most even placement is   4 | 2 | 3 | 3
, which has the minimum variance among all ways of placing the objects.

I think it would also work to just minimize the sum of the absolute values
of differences of distinct pairs of objects. For example:

4 | 2 | 3 | 3:  |4 - 2| + |4 - 3| + |4 - 3| + |2 - 3| + |2 - 3| + |3 - 3| =
5

but

4 | 2 | 4 | 2: |4 - 2| + |4 - 4| + |4 - 2| + |2 - 4| + |2 - 2| + |4 - 2| = 8

The most even distribution has the smallest sum.

But it sounds like you have found a good approach.
