### ISSUE TITLE
cvrptw plot example distance and transit_time constraint make me confused

### ISSUE THREAD

**Issue by showkeyjar** [google/or-tools#1586]
who can help me to explain why [examples/cvrptw_plot.py ](https://github.com/google/or-tools/blob/stable/examples/python/cvrptw_plot.py ) use both "distance" and "transit_time" to constraint the vrp model ?

I think vehicle's "transit_time" is calculated from vehicle's "distance", so if "distance" is a duplicate condition?

**Comment by lperron** [comment]
It can depend on the vehicle (different speeds).
And you could have max driving length limits and time windows.

This being said, deciding which dimensions to use is problem specific. Use
the one that you need.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by showkeyjar** [comment]
thanks, solved my problem.
