### ISSUE TITLE
Print Slack Variable

### ISSUE THREAD

**Issue by abduakhatov** [google/or-tools#1589]
Hi there!
In older versions of ortools (aprx. ~6.8) slack windows from  slack_var, assignment could be printed. But, now I am using ~7.3, so tried to print slack window in result:
```
slack_var = time_dimension.SlackVar(index)
assignment.Min(time_var)
assignment.Max(time_var)
```

But, the program stops at the second line above:
> Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

After some research: I tried following answers  below:

[github](https://github.com/google/or-tools/issues/708)  
[stackover](https://stackoverflow.com/questions/50569820/vrptw-how-to-handle-time-windows-and-slacks-for-the-special-depot-node)  by @Mizux
[Google Groups](https://groups.google.com/forum/#!topic/or-tools-discuss/LOgQO5vckq8) by @lperron 

P.S. all answers above are in 2018
Could you please explain why it is stopping there? And Suggest a way to print slack windows in result

**Comment by lperron** [comment]
https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/samples/cvrptw_break.py

is a working example. It does 

routing.AddToAssignment(time_dimension.SlackVar(index))

inside.
