### ISSUE TITLE
Generalised network flow?

### ISSUE THREAD

**Issue by donovanhide** [google/or-tools#159]
Hi,

sorry to file an issue for this, but have you considered adding a generalized network flow solver? In other words, a solver for a  graph with edges with an associated gain factor that allows for the maximization of sink output given constrained source input? Here's one paper that describes an algorithm:

https://www.cs.princeton.edu/~wayne/papers/gain-scaling.pdf

Unfortunately, I haven't been able to find any practical implementation anywhere! Would be interested in hearing your thoughts :-)

**Comment by lperron** [comment]
no application, thus no incentive to implement.
I like the idea though.
