### ISSUE TITLE
Constrained random generation with CP-SAT

### ISSUE THREAD

**Issue by verificationcontractor** [google/or-tools#1590]
Hi is it possible to generate random solutions for the constraints using CP-SAT? This is a feature used heavily in functional hardware verification. 

For example if want to generate 3 random 8-bit numbers that sum to 100:

```python
from ortools.sat.python import cp_model

model = cp_model.CpModel()

x = model.NewIntVar(0, 255, 'x')
y = model.NewIntVar(0, 255, 'y')
z = model.NewIntVar(0, 255, 'z')

model.add( x+ y + z == 100 )

solver = cp_model.CpSolver()
status = solver.Solve(model)

if status == cp_model.FEASIBLE:
        print('x = %i' % solver.Value(x))
        print('y = %i' % solver.Value(y))
        print('z = %i' % solver.Value(z))
```

This will always print
x = 0
y = 0
z = 100

I would like to see random solutions like (1,1, 98) or (16, 17, 67), etc.
Is it possible to do this with the CP-SAT solver?

**Comment by stradivari96** [comment]
https://github.com/google/or-tools/blob/stable/ortools/sat/doc/solver.md#searching-for-all-solutions-in-a-satisfiability-model

**Comment by lperron** [comment]
Yes, hint random values in the initial model, and search for a feasible
solution.
Should be good enough.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 20 sept. 2019 à 16:13, Xiang Chen <notifications@github.com> a
écrit :

>
> https://github.com/google/or-tools/blob/stable/ortools/sat/doc/solver.md#searching-for-all-solutions-in-a-satisfiability-model
>
> El vie., 20 sept. 2019 16:08, verificationcontractor <

**Comment by verificationcontractor** [comment]
How do I "hint values in the initial model"? Is there a way to initialize the variables to some random values?

**Comment by lperron** [comment]
https://github.com/google/or-tools/blob/stable/ortools/sat/doc/model.md

**Comment by verificationcontractor** [comment]
Thank you very much!

**Comment by verificationcontractor** [comment]
Actually, I just tried this and it doesn't work:
```python
from ortools.sat.python import cp_model
import numpy as np

model = cp_model.CpModel()

x = model.NewIntVar(0, 255, 'x')
y = model.NewIntVar(0, 255, 'y')
z = model.NewIntVar(0, 255, 'z')

model.Add( x + y + z == 100 )

model.Proto().solution_hint.vars.append(x.Index())
model.Proto().solution_hint.values.append(np.random.randint(0,256))
model.Proto().solution_hint.vars.append(y.Index())
model.Proto().solution_hint.values.append(np.random.randint(0,256))
model.Proto().solution_hint.vars.append(z.Index())
model.Proto().solution_hint.values.append(np.random.randint(0,256))

solver = cp_model.CpSolver()
solution_printer = cp_model.VarArrayAndObjectiveSolutionPrinter([x, y, z])
status = solver.SolveWithSolutionCallback(model, solution_printer)

print('Status = %s' % solver.StatusName(status))
print('Number of solutions found: %i' % solution_printer.solution_count())
```
It always prints:
Solution 0, time = 0.01 s, objective = 0
  x = 0   y = 0   z = 100
Status = FEASIBLE
Number of solutions found: 1

I also tried randomly picked hard coded constants, got the same result.

**Comment by stradivari96** [comment]
I think the problem is too simple, so it is presolved away. You could try disabling it:
```
from ortools.sat.python import cp_model
import numpy as np

model = cp_model.CpModel()

x = model.NewIntVar(0, 255, 'x')
y = model.NewIntVar(0, 255, 'y')
z = model.NewIntVar(0, 255, 'z')

model.Add(x + y + z == 100)

model.AddHint(x, np.random.randint(0, 101))
model.AddHint(y, np.random.randint(0, 101))
model.AddHint(z, np.random.randint(0, 101))

solver = cp_model.CpSolver()
solver.parameters.cp_model_presolve = False

solution_printer = cp_model.VarArrayAndObjectiveSolutionPrinter([x, y, z])
status = solver.SolveWithSolutionCallback(model, solution_printer)

print('Status = %s' % solver.StatusName(status))
print('Number of solutions found: %i' % solution_printer.solution_count())
```

**Comment by verificationcontractor** [comment]
Yes, now it seems to yield random results. Although they don't seem to be quite uniformly distributed...I see this when I run the program multiple times. Maybe if I repeat the generation multiple times in the same run it will look better. Either way, it's a good start. Thank you!
