### ISSUE TITLE
Sat Solver multithreading documentation

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [google/or-tools#1591]
Hello,

I'm trying to accomplish multi-threading with the SAT solver, similar as how it's discussed here:
https://github.com/google/or-tools/issues/933

However, one link doesn't work anymore, but even going through what I think is the current link:
https://github.com/google/or-tools/blob/stable/docs/index.md I don't find the info.
Also, when going to the second link, I'm also not finding the info there.

Would it be possible to point me in the right direction?

Best regards

**Comment by stradivari96** [comment]
Which language?
In Python is `solver.parameters.num_search_workers = 8` as seen in:
https://github.com/google/or-tools/blob/stable/examples/python/shift_scheduling_sat.py#L381

**Comment by LanderBeeuwsaert** [comment]
@stradivari96 
Seems it's not compatible with SearchForAllSolutions in Python but thanks anyway for the info!

**Comment by lperron** [comment]
No, too complex to de-duplicate solutions in parallel.
