### ISSUE TITLE
feasible/infeasible solutions with same data input

### ISSUE THREAD

**Issue by raminetinati** [google/or-tools#1594]
Broad question: running 

CPSolver with same data as input. Inconsistent result when solving. Some executions are feasible, some are infeasible, some are optimal.

How is this possible if the input data source does not change, and there are no external inputs changing the data/

For Environment information:
Python 3.5.3
ortools 7.1.6722

I'm running the CPSolver with multi-threading enabled

Thanks,
Ramine

**Comment by lperron** [comment]
Please update to 7.3.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 25 sept. 2019 à 10:58, Ramine Tinati <notifications@github.com> a
écrit :
