### ISSUE TITLE
Set limit on sum of dimension values over several vehicles

### ISSUE THREAD

**Issue by filippobistaffa** [google/or-tools#1595]
I have defined a "cost" dimension for each vehicle (with `AddDimensionWithVehicleTransits`). Is it possible to set a limit on the sum of the "costs" over a given set of vehicles, i.e., if the sum the "costs" of said vehicles exceeds a given quantity, that solution is not considered feasible?

**Comment by lperron** [comment]
You can always get the solver and get all the vehicle cumul vars and add a
constraint on those.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by filippobistaffa** [comment]
Once I collected all those cumul vars, how do I set the constraint on the sum of those variables?
My (unsuccessful) try is the following:
```
total_cost = []
for i in range(data['n_vehicles']):
    if some_selection_condition:
        total_cost.append(cost_dimension.CumulVar(routing.End(i)))
routing.solver().Add(routing.solver().Sum(total_cost) <= cost_max)
```
This does not seem to be correct, as I get a solver status = 2 (unfeasible) even when I set a `cost_max` for which I'm sure a solution exists. What am I doing wrong?

**Comment by Mizux** [comment]
Strange, are your node droppable (i.e. part of a `addDisjunction([index])`) so the solver could have drop few of them ?
