### ISSUE TITLE
Third party Abseil-cpp files was not found!

### ISSUE THREAD

**Issue by jstrmen** [google/or-tools#1596]
I followed steps from https://developers.google.com/optimization/install/cpp/source_linux. I ran 'make third_party' and then make cc with following error 'makefiles/Makefile.third_party.unix.mk:44: *** Third party Abseil-cpp files was not found! did you run 'make third_party' or set UNIX_ABSL_DIR ?.  Stop.'

Thing with 'UNIX_ABSL_DIR' is not mentioned anywhere and even Clion is complaining about missing 'abslConfig.cmake'. So I suppose abseil-cpp dependency is missing and couldn't be installed automaticly. 

(Btw from your tutorial I am not sure if 'Build the source code' part 2. 'To use a third party solver, open Makefile.local...' is required or not.)

Thanks a lot.

**Comment by lperron** [comment]
This is build routinely, every day.
Make sure all the tools are in place (git, cmake...).

Make sure you have the right version of the sources.

Please indicate your Linux flavor.

**Comment by lperron** [comment]
any news ? Please reopen if needed.

**Comment by jstrmen** [comment]
Finally I found the problem. It was crashing while 'make third_party' at building '[dependencies/sources/patchelf-0.10] Error 1' because of missing automake. After 'sudo apt-get install automake' it built properly. 

Thanks for help and it probably should be added to prerequisites for ubuntu in your install tutorial. My distro is 'Linux Mint 19.1 Cinnamon'.

**Comment by yugInd8** [comment]
I am having this issue and I checked , automake is installed. When I try to run a "program.cc" with google or-tools by typing the command : 
make run SOURCE=/home/yug_cs01/one/program.cc
It shows this : 
/bin/sh: 0: Illegal option -r
/bin/sh: 0: Illegal option -r
/bin/sh: 0: Illegal option -r
makefiles/Makefile.third_party.unix.mk:44: *** Third party Protobuf files was not found! did you run 'make third_party' or set UNIX_PROTOBUF_DIR ?.  Stop.

Please help I'm new.

**Comment by Mizux** [comment]
@yugInd8 for user question please use the mailing list or our discord.
It seems you are using a build from source approach on a Ubuntu like distro (note: we don't officially support Elementary OS).
so you should run  `make third_party`, `make cc`, then `make run SOURCE=....`

If you can provide us a Dockerfile so we can reproduce it...
