### ISSUE TITLE
Trucks assignment for VRP

### ISSUE THREAD

**Issue by alexpoh** [google/or-tools#1598]
Hi,

Here a scenario, I have 3 plants to deliver material to multiple customer sites. Take for an example,
Plants: P1, P2, P3
Customer sites: S1, S2, S3, S4, S5, S6

Constraints
1. Only allow trucks to deliver material from a plant to a site and return to the nearest plant after delivery material to customer site, such as P1 -> S1 -> P1 (or P2 if P2 is the nearest plant for return trip).

2.  The trucks are not to delivery material from any plant to another plant

3. The trucks are not to delivery from customer site to another customer sites, such as P1 -> S2 -. S3. (this is not possible)

4. The trucks have to deliver the orders base on each orders start time. 

I have tried TSP, VRP, CVRP, pickup and delivery and seem doesn't fit in the constraints where i have mentioned above. Seek some advice for the solutions. 

Thank you.
Alex

**Comment by lperron** [comment]
This is not a tsp. You do not create routes.

This is an assignment.

**Comment by alexpoh** [comment]
Thanks for your advice, will looking into it.

By the way, i will like to understand how is the flow being compute from the maximum cost flow, such as flow for Arc 0 -> 1 is 12?

  Arc    Flow / Capacity  Cost
0 -> 1    12  /  15        48
0 -> 2     8  /   8        32
1 -> 2     8  /  20        16
1 -> 3     4  /   4         8
1 -> 4     0  /  10         0
2 -> 3    12  /  15        12
2 -> 4     4  /   4        12
3 -> 4    11  /  20        22
4 -> 2     0  /   5         0
