### ISSUE TITLE
How to use CPLEX in ORTools to resolve job shop problem.

### ISSUE THREAD

**Issue by stoneren0316** [google/or-tools#1599]
Many thanks for the great work of or-tools.
I want to do the job shop problem through or-tools and I want to use CPLEX as the resolver.
I have the CPLEX liscense and or-tools have been installed from source following the install guide.
My question is how could I use CPLEX as the constraint programming resolver in code.
I saw the linear programming and integer programming examples Using CPLEX. 
Is there any guide or example for constraint programming or job shop like problems?

**Comment by lperron** [comment]
There are link to the CPLEX constraint programming solver.
We provide our own (CP-SAT).
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 26 sept. 2019 à 11:51, stoneren0316 <notifications@github.com> a
écrit :

**Comment by stoneren0316** [comment]
Thank you for the quick reply.
I don't quite understand. 
I know the CP-SAT.
But is there any way to use the CPLEX constraint programming solver through OR-Tools?

**Comment by lperron** [comment]
No.

Le jeu. 26 sept. 2019 à 11:59, stoneren0316 <notifications@github.com> a
écrit :

**Comment by stoneren0316** [comment]
So only linear programming and integer programming can use the CPLEX as resolver? 
any others？
Sorry for bother again.

**Comment by lperron** [comment]
Just LP and MIP.
