### ISSUE TITLE
CP-SAT: Model deemed feasible only with additional constraints

### ISSUE THREAD

**Issue by PistonMiner** [google/or-tools#1602]
When attempting to solve the attached model (attached infeasible.proto, using the Python bindings, version 7.3.7083; I did not test other languages), the solver will report infeasibility.

However, adding an additional set of constraints to the same problem (attached feasible.proto, same environment) that (as far as I know) should only narrow the search space makes the solver report feasibility and find solutions.

It was my understanding that infeasibility should only ever be reported when the problem is proven to have no solutions, which would seem to me to be in contradiction to the problem having solutions in a more constrained environment.

If necessary, I can supply the Python code that generates both of these models as well.

Model protos: [models.zip](https://github.com/google/or-tools/files/3664434/models.zip)

**Comment by lperron** [comment]
With the new code, I see that you use enforcement literals on the element constraint.
Which is not supported.

Next version will check there and refuse the models.

**Comment by PistonMiner** [comment]
Thanks for the quick response; I've moved the enforcement literal to an attached equality constraint which has resolved the problem.
