### ISSUE TITLE
including graph.h in Visual Studio 2019 causes syntax error

### ISSUE THREAD

**Issue by voxoid0** [google/or-tools#1605]
I downloaded and extracted or-tools_VisualStudio2017-64bit_v.7.3.7083, and am using Visual Studio 2019, with platform toolset Visual Studio 2019 (v142). The following program:

```
#include "ortools/graph/graph.h"

int main()
{
	return 0;
}
```

Causes the following error four times:

C2760 syntax error: unexpected token 'auto', expected 'expression'

On graph.h lines 1122, 1441, 1449, 1950 . 1122 looks like this:

```
template <typename NodeIndexType, typename ArcIndexType>
ArcIndexType ListGraph<NodeIndexType, ArcIndexType>::OutDegree(
    NodeIndexType node) const {
  ArcIndexType degree(0);
  for (auto arc ABSL_ATTRIBUTE_UNUSED : OutgoingArcs(node)) ++degree;
  return degree;
}
```

(I am able to use modern C++ features such as auto just fine in the project.)

**Comment by lperron** [comment]
Another invasive #define in windows.h

Can you look at the preprocessed code ?

**Comment by lperron** [comment]
We define this when compiling on Windows

/DNOMINMAX /DWIN32_LEAN_AND_MEAN=1

It should.help.

**Comment by voxoid0** [comment]
Thank you, Iperron, I'll try that next.
