### ISSUE TITLE
Dependencies are being built with single cpu thread only

### ISSUE THREAD

**Issue by Talkless** [google/or-tools#1606]
Downloaded v7.3 source archive, executed `cmake ../ -DBUILD_absl=1 ...`, and I see that dependences (is it abseil, CoinUtils or whatever) are being built during configure time only utilizing single CPU core. I've tried using `env CMAKE_BUILD_PARALLEL_LEVEL=4 cmake ../ -DBUILD_absl=1 ...` but it does not help.

Debian 9 (stretch) amd64 with default CMake 3.7.2

**Comment by lperron** [comment]
Yes, I do not control that easily.

But you only build once :-)

Le lun. 30 sept. 2019 à 08:05, Vincas Dargis <notifications@github.com> a
écrit :

**Comment by Talkless** [comment]
Looks like Debian's CMake is just too old, building with recent CMake version makes it build in parallel by default.

**Comment by lperron** [comment]
Nice.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 30 sept. 2019 à 08:42, Vincas Dargis <notifications@github.com> a
écrit :
