### ISSUE TITLE
Which SCIP specific parameters can be set through OR-Tools?

### ISSUE THREAD

**Issue by elmuz** [google/or-tools#1609]
Hi there,

SCIP has an infinite number of [parameters](https://scip.zib.de/doc-6.0.2/html/PARAMETERS.php) that can be set during optimization.
I know that some of them are directly linked through `pywraplp.MPSolverParameters` configuration. In fact, I was able to disable PRESOLVE that way.

As far as I understood all the other parameters should be passed through `SetSolverSpecificParametersAsString()`. I saw example of the use of this function with CPLEX - and I can confirm it worked with it. Anyone has experience in using it with SCIP? In particular, I want to disable heuristics. I know that in SCIP command line it is simply `set heuristics emphasis off`. Do you know how to translate it in OR Tools?

Cheers

**Comment by lperron** [comment]
The syntax is not specific to or-tools, it is the Scip syntax for config
files.
