### ISSUE TITLE
Cannot find routing_enums_pb2 in python example

### ISSUE THREAD

**Issue by mombi93** [google/or-tools#161]
I tried running the tsp.py example but was given an error instead. It seems that routing_enums_pb2 could not be found in ortools python library. Can someone help me with this? I am using python 2.7.5 at the moment.

**Comment by lperron** [comment]
Strange,

I just reran:
make clean
make python
make rpy EX=tsp

Running python/tsp.py

[06:19:03] src/constraint_solver/routing.cc:3956: A depot must be
specified, setting one at node 0

219

0 -> 4 -> 5 -> 1 -> 7 -> 6 -> 2 -> 8 -> 3 -> 9 -> 0


Can you give me more details? (platform, build status...)


Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-03-10 0:35 GMT-08:00 Muhammad Rafdi <notifications@github.com>:

**Comment by mombi93** [comment]
Hi Laurent,

I am running on OSX mavericks machine, the latest version of or-tools and python 2.7.5.

I installed or-tools three different ways:

1. running setup.py as stipulated here: [](https://developers.google.com/optimization/installing#python)
2. installed ortools through pip
3. cloning or-tools repo and ran the commands you have used in the last post.

Nothing works. When I run python tsp.py on the examples this is what I get:

`Traceback (most recent call last):
  File "tsp.py", line 32, in <module>
    from ortools.constraint_solver import routing_enums_pb2
ImportError: cannot import name routing_enums_pb2`

I think the main issue is that it is could not find routing_enums_pb2 in ortools.constraint_solver. 

Any advice?

**Comment by lperron** [comment]
I guess that after you have installed ortools through pip, it takes
precedence against the modules from the cloned repo.

And I have not yet built the new pypi modules with the routing_enums.pb2.'

Can you try cleaning ortools from pip and rerun option 3?

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-03-10 15:18 GMT-08:00 Muhammad Rafdi <notifications@github.com>:

**Comment by mombi93** [comment]
I've uninstalled ortools using pip and then installed or-tools using option 3 again.

Installing through option 3 gives me the following error (same error as last time I did it):

/Users/muhammad/code/git/or-tools/dependencies/install/bin/protoc --proto_path=src --cpp_out=src/gen src/constraint_solver/solver_parameters.proto
make: /Users/muhammad/code/git/or-tools/dependencies/install/bin/protoc: No such file or directory
make: *** [src/gen/constraint_solver/solver_parameters.pb.cc] Error 1

it seems that I am missing /install/bin/protoc in dependencies folder in or-tools repository. I just checked the repo and install folder is not even there at all.

Advice?

**Comment by lperron** [comment]
Did you run make third_party? Please have a look at building instructions.

Thanks
Le 11 mars 2016 2:01 AM, "Muhammad Rafdi" <notifications@github.com> a
écrit :

**Comment by mombi93** [comment]
I followed the instruction to install from source and it works now! Even though I had to reinstall it a few times because some of the dependencies were not installed (for whatever reasons).

Thank you for this!
