### ISSUE TITLE
Constraint programming: What optimization method is used by CP_SAT while optimizing?

### ISSUE THREAD

**Issue by stoneren0316** [google/or-tools#1610]
What optimization method is used by CP_SAT while optimizing?
Local search? 
Or some heuristic algorithm?
Many thanks!

**Comment by stoneren0316** [comment]
What is the difference between origin CP and CP_SAT's optimization algorithm?

**Comment by lperron** [comment]
Answered multiple times.

Search for Peter Stuckey 'search is dead'.

**Comment by stoneren0316** [comment]
@lperron So sorry for troubling again!
I am working on some job shop like problem and I want to confirm some details about CP and CP_SAT sovler.
1. CP_SAT is a better solver so CP solver is not recommended to use any more?
2. CP solver supports customization of the search and CP_SAT only supports static search stategies, right?

**Comment by lperron** [comment]
yes and yes.
For 2) I usually do not even use search strategy, the default one,
especially with multithreading is good enough.

For the technology, search for :'Search is Dead' from Peter Stuckey.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 10 oct. 2019 à 12:08, stoneren0316 <notifications@github.com> a
écrit :
