### ISSUE TITLE
Building with SCIP 6.0.2 on manylinux1

### ISSUE THREAD

**Issue by syonekura** [google/or-tools#1613]
Hi, i'm trying to build an ortools wheel with scip using the [manylinux dockerfile](https://github.com/google/or-tools/blob/stable/tools/docker/manylinux1.Dockerfile), adding the steps [here](https://developers.google.com/optimization/install/python/source_linux#install-the-scip-optimization-suite) to install scip before the wheels (just before the `# ORTOOLS #` section:

```
# SCIP
ARG SCIP_VERSION=6.0.2
COPY ./lib/scipoptsuite-${SCIP_VERSION}.tgz /
ENV SCIP_SRC /scipoptsuite-${SCIP_VERSION}
ENV SCIP_BUILD /scipoptsuite-${SCIP_VERSION}/build
ENV SCIP_INSTALL /scip_install
RUN tar -xf scipoptsuite-${SCIP_VERSION}.tgz
WORKDIR "$SCIP_BUILD"
RUN cmake -DCMAKE_INSTALL_PREFIX=$SCIP_INSTALL -DGMP=false -DZIMPL=false -DTPI=tny -DPARASCIP=true ..
RUN make
RUN make install
```

But when running make I get the following error:
```
[ 44%] Building CXX object scip/src/CMakeFiles/scip.dir/symmetry/compute_symmetry_none.cpp.o
[ 44%] Linking CXX executable ../../bin/scip
CMakeFiles/scip.dir/tinycthread/tinycthread.c.o: In function `_tthread_timespec_get':
tinycthread.c:(.text+0x39a): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/scip] Error 1
make[1]: *** [scip/src/CMakeFiles/scip.dir/all] Error 2
make: *** [all] Error 2
```

Am I missing some flag in the cmake, or should install some library?

**Comment by lperron** [comment]
I don't know. this is a scip issue.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
