### ISSUE TITLE
VRP with Roaming Delivery Locations?

### ISSUE THREAD

**Issue by arukhin** [google/or-tools#1614]
I asked [this question](https://stackoverflow.com/questions/58126172/how-to-implement-routing-with-roaming-delivery-locations-with-time-windows-in-or) on stackoverflow, but it received no attention.  I was hoping to receive some sort of guidance here.  

How can one modify the constraints of a routing problem so that the delivery location  can be selected from one or more time-window/location pairs (instead of exactly one time-window/location pair as is the case of standard VRP)?

**Comment by lperron** [comment]
Look at disjunction.

Is this a pdp ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 1 oct. 2019 à 15:48, Andrey Rukhin <notifications@github.com> a
écrit :

**Comment by arukhin** [comment]
It is not a PDP (Pickup and Delivery problem) yet.  For future reference, what would one do if it were a PDP?

**Comment by lperron** [comment]
Optionality and pdp pairs are a bit tricky. I would duplicate all nodes
such that no pair shares any node with another pair.

Le mar. 1 oct. 2019 à 17:14, Andrey Rukhin <notifications@github.com> a
écrit :
