### ISSUE TITLE
Different Pickup locations per vehicle, or find 'cheapest' Pickup location

### ISSUE THREAD

**Issue by PauliusGrigelis** [google/or-tools#1616]
Sorry for bad English.
We have a scenario, where multiple vehicles have different depot locations, each delivery node have multiple possible pickup locations. The goal is to include a single 'cheapest' pickup location out of list of possible pickups.

Since we don't know yet which vehicle will be delivering where, we can't select single 'closest' pickup.

So, does or-tools support different pickup locations per vehicle? That way we would use 3d matrix (2d matrix of pickup and delivery per vehicle), similarly like with distance or time constraints.

Anything helps.

**Comment by PauliusGrigelis** [comment]
![image](https://user-images.githubusercontent.com/17303382/66045604-c18bd800-e52c-11e9-82e0-e34bd8bd854a.png)

Let's pretend that this is a map, V stands for vehicle (green circles), P for Pickup (purple), D for delivery location (red).

Let's assume that V2 and V3 won't make it in time (shift ends too early, or they are very slow). So we get a plan, V1 -> P1 -> D1, since P1 was assigned as a pickup for D1, but it has an alternative pickup location P2.  And wanted result is a V1 -> P2 -> D1.
 If a route is generated for V2, we would like to use P1 as a pickup for D1 and so on.

**Comment by lperron** [comment]
Rough sketch:


   - 1 vehicle per depot
   - duplicate each node attached to two different PDP pairs.
   - add all pickup nodes to a disjunction
   - add all delivery nodes to a disjunction
   - add all PDP pairs to the model.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 2 oct. 2019 à 08:55, PauliusGrigelis <notifications@github.com> a
écrit :

**Comment by PauliusGrigelis** [comment]
Could you please elaborate on this step:  - duplicate each node attached to two different PDP pairs.

I forgot to mention that we want only 1 visit to delivery node, I'm afraid that by duplicating delivery node solution will give multiple visits to that node

**Comment by lperron** [comment]
I am travelling.

This has been detailed multiple times in this mailing list.

Le mer. 2 oct. 2019 à 09:25, PauliusGrigelis <notifications@github.com> a
écrit :

**Comment by PauliusGrigelis** [comment]
Thank you, it works.

Instead of adding all delivery nodes to disjunction we add disjuction for each group.

Let's say we have 2 delivery nodes 1 and 2.
1 node has 2 pickup nodes 3 and 4.
2 node has 2 pickup nodes 5 and 6.

After duplicating we have 4 delivery nodes 1,7,2,8.
PAD array: [[3,1],[4,7],[5,2],[6,8]]

On top of PDP constraint we add disjunction([1,7]) and another one disjunction(2,8).
In our case there is no need to add disjunction for pickups, since single pickup node can be visited multiple times, but we have constraint that there is only 1 visit per route.

Have a nice trip.
