### ISSUE TITLE
RuntimeError: SWIG std::function invocation failed

### ISSUE THREAD

**Issue by chiragbhatia72** [google/or-tools#1620]
Environment:
OR-Tools version: 7.3.7083
OS: Mac OSX
Python version: 2.7.16

Traceback (most recent call last):
  File "cvrp.py", line 101, in <module>
    main(data)
  File "cvrp.py", line 97, in main
    print_solution(data, manager, routing, assignment)
  File "cvrp.py", line 23, in print_solution
    plan_output = 'Route for vehicle {}:\n'.format(vehicle_id)
RuntimeError: SWIG std::function invocation failed.

I am getting RuntimeError while running the capacitated vehicle routing problem (CVRP). I have attached my code. Can someone please help me with this. Thanks in advance.

[cvrp.py.zip](https://github.com/google/or-tools/files/3689623/cvrp.py.zip)

**Comment by lperron** [comment]
It works perfectly on master.

Please note that 7.3 is the last release that supports python 2.7.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 4 oct. 2019 à 04:24, Chirag Bhatia <notifications@github.com> a
écrit :
