### ISSUE TITLE
GLOP - Restart with new constraint

### ISSUE THREAD

**Issue by N-Wouda** [google/or-tools#1621]
Is it possible to solve a model, add a new constraint, and re-solve with said additional constraint? I'm using the GLOP linear solver via the Python wrapper, but get the following error message,

`E1004 15:35:47.898052 14156 linear_solver.cc:1486] The model has been changed since the solution was last computed.`

Which is obviously correct, as I've added a new constraint in-between. Do you know of a work-around, or should I create a new solver and equip it with the same constraints + the new one?

**Comment by lperron** [comment]
Are you sure you are resolving after adding the new constraint ? The
message indicates you tried to access the solution while the model has
changed.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 4 oct. 2019 à 09:51, Niels Wouda <notifications@github.com> a
écrit :

**Comment by N-Wouda** [comment]
D'oh! I was reusing the old value just after adding the new constraint, to compute a next step in my algorithm. I've since reordered my code, and now it appears to work beautifully. How silly.

Thank you for your quick reply!

**Comment by thomasahle** [comment]
Is it a problem to access the old values while still creating new constraints?
Otherwise, is there a way to disable the warning?
