### ISSUE TITLE
Gurobi ISV License Key

### ISSUE THREAD

**Issue by pmotakef** [google/or-tools#1625]
Hello everyone,
The company I work with has an ISV license key from Gurobi which means we don't have a gurobi.lic file. But to use the Gurobi we create a "gurobipy.Env.OtherEnv" object and pass in parameters for organization name, license key, etc. Then this Env object is passed to gurobipy.Model.
I was wondering if in OR-tools we can pass the gurobipy.Env object (or GRBEnv) when creating the solver?
Going through the source code it seems "_pywraplp.new_Solver" only takes a name and a solver type, while this method calls LoadGurobiEnvironment(GRBenv** env). But I am not sure where the env object is created and passed into this function.
Thanks a lot.

**Comment by lperron** [comment]
As you are compiling from source already, I would patch
gurobi_environment.cc or gurobi_interface.cc to do the right thing.

This would be easier than going through the python-c++ interface.

--Laurent
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 7 oct. 2019 à 10:56, Pouya Moetakef <notifications@github.com> a
écrit :
