### ISSUE TITLE
Job Scheduling with CP SAT Solver

### ISSUE THREAD

**Issue by hktony0129** [google/or-tools#1626]
I'm working on creating a program to schedule jobs using CP SAT solver.
Each job would be either daily job that runs on specific days of the week, or weekly job that runs once per week.
Each job would use a certain percentage of resources available, and the use differs between jobs. 
There can also be dependency between 2 jobs, so one has to finish before another

For example:
- job1 is a job that runs daily Monday - Friday, lasts for 2 hours and use 20% of computing power. 
- job2 is a job that runs daily Monday - Friday, lasts for 1 hour and use 50% of computing power. Job1 is a dependency of Job2
- job3 is a weekly job that can be ran on any day between Wednesday - Friday. For 6 hour and use 80% of computing power.

The goal is to find the a feasible solution to arrange the jobs. (The starting time for each job in minutes)

So I'm currently trying to find the best way of modelling the problem.  

My current approach is  to create an interval variables for each instance of job execution with domain (0 - 1440* 7); 5 intervals for job1, 5 intervals for job2 and 1 interval for job3.  
Then add equality constraints to ensure that the instances for the same job differs exactly by 1 day.  
And add all the intervals together into a cumulative constraint to satisfy the resource constraint. 

However, we currently have around 200 jobs to be scheduled, the model would take around 10 minutes to return a feasible solution. 

Do you know if there's a way to model the problem better to speed up the performance of the 

Thank you

**Comment by lperron** [comment]
Do you really need to schedule to the minute ?
Can you do 5 minutes, 10 minutes ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by hktony0129** [comment]
I think minute would be preferred for our use case.

Do you think creating a cumulative constraint for each day would be a better approach?
Something like this:
```
cumulative_jobs = []
cumulative_demands = []

for i in range(7):
	cumulative_jobs.append([])
	cumulative_demands.append([])

for job in all_jobs:
	bools = []
	for day in range(7):
		if job.scheduled(day):
			if job.is_daily_job():
				cumulative_jobs[day].append(job.interval_variable)
			else:
				bool = model.NewBoolVar("somename")
				interval = model.NewOptionalIntervalVar(job.start, job.time, job.end, bool, "somename")
				cumulative_jobs[day].append(job.interval_variable)
				bools.append(bool)
			cumulative_demands[day].append(job.demand)
	if not job.is_daily_job():
		model.Add(sum(bools) == 1)

for i in range(7):
	model.AddCumulative(cumulative_jobs[i], cumulative_demands[i], 100)
```

**Comment by lperron** [comment]
definitely worth trying.

Can you send me the current code ? (could be by PM).
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by hktony0129** [comment]
I have tried to model the problem with the approach, however it became difficult to model some of the other constraints that we have. So I think we might stick to what we have right now.

Our current approach is similar, but instead of having 7 cumulative constraints, we only have 1 for the entire week. 
For weekly job there is an interval within the range [0, 7 * 24 * 60]
For daily job, there is an interval for each of its scheduled day [day * 24 * 60, (day+1) * 24 * 60]. And there is additional constraint to a reference variable so that the start times are separated by exactly 24 * 60.
`model.Add(job_ref_start + 24 * 60 * day == interval_start)`

Also do you know anywhere that I can find a high level overview of how CP-SAT solver work. And maybe some technical papers as well.

Thank you
Tony

**Comment by lperron** [comment]
For the technical explanation, search for 'search is dead' talk by Peter
Stuckey.

**Comment by lperron** [comment]
I think you approach is a good one.
You can add a redundant 1 day cumulative constraint that contains all daily jobs. It could also contains an 'aggregated' version of the weekly jobs.

**Comment by hktony0129** [comment]
Thank you for your help Laurent.
I will give the redundant cumulative constraints a try.
