### ISSUE TITLE
Solving Bin Packing with Multiple Dimensions and Multiple Bins

### ISSUE THREAD

**Issue by deepuec** [google/or-tools#1627]
Hi,
  I have a number different products with 3 dimensions (length X width X height) and multiple 3-Dimensional Bins of same dimensions (Length X Width X Height). We need to pack all the items in the least number of bins, trying to keep products of the same type together in the same bin as much as possible and only split if absolutely needed. 

Is there a good way to model this ?

We tried simplifying this to a uni-dimensional by abstracting how many cases of a product fit in a bin and then converting that fraction into a integer by multiplying everything by say 1000 to get a good approximation, and solving using CP Solver or a Knapsack problem. 

In one case we end up with all the Bins being filled uniformly rather than trying to pack as much as possible in each bin. 
In the Knapsack formulation, it does do close to what we need, except it does not split the products because of our approximation, so for example if we have 3 products of {13,25,19} (for a total capacity of 57) and bin capacity 30, so we can optimally fit it in 2 trucks (with total capacity of 30X2 = 60) but the Knapsack formulation uses 3 Bins instead of splitting one of the products into 2 separate trucks.

Thanks
Deepak

**Comment by lperron** [comment]
You want to do exact bin-packing (making sure the boxes do not intersect) ?

A 'brute force' model would have on copy of each box per bin. A box is
represented by one of its corners.
Then for two bin in the same box, I would have this constraint:
  bool_or(box_one_is_not_in_this_box,
          box_two_is_not_in_this_box,
          box_one_is_on_the_left_of_box_two,
          box_one_is_on_the_right_of_box_two,
          ...)  # behind, in front, above, below

Then you know how many of each box type is in each bin, and compute your
objective accordingly.

If the number of possible bins is limited, you can precompute all of them,
and just decide on how many of each bin filling options you need for your
problem.



Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 7 oct. 2019 à 12:44, Deepak Naik <notifications@github.com> a
écrit :

**Comment by deepuec** [comment]
Hi @lperron , 

Can Or-Tool solve multi dimensional multi knapsack problem? Could you please share some examples around it.
