### ISSUE TITLE
Does or-tools support fractional Knapsack problem?

### ISSUE THREAD

**Issue by deepuec** [google/or-tools#1628]

**Comment by lperron** [comment]
There is nothing special to this problem.
This is a pure linear programming model. 
In one dimension, you just need to sort correctly.

**Comment by deepuec** [comment]
Hi @lperron , Thanks for the update. 
I have simple problem below
 we have 3 products of {13,25,19} (for a total capacity of 57) and bin capacity 30, so we can optimally fit it in 2 trucks (with total capacity of 30X2 = 60) .
When I initialize solver with 2 bin capacity and solve, I see item with 25 weight is assigned to first truck and 19 to second one leaving behind product with weight 13.

How can I instruct the solver to split product 13 and fill the trucks.

**Comment by lperron** [comment]
create 2 fake items one of size 30, one of size 57 - 30 = 27, and change
your problem to have 2 items instead.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 7 oct. 2019 à 15:29, Deepak Naik <notifications@github.com> a
écrit :

**Comment by mmg0311** [comment]
Hi @lperron 

I am having following requirement where i think some variation of fractional knapsack could help me solve this, can you please suggest how can I create an expression to achieve the following goal.
 
Requirement :
Consider 'n' sacks with some capacity and items with varying weights the weight of items is sum of their subitems.

Goal :
 Pack the items in sacks in such a way that we minimise the distribution of subitems of a particular item in sacks

thanks!!

**Comment by lperron** [comment]
No necro-posting please, and do not use issues fo modeling questions.
