### ISSUE TITLE
Creating interval variables leads to infeasible solution without adding constraints

### ISSUE THREAD

**Issue by woopsix** [google/or-tools#1629]
So, i'm facing a strange issue.
I have a tuple of time durations and i'm trying to create a list of interval variables.
Thing is, when i use the model to create a new interval var, the solution is infeasible, even without adding a constraint.

example:

    my_model = cp_model.CpModel()
    solver = cp_model.CpSolver()

    load_tuple = (60, 30, 50, 40)
    duration_tuple = (2, 1, 2, 5)
    names = ('A', 'B', 'C', 'D')

    start_task_time = my_model.NewIntVar(0, 1000, 'start_time')
    end_task_time = my_model.NewIntVar(0, 1000, 'end_time')

    tasks = []

    for load, duration, name in zip(load_tuple, duration_tuple, names):
        tasks.append(
            my_model.NewIntervalVar(start_task_time, duration, end_task_time, name)
        )

    status = solver.Solve(my_model)

    print(solver.StatusName(status))

or tools Version: 7.3.7083

**Comment by stradivari96** [comment]
Hmm, your model is wrong, you are telling the solver to create 4 intervals that start and end at the same time with different durations.

You must create more start and end intvars.

**Comment by lperron** [comment]
Exactly. Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
