### ISSUE TITLE
addDimensionWithVehicleTransitAndCapacity is not implemented in Java Swig

### ISSUE THREAD

**Issue by pocman** [google/or-tools#163]
Support for vectors of evaluators seems to be missing in Java.

```
  public boolean addDimensionWithVehicleTransitAndCapacity(SWIGTYPE_p_std__vectorT_ResultCallback2T_long_long__RoutingModel_NodeIndex__RoutingModel_NodeIndex_t_p_t var1, long var2, LongResultCallback1 var4, boolean var5, String var6) {
    return operations_research_constraint_solverJNI.RoutingModel_addDimensionWithVehicleTransitAndCapacity(this.swigCPtr, this, SWIGTYPE_p_std__vectorT_ResultCallback2T_long_long__RoutingModel_NodeIndex__RoutingModel_NodeIndex_t_p_t.getCPtr(var1), var2, SWIGTYPE_p_ResultCallback1T_long_long_long_long_t.getCPtr(var4.getPermanentCallback()), var4, var5, var6);
  }
```

**Comment by furnon** [comment]
We are aware of the issue and looking into it. The fix is not
straightforward.

**Comment by pocman** [comment]
@furnon @dlahlou 
Do you have any update on this issue ?
Or maybe a work around ? What If I create as many dimension as vehicle and I use `addDimensionWithVehicleCapacity` with all but one capacity set to infinity ?

**Comment by pocman** [comment]
@furnon @dlahlou
Do you have any update on this issue ?

**Comment by furnon** [comment]
Yes it's available now.

**Comment by pocman** [comment]
Thanks, I'm not sure to know how to generate a `SWIGTYPE_p_std__vectorT_ResultCallback2T_long_long__RoutingModel_NodeIndex__RoutingModel_NodeIndex_t_p_t` object. Could you provide an example ?

We had a lot of trouble migrating From 4.? (before github releases) to 5.1
Thanks to Lightbend support, we were able to fix all our issues with `sbt run`, `sbt test` and `sbt stage`.

It involved using ` "com.typesafe.play"     %% "play-native-loader"       % "1.0.0"` and adding the following to our build.sbt file.
```
fork in Test := false

// Path separators varies according to OS. Linux and MacOS uses ":"
// while Windows uses ";".
val pathSeparator = System.getProperty("path.separator")

// Avoid to complete override java.library.path.
val currentJavaLibraryPath = System.getProperty("java.library.path")

javaOptions in run += s"-Djava.library.path=$currentJavaLibraryPath$pathSeparator${baseDirectory.value / "lib"}"

javaOptions in Test += s"-Djava.library.path=$currentJavaLibraryPath$pathSeparator${baseDirectory.value / "lib"}"

includeFilter in unmanagedJars := {
  val old = (includeFilter in unmanagedJars).value
  old || "*.dylib"
}
```

Tags for desperate folks : 
`java.lang.UnsatisfiedLinkError: com.google.ortools.constraintsolver.operations_research_constraint_solverJNI.swig_module_init()V`
`java.lang.UnsatisfiedLinkError: no jniortools in java.library.path`
`java.lang.UnsatisfiedLinkError: /tmp/sbt_689ab529/sbt_facc3145/libjniortools.so: libortools.so: cannot open shared object file: No such file or directory`

**Comment by furnon** [comment]
Here's a simple example with a single vehicle:
 NodeEvaluator2[] transits = new NodeEvaluator2[1];
 transits[0] = new NodeEvaluator2() {
        @Override
        public long run(int firstIndex, int secondIndex) {
          return 10; // put an actual meaningful value here
        }
      };
 long capacity[] = new long[1];
 capacity[0] = 1000; // put an actual meaningful capacity here
 routing.addDimensionWithVehicleTransitAndCapacity(
        transits,
        10000,
        capacity,
        true,
        "dim");

**Comment by pocman** [comment]
Perfect, thanks !

**Comment by pocman** [comment]
@furnon I tried your simple example but I'm still stuck with the signature generated by swig : 
```
    public boolean AddDimensionWithVehicleTransits(SWIGTYPE_p_std__vectorT_ResultCallback2T_long_long__RoutingModel_NodeIndex__RoutingModel_NodeIndex_t_p_t var1, long var2, long var4, boolean var6, String var7) {
        return operations_research_constraint_solverJNI.RoutingModel_AddDimensionWithVehicleTransits(this.swigCPtr, this, SWIGTYPE_p_std__vectorT_ResultCallback2T_long_long__RoutingModel_NodeIndex__RoutingModel_NodeIndex_t_p_t.getCPtr(var1), var2, var4, var6, var7);
    }
```
