### ISSUE TITLE
GRBcomputeIIS for Gurobi wrapper

### ISSUE THREAD

**Issue by pmotakef** [google/or-tools#1631]
Hi,
Is there a way to use the GRBcomputeIIS(model) or Model.ComputeIIS() to get Irreducible Inconsistent Subsystem in python wrapper of Gurobi?
Thanks,

**Comment by lperron** [comment]
No.

Out of curiosity, why would you prefer or-tools over the gurobi python layer ?

**Comment by pmotakef** [comment]
Thanks a lot for your answer. 
Because we want to have the option of leaving Gurobi in future if we have to, and just switch the solver for out code to continue working. I thought or-tools would be great for this.
