### ISSUE TITLE
How to solve the flexible job shop problem with multiple slots machines?

### ISSUE THREAD

**Issue by stoneren0316** [google/or-tools#1633]
Hello,
In our flexible job shop problem, there are machines with 5 slots. this means one machine of this kind can do 5 tasks one time at most and these tasks in one machine must start at the same time.
I learned the cumulative constraint, but I still don't know if the problem can be modeled by it.
Is there any method or examples?
Many thanks!

**Comment by stoneren0316** [comment]
I am using CP_SAT solver.

**Comment by stoneren0316** [comment]
CP_SAT solver

**Comment by lperron** [comment]
Do all the jobs have the same duration ?

**Comment by stoneren0316** [comment]
Tasks processed by the multi slot machine have the same duration.
like the job shop problem, there are multi sub-tasks in a job.
For example, Machine M has 3 slots; job A has 3 tasks and the 1st task must be processed on Machine M; job B has 4 tasks and the 2nd task must be processed on M.  Machine M can process the two tasks (maybe more) in parallel and the two tasks which have the same duration must start at the same time.

**Comment by lperron** [comment]
Batch scheduling is a good question.

If you know that all parallel jobs with have 'periodic' start times, you can inflate time by adding 1 timestep around each batch, and add a fixed interval var filling each boundary on each machines.
This way, jobs must fall in the batchs.

If the possible start times cannot be deduced in advance, then you need to go the long road.
Create one Boolean for each pair of jobs. Make sure that this Boolean is equivalent to the jobs overlapping. Then having this Boolean forcing the start vars to be equal.

This can be simplified into:
For a pair of intervals t1 and t2
b => start(t1) == start(t2)
not(b) => or(t1_before_t2, t2_before_t1)
t1_before_t2 <=> end(t1) <= start(t2)  # Note the equivalence
t2_before_t1 <=> end(t2) <= start(t1)

I hope this helps.
