### ISSUE TITLE
VRP with pickups and deliveries and load balancing

### ISSUE THREAD

**Issue by lantica** [google/or-tools#1635]
Hi, I wonder if i can use the ortool to solve this problem. 
It is a VRP problem with pickups and deliveries and multiple vehicles, but instead of finding out the minimum total travelling distance, I would like to make the longest route for the vehicles as short as possible (to some extent like load balancing?). 

Also, for the pickup and delivery part, the vehicle must go to the delivery point immediately after pickups. What first comes into my mind is to add the capacity constraint for it. Setting the demands for pickup points as 1 and delivery points as -1. Is it a good way to do?

**Comment by wnglnd** [comment]
Hello,
I have done about the same thing as you mention.

Regarding the Pickups and Deliveries I followed the [excellent guide](https://developers.google.com/optimization/routing/pickup_delivery) at the OR homepage. 

Considering the re-loading, a big help for me was [this example](https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/samples/cvrp_reload.py). See especially lines 182 - 186 which I think sets a Slack on the Delivery points (the ones with negative demand) which effectively unloads the vehicle.

Regarding loadbalancing see line 154 if the example above. That will put a large cost on the vehicle with the longest route, meaning that the solver will try to make that as small as possible which leads to a balancing effect on the vehicles' traveled distances.

If you want to restrict the vehicle to go directly to the delivery after pickup, you should also set the vehicle capacity to 1.

**Comment by routemegood** [comment]
Another option for saying the vehicle must do the delivery immediately after the pickup is to add a custom constraint that says so. Something along the lines of:
```
routing_model.solver().Add(routing_model.NextVar(pickup_index) == delivery_index)
```

Hope this helps.
