### ISSUE TITLE
About solver selection on job shop problem, CP or CP_SAT 

### ISSUE THREAD

**Issue by stoneren0316** [google/or-tools#1636]
@lperron So sorry for troubling again!
I am working on some job shop like problem and I want to confirm some details about CP and CP_SAT sovler.

1. CP_SAT is a better solver so CP solver is not recommended to use any more?
2. CP solver supports customization of the search and CP_SAT only supports static search stategies, right?

**Comment by lperron** [comment]
yes. Answered in the other thread.
