### ISSUE TITLE
how to set constraint for assign all orders in vrp

### ISSUE THREAD

**Issue by showkeyjar** [google/or-tools#1637]
I noticed cvrptw example will have unassigned orders.
but in real world, some times we have reserved orders,
and we can reassign those orders in hours,
so we must ensure assign all orders.
how to set constraint let system must assign all orders in vrp?

**Comment by showkeyjar** [comment]
I think this is Quadratic Distribution Problem, dose ortools can solver this problem?

**Comment by Mizux** [comment]
to make an order mandatory simply add a penalty equal to max value to it.

**Comment by showkeyjar** [comment]
ok , I'll have a try.

**Comment by showkeyjar** [comment]
ok , I think DEAP could be better choice.
