### ISSUE TITLE
Precision issue?

### ISSUE THREAD

**Issue by stradivari96** [google/or-tools#1639]
Hi,

I have attached my model proto that returns an OPTIMAL objective value of:
```
objective_value: 200007559.99999997
```
Therefore python solver.Value gives me 200007559 which is actually infeasible in my model.

Is this a bug or I am doing something wrong?

[model_proto.txt](https://github.com/google/or-tools/files/3718384/model_proto.txt)

**Comment by lperron** [comment]
Which language?

Le ven. 11 oct. 2019 à 17:38, Xiang Chen <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
Can you check you are not printing it as an integer ?

**Comment by stradivari96** [comment]
Got it, forgot to round it up.
Thanks!
