### ISSUE TITLE
Error in GetFingerprintOfEvaluator

### ISSUE THREAD

**Issue by pocman** [google/or-tools#164]
When running Routing Model with 105 vehicles and 250 locations and using : 
`addDimensionWithVehicleCapacity` for weight,
`addDimension` for time and `setArcCostEvaluatorOfVehicle` for each vehicle I have this error : 
```
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libjniortools.dylib+0x683d2]  operations_research::RoutingModel::GetFingerprintOfEvaluator(ResultCallback2<long long, IntType<operations_research::_RoutingModel_NodeIndex_tag_, int>, IntType<operations_research::_RoutingModel_NodeIndex_tag_, int> >*) const+0x112
C  [libjniortools.dylib+0x68c3b]  operations_research::RoutingModel::ComputeCostClasses()+0x67b
C  [libjniortools.dylib+0x6c503]  operations_research::RoutingModel::CloseModel()+0x93
C  [libjniortools.dylib+0x70ba1]  operations_research::RoutingModel::Solve(operations_research::Assignment const*)+0x21
C  [libjniortools.dylib+0x38c6b]  Java_com_google_ortools_constraintsolver_operations_1research_1constraint_1solverJNI_RoutingModel_1solveWithParameters+0x1b
j  com.google.ortools.constraintsolver.operations_research_constraint_solverJNI.RoutingModel_solveWithParameters(JLcom/google/ortools/constraintsolver/RoutingModel;JLcom/google/ortools/constraintsolver/RoutingSearchParameters;JLcom/google/ortools/constraintsolver/Assignment;)J+0
j  com.google.ortools.constraintsolver.RoutingModel.solveWithParameters(Lcom/google/ortools/constraintsolver/RoutingSearchParameters;Lcom/google/ortools/constraintsolver/Assignment;)Lcom/google/ortools/constraintsolver/Assignment;+15

```

This is probably caused by the size of the instance but the error is not really explicit.

I have the possibility to use a microservice to run Or-tools RoutingModel. Should I use Python instead of java or will I have the same issues and do I need to switch to pure c++ ?

**Comment by furnon** [comment]
The problem is rather small so I don't think size is directly an issue. I'm
trying to reproduce this but my guess is that it could be due to something
going wrong with the evaluators you pass to setArcCostEvaluatorForVehicle.
Do you create them on the fly ? Do you keep a reference to avoid having the
GC clean them up ?

Vincent

**Comment by pocman** [comment]
My initial guess was also related to GC and the initial implementation was : 
```
    for (int vehicleIndex = 0; vehicleIndex < initialValues.numberOfVehicles(); vehicleIndex++) {
      final Vehicle vehicle = initialValues.vehiclesAsJava().get(vehicleIndex);
      final List<List<Long>> costMatrix = CostMatrixBuilder.apply(vehicle, initialValues).matrix(locations);

      final NodeEvaluator2 arcCostCallback = new NodeEvaluator2() {
        @Override
        public long run(int firstNode, int secondNode) {
          return costMatrix.get(firstNode).get(secondNode);
        }
      };

      routingModel.setArcCostEvaluatorOfVehicle(arcCostCallback, vehicleIndex);
    }
```

I switched to :
```
    for (int vehicleIndex = 0; vehicleIndex < initialValues.numberOfVehicles(); vehicleIndex++) {
      final Vehicle vehicle = initialValues.vehiclesAsJava().get(vehicleIndex);
      costMatrices.add(CostMatrixBuilder.apply(vehicle, initialValues).matrix(locations));

      final int index = vehicleIndex
      final NodeEvaluator2 arcCostCallback = new NodeEvaluator2() {
        @Override
        public long run(int firstNode, int secondNode) {
          return costMatrices.get(index).get(firstNode).get(secondNode);
        }
      };

      routingModel.setArcCostEvaluatorOfVehicle(arcCostCallback, vehicleIndex);
    }
```
where `costMatrices` is an instance variable but no much luck. The GC is quite aggressive :/

**Comment by furnon** [comment]
To ease debugging, you can also try disabling evaluator fingerprinting
(which is used to create evaluator equivalence classes) by setting search
parameters as follows:
    RoutingSearchParameters parameters =
        RoutingSearchParameters.newBuilder()
            .mergeFrom(RoutingModel.defaultSearchParameters())
            .setFingerprintArcCostEvaluators(false)
            .build();
and then calling solveWithParameters(parameters); instead of solve().

**Comment by furnon** [comment]
You also have to store the callbacks outside the loop with something like
this to keep the callbacks safe from the GC:

for (int vehicleIndex = 0; vehicleIndex < initialValues.numberOfVehicles();
vehicleIndex++) {
      final Vehicle vehicle =
initialValues.vehiclesAsJava().get(vehicleIndex);
      costMatrices.add(CostMatrixBuilder.apply(vehicle,
initialValues).matrix(locations));

      final int index = vehicleIndex;
      arcCostCallbacks.add(new NodeEvaluator2() {
        @Override
        public long run(int firstNode, int secondNode) {
          return costMatrices.get(index).get(firstNode).get(secondNode);
        }
      });

      routingModel.setArcCostEvaluatorOfVehicle(arcCostCallbacks[index],
vehicleIndex);
    }

**Comment by pocman** [comment]
It seems to be lot more stable with callbacks outside the loop !

I was not able to find `setFingerprintArcCostEvaluators` in the jar.
```
Manifest-Version: 1.0
Created-By: 1.8.0-google-v7 (Google Inc.)
```

**Comment by furnon** [comment]
On Thu, Mar 17, 2016 at 11:51 AM, Thomas <notifications@github.com> wrote:

> It seems to be lot more stable with callbacks outside the loop !
>

By stable do you mean it works now ?


> I was not able to find setFingerprintArcCostEvaluators in the jar.
>

Are you importing
com.google.ortools.constraintsolver.RoutingSearchParameters ? Anyways, if
the problem is fixed you don't need that anymore.

**Comment by pocman** [comment]
It works for medium instances but I now have an issue with my JVM size (2Go is not enough).
I'll look into that.

About RoutingSearchParameters, I'm already using that :

```
      final RoutingSearchParameters routingSearchParameters = new RoutingSearchParameters();
      final RoutingParameters globalParameters = new RoutingParameters();
      globalParameters.setUse_light_propagation(true);
      RoutingModel.setGlobalParameters(globalParameters);

      routingModel.setFirstSolutionStrategy(RoutingModel.ROUTING_ALL_UNPERFORMED);
      routingSearchParameters.setFirst_solution("PathCheapestArc");
      routingSearchParameters.setTrace(true);
      routingSearchParameters.setNo_lns(true);

      final Optional<Assignment> assignment = Optional.ofNullable(routingModel.solveWithParameters(routingSearchParameters, null));
```

Are those parameters still useful ?
It looks like I'm not using the up to date version of OrTools because I can't compile https://github.com/google/or-tools/blob/0e6b0304bacac754864190eea416924aaa9a07ba/examples/com/google/ortools/samples/Tsp.java

**Comment by lperron** [comment]
I did not update binary archives. You need to compile from sources.
Hopefully, I will be able to build them soon.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-03-17 18:21 GMT+01:00 Thomas <notifications@github.com>:
