### ISSUE TITLE
CP-SAT: The more search_workers, the more time used to get the first feasible solution.

### ISSUE THREAD

**Issue by stoneren0316** [google/or-tools#1641]
Hello, @lperron.
I am working on some job shop like problem and I am doing some test using jobshop_sat.cc.
I found when num_search_workers set to 8, it usually take more time to get the 1st feasible solution than 1. Is this normal? Should num_search_workers be set to 1 if I want to get 1st feasible as soon as possilbe?
Thanks a lot!

**Comment by lperron** [comment]
Search is non deterministic, and workers share information, which in turn can change the search.
In practise, it improves search a lot, but you can be unlucky.

**Comment by stoneren0316** [comment]
Thanks for the reply.
I think I get a little more understanding.
