### ISSUE TITLE
.proto files still being imported into .NET framework project

### ISSUE THREAD

**Issue by Landcross** [google/or-tools#1642]
Last friday the update with support for .NET framework was released. I installed the NuGet package into an existing project, and to my surprise the .proto files are still being imported into the project, even though pull request #1500 mentions:

> Removed Protobuf files (.proto) from Nuget package in order to prevent copying them into Nuget consumers project.

I have no idea why it does that. I created test projects (.NET Framework) both inside and outside the solution, and it indeed does not add the .proto files anymore (while it did before 7.4), but for some mysterious reason it still does in this specific project. The project is a Class Library with .NET Framework 4.6.1.

I'm fairly new to .NET, any idea why it's still adding the .proto files inside this existing project?

**Comment by lperron** [comment]
Because it was a request.
I have added them back.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
the removed of proto files patch have been reverted since few advanced users need them (requirement for their use cases).

note: maybe we need to clean them a little to follow the `<contentFiles>` scheme see https://docs.microsoft.com/en-us/nuget/reference/nuspec#including-content-files

**Comment by Landcross** [comment]
But then why do they show up within my existing project, but don't show up in any newly created .NET Framework or .NET Core project?

**Comment by lperron** [comment]
I don't know. I welcome any suggestions to embed these files inside the
nupkg that is not intrusive.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
