### ISSUE TITLE
Employee scheduling - add constraint that someone works at most two shifts if they are consecutive

### ISSUE THREAD

**Issue by lambdaofgod** [google/or-tools#1643]
I want to make shifts more granular, so I divided them into half-shifts (people are still supposed to work one shift though, which means two consecutive half-shifts).
The problem with this is that now I have trouble encoding constraint for consecutive half shifts.
If I drop requirement of consecutive half-shifts I only need to change line
```model.Add(sum(shifts[(n, d, s)] for s in all_shifts) <= 1)```
To have 2 instead of 1.

I tried encoding requirement for consecutive shifts:
```
(sum(shifts[(n, d, s)] for s, __ in all_shifts) <= 1)
                  or (max([shifts[(n, d, s)] + shifts[(n, d, s+1)] for s in all_shifts[:-1]]) == 2)
```
But it doesn't work (it doesn't find any solution when there obviously is one). I also tried using AddOr with these two conditions, but then I get

> TypeError: NotSupported: model.GetOrMakeBooleanIndex(((((((shift_n0d0s0) + shift_n0d0s1) + shift_n0d0s2) + shift_n0d0s3) + shift_n0d0s4) + shift_n0d0s5) <= 1)

Which seems to come from old condition, and not the one I wrote.

**Comment by lperron** [comment]
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 14 oct. 2019 à 10:40, Jakub Bartczuk <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
You cannot add python constructs (min, max, or, and, if, then) in a
constraint. It makes no sense, as they are interpreted by python before
being added to the solver.

To say that you cannot work 3 consecutive shifts, take all sequence of 3
shifts, and add

model.AddBoolOr([shift(i).Not(), shift(i + 1).Not(), shift(i + 2).Not()])

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lambdaofgod** [comment]
My problem is that I need employees to work one shift OR two consecutive shifts.
I don't see how to do that because this condition is of the form

cond_1 OR (cond_2_1 AND cond_2_2) OR ... OR (cond_n_1 AND cond_n_2)

Which makes a problem since I don't see how I can add conjunction of alternatives or alternative of conjunctions.

**Comment by stradivari96** [comment]
You can create intermediate boolean variables.
`AddBoolAnd([cond_2_1, cond_2_2]).OnlyEnforceIf(cond21_22)`
and use them in AddBoolOr
