### ISSUE TITLE
[Help] Constraint at vehicle route end 

### ISSUE THREAD

**Issue by thucnc** [google/or-tools#1644]
Based on the Routing.End(int vehicle) method and a distance dimension (so called distance_dimension) , can I set a constraint such as :

```
Routing.End(int vehicle) < 10 || distance_dimension.CumVar(Routing.End(int vehicle)) < 100
Routing.End(int vehicle) < 8 || distance_dimension.CumVar(Routing.End(int vehicle)) < 80
```

The idea is I want to set condition based on the total visited node count and the total travelled distance, but I don't want to use DependentDimension... method because it is not ready on Python yet.

For example, I want the max_distance of a trip of 10 nodes should be under 100 kms, trip of 9 nodes should be under 90 kms, etc... So, in this case, if ortools get the distance of 9 nodes at 91kms, it should back to 8 nodes state instead of going further to 10 nodes. 

Please advise. Thanks

**Comment by abduakhatov** [comment]
Maybe I misunderstood but, what is the point of 10 node 100km constraint then, if 9 node 91 km is the limit?

**Comment by thucnc** [comment]
@abduakhatov I charge my customer per stop, say 10$/stop, and I pay our driver per distance, say 5$/km, so my profit is `(node_count*10 - distance*5)`. So I define a required earning per distance (epd) and need to find trips satisfying the epd as many as possible, others will be ignored. 

That's is my idea. :D

**Comment by abduakhatov** [comment]
> For example, I want the max_distance of a trip of 10 nodes should be under 100 kms, trip of 9 nodes should be under 90 kms, etc

First you can create [distance_dimension](https://developers.google.com/optimization/routing/vrp) and [counter](https://github.com/google/or-tools/issues/958#issuecomment-470010900) of nodes per vehicle
```
plus_one_callback_index = routing.RegisterUnaryTransitCallback(lambda index : 1)
dimension_name = 'Counter'
routing.AddDimension(
  plus_one_callback_index,
  0,  # null capacity slack
  N,  # vehicle maximum capacities
  True,  # start cumul to zero
  'Counter')
counter_dimension = routing.GetDimensionOrDie(dimension_name)
for vehicle_id in range(num_vehicle):
  index = routing.End(vehicle_id)
  solver = routing.solver();
  num_stops = counter_dimension.CumulVar(index)
  total_distance_per_vehicle = distance_dimension.CumulVar(index)
  solver.Add(num_stops*10 >= total_distance_per_vehicle) # 5stops*10 >= 50km

```

P.S. did not tested hope it works

**Comment by abduakhatov** [comment]
@thucnc #1121 you already asked this kinda question.

**Comment by thucnc** [comment]
Hi @abduakhatov , thanks for your solution, let me try on this.
For another similar question, actually the suggested solution doesn't work on python with DependentDimension as I already mentioned at beginning of this issue. Hence I ask for another approach.

**Comment by thucnc** [comment]
On the other hand, is there any way to check and reject a solution at the time it is found ?

**Comment by abduakhatov** [comment]
You mean post solution or inter-solution? I don't know regarding routing, but pywrapsat contains solution callback. Found [something](https://github.com/google/or-tools/blob/v7.0/ortools/constraint_solver/routing.h#L793) or #651

**Comment by thucnc** [comment]
@abduakhatov I can't find sample code for the solution callback so quite confused how to implement it. On the other hand, the code `solver.Add(num_stops*10 >= total_distance_per_vehicle) # 5stops*10 >= 50km` does not work, the reason is I can not compare CumulVar with a constant (int) value. I think the current approach for this problem does not work. So, I will check other aspects.
