### ISSUE TITLE
How to build the wheel package on ppc64le

### ISSUE THREAD

**Issue by xauthulei** [google/or-tools#1646]
Now , I am try to install the tensor2tensor on the ppc64le, however it is required ortools:
```
ERROR: Could not find a version that satisfies the requirement ortools (from mesh-tensorflow->tensor2tensor===1.13.4) (from versions: none)
ERROR: No matching distribution found for ortools (from mesh-tensorflow->tensor2tensor===1.13.4)
````
so, I am try  build the whl  on the ppc64le, Could I know what is right steps to build the whl?

**Comment by lperron** [comment]
Can you use docker ?

If yes, look at or-tools/tools/docker

there is a makefile and some docker files.
Adapt them, the command to build in the end (inside the hosted image) would
be make pypi_archive


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by xauthulei** [comment]
@lperron , Thanks for your suggestion, Meanwhile, Could I know how to build the `whl` using the  [setup.py ](https://github.com/google/or-tools/blob/stable/tools/setup.py) , linking this : `python setup.py bdist_wheel` ?

**Comment by lperron** [comment]
OR-Tools is a complex C++ code wrapped in python.
You can have a look at:

https://developers.google.com/optimization/install/python/source_linux
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
