### ISSUE TITLE
Force the solver to assign node i to vehicle j

### ISSUE THREAD

**Issue by amih77** [google/or-tools#1647]
Hello,

Still haven't found the right method to pre-assign node `i` with vehicle `j`. Say that I have nodes `[0, 1, 2, 3, 4, 5, 6]` and 2 vehicles `[0, 1]`. I want to pre-assign nodes` [0, 2, 4]` to `vehicle_0` and `[1, 3, 5]` to `vehicle_1`. For simplicity, assume that node #6 is assignable for either `vehicle_0` or `vehicle_1`. I've succeeded assigning `[0,..,5]` but not node 6. For my model, pre-assigned node is a hard constraint in the sense that a valid assignment is an assignment that contains all preassigned nodes and assigns them to the right vehicles. 

Solutions as in https://github.com/google/or-tools/issues/847 and https://github.com/google/or-tools/issues/1202 miss locations although full assignment is feasible.

**Comment by lperron** [comment]
I do not see the problem with this, except that you cannot use depot,
start and end nodes in your pre-assigned nodes.

index_0 = manager.NodeToIndex(0)
routing.VehicleVar(index_0).SetValues([0])

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by amih77** [comment]
I have a feasible problem with a set of 3 nodes `[0, 1, 2]`, and 2 vehicles. Running it without preassigned nodes yields the assignment `{'vehicle_1':[0, 1, 2]}` (so in particular, it will be feasible with preassigning any subset of nodes).
Now, running it with:
```
index_0 = self.manager.NodeToIndex(0)
self.routing.VehicleVar(index_0).SetValues([0])

index_1 = self.manager.NodeToIndex(1)
self.routing.VehicleVar(index_1).SetValues([1])
```
outputs:
`{'vehicle_0':[0], 'vehicle_1':[1]}`, with no node 2.

**Comment by lperron** [comment]
and you have no depot ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by amih77** [comment]
I do, but they are in indices `[3, 4, 5, 6]`.

**Comment by amih77** [comment]
Sorry - it was a bug on my part, I didn't sort the locations list in the right time, which caused a problem in the durations matrix. This method seems to work perfectly for me.
