### ISSUE TITLE
VRPTW - how to set different Time Window for different vehicle

### ISSUE THREAD

**Issue by AsiaLootus** [google/or-tools#1648]
Hi all,

I have a problem where the same task has different Time Window based on the vehicle is visiting it.
 
For example, if the task A is visited by the vehicle 1, it has a time window [a,b]; if the same task is visited by the vehicle 2, it has a time window [c,d].

Is this possible?
Thanks!

**Comment by lperron** [comment]
duplicate the nodes, add the copies in a disjunction. Fix the vehicle var
of each node, and assign different time windows to each node.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 16 oct. 2019 à 11:48, AsiaLootus <notifications@github.com> a
écrit :
