### ISSUE TITLE
C# Memory Leak IDisposable Not Implemented Properly

### ISSUE THREAD

**Issue by dannymyers** [google/or-tools#165]
When I try to call .Dispose() on the solver, I get the following exception:

> MethodAccessException was unhandled: C++ destructor does not have public access.

I believe the fix you did for #100 is needed in the C# swig file as well?

Here is the repro code:

```
using(var x = Solver.CreateSolver("X", "CBC_MIXED_INTEGER_PROGRAMMING"))
{
}
```

PS: Thank you for this library!

**Comment by lperron** [comment]
Yes, I just pushed the fix to github.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-03-16 20:47 GMT+01:00 dannymyers <notifications@github.com>:

**Comment by Mizux** [comment]
Could be related to https://github.com/swig/swig/issues/421
