### ISSUE TITLE
Build behavior:  Or-Tools in .Net Framework 4.7.2 builds but lacks the new APIs

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1651]
Hello,
Since we are still having some issues with  NertCore, we built OR-Tools 7.2 using .Net Framework 4.7.2 and the project builds and runs!
However, certain APIs are simply not present; for example SetPickDropPolicy, RoutingIndexMAnager.

Can that be? the project builds but 'hides' certain APIs due to .Net environment?

Guy

**Comment by lperron** [comment]
Note sure.
Please note that 7.4 supports 4.7.2.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
