### ISSUE TITLE
Could not load file or assembly 'Google.OrTools' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

### ISSUE THREAD

**Issue by pablojmp** [google/or-tools#1655]
This seems related to [https://github.com/google/or-tools/issues/1421](https://github.com/google/or-tools/issues/1421)

This happens on Windows 10 with Visual Studio 2019 and a web application targeting .NET Framework 4.6.2

I used sn.exe to check if the assembly had any strong name verification issues and i got this:
```
sn -v .\Google.OrTools.dll

Microsoft (R) .NET Framework Strong Name Utility Version 4.0.30319.0
Copyright (c) Microsoft Corporation. All rights reserved.

Failed to verify assembly -- Strong name validation failed.
```

**Comment by ranjithota** [comment]
> This seems related to #1421
> 
> This happens on Windows 10 with Visual Studio 2019 and a web application targeting .NET Framework 4.6.2
> 
> I used sn.exe to check if the assembly had any strong name verification issues and i got this:
> 
> ```
> sn -v .\Google.OrTools.dll
> 
> Microsoft (R) .NET Framework Strong Name Utility Version 4.0.30319.0
> Copyright (c) Microsoft Corporation. All rights reserved.
> 
> Failed to verify assembly -- Strong name validation failed.
> ```

I have tried X64 .Net 4.7.1 and 4.7.2 as well.

**Comment by lperron** [comment]
Duplicate
