### ISSUE TITLE
solver SetNumThreads and set_time_limit in python is not working

### ISSUE THREAD

**Issue by oneengineer** [google/or-tools#1656]
I create a CBC_MIXED_INTEGER_PROGRAMMING solver,
try to make it run fast in multiple-thread

```
k = solver.SetNumThreads(16)
print("SetNumThreads? ", k )
solver.set_time_limit(1000 * 60 * 3 )
solver.Solve()
```

It print out

```
SetNumThreads?  True
No match for threads - ? for list of commands
No match for 16 - ? for list of commands
```

From the cpu monitor, it seems it is not running in 16 threads. It has no difference from 1 thread.

The timelimit also doesn't work

**Comment by lperron** [comment]
Which OS?

**Comment by oneengineer** [comment]
I am using windows 10.
```
pip show ortools
Name: ortools
Version: 7.4.7247
Summary: Google OR-Tools python libraries and modules
Home-page: https://developers.google.com/optimization/
Author: Google Inc
Author-email: lperron@google.com
License: Apache 2.0
Location: ....\appdata\roaming\python\python37\site-packages
Requires: protobuf, six
Required-by:
```

**Comment by lperron** [comment]
Default compilation of CBC on windows does not enable parallelism. I have
no plan to fix this as parallelism gain is minimal at best.

Are you sure time limits are not working ? I checked and they applied.
Maybe the granularity is too large and the solver is waiting a long time
before checking it.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 21 oct. 2019 à 07:47, oneengineer <notifications@github.com> a
écrit :

**Comment by oneengineer** [comment]
My mistake, set_time_limit works fine.
BTW, does the linux version of CBC or other solver have enabled parallelism? Or I have to rebuild everything myself?

**Comment by lperron** [comment]
It does.

You can test performance there.

BTW, if your problem only contains integer or binary variables, I just
pushed on master a backend for the linear solver using our CP-SAT solver.
Just use SAT_INTEGER_PROGRAMMING, after rebuilding from sources.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 22 oct. 2019 à 11:16, oneengineer <notifications@github.com> a
écrit :

**Comment by Ez-Kassad** [comment]
Hi.
In the version 7.4.7247 
I’m not able to find SAT_INTEGER_PROGRAMMING in OptimizationProblemType for the java version.
Can you you help me pleaz? 
Thx

**Comment by lperron** [comment]
Strange, on master, it is present, and I do not remember changing it after
the release.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by gdowdy3** [comment]
Does the MacOSX version of CBC included with OR-Tools have parallelism enabled? Or do I have to build it from source to enable this feature?

**Comment by lperron** [comment]
It should work out of the box.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 2 juil. 2020 à 16:35, Garrett R Dowdy <notifications@github.com> a
écrit :
