### ISSUE TITLE
'module' object has no attribute 'RoutingIndexManager'

### ISSUE THREAD

**Issue by adhamenaya** [google/or-tools#1657]
I am using `or-tools 6.10.6025` and `python 3.7.0`, I am following the example in this link: https://developers.google.com/optimization/routing/tsp

But I got the following error:

`AttributeError: 'module' object has no attribute 'RoutingIndexManager'`
Could you please advise?

**Comment by stradivari96** [comment]
X-posted here: https://stackoverflow.com/questions/58502651/module-object-has-no-attribute-routingindexmanager
> Your version of ortools is too old. IndexManager is >= 7.0
