### ISSUE TITLE
Linear solver future plan: features across solvers, QP, cones, column generation

### ISSUE THREAD

**Issue by rlloretb** [google/or-tools#1659]
More than raising an issue to be fixed, I would like to ask the main developers, what do you have in mind for MILP in future releases.

1) I have seen that priority has been given recently to routing solver and CPSAT, which is very nice (I am using both). However, the interface for linear solvers seems to lack basic features, especially across solvers. Moreover, information is not clear in this regard: what can or cannot be done with each solver. Would it be possible to summarize solver features somewhere?

2) Also, Is there any chance OR-tools will eventually support quadratic optimization, second order cone and further interaction with solver during the optimization (i.e. column generation). I had asked about QP some months ago, the reply was on that there would be changes in protobuf.

3) CBC, the default solver. We know that the interface to that solver is inconvenient. Are there any talks with the CBC team on making it more compatible with or-tools?

**Comment by lperron** [comment]
Hi,

1) yes
2) It does, if you use the proto interface and compile with SCIP or Gurobi.
This is available in C++, Java, and Python.
3) I talk with the CBC team. I do not think they have any bandwidth to
change the API. I would assume their focus is the cbc binary.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
