### ISSUE TITLE
AttributeError: type object 'Solver' has no attribute 'GLPK_MIXED_INTEGER_PROGRAMMING'

### ISSUE THREAD

**Issue by hxd1011** [google/or-tools#166]
Hi, I am trying to run the example knapsack_mip.py and got this error.

Anyone can help?

Thank you !

**Comment by lperron** [comment]
Ah, I cannot distribute or-tools with GLPK included for licence reason.
Can you change GLPK to CBC ?

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-03-19 3:55 GMT+01:00 hxd1011 <notifications@github.com>:

**Comment by lperron** [comment]
I did change all python mip files to default to CBC instead of GLPK.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-03-19 18:48 GMT+01:00 Laurent Perron <lperron@google.com>:

**Comment by hxd1011** [comment]
CBC works very well.

Only GLPK not working, thanks for quick reply.

BTW, I have GLPK installed on my linux box (glpsol is in the PATH), it still cannot use it?
