### ISSUE TITLE
constraint build slow

### ISSUE THREAD

**Issue by chenxuanhanhao** [google/or-tools#1663]
obj_driver= solver.NumVar(-M,M,'obj_driver')
        solver.Add( obj_driver == solver.Sum(driver_weight[i]*dis_mat[i, j] * x[i, j] for i in range(m) for j in range(n)) )
        print('obj_driver built completed..' )    

i: hundreds
j: hundreds

took a long long time to build this constraint

any suggestions to improve the performance?

**Comment by lperron** [comment]
1) Use the non algebraic API
2) use the routing library :-)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by chenxuanhanhao** [comment]
Thx Perron
Can you be more specific?
Any specific examples?
A little bit overwhelmed~

**Comment by chenxuanhanhao** [comment]
Googled or-tools & non algebraic API, got nothing valuable.

Actually I'm solving a location model (c.f. p-median location model). Took 20+ minutes to build the following constraint, yet solved to OPTIMAL after pre-processing ^_^

solver.Add( obj_driver == solver.Sum(driver_weight[i]*dis_mat[i, j] * x[i, j] for i in range(m) for j in range(n)) )

**Comment by chenxuanhanhao** [comment]
Would the routing library be helpful to a location problem on CONSTRAINT BUILDING instead of SOLVING to OPTIMAL?

**Comment by lperron** [comment]
https://github.com/google/or-tools/blob/stable/ortools/linear_solver/samples/linear_programming_example.py
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by chenxuanhanhao** [comment]
Thx 

You mean building the constraint in the following way would accelerate the contraint-building process?

Thx. I shall try that.

    constraint0 = solver.Constraint(-solver.infinity(), 14)
    constraint0.SetCoefficient(x, 1)
    constraint0.SetCoefficient(y, 2)

**Comment by lperron** [comment]
Worth trying.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by chenxuanhanhao** [comment]
obj_driver= solver.NumVar(-M,M,'obj_driver')
#         solver.Add( obj_driver == solver.Sum(driver_weight[i]*dis_mat[i, j] * x[i, j] for i in range(m) for j in range(n)) )
        obj_driver_constraint = solver.Constraint(0, 0)
        obj_driver_constraint.SetCoefficient(obj_driver, -1)
        for i in range(m):
            if 1==i%100:
                print('driver: i ', i)
            for j in range(n):
                obj_driver_constraint.SetCoefficient(x[i,j], driver_weight[i]*dis_mat[i, j] )  
        print('obj_driver built completed..' )    


That should work faster?

Is there an elegant way to vectorize the two hundreds times hundreds for cycles of the python code?

**Comment by lperron** [comment]
Not using python  :-)

**Comment by chenxuanhanhao** [comment]
Python API is important for community growth ..
For instance, Tensorflow / Pytorch/ Keras ...

**Comment by chenxuanhanhao** [comment]
Vectorizing the two-fold for cycles would accelerate the Python program several orders of magnitude

**Comment by chenxuanhanhao** [comment]
import time
import numpy as np

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("Vectorized version: " , str(1000*(toc-tic)) + "ms")

c = 0
tic1 = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc1 = time.time()
print(c)
print("For loop version: " , str(1000*(toc1-tic1)) + "ms")



249801.55978809926
Vectorized version:  1.2989044189453125ms
249801.55978811116
For loop version:  1104.9799919128418ms

**Comment by lperron** [comment]
I welcome any contribution to support numpy in the linear solver, or on the
flow algorithms.
I do not have the time to do it.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by chenxuanhanhao** [comment]
Got.

My current issue  is on model BUILDING, instead of SOLVER / ALGORITHM.

**Comment by lperron** [comment]
Exactly, solving is in C++.
Building the model is in python, and is slow.
