### ISSUE TITLE
Dependence on previous nodes

### ISSUE THREAD

**Issue by murr999888** [google/or-tools#1667]
Please help.

The car at the beginning of the route has a maximum load and therefore develops a speed less than at the end of the route.

As the car moves along the route and the cargo is unloaded by customers, its weight decreases and it can move at a faster speed.

This behavior must be taken into account when determining the optimal route with time windows. The time of arrival at a particular point should depend on the number of route points visited by the car before this.

How to do it? # #

**Comment by lperron** [comment]
You can't.

**Comment by lperron** [comment]
The distance matrix is supposed to be constant.

**Comment by TeodoraBogdan** [comment]
Has this case been dealt with? Or the matrix must still be constant?

**Comment by lperron** [comment]
yes, I believe the code has been removed :-)
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mar. 13 sept. 2022 à 15:21, TeodoraBogdan ***@***.***> a
écrit :
