### ISSUE TITLE
Question: All things being equal, random solution

### ISSUE THREAD

**Issue by joegaudet** [google/or-tools#1671]
Hey Guys,

As always, great work on this.

I was wondering, in a situation where there are N equally optimal solutions, is there a way to grab a random one each time?

What I'm currently observing is that the solution selected is always the same, I would assume there's some way to set a seed or some such that would result in a random selection.

.joe

**Comment by lperron** [comment]
Which solver? If you are using the CP-SAT solver, there are some
randomization parameters, but their effect is limited.

You can also try hinting random partial assignments, but this would also be
limited.

Le dim. 27 oct. 2019 à 20:36, Joe Gaudet <notifications@github.com> a
écrit :

**Comment by joegaudet** [comment]
@lperron using the CP-SAT solver.

**Comment by stradivari96** [comment]
Related issue: https://github.com/google/or-tools/issues/1590

**Comment by joegaudet** [comment]
@lperron I'm doing a variant of the nurse scheduling problem, so it's a bit unclear how I could hint at a solution. 

I could randomly hint one of the assignment booleans to be true, but it might not actually be a valid assignment.

**Comment by lperron** [comment]
Yes, the solver will try to follow as much as possible, then slowly revert
to standard vsids strategy.

This is the 'best' solution achievable currently.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 28 oct. 2019 à 17:15, Joe Gaudet <notifications@github.com> a
écrit :

**Comment by joegaudet** [comment]
It seems to have worked well, thanks!
