### ISSUE TITLE
Cap total driving time, excluding Slack time to the 1st Node

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1674]
Hello,
In a scenario with time-windows, the Solver may have certain vehicles visit their first Node with Slack time -  when the Node's earliest visit time comes later than the net driving time from the start point to that Node.

I wish to **cap the total driving time per vehicle, but exclude Slack time to the first Node**, since the driver is not actually driving during that Slack. 
However, the time between later Nodes should include the Slack, as the driver is 'on the road'.

Bad options:
- Capping the "time" dimension will include Slacks, including Slack to the first Node.
- Capping over a dedicated dimension "net_time" with forced Slack=0 will not include the Slack when traveling between later Nodes.

Can I just get rid of the Slack to the first Node?

Thx

**Comment by routemegood** [comment]
You could potentially achieve this with a custom constraint, where you take the difference between the end and start times, subtract the slack variable to the first node and constrain that instead. Something along the lines of:

```
routing_model.solver().Add(time_dimension.CumulVar(routing_model.End(vehicle)) - time_dimension.CumulVar(routing_model.Start(vehicle)) - time_dimension.SlackVar(routing_model.Start(vehicle)) <= total_driving_time)
```
I think there is a SlackVar for the starting nodes, although I could be wrong.

Hope this helps

**Comment by GuyBenhaim** [comment]
Thanks!
I will check and report if this works.
