### ISSUE TITLE
Your docs contain Nazi Symbolism

### ISSUE THREAD

**Issue by thecarlmartin** [google/or-tools#1675]
Hi everyone, 

I love the tool, but someone messed with your docs. Check for example the page on the Domain class: https://github.com/google/or-tools/blob/stable/docs/python/ortools/util/sorted_interval_list.html
At the bottom of the page, the swastika symbol was inserted (line 772). I think it would be appropriate to remove it.
Best,

Carl

**Comment by stradivari96** [comment]
Looks like it comes from pdoc https://github.com/pdoc3/pdoc/issues/ 87

**Comment by lperron** [comment]
Fixed.

Thanks

**Comment by Mizux** [comment]
switched back to `pdoc` instead of using `pdoc3`

ref: https://github.com/mitmproxy/pdoc?tab=readme-ov-file#pdoc-vs-pdoc3
