### ISSUE TITLE
Rounding with no warnings when using BoolVar (and probably IntVar) in a linear context

### ISSUE THREAD

**Issue by mclegrand** [google/or-tools#168]
Hi, 

I tried to solve problem which was originally in an integer setting, in a linear continuous settings, assuming that BoolVars would be just treated as variables in [0,1] instead of {0;1}. Everything compiled and executed fine and fast. The problem was that the solution_value() returned by all variables had been silently rounded, which I only found after a long investigation on why some constraints were not satisfied (most of my constraints were satisfied, and it was a constraint that I prettyprinted as "(lb=0) <= (coeff=1)_(value=1) + (coeff=1)_(value=1) <= (ub=1)"  after a Solve() call (and I checked with gdb that there were no other variables involved in the constraints) that completely puzzled me; no matter whether GLOP_LINEAR_PROGRAMMING or GLPK_LINEAR_PROGRAMMING was used). 

It was only when I tried NumVars that I realized that the offending constraints were in fact round(0.5)+round(0.5) ...

It would be nice to either have a warning when using Bool or Int in a linear context and/or treat them as NumVars without rounding

Thanks!

**Comment by lperron** [comment]
We have added unrounded_solution_value().

I agree with the warning, but it cannot be too verbose.
