### ISSUE TITLE
CP-SAT solver inner checks and kNoIntervalVariable property

### ISSUE THREAD

**Issue by bendeguz-modli** [google/or-tools#1680]
Hello,

I'm working on a 2D bin packing problem with CP-SAT solver on Windows with C++, version 7.3 and I have two questions/problems.

The first one is quite general: is there a way to catch the inner check fails of the solver? I'm developing a module with c++ which communicates with a backend through exit codes, but when a check fails, the program just shuts down silently and no feedback reaches the backend. Can I catch these somehow to give proper response that something went wrong?

The second one is more concrete: sometimes I got a failed check with the kNoIntervalVariable property (-1 v -1). What does this variable represents? I can't figure out what might be the problem. I use 2DNoOverlap constraints with the workaround mentioned in [#1477](https://github.com/google/or-tools/issues/1477) to handle the is_present bool variables.

Any help would be appreciated!
Thanks!

**Comment by lperron** [comment]
Actually, we should check them in the model validator first.

If you have a check failed during construction, please send us some some that exhibits the problem.
