### ISSUE TITLE
Solution Hinting sample code when constrain/resouces changes

### ISSUE THREAD

**Issue by YooTimmy** [google/or-tools#1681]
Hello All,

I tried to search for this but did not find a good reference yet. Appreciated if anyone could help to give some pointers.

I wanted to use solution the "solution hinting" method to generate an updated schedule when the resources/constrains changes. I found some code provided by @stradivari96 (Thank you for that)that does the hinting, which I think it will store the variable values from previous optimal solution.
```
    model.Proto().solution_hint.Clear()
    # for solver to remember the previous optimal solution.
    for i in range(len(model.Proto().variables)):
        model.Proto().solution_hint.vars.append(i)
        model.Proto().solution_hint.values.append(solver.ResponseProto().solution[i])
```
However, I still could not figure out how to use it for next solver when resources changed. For instance, say if 1 machine is faulty and I have to remove it from the available list. 
However for the variables it saves for hinting previously, the variables names are like "interval_j3_t0_a0", where there are no direct information for machines. 
The machine information is embedded inside the variables (based on what I understand), so how can we tell the solver that "machine 1 is not working anymore, please use other machines to generate a schedule while trying to make minimum changes to the current schedule as much as possible"?

Some sample code would be greatly helpful. Thank you for your help in advance!

**Comment by stradivari96** [comment]
You don't have to hint all variables, save the previous solution in a way that is easy to work with (for example, Dict[machine, task] -> value) and use the `model.AddHint(var, value)` after filtering the variables of the new model

**Comment by lperron** [comment]
https://github.com/google/or-tools/blob/master/ortools/sat/doc/model.md

**Comment by YooTimmy** [comment]
Thank you for your comments, I will have a try! @stradivari96
