### ISSUE TITLE
Pickup delivery with vehicle capacity 

### ISSUE THREAD

**Issue by kzorina** [google/or-tools#1682]
Hello. I want to solve task of VRP when I have multiple cars with capacity and I want to transfer items inside system. So pick up items from some points and drop them somewhere. I tried to do this as pickup delivery problem with "demand"  = ```amount_of_items``` on point where I should drop and ```-amount_of_items ``` on pick-up point. But it seems that it is not converging. 

Also I want to be able to visit one pick-up point twice with same car. Is it possible?

**Comment by abduakhatov** [comment]
1. Could you please clarify the problem, coz the solution seems to be [this](https://developers.google.com/optimization/routing/pickup_delivery)
2. You  can create a dummy node (ex: node A and A') and 
   a) #1202
   b) by [Muzux](https://github.com/google/or-tools/issues/334#issuecomment-484781754)
   c) https://www.bountysource.com/issues/73870858-specific-nodes-visited-by-specific-vehicles
   d) not sure regarding this one:

https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/routing.h#L618

**Comment by kzorina** [comment]
> 1. Could you please clarify the problem, coz the solution seems to be [this](https://developers.google.com/optimization/routing/pickup_delivery)

So the problem is that let's say I have two cars (capacity = 6), depo and 5 points. Then I have list: pickup point - delivery point - amount like this :
0 - 4 - 10
1 - 3 - 5
1 - 4 - 3
1 - 5 - 3
2 - 3 - 1
4 - 5 - 3

So basically I need to pick up from same station few times (maybe more than two, maybe all fit in one car but different destinations) and also drop to stations few times. Everything considering capacity of a car.

> 2. You  can create a dummy node (ex: node A and A') and
>    a) #1202
>    b) by [Mizux](https://github.com/google/or-tools/issues/334#issuecomment-484781754)
>    c) https://www.bountysource.com/issues/73870858-specific-nodes-visited-by-specific-vehicles
>    d) not sure regarding this one:
> 
> https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/routing.h#L618
 Thank you, will look into that!

**Comment by abduakhatov** [comment]
> The problem is that let's say I have two cars (capacity = 6), depo and 5 points. Then I have list: pickup point - delivery point - amount :
0 - 4 - 10
1 - 3 - 5
1 - 4 - 3
1 - 5 - 3
2 - 3 - 1
4 - 5 - 3
>
>So basically I need to pick up from same station few times (maybe more than two, maybe all fit in one car but different destinations) and also drop to stations few times. Everything considering capacity of a car.

So this is pdp problem, after you add a dummy nodes, you can surely use those as pick and delivery nodes. Regarding the capacity, try to divide the capacity into smaller values, which could satisfy the capacity of a vehicle (ex: 10 could be divided into 5:5 two nodes, here two dummy nodes, so that the car returns and picks rest). Basically dummy node and [pdp](https://developers.google.com/optimization/routing/pickup_delivery) do the job

**Comment by kzorina** [comment]
Good, I will try it. Thank you. I was trying pickup delivery before (without dummy nodes) and it was not converging.. But I will try with this trick now.

**Comment by kzorina** [comment]
Ok, sorry, I missed important part in my example.  Car should be able to visit few pickup places before drop. Or pick at one place and drop at few nodes. So let's say I have depo and then 4 points close to each other. And I have to pick from one of those 4 points and drop to others. If depo is far - it is better to visit with one car and move twice to the pickup point than use second car. 

In other terms:
distance matrix: (not correct numbers, just to show idea)

| 0  | 1 | 2 | 3 | 4 |
| --- | --- | --- | --- | --- |
| 0 | 100 | 110 | 110 | 120 |
| 100 | 0 | 1 | 1 | 1 |
| 110 | 1 | 0 | 1 | 1 |
| 110 | 1 | 1 | 0 | 1 |
| 120 | 1 | 1 | 1 | 0 |

demands = [0, -9, 3, 3, 3]
pickups_deliveries = [[1,2],[1,3],[1,4]]
num_vehicles = 2
capacities = [6,6]
depot = 0

Best route shoul be something like 0 -> 1 (pick 6) -> 2 ->3 -> 1 (pick 3) -> 4 -> 0

I am not sure, how to setup such problem..

**Comment by abduakhatov** [comment]
@kzorina I am not sure regarding which strategy to reduce the number of cars.

> And I have to pick from one of those 4 points and drop to others.

#968 is what you need, as these 4 points become alternative pickup points.
For the rest, pdp and dummy nodes should be the solution, btw try to play with strategies for the solver

**Comment by kzorina** [comment]
Ok, thanks for help
