### ISSUE TITLE
CP SAT Objective Channeling

### ISSUE THREAD

**Issue by laventnc** [google/or-tools#1684]
### Summary ###

Inability to model the relationship between my objective function and decision variables.

A simplified version is as follows:
you have a basket of stocks you are invested in. The goal is to optimize your allocations according to descriptive statistics calculated on the portfolio's return stream. 

This last part is where I am getting stuck. **While the objective function is a simple linear combination of statistics, the data used to calculate it is a product of domain-logic applied to the decision variables (not the variables themselves)**. For examples of the descriptive statistics, let's go with [Sharpe Ratio](https://en.wikipedia.org/wiki/Sharpe_ratio), [Diversification Ratio](https://seekingalpha.com/article/1033601-modern-portfolio-theory-2_0-the-most-diversified-portfolio), and [Maximum Drawdown](https://www.investopedia.com/terms/m/maximum-drawdown-mdd.asp). 

### Background ###
I initially tried using *MathNet.Numerics.Optimization*, and quickly moved to *Microsoft.SolverFoundation*. Long story short, I wasn't able to overcome this same hurdle within the confines of their OML language queries.

After reading through the Google OR-Tools documentation, some examples, and various blog posts... I believe that I need to somehow channel my objective function, similar to [Constraint Channeling](https://developers.google.com/optimization/cp/channeling).

### Current Stage ###
Simplified Example:

```c#
using Google.OrTools.Sat;

CpModel model = new CpModel();

IntVar[] stockWeights = _StockList.Select(x => model.NewIntVar(0, 100, x.Symbol)).ToArray();

// example constraint, must be fully invested
model.Add(LinearExpr.Sum(stockWeights) == 100);

???
calculate the total portfolio's return stream
calculate descriptive statistics x, y and z
???

model.Maximize(x * y - z);

```
To be clear I don't need help calculating the portfolio's return stream, or statistics on it. What I can't figure out is how to allow the model to interface with this domain-specific logic.

Is there a way to feed `IntVar[] stockWeights` to a static function, and thereby produce the inputs needed in the objective function? I would prefer to avoid simply defining numerous intermediary variables as this would be a nightmare in my real environment. 

Any direction you could provide or comments would be greatly appreciated as I am starting to go crazy bouncing around libraries.

**Comment by lperron** [comment]
Short answer, you cannot use a black box function inside the solver. You
will need to create all the intermediate variables.

You can also look at the allowed assignment constraint.

**Comment by laventnc** [comment]
Unless I'm missing something, creating intermediate variables wouldn't be possible given that I need to calculate squared differences for volatility...

I understand why the constraints have to be linear, but if the variables themselves can't leverage non-linear functions then I don't see how I can use SAT / ConstraintSolver

**Comment by laventnc** [comment]
specifically, I don't see how I can get back to an IntVar from LinearExpr. e.g.,

```
IntVar[] Rp = new IntVar[_Returns.RowCount];
for (int i = 0; i < _Returns.RowCount; i++)
{
    Rp[i] = LinearExpr.ScalProd(cash.Concat(futures), _Returns.Row(i).AsEnumerable());
}
```

Rp[i] would need to be some kind of IntVar / Constant... as it works now I am forced to continue using LinearExpr, which drastically limits the tools available

**Comment by lperron** [comment]
You can have product of variables using the AddProductEquality
