### ISSUE TITLE
More control over local search operators during solve

### ISSUE THREAD

**Issue by routemegood** [google/or-tools#1687]
Hi team, I was wondering if it's possible to tell the solver to switch to a different local search operator from a callback during the solve. I'm using the routing library to solve a complex PDP with optional shipments, and some of my problems have solutions where all shipments can be served, but the solver struggles to find them.
This is primarily because it starts with a solution that doesn't serve all shipments, and then tries to improve that with various LS operators that don't perform insertions. It gets stuck in these operators, performing many iterations without finding better solutions, where it should switch to another operator (like the insertion operators).
I would like to be able to use an AtSolution callback to detect that the solver has not found a better solution after a certain number of iterations or amount of time and make a suggestion that it tries using a particular operator. Is this already possible, and if not, could it be possible in the near future?
Thanks for your help.

**Comment by lperron** [comment]
You can parametrize which operators are used or not.
The rest is beyond your control.
