### ISSUE TITLE
Routing Problem 30 sites visit maximum travel time is 10 hours a day each day vehicle goes back to depot atleast 30 minutes stop at one site. 

### ISSUE THREAD

**Issue by jamienjoroge** [google/or-tools#1689]
I am a beginner with or-tools I am trying to solve a rather specific problem whereby I have one vehicle that does delivery to many sites within the month. maximum working day is 10 Hours and a stop at the site is of maximum 30 minutes each day after the 10 hours the vehicle goes back to depot and starts again eliminating the already visited sites from the matrix. please help

**Comment by lperron** [comment]
Please start reading the examples, the doc and ask for specific questions.
