### ISSUE TITLE
VRPTW but add 2 minutes each stop 

### ISSUE THREAD

**Issue by maxrho** [google/or-tools#1690]
Hello!

Please advice, my case is that we are doing food delivery.

```
I have X cars (most often around 4-6)

I start at resturant.
I need to be back at resturant after T  (atm this is set to 22 minutes.)

I have Y ammount of orders to deliver.

Each time my drivers stop, it takes Z minutes to give customer food.

Z is approx 2 minutes.
```

How do I add Z to VRPTW-calculations?

My VRPTW works flawlessly but no time is added for the stops...

What i've tried:

Searchning for ways to implement FixedDurationIntervalVar and searching github for this - can't get this to work properly except when it comes to loading at NODE, but i want 2 min extra at each STOP only.

Using breaktime - this seems like the wrong way to solve this and I've not had any luck.

Using waittime to solve this - this also seems wrong since it's supposed to solve to another problem.

Any help, tips or pointers are appriciated!

BR,
Max

**Comment by lperron** [comment]
Just add 2 minutes to each time transition.

**Comment by maxrho** [comment]
Don't really understand how I would do that, since I'm sending a matrix of cords and getting a routing back, but I guess I'll continue trying.

**Comment by lperron** [comment]
At some point, you have a method that converts 2 sets of coordinates into a
time to travel.
Add 2 minutes there.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by maxrho** [comment]
As I understand it, I'm sending a set of coordinates and restrictions, and then i'm getting several routes back.

I don't convert 2 sets of coords myself, the Distance matrix api caluclulates 20 sets of coords into 5 routes.

I'm trying to set the restrictions so that it waits, but maybe I'm just doing everything wrong :s
