### ISSUE TITLE
No AddLessOrEqual in C# model

### ISSUE THREAD

**Issue by Landcross** [google/or-tools#1691]
I'm trying to build something with Google OR-Tools and I'm taking (a lot) of inspiration from: https://github.com/google/or-tools/blob/stable/examples/cpp/jobshop_sat.cc

The difference is that I'm working in C#. In the C++ JobShop example linked above, model.AddLessOrEqual is used a few times, but I can't find that method in the C# interface. Is it missing? Should I use something else?

Thanks!

**Comment by lperron** [comment]
Model.Add(expr1 <= expr2)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by stradivari96** [comment]
There are a lot of C# examples BTW:
* https://github.com/google/or-tools/tree/stable/examples/dotnet
* https://github.com/google/or-tools/tree/stable/examples/contrib

**Comment by Landcross** [comment]
_Facepalm_. I was so reading into the various different methods that are available that I completely forgot about the general Add... Thanks for the heads-up and excuse me for the stupid question.
