### ISSUE TITLE
TDTSP with Google OR-Tools

### ISSUE THREAD

**Issue by bouldrini** [google/or-tools#1695]
Hey folks,

im wondering if there is a way to solve a time dependent travelling salesman problem (TDTSP - 
 varying costs between nodes) using the Google OR-Tools.

- If there is a way, it would be nice if you point me to the right direction (I couldnt find anything related in the TSP, VRP taylored 'Routing' Section)

- If there is a way using more abstract algorithms that are not taylored to the TSP, VRP topic it would be nice if your point me to documents that explain the transfer.

- If this is not the correct place to ask this question, please direct me to the right place. 

Best regards and a good day for you folks,
bouldrini

**Comment by lperron** [comment]
Short answer:

this functionality in the routing library is not mature enough. So I cannot help you.
