### ISSUE TITLE
How to use the first solution strategy as an initial solution for a local search metaheuristic?

### ISSUE THREAD

**Issue by Adnanay** [google/or-tools#1697]
Hi,
my issue is very similar to the issues  #455 and #1297 
1- i wanted to know if there is any update about that issue, because i'm trying to work on my Bachelor thesis with OR-Tools and i've landed on the same question "How to use the first solution strategy as an initial solution for a local search metaheuristic?"
I'm trying to solve some instances of VRPTW from [VRP-REP](http://www.vrp-rep.org/variants/item/vrptw.html)
I've tried it the same way as here:
`search_parameters = pywrapcp.DefaultRoutingSearchParameters()
search_parameters.first_solution_strategy   = (routing_enums_pb2.FirstSolutionStrategy.LOCAL_CHEAPEST_INSERTION)
search_parameters.local_search_metaheuristic = (routing_enums_pb2.LocalSearchMetaheuristic.GUIDED_LOCAL_SEARCH)
search_parameters.time_limit.seconds = 60`
but the value of the first solution strategy is getting worse and worse as long as i let the solver run!!!
I've tried all combinations between the first_solution_strategy and the local_search_metaheuristic and every time i got a good solution from the first solution strategy it gets worse when i try to improve it unsing a local search strategy (by worse i mean the solution is increasing while it should be decreasing, because of the method `routing.AddVariableMinimizedByFinalizer()` ).

2- is there any other resources where i can find more instances with the optimal solution so i can compare my solution to the optimal one.

Any help will be much appreciated

**Comment by lperron** [comment]
I cannot comment on 2.

On 1, the first solution strategy seems to find a good solution, or at least one in a local minimum, and fails to find an improving one. The cost going up is normal for GLS, as it penalizes frequent features in order to try to escape this local minimum

**Comment by CervEdin** [comment]
2. Checkout benchmarks like the Solomon vrp instances?
