### ISSUE TITLE
Manually setting solver parameters 

### ISSUE THREAD

**Issue by rautmadhura4** [google/or-tools#1698]
Currently in Java, only few parameters like MIP_GAP, INCREMENTALITY, SCALING can be set using methods exposed. Is there any way to be able to set other cbc parameters? Please help.

**Comment by lperron** [comment]
I do not know how to do it.

For all the other solvers, I can pass a string to specify specific
parameters. I have not found an API to do it with CBC.

I welcome contributions to do it.

But this is currently not supported.

Le ven. 8 nov. 2019 à 01:23, rautmadhura4 <notifications@github.com> a
écrit :
