### ISSUE TITLE
Cpu usage

### ISSUE THREAD

**Issue by stradivari96** [google/or-tools#1699]
Quick question, sorry if it has been asked before:

If I set num_search_workers=16 I see that it only uses 8 cores to find the first solution and then launches the remaining ones for LNS after that.
Is this correct?

**Comment by lperron** [comment]
Actually only 5 until a solution is found.
We will improve that in the future, but this is not the highest priority.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by stradivari96** [comment]
As always, thanks for your help!
