### ISSUE TITLE
Capabilities of Or tools

### ISSUE THREAD

**Issue by majesticnavann** [google/or-tools#1700]
Hi,
I have 60,000 locations in a 300sq mile area. Is or tools capable of solving a vrp  solution with 100 vechicles? 

Thanks for you help!

**Comment by lperron** [comment]
Without geographical or time based decomposition, no.

Le ven. 8 nov. 2019 à 19:06, majesticnavann <notifications@github.com> a
écrit :

**Comment by majesticnavann** [comment]
Sorry i do have lat and long for each point, is this possible?

**Comment by CervEdin** [comment]
The distance matrix of 60,000x60,000 floats alone is 115gb

**Comment by majesticnavann** [comment]
Thanks, not a good idea then, i will cluster down first! Best wishes. My VOG-L09. On O2.-------- Original Message --------Subject: Re: [google/or-tools] Capabilities of Or tools (#1700)From: CervEdin <notifications@github.com>To: google/or-tools <or-tools@noreply.github.com>CC: majesticnavann <thomaskelly75@gmail.com>,Author <author@noreply.github.com>The distance matrix of 60,000x60,000 floats alone is 115gb

**Comment by CervEdin** [comment]
It's a huge VRP. Try techniques to reduce the problem.

Combine locations together using clustering or split the problem up, looking only at certain regions or certain time
