### ISSUE TITLE
How do I set integer feasibility tolerance for CBC?

### ISSUE THREAD

**Issue by yd2102** [google/or-tools#1701]
Hi, I am using OR-Tools for my mixed-integer programming problem and I have a need to set the integer feasibility tolerance that the CBC solver uses. I am using the Python interface OR-Tools exposes. How do I set this parameter through the Python interface? Thanks!

**Comment by Mizux** [comment]
here https://github.com/google/or-tools/blob/stable/ortools/linear_solver/cbc_interface.cc you can see all parameters of CBC binded by the OR-Tools linear solver interface.

I would say, it is not binded see:
https://github.com/google/or-tools/blob/46173008fdb15dae1dca0e8fa42a21ed6190b6e4/ortools/linear_solver/cbc_interface.cc#L506-L512

contrary to gurobi wrapper:
https://github.com/google/or-tools/blob/46173008fdb15dae1dca0e8fa42a21ed6190b6e4/ortools/linear_solver/gurobi_interface.cc#L591-L602

or SCIP
https://github.com/google/or-tools/blob/46173008fdb15dae1dca0e8fa42a21ed6190b6e4/ortools/linear_solver/scip_interface.cc#L799-L816

**Comment by lperron** [comment]
CBC API is catastrophic, and I do not want to spend time on it.
I welcome contribution is somebody knows how to do it.
