### ISSUE TITLE
Cannot install OR-Tools v7.4 under Windows 10 with python 3.8.0 64-bit

### ISSUE THREAD

**Issue by pythonaddict** [google/or-tools#1702]
I have:

- python 3.8.0 64-bit
- Windows 10 64-bit
- pip 19.3.1

When I try to install latest ortools (v7.4) with the following command in cmd:

`pip install ortools`

I get the following error:

> ERROR: Could not find a version that satisfies the requirement ortools (from versions: none)
> ERROR: No matching distribution found for ortools

**Comment by lperron** [comment]
Already answered, should be next release.
