### ISSUE TITLE
AddMax/MinEquality constraint not working with OnlyEnforceIf

### ISSUE THREAD

**Issue by eigen-carmona** [google/or-tools#1703]
I'm using the SAT-Solver in python and I've come across some odd behavior. There seems to be a bug with the AddMaxEquality constraint when it is used together the method OnlyEnforceIf taking a BoolVar as input.

Here's a brief example of the problem:

`from ortools.sat.python import cp_model`
`model = cp_model.CpModel()`
`solver = cp_model.CpSolver()`

`a = model.NewIntVar(0,15, 'a')`
`b = model.NewIntVar(0,15, 'b')`
`c = model.NewIntVar(0,15, 'c')`
`d = model.NewIntVar(0,15, 'd')`
`e = model.NewBoolVar('e')`

`model.AddMaxEquality(d, [a,b,c]).OnlyEnforceIf(e)`

`solver.Solve(model)`

As a result, I get `MODEL_INVALID`

However, with the following instead: `model.AddMaxEquality(d, [a,b,c]).OnlyEnforceIf(1)` the result is `FEASIBLE`.

Furthermore, I'm using ortools version 7.4.7247.

**Comment by stradivari96** [comment]
From the last CHANGELOG:
> CP-SAT: The solver now checks for constraints that do not support enforcement literals (they are the Boolean literals passed to OnlyEnforceIf() methods). The model checker will return an error before solving if such a constraint has an enforcement literal.

So yeah, it is not accepted anymore. I guess you can declare a intermediate var:
```
tmp = model.NewIntVar(0,15, '')
model.AddMaxEquality(tmp, [a,b,c])

model.Add(d == tmp).OnlyEnforceIf(e)
```

PS: `.OnlyEnforceIf(1)` works because it is removed during presolve

**Comment by eigen-carmona** [comment]
I reviewed the documentation and found out that the `OnlyEnforceIf` method is sepcified to work with `BoolAnd`, `BoolOr` and "linear constraints". I'm guessing `AddMaxEquality` and `AddMinEquality` do not fall into any of these categories...
I've found a workaround for my need, but it would make some useful feature for the `OnlyEnforceIf` method to also work for the aforementioned constraints.

**Comment by lperron** [comment]
Exactly.

Thanks

**Comment by sagittaros** [comment]
I had the same issue (ie. MODEL_INVALID) but for `AddCircuit`.
Mine is a job-shop problem where some machines are not used, causing AddCircuit to fail with the status `INFEASIBLE`.

This is how I fixed it:
```python
is_used = model.NewBoolVar("")
model.Add(sum(machine_presences) > 0).OnlyEnforceIf(is_used)
model.Add(sum(machine_presences) == 0).OnlyEnforceIf(is_used.Not())
arcs.append([0, 0, is_used.Not()]) # << this is key
```

**Comment by lperron** [comment]
As documented, OnlyEnforceIf only works on BoolOr, BoolAnd, and Linear
equations.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le dim. 26 avr. 2020 à 04:29, Felix Tioh <notifications@github.com> a
écrit :

**Comment by evandrix** [comment]
`OnlyEnforceIf` doesn't work with `AddAllowedAssignments` :(

i wanted to specify a constraint to one fixed list of literal value pairs for `[x,y]`, if a certain boolean is true, and to another fixed list of literal value pairs for `[x,y]` otherwise.

Is there a way to do so?

**Comment by stradivari96** [comment]
Maybe something like this?

```python
model = cp_model.CpModel()
x = model.NewIntVar(0, 10, "x")
y = model.NewIntVar(0, 10, "y")

boolean = model.NewBoolVar("")
a1 = model.NewBoolVar("a1")
a2 = model.NewBoolVar("a2")
b1 = model.NewBoolVar("b1")
b2 = model.NewBoolVar("b2")

model.AddBoolOr([a1, a2]).OnlyEnforceIf(boolean)
model.AddBoolOr([b1, b2]).OnlyEnforceIf(boolean.Not())

model.Add(x == 1).OnlyEnforceIf(a1)
model.Add(y == 1).OnlyEnforceIf(a1)

model.Add(x == 2).OnlyEnforceIf(a2)
model.Add(y == 2).OnlyEnforceIf(a2)
```

**Comment by evandrix** [comment]
Ok I see, so I have to list it out line-by-line

I was just wondering whether there was a concise way to write it e.g. `AddAllowedAssignments` allows me to specify a single list in one line

**Comment by lperron** [comment]
As documented, OnlyEnforceIf only works on bool_or, bool_and, and linear
constraints.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by eyaler** [comment]
I am not getting an error when trying to apply OnlyEnforceIf on AddAllowedAssignments and the solver fails silently

**Comment by lperron** [comment]
It does not fail silently. It returns a model_invalid status.
