### ISSUE TITLE
OS X linking

### ISSUE THREAD

**Issue by cristiulian** [google/or-tools#1704]
I have a question, compared to the windows prebuilt binaries (which consist on one big static .lib),  I notice that the os x prebuilt ones contain a whole bunch of dynamic libs, static ones and .la files.
Any thoughts and guidelines about how should I link my app to or-tools on os x?
I'm using QT on both windows and os x, and I'm interested on using the cbc mixed integer linear solver.

**Comment by lperron** [comment]
You need to link with all libraries.
You can look at the makefiles to see what to include and in which order.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le sam. 9 nov. 2019 à 20:57, cristiulian <notifications@github.com> a
écrit :
