### ISSUE TITLE
CBC Unknown solver status crashes java call library

### ISSUE THREAD

**Issue by warielon** [google/or-tools#1710]
Sometimes when I try to solve a MIP problem with CBC, the c++ library crashes my java program.
I have the following error : 

> F1109 15:34:00.706626 30493 cbc_interface.cc:424] Unknown solver status! Secondary status: 2
> *** Check failure stack trace: ***

I can't even handle an exception and it crashes totally my java program.
Can you help me at least to catch the error in Java so I can relaunch the solver with other params please ?

I am running or-tools 7.3.7083 with cbc solver 3.10.3 under ubuntu 18.40

Thanks,
Ariel

**Comment by warielon** [comment]
error raised from https://153.96.46.203/philipps/or-tools/blob/836e75ad484988cc72a25521e6e226143e358a95/ortools/linear_solver/cbc_interface.cc

but I am not able to catch it !

> switch (tmp_status) {
>     case 0:
>       // Order of tests counts; if model.isContinuousUnbounded() returns true,
>       // then so does model.isProvenInfeasible()!
>       if (model.isProvenOptimal()) {
>         result_status_ = MPSolver::OPTIMAL;
>       } else if (model.isContinuousUnbounded()) {
>         result_status_ = MPSolver::UNBOUNDED;
>       } else if (model.isProvenInfeasible()) {
>         result_status_ = MPSolver::INFEASIBLE;
>       } else {
>         LOG(FATAL) << "Unknown solver status! Secondary status: "
>                    << model.secondaryStatus();
>       }
>       break;
>   

```

**Comment by lperron** [comment]
Thanks. Fixed on master.

**Comment by warielon** [comment]
Thanks :)
