### ISSUE TITLE
С# Not found CloseVisitTypes() AddHardTypeIncompatibility

### ISSUE THREAD

**Issue by murr999888** [google/or-tools#1711]
**C# 
.NET Framework 4.6.1
OrTools 7.4.7247 (or-tools_VisualStudio2017-64bit_v7.3.7083)
CVRPTW**

I am trying to solve the following problem:
only one of the node in the list A, B, C, D can visit the vehicle.

If the route passes through node A, then it cannot pass through nodes B, C, D.
If the route passes through node B, then it cannot pass through nodes A, C, D.
Etc.

I tried to assign different types of visits to the nodes. I found the SetVisitType function in c #, however I did not find the AddHardTypeIncompatibility, CloseVisitTypes, which are present in the library sources.

> void SetVisitType(int64 index, int type);
  int GetVisitType(int64 index) const;
  /// This function should be called once all node visit types have been set and
  /// prior to adding any incompatibilities/requirements.
  // TODO(user): Reconsider the logic and potentially remove the need to
  /// "close" types.
  void CloseVisitTypes();
  int GetNumberOfVisitTypes() const { return num_visit_types_; }
  /// Incompatibilities:
  /// Two nodes with "hard" incompatible types cannot share the same route at
  /// all, while with a "temporal" incompatibility they can't be on the same
  /// route at the same time.
  void AddHardTypeIncompatibility(int type1, int type2);
  void AddTemporalTypeIncompatibility(int type1, int type2);

It's bug?

**Comment by murr999888** [comment]
I understood why I can not find these functions. But will they still be implemented in the near future?

[https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/csharp/routing.i](url)

> // Ignored:
%ignore RoutingModel::AddDimensionDependentDimensionWithVehicleCapacity;
%ignore RoutingModel::AddHardTypeIncompatibility;
%ignore RoutingModel::AddMatrixDimension(
    std::vector<std::vector<int64> > values,
    int64 capacity,
    bool fix_start_cumul_to_zero,
    const std::string& name);
%ignore RoutingModel::AddSameVehicleRequiredTypeAlternatives;
%ignore RoutingModel::AddTemporalRequiredTypeAlternatives;
%ignore RoutingModel::AddTemporalTypeIncompatibility;
%ignore RoutingModel::CloseVisitTypes;
%ignore RoutingModel::GetAllDimensionNames;
%ignore RoutingModel::GetDeliveryIndexPairs;
%ignore RoutingModel::GetDimensions;
%ignore RoutingModel::GetDimensionsWithSoftAndSpanCosts;
%ignore RoutingModel::GetDimensionsWithSoftOrSpanCosts;
%ignore RoutingModel::GetHardTypeIncompatibilitiesOfType;
%ignore RoutingModel::GetPerfectBinaryDisjunctions;
%ignore RoutingModel::GetPickupIndexPairs;
%ignore RoutingModel::GetSameVehicleRequiredTypeAlternativesOfType;
%ignore RoutingModel::GetTemporalRequiredTypeAlternativesOfType;
%ignore RoutingModel::GetTemporalTypeIncompatibilitiesOfType;
%ignore RoutingModel::HasHardTypeIncompatibilities;
%ignore RoutingModel::HasSameVehicleTypeRequirements;
%ignore RoutingModel::HasTemporalTypeIncompatibilities;
%ignore RoutingModel::HasTemporalTypeRequirements;
%ignore RoutingModel::HasTypeRegulations;
%ignore RoutingModel::MakeStateDependentTransit;
%ignore RoutingModel::RegisterStateDependentTransitCallback;
%ignore RoutingModel::StateDependentTransitCallback;
%ignore RoutingModel::SolveWithParameters(
    const RoutingSearchParameters& search_parameters,
    std::vector<const Assignment*>* solutions);
%ignore RoutingModel::SolveFromAssignmentWithParameters(
      const Assignment* assignment,
      const RoutingSearchParameters& search_parameters,
      std::vector<const Assignment*>* solutions);
%ignore RoutingModel::TransitCallback;
%ignore RoutingModel::UnaryTransitCallbackOrNull;

**Comment by Mizux** [comment]
looking at the prototype:
https://github.com/google/or-tools/blob/dbac8c324d1fa3d37ed992174aa4c0fcc48cd673/ortools/constraint_solver/routing.h#L730

This method should not have any issue to be wrapped by SWIG. I guess it is currently ignored until someone find the time to test (i.e. or write a sample) using it in all supported "OSS" languages (i.e. java, .net, python) for consistency.

**Comment by murr999888** [comment]
It would be great if this “someone” took the time to do this.  ))
Thx.

**Comment by sghb** [comment]
Alternatively, could one use a dimension of capacity 1 and have each of the nodes A, B, C, D add 1 to it?

**Comment by Mizux** [comment]
done in 930e7fb0d62afbdd563ce5d322e93316a6f9d4c3
