### ISSUE TITLE
Are constraints on the CostVar possible?

### ISSUE THREAD

**Issue by hklarner** [google/or-tools#1712]
This is a cross-post from stack exchange: https://stackoverflow.com/questions/58809525/how-can-i-search-for-a-solution-with-a-lower-cost

I have found a solution with assignment.objectiveValue() equal to 4400. I would like to search for solutions with a lower cost than 4400. My first attempt is:

```
cpsolver.addConstraint(cpsolver.makeLess(routingModel.costVar(), 4400));
```
But java informs me that:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fe9dfa76227, pid=29481, tid=0x00007fea3a35a700
#
# JRE version: OpenJDK Runtime Environment (8.0_222-b10) (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.222-b10 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libortools.so+0x6ca227]  operations_research::Solver::MakeSum(operations_research::IntExpr*, long)+0x17
```
My hunch is that I can not add constraints that involve the costVar(). Is that true?

**Comment by lperron** [comment]
Answered on S.O.
