### ISSUE TITLE
Question: CP-SAT - resolve after updating model

### ISSUE THREAD

**Issue by michalsustr** [google/or-tools#1717]
We're considering to use CP-SAT solver in one academic project, as a component of one algorithm.  We'd like to generate one solution at a time, and based on it update the model's constraints and objective function iteratively. Is it possible to do this efficiently, so that the solver does not have to restart from scratch?

I checked the documentation that you can specify the number of requested solutions by aborting the solver: https://developers.google.com/optimization/cp/cp_tasks#solution_limit

If we abort, change the model, and resolve, does it start from scratch, or it improves from the last found solution?

Thanks a lot!

**Comment by stradivari96** [comment]
Yes, you can hint the previous solution, see: https://github.com/google/or-tools/blob/master/ortools/sat/doc/model.md#solution-hinting

**Comment by michalsustr** [comment]
Thank you for the pointer!
