### ISSUE TITLE
Parallel processing

### ISSUE THREAD

**Issue by bcholmes87** [google/or-tools#1718]
Hi,
I am currently employing Google's OR tools and the CP-SAT solver to tackle a scheduling problem. However, in scaling up my problem I am beginning to encounter performance issues and therefore I am now looking to run the model on a cluster. My question is, how many cores can the CP-SAT solver effectively make use of?

In an earlier post on this forum I have read that the solver is comprised of 6 algorithms and, as a result, is not capable of utilising more than 6 unique cores. Is this correct?

**Comment by CervEdin** [comment]
If your challenge is scaling, I would focus on simplifying the problem and optimizing the model first and foremost.

Scheduling problems are NP-hard, expect the compute requirements to scale exponentially.

**Comment by stradivari96** [comment]
Here is a recent issue I opened: https://github.com/google/or-tools/issues/1699

**Comment by lperron** [comment]
The solver uses the first 5 threads to generic methods, and use all the remaining ones on LNS.

So you can scale.

This being said, we tune our solver with 8 workers when running in parallel. But I have seen applications with 32 or 64 workers.

**Comment by bcholmes87** [comment]
Thank you for the responses. Really helpful!

**Comment by konstantinos-paper** [comment]
> The solver uses the first 5 threads to generic methods, and use all the remaining ones on LNS.
> 
> So you can scale.
> 
> This being said, we tune our solver with 8 workers when running in parallel. But I have seen applications with 32 or 64 workers.

Is the 5 threads approach still applicable? @lperron

**Comment by lperron** [comment]
We now tune for 16 workers.

Between 10 and 11 will be used for generic methods. The rest for LNS.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
