### ISSUE TITLE
Add Python 3.8 support

### ISSUE THREAD

**Issue by sameer** [google/or-tools#1719]
Hello, are there plans to support Python 3.8 with the next release?
Mizux: yes target v7.5 release this month

Task Coding:
* [x] Update the docker stuff to build the python package on Linux
* [x] Update the release script on MacOS and
* [x] Update the release script on Windows 

Task infra:
* [x]  Update the mac release machine to add support to python 3.8
* [x] Update the Windows VM release machine to add support for python 3.8

**Comment by stradivari96** [comment]
Duplicate of https://github.com/google/or-tools/issues/1702
> should be next release.

**Comment by Mizux** [comment]
Reopen it to track the advancement...

**Comment by Mizux** [comment]
https://github.com/google/or-tools/commit/4021c4ec517ba5c4bcfcb0923dcd873da3b8fa30
