### ISSUE TITLE
Any documentation for CP solver

### ISSUE THREAD

**Issue by hxd1011** [google/or-tools#172]
Hi, All, I am trying to learn more about Constraint Programming. However, the current examples are not very easy to understand, could anyone give me a link on CP solver's documentation?

 For example, in basic Knapsack problem we have

solver.Add(solver.ScalProd(x, weights) <= capacity)

How do I know the solver has the method of Add or Scalar Product?

I checked source and searched around, but cannot find the documentation.

Any resources are helpful. Thank you.

**Comment by lperron** [comment]
Hi,

in the source code, you will find documentation/reference_manual/index.html.
This is a reference manual that lists all methods.

It is actually extracted from the header files. So, might as well read
src/constraint_solver/constraint_solver.h

About python, any API is transformed to CamelCase, and the Make prefix is
removed

solver::MakeIntVar -> solver.IntVar in python.

You can also check the ongoing work on developer.google.com/optimization

I hope this helps.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-04-05 22:59 GMT+02:00 hxd1011 <notifications@github.com>:

**Comment by hxd1011** [comment]
Great! this helps a lot, Thank you.

**Comment by kpagcha** [comment]
I can't find that documentation.

**Comment by Mizux** [comment]
Seems to have gone with the v5.1
https://github.com/google/or-tools/tree/v5.0/documentation/reference_manual

Now you should use the new website: https://developers.google.com/optimization/cp/
