### ISSUE TITLE
Installation issue OR-tools in windows

### ISSUE THREAD

**Issue by ajohnsonGH** [google/or-tools#1720]
I am having trouble installing OR-tools. I went through question
[Installation issue OR-tools in windows #509](https://github.com/google/or-tools/issues/509), but I still was not able to install. 

I tried the last steps from the previous post and check I am running windows 10 enterprise 64-bit
python -c "import platform; print(platform.architecture())"
('64bit', 'WindowsPE')
PS C:\WINDOWS\system32> python -m pip install ortools
ERROR: Could not find a version that satisfies the requirement ortools (from versions: none)
ERROR: No matching distribution found for ortools

But I still get the same error.
Any help would be appreciated.

**Comment by lperron** [comment]
Which python version?

Le jeu. 14 nov. 2019 à 16:58, ajohnsonGH <notifications@github.com> a
écrit :

**Comment by ajohnsonGH** [comment]
Version 3.8.0

**Comment by lperron** [comment]
As answered 2 times already, it will be supported in the next release.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 14 nov. 2019 à 19:11, ajohnsonGH <notifications@github.com> a
écrit :
