### ISSUE TITLE
Build as one static lib? (C++, macOS)

### ISSUE THREAD

**Issue by asmaloney** [google/or-tools#1721]
How do I build this as one static lib on macOS instead of the 40+ static and dynamic libs it currently produces?

(I would prefer CMake, but if there's a way to do it with the straight Makefile that I'm missing, that's good too!)

Thank you!

**Comment by lperron** [comment]
This is not implemented as it would require deep changing of the
dependencies.

I welcome contributions if you manage to do it.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 15 nov. 2019 à 09:31, Andy Maloney <notifications@github.com> a
écrit :
