### ISSUE TITLE
Need to minimize total VRP Pickup and Delivery miles with capacity constraint on Vehicles 

### ISSUE THREAD

**Issue by pavankarlapudi** [google/or-tools#1723]
Hi,
I am trying to formulate a CVRPPD problem in python which involves from a Depot, need to visit all Pickup and Delivery points(customers) using vehicles with fixed capacity and come back to Depot. The  objective is to minimize  the sum of total travel miles, with the restriction that the vehicle must have enough capacity for transporting the commodities to be delivered and those ones picked-up at customers for returning them to the depot.

Note that Delivery points goods should be picked from depot.
Also some customers can have both Pickup and Delivery at the same day

I have gone through both Capacity constraint algo and pickup and deliver algo in google developer platform. Now I need to combine these to get my results. 
Please through some guidance on how i should formulate it  and solve this problem with or tools.
 
Like should i mention  negative sign demand at delivery point and positive sign for pickup ?
Should i write my pickup and delivery routes like this [0,2],[3,0] ? ( because for delivery we need to pick from depot and pickup items need to go back to depot)
how can check for vehicle capacity while doing all the pickup and delivery ?

If there is any code or an issue on the same which is already solved . please let me know the relevant thread to look into ?

Thanks in advance for your help

**Comment by pavankarlapudi** [comment]
Hey can anyone help in this ?

**Comment by aloramakak** [comment]
I would also like to know the anwer to this problem because I have a similar issue. Maybe somebody can help???

**Comment by lperron** [comment]
I believe the mailing list is more suited for this. A lot less people
receive notifications for google issues compared to the mailing list.
Furthermore, github issues should be about product issues (bugs, missing
features, performance problems).
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 12 déc. 2019 à 13:47, aloramakak <notifications@github.com> a
écrit :
