### ISSUE TITLE
Python Jupyter kernel crashes when running CVRP

### ISSUE THREAD

**Issue by 7cb15** [google/or-tools#1729]
I am getting the following error when running a CVRP model which crashes the kernel in the jupyter notebook I am running the program in:

`WARNING: Logging before InitGoogleLogging() is written to STDERR
F1120 17:32:45.784871 202909120 routing.cc:1192] Check failed: 0 < vehicles_ (0 vs. 0) 
*** Check failure stack trace: ***`

Here is an excerpt of the program where the kernel continues to crash:

` for i in pickup_locations:
    
    print(i)    
    
    orders_geo = window_range(orders_geo,1,1)
    order_groups = orders_geo[orders_geo.pickup_latlon==i]
    
    for j in delivery_days:
        
        print(j)
    
        order_groups = order_groups[(order_groups.min_window <=j)&(order_groups.max_window>=j)]
        
        #filter df to specific pickup locations
        location_list = list(order_groups.dropoff_latlon) #create list of delivery locations
        location_list.append(i) #append the pickup location to the delivery list

        distance_matrix_calc = distance_matrix(location_list) #generates a distance matrix in miles

        data = create_data_model(distance_matrix_calc,order_groups) #create the input data structure

            # Create the routing index manager.
        manager = pywrapcp.RoutingIndexManager(len(data['distance_matrix']),
                                               data['num_vehicles'], data['depot'])

        # Create Routing Model.
        routing = pywrapcp.RoutingModel(manager)

        # Create and register a transit callback.
        def distance_callback(from_index, to_index):
            """Returns the distance between the two nodes."""
            # Convert from routing variable Index to distance matrix NodeIndex.
            from_node = manager.IndexToNode(from_index)
            to_node = manager.IndexToNode(to_index)
            return data['distance_matrix'][from_node][to_node]

        transit_callback_index = routing.RegisterTransitCallback(distance_callback)

        # Define cost of each arc.
        routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

        #apply distance constraint
        #dimension_name = 'Distance'
        #routing.AddDimension(transit_callback_index,0,5000,True,dimension_name) #set max distance equal to max order
        #distance_dimension = routing.GetDimensionOrDie(dimension_name)
        #distance_dimension.SetGlobalSpanCostCoefficient(100)

        # Add Capacity constraint.
        def demand_callback(from_index):
            """Returns the demand of the node."""
            # Convert from routing variable Index to demands NodeIndex.
            from_node = manager.IndexToNode(from_index)
            return data['demands'][from_node]

        demand_callback_index = routing.RegisterUnaryTransitCallback(
            demand_callback)
        routing.AddDimensionWithVehicleCapacity(
            demand_callback_index,
            0,  # null capacity slack
            data['vehicle_capacities'],  # vehicle maximum capacities
            True,  # start cumul to zero
            'Capacity')
        
        # Setting first solution heuristic.
        search_parameters = pywrapcp.DefaultRoutingSearchParameters()
        search_parameters.first_solution_strategy = (
            routing_enums_pb2.FirstSolutionStrategy.PARALLEL_CHEAPEST_INSERTION)

        # Solve the problem.
        assignment = routing.SolveWithParameters(search_parameters)

        # Print solution on console.
        if assignment:
            print_solution(data, manager, routing, assignment)`

Note that the model was running as expected in the first loop (`for i in pickup_locations:`) but when I add the second loop (`for j in delivery_days:`) I get the error.

I have tried changing `search_parameters = pywrapcp.RoutingModel.DefaultSearchParameters()` which was a suggested solution in another issue but it did change the behavior.

Any help understanding the error message or debugging is much appreciated!

**Comment by CervEdin** [comment]
Which version of python is the kernel running?

**Comment by 7cb15** [comment]
I'm using the following versions:

python: v 3.7.3
ortools: v 7.4.7247

**Comment by 7cb15** [comment]
I was able to debug the problem by adjusting the way that the number of vehicles is calculated in the `create_data_model()` function:

Original function:

`def create_data_model(distance_matrix,df):
    '''functions for defining model parameters in a dictionary
    distance_matrix: distance matrix of all delivery and pickup locations
    num_locations: number of locations
    num_vehicles: number of vehicles in model, defined as the min() based on weight
    depot: the index of the pickup location in the distance matrix'''

    data = {} #initialize empty dictionary
    data['distance_matrix'] = distance_matrix #set distance matrix
    data['num_locations'] = len(distance_matrix)-1 #number of total locations
    #set the default number of vehicles as the avg between the min and max possible vehicles
    data['num_vehicles'] = int(round(((df.delivery_num.count())+(df.weight.sum() / 45000)) / 2)) 
    data['depot'] = len(distance_matrix)-1 #index of the pickup location in the distance matrix, always last in index
    inital_demand_list = list(df.weight) #create list of demand capacities based on weight of orders
    inital_demand_list.append(0) 
    data['demands'] = inital_demand_list #define demand as the weight of each order
    data['vehicle_capacities'] = [45000 for i in range(data['num_vehicles'])] #set capacities, 45k lbs per vehicle

    return data`

Revised function:

`def create_data_model(distance_matrix,df):
    '''functions for defining model parameters in a dictionary
    distance_matrix: distance matrix of all delivery and pickup locations
    num_locations: number of locations
    num_vehicles: number of vehicles in model, defined as the min() based on weight
    depot: the index of the pickup location in the distance matrix'''

    data = {} #initialize empty dictionary
    data['distance_matrix'] = distance_matrix #set distance matrix
    data['num_locations'] = len(distance_matrix)-1 #number of total locations
    #set the default number of vehicles as the avg between the min and max possible vehicles
    data['num_vehicles'] = int(round(((df.delivery_num.count())+(df.weight.sum() / 45000)) / 2) + 1) 
    data['depot'] = len(distance_matrix)-1 #index of the pickup location in the distance matrix, always last in index
    inital_demand_list = list(df.weight) #create list of demand capacities based on weight of orders
    inital_demand_list.append(0) 
    data['demands'] = inital_demand_list #define demand as the weight of each order
    data['vehicle_capacities'] = [45000 for i in range(data['num_vehicles'])] #set capacities, 45k lbs per vehicle

    return data`
