### ISSUE TITLE
solve is slow when give a complex objective_expr 

### ISSUE THREAD

**Issue by hukun1995** [google/or-tools#1731]
solve is slow when give a complex objective_expr , like sum(thounds of productVar)
But when obj's vars do not exist in constraints,  the solver's speed will be influenced severely?
What can I do to get a feasible sulution quickly?

**Comment by lperron** [comment]
change the model.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by hukun1995** [comment]
e..But i don not know why obj_expr influence the speed to get a feasible solution?
