### ISSUE TITLE
Not supported: count_eq

### ISSUE THREAD

**Issue by PatrickTrentin88** [google/or-tools#1732]
I downloaded the latest version of `or-tools`, and I ran:

```
~$ mzn2fzn -O- -G "or_tools_cp" --output-to-stdout warehouses.mzn > warehouses.or_tools_cp.fzn
~$ fzn-or-tools warehouses.or_tools_cp.fzn
```

This is the output of the second command:

```
 Not supported count_eq
*** Check failure stack trace: ***
    @     0x7f3ab047f25a  google::LogMessage::Fail()
    @     0x7f3ab047f195  google::LogMessage::SendToLog()
    @     0x7f3ab047eac6  google::LogMessage::Flush()
    @     0x7f3ab0482546  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f3ab05c21e3  operations_research::sat::(anonymous namespace)::CpModelProtoWithMapping::FillConstraint()
    @     0x7f3ab05c4f84  operations_research::sat::SolveFzWithCpModelProto()
    @     0x556ebe56d974  main
    @     0x7f3ab006a1e3  __libc_start_main
    @     0x556ebe56de0e  _start
    @              (nil)  (unknown)
Aborted (core dumped)
```

The warehouses.mzn file is attached ([warehouses.zip](https://github.com/google/or-tools/files/3875997/warehouses.zip)).

**Workaround:** delete the file `count_eq.mzn` within the directory `or_tools_cp` of global constraints, so that the one provided by `MiniZinc` is used.

**Comment by lperron** [comment]
the old cp backend is not supported anymore.
Either you get it from an old release, or you use the _sat mzn files.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 21 nov. 2019 à 18:50, PatrickTrentin88 <notifications@github.com> a
écrit :

**Comment by PatrickTrentin88** [comment]
Thanks.

It would be helpful to print a warning message to signal that this feature is no longer supported.

**Comment by lperron** [comment]
This was documented in release notes.

Le ven. 22 nov. 2019 à 12:17, PatrickTrentin88 <notifications@github.com> a
écrit :

**Comment by PatrickTrentin88** [comment]
@lperron could you please help me find the exact release that dropped the support for FlatZinc(CP)? I have searched in the release notes, and the only thing I found is that at some point FlatZinc(SAT) became the default.

**Comment by lperron** [comment]
Maybe it was not announced, but the code has not changed in 3+ years.
You can take any old release.

This being said, the CP backend is really not competitive w.r.t. the CP-SAT
backend.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 26 nov. 2019 à 13:17, PatrickTrentin88 <notifications@github.com> a
écrit :

**Comment by PatrickTrentin88** [comment]
Yeah, coming from SAT/SMT/OMT, I understand that performance difference. 

I am evaluating whether I should remove from the paper the results I obtained with FlatZinc(CP) with the version 6.7.4981 of OrTools too, since there are a large number of unsupported formulas (25/100).

**Comment by lperron** [comment]
I completely dropped flatzinc/CP and did not use it in competitions for 2
years now.
And I recently completely killed the code.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 26 nov. 2019 à 13:30, PatrickTrentin88 <notifications@github.com> a
écrit :

**Comment by PatrickTrentin88** [comment]
Thanks for your feedback and help. I've decided to drop the results too.
