### ISSUE TITLE
DijkstraShortestPath directly in python

### ISSUE THREAD

**Issue by TimoK93** [google/or-tools#1734]
Hey folks,

i'm trying to use a shortest path algorithm in python. I found your library and the method DijkstraShortestPath described in:
https://github.com/google/or-tools/blob/6755c61315c7bb382a558b27cdff7ea2d5970c9c/ortools/graph/shortestpaths.h#L31-L39

Is there a way to use the algorithm directly in python? Maybe with an short code example?

My probem till now is the following:
`TypeError: in method 'DijkstraShortestPath', argument 4 of type 'std::function< int64 (int,int) >'`

Im not sure what to pass in argument "graph".

Thanks for help!
Timo

**Comment by CervEdin** [comment]
You want to use OR-tools solely for computing the shortest path?

**Comment by TimoK93** [comment]
Hey CervEdIn,
yes, thats what i need to do!

**Comment by lperron** [comment]
The quality of the implementation is really low. This is the most basic
implementation.

Le ven. 22 nov. 2019 à 11:35, Timo Kaiser <notifications@github.com> a
écrit :

**Comment by CervEdin** [comment]
@TimoK93 I would advice against that. 

It's better to use a native Python library dedicated to shortest path calculation or implementing it yourself

**Comment by TimoK93** [comment]
Okay thank you... I think i will implement dijkstra on myself!

Have a nice weekend!
Timo
