### ISSUE TITLE
Same vehicles for some stops.

### ISSUE THREAD

**Issue by tigrandp** [google/or-tools#174]
Is there a way to specify that some stops should be served with the same vehicle ?

**Comment by Grovespaz** [comment]
Have a look at AddPickupAndDelivery, but be aware: this function merely locks both stops to the vehicle, it doesn't guarantee their order (e.g. delivery can come before pickup).

This function basicly does the following (C#):
solver.Add(solver.MakeEquality(routing.VehicleVar(constraint.Pickup), routing.VehicleVar(constraint.Delivery));
