### ISSUE TITLE
Defining two possible ranges for a CumulVar

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1742]
Hello,
Is there a way to define two non-overlapping ranges for the value of CumulVar?
Something like:   CumulVar(@Node) = SetRange(A,B) OR SetRange(C,D) 
Thx

**Comment by lperron** [comment]
You can use

http://google.github.io/or-tools/cpp_routing/classoperations__research_1_1Solver.html#ada8465da06ae8815d5f783d7bc9fff8d

or its negation by using the complement

http://google.github.io/or-tools/cpp_routing/classoperations__research_1_1Solver.html#a2615c4443c80ae1433d5e686963f6cc6
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
Thx, but I don't understand what to do with this.
The IntExpr should be the CumulVar ?  
How are the min/max values of each range reflected in const std::vector<int64>& values ?

**Comment by lperron** [comment]
either you expand to all values, or you use the negative version if the
complement of the intervals.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
Probably impractical to expand all values in my case ... maybe if I create/use a compressed version of the real dimension.

Or a constraint with an OR over between two MakeBetweenCt (IntExpr *const expr, int64 l, int64 u). Need to check the right syntax.

Or use two Nodes each with one range, plus a Disjunction.

I was hoping for something 'cleaner' ....

**Comment by lperron** [comment]
You cannot or constraints.

The simplest is:

NotMemberCt(var, [INT_MIN, B + 1, D + 1]. [A - 1, C - 1, INT_MAX])
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
Got it. 
NotMemberCt(**var**, [INT_MIN, B + 1, D + 1]. [A - 1, C - 1, INT_MAX])
                                                                                 "var" would my CumulVar(@Node)?

**Comment by lperron** [comment]
it was pseudo-code
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
Sure,  but the IntExpr should be the CumulVar whose values I wish to constraint?

**Comment by lperron** [comment]
yes
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
