### ISSUE TITLE
VRP Some nodes only to be served by particular type of vehicle. The vehicle can serve 2 types of node.

### ISSUE THREAD

**Issue by akarsh1995** [google/or-tools#1743]
some nodes refrigerated Must be served by refrigerated vehicles in the fleet
some nodes oil must be served by oil vehicles in the fleet
all ordinary nodes can be served by any vehicle in the fleet

all vehicles ----> have capacities associated with it. 
all nodes ------> may have load associated with it 
all nodes ------> definitely have vehicle type associated with it. (oil or refrigerated or ordinary)

I tried solving it using DimensionWithVehicleCapacity constraint but it is defined if particular vehicle is supposed to serve particular types of node

I also tried figuring out the solution using allowing nodes for vehicle but cannot map the solution in mind.

**Comment by lperron** [comment]
Restrict the vehicle var of the nodes.
Search for the mailing list.
