### ISSUE TITLE
Elastic scheduling

### ISSUE THREAD

**Issue by DominikRoB** [google/or-tools#1746]
Is there a way to construct the ressource contraints of activities according to elastic scheduling in the CP SAT Solver? (I am using python)

With elastic scheduling I mean that a activitys usage of a ressource can varie over time and the sum of used ressources over the whole time has to be equal to a specified amount.

Thanks!

**Comment by lperron** [comment]
No. We do not support this feature.

Le mar. 26 nov. 2019 à 16:53, DominikRoB <notifications@github.com> a
écrit :
