### ISSUE TITLE
Can OR-Tools 7.4 run on .Net Framework, i.e. not only .NetCore ?

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1747]
Hello,
I found this in 7.4 New features and improvements:
"The architecture of the NuGet package has been completely rewritten. In particular, **it now supports the .NET framework >= 4.5.2 on Windows platforms.** "

Does this mean we can build on .Net Framework?

Thx

**Comment by lperron** [comment]
It should

**Comment by GuyBenhaim** [comment]
Neat!
Will check.
