### ISSUE TITLE
VRP with weighting for specific vehicles to arrive at certain nodes

### ISSUE THREAD

**Issue by lmcmahon7** [google/or-tools#1749]
Hi,

I'm trying to do a VRP where we have the main objective to minimise the time that vehicles are operating (total time in service).  That is working fine.  The secondary objective is proving more challenging.  

The secondary objective is to make vehicles that have been to nodes in previous scenarios to preferentially go there again.  Eg.  vehicle A generally attends nodes 1,2,3.  I'm trying to get the simulation to optimise for this.  

I'm importing a list of vehicles and their previous attendance at nodes.  Eg
Vehicle 1 - Nodes [A,B,C]
Vehicle 2 - Nodes [B,C,D]
Vehicle 3 - Node [E]
**Note:** there may be overlap in previous attendance.

I tried inputting this this using 
routing.AddSoftSameVehicleConstraint([A, B, C], 100)
This method has drawbacks as it specifies that **a** vehicle should attend the same nodes.  I want to be more specific and specify that a specific vehicle should attend specific nodes.  Eg Vehicle 1 should attend A,B,C rather than A,B,C should be attended by a single vehicle.

My current thinking is that I should add a vehicle specific callback.  This would specify 1 at nodes previously attended and 0 otherwise.  I could then get the vehicles to accumulate this dimension at these nodes and reward each "pickup" with a negative cost.  

I'm wondering if I'm on the right track or if there's another method that you'd use to do this.

**Comment by Mizux** [comment]
Use `routing.VehicleVar(location_index).SetValues([-1, vehicle_index])`

ref: https://github.com/google/or-tools/blob/fa84bc05e72641dddfbb98164d81b8bc9bef6ea5/ortools/constraint_solver/routing.h#L1201-L1203
