### ISSUE TITLE
flexible_job_shop_sat.py - find minimum of drivers

### ISSUE THREAD

**Issue by alexpoh** [google/or-tools#1750]
Hi, 

How can i find the minimum drivers inorder to fulfill the requirement of nooverlap interval constraint for  each driver?
For example, when I tried with 3 drivers, the solver not able return the objectivevalue whereas the solver was able to return objective after tested with 4 or 5 drivers.  

import collections
from ortools.sat.python import cp_model

timeframe = [
    [0, '14:00', '14:13', 0, 13, 13],
    [1, '14:00', '14:15', 0, 15, 15],
    [2, '14:10', '14:30', 10, 30, 20],
    [3, '14:10', '14:27', 10, 27, 17],
    [4, '14:20', '14:50', 20, 50, 30],
    [5, '14:25', '14:40', 25, 40, 15],
    [6, '14:35', '15:00', 35, 60, 25],
    [7, '14:45', '14:55', 45, 55, 10]
]

jobs = [ # duration, 5 drivers
    [(13, 2), (13, 3)],
    [(15, 1), (15, 2), (15, 3), (15, 4), (15, 5)],
    [(20, 1), (20, 2), (20, 3), (20, 4), (20, 5)],
    [(17, 1), (17, 2), (17, 3), (17, 4), (17, 5)],
    [(30, 1), (30, 2), (30, 3), (30, 4), (30, 5)],
    [(15, 1), (15, 2), (15, 3), (15, 4), (15, 5)],
    [(25, 1), (25, 2), (25, 3), (25, 4), (25, 5)],
    [(10, 1), (10, 2), (10, 3), (10, 4), (10, 5)]             
]

"""
jobs = [ # duration, 4 drivers
    [(13, 2), (13, 3)],
    [(15, 1), (15, 2), (15, 3), (15, 4)],
    [(20, 1), (20, 2), (20, 3), (20, 4)],
    [(17, 1), (17, 2), (17, 3), (17, 4)],
    [(30, 1), (30, 2), (30, 3), (30, 4)],
    [(15, 1), (15, 2), (15, 3), (15, 4)],
    [(25, 1), (25, 2), (25, 3), (25, 4)],
    [(10, 1), (10, 2), (10, 3), (10, 4)]             
]"""

"""
jobs = [# duration, 3 drivers
    [(13, 2), (13, 3)],
    [(15, 1), (15, 2), (15, 3)],
    [(20, 1), (20, 2), (20, 3)],
    [(17, 1), (17, 2), (17, 3)],
    [(30, 1), (30, 2), (30, 3)],
    [(15, 1), (15, 2), (15, 3)],
    [(25, 1), (25, 2), (25, 3)],
    [(10, 1), (10, 2), (10, 3)]             
]
"""
num_jobs = len(jobs)
all_jobs = range(num_jobs)

num_drivers = max(alt[1] for job in jobs for alt in job)
all_drivers = range(num_drivers)

model = cp_model.CpModel()

horizon = 0
for job in jobs:
    max_task_duration = 0
    for alternative in job:
        max_task_duration = max(max_task_duration, alternative[0])
    horizon += max_task_duration
    
print('Horizon = %i' % horizon)

task_type = collections.namedtuple('Task', 'start end interval')

assigned_task_type = collections.namedtuple('assigned_task_type', 
                                            'start task duration')

all_tasks = {}
intervals_per_resources = collections.defaultdict(list)

presences = {}
task_ends =[]

for task_id in all_jobs:
    task = jobs[task_id]
    
    min_duration = task[0][0]
    max_duration = task[0][0]
    
    num_alternatives = len(task)
    all_alternatives = range(num_alternatives)

    for alt_id in range(1, num_alternatives):
        alt_duration = task[alt_id][0]
        min_duration = min(min_duration, alt_duration)
        max_duration = max(max_duration, alt_duration)
    
    #print(f"task={task_id} -> min={min_duration} -> max={max_duration}")
    
    #Create main interval for the task
    suffix = '_t%i' % (task_id)
    start = model.NewIntVar(0, horizon, 'start' + suffix)
    duration = model.NewIntVar(min_duration, max_duration, 'duration' + suffix)
    end = model.NewIntVar(0, horizon, 'end' + suffix)
    interval = model.NewIntervalVar(start, duration, end, 'interval' + suffix)
    
    all_tasks[task_id] = task_type(start=start, end=end, interval=interval)
    
    start_time = timeframe[task_id][3]
    end_time = timeframe[task_id][4]
    
    # Create alternative intervals
    if num_alternatives > 1:
        l_presences = []
        for alt_id in all_alternatives:
            alt_suffix = '_t%i_a%i' % (task_id, alt_id)
            l_presence = model.NewBoolVar('presence' + alt_suffix)
            l_start = model.NewIntVar(0, horizon, 'start' + alt_suffix)
            l_duration = task[alt_id][0]
            l_end = model.NewIntVar(0, horizon, 'end' + alt_suffix)
            l_interval = model.NewOptionalIntervalVar(l_start,
                                                      l_duration,
                                                      l_end,
                                                      l_presence,
                                                      'interval' + alt_suffix)
            l_presences.append(l_presence)
            
            # Link the master variables with the local ones.
            model.Add(start == l_start).OnlyEnforceIf(l_presence)
            model.Add(duration == l_duration).OnlyEnforceIf(l_presence)
            model.Add(end == l_end).OnlyEnforceIf(l_presence)
            
            model.Add(start == start_time).OnlyEnforceIf(l_presence)
            model.Add(end == end_time).OnlyEnforceIf(l_presence)
            
            # Add the local interval to the right driver.
            intervals_per_resources[task[alt_id][1]].append(l_interval)
            
            # Store the presences for the solution.
            presences[(task_id, alt_id)] = l_presence
        
        # Select exactly one presence variable.
        model.Add(sum(l_presences) == 1)
    else:
        intervals_per_resources[task[0][1]].append(interval)
        presences[(task_id, 0)] = model.NewConstant(1)
    
for driver_id in range(1, num_drivers + 1):
    intervals = intervals_per_resources[driver_id]
    if len(intervals) > 1:
        model.AddNoOverlap(intervals)

obj_var = model.NewIntVar(0, horizon, 'makespan')
model.AddMaxEquality(obj_var, 
                     [all_tasks[task_id].end for task_id in all_tasks])
model.Minimize(obj_var)

solver = cp_model.CpSolver()
status = solver.Solve(model)

display = 1
if status == cp_model.OPTIMAL:
    if display == 1:
        assigned_jobs = collections.defaultdict(list)
        for task_id, tasks in enumerate(jobs):
            driver = -1
            duration = -1
            selected = -1          
            for alt_id in range(len(jobs[task_id])):
                if solver.Value(presences[(task_id, alt_id)]):
                    duration = jobs[task_id][alt_id][0]
                    driver = jobs[task_id][alt_id][1]
                    assigned_jobs[driver].append(
                        assigned_task_type(
                            start = solver.Value(all_tasks[task_id].start),
                            task = task_id,
                            duration = duration
                        )
                    )
        output = ''
        
        for driver in range(1, num_drivers+1):
            assigned_jobs[driver].sort()
            sol_line_tasks = 'Driver ' + str(driver) + ': '
            sol_line = '          '
            
            for assigned_task in assigned_jobs[driver]:
                if assigned_task ==  assigned_jobs[driver][-1]:
                    name = 'task_%i' % (assigned_task.task)
                else:
                    name = 'task_%i ->' % (assigned_task.task)
                sol_line_tasks += '%-10s' % name
                start = assigned_task.start
                duration = assigned_task.duration
                
                sol_tmp = '[%i, %i]' % (start, start + duration)

                sol_line += '%-10s' % sol_tmp
                
            sol_line += '\n'
            sol_line_tasks += '\n'
            output += sol_line_tasks
            output += sol_line
        
        print(output)
        
    else:
    
        for task_id in all_jobs:
            start_value = solver.Value(all_tasks[task_id].start)
            end_value = solver.Value(all_tasks[task_id].end)
            driver = -1
            duration = -1
            selected = -1
            for alt_id in range(len(jobs[task_id])):
                if solver.Value(presences[(task_id, alt_id)]):
                    duration = jobs[task_id][alt_id][0]
                    driver = jobs[task_id][alt_id][1]
                    selected = alt_id
            print('  task_%i starts at %i, ends at %i (alt %i, driver %i, duration %i)' %
                  (task_id, start_value, end_value, selected, driver, duration))

**Comment by stradivari96** [comment]
If it doesnt take too long to prove INFEASIBLE you can just retry with one more.

You can also create more than enough drivers and minimize them.

**Comment by lperron** [comment]
1) Once again, it looks close to a routing problem, where minimizing the number of drivers is easy.
2) This is not really an issue with the solver. Could you use the mailing list for that ?
