### ISSUE TITLE
VRP w/ PDP - Force vehicle to go to pickup before going to depot

### ISSUE THREAD

**Issue by Fendrium** [google/or-tools#1752]
Hello,

I am working on a script that has been developed by someone else, which means I am still quite new to or-tools.
I am using Python 3.7.3 and 7.2.6977.

One of the feature that is required is to force a vehicle to stop by a pickup just before going to the depot at the end.
The routing would be like the following example:
Depot-> Drop->Drop->**Pickup->Depot**

This is to make sure the truck is full before going back to the depot. In this example, we assume the truck is already full at the beginning. My pickup points have negative demands.

So far, I have tried using multiple ways of doing this:
- With NextVar(), I tried to make no stop before the routing.End(Vehicle) like this
```python
for v in range(len(vehicle_list)):if data['full_at_end'][v] == 'Yes':
        index = routing.End(v)
        for drop in drop_list:
            drop_index = manager.NodeToIndex(drop)
            routing.solver().Add(routing.NextVar(drop_index) != index )
````
This solution didn't really work as expected, it either does not do what is expected for vehicles that have to be full at end, or the case naturally happens on other vehicles that aren't required to be full at end.
- With AddPickupAndDelivery(), I tried the following with just one source and one depot for testing
```python
for v in range(len(vehicle_list)):
    if data['full_at_end'][v] == 'Yes':
        if vehicle_list[v] == '9193':
            end_index = routing.End(v)         
            routing.AddPickupAndDelivery(manager.NodeToIndex(343), manager.NodeToIndex(end_index))
   
            routing.solver().Add(
                    routing.VehicleVar(manager.NodeToIndex(343)) == routing.VehicleVar(end_index))
```
This code crashes the kernel

I did not try with disjunctions, because it really is the order that I want to preserve, rather than just the fact of passing by the node.

I have been pulling my hair on this for a few weeks, so your help will be greatly appreciated.

Thank you very much in advance.

**Comment by lperron** [comment]
you can make sure that the only available arcs in the graph going to the depot are the one coming from a pickup point.
