### ISSUE TITLE
Check if hinted solution is valid

### ISSUE THREAD

**Issue by stradivari96** [google/or-tools#1754]
Is there a fast way to check if a hinted solution is valid in python?
Or should I just use model.Add to set the values?

**Comment by lperron** [comment]
I would use model.Add()
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 28 nov. 2019 à 12:18, Xiang Chen <notifications@github.com> a
écrit :

**Comment by stradivari96** [comment]
Thanks!

I actually only wanted a quick visual inspection so using log_search_progress = True also worked.

**Comment by stradivari96** [comment]
Leaving this here in case someone needs it in the future.

```python
def check_hint(model: cp_model.CpModel) -> bool:
    """Check the hinted solution is valid"""
    # No hint
    if not model.Proto().solution_hint.vars:
        return True
    # Clone model
    tmp_model = cp_model.CpModel()
    tmp_model.Proto().CopyFrom(model.Proto())

    solver = cp_model.CpSolver()
    variables = tmp_model.Proto().solution_hint.vars
    values = tmp_model.Proto().solution_hint.values
    for i, var in enumerate(variables):
        var = tmp_model.Proto().variables[var]
        value = values[i]
        lb, ub = var.domain
        if not (lb <= value <= ub):
            # outside the domain
            return False
        var.ClearField("domain")
        var.domain.extend([value, value])

    # hopefully presolved
    status = solver.Solve(tmp_model)
    return status in [cp_model.FEASIBLE, cp_model.OPTIMAL]
```

**Comment by hklarner** [comment]
> Is there a fast way to check if a hinted solution is valid in python?

@stradivari96  What is a "hinted solution" ? Does this apply to the VRP setting?
