### ISSUE TITLE
CVRP multiple cargo:How to constraint every node to be visited only by one vehicle?

### ISSUE THREAD

**Issue by nikosio** [google/or-tools#1756]
The problem with multiple cargo is that the final route allows a node to be visited by multiple vehicles in order to deliver all the cargo  and we do not want that to happen in our solution

**Comment by lperron** [comment]
It never happens.

Le dim. 1 déc. 2019 à 15:10, Nikos Iosifidis <notifications@github.com> a
écrit :

**Comment by nikosio** [comment]
I am afraid it DOES HAPPENS see : https://github.com/google/or-tools/issues/942,
4. Lastly, and this is VERY IMPORTANT as well. How do I make sure that when a truck visits a location, it delivers everything in one go? I did have an issue earlier when Products 1,2,3,4 were delivered by Truck A and Product 5 was solely delivered by Truck B. Due to cost issues, I cannot split the delivery into two Trucks.

Can i use a dimension to count number of different vehicles (vehicle ID's) that pass from a node and contraint this dimension to be at most one ?
