### ISSUE TITLE
Building for Windows tries to apply outdated abseil patch

### ISSUE THREAD

**Issue by abeham** [google/or-tools#1757]
This concerns master.

In f2c7d2cf74dc1de16cf53e5daa9d5f235e14f61c abseil was bumped to a different version, but Line 364 in Makefile.win.mk still tries to apply the patch that was used before, but which does not exist.

In 2ff000ab9a7ba37c55205c44822a8cbb2ad4e786 where this was done for unix, the line trying to apply the patch was commented, this needs to be done for Makefile.win.mk also.

```
#	cd dependencies\sources\abseil-cpp-$(ABSL_TAG) && git apply "$(OR_TOOLS_TOP)\patches\abseil-cpp-$(ABSL_TAG).patch"
```

**Comment by lperron** [comment]
Fixed
