### ISSUE TITLE
SCIP-6.0.2 under Windows doesn't build on master

### ISSUE THREAD

**Issue by abeham** [google/or-tools#1758]
In scip_interface.cc it complains that scip_constraint_handler_ is not found in line 162: `scip_constraint_handler_.reset();`

**Comment by lperron** [comment]
Thanks. Fixed
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le dim. 1 déc. 2019 à 23:47, Andreas Beham <notifications@github.com> a
écrit :
