### ISSUE TITLE
Setup.py Install Issue

### ISSUE THREAD

**Issue by ctriley** [google/or-tools#176]
System information: Mac OS X 10.11.4 (15E65)

Attempting to install with setup.py yielded this error:

/Users/connorriley/.virtualenvs/cse5095/lib/python2.7/site-packages/setuptools-20.7.0-py2.7.egg/setuptools/dist.py:294: UserWarning: The version specified ('2.Unversioned directory') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
running install
running bdist_egg
running egg_info
writing requirements to ortools_examples.egg-info/requires.txt
writing ortools_examples.egg-info/PKG-INFO
writing top-level names to ortools_examples.egg-info/top_level.txt
writing dependency_links to ortools_examples.egg-info/dependency_links.txt
reading manifest file 'ortools_examples.egg-info/SOURCES.txt'
writing manifest file 'ortools_examples.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.11-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build/bdist.macosx-10.11-x86_64/egg
creating build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/PKG-INFO -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/SOURCES.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/dependency_links.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/requires.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/top_level.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/ortools_examples-2.Unversioned.directory-py2.7.egg' and adding 'build/bdist.macosx-10.11-x86_64/egg' to it
removing 'build/bdist.macosx-10.11-x86_64/egg' (and everything under it)
Processing ortools_examples-2.Unversioned.directory-py2.7.egg
Removing /Users/connorriley/.virtualenvs/cse5095/lib/python2.7/site-packages/ortools_examples-2.Unversioned.directory-py2.7.egg
Copying ortools_examples-2.Unversioned.directory-py2.7.egg to /Users/connorriley/.virtualenvs/cse5095/lib/python2.7/site-packages
ortools-examples 2.Unversioned.directory is already the active version in easy-install.pth

Installed /Users/connorriley/.virtualenvs/cse5095/lib/python2.7/site-packages/ortools_examples-2.Unversioned.directory-py2.7.egg
Processing dependencies for ortools-examples===2.Unversioned.directory
Searching for ortools
Reading https://pypi.python.org/simple/ortools/
No local packages or download links found for ortools
error: Could not find suitable distribution for Requirement.parse('ortools')

Next I tried installing via 
These directions:
Upgrade setuptools from 12.05 to 12.1 by running 'curl https://bootstrap.pypa.io/ez_setup.py -o - | python'
Run 'pip install ez_setup'
Install or-tools by running 'pip install ortools'

This also failed with the following error:
Collecting ortools
  Could not find a version that satisfies the requirement ortools (from versions: )
No matching distribution found for ortools

**Comment by antoniomedrano** [comment]
I have it up and running just fine using Mac OS X 10.11.4 on my retina MBP.
I used the procedure outlined at [the or-tools website](https://developers.google.com/optimization/installing#python), and in particular installing using the following command:
`sudo python setup.py install --user`
I found when I didn't install with the --user flag then I had to use sudo each time I wanted to run or-tools. I hope this helps.

**Comment by lperron** [comment]
Which python are you using?
The default one in the command line tools?

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-04-28 20:41 GMT+02:00 Antonio Medrano <notifications@github.com>:

**Comment by tcfuji** [comment]
I'm getting the same error but I'm using a Python virtual environment. Is it necessary to use the built-in OS X Python?

**Comment by lperron** [comment]
I have not tested with anything else than the default python.
With setuptools being very brittle, I do not know how it behaves with different python versions.
Experience suggests it does not do well.

Please note that it also interactcs with sudo/non sudo installs, as some libraries installed in one mode can be unreachable from the other mode.

**Comment by lperron** [comment]
I do not know.
I am only building/testing with the default python.

One option is to build from source, and create python packages

make third_party
make install_python_modules
make python
make pypi_archive

will build a temp/ortools directory with a correct setup.py file. You can
build .egg files from there.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-06-04 22:57 GMT+02:00 Ted <notifications@github.com>:

**Comment by Mizux** [comment]
Hi,

Since version v6.7, you can use `make install_python` and it should work like a charm :wink:
