### ISSUE TITLE
linear solver pywraplp getting failed constraint in case on infeasibility

### ISSUE THREAD

**Issue by P00L** [google/or-tools#1760]
Hi,

I'm using pywraplp linear solver **CBC_MIXED_INTEGER_PROGRAMMING, GLOP_LINEAR_PROGRAMMING and CLP_LINEAR_PROGRAMMING**. 

When the solution gives **INFEASIBLE** as result there is a way to identify wich constraint makes the solution infeasible? 
My idea is to add one constraint at the time and re-run the entire simulation to identify the constraint giving the infeasibility, at the cost of a big overhead in time since the simulation in quite expensive.

Thanks for your help

**Comment by lperron** [comment]
This is called IIS. (https://or.stackexchange.com/questions/372/is-the-irreducible-infeasible-subset-iis-of-an-lp-unique/374)

Unfortunately, we do not expose this feature.

You can export the model as an MPS file and feed that directly to a solver binary.
