### ISSUE TITLE
Possibility of NPE [CpSolver, Java]

### ISSUE THREAD

**Issue by prissky** [google/or-tools#1762]
Hi all,

SatHelper.solveWithParametersAndSolutionCallback() may return NULL, but CpSolver.solveWithSolutionCallback() does not expect it which causes NPE. 

Seems like a bug or am I mistaken?

**Comment by lperron** [comment]
Can you send a code they exhibits the problem ?

**Comment by prissky** [comment]
I have not managed to obtain a 100% exhibit yet, since it is a rare race condition caused by an early StopSearch(). But the fact that NULL is checked on one level and not on the other looks suspicious to me.

**Comment by lperron** [comment]
I checked, it nevers returns null.
It always return an instance of CpSolverResponse.
