### ISSUE TITLE
pywraplp GLOP_LINEAR_PROGRAMMING timeout

### ISSUE THREAD

**Issue by P00L** [google/or-tools#1763]
Hi,

I'm using pywraplp GLOP_LINEAR_PROGRAMMING linear solver and I've tried to use `set_time_limit()` to catch solution resulting in long simulation but seems to not affect the time limit. After some test seems that exist a limit of 20467 iterations (`retrived with iterations()`). It's possible to edit this limit?

Thanks

**Comment by lperron** [comment]
I do not understand what you tried to do or the question. Sorry

**Comment by P00L** [comment]
Here a snipper of the code I am running

```
from ortools.linear_solver import pywraplp

solver = pywraplp.Solver('my_simluation', pywraplp.Solver.GLOP_LINEAR_PROGRAMMING)
solver.set_time_limit(420000)

... # model definition

solver.Solve()
print(self.solver.iterations()))
print(self.solver.wall_time()))

```

The line `solver.set_time_limit(420000)` seems to be ignored since the solution gives TIMEOUT result with a wall time of 146629 that is less than the timeout setted.

**Comment by Mizux** [comment]
did you try `SetTimeLimit` instead ?

https://github.com/google/or-tools/blob/4a0e9b1860276a021335aacb8b69e10a0d08942c/examples/tests/pywraplp_test.py#L89

**Comment by P00L** [comment]
Yes same result with `SetTimeLimit()`. 

Also noticed that the wall time start counting from the moment solver is instantiated instead of real simulation execution from the moment `Solve()` is invoked, as i thought.

To catch TIMEOUT I am using response code 6 marked with NOT_SOLVED

**Comment by P00L** [comment]
the stange thing is that if I run an example like [linear_programming]( https://github.com/google/or-tools/blob/stable/examples/python/linear_programming.py) if I specify `SetTimeLimit(1)` works correctly returning status code 6.

I'll try to better debug my model

**Comment by P00L** [comment]
After some test the problem seems not related to time out. I tried to remove `SetTimeLimit()` and execute a simulation with CLP_LINEAR_PROGRAMMING instead of GLOP_LINEAR_PROGRAMMING. CLP_LINEAR_PROGRAMMING gives solution optimal while GLOP_LINEAR_PROGRAMMING gives solution not solved (the timeout stated before )

**Comment by lperron** [comment]
Can you send us the model ? MPS or protobuf.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 4 déc. 2019 à 16:40, Paolo Fusari <notifications@github.com> a
écrit :

**Comment by yelinbao** [comment]
the same problem exists with java

**Comment by kyler1990** [comment]
I call the method solve() with timeout setting in java first time , it return not_solved. Then i call the solve() second time , it return feasible

**Comment by lperron** [comment]
cannot reproduce (no data). Reopen if needed.
