### ISSUE TITLE
How decrease number of "O" shifts in shift scheduling

### ISSUE THREAD

**Issue by asooft** [google/or-tools#1765]
Hello, 

Please, I would like to inquire about how I provide the number of "O" shifts for employees because the normal schedule is distributed every 4 weeks where there will be 4 "O" shift. Because I did not understand it and I do not understand how to modify it.

`  // Shift constraints on continuous sequence :
            //     (shift, hard_min, soft_min, min_penalty,
            // soft_max, hard_max, max_penalty)
            var shiftConstraints = new(int Shift, int HardMin, int SoftMin, int MinPenalty, int SoftMax, int HardMax, int MaxPenalty)[]
            {
            // One or two consecutive days of rest, this is a hard constraint.
            (0, 1, 1, 0, 2, 2, 0),
            // Between 2 and 3 consecutive days of night shifts, 1 and 4 are
            // possible but penalized.
            //(3, 1, 2, 20, 3, 4, 5),
            };`

`// Weekly sum constraints on shifts days:
            //     (shift, hardMin, softMin, minPenalty,
            // softMax, hardMax, maxPenalty)
            var weeklySumConstraints = new(int Shift, int HardMin, int SoftMin, int MinPenalty, int SoftMax, int HardMax, int MaxPenalty)[]
            {
            // Constraints on rests per week.
            (0, 1, 2, 7, 2, 3, 4),
            // At least 1 night shift per week (penalized). At most 4 (hard).
            //(3, 0, 1, 3, 4, 4, 0),
            };`
for what is in a particular problem I have such as the problem I explained above

**Comment by asooft** [comment]
Can any one tell me the solution?

**Comment by asooft** [comment]
i wait the solution? 
i want to build the table without "O" shifts??

**Comment by lperron** [comment]
Please stop spamming.
