### ISSUE TITLE
CVRP multiple demands at one location but only one truck to deliver all

### ISSUE THREAD

**Issue by nikosio** [google/or-tools#1767]
Can i use a dimension to count number of different vehicles (vehicle ID's) that pass from a node and contraint this dimension to be at most one ?

**Comment by lperron** [comment]
Just force the vehicle vars of the duplicated nodes to be equal.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 5 déc. 2019 à 14:55, Nikos Iosifidis <notifications@github.com> a
écrit :
