### ISSUE TITLE
LP / MPS Exports Truncated

### ISSUE THREAD

**Issue by dnarayan** [google/or-tools#177]
When exporting a substantially large problem to the LP format, the text is truncated with a "..." which seems to be placed in the middle of the export.

Is this designed behavior - is it easy to change?

**Comment by hxd1011** [comment]
Can you use GLPK or LP SOLVE to make the model format transformation? Also would you please edit your post and remove the content of MPS file, it does not help for debugging.

Here is an example of using glpk to convert the model format to mps

![image](https://cloud.githubusercontent.com/assets/13385855/14864994/86c68856-0c8a-11e6-80b8-b79eef4734d2.png)

**Comment by dnarayan** [comment]
My apologies - the issue is not OR Tools at all. I was looking at the string in the Visual Studio debugger string visualizer, which truncates the string. When writing it to file, it appears correctly. Very sorry for the false report.
