### ISSUE TITLE
OverflowError: in method 'RoutingIndexManager_IndexToNode', argument 2 of type 'int64'

### ISSUE THREAD

**Issue by 07tiru07** [google/or-tools#1770]
below is my code
"""Simple Vehicles Routing Problem."""

from __future__ import print_function
from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp

from time import sleep 
import math
from itertools import combinations

CAB_CAPACITY = 3

def create_data_model():
    """Stores the data for the problem."""
    data = {}
    data['distance_matrix'] = [[0, 3614, 7213, 7922, 6945, 17943, 25253, 44904, 19478, 12146, 10706], [1978, 0, 8827, 9535, 8558, 14375, 21685, 41336, 17135, 9616, 9900], [8750, 8475, 0, 5111, 2256, 18204, 25514, 45165, 23544, 12430, 5373], [9873, 9599, 4337, 0, 4068, 29259, 36113, 55764, 27327, 8988, 9500], [9158, 8883, 1188, 5519, 0, 19182, 26492, 46143, 31177, 12837, 6351], [15747, 13832, 17938, 20517, 17670, 0, 11351, 31002, 5707, 20716, 14174], [25443, 23528, 27634, 37592, 27366, 11833, 0, 19659, 10617, 30911, 23870], [43364, 41449, 45555, 55513, 45287, 29754, 22700, 0, 28548, 48832, 41791], [18383, 16377, 30329, 27249, 30061, 5714, 8952, 28612, 0, 20567, 19746], [7560, 7230, 14408, 11327, 14139, 20271, 27125, 46776, 18339, 0, 17084], [12745, 10830, 5333, 9858, 7002, 14716, 22026, 41677, 20056, 17176, 0]]
    # data['num_vehicles'] = 2
    # data['starts'] = [1, 3]
    # data['ends'] = [0, 0]
    return data

# def print_solution(data, manager, routing, solution):
#     """Prints solution on console."""
#     max_route_distance = 0
#     for vehicle_id in range(data['num_vehicles']):
#         index = routing.Start(vehicle_id)
#         plan_output = 'Route for vehicle {}:\n'.format(vehicle_id)
#         route_distance = 0
#         while not routing.IsEnd(index):
#             plan_output += ' {} -> '.format(manager.IndexToNode(index))
#             previous_index = index
#             index = solution.Value(routing.NextVar(index))
#             route_distance += routing.GetArcCostForVehicle(
#                 previous_index, index, vehicle_id)
#         plan_output += '{}\n'.format(manager.IndexToNode(index))
#         plan_output += 'Distance of the route: {}m\n'.format(route_distance)
#         print(plan_output)
#         max_route_distance = max(route_distance, max_route_distance)
#     print('Maximum of the route distances: {}m'.format(max_route_distance))

def print_solution(data, manager, routing, assignment):
    """Prints assignment on console."""
    total_distance = 0
    total_load = 0
    for vehicle_id in range(data['num_vehicles']):
        index = routing.Start(vehicle_id)
        plan_output = 'Route for vehicle {}:\n'.format(vehicle_id)
        route_distance = 0
        route_load = 0
        while not routing.IsEnd(index):
            node_index = manager.IndexToNode(index)
            route_load += data['demands'][node_index]
            plan_output += ' {0} Load({1}) -> '.format(node_index, route_load)
            previous_index = index
            index = assignment.Value(routing.NextVar(index))
            route_distance += routing.GetArcCostForVehicle(
                previous_index, index, vehicle_id)
        plan_output += ' {0} Load({1})\n'.format(manager.IndexToNode(index),
                                                 route_load)
        plan_output += 'Distance of the route: {}m\n'.format(route_distance)
        plan_output += 'Load of the route: {}\n'.format(route_load)
        print(plan_output)
        total_distance += route_distance
        total_load += route_load
    print('Total distance of all routes: {}m'.format(total_distance))
    print('Total load of all routes: {}'.format(total_load))

def main():
    """Entry point of the program."""
    # Instantiate the data problem.
    data = create_data_model()
    print(data)

    # Running for loop to check for each possible way to find the route 
    print("No of dropoff/pickup points", len(data['distance_matrix']))
    no_of_employees = len(data['distance_matrix']) - 1
    no_of_cabs = math.ceil(no_of_employees / CAB_CAPACITY)
    print("no of employees", no_of_employees)
    print("no of cabs", no_of_cabs)
    ends = [0]*no_of_cabs
    starts = list(range(1,no_of_employees))
    print("starts",starts)
    print("ends",ends)

    list_of_start_combinations = list(combinations(starts,no_of_cabs))
    print("combinations",list_of_start_combinations)

    data['ends'] = ends
    data['num_vehicles'] = no_of_cabs
    data['demands'] = [1]*no_of_employees
    print("demand", data['demands'])
    data['vehicle_capacities'] = [CAB_CAPACITY]*no_of_cabs
    print("vehicle_capacities", data['vehicle_capacities'])

    for start in list_of_start_combinations:
        data['starts'] = start
        print("start", start)
        # Create the routing index manager.
        manager = pywrapcp.RoutingIndexManager(len(data['distance_matrix']),
                                            data['num_vehicles'], data['starts'],
                                            data['ends'])

        # Create Routing Model.
        routing = pywrapcp.RoutingModel(manager)
        print(routing)

        # Create and register a transit callback.
        def distance_callback(from_index, to_index):
            """Returns the distance between the two nodes."""
            # Convert from routing variable Index to distance matrix NodeIndex.
            from_node = manager.IndexToNode(from_index)
            to_node = manager.IndexToNode(to_index)
            return data['distance_matrix'][from_node][to_node]

        transit_callback_index = routing.RegisterTransitCallback(distance_callback)

        # Define cost of each arc.
        routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

        # Add Distance constraint.
        dimension_name = 'Distance'
        routing.AddDimension(
            transit_callback_index,
            0,  # no slack
            5000000,  # vehicle maximum travel distance
            True,  # start cumul to zero
            dimension_name)
        distance_dimension = routing.GetDimensionOrDie(dimension_name)
        distance_dimension.SetGlobalSpanCostCoefficient(100)

        #Added the capacity constraint
        # Add Capacity constraint.
        def demand_callback(from_index):
            """Returns the demand of the node."""
            # Convert from routing variable Index to demands NodeIndex.
            from_node = manager.IndexToNode(from_index)
            return data['demands'][from_node]

        demand_callback_index = routing.RegisterUnaryTransitCallback(
            demand_callback)
        routing.AddDimensionWithVehicleCapacity(
            demand_callback_index,
            0,  # null capacity slack
            data['vehicle_capacities'],  # vehicle maximum capacities
            True,  # start cumul to zero
            'Capacity')

        # Setting first solution heuristic.
        search_parameters = pywrapcp.DefaultRoutingSearchParameters()
        search_parameters.first_solution_strategy = (
            routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)

        print('search parameters', search_parameters)

        # Solve the problem.
        solution = routing.SolveWithParameters(search_parameters)
        print('solution', solution)

        # Print solution on console.
        if solution:
            print_solution(data, manager, routing, solution)

if __name__ == '__main__':
    main()

**Comment by lperron** [comment]
Strange, I just ran your model, without any problem.

**Comment by Mizux** [comment]
seems to be a duplicate of #1890
