### ISSUE TITLE
Unable to add constraint for a node in PickupDelivery VRP

### ISSUE THREAD

**Issue by Nikhil-Vashishtha** [google/or-tools#1771]
Hi community,
I need some guidance.
I am solving Pickup Delivery VRP, and need to visit a particular node (not in pickup delivery list) to be visited just before depot while route completes, for stocktaking and other management purposes.
But I am unable to do it with the constraint:-
```
routing.solver().Add(
	routing.NextVar(manager.NodeToIndex(18)) == manager.NodeToIndex(17))
```
where, 17 is depot, and 18 is the node which I need to visit.

Any pointers would be appreciated.
Thanks

**Comment by CervEdin** [comment]
Is the issue the model becomes unsatisfiable?

**Comment by Nikhil-Vashishtha** [comment]
No, the the last location is depot only.
I need to add one separate node in the middle.
Or is it that I can't reference the depot in NextVar from earlier node, when it is dong closed loop?!

**Comment by Nikhil-Vashishtha** [comment]
Was able to solve using duplicate nodes.

Thanks
