### ISSUE TITLE
clustering for clusters with different sizes

### ISSUE THREAD

**Issue by finalight** [google/or-tools#1772]
Given in the python example for clustering, I notice that it's trying to cluster 40 cities into 4 equal groups.

is it possible to group number of elements into X groups such that each group might contain different number of elements?

I tried to change the value for the example and it will throw me an error stating that list index(0) is out of range, not sure which part I need to change in order to able to have clusters of different sizes, or is it not possible at all...

**Comment by lperron** [comment]
It is. You need to look at the model.

Le lun. 9 déc. 2019 à 06:06, Lee Zhen Jie <notifications@github.com> a
écrit :

**Comment by finalight** [comment]
Hi, I don't understand which part of the model to change to have different clusters having different number of elements.

**Comment by lperron** [comment]
I thought it was obvious from the code:

        # Number of groups to split the nodes, must divide num_nodes.
        num_groups = 4
        group_size = num_nodes // num_groups

        # Number of neighbors:
        for n in range(num_nodes):
            model.Add(sum(neighbors[m, n] for m in range(n)) + 
                      sum(neighbors[n, m] for m in range(n + 1, num_nodes)) ==
                      group_size - 1)

**Comment by lperron** [comment]
This being said, the problem become complex.
You will need to make sure that:

1. all nodes are within a group of respectable size (easy with the constraint above)

1. you will need to constrain the number of groups, which implies counter the number of distinct groups. This will be challenging
