### ISSUE TITLE
StackOverflowException for constraint involving a large sum

### ISSUE THREAD

**Issue by abeham** [google/or-tools#1773]
I have a bigger sum that I am creating when building the model. It consists of more than 30000 products of a variable and a constant. I add them to a big linear expression as in the following example (using C#):

```csharp
Variable[][][][] x;
double[] someconst;
// initialization of x and someconst
var someVariable = model.MakeNumVar(0, double.PositiveInfinity, "s");
var sum = new LinearExpr();
foreach (var dim1 in dimension1) /* ... */ foreach (var dim4 in dimension4) {
  sum += x[dim1]/*...*/[dim4] * someconst[dim1];
}
model.Add(someVariable == sum);
```

I receive a StackOverflowException when executing `model.Add(...)`, but probably emerging from C++ code - it can't be caught with VS 2019. It's a .NET Core 2.1 project.

**Comment by lperron** [comment]
Please use the constraint API.

MakeConstraint, SetCoefficient.

In the meantime, if you can send me a fill model to reproduce, please do.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 9 déc. 2019 à 14:17, Andreas Beham <notifications@github.com> a
écrit :

**Comment by abeham** [comment]
Thanks that solves the problem!
