### ISSUE TITLE
SIGSEGV: Problematic Frame C [libortools.so...]

### ISSUE THREAD

**Issue by arukhin** [google/or-tools#1774]
I have received the following error for some (but not all?) parameter choices:
A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f7340daba77, pid=52049, tid=0x00007f746e2c4700

JRE version: Java(TM) SE Runtime Environment (8.0_231-b11) (build 1.8.0_231-b11)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.231-b11 mixed mode linux-amd64 compressed oops)
Problematic frame:
C  [libortools.so+0x756a77]  void std::__introsort_loop<__gnu_cxx::__normal_iterator<operations_research::RoutingDimension**, std::vector<operations_research::RoutingDimension*, std::allocator<operations_research::RoutingDimension*> > >, long, __gnu_cxx::__ops::_Iter_comp_iter<operations_research::RoutingModel::GetOrCreateLocalSearchFilters()::{lambda(operations_research::RoutingDimension const*, operations_research::RoutingDimension const*)#3}> >(__gnu_cxx::__normal_iterator<operations_research::RoutingDimension**, std::vector<operations_research::RoutingDimension*, std::allocator<operations_research::RoutingDimension*> > >, __gnu_cxx::__ops::_Iter_comp_iter<operations_research::RoutingModel::GetOrCreateLocalSearchFilters()::{lambda(operations_research::RoutingDimension const*, operations_research::RoutingDimension const*)#3}>, long, __gnu_cxx::__ops::_Iter_comp_iter<operations_research::RoutingModel::GetOrCreateLocalSearchFilters()::{lambda(operations_research::RoutingDimension const*, operations_research::RoutingDimension const*)#3}>)+0x187

OS: Ubuntu Linux 16.04
The routing solver runs fine with three or four vehicles. Consistently crashes with five or more.

On windows 10, there was no problem with up to twenty vehicles (identical code)...

The associated log file is attached.
[hs_err_pid52049.log](https://github.com/google/or-tools/files/3940415/hs_err_pid52049.log)

**Comment by lperron** [comment]
Increase the java memory size.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 9 déc. 2019 à 16:35, Andrey Rukhin <notifications@github.com> a
écrit :

**Comment by arukhin** [comment]
it is not a memory issue (see attached).  Reverting to 7.3 solves the problem

[hs_err_pid5592.log](https://github.com/google/or-tools/files/3941456/hs_err_pid5592.log)

**Comment by lperron** [comment]
Can you send me a code to reproduce the problem ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 9 déc. 2019 à 20:46, Andrey Rukhin <notifications@github.com> a
écrit :
