### ISSUE TITLE
How can Iimit type of shifts for each nurse

### ISSUE THREAD

**Issue by anooplogicplum** [google/or-tools#1775]
I have 5 types of shifts M6-4,M7-3,M9-2,M9-5,M10-6. I want to assign each nurse only two types out of these 5 shifts. So Nurse N1 would work on M6-4 & M9-2 for the week while N2 will only work M7-3 & M10-6. 

I tried many methods without success. Is there a method where I can find the unique shift types and limit them to two ? Can anyone please help ?

**Comment by lperron** [comment]
The usual trick

``
all_shift_types_used = []
for each shift_type:
  shift_is_used = model.NewBoolVar('')
  all_shifts_of_this_type = # Collect them
  model.AddBoolOr(all_shifts_of_this_type).OnlyEnforceIf(shift_is_used)
  for shift_literal in all_shifts_of_this_type:
    model.AddImplication(shift_literal, shift_is_used)
  all_shift_types_used.append(shift_is_used)

model.Add(sum(all_shift_types_used) <= 2)
``
