### ISSUE TITLE
VRP Pick-Delivery constraints

### ISSUE THREAD

**Issue by lcluz** [google/or-tools#1776]
Hi,
I would like to know if it possible to add some constraints to the pick-delivery VRP problem in a way that:
1. it would have to do a certain number of pick-delivery "jobs", i.e., go to a pick and deliver to a delivery more than once;
2. 2 vehicles couldn't do a pick-delivery at the same time;
3. give priorities to the most important jobs; 
4. not go to a depot in between.

I would assume it would have to be done with a Time dimension.
For 1 I tried to do this with capacity, in which the demand is higher than the vehicle capacity, but I got no solution.

Any hints if this is even possible?

**Comment by lcluz** [comment]
Got the answer for point 4: add a dummy node, which is a done that is at time 0 from all nodes.

For 1 and 2: I ended up duplicating a node for a number of times to be able to do that pick-delivery several times per route. But this would allow for different vehicles to do the same pick-delivery at the same time, which is something I don't want. So I just added the following condition:

```
    data['equivalents']=[[0,1,2,3,4,5,6,7,8,9,],[10,11,12,13,14,15,16],[17,18,19,20,21]]
    for equivalent in data['equivalents']:
        for i in range(len(equivalent)):
            for j in equivalent[i + 1:]:
                routing.solver().Add(
                    time_dimension.CumulVar(manager.IndexToNode(j)) >
                    time_dimension.CumulVar(manager.IndexToNode(equivalent[i])))
```
in which each vector inside the "equivalents" data are the nodes that represent the same pick-point(delivery points come right after pick up, so no need to do those).

This is not giving any result, in fact it seem that the program is in an endless loop.
Anyone can help?

**Comment by lcluz** [comment]
I came to the conclusion that the problem here is that when I do the CumulVar it is only for one vehicle and not for all of them. Any way of doing a "global" CumulVar?

**Comment by Mizux** [comment]
* for same vehicle take a look at this https://gist.github.com/Mizux/9e37c370a459bd472a6ac13c304f0b54
* For one pickup at a time, you can try to modelise resource constraint using this: https://developers.google.com/optimization/routing/cvrptw_resources
