### ISSUE TITLE
Unable to drop nodes using penalty and disjunction in VRP

### ISSUE THREAD

**Issue by Nikhil-Vashishtha** [google/or-tools#1777]
Hi community,

I am solving pickup delivery VRP. There are some nodes from total 11 nodes which are not needed, as I have 4 pairs of pickup delivery and 1 depot.

```
data["pickups_deliveries"] = [[2,6],[5,9],[1,10],[3,8]]
data["depot"] = 0
```

I am trying to skip nodes 4, 7 using the following, but unable to.

```
penalty = 10000000
for node in [4,7]:
    routing.AddDisjunction([manager.NodeToIndex(node)], penalty)
```
Any pointers would be appreciated.

Thanks

**Comment by Nikhil-Vashishtha** [comment]
Solved, added the correct penalty.

Thanks

**Comment by sergiowang** [comment]
Your penalty is too small, which result in the model would drop the nodes rather than pick the node. (cost for picking up the node is larger than dropping the node). Try set penalty value larger.
