### ISSUE TITLE
How to use the value of SlackVar

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1778]
Hello,
For a given Dimension I'm wish to use the **value** of the SlackVar of a certain Node (during solving) in another condition on the same Dimension. 
I used:
  IntExpr Slk = model.SlackVar(model.Start(vehicle), "dim"); 
How do I use its value in the other condition: 
  model.CumulVar(Node_Index, "dim").SetMax(Slk * 10);

Advice would be appreciated.

**Comment by lperron** [comment]
This makes no sense.
SetMax() takes an integer value.

Slk is a variable.

You can write (approximate code):

    model.solver().Add(model.CumulVar(Node_Ondex, "dim") <= Slk * 10)

This being said, I do not understand the semantics of you equation.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
Exactly, I'm trying to have Solver() use the **value** of that expression.
What I just did and seems to work now, is:
IntVar Slk = model.SlackVar(model.Start(vehicle), "dim");
model.solver().Add(model.CumulVar(Node_Index, "dim") <= Slk.Value() * 10)

**Comment by lperron** [comment]
No. you cannot use Value(). Value() only makes sense if called from within
the search.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
Indeed, does not work.
I found a way that works by including both the cumulvar and the slackvar in the same condition.

Thanks
