### ISSUE TITLE
Or-tools failed to solver with error `Segmentation Fault` when adding dimension. 

### ISSUE THREAD

**Issue by tigrandp** [google/or-tools#178]
`routing.SolveWithParameters(parameters, None)`
starts failing after adding dimension to `RoutingModel`. Prior to adding this dimension I had two more and they worked just fine. One of which I added using `RoutingModel.AddDimensionWithVehicleCapacity` and another using `RoutingModel.AddDimension`.  But now after adding third one which is not different by the way of adding from the second one, solver starts failing with error 'Segmentation Fault' how can I find out more information what was wrong or is it my fault or I violated some assumption which I should have obeyed ?

**Comment by furnon** [comment]
What language are you using (C++, Java, Python, C#) ? Are you re-using
dimension callbacks ?

**Comment by tigrandp** [comment]
@furnon I am using Python. No I am nor re-using dimensions just creating new one.

**Comment by tigrandp** [comment]
I am just wondering whether you have some ability to add flag which will be responsible for stack trace printing ?
