### ISSUE TITLE
Solving multiple times with SolveWithSolutionCallback

### ISSUE THREAD

**Issue by DominikRoB** [google/or-tools#1780]
Hey,

when I tried to solve my model in succession with multiple objective functions, I noticed that calling 
SolveWithSolutionCallback(), after it already has been called once, does not work properly,
it ends after around 0.05 (+- 0.02 as far as I can tell) seconds walltime. (Even if I don't change anything about the model between the solver calls)

Solve() is not affected by this. I can call it before or after SolveWithSolutionCallback() and it works as expected. 

In a smaller working example, that reaches optimality way faster than the 0.05 seconds, everything seems normal.

Greetings,
DominikRoB

**Comment by stradivari96** [comment]
Do you reuse your callback? If so, could you try using a new instance?

**Comment by DominikRoB** [comment]
I tried - using a new instance of the SolutionPrinter does work out normally, but I lose my solution count, of course.

**Comment by stradivari96** [comment]
You could save it and initialize the new callback with the old count or just add them at the end

**Comment by DominikRoB** [comment]
Yes, I will do it like that now - It just seemed strange to me, that the repeated callback works fine for small problems, but not for larger ones.
