### ISSUE TITLE
How to Configure the gap in OR-tools Routing library

### ISSUE THREAD

**Issue by Adnanay** [google/or-tools#1783]
is there a way that i can set the gap of the `pywrapcp.RoutingModel()` in python, so that the solving process will terminate when a certain gap is reached (for example, something like `model.setParam(GRB.Param.MIPGap, 0.50)` in Gurobi).

**Comment by lperron** [comment]
THis makes no sense.

The routing library does not use GUrobi, and is not based on a MIP solver.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
