### ISSUE TITLE
VRP with Time Windows - More than 1 SOFT time window per location

### ISSUE THREAD

**Issue by Mazzjs** [google/or-tools#1784]
Hi guys,
thanks for this awesome library!

I have a situation where a location (or "customer") has two or more available time windows (let's say it's open in the morning, closed for siesta, and then open again until the evening). And these time windows are all soft, which means the location can be visited outside the time window but with a penalty ( let's say the time windows are the best time for visiting, other time is also available).

I learned about using "`SetCumulVarSoftLower/UpperBound`" as a soft constraint for time window. How can I add two with soft "OR" logic between them?

This problem is similar to #456, but I think the `NotMemberCt `is hard constraint.

thanks in advance,
Mazz

**Comment by lperron** [comment]
You can duplicate the nodes, assign different time window to each node, and
add all of them in a disjunction.
