### ISSUE TITLE
Pickup Delivery VRP revisit (multi-use) nodes

### ISSUE THREAD

**Issue by Nikhil-Vashishtha** [google/or-tools#1785]
Hi community,

I have a problem as follows:-

Need to visit the pickup delivery nodes with following conditions:-

1. If pickup made, must be delivered before next pickup. So constraint becomes:-
`
routing.solver().Add(
routing.NextVar(pickup_index) == delivery_index
)
`
2. A node can be revisited for another pickup-delivery job. So, pickup deliveries can be
`
pd_list = [[2, 3], [4, 7], [1, 9], [5,10], [4, 6]]
`
becomes:-
`
2->3
4->7
1->9
5->10
4->6
`
et cetera combined to optimize the distance.

My issue is how to add the pickup-delivery, 4->6, as node 4 is already visited.

Thanks and Regards

**Comment by lperron** [comment]
You nzedy to duplicate the nodes.
There are multiple discussions on this topic in the mailing list.

Le lun. 16 déc. 2019 à 07:42, nikhilvashishtha <notifications@github.com> a
écrit :
