### ISSUE TITLE
ImportError: undefined symbol: _threadnumber

### ISSUE THREAD

**Issue by sirily** [google/or-tools#1786]
Hello,
I've got python 3.8 as python3 in my system and python 3.7 virtual enviroment. I need to run or-tools in Jupyter notebook with kernel based on python 3.7 venv. What I did:
1. cloned repo 
2. make third_party
3. set UNIX_PYTHON_VER = 3.7 and UNIX_SCIP_DIR = /usr/scipoptsuite-6.0.2 in Makefile.local
4. make python_package
5. activated venv, cd into wheel package dir (or-tools/temp_python3.7/ortools/)
6. pip install . 
Got "Successfully installed ortools-7.4.7384" answer

So ortools now into my venv/lib/python3.7/site-packages

But when I've tried to import pywraplp, I've got that error: 

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-9cb27b840291> in <module>
----> 1 from ortools.linear_solver import pywraplp
      2 import numpy as np
      3 import pandas as pd
      4 from get_cost import score

~/py37/lib/python3.7/site-packages/ortools/linear_solver/pywraplp.py in <module>
     11 # Import the low-level C/C++ module
     12 if __package__ or "." in __name__:
---> 13     from . import _pywraplp
     14 else:
     15     import _pywraplp

ImportError: /home/satellite/py37/lib/python3.7/site-packages/ortools/linear_solver/../../ortools/.libs/libortools.so: undefined symbol: _threadnumber
```

System: Manjaro Linux 5.4.2-1
Python: Python 3.7.5
Jupyter: jupyter core     : 4.6.1
              ipython          : 7.10.1
              ipykernel        : 5.1.3
              jupyter client   : 5.3.4
Or-tools: ortools-7.4.7384

**Comment by lperron** [comment]
Can you try without scip ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by sirily** [comment]
Yep, it works without scip. But all this troubles were because I need scip, otherwise I'd install or-tools through pip without dealing with source files. Can you suggest me how to use third party solver? I had troubles with glpk before, and now or-tools with scip don't work either

**Comment by sirily** [comment]
Managed to build or-tools with scipoptsuite-6.0.0. Does scip-6.0.2 really support? This version wrote in Makefile.local, but I didn't find it in changelog.
Also I couldn't built or-tools with glpk-4.65. Did [this](http://or-tools.blogspot.com/2017/03/linking-glpk-with-or-tools-on-unix.html), but got that error:

`/usr/bin/ld: /usr/glpk-4.65/lib/libglpk.a(libglpk_la-tls.o): relocation R_X86_64_TPOFF32 against `tls' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/glpk-4.65/lib/libglpk.a(libglpk_la-stdc.o): relocation R_X86_64_TPOFF32 against `result.4373' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/glpk-4.65/lib/libglpk.a(libglpk_la-env.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make: *** [makefiles/Makefile.cpp.mk:177: lib/libortools.so] Error 1`

I've seen [issue](https://github.com/google/or-tools/issues/1459) where glpk-4.65 was used, but I can't find any information about installation except lperron's blogpost. What did I do wrong?

**Comment by lperron** [comment]
glpk: you need to add -fPIC to the build arguments. Something to pass to
./configure.  I would not use it. performance is bad.

scip: make sure that you are loading the right DLLs. I recommend building
SCIP with the parameters described in the Makefile.local.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by chenwt-87** [comment]
hello!  have you fixed the problem of " undefined symbol:  _threadnumber"?    I 've got the same problem on Linux,  with the SCIP complied on "Make TPI=tny".

**Comment by lperron** [comment]
No, this is why SCIP on linux is not compiled with thread support on linux.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by lperron** [comment]
I just fixed it on master.

**Comment by chenwt-87** [comment]
thx very much ， I'll try it

**Comment by chenwt-87** [comment]
> I just fixed it on master.

hello, I. just download the branch of master ， and tried a simple case。

it returns error as follows ：
[syncstore.c:72] ERROR: Error <0> in function call
[scip_general.c:245] ERROR: Error <0> in function call
[scip_general.c:289] ERROR: Error <0> in function call
[syncstore.c:88] ERROR: Error <0> in function call
[scip_general.c:331] ERROR: Error <0> in function call
solve failed
Time =  0.0108 seconds
[syncstore.c:72] ERROR: Error <0> in function call
[scip_general.c:245] ERROR: Error <0> in function call
[scip_general.c:289] ERROR: Error <0> in function call
[syncstore.c:88] ERROR: Error <0> in function call
[scip_general.c:331] ERROR: Error <0> in function call
[scip_solve.c:3381] ERROR: invalid SCIP stage <13>
[scip_prob.c:704] ERROR: Error <-8> in function call
[scip_general.c:325] ERROR: Error <-8> in function call
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0717 04:33:20.859619 84210 scip_interface.cc:263] Check failed: SCIPfree(&old_scip) == SCIP_OKAY (-8 vs. 1) 
*** Check failure stack trace: ***


=====================
and the code is like below：
from ortools.linear_solver import pywraplp
#from ortools.algorithms import pywrapknapsack_solver
#from ortools.linear_solver import linear_solver_pb2
import time
import numpy as np


def main():
    # Data
    start = time.time()

    # costs = [[90, 76, 75, 70, 50, 74],
    #       [35, 85, 55, 65, 48, 101],
    #       [125, 95, 90, 105, 59, 120],
    #       [45, 110, 95, 115, 104, 83],
    #       [60, 105, 80, 75, 59, 62],
    #       [45, 65, 110, 95, 47, 31],
    #       [38, 51, 107, 41, 69, 99],
    #       [47, 85, 57, 71, 92, 77],
    #       [39, 63, 97, 49, 118, 56],
    #       [47, 101, 71, 60, 88, 109],
    #       [17, 39, 103, 64, 61, 92],
    #       [101, 45, 83, 59, 92, 27]]
    # costs = np.random.randint(50, 68, size=(30, 20))

    costs = [[65, 64, 61, 55, 63, 60, 62, 52, 53, 62, 64, 5, 56, 52, 64, 66, 58, 57 ,57, 54],
     [53,63,66,54,52,62,63,65,53,64,62,59,59,60,64,55,54,60,52,56],
     [66,59,54,61,56,61,65,55,54,58,50,56,57,65,65,65,54,54,62,55],
     [52,51,50,58,50,55,56,63,54,65,53,55,62,57,51,66,63,66,67,66],
     [66,58,65,61,62,50,57,59,64,52,67,64,65,59,53,51,63,51,53,53],
     [58,66,59,61,67,67,52,54,51,50,64,53,53,63,62,62,55,67,56,63],
     [58,55,59,65,65,52,51,65,61,52,52,65,64,53,64,50,55,58,63,59],
     [58,57,58,64,54,66,62,66,59,53,53,50,56,65,50,59,60,52,55,57],
     [53,52,57,54,52,57,58,58,55,60,52,51,50,52,57,51,50,55,67,53],
     [50,56,51,54,65,58,50,59,53,63,65,59,58,67,59,63,52,60,63,51],
     [59,62,64,64,54,52,64,50,51,53,61,67,52,52,65,61,50,50,58,62],
     [65,60,58,54,62,50,65,51,56,57,67,67,65,61,60,60,65,67,57,57],
     [58,54,61,55,65,56,56,59,60,52,63,61,56,66,59,50,55,56,57,61],
     [66,64,55,65,51,57,60,52,52,55,51,67,66,57,62,56,66,52,56,64],
     [67,52,66,61,64,65,60,52,63,54,51,50,67,60,62,51,59,63,60,58],
     [57,61,63,64,50,53,61,59,58,55,57,65,67,61,60,57,63,64,54,53],
     [52,61,53,63,53,62,50,60,53,60,54,53,53,60,56,60,65,60,63,52],
     [67,60,54,61,63,61,52,59,64,50,64,67,54,52,67,57,67,62,55,55],
     [60,51,52,57,60,61,65,58,63,63,65,57,52,52,63,56,66,65,62,51],
     [53,64,54,53,65,57,54,67,67,52,50,50,62,66,66,54,66,65,67,59],
     [62,61,50,57,58,67,58,64,66,52,60,50,64,57,64,67,54,50,66,62],
     [58,58,52,59,55,55,53,54,60,53,50,59,65,55,51,57,58,63,52,53],
     [57,60,53,66,55,66,64,65,60,66,58,66,56,64,58,67,64,55,57,56],
     [55,63,66,64,61,54,57,59,51,57,65,59,60,63,57,67,66,59,55,56],
     [50,54,54,51,62,66,65,56,66,65,54,66,63,54,51,56,67,63,58,66],
     [60,67,64,57,56,55,59,63,59,58,56,56,66,58,57,63,59,54,63,65],
     [65,55,62,54,56,58,66,60,61,63,53,56,67,66,64,55,52,55,66,65],
     [57,57,67,62,67,56,67,52,58,61,52,53,53,67,60,62,61,50,58,57],
     [59,60,56,59,51,64,58,52,63,65,59,51,53,50,56,55,66,59,57,56],
     [64,50,56,61,50,63,53,61,57,60,53,56,66,52,50,62,65,64,50,63]]


    # print(costs)
    num_workers = len(costs)
    num_tasks = len(costs[0])

    # Solver
    # Create the mip solver with the SCIP backend.
    # solver = pywraplp.Solver.CreateSolver('CBC')
    solver = pywraplp.Solver('simple_mip1_program',
                             pywraplp.Solver.SCIP_MIXED_INTEGER_PROGRAMMING)

    # Variables
    # x[i, j] is an array of 0-1 variables, which will be 1
    # if worker i is assigned to task j.
    x = {}
    for i in range(num_workers):
        for j in range(num_tasks):
            x[i, j] = solver.IntVar(0, 1, name='X_人员{}_任务{}'.format(i, j))

    # Constraints
    # Each worker is assigned to at most 1 task.
    for i in range(num_workers):
        solver.Add(solver.Sum([x[i, j] for j in range(num_tasks)]) <= 1, name='人员接单约束_{}'.format(i))

    # Each task is assigned to exactly one worker.
    for j in range(num_tasks):
        solver.Add(solver.Sum([x[i, j] for i in range(num_workers)]) == 1, name='任务被接约束_{}'.format(j))

    # Objective
    objective_terms = []
    for i in range(num_workers):
        for j in range(num_tasks):
            objective_terms.append(costs[i][j] * x[i, j])
    solver.Minimize(solver.Sum(objective_terms))
   .....

**Comment by lperron** [comment]
Did you rebuild SCIP or let the make third_party do it ?
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by chenwt-87** [comment]
I run the make third_party and make all

**Comment by chenwt-87** [comment]
I run the make third_party and make all

**Comment by lperron** [comment]
make clean_third_party clean

before ?

It ran fine on my machine.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by chenwt-87** [comment]
I tried again with the command of 
1、 make clean_third_party clean， 
2、 make third_party， 
3、make python
4、 make test_python 
but still met the error。   
does it related to the version of linux  of python ？

**Comment by lperron** [comment]
Indeed, it does not work in python.

I will continue to investigate.

Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by chenwt-87** [comment]
thank you vrey  much.

**Comment by lperron** [comment]
Note that it works if you use the cmake build.

**Comment by chenwt-87** [comment]
do you mean that use cmake to install the SCIP  ?  or use cmake to replace the "make third party"?

**Comment by lperron** [comment]
cmake to replace `make  third_party python`

mkdir build
cd build
cmake -DBUILD_PYTHON=ON ..
make

Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by chenwt-87** [comment]
I just tried with your command 
mkdir build
cd build
cmake -DBUILD_PYTHON=ON ..
make
make install_python


but still  raise the problem. " SCIP was compiled without task processing interface. Parallel solve not possible"
should I add some parameters in  "cmake -DBUILD_PYTHON=ON .. "  to enable TPI?

**Comment by Mizux** [comment]
Hi,
here the current update:
* CMake didn't enable the TPI aka compile SCIP with the multithread support disabled.
* BUT you can enable it changing this line
https://github.com/google/or-tools/blob/077a6fa29cb5edb16740d4e3cfa3bf4ecd82b492/cmake/dependencies/CMakeLists.txt#L89
to 
```cmake
 set(TPI "tny" CACHE STRING "Scip param") 
```

**Comment by chenwt-87** [comment]
> Hi,
> here the current update:
> 
> 1. CMake didn't enable the TPI aka we currently compile SCIP with the multi-thread support disabled.
> 2. BUT you can enable it changing this line
>    https://github.com/google/or-tools/blob/077a6fa29cb5edb16740d4e3cfa3bf4ecd82b492/cmake/dependencies/CMakeLists.txt#L89
>    
>    to
> 
> ```cmake
>  set(TPI "tny" CACHE STRING "Scip param") 
> ```
> 
> then compile using the classic:
> 
> ```shell
> cmake -S. -Bbuild -DBUILD_PYTHON=ON
> cmake --build build
> ```
> 
> 1. seems to work using cmake build
> 
> ```shell
> ./build/python/venv/bin/python ortools/linear_solver/samples/integer_programming_example.py
> initializing seeds to 1963210296 in concurrent solver 'scip-2'
> initializing seeds to 1332858414 in concurrent solver 'scip-3'
> initializing seeds to 1541326760 in concurrent solver 'scip-4'
> initializing seeds to 247360965 in concurrent solver 'scip-5'
> initializing seeds to 387742462 in concurrent solver 'scip-6'
> initializing seeds to 520723434 in concurrent solver 'scip-7'
> initializing seeds to 1176648445 in concurrent solver 'scip-8'
> starting solve in concurrent solver 'scip-5'
> starting solve in concurrent solver 'scip-1'
> starting solve in concurrent solver 'scip-7'
> starting solve in concurrent solver 'scip-6'
> starting solve in concurrent solver 'scip-4'
> starting solve in concurrent solver 'scip-2'
> starting solve in concurrent solver 'scip-8'
> starting solve in concurrent solver 'scip-3'
> concurrent solver 'scip-5' stopped with status optimal solution found
> concurrent solver 'scip-6' stopped with status optimal solution found
> concurrent solver 'scip-7' stopped with status optimal solution found
> concurrent solver 'scip-8' stopped with status optimal solution found
> concurrent solver 'scip-2' stopped with status optimal solution found
> concurrent solver 'scip-1' stopped with status optimal solution found
> concurrent solver 'scip-3' stopped with status optimal solution found
> concurrent solver 'scip-4' stopped with status optimal solution found
> Maximum objective function value = 35
> 
> x = 7
> y = 3
> z = 5
> ```
> 
> 1. Make use the SCIP make based build which seems borken
>    I'm currently working on migrating it to CMake based build for SCIP, I'll keep you posted of any advancement...
>    EDIT: seems to work on linux ! I'll try to do a patch ASAP this afternoon (Paris Time)

It dose works！ that‘s exciting！looking forward to the python pacakge～

**Comment by chenwt-87** [comment]
I’ve found the  package  "ortools-9.0.9125-cp39-cp39-linux_x86_64.whl"  in the path '/or-tools/build/python/dist/',
and  it works  via  pip install ortools-9.0.9125-cp39-cp39-linux_x86_64.whl
