### ISSUE TITLE
Get the Index of a vehicle's Start Node

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1789]
I'm trying to get from solver the 64b index value of a vehicle's Start Node, by identifying the vehicle using the Index of a Node that solver is trying to visit. for using this value in constraints.

```
long Start_Node = model.Start((int)model.VehicleVar(Node_Index).Value())
```
It fails during compilation. Why?

Thx

**Comment by GuyBenhaim** [comment]
Any tips?

**Comment by GuyBenhaim** [comment]
Hello, When solver aims to include a certain Node in a **certain Route/Vehicle** can the solver extract the Start-Node of  **that vehicle**, during this calculation, and use it in a constraint that conditions whether inclusion is allowed or not?

**Comment by lperron** [comment]
Note that github issues have limited audience.
For these questions, I would ask the mailing list.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
Thx, how do I do that?

**Comment by GuyBenhaim** [comment]
found it.
