### ISSUE TITLE
VRP with multiple soft time windows per location

### ISSUE THREAD

**Issue by samfisher07** [google/or-tools#1790]
Hi all,

I would like to allow a delivery location to have multiple time windows. For example, over a 2 day horizon being available between 8am - 5pm on each day.

I found a solution to this (https://github.com/google/or-tools/issues/456):

```
solver = routing.solver()
solver.AddConstraint(
    solver.NotMemberCt(
        time_dimension.CumulVar(order), 
        forbidden_time_frame_starts, forbidden_time_frame_ends
    )
)
```
Which seems to allow for unavailable windows within a larger available time window?

I also require these time windows to be soft constraints and found a solution for this (https://groups.google.com/forum/#!topic/or-tools-discuss/7YqIEo2DA5w):

```
 routingModel.GetDimensionOrDie("timeDimension")
.SetCumulVarSoftLowerBoundFromIndex(index, node.TimeWindowFrom, APPOINTMENT_PENALTY_COEFFICIENT);
 routingModel.GetDimensionOrDie("timeDimension")
.SetCumulVarSoftUpperBoundFromIndex(index, node.TimeWindowTill, APPOINTMENT_PENALTY_COEFFICIENT);
```

Which makes the upper and lower bounds of the time window soft limits with a penalty multiplier. However this seems to be for a single time window.

Is there any way for these 2 functionalities to be used together to make multiple soft time windows for a single location? 

Any help on this issue would be greatly appreciated.

Regards,
Sam

**Comment by lperron** [comment]
Duplicate the node. Add a disjunction. Create a soft penalty for each node


Le mer. 18 déc. 2019 à 07:42, samfisher07 <notifications@github.com> a
écrit :

**Comment by samfisher07** [comment]
Thank you @lperron, much appreciated.

**Comment by samfisher07** [comment]
Hi all,

I found from my research into the AddDisjunction function that disjunctions may not be applied to the first or last node. How then would multiple soft time windows be applied to the first and last node? For example the depot departure and depot arrival time windows.

Also with implementing the the node duplication with disjunctions solution to the other nodes, does anyone know the performance impact compared to using a single time window with multiple forbidden and allowable time regions within it? My application may service thousands of nodes with multiple windows per node and I'm a bit concerned with the performance impact of this solution at that scale.

Thanks for any assistance.
Regards,
Sam

**Comment by lperron** [comment]
Please do not use GitHub issues. They have very limited visibility.

Le mer. 8 janv. 2020 à 08:40, samfisher07 <notifications@github.com> a
écrit :

**Comment by samfisher07** [comment]
Apologies, I'm new to GitHub. Where should I post this question? As a separate issue? Thought here would be best as it's part of the same issue.

**Comment by lperron** [comment]
or-tools-discuss mailing list.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 8 janv. 2020 à 10:24, samfisher07 <notifications@github.com> a
écrit :

**Comment by qiniuweihe** [comment]
Except create the same node through data and add disjunction, Is there a better way to solve this multi-soft time windows?
