### ISSUE TITLE
Vehicle specific constraint that can start with a given value

### ISSUE THREAD

**Issue by Akavall** [google/or-tools#1791]
I need to add constraint that is vehicle specific (similar to transit constraint), but is accumulates values similar to Capacity constraint.

For example, I am trying to add constraint on Draft (for vessel).

1. Each Vehicle starts with specific Draft
2. As cargo loaded on vehicle draft increases, but at different rates for each vehicle
3. Vehicle can only go to a port that has deeper water than the Draft the vehicle has after pickup.

What Dimensions is the best approach to tackle this problem?

Neither VehicleCapacity Dimension or VehicleTransits look right. I tried to make it work with both.

When I try VehicleCapacity, I don't see make changes in draft specific to a vehicle, and I don't see how in start a vehicle with specific draft to match the ports.

With VehicleTransit, since I can create callbacks specific to the vehicle, I can make changes to draft specific to the vehicle, but I don't see how to starting specific position. Also accumulation does work exactly like I want, I get a feeling that VehicleTransit dimension is not an ideal fit for this.

I found `DependentDimensionWithVehicleCapacity`, but I am not sure if that's what I need.

Let me know if I need to provide more information.

Any help appreciated.

**Comment by lperron** [comment]
For a given vehicle, what not have a new node, distance 0 from the depot,
with one 1 possible vehicle, that will set the initial value of the
dimension ?
And make sure that no other routing outgoing from the depot can be visited
by that vehicle .
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
