### ISSUE TITLE
Extend the span of a dimension

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1792]
Hello,
Is there a way to 'motivate' solver to extend the global span of a dimension?
I tried with a negative cost coefficient but, as expected, solver aborted.
Any tricks?
thx

**Comment by lperron** [comment]
Increase the cost of vehicles?

**Comment by GuyBenhaim** [comment]
Interesting perspective!  You mean the fixed costs, relative to the Node penalties?

Actually, in most cases we use relatively high penalties - probably solver is already motivated to use the vehicles for as long as possible.

However, I'm looking to extend the span of a special dimension, which is not necessarily correlated with travel time.  Is there a way to force solver to maximize its CumulVar at the end Node?

**Comment by Mizux** [comment]
by adding a CumulVar soft **lower** bound on the end node i.e. vehicle has incentice to increase the CumulVar to reduce this extra cost....
