### ISSUE TITLE
VRP: Force a node to be delivered first by any vehicle

### ISSUE THREAD

**Issue by samfisher07** [google/or-tools#1793]
Hi all,

Is there a way to force a node to be delivered first? It can be on any vehicle but must be done as the first stop. The practical application is a delivery being missed the previous day and therefore must be the first stop today.

A possible solution would be setting the distance between the start_point and node to be 0, making the solver see it as most feasible. However this method is not necessarily guaranteed.

Furthermore making this a soft constraint with a configurable penalty would be ideal (Similar to the soft time window constraints).

Thanks in advance for any help!
Regards, 
Sam

**Comment by lperron** [comment]
add a dimension with a constant distance of one.
Force the cumulvar to be 1.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 19 déc. 2019 à 14:45, samfisher07 <notifications@github.com> a
écrit :

**Comment by samfisher07** [comment]
Thanks @lperron for the reply.
I'm a little confused as to how this works to make the node the first stop. Could you please link a small snippet of code implementing this?

**Comment by hklarner** [comment]
In Python:
```
def evaluator(index_start: int, index_dest: int):
            return 1
   
fix_start_cumul_to_zero = True
slack_max = 0
name = 'stop_sequence_dimension'
capacity = max_stops_per_vehicle
        
callback_index = routing_model.RegisterTransitCallback(evaluator)
routing_model.AddDimension(callback_index, slack_max, capacity, fix_start_cumul_to_zero, name)
stop_sequence_dimension = self.routing_model.GetDimensionOrDie(name)

stop_index = index_manager.NodeToIndex(stop_node)
cpsolver = routing_model.solver()
cpsolver.Add(stop_sequence_dimension.CumulVar(stop_index) == 1)
```

**Comment by samfisher07** [comment]
Thanks @hklarner, this makes perfect sense now. Much appreciated.
