### ISSUE TITLE
VRP/TSP as Sequence Dependent Production Scheduler

### ISSUE THREAD

**Issue by hpswalters** [google/or-tools#1794]
I've tested the VRP as a solver for the sequence-dependent line scheduling problem and it works very well.   I've substituted the distance matrix for a processing time matrix and it is very fast for 60 jobs on a single line.  I want to expand this to two production lines, each with different processing capabilities in terms of both run and set-up times.  The easiest way to do this would be with a separate processing time matrix.

If such a thing is possible, how would I do it?  This would be similar to modeling a VRP with two types of vehicle costs.  One where I have my own truck, and another that I outsource and pay for things like mileage, stop charges, unloading, loading, etc.

Any insights would be appreciated.
Thanks for these tools.  They have come in very handy

Regards,
hpsw

**Comment by hpswalters** [comment]
Thinking about this....
Would it be possible to write a Time_Calculator-Callback (instead of a Distance_Calculator_Callback) that simply looks up the values of the processing times I have?

**Comment by hpswalters** [comment]
This didn't work, at least the way I did it.  Any insights would be appreciated

**Comment by hklarner** [comment]
I don't know what a "the sequence-dependent line scheduling problem" is but I know how to create two dimensions (distance, time, whatever) and add to the routing model constraints on the cumulative values. Would that help you? What have you tried so far?

**Comment by lperron** [comment]
There are three example of sequence dependent scheduling in the examples.

The simplest one is jobshop with transitions in python.

**Comment by hpswalters** [comment]
hk, Laurent,
Thanks for the reply.  I will look in github for the example you provide.
I must have missed it.  I will let you know how that works

Again, thanks for the tools and this forum

**Comment by hpswalters** [comment]
I've have reviewed the python examples in the repository.  I didn't find one that looked like there was something related to "transitions" per Laurent.  I did see:

flexible_job_shop_sat.py
jobshop_ft06_distance_sat.py
jobshop_ft06_sat.py
jobshop_with_maintenance_sat.py
single_machine_scheduling_with_setup_release_due_dates_sat.py

The closest match is the single_machine_scheduling_with_setup_release_due_dates_sat.py.  In my case the release dates would all be 0, and the due dates would all be the end of the week (or as fast as possible).  

A little background:
The sequence-dependent line scheduling problem seeks to find a solution to the situation where, in an asset-intensive production operation,  the run times for a job on a line (many machines linked together but modeled as one) are fixed (regardless of order), but the set-up times vary according to the preceding job.  Thus, the data (durations and set-up) can be presented as a single matrix and this makes it ideal for a TSP/VRP problem set-up. 

As is frequently the case in production operations, I am typically not restricted to a single line.  Thus,   the next simplest case is a choice between two lines where the second line is, for example, slower than the first and the jobs have different (longer) durations and different (sequence-dependent) set-up times.  This results in a second matrix of duration and setup.  

Purpose/Application:
Not only is this an interesting problem but a practical one as well.  The situation I find myself in is training multiple production managers and supervisors to make quick decisions when unforeseen situations arise.  They lack the ability to run optimization models so I am attempting to develop a relatively straightforward ruleset to follow based on the optimization results.  I have solved this using a genetic algorithm but the solution time gets prohibitively long when there are more than 60 jobs (there are frequently over 100).  However, for a specific product group in the two line scenario, a rule set is beginning to emerge--Fill the remaining line capacity for the fastest line by selecting the largest job, then the smallest, then the second largest, then the second smallest and so on with a focus on vessel changes first and then color (sequence according to same size and color changes first since color changes are faster than size changes).  This has been counter intuitive for the scheduling staff who scheduled only according to size running the largest jobs first on the fastest line.  However, it is logical.  The algorithm is balancing run time and set-up time resulting in a situation where the "middle" jobs are sent to the second (slower line).  
My problem is that I need to run many, many scenarios for multiple product groups as different groups on different lines may have different rulesets.  The speed that the VRP works is about two orders of magnitude faster than the genetic algorithm, which is immensely helpful. 

Here is what I have tried...without success:
Constructing a Time_Difference callback for Line 2 where I add the time difference as an incremental time penalty -- time_difference(j,k) = time_line_2(j,k) - time_line_1(j,k).  Written out:  the time difference on line 2 difference for job k which was preceded by job j is the difference between the time on line 2 for job k preceded by job j and the time on line 1 for job k preceded by job j.  So far, this has always been greater than zero although I'm not sure that matters.   

Here is what I have tried:
# Create and register a duration callback for Line 1 - the fastest line
    def time_callback(from_index, to_index):
        """Returns the processing and setup time between the two jobs."""
        # Convert from routing variable Index to time matrix NodeIndex.
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return data['time_matrix'][from_node][to_node]

     transit_callback_index = routing.RegisterTransitCallback(time_callback)
     routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

     time_dif = 'Time_Dif'
     routing.AddDimension(
        transit_callback_index,
        for i in range(data['time_matrix'])
            for j in range(data['time_matrix'])
                 jobTime2(i,j) - jobTime1(i,j),  # time difference
        9999999,  # maximum time per line
        False,  # Don't force start cumul to zero.
        time_dif)
    time_dimension = routing.GetDimensionOrDie(time_dif)

    for line_id in range(data['num_lines']):
        index = routing.Start(line_id)
        time_dimension.CumulVar(index).SetRange(data['time_dif'][0][0],
                                                                                     data['time_dif'][0][1])

And from here I'm lost

Thanks for reading this far.  I'm sure I'm doing this wrong so any insights would be appreciated

Merry Christmas
