### ISSUE TITLE
Cost of Multiple Dimensions per vehicle using SetArcCostEvaluatorOfVehicle

### ISSUE THREAD

**Issue by BrunoCheLeonB** [google/or-tools#1795]
Hi,

I want to know if is possible to consider more than one cost (matrix cost) for the VRP problem. For example, I implement the basic VRP that minimize the distance (route) for each vehicle, using this code.

# General matrix
    def distance_callback(from_index, to_index):
        """Returns the distance between the two nodes."""
        # Convert from routing variable Index to distance matrix NodeIndex.
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return data['distance_matrix'][from_node][to_node]

    transit_callback_index = routing.RegisterTransitCallback(distance_callback)
     Define cost of each arc.

    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

     Add Distance constraint.
    dimension_name = 'Distance'
    routing.AddDimension(
        transit_callback_index,
        0,  # no slack
        3000,  # vehicle maximum travel distance
        True,  # start cumul to zero
        dimension_name)
    distance_dimension = routing.GetDimensionOrDie(dimension_name)
    distance_dimension.SetGlobalSpanCostCoefficient(100)`

If I add a new matrix cost per vehicle using the next code, the model will be consider the last matrix per vehicle or will be consider the basic matrix for all vehicle and the particular matrix per vehicle?

# Particular matrix
`
for vehicle_idx in range(data['n_vehicles']):
    def vehicle_cost_callback(from_index, to_index, i=vehicle_idx):
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return data['vehicle_costs'][i] * data['time_matrices'][i][from_node][to_node]
    cost_callback_index = routing.RegisterTransitCallback(vehicle_cost_callback)
    cost_callback_indices.append(cost_callback_index)
    routing.SetArcCostEvaluatorOfVehicle(cost_callback_index, vehicle_idx)

cost_dimension_name = 'Cost'
routing.AddDimensionWithVehicleTransits(
    cost_callback_indices,
    0,
    max_int,
    False,
    cost_dimension_name)`

Finally, if the answer is yes, how can I print both solution separate

Thank you so much !

**Comment by rahulkhankar** [comment]
Has anyone solved the problem of different costs for a different vehicle? Please give me the source code. I am failing again and again

def main():
    """Solve the CVRP problem."""
    # Instantiate the data problem.
    data = create_data_model()

    # Create the routing index manager.
    manager = pywrapcp.RoutingIndexManager(len(data['distance_matrix']),
                                           data['num_vehicles'], data['starts'],
                                           data['ends'])

    # Create Routing Model.
    routing = pywrapcp.RoutingModel(manager)
    cost_callback_indices=[]

    for vehicle_idx in range(data['num_vehicles']):
      def vehicle_cost_callback(from_index, to_index, i=vehicle_idx):
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return data['distance_matrix'][i][from_node][to_node]
      cost_callback_index = routing.RegisterTransitCallback(vehicle_cost_callback)
      cost_callback_indices.append(cost_callback_index)
      routing.SetArcCostEvaluatorOfVehicle(cost_callback_index, vehicle_idx)

    dimension_name = 'Cost'
    routing.AddDimensionWithVehicleTransits(
        cost_callback_indices,
        0,
        10000000,
        False,
        dimension_name)
    distance_dimension = routing.GetDimensionOrDie(dimension_name)
    distance_dimension.SetGlobalSpanCostCoefficient(100)


    # Add Capacity constraint.
    def demand_callback(from_index):
        """Returns the demand of the node."""
        # Convert from routing variable Index to demands NodeIndex.
        from_node = manager.IndexToNode(from_index)
        return data['demands'][from_node]

    demand_callback_index = routing.RegisterUnaryTransitCallback(
        demand_callback)
    routing.AddDimensionWithVehicleCapacity(
        demand_callback_index,
        0,  # null capacity slack
        data['vehicle_capacities'],  # vehicle maximum capacities
        True,  # start cumul to zero
        'Capacity')

    # Setting first solution heuristic.
    search_parameters = pywrapcp.DefaultRoutingSearchParameters()
    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)
    search_parameters.local_search_metaheuristic = LocalSearchMetaheuristic.TABU_SEARCH
    search_parameters.time_limit.seconds = 10
    search_parameters.log_search = True

    # Solve the problem.
    solution = routing.SolveWithParameters(search_parameters)

    # Print solution on console.
    if solution:
      print_solution(data, manager, routing, solution)

    else:
      print('No solution')

**Comment by Mizux** [comment]
https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/ortools/constraint_solver/routing.h#L893-L898

https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/ortools/constraint_solver/routing.cc#L1176-L1188

So as you can it will replace the previous "cost" i.e. you can only have **ONE** arc cost per vehicle...
