### ISSUE TITLE
VRP: How to choose random and assign random?

### ISSUE THREAD

**Issue by hklarner** [google/or-tools#1796]
The first solution strategy `FIRST_UNBOUND_MIN_VALUE` is a combination of the variable strategy `CHOOSE_FIRST_UNBOUND` and the value strategy `ASSIGN_MIN_VALUE`. Given the following variables strategies:
- CHOOSE_FIRST_UNBOUND
- CHOOSE_RANDOM,
- CHOOSE_MIN_SIZE_LOWEST_MIN
- CHOOSE_MIN_SIZE_HIGHEST_MIN
- CHOOSE_MIN_SIZE_LOWEST_MAX
- CHOOSE_MIN_SIZE_HIGHEST_MAX
- CHOOSE_PATH
and value strategies
- ASSIGN_MIN_VALUE
- ASSIGN_MAX_VALUE,
- ASSIGN_RANDOM_VALUE
- ASSIGN_CENTER_VALUE
exist for the CP solver, are the corresponding first solution strategies for the routing model?

**Comment by lperron** [comment]
Dues to the nature of the encoding of the circuit with the next variables.
Using these does not make sense.
You should trust the first solution heuristics and try all of them if
needed.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
