### ISSUE TITLE
Check failed: SolutionIsFeasible in CP-SAT solver

### ISSUE THREAD

**Issue by jesenko** [google/or-tools#1797]
When solving large scheduling problem, CP-SAT solver sporadically fails with following error when improving soluition:

```
Check failed: SolutionIsFeasible( model_proto, std::vector<int64>(response->solution().begin(), response->solution().end())) main solver
*** Check failure stack trace: ***
    @     0x7ff734f0446c  google::LogMessage::Fail()
    @     0x7ff734f043b4  google::LogMessage::SendToLog()
    @     0x7ff734f03cf5  google::LogMessage::Flush()
    @     0x7ff734f075ac  google::LogMessageFatal::~LogMessageFatal()
    @     0x7ff735a0edf4  _ZNSt17_Function_handlerIFvPN19operations_research3sat16CpSolverResponseEEZNS1_12SolveCpModelERKNS1_12CpModelProtoEPNS1_5ModelEEUlS3_E0_E9_M_invokeERKSt9_Any_dataOS3_
    @     0x7ff735a0c620  _ZZN19operations_research3sat12SolveCpModelERKNS0_12CpModelProtoEPNS0_5ModelEENKUlRKNS0_16CpSolverResponseEE2_clES8_
    @     0x7ff735b2a649  operations_research::sat::SharedResponseManager::NewSolution()
    @     0x7ff735a10136  _ZZN19operations_research3sat12_GLOBAL__N_19LnsSolver12GenerateTaskElENKUlvE_clEv
    @     0x7ff735b2463c  _ZNSt17_Function_handlerIFvvEZN19operations_research3sat20NonDeterministicLoopERKSt6vectorISt10unique_ptrINS2_9SubSolverESt14default_deleteIS5_EESaIS8_EEiEUlvE_E9_M_invokeERKSt9_Any_data
    @     0x7ff73580ed8f  operations_research::RunWorker()
    @     0x7ff73756266f  (unknown)
    @     0x7ff73aa666db  start_thread
    @     0x7ff73ad9f88f  clone
    @              (nil)  (unknown)
```

When exception occurs, solver has already found some viable solutions.

I have attached model and solver protobuf. I was not (yet) able to pinpoint exact failure scenario... The model corresponds to shift scheduling problem with lot's of constraints and various optimality criteria, which is solved by LNS (thus most of variables are fixed to current best solution).

I got failure on current release (7.4) and current master.

[protobufs.zip](https://github.com/google/or-tools/files/3988740/protobufs.zip)

**Comment by lperron** [comment]
Thanks. We will have a look.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 20 déc. 2019 à 15:50, Simon Jesenko <notifications@github.com> a
écrit :

**Comment by timothylowjc** [comment]
Hello!

Just to upvote, I've run into this as well but with basically no stacktrace.

> Check failed: SolutionIsFeasible( model_proto, std::vector<int64>(response->solution().begin(), response->solution().end())) main solver
*** Check failure stack trace: ***
    @     0x7f2ad77d5100  (unknown)
    @     0x7f2ad77d505c  (unknown)
    @     0x7f2ad77d49c0  (unknown)
    @     0x7f2ad77d7df6  (unknown)
    @     0x7f2ad4cb3334  (unknown)
    @     0x7f2ad4cb0daf  (unknown)
    @     0x7f2ad4dc1fb1  (unknown)
    @     0x7f2ad4cb106d  (unknown)
    @     0x7f2ad4d5a60d  (unknown)
    @     0x7f2ad4d623b6  (unknown)
    @     0x7f2ad4cb1b3d  (unknown)
    @     0x7f2ad4cb1ce1  (unknown)
    @     0x7f2ad4dbb24c  (unknown)
    @     0x7f2ad4acb938  (unknown)
    @     0x7f2ad50f22ff  (unknown)
    @     0x7f2af9de76db  (unknown)
    @     0x7f2afa12188f  (unknown)
    @              (nil)  (unknown)

**Comment by lperron** [comment]
I need the model. Just a stack trace is not helping :-)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 6 févr. 2020 à 09:18, timothylowjc <notifications@github.com> a
écrit :

**Comment by timothylowjc** [comment]
Hi @lperron ,

Sorry about that! I thought I uploaded it.

[modelproto060220.txt](https://github.com/google/or-tools/files/4164633/modelproto060220.txt)


```
Solution 0, time = 1.756389 s, objective = 896590
Solution 1, time = 1.820084 s, objective = 897230
Solution 2, time = 1.849225 s, objective = 1095520
Solution 3, time = 1.892417 s, objective = 1296590
Solution 4, time = 1.925148 s, objective = 1690670
Solution 5, time = 1.958907 s, objective = 1789110
Solution 6, time = 1.991129 s, objective = 1887680
Solution 7, time = 2.016758 s, objective = 1888320
Solution 8, time = 2.042712 s, objective = 1888470
Solution 9, time = 2.076233 s, objective = 1893200
Solution 10, time = 2.448016 s, objective = 1990680

Check failed: SolutionIsFeasible( model_proto, std::vector<int64>(response->solution().begin(), response->solution().end())) main solver
*** Check failure stack trace: ***
    @     0x7f9c17fd5100  (unknown)
    @     0x7f9c17fd505c  (unknown)
    @     0x7f9c17fd49c0  (unknown)
    @     0x7f9c17fd7df6  (unknown)
    @     0x7f9c154b3334  (unknown)
    @     0x7f9c154b0daf  (unknown)
    @     0x7f9c155c1fb1  (unknown)
    @     0x7f9c154b106d  (unknown)
    @     0x7f9c1555a60d  (unknown)
    @     0x7f9c155623b6  (unknown)
    @     0x7f9c154b1b3d  (unknown)
    @     0x7f9c154b1ce1  (unknown)
    @     0x7f9c155bb24c  (unknown)
    @     0x7f9c152cb938  (unknown)
    @     0x7f9c158f22ff  (unknown)
    @     0x7f9c3ade76db  (unknown)
    @     0x7f9c3b12188f  (unknown)
    @              (nil)  (unknown)
```

Just some additional information, it does have solutions and then stops working.

**Comment by lperron** [comment]
This runs fine on master

#Variables: 2573 (737 in objective)
 - 2046 in [0,1]
 - 11 in [0,200]
 - 22 in [1,588]
 - 11 in [31,231]
 - 11 in [32,232]
 - 11 in [67,267]
 - 11 in [76,276]
 - 11 in [84,284]
 - 11 in [88,288]
 - 11 in [96,296]
 - 11 in [107,307]
 - 22 in [112,312]
 - 11 in [116,316]
 - 11 in [117,317]
 - 11 in [120,320]
 - 22 in [128,328]
 - 11 in [138,338]
 - 11 in [141,341]
 - 11 in [146,346]
 - 11 in [147,347]
 - 22 in [152,352]
 - 11 in [156,356]
 - 11 in [164,364]
 - 11 in [177,377]
 - 11 in [179,379]
 - 11 in [184,384]
 - 11 in [190,390]
 - 11 in [192,392]
 - 11 in [203,403]
 - 11 in [204,404]
 - 11 in [215,415]
 - 22 in [227,427]
 - 11 in [288,488]
 - 33 in [328,528]
 - 11 in [333,533]
 - 11 in [346,546]
 - 11 in [365,565]
 - 22 in [379,579]
 - 11 in [387,587]
 - 21 constants in
{0,1,17,23,24,25,26,27,29,31,33,34,35,37,45,51,59,63,64,75,1387}
#kInterval: 363 (#enforced: 363)
#kLinear1: 968 (#enforced: 968)
#kLinear2: 10164 (#enforced: 10164)
#kLinearN: 264
#kNoOverlap: 11
#kReservoir: 33
I0206 12:02:05.945744   20962 cp_model_solver.cc:2459] *** starting model
presolve at 0.01s
I0206 12:02:07.092032   20962 cp_model_presolve.cc:4468] - 8997 affine
relations were detected.
I0206 12:02:07.092070   20962 cp_model_presolve.cc:4470] - 8997 variable
equivalence relations were detected.
I0206 12:02:07.092079   20962 cp_model_presolve.cc:4478] - rule
'at_most_one: removed literals' was applied 171 times.
I0206 12:02:07.092082   20962 cp_model_presolve.cc:4478] - rule 'bool_or:
always true' was applied 6626 times.
I0206 12:02:07.092084   20962 cp_model_presolve.cc:4478] - rule 'bool_or:
fixed literals' was applied 516 times.
I0206 12:02:07.092085   20962 cp_model_presolve.cc:4478] - rule 'bool_or:
implications' was applied 63 times.
I0206 12:02:07.092087   20962 cp_model_presolve.cc:4478] - rule 'bool_or:
removed enforcement literal' was applied 15 times.
I0206 12:02:07.092089   20962 cp_model_presolve.cc:4476] - rule
'deductions: 5307 stored' was applied 1 time.
I0206 12:02:07.092091   20962 cp_model_presolve.cc:4478] - rule
'enforcement literal not used' was applied 91 times.
I0206 12:02:07.092093   20962 cp_model_presolve.cc:4478] - rule 'false
enforcement literal' was applied 31771 times.
I0206 12:02:07.092095   20962 cp_model_presolve.cc:4478] - rule 'linear:
always true' was applied 1319 times.
I0206 12:02:07.092097   20962 cp_model_presolve.cc:4478] - rule 'linear:
divide by GCD' was applied 161 times.
I0206 12:02:07.092099   20962 cp_model_presolve.cc:4478] - rule 'linear:
empty' was applied 607 times.
I0206 12:02:07.092101   20962 cp_model_presolve.cc:4478] - rule 'linear:
enforcement literal in constraint' was applied 101 times.
I0206 12:02:07.092103   20962 cp_model_presolve.cc:4478] - rule 'linear:
extracted at most one (min).' was applied 2 times.
I0206 12:02:07.092105   20962 cp_model_presolve.cc:4478] - rule 'linear:
extracted enforcement literal from constraint' was applied 38 times.
I0206 12:02:07.092106   20962 cp_model_presolve.cc:4478] - rule 'linear:
fixed or dup variables' was applied 1304 times.
I0206 12:02:07.092109   20962 cp_model_presolve.cc:4478] - rule 'linear:
infeasible' was applied 1446 times.
I0206 12:02:07.092111   20962 cp_model_presolve.cc:4478] - rule 'linear:
negative clause' was applied 16 times.
I0206 12:02:07.092113   20962 cp_model_presolve.cc:4478] - rule 'linear:
negative equal one' was applied 242 times.
I0206 12:02:07.092115   20962 cp_model_presolve.cc:4478] - rule 'linear:
positive at most one' was applied 22 times.
I0206 12:02:07.092118   20962 cp_model_presolve.cc:4478] - rule 'linear:
positive reified and' was applied 30 times.
I0206 12:02:07.092120   20962 cp_model_presolve.cc:4478] - rule 'linear:
remapped using affine relations' was applied 158 times.
I0206 12:02:07.092122   20962 cp_model_presolve.cc:4478] - rule 'linear:
simplified rhs' was applied 13093 times.
I0206 12:02:07.092124   20962 cp_model_presolve.cc:4478] - rule 'linear:
singleton column' was applied 618 times.
I0206 12:02:07.092126   20962 cp_model_presolve.cc:4478] - rule 'linear:
size one' was applied 621 times.
I0206 12:02:07.092128   20962 cp_model_presolve.cc:4478] - rule 'linear:
split boxed constraint' was applied 15 times.
I0206 12:02:07.092130   20962 cp_model_presolve.cc:4478] - rule 'objective:
variable not used elsewhere' was applied 550 times.
I0206 12:02:07.092133   20962 cp_model_presolve.cc:4478] - rule 'presolve:
iteration' was applied 2 times.
I0206 12:02:07.092139   20962 cp_model_presolve.cc:4478] - rule 'removed
duplicate constraints' was applied 19 times.
I0206 12:02:07.092141   20962 cp_model_presolve.cc:4478] - rule 'reservoir:
expanded' was applied 33 times.
I0206 12:02:07.092144   20962 cp_model_presolve.cc:4478] - rule 'setppc:
removed redundant constraints' was applied 2 times.
I0206 12:02:07.092147   20962 cp_model_presolve.cc:4478] - rule 'true
enforcement literal' was applied 577 times.
I0206 12:02:07.092152   20962 cp_model_presolve.cc:4478] - rule 'variables:
detect half reified value encoding' was applied 484 times.
I0206 12:02:07.093902   20962 cp_model_solver.cc:2484] Optimization model
'':
#Variables: 5630 (170 in objective)
 - 5484 in [0,1]
 - 3 in [0,200]
 - 22 in [1,588]
 - 3 in [31,231]
 - 2 in [32,232]
 - 3 in [67,267]
 - 3 in [76,276]
 - 3 in [84,284]
 - 3 in [88,288]
 - 2 in [96,296]
 - 3 in [107,307]
 - 6 in [112,312]
 - 2 in [116,316]
 - 3 in [117,317]
 - 1 in [120,320]
 - 4 in [128,328]
 - 1 in [138,338]
 - 3 in [141,341]
 - 3 in [146,346]
 - 1 in [147,347]
 - 4 in [152,352]
 - 3 in [156,356]
 - 1 in [164,364]
 - 1 in [177,377]
 - 2 in [179,379]
 - 1 in [184,384]
 - 3 in [190,390]
 - 3 in [192,392]
 - 1 in [203,403]
 - 3 in [204,404]
 - 1 in [215,415]
 - 6 in [227,427]
 - 3 in [288,488]
 - 8 in [328,528]
 - 3 in [333,533]
 - 3 in [346,546]
 - 3 in [365,565]
 - 6 in [379,579]
 - 2 in [387,587]
 - 18 constants in {17,23,24,25,26,27,29,31,33,34,35,37,45,51,59,63,64,75}
#kAtMostOne: 4482 (#literals: 16681)
#kBoolAnd: 46 (#enforced: 46) (#literals: 217)
#kBoolOr: 3879 (#literals: 16104)
#kInterval: 174 (#enforced: 174)
#kLinear1: 218 (#enforced: 218)
#kLinear2: 5426 (#enforced: 5426)
#kLinearN: 111 (#enforced: 108)
#kNoOverlap: 11
I0206 12:02:07.097418   20962 cp_model_solver.cc:2624] *** starting to load
the model at 1.16s
I0206 12:02:07.448031   20962 synchronization.cc:131] #Bound   1.51s
best:-inf  next:[-108661,2013672] init
I0206 12:02:07.448074   20962 cp_model_solver.cc:2630] *** starting
sequential search at 1.51s
I0206 12:02:07.448078   20962 cp_model_solver.cc:2632] Initial num_bool:
5590
I0206 12:02:07.886365   20962 synchronization.cc:131] #1       1.95s
best:1890869 next:[1890870,2013672]  num_bool:5922
I0206 12:02:07.897007   20962 synchronization.cc:131] #2       1.96s
best:1891730 next:[1891731,2013672]  num_bool:5933
I0206 12:02:07.902234   20962 synchronization.cc:131] #3       1.96s
best:1892480 next:[1892481,2013672]  num_bool:5934
I0206 12:02:07.909269   20962 synchronization.cc:131] #4       1.97s
best:1892700 next:[1892701,2013672]  num_bool:5934
I0206 12:02:07.923609   20962 synchronization.cc:131] #5       1.98s
best:1892710 next:[1892711,2013672]  num_bool:5934
I0206 12:02:07.932455   20962 synchronization.cc:131] #6       1.99s
best:1893740 next:[1893741,2013672]  num_bool:5939
I0206 12:02:07.938882   20962 synchronization.cc:131] #7       2.00s
best:1993790 next:[1993791,2013672]  num_bool:5940
I0206 12:02:07.949809   20962 synchronization.cc:131] #8       2.01s
best:1993930 next:[1993931,2013672]  num_bool:5941
I0206 12:02:07.958914   20962 synchronization.cc:131] #9       2.02s
best:1994880 next:[1994881,2013672]  num_bool:5944
I0206 12:02:07.968361   20962 synchronization.cc:131] #10      2.03s
best:1995680 next:[1995681,2013672]  num_bool:5944
I0206 12:02:07.983584   20962 synchronization.cc:131] #11      2.04s
best:1995790 next:[1995791,2013672]  num_bool:5949
I0206 12:02:08.181634   20962 synchronization.cc:131] #12      2.24s
best:1995870 next:[1995871,2013672]  num_bool:5955
I0206 12:02:08.326196   20962 synchronization.cc:131] #13      2.39s
best:1996470 next:[1996471,2013672]  num_bool:5960
I0206 12:02:08.353934   20962 synchronization.cc:131] #14      2.41s
best:1997340 next:[1997341,2013672]  num_bool:5962
I0206 12:02:08.395148   20962 synchronization.cc:131] #15      2.46s
best:1997449 next:[1997450,2013672]  num_bool:5967
I0206 12:02:08.432400   20962 synchronization.cc:131] #16      2.49s
best:1997730 next:[1997731,2013672]  num_bool:5971
I0206 12:02:08.441555   20962 synchronization.cc:131] #17      2.50s
best:1997740 next:[1997741,2013672]  num_bool:5971
I0206 12:02:08.470982   20962 synchronization.cc:131] #18      2.53s
best:1997870 next:[1997871,2013672]  num_bool:5976
I0206 12:02:08.520565   20962 synchronization.cc:131] #19      2.58s
best:1997940 next:[1997941,2013672]  num_bool:5979
I0206 12:02:08.582198   20962 synchronization.cc:131] #20      2.64s
best:1998060 next:[1998061,2013672]  num_bool:5982
I0206 12:02:09.154960   20962 synchronization.cc:131] #21      3.22s
best:1998070 next:[1998071,2013672]  num_bool:5983
I0206 12:02:09.340234   20962 synchronization.cc:131] #22      3.40s
best:1998209 next:[1998210,2013672]  num_bool:5988
I0206 12:02:09.370179   20962 synchronization.cc:131] #23      3.43s
best:1998249 next:[1998250,2013672]  num_bool:5991
I0206 12:02:09.479529   20962 synchronization.cc:131] #Bound   3.54s
best:1998249 next:[1998250,2013216]
I0206 12:02:09.866036   20962 synchronization.cc:131] #24      3.93s
best:1998250 next:[1998251,2013216]  num_bool:5995
I0206 12:02:09.898103   20962 synchronization.cc:131] #25      3.96s
best:1998290 next:[1998291,2013216]  num_bool:5999
I0206 12:02:09.971624   20962 synchronization.cc:131] #26      4.03s
best:1998559 next:[1998560,2013216]  num_bool:6001
I0206 12:02:10.023130   20962 synchronization.cc:131] #Bound   4.08s
best:1998559 next:[1998560,2000000]
I0206 12:02:10.099882   20962 synchronization.cc:131] #27      4.16s
best:1998560 next:[1998561,2000000]  num_bool:6002
I0206 12:02:10.210147   20962 synchronization.cc:131] #28      4.27s
best:1998570 next:[1998571,2000000]  num_bool:6002
I0206 12:02:10.244918   20962 synchronization.cc:131] #29      4.31s
best:1998640 next:[1998641,2000000]  num_bool:6003
I0206 12:02:10.265979   20962 synchronization.cc:131] #Bound   4.33s
best:1998640 next:[1998641,1999040]
I0206 12:02:10.266198   20962 synchronization.cc:139] #Done    4.33s
I0206 12:02:10.273166   20962 cp_model_solver.cc:2646] CpSolverResponse:
status: OPTIMAL
objective: 1998640
best_bound: 1998640
booleans: 6003
conflicts: 7930
branches: 195991
propagations: 7090495
integer_propagations: 3876470
walltime: 4.33379
usertime: 4.32326
deterministic_time: 2.00399
primal_integral: 0
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 6 févr. 2020 à 11:47, timothylowjc <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
both problems works fine on master.
Closing the issue.
