### ISSUE TITLE
Multi-threading CBC solver

### ISSUE THREAD

**Issue by antoniomedrano** [google/or-tools#180]
Is there a way to multi-thread the CBC solver to use more than just one processor core? I'm using the python interface for or-tools.

**Comment by hxd1011** [comment]
Hi, I have tried that with CBC stand alone executable. What I leaned is that, some builds may not have multi-thread enabled. i.e., -threads option is not always available.

Check this link and you will find all 2.7 builds are not parallel enabled (has -parallel in the name.)
http://www.coin-or.org/download/binary/Cbc/

Do not know How google OR will handle that

**Comment by lperron** [comment]
When build CBC in make third_party, 
I am using this flags in the configure part

ADD_CXXFLAGS="-DCBC_THREAD_SAFE -DCBC_NO_INTERRUPT"


Should I add something else?

**Comment by sschnug** [comment]
(Without knowing anything about Cbc's incorporation into ortools) I think in terms of configure ```--enable-cbc-parallel``` [might](https://github.com/h-g-s/lp/issues/1#issuecomment-357816478) be relevant.

**Comment by rlloretb** [comment]
Just to make it clear, is the parallel option for CBC enabled by default?

**Comment by lperron** [comment]
Definitely for unix

https://github.com/google/or-tools/blob/stable/makefiles/Makefile.third_party.unix.mk#L361

and I believe so for windows

https://github.com/google/or-tools/blob/stable/makefiles/Makefile.third_party.win.mk#L369
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
