### ISSUE TITLE
Type or namespace CpModel not found

### ISSUE THREAD

**Issue by MrYossu** [google/or-tools#1801]
Trying to follow the 1st example at https://developers.google.com/optimization/cp/cp_solver using C# in LinqPad. I have done the linear optimisation examples without problem, however, when I type the line...

    CpModel model = new CpModel();

...I get a compiler exception as shown in the title.

I have checked the "usings" and they are all there. I also tried manually typing `Google.OrTools` and seeing what came up in Intellisense, but couldn't find any mention of this class anywhere.

**Comment by stradivari96** [comment]
`using Google.OrTools.Sat` ?

**Comment by MrYossu** [comment]
Yup

**Comment by lperron** [comment]
Which version ?

**Comment by MrYossu** [comment]
5.0.6170.24109 which is the latest I get from Nuget

**Comment by MrYossu** [comment]
I'm using the Google.OrTools.x86 Nuget package by the way, the other OrTools packages didn't work in LinqPad

**Comment by MrYossu** [comment]
Just to elaborate on my previous comment, if I install the `Google.OrTools v7.4.7247` Nuget package, then when I try to run any code, I get an exception...

Could not load file or assembly 'file:///C:\Users\AY Silver\AppData\Local\LINQPad\NuGet.FW46\Google.OrTools\Google.OrTools.7.4.7247\lib\net452\Google.OrTools.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.

That's why I'm using the x86 package, as it works (or has so far)

**Comment by lperron** [comment]
It works. But it is so old, there are no CP-SAT solver, the examples will
not compile...

**Comment by lperron** [comment]
X86 is no longer supported.
