### ISSUE TITLE
Solver.Solve() returns an int, not Solver.ResultStatus (which doesn't exist)

### ISSUE THREAD

**Issue by MrYossu** [google/or-tools#1802]
I'm trying to follow the example at https://developers.google.com/optimization/mip/integer_opt using C# in LinqPad. I have copied out the code, but get a compiler error on the line...

    Solver.ResultStatus resultStatus = solver.Solve();

...as the method `Solve()` returns an `int`, not a `Solver.ResultStatus`. Furthermore, I can't find a type `Solver.ResultStatus` anywhere.

I have a `using` for `Google.OrTools.LinearSolver` as directed.

Here is the complete LinqPad file (note that this is the contents of the file, not what you type in the editor, as it includes the query metadata)...

```
<Query Kind="Statements">
  <Output>DataGrids</Output>
  <Reference Relative="..\..\..\AppData\Local\LINQPad\NuGet.FW46\Google.OrTools\Google.Protobuf.3.10.0\lib\net45\Google.Protobuf.dll">&lt;LocalApplicationData&gt;\LINQPad\NuGet.FW46\Google.OrTools\Google.Protobuf.3.10.0\lib\net45\Google.Protobuf.dll</Reference>
  <NuGetReference>Google.OrTools.x86</NuGetReference>
  <Namespace>Google.OrTools.LinearSolver</Namespace>
</Query>

Solver solver = Solver.CreateSolver("SimpleMipProgram", "CBC_MIXED_INTEGER_PROGRAMMING");
Variable x = solver.MakeIntVar(0.0, double.PositiveInfinity, "x");
Variable y = solver.MakeIntVar(0.0, double.PositiveInfinity, "y");
solver.Add(x + 7 * y <= 17.5);
solver.Add(x <= 3.5);
solver.Maximize(x + 10 * y);
var resultStatus = solver.Solve();
```

The compiler error is on the last line.

Any ideas? Thanks

**Comment by lperron** [comment]
Which version of or-tools?

**Comment by lperron** [comment]
Version too old.

**Comment by MrYossu** [comment]
So how do I use the latest? As I mentioned in [my other issue](https://github.com/google/or-tools/issues/1801), if I install the Google.OrTools v7.4.7247 Nuget package, then when I try to run any code, I get an exception...

_Could not load file or assembly 'file:///C:\Users\myuser\AppData\Local\LINQPad\NuGet.FW46\Google.OrTools\Google.OrTools.7.4.7247\lib\net452\Google.OrTools.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format._

How do I use the latest from LinqPad?

**Comment by MrYossu** [comment]
OK, I see you've closed this, so I will open a [new issue](https://github.com/google/or-tools/issues/1803) for my (now slightly different) question.
