### ISSUE TITLE
change seed in cp solver c++?

### ISSUE THREAD

**Issue by 515orestis** [google/or-tools#1804]
i am using  cp solver to solve a routing problem i am trying unsuccessfully to introduce  randomness
on my problem( using reseed) is there a flag or any other specific configuration that i need to do?

using or tools 7.1
and best_insertions

if you need more info i will be more than happy to help

**Comment by Mizux** [comment]
in C++ we have:
https://github.com/google/or-tools/blob/2fc5d0c6810600f5a1664b6b8dccb7b728b15d16/ortools/constraint_solver/constraint_solver.h#L92-L94
which won't be binded in Python, Java or .Net

**Comment by vgala** [comment]
How can i achieve the same in Python ?
