### ISSUE TITLE
Multi-threading in CBC on Windows 10

### ISSUE THREAD

**Issue by louis925** [google/or-tools#1805]
I am trying to run the `CBC_MIXED_INTEGER_PROGRAMMING ` solver with multi-threads in the ortools on Windows 10 but it seems to not accept the thread argument.
When I do 
```
solver = pywraplp.Solver('', pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING)
solver.SetNumThreads(24)
```
with the problem and then `solver.Solve()`, it printed
```
No match for threads - ? for list of commands
No match for 24 - ? for list of commands
```
on the terminal, and only use 1 core of my CPU. If I don't specify `solver.SetNumThreads(24)`, then it also use one core. However, when I run the same code on macOS, it can run multi-threads automatically.

I read from a recent issue on [the CBC repo](https://github.com/coin-or/Cbc/issues/270) that they are providing parallel version of the binaries. I was wondering if the or-tools has include that already? 

I have also tried to build from the source of or-tools but it stopped with the error
```
...
copy dependencies\sources\Cbc-2.10.3\Cbc\MSVisualStudio\v10\x64-v142-Release\*.lib dependencies\install\lib\coin
The system cannot find the path specified.
tools\make: *** [dependencies\install\bin\cbc.exe] Error 1
```

**Comment by lperron** [comment]
By default, we build cbc on windows ourselves, we we use the visual studio solution for that.
I do not know how to enable parallel solve using this.

You can try building from source, and overriding the cbc path to use one from the binary distribution.  This may require  some tweaking of the makefiles.

This being said, I am not sure it is worth the effort. I do not recommend CBC even if it is the best open source free for all MIP solver available.

**Comment by louis925** [comment]
I see. I have no choice other than using CBC since it is the only free MIP solver that I can found now.
