### ISSUE TITLE
Naming constraints in SAT

### ISSUE THREAD

**Issue by cjolinla** [google/or-tools#1806]
Hi,

I recall the Linear Solver v7.2.6977 offered the ability to name the constraints with a unique string through the Solver.MakeConstraint() method. It was particularly useful for debugging especially when using the Solver.ExportModelAsLpFormat(false) method to visualize the model and ensure the proper expressions were in fact implemented.

I am now working with the SAT solver v7.2.6977 (original model was created on that version) and I can't find a way to label my constraints. Is there a way to do so in SAT v7.4? Also is there a way to print out the model to a text file once built? 

Thank you

**Comment by lperron** [comment]
Yes, it is a bit manual. 
You need to get the underlying protobuf object of the constraint. It supports the 'name' field.

See https://github.com/google/or-tools/blob/stable/ortools/sat/doc/model.md for some preliminary documentation.
