### ISSUE TITLE
KnapSack

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1809]
Hello,
I was using KNAPSACK_MULTIDIMENSION_BRANCH_AND_BOUND_SOLVER, in a problem with **2 capacity dimensions and up to 60 items** to try an fit. In this case only around items 10 practically fit the bin (i.e. meet both capacity dimensions). 
The algo worked pretty will up to 20+ items however, anywhere above 28 items causes the CPU memory consumption to grow continuously until the program crashes.

Using KNAPSACK_MULTIDIMENSION_CBC_MIP_SOLVER worked well up to 100 items, no issues. I did not deeply validate the optimality of the assignment, but these seemed OK.

Any drawbacks with using the CBC_MIP?

Happy Holidays!

**Comment by lperron** [comment]
Please check the solution. We have found case where it was obviously wrong.

**Comment by GuyBenhaim** [comment]
Should I then add post-processing code to validate the solver solution?
Was the problem with BRANCH_AND_BOUND or CBC_MIP or with both?

**Comment by orwant** [comment]
The problem must have been with only CBC. If the problem was with Google's
solver, Laurent would have fixed it by now :-)

Jon

**Comment by lperron** [comment]
Exactly, CBC is unreliable, sometimes. Especially on very small problems.

Le sam. 28 déc. 2019 à 21:15, Jon Orwant <notifications@github.com> a
écrit :

> The problem must have been with only CBC. If the problem was with Google's
> solver, Laurent would have fixed it by now :-)
>
> Jon
>

**Comment by GuyBenhaim** [comment]
Aoutch
So, any way to contain or control the issue I described with BRANCH_AND_BOUND, using up to 60 items?
