### ISSUE TITLE
Missing Soft Constraints Examples (C#)

### ISSUE THREAD

**Issue by kongres** [google/or-tools#181]
Hi guys.

Thank you for the great library.

I need your help to understand how it works and works at all in C#.

Take example Nurse Rostering - https://github.com/google/or-tools/blob/master/examples/csharp/nurse_rostering_transition.cs

If we want to define hard constraints we write so:

```
solver.Add(day_stat[day, day_shift] <= 4);
solver.Add(day_stat[day, night_shift] == 1);
solver.Add(day_stat[day, off_shift] == 2);
```

But what do we have to write if we want to write soft constraints? The solver will use them for searching solutions but will not follow them hard.

Or does it work in other way?

Also how can I get hard and soft scores of each solution?

**Comment by lperron** [comment]
You have few soft constraints available.

in https://github.com/google/or-tools/blob/master/src/constraint_solver/constraint_solver.h, 
look for constraints with Is in the name like

MakeIsEqualVar()

There are usually two variants

MakeXXXVar() -> creates a boolean variable that is the status of the constraint.
MakeXXXCt() uses a third argument that is the equivalent of the above boolean variable.

I hope this helps.

**Comment by Mazzjs** [comment]
hi, @lperron .

I have the same question with @kongres . 

I have checked the two functions you mentioned above. The MakeXXXVar() returns an IntVar, and MakeXXXCt() returns a Constraint. but I don't know how to make these functions to a soft constraint. In other words, I don't know that how to add penalty cost to the objective function.

Could you explain it with more details? Examples would help me understand better!

Thank you in advance.

**Comment by lperron** [comment]
The idea is the following:

if you add x >= 5 to the model/solver, it is  a hard constraint.

If you create var == (x >= 5), you can make it soft.

var is 0 is the constraint (x >= 5) is violated.
Just add (1 - var) * penalty to the minimization objective to specify that x >=5 is a soft constraint.

This being said, I encourage looking at the CP-SAT solver:

https://github.com/google/or-tools/blob/master/ortools/sat/doc/index.md

Where this notion is much clearer, especially the Channeling part.
