### ISSUE TITLE
Packing with Multi-Dimensions and Multi-Bins

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#1810]
Hello,

Do you have reference/demo code for or-tools to solve this?
I have seen some correspondence but not a solution that would save deep diving into this ...

Happy Holidays!

**Comment by paultrow** [comment]
There's an example of multiple knapsacks here:
https://developers.devsite.corp.google.com/optimization/bin/multiple_knapsack

This just has one dimension (weight), but you can add as many as you want.

**Comment by orwant** [comment]
That URL should be
https://developers.google.com/optimization/bin/multiple_knapsack.

Jon

**Comment by GuyBenhaim** [comment]
Thx.
I earlier looked at the developers site, but I will check if adding dimensions is easy.

**Comment by GuyBenhaim** [comment]
So, I should add another dimension/s by duplicating this existing contraint:
solver.MakeRowConstraint(Weight <= data.BinCapacities[j]);

**Comment by lperron** [comment]
exactly
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
