### ISSUE TITLE
Are the `start` and `end` being set correctly for routing?

### ISSUE THREAD

**Issue by MarcoGorelli** [google/or-tools#1811]
Here's a minimal example:

```python
from ortools.constraint_solver import pywrapcp

manager = pywrapcp.RoutingIndexManager(10, 1, [1], [0])
routing = pywrapcp.RoutingModel(manager)
print(routing.Start(0), routing.End(0))
```
This returns
```
0 9
```
while I was expecting to see
```
1 0
```

I am using ortools version '7.4.7247'

**Comment by lperron** [comment]
The result is an 'index', not a node. You need to apply index to node to
get 0 and 1.

Le sam. 28 déc. 2019 à 19:00, Marco Gorelli <notifications@github.com> a
écrit :
