### ISSUE TITLE
Function SetSoftSpanUpperBoundForVehicle missing in wrappers

### ISSUE THREAD

**Issue by yarik1988** [google/or-tools#1815]
Hello! I need function `SetSoftSpanUpperBoundForVehicle()` to penalize overdue time for each vehicle. The thing is that each vehicle has different limit of time, so I really need this function.
However, it seems such function exists only in C/C++ implementation. (routing.h, line 2344) 

EDIT(mizux):

* [ ] `RoutingDimension::SetSoftSpanUpperBoundForVehicle()`
* [ ] `RoutingDimension::HasSoftSpanUpperBounds()`
* [ ] `RoutingDimension::GetSoftSpanUpperBoundForVehicle()`
* [ ] `RoutingDimension::SetQuadraticCostSoftSpanUpperBoundForVehicle()`
* [ ] `RoutingDimension::HasQuadraticCostSoftSpanUpperBounds()`
* [ ] `RoutingDimension::GetQuadraticCostSoftSpanUpperBoundForVehicle()`

**Comment by Mizux** [comment]
According to:

https://github.com/google/or-tools/blob/be4f992ab984314ddf8c24f79d5b5dcb72738cc7/ortools/constraint_solver/routing.h#L2408-L2427

To bind it we need first a wrapper on the `SimpleBoundCosts::BoundCost` class...

**Comment by Mizux** [comment]
Why not using `SetCumulVarSoftUpperBound()` on vehicle end index instead ?
https://github.com/google/or-tools/blob/67f1b08b63e4ae6837f68df7c3173619bf8fafb0/ortools/constraint_solver/routing.h#L2426-L2435

**Comment by Mizux** [comment]
Method `void SetSoftSpanUpperBoundForVehicle(SimpleBoundCosts::BoundCost bound_cost, int vehicle)` is still guarded from SWIG parsing.
