### ISSUE TITLE
Increasing the solution time limits for CBC in Python makes the problem infeasible.

### ISSUE THREAD

**Issue by tonghuikang** [google/or-tools#1817]
Thank you for your work on this set of optimisation tools.

For the `Solver.CBC_MIXED_INTEGER_PROGRAMMING`, increasing the solution time limits makes my model infeasible.

Code
https://www.kaggle.com/huikang/draw-equal-cstcs?scriptVersionId=26026929
https://www.kaggle.com/huikang/draw-equal-cstcs?scriptVersionId=26026781

The solution time is changed from `solver.set_time_limit(10*1000)` to `solver.set_time_limit(100*1000)`
The above change is the only change of code between the two versions.

The status then changed from feasible into infeasible. 
`status == solver.FEASIBLE`
`status == solver.INFEASIBLE`
I also could no longer access `solution_value()` because the problem is now infeasible.

`!pip freeze | grep ortools` returns `ortools==7.4.7247`

**Comment by sschnug** [comment]
Some remarks:

- Your links don't work
- CoinOR [Cbc](https://github.com/coin-or/Cbc) is not part of ortools, but only wrapped and part of the deploy-pipeline 
    - ortools-devs are mentioning Cbc's instability quite often (and yet it's probably the best *free* solver)
    - **imho** i expect Cbc to follow a different path depending on the configuration and this even includes increasing the time-limit (like `i got so much time left; let's use more of my expensive techniques like strong-branching`)
        - it's not great, that this would lead to conflicting results, but it's possible due to numerical issues (or general bugs)
        - assuming, it's not a bug: **check your model in regards to numerical-stability**! (scaling and co.)
    - debugging Cbc here needs a more sane debugging-setup which is reproducible:
        - source-code
            - to analyze numerical-trouble
            - to enforce + analyze deterministic nature (random-seed; multithreading)
            - to enforce + analyze inner-state (e.g. resolve; not sure if ortools does something like that)

I don't see a ortools-related problem here. And as mentioned: debugging Cbc will need much more details.

**Comment by lperron** [comment]
the next step would be to generate the MPS model, and try it with the cbc binary with different time limits. But as written above, the linear solver wrapper does not do anything special.
