### ISSUE TITLE
IntervalVar missing start, end, duration fields in Python

### ISSUE THREAD

**Issue by jediahkatz** [google/or-tools#1818]
Similar to #967 it seems that the `start`, `end`, and `duration` fields are missing for IntervalVars in python. I am not able to run this example because the fields used do not actually exist and I get an AttributeError: https://developers.google.com/optimization/scheduling/job_shop

Is there another way to access them, or is it a bug? And if it is a bug, is the only workaround for now just to store the start / end / duration variables separately?

**Comment by lperron** [comment]
The proto just stores the index of the integer variables in the main model
protobuf. I do not wish to store everything in the python stub, so you will
need to store them separately.

I use named tuples for this purpose in my examples.


Le mar. 31 déc. 2019 à 20:06, Jediah Katz <notifications@github.com> a
écrit :

**Comment by jediahkatz** [comment]
Ah, I misunderstood how you were doing this in the example. I was trying to rewrite it myself. Thank you!

**Comment by jediahkatz** [comment]
Sorry, one more quick question: would storing everything in the python stub myself possibly cause any performance degradation over namedtuples? For example:
```
task = model.NewIntervalVar(start, duration, end, name)
task.start = start
task.end = end
```
etc?

**Comment by lperron** [comment]
It should work.

Le mar. 31 déc. 2019 à 23:09, Jediah Katz <notifications@github.com> a
écrit :
