### ISSUE TITLE
Non-integer result despite using IntVar()

### ISSUE THREAD

**Issue by ashay** [google/or-tools#1819]
Hello,

I have a short program (5 variables, 4 constraints, shown below), where each variable is created using the IntVar() function. However, when I print the value of the variable, it shows a float value, whereas it seems like the value should be an integer. Is there something wrong with my program?

The supplied constraints are not satisfied if I round the float result to the nearest integer.

```python
from ortools.linear_solver import pywraplp

solver_kind = pywraplp.Solver.GLOP_LINEAR_PROGRAMMING
solver = pywraplp.Solver("default", solver_kind)

a0_half = solver.IntVar(0, 1, "a0_half")
a1_half = solver.IntVar(0, 1, "a1_half")

M = 10
a0_count = solver.IntVar(0, M-1, "a0_count")
a1_count = solver.IntVar(0, M-1, "a1_count")

b0_count = solver.IntVar(0, M-1, "b0_count")

solver.Add(a0_count - b0_count <= M * (1 - a0_half) - 1)
solver.Add(b0_count - a0_count <= M * a0_half       - 1)

solver.Add(a1_count - b0_count <= M * (1 - a1_half) - 1)
solver.Add(b0_count - a1_count <= M * a1_half       - 1)

solver.Maximize(0)

if solver.Solve() == pywraplp.Solver.OPTIMAL:
    print(a0_half.solution_value())    # This line prints 0.1
    print(a1_half.solution_value())    # This line prints 0.1
```

**Comment by ashay** [comment]
Forgot to mention, I tried this on both the latest commit from the `stable` branch as well as on the version obtained using `pip`.

**Comment by stradivari96** [comment]
See: https://groups.google.com/forum/#!msg/or-tools-discuss/p5qVzZWIeIg/g77egaD-AAAJ

> Glop is a pure LP. It will only solve the relaxation of the mip problem. So it is normal that the error checker tells you that the solution is not integral.
You can change GLOP_LINEAR_PROGRAMMING to BOP_INTEGER_PROGRAMMING if you program is purely boolean. Or you can stay with CBC

**Comment by lperron** [comment]
On master, you can now use SAT_INTEGER_PROGRAMMING.
