### ISSUE TITLE
C# SWIG Wrapper is Inconsistent

### ISSUE THREAD

**Issue by fallaciousreasoning** [google/or-tools#182]
Hey guys, this looks like an awesome library. However, I noticed a small bug in the C# SWIG wrapper. When using the maxflow algorithm in python and calling the method `GetSinkSideMinCut` it returns a list of strings and takes no parameters. In C#, I expect the the behavior is meant to be similar but the method returns `void` and takes one argument, a `SWIGTYPE_p_std__vectorT_int_t`

I suppose this is probably a problem with your SWIG wrapper for C#. I'd try and fix it myself but I'm honestly a little out of my depth (I've never used SWIG before).

**Comment by Mizux** [comment]
This method is currently hidden since v7.0 (IIRC) since we don't have the needed swig *typemap* yet.

Please follow #1276 to get an up to date C# statute.
