### ISSUE TITLE
Is there a way to produce non deterministic solution on routing library?

### ISSUE THREAD

**Issue by mariamatz** [google/or-tools#1821]
I'm using the routing library in order to solve some VRPs. I'm trying to use Solver::Reseed().Expecting to see different results in the search log but every time i get exactly the same log. The results seems to be deterministic.
Is there a flag or any other specific configuration that i need to do?
 
using or tools 7.1
best_insertion
C++
and guided local search
 
 
if you need more info i will be more than happy to help 
 
related issues 
https://github.com/google/or-tools/issues/1804
https://github.com/google/or-tools/issues/1145
https://github.com/google/or-tools/issues/881
https://github.com/google/or-tools/issues/291
https://github.com/google/or-tools/issues/702

**Comment by Mizux** [comment]
duplicate, please try to ask on the mailing list ortools-discuss instead....
Thx !
