### ISSUE TITLE
segfault vrp_pickup_delivery.cc

### ISSUE THREAD

**Issue by developer-qoo10** [google/or-tools#1827]
# Setup
OS : CentOS Linux release 7.5.1804
Or-Tools : 7.4.7247
g++ : 4.8.5

# Protocol
I compiled an example `vrp_pickup_delivery.cc` using:
```sh
g++ -std=c++11 -lprotobuf -lglog -lgflags -lortools -o ex vrp_pickup_delivery.cc
```

# Observed
However, an aborted error occurred in the compiled executable.
```sh
----------------------------------------------
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0107 18:16:23.885967 14623 routing_index_manager.h:73] Check failed: index < index_to_node_.size() (140727098947872 vs. 24)
*** Check failure stack trace: ***
Aborted
-----------------------------------------------
```
Thank you.

**Comment by Mizux** [comment]
May I have more details ? Step to reproduce etc.... ?

Thanks

**Comment by developer-qoo10** [comment]
OS : CentOS Linux release 7.5.1804
Or-Tools : 7.4.7247
g++ : 4.8.5

I compiled an example vrp_pickup_delivery.cc
( g++ -std=c++11 -lprotobuf -lglog -lgflags -lortools -o ex vrp_pickup_delivery.cc )
However, an aborted error occurred in the compiled executable.

==============================================
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0107 18:16:23.885967 14623 routing_index_manager.h:73] Check failed: index < index_to_node_.size() (140727098947872 vs. 24)
*** Check failure stack trace: ***
Aborted
===============================================

Thank you.

**Comment by Mizux** [comment]
did you modify this sample ? where did you find it ?

**Comment by developer-qoo10** [comment]
Sample was downloaded from google ortools site

page:
https://developers.google.com/optimization/install/cpp/linux

download:
https://github.com/google/or-tools/releases/download/v7.4/or-tools_centos-7_v7.4.7247.tar.gz

**Comment by Mizux** [comment]
I can reproduce it using
Dockerfile:
```dockerfile
FROM centos:7

RUN yum -y update
RUN yum groupinstall -y 'Development Tools'
RUN yum install -y wget zlib-devel

USER root
WORKDIR /root
RUN  wget https://github.com/google/or-tools/releases/download/v7.4/or-tools_centos-7_v7.4.7247.tar.gz
RUN tar xzvf *.tar.gz
WORKDIR /root/or-tools_CentOS-7.6.1810-64bit_v7.4.7247
COPY Makefile .
RUN make detect
RUN make run SOURCE=examples/cpp/vrp_pickup_delivery.cc
```

note I had to patch the Makefile to remove abseil dynamic library since we use static ones now
```diff
--- old	2020-01-14 10:19:11.000000000 +0100
+++ Makefile	2020-01-14 10:19:42.000000000 +0100
@@ -68,37 +68,7 @@
   LIB_PREFIX = lib
   PRE_LIB = -Llib -Llib64
   CBC_LNK = -lCbcSolver -lCbc -lOsiCbc -lCgl -lClpSolver -lClp -lOsiClp -lOsi -lCoinUtils
-  ABSL_LNK = \
--labsl_bad_any_cast_impl \
--labsl_bad_optional_access \
--labsl_bad_variant_access \
--labsl_base \
--labsl_city \
--labsl_civil_time \
--labsl_debugging_internal \
--labsl_demangle_internal \
--labsl_dynamic_annotations \
--labsl_examine_stack \
--labsl_failure_signal_handler \
--labsl_graphcycles_internal \
--labsl_hash \
--labsl_hashtablez_sampler \
--labsl_int128 \
--labsl_leak_check \
--labsl_malloc_internal \
--labsl_optional \
--labsl_raw_hash_set \
--labsl_spinlock_wait \
--labsl_stacktrace \
--labsl_str_format_internal \
--labsl_strings \
--labsl_strings_internal \
--labsl_symbolize \
--labsl_synchronization \
--labsl_throw_delegate \
--labsl_time \
--labsl_time_zone
-  OR_TOOLS_LNK = $(PRE_LIB) $(ABSL_LNK) -lprotobuf -lglog -lgflags $(CBC_LNK) -lortools
+  OR_TOOLS_LNK = $(PRE_LIB) -lprotobuf -lglog -lgflags $(CBC_LNK) -lortools
   OBJ_OUT = -o #
   EXE_OUT = -o #
   O = .o
```

**Comment by Mizux** [comment]
note: we build the centos archive using the image
```dockerfile
FROM centos/devtoolset-7-toolchain-centos7
USER root
```

**Comment by Mizux** [comment]
Ok, you have to install gcc-7.3 using:

```sh
yum install centos-release-scl
yum install devtoolset-7-gcc-c++
export PATH=/opt/rh/devtoolset-7/root/usr/bin:$PATH
g++ --version
...
```

**Comment by developer-qoo10** [comment]
confirmed no problem in g ++ 7.3.1 20180303.
Thank you very much.

**Comment by Mizux** [comment]
FYI we are dropping the support for cento-7 to replace it by centos-8 which don't have this issue since g++ default package is ok
