### ISSUE TITLE
Capacity Constraints Problem

### ISSUE THREAD

**Issue by doublesunshine** [google/or-tools#1828]
There was a problem when I used the capacity limit feature.
I'VE SET UP FOUR VEHICLES FOR TRANSPORT
I set the capacity of the vehicle to 5,5,5,8
Final Planning Results:
First car, NO TRANSPORT
Second Vehicle, 6.3 T
Third Vehicle, Transport 4T
Fourth Vehicle, 9.5 T

I would like to ask why there is a planned load greater than the limited capacity

**Comment by doublesunshine** [comment]
这个问题解决了。
不仅仅距离矩阵是需要整数的。需求矩阵也同样需要整数。
直接小数点乘10就好了

**Comment by Mizux** [comment]
did you use integer everywhere instead of float/double ?

**Comment by doublesunshine** [comment]
> did you use integer everywhere instead of float/double ?


My Distance Matrix is an Integer, but there are decimals in the demand Matrix.

I found the problem

**Comment by Mizux** [comment]
Can you close this issue if it resolved and also provide the solution for others ?

Thanks !

**Comment by doublesunshine** [comment]
thanks ,i will help other people .
lol
