### ISSUE TITLE
Using MPVariable as MPConstrains bound [C++]

### ISSUE THREAD

**Issue by alegaballo** [google/or-tools#1832]
I want to use a BoolVar as lower bound in my constraint, y1 is a flag variable set to 1 one other conditions are satisfied. 

```cpp
namespace opr = operations_research;
double min = 10;
opr::MPVariable* const y1 = solver.MakeBoolVar("y1");
opr::MPConstraint *const c1 = solver.MakeRowConstraint(-min * y1, min);
```
This way the compiler complains because of incompatible data types, dereferencing the pointer doesn't work either and the only way I got it to compile is by using `y1->solution_value()`.
The problem is that I don't think that's the correct solution because it copies the current y1 value and I'd like the bound to change with y1.

**Comment by lperron** [comment]
As answered in s.o. use 2 equations.

**Comment by alegaballo** [comment]
@lperron I don't understand how it'd affect my issue, could you give me an example?

**Comment by lperron** [comment]
In your original example,

-M * y_1 <= x <= 10

Write it as:

x <= 10
x + M * y1 >= 0
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by alegaballo** [comment]
How could I not think that? Thank you!
