### ISSUE TITLE
VRP Perfomance

### ISSUE THREAD

**Issue by TrungTDD** [google/or-tools#1833]
Hi all, 
I have a problem with VRP solution. Now, I am testing on a large of deliveries location. I have used DBSCAN algorithm for clustering these deliveries location into smaller batch. 
Is there anyway to run VRP solution in batch of deliveries solution with initialize number_vehicles or max_distance.

**Comment by lperron** [comment]
I do not understand the question.

If you want to reach the user base, please use the mailing list. 
github issues have very limited audience.

**Comment by Mizux** [comment]
The mailing list is available at [or-tools-discuss](https://groups.google.com/forum/#!forum/or-tools-discuss)
