### ISSUE TITLE
Change-over after overlapping activities

### ISSUE THREAD

**Issue by DominikRoB** [google/or-tools#1834]
Hey,

I am trying to handle change-over times in the case of multiple activities on the same machine, where some acitivites can overlap. I am using the AddCircuits to sort the activities by start-times.
When one activity A is completly overlapping by another   (start < startA & end1 > endA) I want to remove activity A from the circuit. 

Problem:
I can not find a way to implement a relationship like
```
overlap_var = model.NewBoolVar("ActA is overlapped") # Intermediate variable
## What I tested:

model.Add(overlap_var == 1).OnlyEnforceIf( (start_var1 - start_var2 >= 0) and (end_var2 < end_var1))
# TypeError: bad operand type for unary -: 'BoundedLinearExpression'

model.Add(overlap_var == (start_var1 - start_var2 >= 0) and (end_var2 < end_var1)) 
# AttributeError: 'BoundedLinearExpression' object has no attribute 'Index'

```

Is it not possible to express the conditional I need for this?

Thank you!

**Comment by lperron** [comment]
A popular error :-)

https://github.com/google/or-tools/blob/stable/ortools/sat/doc/channeling.md


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 9 janv. 2020 à 14:10, DominikRoB <notifications@github.com> a
écrit :
