### ISSUE TITLE
Disjunction with different penalty for each index

### ISSUE THREAD

**Issue by PauliusGrigelis** [google/or-tools#1836]
In our case we have time windows for pickup and delivery location, each delivery can have multiple pickup locations. And this case is covered.

**The problem is when we can't make delivery in time.** In this case we expand time window interval.
To determine if we need to expand we look at dropped nodes, but for that we need to have solution. **Unfortunately, on next routing invocation/run we might have more vehicles and now we can make it in original time window.**

**Basically**, what we want to do is to tell that **1 order in time is better than 2 orders in route, if at least one of them would be delivered late**;

for example if we would duplicate order for original interval and extended, but assigned penalty accordingly: 
Order1_1 [500; 600] - penalty 3000
Order1_2 [500; 600] - penalty 3000 (different pickup location)
Order1_3 [500; 700] - penalty 1000
Order1_4 [500; 700] - penalty 1000 (different pickup location)

Order2_1 [600; 700] - penalty 3000
Order2_2 [600; 700] - penalty 3000

So, in our case **route to Order1_1 is better than Order1_3 and Order2_1, but if it's impossible then Order1_3 and Order2_1 is fine.**

Something like this would be awesome (unfortunately, impossible):
routing.AddDisjunction([Order1_1, Order1_2, Order1_3, Order1_4], [3000, 3000, 1000, 1000]);

Maybe, something like this could work: 

index1 = routing.AddDisjunction([Order1_1, Order1_2], 3000);
index2 = routing.AddDisjunction([Order1_3, Order1_4], 1000);
routing.AddDisjunction([index1, index2]); - doesn't seem right :D

or 

routing.AddDisjunction([Order1_1, Order1_2, Order1_3, Order1_4]);
routing.AddDisjunction([Order1_1, Order1_2], 3000);
routing.AddDisjunction([Order1_3, Order1_4], 1000);

Solution I see is where in single routing invocation we generate 2 solutions.
1st with original times, second with expanded time windows for dropped (unique) nodes. But it would slow us down, doing my best to avoid it.

I can provide more info if needed.
Thanks in advance.

**Comment by lperron** [comment]
Please use the mailing list. Issues have very limited visibility.

**Comment by PauliusGrigelis** [comment]
I'm not experienced on creating issues/tickets, so "mailing list" means nothing to me :D
If, by that, you mean "write an e-mail letter" I couldn't find email address. But it seems you, guys, have registered a ticket, right?
If I still have something to do to get my answer - could you provide an instruction? Thanks.

**Comment by Mizux** [comment]
@PauliusGrigelis  please ask on our dedicated forum (mailing list) at https://groups.google.com/forum/#!forum/or-tools-discuss

**Comment by PauliusGrigelis** [comment]
Issue moved to: https://groups.google.com/forum/#!topic/or-tools-discuss/wjbYOQZU5G0
