### ISSUE TITLE
An issue about pdptw

### ISSUE THREAD

**Issue by neumarina** [google/or-tools#184]
In pdptw.cc, we can add penalty costs to allow skipping nodes as follows.
`routing.AddDisjunction(orders, kPenalty);`
 But now, I don't want to skip any node. What should I do for this? I tried:
`routing.AddDisjunction(orders);`
But the assignment the solve return is null, the function **_LoadAndSolve_** return false, the program output _Error solving ..._
@lperron @mikrobi

**Comment by furnon** [comment]
Just don't call AddDisjunction at all; this will make all nodes mandatory.
Be careful though, first solution strategies such as ALL_UNPERFORMED won't
work in this case.

Vincent

**Comment by neumarina** [comment]
yeah, I comment AddDisjunction, the function **_LoadAndSolve_** return false, ALL_UNPERFORMED don't work, but another one can do.

 In this, I have a question: in my case, the number of vehicles is 12, the number of nodes is 223, use AddDisjunction, the solution this program return skip some nodes, the  resulting number of vehicle is 4,  of nodes is 217, remaining 8 vehicles and 6 nodes. Why do not assign the 8 vehicles to the 6 nodes instead of skipping them?

**Comment by furnon** [comment]
On Fri, May 13, 2016 at 10:51 AM, neumarina <notifications@github.com>
wrote:

> yeah, I comment AddDisjunction, the function *LoadAndSolve* return false,
> ALL_UNPERFORMED don't work, but another one can do.
>
> In this, I have a question: in my case, the number of vehicles is 12, the
> number of nodes is 223, use AddDisjunction, the solution this program
> return skip some nodes, the resulting number of vehicle is 4, of nodes is
> 217, remaining 8 vehicles and 6 nodes. Why do not assign the 8 vehicles to
> the 6 nodes instead of skipping them?
>

There are potentially two reasons:
a) the penalties are too low compared to other costs and it's cheaper to
skip nodes;
b) the 6 remaining nodes cannot actually be performed due to constraints of
your model; what you could test is manually build an initial solution from
the partial one you obtained and build single-node routes on unused
vehicles.

BTW what happens if you use PARALLEL_CHEAPEST_INSERTION as first solution
strategy ?

**Comment by neumarina** [comment]
> There are potentially two reasons:
a) the penalties are too low compared to other costs and it's cheaper to
skip nodes;
b) the 6 remaining nodes cannot actually be performed due to constraints of
your model; what you could test is manually build an initial solution from
the partial one you obtained and build single-node routes on unused
vehicles.

Considering the penalty, I tried many bigger values(10^12, my case normal maximun level is 10^6), it don't work.
For b), I really have no idea about the constraints of model. Where does the conflict may appear in?

I'm trying PARALLEL_CHEAPEST_INSERTION, the program is running.

**Comment by rajatjangir** [comment]
I am relatively new to this tool but if i may add. I have tried removing the AddDisjunction method from my program and it takes ages to run or probably doesn't run at all.
Also i 've tried almost all first solution strategies, many of them just returns null value as solution and other are just stuck calculating the solution.
Is there any documentation which explains the use of the build in functions which i may refer. It would be great if it is  in java or c#.

**Comment by dlahlou** [comment]
@rajatjangir 
Here is a link to the official [documentation](https://developers.google.com/optimization).
I hope this helps.

**Comment by rajatjangir** [comment]
@dlahlou 
Thanks for the link but i have been trying to find the solution in these documents for quite some time. But can's find something which explains the use of the following:
1. Use of penalties in vehicle routing .
2. How to calculate distance based on geographical coordinates.
3. Various first solution strategies.

And the most important of all
Why my nodes keep on dropping when i try to schedule the rides. Is there a way that when the cheapest or optimal solution is not available then at least all rides get scheduled even though at a higher cost.

Currently i have tried multiple time times but seems like  i am not able to find a good configuration for  this particular type of a problem.

I know its too much but i would really appreciate if someone could help on that.
Thanks

**Comment by dlahlou** [comment]
@rajatjangir 
It's a good idea to check the code comments in the C++ headers to know more about the use of a class or its members.

1. For example, to have more information about penalties, you can check this [comment](https://github.com/google/or-tools/blob/master/src/constraint_solver/routing.h#L510).
2. Or-tools doesn't provide a method to calculate distances, it's up to the user to calculate them and pass them to the solver via a callback as shown in this [example](https://github.com/google/or-tools/blob/master/examples/python/cvrptw.py#L153).
3. First solution strategies are documented [here](https://developers.google.com/optimization/reference/constraint_solver/routing/) and [here](https://github.com/google/or-tools/blob/master/src/constraint_solver/routing.h#L75).
4. To make all the nodes active, please use [AddAllActive()](https://github.com/google/or-tools/blob/master/src/constraint_solver/routing.h#L506) method. Note that in this case, the solver may not be able to find a feasible solution.

I hope this helps.
