### ISSUE TITLE
Module Selection

### ISSUE THREAD

**Issue by Legolash2o** [google/or-tools#1840]
**What language and solver does this apply to?**
All, Python, Java, C#, C++ / CP-SAT, Routing, Linear Solver

Python. aStar and MCF

**Describe the problem you are trying to solve.**

OR-Tools size

**Describe the solution you'd like**

Being able to install just the ones I need as I only use just aStar and MCF.

**Describe alternatives you've considered**
None

**Additional context**

I would like to put this on a lambda function in AWS but the total size to too big for it due to a storage space limitation.

**Comment by Mizux** [comment]
don't understand the issue, did you try to install the whole archive ?
You may selectively choose what you want otherwise, it's a prebuilt SDK...

note: Google Cloud Function with python 3.7 is working BTW see #1822.

**Comment by torressa** [comment]
Hey, I have the same issue. 
Used a similar docker image to the in `tools/docker/ubuntu-18.04.Dockerfile` and the resulting image ends up being ~3GB. However, I'm just using the CP-SAT solver.
Would be good if you could hint on how to selectively choose what to build/install.

**Comment by Mizux** [comment]
@torressa 
* In the foreseeable future,  I don't think we will put resources to reduce the "development environment size" used to be able to **BUILD** ortools. 
* In the foreseeable future,  I don't think we will have resources to split or-tools in small libraries with clean dependencies (or at least with the Makefile based build)
* Did you use/need all languages ? I mean you can only build the C++ library if you want...
* we provide an archive (that you can rebuild using make archive) which is smaller in size
* we provide prebuilt package for python/.Net is it sufficient for your use case (you can also rebuilt them using make target `python_package` or `dotnet_package` IIRC) ?
* We would like to provide maven package for Java ASAP
* I would like to provide a clean C++ CMake install to libortools could be easily integrated to any distro package manager, brew or vcpkg

**Comment by Mizux** [comment]
@Legolash2o did you want to use Python lambda function ?

**Comment by Legolash2o** [comment]
We currently use NodeJS but more than happy to use Python.

**Comment by torressa** [comment]
@Mizux Thanks for the fast reply!
That's fair enough, didn't expect you to.
Just thought that you guys might not test the whole library when making changes to a single component.

**Comment by torressa** [comment]
Was being stupid in my Dockerfile, the image with a full C++ installation is only 484 MB.
Just in case, here it is:

```docker
FROM ubuntu:18.04

#############
##  SETUP  ##
#############
RUN apt-get update -qq \
&& apt-get install -yq \
  git pkg-config wget make cmake autoconf libtool zlib1g-dev gawk g++ curl subversion \
  lsb-release \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

################
##  OR-TOOLS  ##
################
ARG SRC_GIT_BRANCH
ENV SRC_GIT_BRANCH ${SRC_GIT_BRANCH:-master}
ARG SRC_GIT_SHA1
ENV SRC_GIT_SHA1 ${SRC_GIT_SHA1:-unknown}

WORKDIR /root
# Download, prebuild and install or-tools for C++
RUN git clone -b "${SRC_GIT_BRANCH}" --single-branch https://github.com/google/or-tools \
&& echo "sha1: $(cd or-tools && git rev-parse --verify HEAD)" \
&& echo "expected sha1: ${SRC_GIT_SHA1}" \
&& cd or-tools/ && make detect && make third_party \
&& make detect_cc && make cc && make install_cc && make clean \
&& cd .. && rm -rf or-tools
```

**Comment by Mizux** [comment]
@torressa maybe you didn't spot it ;)
Once we have built the archive (`make archive`), I try to test (`make test_archive`) it in a minimal/clean image(s) located there: https://github.com/google/or-tools/tree/stable/tools/docker/test

e.g. for C++ against a ubuntu-18.04 container
https://github.com/google/or-tools/blob/b4298f709f116de08f490ac2bfe5e295fcc91f40/tools/docker/test/ubuntu-18.04/cc.Dockerfile#L1-L12

And everything is orchestrated through a Makefile at https://github.com/google/or-tools/blob/stable/tools/docker/Makefile

So we have a portable "CI" based on Makefile/Docker that we could test on various public CI (travis-CI, appveyor, circle-ci, github workflow actions) provided they have runner with make and docker available....

**Comment by torressa** [comment]
@Mizux Sweet, thanks for the clarification! :)
