### ISSUE TITLE
slackvar.setvalue not working

### ISSUE THREAD

**Issue by ah-ma** [google/or-tools#1844]
**What version of OR-tools and what language are you using?**
Version: 7.4.7247
Language: Python

Hello,
so i am trying to make a scenario such as to limit the number of nodes to be visited by the same vehicle after a certain node.
I control the problem with a time_dimension as well, but its irrelevant here.
so for instance if i choose node 20, and have a total number of nodes=40
then node 20 can be anywhere in the route as long as the max number of nodes to be visited after it is three 
how i thought i can do it is to make a capacity for vehicles = 40,
and let each node has a load of 1,
when node 20 is passed, then it resets the slackvar to 37,
that way it the vehicle can only take three more vehicles only

```python
capacity_dimension = routing.GetDimensionOrDie('Capacity')
capacity_dimension.SlackVar(20).SetValue(37)
```

what can i do?

 thx

**Comment by Mizux** [comment]
First you need to use the routing index manager to get the index of node 20.
https://github.com/google/or-tools/blob/b4298f709f116de08f490ac2bfe5e295fcc91f40/ortools/constraint_solver/samples/cvrp_reload.py#L184-L185

**Comment by ah-ma** [comment]
ok thx but what i have multiple vehicle capacities?
also this method sometimes produces segmentation_fault

**Comment by Mizux** [comment]
if you know the vehicle index, I would try
```python
node_index = manager.NodeToIndex(20)
end_index = routing.End(vehicle_index)
routing.solver().Add(
  distance_dimension.CumulVar(node_index) <=
  distance_dimension.CumulVar(end_index) + 3)
```

**Comment by ah-ma** [comment]
thats smart actually,
but don't you mean capacity_dimension?
assuming all loads are equal to 1 then with this 

node_index = manager.NodeToIndex(20)
end_index = routing.End(vehicle_index)
routing.solver().Add(
  capacity_dimension.CumulVar(node_index) <=
  capacity_dimension.CumulVar(end_index) + 3) 

it will always be before the end by 3 

but unfortunately i don't know the vehicle's index

**Comment by Mizux** [comment]
yes wrong copy paste, also I updated the equation (mix end_index and node_index).
But yes only work if you know the vehicle whose the node belongs to.
