### ISSUE TITLE
Solvers for Minimum Cost Flow Problems

### ISSUE THREAD

**Issue by CPMOliveira** [google/or-tools#1846]
Currently, the RELAX-IV algorithm is considered the most efficient.
I suggest using the following project to incorporate new ideas:

https://github.com/frangio68/Min-Cost-Flow-Class

**Comment by sschnug** [comment]
*Most efficient* always depends on the use-case. Not everyone works on the same data.

If one is interested to contribute on this topic, i would recommend to start with [Minimum-cost flow algorithms: an experimental evaluation](https://www.tandfonline.com/doi/abs/10.1080/10556788.2014.895828) (and the linked high-performance implementations within [CoinOR lemon](https://lemon.cs.elte.hu/trac/lemon)), which gives much more hints compared to aboves link (and includes it in it's experiments). It also says:

> We also considered two other solvers, RelaxIV and PDNET, but they did
not turn out to be robust. They tend to be orders of magnitude slower than costscaling and primal simplex codes, although RelaxIV is very fast on certain kinds of easy problem instances.
