### ISSUE TITLE
CP_Solver for non-delay schedules

### ISSUE THREAD

**Issue by nicopinio** [google/or-tools#1847]
**What language and solver does this apply to?**
Python, CP-SAT

**Describe the problem you are trying to solve.**
Hello everyone, I am working on the ft06 problem instance (https://github.com/google/or-tools/blob/stable/examples/python/jobshop_ft06_sat.py), whose optimal makespan is **55**, resulting in a **delay schedule**. In this schedule, from t=6, the third machine waits until t=8 when it can process a task that is then available. It does so even though at t=6, there is a task waiting at that machine which could be processed.

However, I'd like the solution to include only **non-delay** schedules, meaning that, whenever one or more jobs are available at a time t, the machine must be occupied and can not stay empty. Out of literature, I know that the optimum for that task is **57** (instead of 55).

Again: this means that, whenever there are tasks in the queue which can be processed by a machine, the machine is occupied immediately. Of course, a machine can still stay empty, but only when there are no tasks available for it at the moment.

**Describe the solution you'd like**
I'd like to adapt the jobshop_ft06 code in such a way that it considers the conditions of a non-delay schedule and outputs 57 instead of 55 as its optimal solution.

Any help would be greatly appreciated, since this is my first time working with ortools.
Thanks so much in advance!

**Comment by lperron** [comment]
Please use the mailing list.

Le sam. 18 janv. 2020 à 16:58, nicopinio <notifications@github.com> a
écrit :
