### ISSUE TITLE
Compiling from source with SCIP – missing lib/libsoplex-pic.a in SCIP install path

### ISSUE THREAD

**Issue by matus-tomlein** [google/or-tools#1848]
**What version of OR-tools and what language are you using?**
Version: v7.4
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
MIP with SCIP

**What operating system (Linux, Windows, ...) and version?**
macOS Catalina

**What did you do?**
Following instructions from https://developers.google.com/optimization/install/python/source_mac.
1. I downloaded SCIP (tried versions 6.0.0, 6.0.1, 6.0.2) and compiled using the make command as in instructions.
2. I added the path to the SCIP install folder to Makefile.local in ortools
3. When running make python, I get the following error:
```clang: error: no such file or directory: '.../scipoptsuite-6.0.1/install_dir/lib/libsoplex-pic.a'```

When looking in the install dir for SCIP, I can only find libsoplex.a, libsoplex-pic.a is not there. Have I missed some step or is the link to the libsoplex-pic.a file wrong?

**Comment by Mizux** [comment]
I guess you `-fPIC` enabled version of SCIP since we will load the ortools library into the python runtime.

seems related to https://github.com/google/or-tools/issues/1536#issuecomment-526942727 and #1115

**Comment by Mizux** [comment]
Seems to comes from:
https://github.com/google/or-tools/blob/abba070522729bea22af5861717eab6250560bd3/makefiles/Makefile.unix.mk#L195-L197

While I talked about `libsoplex.a` there
https://github.com/google/or-tools/issues/1115#issue-418693079

Need to investigate...

**Comment by pqant** [comment]
Hi , 
is there any improvement?

**Comment by Mizux** [comment]
we now ship or-tools with scip 7.0.1
