### ISSUE TITLE
Set different transit_evaluators_ for the same dimension.

### ISSUE THREAD

**Issue by tigrandp** [google/or-tools#185]
Is it possible to set different `transit_evaluators_` for the same dimension ? If it is the case then for `RoutingModel` and for any Dimension it will be easier to add additional constraints based which vehicles serves the customers.

**Comment by furnon** [comment]
If you mean if it is possible to set different evaluators for each vehicle
then you can use AddDimensionWithVehicleTransits.

**Comment by tigrandp** [comment]
@furnon Thanks !
