### ISSUE TITLE
Example bus_driver_scheduling_sat.py

### ISSUE THREAD

**Issue by xywwww1114** [google/or-tools#1851]
Hi all,

I tried to run the example ['bus_driver_scheduling_sat.py'](https://github.com/google/or-tools/blob/stable/examples/python/bus_driver_scheduling_sat.py) , but waited for long time and didn't get the final output, as attached.

I am wondering if this example has any requirements on the machine?

![图片2](https://user-images.githubusercontent.com/59903345/72786901-bb4f7200-3c69-11ea-8a8e-784a880b22b6.png)

**Comment by lperron** [comment]
The problem is hard. I have not found a good solution for anything but the
small instance.
I am working on it and welcome any improvement.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 21 janv. 2020 à 09:21, xywwww1114 <notifications@github.com> a
écrit :
