### ISSUE TITLE
Code signature not valid for use in process using Library Validation on MacOS

### ISSUE THREAD

**Issue by rch** [google/or-tools#1858]
**What version of OR-tools and what language are you using?**
Version: stable/v7.3 (and master a6a78552e)
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
MacOS 10.15.2

1. make third_party && make java && make test_java

Exception in thread "main" java.lang.UnsatisfiedLinkError:
`/or-tools/lib/libjniortools.jnilib: dlopen(/or-tools/lib/libjniortools.jnilib, 1): no suitable image found.  Did find:
	/or-tools/lib/libjniortools.jnilib: code signature in (/or-tools/lib/libjniortools.jnilib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.`

I'm using a new laptop.

**Comment by Mizux** [comment]
Can you provide us the java version you used ?
e.g. `java -version`

**Comment by Mizux** [comment]
Seems to be related to [macOS notarization](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution)

**Comment by rch** [comment]
Sorry for the delay - here's my Java version:

> $ java -version
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.2+10, mixed mode)

**Comment by romdarom** [comment]
Hi. i used java 11 as well as 8
I added the following to /Applications/Papyrus.app/Contents/Info.plist, as suggested 
`	<key>com.apple.security.cs.allow-unsigned-executable-memory</key>
	<true />
	<key>com.apple.security.cs.disable-library-validation</key>
	<true />
`
didn't change anything. 

> Seems to be related to [macOS notarization](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution)
> 
> Solution could be related to [electron-userland/electron-builder#3940 (comment)](https://github.com/electron-userland/electron-builder/issues/3940#issuecomment-501702531)

Any help available here? thx in any case

**Comment by cmcgann-plenty** [comment]
@rch Did you have success? I am having the same problem but am not able to apply the patterns from that post to the build process for or-tools. How do I get a plist built into the jar file - if that is what I need? And what do I use instead of the electron build scrip if running this using the recommended make system? Thanks.
