### ISSUE TITLE
Unsure if intended behavior of BoolXOr with power set Boolean variables

### ISSUE THREAD

**Issue by trianta2** [google/or-tools#1859]
**What version of OR-tools and what language are you using?**
Version: ortools==7.4.7247
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
macOS 10.14.5

**What did you do?**

Given the power set of a set of variables, I want to satisfy the Boolean AND of exactly one of those sets. For example, for variables [A, B, C], generate sets [[A], [B], [C], [A,B], ..., [A,B,C]], and have the solver satisfy the Boolean AND of exactly one of those sets.

In my implementation, I use an auxiliary variable that is 1 iff all variables in a given set are 1, via `AddMinEquality`. Then I XOR these aux variables.

The issue is that the XOR constraint on the aux variables doesn't seem to be enforced. Is this intended behavior?

```
from itertools import chain, combinations

from ortools.sat.python.cp_model import CpModel, CpSolver


def powerset(iterable, min_size=1):
    s = list(iterable)
    return chain.from_iterable(combinations(s, r) for r in range(min_size, len(s) + 1))


model = CpModel()

varz = [model.NewBoolVar(f"v{i}") for i in range(3)]

auxs = []
for p in powerset(varz):
    name = ",".join(v.Name() for v in p)
    aux = model.NewBoolVar(f"a({name})")
    model.AddMinEquality(aux, p)  # 1 iff all variables are 1
    auxs.append(aux)

model.AddBoolXOr(auxs)

model.Maximize(sum(varz))

solver = CpSolver()
solver.Solve(model)

for v in varz:
    print(f"{v.Name()} : {solver.Value(v)}")

print()

for v in auxs:
    print(f"{v.Name()} : {solver.Value(v)}")

```

Output:

```
v0 : 1
v1 : 1
v2 : 1

a(v0) : 1
a(v1) : 1
a(v2) : 1
a(v0,v1) : 1
a(v0,v2) : 1
a(v1,v2) : 1
a(v0,v1,v2) : 1
```

**What did you expect to see**

Only 1 aux variable with value 1. Since the power set contains subsets, I was expecting only one of the unary aux variables (i.e. a(v0), a(v1), a(v2)) to be 1 in order to maximize the objective.

**What did you see instead?**

All aux variables had value 1.

**Anything else we should know about your project / environment**

Nope.

**Comment by stradivari96** [comment]
Xor means that the sum is odd, you probably want `model.Add(sum(aux) == 1)`

**Comment by trianta2** [comment]
Ah, that was my misunderstanding. Your suggestion works and I now see the expected output. Thanks for the quick reply.
