### ISSUE TITLE
Using C# to call CBC in Google OR Tools

### ISSUE THREAD

**Issue by yongSolver** [google/or-tools#186]
I noticed that you can solver linear problems using C# with Google OR Tools. But I can't seem to find examples where you can solve integer problems using C# with Google OR Tools. The only example they have is in Python to call the CBC engine. Can you use C# to call CBC or SCIP?
Thanks!
Yong

**Comment by lperron** [comment]
examples/csharp/csintegerprogramming.cs demonstrates how to call CBC/SCIP
from C#.
Now, to use SCIP, you need to compile or-tools yourself, for licensing
reasons.

--Laurent

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-05-19 12:42 GMT-07:00 yongSolver <notifications@github.com>:

**Comment by yongSolver** [comment]
Cool! Thanks very much Laurent.
