### ISSUE TITLE
LongLongToLong is sealed

### ISSUE THREAD

**Issue by jweizman** [google/or-tools#1860]
Hi 
After upgrading to 7.4, my code does not compile anymore:
LongLongToLong appears to be sealed?
and i can't override Run anymode?
Thx

```cs
public class CallbackNodeEvaluator : LongLongToLong
    {
        public delegate int GetDistance(int fromNode, int toNode);
        
        public CallbackNodeEvaluator(RoutingIndexManager routingIndexManager, GetDistance callback, string dimensionName, int nodesCount, bool excludeStartAndEnd = true)
        {
          
           
        }

        public override long Run(long fromIndex, long toIndex)
        {
            var fromNode = _routingIndexManager.IndexToNode(fromIndex);
            var toNode = _routingIndexManager.IndexToNode(toIndex);
            return _distances[fromNode, toNode];
        }
    }
```

**What version of OR-tools and what language are you using?**
Version: 7.4
Language: C#

**Which solver are you using CPSAT

**What operating system (Linux, Windows, ...) and version?**

**What did you do?**

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by Mizux** [comment]
.Net API have been reworked to support lambda and be more ".Net friendly"
see:
https://github.com/google/or-tools/blob/858fa626959f7e386153af82756384b79f983b5a/ortools/constraint_solver/samples/SimpleRoutingProgram.cs#L45-L53

**Comment by Mizux** [comment]
otherwise you need to override Call()
https://github.com/google/or-tools/blob/858fa626959f7e386153af82756384b79f983b5a/ortools/constraint_solver/samples/Tsp.cs#L53-L90
https://github.com/google/or-tools/blob/858fa626959f7e386153af82756384b79f983b5a/ortools/constraint_solver/samples/Tsp.cs#L138-L139

**Comment by Mizux** [comment]
Seems to have been done in 7.0...
https://developers.google.com/optimization/support/release_notes#callbacks
