### ISSUE TITLE
   Capacity Constraints     The distance is always zero    

### ISSUE THREAD

**Issue by doublesunshine** [google/or-tools#1863]
I had a little problem with the Capacity Constraints

There's no way to tell. The distance from the route, it's always zero. I don't know what it is
always :
```
Route for vehicle 0:
 0 Load(0) ->  2 Load(240) ->  0 Load(240)
Distance of the route: 0m
Load of the route: 240
```
i don't know what happen

The interesting thing is, when I use the data, in the example, it shows the correct distance.
However, when I switched to my array, I had this  problem.

this is  port of data:
```python
# this is example 
    # data['distance_matrix'] = [
    #     [
    #         0, 548, 776, 696, 582, 274, 502, 194, 308, 194, 536, 502, 388, 354,
    #         468, 776, 662
    #     ],
    #     [
    #         548, 0, 684, 308, 194, 502, 730, 354, 696, 742, 1084, 594, 480, 674,
    #         1016, 868, 1210
    #     ],
    #     [
    #         776, 684, 0, 992, 878, 502, 274, 810, 468, 742, 400, 1278, 1164,
    #         1130, 788, 1552, 754
    #     ],
    #     [
    #         696, 308, 992, 0, 114, 650, 878, 502, 844, 890, 1232, 514, 628, 822,
    #         1164, 560, 1358
    #     ],
    #     [
    #         582, 194, 878, 114, 0, 536, 764, 388, 730, 776, 1118, 400, 514, 708,
    #         1050, 674, 1244
    #     ],
    #     [
    #         274, 502, 502, 650, 536, 0, 228, 308, 194, 240, 582, 776, 662, 628,
    #         514, 1050, 708
    #     ],
    #     [
    #         502, 730, 274, 878, 764, 228, 0, 536, 194, 468, 354, 1004, 890, 856,
    #         514, 1278, 480
    #     ],
    #     [
    #         194, 354, 810, 502, 388, 308, 536, 0, 342, 388, 730, 468, 354, 320,
    #         662, 742, 856
    #     ],
    #     [
    #         308, 696, 468, 844, 730, 194, 194, 342, 0, 274, 388, 810, 696, 662,
    #         320, 1084, 514
    #     ],
    #     [
    #         194, 742, 742, 890, 776, 240, 468, 388, 274, 0, 342, 536, 422, 388,
    #         274, 810, 468
    #     ],
    #     [
    #         536, 1084, 400, 1232, 1118, 582, 354, 730, 388, 342, 0, 878, 764,
    #         730, 388, 1152, 354
    #     ],
    #     [
    #         502, 594, 1278, 514, 400, 776, 1004, 468, 810, 536, 878, 0, 114,
    #         308, 650, 274, 844
    #     ],
    #     [
    #         388, 480, 1164, 628, 514, 662, 890, 354, 696, 422, 764, 114, 0, 194,
    #         536, 388, 730
    #     ],
    #     [
    #         354, 674, 1130, 822, 708, 628, 856, 320, 662, 388, 730, 308, 194, 0,
    #         342, 422, 536
    #     ],
    #     [
    #         468, 1016, 788, 1164, 1050, 514, 514, 662, 320, 274, 388, 650, 536,
    #         342, 0, 764, 194
    #     ],
    #     [
    #         776, 868, 1552, 560, 674, 1050, 1278, 742, 1084, 810, 1152, 274,
    #         388, 422, 764, 0, 798
    #     ],
    #     [
    #         662, 1210, 754, 1358, 1244, 708, 480, 856, 514, 468, 354, 844, 730,
    #         536, 194, 798, 0
    #     ],
    # ]
    # data['demands'] = [0, 1, 1, 2, 4, 2, 4, 8, 8, 1, 2, 1, 2, 4, 4, 8, 8]
    #
    # data['vehicle_capacities'] = [15, 15, 15, 15]
    # print("demands is %d" % sum(data['demands']))
    # data['num_vehicles'] = 4
    # data['depot'] = 0
```
this is my data:
```python 
    data['distance_matrix'] = [
 ['0', '5089', '2678', '2086', '656', '945', '1129', '901', '1979', '1929', '2496', '2042', '3320', '2731', '3701', '3094', '3709', '4830'],
 ['5097', '0', '7594', '6986', '5265', '4869', '4198', '5801', '5336', '4007', '4257', '4358', '1982', '2845', '4656', '2526', '1593', '502'],
 ['2736', '7640', '0', '1194', '2456', '2879', '3761', '2477', '3099', '3866', '4070', '4334', '5875', '5168', '4387', '5726', '6340', '7383'],
 ['1984', '6970', '1182', '0', '2311', '2599', '3011', '1447', '2069', '3583', '4150', '3303', '5202', '4613', '5267', '4975', '5590', '6711'],
 ['657', '5248', '2390', '2311', '0', '490', '1682', '1454', '2532', '1474', '2041', '2595', '3486', '2776', '3245', '3647', '4050', '4991'],
 ['955', '4842', '2821', '2609', '494', '0', '1979', '1752', '2829', '1068', '1636', '2893', '3176', '2371', '2840', '3655', '3740', '4585'],
 ['1124', '4184', '3689', '3013', '1667', '2001', '0', '1828', '1726', '2731', '3241', '1443', '2650', '2934', '4445', '2189', '2804', '3925'],
 ['910', '5790', '2468', '1441', '1453', '1742', '1830', '0', '1449', '2726', '3293', '2655', '4021', '3432', '4497', '3795', '4410', '5531'],
 ['1995', '5308', '3093', '2066', '2538', '2826', '1637', '1462', '0', '3810', '4378', '1148', '3790', '4297', '5582', '2993', '3927', '5048'],
 ['1930', '3994', '3798', '3584', '1469', '1073', '2723', '2727', '3805', '0', '759', '3868', '2436', '1522', '1963', '3522', '3064', '3737'],
 ['2495', '4240', '4013', '4149', '2034', '1638', '3230', '3292', '4370', '764', '0', '4407', '2682', '1590', '1461', '4360', '3310', '3983'],
 ['2051', '4333', '4320', '3293', '2594', '2882', '1442', '2758', '1150', '3866', '4409', '0', '2815', '3446', '5613', '1947', '2953', '4074'],
 ['3284', '1963', '5775', '5173', '3448', '3143', '2608', '3988', '3796', '2446', '2696', '2818', '0', '1284', '3362', '1711', '728', '1706'],
 ['2741', '2830', '5117', '4630', '2789', '2393', '2940', '3445', '4444', '1530', '1587', '3438', '1272', '0', '2233', '2950', '1900', '2573'],
 ['3692', '4647', '4323', '5279', '3231', '2835', '4427', '4489', '5567', '1961', '1450', '5604', '3345', '2231', '0', '5023', '3972', '4390'],
 ['3096', '2506', '5660', '4984', '3639', '3664', '2197', '3800', '2985', '3500', '4381', '1933', '1714', '2969', '5047', '0', '1241', '2247'],
 ['3707', '1579', '6272', '5596', '4048', '3743', '2808', '4411', '3945', '3072', '3322', '2968', '723', '1910', '3988', '1261', '0', '1319'],
 ['4826', '416', '7320', '6715', '4992', '4596', '3927', '5530', '5064', '3733', '3983', '4086', '1708', '2571', '4383', '2254', '1321', '0']]
    print(data['distance_matrix'])
    data['demands'] =[0, 150, 240, 350, 459, 220, 110, 229, 150, 140, 350, 350, 120, 90, 160, 240, 290, 220]
    print("demands is %d"%sum(data['demands']))
    data['vehicle_capacities'] = [500, 500,500,500,500, 600,600,600]
    data['num_vehicles'] = 8
    data['depot'] = 0
```

**Comment by doublesunshine** [comment]
Complete code
from __future__ import print_function
from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp
def create_data_model():
    """Stores the data for the problem."""
    data = {}
    # the exmple data 
    # data['distance_matrix'] = [
    #     [
    #         0, 548, 776, 696, 582, 274, 502, 194, 308, 194, 536, 502, 388, 354,
    #         468, 776, 662
    #     ],
    #     [
    #         548, 0, 684, 308, 194, 502, 730, 354, 696, 742, 1084, 594, 480, 674,
    #         1016, 868, 1210
    #     ],
    #     [
    #         776, 684, 0, 992, 878, 502, 274, 810, 468, 742, 400, 1278, 1164,
    #         1130, 788, 1552, 754
    #     ],
    #     [
    #         696, 308, 992, 0, 114, 650, 878, 502, 844, 890, 1232, 514, 628, 822,
    #         1164, 560, 1358
    #     ],
    #     [
    #         582, 194, 878, 114, 0, 536, 764, 388, 730, 776, 1118, 400, 514, 708,
    #         1050, 674, 1244
    #     ],
    #     [
    #         274, 502, 502, 650, 536, 0, 228, 308, 194, 240, 582, 776, 662, 628,
    #         514, 1050, 708
    #     ],
    #     [
    #         502, 730, 274, 878, 764, 228, 0, 536, 194, 468, 354, 1004, 890, 856,
    #         514, 1278, 480
    #     ],
    #     [
    #         194, 354, 810, 502, 388, 308, 536, 0, 342, 388, 730, 468, 354, 320,
    #         662, 742, 856
    #     ],
    #     [
    #         308, 696, 468, 844, 730, 194, 194, 342, 0, 274, 388, 810, 696, 662,
    #         320, 1084, 514
    #     ],
    #     [
    #         194, 742, 742, 890, 776, 240, 468, 388, 274, 0, 342, 536, 422, 388,
    #         274, 810, 468
    #     ],
    #     [
    #         536, 1084, 400, 1232, 1118, 582, 354, 730, 388, 342, 0, 878, 764,
    #         730, 388, 1152, 354
    #     ],
    #     [
    #         502, 594, 1278, 514, 400, 776, 1004, 468, 810, 536, 878, 0, 114,
    #         308, 650, 274, 844
    #     ],
    #     [
    #         388, 480, 1164, 628, 514, 662, 890, 354, 696, 422, 764, 114, 0, 194,
    #         536, 388, 730
    #     ],
    #     [
    #         354, 674, 1130, 822, 708, 628, 856, 320, 662, 388, 730, 308, 194, 0,
    #         342, 422, 536
    #     ],
    #     [
    #         468, 1016, 788, 1164, 1050, 514, 514, 662, 320, 274, 388, 650, 536,
    #         342, 0, 764, 194
    #     ],
    #     [
    #         776, 868, 1552, 560, 674, 1050, 1278, 742, 1084, 810, 1152, 274,
    #         388, 422, 764, 0, 798
    #     ],
    #     [
    #         662, 1210, 754, 1358, 1244, 708, 480, 856, 514, 468, 354, 844, 730,
    #         536, 194, 798, 0
    #     ],
    # ]
    # data['demands'] = [0, 1, 1, 2, 4, 2, 4, 8, 8, 1, 2, 1, 2, 4, 4, 8, 8]
    #
    # data['vehicle_capacities'] = [15, 15, 15, 15]
    # print("demands is %d" % sum(data['demands']))
    # data['num_vehicles'] = 4
    # data['depot'] = 0


    #my data 
    data['distance_matrix'] = [['0', '5089', '2678', '2086', '656', '945', '1129', '901', '1979', '1929', '2496', '2042', '3320', '2731', '3701', '3094', '3709', '4830'], ['5097', '0', '7594', '6986', '5265', '4869', '4198', '5801', '5336', '4007', '4257', '4358', '1982', '2845', '4656', '2526', '1593', '502'], ['2736', '7640', '0', '1194', '2456', '2879', '3761', '2477', '3099', '3866', '4070', '4334', '5875', '5168', '4387', '5726', '6340', '7383'], ['1984', '6970', '1182', '0', '2311', '2599', '3011', '1447', '2069', '3583', '4150', '3303', '5202', '4613', '5267', '4975', '5590', '6711'], ['657', '5248', '2390', '2311', '0', '490', '1682', '1454', '2532', '1474', '2041', '2595', '3486', '2776', '3245', '3647', '4050', '4991'], ['955', '4842', '2821', '2609', '494', '0', '1979', '1752', '2829', '1068', '1636', '2893', '3176', '2371', '2840', '3655', '3740', '4585'], ['1124', '4184', '3689', '3013', '1667', '2001', '0', '1828', '1726', '2731', '3241', '1443', '2650', '2934', '4445', '2189', '2804', '3925'], ['910', '5790', '2468', '1441', '1453', '1742', '1830', '0', '1449', '2726', '3293', '2655', '4021', '3432', '4497', '3795', '4410', '5531'], ['1995', '5308', '3093', '2066', '2538', '2826', '1637', '1462', '0', '3810', '4378', '1148', '3790', '4297', '5582', '2993', '3927', '5048'], ['1930', '3994', '3798', '3584', '1469', '1073', '2723', '2727', '3805', '0', '759', '3868', '2436', '1522', '1963', '3522', '3064', '3737'], ['2495', '4240', '4013', '4149', '2034', '1638', '3230', '3292', '4370', '764', '0', '4407', '2682', '1590', '1461', '4360', '3310', '3983'], ['2051', '4333', '4320', '3293', '2594', '2882', '1442', '2758', '1150', '3866', '4409', '0', '2815', '3446', '5613', '1947', '2953', '4074'], ['3284', '1963', '5775', '5173', '3448', '3143', '2608', '3988', '3796', '2446', '2696', '2818', '0', '1284', '3362', '1711', '728', '1706'], ['2741', '2830', '5117', '4630', '2789', '2393', '2940', '3445', '4444', '1530', '1587', '3438', '1272', '0', '2233', '2950', '1900', '2573'], ['3692', '4647', '4323', '5279', '3231', '2835', '4427', '4489', '5567', '1961', '1450', '5604', '3345', '2231', '0', '5023', '3972', '4390'], ['3096', '2506', '5660', '4984', '3639', '3664', '2197', '3800', '2985', '3500', '4381', '1933', '1714', '2969', '5047', '0', '1241', '2247'], ['3707', '1579', '6272', '5596', '4048', '3743', '2808', '4411', '3945', '3072', '3322', '2968', '723', '1910', '3988', '1261', '0', '1319'], ['4826', '416', '7320', '6715', '4992', '4596', '3927', '5530', '5064', '3733', '3983', '4086', '1708', '2571', '4383', '2254', '1321', '0']]
    print(data['distance_matrix'])
    data['demands'] =[0, 150, 240, 350, 459, 220, 110, 229, 150, 140, 350, 350, 120, 90, 160, 240, 290, 220]
    print("demands is %d"%sum(data['demands']))
    data['vehicle_capacities'] = [500, 500,500,500,500, 600,600,600]
    data['num_vehicles'] = 8
    data['depot'] = 0
    return data


def print_solution(data, manager, routing, assignment):
    """Prints assignment on console."""
    total_distance = 0
    total_load = 0
    for vehicle_id in range(data['num_vehicles']):
        index = routing.Start(vehicle_id)
        plan_output = 'Route for vehicle {}:\n'.format(vehicle_id)
        route_distance = 0
        route_load = 0
        while not routing.IsEnd(index):
            node_index = manager.IndexToNode(index)
            route_load += data['demands'][node_index]
            plan_output += ' {0} Load({1}) -> '.format(node_index, route_load)
            previous_index = index
            index = assignment.Value(routing.NextVar(index))
            route_distance += routing.GetArcCostForVehicle(
                previous_index, index, vehicle_id)
        plan_output += ' {0} Load({1})\n'.format(manager.IndexToNode(index),
                                                 route_load)
        plan_output += 'Distance of the route: {}m\n'.format(route_distance)
        plan_output += 'Load of the route: {}\n'.format(route_load)
        print(plan_output)
        total_distance += route_distance
        total_load += route_load
    print('Total distance of all routes: {}m'.format(total_distance))
    print('Total load of all routes: {}'.format(total_load))


def main():
    """Solve the CVRP problem."""
    # Instantiate the data problem.
    data = create_data_model()

    # Create the routing index manager.
    manager = pywrapcp.RoutingIndexManager(len(data['distance_matrix']),
                                           data['num_vehicles'], data['depot'])

    # Create Routing Model.
    routing = pywrapcp.RoutingModel(manager)


    # Create and register a transit callback.
    def distance_callback(from_index, to_index):
        """Returns the distance between the two nodes."""
        # Convert from routing variable Index to distance matrix NodeIndex.
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return data['distance_matrix'][from_node][to_node]

    transit_callback_index = routing.RegisterTransitCallback(distance_callback)

    # Define cost of each arc.
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)


    # Add Capacity constraint.
    def demand_callback(from_index):
        """Returns the demand of the node."""
        # Convert from routing variable Index to demands NodeIndex.
        from_node = manager.IndexToNode(from_index)
        return data['demands'][from_node]

    demand_callback_index = routing.RegisterUnaryTransitCallback(
        demand_callback)
    routing.AddDimensionWithVehicleCapacity(
        demand_callback_index,
        0,  # null capacity slack
        data['vehicle_capacities'],  # vehicle maximum capacities
        True,  # start cumul to zero
        'Capacity')

    # Setting first solution heuristic.
    search_parameters = pywrapcp.DefaultRoutingSearchParameters()
    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)

    # Solve the problem.
    assignment = routing.SolveWithParameters(search_parameters)

    # Print solution on console.
    if assignment:
        print_solution(data, manager, routing, assignment)


if __name__ == '__main__':
    main()

**Comment by Mizux** [comment]
your new distance matrix contain some string, please remove the quotes...

**Comment by doublesunshine** [comment]
> Your new distance matrix contain some strings instead of integers i.e. 0.
> Please remove the quotes `'1234'` -> `1234` ...

thanks i finally slove this probolem 
and i closed this issues
