### ISSUE TITLE
CVRPTW, Weekly Schedule, Priority Nodes, Multiple Visits - Help defining strategy

### ISSUE THREAD

**Issue by petrilloa** [google/or-tools#1866]
**Version**: 7.0
**Language**: Python
**Solver**: Routing Solver
**OS**: Ubuntu 16

Hi everyone, we are working on a problem for VRPTW and can't decide yet what is the better strategy to solve it.

- Start and End node: 0 (the same - every day the truck start on a depot, recolects bins, and goes back to the depot)
- Weekly Schedule - with one truck (one more if there is no solution as a backup)
- Nodes - All have TIME WINDOWS CONSTRAINTS and DEPENDS on the DAY (For example, some are CLOSED on MONDAY MORNING, others on WEDNESDAY afternoon, and SOME ARE OPEN in the MORNING and in the AFTERNOON, but closed at NOON (siesta time).
- Nodes - All have DEMANDS
- Nodes that are obligatory - Some NODES needs to be visited every day of the week
- Nodes with Priority and weekly visits - Must be visited, at least once a week, the priority ones first
- Nodes number - Around 350 (40 of them are Obligatory)

1 - The first question we asked ourselves is about how to face the weekly agenda strategy.
**As a first option**, we imagine **several iterations of the algorithm**, **WITHOUT adding duplicate nodes** (that is, the nodes that should be visited every day), and adding all the flexible nodes (that is, those that I should go once a week), with disjunction and penalty according to the degree of priority of the same.
All the nodes that are excluded from day 1 are added to day 2, where the mandatory nodes are added again and so on until the end of the week.

This approach has a problem that if I can't find a solution, **I should add a second truck (Backup)** one day, which I'm not sure how to do (maybe add a second truck to the route, with a high associated penalty cost? )

2 - **As a second option**, we thought of a more elegant solution.
Instead of iterating on the algorithm per day, use a strategy of **DUPLICATE mandatory nodes** (for each day of the week).
For this strategy, we think 2 options.
2.1 - **As a first option, add trucks for each day** (in reality it is only one truck per day). Then, to the duplicate mandatory nodes, add a relationship with each truck (to make sure it goes through a mandatory node every day, but not sure how to do this).
But, I'm not sure, how to add a second truck, backup in case you can't find a solution.
**Another problem with this solution** is that I don't know how to handle the different schedules of each node per day, that is, a node can be closed on a Tuesday, on a schedule, but open on other days.

2.2 - Think of a strategy similar to that of recharging, forcing the truck to return to the warehouse when the tour schedule is exceeded (8AM to 5PM). We don't develop this strategy too much yet.

Before moving forward in one direction, we wanted to ask for help in the forum, to try to identify the best strategy. We greatly appreciate your help and comments.

**Comment by lperron** [comment]
Please ask on the mailing list.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 4 févr. 2020 à 13:34, Andrés Petrillo <notifications@github.com> a
écrit :
