### ISSUE TITLE
Integer variable bounds not correctly exporting

### ISSUE THREAD

**Issue by gtshteve** [google/or-tools#187]
Posted this in the discussion forum but realize this is probably a more appropriate place...

I was trying to compare the performance gap between CBC and Gurobi and tried to save some headache by exporting the model I had built using Google OR Tools. Gurobi was saying that the problem instance was infeasible, as I was watching CBC churn away and produce feasible solutions, so I knew this couldn't be the case.

A little digging and I found that the variable bounds were not correctly exporting for my integer variables. They were all showing up with 0-1 bounds even though they were general integer variables. This happened with both LP format and MPS format.

Can other people verify this issue?

**Comment by lperron** [comment]
I believe we fixed the model exporter.

Therefore, I will close this issue.
