### ISSUE TITLE
CVRP-TW-reload with time/distance matrix 

### ISSUE THREAD

**Issue by veer5551** [google/or-tools#1873]
Language:
Python 

Hello,
I am a newbie to the or-tools and trying to model a problem similar to the CVRP-TW-reload one.
This is the model I am referring to https://github.com/google/ortools/blob/stable/ortools/constraint_solver/samples/cvrp_reload.py

It is modeled with locations of the nodes. How can I use the time/distance matrix to model this problem? 

Any help is greatly appreciated!
Thanks in advance!

**Comment by Mizux** [comment]
you can look at https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/samples/tsp_distance_matrix.py
BTW you just need to feed the RoutingSolver by registering some transit callback(s) so you can compute the time/distance matrix as you want provided that your function return integer...

**Comment by veer5551** [comment]
Hello again!

I tried to input the distance matrix from the reference you provided and changed the RoutingIndexManager as follows:
```
    manager = pywrapcp.RoutingIndexManager(len(data['distance_matrix']),
                                           data['num_vehicles'], data['depot'])
```

But I guess all the callbacks in the CVRP_TW_reload model are designed based on the locations and their indices as I am getting the error in the **travel_time ( create_time_evaluator).**

Could you please suggest me how do I modify the existing model's callbacks to support the Time matrix I give as an input.

Thanks in advance!

**Comment by lperron** [comment]
Please use the mailing list.
The issues are not meant for modeling questions.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by veer5551** [comment]
Yes sure.

Posted the topic on google groups/or-tools discussion. ( You mean the same right? I have the slightest idea about mailing list :) )

Sorry for the inconvenience caused!

Thanks for the help!
You are doing a great job!
