### ISSUE TITLE
【NEED HELP】 cvrptw with constraints of different returning back time to depot for each vehiclech 

### ISSUE THREAD

**Issue by ECHOCHENCC** [google/or-tools#1877]
This is quiet a powerful library!
I have solved most of VRP problem, but get stuck with the problem I mentioned on the title.
**My question is:**
Besides the time windows for each location, there is another constraints that require each vehicle to return to the depot(start location) at different time and this return by time is depend on which customers will be visited(different customers have different required return by time). So we can not duplicate the start nodes before I run the model.

Do someone can give me suggestions to solve it by using OR tools? 
Thanks a lot!

**Comment by Mizux** [comment]
Hi,

For modeling issue, prefer to use the mailing list: https://groups.google.com/forum/#!forum/or-tools-discuss

**Comment by Mizux** [comment]
@ECHOCHENCC  do you have a specific customer per location ? did you try to add some pick-up and delivery constraints ?

**Comment by ECHOCHENCC** [comment]
@Mizux Hi! Thank you so much for your suggestion, which is very useful to me!
