### ISSUE TITLE
DLL load failed for latest version of ortools

### ISSUE THREAD

**Issue by veer5551** [google/or-tools#1879]
Python Version - 3.7
ortools Version - 7.57466
IDE - Pycharm

After installing the latest version of ortools via pip, it gives me the following error:
``    from . import _pywrapcp
ImportError: DLL load failed: The specified module could not be found.``

I tried the suggestions after googling the error to no avail.

Any help is greatly appreciated!
Thanks a lot in advance!

**Comment by lperron** [comment]
Please install visual studio 2019 redistributable libraries.

**Comment by veer5551** [comment]
Hey, 
Thank you so much for the amazingly fast reply.
It is working fine now.

Thanks a lot!!

**Comment by Mizux** [comment]
duplicate of #1872
