### ISSUE TITLE
CVRP_TW_reload stops giving solution when number of locations is changed

### ISSUE THREAD

**Issue by veer5551** [google/or-tools#1880]
Python - 3.7
ortools - 7.5.7466

Hello team,

I am a newbie to ortools and trying to model a problem similar to:
https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/samples/cvrp_reload.py

I am trying to play with the model to understand it better. 
But I noticed that the model stops giving the solution as soon as I update the number of nodes/locations.
I have no clue what might be causing this.

I changed the following line to update the number of locations. (Tried with a lesser number)
   ` data['num_locations'] =  len(data['locations'])`
with 
   ` data['num_locations'] = 10` or so.

Am I missing something here?

Any help is greatly appreciated!
Thanks a lot in advance!!

**Comment by lperron** [comment]
Please use the mailing list.

Github issues have very limited reach, and any answer I give will not
benefit the other users.

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
