### ISSUE TITLE
[CP-Sat, Python, 7.5.7466]  Increased amount of unexpected crashes

### ISSUE THREAD

**Issue by DominikRoB** [google/or-tools#1882]
I'm running everything on a windows 10 machine with PyCharmPyCharm 2019.2.4 (Professional Edition).

Since the 7.5 update I am experiencing increased amount of crashes, without trackback, only

> Process finished with exit code -1073741819 (0xC0000005)

and

> Check failed: SolutionIsFeasible( *shared_->model_proto, std::vector<int64>(local_response.solution().begin(), local_response.solution().end())) scheduling_random_lns_auto(d=0.71 s=33 t=0.10 p=1.00)
> *** Check failure stack trace: ***
>     @   00007FFC76A7A72B  PyInit__pywrapsat
>     @   00007FFC76A78979  PyInit__pywrapsat
>     @   00007FFC76B0CEAF  PyInit__pywrapsat
>     @   00007FFC76C7DD59  PyInit__pywrapsat
>     @   00007FFC76E5BE21  PyInit__pywrapsat
>     @   00007FFC76E5AC1F  PyInit__pywrapsat
>     @   00007FFCBB811FFA  _o_exp
>     @   00007FFCBE847974  BaseThreadInitThunk
>     @   00007FFCBF0FA271  RtlUserThreadStart
> Process finished with exit code -1073740791 (0xC0000409)

It usually happens, when I keep several consoles with the same (or similar) models open, or when I run the same model with changed parameters several times within one script. Running my model a single time did not lead to this, so far - but for my project I have to run it many consecutive times.

I had the 0xC0000005 exit-code occure before, when the memory was maxed out, but I made sure the memory was always under 70 %, when it happened lately.

**Comment by lperron** [comment]
Could you send us one model that crashes.

I am actually debugging this code and would like to make sure we did your
problem.

Sorry about that.

--Laurent

PS: this is due to an over zealous presolve. You can disable it for the
time being.

Le jeu. 13 févr. 2020 à 17:34, DominikRoB <notifications@github.com> a
écrit :

**Comment by DominikRoB** [comment]
Here's one of the crashing models. It does not crash each time, but quite regularly.

I did try disabling cp_model_presolve, but that leads to a even more certain crash, it seems.
(Also with Process finished with exit code -1073741819 (0xC0000005))

I'm still trying to find a good situation to regularly reproduce the case for
> Check failed: SolutionIsFeasible( *shared_->model_proto,  [...] Process finished with exit code -1073740791 (0xC0000409)


[model.zip](https://github.com/google/or-tools/files/4225062/model.zip)

**Comment by lperron** [comment]
Thanks.
It should be fixed on master.
