### ISSUE TITLE
Ruby Library

### ISSUE THREAD

**Issue by ankane** [google/or-tools#1884]
Hi, thanks for this great library! I wanted to let you know that [Ruby bindings](https://github.com/ankane/or-tools) are now available. They use the C++ API and follow the Python API (with minor changes to make it more Ruby-like).

If you have any feedback, let me know or feel free to create an issue on the project. Thanks!

**Comment by Mizux** [comment]
Hi,

good job ! If I understand correctly, you are [wrappin the ortools C++ library by hand](https://github.com/ankane/or-tools/blob/master/ext/or-tools/ext.cpp) using the [rice](https://github.com/jasonroelofs/rice) framework and using the [ubuntu v7.5 archive artifact](https://github.com/ankane/or-tools/blob/master/test/ci/install_or_tools.sh) ?

I never did any ruby, does following the python convention (PEP8) is the best choice for building a ruby API wrapper ? (i.e. does ruby provide guide line, coding convention to follow ?)

@lperron concernning rice:
> Rice is known to work on *nix and OSX. Windows is not currently supported.
   Rice requires a C++ compiler with support for C++14 or later.

src: https://github.com/jasonroelofs/rice#installation-installation

**Comment by ankane** [comment]
Thanks @Mizux, you're correct. It uses Rice to wrap the C++ library, which is similar to pybind11 in Python. It follows Ruby conventions and style (rather than PEP8), but uses the class and method naming from Python instead of C++ (for instance `solver.add` instead of `solver.MakeRowConstraint`). I've tested it on both Linux and Mac, and plan to investigate Rice on Windows.

**Comment by joegaudet** [comment]
Man, wish this existed a year ago. I wrote my project in purging, and had to do RPC over https.

**Comment by ankane** [comment]
Hey @Mizux, okay to close? I just wanted to share, but not sure if you have other plans with the milestones.

**Comment by Mizux** [comment]
okay, so I'll close it since we won't integrate this ruby wrapper in the near future...

But @community don't hesitate to use it and reply in this issue if there is a increasing number who want it we may reevaluate it...
BTW many thanks for sharing it !!!

**Comment by ankane** [comment]
np, thanks for building this great library. Will continue to follow the Python API (while keeping it Ruby-like). I've also started adding higher level interfaces for a few tasks, but may move them to a separate project (or many projects) in the future so the main library just follows Python. That's the current thinking anyways.
