### ISSUE TITLE
VRP with capacity and compartment constraints - Strange solutions

### ISSUE THREAD

**Issue by AntonisKl** [google/or-tools#1885]
**Version**: The default one that is installed with pip3
**Language**: Python
**Solver**: Routing Solver
**OS**: Ubuntu 18.04

Hello,

I have a simple code of a VRP with compartments and capacity constraints. I have tried running the program with many different combinations of first solution strategies and local search strategies(metaheuristics). However, in each of the program's executions some of the vehicles' routes are not optimal. Here are the results displayed on the map: [results.zip](https://github.com/google/or-tools/files/4215381/results.zip) . Each html except "all.html" contains the route of a vehicle. "all.html" contains all the routes of the vehicles.
 Could you please provide any suggestion for optimizing all the vehicles' routes?

My code is displayed below. The distance matrix contains distances which are in meters and are produced by using Google's Distance Matrix Service .

```python
def ignore_return_to_premise(d_matrix):
    for d in d_matrix:
        d[0] = 0


class CVRPTW:
    def __init__(self, data):
        self.data = data
        self.assignment = None

        # Create the routing index manager.
        self.manager = pywrapcp.RoutingIndexManager(len(data['distance_matrix']),
                                                    data['num_vehicles'], data['depot'])

        # Create Routing Model.
        self.routing = pywrapcp.RoutingModel(self.manager)

        # Register transit callback
        self.transit_callback_index = self.routing.RegisterTransitCallback(self.distance_callback)

        # Define cost of each arc.
        self.routing.SetArcCostEvaluatorOfAllVehicles(self.transit_callback_index)

        dimension_name = 'Distance'
        self.routing.AddDimension(
            self.transit_callback_index,
            0,  # no slack
            int(np.sum(data['distance_matrix'])),  # vehicle maximum travel distance
            True,  # start cumul to zero
            dimension_name)
        self.distance_dimension = self.routing.GetDimensionOrDie(dimension_name)
        self.distance_dimension.SetGlobalSpanCostCoefficient(100)

        # Add Capacity constraint
        self.total_demand_callback_index = self.routing.RegisterUnaryTransitCallback(self.total_demand_callback)
        self.routing.AddDimensionWithVehicleCapacity(
            self.total_demand_callback_index,
            0,  # null capacity slack
            data['total_vehicle_capacities'],  # vehicle maximum capacities
            True,  # start cumul to zero
            'Capacity')
        capacity_dimension = self.routing.GetDimensionOrDie('Capacity')

        # Add Compartment constraint
        self.demand_items_count_callback_index = self.routing.RegisterUnaryTransitCallback(
            self.demand_items_count_callback)
        self.routing.AddDimensionWithVehicleCapacity(
            self.demand_items_count_callback_index,
            0,  # null capacity slack
            data['vehicle_compartments'],  # vehicle maximum compartments
            True,  # start cumul to zero
            'Compartment')
        compartment_dimension = self.routing.GetDimensionOrDie('Compartment')

        ignore_return_to_premise(self.data['distance_matrix'])

        # Setting first solution heuristic.
        self.search_parameters = pywrapcp.DefaultRoutingSearchParameters()
        self.search_parameters.first_solution_strategy = (
            routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)  # CHRISTOFIDES PATH_CHEAPEST_ARC

    def solve(self):
        # Solve the problem.
        self.assignment = self.routing.SolveWithParameters(self.search_parameters)

        return self.manager, self.routing, self.assignment


    # CALLBACKS
    # distance transit callback
    def distance_callback(self, from_index, to_index):
        """Returns the distance between the two nodes."""
        # Convert from routing variable Index to distance matrix NodeIndex.
        from_node = self.manager.IndexToNode(from_index)
        to_node = self.manager.IndexToNode(to_index)
        return self.data['distance_matrix'][from_node][to_node]

    def total_demand_callback(self, from_index):
        """Returns the demand of the node."""
        # print(from_index)
        # Convert from routing variable Index to demands NodeIndex.
        from_node = self.manager.IndexToNode(from_index)
        return self.data['total_demands'][from_node]
        # return self.data['demands'][from_node]

    def demand_items_count_callback(self, from_index):
        """Returns the demand items count of the node."""
        # Convert from routing variable Index to demands NodeIndex.
        from_node = self.manager.IndexToNode(from_index)
        return self.data['demands_items'][from_node]
```

**Comment by Mizux** [comment]
For modeling related issue you should use the mailing list instead...

* you could remove `self.distance_dimension.SetGlobalSpanCostCoefficient(100)` to speed up the solution search
* Which kind of LNS did you use ? I saw, nothing here... Please also note there is tons of parameters for the LNS...

**Comment by AntonisKl** [comment]
I tried using each of the local search strategies mentioned here https://developers.google.com/optimization/routing/routing_options#local_search_options without any luck. Is this what you mean by Large Neighborhood Search? If not, could you please provide a link with information about changing the parameters for LNS?
Also, I do not understand why some routes of the vehicles are so sub-optimal with the PATH_CHEAPEST_ARC as first solution strategy. As I understand, with this strategy each node gets connected with its nearest node. But, in some of the results' maps this is clearly not the case.

**Comment by Mizux** [comment]
I means when using the GLS aka GUIDED_LOCAL_SEARCH you can tweak few parameters:

First you have a Second constructor for the `RoutingModel` which take a `RoutingModelParameter`
https://github.com/google/or-tools/blob/858fa626959f7e386153af82756384b79f983b5a/ortools/constraint_solver/routing.h#L368-L369
Which is:
https://github.com/google/or-tools/blob/858fa626959f7e386153af82756384b79f983b5a/ortools/constraint_solver/routing_parameters.proto#L431-L433
with `ConstraintSolverParameters` being:
https://github.com/google/or-tools/blob/858fa626959f7e386153af82756384b79f983b5a/ortools/constraint_solver/solver_parameters.proto#L25-L140

Then in the `RoutingSearchParameter` you have;
https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/routing_parameters.proto#L38
You have tons of parameters for the LNS
see: https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/routing_parameters.proto#L93


So first add something like this to your `self.search_parameters`
```python
self.search_parameters.log_search = True
self.search_parameters.time_limit.seconds = 30
self.search_parameters.local_search_metaheuristic = (
        routing_enums_pb2.LocalSearchMetaheuristic.GUIDED_LOCAL_SEARCH)
```

**Comment by AntonisKl** [comment]
Thank you for your suggestion.
I tried tweaking these parameters:
use_tsp_opt
use_path_lns
use_relocate
use_light_relocate_pair
use_relocate_subtrip
use_exchange
use_exchange_pair
use_exchange_subtrip
use_relocate_neighbors

But, the results are still sub-optimal.
