### ISSUE TITLE
Where can I find log file from LOG_IF, utilizing pywraplp

### ISSUE THREAD

**Issue by mlh621** [google/or-tools#1889]
Apologize if this isn't the right place to post this, but when I clicked on "Modeling question" in the form, it brought me to the Google ortools group. When I tried adding a topic there it said I didn't have permission. I didn't see a way to join.

**What version of OR-tools and what language are you using?**
Version: 7.5
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)** : COIN-OR CBC & the BOP solver

**What operating system (Linux, Windows, ...) and version?**: Linux and Windows (two different models, two different requirements/dev environments)

**What did you do?**
The main similarity between the two models I created is that they are both MIP problems. I was finding with my code that after running solve, and then trying to verify the solution the kernel dies. 
So:
`self.solution_indicator = self.solver.Solve()
self.verify_solution = self.solver.VerifySolution(1e-7, True)`

I tested line by line and the solver finishes and returns the ABNORMAL status (4) and I figured out the kernel was actually dying when VerifySolution was called. I do not know why, but I did see that in [here ](https://github.com/google/or-tools/blob/stable/ortools/linear_solver/linear_solver.cc) that there are log functions from logging.h in the base folder. I see it is Google's glog logging package from C++. I also did some digging and found a list of where the log file is supposed to go. See [here](https://github.com/google/glog/blob/master/src/logging.cc). I cannot find it. I would like this output. Do you know where I can find the log file? 

For these particular models it seems since it is abnormal perhaps I should not be calling VerifySolution, but for places where info is getting logged, it would be great to look at the logging information for help debugging!

`#ifdef OS_WINDOWS
  // On windows we'll try to find a directory in this order:
  //   C:/Documents & Settings/whomever/TEMP (or whatever GetTempPath() is)
  //   C:/TMP/
  //   C:/TEMP/
  //   C:/WINDOWS/ or C:/WINNT/`

**What did you expect to see**
I expected the VerifySolution function to output what errors it encountered per its definition in linear_solver.cc. 

**What did you see instead?**
My kernel died.

**Anything else we should know about your project / environment**
I cannot share my model, sorry!

**Comment by lperron** [comment]
The C++ layer outputs the log to stderr.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by mlh621** [comment]
Ok, thanks for that. However, I had created my own logging class to capture both stdout and stderr. I know my logging works because on other models that are not infeasible I can go and see what I am printing out. When it runs into and issue with `VerifySolution` my log file is empty and nothing is printed out either. The kernel just dies.

`class Transcript(object):
    """ Save console output and errors.

        Once import, run sys.stdout = Logger() at start of code.
        At end of code, use stop() function.

        Inspired by a few answers combined here:
        https://stackoverflow.com/questions/14906764/how-to-redirect-stdout-to-both-file-and-console-with-scripting
    """
    def __init__(self, log_dir, f_name):
        self.log_dir = log_dir
        self.f_name = f_name
        self.terminal = sys.stdout
        self.error_message = sys.stderr

        # Set up log location if it doesn't exist
        if not os.path.isdir(self.log_dir):
            os.makedirs(self.log_dir)

        print("Log file:", self.log_dir+f_name+".log")
        self.log = open(self.log_dir+f_name+".log", "a")

    def write(self, message):
        """ Write the console and error messages to log file. """
        self.terminal.write(message)
        self.error_message.write(message)
        self.log.write(message)

    def flush(self):
        """ This flush method is needed for Python 3 compatibility.
            This handles the flush command by doing nothing.
            You might want to specify some extra behavior here.
        """

def stop():
    """Stop transcript and return print functionality to normal"""
    sys.stdout.log.close()
    sys.stdout = sys.stdout.terminal
    # sys.stderr = sys.stderr.error_message
`

I use this class to set up my logging file before setting up my model and calling solve. 

See the attached file for an example when the log file works. It is empty when the model has the issue. Github wouldn't let me upload an empty file.

And just to be sure to understand correctly. `VerifySolution` works when I have a model that is fine. It just doesn't log anything and doesn't work when I have what solver.Solve() returns something that is not optimal or feasible. 

**Why isn't VerifySolution outputting the errors? I can see where it is supposed to print in the C++ function.**
[working_log_file.log](https://github.com/google/or-tools/files/4225982/working_log_file.log)

**Comment by mlh621** [comment]
For some reason the code above is not displaying correctly. See the regular text vs. when the code starts. It goes together.

**Comment by mlh621** [comment]
I am running my code within a Jupyter notebook. I noted that the output from the solver, which is not printed within the notebook/console, is displaying within the Anaconda prompt that is opened and runs when running Jupyter locally. 

This is exactly the output I'd like to save, but which does not get saved when I use my logging class above to capture stderr and stdout. 

Anyone know how to capture this into a file?
![solver_output_in_anaconda_prompt](https://user-images.githubusercontent.com/42215983/75695549-dd2c1380-5c6f-11ea-95fb-9de589c05ee5.png)

**Comment by 1kastner** [comment]
@mlk621 have you made any progress there?

**Comment by 1kastner** [comment]
@Mizux @lperron first of all thanks for your time and patience and this great project you contribute to! Could you tell me if there are any plans to use Python exceptions instead of killing a kernel and relying on stderr? Would such a change be feasible in the near future? Then the error messages would be exactly where needed and the development experience would vastlly improve! I understand that such projects always have too limited resources for too many wishes. So thanks for uour efforts!
