### ISSUE TITLE
Is it possible to understand which contraints affect seriously the optimality of a solution?

### ISSUE THREAD

**Issue by aloumpas** [google/or-tools#1892]
Hi all,

I am using or tools 7.1 (c++) and experimenting with routing library and VRPs. I introduce to the problem all kind of constraints (time windows, capacity, time horizon etc.) and of course some of these constraints affect the optimality of the solution. Sometimes though, one or more constraints affect the optimality much more than the others and this is the point that I want to ask. Is it possible to know after or during the search, which constraints are responsible for serious negative impact on the solution?

P.S. I know about penalties and dropped nodes. I am not interested to drop nodes, my research concerns in to which constraints break down the solution score.

Thanks!

**Comment by lperron** [comment]
Please use the mailing list.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
