### ISSUE TITLE
How to set a constraint between robots for drilling a circuit board with multiple robots (Vehicle Routing)

### ISSUE THREAD

**Issue by balajil12** [google/or-tools#1893]
Hello,
i am trying or tools for drilling a circuit board with 4 robots (problem). All the robots will start the work at the same time. All robots positions are four corners of the board. after Drilling completes it needs to travel back to original position.

I have converted distance to time.

Objective is to find out the minimum travel time for each robot with minimum travel difference between all robots.

Robots named as TopLeft, TopRight, BottomL, BottomR.

Constraints:
1. Always minimum clearance should be maintained between robots. if its closer, one robot must wait or move away from other robot.
2. Each robot can cover 70% of the height and width from its position.
3. Eg. At any point Top left not allowed to travel beyond the TopRight.

I have used the  vehicle routing method with multiple start and end. And assigned a robot for each drill hole (based on its position).

`		RoutingIndexManager manager = new RoutingIndexManager(DrillCount, data.RobotNumber,data.StartPositions, data.StartPositions);

            RoutingModel model = new RoutingModel(manager);

            int transitCall = model.RegisterTransitCallback((long fromIndex, long toIndex) => {
                var fromNode = manager.IndexToNode(fromIndex);
                var toNode = manager.IndexToNode(toIndex);

                return data.DistanceMatrix[fromNode, toNode];
            });

            model.SetArcCostEvaluatorOfAllVehicles(transitCall);

            model.AddDimension(transitCall, 0, 9000, true, "TavelTime");
            RoutingDimension timeDimension = model.GetMutableDimension("TavelTime");
            timeDimension.SetGlobalSpanCostCoefficient(700);

            for (int i=0;i< drillPoints.Length; i++)
            {
                var index = manager.NodeToIndex(i);

                List<long> allowedRobots = new List<long>();
                allowedRobots.Add(-1);

                //Robots Allowed
                for(int k=0;k< robots.Count; k++)
                {
                    var distY = Math.Abs(robots[k].Y - drillPoints[i].Y);
                    var distX  = Math.Abs(robots[k].X - drillPoints[i].X);

                    if(distX< ModelConfig.ToolXMove && distY < ModelConfig.ToolYMove)
                    {
                        allowedRobots.Add(k);
                    }
                }

                model.VehicleVar(index).SetValues(allowedRobots.ToArray());
            }`

I need to apply first & third constrain.
My idea is 
1. Restrict two neighboring drill holes drilled by different robots when cumulated travel time is less than 5 seconds.

2. Store position index of each drill points. X position of each drill point at defined interval is less or more based on the robots.

it would be great if you can suggest the correct methods or alternative solution for this problem.

thanks

**Comment by lperron** [comment]
You cannot in a reasonable way.
You can try with the CP-SAT solver, using the circuit constraint.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 21 févr. 2020 à 13:43, balajil12 <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
And please use the mailing list for modeling questions.

**Comment by balajil12** [comment]
@lperron @Mizux   thanks a lot.
