### ISSUE TITLE
Fix time window in CVRPTW with Python

### ISSUE THREAD

**Issue by Khixinhxan** [google/or-tools#1894]
I want to apply time window (open time, close time) between previous day and next day each depot and stoppoint.
Example : open time 19:00 24-02-2020 , close time 4:00 25-02-2020, I convert range 48h, 
0->24h is 24-02,   24-48 is 25-02.
 Time window is converted, opentime = 19, closetime = 29.
But model don't run
"...SetRange return _pywrapcp.IntExpr_SetRange(self, l, u) Exception: CP Solver fail"

**Comment by lperron** [comment]
You should not use SetRange outside search.

**Comment by Mizux** [comment]
Did you try:
https://github.com/google/or-tools/blob/858fa626959f7e386153af82756384b79f983b5a/ortools/constraint_solver/samples/cvrptw.py#L190-L191

**Comment by Mizux** [comment]
When you create your dimension did you set the "horizon" to 48 ?
```python
horizon = 48
routing.AddDimension(
    time_evaluator_index,
    horizon,  # allow waiting time
    horizon,  # maximum time per vehicle
    False,  # don't force start cumul to zero since we are giving TW to start nodes
    "time")
```

**Comment by Khixinhxan** [comment]
> When you create your dimension did you set the "horizon" to at least 48 ?
> 
> ```python
> horizon = 48
> routing.AddDimension(
>     time_evaluator_index,
>     horizon,  # allow waiting time
>     horizon,  # maximum time per vehicle
>     False,  # don't force start cumul to zero since we are giving TW to start nodes
>     "time")
> ```
> 
> if your range is outside the horizon, it will fail (solver check `l <= horizon && u <= horizo

> When you create your dimension did you set the "horizon" to at least 48 ?
> 
> ```python
> horizon = 48
> routing.AddDimension(
>     time_evaluator_index,
>     horizon,  # allow waiting time
>     horizon,  # maximum time per vehicle
>     False,  # don't force start cumul to zero since we are giving TW to start nodes
>     "time")
> ```
> 
> if your range is outside the horizon, it will fail (solver check `l <= horizon && u <= horizon`)...

I set horizon is 48 and depot open timewindow = 21.5 and close timewindow = 43,
Stoppoint 1 :  open timewindow = 22 and close timewindown = 37
But model still fail.

**Comment by Mizux** [comment]
> I set horizon is 48 and depot open timewindow = 21.5 and close timewindow = 43,

You must use integer !

**Comment by Khixinhxan** [comment]
> > I set horizon is 48 and depot open timewindow = 21.5 and close timewindow = 43,
> 
> You must use integer !

I converted hour to seconds by 21.5*3600 and 43*3600
