### ISSUE TITLE
unexpected behaviour in routingindexmanager

### ISSUE THREAD

**Issue by mteixido** [google/or-tools#1895]
If I understand it correctly the `RoutingIndexManager` class is used in the routing library to properly map nodes to internal indices to keep track of the starting and ending points. However I see a very strange behaviour that I don't know if it is intentional or if it is a bug:

* If I consider a problem with 10 nodes, 2 vehicles and force them to start and end at 0 and 1 with `manager = pywrapcp.RoutingIndexManager(10, 2, [0,1], [0,1])` and I print the mapping with ` print(pd.DataFrame([{'idx': i, 'nidx': manager.IndexToNode(i)} for i in range(manager.GetNumberOfIndices())]))` I get the table:
```
    idx  nidx
0     0     0
1     1     1
2     2     2
3     3     3
4     4     4
5     5     5
6     6     6
7     7     7
8     8     8
9     9     9
10   10     0
11   11     1
```
If I use `NodeToIndex(0)` it returns 0 although it is ambiguous (indexes 0 and 10 are both mapped to node 0)

However if I do the same with different end nodes using: `pywrapcp.RoutingIndexManager(10, 2, [0,1], [3,4])` I get the mapping
```
   idx  nidx
0    0     0
1    1     1
2    2     2
3    3     5
4    4     6
5    5     7
6    6     8
7    7     9
8    8     3
9    9     4
```
but in this case `manager.NodeToIndex(3)` returns -1 although node 3 is uniquely mapped to index 8. Is this behaviour the correct one? I was expecting to return 8.

The full code used to test this issue is:

```python
from ortools.constraint_solver import pywrapcp
import pandas as pd

manager = pywrapcp.RoutingIndexManager(10, 2, [0,1], [0,1])
print(pd.DataFrame([{'idx': i, 'nidx': manager.IndexToNode(i)} for i in range(manager.GetNumberOfIndices())]))
print("index associated to node 0 -> {} ".format(manager.NodeToIndex(0)))  # returns 0 although it seems ambiguous

manager = pywrapcp.RoutingIndexManager(10, 2, [0,1], [3,4])
print(pd.DataFrame([{'idx': i, 'nidx': manager.IndexToNode(i)} for i in range(manager.GetNumberOfIndices())]))
print("index associated to node 3 -> {} ".format(manager.NodeToIndex(3)))  # returns -1 but I don't know why
```

**Comment by Mizux** [comment]
You need to use `Start()` and `End()` methods when using indices related to start/end node...

**Comment by mteixido** [comment]
Thanks Mizux, do you mean the  Start and End methods of the routing class? because I don't see that `RoutingIndexManager` has them (at least exposed in python).

**Comment by Mizux** [comment]
yes, since v7.5 IIRC we should map:
https://github.com/google/or-tools/blob/858fa626959f7e386153af82756384b79f983b5a/ortools/constraint_solver/routing_index_manager.h#L63-L64

**Comment by Mizux** [comment]
Update, IMHO code should not define mapping for start/end node but mapping is generated using:
https://github.com/google/or-tools/blob/858fa626959f7e386153af82756384b79f983b5a/ortools/constraint_solver/routing_index_manager.cc#L81-L86
