### ISSUE TITLE
Fix error result in CVRPTW with Python

### ISSUE THREAD

**Issue by Khixinhxan** [google/or-tools#1896]
I had a problem running CVRPTW, the result seemed to be not realistic, plan out was wrong the whole schedule, I felt that I was short of time from the depot point to the first warehouse.
```

  dropped = []
    for order in range(routing.Size()):

        if (plan.Value(routing.NextVar(order)) == order):
            dropped.append(str(order))

    capacity_dimension = routing.GetDimensionOrDie('Capacity')
    time_dimension = routing.GetDimensionOrDie('Time')

    plan_output = ''
    total_vehicle_not_use = 0
    for route_number in range(routing.vehicles()):

        order = routing.Start(route_number)
        plan_output += 'Route {0}:'.format(route_number)
        if routing.IsEnd(plan.Value(routing.NextVar(order))):
            plan_output += ' Empty \n'
            total_vehicle_not_use = total_vehicle_not_use + 1
        else:
            while True:

                load_var = capacity_dimension.CumulVar(order)
                time_var = time_dimension.CumulVar(order)
                node = manager.IndexToNode(order)
                # L: Load
                # T: Time
                plan_output += \
                    'Stoppoint:{node} Load:({load}) Timewindow({tmin}, {tmax}) -> '.format(
                        node=node,
                        load=plan.Value(load_var),
                        tmin=str(timedelta(seconds=plan.Min(time_var))),
                        tmax=str(timedelta(seconds=plan.Max(time_var))))

                if routing.IsEnd(order):
                    plan_output += ' End {0}.'.format(route_number)
                    break
                order = plan.Value(routing.NextVar(order))
        plan_output += '\n'

    return (plan_output, dropped, `total_vehicle_not_use)`

```
Route 7:Stoppoint:0 Load:(0) Timewindow(0:00:00, 0:00:00) -> Stoppoint:5 Load:(0) Timewindow(18:00:00, 18:00:00) -> Stoppoint:6 Load:(890) Timewindow(19:18:53, 19:18:53) -> Stoppoint:18 Load:(1154) Timewindow(20:28:32, 20:28:32) -> Stoppoint:15 Load:(1377) Timewindow(22:01:39, 22:01:39) -> Stoppoint:16 Load:(2874) Timewindow(23:13:06, 23:13:06) -> Stoppoint:22 Load:(3227) Timewindow(1 day, 1:02:11, 1 day, 1:02:11) -> Stoppoint:0 Load:(3550) Timewindow(1 day, 4:28:52, 1 day, 4:28:52) -> End 7.

As far as I know from depot point 0 to point number 5, it takes 3:00 hours. Please tell me the cause

**Comment by lperron** [comment]
Please ask on the mailing list.

**Comment by Khixinhxan** [comment]
How to  ask on the mailing list :(

**Comment by lperron** [comment]
It was on the page to create the issue,
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
