### ISSUE TITLE
Python CP solver Intvar.SetValues() changes search strategy

### ISSUE THREAD

**Issue by JKBehrens** [google/or-tools#1897]
**What version of OR-tools and what language are you using?**
Version: v7.3.7083 installed via pip (python 2.7)
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP Solver

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 16.04

**What did you do?**

Run the following script:
```python
from __future__ import print_function
import sys
from ortools.constraint_solver import pywrapcp

def main():
  solver = pywrapcp.Solver("simple_example")
  solver.ReSeed(27)
  # Create the variables.
  x = solver.IntVar(0, 30, "x")  # type: pywrapcp.IntVar
  y = solver.IntVar(0, 30, "y")# type: pywrapcp.IntVar
  z = solver.IntVar(0, 30, "z")# type: pywrapcp.IntVar
  x.SetValues([4,13])
  y.SetValues([4,13])
  z.SetValues([4,13])
  # Call the solver.
  db = solver.Phase([x, y, z], solver.CHOOSE_FIRST_UNBOUND, solver.ASSIGN_RANDOM_VALUE)
  solver.Solve(db)
  print_solution(solver, x, y, z)
def print_solution(solver, x, y, z):
  count = 0

  while solver.NextSolution():
    count += 1
    print("x =", x.Value(), "y =", y.Value(), "z =", z.Value())
  print("\nNumber of solutions found:", count)

if __name__ == "__main__":
  main()
```

**What did you expect to see**
random order of solution as a result of `db = solver.Phase([x, y, z], solver.CHOOSE_FIRST_UNBOUND, solver.ASSIGN_RANDOM_VALUE)`

**What did you see instead?**
For any seed I tried, I got the following output. 

```
x = 4 y = 4 z = 4
x = 4 y = 4 z = 13
x = 4 y = 13 z = 4
x = 4 y = 13 z = 13
x = 13 y = 4 z = 4
x = 13 y = 4 z = 13
x = 13 y = 13 z = 4
x = 13 y = 13 z = 13
```

Number of solutions found: 8

When I run the script without the 
`  x.SetValues([4,13])
  y.SetValues([4,13])
  z.SetValues([4,13])`
commands, I observe the desired random behavior. In the context of optimization with restarts, this issue leads to finding (and subsequently rejecting) always the same partial solution.

Thanks for looking into this!
Jan

**Comment by lperron** [comment]
My hypothesis is that random works kind of OK, except it never chooses the max value. Which is unfortunate with normal domains, but catastrophic with domains of size 2 :-)
