### ISSUE TITLE
MiniZinc model: Satifiable with Gecode & Chuffed, unsatisfiable with OR-tools

### ISSUE THREAD

**Issue by LuddeWessen** [google/or-tools#1899]
I run my project using:
minizinc --solver Chuffed -f -v model.mzn data1.dzn data2.dzn --output-time -a
and
minizinc -v model.mzn data1.dzn data2.dzn --output-time -a
Both results in multiple solutions.

However, when running OR-tools, using:
minizinc --solver OR-tools-cpsat -f -v model.mzn data1.dzn data2.dzn --output-time -a
it instantly reports unsatisfiable.

**Comment by LuddeWessen** [comment]
I realize that I haven't provided any info regarding the model, making it impossible to reproduce the error. However, I have hunted down this error for hours, and just need to know if there is something obvious that I am missing.

**Comment by lperron** [comment]
which problem? which version of or-tools ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by LuddeWessen** [comment]
It is MiniZinc v2.4.2 and Google OR-tools v7.5.7466.
Unfortunately, since the bug is so unpredictable I have not managed to replicate the error in a small example.

1) As an example, showing a variable in output sometimes causes unsat, while omitting the variable in the output makes the model satisfiable.
2) Another example - setting some variables to a value gives unsat, even if the variables are assigned to those specific values during optimization without any problem.
3) Adding a variable x with domain 0..10, and posting x < 1 is ok, unless i show the variable in output. if we instead post x < 2 all is well, even if I show the variable in output.

Are there known issues that could cause above behaviour?

**Comment by lperron** [comment]
We have fixed unsat issues on master. But we need a model to verify if your
problem is solved.

**Comment by lperron** [comment]
I will close this issue. If you can send us a model, please do.
