### ISSUE TITLE
Depot with capacity and time windows

### ISSUE THREAD

**Issue by thanh-nguyen-dang** [google/or-tools#1900]
**What language and solver does this apply to?**
All

**Describe the problem you are trying to solve.**
We have the problem with a depot which has capacity (let's say 5 loading dock which work 
independently/asynchronously). However, each loading dock has different available time windows.

With this example
https://developers.google.com/optimization/routing/cvrptw_resources
Currently, I can define the capacity for depot (number of loading docks). Can we add the new feature allowing to add the time windows for different docks?

Note that, we cannot use multiple fake nodes to represent the docks, since we don't know where each request (pickup package) is.

**Comment by lperron** [comment]
As stated here: https://github.com/google/or-tools/issues/new/choose

modeling questions should be asked on the mailing list.

Thanks
