### ISSUE TITLE
Fatal error: check failed: image >= 0 (-1 vs. 0) 

### ISSUE THREAD

**Issue by proshkin** [google/or-tools#1901]
Version: master
Language: Python

CP-SAT
Windows

Attached model cause the following error:
Check failed: image >= 0 (-1 vs. 0) 
*** Check failure stack trace: ***
    @   00007FFBB443A72B  public: void __cdecl google::LogMessage::Flush(void) __ptr64
    @   00007FFBB4438979  public: __cdecl google::LogMessageFatal::~LogMessageFatal(void) __ptr64
    @   00007FFBB46D7495  public: bool __cdecl std::_Deque_unchecked_const_iterator<class std::_Deque_val<struct std::_Deque_simple_types<int> > >::operator<(class std::_Deque_unchecked_const_iterator<class std::_Deque_val<struct std::_Deque_simple_types<int> > > const & __ptr64)
    @   00007FFBB456BFAC  void __cdecl operations_research::sat::ApplyToAllVariableIndices(class std::function<void __cdecl(int * __ptr64)> const & __ptr64,class operations_research::sat::ConstraintProto * __ptr64)
    @   00007FFBB46D7A8F  void __cdecl operations_research::sat::ApplyVariableMapping(class std::vector<int,class std::allocator<int> > const & __ptr64,class operations_research::sat::PresolveContext const & __ptr64)
    @   00007FFBB46DEF03  public: bool __cdecl operations_research::sat::CpModelPresolver::Presolve(void) __ptr64
    @   00007FFBB46E34D4  bool __cdecl operations_research::sat::PresolveCpModel(struct operations_research::sat::PresolveOptions const & __ptr64,class operations_research::sat::PresolveContext * __ptr64,class std::vector<int,class std::allocator<int> > * __ptr64)
    @   00007FFBB44CE6D0  public: __int64 __cdecl <lambda_7a69e8a962ef0af9ebc734e68403651f>::operator()(class operations_research::sat::Model const & __ptr64)const __ptr64
    @   00007FFBB4640019  void __cdecl operations_research::sat::SequentialLoop(class std::vector<class std::unique_ptr<class operations_research::sat::SubSolver,struct std::default_delete<class operations_research::sat::SubSolver> >,class std::allocator<class std::unique_ptr<cla
    @   00007FFBB4833E91  void __cdecl operations_research::RunWorker(void * __ptr64)
    @   00007FFBB4832C9F  private: static unsigned int __cdecl std::thread::_Invoke<class std::tuple<void (__cdecl*)(void * __ptr64),class operations_research::ThreadPool * __ptr64>,0,1>(void * __ptr64)
    @   00007FFC0D730E72  _beginthreadex
    @   00007FFC0F4B7BD4  BaseThreadInitThunk
    @   00007FFC1076CED1  RtlUserThreadStart
[model_cf.txt](https://github.com/google/or-tools/files/4264349/model_cf.txt)

**Comment by lperron** [comment]
Indeed.  Thanks for the report. We will investigate.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Thanks. It should be fixed on master now.
