### ISSUE TITLE
C++ solver output not storing into logging file when running from python

### ISSUE THREAD

**Issue by mlh621** [google/or-tools#1903]
This question is related to [this issue](https://github.com/google/or-tools/issues/1889), which was closed before being fully resolved. Please note some further comments there after it was closed about how I am capturing stderr and stdout to a file. It is not printing the C++ output from the solver there, only what I'm printing from within python.

I am running my code within a Jupyter notebook and I noticed that the output from the solver, which is not printed within the notebook/console, is displaying within the Anaconda prompt that is opened and runs when running Jupyter locally. See the attached picture.

What is shown in the output in the prompt below is exactly what I'd like to save, so I can capture potential errors from LOG_IF, but which is _not_ getting saved when I use my logging class, as seen in issue 1889 (link above) to capture stderr and stdout.

Anyone know how to capture this output? It originates from C++, but I'm using python to code with ortools.
![solver_output_in_anaconda_prompt](https://user-images.githubusercontent.com/42215983/75696061-92f76200-5c70-11ea-8678-67c826d0cfd5.png)
into a file?

**Comment by mlh621** [comment]
For reference, I'm copying my comment from the other issue here to more easily track.

Below is what I'm using to capture stdout and stderr. It captures everything I created to print from python. It doesn't capture any of the C++ output.

I know my logging works because with models that are not infeasible I can go and see what I am printing out. When it runs into and issue with `VerifySolution` my log file is empty and nothing is printed out either. The kernel just dies. I'd like to be able to dig into what is getting printed out by the C++ error-catching type functions I see within the ortools C++ code base.

```python
class Transcript(object):
    """ Save console output and errors.

        Once import, run sys.stdout = Logger() at start of code.
        At end of code, use stop() function.

        Inspired by a few answers combined here:
        https://stackoverflow.com/questions/14906764/how-to-redirect-stdout-to-both-file-and-console-with-scripting
    """
    def __init__(self, log_dir, f_name):
        self.log_dir = log_dir
        self.f_name = f_name
        self.terminal = sys.stdout
        self.error_message = sys.stderr

        # Set up log location if it doesn't exist
        if not os.path.isdir(self.log_dir):
            os.makedirs(self.log_dir)

        print("Log file:", self.log_dir+f_name+".log")
        self.log = open(self.log_dir+f_name+".log", "a")

    def write(self, message):
        """ Write the console and error messages to log file. """
        self.terminal.write(message)
        self.error_message.write(message)
        self.log.write(message)

    def flush(self):
        """ This flush method is needed for Python 3 compatibility.
            This handles the flush command by doing nothing.
            You might want to specify some extra behavior here.
        """

def stop():
    """Stop transcript and return print functionality to normal"""
    sys.stdout.log.close()
    sys.stdout = sys.stdout.terminal
    # sys.stderr = sys.stderr.error_message
```

I use this class to set up my logging file before setting up my model and calling solve. 

See the attached file for an example when the log file works. It is empty when the model has the issue. Github wouldn't let me upload an empty file.

And just to be sure to understand correctly. `VerifySolution` works when I have a model that is fine. It just doesn't log anything and doesn't work when I have what solver.Solve() returns something that is not optimal or feasible. 

**Why isn't VerifySolution outputting the errors? I can see where it is supposed to print in the C++ function.**
[working_log_file.log](https://github.com/google/or-tools/files/4225982/working_log_file.log)

**Comment by Mizux** [comment]
This is a jupyter issue not related to this project
see https://stackoverflow.com/questions/34145950/is-there-a-way-to-redirect-stderr-to-file-in-jupyter

**Comment by mlh621** [comment]
I ran the same code within a Python terminal. Just submitted via `python my_file_name.py` and it still does not save the output from the solver. This would be useful information to analyze/extract some information about the branching tree from. It seems a python/C++ interface issue, unless I'm misunderstanding something. As I said above, I am using that class to capture and output `stdout` and `stderr`. Shouldn't the "Primal, optimal, etc." info be stored there if I'm saving that?

**Comment by 1kastner** [comment]
https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Running%20Code.html#sys.stdout-and-sys.stderr shows that stderr is usualy printed to the cell, not the terminal in the background. But there it ends up for me as well. The stackoverflow article is from 2015, might it be outdated?

**Comment by tias** [comment]
I'd like to re-open this @Mizux 

The solver (in my case: cp-sat 9.0) is logging directly to 'stdout' (in a subprocess?) and not to pythons "sys.stdout". So none of `contextlib.redirect_stdout()` or similar works.

Ideally, in or-tools' Python API, it would capture the stdout that the underlying solver is producing, and then print that in Python.

Here is a small example:

```python
from ortools.sat.python import cp_model

def SearchForAllSolutionsSampleSat():
    """Showcases calling the solver to search for all solutions."""
    # Creates the model.
    model = cp_model.CpModel()

    # Creates the variables.
    num_vals = 3
    x = model.NewIntVar(0, num_vals - 1, 'x')
    y = model.NewIntVar(0, num_vals - 1, 'y')
    z = model.NewIntVar(0, num_vals - 1, 'z')

    # Create the constraints.
    model.Add(x != y)

    # Create a solver and solve.
    solver = cp_model.CpSolver()
    
    solver.parameters.log_search_progress=True # logs to raw stdout, not sys.stdout
    
    solution_printer = cp_model.VarArraySolutionPrinter([x, y, z])
    status = solver.SearchForAllSolutions(model, solution_printer)

    print('Status = %s' % solver.StatusName(status))
    print('Number of solutions found: %i' % solution_printer.solution_count())


SearchForAllSolutionsSampleSat()
```

When running this from Jupyter, it does not show the search log in the cell, it does show it in the terminal in which I launched jupyter.

Ideally, the python API would redirect the stdout output such that it appears in the cell.

Thanks

**Comment by tias** [comment]
Update: I saw an undocument 'log_callback' attribute popping up in the Python API of Solver() (already in 9.0)

it took some playing around to find out how to handle it, but it is the solution to the output redirecting problem!

Add to the above to make the output capturing work as expected:
`solver.log_callback = lambda x: print(x)`


My recommendation would be for or-tools python API to always set that as log callback...
or perhaps when in IPython or if it detects that sys.stdout is changed or so...

**Comment by Mizux** [comment]
IIRC CP-SAT solver logging do support a callback since v9.0 but it is still experimental AFAIK
