### ISSUE TITLE
MILP solver executed indefinitely and gives multiple optimal solutions

### ISSUE THREAD

**Issue by rampallishyam** [google/or-tools#1904]
**What version of OR-tools and what language are you using?**
Version: v7.2
Language:Python

Which solver are you using  Routing Solver

What operating system (Windows 10) and version?

**What did you do?**

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by Mizux** [comment]
what is the problem ?
do you want to set a time limit on the search ?
did you use the GLS ?

**Comment by rampallishyam** [comment]
**what is the problem ?**
Problem: First-mile transportation problem which is same a capacitated vehicle routing problem with multiple depots but each vehicle has depot as origin and A common hub as destination.

**do you want to set a time limit on the search ?**
To be honest the time limit is something that I have not tried. But even if we try the time limit, the solution is infeasible while solver identifies is as a feasible solution.

**did you use the GLS ?**
I do not know the what it means. But what I have tried is that, I have used pywraplp module within python where I have developed the code in python.

**Since routing is NP-Hard solver may need to barely explore all solutions to prove optimality thus an "indefinitely" execution.**

Sure, I will keep this in mind. But I  do not understand why the solver generates in feasible solutions and calls them optimal and also executes indefinitely.

Thanks a lot for helping me with the issue. Very grateful!

**Comment by Mizux** [comment]
Please use the mailing list instead.
You should also try to explain why solution is unfeasible and if possible a way/minimal sample to reproduce your error...
