### ISSUE TITLE
Implement AddMultiplicationEquality for arrays of length > 2

### ISSUE THREAD

**Issue by tobycheese** [google/or-tools#1905]
**What language and solver does this apply to?**
Python, or probably all

**Describe the problem you are trying to solve.**
With cp-sat, `model.AddMultiplicationEquality()` only works with arrays/lists of length 2. Longer arrays crash when solving.

**Describe alternatives you've considered**
The workaround is to split into sub-products, define new variables for those and add the constraint with two variables at most. Which is rather cryptic and needs additional variables.

**Comment by Mizux** [comment]
FYI this is a custom python code, not sure other languages are impacted:
https://github.com/google/or-tools/blob/234d5f19fcf068237a012d3bebadda836c2dd8f8/ortools/sat/python/cp_model.py#L1240-L1247

**Comment by stradivari96** [comment]
related: https://stackoverflow.com/questions/57661398/why-is-the-addmultiplicationequality-limited-to-only-2-variables

**Comment by Mizux** [comment]
Close since it won't be supported for the foreseeable future.

Please take a look at the SO for an efficient workaround...

**Comment by tobycheese** [comment]
Huh, that was quick :-) Thanks for considering, though.
