### ISSUE TITLE
Exponential value in model

### ISSUE THREAD

**Issue by sergioterzella** [google/or-tools#1906]
Good afternoon,

In my model I define the number of agents and the best entry intervals per interval, given the need to manpower.

I minimize the sum of the absolute value of the difference between the number of agents allocated and needed per entry, the calculation is being done correctly.

However, it is necessary to include a parameter that validates if the daily weighted average of the wait_probability indicator is greater than or equal to a fixed value, for example 90%.

I created a model.NewIntVar (servers) that will receive the sum of the number of agents from all shifts for a specific interval to use in the function below.

The variable:

sum_server[e] = model.NewIntVar(-1000,1000,"sum_server {}".format(e))
sum_server[e] = sum([x[i,c] for c in range(len(list_carga_horaria)) for i in range(e+1) if (e-i) < list_carga_horaria[c]])

The type:
type(sum_server[e]) = <class 'ortools.sat.python.cp_model._SumArray'>

Calculation of the indicator (Erlang C):

def wait_probability(traffic, servers):

    L = (traffic**servers / factorial(servers)) * (servers / (servers - traffic))
    sum_ = 0
    for i in range(servers):
        sum_ += (traffic**i) / factorial(i)
    return (L / (sum_ + L))

When I run the model I get the error below:
TypeError: unsupported operand type(s) for ** or pow(): 'float' and '_SumArray'
Exactly on "traffic**servers"

I saw in another post that ortools does not work with exponents, we already have some way out, do any have any ideas?

Att,

Sergio Terzella

**Comment by lperron** [comment]
Precompute everything and use an element constraint.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 3 mars 2020 à 22:31, sergioterzella <notifications@github.com> a
écrit :
