### ISSUE TITLE
CVRPPAD problem with delivery, pickup have demand delivery do not match vehicle capactity

### ISSUE THREAD

**Issue by Khixinhxan** [google/or-tools#1907]
What version of OR-tools and what language are you using?
Version: v7.2
Language: Python

I am having some problems in the CVRPPAD problem. Vehicles departing with all the goods to be delivered (delivery), on the delivery points, can always take action (pickup) and return to the starting point. 

I created the data by doubling the C position, forming C 'with C (positive demand +20, delivery), C' (negative demand -20, pickup). 

The model was still working, but the result was not what I expected, the total delivery of the entire route exceeded the vehicle's capacity.

For example A (depot) -> B (delivery) -> C (delivery) -> C ' (pickup) -> D (delivery) -> A (depot).
Capacity of vehicle is 50, at B need delivery 20, at C need delivery 20, at C ' need pickup 15 and at D need delivery 20.  (20 + 20 -15 +20 = 45 meet the conditions 50)
Something's wrong, the starting vehicle capacity must be 60 !!!

Do you have any suggestions? Thank very much.

**Comment by Mizux** [comment]
You should use the mailing list instead.

You problem here is the pickup quantity is used to make the next delivery...

IMHO you should create 2 dimensions, one for deliveries and one for pickup, then add constraint that the sum of both CumulVar at any location can't exceed the vehicle capacity...

**Comment by Khixinhxan** [comment]
> You should use the mailing list instead.
> 
> You problem here is the pickup quantity is used to make the next delivery...
> 
> IMHO you should create 2 dimensions, one for deliveries and one for pickup, then add constraint that the sum of both CumulVar at any location can't exceed the vehicle capacity...

For this example:
Vehicle starting with 60 demand
1. at B, delivery 20, vehicle capacity still 40
2. at C, delivery 20, vehicle capacity still 20
3. at C', pickup 15, vehicle capacity add 15 => 35
4. at D, delivery 20, vehicle capacity still 15
5. at depot A, vehicle capacity have 15

**Comment by Khixinhxan** [comment]
The purpose of delivery is to maximize the capacity of the vehicle, with the shortest distance, optimize the least cars.I further enhance the delivery and pick up, delivery from the depot goes to the point of need, and the goods from the depot must also go to the depot.
