### ISSUE TITLE
[Windows, CP-SAT, Python] 

### ISSUE THREAD

**Issue by DominikRoB** [google/or-tools#1909]
**What version of OR-tools and what language are you using?**
Version: master
Language: Python

**Which solver are you using**
CP-SAT

**What operating system and version?**
Microsoft Windows 10 Education 64bit

**What did you do?**
I attached the relevant models and a script to reproduce the error.

I build the master branch from source using visual studio 19 and make to test the fix for #1882 
I still get the "Process finished with exit code -1073741819 (0xC0000005)" 

About my model:
I have optimization problem with 2 objectives -
The first objective is makespan (equal to maximum of several variables)  (Model1Proto)
the second objective is completion time (equal to sum of a different set of several variables) (Model2Proto)
Model2Proto uses the optimized makespan of Model1Proto as a constraint, and takes the other resulting variables as hints.

Model1Proto runs without issues, but maybe it is useful for reference.
Model2Proto crashes when solved multiple times.

[crashingmodel.zip](https://github.com/google/or-tools/files/4288451/crashingmodel.zip)

**Comment by lperron** [comment]
Works flawlessly on linux. Still investigating.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
I believe this is fixed.

Thanks for the report.
