### ISSUE TITLE
CVRP Dynamic Distance Callback / No U-Turn Problem

### ISSUE THREAD

**Issue by nicholasrpb** [google/or-tools#1912]
Background: I have a limitation such that the road used is not possible of u-turn. Hence, everytime the algorithm calculate shortest distance between point k to point k+1, it should check if it visiting point k-1 or not, if it visiting then it should find a junction in-front in which vehicle able to do u-turn then calculate and return the distance between the junction and point k+1, otherwise it should just calculate and return the shortest distance between point k to point k+1.

Currently, in the example, the shortest distance between 2 points are rigidly defined in a list:
> def distance_callback(from_index, to_index):
>             """Returns the distance between the two nodes."""
>             # Convert from routing variable Index to distance matrix NodeIndex.
>             from_node = manager.IndexToNode(from_index)
>             to_node = manager.IndexToNode(to_index)
>             return data['distance_matrix'][from_node][to_node]

How is it possible to solve / approach my problem in the routing? Any help / suggestion is greatly appreciated

**Comment by lperron** [comment]
Please use the mailing list.
