### ISSUE TITLE
Orders Delivery 

### ISSUE THREAD

**Issue by alexandchun** [google/or-tools#1913]
HI,

We're struggling with some aspects of the following problem:
a bunch of drivers require to assign to deliver orders consist of fixed start and end times.
After going through most of the examples, I came across bus_driver_scheduling_sat.py fit in most of our requirements such as:

- There only fix number of drivers to assign with orders.
- The orders suppose to assign to drivers shall not be overlap.
- Each order is covered by only 1 driver.
- There may be number of orders available greater than number of drivers or vice versus.

The code embedded is running smoothly without any major issue except when there insufficient drivers to assign all the orders which return no solution.

Is there a feasible solution to return partial result
[fleet_CP_txt.txt](https://github.com/google/or-tools/files/4304298/fleet_CP_txt.txt)

 such as certain orders which cant be assign to be omitted?

I'm using ortools 7.4 and python 3.7

Thanks in advance!

**Comment by Mizux** [comment]
For modeling question, please use the Mailing List instead...
