### ISSUE TITLE
PDP pairs with end stops

### ISSUE THREAD

**Issue by TeodoraB21** [google/or-tools#1914]
**What language and solver does this apply to?**
All, Python, Java, C#, C++ / CP-SAT, Routing, Linear Solver
C++
**Describe the problem you are trying to solve.**
A PDP where the pairs can contain end stops.
ex:
10 stops
2 vehicles
start stops: 0 1
end stops: 5 6
pickup-delivery pairs: [4 5] [7 9]
**Describe the solution you'd like**
One possible solution:
0->3->4->8->5
1->7->2->9->6
**Describe alternatives you've considered**
I tried to duplicate the end stop that is used in the end stops and in the pairs and I set the distance between the duplicated stop and the actual stop to be 0, but the algorithm doesn't put them right after each other.
**Additional context**
From what I saw, the error comes from CompressPath method in connectivity.h. If I changed the method as below, the problem works, but I don't know if the modification is right.
```
  // Compresses the path for node.
  NodeIndex CompressPath(NodeIndex node) {
    CheckNodeBounds(node);
    NodeIndex parent = node;
    while (parent != class_[parent])
	{
		if (parent != class_.size())
		{
			CheckNodeBounds(class_[parent]);
			CheckNodeBounds(class_[class_[parent]]);
			parent = class_[parent];
		}
		else
		{
			parent = class_[0];
			node = class_[0];
		}
    }
    while (node != class_[node]) {
      const NodeIndex old_parent = class_[node];
      class_[node] = parent;
      node = old_parent;
    }
    return parent;
  }
```

**Comment by Mizux** [comment]
Please use the mailing list instead:

1) Yes you must duplicate the node since you can't use an end index as part of a P&D pair

2) You can try to add a constraint on `NextVar()`, C++ like pseudo-code
```cpp
int64 delivery_idx = manager.NodeToIndex(delivery);
int64 end_idx = routing.End(vehicle_idx);
auto active = routing.ActiveVar(delivery_idx) * routing.ActiveVar(end_idx);
solver.AddConstraint(active * routing.NextVar(delivery_idx)  == active * end_idx);
```
ref: https://github.com/google/or-tools/blob/08769b2d9e973b3b6df7883caf0c8b10d47e513e/ortools/constraint_solver/routing.h#L1180-L1184
