### ISSUE TITLE
[HELP] Ensuring first two orders are deliveries? 

### ISSUE THREAD

**Issue by Learner-byte** [google/or-tools#1916]
Hello,

I am modeling a [cvrp](https://developers.google.com/optimization/routing/cvrp) and setting the capacity of the vehicles to the number of deliveries and incrementing the capacity for every pickup and decrementing the capacity for every delivery. I start off with fully loaded trucks. This ensures that my first order will be a delivery. But my requirement is to have first two orders as deliveries and following that the orders can be pickup or delivery. 

Or How to ensure that certain orders don't lie in the first x number of stops? 

Any help?

**Comment by lperron** [comment]
please use the mailing list
