### ISSUE TITLE
MakeBoolVar with long variable name causes solver to crash

### ISSUE THREAD

**Issue by atleri** [google/or-tools#1917]
**What version of OR-tools and what language are you using?**
Version: OR_TOOLS_MAJOR=7
OR_TOOLS_MINOR=5
#PRE_RELEASE=YES
Language: C#

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**:
"CBC_MIXED_INTEGER_PROGRAMMING"

**What operating system (Linux, Windows, ...) and version?**
Windows

**What did you do?**
1. Add variable with long name (not sure of the actual length limit that will trigger this).
2. ...other stuff
3. Run solver
4. Solver crashes without any sensible error message.

**What did you expect to see**
I expected an error message when the variable name is too long. Also, a documentation about max name length would be natural?

**What did you see instead?**
Crash, no info.

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
Most likely a 'feature' of CBC. 
I did not find a specification for names in MPS files or solver. Maybe it is the length, maybe there are some forbidden characters.

Anyway, this is most likely a CBC problem.

**Comment by atleri** [comment]
Hi, OK, thanks. No forbidden characters I think, so yes, the length.

Cheers,
-atle
