### ISSUE TITLE
CBC solver regression: the exact same model solved on 7.0.6546 is proven infeasible in 7.5.7466 

### ISSUE THREAD

**Issue by ihadanny** [google/or-tools#1919]
**What version of OR-tools and what language are you using?**
Version: 7.5.7466
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CBC_MIXED_INTEGER_PROGRAMMING

**What operating system (Linux, Windows, ...) and version?**
mac, Darwin Kernel Version 18.7.0

**What did you do?**

I'm creating and solving a model with 7.0.6546. 
I reach a solution after several seconds `best objective 4110.8937 (best possible 3724.4987)`. 
I saved it as MPS format (attached).
I then upgrade my version to 7.5.7466.
I execute the exact same code and model and get `Result - Problem proven infeasible`.

**What did you expect to see**
the same

[bad_7.5.7466.mps.txt](https://github.com/google/or-tools/files/4322654/bad_7.5.7466.mps.txt)
[good_7.0.6546.mps.txt](https://github.com/google/or-tools/files/4322657/good_7.0.6546.mps.txt)

**Comment by lperron** [comment]
Are you sure it was feasible in the first place ?
Can you reproduce using the cbc binaries ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 12 mars 2020 à 07:41, Ido Hadanny <notifications@github.com> a
écrit :

**Comment by ihadanny** [comment]
what do you mean by  

> reproduce with the CBC binaries?

is there some command line I can use to read and solve a MPS file?
because my application pre-processing is pretty complex and it's currently not-separable from the modeling API calls.

**Comment by lperron** [comment]
https://bintray.com/coin-or/download/Cbc/#files
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 12 mars 2020 à 09:21, Ido Hadanny <notifications@github.com> a
écrit :

**Comment by ihadanny** [comment]
using the cbc command line I was able to solve both the bad file (produced by 7.5) and the good file (produced by 7.0)

**Comment by Mizux** [comment]
which version of cbc did you use ?
they currently have a regression with the last stable version IIRC

**Comment by Mizux** [comment]
https://github.com/coin-or/Cbc/issues/286

**Comment by ihadanny** [comment]
very strange. I downloaded 7.5 from [https://github.com/google/or-tools/releases/download/v7.5/or-tools_MacOsX-10.15.2_v7.5.7466.tar.gz](url), and executed:
`make build SOURCE=examples/cpp/solve.cc
bin/solve --solver cbc --input /var/folders/d3/56thtyr57277cmw8fbs37cc9mcmv_3/T/tmpo2pwc2r8/bad_7.5.7466.mps --time_limit_ms 5000`

and got:

`
Status      : MPSOLVER_FEASIBLE
Objective   : 4.848683892999999e+03
BestBound   : 3.724498655000000e+03
`

**Comment by ihadanny** [comment]
so it works from the C++ API.
Is there some way I can do the same from the python API?

**Comment by cloudmu** [comment]
> 
> 
> which version of cbc did you use ?
> they currently have a regression with the last stable version IIRC
> EDIT: see: [coin-or/Cbc#286](https://github.com/coin-or/Cbc/issues/286)
> And we bump it in v7.1 https://github.com/google/or-tools/releases/tag/v7.1

If the root cause is the CBC regression, this issue would affect not only Python, but also or-tools API in other languages (Java and C#).

**Comment by cloudmu** [comment]
@Mizux is this bug resolved?  Thanks.
