### ISSUE TITLE
Python Setup Errors

### ISSUE THREAD

**Issue by sagar81** [google/or-tools#192]
I am trying to install ortools python and seeing the following issues.
System Info: Mac OSX 10.11.3 EI Capitan

I tried the following two eggs
ortools-2.3393-py2.7-macosx-10.11-intel.egg
ortools-3.3574-py2.7-macosx-10.11-intel.egg

I used sudo easy_install <egg_file_name>
Both the eggs showed error on following import
from ortools.constraint_solver import routing_enums_pb2

Also the second egg (3.3574) gives following error when running cvrptw.py
Traceback (most recent call last):
  File "cvrptw.py", line 737, in <module>
    main()
  File "cvrptw.py", line 628, in main
    glob_param = pywrapcp.RoutingParameters()
AttributeError: 'module' object has no attribute 'RoutingParameters'

It seems the above issue of 'RoutingParameters' is resolved in https://github.com/google/or-tools/pull/119
but I can't seem to follow where the new API is, that has this issue resolved.

Then I uninstalled ortools using pip uninstall ortools.
Next I cloned the repository from git and ran following commands as described on webpage
make third_party
make python_modules

Tried with and without sudo both.

After running this command I can't seem to find where setup.py is located.
So I just tried to run cvrptw.py in or-tools/example/python directory I saw the following error.
Traceback (most recent call last):
  File "cvrptw.py", line 42, in <module>
    from ortools.constraint_solver import pywrapcp
ImportError: No module named ortools.constraint_solver

I am using anaconda.
Please let me know what should I do to get or-tools for python set up properly and running.

**Comment by lperron** [comment]
OK, I have not debugged installation with anaconda. We will have a look.

setup.py

 is in or-tools/temp/or-tools

I hope this helps.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-06-11 6:03 GMT+02:00 sagar81 <notifications@github.com>:

**Comment by lperron** [comment]
Actually, to create the pypi module (without uploading it), you need to type:
make third_party
make install_python_modules
make python
make pypi_archive

(you can also run make test_python)

**Comment by sagar81** [comment]
There is no dir called temp after I cloned the repository, master branch. I got the setup.py in or-tools/tools/setup.py.  But when I ran it using 
sudo python  setup.py install
it gave the following error:
  
File "setup.py", line 14
    DELETEUNIX               extra_link_args=['/MANIFEST'],
                                           ^
SyntaxError: invalid syntax

Any idea why this is happening and what can I do to fix it.

Thanks,
Sagar

**Comment by lperron** [comment]
Him 

have you seen my second post with full instructions to build the package?

Thanks

**Comment by sagar81** [comment]
Ah right, I forgot one of the commands there. Thanks a lot.
