### ISSUE TITLE
is there an implementation of ruin-and-recreate Schrimpf meta-heuristic? 

### ISSUE THREAD

**Issue by ihadanny** [google/or-tools#1920]
[https://github.com/graphhopper/jsprit/blob/master/docs/Meta-Heuristic.md](url) describe the ruin-and-recreate meta-heuristic. Is there an implementation of that idea for ORTOOLS? or is the current GUIDED_LOCAL_SEARCH close enough?

**Comment by lperron** [comment]
Is there an implementation of ..: no
is it close enough? you tell me :-)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 12 mars 2020 à 13:36, Ido Hadanny <notifications@github.com> a
écrit :

**Comment by ihadanny** [comment]
sounds like a challenge! :) we'll check it out on our use-case and let you know. funny that there's no thorough benchmark results comparing the 2 methods/tools

**Comment by DavidLSmyth** [comment]
@ihadanny any luck with this? Also interested in this if you managed to implement it or compare to  GUIDED_LOCAL_SEARCH
