### ISSUE TITLE
CP-SAT: Higher num_search_workers value increases the resolution time

### ISSUE THREAD

**Issue by jox79** [google/or-tools#1921]
**What version of OR-tools and what language are you using?**
Version: 7.5
Language:Python
Solver: CP-SAT
OS: Windows
CPU: 32 Cores
RAM: 128 GB

Dears,
I'm playing with num_search_workers parameter and I discovered a strange behaviour with or-tool 7.5 on windows.
I did the following tests on a 32 core machine and I discovered that 1 thread has the best performances.
Do you know why?:

start to solve using 1 threads ... solved in 13.578 secs

start to solve using 2 threads ... solved in 45.832 secs

start to solve using 4 threads ... solved in 53.031 secs

start to solve using 8 threads ... solved in 62.013 secs

start to solve using 16 threads ... solved in 157.5 secs

start to solve using 32 threads ... solved in 807.778 secs

start to solve using 64 threads ... solved in 386.252 secs

Attached please find the model:
[model.zip](https://github.com/google/or-tools/files/4326743/model.zip)

The scenario to solve is a boolean problem with linear constraints.
Thanks in advance for support.

**Comment by gregy4** [comment]
My computer with enough memory currently doesn't work so I cannot try your model. But I have two advices:
  1. Please try to solve your problem in linux (virtual machine is also possible), there's a suspicion that something is wrong with VS2019 and the issue was not solved yet.
  2. How much memory is used by solver ?  In extreme case, when a lot of memory is used, cpu cache can have a lot misses and I can imagine that less threads can be faster.

**Comment by gregy4** [comment]
I was able to reproduce it on or-tools 7.4 with java and windows 10. So it has nothing to do with VS2019 and memory shouldn't be problem also.

I think for 1 search worker is used strategy 'auto' which shoud be some kind of default sat search based on vsid heuristic. For 2 search workers should be used auto and some other strategy, I saw a code where based on index of a worker is selected strategy. With your proto file is logged only auto strategy so I would expect same result for both variants.

1 search worker

*** starting to load the model at 7.21s
*** starting sequential search at 8.68s
Initial num_bool: 145884
#Bound   8.68s best:-inf  next:[-0,2.66611626e+09] 
#Bound   8.80s best:-inf  next:[-0,2.66610501e+09] 
#1       9.08s best:2.66610501e+09 next:[2.66610501e+09,2.66610501e+09]  num_bool:145884
solution 2.666105007E9
#Done   11.02s

2 search workers

*** starting Search at 7.36s with 2 workers and strategies: [ auto, lp_br, helper, rnd_lns_auto, var_lns_auto, cst_lns_auto, rins/rens_lns_auto ]
#Bound   9.03s best:-inf  next:[-0,2.66611626e+09] auto
#Bound   9.16s best:-inf  next:[-0,2.66610501e+09] auto
#1      44.59s best:2.66610501e+09 next:[2.66610501e+09,2.66610501e+09] auto num_bool:145884
solution 2.666105007E9
#Done   46.80s  auto

**Comment by stradivari96** [comment]
Hi, just wanted to point out that this was kinda discussed/solved over at StackOverflow

https://stackoverflow.com/questions/60656897/cp-sat-higher-num-search-workers-value-increases-the-resolution-time
