### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [google/or-tools#1924]
I would like to point out that an identifier like “[`orfz__scan_bytes`](https://github.com/google/or-tools/blob/554cbccaa95b4c11eced13f145de1bf468e1f919/ortools/flatzinc/parser.cc#L30 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by lperron** [comment]
That is a name generated in c code by bison.

Le mar. 17 mars 2020 à 18:48, Markus Elfring <notifications@github.com> a
écrit :

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by lperron** [comment]
Are you trying to go pedantic on me ?

This is a minizinc layer, for academic challenges.


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 17 mars 2020 à 22:10, Markus Elfring <notifications@github.com> a
écrit :

**Comment by elfring** [comment]
I suggest to reconsider a specific implementation detail.
How do you think about to [reduce the tampering with the reserved name space](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?

**Comment by Mizux** [comment]
FYI this issue come the prefix:
https://github.com/google/or-tools/blob/858fa626959f7e386153af82756384b79f983b5a/ortools/flatzinc/parser.yy#L2

Flex doc:
> -Pprefix
changes  the default yy prefix used by flex for all globally-visible variable and  function names  to
instead  be prefix.  For example, -Pfoo changes the name of yytext to footext.   It  also  changes  the
name  of	the  default output file from lex.yy.c to lex.foo.c.  
Here are all of the names affected:
  yy_create_buffer
  yy_delete_buffer
  yy_flex_debug
  yy_init_buffer
  yy_flush_buffer
  yy_load_buffer_state
  yy_switch_to_buffer
  yyin
  yyleng
  yylex
  yylineno
  yyout
  yyrestart
  yytext
  yywrap

src: http://dinosaur.compilertools.net/flex/manpage.html
