### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [google/or-tools#1925]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [RevBitSet](https://github.com/google/or-tools/blob/39f44709bba203f5ff3bc18fab8098739f189a6d/ortools/constraint_solver/utilities.cc#L58)
- [SumObjectiveFilter](https://github.com/google/or-tools/blob/858fa626959f7e386153af82756384b79f983b5a/ortools/constraint_solver/local_search.cc#L2525)

**Comment by lperron** [comment]
Short answer, no.  :-)

Le mar. 17 mars 2020 à 18:54, Markus Elfring <notifications@github.com> a
écrit :

**Comment by elfring** [comment]
Do you really prefer to keep affected software components exception-unsafe in the C++ sense?

**Comment by elfring** [comment]
Would you take any other class into account as a similarly helpful alternative for a smart C++ pointer?

**Comment by lperron** [comment]
I don't want smart pointers for these classes. We have very thorough memory
checking at Google.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 17 mars 2020 à 22:22, Markus Elfring <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
the solver uses setjmp/longjmp, and you are talking to me about smart pointers.
I don't get it.

**Comment by elfring** [comment]
Do you care for run time consequences if [the exception “std::bad_alloc”](https://en.cppreference.com/w/cpp/memory/new/bad_alloc "Description for std::bad_alloc") would be thrown?

**Comment by lperron** [comment]
The program crashes. When it happens, we track it and fixes it.
But usually, when this happens, you are in trouble anyway.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 17 mars 2020 à 22:34, Markus Elfring <notifications@github.com> a
écrit :

**Comment by elfring** [comment]
I would appreciate a better known software behaviour also for exceptional situations.

**Comment by elfring** [comment]
Does your own source code analysis point [any remaining open issues](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "C++ Guideline “R.11: Avoid calling new and delete explicitly”") out?

**Comment by lperron** [comment]
We have extensive checking and hinting tools internally.
I will follow their recommendations.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 18 mars 2020 à 09:33, Markus Elfring <notifications@github.com> a
écrit :

**Comment by elfring** [comment]
Do the mentioned analysis tools suggest to [reconsider the usage of C++ new and delete operators](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r20-use-unique_ptr-or-shared_ptr-to-represent-ownership "C++ Guideline “R.20: Use unique_ptr or shared_ptr to represent ownership”")?

**Comment by lperron** [comment]
Please, I will stick to Google recommendations. I truly believe they are
good.

Your comments are not helping. I am sorry, as this is important for you,
but I will not change my code until our internal recommendation system
tells me to.

Thanks for your time.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 18 mars 2020 à 09:49, Markus Elfring <notifications@github.com> a
écrit :

**Comment by elfring** [comment]
Can Google recommendations (or the corresponding analysis tools) be incomplete in comparison to the C++ core guidelines?

**Comment by lperron** [comment]
Please stop this discussion. This is going nowhere.
I will not deviate from Google's internal recommendation, and I will
definitely not embark in a complex and error prone rewrite of the code.

Thanks again for your time and your concerns.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 18 mars 2020 à 10:15, Markus Elfring <notifications@github.com> a
écrit :

**Comment by elfring** [comment]
:crystal_ball: I am curious under which circumstances recommendations will be taken better into account also from the C++ core guidelines.

**Comment by lperron** [comment]
This is my last mail in this thread.

Have a good day.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 18 mars 2020 à 10:32, Markus Elfring <notifications@github.com> a
écrit :
