### ISSUE TITLE
Warm start annotations ignored

### ISSUE THREAD

**Issue by mvnarvaezt** [google/or-tools#1931]
I just copy pasted it in the minizinc ide (version 2.2.3) with geocode 6.1.0. 
I'm using Windows 10.4.

Here is the output:
```
`Warning,` ignored search annotation: warm_start_array([warm_start([[xi(1), xi(2)], [i(8), i(4)]]), warm_start([[xf(0), xf(2)], [f(5.6), f(4.7)]]), warm_start([[xs(0), xs(1), xs(2)], [s(), s()]])])
Warning, ignored search annotation: warm_start([[xb(0)], [b(true)]])
x = array1d(1..3, [0, 0, 0]);
xf = array1d(1..3, [1.4, 0.0, 0.0]);
b = true;
xs = array1d(1..3, [{}, {}, 5..9]);
----------
x = array1d(1..3, [0, 0, 1]);
xf = array1d(1..3, [2.4, 0.0, 0.0]);
b = false;
xs = array1d(1..3, [{}, {}, 5..9]);
----------
==========
Finished in 172msec
```

**Comment by lperron** [comment]
Are you using gecode or or-tools ?

**Comment by mvnarvaezt** [comment]
Geocode 6.1.0.  I got this answer in Stackoverflow (https://stackoverflow.com/questions/60780810/how-to-use-warm-starts-in-minizinc/60795087#60795087) 

Basically, the warm_start annotation isnt supported yet with Geocode. They really should add a note about that in the documentation.

**Comment by lperron** [comment]
This is an or-tools forum, not a gecode one.

Le lun. 23 mars 2020 à 04:15, mvnarvaezt <notifications@github.com> a
écrit :
