### ISSUE TITLE
Access violation running simple GLOP example

### ISSUE THREAD

**Issue by gurki** [google/or-tools#1932]
**What version of OR-tools and what language are you using?**
Version: 
- stable (858fa626959f7e386153af82756384b79f983b5a)
- pre-built [VisualStudio2019-64bit_v7.5.7466 ](https://developers.google.com/optimization/install/cpp/windows)

Language: C++17

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
- CBC
- GLOP

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
Run [C++ Get Started Example](https://developers.google.com/optimization/introduction/cpp) or [MIP Example](https://developers.google.com/optimization/mip/integer_opt)

**What did you see?**
Consistent crash due to access violation in `absl::container_internal::raw_hash_set` when calling 
`objective->SetCoefficient(x, 3);`. Digging into it, it seems the objective is not initialized correctly. And going back further in the example, the constraint vector itself seems corrupt already. This is the console output:
```
I0321 00:00:31.862984 16288 main.cpp:12] Number of variables = 2
I0321 00:00:31.864295 16288 main.cpp:28] Number of constraints = 389726751
00:00:31: The program has unexpectedly finished.
```

Not sure at all what the issue here is. Thanks for any input!

**Comment by Mizux** [comment]
Prebuilt are using abseil-cpp C++11 while it seems you are using C++17. Since abseil-cpp is standard dependent (header will change according to c++ standard version) you must:
* rebuilt or-tools against C++17, ed this is not officially supported so you'll need to hack the build system and you'll be on your own
* Build your project against C++11

**Comment by gurki** [comment]
Compiling the examples with C++11 did indeed solve the issue. Thanks for your quick response!

Are there plans to update the standard at some point, as our project uses C++17 features throughout? For now I'm gonna go ahead and venture into DIY-rebuild-or-tools-land. Wish me luck.
