### ISSUE TITLE
Operator overloading for CP-SAT / C++

### ISSUE THREAD

**Issue by syxolk** [google/or-tools#1933]
**What language and solver does this apply to?**
C++ / CP-SAT

**Describe the problem you are trying to solve.**
It would be really nice to have operator overloading for the C++ interface of CP-SAT to improve readability of the model building code. It also makes it easier to transition from Python to C++.

**Describe the solution you'd like**
I already experimented a bit with it by implementing the following operators:
```c++
namespace operations_research {
namespace sat {
  LinearExpr operator+ (LinearExpr x, const LinearExpr &y);
  LinearExpr operator* (const LinearExpr& x, std::int64_t f);
  LinearExpr operator* (std::int64_t f, const LinearExpr& x);
}
}
```

which allows me to write code like this:
```c++
cp_model.AddLessThan(3 * x + 2 * y + 2 * z, 11);
```

in the future it might even look like this:
```c++
cp_model.Add(3 * x + 2 * y + 2 * z < 11);
```

**Describe alternatives you've considered**
I know that the Python wrapper already has overloaded operators but model building is much slower than in C++.

As you can see, operator overloading can be implemented with a separate header-file without touching OR-Tools. However, this comes with a significant performance penalty, as I'm going to explain below.

**Additional context**
There are three improvements that cannot be easily done with an external header library but instead must be implemented in OR-Tools:

* **Reduce temporary objects by implementing Move-Semantics on LinearExpr**: When constructing a linear term such as `1 * w + 3 * x + 2 * y + 2 * z` a lot of temporary LinearExpr are created (that allocate two vectors each). Using C++ Move Semantics, only one temporary object is created and then modified, reducing the memory allocation overhead.
- **Use Small-Vector implementation for LinearExpr**: Currently, the LinearExpr class holds two vectors containing all variables and their coefficients. Those two vectors must be allocated whenever you want to create a linear constraint. However, a lot of linear constraints only consist of a small number of variables. I think it would greatly reduce memory allocations if we could use a [Smallvec, similar to what is done in Rust](https://github.com/servo/rust-smallvec) that holds a small amount of items directly on the stack and falls back to heap allocation only if needed.
- **New LinearInequality class**: This class would be needed to hold linear inequalities such as `2*x + 1*y >=10`. Effectively, this is a LinearExpr and a Domain. Then, one could add a method on CpModelBuilder to accept such a linear inequality: `model.Add(2 * x > 10)`. This would be nice syntactic sugar compared to `model.AddGreaterThan(2 * x, 10)`.

**Comment by lperron** [comment]
Sorry, it was a deliberate decision not to.

**Comment by Phibedy** [comment]
@lperron why? Because we would like to move from python to C++, but we do not like the C++ usability. We don't mind creating a pull-request.

**Comment by lperron** [comment]
Sorry, long internal discussion.

I will not accept a pull request for this.
You can always create your own operators in your application.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
