### ISSUE TITLE
setTimeLimit() not working for LocalSearchMetaheuristic.Value.GREEDY_DESCENT

### ISSUE THREAD

**Issue by janmenjoyroy** [google/or-tools#1934]
**What version of OR-tools and what language are you using?**
Version: v7.5
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing Solver

**What operating system (Linux, Windows, ...) and version?**
Linux Ubuntu 18.04 LTS

**What did you do?**
We tried to set the setTimeLimit() value for the Routing solver, so that it return or stop finding optimal solution after that timeout (in seconds).

Please find the code snippet below:
`RoutingSearchParameters searchParameters = main.defaultRoutingSearchParameters()
				.toBuilder()			 
                               .setLocalSearchMetaheuristic(LocalSearchMetaheuristic.Value.GREEDY_DESCENT)
				.setTimeLimit(Duration.newBuilder().setSeconds(1).build())
				.build();`

**What did you expect to see**
The TSP solver should stop searching for optimum route after the set time limit is reached. 

Example: We set the time limit to 1.0 sec
But the below o/p shows that the TSP is running beyond 1.0 sec.
Tsp ex time : 4.517

**What did you see instead?**
The TSP solver is continuing beyond the time set and the different timeout values in seconds are not working. 

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by suchee** [comment]
I have the same issue. Can some one throw some insights here @Mizux

**Comment by Mizux** [comment]
Please ask on the mailing list, IIRC time limit is for the Local Search since it is checked each time a new solution is found.
