### ISSUE TITLE
google-ortools-native.dll not found after app installation

### ISSUE THREAD

**Issue by atleri** [google/or-tools#1936]
**What version of OR-tools and what language are you using?**
Version: 7.5.7466 (nuget)
Language: C#

**the default linear solver (GLOP?)**

**Developed on Windows 10 Enterprise, tested installation on Windows 10 Pro, both computers x64**

**What did you do?**
I have a solution with many projects, some .Net Framework 4.7.2 (including the main application),
and some .net standard 2.0 (including the assembly using OR-tools).

I have install the OR-tools nuget package for both the assembly that uses or-tools, and for the main application.

When I run this on the developement PC, all is good. Even if I run it directly from the bin-directory, not through visual studio.

However, when I deploy to my test computer (either by simply copying the whole bin-directory or as ClickOnce publishing), the program claims that google-ortools-native.dll is not found, even if it is in the same directory as the application. The exception information is as follows:

![ErrorMsg](https://user-images.githubusercontent.com/59446019/77577643-7220d600-6ed7-11ea-908a-e20f3be9c7f1.jpg)

I'm assuming this is because some dependency of google-ortools-native.dll is not present, but I'm not able to figure out which.

DependencyWalker indeed reports a lot of missing files. The report is the same on both computer.

But as I said, it does work perfectly on the development computer.

I've seen several issues that looks related, but have not been able to devine a solution. Any help would be much appreciated.

![DependencyWalkerCapture](https://user-images.githubusercontent.com/59446019/77577415-0b9bb800-6ed7-11ea-91ab-abdf8dfebd1a.JPG)

**Comment by atleri** [comment]
Ahh, it seems that the reports from DependencyWalker is due to limitations in DependencyWalker:
"..These are API-sets - essentially, an extra level of call indirection introduced gradually since windows 7. Dependency walker development seemingly halted long before that, and it can't handle API sets properly.

So these are all false negatives and nothing to worry about. You're not missing anything."
(from https://stackoverflow.com/questions/36240215/dependency-walker-missing-dlls )

**Comment by Mizux** [comment]
Did you install the C++ 2019 runtime redistributable on your test machine ?

**Comment by atleri** [comment]
Hi,
Thanks for the fast response. No, that was exactly it, thank you.

BTW, I did not submit an issue, but earlier I downloaded the source code to build locally. The build failed because one of the files contained a broken url for downloading SWIG. I just found another url that work, and so the whole thing worked, but I just thought I'd let you know…

Krgds,
-atle

**Comment by ptr1120** [comment]
Is the google-ortools-native.dll inside the directory you are deploying? Are you using netframework or netcore for the target app. Do you use the new csproj format or the old for the target app?

**Comment by Mizux** [comment]
@atleri did you use the stable branch (our default branch) then yes the url is broken:
https://github.com/google/or-tools/blob/858fa626959f7e386153af82756384b79f983b5a/makefiles/Makefile.third_party.win.mk#L514

But now we use again the official default sourceforge url on master:
https://github.com/google/or-tools/blob/4e87a1c61610e89ce1a73ded7d9b255fa59c75c2/makefiles/Makefile.third_party.win.mk#L514

I hope to release a new release (v7.6) in April

**Comment by atleri** [comment]
Yes, I used your stable branch. OK, so all is in hand.
Thanks again for your fast and helpful responses. Keep up the good work.

Krgds,
-atle
