### ISSUE TITLE
 cannot import name 'pywrapcp' from 'ortools' 

### ISSUE THREAD

**Issue by victor510295** [google/or-tools#1939]
I've already download the package "ortools"
`from ortools import pywrapcp`
and trying to use "pywrapcp" this function.
```
manager = pywrapcp.RoutingIndexManager(len(data['distance_matrix']),
                                       data['num_vehicles'], data['depot'])
```
But it shows error:
**ImportError: cannot import name 'pywrapcp' from 'ortools'**

How can I solve it?

**Comment by lperron** [comment]
which platform?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 27 mars 2020 à 11:15, victor510295 <notifications@github.com> a
écrit :

**Comment by pointer** [comment]
windows 10, nodejs

**Comment by lperron** [comment]
Make sure you have visual studio 2019 redistributables installed

Le lun. 1 juin 2020 à 13:49, Kateb Ghemari <notifications@github.com> a
écrit :

**Comment by jha-vineet69** [comment]
Hey @victor510295 pywrapcp is available under ortools.constraint_solver. Use "from ortools.constraint_solver import pywrapcp" instead.

**Comment by sannicosan** [comment]
OR-Tools really needs proper documentation to understand what is the parent modules of the subclasses you import.. 
Even in the guides, the imports are missing so you can't possibly know where they come from..

**Comment by lperron** [comment]
This is vague and not helping.
Especially in python, all classes are prefixed by the name of the module

Doc is as good as possible, and clearly lacking.
So sweeping statements are just not useful.

Thanks

Le mar. 31 janv. 2023, 18:39, Nicolás Sánchez ***@***.***> a
écrit :

**Comment by Mizux** [comment]
> OR-Tools really needs proper documentation to understand what is the parent modules of the subclasses you import.. Even in the guides, the imports are missing so you can't possibly know where they come from..

Which page ?
https://developers.google.com/optimization/routing/vrp#complete_programs here you can see them...
