### ISSUE TITLE
Missing functions in python

### ISSUE THREAD

**Issue by tigrandp** [google/or-tools#194]
Call of `MakeForbiddenIntervalCt` on `constraint_solver` fails in python.

**Comment by lperron** [comment]
It was renamed to MakeNotMember, so NotMember un python.

I have not checked though.
Le 13 juin 2016 21:10, "Tigran Hakobyan" <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
I have checked, and it was missing.
I have added it and pushed it to github.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-06-13 22:37 GMT+02:00 Laurent Perron <lperron@google.com>:

**Comment by tigrandp** [comment]
Thanks !
