### ISSUE TITLE
Solver crashes with exception "exception of type std::out_of_range: `InlinedVector::at(size_type) const` failed bounds check"

### ISSUE THREAD

**Issue by lalithsuresh** [google/or-tools#1940]
**What version of OR-tools and what language are you using?**
Version: master/v7.3/v7.2 etc.
Language: C++/Java/Python/C#

Version: 7.5
Language: Java
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

CP-SAT

**What operating system (Linux, Windows, ...) and version?**

Reproducible on Linux (Ubuntu 18.04) and macOS Mojave 10.14.6

**What did you do?**
Run a large model with cumulative constraints.

**What did you expect to see**

Runs without errors.

**What did you see instead?**

On Mac, from IDE:
```
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: `InlinedVector::at(size_type) const` failed bounds check

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

On Linux:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  `InlinedVector::at(size_type) const` failed bounds check
^[[m#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fab676188f0, pid=1, tid=19
#
# JRE version: OpenJDK Runtime Environment (12.0.2+10) (build 12.0.2+10)
# Java VM: OpenJDK 64-Bit Server VM (12.0.2+10, mixed mode, sharing, tiered, compressed oops, serial gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x408f0]  abort+0x230
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P" (or dumping to //core.1)
#
# An error report file with more information is saved as:
# //hs_err_pid1.log
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-build/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

I'm pretty sure the model worked at similar scales before (maybe I was on an older version of or-tools?). If this error is new to you, I can try to dig a bit deeper and try to produce a model Proto (which I was also not successful in doing in the past due to #1779 ).

**Comment by lperron** [comment]
Please send a model proto.

Le sam. 28 mars 2020 à 20:20, Lalith Suresh <notifications@github.com> a
écrit :

**Comment by lalithsuresh** [comment]
Found the cause. It was a bug in one end of my system, which eventually led to `model.newFixedInterval()` being invoked with an empty Domain. Here's a test case to reproduce it.

```
    @Test
    public void testIntervalsCrash() {
        // Create the model.
        final CpModel model = new CpModel();
        final Domain d = Domain.fromValues(new long[0]);
        final IntervalVar var = model.newFixedInterval(d.min(), d.max(), "");
    }
```

**Comment by lperron** [comment]
Thanks. I will add that to our validator and tests.
