### ISSUE TITLE
Exception in initializing Routing Index Manager with version 7.5 on Ubuntu 18.04

### ISSUE THREAD

**Issue by pardeep632** [google/or-tools#1942]
**What version of OR-tools and what language are you using?**
Version: 7.5
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing Solver

**What operating system (Linux, Windows, ...) and version?**
Linux Ubuntu 18.04
**What did you do?**
Try to initialize Routing Index Manager.
Steps to reproduce the behavior
Code Snippet:
```java
       val dd = dataModel.timeDistancePair.first

        val manager = RoutingIndexManager(dd.size, dataModel.mDriverList.size, dataModel.depot)
        val routing = RoutingModelWithoutGC(manager)

        val longUnaryOperator = LongUnaryOperator { fromIndex: Long ->
            val fromNode = manager.indexToNode(fromIndex)
            dataModel.demands[fromNode]
        }
        val demandCallbackIndex = routing.registerUnaryTransitCallback(longUnaryOperator)

        /* ============= Start driver distance constraint from depot ==========*/

        val longBinaryOperator = LongBinaryOperator { left, right ->
            val fromNode = manager.indexToNode(left)
            val toNode = manager.indexToNode(right)
            dd[fromNode][toNode]
        }

        val transitCallbackIndex = routing.registerTransitCallback(longBinaryOperator)
        routing.setArcCostEvaluatorOfAllVehicles(transitCallbackIndex)
        /* ============= End driver distance constraint from depot ==========*/

        routing.addDimensionWithVehicleCapacity(
            demandCallbackIndex, 0, // null capacity slack
            dataModel.vehicleCapacities.toLongArray(), // vehicle maximum capacities
            true, // start cumul to zero
            "Capacity"
        )

        val searchParameters = main.defaultRoutingSearchParameters()
            .toBuilder()
            .setFirstSolutionStrategy(FirstSolutionStrategy.Value.PATH_CHEAPEST_ARC)
            .build()
        val solution = routing.solveWithParameters(searchParameters)`
```
**What did you expect to see**

**What did you see instead?**
Exception in thread "OkHttp Dispatcher" java.lang.NoSuchMethodError: SwigDirector_PathOperator_OnNodeInitialization
	at com.google.ortools.constraintsolver.mainJNI.swig_module_init(Native Method)
	at com.google.ortools.constraintsolver.mainJNI.<clinit>(mainJNI.java:2452)
	at com.google.ortools.constraintsolver.RoutingIndexManager.<init>(RoutingIndexManager.java:46)
	at com.x.y.z.solver.MySolver.orToolsSolver(MySolver.kt:142) This line is  (`val manager = RoutingIndexManager(dd.size, dataModel.mDriverList.size, dataModel.depot)`)

**Anything else we should know about your project / environment**

**Comment by Mizux** [comment]
There won't be any maintenance effort for the v7.5, please try to update to the last version and see if the problem still occurs.
