### ISSUE TITLE
swigwin download path changed

### ISSUE THREAD

**Issue by davidhdezf** [google/or-tools#1943]
Tried to install ORTools from source and got an error in swigwin

The new path is:
https://newcontinuum.dl.sourceforge.net/project/swig/swigwin/swigwin-4.0.1/swigwin-4.0.1.zip

Changed Makefile.third_party.win.mk to solve the problem

**Comment by Mizux** [comment]
did you use master or default branch ?

**Comment by davidhdezf** [comment]
Hi Mizux, I used the default  (stable) branch. 

Best regards,

**Comment by lperron** [comment]
This is fixed on master.

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 31 mars 2020 à 18:26, davidhdezf <notifications@github.com> a
écrit :
