### ISSUE TITLE
SatParameters::set_max_memory_in_mb() won't work

### ISSUE THREAD

**Issue by WyldeCat** [google/or-tools#1944]
**What version of OR-tools and what language are you using?**
Version: master/v7.3/v7.2 etc.
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 16.04

**What did you do?**
Build a big CP model and use set_max_memory_in_mb() function.

**What did you expect to see**
I have 128GB memory in my system and used set_max_memory_in_mb() function with 65536 as argument.
But while my program is hanging in SolveCpModel() function, my system has 96GB of free memory at that time, system memory usage is steadily increasing and process is killed eventually.

I followed this guide (https://developers.google.com/optimization/cp/cp_tasks) and switch 
```
parameters.set_max_time_in_seconds(10.0);
```
to
```
parameters.set_max_memory_in_mb(65536);
```

**Comment by lperron** [comment]
Can you send us a faulty model ?

**Comment by lperron** [comment]
This is a known issue. We will not solve it.
