### ISSUE TITLE
Python CPSAT AddCumulative like constraint which forces equal and t depending capacity

### ISSUE THREAD

**Issue by Phibedy** [google/or-tools#1946]
**What language and solver does this apply to?**
Python CP-SAT

**Describe the problem you are trying to solve.**
Number of overlapping intervals at slot t.
Like the AddCumulative constraint:
```python
    def AddCumulative(self, intervals, demands, capacity):
        """Adds Cumulative(intervals, demands, capacity).
    This constraint enforces that:
        for all t:
          sum(demands[i]
            if (start(intervals[t]) <= t < end(intervals[t])) and
            (t is present)) <= capacity
```
I would like to have a constraint which does the following 
```python
    def AddXXX(self, intervals, demands, capacity):
       """
    This constraint enforces that:
        for all t:
          sum(demands[i]
            if (start(intervals[t]) <= t < end(intervals[t])) and
            (t is present)) == capacity[t]
```

At the moment I am using a boolean array for each interval which indicates if the index of the given boolean in the array is included in the interval. Afterwards I sum them up, but that seems to be quite slow if I add a lot of intervals.

I also tried to optimize it by using `NewConstant(0/1)` instead of `NewBoolean` if I already know the result for the slot, but this did not change anything.

**Comment by lperron** [comment]
Please use the mailing list.
