### ISSUE TITLE
VRPTW Multiple Depots all different departure time

### ISSUE THREAD

**Issue by ignoramous1** [google/or-tools#1949]
Im using or-tools in python and have 9 depots, each one opens at a different time. Ive set the time windows for each depot, but all vehicles departing from different depots depart at the same time as the first depot. 

`  data['time_windows'] = [
        (150, 840), #0 Depot
        (537, 1227), #1 Depot
        (120, 810), #2 Depot
        (180, 870), #3 Depot
        (120, 810), #4 Depot
        (180, 870), #5 Depot
        (360, 1050), #6 Depot
        (60, 750), #7 Depot
        (0, 690), #8 Depot
        ...all other delivery point time windows...
`
Route output has all vehicles leaving at the same time
`0 Time(150,150) 
1 Time(150,150)
...
8 Time(150,150)`

Im currently using a work around, starting all depots at 0 and modifying the time matrix to add the depot delayed start time to the time from each depot to the delivery locations. I think this is affecting the ability to find the best solution. 

Is there a way to get the solver to have different departure times for each depot? Instead of applying the departure time from the first depot to all vehicles leaving all the other depots?

**Comment by lperron** [comment]
Please use the mailing blist.
