### ISSUE TITLE
AStar Python Ortools

### ISSUE THREAD

**Issue by swethmandava** [google/or-tools#195]
I have installed python ortools from the python package available here 
https://developers.google.com/optimization/installing#python

It works fine but isn't updated with AStar algorithm in graph. How can I update my python package to include AStar?

**Comment by lperron** [comment]
Hi,

RIght now you need to build python from sources to have access to AStar
from python.
We should be releasing new pypi modules very soon.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-06-14 11:33 GMT+02:00 swethmandava <notifications@github.com>:

**Comment by lperron** [comment]
Exported in the latest pypi modules.
Closing
