### ISSUE TITLE
[Help Pls] How to solve the problem of truck space capacity for delivery and pickup in (CPDVRPTW) >

### ISSUE THREAD

**Issue by Khixinhxan** [google/or-tools#1954]
**What language and solver does this apply to?**
All, Python Routing, Linear Solver

I have a network of points to delivery and points to pickup and a number of points at the same location as the points to be delivered and to be taken (I will duplicate this point in the data) How do the vehicles can do all the main tasks delivery all points , at the same time, goods will be picked up at the condition that the goods are existing on the car + the goods need pickup <= truck capacity at each node.

**Comment by Mizux** [comment]
For modeling question please use the mailing-list instead...
