### ISSUE TITLE
vrp_capacity not find solution

### ISSUE THREAD

**Issue by janderadutra** [google/or-tools#1955]
In the example https://raw.githubusercontent.com/google/or-tools/master/ortools/constraint_solver/samples/vrp_capacity.py 

data['demands'] = [0, 1, 1, 2, 4, 2, 4, 8, 8, 1, 2, 1, 2, 4, 4, 8, 8]
data['vehicle_capacities'] = [15, 15, 15, 15] 
it works, but if changed position, not works.
Ex.
data['demands'] = [0, 1, **8**, 2, 4, 2, 4, 8, **1**, 1, 2, 1, 2, 4, 4, 8, 8]
data['vehicle_capacities'] = [15, 15, 15, 15]

I test in another situation and the same error

**Comment by KingDoum** [comment]
did you try to increase the capacity of your total truck

**Comment by janderadutra** [comment]
> did you try to increase the capacity of your total truck

the truck won't do if I increase

**Comment by alessandrobessi** [comment]
I don't know if the following can help, but I get the same issues (in Python and C++) if I add the following constraints:

```
  // [START orders]
  Solver *const solver = routing.solver();
  for (auto order : data.orders)
  {
    for (int i = 0; i < order.size() - 1; i++)
    {
      solver->AddConstraint(solver->MakeEquality(
          routing.VehicleVar(order[i]), routing.VehicleVar(order[i + 1])));
    }
  }
  // [END orders]
```
where `orders` is defined inside the `DataModel` struct in `examples/cpp/vrp_capacity.cc`
```
const std::vector<std::vector<int64>> orders{
      {8, 6, 2, 10},
      {4, 3, 5, 9},
      {7, 1, 15, 11, 14},
      {13, 12, 16}};
```
In this case, it works if I set:
```
  const std::vector<int64> vehicle_capacities{20, 24, 30};
```
but it does not neither if I shuffle the capacities:
```
  const std::vector<int64> vehicle_capacities{30, 24, 20}; // does not work!
```
neither if I shuffle the order of `const std::vector<int64> demands`

**Comment by Mizux** [comment]
This equality meant both node must be assigned at the same time but usually the solver create the first solution incrementaly by adding nodes one by one.

**Comment by janderadutra** [comment]
This problem is structural and difficult to solve. You need to find the balance so as not to hinder the best sequence of points. 
But if you can, that lib will be much better.
Good Luck!

**Comment by janderadutra** [comment]
will be solved or problem, or have they given up?

**Comment by Mizux** [comment]
@alessandrobessi you should try to use ActiveVar for your constraint:
e.g.
```python
constraintActive = routing.ActiveVar(routing.NodeToIndex(A)) * routing.ActiveVar(routing.NodeToIndex(B))
routing.solver().Add(
  constraintActive * routing.VehicleVar(routing.NodeToIndex(A)) == 
  constraintActive * routing.VehicleVar(routing.NodeToIndex(B)))
```
