### ISSUE TITLE
Troubles building from master on Linux Debian

### ISSUE THREAD

**Issue by andreacassioli** [google/or-tools#1959]
Hi, 
I am building or-tools from `master` on a `Debian 10` machine. Following 

https://developers.google.com/optimization/install/cpp/source_linux#build_linux

I have struggle with two issues running `make third_party`:

* if `swig` is not available, I got a weird message: `/bin/sh: 0: Illegal option -r` . it seems to originate in `makefiles/Makefile.third_party.unix.mk` when available `swig` version is checked. If it is not available I guess the shell extension fails. Installing `swig` fix the error message. I could not find this step in the docs. Have I missed some info? If not, I guess it should be added.

* the `configure` script in the `dependencies/sources/patchelf-0.10/` did not get created and that cause `make third_party` to fail. Manually running `make` in that folder did the trick. Again, did I miss a step here as well?

**Comment by Mizux** [comment]
If I recall correctly, the "-r" issue may comes from the `lsb_release` package not installed.

you should take a look of my incoming Dockerfile here:
https://github.com/google/or-tools/blob/mizux/dev/makefiles/docker/centos/Dockerfile

I'll push it to master once I solved the last remaining ci issue
see: https://github.com/google/or-tools/actions/runs/75381755

**Comment by andreacassioli** [comment]
@Mizux yes I did check the requirements, and indeed `lsb_release` was already installed. I tried also to remove it and it makes no difference. 

Even thought Swig is need for specific bindings, it still checks for it.

What about this `configure` issue?

**Comment by Mizux** [comment]
contrary to Bazel or CMake, Makefile based build need to parse ALL Makefile.*.mk then in a second pass resolve the target which means the SWIG check "written in Make syntax" which is only needed for Java, .Net or Python is always performed each time make is run -_-...

**Comment by Mizux** [comment]
for the configure issue first time I heard it, my bet the patchelf wget command fails to properly download it ?

**Comment by andreacassioli** [comment]
@Mizux OK, thanks for following up. Let's see if I will experience similar issue in the future. Feel free to close or keep the issue for reference until you get your PR in master.

**Comment by Mizux** [comment]
CI Make on Debian is on master -> I'll close it, but keep it in mind if ever happen
BTW thanks for the feedback...
