### ISSUE TITLE
Compilation issue std::isnan undefined

### ISSUE THREAD

**Issue by shannonfenn** [google/or-tools#196]
On Ubuntu 16.04 with gcc 5.3.1.

Steps to reproduce:
  `make python`

Problem:
 ` ‘isnan’ was not declared in this scope`      (occurs in multiple source files)

Possible source:
  `using std::isnan;` is given in fp_utils.h but only for systems where `__APPLE__` is defined.

**Comment by lperron** [comment]
Hello, 

I have pushed the fix to github.

Thanks for the report.
