### ISSUE TITLE
Makespan in scheduling problem

### ISSUE THREAD

**Issue by Montassar30** [google/or-tools#1964]
**What language and solver does this apply to?**
, C++ 

Hi! I'm having some troubles calculating the makespan in a scheduling problem. The problem is Rm|Sijk|Cmax, that is to say I have to schedule n jobs on m independant unrelated machines, where the set up times are not symmetric and depend on the machine (for all jobs i,j and all machine k, Sijk =! Sjik). Moreover, each job can only be processed on a subset of the m machines. There is no preemption. The objective is to minimize the makespan

**Comment by lperron** [comment]
Please use the mailing list.

**Comment by Mizux** [comment]
duplicate of #1963 ...
