### ISSUE TITLE
Mac OS security issue

### ISSUE THREAD

**Issue by klementtan** [google/or-tools#1965]
**What version of OR-tools and what language are you using?**
Version: v7.5.7466
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Mac OS Catalina v10.15.4
**What did you do?**
1. Download binary from [here](https://developers.google.com/optimization/install/cpp/mac)
2. run `make test_cc` in terminal

**What did you expect to see**
Successful installation

**What did you see instead?**
<img width="429" alt="image" src="https://user-images.githubusercontent.com/49265907/79455372-582e6b00-801f-11ea-89ed-bcb702d9bf49.png">

**Comment by Mizux** [comment]
AFAIK Apple start to rollout developer certificat everywhere, still don't know how to resolve it for a FOSS project.

**Comment by lperron** [comment]
Cannot reproduce. Please reopen if needed. Note that or-tools is provided by brew.
