### ISSUE TITLE
CP: creating a variable with an empty domain

### ISSUE THREAD

**Issue by sghb** [google/or-tools#1966]
Hi,

This is for the (classic) CP solver in OR-Tools 7.5.7466 via Python (Windows 10).

Creating a variable with an empty domain should lead to the solver quickly returning, just with no solutions.  Instead, it goes into what looks like a long loop.

Cheers
```python
import ortools.constraint_solver.pywrapcp

solver = ortools.constraint_solver.pywrapcp.Solver('')

## This works as expected
# x = solver.IntVar(0, 3)
# solver.Add(x <= -2)

## This does not
x = solver.IntVar(0, -2)

asg = solver.Assignment()
asg.Add([x])
coll = solver.AllSolutionCollector(asg)

db = solver.Phase([x], solver.INT_VAR_DEFAULT, solver.INT_VALUE_DEFAULT)

solver.Solve(db, [coll, solver.SearchLog(1, None)])

n = coll.SolutionCount()

for i in range(n):
    sol = coll.Solution(i)
    print('Solution %d: %s' % (i + 1, sol))

print('# Solving done in %.3fs: %d branches, %d failures, %d solutions' % (
    solver.WallTime() / 1000, solver.Branches(), solver.Failures(), n))
```

**Comment by lperron** [comment]
You are aware that this solver is deprecated ?

**Comment by Mizux** [comment]
not sure `x = solver.IntVar(0, -2)` is a relevant interval BTW this solver is deprecated so I don't think we will try to fix this corner case in the forseeable future  i.e. check input ranges and throw errors/whatever.
BTW thanks for the feedback ! I'll close it, since it won't be fixed...

**Comment by sghb** [comment]
Yes; I understand.

This came up in a solver with a user-defined search strategy that is much faster than basic CPSAT (lots of awkward symmetries in the model).

It is of course easy to work around this issue.  Thank you for your work, on both solvers.
