### ISSUE TITLE
AddDimensionWithVehicleCapacity(): Different slack per node per vehicle 

### ISSUE THREAD

**Issue by AntonisKl** [google/or-tools#1968]
**Language**: Python

Hello,

Suppose we add a dimension to the VRP using the function **AddDimensionWithVehicleCapacity()**. In the problem I am trying to solve, I want to be able to **set a different Slack value per node per vehicle**. As for "per node", I am using the **SetRange()** method to set the Slack value as I wish in each node.
But, is there a way to set a **different Slack value for each vehicle in each node**?

Thank you in advance.

**Comment by lperron** [comment]
Please use the mailing list

**Comment by Mizux** [comment]
By default, except start and end node, all nodes are vehicle agnostic...
I would:
1. duplicate all nodes
2. Associate each node to a specific vehicle (you must have a setRange on vehicle property of a node IIRC)
3. Set a Slack var for each node (i.e. for a specific vehicle)
4. Add all duplicate node to a disjunction so only one will be visited

**Comment by Shaharsha** [comment]
Hi @Mizux,
I trying to do something similar but I'm having a problem.

When I'm using both this: solver.Add(routing.VehicleVar(routing.NodeToIndex(node_A1_index)) == vehicle_1_index)
and
this: routing.AddDisjunction([A1_index, A2_index, A3_index])

The solver doesn't find a solution. But when I remove one of them, it finds a solution.
Maybe this constraint (solver.Add(routing.VehicleVar(routing.NodeToIndex(node_A1_index)) == vehicle_1_index))
assures that this node is delivered using vehicle_1_index vehicle, and if its dropped the solver is unable to find a solution?

If so, do you have a suggestion how to put this constraint but allow the node to be dropped?
