### ISSUE TITLE
Python pip support 

### ISSUE THREAD

**Issue by jvgomez** [google/or-tools#197]
Related to issue #176 

The current packaging generates .egg files, which are useful for easy_install, but pip does not support this format, and therefore `sudo pip install ortools` fail.

It would be nice to have a pip-compatible version.

**Comment by wolfv** [comment]
Maybe the fix would be to change the line 

```
cd temp/ortools && python$(PYTHON_VERSION) setup.py bdist_egg upload
```

to 

```
cd temp/ortools && python$(PYTHON_VERSION) setup.py sdist upload
```

which uploads a source tar.gz which, if my assumptions are correct, can be installed through pip.

**Comment by lperron** [comment]
Unfotunately not, as we are bundling shared librairies, that are too
complex to build for setuptools.

Le 22 juin 2016 8:49 AM, "Wolf Vollprecht" <notifications@github.com> a
écrit :

**Comment by wolfv** [comment]
How about `bdist_wheel`? That's also how tensorflow is distributed.

**Comment by lperron** [comment]
We are transitioning to wheel for windows and Mac. Unfortunately, this is
not supported on linux with native modules.

Le 22 juin 2016 9:55 AM, "Wolf Vollprecht" <notifications@github.com> a
écrit :

**Comment by edmorley** [comment]
> We are transitioning to wheel for windows and Mac. Unfortunately, this is
> not supported on linux with native modules.

Fwiw, after [PEP 513](https://www.python.org/dev/peps/pep-0513/), pip and PyPI now support Linux wheels. 

(Note the Python packaging docs aren't quite up to date [here](https://packaging.python.org/distributing/#platform-wheels), as noted by pypa/python-packaging-user-guide#238, so refer to the PEP page for guidance instead.)

**Comment by christianklotz** [comment]
I have only limited knowledge about the distribution mechanisms I'm afraid but I wondered if it's "just" a change in [Makefile.python.mk#L318-L326](https://github.com/google/or-tools/blob/a86664de480d13383d8157b3954b63e6e970b86d/makefiles/Makefile.python.mk#L321-L325) or whether it involves more?

```sh
ifeq ($(SYSTEM),win)
	cd $(PYPI_ARCHIVE_TEMP_DIR)\ortools && $(PYTHON_EXECUTABLE) setup.py bdist_egg bdist_wheel bdist_wininst
else
  ifeq ($(PLATFORM),MACOSX)
	cd $(PYPI_ARCHIVE_TEMP_DIR)/ortools && $(PYTHON_EXECUTABLE) setup.py bdist_egg bdist_wheel
  else
	cd $(PYPI_ARCHIVE_TEMP_DIR)/ortools && $(PYTHON_EXECUTABLE) setup.py bdist_egg 
  endif
endif
```


```bash
ifeq ($(SYSTEM),win)
	cd $(PYPI_ARCHIVE_TEMP_DIR)\ortools && $(PYTHON_EXECUTABLE) setup.py bdist_egg bdist_wheel bdist_wininst
else
	cd $(PYPI_ARCHIVE_TEMP_DIR)/ortools && $(PYTHON_EXECUTABLE) setup.py bdist_egg bdist_wheel
endif
```

**Comment by lperron** [comment]
If you do that, twine complains that you cannot upload linux wheel.

It is much more complex than that (see manylinux wheel).

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-03-14 16:20 GMT+01:00 Christian Klotz <notifications@github.com>:
