### ISSUE TITLE
Partial Solution to the assignment problem

### ISSUE THREAD

**Issue by anorak94** [google/or-tools#1970]
I am using the or tools for solving as assignment problem. I noticed on one of the threads that there is no way to compute the partial solution to the assignment problem. Is it possible to model this problem in some other way in or tools. my use case can have some workers that are not assigned any tasks at all so instead of no feasible assignment i would like to access the best partial assignment. I was going through the examples and it looks really cool.
Thanks

**Comment by Mizux** [comment]
Please use the mailing list instead...

**Comment by amitbcp** [comment]
@anorak94 where you able to get a feasible solution for this ?

**Comment by anorak94** [comment]
Im not an expert on this but maybe something like optimal transport
