### ISSUE TITLE
NOT LINKED pick-up and delivery problem

### ISSUE THREAD

**Issue by idimitriou** [google/or-tools#1971]
Hello,

so far I have seen a lot of work for the simple pickup or a more complex pickup and delivery problem. However, I still haven't seen a solution for the following problem: both pickups and deliveries must be executed but the deliveries and pick-ups are not linked to each other, they are separate orders. Without the pick-up you can still do the delivery.

I tried to solve such a problem by using negative values for the delivery quantities and positive values for the pick-up quantities  in the demands table. However, I quickly realized that I need to know beforehand the initial load that is impossible. 

Any thoughts on that?

**Comment by Mizux** [comment]
Please use the mailing list instead !
