### ISSUE TITLE
Compilation failure ARM64 Raspberry PI using Docker

### ISSUE THREAD

**Issue by andyyardley** [google/or-tools#1973]
**What version of OR-tools and what language are you using?**
Version: Stable

**What operating system (Linux, Windows, ...) and version?**
Raspian

**What did you do?**
I tried building from source using the following docker file direct on the ARM64 PI3. This docker file works correctly on x86-64 MacOS.

`FROM python

RUN apt-get update

RUN apt-get -y install git autoconf libtool zlib1g-dev gawk g++ curl cmake subversion make lsb-release swig python-dev python-setuptools python-six gfortran

WORKDIR /usr/lib/python2.7

RUN git clone --recurse-submodules https://github.com/google/or-tools.git

WORKDIR /usr/lib/python2.7/or-tools

RUN make third_party > /root/make_third_party.txt
RUN make python
RUN pip install six
RUN make test_python`

**Compilation failed with the following error**
`g++ -fPIC -std=c++11 -fwrapv -O4 -DNDEBUG -I. -Iortools/gen -I/usr/lib/python2.7/or-tools/dependencies/install/include -I/usr/lib/python2.7/or-tools/dependencies/install/include -I/usr/lib/python2.7/or-tools/dependencies/install/include -I/usr/lib/python2.7/or-tools/dependencies/install/include -I/usr/lib/python2.7/or-tools/dependencies/install/include/coin -I/usr/lib/python2.7/or-tools/dependencies/install/include -I/usr/lib/python2.7/or-tools/dependencies/install/include/coin -I/usr/lib/python2.7/or-tools/dependencies/install/include -I/usr/lib/python2.7/or-tools/dependencies/install/include/coin -DUSE_CLP -I/usr/lib/python2.7/or-tools/dependencies/install/include -I/usr/lib/python2.7/or-tools/dependencies/install/include/coin -I/usr/lib/python2.7/or-tools/dependencies/install/include -I/usr/lib/python2.7/or-tools/dependencies/install/include/coin -DUSE_CBC -Wno-deprecated -DUSE_GLOP -DUSE_BOP     -DOR_TOOLS_MAJOR=7 -DOR_TOOLS_MINOR=6 -I/usr/local/include/python3.8 -I/usr/local/lib/python3.8  -I/usr/local/include/python3.8 -DPY3 \
 -c ortools/gen/ortools/algorithms/knapsack_solver_python_wrap.cc \
 -o objs/swig/knapsack_solver_python_wrap.o
ortools/gen/ortools/algorithms/knapsack_solver_python_wrap.cc:3151:3: error: #error "SWIG wrapped code invalid in 32 bit architecture, regenerate code using -DSWIGWORDSIZE32"
 # error "SWIG wrapped code invalid in 32 bit architecture, regenerate code using -DSWIGWORDSIZE32"
   ^~~~~
In file included from ortools/gen/ortools/algorithms/knapsack_solver_python_wrap.cc:3165:
./ortools/base/python-swig.h: In function ‘bool PyObjAs(PyObject*, T*)’:
./ortools/base/python-swig.h:59:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
./ortools/base/python-swig.h: In function ‘PyObject* PyObjFrom(const T&)’:
./ortools/base/python-swig.h:63:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
make: *** [makefiles/Makefile.python.mk:148: objs/swig/knapsack_solver_python_wrap.o] Error 1`

**Comment by lperron** [comment]
arm is not officially supported. and 32 bit compilation is for sure not working.

**Comment by andyyardley** [comment]
Cool, I'll switch to a 64bit kernel and try again, thanks.

**Comment by Mizux** [comment]
note: python2 is not anymore supported either...
