### ISSUE TITLE
cmake compilation fail

### ISSUE THREAD

**Issue by pboerr** [google/or-tools#1974]
**What version of OR-tools and what language are you using?**
Version: tried both stable and master.
Language: C++
**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Trying to use linear solver
**What operating system (Linux, Windows, ...) and version?**
macos 10.15.4
**What did you do?**
1. I copied and pasted the recommended cmake https://github.com/google/or-tools/blob/stable/cmake/README.md#using-fetchcontent into my project's CMakeLists.txt
2. After than I run from terminal: cmake -DBUILD_DEPS=ON .
3. Finally, cmake --build . --config Debug
 
**What did you expect to see**
I expect to be able to compile my project with OR tools.

**What did you see instead?**
Compilation fails bacause an undefined symbol absl::lts_2020_02_25::numbers_internal...
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/7889879/80288930-b5a67400-8711-11ea-8fd8-2201cb150735.png">

**Anything else we should know about your project / environment**
Is a simple c++ project

**Comment by Mizux** [comment]
Please note CMake build is still experimental.

I'll try to take a look at this OR-Tools FetchContent consumption issue.

**Comment by Mizux** [comment]
Should be fixed on master now (lots of stuff concerning dependencies management last week), please ask for reopen if you still see it !
