### ISSUE TITLE
Driver schedules for vehicles in CVRPTW

### ISSUE THREAD

**Issue by sreyas7** [google/or-tools#1976]
I am trying to create a similar CVRPTW where I am allowing the vehicle to travel for multiple days and one of the constraints is that the vehicle can only travel for a duration of 'max working hours' for each day.
I am trying to implement the same approach that @Mizux had suggested in issue #1202 but somehow I am still unable to get it.
I did the following change to overcome the exact same error that @calatian had encountered but something seems to be wrong which leads to an infeasible solution.

![Github_Issue](https://user-images.githubusercontent.com/32644395/80302158-f790f200-87c5-11ea-946a-eb3f9fb9bad2.png)

The vehicle is only allowed to travel between 7 AM to 7 PM every day.
I am giving it a service time of 10 minutes for each location.

**Can you show what change did you suggest? @Mizux**

Thanks.

**Comment by lperron** [comment]
Please use the mailing list.

**Comment by sreyas7** [comment]
> I am trying to create a similar CVRPTW where I am allowing the vehicle to travel for multiple days and one of the constraints is that the vehicle can only travel for a duration of 'max working hours' for each day.
> I am trying to implement the same approach that @Mizux had suggested in issue #1202 but somehow I am still unable to get it.
> I did the following change to overcome the exact same error that @calatian had encountered but something seems to be wrong which leads to an infeasible solution.
> 
> ![Github_Issue](https://user-images.githubusercontent.com/32644395/80302158-f790f200-87c5-11ea-946a-eb3f9fb9bad2.png)
> 
> The vehicle is only allowed to travel between 7 AM to 7 PM every day.
> I am giving it a service time of 10 minutes for each location.
> 
> **Can you show what change did you suggest? @Mizux**
> 
> Thanks.

I found a workaround for this. Instead of adding all the break intervals to the brake intervals list, I added all the breaks in the driver intervals list and then added then as separate brake intervals.
