### ISSUE TITLE
OR-Tools 7.6 build fails with SCIP enabled - ortools/linear_solver/scip_callback.h file missing

### ISSUE THREAD

**Issue by ogunheper** [google/or-tools#1978]
**What version of OR-tools and what language are you using?**
Version: v7.6
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
SCIP

**What operating system (Linux, Windows, ...) and version?**
macOS

**What did you do?**
Trying to build OR-Tools from source with SCIP enabled on macOS.

**What did you expect to see**
I expect the build to be completed without an error.

**What did you see instead?**
clang++ -fPIC -std=c++11  -mmacosx-version-min=10.9 -stdlib=libc++ -O4 -DNDEBUG -I. -Iortools/gen -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include/coin -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include/coin -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include/coin -DUSE_CLP -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include/coin -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include/coin -DUSE_CBC -Wno-deprecated -DUSE_GLOP -DUSE_BOP -I/usr/local/glpk-4.65/include -DUSE_GLPK -I/usr/local/scipoptsuite-6.0.2/include -DUSE_SCIP -DNO_CONFIG_HEADER -I/Library/gurobi902/mac64/include -DUSE_GUROBI  -DOR_TOOLS_MAJOR=7 -DOR_TOOLS_MINOR=6 -c ./ortools/linear_solver/scip_interface.cc -o objs/linear_solver/scip_interface.o
./ortools/linear_solver/scip_interface.cc:37:10: fatal error: 'ortools/linear_solver/scip_callback.h' file not found
#include "ortools/linear_solver/scip_callback.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [objs/linear_solver/scip_interface.o] Error 1

**Anything else we should know about your project / environment**
The same build from source scripts with SCIP were running perfectly for 7.5

It seems that a file (ortools/linear_solver/scip_callback.h) is missing in the v7.6 branch. It's also missing in the master branch. It might not been added during commits.

Best regards,
Ogün

**Comment by lperron** [comment]
Thanks. We will fix it.

**Comment by lperron** [comment]
I have pushed some fixes on master. Can you test it ?

**Comment by ogunheper** [comment]
Checked out master and retried a clean build. I got the following errors;

`
clang++ -fPIC -std=c++11  -mmacosx-version-min=10.9 -stdlib=libc++ -O4 -DNDEBUG -I. -Iortools/gen -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include/coin -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include/coin -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include/coin -DUSE_CLP -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include/coin -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include/coin -DUSE_CBC -Wno-deprecated -DUSE_GLOP -DUSE_BOP -I/usr/local/glpk-4.65/include -DUSE_GLPK -I/usr/local/scipoptsuite-6.0.2/include -DUSE_SCIP -DNO_CONFIG_HEADER -I/Library/gurobi902/mac64/include -DUSE_GUROBI  -DOR_TOOLS_MAJOR=7 -DOR_TOOLS_MINOR=6 -c ./ortools/linear_solver/scip_interface.cc -o objs/linear_solver/scip_interface.o
./ortools/linear_solver/scip_interface.cc:180:3: error: use of undeclared identifier 'scip_constraint_handler_'
  scip_constraint_handler_.reset();
  ^
./ortools/linear_solver/scip_interface.cc:391:5: error: use of undeclared identifier 'branching_priority_reset_'
    branching_priority_reset_ = true;
    ^
2 errors generated.
make: *** [objs/linear_solver/scip_interface.o] Error 1
`

Best regards,
Ogün

**Comment by lperron** [comment]
I have fixed the code on master.
It targets scip 7.0.

**Comment by ogunheper** [comment]
You had mentioned targeting 7.0. Is SCIP 6.0.2 still supported or not?

Thanks,
Ogün

**Comment by lperron** [comment]
they are not compatible. I had to remove the lpfeastol parameter.
The code should compile though.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by pqant** [comment]
@lperron it's still giving an error while compiling.

**I tested both on master and v7.6 branches.no way.it's not compiling. on v7.6 the message was the same as @ogunheper 's compiling error. The error message that I encountered while I'm trying to compile on master branch is below.**


What version of OR-tools and what language are you using?
Version: v7.6
Language: C++

Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)
SCIP v7.0.0

What operating system (Linux, Windows, ...) and version?
macOS 10.15.3 

What did you do?
Steps to reproduce the behavior:
Trying to build OR-Tools from source with SCIP v7.0.0 enabled on macOS 10.15.3 .

What did you expect to see
I expect the build to be completed without an error.

What did you see instead?

ON master branch : 

`clang++ -fPIC -std=c++11  -mmacosx-version-min=10.9 -stdlib=libc++ -O4 -DNDEBUG -I. -Iortools/gen -I/Users/eralp/work/src/unisyslabs/endurance/or-tools/dependencies/install/include -I/Users/eralp/work/src/unisyslabs/endurance/or-tools/dependencies/install/include -I/Users/eralp/work/src/unisyslabs/endurance/or-tools/dependencies/install/include -I/Users/eralp/work/src/unisyslabs/endurance/or-tools/dependencies/install/include -I/Users/eralp/work/src/unisyslabs/endurance/or-tools/dependencies/install/include/coin -I/Users/eralp/work/src/unisyslabs/endurance/or-tools/dependencies/install/include -I/Users/eralp/work/src/unisyslabs/endurance/or-tools/dependencies/install/include/coin -I/Users/eralp/work/src/unisyslabs/endurance/or-tools/dependencies/install/include -I/Users/eralp/work/src/unisyslabs/endurance/or-tools/dependencies/install/include/coin -DUSE_CLP -I/Users/eralp/work/src/unisyslabs/endurance/or-tools/dependencies/install/include -I/Users/eralp/work/src/unisyslabs/endurance/or-tools/dependencies/install/include/coin -I/Users/eralp/work/src/unisyslabs/endurance/or-tools/dependencies/install/include -I/Users/eralp/work/src/unisyslabs/endurance/or-tools/dependencies/install/include/coin -DUSE_CBC -Wno-deprecated -DUSE_GLOP -DUSE_BOP  -I/Users/eralp/work/src/unisyslabs/scip7/install/dir/include -DUSE_SCIP -DNO_CONFIG_HEADER   -DOR_TOOLS_MAJOR=7 -DOR_TOOLS_MINOR=7 -c ./ortools/linear_solver/scip_interface.cc -o objs/linear_solver/scip_interface.o
In file included from ./ortools/linear_solver/scip_interface.cc:35:
./ortools/linear_solver/scip_helper_macros.h:33:10: error: use of undeclared identifier 'util'
  return util::InvalidArgumentError(
         ^
In file included from ./ortools/linear_solver/scip_interface.cc:36:
./ortools/linear_solver/scip_proto_solver.h:23:1: error: use of undeclared identifier 'util'
util::Status ScipSetSolverSpecificParameters(const std::string& parameters,
^
./ortools/linear_solver/scip_interface.cc:740:40: error: no member named 'ValueOrDie' in 'absl::StatusOr<operations_research::MPSolutionResponse>'
  if (status_or.ok()) return status_or.ValueOrDie();
                             ~~~~~~~~~ ^
./ortools/linear_solver/scip_interface.cc:743:7: error: use of undeclared identifier 'util'
  if (util::IsUnimplemented(status_or.status())) return absl::nullopt;
      ^
./ortools/linear_solver/scip_interface.cc:892:15: error: use of undeclared identifier 'util'
    status_ = util::InvalidArgumentError(absl::StrFormat(
              ^
./ortools/linear_solver/scip_interface.cc:901:15: error: use of undeclared identifier 'util'
    status_ = util::InvalidArgumentError(absl::StrFormat(
              ^
./ortools/linear_solver/scip_interface.cc:912:10: error: use of undeclared identifier 'util'
  return util::InternalError(
         ^
7 errors generated.`

Thanks 
Eralp

**Comment by pqant** [comment]
@ogunheper  **Were you able to compile the master branch targeting SCIP v.7.0.0 without any problem?**

Thanks,
Eralp

**Comment by lperron** [comment]
I just pushed the fix on master.

Please try again.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 19 mai 2020 à 14:53, Dr.Emmet Brown <notifications@github.com> a
écrit :

**Comment by pqant** [comment]
Hi @lperron

I've tried to compile but unfortunately, the result was the same. 

Could you control it again?

**Comment by lperron** [comment]
I just pushed 2 fixes.
I compiled with scip locally on my machine.

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 19 mai 2020 à 15:49, Dr.Emmet Brown <notifications@github.com> a
écrit :

**Comment by pqant** [comment]
Thank you @lperron 

it's working like a charm. 

Best regards,
Eralp
