### ISSUE TITLE
OR-Tools 7.6 build fails with Gurobi enabled - use of undeclared identifier 'gtl'

### ISSUE THREAD

**Issue by ogunheper** [google/or-tools#1979]
**What version of OR-tools and what language are you using?**
Version: v7.6
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Gurobi

**What operating system (Linux, Windows, ...) and version?**
macOS

**What did you do?**
Trying to build OR-Tools from source with Gurobi enabled on macOS.

**What did you expect to see**
I expect the build to be completed without an error.

**What did you see instead?**
clang++ -fPIC -std=c++11  -mmacosx-version-min=10.9 -stdlib=libc++ -O4 -DNDEBUG -I. -Iortools/gen -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include/coin -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include/coin -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include/coin -DUSE_CLP -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include/coin -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include -I/Users/ogun.heper/Downloads/or-tools/or-tools/dependencies/install/include/coin -DUSE_CBC -Wno-deprecated -DUSE_GLOP -DUSE_BOP -I/usr/local/glpk-4.65/include -DUSE_GLPK -I/usr/local/scipoptsuite-6.0.2/include -DUSE_SCIP -DNO_CONFIG_HEADER -I/Library/gurobi902/mac64/include -DUSE_GUROBI  -DOR_TOOLS_MAJOR=7 -DOR_TOOLS_MINOR=6 -c ./ortools/linear_solver/gurobi_proto_solver.cc -o objs/linear_solver/gurobi_proto_solver.o
./ortools/linear_solver/gurobi_proto_solver.cc:277:25: error: use of undeclared identifier 'gtl'
  auto gurobi_deleter = gtl::MakeCleanup([delete_gurobi_objects]() {
                        ^
1 error generated.
make: *** [objs/linear_solver/gurobi_proto_solver.o] Error 1

**Anything else we should know about your project / environment**
The same build from source scripts with Gurobi were running perfectly for 7.5

It seems that the namespace for MakeCleanup is mistakenly used as gtl instead of absl

Best regards,
Ogün

**Comment by lperron** [comment]
Sorry, absl changes a bit to fast for me :-)

**Comment by ogunheper** [comment]
Is it possible to create a 7.6.1 release including the fix for #1978 ?

We can not use SCIP and/or Gurobi on v7.6

Best regards,
Ogün

**Comment by lperron** [comment]
just grab on master.
We will do a 7.7 in May.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by ogunheper** [comment]
Thanks @lperron, will do so.

Best regards,
Ogün
