### ISSUE TITLE
Java binary compilation instruction is incorrect.

### ISSUE THREAD

**Issue by cemkoc** [google/or-tools#198]
Hi,
I noticed that after installing the java binary the instructions present both on the README and on the web page to compile the example class is wrong. When compiling it should also include the lib/protobuf.jar in the classpath but currently this is missing hence it is causing some headaches when getting started. Correct command to compile should be like this:

`javac -d objs -cp lib/com.google.ortools.jar:lib/protobuf.jar \ examples/com/google/ortools/samples/RabbitsPheasants.java`

**Comment by dlahlou** [comment]
Hello cemKoc,
Thank you for your remark. We updated the README with the right command.
Regards.
