### ISSUE TITLE
Check failed: postsolve_response.status()

### ISSUE THREAD

**Issue by RobertAditazz** [google/or-tools#1981]
Hello,

I am running the latest stable or-tools (7.6) using this command:
```sh
fzn-or-tools  -num_solutions=0 -all_solutions=true -threads=8 -time_limit=1800 -params="cp_model_probing_level:0"  input.fzn
```
And after about 20 minutes, I encountered this error.  What does it mean?

Thanks,
Robert

--------------------------------------
[input.zip](https://github.com/google/or-tools/files/4536721/input.zip)

```
Check failed: postsolve_response.status() == CpSolverStatus::FEASIBLE || postsolve_response.status() == CpSolverStatus::OPTIMAL 
*** Check failure stack trace: ***
    @     0x145fac3dccf4  google::LogMessage::Fail()
    @     0x145fac3dcc38  google::LogMessage::SendToLog()
    @     0x145fac3dc574  google::LogMessage::Flush()
    @     0x145fac3e009b  google::LogMessageFatal::~LogMessageFatal()
    @     0x145faa66fb64  operations_research::sat::(anonymous namespace)::PostsolveResponse()
    @     0x145faa6707bc  _ZZN19operations_research3sat12_GLOBAL__N_19LnsSolver12GenerateTaskElENKUlvE_clEv
    @     0x145faa77e91c  _ZNSt17_Function_handlerIFvvEZN19operations_research3sat20NonDeterministicLoopERKSt6vectorISt10unique_ptrINS2_9SubSolverESt14default_deleteIS5_EESaIS8_EEiEUlvE_E9_M_invokeERKSt9_Any_data
    @     0x145faa48141f  operations_research::RunWorker()
    @     0x145fabedfc80  (unknown)
    @     0x145fac1b06ba  start_thread
    @     0x145fab94e41d  clone
    @              (nil)  (unknown)
```

**Comment by lperron** [comment]
something we

**Comment by lperron** [comment]
Hi, 

I can confirm the bug.
Is there a way you can reduce the size of the model and still exhibit the bug ?

Thanks

**Comment by RobertAditazz** [comment]
Hello,
I don't have a way to do that, unfortunately.  This error came about as I added
more and more constraints to the model and I am not sure which combination of
constraints caused the error.
-Robert

**Comment by peerjuettner** [comment]
Hi,
I also have the same issue, running OR-Tools 7.6. The following error shows after a few seconds:
`Check failed: postsolve_response.status() == CpSolverStatus::FEASIBLE || postsolve_response.status() == CpSolverStatus::OPTIMAL 
*** Check failure stack trace: ***
    @     0x7f163c09725a  google::LogMessage::Fail()
    @     0x7f163c097195  google::LogMessage::SendToLog()
    @     0x7f163c096ac6  google::LogMessage::Flush()
    @     0x7f163c09a546  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f1606e255df  operations_research::sat::(anonymous namespace)::PostsolveResponse()
    @     0x7f1606e256e9  _ZNSt17_Function_handlerIFvPN19operations_research3sat16CpSolverResponseEEZNS1_12SolveCpModelERKNS1_12CpModelProtoEPNS1_5ModelEEUlS3_E0_E9_M_invokeERKSt9_Any_dataOS3_
    @     0x7f1606e23156  _ZZN19operations_research3sat12SolveCpModelERKNS0_12CpModelProtoEPNS0_5ModelEENKUlRKNS0_16CpSolverResponseEE2_clES8_
    @     0x7f1606f5d085  operations_research::sat::SharedResponseManager::NewSolution()
    @     0x7f1606e24b22  _ZNSt17_Function_handlerIFvvEZN19operations_research3sat12_GLOBAL__N_118SolveLoadedCpModelERKNS2_12CpModelProtoEPNS2_21SharedResponseManagerEPNS2_5ModelEEUlvE_E9_M_invokeERKSt9_Any_data
    @     0x7f1606ef2411  operations_research::sat::MinimizeIntegerVariableWithLinearScanAndLazyEncoding()
    @     0x7f1606e23b9f  operations_research::sat::(anonymous namespace)::SolveLoadedCpModel()
    @     0x7f1606e2a895  operations_research::sat::SolveCpModel()
    @     0x7f1607d8f0db  operations_research::sat::SatHelper::SolveWithParametersAndSolutionCallback()
    @     0x7f1607d8df70  Java_com_google_ortools_sat_mainJNI_SatHelper_1solveWithParametersAndSolutionCallback
    @     0x7f165491f950  (unknown)`

I do not want to make the source code public, however, I can assist if there are questions about the model etc.

**Comment by lperron** [comment]
can you try using master ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 11 mai 2020 à 11:10, Peer Jüttner <notifications@github.com> a
écrit :

**Comment by peerjuettner** [comment]
I've tried, but get this error after copying the files to /usr/java/packages/lib:

> Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/java/packages/lib/libjniortools.so: /usr/java/packages/lib/libglog.so.0: file too short
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2649)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
	at java.base/java.lang.System.loadLibrary(System.java:1870)
	at ---.---.---.Solver.<clinit>(Solver.java:34)
	at ---.---.---.cpsolver.Program.main(Program.java:9)

**Comment by peerjuettner** [comment]
Hi, I tried again today with a master build. I was sucessful in building this time. However, I now get the following message when running my model:

> Check failed: SolutionIsFeasible(model_proto, std::vector<int64>(response->solution().begin(), response->solution().end()), &mapping_proto, &postsolve_mapping) final postsolved solution
*** Check failure stack trace: ***
    @     0x7f3cc4185862  google::LogMessage::Fail()
    @     0x7f3cc41857ad  google::LogMessage::SendToLog()
    @     0x7f3cc41850ea  google::LogMessage::Flush()
    @     0x7f3cc41889b2  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f3c86bb20f4  _ZNSt17_Function_handlerIFvPN19operations_research3sat16CpSolverResponseEEZNS1_12SolveCpModelERKNS1_12CpModelProtoEPNS1_5ModelEEUlS3_E0_E9_M_invokeERKSt9_Any_dataOS3_
    @     0x7f3c86bad866  _ZZN19operations_research3sat12SolveCpModelERKNS0_12CpModelProtoEPNS0_5ModelEENKUlRKNS0_16CpSolverResponseEE2_clES8_
    @     0x7f3c86d01fc5  operations_research::sat::SharedResponseManager::NewSolution()
    @     0x7f3c86baf0be  _ZNSt17_Function_handlerIFvvEZN19operations_research3sat12_GLOBAL__N_118SolveLoadedCpModelERKNS2_12CpModelProtoEPNS2_21SharedResponseManagerEPNS2_5ModelEEUlvE_E9_M_invokeERKSt9_Any_data
    @     0x7f3c86c83f89  operations_research::sat::MinimizeIntegerVariableWithLinearScanAndLazyEncoding()
    @     0x7f3c86bae18f  operations_research::sat::(anonymous namespace)::SolveLoadedCpModel()
    @     0x7f3c86bb42af  operations_research::sat::SolveCpModel()
    @     0x7f3cc4304ec1  operations_research::sat::SatHelper::SolveWithParametersAndSolutionCallback()
    @     0x7f3cc4303dc5  Java_com_google_ortools_sat_mainJNI_SatHelper_1solveWithParametersAndSolutionCallback
    @     0x7f3cdc91f950  (unknown)

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by lperron** [comment]
Can you send us the model ?

Le lun. 25 mai 2020 à 10:06, Peer Jüttner <notifications@github.com> a
écrit :

**Comment by peerjuettner** [comment]
@lperron Here is the model code: https://drive.google.com/open?id=1LoLSHORZc-2N31xEO37Ugt1M7HQvkwVx
The offending constraint is added on lines 286/287. In the code they are currently commented out. Without those lines the model works fine.

Does this help?

**Comment by lperron** [comment]
I cannot run the model as I miss most of the import.
Just before solving, can you write the model to file
(model.build().toString()) and send it to me (by PM).


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 26 mai 2020 à 20:53, Peer Jüttner <notifications@github.com> a
écrit :

**Comment by peerjuettner** [comment]
I'm unaware as to how to send a pm over github, so I will add the link directly here. 
I have uploaded both models, the "working" version is the one with the offending constraint commented out / not added to the obj. The other one is the broken one where the constraint is added to the obj. Let me know if you need anything else.

https://drive.google.com/open?id=1_cXmqSGPgtYlw_dD0q_j-0sWC0Se2rpS

**Comment by lperron** [comment]
I re-ran the broken model on master.
Went fine.  Still improving solutions after 15mn. But working fine.

I will close the issue. Thanks for the report. Please reopen if it still does not work on 8.0 (coming soon).
