### ISSUE TITLE
OR-Tools v7.6 with CP-SAT solver failed even with sample code

### ISSUE THREAD

**Issue by whoknowsname** [google/or-tools#1982]
**What version of OR-tools and what language are you using?**
Version:  v7.6.7691
Language: Python 3.7.1

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows10

**What did you do?**
Try to solve an employee scheduling problem with CP-SAT solver

**What did you expect to see**
No error
**What did you see instead?**
PS G:\employee_scheduling> python -u "g:\employee_scheduling\test.py"
Traceback (most recent call last):
  File "g:\employee_scheduling\test.py", line 2, in <module>
    from ortools.sat.python import cp_model
  File "G:\Python\lib\site-packages\ortools\sat\python\cp_model.py", line 59, in <module>
    from ortools.sat import pywrapsat
  File "G:\Python\lib\site-packages\ortools\sat\pywrapsat.py", line 13, in <module>
    from . import _pywrapsat
ImportError: DLL load failed: The specified module could not be found（找不到指定的模块。）

Even with the sample code on
https://developers.google.com/optimization/scheduling/employee_scheduling
**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
have you installed visual studio 2019 redistributables.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 27 avr. 2020 à 15:46, whoknowsname <notifications@github.com> a
écrit :

**Comment by whoknowsname** [comment]
i operate the sample code in visual studio code
and where can i download visual studio 2019 redistributables?

**Comment by whoknowsname** [comment]
i operate the sample code in visual studio code
and where can i download visual studio 2019 redistributables?

**Comment by lperron** [comment]
search 'visual studio 2019 redistributables', this is the first link :-)
