### ISSUE TITLE
How to search the next solution after StopSearch() ?

### ISSUE THREAD

**Issue by ejad9** [google/or-tools#1985]
Hello,

In the scheduling problem, I would like to allow the user to look for the next solution as many time as he wants without solving all the problem (that can take too much time)

For the moment I use SearchForAllSolutions() with a StopSearch() limit in the solution_printer.
That works properly but I met the fowolling problems :
- the solver potentially run longer than needed (if the first solution was fine for example)
- if the user want to look further than the solution limit, he is forced to run the program a 2nd time from 0 with a higher solution limit, which is not great.

Is it possible to resume a search after calling StopSearch() without beggining the search from 0 ?
Or is it possible to use Solve() as many time as wanted ?

Thanks a lot for any help.

NB : I'm working with python 3.7 and ortools 7.4.7247 (higher versions doesn't install properly with windows10)

**Comment by lperron** [comment]
You can't.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by ejad9** [comment]
Thank for this rapid answer.
And is it possible to search the next solution after Solve() ?

Or is the SearchForAllSolutions() with a StopSearch() limit the only way to look for next solution ?

**Comment by stradivari96** [comment]
This isn't really a OR-Tools question, but you could block the callback with something like:
```python
next_solution = input("Continue? (y/n):")
if next_solution != "y":
    self.StopSearch()
```
Or some multithreading thingy

**Comment by ejad9** [comment]
I'll try that, thanks for your answers
