### ISSUE TITLE
Vehicle Pickup and Delivery Program for C#

### ISSUE THREAD

**Issue by rajatjangir** [google/or-tools#199]
Hi everyone,
First of all thanks for such a great library.

I've been using this library for my research project for quite some time. Though i am still in the learning phase.

My aim is to develop a Vehicle Routing Problem with Pickup and Delivery Constraints also i would like to learn how to add or remove constraints but my c++ is not very sharp though i can understand c# quite well.

I've gone through the CSVRPTW example written in c# but i was not able to modify much in that and also while debugging i was not able to get inside the code in many functions , i assume because of the SWIG wrapper being used.

I'am in dire need for help as summers are about to end i have to complete my project. If anyone could help me in understanding how to add constraints or any example which has datasets or a file so that i can visualize the data and hence modify it.

Thanks in advance!!

**Comment by orwant** [comment]
There's a Python example of adding capacity and time constraints newly
documented here:
https://developers.google.com/optimization/routing/tsp/vehicle_routing_time_windows

The same approach will work in C#.

Jon
