### ISSUE TITLE
Cannot compile Googe OR-Tools from source

### ISSUE THREAD

**Issue by muisklik** [google/or-tools#1990]
Environment Visual Studio 2019 16.5.4 with x64 Native Tools Command Prompt, CMake 3.17.2 x86

When I run the command tools\male third_party I get the error message:
C:\or-tools\dependencies\sources\zlib-1.2.11\zconf.h(247): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64\cl.EXE"' : return code '0x2'

The file stddef.h exists in C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\lib\clang\9.0.0\include. 

Adding the path to the environment variable INCLUDE give new errors:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\lib\clang\9.0.0\include\stddef.h(18): warning C4067: unexpected tokens following preprocessor directive - expected a newline
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\lib\clang\9.0.0\include\stddef.h(30): warning C4067: unexpected tokens following preprocessor directive - expected a newline
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\lib\clang\9.0.0\include\stddef.h(32): warning C4067: unexpected tokens following preprocessor directive - expected a newline
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\lib\clang\9.0.0\include\stddef.h(35): error C2061: syntax error: identifier 'ptrdiff_t'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\lib\clang\9.0.0\include\stddef.h(35): error C2059: syntax error: ';'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\lib\clang\9.0.0\include\stddef.h(41): warning C4067: unexpected tokens following preprocessor directive - expected a newline
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\lib\clang\9.0.0\include\stddef.h(43): warning C4067: unexpected tokens following preprocessor directive - expected a newline
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\lib\clang\9.0.0\include\stddef.h(46): error C2054: expected '(' to follow '__SIZE_TYPE__'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\lib\clang\9.0.0\include\stddef.h(55): warning C4067: unexpected tokens following preprocessor directive - expected a newline
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\lib\clang\9.0.0\include\stddef.h(67): warning C4067: unexpected tokens following preprocessor directive - expected a newline
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\lib\clang\9.0.0\include\stddef.h(68): warning C4067: unexpected tokens following preprocessor directive - expected a newline
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\lib\clang\9.0.0\include\stddef.h(74): error C2085: '__WCHAR_TYPE__': not in formal parameter list
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\lib\clang\9.0.0\include\stddef.h(74): error C2146: syntax error: missing ',' before identifier 'wchar_t'
C:\or-tools\dependencies\sources\zlib-1.2.11\zconf.h(248): error C2085: 'z_size_t': not in formal parameter list
C:\or-tools\dependencies\sources\zlib-1.2.11\zconf.h(391): error C2085: 'Byte': not in formal parameter list
C:\or-tools\dependencies\sources\zlib-1.2.11\zconf.h(393): error C2085: 'uInt': not in formal parameter list
C:\or-tools\dependencies\sources\zlib-1.2.11\zconf.h(394): error C2085: 'uLong': not in formal parameter list
C:\or-tools\dependencies\sources\zlib-1.2.11\zconf.h(400): error C2085: 'Byte': not in formal parameter list
C:\or-tools\dependencies\sources\zlib-1.2.11\zconf.h(400): error C2146: syntax error: missing ',' before identifier 'Bytef'
C:\or-tools\dependencies\sources\zlib-1.2.11\zconf.h(402): error C2085: 'charf': not in formal parameter list
C:\or-tools\dependencies\sources\zlib-1.2.11\zconf.h(403): error C2085: 'intf': not in formal parameter list
C:\or-tools\dependencies\sources\zlib-1.2.11\zconf.h(404): error C2085: 'uInt': not in formal parameter list
C:\or-tools\dependencies\sources\zlib-1.2.11\zconf.h(404): error C2146: syntax error: missing ',' before identifier 'uIntf'
C:\or-tools\dependencies\sources\zlib-1.2.11\zconf.h(405): error C2085: 'uLong': not in formal parameter list
C:\or-tools\dependencies\sources\zlib-1.2.11\zconf.h(405): error C2146: syntax error: missing ',' before identifier 'uLongf'
C:\or-tools\dependencies\sources\zlib-1.2.11\zconf.h(408): error C2085: 'voidpc': not in formal parameter list
C:\or-tools\dependencies\sources\zlib-1.2.11\zconf.h(409): error C2085: 'voidpf': not in formal parameter list
C:\or-tools\dependencies\sources\zlib-1.2.11\zconf.h(410): error C2085: 'voidp': not in formal parameter list
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vadefs.h(15): warning C4079: unexpected token 'string'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vadefs.h(15): warning C4081: expected 'newline'; found ')'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vadefs.h(48): warning C4081: expected ')'; found 'string'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vadefs.h(61): error C2085: 'uintptr_t': not in formal parameter list
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vadefs.h(72): error C2085: 'va_list': not in formal parameter list
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vadefs.h(145): error C2143: syntax error: missing ')' before '*'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vadefs.h(145): error C2082: redefinition of formal parameter '__va_start'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vadefs.h(145): error C2143: syntax error: missing ';' before '*'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vadefs.h(145): error C2059: syntax error: ')'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vadefs.h(198): warning C4161: #pragma pack(pop...): more pops than pushes
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vcruntime.h(344): error C2146: syntax error: missing ')' before identifier '_StackCookie'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vcruntime.h(344): error C2061: syntax error: identifier '_StackCookie'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vcruntime.h(344): error C2059: syntax error: ';'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vcruntime.h(344): error C2059: syntax error: ')'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vcruntime.h(345): error C2146: syntax error: missing ')' before identifier '_StackCookie'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vcruntime.h(345): error C2061: syntax error: identifier '_StackCookie'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vcruntime.h(345): error C2059: syntax error: ';'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vcruntime.h(345): error C2059: syntax error: ')'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vcruntime.h(349): error C2061: syntax error: identifier '__security_cookie'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\vcruntime.h(349): error C2059: syntax error: ';'
C:\or-tools\dependencies\sources\zlib-1.2.11\zconf.h(444): fatal error C1083: Cannot open include file: 'sys/types.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64\cl.EXE"' : return code '0x2'
Stop.
tools\make: *** [dependencies/install/lib/zlib.lib] Error 2

Please help!

**Comment by Mizux** [comment]
strange the native developper command prompt should setup correctly the environment so `stddef.h` etc will be found.

When you start the cmd prompt what do you see ? (you should see some log that VC 2019 is setup etc...)

**Comment by muisklik** [comment]
No need to compile from source code anymore since building software using the NUPKG works again.
