### ISSUE TITLE
AddDimensionWithVehicleTransits giving inconsistent CumulVar values

### ISSUE THREAD

**Issue by MoosaSaadat** [google/or-tools#1992]
**What version of OR-tools and what language are you using?**
Version: 7.5.7466
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
I am using the CVRPTW example. I have a heterogeneous fleet of vehicles (different speeds) so I am using **AddDimensionWithVehicleTransits**. I am setting the Dimesion like this:

```python
# Create callback fns for total time
tot_time_callbacks = []
tot_time_callback_indices = []
for veh in vehicles.vehicles:
    tot_time_callbacks.append(customers.make_tot_time_callback(veh.speed))
    tot_time_callback_indices.append(
        routing.RegisterTransitCallback(tot_time_callbacks[-1])
    )
# Add a dimension for time and a limit on the total time_horizon
routing.AddDimensionWithVehicleTransits(
    tot_time_callback_indices,  # total time function callbacks
    customers.time_horizon,
    customers.time_horizon,
    True,
    "Time",
)
```
Callback Function:
```python
def make_tot_time_callback(self, speed_kmph):
    """
    Creates a callback function for total time. Assuming an average
    speed of speed_kmph
    Args:   speed_kmph: the average speed in km/h
    Returns:
        function [transit_time_return(a, b)]: A function that takes the
            from/a node index and the to/b node index and returns the
            total (in seconds) time from a to b.
    """

    def tot_time_return(from_index, to_index):
        # Convert from routing variable Index to distance matrix NodeIndex.
        from_node = self.manager.IndexToNode(from_index)
        to_node = self.manager.IndexToNode(to_index)
        # Calculate transit time and service time
        transit_time = self.distmat[from_node][to_node] / (speed_kmph / 3600)
        service_time = (
            abs(self.customers[from_node].demand) * self.service_time_per_dem
        )

        return int(transit_time + service_time)

    return tot_time_return

```

**What did you expect to see**
In my case, I have 2 vehicles for a total of 20 deliveries. Correct times for them are:
```
Time Taken: 5:28:50
Time Taken: 5:06:30
```

**What did you see instead?**
When, I run the code I mostly get the right results. But, every once in a while (1 to 2 times per 10 runs), I get wrong results for the **first vehicle only**. Second vehicle always has the same time which is correct. But, the first one shows wrong results some times.

**Anything else we should know about your project / environment**
I am using the CVRPTW.py example code as my base code. I have duplicate locations (different floor deliveries). I tried a lot of things to debug this problem but didn't succeed. I came across another problem that **TransitVar()** give no values. Only **CumulVar()** provide information. Any explanation on this will be helpful as well.

**Comment by Mizux** [comment]
IIRC, by default TransitVar it is not exported in the solution/assignement did you add it ?

**Comment by MoosaSaadat** [comment]
No, I wasn't exporting TransitVar before. I tried the following but it didn't work either.

1) Looking at #1079 I changed the code where time windows are added
```python
time_dimension = routing.GetDimensionOrDie("Time")
for cust in customers.customers:
    if cust.tw_open is not None:
        index = manager.NodeToIndex(cust.index)
        time_dimension.CumulVar(index).SetRange(
            cust.tw_open.seconds, cust.tw_close.seconds
        )
        # Adding TransitVar and SlackVar to Assignment
        routing.AddToAssignment(time_dimension.TransitVar(index))
        routing.AddToAssignment(time_dimension.SlackVar(index))

```

2) Tried printing the output
```python
time_dimension = routing.GetDimensionOrDie("Time")
for route_number in range(routing.vehicles()):
    order = routing.Start(route_number)
    vehicle_time_taken = 0
    while True:
        time_var = time_dimension.CumulVar(order)
        transit_var = time_dimension.TransitVar(order)
        slack_var = time_dimension.SlackVar(order)
        node = manager.IndexToNode(order)
        if routing.IsEnd(order):
            vehicle_time_taken += assignment.Min(time_var)
            break
        print(
            f"[{route_number, node}] => Cumul[{assignment.Min(time_var)}, {assignment.Max(time_var)}, {assignment.Value(time_var)}]  Transit[{assignment.Min(transit_var)}, {assignment.Max(transit_var)}, {assignment.Value(transit_var)}]  Slack[{assignment.Min(slack_var)}, {assignment.Max(slack_var)}, {assignment.Value(slack_var)}]"
        )
        order = assignment.Value(routing.NextVar(order))
    print(f"Time Taken: {str(timedelta(seconds=vehicle_time_taken))}\n")
```
It doesn't print anything, neither does it show any errors.

So, I tried one more thing:
```python
...
time_var = time_dimension.CumulVar(order)
transit_var = time_dimension.TransitVar(order)
slack_var = time_dimension.SlackVar(order)

print(time_var)
print(transit_var)
print(slack_var)
```
It gives the following output:
```python
Time21(0)
CastVar<21>(-9223372036854775808..9223372036854775807)
Time slack21(0..86400)
```
Which I think indicates some problem. **CumulVar** and **SlackVar** show values but **TransitVar** doesn't.
**Note:** Although **SlackVar** outputs the value above but **Assignment.Min(), Assignment.Max(), and Assignment.Value()** are not working on it.

**Comment by MoosaSaadat** [comment]
Ah! The problem didn't lie in any of the above mentioned code. I was actually using random time windows for each of my customers. The degree of randomness was quite small, therefore, I was getting close results (mostly the same).

With this problem being solved, I think some help about the behavior of **TransitVar** will still be helpful. Thanks!

**Comment by Mizux** [comment]
For such question please use the mailing list or the discord channel (chat button on the [README.md](https://github.com/google/or-tools/blob/stable/README.md))
