### ISSUE TITLE
CP-SAT solver -- 'int' object is not subscriptable

### ISSUE THREAD

**Issue by whoknowsname** [google/or-tools#1993]
**What version of OR-tools and what language are you using?**
Version: v7.6
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT
**What operating system (Linux, Windows, ...) and version?**
Windows10
**What did you do?**
```python
count_nonstop_work = {}
for p in all_people:
    for d in all_days:
        count_nonstop_work[(p, d)] = model.NewIntVar(0, ub, "count_nonstop_work_{}_{}".format(p, d))

for p in all_people:
    for d in all_days:
        if sum(y[(p, d, c)] for c in all_classes) == 1:
            if d == 0:
                model.Add(count_nonstop_work[(p, d)] == 1)
            else:
                model.Add(count_nonstop_work[(p, d)] == count_nonstop_work[(p, d - 1)] + 1)
        else:
            model.Add(count_nonstop_work[(p, d)] == 0)
        model.Add(s[(p, d)] == count_nonstop_work[(p, d)])
```

**What did you expect to see**
No error
**What did you see instead?**
```
Traceback (most recent call last):
  File "G:/employee_scheduling/solution.py", line 173, in <module>
    model.Add(s[(p, d)] == count_nonstop_work[(p, d)])
TypeError: 'int' object is not subscriptable
```

**Comment by stradivari96** [comment]
Doesn't seems related to OR-Tools, looks like a simple Python error instead.
What is `s`? Is it a dict?

**Comment by whoknowsname** [comment]
> Doesn't seems related to OR-Tools, looks like a simple Python error instead.
> What is `s`? Is it a dict?

s is defined like :
```
s = {}  # 员工已连续上班天数
for p in all_people:
    for d in all_days:
        s[(p, d)] = model.NewIntVar(0, ub, 's_p%id%i' % (p, d))
```

**Comment by lperron** [comment]
definitely a python error.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 30 avr. 2020 à 14:39, whoknowsname <notifications@github.com> a
écrit :

**Comment by stradivari96** [comment]
Helped him privately, `s` was being reassigned...
I think you can close this now as it was a programming bug anyway.

**Comment by whoknowsname** [comment]
> Helped him privately, `s` was being reassigned...
> I think you can close this now as it was a programming bug anyway.

 i have closed it

**Comment by Mizux** [comment]
Thanks @stradivari96  !
