### ISSUE TITLE
Integrality not being respected when using Glop linear solver

### ISSUE THREAD

**Issue by letsgolesco** [google/or-tools#1994]
**What version of OR-tools and what language are you using?**
Version: 7.6.7691
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
GLOP

**What operating system (Linux, Windows, ...) and version?**
We've observed this in two environments: 
- `Linux 4.19.112+ #1 SMP Thu Mar 26 23:42:41 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux`
- `MacOS 10.15.4`

**What did you do?**

We’re trying to create pairings for a group of people where everyone is matched to exactly one other person. If the group has an odd number of people, exactly one person should be left unmatched.

We are using boolean variables to represent whether a pairing has been made between two users. We are experiencing multiple values of 0.5 in our solution when we expect only 0 or 1.

This issue occurs with the Glop solver but not with the CBC MIP solver.

In place of `BoolVar` we have also tried using `NumVar` and `Var` (with integrality `True`).

Code example:

```python
from ortools.linear_solver import pywraplp


def solver_test():
    matrix_length = 101
    solver = pywraplp.Solver("Solver Name", pywraplp.Solver.GLOP_LINEAR_PROGRAMMING)

    # Decision Variables
    scores_matrix = {i: {} for i in range(matrix_length)}
    for i in range(matrix_length - 1):
        for j in range(i + 1, matrix_length):
            decision_variable = solver.BoolVar(f"x_{i},{j}")

            # Our attempt using NumVar looked like this:
            # decision_variable = solver.NumVar(0, 1, f"x_{i},{j}")
            # 

            # Our attempt using Var looked like this:
            # decision_variable = solver.Var(0, 1, True, f"x_{i},{j}")

            scores_matrix[i][j] = decision_variable
            scores_matrix[j][i] = decision_variable

    # Constraints
    for score_list in scores_matrix.values():
        constraint = solver.Constraint(0, 1)
        for score in score_list.values():
            constraint.SetCoefficient(score, 1)

    # Maximization
    objective = solver.Objective()
    for i in range(matrix_length - 1):
        for j in range(i + 1, matrix_length):
            objective.SetCoefficient(scores_matrix[i][j], 1)

    objective.SetMaximization()

    # Solve
    status = solver.Solve()
    if status == pywraplp.Solver.OPTIMAL:
        print(f"Objective value = ", solver.Objective().Value())
        for i in range(matrix_length - 1):
            for j in range(i + 1, matrix_length):
                solution_value = scores_matrix[i][j].solution_value()
                if solution_value != 0.0 and solution_value != 1.0:
                    print(f"({i},{j}): {solution_value}")
    else:
        print("No optimal solution could be found")


solver_test()
```

**What did you expect to see**

- Objective value 50
- All decision variables have a value of either 0 or 1.
- `SetInteger` method to exist in our decision variables

**What did you see instead?**

- Objective value 51
- Three decision variables have a value of 0.5, the rest 0 or 1
- `SetInteger` method did not exist in our decision variables

**Comment by stradivari96** [comment]
See:
* https://stackoverflow.com/questions/59116520/linear-programming-google-ortools-incorrect-decision-variable-final-values/59125270#59125270
* https://groups.google.com/forum/#!msg/or-tools-discuss/p5qVzZWIeIg/g77egaD-AAAJ

> Glop is a pure LP. It will only solve the relaxation of the mip problem. So it is normal that the error checker tells you that the solution is not integral.
> You can change GLOP_LINEAR_PROGRAMMING to BOP_INTEGER_PROGRAMMING if you program is purely boolean.
Or you can stay with CBC
