### ISSUE TITLE
What does it mean when Gurobi returns an "ABNORMAL" status?

### ISSUE THREAD

**Issue by gdowdy3** [google/or-tools#1997]
**What version of OR-tools and what language are you using?**
Version: stable (downloaded source code from GitHub on 30-Apr-2020)
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Gurobi

**What operating system (Linux, Windows, ...) and version?**
Windows 10 Pro

**What did you do?**
1. Downloaded stable source code.
2. Built from source, including Gurobi in the compilation.
3. Successfully solved a small optimization problem using Gurobi.
4. Attempted to solve a larger problem with Gurobi.

**What did you see instead?**
The line `status = solver.Solve()` results in a value of `4` being assigned to `status`, which, if I am not mistaken, corresponds to a `ResultStatus` of `pywraplp.Solver.ABNORMAL`.

**Anything else we should know about your project / environment**
The Gurobi output log includes only the following:
```
Solving the model...
Gurobi Optimizer version 9.0.0 build v9.0.0rc2 (win64)
Optimize a model with 15451564 rows, 19854540 columns and 35172741 nonzeros
Model fingerprint: 0x14bdb496
Coefficient statistics:
  Matrix range     [1e+00, 4e+01]
  Objective range  [4e-03, 8e+05]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e-02, 1e+06]
 
Concurrent LP optimizer: dual simplex and barrier
Showing barrier log only...
```
There are two things to note here:

1. There is no error message.
2. It is a rather large model. (I'm trying to solve it on my unexceptional laptop.)

My best theory at present is that Gurobi is simply crashing because it is running out of memory.  Can anyone confirm this theory?  At the least, can you tell me how I might find an error message that would state the error more explicitly?

**Comment by lperron** [comment]
I guess gurobi decided it could not solve the model.

Le ven. 1 mai 2020 à 23:09, Garrett R Dowdy <notifications@github.com> a
écrit :

**Comment by Mizux** [comment]
You should ask on the mailing list otherwise

**Comment by gdowdy3** [comment]
Hey guys, thanks for the reply.  I've posted on the Google groups mailing list, as you've suggested. Here's some additional relevant information:

If I use OR-Tools to write the problem to a .LP file and then read in and attempt to solve the .LP file using Gurobi's command line interface, it has no problem.  It solves without error.  The Gurobi output is shown below:

```
C:\Users\gdowdy3\Projects\Gurobi Test>gurobi
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Using license file C:\Users\gdowd\gurobi.lic
Set parameter LogFile to value gurobi.log
 
Gurobi Interactive Shell (win64), Version 9.0.0
Copyright (c) 2019, Gurobi Optimization, LLC
Type "help()" for help
 
gurobi> m = read('TestModel.lp')
Read LP format model from file TestModel.lp
Reading time = 85.00 seconds
Obj: 15451564 rows, 15131806 columns, 31058151 nonzeros
gurobi> m.optimize()
Gurobi Optimizer version 9.0.0 build v9.0.0rc2 (win64)
Optimize a model with 15451564 rows, 15131806 columns and 31058151 nonzeros
Model fingerprint: 0xb863d8c9
Coefficient statistics:
  Matrix range     [1e+00, 4e+01]
  Objective range  [4e-03, 8e+05]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e-02, 1e+06]
 
Concurrent LP optimizer: dual simplex and barrier
Showing barrier log only...
 
Presolve removed 0 rows and 0 columns (presolve time = 13s) ...
Presolve removed 12897530 rows and 1979025 columns (presolve time = 18s) ...
Presolve removed 13502231 rows and 8190922 columns (presolve time = 20s) ...
Presolve removed 13829678 rows and 8285721 columns (presolve time = 26s) ...
Presolve removed 13830154 rows and 8474671 columns (presolve time = 37s) ...
Presolve removed 13835483 rows and 8480000 columns (presolve time = 41s) ...
Presolve removed 14689545 rows and 9337998 columns
 
Solved with dual simplex
Solved in 663428 iterations and 184.14 seconds
Optimal objective  4.401466425e+08
```
This suggests that the problem is not with Gurobi specifically, but with how Gurobi and OR-Tools are communicating.

Do you agree?

One additional detail I'd like to note which may or may not be relevant: In my previous post, you will see that there are 19854540 columns.  In this post, you will see that there are only 15131806.  I am not sure why these two numbers are different...

**Comment by gdowdy3** [comment]
Another detail which may or may not be important: when I create the solver object with the command
```python
solver = pywraplp.Solver('simple_mip_program', pywraplp.Solver.GUROBI_MIXED_INTEGER_PROGRAMMING)
```
I get the following warning message:
```
Warning: parameter changes on this environment will not affect existing models.
```
This is true both for my small model that works and for my larger model which does not work.

**Comment by gdowdy3** [comment]
@Mizux @lperron , any further thoughts on this?
