### ISSUE TITLE
Disjunction, NotMemberCt constraint ignores Disjunction

### ISSUE THREAD

**Issue by ilaif** [google/or-tools#1999]
**What version of OR-tools and what language are you using?**
Version: 7.1.6720
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing Solver

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 18.04

**What did you do?**
1. Define multiple time windows to visit a node via NotMemberCt:
```python
solver.AddConstraint(
    solver.NotMemberCt(
        time_dimension.CumulVar(manager.NodeToIndex(node_index)),
        [500],
        [horizon]
    )
)
```

2. Add a constraint to visit this node:
```python
node_cumul_var = time_dimension.CumulVar(
    manager.NodeToIndex(node_index)
)
solver.Add(750 <= node_cumul_var)
```

3. Add disjunction for that node to make it optional
```python
routing.AddDisjunction([manager.NodeToIndex(node_index)], penalty_base)
```

In this setting:
1. From (1) - The node cannot be visited between 500 and the horizon, so it can be visited only during 0 - 500.
2. From (2) - The node can only be visited from 750.
3. Therefore, the node **cannot be visited in this solution**.

**What did you expect to see**

I expected this node to be dropped due to Disjunction (3), and a solution to be found.

**What did you see instead?**

The solver says no solution is found (I've tried multiple FirstSolutionStrategy just in case - but none worked).

This is either a bug or my misunderstanding of how this should work. If it's not a bug, how would you go about solving this? I'm trying to minimize "pre-solver" logic such as checking myself whether I should include unreachable nodes before handing it over to the solver.

Thanks,
Ilai

**Comment by lperron** [comment]
1 just say that it cannot be visited at 500.

Please fix and reopen the bug if still present.
