### ISSUE TITLE
How to include or-tools in c++ project on Ubuntu 16.04?

### ISSUE THREAD

**Issue by Nguyen-K60** [google/or-tools#2000]
Hello everyone,
I have a c++ project which is run by waf command. I need to use example vrp_capacity.cc many times in this project, what should I do?
Thank you.

**Comment by Mizux** [comment]
take the ubuntu 16.04  archive (in the release tab on github)
Take a look at the Makefile or (run it) to get all include, compile, link flags -> port them to your waf build system 
Don't forget to copy libs in your project too !

**Comment by Nguyen-K60** [comment]
Thank you Mizux, I will try your suggestion.
