### ISSUE TITLE
Freeze/commit part of the route provided in initial solution

### ISSUE THREAD

**Issue by drgoda** [google/or-tools#2003]
**What language and solver does this apply to?**
Python, Java

**Describe the problem you are trying to solve.**
I am solving a dynamic VRP and hence when I reoptimize, I would like to freeze already committed deliveries on a route and only optimize the later part of the sequence considering newer deliveries that have come in after last run. Unable to figure out how to do this when I give previous routes as initial solution for this run.
**Describe the solution you'd like**
Option to freeze part of the sequence and only allow changes to others while running  metaheuristics/local search to improve upon the initial solution.
**Describe alternatives you've considered**
Was thinking of altering distance matrices where only frozen arcs have 0 cost and those nodes are infinite cost from others. But need a more elegant solution.
**Additional context**

**Comment by lperron** [comment]
https://developers.google.com/optimization/routing/routing_tasks#setting-initial-routes-for-a-search

**Comment by drgoda** [comment]
Sorry I did not get how to do this. Could you please elaborate?

**Comment by drgoda** [comment]
I know initial routes can be set. My question is how to apply lock on specific parts of the initialized route in python.

**Comment by lperron** [comment]
Please use the mailing list. Github issues have very limited audience.
