### ISSUE TITLE
CP-SAT max_time_in_seconds doesn't work in 7.6

### ISSUE THREAD

**Issue by jox79** [google/or-tools#2009]
**What version of OR-tools and what language are you using?**
Version: 7.6
Language: Python
CP-SAT
Windows
With 8 threads.  I set up the parameter max_time_in_seconds = 600 seconds  but the solver stops with a feasible solution after 2164 seconds 
The same model with 7.5 versione stops properly after 600 seconds.
Attached the model
[model.zip](https://github.com/google/or-tools/files/4601493/model.zip)

**Comment by lperron** [comment]
Please send a model.

**Comment by jox79** [comment]
Hi Laurent,
It is attached in the Github issue. Isn't it?
Regards
Stefano


Il Sab 9 Mag 2020, 00:24 Laurent Perron <notifications@github.com> ha
scritto:

> Please send a model.
>

**Comment by lperron** [comment]
My bad, it was not visible in the email. We will have a look.

**Comment by lperron** [comment]
This is my run on master with a 60s time limit (on my mac).

status: FEASIBLE
objective: 2.23851084e+14
best_bound: 3.24984035e+15
booleans: 335174
conflicts: 1123
branches: 762505
propagations: 55075574
integer_propagations: 38288997
walltime: 62.4871
usertime: 62.4871
deterministic_time: 22.2746
primal_integral: 796.47

I will run it on windows.

**Comment by jox79** [comment]
that's strange. Could it be the issue on windows only? I'm sure it does not depend on my code because I'm measuring the time just before and after the solve:
 start = time.time()
 status = solver.Solve(model)  
 end = time.time() - start

**Comment by jox79** [comment]
I made further tests, with 20 minutes of max time. it seems that the search stops after 20 minutes, because the CPU is released from 100% (8 solvers) to 40%, while the RAM is still high (4.5GB). It seems like it is taking long time to make some operation in memory, like saving the saving the status. With 7.5 it normally takes few seconds after the end of search.

**Comment by lperron** [comment]
Yes, one of the subsolvers is slow to react :-(

**Comment by jox79** [comment]
Is there the possibility to fix? I really like to use the 7.6 but now I have done the downgrade to 7.5 because all my models are similar to the one I've sent to you.
Regards
Stefano

**Comment by lperron** [comment]
I guess it is one of the LNS workers.

You can use 6 threads, or maybe disable the rins one (if it is the culprit)
by setting use_rins_lns  to false.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by jox79** [comment]
If I do as you suggest could I get better result with 7.6 compared with 7.5
with 8 threads?
Thank you

Il Gio 21 Mag 2020, 19:53 Laurent Perron <notifications@github.com> ha
scritto:

> I guess it is one of the LNS workers.
>
> You can use 6 threads, or maybe disable the rins one (if it is the culprit)
> by setting use_rins_lns to false.
> Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68
> 53
> 00
>
>
>

**Comment by lperron** [comment]
I cannot answer this question. You need to test.

**Comment by lperron** [comment]
I believe it is fixed on master. I will close the issue.
Please reopen if it still exists with the 8.0 release.
