### ISSUE TITLE
Complex expression in channeling constraints

### ISSUE THREAD

**Issue by 2nikita** [google/or-tools#2010]
I’m new to CP-SAT Solver and CP concept and trying to implement one complex expression in the channeling constraint in my model.

I have the following variables:
 ```
z, x, b - boolean
d, a - integer
```
which form the constraint:

`(z = 0 /\ x = 1 /\ d >= a) => b = 1`

I’m programming in Python and checked the examples of how to link expressions like:  
`x < 5 => y = 10 - x`
through intermediate boolean variable, but can’t figure out how to model my constraint.

Could you please give some hints/suggestions?

**Comment by stradivari96** [comment]
Hi, you should ask modeling questions at the mailing list: https://groups.google.com/forum/#!forum/or-tools-discuss

That said, this should work:
```python
tmp = model.NewBoolVar("d >= a")
model.Add(d >= a).OnlyEnforceIf(tmp)
model.Add(d < a).OnlyEnforceIf(tmp.Not())

model.Add(b == 1).OnlyEnforceIf([z.Not(), x, tmp])
```
