### ISSUE TITLE
OR tools liner solver

### ISSUE THREAD

**Issue by ittb** [google/or-tools#2011]
@lperron 
I am very new to Python an OR-Tools, so please excuse the simplicity of my question.
I installed OR-Tools on my 64-bit, Win10 machine. I am using Python 64bit. I am working on both PyCharm amd Jupyter Notebook.
I get the error No module named 'ortools'.
I had Visual Studio Professional 2017 15.9.22 downloaded but that did not fix the issue.
I reviewed the prior issue No module named 'ortools' #737, but it didn't help.
I appreciate your help.

ImportError                               Traceback (most recent call last)
<ipython-input-1-30aa6e4536b2> in <module>
      1 from __future__ import print_function
----> 2 from ortools.linear_solver import pywraplp

~\AppData\Roaming\Python\Python37\site-packages\ortools\linear_solver\pywraplp.py in <module>
     11 # Import the low-level C/C++ module
     12 if __package__ or "." in __name__:
---> 13     from . import _pywraplp
     14 else:
     15     import _pywraplp

ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by Mizux** [comment]
did you try to install the VS 2019 redistributable ?

**Comment by Mizux** [comment]
https://developers.google.com/optimization/install/python/windows#microsoft-visual-c++-redistributable
