### ISSUE TITLE
Incremental solving using CP-SAT solver

### ISSUE THREAD

**Issue by EmielRommelse** [google/or-tools#2014]
**What language and solver does this apply to?**
All / CP-SAT

**Describe the problem you are trying to solve.**
I want to use the CP-SAT solver as the subproblem in delayed column generation. For this I am repeatedly solving the same model with one additional negative reduced cost constraint each iteration.

**Describe the solution you'd like**
Incremental solving or possibility to add constraints during callback. Since no variables are added or previous constraints are changed, the domain reductions and search tree of the previous search could be used as a starting point for a considerable decrease in runtime.

**Describe alternatives you've considered**
•	Solving the model repeatedly from scratch.
•	Checking and updating the reduced cost constraint in a ‘CpSolverSolutionCallback’. However, this causes the solver to spend a lot of time in branches that are infeasible with regards to the reduced cost constraint.
•	Trying to convert to MIP. However, my subproblem is very suitable for CP due to conditionals.

**Additional context**
Use cases: Multi-dimensional cutting stock problems, guillotine problems, orthogonal packing.

**Comment by lperron** [comment]
In the sub-problem, do you have an objective ?

**Comment by EmielRommelse** [comment]
No, I do not. I am using the CP-SAT solver to find a feasible solution.

**Comment by EmielRommelse** [comment]
After reading the Java reference on github I found the _solver.parameters.fill_tightened_domains_in_response_ parameter and I am using the tightened variables in the _solverResponseStats_ to update variable domains. This does seem to have some of the desired affects, even though updating the domains of currently existing variables is somewhat tricky. 

Still, continuing the search for solutions where the solver exited would be an improvement over this as the tightening of domains only partially reflects the exploration done by the solver.

**Comment by EvanHonnold** [comment]
I have a similar use-case -- I use the CP-SAT solver to check whether a system is feasible, and then if it is, I test a number of additional constraints one at a time to see if any one of them renders the system infeasible. It would be great if I could use the results of the first feasibility check to speed up the subsequent searches.

**Comment by lperron** [comment]
You can
Use hinting. Model.AddHint()

Le dim. 13 déc. 2020 à 04:09, Evan Honnold <notifications@github.com> a
écrit :

**Comment by sk-surya** [comment]
I too have the same use case as EmielRommelse. Excited for incremental solving feature in CP-SAT.

**Comment by sk-surya** [comment]
I too have the same use case as EmielRommelse. Excited for incremental solving feature in CP-SAT.

I'm trying to solve a sub-problem (an optimization problem) where I'll be happy if I get a solution with negative objective value. So using a CP solver it makes sense to add this as a constraint. But I would be happier, if I could get improving solutions if I have some more time, (I dont want the global optimum, but a good one) by specifying an objective, but I do not want the solver to use branch and bound/LP or any technique that tries to prove optimality. ie, essentially a pure local search CP-SAT solver with no optimality tracking to save time. I feel Incremental solving on a CSP or an option to use CP-SAT with objective as just local search could solve this. If there is any other way that exists, please let me know.

**Comment by ktnr** [comment]
Has this been closed because a new feature has been added in v9.3 or because there are no plans to have more functionality than `Model.AddHint()`?

**Comment by lperron** [comment]
no plan for more than AddHint().
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
