### ISSUE TITLE
How to use ApplyLocksToAllVehicles() in python?

### ISSUE THREAD

**Issue by SiddharthaPaul** [google/or-tools#2015]
**What version of OR-tools and what language are you using?**
Version: 6.10.6025
Language: Python

I am trying to start the VRP with an initial solution (e.g. [1,3,8,5]) where I want to lock the first two nodes of the route (i.e. [1,3]). In this context how do I use ApplyLocksToAllVehicles() in python? I did not find any example or documentation on the same. Any quick help will be highly appreciated.

**Comment by lperron** [comment]
Please use the mailing list.
