### ISSUE TITLE
define only maschine type but generate as many as you need "real" machines from type in .NET code

### ISSUE THREAD

**Issue by SGuzel** [google/or-tools#2025]
Hey folks, 

we have also a scheduling problem but slightly different. (of course :) )
Our problem is, that we have a type of machine for example (Type: WasherType) but we can not really estimate how many we would use real WasherMachine of type WasherType. 
We would also define a max count of WasherType, something like, you can only allocate 5 Washer from WasherType.
 If one job is executed on Washer1 than the algorithm should create another Washer->Washer 2 and let execute the job parallel to Washer 1 an so on, till all Washers are busy. 

Aim-> define max need of  Washer.

Is there any example doing this with ORTools for .NET? 

Best, 
-Sue

**Comment by lperron** [comment]
Please use the mailing list.
