### ISSUE TITLE
Error when solving CPSolver using SearchAllSolutions

### ISSUE THREAD

**Issue by Caster89** [google/or-tools#2026]
**What version of OR-tools and what language are you using?**
Version: v7.6.7691
Language: C#

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
I created a model with optional IntervalVars and tried to maximize the number of IntervalVars placed in the given time horizon.

**What did you expect to see**
A solution to the problem, showing as many IntervalVars as possible scheduled

**What did you see instead?**
The program ends unexpectedly. In debug mode it returns that the SearchAllSolutions exited with code 3221226505.

Here is the MWE of what I did:

`
public class MaximizeOptionals
    {
        CpModel model;
        CpSolver solver;

        List<IntervalVar> tasks = new List<IntervalVar>();
        Dictionary<IntervalVar, IntVar> tasksToStart = new Dictionary<IntervalVar, IntVar>();
        Dictionary<IntervalVar, IntVar> tasksToEnd = new Dictionary<IntervalVar, IntVar>();
        Dictionary<IntervalVar, IntVar> tasksToScheduled = new Dictionary<IntervalVar, IntVar>();

        int HorizonStart = 0;
        int HorizonEnd = 30;

        public MaximizeOptionals()
        {
            model = new CpModel();
            solver = new CpSolver();
            for(int i = 0; i <5; i++)
            {
                var tmpStart = model.NewIntVar(HorizonStart, HorizonEnd, $"Task_{i}_Start");
                var tmpStop = model.NewIntVar(HorizonStart, HorizonEnd, $"Task_{i}_Stop");
                var tmpOptional = model.NewBoolVar($"Task_{i}_Scheduled");

                tasks.Add(model.NewOptionalIntervalVar(tmpStart, 4, tmpStop,tmpOptional, $"Task_{i}"));
                tasksToStart[tasks.Last()] = tmpStart;
                tasksToEnd[tasks.Last()] = tmpStop;
                tasksToScheduled[tasks.Last()] = tmpOptional;

            }

            model.AddNoOverlap(tasks);
            //Maximize the number of scheduled Tasks
            IntVar Scheduled = model.NewIntVar(0, tasks.Count(), "schedule");
            model.Add(Scheduled == LinearExpr.Sum(tasksToScheduled.Values));
            model.Maximize(Scheduled);

            SolutionPrinter cb = new SolutionPrinter();
            CpSolverStatus status = solver.SearchAllSolutions(model, cb);

            foreach(IntervalVar t in tasks)
            {
                Console.WriteLine($"{t.Name()}: Scheduled {solver.Value(tasksToScheduled[t])}");
                Console.WriteLine($"\t-Starts at {solver.Value(tasksToStart[t])}");
                Console.WriteLine($"\t-Ends at {solver.Value(tasksToEnd[t])}");
            }
        }
    }
`

When run like this the program ends unexpectedly at the solver.SearchAllSolutions line and returns 
`The program '[20568] Scheduler.exe' has exited with code -1073740791 (0xc0000409).`
To make it work I can either use `solver.Solve(model)` (solver.SolveWithSolutionCallback fails in the same way as SearchAllSolutions), or I can change my objective to the classic minimize Makespan

`
            IntVar MakeSpan = model.NewIntVar(HorizonStart, HorizonEnd, "makespan");
            List<IntVar> ends = tasksToEnd.Values.ToList();
            model.AddMaxEquality(MakeSpan, ends);
            model.Minimize(MakeSpan);
`

In which case any of the solve methods works. 
I think it might have something to do with the SolutionCallback but I don't understand why it would work with one Objective and not with another one

![image](https://user-images.githubusercontent.com/8697281/82432182-f3d45080-9a8f-11ea-9667-8a93e42ab984.png)

**Comment by lperron** [comment]
SearchForAllSolutions is not supported for optimization models, only for feasibility ones.

**Comment by Caster89** [comment]
Hi Laurent, 
Thank you for the prompt answer. I'm sorry I'm kind of new to constraint problems and I am not sure I understand why Minimizing the end time of the tasks is different to Maximizing the number of tasks, and how one is an optimization model while the other is a feasibility one.

**Comment by lperron** [comment]
Both are optimization models.

As documented in all non .NET languages, SearchForAllSolutions only works
on feasibility models.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Caster89** [comment]
Ok. So in theory it should fail with both cases, the fact that it works without errors when I minimize the makespan is fortuitous and in theory it is not supported and should fail?
