### ISSUE TITLE
Mutually Exclusive Cargos

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#2027]
For C#, Routing
I'd like to present loading cargo that are incompatible, on the same vehicle.
cargo of type A cannot be loaded together her with cargo type B :  A & A is valid, B & B is valid, but A & B is invalid.

I cannot see how this can be done based on capacity limit. Could we create a dedicated variable for this?

Thanks

**Comment by lperron** [comment]
Please use the mailing list.

**Comment by GuyBenhaim** [comment]
Sorry, what is the mailing list?

**Comment by GuyBenhaim** [comment]
ok, re-posted in the Forum
