### ISSUE TITLE
Can I use ortools as spark udf?

### ISSUE THREAD

**Issue by songzhiyong** [google/or-tools#2029]
**What version of OR-tools and what language are you using?**
Version: ortools==7.6.7691
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
 CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you do?**
I create a cp_model.CpSolver and register as udf of spark

but the result is not as expected, sometimes wrong optimal value, sometimes correct, same code and same parameters

when I run on my laptop and not use as spark udf, always get correct result

**Comment by lperron** [comment]
most likely you need to add the native libraries in some kind of path.
