### ISSUE TITLE
Making a custom database for items and doing pickup and delivery accordingly.

### ISSUE THREAD

**Issue by cskarthik7** [google/or-tools#2030]
I have been trying to implement a feature like for e.g. There is shop with x quantity of items A, y quantity of items B and z quantity of items C so I want to add pickup and delivery orders based on request of nodes and as well as reduce the amount of quantities as the items are dispatched from the shops.

Is there any way to improvise in vrp_pickup_delivery.cc ?
 
@Mizux

**Comment by lperron** [comment]
Please use the mailing list.
