### ISSUE TITLE
Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE threw an exception (SWIGExceptionHelper)

### ISSUE THREAD

**Issue by nicolasmohamed** [google/or-tools#2032]
**What version of OR-tools and what language are you using?**
Version: NuGet package 7.6.7691
Language: C#

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing Solver

**What operating system (Linux, Windows, ...) and version?**
Windows MSBuild (Azure)

**What did you do?**
1. Add NuGet package
2. Build from Azure DevOps pipeline

**What did you expect to see**

**What did you see instead?**
Runtime exception:

The type initializer for 'Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE' threw an exception.
Inner Exception: The type initializer for 'SWIGExceptionHelper' threw an exception.
Stack trace: dGoogle.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.new_RoutingIndexManager__SWIG_0(Int32 jarg1, Int32 jarg2, Int32 jarg3)

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
Local environment works fine. Those error happen when we use Azure DevOps MSBuild

**Comment by nicolasmohamed** [comment]
It seems related to VC++ 2019 not being installed in the app service.

From KUDU console

reg query HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Dependencies\Microsoft.VS.VC_RuntimeMinimumVSU_amd64,v14
**Microsoft Visual C++ 2017 x64 Minimum Runtime - 14.15.26706**

reg query HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Dependencies\Microsoft.VS.VC_RuntimeAdditionalVSU_amd64,v14
**Microsoft Visual C++ 2017 x64 Additional Runtime - 14.15.26706**

Please note that VC++ 2019 cannot be installed as the app service runs within a sandbox. 

Any ideas? 

Thanks

**Comment by Mizux** [comment]
Why you can't  install the VS 2019 x64 Runtime ?

**Comment by nicolasmohamed** [comment]
Because every Azure App Service runs within a sandbox as PaaS, in shared hardware, so you have no access to install VC++. 

[](https://docs.microsoft.com/en-us/archive/blogs/benjaminperkins/visual-c-redistributable-packages-for-visual-studio-azure-app-service)

**Comment by lperron** [comment]
OR-Tools contains native AMD64 code. Please check this is possible in Azure.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 22 mai 2020 à 20:09, nicolasmohamed <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
If this is true, you cannot use or-tools and azure together.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le sam. 23 mai 2020 à 01:30, nicolasmohamed <notifications@github.com> a
écrit :

**Comment by nicolasmohamed** [comment]
Hello Laurent, our .Net project has been configured for x64 platform, with x64 MSBuild and x64 app service so it should not have any platform incompatibility issue. We would like to give it a try with VC++2017, if possible, as it seems the issue could be related to C++ Interop.

Maybe downgrade to a previous package version? Another solution would be to create a new app service (linux) and use it as a API, but we definitely prefer to avoid that. 

Thanks

**Comment by lperron** [comment]
Unfortunately, vc2017 cannot compile one of our dependency.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le sam. 23 mai 2020 à 12:18, nicolasmohamed <notifications@github.com> a
écrit :

**Comment by nicolasmohamed** [comment]
Would it be possible for you to upload v7.4 nuget package with the signed dlls (or just the dlls)? That package is not usable as it is right now and it would be great for us to use it, along with many others that use Azure app services.

Thanks!

**Comment by nicolasmohamed** [comment]
[Update] We've managed to use v7.6 deployed in a linux 64-bit app service (Net Core 3.1). Not the best option for us, but it is working as expected.

**Comment by Mizux** [comment]
@nicolasmohamed are you sure VS2019 is not installed ?

see:
https://github.com/projectkudu/kudu/blob/c86560ae490b398a2073ebad2f750aa153834d8c/build.cmd#L11-L18
and it seems Microsoft provide VS2019 pipeline
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software

**Comment by nicolasmohamed** [comment]
Hi @Mizux! 

Our app services don't have VC++ 2019 runtime installed. So, it builds OK with that pipeline but it fails on runtime. 
On the other hand, our SA made a [serverless function](https://docs.microsoft.com/en-us/azure/azure-functions/) and it is working from there as well. So that would be the best solution for us, at this time.
