### ISSUE TITLE
Change from virtualenv to venv?

### ISSUE THREAD

**Issue by cdeil** [google/or-tools#2035]
I got this:
```
% make test_package_python
<snip>
/Users/cdeil/anaconda3/envs/hcem/bin/python3.7 -m virtualenv temp_python3.7/venv
/Users/cdeil/anaconda3/envs/hcem/bin/python3.7: No module named virtualenv
```
(see [full log](https://gist.github.com/cdeil/4655776820758e73a5c673b56257a7b6#file-gistfile1-txt-L506))

Since Python 3.3 the `venv` package is in the Python standard library:
https://docs.python.org/3/library/venv.html

Change `python -m virtualenv` to `python -m venv` to get rid of this external dependency to the third-party [virtualenv](https://pypi.org/project/virtualenv/) package?

Alternatively, if you want to keep `virtualenv` for some reason, the dependency should be mentioned here:
https://developers.google.com/optimization/install/python/source_mac#python

I could send a PR with the change. Let me know.

**Comment by Mizux** [comment]
need to check if it fulfill our simple use case.
Should be done for the cmake build also (try to keep them in sync)

For the record:
https://github.com/google/or-tools/blob/5ff76b487a6c2006326765d6417964599eedc8c9/makefiles/Makefile.python.mk#L1114-L1116
and here:
https://github.com/google/or-tools/blob/5ff76b487a6c2006326765d6417964599eedc8c9/cmake/python.cmake#L232-L252

**Comment by Mizux** [comment]
maybe related to #1960 which need to be done in google internal code base to limit the divergence...
