### ISSUE TITLE
Cp model requires int, errors on numpy.int64 in .NewIntVar()

### ISSUE THREAD

**Issue by nielsuit227** [google/or-tools#2036]
**What version of OR-tools and what language are you using?**
Version: 7.6.7691
Language: Python 3.8.2

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
n/a

**What operating system (Linux, Windows, ...) and version?**
Windows 10 Home

**What did you do?**
from ortools.sat.python import cp_model
import numpy as np
x = np.array([1])[0]
model = cp_model.Model()
model.NewIntVar(0, x, 'name')

**What did you expect to see**
New variable

**What did you see instead?**
Domain error. 

Make sure you include information that can help us debug (full error message, model Proto).
Traceback (most recent call last):
  File "C:\Users\Niels\AppData\Local\Programs\Python\Python38\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-272e0733f6a8>", line 1, in <module>
    start_var = model.NewIntVar(0, horizon, 'start' + suffix)
  File "C:\Users\Niels\AppData\Local\Programs\Python\Python38\lib\site-packages\ortools\sat\python\cp_model.py", line 718, in NewIntVar
    return IntVar(self.__model, Domain(lb, ub), name)
  File "C:\Users\Niels\AppData\Local\Programs\Python\Python38\lib\site-packages\ortools\util\sorted_interval_list.py", line 81, in __init__
    _sorted_interval_list.Domain_swiginit(self, _sorted_interval_list.new_Domain(*args))
TypeError: Wrong number or type of arguments for overloaded function 'new_Domain'.
  Possible C/C++ prototypes are:
    operations_research::Domain::Domain()
    operations_research::Domain::Domain(int64)
    operations_research::Domain::Domain(int64,int64)

**Anything else we should know about your project / environment**
Nope

**Comment by lperron** [comment]
I do not understand why this is an error.

**Comment by Mizux** [comment]
basically you need to pass two int64 (min and max) and a name i.e. `NewIntVar(min, max, 'name')` in your code you are passing a numpy array i.e. x as max value...

**Comment by nielsuit227** [comment]
Yeah I know that, I fed a python native integer and a 64 bit numpy integer. 
I used np.array([1])[0] to create a numpy integer, but it isn't actually an array. 
Anyways, not sure whether this classifies as an error as Iperron states, but given how commonly used numpy is, I feel like the model shouldn't error when an integer is taken from a numpy array.

**Comment by Mizux** [comment]
Feel free to patch the Python SWIG typename so numpy int64 as well as regular python int type are parsed and converted to C++ `std::int64_t` ;)
