### ISSUE TITLE
Routing Solver is suppressing exceptions

### ISSUE THREAD

**Issue by jmriddell** [google/or-tools#2038]
**Version:** 7.6.7691
**Language:** Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit]
**Solver:** Routing Solver
**Operating System:** Microsoft Windows 10 Pro 10.0.18363 Build 18363

**What did you do?**
1. Start with the example file for the travelling salesman problem
    https://github.com/google/or-tools/blob/75fba177ea467e8346c8738c722916f82bcd698f/ortools/constraint_solver/samples/tsp.py#L1-L145
2. Write a faulty callback function
    ```python
    def faulty_distance_callback(from_index, to_index):
        raise RuntimeError("This is intended to fail.")
    ```
3. Go to where the original distance callback was defined inside the `main` function
    https://github.com/google/or-tools/blob/75fba177ea467e8346c8738c722916f82bcd698f/ortools/constraint_solver/samples/tsp.py#L115
4. Replace the original distance callback with the new faulty one
    ```python
    distance_callback = faulty_distance_callback
    ```
5. Run the file
    ```bash
    python tsp.py
    ```
**What did you expect to see**
The program execution stopped with `RuntimeError: This is intended to fail.`

**What did you see instead?**
The program executed successfully with output:
```
Route for vehicle 0:
 0 -> 16 -> 15 -> 14 -> 13 -> 12 -> 11 -> 10 -> 9 -> 8 -> 7 -> 6 -> 5 -> 4 -> 3 -> 2 -> 1 -> 0
Distance of the route: 0m
```

**Notes:**
- Experimenting with it found that when `distance_callback` works as intended, it is called multiple times, but the faulty one is just called once and a result is returned.
- Sometimes switching from the faulty function to the non faulty one makes the python interpreter to crash without returning an error.

**Comment by Mizux** [comment]
I think exception are catched in the SWIG wrapper...
