### ISSUE TITLE
import examples.cs is'nt working

### ISSUE THREAD

**Issue by savvaskef** [google/or-tools#204]
Hi,this is my story:
I eagerly downloaded google.or.tools from GitHub.I started by loading the solution in VSTO2015,c#.
Initially there were problems the codes of which I cannot recall.After some struggle I downloaded google.or.library from nugget since the dll reference was not working(I told you I don't remember the error codes).After altering platform on the solution properties the examples already loaded at the solution ran properly (with little errors maybe because of version of the references).

My real problem is when I am trying to import an existing example.cs in a newly created project.I'd think that if I was able to turn the platform to x64 the example would load.However there is no choice in the solution properties for the project i'vbeen talking about other than 'AnyCPU'.

The error I get now is 

An unhandled exception of type 'System.BadImageFormatException' occurred in Apuzzle Project.exe

Additional information: Loading the file or assemply cannot be loaded 'Google.OrTools, Version=2.0.3298.6634, Culture=neutral, PublicKeyToken=null' or relavant assembly

Thnx in advance,
Savvas Kefalas

**Comment by lperron** [comment]
I suspect you are using 32bit .NET.
We only build 64 bit archives/libraries.

Can you check that?

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-07-04 14:35 GMT+02:00 savvaskef <notifications@github.com>:

**Comment by savvaskef** [comment]
i was nearly sure that my VSTO was x64---however it is enlisted in program files(x86). Why then the solution.sln runs in platform x64, debug once I specify the platform and add the reference?

Is it possible to send me a solution file with all classes added?Or how should I achieve something like that?

**Comment by savvaskef** [comment]
detail added:when I use vsto2010 (in solution properties-->configuration properties-->configuration.) all projects are by default set to x64 and work while a_puzzle.cs, once added, has x86 selected with no possible other choices (that is the same problem only without anycpu and instead x86)

**Comment by savvaskef** [comment]
but why do the 5 .CSs that are added to the solution work while the rest .CSs are added provide no choice to change the platform?

**Comment by lperron** [comment]
As we are moving to a dotnet core packaging with nuget support.
I think this is obsolete.
