### ISSUE TITLE
CP-Sat throws exception due to zero-weight std::discrete_distribution

### ISSUE THREAD

**Issue by JoelKKelso** [google/or-tools#2040]
**What version of OR-tools and what language are you using?**
Version: v7.6
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-Sat

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
Running a regression test problem with CP-Sat (involves a scheduling problem with a few hundred boolean variables, linear and boolean constraints). This worked in v7.3

Got a _STL_ASSERT in MSVC random called from linear_programming_constraint.cc, here (see line at bottom calling std::discrete_distribution):

 weights.clear();
      for (const auto entry : lp_data_.GetSparseColumn(var_to_eliminate)) {
        const RowIndex row = entry.row();
        const auto status = simplex_.GetConstraintStatus(row);
        if (status == glop::ConstraintStatus::BASIC) continue;
        if (status == glop::ConstraintStatus::FREE) continue;

        // We dissalow all the rows that contain a variable that we already
        // eliminated (or are about to). This mean that we choose rows that
        // form a "triangular" matrix on the position we choose to eliminate.
        if (used_rows[row]) continue;
        used_rows[row] = true;

        // TODO(user): Instead of using FIXED_VALUE consider also both direction
        // when we almost have an equality? that is if the LP constraints bounds
        // are close from each others (<1e-6 ?). Initial experiments shows it
        // doesn't change much, so I kept this version for now. Note that it
        // might just be better to use the side that constrain the current lp
        // optimal solution (that we get from the status).
        bool add_row = false;
        if (status == glop::ConstraintStatus::FIXED_VALUE ||
            status == glop::ConstraintStatus::AT_UPPER_BOUND) {
          if (entry.coefficient() > 0.0) {
            if (dense_cut[var_to_eliminate] < 0) add_row = true;
          } else {
            if (dense_cut[var_to_eliminate] > 0) add_row = true;
          }
        }
        if (status == glop::ConstraintStatus::FIXED_VALUE ||
            status == glop::ConstraintStatus::AT_LOWER_BOUND) {
          if (entry.coefficient() > 0.0) {
            if (dense_cut[var_to_eliminate] > 0) add_row = true;
          } else {
            if (dense_cut[var_to_eliminate] < 0) add_row = true;
          }
        }
        if (add_row) {
          possible_rows.push_back(row);
          weights.push_back(row_weights[row]);
        }
      }
      if (possible_rows.empty()) break;

      const RowIndex row_to_combine =
          possible_rows[std::discrete_distribution<>(weights.begin(),
                                                     weights.end())(*random_)];

The weights vector had a single item with value zero: I presume std::discrete_distribution is unwilling to return a distribution from that (and fair enough). I don't know enough about this to know if it's never supposed to get into that state, or if you can just check to see if weights has total weight zero and in that case just do a uniform distribution.

If needed I could start trying to narrow down a smaller test case, but that might take a while. Tried the same thing twice and got identical result.

Stack trace pic attached.
![CPSatStackTrace](https://user-images.githubusercontent.com/66106522/83225649-d8192a80-a1b2-11ea-936f-ad2111c5c0f0.png)

**Comment by lperron** [comment]
I pushed the fix. Thanks for the report.
