### ISSUE TITLE
Install ortools with Gurobi solver in python venv

### ISSUE THREAD

**Issue by yifanguan** [google/or-tools#2041]
**What version of OR-tools and what language are you using?**
Version: master
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Gurobi
**What operating system (Linux, Windows, ...) and version?**
Linux ubuntu 16.04

Hi, I'm installing python or-tools with Gurobi now.
I follow the instructions listed in [this page](https://developers.google.com/optimization/install/python/source_linux#ubuntu-16.04).

Specifically,

(1) 
make third-party
(2)
vim Makefile.local
UNIX_GUROBI_DIR = /opt/gurobi902
UNIX_LIB_VERSION = 90
(3)
make python

I'm wondering whether it is possible to specify which python will use to build and contain the or-tools packages.
Currently, it uses /usr/bin/python3.5 and I really want to let or-tools packages built with my specific virtual environment python.
Can I do so?

Thank you for your time and help!

Edit: I find out I can only 'import ortools' inside the repo 'or-tools' folder.
Is there any way I can turn this compiled library into a binary, and simply 'import ortools' anywhere I want and put the binary in my virtual env python?

Thank you again!

**Comment by Mizux** [comment]
Hi,

For Gurobi you should define `UNIX_GUROBI_DIR` and `GUROBI_LIB_VERSION`
https://github.com/google/or-tools/blob/5ff76b487a6c2006326765d6417964599eedc8c9/makefiles/Makefile.unix.mk#L101-L104
and
https://github.com/google/or-tools/blob/5ff76b487a6c2006326765d6417964599eedc8c9/makefiles/Makefile.unix.mk#L137-L142

For python you can look at:
https://github.com/google/or-tools/blob/5ff76b487a6c2006326765d6417964599eedc8c9/makefiles/Makefile.unix.mk#L75-L89

So if your venv is loaded then you can pass `UNIX_PYTHON_VER`, there is good chance the shell script will catch the correct include etc... 

you can check using target `detect_python` IIRC i.e.
```sh
make detect_python
```
