### ISSUE TITLE
terminate called after throwing an instance of 'Swig::DirectorException'   what():  Could not get exception message in JavaExceptionMessage

### ISSUE THREAD

**Issue by peerjuettner** [google/or-tools#2042]
**What version of OR-tools and what language are you using?**
Version: v7.6.7691
Language: Java
**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT
**What operating system (Linux, Windows, ...) and version?**
Linux
**What did you do?**
Load model, try solving, recieve error

**What did you expect to see**
Model solution showing

**What did you see instead?**
```
terminate called after throwing an instance of 'Swig::DirectorException'
  what():  Could not get exception message in JavaExceptionMessage
```

Make sure you include information that can help us debug (full error message, model Proto).

Model Proto (minified from whole solution):

[model.txt](https://github.com/google/or-tools/files/4701293/model.txt)

**Anything else we should know about your project / environment**
--

**Comment by lperron** [comment]
Most likely an error in your solution callback.
The model works fine in C++.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 29 mai 2020 à 12:39, Peer Jüttner <notifications@github.com> a
écrit :
