### ISSUE TITLE
Indicator constraint for constraint programming

### ISSUE THREAD

**Issue by sreyas7** [google/or-tools#2043]
using ORTools v7+ in Python on Windows 10

solvers like CPLEX have an indicator function which sets enforces a constraint only if it satisfies a boolean condition, but I couldn't find any function in ORTools CP-SAT.

Please reference it, if it is present.

Thanks,
Sreyas

**Comment by lperron** [comment]
Modeling questions should be asked on the mailing list. 

The answer is here: https://github.com/google/or-tools/blob/master/ortools/sat/doc/channeling.md
