### ISSUE TITLE
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil to field java.nio.Buffer.address

### ISSUE THREAD

**Issue by CervEdin** [google/or-tools#2044]
**What version of OR-tools and what language are you using?**
Version: v7.6.7691
Language: Java 11 (Scala 2.12.4)

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing Solver

**What operating system (Linux, Windows, ...) and version?**
Ubuntu-18.04-64bit

**What did you do?**
n/a

**What did you expect to see**
n/a

**What did you see instead?**

When starting the sbt shell with java 11 I got the following warning
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/erik/.sbt/boot/scala-2.12.4/org.scala-sbt/sbt/1.1.4/protobuf-java-3.3.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
```

**Anything else we should know about your project / environment**
Happy to provide more information if needed.

**Further information**

It seems related to [protobuf issue 3781](https://github.com/protocolbuffers/protobuf/issues/3781) which appears to be a well-known issue. I suspect you are aware of the issue, nevertheless I thought I ought to report it.

**Comment by lperron** [comment]
It seems you have an old version of protobuf installed.
This was corrected in later versions.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
