### ISSUE TITLE
Max Distance as a function of customers on route

### ISSUE THREAD

**Issue by nag96** [google/or-tools#2045]
Hi,

I'm trying to add a constraint to my VRP where max distance that a vehicle can go is based on the number of customers on the route.

dimension_name = 'Distance'
routing.AddDimension(
    transit_callback_index,
    0,  # no slack
    3000,  # vehicle maximum travel distance
    True,  # start cumul to zero
    dimension_name)
distance_dimension = routing.GetDimensionOrDie(dimension_name)
distance_dimension.SetGlobalSpanCostCoefficient(100)

Above is the code to specify a number as maximum distance. I have a requirement to bring it in the as a function of the customers the vehicle serves. Indirectly, I'm trying to bring a time constraint. For suppose, it takes 10 minutes to serve a customer and in total i have 100 minutes for travel with 500 meters per minute speed, the max distance i can go is (100 - num of customer * 10) * 500.

Like 
Max_Distance < (100 - no.of customers on route for every vehicle * 10) * 500

Thanks.

**Comment by lperron** [comment]
Please use the mailing list.

**Comment by optimaster69** [comment]
Hi,

I think putting max span constraint on time dimension would be a right way to solve it.

-> You can create a time dimension, similar to distance dimension
-> Transit call-back (i,j) should return service time at node i (10 minutes in your case) + transit time from i to j
-> Put a max span constraint on time dimension using [https://developers.google.com/optimization/reference/python/constraint_solver/pywrapcp#setspancostcoefficientforallvehicles](this)
