### ISSUE TITLE
Minimizing average time to delivery

### ISSUE THREAD

**Issue by thisisjeffchen** [google/or-tools#2046]
**What language and solver does this apply to?**
All, Python, Java, C#, C++ / CP-SAT, Routing, Linear Solver

All - we're using the python wrapper for or-tools though

**Describe the problem you are trying to solve.**
Hello - this library is great! 
We are interested in minimizing the **average time** to delivery given a fixed number of drivers and deliveries. Our current solution is based on the example https://developers.google.com/optimization/routing/vrp, with arbitrary return depot locations by zeroing out distance_matrix[i][0] = 0

But we cannot minimize the average time to delivery. Both time and distance accumulation methods, it minimizes the total. Here is an example with 3 deliveries:

A_Near --> B_Far --> C_Middle
10 mins --> 50 mins --> 60 mins
(time shown is total time from depot)

This is often the solution found, which minimizes the total travel time, but C_middle is getting her delivery very late.

**Describe the solution you'd like**

We would like 
A_Near --> C_middle --> B_Far
10 mins --> 20 mins --> 65 mins

**Describe alternatives you've considered**
We tried to use distance as a proxy to total time, but that introduces other issues as we have many drivers in flight and algorithm now will favor giving some drivers a slightly longer route to minimize the route of other drivers.

We've also tried constraining the time to delivery from the depot based on a multiple of the distance. eg the shorter distance deliveries have an earlier time window using the data['time_windows'] field. But this is tricky because it involves setting a magical multiple - if we set it too high, then the algorithm does not optimize correctly, if we set it too low, the algorithm will not find a solution.

These seem like hacks and we really just need to just have the algorithm minimize average time for delivery directly.

**Additional context**
Here's a snippet of our code:

```python
 # Create and register a transit callback.
    def distance_callback(from_index, to_index):
        """Returns the distance between the two nodes."""
        # Convert from routing variable Index to distance matrix NodeIndex.
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return data[route_matrix][from_node][to_node]

    transit_callback_index = routing.RegisterTransitCallback(distance_callback)

    # Define cost of each arc.
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

    # Add Distance constraint.
    dimension_name = 'Duration'
    routing.AddDimension(
        transit_callback_index,
        0,  # no slack
        3600,  # vehicle maximum time
        True,  # start cumul at zero
        dimension_name)
    distance_dimension = routing.GetDimensionOrDie(dimension_name)
    distance_dimension.SetGlobalSpanCostCoefficient(100)

    # Setting first solution heuristic.
    search_parameters = pywrapcp.DefaultRoutingSearchParameters()
    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)

    # Solve the problem.
    solution = routing.SolveWithParameters(search_parameters)
```

**Comment by Mizux** [comment]
You should ask on the mailing list instead !

My 2 cents.
there is no direct API for what you looking for but you can try to set an soft upper bound on a time dimension for each delivery nodes...
https://github.com/google/or-tools/blob/6356303a3d30e55a09edafdf50991eec23d4620e/ortools/constraint_solver/routing.h#L2298-L2307
For finding "good" upper bound you can use as first heuristic: the travel time from depot to the node * coefficient.

Hope you'll manage to make it work !
