### ISSUE TITLE
Importing tensorflow breaks ortools

### ISSUE THREAD

**Issue by hoefling** [google/or-tools#2047]
**What version of OR-tools and what language are you using?**
Version: 7.6.7691
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

None as the import segfaults already.

**What operating system (Linux, Windows, ...) and version?**

MacOS Catalina 10.15.5

**What did you do?**

```sh
$ python3.8 -m venv tstenv
$ source tstenv/bin/activate
$ pip install ortools tensorflow
$ python -c "import tensorflow as tf; from ortools.algorithms.pywrapknapsack_solver import KnapsackSolver"
[libprotobuf ERROR /Users/corentinl/work/master/dependencies/sources/protobuf-3.11.2/src/google/protobuf/descriptor_database.cc:394] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL /Users/corentinl/work/master/dependencies/sources/protobuf-3.11.2/src/google/protobuf/descriptor.cc:1356] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
[1]    6812 abort      python -c
```

**What did you expect to see**

No segfault I guess :-)

**What did you see instead?**
See the error log above.

Make sure you include information that can help us debug (full error message, model Proto).

```sh
$ pip show protobuf | grep -i version
Version: 3.12.2
```

**Anything else we should know about your project / environment**

Nothing special, Python 3.8 installed from www.python.org/downloads, but I doubt it's an issue here. Rest installed from PyPI: `tensorflow==2.2.0`, `ortools==7.6.7691`.

**Comment by hoefling** [comment]
Notice that reversing the imports produces no error:

```sh
$ python -c "from ortools.algorithms.pywrapknapsack_solver import KnapsackSolver; import tensorflow as tf; print('This is fine')"
This is fine
```

**Comment by hoefling** [comment]
Also notice the issue emerges only when importing `pywrapknapsack_solver` as e.g. importing `ortools.algorithms` works just fine:

```sh
$ python -c "import tensorflow as tf; import ortools.algorithms; print('This is fine')"
This is fine
```

**Comment by hoefling** [comment]
May be related to tensorflow/tensorflow#35573

**Comment by CervEdin** [comment]
possibly related
https://github.com/google/or-tools/issues/1830

**Comment by Mizux** [comment]
we still use protobuf 3.11.2 while tensorflow last release seems to use the last release...
