### ISSUE TITLE
Cp-Sat python AddAbsEquality drastically increases memory consumption after some time

### ISSUE THREAD

**Issue by Phibedy** [google/or-tools#2048]
**What version of OR-tools and what language are you using?**
Version: v7.6.
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT
**What operating system (Linux, Windows, ...) and version?**
ubuntu 20.04

**What did you do?**
If I use `AddAbsEquality` instead of manually calculating the abs using a boolean, the optimization starts to use a huge amount of memory after some time.
I am using 7 threads, taking the abs manually needs about 7gb of ram, if I use `AddAbsEquality` instead it goes after finding about 200 solutions (60 Minutes) from 7gb of ram to 32gb of ram without finding any new solution in about one minute.

There are about 50 `AddAbsEqualitys` which have to be minimized in the end

Code difference:
Using Abs:
```python3
slots = booleanArray
costRaw = model.NewIntVar(-target_slots,max_slots-target_slots,"")
model.Add(costRaw == sum(slots)-target_slots)
costAbs = model.NewIntVar(0,max(target_slots,max_slots-target_slots),"")
model.AddAbsEquality(costAbs,costRaw)
.... minimize a sum of costAbs
```

Custom abs:
```python3
slots = booleanArray
smallerZero = model.NewBoolVar("")
model.Add(sum(slots) < target_slots).OnlyEnforceIf(smallerZero)
model.Add(sum(slots) >= target_slots).OnlyEnforceIf(smallerZero.Not())
costAbs = model.NewIntVar(0,max(target_slots,max_slots-target_slots),"")
model.Add(costAbs == target_slots-sum(slots)).OnlyEnforceIf(smallerZero)
model.Add(costAbs == sum(slots)-target_slots).OnlyEnforceIf(smallerZero.Not())
.... minimize a sum of costAbs
```

I could not come up with a small fully working example but I can share the two models if you need it :)

**Comment by lperron** [comment]
Can you send us a model ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
No news. Closing. Please reopen if you can provide use with a model.
