### ISSUE TITLE
ModelProto exceeds maximum protobuf size

### ISSUE THREAD

**Issue by luizvieira82** [google/or-tools#2049]
**What version of OR-tools and what language are you using?**
Version: 7.6.7691.
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT
**What operating system (Linux, Windows, ...) and version?**
Windows
**What did you do?**
Running problem with different sizes, from 109.500 up to > 1960000 variables and several constraints.
For small problems the solver works fine, even some large problems are handled without any noticeble issues. However, when this large special problem instance is tested, solver throws this error. "Message operations research.sat.Cp ModelProto exceeds maximum protobuf size".
Not sure if it is a issue or some limitation I reached.

**What did you expect to see**
Started optimization.

**What did you see instead?**
Error on output regarding protobuf size.

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
This is a protobuf limitation. There is nothing I can do about it. You can create an issue on their site.

**Comment by lperron** [comment]
You can try to cheat by making sure all variables are unnamed.
