### ISSUE TITLE
C# CP-SAT solver using doubles and floats

### ISSUE THREAD

**Issue by therollingbird** [google/or-tools#2050]
**What language and solver does this apply to?**
C#/CP-SAT,

**Describe the problem you are trying to solve.**
when creating models for CP sat most of my coefficients are doubles/decimals/floats and CP sat only allows long. if i convert the coefficient become less meaningful mainly for objectives i.e. 
instead of 
model.AddTermToObjective(variable, 30.55); i am forced to use 
model.AddTermToObjective(variable, Convert.ToInt64(30.55)); this will convert 30.55 to 31 and distorts the results  another example would be 

LinearExpr lhs  = variable* 122.33 i am forced to used the convert to long 
LinearExpr lhs  = variable* Convert.ToInt64(122.33) which would be variable * 122 and does not take into account the decimal 

**Describe the solution you'd like**
to include types of doubles/decimals or floats to that we can write expressions like 
LinearExpr lhs  = variable* 122.33
i know Gurobi allows the decimals 
when i test with Gurobi vs Or Tools creating a lineup solution the first few results are the same but then they start to differ 

**Describe alternatives you've considered**

**Additional context**

**Comment by CervEdin** [comment]
Gurobi is a different kind of solver.

With a CP solver you often convert decimals to integers by multiplying with
the precision you want instead.

Ie, of you need 30.55 instead of 31. Just scale everything relevant by a
factor of 100. So you have a long 3055 instead

**Comment by lperron** [comment]
CP-SAT supports objective scaling. Unfortunately not in C# :-(

So multiply all your coefficients by 1000 before rounding. And divide the
objective value by 1000 when using it.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by therollingbird** [comment]
@lperron and @CervEdin thank you for pointing me to the right directions i just implemented a utilities code to do that  and ran the tests again the 20 tests i ran the results are now similar to Gurobi results for both optimal and feasible solutions the code is below if there is a better way of doing this let me know and hope this helps others 

  //https://github.com/google/or-tools/issues/2050
        public long ScaleToLong(double number)
        {
            double n = number;
            n = n * 1000;
            long l = Convert.ToInt64(n);
            return l;
        }

        public double ScaleToDouble(int roundBy, long number)
        {
            double n = number;
            n = n / 1000;
            return Math.Round(n, roundBy);
        }
