### ISSUE TITLE
Minimum loading for each truck?

### ISSUE THREAD

**Issue by kanwarnain** [google/or-tools#2052]
Hi, I am working on setting up a CVRPTW code. I want each vehicle to carry at least 50% of its capacity. I have different costs associated with each vehicle, so obviously the optimiser will prefer using vehicles with lesser costs. But I want to use all vehicles atleast to 50% of their max capacity (the total demand for customers is more than sum of 50% capacities of all vehicles). Please help how to achieve this. 

PS: I am a newbie to ortools. 

Using python 3.7

**Comment by lperron** [comment]
Please use the mailing list.

**Comment by optimaster69** [comment]
You can put soft lower bound on cumulvar at vehicle start location.
[https://developers.google.com/optimization/reference/python/constraint_solver/pywrapcp#setcumulvarsoftlowerbound](url)
