### ISSUE TITLE
Building for Java with cmake on Windows

### ISSUE THREAD

**Issue by RuiPacas** [google/or-tools#2053]
**What version of OR-tools and what language are you using?**
Version: master - https://github.com/google/or-tools/commit/b58a4607b4f12f1c0486d76a1d147477cc30e7bf

Language: Java

Building for: Visual Studio 16 2019
Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.

**What did you do?**
1. Downloaded Master .zip
2. Extracted
3. Opened terminal on ...\or-tools-master\or-tools-master
4. Executed "cmake -S. -Bbuild -DBUILD_JAVA=ON"

**What did you expect to see**
I was expecting to get the binaries to add to my IntellIJ project

**What did you see instead?**
Error Message

Make sure you include information that can help us debug (full error message, model Proto).
I'll leave CMakeOutput.log and CMakeError.log to be consulted.
[CMakeError.log](https://github.com/google/or-tools/files/4729176/CMakeError.log)
[CMakeOutput.log](https://github.com/google/or-tools/files/4729179/CMakeOutput.log)

**Comment by Mizux** [comment]
after investigating your issue:

```
Performing C++ SOURCE FILE Test COMPILER_HAS_DEPRECATED_ATTR failed with the following output:
Change Dir: D:/Downloads/or-tools-master/or-tools-master/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe cmTC_d7b50.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) C/C++ Optimizing Compiler Version 19.21.27702.2 for x64
  src.cxx
  Copyright (C) Microsoft Corporation.  All rights reserved.
  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D COMPILER_HAS_DEPRECATED_ATTR /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_d7b50.dir\Debug\\" /Fd"cmTC_d7b50.dir\Debug\vc142.pdb" /Gd /TP /errorReport:queue "D:\Downloads\or-tools-master\or-tools-master\build\CMakeFiles\CMakeTmp\src.cxx"
D:\Downloads\or-tools-master\or-tools-master\build\CMakeFiles\CMakeTmp\src.cxx(1,16): error C2065:  '__deprecated__': undeclared identifier [D:\Downloads\or-tools-master\or-tools-master\build\CMakeFiles\CMakeTmp\cmTC_d7b50.vcxproj]
D:\Downloads\or-tools-master\or-tools-master\build\CMakeFiles\CMakeTmp\src.cxx(1,31): error C4430:  missing type specifier - int assumed. Note: C++ does not support default-int [D:\Downloads\or-tools-master\or-tools-master\build\CMakeFiles\CMakeTmp\cmTC_d7b50.vcxproj]
D:\Downloads\or-tools-master\or-tools-master\build\CMakeFiles\CMakeTmp\src.cxx(1,37): error C2448:  '__attribute__': function-style initializer appears to be a function definition [D:\Downloads\or-tools-master\or-tools-master\build\CMakeFiles\CMakeTmp\cmTC_d7b50.vcxproj]


Source file was:
__attribute__((__deprecated__)) int somefunc() { return 0; }
    int main() { return somefunc();}
```

It seems CMake try to check if gcc like `deprecated` attribute is supported.
Can you provide us the version of CMake you are using ? 

The problem seems to come form your CMkae/VSC installation during CMake internal pre check than on ortools directly...

**Comment by RuiPacas** [comment]
I'm using cmake version 3.17.3

**Comment by Mizux** [comment]
can you try master with the following command (which will also build dependencies):
```sh
cmake -S. -Bbuild -DBUILD_DEPS=ON -DBUILD_JAVA=ON
```
