### ISSUE TITLE
How can we solve 0-1 knapsack with conflicting items ?

### ISSUE THREAD

**Issue by vpsinghg** [google/or-tools#2054]
**What language and solver does this apply to?**
All, Python, Java, C#, C++ / CP-SAT, Routing, Linear Solver

**Describe the problem you are trying to solve.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CervEdin** [comment]
Modelling questions go in the mailing list
https://groups.google.com/forum/#!forum/or-tools-discuss

**Comment by lperron** [comment]
Indeed
