### ISSUE TITLE
Unix makefile mention g++ instead of c++

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#2055]
**What version of OR-tools and what language are you using?**
Version: v7.6
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Debian 10

**What did you do?**
Compile or-tools with clang.
Via update-alternatives I updated cc and c++ commands to point to clang compiler.

make third_party
- clang compiler used
make cc
- g++ compiler used.

**What did you expect to see**
Use clang c++ compiler instead of g++ during compilation of or-tools.

**What did you see instead?**
make cc used g++ compiler.

I found that the problem can be solved by replacing string 'g++' with 'c++' in Makefile.unix.mk file.

**Comment by lperron** [comment]
We only support default compilers for each platform
On debian 10, default (as defined by build-essential) is gcc.

**Comment by gregy4** [comment]
This is not wise approach, in mac is used clang, in linux gcc and windows uses microsoft compiler. Any problem related to compiler and not os will be hard to identify. And problems are already here, minimally on windows platform since version 7.5.

In debian part of or-tools build uses cc and c++, and other part g++. This is also wrong since build-essential package doesn't guarantee that gcc is default compiler.

Maybe approach done by chrome browser, use clang on every platform for offical builds. And still leave possibility to use different compiler if possible like my bug report that make different build phases compatible and using same compiler.

**Comment by Mizux** [comment]
you should take a look at the cmake or bazel build then...

**Comment by gregy4** [comment]
Bazel build doesn't work in Windows (glog library wants unistd.h that is not present) so cmake looks like the only one possibility.
