### ISSUE TITLE
Presolve Platform-Dependency

### ISSUE THREAD

**Issue by prissky** [google/or-tools#2056]
**What version of OR-tools and what language are you using?**
Version: v7.6
Language: C++
Solver: CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Win 10, Debian 10, macOS 10

**What did you do?**
On each platform: Loaded model.proto. Presolved. Saved presolved model.

**What did you expect to see?**
Platform-independent deterministic presolve.

**What did you see instead?**
Each presolved model differs in order of constraints. 
[Proto_files_after_presolve_comparison.zip](https://github.com/google/or-tools/files/4735568/Proto_files_after_presolve_comparison.zip)

I suspect such dissimilarity (bug?) might affect subsequent solve.

**Comment by lperron** [comment]
It seems the max clique heuristics is platform dependent. We will investigate further.

**Comment by prissky** [comment]
Thank you. As it turns out, presolved models differ not only among platforms and not only in the order of constraints. Attached bellow, you can find model presolved on Mac by OR-Tools v7.6 compiled by Clang and by bazel. Number of constraints there is also different.
[issue1918.zip](https://github.com/google/or-tools/files/4770331/issue1918.zip)

**Comment by lperron** [comment]
No plan to fix these. It is clearly in the clique max algo.
Note that search is also platform specific, so there is no point in fixing these.
