### ISSUE TITLE
[Routing Solver] Unknown Fleet size/ Fleet size optimization/ Infinite fleet size

### ISSUE THREAD

**Issue by optimaster69** [google/or-tools#2062]
Hi,

I'm trying to solve the CVRPTW with multiple-vehicle types (~42). In my case fleet size/ number of vehicles of each type is unknown. I'm expecting solver to solve for most optimal fleet size and their routes.

Initially I tried to model this problem by creating large number of vehicles for each type and their fixed costs. I expected solver will try to minimize fixed cost of vehicles and distance costs. But in that case solver is unable find an initial solution in significant duration. I think that is because large number of vehicles increases number of possible insertions to a significantly and hence solver fails to explore all possible insertions. i.e: If vehicle type A has 100 vehicles. During insertion phase the solver is trying to insert a job in all 100 vehicles. But since all the empty routes/vehicles are identical we should check insertion cost of all filled vehicles and 1 empty vehicle.

Jsprit library provides an option to define INFINITE fleet size. In this case solver assumes each vehicles type has infinite copy. I think during insertion phase solver tries to add a job in already created routes or 1 empty route of each vehicle type.

**EDIT1:**  I have kept all the jobs (~240) as optional. When I use 10 vehicles of each type (total 420 vehicles) solver returns a solutions with all jobs unassigned after 1 hour. When I reduce number of vehicles of each type to 1(total 42 vehicles), solver returns a feasible solution with 152 unassigned job within 60 seconds.

**EDIT2** When I tried to solve it with 1 vehicle type and 200 copies, solver returns a solutions with all jobs unassigned after 1 hour. When I reduce number of vehicles to 60, I get a solution with all jobs assigned within 2 minutes.

**Comment by lperron** [comment]
Please use the mailing list.

**Comment by Mizux** [comment]
seems related to `vehicle_classes` did you look at https://github.com/google/or-tools/blob/5ff76b487a6c2006326765d6417964599eedc8c9/ortools/constraint_solver/routing.h#L3367-L3374
Personally I didn't play with this feature yet but seems related to what you're looking for

**Comment by optimaster69** [comment]
Thanks.
Since I'm very new to this library I haven't explored insertion heuristics.

I think this is not being taken care by the solver. According to my tests, solver was able to find solution when there 60 vehicles of 1 type. When I increased the vehicles to 200 of the same type, no solution was returned.
