### ISSUE TITLE
Python Basics course_1_assessment_11

### ISSUE THREAD

**Issue by patrickzurich** [google/or-tools#2064]
seqmut-1-4: What will be the value of a after the following code has executed?
a = ["holiday", "celebrate!"]
quiet = a
quiet.append("company")
The value of a will be

I not understand so easy, but I not understand. What is the right answer. And works. I want make finish. This first Certificate only that then I am finish. Thanks for help.

**Comment by peiningtsou** [comment]
I couldn't get the answer for the simple question, help!

**Comment by lperron** [comment]
this is not a python 101 forum.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le dim. 28 juin 2020 à 06:05, peiningtsou <notifications@github.com> a
écrit :

**Comment by royaldevivek** [comment]
The value of a will be

["holiday", "celebrate!", "company"]

**Comment by peiningtsou** [comment]
> The value of a will be
> 
> ["holiday", "celebrate!", "company"]

I know the answer, just didn't know how to get the right code.
