### ISSUE TITLE
Multi-objective optimization - VRP

### ISSUE THREAD

**Issue by mwijaya3** [google/or-tools#2066]
**What language and solver does this apply to?**
Python /  Routing

**Describe the problem you are trying to solve.**
Multi-objective optimization for VRP with distance and priority (soft) as the objective

**Describe the solution you'd like**
Add priority as soft constraints/objectives

**Describe alternatives you've considered**
I have read through issues and googling but the closest I have seen is the:
* VRPTW example (although we enforced the time windows within certain range)
* Job shop: [link](https://github.com/google/or-tools/issues/1727)

**Additional context**
See the question that I posted on [stackexchange](https://or.stackexchange.com/questions/4362/priority-list-constraint).

Any example or similar issue in Python that I can refer to? Thanks in advance!

**Comment by lperron** [comment]
Modeling questions should go on the mailing list.
