### ISSUE TITLE
Routing: ArcCost(start, end) always return zero for any vehicle even if start and end node are not the same.

### ISSUE THREAD

**Issue by Kiros0** [google/or-tools#2067]
**What version of OR-tools and what language are you using?**
Version: 7.6.7691
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing Solver

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
I copied the exact example code from the following link:
https://developers.google.com/optimization/routing/routing_tasks#setting-start-and-end-locations-for-routes

And then added one more vehicle with starting point 0 and ending point 0 by chaning lines 81, 82 and 83 into the following:
    data['num_vehicles'] = 5
    data['starts'] = [1, 2, 15, 16, 0]
    data['ends'] = [0, 0, 0, 0, 0]

And I added this on line 102:
print(routing.IsVehicleUsed(vehicle=vehicle_id, assignment=solution))

**What did you expect to see**
I expected to see a different solution to the problem in which all vehicles with a route would have the corresponding distances printed.

**What did you see instead?**
Vehicles 1 and 2 do have routes, 2 -> 0 and 15 -> 0 which both have a distance according to the distance matrix, but the calculation of Distance of the route says 0. In addition to that, the routing.IsVehicleUsed function also says that the vehicles are not in use.

Not sure whether this is a bug or that I'm missing something here.

Printed output:
True
Route for vehicle 0:
 1 ->  4 ->  3 ->  7 ->  5 -> 0
Distance of the route: 1392m

False
Route for vehicle 1:
 2 -> 0
Distance of the route: 0m

False
Route for vehicle 2:
 15 -> 0
Distance of the route: 0m

True
Route for vehicle 3:
 16 ->  14 ->  13 ->  12 ->  11 -> 0
Distance of the route: 1346m

True
Route for vehicle 4:
 0 ->  8 ->  6 ->  10 ->  9 -> 0
Distance of the route: 1392m

Maximum of the route distances: 1392m

**Anything else we should know about your project / environment**
My goal is to solve a problem where some vehicles start at the depot and others have a different starting location.

[example_code.txt](https://github.com/google/or-tools/files/4766656/example_code.txt)

**Comment by Mizux** [comment]
it seems the method
```python
routing.GetArcCostForVehicle(start, end, vehicle_id)
```
will return `0`

**Comment by Mizux** [comment]
for vehicle_id in range(data['num_vehicles']):
        start = routing.Start(vehicle_id)
        end = routing.End(vehicle_id)
        distance = routing.GetArcCostForVehicle(start, end, vehicle_id)
        print(f"Vehicle {vehicle_id}, dst(start, end): {distance}")

**Comment by Mizux** [comment]
I think the solver use a cost of zero since going from start to end is a mandatory move so you shouldn't take it into account.

Open question [Work in Progress] supposing this schema:
```
[2] ---- 100m ---- [0,1] ---500m---- [4] --500m--- [3]
```
with:
start: [0, 1]
end: [2, 3]

Optimal route should be 1 -> 4 -> 3 since it add zero to mandatory 1->3 route

**Comment by Kiros0** [comment]
In addition to this, because ArcCost(start, end) returns zero for any vehicle even if start and end node are not the same, vehicle penalties are also not taken into account:

    # Set penalty for vehicle use
    routing.SetFixedCostOfAllVehicles(100)

Will not apply to these vehicles. It seems as if these vehicles are given a predecided route from start to end and are not considered when solving the problem.

**Comment by Mizux** [comment]
A vehicle go from start to end without visiting any location is considered unused. This definition Look Good To Me even if vehicle need to travel from start location to end location but using cost zero seems odd to me at least when comparing node insertion...

**Comment by Mizux** [comment]
After investigation, I found it.
You must "enable empty route cost":

```python
    for vehicle_id in range(data['num_vehicles']):
        routing.ConsiderEmptyRouteCostsForVehicle(True, vehicle_id)
```

**Comment by Mizux** [comment]
note @Kiros0 in your case routes become:
```
True
Route for vehicle 0:
 1 ->  4 ->  3 ->  7 -> 0
Distance of the route: 1004m

True
Route for vehicle 1:
 2 ->  6 ->  8 ->  5 -> 0
Distance of the route: 936m

True
Route for vehicle 2:
 15 ->  11 ->  12 ->  13 -> 0
Distance of the route: 936m

True
Route for vehicle 3:
 16 ->  10 -> 0
Distance of the route: 890m

True
Route for vehicle 4:
 0 ->  14 ->  9 -> 0
Distance of the route: 936m
```

full code:
```python
#!/usr/bin/env python3
"""Simple Vehicles Routing Problem."""

from __future__ import print_function
from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp


def create_data_model():
    """Stores the data for the problem."""
    data = {}
    data['distance_matrix'] = [
        [
            0, 548, 776, 696, 582, 274, 502, 194, 308, 194, 536, 502, 388, 354,
            468, 776, 662
        ],
        [
            548, 0, 684, 308, 194, 502, 730, 354, 696, 742, 1084, 594, 480, 674,
            1016, 868, 1210
        ],
        [
            776, 684, 0, 992, 878, 502, 274, 810, 468, 742, 400, 1278, 1164,
            1130, 788, 1552, 754
        ],
        [
            696, 308, 992, 0, 114, 650, 878, 502, 844, 890, 1232, 514, 628, 822,
            1164, 560, 1358
        ],
        [
            582, 194, 878, 114, 0, 536, 764, 388, 730, 776, 1118, 400, 514, 708,
            1050, 674, 1244
        ],
        [
            274, 502, 502, 650, 536, 0, 228, 308, 194, 240, 582, 776, 662, 628,
            514, 1050, 708
        ],
        [
            502, 730, 274, 878, 764, 228, 0, 536, 194, 468, 354, 1004, 890, 856,
            514, 1278, 480
        ],
        [
            194, 354, 810, 502, 388, 308, 536, 0, 342, 388, 730, 468, 354, 320,
            662, 742, 856
        ],
        [
            308, 696, 468, 844, 730, 194, 194, 342, 0, 274, 388, 810, 696, 662,
            320, 1084, 514
        ],
        [
            194, 742, 742, 890, 776, 240, 468, 388, 274, 0, 342, 536, 422, 388,
            274, 810, 468
        ],
        [
            536, 1084, 400, 1232, 1118, 582, 354, 730, 388, 342, 0, 878, 764,
            730, 388, 1152, 354
        ],
        [
            502, 594, 1278, 514, 400, 776, 1004, 468, 810, 536, 878, 0, 114,
            308, 650, 274, 844
        ],
        [
            388, 480, 1164, 628, 514, 662, 890, 354, 696, 422, 764, 114, 0, 194,
            536, 388, 730
        ],
        [
            354, 674, 1130, 822, 708, 628, 856, 320, 662, 388, 730, 308, 194, 0,
            342, 422, 536
        ],
        [
            468, 1016, 788, 1164, 1050, 514, 514, 662, 320, 274, 388, 650, 536,
            342, 0, 764, 194
        ],
        [
            776, 868, 1552, 560, 674, 1050, 1278, 742, 1084, 810, 1152, 274,
            388, 422, 764, 0, 798
        ],
        [
            662, 1210, 754, 1358, 1244, 708, 480, 856, 514, 468, 354, 844, 730,
            536, 194, 798, 0
        ],
    ]
    data['num_vehicles'] = 5
    data['starts'] = [1, 2, 15, 16, 0]
    data['ends'] = [0, 0, 0, 0, 0]
    return data


def print_solution(data, manager, routing, solution):
    """Prints solution on console."""
    max_route_distance = 0
    for vehicle_id in range(data['num_vehicles']):
        index = routing.Start(vehicle_id)
        plan_output = 'Route for vehicle {}:\n'.format(vehicle_id)
        route_distance = 0
        while not routing.IsEnd(index):
            plan_output += ' {} -> '.format(manager.IndexToNode(index))
            previous_index = index
            index = solution.Value(routing.NextVar(index))
            distance = routing.GetArcCostForVehicle(previous_index, index, vehicle_id)
            route_distance += distance
        plan_output += '{}\n'.format(manager.IndexToNode(index))
        plan_output += 'Distance of the route: {}m\n'.format(route_distance)
        print(routing.IsVehicleUsed(vehicle=vehicle_id, assignment=solution))
        print(plan_output)
        max_route_distance = max(route_distance, max_route_distance)
    print('Maximum of the route distances: {}m'.format(max_route_distance))


def main():
    """Entry point of the program."""
    # Instantiate the data problem.
    data = create_data_model()

    # Create the routing index manager.
    manager = pywrapcp.RoutingIndexManager(len(data['distance_matrix']),
                                           data['num_vehicles'], data['starts'],
                                           data['ends'])

    # Create Routing Model.
    routing = pywrapcp.RoutingModel(manager)

    for vehicle_id in range(data['num_vehicles']):
        routing.ConsiderEmptyRouteCostsForVehicle(True, vehicle_id)


    # Create and register a transit callback.
    def distance_callback(from_index, to_index):
        """Returns the distance between the two nodes."""
        # Convert from routing variable Index to distance matrix NodeIndex.
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return data['distance_matrix'][from_node][to_node]

    transit_callback_index = routing.RegisterTransitCallback(distance_callback)

    # Define cost of each arc.
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

    # Add Distance constraint.
    dimension_name = 'Distance'
    routing.AddDimension(
        transit_callback_index,
        0,  # no slack
        2000,  # vehicle maximum travel distance
        True,  # start cumul to zero
        dimension_name)
    distance_dimension = routing.GetDimensionOrDie(dimension_name)
    distance_dimension.SetGlobalSpanCostCoefficient(100)

    # Setting first solution heuristic.
    search_parameters = pywrapcp.DefaultRoutingSearchParameters()
    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)

    # Solve the problem.
    solution = routing.SolveWithParameters(search_parameters)

    # Print solution on console.
    print("\n----------------\n")
    if solution:
        print_solution(data, manager, routing, solution)

    for vehicle_id in range(data['num_vehicles']):
        start = routing.Start(vehicle_id)
        end = routing.End(vehicle_id)
        distance = routing.GetArcCostForVehicle(start, end, vehicle_id)
        print(f"Vehicle {vehicle_id}, dst(start, end): {distance}")

if __name__ == '__main__':
    main()
```

**Comment by Kiros0** [comment]
@Mizux Thank you for the quick responses, that does indeed resolve it!

**Comment by Charan-S-Salian** [comment]
> @Mizux Thank you for the quick responses, that does indeed resolve it!
> 
> Only this part I do not yet fully understand:
> _IIRC fixed cost is implemented as if (nextVar(Start) != End) then FixedCost is applied._
> 
> What would be a good way to implement a cost for a vehicle that starts end ends at given start and end nodes without visiting other nodes inbetween (so when IsVehicleUsed == False) ?
> 
> Take for example this one:
> False
> Route for vehicle 0:
> 0 -> 2
> Distance of the route: 200m

@Mizux  
The problem of **IsVehicleUsed == False** still persists when the The Vehicle travels from a start node to end node  _without visiting other nodes inbetween._


When I use the below case in the final code shared by you,

    data['num_vehicles'] = 6
    data['starts'] = [1, 2, 15, 16, 0, 5]
    data['ends'] = [0, 0, 0, 0, 1, 7]
           return data

I get the following output:

----------------

True
Route for vehicle 0:
 1 ->  4 ->  3 -> 0
Distance of the route: 1004m

True
Route for vehicle 1:
 2 ->  10 ->  9 -> 0
Distance of the route: 936m

True
Route for vehicle 2:
 15 ->  11 ->  12 ->  13 -> 0
Distance of the route: 936m

True
Route for vehicle 3:
 16 ->  14 -> 0
Distance of the route: 662m

**False
Route for vehicle 4:
 0 -> 1**
Distance of the route: 548m

True
Route for vehicle 5:
 5 ->  6 ->  8 -> 7
Distance of the route: 764m

Maximum of the route distances: 1004m


**Could you please shed some light on this issue?**
