### ISSUE TITLE
GetArcCostForVehicle returning 0 when it's not

### ISSUE THREAD

**Issue by nag96** [google/or-tools#2068]
Language: Python
Solver: Routing Solver
OS: Windows

I'm trying to optimize routes for cvrp with arbitrary starts (some from depot itself) and ends at depots. I have 30 vehicles and 99 nodes.

31 147
test callback:1623
31 147 29
test GetArcCost:0
Route for vehicle 29:
 31 Load(3684797) ->  0 Load(3684797)
Distance of the route: 0m
Load of the route: 3684797

Above is the output of vehicle 29. I have referred to the issue https://github.com/google/or-tools/issues/1035 and tried to print it. My distance matrix is in integer format.

63 145
test callback:10331
63 145 27
test GetArcCost:10331
Route for vehicle 27:
 16 Load(1486166) ->  45 Load(2814598) ->  73 Load(5030497) ->  78 Load(7537779) ->  79 Load(8598133) ->  54 Load(9786762) ->  95 Load(10575325) ->  44 Load(12006491) ->  63 Load(13881831) ->  0 Load(13881831)
Distance of the route: 1047265m
Load of the route: 13881831

For vehicle 29, getArcCost for 31, 147 should be 1623 as given by callback. Instead, through getArcCostForVehicle i get it as 0. Even if the vehicle is travelling for only one point, the distance should get calculated.

Where as for vehicle 27, getArcCost of 63, 145 is equal to its callback.

Is it that if the vehicle goes to the depot directly, the distance calculated is zero? Or is it a bug? How can I get a workaround for this?

**Comment by nag96** [comment]
@Mizux Could you please suggest a workaround for my problem? I'm trying to minimize the number of vehicles by assigning penalty to a vehicle used but as mentioned in the above scenario, because distance is zero, even vehicle penalty is also not being considered. Can you suggest a way add penalties for all the vehicles not starting from depot by default even if it directly goes to depot. This can solve my issue.

**Comment by lperron** [comment]
This is a modeling question. Please use the mailing list.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
