### ISSUE TITLE
multi dimensional multi knapsacks model example

### ISSUE THREAD

**Issue by MahaZaid** [google/or-tools#2070]
**What language and solver does this apply to?**
All/ CP-SAT, Routing, Linear Solver

the problem Is that I need a model with 4 constraints:
- same item cannot be in the same bin more than once
- each item has a frequency (items with higher frequency should exist in the bins more than those with lower frequencies)
- each item has a weight (a number representing the importance of the item, so those with higher weight should be added first)
- minimum no. of bins between the existence of the same item in different bins

And also each bin has 1 constrains: 
- each bin can take up to X items.

I couldn't find any example related to multiple dimensions knapsack, and I am confused on how I should add these constraints

**Comment by Mizux** [comment]
https://groups.google.com/forum/#!topic/or-tools-discuss/cjA1D0LI-pY
