### ISSUE TITLE
Can allowed delivery time be modelled?

### ISSUE THREAD

**Issue by mo-zed** [google/or-tools#2071]
In any language, can OR-Tools add allowed delivery time dimension to the solver? The problem would be for example with emergency services, an organ can be in transport for only 30 minutes and not more.

Can this be solved by adding another time dimension as in allowed cumulative time at the point of delivery?

**Comment by Mizux** [comment]
You should use the mailing list for this kind of question.

Supposing you have a Pickup and Delivery node for each organ transport.
You can add a "Duration" dimension which will count duration from point A to B.
 
I think you can add a constraint on the CumulVar, pseudo code:
```python
pickup = manager.NodeToIndex(Pickup_idx)
delivery = manager.NodeToIndex(Delivery_idx)
routing.solver().Add(
  duration_dimension.CumulVar(delivery) <=
  duration_dimension.CumulVar(pickup) + 30 )
```

**Comment by mo-zed** [comment]
I'm sorry for not using the right channels as I'm new to Github. And thanks for the reply. That confirms the solution.
