### ISSUE TITLE
Building of or-tools with bazel on Windows and Clang

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#2072]
**What version of OR-tools and what language are you using?**
Version: v7.7
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
Building of or-tools with bazel 3.2.0, msys2-x86_64-20200602.exe and clang-cl (llvm 10).

bazel build //... --compiler=clang-cl

**What did you expect to see**
Successful build of or-tools with clang compiler and if possible also with vs c++ compiler.

**What did you see instead?**
Failed build of dependent libraries:
* glog and
* abseil-cpp.

note: Solved by current master branches.

Fail in random.cc file - gethostname method wasn't found, maybe missing dependency on winsock library. As a workaround I used default value "default-hostname" in `ACMRandom::HostnamePidTimeSeed()` method.

**Anything else we should know about your project / environment**
On my computer is installed VS2017 but same result was reproduced on another computer with VS2019.

**Comment by lperron** [comment]
bazel works on windows. We will not spend time on supporting non official builds.
