### ISSUE TITLE
static assert fail building sat in debug mode on Windows

### ISSUE THREAD

**Issue by JoelKKelso** [google/or-tools#2077]
**What version of OR-tools and what language are you using?**
Version: v7.7
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10. Visual Studio 2019 16.4.9

**What did you do?**
Build ortools.

**What did you expect to see**

**What did you see instead?**
A static_assert in ortools/sat/encoding.h (see below) fails in debug build, but not release.

ortools/sat/encoding.h Line 129:

// Note that we use <= because on 32 bits architecture, the size will actually
// be smaller than 64 bytes.
static_assert(sizeof(EncodingNode) <= 64,
              "ERROR_EncodingNode_is_not_well_compacted");

I notice that prior to v7.7 this was a COMPILE_ASSERT macro rather than static_assert.

**Comment by lperron** [comment]
32 bit support was dropped a few years ago.

**Comment by Mizux** [comment]
For the record, fixed by #2147
