### ISSUE TITLE
ReadAssignmentFromRoutes and AddDisjunction

### ISSUE THREAD

**Issue by KapecK** [google/or-tools#208]
When I add disjunction to model, ReadAssignmentFromRoutes always return null

`model.AddDisjunction(new int[] {3, 5, 7}, 100000000);`

`var assignment = model.ReadAssignmentFromRoutes(routesArray, false);`

**Comment by furnon** [comment]
Are you sure your routes are valid with respect to the disjunction added ?
If two or more of 3, 5, 7 are in routes then it's not valid (at most one of
them can be in a route).

**Comment by KapecK** [comment]
{3, 5, 7} are not in initial routes.

**Comment by KapecK** [comment]
It's my mistake. Everything works well.
