### ISSUE TITLE
Devsite is following the master branch instead of the stable one

### ISSUE THREAD

**Issue by Rajiv2806** [google/or-tools#2081]
**What version of OR-tools and what language are you using?**
Version: '7.7.7810'
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
 mixed-integer programming (MIP) solvers as defined in: https://developers.google.com/optimization/mip/integer_opt

**What operating system (Linux, Windows, ...) and version?**

Windows 
python 3.6
Conda Virtual Environment 

**What did you do?**
`import ortools
print(ortools.__version__)
from ortools.linear_solver import pywraplp
solver = pywraplp.Solver.CreateSolver('simple_mip_program', 'cbc')`

**What did you expect to see**
> Successful Execution

**What did you see instead?**

> 7.7.7810

> AttributeError: type object 'Solver' has no attribute 'CreateSolver'

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
You are using an example of the master branch against a previous version.
Please recompile using the master branch if you want to use it.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
My bad, it updated directly on devsite.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
doc "reverted" to stable branch, should be ok now...

**Comment by Mani4723** [comment]
Hi, I am still getting this error, I followed the getting started guide provided here - https://developers.google.com/optimization/introduction/python#run-program
