### ISSUE TITLE
C# documentation for MIP Solvers is wrong

### ISSUE THREAD

**Issue by tirafesi** [google/or-tools#2082]
The docs [here](https://developers.google.com/optimization/mip/integer_opt#c_4) (and a lot of other places) have the following example:

```cs
Solver solver = Solver.CreateSolver("SimpleMipProgram", "cbc");
```

This returns `null`.

It should be: 

```cs
Solver solver = Solver.CreateSolver("SimpleMipProgram", "CBC_MIXED_INTEGER_PROGRAMMING");
```

**Comment by Mizux** [comment]
see #2081
