### ISSUE TITLE
PDPTW: Different results when adding constraints, although those were previously met in the unconstrained solution

### ISSUE THREAD

**Issue by SebastienP385** [google/or-tools#2085]
**What version of OR-tools and what language are you using?**
Version: master/v7.3/v7.2 etc.
Language: C++/Java/Python/C#

SNIPPET TO DEMONSTRATE UNSTABILITIES available on the group/email list and there:
https://github.com/SebastienP385/Ortools/blob/master/ORTOOLS_demo_unstabilities_under_constraints.ipynb

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
ROUTING SOLVER
**What operating system (Linux, Windows, ...) and version?**
WINDOWS 10

**What did you do?**
Run the above jupyter notebook: constraints that are met in the original solution, when forced into the code, can lead to not optimal solutions.

**What did you expect to see**
A similar result all thetime: '50 minutes'
**What did you see instead?**
All sorts of values between 50 and 63.
As in my real life project, the problem is more obvious when the constraint on time windows is not the same for each node.

Thanks a lot!

**Comment by Mizux** [comment]
you should try to run the lns.

**Comment by SebastienP385** [comment]
Thank you Mizux. ‘Run the lns’, I m not sure I get what you mean. Would you mind precising a bit.
Merci!

Sebastien

**Comment by lperron** [comment]
It is one search parameter.

Le mer. 1 juil. 2020 à 22:34, SebastienP385 <notifications@github.com> a
écrit :

> Thank you Mizux. ‘Run the lns’, I m not sure I get what you mean. Would
> you mind precising a bit.
> Merci!
>
> Sebastien
>

**Comment by SebastienP385** [comment]
Thank you. On the snippet it works fine, on the real case I still have some cases where it gets stuck, but this is a major progress (working on it, trying to propose alternative 1st solutions). Thanks!
