### ISSUE TITLE
Use lib file with \MT Flag

### ISSUE THREAD

**Issue by Diddlik** [google/or-tools#2089]
**What version of OR-tools and what language are you using?**
Version: master/v7.7/
Language: C++ / VS2019

**Which solver are you using (GLOP)**

**What operating system (Windows 10**

**What did you do?**

I have a large MFC project which is using /MT for linking files. Now I try to integrate the or-tools.lib into projekt, but I always get compilation error, because the lib is compiled with /MD flag. Is it possible to comple the lib with MT?

**Comment by lperron** [comment]
We won't do it. But you can recompile from source.

You will need to search for /MD in the makefile s directory.

**Comment by Diddlik** [comment]
Do I need to change only make file in makefolder or makefile from third_party too?

**Comment by lperron** [comment]
I assume Makefile.third_party.win.mk and Makefile.win.mk.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
