### ISSUE TITLE
C# DLL is not Signed with a Strong Name Key

### ISSUE THREAD

**Issue by dnarayan** [google/or-tools#209]
The C# DLL does not appear to be signed with a strong name key. There was a previous issue on this (https://github.com/google/or-tools/issues/29), which seemed to indicate that the issue had been fixed, but in the latest build I am getting the following error:

An unhandled exception of type 'System.IO.FileLoadException' occurred in mscorlib.dll

Additional information: Could not load file or assembly 'Google.OrTools, Version=2.0.3629.21759, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

**Comment by dlahlou** [comment]
Hi,

C# assemblies are optionally signed, and they are not unless you specify
the path to your keyfile.snk as explained in this file.
<https://github.com/google/or-tools/blob/master/makefiles/Makefile.csharp.mk>

All C# assemblies can optionally be signed. This includes the
> DLLs and the test case EXEs. Signing is currently supported only
> on Windows with the .NET framework.
> To get signed assemblies, use for example:
> make CLR_KEYFILE="c:\full\path\to\keyfile.snk" csharp
> For delay signing, use for example:
> make CLR_KEYFILE="c:\full\path\to\keyfile_pub.snk" CLR_DELAYSIGN=1


Hope this helps

**Comment by dnarayan** [comment]
Thanks yes that helps a lot. I was using the public binaries, so I will have to build it for this purpose. I'd recommend in the future that the public .NET DLLs get signed by default though with a default key (that the builder can change) - it will save consumers of the public binaries from having to do this step when they want to strongly sign their own stuff.
