### ISSUE TITLE
CVRP gives different result in Python and Java

### ISSUE THREAD

**Issue by burbot48** [google/or-tools#2090]
Or tools version:7.5.7466
Python: 3.7

We developed a capacitated vehicle routing model both in python and java platforms. We use the same version of or-tools packages (7.5.7466) and all inputs and searching parameters are the same. But the results are not same.  For instance we have 10 demands and the capacity of each vehicle is 6 demands.  In python 1st vehicle has 5 demands and  2nd vehicle has 5 demands, In java 1st vehicle has 6 demands and 2nd has 4 demands.

Is it possible due tue heuristic approach of or-tools or we have to check some another points.

Regards

**Comment by pybrgr** [comment]
Can you share the model?

**Comment by burbot48** [comment]
this is the  Python Code 

`
def create_data_model():

    data = {}   
    data['distance_matrix']=a   

    data['demands'] = [int(x) for x in talep_ister_zaman2['Tasiyici_Uzunluk']]    

    data['demands'][0]=0    
    data['num_vehicles'] = len(binpacking.to_constant_volume(data['demands'] ,capacity_per_vehicle) )
    data['vehicle_capacities'] = [capacity_per_vehicle]*data['num_vehicles']
    data['depot'] = 0
    return data

def print_solution(data, manager, routing, assignment):
    """Prints assignment on console."""   
    total_distance = 0
    total_load = 0
    #sira=0
    konvoy_max_element=len(konvoy)
    for m in range(data['num_vehicles']):
        
        vehicle_id=konvoy_max_element+m
        konvoy[vehicle_id]=pd.DataFrame()
        index = routing.Start(m)
        plan_output = 'Route for vehicle {}:\n'.format(vehicle_id)
        route_distance = 0
        route_load = 0
        sequence=0
        while not routing.IsEnd(index):                         
            node_index = manager.IndexToNode(index)
            route_load += data['demands'][node_index]
            
            plan_output += ' {0} Load({1}) -> '.format(node_index, route_load)
            previous_index = index
            
            index = assignment.Value(routing.NextVar(index))
            route_distance += routing.GetArcCostForVehicle(
                previous_index, index, m)  
        plan_output += ' {0} Load({1})\n'.format(manager.IndexToNode(index),
                                                 route_load)
        plan_output += 'Distance of the route: {}m\n'.format(route_distance)
        plan_output += 'Load of the route: {}\n'.format(route_load)
        total_distance += route_distance
        total_load += route_load

def main():

    data = create_data_model()

    manager = pywrapcp.RoutingIndexManager(len(data['distance_matrix']),
                                           data['num_vehicles'], data['depot'])

    routing = pywrapcp.RoutingModel(manager)
    def distance_callback(from_index, to_index):
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return data['distance_matrix'][from_node][to_node]

    transit_callback_index = routing.RegisterTransitCallback(distance_callback)
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

    def demand_callback(from_index):
        """Returns the demand of the node."""
        from_node = manager.IndexToNode(from_index)
        return data['demands'][from_node]

    demand_callback_index = routing.RegisterUnaryTransitCallback(
        demand_callback)
    routing.AddDimensionWithVehicleCapacity(
        demand_callback_index,
        0, 
        data['vehicle_capacities'],  
        True,  
        'Capacity')

    search_parameters = pywrapcp.DefaultRoutingSearchParameters() 
    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)
    assignment = routing.SolveWithParameters(search_parameters)

    if assignment:
        print_solution(data, manager, routing, assignment)

 if __name__ == '__main__':
     main()
`

**Comment by pybrgr** [comment]
To recreate this I'm sure the data will be needed.

**Comment by burbot48** [comment]
Here is the data as below.


`data['distance_matrix']=[[0, 351, 291, 344, 291, 399, 248, 245, 399, 258, 167],
 [533, 57, 150, 190, 124, 46, 31, 9, 97, 9, 141],
 [364, 204, 57, 121, 30, 100, 155, 137, 49, 102, 86],
 [540, 139, 233, 57, 207, 36, 114, 72, 14, 72, 224],
 [364, 230, 83, 147, 57, 126, 182, 163, 76, 128, 113],
 [485, 376, 254, 294, 228, 57, 135, 93, 6, 93, 245],
 [407, 323, 176, 240, 149, 219, 57, 256, 168, 221, 205],
 [423, 340, 434, 257, 407, 236, 314, 57, 186, 263, 247],
 [485, 427, 304, 344, 278, 107, 185, 144, 57, 144, 296],
 [397, 621, 485, 538, 459, 517, 366, 338, 467, 57, 208],
 [488, 469, 334, 387, 307, 366, 215, 186, 315, 173, 57]]

data['num_vehicles'] = 2
data['demands']=[0,1,1,1,1,1,1,1,1,1,1]
data['vehicle_capacities']=[6,6]

data['depot'] = 0`

**Comment by pybrgr** [comment]
If no one gets to this before the weekend I'll give it a look.

**Comment by Mizux** [comment]
my 2 cents,

https://github.com/google/or-tools/blob/45770b833997f827d322e929b1ed4781c4e60d44/ortools/constraint_solver/constraint_solver.cc#L89-L92

did you test on the same machine ?

**Comment by lperron** [comment]
We do not aim for determinism across platforms.
