### ISSUE TITLE
How can I use CpModel  to  make three 1s appear in  a 1D array ?

### ISSUE THREAD

**Issue by tongzm** [google/or-tools#2093]
I want three 1s to appear in the shift array，I wrote the following code：

model = cp_model.CpModel()
solver = cp_model.CpSolver()
shifts = {}
for i in range(5):
    shifts[(i)] = model.NewIntVar(0, 3, "shifts(%i)" % i)

for i in range(5):
    model.Add(sum([shifts[(i)]==1  for i in range(5) ]) == 3)
    
solver = cp_model.CpSolver()
status = solver.Solve(model)
print("status:",status)
for i in range(5):
    print(solver.Value(shifts[(i)]))

But it return:
TypeError: unsupported operand type(s) for +: 'int' and 'BoundedLinearExpression'

Can anyboday help me ,please!

**Comment by lperron** [comment]
Please use the mailing list.
