### ISSUE TITLE
Expose the ability to set the branching priority in pywraplp

### ISSUE THREAD

**Issue by snedeljkovic** [google/or-tools#2094]
**What language and solver does this apply to?**
C++ Linear Solver

**Describe the problem you are trying to solve.**
I'd like to add branching priority to certain variables. C++ API:
https://developers.google.com/optimization/reference/linear_solver/linear_solver/MPVariable

**Describe the solution you'd like**
Something along the lines of:
```
var.branching_priority(priority)
```

**Describe alternatives you've considered**
No alternatives, I'm afraid.

**Additional context**
...

**Comment by snedeljkovic** [comment]
@lperron I see you edited my question. Just to be clear, I'd like this functionality to be available in Python.

**Comment by lperron** [comment]
But you write C++ api in your description? And you listed all solvers.

Please be precise.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 6 juil. 2020 à 11:17, snedeljkovic <notifications@github.com> a
écrit :

**Comment by snedeljkovic** [comment]
@lperron Sorry, my intention was to point you to the C++ implementation and suggest you expose that to Python.

**Comment by lperron** [comment]
Now it is clearer. 
I pushed the feature on the master branch,

**Comment by snedeljkovic** [comment]
@lperron Thank you very much!

**Comment by snedeljkovic** [comment]
@lperron I actually need to set the branching priority before solving, The method you added is just a getter. Sorry if I wasn't clear enough (I did mention the ability to set the priority in the title).

**Comment by lperron** [comment]
I added both I believe.

Le lun. 6 juil. 2020 à 12:29, snedeljkovic <notifications@github.com> a
écrit :

**Comment by snedeljkovic** [comment]
@lperron You are right. Thank you, again.
