### ISSUE TITLE
How to get attribute specific to Gurobi solver

### ISSUE THREAD

**Issue by ShivKJ** [google/or-tools#2097]
Hi,

I am using Gurobi. Is there a way to access this solver specific  attribute? For example, Gurobi provides [MIPGap](https://www.gurobi.com/documentation/9.0/refman/mipgap.html), how can I access this attribute when using Ortools?

**Comment by lperron** [comment]
There are two apis

To set parameters, you can use the set solver specific parameters as
string.

Toucan also query a pointer to the solver in c++ using this:
http://google.github.io/or-tools/cpp_linear/classoperations__research_1_1MPSolver.html#a1269e748520719b9d11f6ef2d1c28c42

**Comment by ShivKJ** [comment]
I am using python, so is there a python equivalent?

**Comment by lperron** [comment]
Only the set parameters as strong.

**Comment by ShivKJ** [comment]
Sorry, I did not understand that.

**Comment by lperron** [comment]
Python equivalent of what ?

Do you want to set a parameter or read one ?
Which parameter ?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Have you looked at:
http://google.github.io/or-tools/python/ortools/linear_solver/pywraplp.html#pywraplp.MPSolverParameters
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
