### ISSUE TITLE
Graph algorithms use int32 for arc numberings making large graph sizes crash

### ISSUE THREAD

**Issue by Dachannien** [google/or-tools#2098]
**What version of OR-tools and what language are you using?**
Version: master
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Graph/min cost flow

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you do?**
Loaded graph with more than 2^31 arcs

**What did you expect to see**
Solving the graph min cost flow

**What did you see instead?**
F0707 15:41:28.964172 29109 min_cost_flow.cc:1086] Check failed: arc == augmented_num_arcs (2 vs. -1228197991)

This is caused by overflowing the graph indices (arc/node), which are stored in an int32.  It should be changed to an int64.  Note the comment in graph/graph.h:

// Base class of all Graphs implemented here. The default value for the graph
// index types is int32 since allmost all graphs that fit into memory do not
// need bigger indices.

"Almost"?  Bill Gates would like a word...

Anyway, the fix here appears to be pretty easy.  There are a few spots in graph/ebert_graph.h and graph/graph.h where declarations of int32 should be changed to int64.  I think that fixes it - I was able to rebuild the library, recompile, and run, and this error didn't occur.  (Unfortunately, it turns out that 165 GB isn't enough for everyone, so my project still crashed for running out of memory, but at least I got past this one issue.  It also still runs to completion on a smaller data set.)

**Anything else we should know about your project / environment**
Nope.

Thanks!

**Comment by lperron** [comment]
So the patch is not useful :-) and by actually using int64, you double memory consumption.

**Comment by Dachannien** [comment]
Thanks for reviewing my request.  But I think there is still a good reason to implement this patch.

The memory consumption issues are my problem, not yours.  I have a lot of other stuff in memory that I will need to deal with on my own.  Or, I could run on a bigger VM instance.  But I can solve those problems myself.  Anybody working with data sets this large will have ways to deal with running out of memory.

By using an int32 here, it is _impossible_ to solve a graph with more than 2^31 arcs no matter how much memory the user has.  If a slightly larger int was possible, that would be ideal - by the time you get to, 2^40, it would probably be impossible to solve without quantum computing :) But unfortunately, int32 and int64 are the only choices.

It would be a better patch to provide implementations for both int32 and int64, but that solution would be a bit more effort.  Changing the code to just use int64 is the quick way to fix it.  Either way, I hope you'll reconsider and maybe just leave this as a low-priority feature request instead of closing it entirely.
