### ISSUE TITLE
CVRPTW dropped all nodes when using some first_solution_strategy

### ISSUE THREAD

**Issue by WClouds** [google/or-tools#2099]
**What version of OR-tools and what language are you using?**
Version: v7.7.
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing Solver

**What operating system (Linux, Windows, ...) and version?**
macOS

**What did you do?**
1. Go to the [CVRPTW_plot example](https://github.com/google/or-tools/blob/stable/examples/python/cvrptw_plot.py)
2. Change [the num_stops variable](https://github.com/google/or-tools/blob/e3f500947b1d75dc8fe9fd784acdd88fe06c6557/examples/python/cvrptw_plot.py#L580) from 50 to **100**
3. I use SAVINGS and BEST_INSERTION as the first_solution_strategy to run the code
4. When running with SAVINGS, the code can get a solution. But with BEST_INSERTION, all nodes will be dropped.

**What did you expect to see**
Both strategies can provide a solution.

**What did you see instead?**
SAVINGS can give a solution, but BEST_INSERTION will dropped all of the nodes.

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
There are different strategies for a reason.

**Comment by WClouds** [comment]
@lperron But when I changed the version of OR-tools from v7.7 to v6.10, the BEST_INSERTION strategy can also give a solution instead of dropping all of the nodes.
Is there any difference between the two versions?

**Comment by lperron** [comment]
Lots of work. First solution strategies are the hardest thing in routing.
The team works really hard to make them diverse and as robust as possible.

You cannot expect them to produce the same result.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
