### ISSUE TITLE
GLIBC_2.14 Error on Linux Debian

### ISSUE THREAD

**Issue by edizel** [google/or-tools#210]
Hi,
I  installed or-tools (without any error messages) on a Linux Debian machine to the local directory. But when I try to run an example code, I am getting same error message related with 'GLIBC_2.14'. I also tried to install it on my Mac but again I got the same error. Any ideas?
thanks in advance,
bora

bedizel@login:~/tools/ortools_examples$ python examples/python/car.py 
Traceback (most recent call last):
  File "examples/python/car.py", line 35, in <module>
    from ortools.constraint_solver import pywrapcp
  File "/homedtic/bedizel/.local/lib/python2.7/site-packages/ortools-3.3629-py2.7-linux-x86_64.egg/ortools/constraint_solver/pywrapcp.py", line 28, in <module>
    _pywrapcp = swig_import_helper()
  File "/homedtic/bedizel/.local/lib/python2.7/site-packages/ortools-3.3629-py2.7-linux-x86_64.egg/ortools/constraint_solver/pywrapcp.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrapcp', fp, pathname, description)
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /homedtic/bedizel/.local/lib/python2.7/site-packages/ortools-3.3629-py2.7-linux-x86_64.egg/ortools/constraint_solver/_pywrapcp.so)

**Comment by lperron** [comment]
Hi,

Pypi cannot distinguish between different linux distributions. So we are
stuck.
So to move forward, you need to:
  install or-tools from sources:
https://developers.google.com/optimization/installing
  when you have run everything (make third_party, make
install_python_modules, make python, make test_python), run

make pypi_archive
go into <or-tools>/temp/ortools

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-07-13 10:42 GMT-07:00 edizel <notifications@github.com>:

**Comment by lperron** [comment]
Then

you see a setup.py, just run:
  python setup.py install

It should do the same as you installation from pypi.

I am sorry about the trouble, but there are currently no way out. I am
hoping https://www.python.org/dev/peps/pep-0513/ will solve this problem.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-07-13 11:01 GMT-07:00 Laurent Perron <lperron@google.com>:

**Comment by edizel** [comment]
Great!
I could successfully installed it on my mac.
One little question: These process also works exactly same on a linux machine (Debian in my case)?

thanks a lot

**Comment by lperron** [comment]
yes.

If not, please report the problems.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-07-15 5:21 GMT-07:00 edizel <notifications@github.com>:
