### ISSUE TITLE
Associate cost with Slack variable

### ISSUE THREAD

**Issue by drgoda** [google/or-tools#2100]
**What language and solver does this apply to?**
Python

**Describe the problem you are trying to solve.**
I want to allow slack or waiting time at a node to make time windows feasible for the vehicle for subsequent nodes but want to associate cost with the waiting time. 

**Describe the solution you'd like**
is there a way to consider slack of the node into arc cost? For example slack of the origin node into the arc?

**Describe alternatives you've considered**
Creating dummy nodes in between with time window  =[ earliest pick up of one node, earliest pick up of another node] and cost associated equal to difference of the two.

**Additional context**
Context is basically a courier needs to wait at a particular location before it is time to deliver another order at same location and there is a cost associated with it

**Comment by lperron** [comment]
Please use the mailing list.
