### ISSUE TITLE
Uniform API to create variables and get values?

### ISSUE THREAD

**Issue by cdeil** [google/or-tools#2102]
For CP-SAT I see [here](https://developers.google.com/optimization/cp/cp_solver) that the way to create variables and to get their values is this:
```
model = cp_model.CpModel(...)
variable = model.NewIntVar(0, 10, 'variable')
value = solver.Value(variable)
```
For Glop I see [here](https://developers.google.com/optimization/lp/glop) that the way to create variables and get their values is this:
```
solver = pywraplp.Solver(...)
variable = solver.NumVar(0, solver.infinity(), 'x')
value = variable.solution_value()
```

Is there are fundamental reason for the differences?

Difference 1: in one case variables created via the model, in the other the solver
Difference 2: in one case solution value has to be obtained via the solver, in the other a method on the variable gives it

We are using CP-SAT and our codebase would simplify if we could get the value from the variable without having to pass the solver around. Is it possible to have a `NewIntVar.solution_value` at the moment, or would it make sense to add it in a future release?

**Comment by lperron** [comment]
Actually, in future releases, we will go the over way, and remove
solution_value() from the MPVariables.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 15 juil. 2020 à 17:11, Christoph Deil <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
And to answer the first question, the CP-SAT API was written 10 years after
the MPSolver one.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by cdeil** [comment]
Is there ever a value in having a `CpSolver` and `CpModel` as two objects?
I.e. do you sometimes pass one model to multiple solvers?
Or sometimes use one solver on multiple models?
Is there any example in the repo or docs where this is of value?

From my beginner perspective, the distinction of the two doesn't seem useful, and it's just inconvenient to not be able to get the solution value from the variable directly, but to have to pass the solver around to the pieces of our codebase that want to access the solution values.

Would be nice to have some docs section that explains this basic design.

**Comment by lperron** [comment]
The input language of the CP-SAT solver is a protobuf. This allows
serialization, storage. It enables multi threading, presolve.
So there is a big benefit of having a modeling object.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 15 juil. 2020 à 17:51, Christoph Deil <notifications@github.com> a
écrit :
