### ISSUE TITLE
Possible Bug w/ Wedding Seating Chart Example

### ISSUE THREAD

**Issue by ankane** [google/or-tools#2106]
**What version of OR-tools and what language are you using?**
Version: 7.7
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)** CP-SAT

**What operating system (Linux, Windows, ...) and version?** Mac

**What did you do?**

Ran the `wedding_optimal_chart.py` example (https://github.com/google/or-tools/blob/stable/examples/python/wedding_optimal_chart_sat.py) with the following variables changed to simplify it

```python
num_tables = 2
table_capacity = 3
min_known_neighbors = 1
C = [[2, 2, 2, 0], [2, 2, 2, 0], [2, 2, 2, 1], [0, 0, 1, 1]]
names = ["A", "B", "C", "D"]
```

- A, B, and C have a connection weight of 2
- C and D have a connection weight of 1

Full code if it's useful: https://gist.github.com/ankane/6602dd6c5926f0015674e3907b493cac

**What did you expect to see**

One solution - (A, B) and (C, D), since everyone must know at least one other person at the table

**What did you see instead?**

Two solutions

```
Solution 0, time = 0.003925 s, objective = 3
Table 0: 
  A
  B
Table 1: 
  C
  D
Solution 1, time = 0.004092 s, objective = 6
Table 0: 
  A
  B
  C
Table 1: 
  D
Statistics
  - conflicts    : 3
  - branches     : 17
  - wall time    : 0.001479 s
  - num solutions: 2
```

**Anything else we should know about your project / environment**

I think something might be off with this constraint:

```python
# Min known neighbors rule.
for t in all_tables:
    model.Add(
        sum(same_table[(g1, g2, t)]
            for g1 in range(num_guests - 1)
            for g2 in range(g1 + 1, num_guests) for t in all_tables
            if C[g1][g2] > 0) >= min_known_neighbors)
```

Edit: updated link to right example (SAT one) and add two more variables that were changed (sorry!)

**Comment by Mizux** [comment]
yup should be replaced by:
```python
   # Min known neighbors rule.
    for g in all_guests:
        model.Add(
            sum(same_table[(g, g2, t)]
                for g2 in range(g + 1, num_guests)
                for t in all_tables
                if C[g][g2] > 0) +
            sum(same_table[(g1, g, t)]
                for g1 in range(g)
                for t in all_tables
                if C[g1][g] > 0)
            >= min_known_neighbors)
```

**Comment by ankane** [comment]
That was fast, thanks @Mizux! Working really well now.
