### ISSUE TITLE
RoutingModel error; does not contain a definition to DefaultSearchParameters in C# TSP example

### ISSUE THREAD

**Issue by johnlysam** [google/or-tools#211]
I have installed the package from ortools  from nuget https://www.nuget.org/packages/Google.OrTools/

In the c# examples of TSP class I am getting error on following code

RoutingSearchParameters search_parameters = RoutingModel.DefaultSearchParameters();

I have checked in object browser and found RoutingModel does not contain a definition to DefaultSearchParameters

How to make this work?

**Comment by lperron** [comment]
Hi

nuget has not been updated in a long time.
I am waiting for a google.protobuf nuget package that is out of beta, as
nuget does not allow dependencies on beta packages.

I am sorry about that.

Can you install from C# libraries?




Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-07-15 8:19 GMT-07:00 johnlysam <notifications@github.com>:

**Comment by swestner** [comment]
As far as I know, Nuget does allow dependencies on pre-releases packages. It does force the depending package to also release as a pre-release.

So if the or-tools were to release as a beta package they could have dependancies on pre-release packages.

**Comment by lperron** [comment]
Fixed a long time ago :-(

Closing the issue.
