### ISSUE TITLE
make third_party failed on CentOS 6.10 

### ISSUE THREAD

**Issue by niangjunchen** [google/or-tools#2110]
**What version of OR-tools and what language are you using?**
Version: v7.7
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Haven't finished installation, but I am trying to use Gurobi after building from source. 

**What operating system (Linux, Windows, ...) and version?**
Linux CentOS 6.10

**What did you do?**
1. Follow instruction on https://developers.google.com/optimization/install/python/source_linux
2. make third_party failed with the following message 

cd dependencies/sources/protobuf-v3.12.2 && \
   /usr/bin/cmake -Hcmake -Bbuild_cmake \
    -DCMAKE_PREFIX_PATH="/home/cudo/or-tools/dependencies/install" \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_TESTING=OFF \
    -Dprotobuf_BUILD_TESTS=OFF \
    -Dprotobuf_BUILD_EXAMPLES=OFF \
    -DCMAKE_CXX_FLAGS="-fPIC " \
    -DCMAKE_INSTALL_PREFIX=../../install && \
  /usr/bin/cmake --build build_cmake -- -j 4 && \
  /usr/bin/cmake --build build_cmake --target install
CMake Error: The source directory "/home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/cmake" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** [dependencies/install/lib/libprotobuf.so] Error 1

The protobuf-v3.12.2 directory only contains a directory called "build_cmake", but it seems the script is looking for a folder called "cmake".  I am not sure how to fix this issue. Any help will be greatly appreciated.

**Comment by Mizux** [comment]
seems protobuf is not cloned...

can you try master branch ?

**Comment by Mizux** [comment]
Also please note Centos 6.10 is near its end of life so we won't support it and you should migrate to Centos 8 if you can...
ref: https://wiki.centos.org/About/Product

**Comment by niangjunchen** [comment]
> seems protobuf is not cloned...
> try to suppress this directory
> `rm -rf dependencies/sources/protobuf-*`
> 
> You can also try `make build_protobuf` on a fresh or-tools clone, this will only try to build protobuf so it can be easy for you to figure out what is the problem...
> 
> see:
> https://github.com/google/or-tools/blob/45770b833997f827d322e929b1ed4781c4e60d44/makefiles/Makefile.third_party.unix.mk#L269-L288
> 
> can you try master branch ?

Thanks, @Mizux. Yes, it seems the error is in building the protobuf. I ran make build_protobuf on a fresh or-tools clone on the master branch and it got into the following problem:

gmake[3]: *** [CMakeFiles/libprotobuf.dir/home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/generated_enum_util.cc.o] Error 1
gmake[2]: *** [CMakeFiles/libprotobuf.dir/all] Error 2
gmake[1]: *** [all] Error 2
make: *** [dependencies/install/lib/libprotobuf.so] Error 2


I have attached the full output and error message. 

[error.txt](https://github.com/google/or-tools/files/4970060/error.txt)
[output.txt](https://github.com/google/or-tools/files/4970061/output.txt)

**Comment by Mizux** [comment]
According to the log we can see:
```sh
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
...
-- Performing Test protobuf_HAVE_BUILTIN_ATOMICS
-- Performing Test protobuf_HAVE_BUILTIN_ATOMICS - Failed
...
In file included from /home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/arena.h:55,
                 from /home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/arena.cc:31:
/home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/arena_impl.h:36:18: error: atomic: No such file or directory
In file included from /home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/arena.h:55,
                 from /home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/arenastring.h:41,
                 from /home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/any.h:37,
                 from /home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/any_lite.cc:31:
/home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/arena_impl.h:36:18: error: atomic: No such file or directory
```

Open question: does protobuf v3.12.2 can be built using GCC 4.4.7 ?

**Comment by Mizux** [comment]
Ok, the issue is Protobuf can't be built using the default centos:6 gcc 4.4.7 compiler -> please update your compiler (or deal with the Protobuf community to make it works)...

Here a simple Dockerfile to reproduce the error:
```Dockerfile
# Create a virtual environment with all tools installed
# ref: https://hub.docker.com/_/centos
FROM centos:6 AS base
LABEL maintainer="mizux.dev@gmail.com"
# Install system build dependencies
ENV PATH=/usr/local/bin:$PATH
RUN yum -y update \
&& yum -y install git wget which zlib-devel \
&& yum -y groupinstall "Development Tools" \
&& yum clean all \
&& rm -rf /var/cache/yum
# Install CMake 3.18.0
RUN wget "https://cmake.org/files/v3.18/cmake-3.18.0-Linux-x86_64.sh" \
&& chmod a+x cmake-3.18.0-Linux-x86_64.sh \
&& ./cmake-3.18.0-Linux-x86_64.sh --prefix=/usr/local/ --skip-license \
&& rm cmake-3.18.0-Linux-x86_64.sh
CMD [ "/usr/bin/bash" ]

FROM base AS devel
WORKDIR /project
# centos6 only have git 1.7 so we can't clone a tag...
RUN git clone -b "3.12.x" --depth 1 https://github.com/protocolbuffers/protobuf.git
WORKDIR protobuf
RUN git checkout -b "v3.12.2" v3.12.2

FROM devel AS build
RUN cmake -Scmake -Bbuild -DBUILD_SHARED_LIBS=ON \
 -DBUILD_TESTING=OFF -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_BUILD_EXAMPLES=OFF
RUN cmake --build build
```

Simply test running
```ssh
docker build -t 2110 .
```

**Comment by Mizux** [comment]
Note you can install gcc 9 using devtoolset

```Dockerfile
# Install newer GCC
# see: https://centos.pkgs.org/6/centos-sclo-rh-x86_64/devtoolset-9-9.0-1.el6.x86_64.rpm.html
RUN yum -y install centos-release-scl-rh
RUN yum -y install devtoolset-9
#RUN scl enable devtoolset-9 bash
#RUN ls /opt/rh/devtoolset-9/root/usr/bin
ENV PATH="/opt/rh/devtoolset-9/root/usr/bin:${PATH}"
```

**Comment by niangjunchen** [comment]
Thanks, @Mizux, installing gcc9 solved my previous problem. However, make build_protobuf still failed with at a later stage ... 

The error message looks like: 

/home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/arena.h:719: error: â€˜friendâ€™ used outside of class
/home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/arena.h:719: error: invalid use of template-name â€˜google::protobuf::internal::GenericTypeHandlerâ€™ without an argument list
/home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/arena.h:720: error: â€˜friendâ€™ used outside of class
/home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/arena.h:720: warning: declaration â€˜struct google::protobuf::internal::ArenaStringPtrâ€™ does not declare anything
/home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/arena.h:721: error: â€˜friendâ€™ used outside of class
/home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/arena.h:721: warning: declaration â€˜struct google::protobuf::internal::LazyFieldâ€™ does not declare anything
/home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/arena.h:722: error: â€˜friendâ€™ used outside of class
/home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/arena.h:722: warning: declaration â€˜struct google::protobuf::internal::EpsCopyInputStreamâ€™ does not declare anything
/home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/arena.h:723: error: â€˜friendâ€™ used outside of class
/home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/arena.h:725: error: â€˜friendâ€™ used outside of class
/home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/arena.h:732: error: expected declaration before â€˜}â€™ token
gmake[3]: *** [CMakeFiles/libprotobuf.dir/home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/extension_set.cc.o] Error 1
gmake[3]: *** [CMakeFiles/libprotobuf.dir/home/cudo/or-tools/dependencies/sources/protobuf-v3.12.2/src/google/protobuf/generated_enum_util.cc.o] Error 1
gmake[2]: *** [CMakeFiles/libprotobuf.dir/all] Error 2
gmake[1]: *** [all] Error 2
make: *** [dependencies/install/lib/libprotobuf.so] Error 2

I have also attached the full output and error messages. 
[error.txt](https://github.com/google/or-tools/files/4972433/error.txt)
[output.txt](https://github.com/google/or-tools/files/4972434/output.txt)
