### ISSUE TITLE
CP-SAT: solution not found in v7.7 but found quickly in v7.5

### ISSUE THREAD

**Issue by frasernutricia** [google/or-tools#2111]
Version: stable branch
Language: C++
CP-SAT
Debian Buster
[protoDebug.txt](https://github.com/google/or-tools/files/4971863/protoDebug.txt)

Running the attached model in v7.5 takes about 200 secs wall time and returns a correct solution. Running the same model in stable branch still fails to finish after many hours. The same behaviour occurs with v7.6, so looks like it is due to changes from v7.5 to v7.6. Happens with multiple seeds. Default options used in v7.7 (in v7.5 also default, only option set explicitly is deterministic_parallel_search = true and number of workers).  Changing the problem slightly (either simplifying or adding extra constraints) does run in v7.7 but that is not the problem I need to find solutions to. 

thanks for your help!

**Comment by lperron** [comment]
3 comments:
  -deterministic_parallel_search with num_search_workers > 1 is very experimental. I suspect it was not implemented in 7.5, and the first stab at is decrease its performance a lot. Unfortunately, this is expected. 
  - there is an extra parameter (something like batch size that you can tweak)
  - on the meta level, degrading performance one one single problem is not considered a bug. Between versions, we try to improve performance on average or on the majority of cases, but never on all cases.

**Comment by frasernutricia** [comment]
Understood not a bug, sorry. Given the huge hit in performance in sequential not just parallel (see below) for this case would it be possible to have a feature request (or advice) that allows for the previous behaviour in v7.5 to be an option? e.g. 
v7.5 = 6000 secs walltime    (1 worker, sequential search, default settings)
v7.7 = 30000 secs walltime (1 worker, sequential search, default settings)
v7.5 = 200 sec walltime (4 workers, default settings)

**Comment by lperron** [comment]
We have pushed a first performance fix. I keep the bug open as this is not completely resolved yet.

**Comment by lperron** [comment]
I ran with the latest code.
With 8 threads, it finds a solution in 260s on my laptop.
