### ISSUE TITLE
shift_minimization_sat.cc - Unable to get result when using large data set (job > 800 and worker > 100)

### ISSUE THREAD

**Issue by rakeshshahu** [google/or-tools#2113]
**What version of OR-tools and what language are you using?**
Version: master/v7.7.7810
Language: C++/Java 

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Ubuntu and MacOS - Problem on both

**What did you do?**
1. Simply ran the shift_minimization_sat.cc with larger data set. it works beautifully for smaller data set 
 
*What did you expect to see**
Executed the process on a 16 vCPU and still unable to get results after 4 hours 
Expected to see the result under an hour for (example data files) with job > 800 and workers > 100
 

**What did you see instead?**
Ran the same on 16 vCPU machine and still no results after 4 hours. 

Make sure you include information that can help us debug (full error message, model Proto).
No change to the model as we wanted to check if the CP-SAT can scale and then change the model in shift_minimization_sat.cc to fit our requirements

**Anything else we should know about your project / environment** 
Started using the solver recently. Worked well for small data set, however we have to add more constraints (later) and larger data set. We tried to check the original code (shift_minimization_sat.cc) with larger data set which seems have issue with scale

**Comment by lperron** [comment]
These are np-hard problems.  So these expectations are unrealistics.
