### ISSUE TITLE
Expose some way to set random seed for MIP solvers

### ISSUE THREAD

**Issue by amit2103** [google/or-tools#2114]
**What language and solver does this apply to?**
Java

**Describe the problem you are trying to solve.**

For MIP we would like to solve the problem of setting the seed for the Solver so that we can always come up with the same solutions given the same problem.
**Describe the solution you'd like**

Anyway we can set the SEED for the solvers will be nice

**Comment by lperron** [comment]
Are there apis.tl set seeds in scip, CBC, gurobi, cplex... ?

Le dim. 26 juil. 2020 à 16:23, Amit Pandey <notifications@github.com> a
écrit :

**Comment by amit2103** [comment]
I might be mistaken but CBC home page in Github says this
"Allow initialization of random seed by user"

I also saw similar things for SCIP ...
I dont have idea about Gurobi perhaps we can ignore it incase its set and
the underlying soler doesnt allow it ?

**Comment by lperron** [comment]
Btw, is this really helping?

**Comment by amit2103** [comment]
I might be totally wrong but by allowing setting the seed , won't it allow
for reproducible results ?

**Comment by lperron** [comment]
I would expect the solvers to be deterministic on the same instance with
the same environment (platform, cpu...) without it.

On a side note, I do not trust CBC.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 28 juil. 2020 à 07:47, Amit Pandey <notifications@github.com> a
écrit :

**Comment by amit2103** [comment]
We have a set of tests we run for some solutions , this is typically run on
different platforms ( depending on Dev machines ) , yeah cbc is profoundly
unreliable .

**Comment by lperron** [comment]
My take, use the parameters as string.
