### ISSUE TITLE
In need of some clarity regarding how neighbouring solutions are generated for ATSP?

### ISSUE THREAD

**Issue by gclplp** [google/or-tools#2115]
I am using OR-tools to solve an asymmetric travelling salesman problem. It seems to be working well as the problem is not too big (about 300 nodes), however I have a very basic question, I understand that neighbouring solutions are generated and then some kind of small change is made to generate neighbours which are then evaluated through say Simulated Annealing, What I am not certain of is how this neighbouring solutions are generated, are two edges randomly swapped or is it something else? I realise the question is quite basic but any help would be appreciated.

**Comment by lperron** [comment]
Please use the mailing list.

**Comment by Mizux** [comment]
Not sure for simulated annealing but for LNS you can see here the list of operators:
https://github.com/google/or-tools/blob/45770b833997f827d322e929b1ed4781c4e60d44/ortools/constraint_solver/routing_parameters.proto#L91-L335

**Comment by gclplp** [comment]
Thank you Mizux ended up finding that after I posted, just in case someone else sees this, the manual has more detail of how the operators are cycled through (http://www.lia.disi.unibo.it/Staff/MicheleLombardi/or-tools-doc/user_manual/manual/ls/ls_operators.html).
