### ISSUE TITLE
Multiple possible machines

### ISSUE THREAD

**Issue by Eduardoofc** [google/or-tools#2116]
**What language and solver does this apply to?**
All, Python, Java, C#, C++ / CP-SAT, Routing, Linear Solver
Python
**Describe the problem you are trying to solve.**
I have some tasks that use just one machine to process. But I wouldnt like to specify just one possible machine to each task. 
**Describe the solution you'd like**
What i actually need is multiple possible machine for each task.
**Describe alternatives you've considered**

**Additional context**

**Comment by lperron** [comment]
Please use the mailing list
