### ISSUE TITLE
Could not load file or assembly Google.OrTools, Version=7.7.7816.0

### ISSUE THREAD

**Issue by MarkRLV** [google/or-tools#2117]
**What version of OR-tools and what language are you using? <b>Version 7.7.7816.0</b>
Language: <b>C# in Visual Studio Community 2017 Version 15.9.21</b>

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)?  <b>GLOP</b>

**What operating system (Linux, Windows, ...) and version?  <b>Windows 10</b>

Trying to implement Google OR Tools based on this web page's directions:
https://developers.google.com/optimization/introduction/dotnet

In the package manager I did this command:  <b>Install-Package Google.OrTools -Version 7.7.7816. </b>

That command caused Visual Studio to recognize the <b>using Google.OrTools.LinearSolver;</b> statement in my program. 

I slightly edited the SimpleLpProgram.csproj file that was auto-generated to include:

<b>
  < ItemGroup >
    < PackageReference Include="Google.OrTools" Version="7.7.*" / >
  < /ItemGroup >
</b>
A lot of what seems to be recommended on developers.google web page above seemed to be auto-generated through nuget in the .csproj file.

When I run the program, I get this error:

<b>
System.BadImageFormatException
  HResult=0x8007000B
  Message=Could not load file or assembly 'Google.OrTools, Version=7.7.7816.0, Culture=neutral, PublicKeyToken=53dbb1ea090cbef7' or one of its dependencies. An attempt was made to load a program with an incorrect format.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
</b>
My Program.cs file:

[program.cs.txt](https://github.com/google/or-tools/files/4985419/program.cs.txt)

My SimpleLpProgram.csproj file:

[SimpleLpProgram.csproj.txt](https://github.com/google/or-tools/files/4985420/SimpleLpProgram.csproj.txt)

My Packages.config file:

[packages.config.txt](https://github.com/google/or-tools/files/4985421/packages.config.txt)

Any ideas on how to fix would be appreciated!

**Comment by lperron** [comment]
Did you install visual studio 2019 redistributable ? Can you check the cpu
architecture to be x64?

**Comment by MarkRLV** [comment]
I had not previously installed VS 2019 redistributable, but I just installed it, rebooted and no change.
Yes, I have x64.  My chip is an Intel i5-2430 @ 2.4 GHz

I didn't fully follow or understand the "MakeFile" requirements.  Are those required if you are using Visual Studio?

There are multiple references to x64 in my .csproj file:

[SimpleLpProgram.csproj.txt](https://github.com/google/or-tools/files/4988917/SimpleLpProgram.csproj.txt)

**Comment by lperron** [comment]
'Release|AnyCPU' "

You need to target Release/x64
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by MarkRLV** [comment]
That solved it!  Had to change "AnyCPU" to "x64" not just on the Release|AnyCPU, but all other references to AnyCPU as well.

That got me past the first line of code:
Solver solver = Solver.CreateSolver("SimpleLpProgram", "GLOP");

Then when it tries to do:
Variable x = solver.MakeNumVar(0.0, 1.0, "x");

I get the error:
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=SimpleLpProgram
  StackTrace:
   at SimpleLpProgram.Program.Main(String[] args) in C:\Users\markr\source\repos\SimpleLpProgram\SimpleLpProgram\Program.cs:line 14

Any ideas on that issue?

**Comment by MarkRLV** [comment]
Found the solution:
Change "GLOP" to  "GLOP_LINEAR_PROGRAMMING"

**Comment by Mizux** [comment]
For the record our provided sample is correct nothing to change...
https://github.com/google/or-tools/blob/45770b833997f827d322e929b1ed4781c4e60d44/ortools/linear_solver/samples/SimpleLpProgram.cs#L25

**Comment by lperron** [comment]
yes, I changed the code after 7.7
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by javedsarwa** [comment]
Facing the same issue when trying to deploy on azure app service, locally its working fine. I have also tried with the window x64.

I am using VS2022, .Net Framework 4.8 and try to deploying on azure app service.

Google.OrTools Version is:  9.2.9972

Error: Could not load file or assembly 'Google.OrTools' or one of its dependencies. An attempt was made to load a program with an incorrect format.
