### ISSUE TITLE
Combination of Capacity and Vehicle Routing with Pickups and Deliveries constraints

### ISSUE THREAD

**Issue by ranganaAssetDigital** [google/or-tools#2118]
Hi,
I am using following code to get a routing solution which involves Capacity and Vehicle Routing with Pickups and Deliveries constraints. If i use vehicle capacities as 30 it works without an issue, however if i add 15 as vehicle capacity it will not give me a solution.
This is my full code [sample](https://gist.github.com/ranganaAssetDigital/b0d9257ed72fc2133b6ba967fc0929d5)

any idea on this issue is much appreciated.

**Comment by lperron** [comment]
Please use the mailing list.

**Comment by luanmisaelmoura** [comment]
Hello, try setting the destination demands with the negative value from the origin demands. For example, I saw your code and tried with this data['demands'] = [0, 5, 5, -10, 10, 10, -5, 5, -5, -10, -5, 5, -5]. You can see that the destiny node has a negative value corresponding to its origin. It worked for me.
