### ISSUE TITLE
Follow up to #2117

### ISSUE THREAD

**Issue by MarkRLV** [google/or-tools#2119]
1) Wanted to say thanks to @lperron 

2)  Offer some sample code of a slightly more real world problem that was described at https://users.math.msu.edu/users/drachman/math106spring01/lec20_linear_programming.pdf 

[lpfarm.cs.txt](https://github.com/google/or-tools/files/4989397/lpfarm.cs.txt)

**Comment by lperron** [comment]
Thanks
