### ISSUE TITLE
Optimize a problem that involves a 2-dimensional matrix and two 1-dimensional matrices that requires a matrix multiply function.

### ISSUE THREAD

**Issue by MarkRLV** [google/or-tools#2120]
**What language and solver does this apply to? **C#, Linear Solver**

In business finance, there is a desire to meet a certain minimum return on investment while minimizing risk.  If you take a collection of N stocks, I can compute a Return Matrix (array) that is 1x30 (when N=30).  Call that matrix R.

I can also compute a Covariance Matrix (array) that is 30x30.  In EXCEL the function is COVAR.  This matrix (array) tells how volatile one investment is compared to another.  Call that matrix C.

The variables are a Weights Matrix (array) that is 30x1.  This represents the percentage of your total investment you want to put into each stock.  The range is 0 <= w(i) <= 1.  The sum of the weights should be 1 (100%).  Call that Matrix W.

The Portfolio Return then is the matrix product of W times R.
The Variance (risk) is the matrix product a Matrix Multiply of (W-transposed, Matrix Multiply (C, W)

An example of this in excel is this worksheet:
[PO_20090101_20170101.XLSX](https://github.com/google/or-tools/files/4992106/PO_20090101_20170101.XLSX)

I would like to be able to do what the EXCEL solver does without having to put the data in EXCEL and then manually having to run the solver each time.

The objective is to MINIMIZE the Variance (which is a single number, but a rather complex calculation).

The constraints are 
1) that the Portfolio Return must be >= some value (in the spreadsheet represented by a percentage return per month, such as 1%)
2) That the sum of the weights cannot exceed 1.

Optionally the weights might be less than zero, but there should be an option to not let them be less than zero.  Weight less than zero represents "short selling" of a stock.

Another example of this, in Python is shown at this web site:
https://towardsdatascience.com/efficient-frontier-portfolio-optimisation-in-python-e7844051e7f

I would like to be able to do this entirely in C# with Google OR tools.  Is that possible?

**Comment by lperron** [comment]
Please use the mailing list.
