### ISSUE TITLE
Constraints and conditions between routes

### ISSUE THREAD

**Issue by OlatzSG001** [google/or-tools#2122]
Hi!

I would like to know if there is a way to make routes related between them with some constraints in a VRP TW. For example, I need to indicate that the route number 2 only can start after route number 1 has finished.

Also, I would like to know if there is a way to add X minute of pause in the route after some deliveries. For example, for route 1, when the vehicle has already delivered more than 400 units, it has to do a 30 minutes rest.

Thank you in advance.

**Comment by Mizux** [comment]
Please ask on the mailing list instead...

1) You can create some constraint like this
```python
routing.solver().Add(
  time_dimension.CumulVar(routing.End(1)) <=
  time_dimension.CumulVar(routing.Start(2)))
```
take a look at [samples](https://github.com/google/or-tools/tree/master/ortools/constraint_solver/samples) or the [online documentation](https://developers.google.com/optimization/routing)

2) You may use break to create this 30min rest.  
see: https://github.com/google/or-tools/blob/master/ortools/constraint_solver/samples/cvrptw_break.py
But I don't know how to link break against the number of delivered goods...
