### ISSUE TITLE
Multiple Merchants multiple Orders Routing

### ISSUE THREAD

**Issue by vtthanh83** [google/or-tools#2124]
Hello,

I am new to or-tools, currently I have problem to optimise routing for multiple merchants with multiple orders, ie. merchant A with list of orders A1, A2,..., A10 and merchant B with orders B1, B2, ... , B10. My problem is to find best routes to mix orders of A and B, ie. allow routes to pick up orders at B while delivering A's orders.

Expected solution is something like this:
Route1:  pickup at A -> A1 -> A2 -> A3 -> pick up at B -> A4 -> B1 -> B2 -> A5 -> B3 -> A6 -> A7
Route2: pickup at A -> A8 -> A9 -> pick up at B -> B4 -> B5 -> A10 -> B6 -> B7, etc.

Original my idea is to include depot B as a special visited point and all B's orders must visit after B, but this is ok only for 1 route, I could not find solution how to force all routes must visit B before visiting any B's orders.
Under stand or-tools has pick-up and deliver example but this is for a pair, I am wondering if I can utilise the example with some adjustment? 

Thanks,
Thanh

**Comment by lperron** [comment]
Please use the mailing list.
