### ISSUE TITLE
when adding AddDimensionWithVehicleCapacity to VRPTW, getting verflowError: in method 'RoutingIndexManager_IndexToNode', argument 2 of type 'int64'

### ISSUE THREAD

**Issue by amitca71** [google/or-tools#2127]
**What version of OR-tools and what language are you using?** 
Version: 7.7.7810
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
constraint_solver
**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
adding capacity constraint to VRPTW
without adding the capacity constraint all worked well, and i got good results (try to comment line 86 (routing.AddDimensionWithVehicleCapacity , and you get outcome)

**What did you expect to see**
expected to get solution with capacity constraint

**What did you see instead?**
\Anaconda3\envs\myenv\lib\site-packages\ortools\constraint_solver\pywrapcp.py in IndexToNode(self, index)
   2791     def IndexToNode(self, index: "int64") -> "operations_research::RoutingIndexManager::NodeIndex":
-> 2792         return _pywrapcp.RoutingIndexManager_IndexToNode(self, index)
   2793 

OverflowError: in method 'RoutingIndexManager_IndexToNode', argument 2 of type 'int64'

The above exception was the direct cause of the following exception:

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by amitca71** [comment]
sorry, i added wrong code. the following is the correct one:

"""Vehicles Routing Problem with time and capacity constraints"""

from __future__ import print_function
from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp

from time import sleep 
import math
from itertools import combinations



def create_data_model():
    """Stores the data for the problem."""
    data = {}
    data['time_matrix'] = [[0, 15, 11], [15, 0, 3], [11, 3, 0]]
    data['num_vehicles'] = 3
    data['time_windows']=[(0, 15), (15, 37), (11, 37)]
    data['depot']=0
    data['demands']=[1, 1]
    data['vehicle_capacities']=[3, 3, 3]
    return data

def createModel(timeFrameData, maxTimePerVehicle=50):
    # Create the routing index manager.
    manager = pywrapcp.RoutingIndexManager(len(timeFrameData['time_matrix']),
                                           timeFrameData['num_vehicles'], timeFrameData['depot'])

    # Create Routing Model.
    routing = pywrapcp.RoutingModel(manager)


    # Create and register a transit callback.
    def time_callback(from_index, to_index):
        """Returns the travel time between the two nodes."""
        # Convert from routing variable Index to time matrix NodeIndex.
        try:
            from_node = manager.IndexToNode(from_index)
            to_node = manager.IndexToNode(to_index)
        except Exception (e):
            print(e)
        return timeFrameData['time_matrix'][from_node][to_node]

    transit_callback_index = routing.RegisterTransitCallback(time_callback)

    # Define cost of each arc.
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

    # Add Time Windows constraint.
    time = 'Time'
    routing.AddDimension(
        transit_callback_index,
        0,  # allow waiting time
        maxTimePerVehicle,  # maximum time per vehicle
        False,  # Don't force start cumul to zero.
        time)
    time_dimension = routing.GetDimensionOrDie(time)
    # Add time window constraints for each location except depot.
    for location_idx, time_window in enumerate(timeFrameData['time_windows']):
        if location_idx == 0:
            continue
        index = manager.NodeToIndex(location_idx)
        time_dimension.CumulVar(index).SetRange(time_window[0], time_window[1])
    # Add time window constraints for each vehicle start node.
    for vehicle_id in range(timeFrameData['num_vehicles']):
        index = routing.Start(vehicle_id)
        time_dimension.CumulVar(index).SetRange(timeFrameData['time_windows'][0][0],
                                                timeFrameData['time_windows'][0][1])

    # Instantiate route start and end times to produce feasible times.
    for i in range(timeFrameData['num_vehicles']):
        routing.AddVariableMinimizedByFinalizer(
            time_dimension.CumulVar(routing.Start(i)))
        routing.AddVariableMinimizedByFinalizer(
            time_dimension.CumulVar(routing.End(i)))
    ##############################
    # Add Capacity constraint.
    def demand_callback(from_index):
        """Returns the demand of the node."""
        # Convert from routing variable Index to demands NodeIndex.
        from_node = manager.IndexToNode(from_index)
        return data['demands'][from_node]

    demand_callback_index = routing.RegisterUnaryTransitCallback(
        demand_callback)
#if u comment the below line, its providing result
    routing.AddDimensionWithVehicleCapacity( demand_callback_index, 0, timeFrameData['vehicle_capacities'], True, 'Capacity')
    ###############################
    # Setting first solution heuristic.
    search_parameters = pywrapcp.DefaultRoutingSearchParameters()
    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)

    # Solve the problem.
    solution = routing.SolveWithParameters(search_parameters)
    return(manager, routing, solution)


def print_solution(data, manager, routing, solution):
    """Prints solution on console."""
    time_dimension = routing.GetDimensionOrDie('Time')
    total_time = 0
    for vehicle_id in range(data['num_vehicles']):
        index = routing.Start(vehicle_id)
        plan_output = 'Route for vehicle {}:\n'.format(vehicle_id)
        while not routing.IsEnd(index):
            time_var = time_dimension.CumulVar(index)
            plan_output += '{0} Time({1},{2}) -> '.format(
                manager.IndexToNode(index), solution.Min(time_var),
                solution.Max(time_var))
            index = solution.Value(routing.NextVar(index))
        time_var = time_dimension.CumulVar(index)
        plan_output += '{0} Time({1},{2})\n'.format(manager.IndexToNode(index),
                                                    solution.Min(time_var),
                                                    solution.Max(time_var))
        plan_output += 'Time of the route: {}min\n'.format(
            solution.Min(time_var))
        print(plan_output)
        total_time += solution.Min(time_var)
    print('Total time of all routes: {}min'.format(total_time))


def main():
    """Entry point of the program."""
    # Instantiate the data problem.
    data = create_data_model()
    print(data)

    manager, routing, solution=createModel(data)
    print_solution(data, manager, routing, solution)

if __name__ == '__main__':
    main()

**Comment by lperron** [comment]
can you fix the indent problem ? You need to add 4 space in front of each line of code.

**Comment by amitca71** [comment]
"""Vehicles Routing Problem with time and capacity constraints"""

from __future__ import print_function
from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp

from time import sleep 
import math
from itertools import combinations



def create_data_model():
    """Stores the data for the problem."""
    data = {}
    data['time_matrix'] = [[0, 15, 11], [15, 0, 3], [11, 3, 0]]
    data['num_vehicles'] = 3
    data['time_windows']=[(0, 15), (15, 37), (11, 37)]
    data['depot']=0
    data['demands']=[1, 1]
    data['vehicle_capacities']=[3, 3, 3]
    return data

def createModel(timeFrameData, maxTimePerVehicle=50):
    # Create the routing index manager.
    manager = pywrapcp.RoutingIndexManager(len(timeFrameData['time_matrix']),
                                           timeFrameData['num_vehicles'], timeFrameData['depot'])

    # Create Routing Model.
    routing = pywrapcp.RoutingModel(manager)


    # Create and register a transit callback.
    def time_callback(from_index, to_index):
        """Returns the travel time between the two nodes."""
        # Convert from routing variable Index to time matrix NodeIndex.
        try:
            from_node = manager.IndexToNode(from_index)
            to_node = manager.IndexToNode(to_index)
        except Exception (e):
            print(e)
        return timeFrameData['time_matrix'][from_node][to_node]

    transit_callback_index = routing.RegisterTransitCallback(time_callback)

    # Define cost of each arc.
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

    # Add Time Windows constraint.
    time = 'Time'
    routing.AddDimension(
        transit_callback_index,
        0,  # allow waiting time
        maxTimePerVehicle,  # maximum time per vehicle
        False,  # Don't force start cumul to zero.
        time)
    time_dimension = routing.GetDimensionOrDie(time)
    # Add time window constraints for each location except depot.
    for location_idx, time_window in enumerate(timeFrameData['time_windows']):
        if location_idx == 0:
            continue
        index = manager.NodeToIndex(location_idx)
        time_dimension.CumulVar(index).SetRange(time_window[0], time_window[1])
    # Add time window constraints for each vehicle start node.
    for vehicle_id in range(timeFrameData['num_vehicles']):
        index = routing.Start(vehicle_id)
        time_dimension.CumulVar(index).SetRange(timeFrameData['time_windows'][0][0],
                                                timeFrameData['time_windows'][0][1])

    # Instantiate route start and end times to produce feasible times.
    for i in range(timeFrameData['num_vehicles']):
        routing.AddVariableMinimizedByFinalizer(
            time_dimension.CumulVar(routing.Start(i)))
        routing.AddVariableMinimizedByFinalizer(
            time_dimension.CumulVar(routing.End(i)))
    ##############################
    # Add Capacity constraint.
    def demand_callback(from_index):
        """Returns the demand of the node."""
        # Convert from routing variable Index to demands NodeIndex.
        from_node = manager.IndexToNode(from_index)
        return data['demands'][from_node]

    demand_callback_index = routing.RegisterUnaryTransitCallback(
        demand_callback)
#if u comment the below line, its providing result
    routing.AddDimensionWithVehicleCapacity( demand_callback_index, 0, timeFrameData['vehicle_capacities'], True, 'Capacity')
    ###############################
    # Setting first solution heuristic.
    search_parameters = pywrapcp.DefaultRoutingSearchParameters()
    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)

    # Solve the problem.
    solution = routing.SolveWithParameters(search_parameters)
    return(manager, routing, solution)


def print_solution(data, manager, routing, solution):
    """Prints solution on console."""
    time_dimension = routing.GetDimensionOrDie('Time')
    total_time = 0
    for vehicle_id in range(data['num_vehicles']):
        index = routing.Start(vehicle_id)
        plan_output = 'Route for vehicle {}:\n'.format(vehicle_id)
        while not routing.IsEnd(index):
            time_var = time_dimension.CumulVar(index)
            plan_output += '{0} Time({1},{2}) -> '.format(
                manager.IndexToNode(index), solution.Min(time_var),
                solution.Max(time_var))
            index = solution.Value(routing.NextVar(index))
        time_var = time_dimension.CumulVar(index)
        plan_output += '{0} Time({1},{2})\n'.format(manager.IndexToNode(index),
                                                    solution.Min(time_var),
                                                    solution.Max(time_var))
        plan_output += 'Time of the route: {}min\n'.format(
            solution.Min(time_var))
        print(plan_output)
        total_time += solution.Min(time_var)
    print('Total time of all routes: {}min'.format(total_time))


def main():
    """Entry point of the program."""
    # Instantiate the data problem.
    data = create_data_model()
    print(data)

    manager, routing, solution=createModel(data)
    print_solution(data, manager, routing, solution)

if __name__ == '__main__':
    main()

**Comment by amitca71** [comment]
> can you fix the indent problem ? You need to add 4 space in front of each line of code.

done

**Comment by Mizux** [comment]
do you know from which line, this exception is throw ?

**Comment by Mizux** [comment]
you demand `data['demands']=[1, 1] ` should be `data['demands']=[0, 1, 1]` otherwise second location 2 will be out of bound...

**Comment by amitca71** [comment]
Thanks alot for such a prompt answer 🥇 
the exception is abit misleading....
