### ISSUE TITLE
"google.protobuf.Int64Value" is not defined.

### ISSUE THREAD

**Issue by yurivict** [google/or-tools#2128]
I have the latest released protobuf-3.12.4 installed, and or-tools-7.8 fails:
```
[1/237] cd /wrkdirs/usr/ports/math/or-tools/work/.build && /usr/local/bin/protoc --proto_path=/wrkdirs/usr/ports/math/or-tools/work/or-tools-7.8 --cpp_out=/wrkdirs/usr/ports/math/or-tools/work/.build ortools/data/jobshop_scheduling.proto
FAILED: ortools/data/jobshop_scheduling.pb.cc ortools/data/jobshop_scheduling.pb.h
cd /wrkdirs/usr/ports/math/or-tools/work/.build && /usr/local/bin/protoc --proto_path=/wrkdirs/usr/ports/math/or-tools/work/or-tools-7.8 --cpp_out=/wrkdirs/usr/ports/math/or-tools/work/.build ortools/data/jobshop_scheduling.proto
google/protobuf/wrappers.proto: File not found.
ortools/data/jobshop_scheduling.proto:48:1: Import "google/protobuf/wrappers.proto" was not found or had errors.
ortools/data/jobshop_scheduling.proto:73:3: "google.protobuf.Int64Value" is not defined.
ortools/data/jobshop_scheduling.proto:96:3: "google.protobuf.Int64Value" is not defined.
ortools/data/jobshop_scheduling.proto:135:3: "google.protobuf.DoubleValue" is not defined.
```

**Comment by lperron** [comment]
can you try with 3.13.2 ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 4 août 2020 à 22:08, yuri@FreeBSD <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
It seems something has changed on the proto side.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by yurivict** [comment]
> can you try with 3.13.2 ?

I need to update the port, and ```3.13.2``` has been removed from the ports system as obsolete.

**Comment by Mizux** [comment]
According to the log, it seems there is no `--protoc_path=/wrkdirs/usr/ports/math/or-tools/work/or-tools-7.8/dependencies/install/include` thus protoc won't find "google/protobuf/wrappers.proto" if using a make based build.

Which builder did you used (cmake, bazel, make) ?
Did you use an installed version of protobuf (I.e. external dependencies) ?

**Comment by yurivict** [comment]
> Which builder did you used (cmake, bazel, make) ?

cmake

> Did you use an installed version of protobuf (I.e. external dependencies) ?

External protobuf installed from a package.

**Comment by Mizux** [comment]
So I guess I need to patch
https://github.com/google/or-tools/blob/a0a56698ba8fd07b7f84aee4fc45d891a8cd9828/cmake/cpp.cmake#L250-L256
The `MATCHES` seems weird
or
https://github.com/google/or-tools/blob/stable/cmake/FindProtobuf.cmake
since there is no `INTERFACE_INCLUDE_DIRECTORIES` defined...

**Comment by Mizux** [comment]
Does your protobuf installation provide a findProtobuf.cmake or pkgconfig file ?

**Comment by yurivict** [comment]
It provides .pc file.
