### ISSUE TITLE
[CMake] USE_SCIP=OFF not working

### ISSUE THREAD

**Issue by joshuaeckroth** [google/or-tools#2129]
libscip (SCIP optimization library) is suddenly required for any cmake C++ build, ignoring USE_SCIP option.

This line: https://github.com/google/or-tools/blame/stable/cmake/cpp.cmake#L222 requires libscip, ignoring the USE_SCIP setting. Removing this line allows a successful build (assuming one does not wish to use scipopt library).

**Comment by joshuaeckroth** [comment]
This is important for commercial uses since SCIP's license is not open source.

**Comment by Mizux** [comment]
For release v7.8 we get the agreement to integrate scip the build process, but yes you still need to comply with scip license limitation.

Having a USE_SCIP=OFF is a target goal, I'll try to fix it ASAP

**Comment by lperron** [comment]
Starting with or-tools 7.8, SCIP is not built in by default.
To use it, you must comply with the license. But this is not required for
just compiling it.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 6 août 2020 à 14:43, Joshua Eckroth <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
Do you think this is still a problem ?
I checked with the SCIP team before doing the change.

**Comment by lperron** [comment]
On master, I have added BUILD_SCIP=OFF in commented form in Makefile.local.
Uncommenting it, and then *make clean*, then* make all* will build or-tools
without SCIP support.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
