### ISSUE TITLE
CP-SAT: Multi_Threading crash

### ISSUE THREAD

**Issue by cfsfifty** [google/or-tools#2131]
**What version of OR-tools and what language are you using?**
Version: master/v7.7.7810
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows Version	10.0.18362 Build 18362

**What did you do?**
Starting model solution with
solver.parameters.log_search_progress = True
solver.parameters.num_search_workers  = 6

**What did you expect to see**
Solution of model or INFEASIBLE.

**What did you see instead?**
After 43460.28s:
Check failed: prev_[head] == -1 (7 vs. -1) Trivially UNSAT or duplicate arcs while adding 78 -> 86
*** Check failure stack trace: ***
    @   00007FFE9BA09CFB  PyInit__pywrapsat
    @   00007FFE9BA07FF9  PyInit__pywrapsat
    @   00007FFE9BCA6634  PyInit__pywrapsat
    @   00007FFE9BCA824A  PyInit__pywrapsat
    @   00007FFE9BC784A7  PyInit__pywrapsat
    @   00007FFE9BC78D0E  PyInit__pywrapsat
    @   00007FFE9BABD1F6  PyInit__pywrapsat
    @   00007FFE9BAAE9FF  PyInit__pywrapsat
    @   00007FFE9BCAFD79  PyInit__pywrapsat
    @   00007FFE9BED1FC1  PyInit__pywrapsat
    @   00007FFE9BED0DDF  PyInit__pywrapsat
    @   00007FFF23950E82  _beginthreadex
    @   00007FFF24797BD4  BaseThreadInitThunk
    @   00007FFF25C0CE51  RtlUserThreadStart

The model proto is here
[model_2_2.zip](https://github.com/google/or-tools/files/5039833/model_2_2.zip)

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
I believe this was fixed recently,
Can you check with 7.8 ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
I could reproduce it with 7.8

I have pushed a tentative fix.

**Comment by cfsfifty** [comment]
Thanks a lot! I am eagerly waiting for the fixed release.The problem looked similar to the one fixed in 7.8. I am currently still running 7.7. Do you run the solver in a cluster or the cloud? Thanks again,Christoph  Von: Laurent PerronGesendet: Saturday, August 8, 2020 10:31 PMAn: google/or-toolsCc: cfsfifty; AuthorBetreff: Re: [google/or-tools] CP-SAT: Multi_Threading crash (#2131) I could reproduce it with 7.8I have pushed a tentative fix.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lperron** [comment]
With the code on master (post 7.8), with parameters:

Parameters: log_search_progress: true linearization_level: 3
num_search_workers: 10

Optimality is proven in ~15000s

status: OPTIMAL

objective: 115

best_bound: 115

booleans: 24115

conflicts: 569945

branches: 2090278

propagations: 226954845

integer_propagations: 213987092

walltime: 15207.2

usertime: 151059

deterministic_time: 155393

primal_integral: 242125

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by cfsfifty** [comment]
Hi Laurent,

what is "linearization_level: 3" ?
Do you have some explanations for the options?
I am currently experimenting with AddCumulative and
AddRevervoirConstraint/AddRevervoirConstraintWithActive
for a buffer tank.

Thanks!


Am Mo., 10. Aug. 2020 um 23:08 Uhr schrieb Laurent Perron <
notifications@github.com>:

**Comment by lperron** [comment]
the linearization_level controls how complete is the linear relaxation of
the problem passed to the internal simplex.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by cfsfifty** [comment]
Interesting, do you have a link about that?
What linear relaxation do you use?

Am Mo., 17. Aug. 2020 um 13:09 Uhr schrieb Laurent Perron <
notifications@github.com>:

**Comment by lperron** [comment]
Nothing spectacular
linear, enforced linear, boolean or and and, circuit constraint + sub tour
elimination dynamic cuts, dynamic linearization of product and square.
We are starting to look at scheduling relaxation, but literature is not
adapted as most of what it does is already captured by the CP propagation.

See ortools/sat/linear_relaxation.{cc|h} and ortools/sat/cuts.{cc|h}
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by cfsfifty** [comment]
So you use CP propagation and simplex relaxation. And generate constraints
as in
"Search is dead, long live proof"
https://people.eng.unimelb.edu.au/pstuckey/PPDP2013.pdf

When do you use CP propagation and when simplex relaxation?
Do you solve for single values with the simplex?
I am currently interested in scheduling, and I have a buffer tank which
complicates the solution.

Am Mo., 17. Aug. 2020 um 17:12 Uhr schrieb Laurent Perron <
notifications@github.com>:

**Comment by lperron** [comment]
I do not understand single value for the simplex.

We use simplex in multiple ways:
  - infeasibility detection
  - lower bound of the objective
  - reduced cost fixing
  - search heuristics
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
