### ISSUE TITLE
Google Or Tools error when "make java" in linux

### ISSUE THREAD

**Issue by frankcheng1991** [google/or-tools#2132]
ORIGIN/../dependencies/install/lib'
objs/swig/sat_java_wrap.o: In function `Swig::ExceptionMatches(JNIEnv_*, _jthrowable*, char const*)':
sat_java_wrap.cc:(.text+0x299): multiple definition of `Swig::ExceptionMatches(JNIEnv_*, _jthrowable*, char const*)'
objs/swig/constraint_solver_java_wrap.o:constraint_solver_java_wrap.cc:(.text+0x1501d): first defined here
collect2: error: ld returned 1 exit status
make: *** [lib/libjniortools.so] Error 1

**Comment by lperron** [comment]
Which distribution?

**Comment by Mizux** [comment]
Which version of SWIG ?

**Comment by frankcheng1991** [comment]
Thanks for all of your reply, below are my running environments:

Swig: 3.0.5
Jdk:  1.8.0_262
Python 3.6.9
Ruby: 2.0.0p648 (2015-12-16)
gcc/g++: 4.9.2
cmake: 3.6.2 
os: Centos 7

Try to make java version of google or-tools from "stable" branch.

By the way, actually I am trying to use flatzinc version of or-tools inside Java projects. The binary version only contains flatzinc-or-tools.exe/.so, and I don't want to only use them in command line tools. That's why I try "make java" version of or-tools.

Thanks a million!

**Comment by lperron** [comment]
I believe you need a later swig (3.0.12 at least IMO).

Le lun. 10 août 2020 à 17:10, frankcheng1991 <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
Note that the de solver has no API to get a solution. It only outputs to
stdout.

**Comment by stradivari96** [comment]
gcc also looks a bit dated

**Comment by frankcheng1991** [comment]
The problem has been resolved by upgrading Swig from 3.0.5 to 3,0.12. 

Thanks a lot again!

I will close this issue.
