### ISSUE TITLE
AddMultiplicationEquality and negative integers ( range [-1, 0, 1] )

### ISSUE THREAD

**Issue by HenkVandecasteele** [google/or-tools#2133]
**What version of OR-tools and what language are you using?**
Version: 7.7.7810
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Solver: CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Operating System: Windows

**What did you do?**
1. Run example program in Attachment 
[topology.zip](https://github.com/google/or-tools/files/5050570/topology.zip)

**What did you expect to see**
Solutions for the constraint Z = X*Y with domains [-1,0,1] of these variables 

**What did you see instead?**
An error-message:
"Not supported
*** Check failure stack trace: ***
...
"
Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
This is just an example, many constraints of type Z=X*Y will be automatically generated in the real program, where many variables with the range [-1, 0,  1] are kept in matrices. Multiplication of these matrices leads to such constraints.

Maybe I'm expecting too much using such constraints with a domain including negative, zero and positive values. Probably I can get around it by generating constraints as follows (with quite some extra variables and constraints as penalty ;-) . :
 AbsX = abs(X)
 AbsY = abs(Y)
 AbsZ = abs(Z)
 AbsZ = AbsX* AbsY
 (X >= 0).OnlyEnforceIf(PositiveX) 
 (X < 0) . OnlyEnforceIf(PositiveX.not())
 (Y >= 0).OnlyEnforceIf(PositiveY) 
 (Y < 0) . OnlyEnforceIf(PositiveY.not())
 (Z >= 0).OnlyEnforceIf(PositiveZ) 
 (Z < 0) . OnlyEnforceIf(PositiveZ.not()))
 (PositiveX == PositiveY).OnlyEnforceIf(PositiveZ)
 (PositiveX != PositiveY).OnlyEnforceIf(PositiveZ.not())

Is this the way to go? Or was the original constraint  Z=X*Y  expected to work?

**Comment by HenkVandecasteele** [comment]
So I tried: 

``
# Z = X *Y, assuming range of all variables [-1,1]
def multiply(model, Z, X, Y):   
    AbsX = model.NewIntVar(-1, 1, "")
    AbsY = model.NewIntVar(-1, 1, "")
    AbsZ = model.NewIntVar(-1, 1, "")
    PositiveX = model.NewBoolVar("")
    PositiveY = model.NewBoolVar("")
    PositiveZ = model.NewBoolVar("")
    model.AddAbsEquality(AbsX, X)
    model.AddAbsEquality(AbsY, Y)
    model.AddAbsEquality(AbsZ, Z)
    model.AddMultiplicationEquality(AbsZ, [AbsX, AbsY])
    model.Add(X >= 0).OnlyEnforceIf(PositiveX)
    model.Add(X < 0). OnlyEnforceIf(PositiveX.Not())
    model.Add(Y >= 0).OnlyEnforceIf(PositiveY)
    model.Add(Y < 0). OnlyEnforceIf(PositiveY.Not())
    model.Add(Z >= 0).OnlyEnforceIf(PositiveZ)
    model.Add(Z < 0).OnlyEnforceIf(PositiveZ.Not())
    model.Add(PositiveX == PositiveY).OnlyEnforceIf(PositiveZ)
    model.Add(PositiveX != PositiveY).OnlyEnforceIf(PositiveZ.Not())    
``
Gives me:
``
solution 1 X=0 Y=0 Z=0
solution 2 X=0 Y=1 Z=0
solution 3 X=1 Y=0 Z=0
solution 4 X=-1 Y=1 Z=-1
solution 5 X=-1 Y=-1 Z=1
solution 6 X=1 Y=-1 Z=-1
solution 7 X=1 Y=1 Z=1
``

So that is doing the trick. Still the question if  this is the expected way of encoding such constraint, ... .  Thanks in advance!

**Comment by lperron** [comment]
First time in 20 years that I have seen a real need to multiplication
between 2 general integer variables.

Your encoding is very slow, you can use an allowed assignments constraint
with the 9 possible tuples.

**Comment by HenkVandecasteele** [comment]
@lperron Thanks for the advice! 
Actually my coding above is wrong in the case of 1 negative value and the other value 0  :-( .
The assignment-based solution will be easier to verify!

Regards,

Henk

**Comment by lperron** [comment]
I have pushed support for product with variables spanning across 0.
