### ISSUE TITLE
Minimize Global Span Cost + Distributed nodes per vehicle

### ISSUE THREAD

**Issue by cacosandon** [google/or-tools#2138]
**What version of OR-tools and what language are you using?**
Version: master
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CVRPTW
**What operating system (Linux, Windows, ...) and version?**
Linux

--------------------

Hello!

I am working in a VRPTW with many vehicles. When I have different pickup and deliveries that are mixed in a map, the solver always result in all nodes for only one vehicle.

I already did a lot of things: set GlobalSpanCost for different dimensions (distance, time, unary, etc.), setting minimum nodes to visit (unfeasible), changing first solution strategy, working with metaheuristics, more time, log search and nothing works.

Any one with the same problem? How can I fix this?

Thank you :)

**Comment by lperron** [comment]
Please use the mailing list.
