### ISSUE TITLE
1 trivial restriction fails

### ISSUE THREAD

**Issue by huig-** [google/or-tools#2139]
I am working with LinearSolver (SAT_INTEGER_PROGRAMMING) on version 7.8.7959 with C# and after a couple hours I found that the constraint that was making the model infeasible (with more than 50k constraints) could be reduced just to the following code. In the actual model I need a variable to take values up to 20000000 to make some slack constraints true (sum + slack >= 2e+07 or some bigger values) when needed

INFEASIBLE:
````csharp
Solver newSolver = Solver.CreateSolver("NOT_WORKING", "SAT_INTEGER_PROGRAMMING");
Variable aux = newSolver.MakeNumVar(Double.MinValue, Double.PositiveInfinity, "test");
Objective obj = newSolver.Objective();
obj.SetCoefficient(aux, 1);
obj.SetMaximization();
newSolver.Add(aux == 20000000);
Solver.ResultStatus r = newSolver.Solve();
````

OPTIMAL
````csharp
Solver newSolver = Solver.CreateSolver("WORKING", "SAT_INTEGER_PROGRAMMING");
Variable aux = newSolver.MakeNumVar(Double.MinValue, Double.PositiveInfinity, "test");
Objective obj = newSolver.Objective();
obj.SetCoefficient(aux, 1);
obj.SetMaximization();
newSolver.Add(aux == 10000000);
Solver.ResultStatus r = newSolver.Solve();
````

Also, Double.PositiveInfinity < 20000000 is false.

**Comment by stradivari96** [comment]
Small comment, adding this kinda works:
```
newSolver.SetSolverSpecificParametersAsString("mip_max_bound: 1e8")
```

**Comment by lperron** [comment]
exactly.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 19 août 2020 à 16:00, Xiang Chen <notifications@github.com> a
écrit :
