### ISSUE TITLE
Weekly Scheduling Problem

### ISSUE THREAD

**Issue by Surya-Vijayakumar** [google/or-tools#2141]
**What language and solver does this apply to?**
Python, Routing

**Describe the problem you are trying to solve.**
@Mizux Would be great if you can point me towards a solution that has been framed for the below through or tools

We have a travel time matrix for all the locations

The locations have multiple time windows which fall at the same time frame but on different days of the week. While some locations may have multiple time windows, others only have a single time window where order can be served, 

The trucks have capacity constraints. They can only take up-to a certain amount of load in lbs.

The trucks also have travel constraints. Trucks can only travel max 'X' hours in day. And after 'X' hours, a break-time of 'Y' hours needs to be provided and then the truck should restart again the next day and continue to serve orders until all orders on its manifest are served.

The objective is to serve all orders and minimize the number of trucks used along with distance traveled.

**Comment by lperron** [comment]
Please use the mailing list.

**Comment by Surya-Vijayakumar** [comment]
Can you please share the mailing list

**Comment by lperron** [comment]
That was the link given in the create issue page in the modeling section.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
