### ISSUE TITLE
Logging Printing while not enabled

### ISSUE THREAD

**Issue by timothylowjc** [google/or-tools#2143]
**What version of OR-tools and what language are you using?**
Version:  7.8.7959
Language: Python 3.6.9

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows Subsystem Linux

**What did you do?**
So I ran my model as per usual, but noticed it was printing messages I'd not seen before:

![image](https://user-images.githubusercontent.com/43809753/91686209-45ac6c80-eb8f-11ea-9c4a-4ec1b4abffe5.png)

Those "Cut" messages had usually not appeared, but for some reason showed up in this one. I understand its some experimental thing that was recently added, but did not expect printed messages.

https://github.com/google/or-tools/issues/2019 This thread mentions that with logging enabled these messages will appear, but I don't have logging enabled, and they appear no matter how i call the solution caller.

Also, they appear to pop up relatively inconsistently? This bug happened a while ago but I wasn't able to replicate, but for this particular problem model it comes up every time.

Make sure you include information that can help us debug (full error message, model Proto).

[2020-08-31 134340.txt](https://github.com/google/or-tools/files/5148482/2020-08-31.13.43.40.txt)

model proto as above.

Apologies if I'm posting in the wrong place, the only other relevant git issue I could find was the one I posted above

**Comment by lperron** [comment]
Are you sure logging is not enabled ?

This is the code that prints out this log:

  if (sat_parameters_.log_search_progress() && num_cuts_ > 0) {
    LOG(INFO) << "Total cuts added: " << num_cuts_;
    for (const auto& entry : type_to_num_cuts_) {
      LOG(INFO) << "Added " << entry.second << " cuts of type '" << entry.first
                << "'.";
    }
  }

To me, this is clear you need to set up log_search_progress.

**Comment by stradivari96** [comment]
Maybe it is related to https://github.com/google/or-tools/issues/1918#issuecomment-674039627?

In windows it used to log
`Total cuts added: 0`
quite a few times.

**Comment by lperron** [comment]
This was removed.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 31 août 2020 à 22:07, Xiang Chen <notifications@github.com> a
écrit :

**Comment by timothylowjc** [comment]
Hey thanks for the response! So I saw log_search_progress, but

![image](https://user-images.githubusercontent.com/43809753/91794630-245e8580-ec4e-11ea-9fa3-d22793ea526c.png)

I noticed it specifically defaults to False, and so don't call that parameter in my code at all. I could do maybe `solver.parameters.log_search_progress = False` on top of that, but if it really defaults to False then this seems like a bug anyway

**Comment by stradivari96** [comment]
Sorry, what I meant is that this might have already been fixed on master as that other fix isn't deployed yet
