### ISSUE TITLE
operations_research_constraint_solverPINVOKE

### ISSUE THREAD

**Issue by escoma77** [google/or-tools#2144]
The type initializer for 'Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE' threw an exception.
System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'Google.OrTools.runtime.win-x64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

I had this exception and search all same problem and my solution was:
The problem was that the nuget packages was in user folder, in my case it's a service how executes the dll, I changed de user in the service and work

C:\Users\"user"\.nuget\packages\google.ortools.runtime.win-x64\7.5.7466

**Comment by Mizux** [comment]
OR-Tools is splitted in, at least, two package a runtime platform dependent package providing the C++ and swig wrapper library, and a "pure" .Net package depending of this package.

Please take a look at https://github.com/Mizux/dotnet-native if you want to understand how it is working on a simpler project...
