### ISSUE TITLE
Function to set the start value of a dimension

### ISSUE THREAD

**Issue by Surya-Vijayakumar** [google/or-tools#2145]
**What language and solver does this apply to?**
Python

**Describe the problem you are trying to solve.**
Which function to use to set start value of a dimension in or-tools?

**Comment by lperron** [comment]
Please use the mailing list.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Surya-Vijayakumar** [comment]
Hi, Please do accept my join request
