### ISSUE TITLE
Feed initial solution suggestion to cp model

### ISSUE THREAD

**Issue by PMLP-novo** [google/or-tools#2146]
**What language and solver does this apply to?**
Python

**Describe the problem you are trying to solve.**
I have a very complex optimisation problem where I can only solve the problem if I first make an optimisation running with many more constraints to produce a candidate good heuristic solution and then optimising again using without the unnecessary constraints and the initial solution as a starting point

**Describe the solution you'd like**
```
# Make base model with real constraints and variables
data = get_data()
model = cp_model.CpModel()
add_make_variables(model, data)
add_constraints(model, data)

# Add constraints that minimizes search space but only leads to sub-optimal solution
add_unnesseary_constraints(model, data)
initial_solver = cp_model.CpSolver()
initial_solver.Solve(model)

remove_unnessary_constraints(model,data)

# Find the optimal solution using the sub-optimal solution as starting point
final_solver = cp_model.CpSolver()
final_solver.Solve_with_initial_solution(model, initial_solver.__solution)
```

**Describe alternatives you've considered**
Alternatively if deleting constraints are not possible recreating the model and transferring the initial solution by name match is also a thing I considered

**Comment by lperron** [comment]
This is called hinting and documented ( :-) ) here:
http://google.github.io/or-tools/python/ortools/sat/python/cp_model.html#cp_model.CpModel.AddHint
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by PMLP-novo** [comment]
Okay thank you for the hint.
Then i would just like to know to hint a full solution. Like
```
def HintFullSolutionByNameMatch(full_model, restricted_model, restricted_solver):
    for restricted_variable in restricted_model.__model.variables:
        full_model_variable = full_model.get_variable_by_name(restricted_variable.name)
        if full_model_variable:
            hint_value = restricted_solver.Value(restricted_variable)
            full_model.AddHint(full_model_variable,hint_value)
```
Then I think I'm good to go. 
And by the way thanks for your help
