### ISSUE TITLE
Strange behaviors with float values

### ISSUE THREAD

**Issue by andersoncarlosfs** [google/or-tools#2149]
Version: 7.8.7959 (pip)
Language: Python
SO: Linux (Ubuntu)

Example: Capacity Constraints

1. Copy the CVRP example (https://developers.google.com/optimization/routing/cvrp)
2. Replace the integer values with float values: 
    - Original data (https://developers.google.com/optimization/routing/cvrp#model):
   ```
   data['demands'] = [0, 1, 1, 2, 4, 2, 4, 8, 8, 1, 2, 1, 2, 4, 4, 8, 8]
   data['vehicle_capacities'] = [15, 15, 15, 15]
   ```
    - New data:
   ```
   data['demands'] = [0.0, 0.1, 0.1, 0.2, 0.4, 0.2, 0.4, 0.8, 0.8, 0.1, 0.2, 0.1, 0.2, 0.4, 0.4, 0.8, 0.8]
   data['vehicle_capacities'] = [1.5, 1.5, 1.5, 1.5]
   ```
3. See some strange results 

Expectations: Each vehicle carrying a demand equal or less to its capacity (https://developers.google.com/optimization/routing/cvrp#solution)

> Route for vehicle 0:
>  0 Load(0) ->  1 Load(1) ->  4 Load(5) ->  3 Load(7) ->  15 Load(15) ->  0 Load(15)
> Distance of the route: 2192m
> Load of the route: 15
> 
> Route for vehicle 1:
>  0 Load(0) ->  14 Load(4) ->  16 Load(12) ->  10 Load(14) ->  2 Load(15) ->  0 Load(15)
> Distance of the route: 2192m
> Load of the route: 15
> 
> Route for vehicle 2:
>  0 Load(0) ->  7 Load(8) ->  13 Load(12) ->  12 Load(14) ->  11 Load(15) ->  0 Load(15)
> Distance of the route: 1324m
> Load of the route: 15
> 
> Route for vehicle 3:
>  0 Load(0) ->  9 Load(1) ->  8 Load(9) ->  6 Load(13) ->  5 Load(15) ->  0 Load(15)
> Distance of the route: 1164m
> Load of the route: 15
> 
> Total distance of all routes: 6872m
> Total load of all routes: 60

Results: Empty vehicles

> Route for vehicle 0:
>  0 Load(0.0) ->  0 Load(0.0)
> Distance of the route: 0m
> Load of the route: 0.0
> 
> Route for vehicle 1:
>  0 Load(0.0) ->  0 Load(0.0)
> Distance of the route: 0m
> Load of the route: 0.0
> 
> Route for vehicle 2:
>  0 Load(0.0) ->  0 Load(0.0)
> Distance of the route: 0m
> Load of the route: 0.0
> 
> Route for vehicle 3:
>  0 Load(0.0) ->  9 Load(0.1) ->  5 Load(0.30000000000000004) ->  8 Load(1.1) ->  6 Load(1.5) ->  2 Load(1.6) ->  10 Load(1.8) ->  16 Load(2.6) ->  14 Load(3.0) ->  13 Load(3.4) ->  12 Load(3.6) ->  11 Load(3.7) ->  15 Load(4.5) ->  3 Load(4.7) ->  4 Load(5.1000000000000005) ->  1 Load(5.2) ->  7 Load(6.0) ->  0 Load(6.0)
> Distance of the route: 4384m
> Load of the route: 6.0
> 
> Total distance of all routes: 4384m
> Total load of all routes: 6.0

**Comment by lperron** [comment]
Floats are not supported. They are all implemented sounded to integer.
