### ISSUE TITLE
Possible algorithm bug unpacking RoutingModel solution

### ISSUE THREAD

**Issue by mwpowellhtx** [google/or-tools#2150]
Hello, we are working from the [printer example](https://developers.google.com/optimization/routing/vrp#printer) as an algorithm basis unpacking the RoutingModel solution into our domain model, however, we are finding an apparent discrepancy, or maybe we are not doing something quite right.

Per the [_Google Groups OrTools thread_](https://groups.google.com/u/2/g/or-tools-discuss/c/B9RXwgnfpzQ) for background...

So, I have sprinkled strategic debug output throughout our solver approach, documented before/after fuel costs when dimensions are introduced, before/after the solution itself is evaluated, as well as before and after unpacking the assignment.

The domain model, the underlying intended fuel costs, in this case, are correct through and through.

Next, the solver debug output indicates to me that the fuel costs also seem correct, at least as reported via the solver debug message; i.e. let's say the limit was 150, right, the solver incrementally accumulates as expected, 0, 30, 60, 120, 130, and so on. Capped at the 150. That is correct and expected.

However, when we unpack the solution vis-a-vis the printer example, we get a completely different sum, something entirely not bounded by the dimensional vehicle maximum capacity of 150, in excess of that, 175, 210, 260, whatever.

Will post the code from the example here, then also a sample of our algorithm for analysis. Maybe someone notices something that I did not, but I think something may also be not quite right with the indices, etc.

**Comment by mwpowellhtx** [comment]
The example printer algo as a cross reference:

```C#
/// <summary>
///   Print the solution.
/// </summary>
static void PrintSolution(
    in DataModel data,
    in RoutingModel routing,
    in RoutingIndexManager manager,
    in Assignment solution) {
  // Inspect solution.
  long maxRouteDistance = 0;
  for (int i = 0; i < data.VehicleNumber; ++i) {
    Console.WriteLine("Route for Vehicle {0}:", i);
    long routeDistance = 0;
    var index = routing.Start(i);
    while (routing.IsEnd(index) == false) {
      Console.Write("{0} -> ", manager.IndexToNode((int)index));
      var previousIndex = index;
      index = solution.Value(routing.NextVar(index));
      routeDistance += routing.GetArcCostForVehicle(previousIndex, index, 0);
    }
    Console.WriteLine("{0}", manager.IndexToNode((int)index));
    Console.WriteLine("Distance of the route: {0}m", routeDistance);
    maxRouteDistance = Math.Max(routeDistance, maxRouteDistance);
  }
  Console.WriteLine("Maximum distance of the routes: {0}m", maxRouteDistance);
}
```

**Comment by mwpowellhtx** [comment]
And a sample of our approach. Couple of highlights here. First, `Context` is nothing special. It contains domain oriented `Vehicles` and `Nodes`, basically, as well as a healthy instance of the `RoutingIndexManager` and `RoutingModel`, and any other `Options` that may be useful informing bits of our solver approach.

```C#
for (var vehicleIndex = 0; vehicleIndex < this.Context.Vehicles.Length; vehicleIndex++)
{
    var routePoints = new List<string> { "S" };
    var vehicle = this.Context.Vehicles.ElementAt(vehicleIndex);
    for (var routeIndex = this.Context.RoutingModel.Start(vehicleIndex)
        ; !this.Context.RoutingModel.IsEnd(routeIndex)
        ; routeIndex = assignment.Value(this.Context.RoutingModel.NextVar(routeIndex)))
    {
        // -1 here because we add S+nodes+E boundaries in the routing model.
        var stopIndex = this.Context.RoutingIndexManager.IndexToNode(routeIndex) - 1;
        if (stopIndex >= 0)
        {
            var stop = this.Context.Stops.ElementAt(stopIndex);
            routePoints.Add(stop.Description);
            // Do other things with stop...
            vehicle.Stops.Add(stop);
        }
    }
    routePoints.Add("E");
    Console.WriteLine($"Route for {vehicle.Name}: {Join(" -> ", routePoints)}");
}
```

**Comment by mwpowellhtx** [comment]
We are currently using [NuGet package Google.OrTools 7.7](https://www.nuget.org/packages/Google.OrTools/7.7.7816), if that makes any difference. Maybe there was a breaking change somehow, I do not know.

**Comment by mwpowellhtx** [comment]
Not sure what else to do with this one at the moment. It "used to work" as far as any of us can determine. However, now it seems like it does not. The debug output would indicate that the routing model at least made the correct decision. But perhaps we are not interpreting the indices correctly unpacking the solution assignment. That is the most likely thing, I think.

@Mizux Would you or someone mind clarifying, as far as I can tell it should be "fine" to approach as a `for` loop, but maybe there is some interaction with the `RoutingModel` and or `RoutingIndexManager` that I am unware of.

**Comment by mwpowellhtx** [comment]
@Mizux I am trying different things to see if I can persuade a better response, and it has gone from "ignoring" a certain dimension, to perhaps correctly not yielding any solutions whatseover, which is really bizarre to me. I'm sure it will be obvious when we isolate and contain the root cause, but for now it is a mystery. Would you mind sparing a few moments to join me in a Google Meeting to assess some dimensions and such? Maybe something will jump out at you that our usage is not right.

**Comment by Mizux** [comment]
Does your dimension have a non null slack ? so the solver can use it to "refill" your fuel dimension.
Otherwise I don't see any thing strange...

note: by default the arc cost from start to end without visiting any node is 0 even if your callback return a positive number.
see: https://github.com/google/or-tools/blob/a0a56698ba8fd07b7f84aee4fc45d891a8cd9828/ortools/constraint_solver/routing.h#L883-L891

**Comment by mwpowellhtx** [comment]
After some educated guesses, I think it is an over-zealous _dimensional indexing filter_ on my part. In the process of verifying that hypothesis. By filter I mean, checking for routing model index out of range versus domain model same, i.e. `from <= 0 || to <= 0` and so on... Niavely you might think that was innocuous, but I think in some cases it actually makes a difference.

**Comment by mwpowellhtx** [comment]
Verified, yes, it is a dimension indexing thing. I'd taking a strong position to weed out _S+node+E_ edges in the Routing Model evaluator callbacks, and apparently in some cases, we only use the `from` or the `to` index, so too strong a position is too strong in the overall solution. So we dial that back slightly in those cases and it works fine.
