### ISSUE TITLE
Build fails with -llibscip when USE_SCIP=OFF

### ISSUE THREAD

**Issue by yurivict** [google/or-tools#2152]
**What version of OR-tools and what language are you using?**
Version: 7.8
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
default build

**What operating system (Linux, Windows, ...) and version?**
FreeBSD 12.1

**What did you do?**
cmake .
gmake

**What did you expect to see**
success

**What did you see instead?**
Build failed.
```
ld: error: unable to find library -llibscip
```

```-llibscip``` should never be specified (the lib part should be dropped in -l option). In my case SCIP was turned off, so it shouldn't have appeared at all.

**Comment by Mizux** [comment]
should be fixed on master
see: https://github.com/google/or-tools/commit/cc2fdb6e7aeb873aa079cbc4d34cb532f415efb6#diff-ed5192e5b0d17843cb9549861c9e2516
