### ISSUE TITLE
multiple threads crash  error

### ISSUE THREAD

**Issue by hukun1995** [google/or-tools#2157]
ERROR LOG:

#Done 0.12s no_lp
Check failed: !is_present Duplicate variables not supported.
*** Check failure stack trace: ***
 @ 0x7f73ae655dec google::LogMessage::Fail()
 @ 0x7f73ae655d48 google::LogMessage::SendToLog()
 @ 0x7f73ae6556ac google::LogMessage::Flush()
 @ 0x7f73ae658b16 google::LogMessageFatal::~LogMessageFatal()
 @ 0x7f73a77628c2 operations_research::sat::CpModelPresolver::ExpandObjective()
 @ 0x7f73a776c1d9 operations_research::sat::CpModelPresolver::Presolve()
 @ 0x7f73a776c9b1 operations_research::sat::PresolveCpModel()
 @ 0x7f73a7793151 _ZZN19operations_research3sat12_GLOBAL__N_19LnsSolver12GenerateTaskElENKUlvE_clEv
 @ 0x7f73a78c946c _ZNSt17_Function_handlerIFvvEZN19operations_research3sat20NonDeterministicLoopERKSt6vectorISt10unique_ptrINS2_9SubSolverESt14default_deleteIS5_EESaIS8_EEiEUlvE_E9_M_invokeERKSt9_Any_data
 @ 0x7f73a75a6448 operations_research::RunWorker()
 @ 0x7f73ac0d119d execute_native_thread_routine
 @ 0x7f73cc4cfe25 start_thread
 @ 0x7f73cbde134d __clone
 @ (nil) (unknown)

numWorker:8 ; cpu num:5; Linux: CentOS

**Comment by lperron** [comment]
Please specify the or-tools version, the platform, and attach some model or
code.that can be used to reproduce the crash.

Le jeu. 17 sept. 2020 à 05:55, hukun1995 <notifications@github.com> a
écrit :

**Comment by hukun1995** [comment]
the version of or-tools is 7.7 ; setLogSearchProgress is true; numWoker is 8
the platform is docker with CentOs 16+ , one docker has 5 cpu

Code is complecated and it is formal  code, so I am sorry I can't push it .
But I can show the main cp-sat function we used, may it help you:
"addEq;  addEqWithOffset; addLessOrEq; addProductEq; addAbsEquality; addDivisionEquality ,,, "

**Comment by lperron** [comment]
Try with 7.8. We fixed a few crashes in between.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 17 sept. 2020 à 11:44, hukun1995 <notifications@github.com> a
écrit :

**Comment by Mizux** [comment]
No news, spotted on an older version -> closing this issue
