### ISSUE TITLE
Same parameters result in the different solution with cp solver.

### ISSUE THREAD

**Issue by qinchao0915** [google/or-tools#2159]
I am working on a bus scheduling with cp solver. I found if I used the same parameters(with the same time table, the same bus shifts), the solver gave the different solutions as the pic below. I did not set the optimal target.

 Is there any randomness in the cp solver? And how can I control the result when I use the same parameters, it shows the same result. Thank you in advance.

**Comment by lperron** [comment]
Parallel search is non deterministic.

Le ven. 18 sept. 2020 à 05:00, qinchao0915 <notifications@github.com> a
écrit :
