### ISSUE TITLE
SetCumulVarSoftLowerBound not working as expected when a vehicle is not used

### ISSUE THREAD

**Issue by danmarinescu** [google/or-tools#2161]
**What version of OR-tools and what language are you using?**
Version: 7.8.7959
Language: Python

**Which solver are you using?**
Routing Solver

**What operating system (Linux, Windows, ...) and version?**
Linux Debian 10 (Buster)

**What did you do?**
I am trying to balance the distribution of "jobs" between vehicles. First I determine what an even distribution of jobs would be. This value is then used as a soft lower bound imposed at each vehicle's end depo, on a dimension that counts the amount of work performed. 

Below is a simplified version of my implementation to showcase the issue. In this example 2 jobs, each with a duration of 15, are to be equally distributed among two vehicles.

```Python
def working_time_callback(self, index: int) -> int:
    return 15

def add_workload_balancing_dimension(self) -> None:
    working_time_callback_index = self.routing.RegisterUnaryTransitCallback(self.working_time_callback)
    self.routing.AddDimension(
        working_time_callback_index,  # index of callback used to compute the working time of each vehicle
        0,  # the slack variable max is set to 0, as there is no idle time when computing working time
        100,  # maximum working time allowed per vehicle
        True,  # working time starts at 0 and increases with each worked job
        WORKING_TIME_DIMENSION_ID
    )
    self.working_time_dimension = self.routing.GetDimensionOrDie(WORKING_TIME_DIMENSION_ID)

    # set a soft lower bound  of 15 on the amount of time worked
    # by all vehicles; anything below this bound gets multiplied by 5
    for d, _ in enumerate(self.vehicles):
        vehicle_end_booking_index = self.routing.End(d)
        self.working_time_dimension.SetCumulVarSoftLowerBound(
            vehicle_end_booking_index,  # index at which the bound is set
            15,  # the lower bound
            5,  # cost coefficient
        )
```

**What did you expect to see**
I expected each vehicle to get assigned one job. Lacking that, I expected the soft lower bound to result in additional costs to the solution.

**What did you see instead?**
Both jobs were assigned to the same vehicle. Since this could be due to other hard/soft constraints I have in my model, I checked the total costs given by the solutions `ObjectiveValue()` and noted that they were equal to the routing costs of the vehicle which had jobs assigned. This means there there was no penalty for the fact that the second vehicle had no jobs assigned, as one would expect after setting the soft lower bound. More specifically, I expected a penalty of
`(15 (the soft lower bound) - 0 (the amount of time worked by the second vehicle)) * 5  (the cost penalty coeff) = 75` to be added to the total costs of the solution, but that was not the case.

What I noticed from playing with other examples is that the soft lower bound only results in a penalty if the vehicle in question has jobs assigned to it. So e.g. if the lower bound is `40` and the vehicle gets assigned a total of `30` then this results in a added cost of `(40 - 30) * 5 = 50`. However, if the vehicle does not get any jobs assigned, the soft lower bound has no effect, i.e. nothing gets added to the total costs of the solution.

**Comment by danmarinescu** [comment]
Note that my balancing model is similar to the one proposed by @jmarca in https://github.com/google/or-tools/issues/1351#issuecomment-501537397

**Comment by Mizux** [comment]
Did you try to enable empty route cost ?
https://github.com/google/or-tools/blob/a0a56698ba8fd07b7f84aee4fc45d891a8cd9828/ortools/constraint_solver/routing.h#L883-L886
note: disable by default...
My guess is for empty route, **all** cost are ignored...

**Comment by danmarinescu** [comment]
Wasn't aware of that, just enabled empty route costs for all vehicles and it solved my problem. 

Thanks @Mizux, much appreciated.
