### ISSUE TITLE
Any comparison of MIP and CP-SAT solvers? why MIP solver is not finding better solutions?

### ISSUE THREAD

**Issue by amobash2** [google/or-tools#2169]
**What version of OR-tools and what language are you using?**
Version: 7.8.7959
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT, MIP (pywraplp with CBC)

**What operating system (Linux, Windows, ...) and version?**
Windows

**What did you do?**
I have formulated a shift scheduling problem (similar to this work https://link.springer.com/article/10.1007/s10729-011-9155-x) with both CP-SAT and pywraplp with CBC solver with all binary variables.

**What did you expect to see**, **What did you see instead?**
I assumed even if the two solvers are targeting different goals (CP is focused on finding feasible solution) and (pywraplp on finding optimal solution) they will eventually find at least similar solutions after some time limit, given a small size of the problem. However, CP-SAT can easily find better solution while MIP solver even with larger solution time limit cannot find a good solution with reasonable relative gap. I couldn't find any information in the documentation about if there has been any comparison between solvers on similar problems, is there any reason that MIP solver might not be as successful on an integer program compared to CP-SAT? 
The reason I am interested to make MIP solver work for my problem is 1)  CP-SAT requires all coefficients and data to be integer 2) MIP has wrapper around different solvers like Gurobi and CPLEX that I might want to use in future.

**Comment by lperron** [comment]
This is not an issue. Please use the mailing list.

**Comment by amobash2** [comment]
Thanks for replying, but I have already sent request a day ago to join the google group so I can ask my question, but my request has not yet been accepted. How else can I ask this question with more detail maybe? The only comparison available in documentation between the two solvers are for a very simple and small problem and it is somehow strange that MIP with CBC is returning such underperforming results.

**Comment by amobash2** [comment]
Aah I think the problem is related to CBC solver, I switched to SAT_INTEGER_PROGRAMMING solver (which should use similar methodology as CP-SAT, I am hoping I am understanding correctly) and I am getting similar results, and not under performing compared to CP_SAT model. I am gonna try more solver and see if other solvers (including commercial ones) are underperforming or not. Thanks for adding me to the google group.
