### ISSUE TITLE
Binaries using gflags::ParseCommandLineFlags are not working on MacOS

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#2171]
```sh
[0]─[~/work/master]
[^v^]─corentinl@corentinl-macbookair %make test_fz
bin/fz examples/flatzinc/golomb.fzn
ERROR: something wrong with flag 'flagfile' in file '/Users/corentinl/work/master/dependencies/sources/gflags-2.2.2/src/gflags.cc'.  One possibility: file '/Users/corentinl/work/master/dependencies/sources/gflags-2.2.2/src/gflags.cc' is being linked both statically and dynamically into this executable.
make: *** [makefiles/Makefile.cpp.mk:483: rfz_golomb] Error 1
[2]─[~/work/master]
[>_<]─corentinl@corentinl-macbookair %./bin/fz
ERROR: something wrong with flag 'flagfile' in file '/Users/corentinl/work/master/dependencies/sources/gflags-2.2.2/src/gflags.cc'.  One possibility: file '/Users/corentinl/work/master/dependencies/sources/gflags-2.2.2/src/gflags.cc' is being linked both statically and dynamically into this executable.
[1]─[~/work/master]
[>_<]─corentinl@corentinl-macbookair %
```

Currently investigating and doing some tests...
My guess:
* `ortools.dylib` AND `libfz.dylib` are linked against `libgflags.a` so It may be possible that `flagfile` is included twice in `bin/fz` binary thus the bug.
* `libfz` already depends of `libortools` -> not sure fz should depend on libortools at link time...

**Comment by lperron** [comment]
It happens with non flatzinc.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
note: it's working on linux (except the fail of #2070) at least we don't have this 'flagfile' issue

**Comment by Mizux** [comment]
On linux we have:
```sh
[0]─[~/work/master]
[^v^]─mizux@nuc10i7 %nm bin/fz | grep fileflag
[1]─[~/work/master]
[>_<]─mizux@nuc10i7 %nm lib/libfz.so | grep flagfile     
[1]─[~/work/master]
[>_<]─mizux@nuc10i7 %nm lib/libortools.so | grep flagfile
0000000001f5e380 B _ZN3fLS14FLAGS_flagfileB5cxx11E
0000000001f5e410 b _ZN3fLSL10d_flagfileE
0000000001f5e408 b _ZN3fLSL10o_flagfileE
0000000001f5e3c0 b _ZN3fLSL10s_flagfileE
0000000001f5e400 b _ZN3fLSL16FLAGS_noflagfileE
```
so `flagfile` is only defined in `libortools.so`

**Comment by Mizux** [comment]
while on macOS we have:
```sh
0]─[~/work/master]
[^v^]─corentinl@corentinl-macbookair %nm bin/fz | grep flagfile
000000010001d5f8 S __ZN3fLS14FLAGS_flagfileE
000000010001d758 b __ZN3fLSL10d_flagfileE
000000010001d750 b __ZN3fLSL10o_flagfileE
000000010001d720 b __ZN3fLSL10s_flagfileE
000000010001d710 b __ZN3fLSL16FLAGS_noflagfileE
[0]─[~/work/master]
[^v^]─corentinl@corentinl-macbookair %nm lib/libfz.dylib | grep flagfile 
0000000000086cc0 S __ZN3fLS14FLAGS_flagfileE
0000000000086a48 b __ZN3fLSL10d_flagfileE
0000000000086a40 b __ZN3fLSL10o_flagfileE
0000000000086a10 b __ZN3fLSL10s_flagfileE
0000000000086a00 b __ZN3fLSL16FLAGS_noflagfileE
[0]─[~/work/master]
[^v^]─corentinl@corentinl-macbookair %nm lib/libortools.dylib | grep flagfile 
00000000020dd170 S __ZN3fLS14FLAGS_flagfileE
00000000020d6598 b __ZN3fLSL10d_flagfileE
00000000020d6590 b __ZN3fLSL10o_flagfileE
00000000020d6560 b __ZN3fLSL10s_flagfileE
00000000020d6550 b __ZN3fLSL16FLAGS_noflagfileE
```

**Comment by Mizux** [comment]
Most examples/cpp/*.cc using `gflags::ParseCommandLineFlags()` are also impacted...

**Comment by Mizux** [comment]
using cmake build:
```sh
[0]─[~/work/master]
[^v^]─corentinl@corentinl-macbookair %nm build/lib/libortools.dylib | grep flagfile
0000000001451400 S __ZN3fLS14FLAGS_flagfileE
0000000001455050 b __ZN3fLSL10d_flagfileE
0000000001455020 b __ZN3fLSL10s_flagfileE
0000000001455010 b __ZN3fLSL16FLAGS_noflagfileE
[0]─[~/work/master]
[^v^]─corentinl@corentinl-macbookair %nm build/bin/dobble_ls | grep flagfile 
000000010001c608 S __ZN3fLS14FLAGS_flagfileE
000000010001c470 b __ZN3fLSL10d_flagfileE
000000010001c440 b __ZN3fLSL10s_flagfileE
000000010001c430 b __ZN3fLSL16FLAGS_noflagfileE
```

using make:
```sh
[0]─[~/work/master]
[^v^]─corentinl@corentinl-macbookair %nm lib/libortools.dylib| grep flagfile
00000000020dd0b0 S __ZN3fLS14FLAGS_flagfileE
00000000020d6598 b __ZN3fLSL10d_flagfileE
00000000020d6590 b __ZN3fLSL10o_flagfileE
00000000020d6560 b __ZN3fLSL10s_flagfileE
00000000020d6550 b __ZN3fLSL16FLAGS_noflagfileE
[0]─[~/work/master]
[^v^]─corentinl@corentinl-macbookair %nm bin/dobble_ls | grep flagfile      
0000000100024c50 S __ZN3fLS14FLAGS_flagfileE
0000000100024aa8 b __ZN3fLSL10d_flagfileE
0000000100024aa0 b __ZN3fLSL10o_flagfileE
0000000100024a70 b __ZN3fLSL10s_flagfileE
0000000100024a60 b __ZN3fLSL16FLAGS_noflagfileE
[0]─[~/work/master]
[^v^]─corentinl@corentinl-macbookair %c++filt __ZN3fLSL10o_flagfileE
fLS::o_flagfile
```

note: cmake don't have the `fLS::o_flagfile`...

**Comment by Mizux** [comment]
we must build gflags in Release (which is not the case in the Make based build system) but the case for ortools so I suspect we got two flagfile symbols + the extra symbols `__ZN3fLSL10o_flagfileE` which is not generated in release mode (i;e. `-O3 -DNDEBUG`)
i.e. add a `-DCMAKE_BUILD_TYPE=Release`

On my way to create a clean commit (ed we should do it for all our dependencies too) !
Please, wait and see.

**Comment by Dekker1** [comment]
I'm sorry to resurrect this old issue, but I'm running into this exact problem. I'm trying to setup a Homebrew formula which runs `make third_party` and then `make cc fz`. However, it runs exactly into this issue where I get the error posted in the initial description and when I run `nm` on the `libgflags.a` it outputs:
```
dekker1@Sodium lib % nm libgflags.a | grep flagfile
000000000000b780 S __ZN3fLS14FLAGS_flagfileE
000000000000b518 b __ZN3fLSL10d_flagfileE
000000000000b510 b __ZN3fLSL10o_flagfileE
000000000000b4e0 b __ZN3fLSL10s_flagfileE
000000000000b4d0 b __ZN3fLSL16FLAGS_noflagfileE
```

This seems to be the exact same problem, but when I look at the build log, it does add `-DCMAKE_BUILD_TYPE=Release` to the CMake command. Homebrew does setup a clean (and adjusted) build environment that is used during the build steps, but I do not see anything out of the ordinary, so I'm wondering if anyone would have any indication of what environmental variables would be able to induce this behaviour.

Alternatively I'd be happy (maybe even happier) to use the CMake build, but I don't think that contains the FlatZinc solver yet.

**Comment by lperron** [comment]
or-tools c++ is already on homebrew (non flatzinc).
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 19 nov. 2020 à 07:45, Jip J. Dekker <notifications@github.com> a
écrit :

**Comment by Dekker1** [comment]
Hi Laurent,

I've seen that the C++ library was available in Homebrew. That one seems to use CMake to build OR Tools and doesn't seem to have the problem. I'm currently working on the installation of FlatZinc solvers using Homebrew (either being contained in their own Homebrew Tap or added as extensions to the official Formulae). Therefore, I'm trying to create a formula for OR Tools using make as that seems to be the way to create the FlatZinc binary and getting stuck on this problem.

**Comment by lperron** [comment]
are you building on master or on 8.0 ?

Gflags and glog are removed on master.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 19 nov. 2020 à 08:00, Jip J. Dekker <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
Furthermore, the cmake flatzinc part should be quite straightforward.
Just compile all files except parser_main.cc and fz.cc in a library, and
compile fz.cc as a binary.

There is nothing fancy there.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
I'll try to add flatzinc build to cmake today
please wait and see (and follow #2237)

**Comment by ctriley** [comment]
Sorry to resurrect a dead issue, but I think I'm having a related problem when trying to add or-tools to my c++ project.  
This is what my cmake looks like.
```cmake
    include(FetchContent)
    FetchContent_Declare(
            ortools
            GIT_REPOSITORY https://github.com/google/or-tools.git
            GIT_TAG        stable
    )

    set(BUILD_DEPS ON)
    set(BUILD_SAMPLES OFF)
    set(BUILD_EXAMPLES OFF)
    FetchContent_MakeAvailable(ortools)
    set(requiredlibs ${requiredlibs} ortools::ortools)
```
When I try to build in debug, I get this issue at runtime:

ERROR: Something is wrong with flag 'flagfile' in file 'Users/connorriley/dial-a-ride-dispatcher/cmake-build-debug/_deps/absl-src/absl/flags/parse.cc'. One possibility: file 'Users/connorriley/dial-a-ride-dispatcher/cmake-build-debug/_deps/absl-src/absl/flags/parse.cc' is being linked both statically and dynamically into this executable. e.g. some files listed as srcs to a test and also listed as srcs of some shared lib deps of the same test.

I'm on an apple silicon mac.
