### ISSUE TITLE
GLOP:  No Solver Output

### ISSUE THREAD

**Issue by Diddlik** [google/or-tools#2172]
**What version of OR-tools and what language are you using?**
Version: master
Language: C++

**Which solver are you using (GLOP)**

**What operating system (Windows 10)**

On implementation, multitreading does not seem to work in the binary version because OPENMP was not active when compiling the library for release.
Furthermore SolverOutput does not work either. Nothing comes back.

**Comment by Mizux** [comment]
do you mean this lines ?
https://github.com/google/or-tools/blob/a0a56698ba8fd07b7f84aee4fc45d891a8cd9828/ortools/glop/reduced_costs.cc#L366-L408

**Comment by lperron** [comment]
We never compile with open mp. 
We should just remove the code.

**Comment by lperron** [comment]
I renamed the issue.
What do you mean no solver output ? Can you send us a code ?

**Comment by Diddlik** [comment]
I think the problem was, that verbose flag was not seted propertly. Now I get get some output.
