### ISSUE TITLE
Memory leak in .NET Core 3.1 on Linux

### ISSUE THREAD

**Issue by adomass** [google/or-tools#2173]
Version: 7.8.7959.
Language: C#

**Google.OrTools.LinearSolver CBC_MIXED_INTEGER_PROGRAMMING**

**Linux on AWS Lambda running dotnetcore3.1**

1. Run solver on docker (linux). 
2. Dispose solver after finished
3. Check memory increasing

After several runs you run out of memory and lambda vm crashes:
(invoke@invoke.c:331 errno: Address family not supported by protocol) run_dotnet(dotnet_path, &args) failed

**Comment by adomass** [comment]
In this commit i see some changes done regarding this issue https://github.com/google/or-tools/commit/f0f675debd3ea7c5632ad3fdab219d01fa7ee23f

However I don't see  who is destructing memory taken by solver when its being disposed?

**Comment by Mizux** [comment]
My 2 cents,

* `operations_research_linear_solverPINVOKE.new_Solver` is just a SWIG wrapper of the C++ class constructor `MPSolver::MPSolver() `
* `operations_research_linear_solverPINVOKE.Solver_CreateSolver` is the SWIG wrapper of the "Factory" method [`CreateSolver()`](https://github.com/google/or-tools/blob/fa84bc05e72641dddfbb98164d81b8bc9bef6ea5/ortools/linear_solver/linear_solver.h#L254)

**Comment by adomass** [comment]
We have switched our solver to   
Solver = Solver.CreateSolver("MipSolver", Solver.OptimizationProblemType.SAT_INTEGER_PROGRAMMING.ToString());

And it works quite ok for us.
