### ISSUE TITLE
MODEL_INVALID, The relative error during double -> int64 conversion is too high

### ISSUE THREAD

**Issue by huig-** [google/or-tools#2174]
I am working with C# with the Solver SAT_INTEGER_PROGRAMMING and version 7.8.7959 and I am encountering the following error in the logs:

W0930  lp_utils.cc:685] The relative error during double -> int64 conversion is too high! error:6.4325e+15 check_tolerance:0.0001
I0930  sat_proto_solver.cc:129] CpSolverResponse:
status: MODEL_INVALID

From what I have seen in the source code, it could be from scaling errors that come from big constants overflow, but all variables in the model have been truncated to long or int values. Bounds for variables are mainly [0,1], [0,100] and [-1e20, +1e20]. I am running the model with mip_max_bound=1e12.

I have attached the model in MPS format.

[pg.zip](https://github.com/google/or-tools/files/5305012/pg.zip)

**Comment by huig-** [comment]
I have changed to CP-SAT instead of using the LinearSolver with SAT_INTEGER_PROGRAMMING and after running CpModel.Validate() I found out that long.MaxValue or long.MinValue as bounds were not appropiate, although for other input data the same bounds were not giving any trouble with SAT_INTEGER_PROGRAMMING.

I do not understand why it works with some input data and not with another (as said, with CP-SAT it is working no matter which input data), where with some input data it reached optimal or feasible solutions and with the data attached it returned MODEL_INVALID. I guess the issue it can be closed

**Comment by Mizux** [comment]
Thanks for the feedback ! I'll close the issue...
