### ISSUE TITLE
or-tools how solver is choosing vehicles

### ISSUE THREAD

**Issue by tomassimonavicius** [google/or-tools#2179]
Situation that we have(using VRP): We are using only first solution strategy without local search metaheuristics. Also we are using span cost coefficient for each vehicle and also fixed cost. Also we have pallet, weight and volume capacities in place.

We have 80 vehicles and 374 visits. If we are making all vehicles the same (same span cost, same fixed cost, same capacities etc.) then we are getting a best solution with 54 routes and a total solution price is 7917. Solver is producing 99 solutions. If we are changing a single vehicle span cost (and by a tiny margin) then the solution becomes significantly worse than before with 54 routes and a total solution price of 8149. Solver is producing 390 solutions (significantly more).

Why solver is creating more solutions, but giving worse outcome?

And the next situation. All data is the same and all solution making configuration are the same.

If we are changing pallet capacity of two vehicles from 36 pallets to 19 pallets and making them slightly cheaper (fixed price 49 compared to 50 and span cost 0.34 compared to 0.35) then the solver is using those two vehicles. It seems logical at first, but it’s local optimum not a global one, because total solution price is worse than the solution that would have used pricier vehicles with bigger pallet capacity.

Can you explain how solver is choosing vehicles for the solution? Is it reaching for local optimum(best price for the route), or global one(best price for total solution)?

**Comment by lperron** [comment]
This is not an issue. Please ask the question on the mailing list.
