### ISSUE TITLE
Ortools crashes ucrtbase.dll exception code 0xc0000409

### ISSUE THREAD

**Issue by huig-** [google/or-tools#2180]
I am running CP-SAT in windows 10 with C#, ortools v7.8.7959 and after a couple of hours of the model running (and finding several solutions), the application crashes without leaving any trace. Looking in the event registry I find that apparently ucrtbase.dll crashed with exception code 0xc0000409 which seems to be related to STATUS_STACK_BUFFER_OVERRUN.

I have seen a couple of other issues in github as well as discussions on the google groups site (https://groups.google.com/g/or-tools-discuss/c/WiIYPthzZn0/m/1Jed0hnaBQAJ) but no solution proposed other than the GC.KeepAlive(), which I don't think makes sense in this context.

**Edit**
Could this be maybe be associated with the process needing more memory than specified in max_memory_in_mb?

**Comment by lperron** [comment]
I do not think the solver checks the `max_memory_in_mb` parameter.
Most likely, you consumed all memory.

**Comment by huig-** [comment]
Will this be solved in the next release? Is there anyway I can help?

**Comment by lperron** [comment]
It seems you are running out of memory.
So there is little we can do.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 5 oct. 2020 à 09:36, Ignacio Gago <notifications@github.com> a
écrit :

**Comment by huig-** [comment]
Should I give a try at `reduce_memory_usage_in_interleave_mode = true`?

**Comment by lperron** [comment]
I do not think you are using interleave mode.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 5 oct. 2020 à 13:16, Ignacio Gago <notifications@github.com> a
écrit :
