### ISSUE TITLE
MiniZinc: evaluation error: mismatch in array dimensions (probably due to "{}" instead of "0..0" syntax?)

### ISSUE THREAD

**Issue by agentydragon** [google/or-tools#2181]
**What version of OR-tools and what language are you using?**
Version: commit 45770b833997f827d322e929b1ed4781c4e60d44
Language: Minizinc

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
I'm using the OR-Tools Minizinc integration.

**What operating system (Linux, Windows, ...) and version?**
Linux, Pop!_OS 20.04

**What did you do?**
I have a repository that does SAT solving to plan meals (https://gitlab.com/dustin-space/meal-planner). My Python code builds a Minizinc file, which I then solve with the `minizinc` frontend.

With my model, the Gecode Minizinc backend works, but when I run Minizinc with the OR-Tools backend, on some instances of my model I get:

```
solution received from solver:3.28-30:
MiniZinc: evaluation error: mismatch in array dimensions
```

**Data for reproduction**

The model is: https://gitlab.com/dustin-space/meal-scheduler/-/blob/59ae08215a2f6c95a8a909e71cb489758e862623/plan/minizinc/simple-planning.mzn

The instance .dzn is:
```
timesteps = 1;
max_of_recipes_constraints = 0;
Recipes = { Recipe0 };
Ingredients = { Iegg };
Products = { Product0 };
recipe_input_per_portion = [|1 |];
product_contents = [|1 |];
initial_stock = array1d(Ingredients, [0]);
portions_cooked = array1d(TIMESTEP, [2]);
max_obtain_externally = 100;
max_of_recipes_count = array1d(MAX_OF_RECIPES_ITEMS, []);
max_of_recipes_recipes = array1d(MAX_OF_RECIPES_ITEMS, []);
type_has_subtype = array2d(Ingredients, Ingredients, [false]);
banned_recipes = {}
```

The Minizinc frontend compiles it to this Flatzinc:
```
$ cat /tmp/minizinc-planner-52583afd-d787-4588-840c-6f09d201e361/intermediate.fzn
predicate all_different_int(array [int] of var int: x);
var int: X_INTRODUCED_1_:: is_defined_var;
var 1..1: X_INTRODUCED_3_;
var 2..2: X_INTRODUCED_7_;
var 0..0: X_INTRODUCED_8_;
var int: total_products_bought:: output_var;
array [1..2] of var int: stock:: output_array([0..1,1..1]) = [0,X_INTRODUCED_1_];
array [1..1] of var int: recipe_cooked:: output_array([0..0]) = [1];
array [1..1] of var int: recipe_cooked_idx:: output_array([0..0]) = [1];
array [1..1] of var int: products_bought:: output_array([0..0,1..1]) = [total_products_bought];
array [1..1] of var int: products_bought_overall:: output_array([1..1]) = [total_products_bought];
array [1..1] of var int: used_directly:: output_array([0..0,1..1]) = [2];
array [1..1] of var int: as_used_by_recipe:: output_array([0..0,1..1]) = [2];
array [1..1] of var int: obtain_externally:: output_array([1..1]) = [0];
array [1..1] of var int: total_ingredient_use:: output_array([1..1]) = [2];
array [1..1] of var bool: recipe_ever_cooked:: output_array([1..1]) = [true];
array [1..1] of var int: generalization_to_from:: output_array([0..0,1..1,1..1]) = [0];
constraint int_lin_eq([1,-1],[X_INTRODUCED_1_,total_products_bought],-2):: defines_var(X_INTRODUCED_1_);
constraint all_different_int([1]);
constraint int_le(0,X_INTRODUCED_1_);
constraint int_le(0,total_products_bought);
constraint int_le(0,total_products_bought);
solve  minimize total_products_bought;
```

On that Flatzinc, the Gecode solver produces this output:
```
$ ./fzn-gecode /tmp/minizinc-planner-52583afd-d787-4588-840c-6f09d201e361/intermediate.fzn
as_used_by_recipe = array2d(0..0, 1..1, [2]);
generalization_to_from = array3d(0..0, 1..1, 1..1, [0]);
obtain_externally = array1d(1..1, [0]);
products_bought = array2d(0..0, 1..1, [2]);
products_bought_overall = array1d(1..1, [2]);
recipe_cooked = array1d(0..0, [1]);
recipe_cooked_idx = array1d(0..0, [1]);
recipe_ever_cooked = array1d(1..1, [true]);
stock = array2d(0..1, 1..1, [0, 0]);
total_ingredient_use = array1d(1..1, [2]);
total_products_bought = 2;
used_directly = array2d(0..0, 1..1, [2]);
----------
==========
```

Whereas the OR-Tools produces this output:

```
$ bazel run //ortools/flatzinc:fz -- /tmp/minizinc-planner-52583afd-d787-4588-840c-6f09d201e361/intermediate.fzn
...
total_products_bought = 2;
stock = array2d(0..1, 1..1, [0, 0]);
recipe_cooked = array1d({},[1]);
recipe_cooked_idx = array1d({},[1]);
products_bought = array2d({},1..1, [2]);
products_bought_overall = array1d(1..1, [2]);
used_directly = array2d({},1..1, [2]);
as_used_by_recipe = array2d({},1..1, [2]);
obtain_externally = array1d(1..1, [0]);
total_ingredient_use = array1d(1..1, [2]);
recipe_ever_cooked = array1d(1..1, [true]);
generalization_to_from = array3d({},1..1, 1..1, [0]);

----------
==========
```

The only difference in those solutions is that Gecode's Flatzinc solver keeps the `0..0` indices in arrays with a single element in some dimension, but OR-Tools's Flatzinc solver represents those with `{}`. I find that a bit suspicious - `0..0` is AFAIK an array with a single element `0`, but `{}` is an empty set. Diff:

```
$ diff <(cat sol-gecode| sort) <(cat sol-ortools| sort)                                                                                                                                                11:32:35
0a1
> 
3,4c4,5
< as_used_by_recipe = array2d(0..0, 1..1, [2]);
< generalization_to_from = array3d(0..0, 1..1, 1..1, [0]);
---
> as_used_by_recipe = array2d({},1..1, [2]);
> generalization_to_from = array3d({},1..1, 1..1, [0]);
6c7
< products_bought = array2d(0..0, 1..1, [2]);
---
> products_bought = array2d({},1..1, [2]);
8,9c9,10
< recipe_cooked = array1d(0..0, [1]);
< recipe_cooked_idx = array1d(0..0, [1]);
---
> recipe_cooked = array1d({},[1]);
> recipe_cooked_idx = array1d({},[1]);
14c15
< used_directly = array2d(0..0, 1..1, [2]);
---
> used_directly = array2d({},1..1, [2]);
```

The location in the error message from Minizinc (`solution received from solver:3.28-30`) is pointing at the `[1]` part of this line in OR-Tools's solution:
<pre>
...
recipe_cooked = array1d({},<b>[1]</b>);
...
</pre>

So this makes me believe Minizinc is not expecting an `array1d({}, ...)` to have any elements.

**What did you expect to see**

I would expect Minizinc with the OR-Tools backend to successfully solve the attached problem instance.

**What did you see instead?**

Minizinc seems to fail to parse the solution returned by OR-Tools Flatzinc solver, apparently due to a mistake in array dimension declaration.

**Anything else we should know about your project / environment**

- This also reproduces on the `stable` branch of or-tools.
- I built Minizinc from source at commit `44bdb9bfc7e51e1206edd7d2f37a048d40197e5b`
- My project uses Bazel and Minizinc and Gecode are pulled in via [rules_foreign_cc](https://github.com/bazelbuild/rules_foreign_cc)

**Comment by agentydragon** [comment]
BTW: I have not tried minimizing the test case, but I expect this issue should be visible in any problem that has an array which has dimension [1].

**Comment by lperron** [comment]
I fixed the issue.

Thanks for the report.

Please note that with the next version of or-tools. based on the latest
minizinc, you will need to regenerate the fzn files.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by agentydragon** [comment]
That was fast :)

Thanks!
