### ISSUE TITLE
CP-SAT takes 24000 secs in v7.8 but 200 secs in v.7.5

### ISSUE THREAD

**Issue by frasernutricia** [google/or-tools#2182]
Dear or-tools team,
this is the same issue as previous closed ticket #2111 - identical type of problem but now with slightly different coefficients in the constraints. I have attached the protobuf and log files for my CP-SAT problem for v.7.5 and v.7.8. In v7.5 this takes ~200 secs whereas in v7.8 it is ~24000 secs, unfortunately the difference is big enough to make this infeasible (as this is smaller version of a bigger more complex problem). If it were possible to be able to specify options in v7.8 to enable whatever behaviour solved the problem quickly in v7.5 that would be ideal. thanks a lot! Fraser.  

[protoDebug_v78.txt](https://github.com/google/or-tools/files/5321560/protoDebug_v78.txt)
[logv75_4core.txt](https://github.com/google/or-tools/files/5321562/logv75_4core.txt)
[logv78_4core.txt](https://github.com/google/or-tools/files/5321564/logv78_4core.txt)

**Comment by lperron** [comment]
I have no solution at the moment.

**Comment by lperron** [comment]
Actually, I ran 3 times on master with 8 threads

status: OPTIMAL
objective: NA
best_bound: NA
booleans: 3184
conflicts: 1571
branches: 28490
propagations: 363156
integer_propagations: 2862989
walltime: 119.839
usertime: 953.518
deterministic_time: 800.815
primal_integral: 0
