### ISSUE TITLE
False infeasibility alarm on GLOP but CBC is working

### ISSUE THREAD

**Issue by berkorbay** [google/or-tools#2183]
**What version of OR-tools and what language are you using?**
Version: 7.8.7959
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
GLOP / CBC

**What operating system (Linux, Windows, ...) and version?**
MacOS Catalina (also High Sierra)

Hi, 

I encountered a peculiar behavior by GLOP which alerts as "no solution found". The exact log is a bunch of `E1005 11:49:50.196224 118062528 linear_solver.cc:1695] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_NOT_SOLVED` messages. 

Though when I change it to the MIP solver CBC (pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING), CBC can find a solution in almost no time. 

I had my suspicions when I change the model input parameters (e.g. some capacities) and the model started to provide results. I had confirmation when I added dummy continuous variables with no effect on anything else (i.e. objective function) or are not constrained by anything except non-negativity.

For instance, suppose I have a constraint `x => 5` and x is a decision variable and it is included in objective function and other constraints. If I modify the constraint to `x + y => 5` and define y as another nonnegative decision variable GLOP throws an error as "No solution exists". If I also add `y = 0` constraint, I get a proper result. Normally, the solver should be able to find `y = 0` itself because it is allowed in the model.

Unfortunately I cannot provide an example because both the model and the input data is a bit large and propriety. I also couldn't produce a working minimal reproducible example with a dummy input and small model. So, I am just reporting it. Perhaps it is because of GLOP's methodology to find initial solutions, perhaps some other reason.

**Comment by lperron** [comment]
Please attach a code or a model.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
no response -> closing
