### ISSUE TITLE
Is there any way to get shadow price of netflow problem ?

### ISSUE THREAD

**Issue by zhilee2019** [google/or-tools#2185]
**What language and solver does this apply to?**
All, Python, Java, C#, C++ / CP-SAT, Routing, Linear Solver

**Describe the problem you are trying to solve.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lperron** [comment]
This is not an issue. Please use the mailing list.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
