### ISSUE TITLE
Protobuf and .NETFramework 4.0

### ISSUE THREAD

**Issue by KapecK** [google/or-tools#219]
After some latest commits about Protobuf I get warning:
The primary reference "Google.Protobuf" could not be resolved because it was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0"

Can we change Protobuf to work with .NETFramework 4.0?

**Comment by dlahlou** [comment]
Hello Kapeck,
Or-tools was using beta versions of Protobuf, which was hard to maintain. Now we're using Protobuf 3.0.0 which, as mentionned in the [release notes](https://github.com/google/protobuf/releases), targets .NET 4.5.
We're sorry about this compatibility problem.
Regards
