### ISSUE TITLE
CMake build fails in VS and Clion

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#2191]
**What version of OR-tools and what language are you using?**
Version: master from 7.10.2020
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
Build or-tools in VS2019 or Clion IDE, both use cmake.

**What did you expect to see**
Succesful build, it works when I move back in history to commits on Saturday 3.10.2020

**What did you see instead?**
====================[ Build | all | Debug ]=====================================
"C:\Program Files\JetBrains\CLion 2020.2.3\bin\cmake\win\bin\cmake.exe" --build C:\Users\honza\CLionProjects\or-tools\cmake-build-debug --target all
-- ortools version: 8.0.8259
-- Build C++ library: ON
-- Build Python: OFF
-- Build Java: OFF
-- Build .Net: OFF
-- Build samples: ON
-- Build C++ samples: ON
-- Build Python samples: OFF
-- Build Java samples: OFF
-- Build .Net samples: OFF
-- Build examples: ON
-- Build C++ examples: ON
-- Build Python examples: OFF
-- Build Java examples: OFF
-- Build .Net examples: OFF
-- Build all dependencies: ON
-- Build ZLIB: ON
-- Build abseil-cpp: ON
-- Build gflags: ON
-- Build glog: ON
-- Build protobuf: ON
-- SCIP support: ON
-- Build SCIP: ON
-- COIN-OR support: ON
-- Build CoinUtils: ON
-- Build Osi: ON
-- Build Clp: ON
-- Build Cgl: ON
-- Build Cbc: ON
-- CPLEX support: OFF
-- XPRESS support: OFF
-- Fetching ZLIB
--   Populating zlib
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/honza/CLionProjects/or-tools/cmake-build-debug/_deps/zlib-subbuild
[ 11%] Skipping update step for 'zlib-populate'
[ 22%] No configure step for 'zlib-populate'
[ 33%] No build step for 'zlib-populate'
[ 44%] No install step for 'zlib-populate'
[ 55%] No test step for 'zlib-populate'
[ 66%] Completed 'zlib-populate'
[100%] Built target zlib-populate
-- Fetching ZLIB - fetched
-- Fetching Abseil-cpp
--   Populating absl
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/honza/CLionProjects/or-tools/cmake-build-debug/_deps/absl-subbuild
[ 11%] Skipping update step for 'absl-populate'
[ 22%] Performing patch step for 'absl-populate'
error: patch failed: CMakeLists.txt:41
error: CMakeLists.txt: patch does not apply
NMAKE : fatal error U1077: '"C:\Program Files\Git\cmd\git.EXE"' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
CMake Error at C:/Program Files/JetBrains/CLion 2020.2.3/bin/cmake/win/share/cmake-3.17/Modules/FetchContent.cmake:912 (message):
  Build step for absl failed: 2
Call Stack (most recent call first):
  C:/Program Files/JetBrains/CLion 2020.2.3/bin/cmake/win/share/cmake-3.17/Modules/FetchContent.cmake:1003 (__FetchContent_directPopulate)
  C:/Program Files/JetBrains/CLion 2020.2.3/bin/cmake/win/share/cmake-3.17/Modules/FetchContent.cmake:1044 (FetchContent_Populate)
  cmake/dependencies/CMakeLists.txt:71 (FetchContent_MakeAvailable)

-- Configuring incomplete, errors occurred!
See also "C:/Users/honza/CLionProjects/or-tools/cmake-build-debug/CMakeFiles/CMakeOutput.log".
See also "C:/Users/honza/CLionProjects/or-tools/cmake-build-debug/CMakeFiles/CMakeError.log".
NMAKE : fatal error U1077: '"C:\Program Files\JetBrains\CLion 2020.2.3\bin\cmake\win\bin\cmake.exe"' : return code '0x1'
Stop.

**Comment by Mizux** [comment]
May I ask which version of git and cmake did you use ?
seems related to this line:
https://github.com/google/or-tools/blob/8d46746ca058a934ff9e8d63c28fda9b635f65fb/cmake/dependencies/CMakeLists.txt#L66-L70

**Comment by gregy4** [comment]
I use git version 2.21.0.windows.1, clion uses cmake 3.17.3. otherwise in my system is installed cmake version 3.16.5.
VS uses cmake version 3.17.20032601-MSVC_2.

**Comment by Mizux** [comment]
ok according to your trace, cmake try to reconfigure during a build and then try to reapply the git patch which will obviously fail.

to avoid this, I've set the flag
https://github.com/google/or-tools/blob/8259943b1d67b29fd3559b625fe0b854e6d8d290/cmake/dependencies/CMakeLists.txt#L38
BUT until 3.18 while it prevent `FetchContent()` to re-download third party repo(s) it won't prevent CMake to run the `PATCH_COMMAND` -_-
IIRC it is now fixed for CMake >= ~3.18.1

So workaround:
* try to upgrade to CMake 3.18.3 **OR**
* remove your build directory and reconfigure.
