### ISSUE TITLE
Debug build seg fault when building with conan recipe

### ISSUE THREAD

**Issue by philsuess** [google/or-tools#2197]
**What version of OR-tools and what language are you using?**
Version: v8.0
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
GLOP

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**

1. Build ortools in debug version using vc16 (Visual Studio 2019) with MDd flag using conan:
    - install conan: `pip install conan`
    - checkout: https://github.com/philsuess/conan-or-tools
    - run either one of
        - `conan create . user/testing -s compiler="Visual Studio" -s compiler.version=16`
        - `conan create . user/testing -s compiler="Visual Studio" -s compiler.version=16 -s build_type=Debug -s compiler.runtime="MDd"`
2. This will pull or-tools, build it, build the test_package and run it
3. `test_or_tools.cpp` will fail with seg fault because `mut_obj` is NULL in:
```cpp
  operations_research::MPSolver solver("simple_lp_program", problemType);

  // Create the variables x and y.
  auto* const x = solver.MakeNumVar(0.0, 1, "x");
  auto* const y = solver.MakeNumVar(0.0, 2, "y");
  
  operations_research::MPObjective* const mut_obj = solver.MutableObjective();
  std::cout << "objective coefficient of x: " << mut_obj->GetCoefficient(x) << " (should be 0)" << std::endl;
```

![image](https://user-images.githubusercontent.com/17199306/96128352-853bd780-0ef5-11eb-8f68-9f79ff021ba2.png)

![image](https://user-images.githubusercontent.com/17199306/96139543-40b53980-0eff-11eb-8a48-c466e34c399e.png)

**What did you expect to see**
A mutable obective object to manipulate

**What did you see instead?**
seg fault (see screenshots)

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
- using conan version 1.30.1

**Comment by Mizux** [comment]
did you use abseil 20202903 ?
https://github.com/google/or-tools/blob/8d19323faf51f2f004e4de6c1b32a74001fbc7c1/cmake/dependencies/CMakeLists.txt#L69-L70

**Comment by Mizux** [comment]
maybe we should add this requirement here too:
https://github.com/google/or-tools/blob/8d19323faf51f2f004e4de6c1b32a74001fbc7c1/cmake/cpp.cmake#L23-L25

note: currently we don't have ci jobs to test the build of ortools with installed dependencies (ed on my todo list)

**Comment by philsuess** [comment]
> did you use abseil `20200923` ?
> https://github.com/google/or-tools/blob/8d19323faf51f2f004e4de6c1b32a74001fbc7c1/cmake/dependencies/CMakeLists.txt#L69-L70

I am not changing or injecting anything (allthough that is on my todo list). I run with `cmake.definitions['BUILD_DEPS'] = "ON"` (see https://github.com/philsuess/conan-or-tools).

**Comment by philsuess** [comment]
My bad. I did not enforce c++17 in the test_package project. I'm closing this.
