### ISSUE TITLE
Crash during Solve

### ISSUE THREAD

**Issue by anghy23** [google/or-tools#2202]
**What version of OR-tools and what language are you using?**
Version: 8.0
Language: C#

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10

With the attached model I get the following error during solve
[batch.zip](https://github.com/google/or-tools/files/5414770/batch.zip)

Check failed: SolutionIsFeasible( *shared_->model_proto, std::vector<int64>(local_response.solution().begin(), local_response.solution().end())) rens_lns_default_lp_incomplete(d=0.81 s=23 t=0.10 p=1.00)
** Check failure stack trace: **
    @   00007FFD7D378DDB  SWIGRegisterStringCallback_operations_research_util
    @   00007FFD7D377339  SWIGRegisterStringCallback_operations_research_util
    @   00007FFD7D4877B9  SWIGRegisterStringCallback_operations_research_util
    @   00007FFD7DA05869  SWIGRegisterStringCallback_operations_research_util
    @   00007FFD7DE0FB44  SCIPlpiWriteState
    @   00007FFD7DE0E96F  SCIPlpiWriteState
    @   00007FFE07D50E72  _beginthreadex
    @   00007FFE08F87BD4  BaseThreadInitThunk
    @   00007FFE0AAECED1  RtlUserThreadStart

**Comment by lperron** [comment]
I believe it is fixed on master.

The problem solved to optimality in 2 minutes on my machine (using 16 workers).

Thanks.
