### ISSUE TITLE
PrecedencePropagator optimization

### ISSUE THREAD

**Issue by prissky** [google/or-tools#2203]
**What version of OR-tools and what language are you using?**
Version: 8.0
Language: C++

**Which solver are you using**
CP-SAT

**What operating system and version?**
Win 10, Debian 10

**What did you do?**
1. Experiment with replacing **break** on the [line 388 of precedences.cc](https://github.com/google/or-tools/blob/8d19323faf51f2f004e4de6c1b32a74001fbc7c1/ortools/sat/precedences.cc#L388) by **continue**.
2. Executed basically any scheduling problem from my data set (for example [protoFiles.zip](https://github.com/google/or-tools/files/5415921/protoFiles.zip))

**What did you see ?**
Significant improvement in search performance (> 10 %) on both Windows and Linux.

**Comment by lperron** [comment]
This is indeed a bug.

Thanks for reporting. We will fix it soon.

**Comment by prissky** [comment]
Thank you for the swift reply! 
I have another suspicion of [line 402](https://github.com/google/or-tools/blob/8d19323faf51f2f004e4de6c1b32a74001fbc7c1/ortools/sat/precedences.cc#L402). Should it be replaced by condition: `if (num_not_true > 1) break;`?

**Comment by lperron** [comment]
No. we checked.
