### ISSUE TITLE
Nuget package for Windows runtime is not compatible with dotnet core 3.1

### ISSUE THREAD

**Issue by mslazynski** [google/or-tools#2207]
Version: 8.0.8283
Language: C#

I am working on a multi-platform project (it's built and used on macOS/Linux/Windows) in dotnet core 3.1 using the OrTools via nuget. Until the last update, everything was ok, the 8.0.8283, however, misbehaves on Windows and shows me the following warning when building the project:

 ```warning` NU1701: Package 'Google.OrTools.runtime.win-x64 8.0.8283' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.```

I have to stay with the older version for this reason only.

**Comment by lperron** [comment]
It is just a warning.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by mslazynski** [comment]
Roger that. I'm going to close this issue and open a better one with the exact problem happening only in the Windows environment.

**Comment by Mizux** [comment]
The issue is on Windows we target `net45` **AND** `netstandard2.0`. For some reason (need to retrieve the issue) Nuget/.Net Core Teams have decided to send a warning on Visual Studio for any project consuming this kind of project.

**Comment by mslazynski** [comment]
@Mizux thanks for the clarification 👍

**Comment by Mizux** [comment]
@mslazynski  the thread: https://github.com/dotnet/standard/issues/439#issuecomment-321608375

**Comment by mslazynski** [comment]
Thanks.
FYI: adding `NoWarn` to PackageReference wasn't enough in my case, the warning was still there. Probably because I was referencing the whole of Google.OrTools and the `NU1701` applied only to its single reference (Windows runtime). I had to disable `NU1701` globally for the project to get rid of the warning.
