### ISSUE TITLE
SCIP Solver with multiple threads produces only ABNORMAL results (without any information)

### ISSUE THREAD

**Issue by Kermel** [google/or-tools#2210]
**What version of OR-tools and what language are you using?**
8.0.8283
C#

**Which solver are you using (e.g. SCIP)**
SCIP

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
1) Create SCIP solver
2) Set number of thread
3) Set variables and constraints (my mps model attached)
4) Run solver.Solve

**What did you expect to see**
Useful results

**What did you see instead?**
ABNORMAL solution and no error message anywhere

Make sure you include information that can help us debug (full error message, model Proto).
[model.zip](https://github.com/google/or-tools/files/5447896/model.zip)

**Comment by Mizux** [comment]
If you don't set a number of thread does it solve ?

**Comment by Kermel** [comment]
Yes, not setting any threads produces useful result

**Comment by martinvanbuuren** [comment]
The same problem arises with Python. (Win 10, SCIP, Python 3.9) One core works just fine, multiple cores results in an abnormal.

**Comment by lperron** [comment]
SCIP parallel is buggy. We will disable it.
