### ISSUE TITLE
Debug C# and C++ in the same debugging session

### ISSUE THREAD

**Issue by proofkhan** [google/or-tools#2211]
Hi,

I am trying to debug C# and C++ in the same debugging session by trying to load the google-ortools-native symbol file. Could you please direct me how to achieve this? Can I find a VC++ project that generates "google-ortools-native.dll"?

Visual Studio 2019

or-tools-stable\ortools\dotnet\Google.OrTools.sln

1. Changed project properties to true 1: Enable native code debugging 2. Allow unsafe code

2. Copied .pdb file to "C:\Users\<user>\.nuget\packages\google.ortools.runtime.win-x64\8.0.9999\runtimes\win-x64\native"

3. F11 at the line below gives following error, Source Not Available : Source information is missing from the debug information for this module

SatHelper.cs Line 51: System.IntPtr data = operations_research_satPINVOKE.SatHelper_Solve(model_proto.CalculateSize(), ProtoHelper.ProtoToByteArray(model_proto));

**Comment by Mizux** [comment]
We don't do dev on windows here, but here few tips:
* You should try to build from source using the CMake based build using the Visual Studio generator
* Then a build time, you should be able to use `--config Debug` to compile everything in debug mode

Hope it will help you.

**Comment by proofkhan** [comment]
Thanks for the response I tried but didn't work. 

I also tried creating a project from the source code but ran into several errors e.g.  in the files local_search.cc, random.h, random.cc, version.cc, routing.cc, integral_solver.cc, expressions.cc

**Error List:**

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2789	'accept': an object of const-qualified type must be initialized	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3648	
Error	C2065	'event_type': undeclared identifier	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3625	
Error	C2065	'event_type': undeclared identifier	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3645	
Error	C2065	'event_type': undeclared identifier	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3682	
Error	C2065	'filter': undeclared identifier	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3625	
Error	C2065	'filter': undeclared identifier	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3647	
Error	C2065	'filter': undeclared identifier	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3648	
Error	C2065	'filter': undeclared identifier	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3652	
Error	C2065	'filter': undeclared identifier	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3655	
Error	C2065	'filter': undeclared identifier	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3662	
Error	C2065	'filter': undeclared identifier	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3684	
Error	C2065	'filter': undeclared identifier	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3686	
Error	C2065	'filter': undeclared identifier	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3690	
Error	C2065	'generator_': undeclared identifier	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\base\random.h	41	
Error	C2504	'operations_research::ACMRandom': base class undefined	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\base\random.h	55	
Error	C2614	'operations_research::ACMRandom': illegal member initialization: 'generator_' is not a base or member	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\base\random.h	28	
Error	C2614	'operations_research::ACMRandom::MTRandom': illegal member initialization: 'ACMRandom' is not a base or member	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\base\random.h	57	
Error	C2614	'operations_research::ACMRandom::MTRandom': illegal member initialization: 'ACMRandom' is not a base or member	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\base\random.h	60	
Error	C2614	'operations_research::ACMRandom::MTRandom': illegal member initialization: 'ACMRandom' is not a base or member	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\base\random.h	62	
Error	C2660	'operations_research::CapAdd': function does not take 1 arguments	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3655	
Error	C2660	'operations_research::CapAdd': function does not take 1 arguments	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3685	
Error	C2065	'OR_TOOLS_MAJOR': undeclared identifier	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\base\version.cc	18	
Error	C2065	'OR_TOOLS_MINOR': undeclared identifier	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\base\version.cc	19	
Error	C2447	'{': missing function header (old-style formal list?)	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\base\random.cc	34	
Error	C2429	language feature 'structured bindings' requires compiler flag '/std:c++17'	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3624	
Error	C2429	language feature 'structured bindings' requires compiler flag '/std:c++17'	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3644	
Error	C2429	language feature 'structured bindings' requires compiler flag '/std:c++17'	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3681	
Error	C1128	number of sections exceeded object file format limit: compile with /bigobj	google-ortools-native	D:\GoogleORTool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\routing.cc	1	
Error	C2050	switch expression not integral	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3645	
Error	C2050	switch expression not integral	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\local_search.cc	3682	
Error	C2059	syntax error: ')'	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\base\random.h	48	
Error	C2059	syntax error: ')'	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\base\random.h	53	
Error	C2059	syntax error: 'namespace'	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\base\random.cc	34	
Error	C2143	syntax error: missing ')' before ';'	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\base\random.h	53	
Error	C2143	syntax error: missing ';' before '{'	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\base\random.cc	34	
Error	C4146	unary minus operator applied to unsigned type, result still unsigned	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\bop\integral_solver.cc	570	
Error	C4146	unary minus operator applied to unsigned type, result still unsigned	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\expressions.cc	1668	
Error	C4146	unary minus operator applied to unsigned type, result still unsigned	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\constraint_solver\expressions.cc	1683	
Error	C1004	unexpected end-of-file found	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\base\random.cc	95	
Error	C2334	unexpected token(s) preceding ':'; skipping apparent function body	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\base\random.h	48	
Error	C2238	unexpected token(s) preceding ';'	google-ortools-native	d:\googleortool\google-ortools-native-dll\google-ortools-native\ortools\base\random.h	53

**Comment by lperron** [comment]
Make sure you are building as a C++17 project.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by proofkhan** [comment]
yes, I am using VS2017

**Comment by lperron** [comment]
That is not what I meant.

1) vs2017 is not supported
2) you need to specify to use the C++17 language.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by proofkhan** [comment]
Hi Laurent,

I have changed the language and build the project with vs2019.

I have included the include and library folders for the dependencies from this link 
https://github.com/google/or-tools/releases/download/v8.0/or-tools_VisualStudio2019-64bit_v8.0.8283.zip

I added the source code to the project from or-tools-stable

the images below

![image](https://user-images.githubusercontent.com/39146033/97965758-fbee3580-1e0e-11eb-9558-696fc16aefd3.png)

![image](https://user-images.githubusercontent.com/39146033/97965934-38219600-1e0f-11eb-8b2c-45509fcc5b8f.png)

**Comment by proofkhan** [comment]
after I changed the language to default as shown in the image below the errors reduce.

![image](https://user-images.githubusercontent.com/39146033/97966536-1248c100-1e10-11eb-85dd-d40dc81431de.png)

![image](https://user-images.githubusercontent.com/39146033/97967388-407ad080-1e11-11eb-9074-283cbf4822c4.png)

**Comment by Mizux** [comment]
Just to be sure,

* Did you try to create a Visual Studio project from scratch ?
* The zip archive contains **release** build of all libraries and of ortools.lib, I'm not sure it is what you expect...
* `google-ortools-native` is a wrapper on top of ortools.lib so I don't understand why you have error in `lpi_glop.cc` since `ortools.lib` contains the compiled code

ps: You can join us on discord (see chat link on the README.md)

**Comment by proofkhan** [comment]
> Just to be sure,
> 
> * Did you try to create a Visual Studio project from scratch ?
> * The zip archive contains **release** build of all libraries and of ortools.lib, I'm not sure it is what you expect...
> * `google-ortools-native` is a wrapper on top of ortools.lib so I don't understand why you have error in `lpi_glop.cc` since `ortools.lib` contains the compiled code
> 
> ps: You can join us on discord (see chat link on the README.md)

yes, I am trying to compile the dll with source code to be able to debug into the c++ code as shown in the image below

![image](https://user-images.githubusercontent.com/39146033/97975460-47a7db80-1e1d-11eb-886b-4484c8103c32.png)

**Apologies, I updated my earlier comment. I am not using the release version in the link I mentioned earlier.**

![image](https://user-images.githubusercontent.com/39146033/97975195-d831ec00-1e1c-11eb-8279-2c814634d05e.png)

![image](https://user-images.githubusercontent.com/39146033/97975223-e2ec8100-1e1c-11eb-901f-ee04f4516f9c.png)

**Comment by lperron** [comment]
We are now fully cmake based, for C++ and C#. So setting the build in debug mode should solve this.
