### ISSUE TITLE
Constraints not implemented at c# wrapper

### ISSUE THREAD

**Issue by Lederilon** [google/or-tools#2215]
C#
Hi, I have found LoadAtMostOneConstraint, LoadTableConstraint, LoadRoutesConstraint, LoadCircuitCoveringConstraint at source code.
https://github.com/google/or-tools/blob/84c35244c9bdd635609af703bbf3053c16c487c0/ortools/sat/cp_model_loader.cc#L1760
Do you have any plans to implement them at c# wrapper?

**Comment by lperron** [comment]
No. They are not available in C++ either. This is internal API.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 5 nov. 2020 à 14:26, Kostya Hrischenko <notifications@github.com> a
écrit :
