### ISSUE TITLE
Feature request: pause/resume feature for CP-SAT or-tools

### ISSUE THREAD

**Issue by omyl** [google/or-tools#2216]
It would be helpful to allow pause (and resume later) or-tools computations (for example in case usage interim result - or "no result in given time" information - in other system and cancel or resume  computations based on its decision, both without wasting resources for -potentially useless- computations).

We tried to implement this feature via modifying time_limit class, and this seems to be usable (for our cases - we are using CP/CP-SAT and Java only), but we are not sure we cover all situations.

**Comment by prissky** [comment]
Seems useful to ease a decomposition of large problems!

**Comment by Mizux** [comment]
For cross reference, here PR proposal -> https://github.com/google/or-tools/pull/2234

**Comment by omyl** [comment]
is  there any plan if/when/how this feature could be implemented?

**Comment by lperron** [comment]
No plan.
The amount of work vs the gain compared to a simple blocking mutex in the
solution callback is not worth it IMO.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
