### ISSUE TITLE
Is it possible to allow a vehicle to visit the same location multiple times?

### ISSUE THREAD

**Issue by ankitmundada** [google/or-tools#2217]
I am trying to implement VRP with Pickup and delivery Constraints. 
Some of the locations are such that visiting a pointA from pointB requires to already have visited pointB. 
For example a merchant (pointA) wants to replace some item of a user (pointB). For this the vehicle will have to first visit pointA, take the new item from merchant. Then visit pointB (give the item to user), take the old item back and give it back to merchant (pointA). The whole route becomes pointA -> pointB -> pointA.

Is it possible to do this with or-tools VRP solution?
If not currently, I think this a nice to have feature for some new release.

**Comment by Mizux** [comment]
You must:
* use the Pickup&Delivery feature: https://developers.google.com/optimization/routing/pickup_delivery
* Duplicate nodes to have 2 P&D: `pointA1 -> pointB1` and `pointB2 -> pointA2`
* you may add a constraint such that `pointB1 <= pointB2`
