### ISSUE TITLE
Failed to run CPLEX in Python & MacOS setting

### ISSUE THREAD

**Issue by berkorbay** [google/or-tools#2218]
**What version of OR-tools and what language are you using?**
Version: master (8.0.8283)
Language: Python 3.9.0 64-bit

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CPLEX

**What operating system (Linux, Windows, ...) and version?**
MacOS Catalina 10.15.7

**What did you do?**
I tried to set the solver to CPLEX for MIP.

`pywraplp.Solver('solvername',pywraplp.Solver.CPLEX_MIXED_INTEGER_PROGRAMMING)`

**What did you expect to see**
I expected it to work normally (I have *IBM ILOG CPLEX Optimization Studio V12.10 for OSX Multiplatform Multilingual (CC43DML)* installed)

**What did you see instead?**
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1109 18:48:33.670819 205258176 linear_solver.cc:426] Linear solver not recognized.
*** Check failure stack trace: ***
bash-3.2$ Linear solver not recognized.
```

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by Mizux** [comment]
To be sure, did you rebuild from source (CPLEX is a compile time dependency) ?
Which build system did you use ?
Which command did you use ?

**Comment by berkorbay** [comment]
Ah ok, I initially thought it would work just like switching the solver. 🤦‍♀️ I switched to Gurobi btw which is I think included if I read the documentation correctly. Getting another error but that is for another issue:) Thanks a lot!

**Comment by Mizux** [comment]
yes, in the recent release (v7.8+ IIRC), gurobi is now a dynamic optional dependency.
