### ISSUE TITLE
cmake fetchcontent fail if there is another dependency that contains protobuf

### ISSUE THREAD

**Issue by sazconaitbit** [google/or-tools#2219]
im using the FetchContent with cmake to manage my dependencies and include or-tools as dependency for my project. but also im using grpc and protobuf

```
FetchContent_Declare(
        protobuf
        GIT_REPOSITORY https://github.com/protocolbuffers/protobuf.git
        GIT_TAG        v3.13.0
        SOURCE_SUBDIR  cmake
)
## END PROTOBUF ##

## GRPC ##
FetchContent_Declare(
        grpc
        GIT_REPOSITORY https://github.com/grpc/grpc.git
        GIT_TAG        v1.33.x
        GIT_PROGRESS   TRUE
)
## END GRPC ##

## OR-TOOLS ##
FetchContent_Declare(
        or-tools
        GIT_REPOSITORY https://github.com/google/or-tools.git
        GIT_TAG        master
        GIT_PROGRESS   TRUE
        PATCH_COMMAND git apply "${PROJECT_SOURCE_DIR}/patches/or-tools-protobuf.patch"
)

FetchContent_MakeAvailable(protobuf grpc or-tools)
```

in this case grpc also use protobuf, so when cmake try to make available or-tools  I get the next error

```
CMake Error at build/_deps/protobuf-src/cmake/libprotobuf-lite.cmake:64 (add_library):
  add_library cannot create target "libprotobuf-lite" because another target
  with the same name already exists.  The existing target is a static library
  created in source directory
  "/Users/samuaz/Projects/itbit/securities-settlement/cpp/third_party/grpc-src/third_party/protobuf/cmake".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  build/_deps/protobuf-src/cmake/CMakeLists.txt:250 (include) 
```
**So maybe or-tools should check if protobuf already exists before populate it?**

If  I try with or-tools set(BUILD_Protobuf OFF):

```
--   No package 'protobuf' found
CMake Error at /Users/samuaz/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/202.6948.80/CLion.app/Contents/bin/cmake/mac/share/cmake-3.17/Modules/FindPkgConfig.cmake:497 (message):
  A required package was not found
```
because using FetchContent_Declare we can not make the dependency available for findPackage

thanks.

**Comment by Mizux** [comment]
currently we are using
https://github.com/google/or-tools/blob/2089add49bf4dff4edf42fffa85afc5b758f44b9/cmake/deps.cmake#L43-L48

I.e. if we are not building Protobuf then we want to find them through `find_package()`
a possible solution would be to replace the first test by something like this:
```cmake
if(NOT BUILD_Protobuf AND NOT TARGET protobuf::libprotobuf)
```

**Comment by sazconaitbit** [comment]
thanks @Mizux right now I'm using the stable branch, I will try with master and apply small patch with your suggestion at FetchContent_Declare time.

Or maybe in my cmake use FetchContent_Populate instead of FetchContent_Declare for the or-tools to make an isolation operation

**Comment by Mizux** [comment]
BTW i'll try to apply this patch on master ASAP since it will allow us to better support super projects incorporating google/or-tools (through FetchContent or add_subdirectory)
