### ISSUE TITLE
CVRPTW gives different result in Python and Java

### ISSUE THREAD

**Issue by ZhiWeiCui** [google/or-tools#2221]
I have read this https://github.com/google/or-tools/issues/2090, I want to know if there are other reasons that can cause such a problem.

**Comment by Mizux** [comment]
https://github.com/google/or-tools/blob/45770b833997f827d322e929b1ed4781c4e60d44/ortools/constraint_solver/constraint_solver.h#L2785-L2795

**Comment by lperron** [comment]
We do not aim for determinism across platforms.
