### ISSUE TITLE
Why isn't VRP example resulted in a solution when a pickup==delivery

### ISSUE THREAD

**Issue by Ariel-ds-code** [google/or-tools#2223]
**What version of OR-tools and what language are you using?**
Language: Python

**Which solver are you using : Routing Solver

What operating system : Linux

**What did you do?**
1. Go to https://developers.google.com/optimization/routing/pickup_delivery
2. Edit data['pickups_deliveries']: change second item from [2, 10] to [6, 10]
3. Run the code

**What did you expect to see**
A relevant solution, would be come out.
**What did you see instead?**
No solution is found. 
(would be better if you can print out that there is no solution)

**Comment by lperron** [comment]
Please use the mailing list.
