### ISSUE TITLE
Added disjunction for optional reload node becomes insignificant with constraint for node wise allowed vehicles. 

### ISSUE THREAD

**Issue by mdnafiskhan** [google/or-tools#2224]
**What version of OR-tools and what language are you using?**
Version: ortools (8.0.8283)
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing Solver

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you do?**
I was trying to achieve a multi-trip solution by adding reload nodes with demand = -1 * max(vehicle_capacities) and disjunctions to make reloading optional as shown here [https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/samples/cvrp_reload.py](url) and this worked perfectly.

Then I tried to move one step further and tried adding constraint to set vehicles allowed to visit a node like below:

 ```
 for nodo_i in range(routing.nodes()):
            allowed_vehicles = list(data['vehiclesAllowed'][nodo_i])
            print('For node {0}: {1}'.format(nodo_i, allowed_vehicles))
            routing.VehicleVar(nodo_i).SetValues(allowed_vehicles)
```

**What did you expect to see**

I expected to see results according to the newly added constraint and with some multiple trips as there were some optional reload nodes.

**What did you see instead?**

Results were on my expectation just that all reload nodes were visited and non of the reload node was dropped. But solver should have dropped some reload nodes to complete the trip quicker. I have tested it on a dataset with more reload nodes than drop nodes, even in that case all reload nodes were visited, which was not needed.

Note: Before adding a constraint to set vehicles allowed to visit a node this was working fine.

**Things I did to resolve this**

I thought I have made some mistakes while adding a constraint to set vehicles allowed to visit reload nodes.  

I came across this post [https://github.com/google/or-tools/issues/334#issuecomment-484781754](url) and as suggested I tired adding `-1` to the vehicle list for all nodes (reload nodes, depot, and drop points) but didn't get any solution after 30 minutes of run time.

Then I tried with `-1` only for the reload nodes but no solution again.

And without `-1` in the vehicle list for all nodes, I got a solution but all reload nodes were visited even if no. of the reload nodes were more than drop points.

Please help me with this.
Thanks

[cvrp_reload.TXT](https://github.com/google/or-tools/files/5531214/cvrp_reload.TXT)

**Comment by lperron** [comment]
Please use the mailing list.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 12 nov. 2020 à 15:32, mdnafiskhan <notifications@github.com> a
écrit :
