### ISSUE TITLE
Double counting of Gurobi Floating licenses when called from or-tools

### ISSUE THREAD

**Issue by PeterSels** [google/or-tools#2227]
Dear or-tools coders,

1. We experience a problem where, if the Gurobi solvers is instantiated from ortools 8.0.8283 in the single python call:
self.solver = pywraplp.Solver.CreateSolver('GUROBI_MIXED_INTEGER_PROGRAMMING') 
, the floating token license server 'hands over' 2 tokens instead of 1 token per call.
Gurobi support has confirmed this happens for them as well.
This happens for the locally installed Gurobi 9.0.3 version connected to the Gurobi 9.0.3 floating license on the server.

2. We also experience that or-tools, confirmed by Gurobi support, does not work yet with Gurobi 9.1.0, only released last week. Whatever the Gurobi license type, we never get an instantiated solver back (but always None) from the call mentioned in 1. This can be understandable, since or-tools has not done an update since Gurobi 9.1.0 ws released.

It would be great if you could solve the 2 problems above. :)

(PS: When calling a Gurobi 9.0.3 solver via or-tools when the license must come from a Gurobi node locked license the license counting goes just fine: 1 gotten for 1 asked (i.o. 2 gotten 1 asked for a GUrobi floating license).

(PPS: When calling Gurobi 9.0.3 directly without ortools- the floating license counting goes just fine.)

thanks and best regards,

Peter

**Comment by Mizux** [comment]
@At Peter for 2) just create an issue... Do you know the name of the gurobi library in 9.1.0 ?

**Comment by lperron** [comment]
Indeed. I check that the license is valid by creating an env, then I create
a new env for the solver.
I forgot to release the checking env.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by PeterSels** [comment]
Thanks for replying Laurent. Does it makes sense to you (from the code) that this issue of double counting would only appear in case of Gurobi floating licenses and not in the case of Gurobi node locked licenses? I have both, so I can check. Peter

**Comment by lperron** [comment]
No. I believe a node locked license is cached, and thus asking twice only
consumes one license.

Le lun. 16 nov. 2020 à 13:05, Peter Sels <notifications@github.com> a
écrit :

**Comment by PeterSels** [comment]
> @PeterSels for 2) just create an issue... Do you know the name of the gurobi library in 9.1.0 ?

As you proposed, I created a new issues for update or-tools from Gurobi 9.0.3 to Gurobi 9.1.0 in :
https://github.com/google/or-tools/issues/2229

**Comment by Mizux** [comment]
@PeterSels my bad, shame on me, I wanted to say, **I have** just created an issue (#2228).
BTW both issues should be fixed on master now...
