### ISSUE TITLE
Update Gurobi 9.0.3 -> 9.1.0

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#2228]
As described in #2227 Gurobi has to be updated...

This code must be updated
https://github.com/google/or-tools/blob/84c35244c9bdd635609af703bbf3053c16c487c0/ortools/linear_solver/gurobi_environment.cc#L200-L240

I suppose the new version is *gurobi91.dll* or *libgurobi91.so* or *libgurobi91.dylib*

**Comment by lperron** [comment]
Yes. You can specify the full path to the shared library, and it should
work.
