### ISSUE TITLE
Update Gurobi 9.0.3 -> 9.1.0

### ISSUE THREAD

**Issue by PeterSels** [google/or-tools#2229]
@PeterSels for 2) just create an issue... Do you know the name of the gurobi library in 9.1.0 ?

Yes:
--------------
On windows
my %GUROBI_HOME% is:
c:\gurobi903\win64
and lib and bin dirs  look like this:

C:\gurobi903\win64\lib>dir
 Volume in drive C is OS
 Volume Serial Number is CA47-740E

 Directory of C:\gurobi903\win64\lib

11/10/2020  15:08    <DIR>          .
11/10/2020  15:08    <DIR>          ..
11/08/2020  15:38           162.237 gurobi-javadoc.jar
11/08/2020  15:38            85.864 gurobi.jar
11/08/2020  15:38               803 gurobi.py
11/08/2020  15:38            49.520 gurobi90.lib
11/08/2020  15:38           144.384 gurobi90.netstandard20.dll
11/08/2020  15:38           445.326 gurobi90.netstandard20.xml
11/08/2020  15:38         2.377.692 gurobi_c++md2015.lib
11/08/2020  15:38         2.217.914 gurobi_c++md2017.lib
11/08/2020  15:38         2.181.590 gurobi_c++md2019.lib
11/08/2020  15:38         3.603.362 gurobi_c++mdd2015.lib
11/08/2020  15:38         2.822.346 gurobi_c++mdd2017.lib
11/08/2020  15:38         2.679.138 gurobi_c++mdd2019.lib
11/08/2020  15:38         2.843.874 gurobi_c++mt2015.lib
11/08/2020  15:38         2.750.180 gurobi_c++mt2017.lib
11/08/2020  15:38         2.705.452 gurobi_c++mt2019.lib
11/08/2020  15:38         4.129.272 gurobi_c++mtd2015.lib
11/08/2020  15:38         3.394.414 gurobi_c++mtd2017.lib
11/08/2020  15:38         3.225.478 gurobi_c++mtd2019.lib
11/08/2020  15:38             1.215 rootcert.pem
              19 File(s)     35.820.061 bytes
               2 Dir(s)  898.692.595.712 bytes free

--
In the bin dir we have:
C:\gurobi903\win64\bin>dir
 Volume in drive C is OS
 Volume Serial Number is CA47-740E

 Directory of C:\gurobi903\win64\bin

11/10/2020  15:27    <DIR>          .
11/10/2020  15:27    <DIR>          ..
11/08/2020  15:39        18.537.517 grbcluster.exe
11/08/2020  15:39        15.382.826 grbgetkey.exe
11/08/2020  15:39        15.169.412 grbprobe.exe
11/08/2020  15:38           189.440 grbtune.exe
11/08/2020  15:38           335.360 grb_ts.exe
11/08/2020  15:38               330 gurobi.bat
11/08/2020  15:38             2.238 gurobi.env
19/10/2020  16:29               744 gurobi.log
11/08/2020  15:38        32.569.720 gurobi90.dll
11/08/2020  15:38           159.744 Gurobi90.NET.dll
11/08/2020  15:38           454.758 Gurobi90.NET.XML
11/08/2020  15:38        31.906.680 gurobi90_light.dll
11/08/2020  15:38           186.880 GurobiJni90.dll
11/08/2020  15:38           185.856 gurobi_cl.exe
11/08/2020  15:38               491 pysetup.bat
11/08/2020  15:38           166.912 vslauncher.exe
11/08/2020  15:38           458.336 vswhere.exe
              17 File(s)    115.707.244 bytes
               2 Dir(s)  898.691.887.104 bytes free

--

For 910 dirs on Windows it look like this:  (ignore the 'set_aside')

C:\gurobi910set_aside\win64\lib>dir
 Volume in drive C is OS
 Volume Serial Number is CA47-740E

 Directory of C:\gurobi910set_aside\win64\lib

09/11/2020  14:54    <DIR>          .
09/11/2020  14:54    <DIR>          ..
29/10/2020  13:59           159.947 gurobi-javadoc.jar
29/10/2020  13:59            86.294 gurobi.jar
29/10/2020  13:59               804 gurobi.py
29/10/2020  13:59            51.354 gurobi91.lib
29/10/2020  13:59           145.920 gurobi91.netstandard20.dll
29/10/2020  13:59           450.692 gurobi91.netstandard20.xml
29/10/2020  13:59         2.394.372 gurobi_c++md2015.lib
29/10/2020  13:59         2.231.942 gurobi_c++md2017.lib
29/10/2020  13:59         2.195.268 gurobi_c++md2019.lib
29/10/2020  13:59         3.620.216 gurobi_c++mdd2015.lib
29/10/2020  13:59         2.834.348 gurobi_c++mdd2017.lib
29/10/2020  13:59         2.691.520 gurobi_c++mdd2019.lib
29/10/2020  13:59         2.860.554 gurobi_c++mt2015.lib
29/10/2020  13:59         2.764.204 gurobi_c++mt2017.lib
29/10/2020  13:59         2.719.130 gurobi_c++mt2019.lib
29/10/2020  13:59         4.146.122 gurobi_c++mtd2015.lib
29/10/2020  13:59         3.406.412 gurobi_c++mtd2017.lib
29/10/2020  13:59         3.237.860 gurobi_c++mtd2019.lib
29/10/2020  13:59             1.215 rootcert.pem
              19 File(s)     35.998.174 bytes
               2 Dir(s)  898.691.493.888 bytes free

--
and in the bin dir:
C:\gurobi910set_aside\win64\bin>dir
 Volume in drive C is OS
 Volume Serial Number is CA47-740E

 Directory of C:\gurobi910set_aside\win64\bin

09/11/2020  14:54    <DIR>          .
09/11/2020  14:54    <DIR>          ..
29/10/2020  13:59        18.213.126 grbcluster.exe
29/10/2020  13:59        16.370.626 grbgetkey.exe
29/10/2020  13:59        15.787.019 grbprobe.exe
29/10/2020  13:59           191.488 grbtune.exe
29/10/2020  13:59           345.600 grb_ts.exe
29/10/2020  13:59               341 gurobi.bat
29/10/2020  13:59        33.609.592 gurobi91.dll
29/10/2020  13:59           167.800 Gurobi91.NET.dll
29/10/2020  13:59           460.219 Gurobi91.NET.XML
29/10/2020  13:59        32.943.480 gurobi91_light.dll
29/10/2020  13:59           194.936 GurobiJni91.dll
29/10/2020  13:59           181.760 gurobi_cl.exe
29/10/2020  13:59           166.912 vslauncher.exe
29/10/2020  13:59           458.336 vswhere.exe
              14 File(s)    119.091.235 bytes
               2 Dir(s)  898.695.180.288 bytes free

-----------------
On Mac 
my $GUROBI_HOME is:
/Library/gurobi903/mac64

it looks like this:
for 903:
lib:
Herettix:lib peter$ pwd
/Library/gurobi903/mac64/lib
Herettix:lib peter$ l
total 27176
-rwxrwxr-x    1 root  admin     1215 Aug 12 01:22 rootcert.pem
-rwxrwxr-x    1 root  admin   446168 Aug 12 01:22 libgurobi_g++4.2.a
-rwxrwxr-x    1 root  admin   445326 Aug 12 01:22 gurobi90.netstandard20.xml
-rwxrwxr-x    1 root  admin   144384 Aug 12 01:22 gurobi90.netstandard20.dll
-rwxrwxr-x    1 root  admin    85864 Aug 12 01:22 gurobi.jar
-rwxrwxr-x    1 root  admin   162237 Aug 12 01:22 gurobi-javadoc.jar
drwxrwxr-x    3 root  admin       96 Aug 12 01:23 python3.6
drwxrwxr-x    3 root  admin       96 Aug 12 01:23 python3.5
drwxrwxr-x    3 root  admin       96 Aug 12 01:23 python2.7
drwxrwxr-x    3 root  admin       96 Aug 12 01:23 python3.8
drwxrwxr-x  185 root  admin     5920 Aug 12 01:23 python3.7
-rwxrwxr-x    1 root  admin      796 Aug 12 01:23 gurobi.py
-rwxrwxr-x    1 root  admin  6471280 Aug 12 02:18 libgurobi90.dylib
-rwxrwxr-x    1 root  admin   111040 Aug 12 02:18 libGurobiJni90.jnilib
-rwxrwxr-x    1 root  admin  6025856 Aug 12 02:18 libgurobi90_light.dylib
lrwxr-xr-x    1 root  admin       20 Oct 29 11:55 libgurobi_c++.a -> ./libgurobi_g++4.2.a
drwxrwxr-x   18 root  admin      576 Oct 29 11:55 .
drwxrwxr-x   15 root  admin      480 Nov 13 16:02 ..
---
bin:
Herettix:bin peter$ pwd
/Library/gurobi903/mac64/bin
Herettix:bin peter$ l
total 78312
-rwxrwxr-x   1 root  admin       177 Aug 12 01:22 gurobi.sh
-rwxrwxr-x   1 root  admin      2238 Aug 12 01:22 gurobi.env
-rwxrwxr-x   1 root  admin     42288 Aug 12 02:17 grbtune
-rwxrwxr-x   1 root  admin  11522848 Aug 12 02:17 grbprobe
-rwxrwxr-x   1 root  admin   3295664 Aug 12 02:17 python3.7
-rwxrwxr-x   1 root  admin  11655184 Aug 12 02:17 grbgetkey
-rwxrwxr-x   1 root  admin     43424 Aug 12 02:17 gurobi_cl
-rwxrwxr-x   1 root  admin  13415616 Aug 12 02:17 grbcluster
-rwxrwxr-x   1 root  admin     97216 Aug 12 02:17 grb_ts
drwxrwxr-x  11 root  admin       352 Aug 12 02:17 .
drwxrwxr-x  15 root  admin       480 Nov 13 16:02 ..
Herettix:bin peter$ 
--

for 910:
lib:
Herettix:lib peter$ pwd
/Library/gurobi910/mac64/lib
Herettix:lib peter$ l
total 28176
-rwxrwxr-x    1 root  admin    86294 Oct 29 21:52 gurobi.jar
-rwxrwxr-x    1 root  admin   159947 Oct 29 21:52 gurobi-javadoc.jar
-rwxrwxr-x    1 root  admin     1215 Oct 29 21:52 rootcert.pem
-rwxrwxr-x    1 root  admin   444552 Oct 29 21:52 libgurobi_g++4.2.a
-rwxrwxr-x    1 root  admin   450692 Oct 29 21:52 gurobi91.netstandard20.xml
-rwxrwxr-x    1 root  admin   145920 Oct 29 21:52 gurobi91.netstandard20.dll
drwxrwxr-x    3 root  admin       96 Oct 29 21:52 python3.9
drwxrwxr-x    3 root  admin       96 Oct 29 21:52 python3.8
drwxrwxr-x  185 root  admin     5920 Oct 29 21:52 python3.7
drwxrwxr-x    3 root  admin       96 Oct 29 21:52 python3.6
drwxrwxr-x    3 root  admin       96 Oct 29 21:52 python2.7
-rwxrwxr-x    1 root  admin      797 Oct 29 21:52 gurobi.py
-rwxrwxr-x    1 root  admin  6272368 Oct 29 22:38 libgurobi91_light.dylib
-rwxrwxr-x    1 root  admin  6722032 Oct 29 22:38 libgurobi91.dylib
-rwxrwxr-x    1 root  admin   111200 Oct 29 22:38 libGurobiJni91.jnilib
lrwxr-xr-x    1 root  admin       20 Nov  5 17:40 libgurobi_c++.a -> ./libgurobi_g++4.2.a
drwxrwxr-x   18 root  admin      576 Nov  5 17:40 .
drwxrwxr-x   13 root  admin      416 Nov  5 21:28 ..
Herettix:lib peter$ 
--
910 bin:
Herettix:bin peter$ pwd
/Library/gurobi910/mac64/bin
Herettix:bin peter$ l
total 75464
-rwxrwxr-x   1 root  admin       177 Oct 29 21:52 gurobi.sh
-rwxrwxr-x   1 root  admin     42592 Oct 29 22:37 grbtune
-rwxrwxr-x   1 root  admin  11019920 Oct 29 22:37 grbprobe
-rwxrwxr-x   1 root  admin   3295664 Oct 29 22:37 python3.7
-rwxrwxr-x   1 root  admin  11405040 Oct 29 22:37 grbgetkey
-rwxrwxr-x   1 root  admin     43392 Oct 29 22:37 gurobi_cl
-rwxrwxr-x   1 root  admin  12703040 Oct 29 22:37 grbcluster
-rwxrwxr-x   1 root  admin    106704 Oct 29 22:37 grb_ts
drwxrwxr-x  10 root  admin       320 Oct 29 22:37 .
drwxrwxr-x  13 root  admin       416 Nov  5 21:28 ..
Herettix:bin peter$ 

for linux, I don't know... but can go download and check if you want me to...

Also let me know if I could help in testing it out.

thanks and best regards,

Peter

---------------
_Originally posted by @Mizux in https://github.com/google/or-tools/issues/2227#issuecomment-727922064_

**Comment by Mizux** [comment]
Should be in #2228
