### ISSUE TITLE
a bug in "https://developers.google.cn/optimization/lp/glop"

### ISSUE THREAD

**Issue by whoknowsname** [google/or-tools#2230]
**What version of OR-tools and what language are you using?**
Version: 7.8.7959
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
GLOP

**What operating system (Linux, Windows, ...) and version?**
Windows10

**What did you do?**
1.copy the code from https://developers.google.cn/optimization/lp/glop#entire_program
2.when i run the code in pycharm with python 3.7, IDE told me an error happened:
solver = pywraplp.Solver.CreateSolver('GLOP')
TypeError: CreateSolver() missing 1 required positional argument: 'solver_id'
3.then i change the code to "solver = pywraplp.Solver.CreateSolver('Example', 'GLOP')", it was run well.

**Make sure you include information that can help us debug (full error message, model Proto).**
solver = pywraplp.Solver.CreateSolver('GLOP')
TypeError: CreateSolver() missing 1 required positional argument: 'solver_id'

i think the code "solver = pywraplp.Solver.CreateSolver('GLOP')"
 in https://developers.google.cn/optimization/lp/glop#entire_program
should be changed to "solver = pywraplp.Solver.CreateSolver('exampleName', 'GLOP')"

**Comment by lperron** [comment]
This code needs or-tools 8.0

**Comment by Mizux** [comment]
> The `MPSolver::CreateSolver` signature has been changed. The model name argument has been dropped.

ref: https://github.com/google/or-tools/releases/tag/v8.0
