### ISSUE TITLE
c# api: allow to pass constraint name for MPConstraint objects

### ISSUE THREAD

**Issue by smoothdeveloper** [google/or-tools#2231]
When exporting the model to LP file, the constraint get autogenerated names if no name is given:

https://github.com/google/or-tools/blob/8d19323faf51f2f004e4de6c1b32a74001fbc7c1/ortools/linear_solver/linear_solver.h#L1290

But the LinearConstraint types defined in the C# API doen't allow this name to be specified:

https://github.com/google/or-tools/blob/8d19323faf51f2f004e4de6c1b32a74001fbc7c1/ortools/linear_solver/csharp/LinearConstraint.cs#L73

I'm not sure how the dotnet wrapper works, but it would be useful to have ability to get/set that name either through a constructor or through a property.

**Comment by Mizux** [comment]
https://github.com/google/or-tools/blob/8d19323faf51f2f004e4de6c1b32a74001fbc7c1/ortools/linear_solver/csharp/linear_solver.i#L82

https://github.com/google/or-tools/blob/8d19323faf51f2f004e4de6c1b32a74001fbc7c1/ortools/linear_solver/csharp/linear_solver.i#L234

**Comment by lperron** [comment]
the generated code contains the following signature

public Constraint MakeConstraint(double lb, double ub, string name)

on the Solver class.

**Comment by Mizux** [comment]
For the record:
https://github.com/google/or-tools/blob/8d19323faf51f2f004e4de6c1b32a74001fbc7c1/ortools/linear_solver/csharp/linear_solver.i#L113-L120

**Comment by smoothdeveloper** [comment]
Thanks for the prompt feedback, I need to fix the following code:

https://github.com/matthewcrews/flips/blob/7951951714ae86f4a11397cf7af7eb3fa5fa7bd9/Flips/Solve.fs#L56-L74

The code currently makes use of the `Google.OrTools.LinearSolver.Equality` and `Google.OrTools.LinearSolver.RangeConstraint` constructors, it seems that I'd need to bypass that and implement the same as what those types currently do in their respective `Constraint Extract(Solver solver)` virtual methods.

It feels those two classes should have the extra constructor with `string name` parameter and pass that to the call to solver.MakeConstraint, is this going to be considered in future update?
