### ISSUE TITLE
AddModuloEquality() is making model invalid in ortools v8.0.8283 [works in v6.10]

### ISSUE THREAD

**Issue by 270ajay** [google/or-tools#2232]
**What version of OR-tools and what language are you using?**
Version: v8.0.8283
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
1. Please run the code

**What did you expect to see**
- Code would print solution values for `var1` and `var2`

**What did you see instead?**
- Code prints `Model invalid` 

```python
from ortools.sat.python import cp_model

model = cp_model.CpModel()

var1 = model.NewIntVar(0, 10, "var1")
var2 = model.NewIntVar(0, 10, "var2")

isVar1Odd = model.NewBoolVar("IsVar1Odd")
isVar2Odd = model.NewBoolVar("IsVar2Odd")

model.AddModuloEquality(1, var1, 2).OnlyEnforceIf(isVar1Odd)
model.AddModuloEquality(1, var2, 2).OnlyEnforceIf(isVar2Odd)
model.AddBoolOr([isVar1Odd, isVar2Odd])

solver = cp_model.CpSolver()
status = solver.Solve(model)

if status == cp_model.INFEASIBLE:
    print("Infeasible model")

if status == cp_model.MODEL_INVALID: # does not work in ortools v8.0.8283
    print("Model invalid")

if status == cp_model.OPTIMAL:
    print("var1: "+str(solver.Value(var1)))
    print("var2: "+str(solver.Value(var2)))

if status == cp_model.FEASIBLE: # works in ortools v6.10.6025
    print("var1: "+str(solver.Value(var1)))
    print("var2: "+str(solver.Value(var2)))
```

**Anything else we should know about your project / environment**
-N/A

Workaround:
https://stackoverflow.com/questions/51639178/how-do-constraint-optimization-in-ortools-with-coefficents

**Comment by lperron** [comment]
AddModuloEquality does not support enforcement literals.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
and it did not work in 6.x. It was just not checked.

**Comment by 270ajay** [comment]
Thank you for clarifying!

I would be using the approach you mentioned here:
https://stackoverflow.com/questions/51639178/how-do-constraint-optimization-in-ortools-with-coefficents
