### ISSUE TITLE
Crash in CP-Sat on Windows in debug

### ISSUE THREAD

**Issue by JoelKKelso** [google/or-tools#2236]
**What version of OR-tools and what language are you using?**
Version: v8.0
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10 Pro
Visual Studio 16.7.3

**What did you do?**
Solving a model with around 8,000 boolean vars and 40,000 linear constraints.

**What did you expect to see**
Vector array out of bounds exception in operations_research::sat::Trail (see attached stack dump).

**What did you see instead?**
Successful completion of solve.

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
I haven't yet had time to simplify the model to diagnose what is causing it, but here is some
hopefully helpful info.
The model I'm testing with produces the same error every time.
The same model solved correctly in ortools 7.8.
Have only seen the error running with Debug build, have seen the same model succeed in a release build
once.
Have seen the same error coming from a worker thread (when running with 12 workers) and from the main 
solve thread (when restricting the number of workers to 1).
A smaller version of the model (roughly half the size) solved correctly at least once.

[CP-SatWorkerOOBStackDump.txt](https://github.com/google/or-tools/files/5563739/CP-SatWorkerOOBStackDump.txt)

![CP-SatWorkerOOBFrame1](https://user-images.githubusercontent.com/66106522/99609187-5fe93e80-2a4a-11eb-98de-8ca67597f8a1.png)

![CP-SatWorkerOOBFrame2](https://user-images.githubusercontent.com/66106522/99609202-67a8e300-2a4a-11eb-8f59-27aebe9db3d2.png)

**Comment by lperron** [comment]
can you send us the model proto ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 19 nov. 2020 à 02:35, Joel Kelso <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
Closing the issue. Please reopen if you can send us the proto of the model.

**Comment by JoelKKelso** [comment]
Proto of model:
[CP-SatDump.zip](https://github.com/google/or-tools/files/5605370/CP-SatDump.zip)

I have found that this reliably solves in a Windows release build but reliably crashes in debug build.

**Comment by lperron** [comment]
Which parameters are you using ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 27 nov. 2020 à 01:12, Joel Kelso <notifications@github.com> a
écrit :

**Comment by JoelKKelso** [comment]
The only parameters set are set_num_search_workers . I have run it with 1 and 12, both give the same error in debug build.

**Comment by JoelKKelso** [comment]
Found a very small example with the bug, proto attached.
[WindowsDebugModelSmall.zip](https://github.com/google/or-tools/files/5633437/WindowsDebugModelSmall.zip)

**Comment by JoelKKelso** [comment]
I have attached a short example C++ program (and a VS 2019 solution) that exhibits this bug in or-tools v9.0  : this completes successfully in Release builds but crashes in Debug. There is an example model proto in the zip file, but we have found that basically every model we try fails in Debug.
[CPSatProtoSolver.zip](https://github.com/google/or-tools/files/6582287/CPSatProtoSolver.zip)

**Comment by lperron** [comment]
most likely a compilation flag issue.

Problems works fine in debug on mac.
I am recompiling on windows.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Definitely a flag issue.
I compiled the sat_runner.exe example with the library in debug mode.

It runs the examples flawlessly with 8 workers.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by JoelKKelso** [comment]
Thanks. Any idea of what kind of settings might typically cause this kind of thing ?

**Comment by Mizux** [comment]
Very very very wild guess maybe this ?
https://github.com/google/or-tools/blob/b37d9c786b69128f3505f15beca09e89bf078a89/ortools/sat/encoding.h#L130-L142

**Comment by lperron** [comment]
I would compare the flags when compiling with the command line interface
against the one from your project.

To compile in debug, I use

"cl /std:c++17 /EHsc /MD /nologo -nologo  /D__WIN32__ /DPSAPI_VERSION=1
/DNOMINMAX /DWIN32_LEAN_AND_MEAN=1 /D_CRT_SECURE_NO_WARNINGS /Od /Zi"
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
