### ISSUE TITLE
fz: Not supported int_lin_le_imp

### ISSUE THREAD

**Issue by glebbelov** [google/or-tools#2241]
**What version of OR-tools and what language are you using?**
Version: master/stable

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
FlatZinc

**What operating system (Linux, Windows, ...) and version?**
Linux Kubuntu 20.04

**What did you do?**
1. Run
 `minizinc  -v -s -a -f --solver ortools model-ortools-int-lin_le.mzn`
or the FlatZinc instance
 `minizinc  -v -s -a -f --solver ortools model-ortools-int-lin_le.fzn`

[PPL_Model04.tar.gz](https://github.com/google/or-tools/files/5570899/PPL_Model04.tar.gz)

**What did you expect to see**
Solutions

**What did you see instead?**
```
%%%%   - processing initial model with 1 constraints.
%%%%   - done
 Not supported int_lin_le_imp
*** Check failure stack trace: ***
    @     0x7f5a7ce6dd52  google::LogMessage::Fail()
    @     0x7f5a7ce6dc96  google::LogMessage::SendToLog()
    @     0x7f5a7ce6d5d2  google::LogMessage::Flush()
    @     0x7f5a7ce70c5f  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f5a7d327e49  operations_research::sat::(anonymous namespace)::CpModelProtoWithMapping::FillConstraint()
    @     0x7f5a7d32c8ec  operations_research::sat::SolveFzWithCpModelProto()
    @           0x4030d8  main
    @     0x7f5a7bfa80b3  __libc_start_main
    @           0x403239  _start
    @              (nil)  (unknown)
=====ERROR=====
%%%mzn-stat: nSolutions=0
%%%mzn-stat-end
   Done (overall time 0.19 s).
```

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
Just ran it on master

fz ~/Downloads/PPL_Model04/model-ortools-int-lin_le.fzn 
INFO: Analyzed target //ortools/flatzinc:fz (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //ortools/flatzinc:fz up-to-date:
  bazel-bin/ortools/flatzinc/fz
INFO: Elapsed time: 0.119s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
%% File /Users/lperron/Downloads/PPL_Model04/model-ortools-int-lin_le_sat.fzn parsed in 1 ms
%% Presolve model
%%   - done in 0 ms
%% Model model-ortools-int-lin_le_sat
%%   - int_lin_le_imp: 1
%%   - Satisfaction problem
%% *** Starting translation to CP-SAT
Using flag --fz_int_max for unbounded integer variables.
    actual domain is [-1125899906842624..1125899906842624]
%% Satisfaction model 'model-ortools-int-lin_le_sat':
%% #Variables: 3
%%  - 2 in [-1125899906842624,1125899906842624]
%%  - 1 in [0,1]
%% #kLinear2: 1 (#enforced: 1)
Parameters: log_search_progress: true search_branching: FIXED_SEARCH num_search_workers: 1
Satisfaction model 'model-ortools-int-lin_le_sat':
#Variables: 3
 - 2 in [-1125899906842624,1125899906842624]
 - 1 in [0,1]
#kLinear2: 1 (#enforced: 1)
*** starting model presolve at 0.00s
Merged 0 into 0 cliques.
- 0 affine relations were detected.
- 0 variable equivalence relations were detected.
- rule 'enforcement literal not used' was applied 1 time.
- rule 'presolve: iteration' was applied 1 time.
Satisfaction model 'model-ortools-int-lin_le_sat':
#Variables: 0
*** starting to load the model at 0.00s
*** starting sequential search at 0.00s
Initial num_bool: 0
#1       0.00s   fixed_bools:0/0
CpSolverResponse:
status: OPTIMAL
objective: NA
best_bound: NA
booleans: 0
conflicts: 0
branches: 0
propagations: 0
integer_propagations: 0
restarts: 0
lp_iterations: 0
walltime: 0.004413
usertime: 0.004413
deterministic_time: 0
primal_integral: 0
b = false;
x = array1d(1..2, [-1125899906842624, -1125899906842624]);

----------
==========
%%%mzn-stat: objective=0
%%%mzn-stat: objectiveBound=0
%%%mzn-stat: boolVariables=0
%%%mzn-stat: failures=0
%%%mzn-stat: propagations=0
%%%mzn-stat: solveTime=0.004413

**Comment by glebbelov** [comment]
When using fz directly, even worse - a segfault:

bg45@bg45-Precision-5520:~/downloads/Software/Solvers/or-tools/git$ git pull
Вже актуальне.
bg45@bg45-Precision-5520:~/downloads/Software/Solvers/or-tools/git$ ../../../system/bazelisk-linux-amd64 build -c opt ortools/flatzinc/fz --verbose_failures --sandbox_debug --cxxopt='-std=c++17'
INFO: Analyzed target //ortools/flatzinc:fz (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //ortools/flatzinc:fz up-to-date:
  bazel-bin/ortools/flatzinc/fz
INFO: Elapsed time: 0.193s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action

bg45@bg45-Precision-5520:~/Documents/prj/Monash/2015_PlantLayout/Models/PPL_Model04$ ~/downloads/Software/Solvers/or-tools/git/bin/fz model-ortools-int-lin_le.fzn 
 Not supported int_lin_le_imp
*** Check failure stack trace: ***
    @     0x7ff5a3974d52  google::LogMessage::Fail()
    @     0x7ff5a3974c96  google::LogMessage::SendToLog()
    @     0x7ff5a39745d2  google::LogMessage::Flush()
    @     0x7ff5a3977c5f  google::LogMessageFatal::~LogMessageFatal()
    @     0x7ff5a3e2ee49  operations_research::sat::(anonymous namespace)::CpModelProtoWithMapping::FillConstraint()
    @     0x7ff5a3e338ec  operations_research::sat::SolveFzWithCpModelProto()
    @           0x4030d8  main
    @     0x7ff5a2aaf0b3  __libc_start_main
    @           0x403239  _start
    @              (nil)  (unknown)
Перервано (збережено знімок оперативної пам’яті)

**Comment by lperron** [comment]
on stable or on master ?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
./bin/fz  ~/Downloads/PPL_Model04/model-ortools-int-lin_le.fzn

b = false;

x = array1d(1..2, [-1125899906842624, -1125899906842624]);


----------

==========
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by glebbelov** [comment]
It was an old fz from makefiles (repo_root/bin/fz), just noticed bazel puts the fz elsewhere, thank you

**Comment by glebbelov** [comment]
Resolved
