### ISSUE TITLE
Strange TIMEOUT

### ISSUE THREAD

**Issue by glebbelov** [google/or-tools#2243]
**What version of OR-tools and what language are you using?**
Version: master/stable/v8.0.8

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
fz

**What operating system (Linux, Windows, ...) and version?**
Kubuntu 20.04

**What did you do?**
`bazel-bin/ortools/flatzinc/fz -v -s  model-ortools-int-div-manual.fzn`
[model-ortools-int-div-manual.fzn.tar.gz](https://github.com/google/or-tools/files/5572730/model-ortools-int-div-manual.fzn.tar.gz)

**What did you expect to see**
```
aCostSupport = 0;
----------
==========
```

**What did you see instead?**
```
%% TIMEOUT
%%%mzn-stat: objective=0
%%%mzn-stat: objectiveBound=0
%%%mzn-stat: boolVariables=0
%%%mzn-stat: failures=0
%%%mzn-stat: propagations=0
%%%mzn-stat: solveTime=0
```

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
the full log is:

%% File /Users/lperron/Downloads/model-ortools-int-div-manual.fzn parsed in
0 ms

%% Presolve model

%%   - done in 0 ms

%% Model model-ortools-int-div-manual

%%   - int_le: 1

%%   - int_lin_le: 1

%%   - Minimization problem

%% *** Starting translation to CP-SAT

Using flag --fz_int_max for unbounded integer variables.

    actual domain is [-1125899906842624..1125899906842624]

%% Optimization model 'model-ortools-int-div-manual':

%% #Variables: 3 (1 in objective)

%%  - 1 in [-1125899906842624,1125899906842624]

%%  - 1 in [0,1000000000]

%%  - 1 constants in {0}

%% #kLinear1: 1

%% #kLinear2: 1

Parameters: log_search_progress: true search_branching: FIXED_SEARCH
num_search_workers: 1

Possible integer overflow in constraint: name: "int_lin_le"

linear {

  vars: 0

  vars: 2

  coeffs: -1

  coeffs: 42240

  domain: -9223372036854775808

  domain: 0

}

CpSolverResponse:

status: MODEL_INVALID

objective: 0

best_bound: 0

booleans: 0

conflicts: 0

branches: 0

propagations: 0

integer_propagations: 0

restarts: 0

lp_iterations: 0

walltime: 0

usertime: 0

deterministic_time: 0

primal_integral: 0


We are very conservative with overflows, and the definition of 'int' is not
clear.

I used to create open domains as int32min..int32max. Recently we moved to
-2^50, 2^50.

And 42000 is > 2^15, which overflows.



To make it work, you need to specify a lower diameter with the --fz_int_max
parameter.


The TIMEOUT is a bad output. We will fix it.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
I have pushed a small modification.
It now outputs MODEL_INVALID instead of TIMEOUT.

**Comment by glebbelov** [comment]
Helpful, thank you.

**Comment by glebbelov** [comment]
A small remark about the message: saying at least OVERFLOW would be much more meaningful, even better printing the constraint in full (so when the user compiles with --keep-paths, the path anno is printed too, or some other way to find the reason)

**Comment by lperron** [comment]
Good idea. Done.
