### ISSUE TITLE
CP-SAT: Boolean constraints

### ISSUE THREAD

**Issue by novan-p-simanjuntak** [google/or-tools#2246]
I am using python for CP-SAT

I have the following constraints:

1. x1 = a and b
2. x2 = c and d
3. x3 = e and f
4. only 2 of 3 variables (x1, x2, and x3) can be **true**.

For constraint no 4, I plan to use the following code.

```
x1 = model.NewBoolVar('x1')
y2 = model.NewBoolVar('x2')
z3 = model.NewBoolVar('x3')
model.Add(x1 + x2 + x3 == 2) 
```

I want to collect possible solutions for **a, b, c, d, e, f**.
I don't know how to implement constraints 1, 2 and 3. 
Any idea to solve it?

Thank you.

**Comment by lperron** [comment]
Please use the mailing list.

**Comment by novan-p-simanjuntak** [comment]
Ok. I've requested to join the mailing list.
