### ISSUE TITLE
The automatic integration between Gurobi and OR-Tools is not working when Gurobi was installed through conda

### ISSUE THREAD

**Issue by RichardOberdieck** [google/or-tools#2273]
**What version of OR-tools and what language are you using?**
Version: ortools-8.0.8283
Language: Python with conda

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Gurobi

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
Steps to reproduce the behavior (I think):
1. Install Gurobi through conda
2. Uninstall the conda package and install the full version of Gurobi
3. Install OR-Tools
4. Run [the code specified on your dev page](https://developers.google.com/optimization/mip/integer_opt)

**What did you expect to see**
This works, i.e. it returns `0`.

**What did you see instead?**

```
W1204 16:11:16.681918 17484 linear_solver.cc:608] Support for gurobi not linked in, or the license was not found.
```

Note that the license file was set up correctly using `GRB_LICENSE_FILE`, and `gurobi_cl` runs fine by itself. Therefore Gurobi was installed correctly.

**Anything else we should know about your project / environment**
I am reporting this for a client (I am a Gurobi employee).

**Comment by lperron** [comment]
You need to setup GUROBI_HOME to point to the install directory.

**Comment by RichardOberdieck** [comment]
This was done, it was set to `C:\gurobi910\win64`. Do you expect it to be in the `bin` or `lib` folder maybe?

**Comment by lperron** [comment]
But at the time only 9.0 was supported.
The next release (hopefully this week) will support 9.1
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by RichardOberdieck** [comment]
Can it be that the problem is that you have hard-coded the dll location (line 209 in the file you sent)?

```
\\bin\\gurobi90.dll
```

The customer is using Gurobi version 9.1.

**Comment by lperron** [comment]
This is fixed in master. You can also set the full path to the DLL.

Le lun. 7 déc. 2020 à 16:08, RichardOberdieck <notifications@github.com> a
écrit :

**Comment by RichardOberdieck** [comment]
Ok, thanks.

By setting the full path to the DLL you mean setting `GUROBI_HOME` to point directly to the DLL (so `C:\gurobi910\win64\bin\gurobi91.dll`)?

**Comment by lperron** [comment]
No, use
http://google.github.io/or-tools/cpp_linear/classoperations__research_1_1_m_p_solver.html#a0a13ceaa35a35454f5a7ba6cfbe6202a

Should be available in all languages.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 7 déc. 2020 à 16:16, RichardOberdieck <notifications@github.com> a
écrit :

**Comment by RichardOberdieck** [comment]
Perfect, thanks! And thank you for responding this quickly!
