### ISSUE TITLE
last decision or backtrack trail index

### ISSUE THREAD

**Issue by rybickibartek** [google/or-tools#2277]
**What version of OR-tools and what language are you using?**
Version: v8.0.8283
Language: Python 3.7.5

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
macOS Catalina 10.15.6 

**Problem description**
I have built a model, quite big it think (weight of file, saved with ExportToFile, is 122Mb). I try to solve it and some time it failures. Based on stack trace I do not have an idea what is a reason of such behaviour?

File saved with ExportToFile is proto? If not how I can save it to proto? 
How can I load model from proto? [Sorry I was not able to find this information]

**What are next steps?**
What I should do to avoid this behaviour in the future?

**Stack trace**
Check failed: trail_->Index() > last_decision_or_backtrack_trail_index_ (823 vs. 823) 
*** Check failure stack trace: ***
    @        0x112207e5f  google::LogMessageFatal::~LogMessageFatal()
    @        0x112203fb9  google::LogMessageFatal::~LogMessageFatal()
    @        0x111e9f6d5  operations_research::sat::SatSolver::PropagateAndStopAfterOneConflictResolution()
    @        0x111e9e5a8  operations_research::sat::SatSolver::EnqueueDecisionAndBackjumpOnConflict()
    @        0x111dfdce9  operations_research::sat::SolveIntegerProblem()
    @        0x111e4f967  operations_research::sat::CoreBasedOptimizer::Optimize()
    @        0x111d5648a  operations_research::sat::(anonymous namespace)::SolveLoadedCpModel()
    @        0x111d5fc19  _ZNSt3__110__function6__funcIZN19operations_research3sat12_GLOBAL__N_117FullProblemSolver12GenerateTaskExEUlvE_NS_9allocatorIS6_EEFvvEEclEv
    @        0x111ec1b21  std::__1::__function::__func<>::operator()()
    @        0x111b29a96  operations_research::RunWorker()
    @        0x111b2a68c  std::__1::__thread_proxy<>()
    @     0x7fff6cdc0109  _pthread_start
Abort trap: 6

**Anything else we should know about your project / environment**
I have impression that it is not a deterministic behaviour, but I am not sure (there is some randomness in a process of model building - it may differ between consecutive executions).

**Solver parameters**

solver = cp_model.CpSolver()

solver.parameters.log_search_progress = True
solver.parameters.num_search_workers = multiprocessing.cpu_count()

solver.parameters.use_pb_resolution = True
solver.parameters.optimize_with_core = True
solver.parameters.restart_period = 100

solver.parameters.share_objective_bounds = True
solver.parameters.share_level_zero_bounds = True

**Comment by lperron** [comment]
1) export to file writes the proto.
2) use_pb_resolution has not been tested for a long time. Does it crash
without it ?
3) optimize_with_core is set automatically in parallel, remove
4) restart_period is also set, remove
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 9 déc. 2020 à 08:46, rybickibartek <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
PS: you can compress the file, it will help.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by rybickibartek** [comment]
Thanks for quick response. 

I commented out use_pb_resolution, optimize_with_core and restart_period. 
I will let you know if it will happen again.

[problematic_model.txt.zip](https://github.com/google/or-tools/files/5664752/problematic_model.txt.zip)

Can I load somehow model from proto file to run it?

**Comment by lperron** [comment]
examples/cpp/sat_runner.cc

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 9 déc. 2020 à 10:16, rybickibartek <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
Anyway, it seems to solve easily with 8 workers, and no special parameters

status: OPTIMAL

objective: 6017

best_bound: 6017

booleans: 8667

conflicts: 35

branches: 20353

propagations: 143536

integer_propagations: 234162

restarts: 17324

lp_iterations: 39626

walltime: 39.6875

usertime: 39.6875

deterministic_time: 83.9251

primal_integral: 152.753


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by rybickibartek** [comment]
after removing parameters I also do not see any problems now. In the case of similar problems in the future I wil let you know.
Thanks for help! ;-)

**Comment by lperron** [comment]
The pb_resolution has not been tested outside of pure maxsat problems. So
don't use it.

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 9 déc. 2020 à 10:59, rybickibartek <notifications@github.com> a
écrit :
