### ISSUE TITLE
Routing : Savings algorithm no solutions

### ISSUE THREAD

**Issue by atitawat-pol** [google/or-tools#2279]
**What version of OR-tools and what language are you using?**
Version: ortools==8.1.8487
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing
**What operating system (Linux, Windows, ...) and version?**
Linux(google-colab), windows(10 64bit)
**What did you do?**
1. Copy CVRP example from https://developers.google.com/optimization/routing/cvrp#entire_program
2. Change search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.**PATH_CHEAPEST_ARC**)  => **SAVINGS**
3. Why there are not any solution found

**What did you expect to see**
I want to solve CVRP and CVRPTW problem with Savings algorithm.
Could someone share me an example code of CVRP, CVRPTW with SAVINGS algorithm in python please.
**What did you see instead?**
Nothing.
Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by Mizux** [comment]
First strategy are just heuristic with few back tracking I.e. if it doesn't found a solution "easily" you're dead.

That's why it's always good to test few first strategy to find the one which best suite your model...

**Comment by atitawat-pol** [comment]
> First strategy are just heuristic with few back tracking I.e. if it doesn't found a solution "easily" you're dead.
> 
> That's why it's always good to test few first strategy to find the one which best suite your model...

My advisor want me to solve problem with savings algorithm because its easily explain.

Would you please give me an solution founded example python code.

**Comment by Soenk-89** [comment]
Hey guys :) 
I have the same CVRP problem like atitawat-pol. I use the current OR tools version and Python on Spyder (ver. 3.8) on Win10 64bit.

So I also wanna try to solve my CVRP with SAVINGS as Routing Option but unfortunately it's not working   
- Solver Status 2: ROUTING_FAIL: No solution found to the problem.

Other options like SWEEP, AUTOMATIC, PATH_CHEAPEST_ARC working but I have no clue why exactly SAVINGS not. I mean it's one of the most common algorithm. At the end I used PATH_CHEAPEST_ARC but I actually have to use SAVINGS..

Any kinda help would be much appreciated! :))
Thanks in advance

**Comment by Soenk-89** [comment]
> > First strategy are just heuristic with few back tracking I.e. if it doesn't found a solution "easily" you're dead.
> > That's why it's always good to test few first strategy to find the one which best suite your model...
> 
> My advisor want me to solve problem with savings algorithm because its easily explain.
> 
> Would you please give me an solution founded example python code.

Have you found a solution for your issue?  I'm also looking for a way to use SAVINGS
