### ISSUE TITLE
ModuleNotFoundError: No module named 'ortools'

### ISSUE THREAD

**Issue by mariaeileen** [google/or-tools#2281]
Hi, 
I have succesfully downloaded or-tools using homebrew but cannot seem to function when I run my script as I get the error message  _ModuleNotFoundError: No module named 'ortools'_. I have both Python 3.8 and Python 3.7 downloaded and have installed or-tools for both versions as I've read that several others have had problems with or-tools using python 3.8- However, I don't seem to be able to run it with 3.7 either, so does anyone know if its possible at all to use or-tools with Mojave? Might my or-tools version and homebrew version not be compatible with each other? 
**From terminal, showing I have succesfully installed or-tools for Python 3.7:**
$ python -m pip show ortools
Name: ortools
Version: 8.1.8487
Summary: Google OR-Tools python libraries and modules
Home-page: https://developers.google.com/optimization/
Author: Google LLC
Author-email: or-tools@google.com
License: Apache 2.0
Location: /Users/xxx/opt/anaconda3/lib/python3.7/site-packages

**Operating system**
macOS Mojave, 10.14.6
Homebrew version: 2.6.1

**Comment by stradivari96** [comment]
How are you running your script? can you try this?
```
python -c "import ortools; print(ortools.__version__)"
```

**Comment by mariaeileen** [comment]
Hi, 
I'm using IDLE with python version 3.7. 
The output from the command you sent gives "8.1.8487" as an output in terminal. 
Sorry, should have included my ortools version to be 8.1.8487 earlier.

**Comment by mariaeileen** [comment]
and my command that gives the error is : from ortools.linear_solver import pywraplp

**Comment by stradivari96** [comment]
So it looks like you **can** actually import ortools, but in IDLE you are in another python environment

**Comment by mariaeileen** [comment]
Yes, it looks like its imported but I still receive the error message for both python 3.7 and python 3.8 even though I have installed ortools for both versions.

**Comment by stradivari96** [comment]
IDLE is probably using another python instalation, try something like https://www.honchosearch.com/blog/seo/install-python-modulespackage-using-idle-mac/

**Comment by Mizux** [comment]
`Location: /Users/xxx/opt/anaconda3/lib/python3.7/site-packages` seems you install it in an anaconda env not sure IDLE will use it.
As @stradivari96 point out you can figure out which site package is use running
```python
import sys
print(f"{sys.executable}")

import sysconfig
print(f"{sysconfig.get_path('scripts')}")
```

**Comment by mariaeileen** [comment]
Thanks! That helped a lot! :)

**Comment by rmahipal** [comment]
I am getting same problem and I am using PyCharm. Can you help me
