### ISSUE TITLE
[dotnet::routing] RoutingModel::VehicleIndex type issue

### ISSUE THREAD

**Issue by mwpowellhtx** [google/or-tools#2282]
In the `Google.OrTools` `7.5` package version...

Much of dealing with the [_Routing Model_](https://developers.google.com/optimization/reference/constraint_solver/routing/RoutingModel), _Dimensions_, etc, is dancing between `NodeToIndex` and `IndexToNode`, right.

In the case of `VehicleIndex`, when we talk about _Node_, we think of `int`, correct? When we think about `Index`, with respect to `RoutingModel`, `RoutingIndexManager`, etc, we think of `long`, correct?

However, the signature is [`VehicleIndex(int index)`](https://github.com/google/or-tools/blob/v8.0/ortools/constraint_solver/routing.h#L1164), not `VehicleIndex(long index)`.

So... assuming the verbiage is correct and aligned through and through, we need to treat it like a `long index`, do we not?

Maybe this was updated in a recent version?

**Comment by lperron** [comment]
VehicleIndex is in terms of vehicles, not nodes.
So int.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 14 déc. 2020 à 18:33, Michael W Powell <notifications@github.com> a
écrit :

**Comment by mwpowellhtx** [comment]
Not sure I follow the example then... pickup and delivery indexes are landing as `long`... But this is an error.

```CSharp
Solver solver = routing.solver();
for (int i = 0; i < data.PickupsDeliveries.GetLength(0); i++)
{
    long pickupIndex = manager.NodeToIndex(data.PickupsDeliveries[i][0]);
    long deliveryIndex = manager.NodeToIndex(data.PickupsDeliveries[i][1]);
    routing.AddPickupAndDelivery(pickupIndex, deliveryIndex);
    solver.Add(solver.MakeEquality(routing.VehicleVar(pickupIndex), routing.VehicleVar(deliveryIndex)));
    //                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    solver.Add(solver.MakeLessOrEqual(distanceDimension.CumulVar(pickupIndex), distanceDimension.CumulVar(deliveryIndex)));
}
```

Am I reading that incorrectly?

**Comment by Mizux** [comment]
In C++ we have:
* (solver/user vehicle index) call VehicleIndex type: int
* (solver internal node index) call Index type: int64 
* (user node index) call NodeIndex type: int

Often in the code user node index are simply call "Node", which means `NodeToIndex()` will convert **from** user node index (i.e. int) **to** solver internal node index (I.e. int64) aka `long` in .Net.
so this method could be call "Convert_from_UserNodeIndex_to_SolverInternalNodeIndex"

**Comment by lperron** [comment]
vehicleVar is the vehicle used at a given node, so parameter is nodeIndex.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 14 déc. 2020 à 18:50, Michael W Powell <notifications@github.com> a
écrit :

**Comment by mwpowellhtx** [comment]
Yes, I am fairly clear on the purpose of the alignment going on there. What I am not as clear on is the apparent type confusion, again, assuming nodes/vehicles, the model/domain translation to/from node/index, throughout, and so on.

**Comment by mwpowellhtx** [comment]
So... If it is the _"vehicle used at the given node (index)"_, then it should be,

```CSharp
int VehicleIndex(long index) { ... }
```

Not,

```CSharp
int VehicleIndex(int index) { ... }
```

**Comment by mwpowellhtx** [comment]
And along similar lines, more confusion with,

```CSharp
IntVar VehicleVar(long index) { ... }
```

Which seems to agree along the general vehicle/node, node/index concerns, i.e. `long index`.

**Comment by mwpowellhtx** [comment]
So, in summary, if we're saying should be `int vehicle` in vehicle terms, then this is the best I can come up with, confusion between `VehicleIndex(int index)`, and apparently also `VehicleVar(long index)`.

```CSharp
void OnAddPickupAndDelivery(RoutingModel model, Solver solver)
{
    model.AddPickupAndDelivery(pickupIndex, deliveryIndex);

    Constraint GetAlignedVehicleConstraint((int pickup, int delivery) vehicle) => solver.MakeEquality(
        // Expecting long index, but "accepts" int:
        model.VehicleVar(vehicle.pickup), model.VehicleVar(vehicle.delivery)
    //  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    );

    Constraint GetAlignedDimensionConstraint(RoutingDimension routingDim) => solver.MakeLessOrEqual(
        routingDim.CumulVar(pickupIndex), routingDim.CumulVar(deliveryIndex)
    );

    this.AddConstraints(
        GetAlignedVehicleConstraint((model.VehicleIndex((int)pickupIndex), model.VehicleIndex((int)deliveryIndex)))
        //                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        , GetAlignedDimensionConstraint(this.MutableDimension)
    );
}

OnAddPickupAndDelivery(this.Context.Model, this.Context.Solver);
```

**Comment by mwpowellhtx** [comment]
Maybe it should be:

```CSharp
int VehicleIndex(int node) { ... }
```

For starters. i.e. a confusion not only in type, but possibly a confusion in verbiage. Because words matter, right.

**Comment by Mizux** [comment]
I think it should be `int VehicleIndex(int64 index)`

ref:
https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/ortools/constraint_solver/routing.h#L1166-L1177

**Comment by mwpowellhtx** [comment]
@Mizux Sounds good to me. So, in the mean time we can do `(int)index`, of course, we miss some range of indices contrasting `int` with `long` in the interim. As long as the issue is known and/or a patch is on the way.

**Comment by mwpowellhtx** [comment]
@lperron @Mizux Okay, I think I got it sorted out. Will run it through my unit testing to verify the solution more or less agrees.
