### ISSUE TITLE
Many different values of optimal solution

### ISSUE THREAD

**Issue by rybickibartek** [google/or-tools#2283]
**What version of OR-tools and what language are you using?**
Version: 8.0.8283
Language: Python 3.7.5

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
macOS Catalina 10.15.6

**What did you do?**
I run solver on my model many times in a single program and it gives a number of solutions with **different** objective function values. The problem is that all of them are declared to be OPTIMAL.

Objective function values which I get from solver
[5997, 5993, 5997, 5997, 5999, 6005, 5993]

**Model proto**
[model_6000.txt.zip](https://github.com/google/or-tools/files/5694192/model_6000.txt.zip)

**What did you expect to see**
Maybe different optimal solutions, but with the same value of objective function.

**Anything else we should know about your project / environment**
In my experiment I load model from pickled file, but it happen also in a scenario in which I run many separated executions of the same program which build a model and run solver. (In this scenario model is not pickled)

**Code of my program**

```
import pickle as pkl
from ortools.sat.python import cp_model
import multiprocessing

solver = cp_model.CpSolver()

solver.parameters.log_search_progress = True
solver.parameters.num_search_workers = multiprocessing.cpu_count()
solver.parameters.share_objective_bounds = True
solver.parameters.share_level_zero_bounds = True

model = pkl.load(open('model_6000.pkl', 'rb'))
for _ in range(7):
     solver.Solve(model)
```

**Comment by lperron** [comment]
Thanks for the bug report.

I can reproduce it on master.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 15 déc. 2020 à 09:03, rybickibartek <notifications@github.com> a
écrit :

**Comment by rybickibartek** [comment]
Sure thing, it is also my business to have or-tools working correctly ;-)
Please let me know if you have any way to fix this bug.

**Comment by lperron** [comment]
We will.

These tend to be very complex.

Note that all solutions are correct (they are checked).

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 15 déc. 2020 à 10:23, rybickibartek <notifications@github.com> a
écrit :

**Comment by rybickibartek** [comment]
I have one more question related to this bug. I know some feasible solution to this model. Is it guaranteed that if I will 'suggest' it with AddHint method then solver will NOT declare that model is infeasible and will find some solution? Or maybe I cannot hope on this?

**Comment by lperron** [comment]
If you have a feasible solution, then the solver should never declare the
problem as unfeasible.
And the solver will try to reproduce that solution.

I am not sure you will always find it in parallel.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 16 déc. 2020 à 13:39, rybickibartek <notifications@github.com> a
écrit :

**Comment by bolt25** [comment]
Can you, if possible mention why the problem was occurring and how was it fixed? I'm facing a very similar issue in my project. I suspect the high volume of the data might be an issue because when I run it on a smaller subset of variables, I get a reproducible and optimal solution every time.

**Comment by bolt25** [comment]
Oh, I see. So given the bug is fixed do you have any other sources from where this might resurface? Because when I run the problem on a smaller set of data, everything works just fine and quickly. The optimal solution drops when I run the model on the entire data and it takes more than 30-40 mins to give any answer.

**Comment by lperron** [comment]
This has nothing to do with the bug.

The bug was that the same problem returned OPTIMAL or INFEASIBLE, depending on the mood.

Your problem is just that this is a NP-Hard problem, so bigger means exponentially harder.

**Comment by bolt25** [comment]
So to solve this, either I need to introduce more constraints or lower my search space?

**Comment by bolt25** [comment]
> So to solve this, either I need to introduce more constraints or lower my search space?

Because on every run I check the optimizer status and then print the objective value only if the status is optimal. Still, on every run, I get different solutions when I use the entire data.
