### ISSUE TITLE
Improve Maven jar files

### ISSUE THREAD

**Issue by dkkopp** [google/or-tools#2284]
**What language and solver does this apply to?**
Java

**Describe the problem you are trying to solve.**
The project just added Mavenized jar files, but they are specific to each OS. This is not ideal. A better approach is the one taken by the OpenJFX project where the Maven classifier is used to automatically select the proper OS specific jar file.

**Describe the solution you'd like**
The ideal solution is copy the approach taken by the OpenJFX project. This would allow for the resulting jar files to be hosted by Maven Central and would make Java development using the or-tools much simpler.

**Describe alternatives you've considered**
I have made a simple Ant project that massages the existing build to produce what I am talking about. It would be great if the appropriate changes could be made to the existing build system to produce these jars as part of the build process.

[antproject.zip](https://github.com/google/or-tools/files/5698452/antproject.zip)

**Comment by Mizux** [comment]
currently we have one jar per os to ship os dependent libraries then a meta package (per os) containing  the java code and the loader.
BUT before merging the 3 meta packages we must be sure the SWIG code generated is identical on the three platforms...
if test is good I will update the pom.xml template to depends on the three native dependent packages in order to only have one platform agnostic package on top
ref: https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/ortools/java/pom-local.xml.in#L58-L64

**Comment by Mizux** [comment]
in your build.xml, I can see
```
<!-- Use the windows ortools-java jar file as our one true java jar file -->
```
How do you know linux, macos and windows SWIG generated java file are identical and compatible ?

**Comment by mknarula** [comment]
I followed the readme file :
# Java
cd examples/java/LinearProgramming
mvn compile
mvn exec:java

getting this error while running exec 
win32-x86-64\jniortools.dll: Can't find dependent libraries
 at java.lang.ClassLoader$NativeLibrary.load0 (Native Method)
    at java.lang.ClassLoader$NativeLibrary.load (ClassLoader.java:2440)
    at java.lang.ClassLoader$NativeLibrary.loadLibrary (ClassLoader.java:2497)
    at java.lang.ClassLoader.loadLibrary0 (ClassLoader.java:2694)
    at java.lang.ClassLoader.loadLibrary (ClassLoader.java:2627)
    at java.lang.Runtime.load0 (Runtime.java:744)
    at java.lang.System.load (System.java:1870)
    at com.google.ortools.Loader.loadNativeLibraries (Loader.java:86)
    at com.google.ortools.java.LinearProgramming.main (LinearProgramming.java:112)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:830)

**Comment by Mizux** [comment]
note for myself: Try to see if we can use activation... http://maven.apache.org/pom.html#activation
