### ISSUE TITLE
CHECK-fail on my .fzn input

### ISSUE THREAD

**Issue by agentydragon** [google/or-tools#2288]
**What version of OR-tools and what language are you using?**
Version: Git commit 8d19323faf51f2f004e4de6c1b32a74001fbc7c1
Language: Flatzinc solver (via Minizinc)

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Flatzinc solver

**What operating system (Linux, Windows, ...) and version?**
Linux, Pop! OS 20.10

**What did you do?**
1. Pass the following file as input to flatzinc interpreter: https://pastebin.ubuntu.com/p/YhrNyXVySf/
2. See crash:

```
Check failed: var != nullptr
*** Check failure stack trace: ***
    @     0x55f2b87c292a  google::LogMessage::Fail()
    @     0x55f2b87c2865  google::LogMessage::SendToLog()
    @     0x55f2b87c2180  google::LogMessage::Flush()
    @     0x55f2b87c52bc  google::LogMessageFatal::~LogMessageFatal()
    @     0x55f2b80983e7  operations_research::sat::(anonymous namespace)::CpModelProtoWithMapping::LookupVars()
    @     0x55f2b8098d3d  operations_research::sat::(anonymous namespace)::CpModelProtoWithMapping::FillLinearConstraintWithGivenDomain()
    @     0x55f2b809a044  operations_research::sat::(anonymous namespace)::CpModelProtoWithMapping::FillConstraint()
    @     0x55f2b80a16d9  operations_research::sat::SolveFzWithCpModelProto()
    @     0x55f2b8093d4a  main
    @     0x7f58e6fc4cb2  __libc_start_main
    @     0x55f2b8092c2e  _start
    @              (nil)  (unknown)
```

**What did you expect to see**

The passed .fzn should produce a satisfying model.

**What did you see instead?**

See backtrace above.

**Anything else we should know about your project / environment**

I've applied this patch on top of Minizinc because of another bug (in libminizinc): https://github.com/MiniZinc/libminizinc/pull/444

It's possible my patch might be faulty and might be producing invalid .fzn.

If my patch is wrong and this is an issue with the .fzn file being invalid, it would be nice to get a better error message from the or-tools Flatzinc solver explaining the problem, rather than a CHECK-fail that doesn't explain what's wrong in the Flatzinc.

However, my model does work with the Gecode Flatzinc solver. The 2 solvers might have different implemented constraints, so their Flatzinc might have some difference that might contain the issue with the or-tools Flatzinc solver. But I interpret it as some evidence towards there being an issue with the or-tools solver (as opposed to an issue with my minizinc patch).

It would be nice to get a better diagnostic message from the error the CHECK-fail detects. And if the error actually is an error in the or-tools Flatzinc solver (and not broken .fzn generation caused by an error in my MInizinc patch), it would be good to get it fixed.

I can share the Minizinc input that generates the failing Flatzinc if it would help. However, recent versions of Minizinc will crash on the input due to https://github.com/MiniZinc/libminizinc/issues/443 (which my Minizinc patch tries to fix).

**Comment by lperron** [comment]
Have you generated the fzn file with the or-tools mzn library?

**Comment by lperron** [comment]
Thanks for the bug report.
I pushed the fix.

**Comment by agentydragon** [comment]
Thanks for the quick fix. Looks like there's at least 1 more crash somewhere else, I'll report it on another bug.
