### ISSUE TITLE
Python install fails because of error in setup.py

### ISSUE THREAD

**Issue by skosch** [google/or-tools#229]
Just experienced the following error:
```
sebastian@wreck ~/p/c/o/ortools_examples> python setup.py install --user
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    make sure you use \"""" + sys.executable + """\" during the installation"""
NameError: name 'sys' is not defined
```
Changing it from `sys.executable` to `executable` made it run without a hitch. Not sure if that's what it should be, so I'll refrain from opening a PR. Any thoughts?

**Comment by dlahlou** [comment]
Hello skosch,

Thank you for the report. I uploaded a new archive with the fix.

Regards,

Driss
