### ISSUE TITLE
Error compiling cplex_interface.cc using OR-Tools 8.1

### ISSUE THREAD

**Issue by toniwickert** [google/or-tools#2296]
**What version of OR-tools and what language are you using?**
Version: 8.1 (last stable release)
Language: C++/Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Trying to compile OR-Tools with Cplex 12.10 support enable in makelocalfile.

**What operating system (Linux, Windows, ...) and version?**
Linux Mint 20.

**What did you do?**
1. Install the required packages using: https://developers.google.com/optimization/install/java/source_linux#ubuntu-20.04-lts
2. Download the source-code https://github.com/google/or-tools/archive/v8.1.zip
3. Extract to a folder without spaces
4. Go to the root folder
5. make third_party (compiles without errors)
6. Open the Makefile.local and define the Cplex path: UNIX_CPLEX_DIR = /home/your_user/CPLEX
7. make third_party (compiles without errors)
8. make java or make cc return the following error

Note that the same steps work fine using 8.0 release.

make cc
PROTOBUF: found
PROTOC: found
ABSEIL-CPP: found
SCIP: found
COINUTILS: found
OSI: found
CLP: found
CGL: found
CBC: found
CPLEX: found
GLPK: not found
XPRESS: not found
touch dependencies/check.log
g++ -fPIC -std=c++17 -fwrapv -O4 -DNDEBUG -I. -Iortools/gen -Wno-deprecated -DUSE_GLOP -DUSE_BOP  -I/home/toni/ibm3/cplex/include -DUSE_CPLEX  -I/home/toni/or-tools/or-tools-8.1/dependencies/install/include -I/home/toni/or-tools/or-tools-8.1/dependencies/install/include -I/home/toni/or-tools/or-tools-8.1/dependencies/install/include -I/home/toni/or-tools/or-tools-8.1/dependencies/install/include/coin -I/home/toni/or-tools/or-tools-8.1/dependencies/install/include -I/home/toni/or-tools/or-tools-8.1/dependencies/install/include/coin -I/home/toni/or-tools/or-tools-8.1/dependencies/install/include -I/home/toni/or-tools/or-tools-8.1/dependencies/install/include/coin -DUSE_CLP -I/home/toni/or-tools/or-tools-8.1/dependencies/install/include -I/home/toni/or-tools/or-tools-8.1/dependencies/install/include/coin -I/home/toni/or-tools/or-tools-8.1/dependencies/install/include -I/home/toni/or-tools/or-tools-8.1/dependencies/install/include/coin -DUSE_CBC -I/home/toni/or-tools/or-tools-8.1/dependencies/install/include -DUSE_SCIP -DNO_CONFIG_HEADER -DOR_TOOLS_MAJOR=8 -DOR_TOOLS_MINOR=1 -c ./ortools/linear_solver/cplex_interface.cc -o objs/linear_solver/cplex_interface.o
./ortools/linear_solver/cplex_interface.cc: In member function ‘virtual double operations_research::CplexInterface::best_objective_bound() const’:
./ortools/linear_solver/cplex_interface.cc:619:44: error: ‘CheckBestObjectiveBoundExists’ was not declared in this scope
  619 |     if (!CheckSolutionIsSynchronized() || !CheckBestObjectiveBoundExists())
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./ortools/linear_solver/cplex_interface.cc:622:14: error: ‘trivial_worst_objective_bound’ was not declared in this scope
  622 |       return trivial_worst_objective_bound();
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./ortools/linear_solver/cplex_interface.cc:633:12: error: ‘trivial_worst_objective_bound’ was not declared in this scope
  633 |     return trivial_worst_objective_bound();
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Mizux** [comment]
CPLEX is community supported, feel free to send us a patch !
https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/ortools/linear_solver/cplex_interface.cc#L616-L635

I'll investigate if `trivial_worst_objective_bound()` and `CheckBestObjectiveBoundExists()` are not base methods which has been refactor recently (and cplex_interface has not been updated accordingly)

**Comment by Mizux** [comment]
seems to comes from https://github.com/google/or-tools/commit/a2dc7e9a8efe6d4606a774e21279db36be2e68f0
cplex and xpress interface may have been impacted (i.e. not updated accordingly)

**Comment by Mizux** [comment]
@toniwickert May you test against master branch to see if it works ?
Thx !

**Comment by toniwickert** [comment]
@Mizux I've tested using the master branch and it worked fine.
Thanks for the fast answer!
