### ISSUE TITLE
Unexpected solver status: Abnormal

### ISSUE THREAD

**Issue by cbtum** [google/or-tools#2297]
**What version of OR-tools and what language are you using?**
Version: 8.0.8283, 8.1.8487
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
GLOP

**What operating system (Linux, Windows, ...) and version?**
MacOS

**What did you do?**
Created a very simple MIP with one soft constraint:
```java
MPSolver solver = MPSolver.createSolver("GLOP");
MPVariable x = solver.makeBoolVar("x");
MPVariable y = solver.makeBoolVar("y");
MPVariable delta = solver.makeNumVar(0, Double.MAX_VALUE, "delta");

MPConstraint c0 = solver.makeConstraint(4, Double.MAX_VALUE, "c0");
c0.setCoefficient(x, -10);
c0.setCoefficient(y, 10);
c0.setCoefficient(delta, 1);

MPObjective objective = solver.objective();
objective.setCoefficient(delta, 1);
objective.setMinimization();

MPSolver.ResultStatus resultStatus = solver.solve();
System.out.println(resultStatus.toString());
System.out.println(solver.exportModelAsLpFormat());
```

**What did you expect to see**
Optimal solution with x=0, y=1, objective value = 0

**What did you see instead?**
Solver responded ABNORMAL
```
ABNORMAL
\ Generated by MPModelProtoExporter
\   Name             : 
\   Format           : Free
\   Constraints      : 1
\   Variables        : 3
\     Binary         : 2
\     Integer        : 0
\     Continuous     : 1
Minimize
 Obj: +1 delta 
Subject to
 c0_rhs: -10 x +10 y +1 delta  <= 1.79769e+308
 c0_lhs: -10 x +10 y +1 delta  >= 4
Bounds
 0 <= x <= 1
 0 <= y <= 1
 0 <= delta <= 1.79769e+308
Binaries
 x
 y
End
```

**Anything else we should know about your project / environment**
Setting the coefficients of x and y to -1 and +1, leads to an optimal model.

**Comment by cbtum** [comment]
PS: After I saw https://github.com/google/or-tools/issues/1986#issue-608700688, I also tried 8.1.8487 which also shows the behavior described above.

Additional observations:
- It helps to restrict delta, e.g. to 1e+09.
- It does NOT help to initialize c0 without upper bound

**Comment by lperron** [comment]
Can you to replace max_double by +infinity, and min_double by -infinity?

**Comment by cbtum** [comment]
Indeed, replacing the upper bound of c0 as well as the upper bound of delta by Double.POSITIVE_INFINITY also solves the problem.
