### ISSUE TITLE
[mincostflow] Feature request : Allow to equally split same cost flows

### ISSUE THREAD

**Issue by olivierdalang** [google/or-tools#2299]
**What language and solver does this apply to?**
All languages, MinCostFlow Solver

**Describe the problem you are trying to solve.**
When computing MinCostFlow, it can happen that two paths have the exact same cost. Currently, the flow takes one of those path, the other one is unused.
For certains use cases, it would be nice to have the flow split evenly between all possible equivalent paths.

**Describe the solution you'd like**
A parameter (defaulting to false for backwards compatibility) allowing to change that behaviour, making flows split evenly between all same-cost paths.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by lperron** [comment]
This is impossible. It would change the complexity from polynomial to
np-complete.

Please use CP-SAT or a MIP solver.

Le jeu. 24 déc. 2020 à 12:47, Olivier Dalang <notifications@github.com> a
écrit :
