### ISSUE TITLE
VRP not taking into account distances between starting point and ending point for cases when there are no intermediates

### ISSUE THREAD

**Issue by dleybz** [google/or-tools#2300]
**What version of OR-tools and what language are you using?**
Version: ortools-8.1.8487
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing solver

**What operating system (Linux, Windows, ...) and version?**
Colab, so Ubuntu https://colab.research.google.com/drive/16pBJQePbqkz3QFV54L4NIkOn1kwpuRrj#scrollTo=z5FZ_n_ieQfV

**What did you do?**
Create an example VRP program that sets start and end locations, such as in here https://developers.google.com/optimization/routing/routing_tasks#setting-start-and-end-locations-for-routes
Generate a route

**What did you expect to see**
I expected routing to take into account the distance from the start point to the end point

**What did you see instead?**
Routing only took into account the distance of segments:
Route for vehicle 0:
0, 1
Distance of the route: 0m

Route for vehicle 1:
0, 2
Distance of the route: 0m

Route for vehicle 2:
0, 7, 8, 3
Distance of the route: 20989m

Route for vehicle 3:
0, 4
Distance of the route: 0m

Route for vehicle 4:
0, 5
Distance of the route: 0m

Route for vehicle 5:
0, 9, 6
Distance of the route: 28818m

For the following distance matrix:
[[0, 4365, 6177, 10088, 16692, 6526, 18050, 3607, 13941, 18989],
 [4381, 0, 6077, 5717, 15170, 6080, 16091, 2826, 7359, 17030],
 [6418, 5885, 0, 10768, 20926, 3168, 15564, 3783, 11621, 16502],
 [9928, 6067, 11340, 0, 11355, 9539, 9685, 7427, 5666, 19830],
 [15921, 15164, 21044, 10450, 0, 19243, 20147, 19231, 19150, 29533],
 [6263, 5730, 3162, 9649, 19808, 0, 12266, 3628, 6240, 13204],
 [17663, 15041, 16064, 9830, 19857, 12000, 0, 14293, 6178, 9538],
 [3463, 3146, 3378, 7830, 21083, 3727, 14798, 0, 11778, 15737],
 [11874, 8578, 10272, 5604, 19626, 6207, 6146, 8505, 0, 12661],
 [18434, 15812, 16836, 18990, 29148, 12772, 9829, 15065, 12691, 0]]

Make sure you include information that can help us debug (full error message, model Proto).
No error message

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
If they are no intermediate nodes, it means the vehicle is not active.
Thus the travelled distance is 0.

**Comment by Mizux** [comment]
By default the arc cost for a vehicle going from start to end is zero even if it is not the value returned by your registered transit callback...

You may force the solver to return the "correct" cost I.e. counting the cost for an "empty" vehicle which go from start to end by using the following method:
https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/ortools/constraint_solver/routing.h#L938-L946
