### ISSUE TITLE
[dotnet::routing] Unseal the sealed parameters

### ISSUE THREAD

**Issue by mwpowellhtx** [google/or-tools#2301]
I am considering wrapper level adapters for the _Routing parameters_, `Google.OrTools.ConstraintSolver.RoutingModelParameters`, `Google.OrTools.ConstraintSolver.RoutingSearchParameters`, however, I am finding that they are `sealed`. Is there a reason for them to be `sealed`? Reframing the question, is it possible for them to be unsealed?

**Comment by Mizux** [comment]
If I'm not wrong both classes should have been generated by `protoc` since there are protobuf messages.
Did you try to see if protoc have an option to "unseal" them ?

BTW since you should consider them as pure data structure why would you want to inherit from them ?

ref:
https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/ortools/constraint_solver/routing_parameters.proto#L38
https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/ortools/constraint_solver/routing_parameters.proto#L489

**Comment by mwpowellhtx** [comment]
@Mizux Glad you should ask. I am introducing wrapper verniers between the core API and the wrapper usage to help simplify cases such as:

```C#
using TAlpha = System.Nullable<bool>;
using TBravo = Google.OrTools.Util.OptionalBoolean;

public class OptionalBooleanBridge : ValueBridge<TAlpha, TBravo, OptionalBooleanBridge>
{
    // Which bridges between a `bool?` langauge level usage and the enumerated values.
}
```

In these instances, `ValueBridge<...>` is an abstraction I came up with, short of adopting a package dependency on something like an `AutoMapper`, let's say.

Also in cases where the path to the enumerated type is exceptionally verbose, i.e.

```C#
namespace Ellumination.OrTools.ConstraintSolver.Routing
{
    using TAlpha = FirstSolutionStrategy;
    using TBravo = Google.OrTools.ConstraintSolver.FirstSolutionStrategy.Types.Value;

    public class FirstSolutionStrategyBridge : ValueBridge<TAlpha, TBravo, FirstSolutionStrategyBridge>
    {
    }
}
```

Where I defined the vernier enumerated values basically like:

```C#
namespace Ellumination.OrTools.ConstraintSolver.Routing
{
    using LocalSearchMetaheuristic = Google.OrTools.ConstraintSolver.LocalSearchMetaheuristic;
    using FirstSolutionStrategyType = Google.OrTools.ConstraintSolver.FirstSolutionStrategy.Types.Value;

    public enum FirstSolutionStrategy
    {
        /// <summary>
        /// See the homonymous value in <see cref="LocalSearchMetaheuristic"/>.
        /// </summary>
        Unset = FirstSolutionStrategyType.Unset,

        // ...
    }
}
```

It is also a borderline case where I might consider a more automated CG approach, but I am on the fence where that is concerned at the moment.

In this way the namespace usage is not so cluttered and subscribers can focus on engaging with the wrappers within the context of the problem solution at hand, not so much which namespace paths are in question.

The plan in this instance is to introduce either a standalone parameters type, or to actually derive from it and sub in the namespace specific types referring to the `base.Property` for translation.

**Comment by lperron** [comment]
https://github.com/protocolbuffers/protobuf/issues/2154

The answer seems to be no.

**Comment by mwpowellhtx** [comment]
Thank you for the feedback. I'll take that under consideration.
