### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by SaiNathReddi** [google/or-tools#2307]
**What version of OR-tools and what language are you using?**

Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP_SAT
**What operating system (Linux, Windows, ...) and version?**
Windows
**What did you do?**
I tried install  the ortools PIP install ortools

when trying to run from ortools.linear_solver import pywraplp

**What did you expect to see**
The expectation is no error 
**What did you see instead?**
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-13-b7aff4ea2913> in <module>
----> 1 from ortools.linear_solver import pywraplp

~\AppData\Local\Continuum\anaconda3\lib\site-packages\ortools\linear_solver\pywraplp.py in <module>
     11 # Import the low-level C/C++ module
     12 if __package__ or "." in __name__:
---> 13     from . import _pywraplp
     14 else:
     15     import _pywraplp

ImportError: DLL load failed: The specified module could not be found.

Make sure you include information that can help us debug (full error message, model Proto).
I tried to uninstall and reinstall the package but still I am receiving the same error

**Comment by lperron** [comment]
Have you installed visual studio 2019 redistributable libraries ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 1 janv. 2021 à 15:07, SaiNathReddi <notifications@github.com> a
écrit :

**Comment by Mizux** [comment]
https://developers.google.com/optimization/install/python/windows#microsoft-visual-c++-redistributable
