### ISSUE TITLE
libjniortools.jnilib references /Users/dlahlou/Work/or-tools/lib/libortools.dylib

### ISSUE THREAD

**Issue by andygeers** [google/or-tools#231]
Tried using the Java August binary build on Mac OS X, and got
```
probable missing dependency: .../libjniortools.jnilib: dlopen(...../libjniortools.jnilib, 1):
Library not loaded: /Users/dlahlou/Work/or-tools/lib/libortools.dylib
  Referenced from: ..../libjniortools.jnilib
```

Looks like it's got an absolute path to the developer "dlahlou"'s machine?

**Comment by dlahlou** [comment]
Hello @andygeers,

Thank you for the report.

Can you please run `./install_libortools_mac.sh`? It should fix the dependencies path problem.

I believe this will not be necessary in the future releases. We will do it on behalf of the user.

Regards,

Driss.

**Comment by andygeers** [comment]
Ah, that solved it. Apologies if that was documented somewhere - I couldn't see it? 
e.g. would have expected it to be mentioned here: https://developers.google.com/optimization/installing#binary_java

**Comment by dlahlou** [comment]
It's actually, in the README file. We are actively updating the documentation to meet our new release process.
Thank you.
