### ISSUE TITLE
Support stopping the search from outside the solution callback

### ISSUE THREAD

**Issue by DonRobo** [google/or-tools#2310]
**What language and solver does this apply to?**
I'm using CP-SAT with Java, but this feature would be useful for everything

**Describe the problem you are trying to solve.**
I'm running a long search (up to half an hour). I'm displaying intermediate solutions to the user who often wants to stop the search and restart it with a modified model.

**Describe the solution you'd like**
When I receive a cancel request from outside the CpSolver (e.g. from the user) I would like to stop the search without waiting potentially up to 20 minutes for the next better solution.

**Describe alternatives you've considered**
Setting a short timelimit and restarting the search is not an option since it starts from scratch. Sending a regular Thread.interrupt() signal is also not working.

**Comment by lperron** [comment]
This is already possible. Create a callback, pass it to the search. Then
you can call stop search on it from anywhere.


Le sam. 2 janv. 2021 à 11:50, Robert Tieber <notifications@github.com> a
écrit :

**Comment by DonRobo** [comment]
I did not realize that. Thank you for your help.
