### ISSUE TITLE
Clustering and Geo-restrictions for vehicle routing

### ISSUE THREAD

**Issue by ad71** [google/or-tools#2311]
**What language and solver does this apply to?**
Python, Routing

**Describe the problem you are trying to solve.**
The routing solver by default generates routes that pick points along the way. While highly optimized, this is sometimes infeasible to carry out in some real life scenarios. For vehicle routing in big cities, it is sometimes desirable to have vehicles serve points in clusters.
One solution is to use a clustering algorithm beforehand (like `AgglomerativeClustering` from `sklearn`) and run the solver in parallel for each cluster and combine the results. However, this can often be sub-optimal and at the mercy of the initial clusters formed by the clustering algorithm.
Ideally there should be a way for the solver to cross these clusters when required.

Conversely, there might be cases where you do not want vehicles to cross certain motorways or landmarks or enter restricted areas (Geo-restrictions).

**Describe the solution you'd like**
I've been using or-tools for a few weeks now but haven't come across an inbuilt solution to this problem so I made my own. It's a method that uses clusters generated from a third-party clustering algorithm like the ones from `sklearn` and modifies the cost function to allow for breaches within clusters, which makes it another degree of freedom for the solver, instead of being constrained by rigid clusters. This also extends to solving for geo-restrictions without using fancy third-party APIs that return modified distance-matrices.
I was wondering if this project is accepting such contributions or if this will be useful at all, in which case, I would like to share a few example notebooks that go through these scenarios.

**Comment by lperron** [comment]
Hi, this would be very helpful. A notebook example would be perfect.

**Comment by rag9704** [comment]
@ad71  hey, is there any notebook or collab, i can see the solution of yours?

**Comment by AMPechero** [comment]
Hi, I can't see the notebook mentioned:
"Hi, this would be very helpful. A notebook example would be perfect.
I have added a new label for this kind of contributions.
Please look at the Show and Tell part in the discussions."

Could you update any link or a specific part of the OR-tool library
