### ISSUE TITLE
Add multiple delivery points for each pickup 

### ISSUE THREAD

**Issue by gabtorr** [google/or-tools#2312]
**What language and solver does this apply to?**
Python

**Describe the problem you are trying to solve.**
Actually (as long as i look into the tools) thee OR-Tools does'nt have support for multiple delivery points for each pickup. Even the example its tricky.

**Describe the solution you'd like**
Add multiple delivery points for pick up and delivery problem

**Comment by hklarner** [comment]
What's wrong with applying the usual pickup-delivery constraints for each pair?

So if `pickup = 5` and `dropoffs = [1,7,10]` then apply the usual constraints for `pairs = [(5, 1), (5, 7), (5, 10)]`.

**Comment by lperron** [comment]
This is not a product issue. Please use github discussions, or the mailing list.

**Comment by gabtorr** [comment]
@hklarner 
> What's wrong with applying the usual pickup-delivery constraints for each pair?
> 
> So if `pickup = 5` and `dropoffs = [1,7,10]` then apply the usual constraints for `pairs = [(5, 1), (5, 7), (5, 10)]`.
Where do i found more info about the pairs constraint? i tried onee like this (on the example code in the site):
`data['pickups_deliveries'] = [
        [1, 10],
        [1, 6],
        [1, 3],
        [5, 9],
        [7, 8],
        [15, 11],
        [13, 12],
        [16, 14],
    ]`
 And nothing happen :(
