### ISSUE TITLE
Access the transit callback index generated by AddMatrixDimension

### ISSUE THREAD

**Issue by jmarca** [google/or-tools#2315]
**What version of OR-tools and what language are you using?**
Version: master/v 8.1.8487.
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing Solver

**What operating system (Linux, Windows, ...) and version?**
LInux

**What did you do?**

I have been experimenting with the AddMatrixDimension call.  It is fast and exactly what I'm looking for, but there is an issue.

The code does this:

https://github.com/google/or-tools/blob/4cfd14164162be7727b8e4ee992c4b2c49eb768e/ortools/constraint_solver/routing.cc#L959-L965

In short, the transit callback function is created en passant, so to speak.

This is a problem because I want to use the same callback as the argument to `routing.SetArcCostEvaluatorOfAllVehicles()`

Is there a way via the API to access the current value of `transit_evaluators_.size()`, as is done at line https://github.com/google/or-tools/blob/4cfd14164162be7727b8e4ee992c4b2c49eb768e/ortools/constraint_solver/routing.cc#L793?

My current ugly ugly hack is:

```python
    # time
    routing.AddMatrixDimension(
        ev.duration_cache.tolist(), # underlying travel time (duration) matrix
        int(demand.horizon),  # max time is end of time horizon
        False,  # don't set time to zero...vehicles can wait at depot if necessary
        time_dimension_name)
    demand_callback = partial(ev.get_demand_callback(), manager)
    demand_callback_index = routing.RegisterUnaryTransitCallback(demand_callback)
    # super duper possibly buggy ugly HACK
    time_callback_index = demand_callback_index - 1
    routing.SetArcCostEvaluatorOfAllVehicles(time_callback_index)
```

In other words, I create another transit callback, then subtract one from its returned index to guess the value of the MatrixDimension's internally created callback function.

**Comment by Mizux** [comment]
so if I understand correctly you would like to change
https://github.com/google/or-tools/blob/4cfd14164162be7727b8e4ee992c4b2c49eb768e/ortools/constraint_solver/routing.h#L482-L491
to something like this
```cpp
std::tuple<bool, int> AddMatrixDimension( 
     std::vector<std::vector<int64> /*needed_for_swig*/> values, 
     int64 capacity, bool fix_start_cumul_to_zero, const std::string& name);
```

the second argument being the RegisterCallback index ?
so in python hope to have

```python
success, callback_index = routing.AddMatrixDimension(...)
```

**Comment by jmarca** [comment]
Yes that would work. 

But perhaps more general approach is to make functions for `routing.RegisterMatrixTransitCallback([matrix data])` and RegisterVectorTransitCallback

The problem I’m trying to fix is the slow process of calling back to python from c++. I already create matrices and vectors for my dimension callbacks, and it is so much (8x to 10x) faster to use the matrix and vector dimension variants and just pass in all the data at once.

**Comment by jmarca** [comment]
Maybe something like this, just copy and paste from what is there (and sorry, I'm not going to pretend my C++ skills are good enough to submit a patch).

```cpp
int RegisterMatrixCallback(std::vector<std::vector<int64>> values,
                           RoutingModel* model) {
  all_transits_positive = one_liner_are_values_positive(values);
  return RegisterCallback(
                          [model, values](int64 i, int64 j) {
                            return values[manager_.IndexToNode(i).value()]
                                         [manager_.IndexToNode(j).value()];
                          },
                          all_transits_positive
}
```
Note that I'm pretty sure one can't simply refer to `manager_` like I have above.

**Comment by Mizux** [comment]
thinking of it, maybe we could simply add it as an extension/sugar in the RoutingModel wrapper directly...
i.e. the ultimate goal is to have the matrix captured by copy in the C++ side to avoid the python/C++ traversal cost when used.

ps: should be `model->manager_` if this member is public, otherwise need to check if there is a `RoutingModel::GetManager()` method...

**Comment by jmarca** [comment]
Yes, the routing.i python api has the AddMatrixDimension call, and AddVectorDimension.  But the issue is that I need the callback index in order to use the "passed matrix data callback" for the  call to `routing.SetArcCostEvaluatorOfAllVehicles()`.

I can envision situations in which one does not need to create a dimension, but still wants to call  `routing.SetArcCostEvaluatorOfAllVehicles()` using a very large matrix.  That's why I'm suggesting that it might be the most useful to add matrix and vector versions of `RegisterCallback`.

**Comment by Mizux** [comment]
@jmarca do a little bit of rework now we have in pyhon:

```python
int RegisterUnaryTransitVector([....]) # Since we have RegistUnaryTransitCallback()
int RegisterTransitMatrix([[...],[...],...]) # Since we have RegistTransitCallback()

PairIntBool AddVectorDimension([...],....)
PairIntBool AddMatrixDimension([[...],[...],...],....)

usage:
p = routing.AddMatrixDimenion(...)
transit_id = p[0] # get the registered transit callback id
success = p[1] # get the boolean return of AddDimension
```

I didn't find a way in "pure" SWIG to do :disappointed: 
```python
transit_id, success = routing.AddMatrixDimension(...) 
```

You can also take a look at https://github.com/google/or-tools/blob/master/examples/tests/test_routing_api.py

**Comment by jmarca** [comment]
Awesome. I will fire up my master branch Docker container and try it out.

**Comment by Mizux** [comment]
Maybe, I just find a way to output a tuple so API will change again to expected:
```python
transit_id, success = routing.AddMatrixDimension(...) 
```

ps: not pushed yet

**Comment by jmarca** [comment]
I’ll pull again and test it out this weekend. I have high hopes it will be much faster.

**Comment by qemtek** [comment]
@Mizux is it possible to use this approach for item weight? Following the documentation usually we have a dictionary of demands, but in theory could we supply a matrix of weights, where for collections the destination value is positive and for deliveries the destination value is negative?

Ive started using AddMatrixDimension with python but my worry is that the other callbacks will be a bottleneck
