### ISSUE TITLE
Java crash in operations_research::RoutingModel::~RoutingModel()+0x2f

### ISSUE THREAD

**Issue by andygeers** [google/or-tools#232]
I'm doing a CVRPWTW in Java, and it's working pretty well. However, after I have run my routing model a couple of times (I think basically until the Garbage Collector kicks in), it crashes:

```
11:39:49 web.1  | # A fatal error has been detected by the Java Runtime Environment:
11:39:49 web.1  | #
11:39:49 web.1  | #  SIGSEGV (0xb) at pc=0x000000011ffae33f, pid=87260, tid=14339
11:39:49 web.1  | #
11:39:49 web.1  | # JRE version: Java(TM) SE Runtime Environment (8.0_31-b13) (build 1.8.0_31-b13)
11:39:49 web.1  | # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.31-b07 mixed mode bsd-amd64 compressed oops)
11:39:49 web.1  | # Problematic frame:
11:39:49 web.1  | # C  [libortools.dylib+0x2f433f]  operations_research::RoutingModel::~RoutingModel()+0x2f
11:39:49 web.1  | #
11:39:49 web.1  | # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
11:39:49 web.1  | #
11:39:49 web.1  | # An error report file with more information is saved as:
11:39:49 web.1  | # /Users/andygeers/hubbub/capacity-manager/hs_err_pid87260.log
```

Log file attached: [hs_err_pid87260.log.txt](https://github.com/google/or-tools/files/434542/hs_err_pid87260.log.txt)

Here's a (mostly) minimal Java program that crashes when you run it:
[crashingcvrptw.zip](https://github.com/google/or-tools/files/445315/crashingcvrptw.zip)

`java -cp objs:lib/com.google.ortools.jar:lib/uk.co.hubbub.ortools.jar uk.co.hubbub.ortools.CapacitatedVehicleRoutingProblemWithTimeWindows`

**Comment by andygeers** [comment]
So latest update is that I can reproduce this purely from Java (so it was nothing to do with using JRuby) - basically as soon as the Garbage Collector kicks in it crashes. I've attached a zip file with my Java program that crashes when you run it.

**Comment by andygeers** [comment]
There is an old discussion topic on the same issue: https://groups.google.com/forum/#!topic/or-tools-discuss/dpTJ35xJA64

**Comment by dlahlou** [comment]
Hello Andy,
I would like to debug your code, so can you please attach the zip file you talked about?
Regards.

**Comment by andygeers** [comment]
It was that link at the bottom of my first post: [crashingcvrptw.zip](https://github.com/google/or-tools/files/445315/crashingcvrptw.zip)

Just in case, I've built another one that should hopefully do the same thing:
[CrashReproduction.zip](https://github.com/google/or-tools/files/454820/CrashReproduction.zip)

**Comment by lperron** [comment]
Just checked the problem. It runs fine on my machine.
Closing the issue.
