### ISSUE TITLE
Inconsistent behavior with user-defined domains, presolve, memory allocation

### ISSUE THREAD

**Issue by FelTam** [google/or-tools#2322]
**What version of OR-tools and what language are you using?**
Version: master
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
We solve a 3-dimensional container loading problem with the start positions of items as integer variables. 
Case 1: We set the domains of the variables with
```cpp
yStartPosition.emplace_back(this->cp_model.NewIntVar({ 0, container.Dy - minDimItem }));
```

Case 2: We set the domains of the variables with 
```cpp
yStartPosition.emplace_back(this->cp_model.NewIntVar(
     operations_research::Domain::FromFlatSpanOfIntervals(yStartPoints)));
```
to reduce the number of possible start points. yStartPoints is a `std::vector<int64>`.

**What did you expect to see**
Consistent behavior in all runs.

**What did you see instead?**
The program runs without any errors using Case 1. However, in Case 2, sometimes the program terminates with various errors and sometimes it runs as expected, even for the same instance. The errors are a kind of mystery for us and we have attached some screenshots of the call stack.
![error_AffineRelation](https://user-images.githubusercontent.com/76058557/103924466-590bad80-5116-11eb-8c32-ebabef8bbdd3.PNG)
![error_Presolve](https://user-images.githubusercontent.com/76058557/103924470-59a44400-5116-11eb-8104-8cc601ffc468.PNG)
![error_Add_Parameters](https://user-images.githubusercontent.com/76058557/103924471-59a44400-5116-11eb-9af1-eca9aecf9cb0.PNG)

See also the model proto files
[protoModel_Case1.txt](https://github.com/google/or-tools/files/5784365/protoModel_Case1.txt)
[protoModel_Case2.txt](https://github.com/google/or-tools/files/5783074/protoModel_Case2.txt)

**Anything else we should know about your project / environment**
We use Visual Studio 2019 with std:c++latest.

**Comment by lperron** [comment]
case 1 file is truncated.

**Comment by FelTam** [comment]
Sorry, don't know how the last 100 lines got lost. I have updated protoModel_Case1.txt. This should be complete.

**Comment by lperron** [comment]
Which parameters are you using when solving ?

**Comment by FelTam** [comment]
The program terminates unexpectedly with different paramter settings. We have tested default settings, turning off presolve, multi-threading and single-threading.

**Comment by lperron** [comment]
I have just run it on the master branch multiple times, without any problem.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
It could be a mismatch between protobuf versions. Have you updated it
independently from the or-tools library?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by FelTam** [comment]
The error was in determining the new starting points. Memory was corrputed in a corner case. I thought I've checked this, but well.. 
Now everything is working fine. I am sorry for wasting your time and thank you for the quick support and building such a great tool.
