### ISSUE TITLE
integration with or-tools in c++ with bazel

### ISSUE THREAD

**Issue by safronau** [google/or-tools#2328]
Could you please add some description at https://github.com/google/or-tools/tree/stable/bazel#integration instead of TODO.

**Comment by lperron** [comment]
There is nothing specific to or-tools there.

**Comment by Mizux** [comment]
@lperron the goal is to provide a sample/tempate project like we did for CMake
https://github.com/google/or-tools/tree/stable/cmake#integration
The best is to have a repo like https://github.com/or-tools/cmake_or-tools but for bazel based build.

**Comment by Mizux** [comment]
@safronau something like this: https://github.com/or-tools/bazel_or-tools
