### ISSUE TITLE
error C2001

### ISSUE THREAD

**Issue by FishHe** [google/or-tools#2329]
Version：ortools 8.1
Environment：VS2019 x64

cl /std:c++17 /EHsc /MD /nologo -nologo  /D__WIN32__ /DPSAPI_VERSION=1 /DNOMINMAX /DWIN32_LEAN_AND_MEAN=1 /D_CRT_SECURE_NO_WARNINGS /O2 -DNDEBUG /I. /Iortools/gen /DUSE_GLOP /DUSE_BOP     /I"dependencies\\install\\include" /I"dependencies\\install\\include" /I"dependencies\\install\\include" /I"dependencies\\install\\include" /I"dependencies\\install\\include\\coin" /I"dependencies\\install\\include" /I"dependencies\\install\\include\\coin" /I"dependencies\\install\\include" /I"dependencies\\install\\include\\coin" /DUSE_CLP /I"dependencies\\install\\include" /I"dependencies\\install\\include\\coin" /I"dependencies\\install\\include" /I"dependencies\\install\\include\\coin" /DUSE_CBC /I"dependencies\\install\\include" /DUSE_SCIP /DNO_CONFIG_HEADER  /DOR_TOOLS_MAJOR=8 /DOR_TOOLS_MINOR=1 -c .\\ortools\\linear_solver\\linear_solver.cc /Foobjs\\linear_solver\\linear_solver.obj
linear_solver.cc
.\ortools\linear_solver\linear_solver.cc(806): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保 存为 Unicode 格式以防止数据丢失
.\ortools\linear_solver\linear_solver.cc(1266): error C2001: 常量中有换行符
.\ortools\linear_solver\linear_solver.cc(1267): error C2143: 语法错误: 缺少“;”(在“}”的前面)
.\ortools\linear_solver\linear_solver.cc(1274): error C2001: 常量中有换行符
.\ortools\linear_solver\linear_solver.cc(1275): error C2143: 语法错误: 缺少“;”(在“}”的前面)
.\ortools\linear_solver\linear_solver.cc(1287): error C2001: 常量中有换行符
.\ortools\linear_solver\linear_solver.cc(1288): error C2143: 语法错误: 缺少“)”(在“:”的前面)
.\ortools\linear_solver\linear_solver.cc(1429): warning C4805: “==”: 在操作中将类型“double”与类型“bool”混合不安全
make: *** [makefiles/Makefile.gen.mk:3384: objs/linear_solver/linear_solver.obj] Error 2

**Comment by Mizux** [comment]
Google translate:
```
.\ortools\linear_solver\linear_solver.cc(806): warning C4819: This file contains characters that cannot be represented in the current code page (936). Please save the file in Unicode format to prevent data loss
.\ortools\linear_solver\linear_solver.cc(1266): error C2001: newline character in constant
.\ortools\linear_solver\linear_solver.cc(1267): error C2143: syntax error: missing ";" (before "}")
.\ortools\linear_solver\linear_solver.cc(1274): error C2001: newline character in constant
.\ortools\linear_solver\linear_solver.cc(1275): error C2143: syntax error: missing ";" (before "}")
.\ortools\linear_solver\linear_solver.cc(1287): error C2001: newline character in constant
.\ortools\linear_solver\linear_solver.cc(1288): error C2143: syntax error: missing ")" (before ":")
.\ortools\linear_solver\linear_solver.cc(1429): warning C4805: "==": It is not safe to mix the type "double" with the type "bool" in the operation
```

**Comment by Mizux** [comment]
https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/ortools/linear_solver/linear_solver.cc#L1266
and
https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/ortools/linear_solver/linear_solver.cc#L1274
and
https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/ortools/linear_solver/linear_solver.cc#L1287
