### ISSUE TITLE
Missing documentation on disabling Large Neighbourhood Search

### ISSUE THREAD

**Issue by andygeers** [google/or-tools#233]
I started using or-tools back when the CapacitatedVehicleRoutingProblemWithTimeWindows Java example used setNo_lns(true) on RoutingSearchParameters. As far as I can tell this option has been removed, but I can't see any documentation on what the replacement is.

Now I'm setting parameters like so:
```
RoutingSearchParameters parameters = RoutingSearchParameters.newBuilder()
      .mergeFrom(RoutingModel.defaultSearchParameters())
      .build();
```

**Comment by mjfwest** [comment]
I can't find any documentation for the options in Python either, however I think the replacement in Python is shown in #235. Perhaps this helps?

**Comment by dlahlou** [comment]
Hello @andygeers,

I tried your code, and it works. Here is another way to do it : 
 ```
RoutingSearchParameters.LocalSearchNeighborhoodOperators local_search_operators = 
  RoutingSearchParameters
  .LocalSearchNeighborhoodOperators
  .newBuilder()
  .setUsePathLns(true)
  .build();

RoutingSearchParameters search_parameters =
    RoutingSearchParameters.newBuilder()
    .mergeFrom(RoutingModel.defaultSearchParameters())
    .setFirstSolutionStrategy(FirstSolutionStrategy.Value.PATH_CHEAPEST_ARC)
    .setLocalSearchOperators(local_search_operators)
    .build();
```

and to get the parameters values, you can try this : 
`System.out.println("use_path_lns : " + search_parameters.getLocalSearchOperators().getUsePathLns());`

I hope this helps.

Regards,

Driss
