### ISSUE TITLE
using ortools in Visual Studio2019 

### ISSUE THREAD

**Issue by Hei5enber9** [google/or-tools#2335]
**What version of OR-tools and what language are you using?**
C++, VS2019

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
ALL

**What operating system (Linux, Windows, ...) and version?**
WINDOWS10

**What did you do?**
I downloaded the Binary file and passed the test:  `tools\make test_cc`

I want to debug the code in VS2019, here are the Debug Properties.
![image](https://user-images.githubusercontent.com/40930438/104556454-9a520f00-567a-11eb-95af-f9d8c0077023.png)
![image](https://user-images.githubusercontent.com/40930438/104556466-9f16c300-567a-11eb-9dee-eff2c8cdc10e.png)
![image](https://user-images.githubusercontent.com/40930438/104556490-a8a02b00-567a-11eb-8d59-0d5632000bdc.png)
![image](https://user-images.githubusercontent.com/40930438/104556507-ae960c00-567a-11eb-9b2e-6f18ea59bb6c.png)

I got lots of errors like:
1>ortools.lib(CglRedSplit2Param.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in Source.obj
1>ortools.lib(CglGMIParam.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Source.obj
1>ortools.lib(CglGMIParam.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in Source.obj
1>ortools.lib(CoinRational.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Source.obj
1>ortools.lib(CoinRational.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in Source.obj
1>ortools.lib(CglLandPSimplex.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Source.obj
1>ortools.lib(CglLandPSimplex.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in Source.obj
1>ortools.lib(Cgl012cut.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Source.obj
1>ortools.lib(Cgl012cut.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in Source.obj
1>ortools.lib(sparse_column.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Source.obj
1>ortools.lib(sparse_column.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in Source.obj
1>ortools.lib(rational_approximation.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Source.obj
1>ortools.lib(rational_approximation.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in Source.obj
1>ortools.lib(sparse_permutation.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Source.obj
1>ortools.lib(sparse_permutation.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in Source.obj
1>ortools.lib(pb_constraint.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Source.obj
1>ortools.lib(pb_constraint.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in Source.obj
1>ortools.lib(sat_decision.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Source.obj
1>ortools.lib(sat_decision.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in Source.obj
1>ortools.lib(sat_solver.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Source.obj

So I changed the Runtime Library:
![image](https://user-images.githubusercontent.com/40930438/104556771-1cdace80-567b-11eb-81ea-e2221b7968ac.png)

But it doesn't work.  I find some similar questions in Issues, which is helpless. 

Could you please give a detailed instruction how to use ortools in VS2019?

Thanks!

**Comment by Mizux** [comment]
Binary files are generated using the makefile based build AND we only generate in release (i.e. without the debug flag activated that's why you hae libortools.lib and no debug libortools.dlib).

You could try to build from source using the CMake based build instead (which should integrate nicely with the VS2019 builtin support)

**Comment by juntek** [comment]
@Mizux I've tried, but I failed. Perhaps I did something wrong or stupid. What I did:

1. download or-tools stable repository
2. run  x64 Native Tools Command Prompt for VS2019
3. Open a terminal and navigate to the directory where you extracted the files. Then enter: tools\make third_party
4. Start VS2019 and open or-tools folder
5. cmake generation failed:

1> [CMake] CMake Error at cmake/deps.cmake:20 (find_package):
1> [CMake]   By not providing "Findabsl.cmake" in CMAKE_MODULE_PATH this project has
1> [CMake]   asked CMake to find a package configuration file provided by "absl", but CMake did not find one.
1> [CMake] 
1> [CMake]   Could not find a package configuration file provided by "absl" with any of the following names:
1> [CMake] 
1> [CMake]     abslConfig.cmake
1> [CMake]     absl-config.cmake
1> [CMake] 
1> [CMake]   Add the installation prefix of "absl" to CMAKE_PREFIX_PATH or set
1> [CMake]   "absl_DIR" to a directory containing one of the above files.  If "absl"
1> [CMake]   provides a separate development package or SDK, be sure it has been installed.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeLists.txt:234 (include)
1> [CMake] -- Configuring incomplete, errors occurred!

**Comment by lperron** [comment]
you are mixing the cmake based build, and the make based build.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by juntek** [comment]
@lperron thank you for your prompt response.
OK, I deleted the whole folder, downloaded fresh copy of or-tools stable repository, started VS2019 and then opened or-tools folder but now cmake cannot find ZLIB:

1> [CMake]   Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)

**Comment by lperron** [comment]
Make sure you have an up to date cmake version.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by juntek** [comment]
cmake version 3.19.2

**Comment by lperron** [comment]
and pass -DBUILD_DEPS=ON
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by juntek** [comment]
CMake cache has been generated successfully now.

However, build fails:
`FAILED: _deps/scip-build/CMakeFiles/scip_update_githash`
[...]
`CMake Error at scip_update_githash.cmake:7 (if):`
`    if given arguments:`
  
      "(" "GIT" ")" "AND" "(" "EXISTS" "D:/or-tools/out/build/x64-Debug" "(" "default" ")" "/_deps/scip-src/.git" ")"
  
    Unknown arguments specified`

**Comment by juntek** [comment]
@Hei5enber9 I've just managed to build debug version of the library by manually modifying a couple of configuration files. Here's what you need to do:
1. Clone or download a fresh copy of OR-Tools "stable" repository 
2. Uncompress attached file [ortools_debug_cfg.zip](https://github.com/google/or-tools/files/5928436/ortools_debug_cfg.zip)
3. Replace CMakeLists.txt file in or-tools main folder
4. Replace *.mk files in 'makefiles' subfolder
5. Start "x64 Native Tools Command Prompt for VS 2019" and cd to your or-tools folder
6. Enter: tools\make third_party
7. Enter: tools\make cc
8. Once build completes, your ortools.lib file will be in the 'lib' folder. You can rename the file to 'ortoolsd.lib' if you want to keep release builds as well

**Comment by Hei5enber9** [comment]
> @Hei5enber9 I've just managed to build debug version of the library by manually modifying a couple of configuration files. Here's what you need to do:
> 
> 1. Clone or download a fresh copy of OR-Tools "stable" repository
> 2. Uncompress attached file [ortools_debug_cfg.zip](https://github.com/google/or-tools/files/5928436/ortools_debug_cfg.zip)
> 3. Replace CMakeLists.txt file in or-tools main folder
> 4. Replace *.mk files in 'makefiles' subfolder
> 5. Start "x64 Native Tools Command Prompt for VS 2019" and cd to your or-tools folder
> 6. Enter: tools\make third_party
> 7. Enter: tools\make cc
> 8. Once build completes, your ortools.lib file will be in the 'lib' folder. You can rename the file to 'ortoolsd.lib' if you want to keep release builds as well

Thanks juntek. I will try your method when I am free. 

I built successfully Debug mode using Cmake. But there are some errors, i.e. I can’t pass ALL test examples. (Out range of vector subscripts). 

But I can pass all tests in Release mode.
