### ISSUE TITLE
OR-Tools with xamarin.ios

### ISSUE THREAD

**Issue by DeveloperOnGitHub** [google/or-tools#2339]
**What version of OR-tools and what language are you using?**
Version: master/v8.1.8487
Language: C#/Xamarin.ios

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
SCIP Solver with OR-tools

**What operating system (Linux, Windows, ...) and version?**
Xamarin on Apple iOS 14

**What did you do?**
I am using the or-tools successfully in a C# WinForms application on my Windows PC. But now, I want to implement it as an App for my iPhone using **Xamarin.ios**.

When I compile my App for a target "Any CPU" it compiles successfully and is also launching the App successfully on the Simulator for an iPhone 11. Creating an instance of the Solver in my code it crashes at the following line of code with a System.TypeInitializationException and the following message :

Solver solver = Solver.CreateSolver("SCIP");
```
-        $exception    {System.TypeInitializationException: The type initializer for 'Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: google-ortools-native assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE+SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_operations_research_linear_solver(Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE/SWIGExceptionHelper/ExceptionDelegate)
  at Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE+SWIGExceptionHelper..cctor () [0x000ee] in <0ffc7b4e8212457789d975cd96b6733e>:0
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE..cctor () [0x00000] in <0ffc7b4e8212457789d975cd96b6733e>:0
   --- End of inner exception stack trace ---
  at Google.OrTools.LinearSolver.Solver.CreateSolver (System.String solver_id) [0x00000] in <0ffc7b4e8212457789d975cd96b6733e>:0
  at MacroCalculatorApp.FirstViewController.CmdCalculateMacros_TouchUpInside (UIKit.UIButton sender) [0x00001] in D:\Development\C#\CalculatorApp\CalculatorApp\FirstViewController.cs:30
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.6.0.15/src/Xamarin.iOS/UIKit/UIApplication.cs:86
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.6.0.15/src/Xamarin.iOS/UIKit/UIApplication.cs:65
  at MacroCalculatorApp.Application.Main (System.String[] args) [0x00001] in D:\Development\C#\CalculatorApp\CalculatorApp\Main.cs:12 }    System.TypeInitializationException
```

Well, since the or-tools normally use x64 not so unusual.

But, when I compile for target platform "x64" it does not compile successfully and ends up with the following error message:

Error while loading assemblies: /Users/user123456/Library/Caches/Xamarin/mtbs/builds/CalculatorApp/fda88690a4f0385e766da2e9f1a0fa346f22da910448991cb2900847d21d3cc4/bin/iPhoneSimulator/Debug/google-ortools-native.dll.    CalculatorApp   

So, how can I get my App running using or-tools on an iPhone? Is there a way?

**Comment by lperron** [comment]
I am not sure iphone will recognize the x86_64 architecture. And I do not
know if dotnet core is supported on iphone.

Currently, architectures are hardcoded in C# here:
https://github.com/google/or-tools/tree/master/ortools/dotnet in the
runtime directories.

You will need to add a new runtime id for iphone, if it exists. Add it to
main config files there and recompile.

We have not started this journey yet, but we are very interested in your
progress :-)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
For the cmake supposing you have MSVC 2019+, you should try to use:

```sh
cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DBUILD_DOTNET=ON -DBUILD_CXX_SAMPLES=OFF -DBUILD_CXX_EXAMPLES=OFF
cmake --build build --config Release --target ALL_BUILD -v -- /maxcpucount
```

ref: https://github.com/google/or-tools/blob/stable/.github/workflows/win_dotnet.yml

**Comment by DeveloperOnGitHub** [comment]
Hi Mizux,

thanks a lot for your support! My build did work now with these options. I am going to experiment with the xamarin.ios stuff and hope, I can get it running. I will let you guys know how it worked.

**Comment by Mizux** [comment]
please note:
- the cmake build will use the csproj template files located here:
https://github.com/google/or-tools/tree/stable/ortools/dotnet/Google.OrTools.runtime.win-x64 so you can try to hack them to ad xamarin Target Framework Moniker.
- the relevant cmake stuff is here: https://github.com/google/or-tools/blob/stable/cmake/dotnet.cmake
- or you can hack directly the generated csproj which should be in build/dotnet/... and rerun the build by hand
https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/cmake/dotnet.cmake#L171-L172

ref:
https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/cmake/dotnet.cmake#L86-L96

**Comment by DeveloperOnGitHub** [comment]
Hhm, I made some changes in different places and also started off also with a TargetFramework **net5.0-ios** according to the following link https://docs.microsoft.com/en-us/dotnet/standard/frameworks
Expectation is that also this TFM includes standard .NET Framework **net452** which was defined with the **win-x64** RID

`<PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>netstandard2.1;netstandard2.0;net5.0-ios</TargetFrameworks>
    <RuntimeIdentifier>ios.11-x64</RuntimeIdentifier>
    <AssemblyName>google-ortools-native</AssemblyName>
    <Version>@PROJECT_VERSION@</Version>
    ...
</PropertyGroup>`

Here is my BUT : I figured out that even with my first successful make-process mentioned above, no nupgk for Google.OrTools.runtime.osx-x64 or Google.OrTools.runtime.linux-x64 was generated, just the Google.OrTools.runtime.win-x64

I used the zipped sources from GIT named or-tools-master.zip and used your cmake-Commands in this root directory. Your command used  **--target ALL_BUILD**, so my expectation was I would get nupgk's for **ALL** RIDs specified in the directories under "d:\development\or-tools-master\ortools\dotnet\.."

When I was looking for the reason and looking into other script files, I saw different variables and checks for the **OS** to build and also found labels like **APPLE** and so on.

Where are these variables set and how would I have an influence on them to build my new **Google.OrTools.runtime.ios-x64** RID with the ** *.csproj.in** and ** *.targets** files which I created under "d:\development\or-tools-master\ortools\dotnet\.."?
What would be the way to build just this RID or at least include it in the build?

Currently, I use the command from you:
`cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DBUILD_DOTNET=ON -DBUILD_CXX_SAMPLES=OFF -DBUILD_CXX_EXAMPLES=OFF
cmake --build build --config Release --target ALL_BUILD -v -- /maxcpucount`

**Comment by Mizux** [comment]
Just few questions to fully understand:
* What is your **HOST** system ?
* What is your **TARGET** system ?
* Do you know the RID and TFM needed for your target OS ?

Supposing you are on windows, and want to target ios I see currently few "challenges"
- First it means you may want to cross compile native C++ code for target processor IIRC iOS is using ARM processor
Luckily this week, I integrate cross compilation support in our CMake based build for the C++ build **BUT** I don't know if an linaro arm64 cross toolchain will work on iOS (also I thought you have to use Xcode on a MacOS to do IOS native dev).
you can take a look at the script in [tools/cross_compile.sh](https://github.com/google/or-tools/blob/master/tools/cross_compile.sh).

- Second currently I only tested the C++ build, but I didn't do/test the .NET wrapper I.e. you may adapt our SWIG machinery to also generate .Net wrapper and the C++ internal code for an ARM64 target
EDIT: seems the code generated should be processor agnostic.

**Comment by DeveloperOnGitHub** [comment]
Hi Mizux,

> Just few questions to fully understand:
> 
>     * What is your **HOST** system ?
>     * What is your **TARGET** system ?

Currently, my Host-System for this Compile/Make is Windows 10 and I would like to compile the or-tools for use on an iPhone Xs with latest iOS 14.3. But, I'd also have Mac OS with Xcode and VS 2019 for Mac available if needed.


>     * Do you know the RID and TFM needed for your target OS ?

Well, this is kind of a challenge, since I am not experienced with or-tools compilation and corresponding settings.

My understanding was, that I could use **any** RID I want (following the or-tools naming conventions) and the Runtime ID will finally determine the (Cross-Platform) Compilation for the corresponding target system. Am I wrong on this?

Therefore, the RID or Naming of the Folder/Files in D:\Development\or-tools-master\ortools\dotnet was just **Google.OrTools.runtime.ios-x64**. For my Runtime-ID, I refererred to the following list [https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.NETCore.Platforms/pkg/runtime.json](https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.NETCore.Platforms/pkg/runtime.json) and wanted to try **ios.13-arm64** or more general **ios.13-x64**. This is not the latest iOS-Version, but, I assume we do not need methods from the latest API in **iOS 14.3**

    ...
    "ios.13-arm64": {
        "#import": [
        "ios.13",
        "ios.12-arm64"
      ]
    },
    "ios.13-x64": {
      "#import": [
        "ios.13",
        "ios.12-x64"
      ]
    },
    ...

For **TFM**, I just referred to [https://docs.microsoft.com/en-us/dotnet/standard/frameworks](https://docs.microsoft.com/en-us/dotnet/standard/frameworks). So, maybe use `<TargetFramework>...;net5.0-ios14.0</TargetFramework>` or `<TargetFramework>...;net5.0</TargetFramework>` or even a combination with `<TargetFramework>...;net452;net5.0</TargetFramework>`. For the last one, I don't know, if this would make sense, since **net5.0** should include **net452** so we could get rid of this.

In section **.NET 5 OS-specific TFMs** it is mentioned that TFM **net5.0-ios** includes **xamarin.ios (plus everything else inherited from net5.0)**, so this would be my starting point.



> Supposing you are on windows, and want to target ios I see currently few "challenges"
> 
>     * First it means you may want to cross compile native C++ code for target processor IIRC iOS is using ARM processor
>       Luckily this week, I integrate cross compilation support in our CMake based build for the C++ build **BUT** I don't know if an linaro arm64 cross toolchain will work on iOS (also I thought you have to use Xcode on a MacOS to do IOS native dev).
>       you can take a look at the script in [tools/cross_compile.sh](https://github.com/google/or-tools/blob/master/tools/cross_compile.sh).

For iPhone App-Development, also using Xamarin.ios, you really need a Mac and Xcode to do the native compile.
But, I am confused, do you really need to compile or-tools on the corresponding target system? Normally, this should be done by the native C++ cross-platform compiler for the corresponding target processor architecture.
So, for my understanding, we should trigger a Cross-Plattform Compile for the arm-x64 processor architecture and with the settings above my hope was or-tools would run on it.


>     * Second currently I only tested the C++ build, but I didn't do/test the .NET wrapper I.e. you may adapt our SWIG machinery to also generate .Net wrapper and the C++ internal code for an ARM64 target
>       EDIT: seems the code generated should be processor agnostic.

When I got you correctly, currently no Cross-Platform compilation isn't possible until you integrated the Cross-Platform Compile in the Make-Process.

If you like you could also try with the settings for RID and TFM from above as long it makes sense what I mentioned and see if we get a *.nupgk output with your new Cross-Platform-Compile-Process. I could give it a try then with my Xamarin.ios App doing the Compile of my App with Mac OS and Xcode.

**Comment by DeveloperOnGitHub** [comment]
Hi Mizux,

what do you think about my comments? Am I wrong on something?
Just do not know about difficulties with the Cross-Compiler-Stuff since there seems to be Cross-Compilation for Linux and OSX currently already. Is this different with Mobile Phones and especially with Cross-Compilation for the iPhone-Hardware?

Sorry for all my questions - just interested in all that ;)

**Comment by DeveloperOnGitHub** [comment]
Hi Mizux,

>     * Second currently I only tested the C++ build, but I didn't do/test the .NET wrapper I.e. you may adapt our SWIG machinery to also generate .Net wrapper and the C++ internal code for an ARM64 target
>       EDIT: seems the code generated should be processor agnostic.

what do you think about my comments? Am I wrong on something? Just do not know about difficulties with the Cross-Compiler-Stuff since there seems to be Cross-Compilation for Linux and OSX currently already. Is this different with Mobile Phones and especially with Cross-Compilation for the iPhone-Hardware?

Sorry for all my questions - just interested in all that ;)

**Comment by DeveloperOnGitHub** [comment]
Hi Mizux,

> Supposing you are on windows, and want to target ios I see currently few "challenges"
> 
>     * First it means you may want to cross compile native C++ code for target processor IIRC iOS is using ARM processor
>       Luckily this week, I integrate cross compilation support in our CMake based build for the C++ build **BUT** I don't know if an linaro arm64 cross toolchain will work on iOS (also I thought you have to use Xcode on a MacOS to do IOS native dev).
>       you can take a look at the script in [tools/cross_compile.sh](https://github.com/google/or-tools/blob/master/tools/cross_compile.sh).

what do you think about my comments? Am I wrong on something? Just do not know about difficulties with the Cross-Compiler-Stuff since there seems to be Cross-Compilation for Linux and OSX currently already. Is this different with Mobile Phones and especially with Cross-Compilation for the iPhone-Hardware?

Sorry for all my questions - just interested in all that ;)

**Comment by Mizux** [comment]
My 2 cents,

## Target Framework Moniker (TFM)

> The `net5.0`, `net6.0`, and `net7.0` TFMs include technologies that work across different platforms. Specifying an OS-specific TFM makes APIs that are specific to an operating system available to your app, for example, Windows Forms or iOS bindings. OS-specific TFMs also inherit every API available to their base TFM, for example, the `net6.0` TFM.

> |   **TFM** | Compatible with |
 | net6.0-ios | xamarin.ios (+everything else inherited from net6.0) |

ref: https://docs.microsoft.com/en-us/dotnet/standard/frameworks#net-5-os-specific-tfms

So our `net6.0` TFM could be consumable in a `net6.0-ios` project

## Runtime IDentifier (RID)

On apple M1 we do support `osx-arm64` RID

```xml
    "ios-arm64": {
      "#import": [
        "ios",
        "unix-arm64"
      ]
    },
```
https://github.com/dotnet/runtime/blob/51f3ca60ed119375fe55fd300b219ee2317dbb75/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json#L1284-L1289

So `ios-arm64` RID import `unix-arm64` but not `osx-arm64` so osx-arm64 won't be loaded by ios-arm64 IMHO

## C++ Cross-Compilation

Currently our CMakeLists.txt do not support ios toolchain or at least we don't provide one and we should adapt few line
e.g.
https://github.com/google/or-tools/blob/a3d0375dc82af83373733506000139a958d490a2/cmake/dotnet.cmake#L48-L53
To add support for `ios-arm64` and/or `ios-x64`

**Comment by DeveloperOnGitHub** [comment]
I think making sure that the correpsonding ios simulator is included and supported in the configuration would also be beneficial!

**Comment by DeveloperOnGitHub** [comment]
> We have release osx-arm64 for .net. Is this enough ?

Does it mean you were able to build for ios and fix the make for ios? I tried a lot with an ios-toolchain file, but really couldn't make it in the end as I got final errors I couldn't solve in the end. I really did not have a clue where they came from and how to get around them.

**Comment by lperron** [comment]
We build on an arm mac.

**Comment by DeveloperOnGitHub** [comment]
I thought a build process for Mac was already included and working? How does it impact a successful build for iOS? The initial issue mentioned Xamarin, I would extend it though to "build on iOS in general" which means .NET MAUI is really interesting.

**Comment by Mizux** [comment]
Will close it, no time to add support for ios RID or xamarin TFM.

With all the information above you should be able to tweak the cmake build system to do it yourself.
note: You can use this project to iterate faster www.mizux.dev/dotnet-native , then once you have this hello world running you can hack or-tools accordingly...
