### ISSUE TITLE
Strange behaviour in flexible_job_shop_sat example

### ISSUE THREAD

**Issue by filippobistaffa** [google/or-tools#2341]
While playing around with the [flexible_job_shop_sat](https://github.com/google/or-tools/blob/stable/examples/python/flexible_job_shop_sat.py) example, I tried to change the number of tasks in each job. Specifically, I tried to simplify the problem and set only 1 task per job:
```python
jobs = [ # task = (processing_time, machine_id)
    [ # Job 0
        [(3, 0)], # alternative 0
        [(2, 1)], # alternative 1
        [(2, 2)], # alternative 2
    ],
    [ # Job 1
        [(2, 0)],
        [(1, 1)],
        [(2, 2)],
    ],
    [ # Job 2
        [(2, 0)],
        [(2, 1)],
        [(3, 2)],
    ],
]
```
When running the same code with this input, the output does not quite make sense (for instance, it still shows 3 tasks per job):
```python
Job 0:
  task_0_0 starts at 4 (alt 0, machine 0, duration 3)
  task_0_1 starts at 7 (alt 0, machine 1, duration 2)
  task_0_2 starts at 9 (alt 0, machine 2, duration 2)
Job 1:
  task_1_0 starts at 0 (alt 0, machine 0, duration 2)
  task_1_1 starts at 2 (alt 0, machine 1, duration 1)
  task_1_2 starts at 3 (alt 0, machine 2, duration 2)
Job 2:
  task_2_0 starts at 2 (alt 0, machine 0, duration 2)
  task_2_1 starts at 4 (alt 0, machine 1, duration 2)
  task_2_2 starts at 6 (alt 0, machine 2, duration 3)
Solve status: OPTIMAL
Optimal objective value: 11
Statistics
  - conflicts : 2
  - branches  : 15
  - wall time : 0.001405 s
```
I guess one of the problems is that the number of tasks is defined as `len(jobs[job_id])`
https://github.com/google/or-tools/blob/4a755da303ff5c4330a71259e32f7427c2c7d541/examples/python/flexible_job_shop_sat.py#L167
while this is really the number of alternatives, as far as I understand? Or am I missing something? More in general, is this bug only related to the output code, or does it also affect the modelling part?

**Comment by lperron** [comment]
[(3, 0)], # task 0 with 1 alternative
        [(2, 1)], # task 1 with 1 alternative
        [(2, 2)], # task 2 with 1 alternative

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
https://github.com/google/or-tools/blob/252564060e3ac14bf3be7e4da1fde8f901e82310/examples/python/flexible_job_shop_sat.py#L36-L40

**Comment by filippobistaffa** [comment]
Ok now it makes sense, I was just confused by the comment :+1:
