### ISSUE TITLE
Examples mismatch between source and binary distributions

### ISSUE THREAD

**Issue by juntek** [google/or-tools#2347]
**What language and solver does this apply to?**
All, Python, Java, C#, C++

**Describe the problem you are trying to solve.**
1. Download binary distribution
2. Download (clone) source distribution
3. Compare examples folder between the two distributions

**Describe the solution you'd like**
The set of examples in source and binary distributions should be the same. 
For now there is a huge discrepancy between the two.

**Comment by Mizux** [comment]
Did you compare against the correct tag ?
Our Default branch is set to stable, while our dev branch is master...

Please provide more details, source branch, archives name etc...

**Comment by lperron** [comment]
I do not understand why this is a problem.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
And more to the point, 

we have scripts that copy all c++, cs, java examples.
The only thing we knowingly do not copy are all the data sets which are huge.

**Comment by juntek** [comment]
I do not uderstand why binary distribution has a different set of examples. I think it should be consistent.
For example in binary distribution java folder has huge set of examples, but in source repo it is very tiny.
It would also make bug reporting easier. For example there is a bug in VRP java example from binary distribution (lacks distance constraint)

**Comment by lperron** [comment]
We copy contrib examples in their respective language based directories when we build the archive.

**Comment by lperron** [comment]
And we keep them separated in the source because it helps licensing.

**Comment by Mizux** [comment]
in source all pom.xml for each samples and examples are built on the fly by the Makefile or CMake build system, in the binary distribution we ship examples with the generated pom.xml to avoid to use advanced **GNU** Makefile features which may not be available in all installations BUT all .java files should be identical.

CMake generation
https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/cmake/java.cmake#L223-L309

Make generation
https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/makefiles/Makefile.java.mk#L468-L570

Archive code generation (note binary are built using the makefile based build)
https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/makefiles/Makefile.archive.mk#L87-L123

**Comment by juntek** [comment]
Do you mean I need to run build in the source repo in order for the examples to be downloaded?

**Comment by Mizux** [comment]
no, I means in the source examples are in: `ortools/*/samples/*.java` `examples/contrib/*.java` `examples/java/*.java`.
when running the build the "archive layout" will be generated in the build directory (i.e. the build system copy the java file and generate the pom.xml) so you should have more or less the same layout than the binary archive but in the build dir.

**Comment by Mizux** [comment]
@juntek are your talking of these java samples: https://github.com/google/or-tools/tree/stable/ortools/constraint_solver/samples

**Comment by juntek** [comment]
OK, now I understand. So there are "sources of examples" which in binary distribution are copied into their respective folder.
A bit confusing but that's ok.
