### ISSUE TITLE
Suppress Error Messages from Solver when no Solution exists

### ISSUE THREAD

**Issue by julesy89** [google/or-tools#2350]
**What language and solver does this apply to?**
Python

Great optimization library and really simple to use!

I am solving hundreds of smaller integer linear programs and for many of them, no feasible solution exists. This is totally fine and expected,  but the printouts in the command line blow up. Is there a way to disable this independent of the solver?

`E0708 15:51:31.420898     1 linear_solver.cc:1688] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE`

**Comment by Mizux** [comment]
comes from:
https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/ortools/linear_solver/linear_solver.cc#L1683-L1693

**Comment by julesy89** [comment]
Thanks for that hint. Is there a way to disable logging without recompiling the whole library?

**Comment by stradivari96** [comment]
Dup: https://github.com/google/or-tools/issues/776
The workaround is to check the status before accessing the variables.

**Comment by julesy89** [comment]
That is exactly what I was searching for! Thanks!
