### ISSUE TITLE
fzn_cumulative not supported

### ISSUE THREAD

**Issue by glebbelov** [google/or-tools#2363]
**What version of OR-tools and what language are you using?**
Version: master or stable/8.1
Language: FlatZinc

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
fz

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 19.10

**What did you do?**
`or-tools/bin/fz ../challenge_from_2012/mznc2015_probs/largescheduling/largecumulative.fzn -fz_logging 5`

[largecumulative.fzn.tar.gz](https://github.com/google/or-tools/files/5884910/largecumulative.fzn.tar.gz)

(The FZN was obtained as follows: `minizinc --solver ortools -f ../challenge_from_2012/mznc2015_probs/largescheduling/largecumulative.mzn ../challenge_from_2012/mznc2015_probs/largescheduling/instance-0100-1.dzn -i`)

**What did you expect to see**
Optimal solution

**What did you see instead?**
```
%% File ../challenge_from_2012/mznc2015_probs/largescheduling/largecumulative.fzn parsed in 1 ms
%% Presolve model
%%   - done in 0 ms
%% Model largecumulative
%%   - array_int_maximum: 1
%%   - fzn_cumulative: 1
%%   - int_lin_eq: 100
%%   - int_lin_le: 100
%%   - Minimization problem
%% *** Starting translation to CP-SAT
 Not supported fzn_cumulative
*** Check failure stack trace: ***
    @     0x7f2f33eab6ac  google::LogMessage::Fail()
    @     0x7f2f33eab5f5  google::LogMessage::SendToLog()
    @     0x7f2f33eaaf37  google::LogMessage::Flush()
    @     0x7f2f33eae7ec  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f2f33f71987  operations_research::sat::(anonymous namespace)::CpModelProtoWithMapping::FillConstraint()
    @     0x7f2f33f7588e  operations_research::sat::SolveFzWithCpModelProto()
    @     0x55d6dd0fae9f  main
    @     0x7f2f33adb09b  __libc_start_main
    @     0x55d6dd0fb32a  _start
    @              (nil)  (unknown)
Aborted (core dumped)
```

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
Strange:

https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/ortools/flatzinc/cp_model_fz_solver.cc#L665

Are you sure you are calling the correct binary ?

**Comment by glebbelov** [comment]
Yes wrong binary, thank you.
