### ISSUE TITLE
Failure on a simple FlatZinc

### ISSUE THREAD

**Issue by glebbelov** [google/or-tools#2364]
**What version of OR-tools and what language are you using?**
Version: master
Language: FlatZinc

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
fz

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 19.10

**What did you do?**
`or-tools/build/bin/fz -f -s -v ../challenge_from_2012/mznc12-problems/tpp/tpp.fzn`

FZN:
```
predicate fzn_subcircuit(array [int] of var int: x);
int: X_INTRODUCED_2_ = 340;
array [1..9] of int: succ = [1,2,3,4,5,9,7,8,6];
array [1..30] of int: purchaseLoc = [6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6];
constraint fzn_subcircuit(succ);
solve :: seq_search([int_search(succ,input_order,indomain_min,complete),int_search(purchaseLoc,input_order,indomain_min,complete)]) minimize X_INTRODUCED_2_;
```

**What did you expect to see**
```

----------
==========
```

**What did you see instead?**
```
=====MODEL INVALID=====
```
or UNKNOWN if running via `minizinc`

Moreover, when adding `-fz_logging 5`, I see
```
Check failed: absl::EndsWith(problem_name, ".fzn") 
*** Check failure stack trace: ***
    @     0x7fd214d91320  (unknown)
Aborted (core dumped)
```

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
The second error is that you must use --fz_logging, and you cannot add a number afterwards. The solver thinks 5 is the filename.

**Comment by lperron** [comment]
Thanks.
I pushed the fix to master.

**Comment by lperron** [comment]
And I also improved the error message about the file name
