### ISSUE TITLE
CP-SAT does not solve problem from C++

### ISSUE THREAD

**Issue by prissky** [google/or-tools#2375]
**Version:** v8.1
**Language:** C++/Java
**Solver:** CP-SAT
**OS:** Windows

**Steps to reproduce the behavior:**
1. Load [model](https://github.com/google/or-tools/files/5918991/model.zip) from proto-file in Java. Solve in 100 s.
2. Load the same model in C++. It takes 260 s only to start presolve. Process takes up all memory. 

**I expected to see:**
Similar behavior.

**Instead I saw:**
No solution from C++, not even search started yet.

**Comment by lperron** [comment]
No, loading it in C++:

I1011 15:09:04.704101     1 sat_runner.cc:172] Reading a CpModelProto.

I1011 15:58:35.652343     1 cp_model_solver.cc:2949] Parameters:
log_search_progress: true

I1011 16:07:22.776123     1 cp_model_solver.cc:2973] Optimization model '':

#Variables: 582431 (1 in objective)

 - 175 different domains in [0,5070] with a largest complexity of 1.

 - 15762 constants in {0,1,2,3,4,5,6,7,8,9,10,11,1 ...
2,309,324,332,342,388,401,427,480,492,568,70000}

#kCumulative: 119

#kIntMax: 1

#kInterval: 9622 (#enforced: 7260)

#kLinear1: 2118075 (#enforced: 2114285)

#kLinear2: 54098 (#enforced: 37623)

#kLinearN: 3846 (#terms: 80076)

I1011 16:10:13.392333     1 cp_model_solver.cc:3016] *** starting model
presolve at 0.70s

I1011 22:55:02.243164     1 simplification.cc:337] num removable Booleans:
354311 / 582439

I1011 22:55:02.279541     1 simplification.cc:339] num trivial clauses:
185119

I1011 22:55:03.713623     1 simplification.cc:924]  [0s] clauses:506757
literals:1017557 vars:181986 one_side_vars:178238 simple_definition:1870
singleton_clauses:0

I1011 22:55:48.009765     1 simplification.cc:924]  [0.0446084s]
clauses:325009 literals:651809 vars:181986 one_side_vars:179097
simple_definition:1817 singleton_clauses:0

I1011 22:56:43.771972     1 simplification.cc:924]  [0.100567s]
clauses:320777 literals:643345 vars:180392 one_side_vars:179408
simple_definition:982 singleton_clauses:0

I1011 23:24:43.751708     1 cp_model_presolve.cc:4408] Merged 319466 into
312884 cliques.

I1012 02:11:10.562011     1 simplification.cc:337] num removable Booleans:
354330 / 582439

I1012 02:11:10.583984     1 simplification.cc:339] num trivial clauses: 0

I1012 02:11:11.658447     1 simplification.cc:924]  [0s] clauses:307860
literals:617511 vars:173826 one_side_vars:172842 simple_definition:982
singleton_clauses:0

I1012 02:11:37.195068     1 simplification.cc:924]  [0.0261957s]
clauses:307856 literals:617503 vars:173826 one_side_vars:172842
simple_definition:982 singleton_clauses:0

I1012 02:12:17.561523     1 simplification.cc:924]  [0.0665773s]
clauses:307856 literals:617503 vars:173826 one_side_vars:172842
simple_definition:982 singleton_clauses:0

I1012 03:03:38.721679     1 cp_model_presolve.cc:4820] 41 affine relations
still in the model.

I1012 03:44:47.840820     1 cp_model_presolve.cc:5079] - 271528 affine
relations were detected.

I1012 03:44:47.865478     1 cp_model_presolve.cc:5081] - 241471 variable
equivalence relations were detected.

I1012 03:44:47.898925     1 cp_model_presolve.cc:5089] - rule 'TODO
variables: only used in encoding.' was applied 66 times.

I1012 03:44:47.904541     1 cp_model_presolve.cc:5089] - rule 'affine: new
relation' was applied 213947 times.

I1012 03:44:47.908935     1 cp_model_presolve.cc:5087] - rule 'at_most_one:
transformed into max clique.' was applied 1 time.

I1012 03:44:47.912841     1 cp_model_presolve.cc:5089] - rule 'bool_and:
always false' was applied 691 times.

I1012 03:44:47.916992     1 cp_model_presolve.cc:5089] - rule 'bool_and:
fixed literals' was applied 2 times.

I1012 03:44:47.921142     1 cp_model_presolve.cc:5089] - rule 'bool_and:
non-reified.' was applied 582 times.

I1012 03:44:47.925292     1 cp_model_presolve.cc:5089] - rule 'bool_or:
always true' was applied 1022 times.

I1012 03:44:47.929199     1 cp_model_presolve.cc:5089] - rule 'bool_or:
fixed literals' was applied 421 times.

I1012 03:44:47.933105     1 cp_model_presolve.cc:5089] - rule 'bool_or:
implications' was applied 1253 times.

I1012 03:44:47.937255     1 cp_model_presolve.cc:5089] - rule 'bool_or:
only one literal' was applied 115905 times.

I1012 03:44:47.941406     1 cp_model_presolve.cc:5089] - rule 'bool_or:
removed enforcement literal' was applied 3652 times.

I1012 03:44:47.945800     1 cp_model_presolve.cc:5089] - rule 'cumulative:
convert to no_overlap' was applied 8 times.

I1012 03:44:47.950683     1 cp_model_presolve.cc:5089] - rule 'cumulative:
removed intervals with no demands' was applied 7 times.

I1012 03:44:47.954345     1 cp_model_presolve.cc:5087] - rule 'deductions:
1965318 stored' was applied 1 time.

I1012 03:44:47.958251     1 cp_model_presolve.cc:5089] - rule 'dual:
reduced domain' was applied 355 times.

I1012 03:44:47.962402     1 cp_model_presolve.cc:5089] - rule 'exactly_one:
duplicate literals' was applied 3 times.

I1012 03:44:47.966552     1 cp_model_presolve.cc:5089] - rule 'exactly_one:
removed literals' was applied 285 times.

I1012 03:44:47.970458     1 cp_model_presolve.cc:5089] - rule 'exactly_one:
size two' was applied 78 times.

I1012 03:44:47.974609     1 cp_model_presolve.cc:5089] - rule 'false
enforcement literal' was applied 238219 times.

I1012 03:44:47.978759     1 cp_model_presolve.cc:5087] - rule 'int_max:
reduced domains' was applied 1 time.

I1012 03:44:47.982666     1 cp_model_presolve.cc:5087] - rule 'int_max:
removed dup' was applied 1 time.

I1012 03:44:47.986328     1 cp_model_presolve.cc:5089] - rule 'int_max:
removed variables' was applied 14 times.

I1012 03:44:47.990478     1 cp_model_presolve.cc:5089] - rule 'interval:
reduced domains' was applied 5241 times.

I1012 03:44:47.994384     1 cp_model_presolve.cc:5089] - rule 'interval:
unused, converted to linear' was applied 6152 times.

I1012 03:44:47.999023     1 cp_model_presolve.cc:5089] - rule 'linear:
always true' was applied 6016 times.

I1012 03:44:48.003417     1 cp_model_presolve.cc:5089] - rule 'linear:
empty' was applied 9343 times.

I1012 03:44:48.007568     1 cp_model_presolve.cc:5089] - rule 'linear:
enforcement literal in expression' was applied 552 times.

I1012 03:44:48.011718     1 cp_model_presolve.cc:5089] - rule 'linear:
extracted enforcement literal' was applied 2 times.

I1012 03:44:48.015869     1 cp_model_presolve.cc:5089] - rule 'linear:
fixed or dup variables' was applied 14367 times.

I1012 03:44:48.020019     1 cp_model_presolve.cc:5089] - rule 'linear:
infeasible' was applied 115554 times.

I1012 03:44:48.024169     1 cp_model_presolve.cc:5089] - rule 'linear:
negative reified and' was applied 3772 times.

I1012 03:44:48.027832     1 cp_model_presolve.cc:5089] - rule 'linear:
positive clause' was applied 1752 times.

I1012 03:44:48.031982     1 cp_model_presolve.cc:5089] - rule 'linear:
positive equal one' was applied 456 times.

I1012 03:44:48.036132     1 cp_model_presolve.cc:5089] - rule 'linear:
positive reified and' was applied 829210 times.

I1012 03:44:48.040039     1 cp_model_presolve.cc:5089] - rule 'linear:
reduced variable domains' was applied 2646 times.

I1012 03:44:48.044189     1 cp_model_presolve.cc:5089] - rule 'linear:
remapped using affine relations' was applied 240468 times.

I1012 03:44:48.048095     1 cp_model_presolve.cc:5089] - rule 'linear:
simplified rhs' was applied 1898366 times.

I1012 03:44:48.052490     1 cp_model_presolve.cc:5089] - rule 'linear:
singleton column' was applied 2 times.

I1012 03:44:48.056884     1 cp_model_presolve.cc:5089] - rule 'linear: size
one' was applied 123485 times.

I1012 03:44:48.060791     1 cp_model_presolve.cc:5089] - rule 'linear:
small Boolean expression' was applied 1885 times.

I1012 03:44:48.064697     1 cp_model_presolve.cc:5087] - rule 'linear:
split boxed constraint' was applied 1 time.

I1012 03:44:48.068603     1 cp_model_presolve.cc:5089] - rule 'no_overlap:
no intervals' was applied 6 times.

I1012 03:44:48.072753     1 cp_model_presolve.cc:5089] - rule 'no_overlap:
removed redundant intervals' was applied 6 times.

I1012 03:44:48.076904     1 cp_model_presolve.cc:5089] - rule 'presolve:
iteration' was applied 2 times.

I1012 03:44:48.080566     1 cp_model_presolve.cc:5089] - rule 'removed
duplicate constraints' was applied 424908 times.

I1012 03:44:48.084716     1 cp_model_presolve.cc:5089] - rule 'true
enforcement literal' was applied 125800 times.

I1012 03:44:48.088867     1 cp_model_presolve.cc:5089] - rule 'variables
with 2 values: create encoding literal' was applied 8 times.

I1012 03:44:48.093261     1 cp_model_presolve.cc:5089] - rule 'variables
with 2 values: new affine relation' was applied 8 times.

I1012 03:44:48.097167     1 cp_model_presolve.cc:5089] - rule 'variables:
detect fully reified value encoding' was applied 90150 times.

I1012 03:44:48.101318     1 cp_model_presolve.cc:5089] - rule 'variables:
detect half reified value encoding' was applied 1181476 times.

I1012 03:44:48.105712     1 cp_model_presolve.cc:5089] - rule 'variables:
merge equivalent var value encoding literals' was applied 2999 times.

I1012 03:51:18.126708     1 cp_model_solver.cc:3055] Optimization model '':

#Variables: 226382 (1 in objective)

 - 4172 different domains in [0,4780] with a largest complexity of 3.

 - 167 constants in {1,2,3,4,5,6,7,8,9,10,11,12,13 ...
287,292,309,324,332,342,388,401,427,480,492,568}

#kAtMostOne: 6333 (#literals: 18999)

#kBoolAnd: 5400 (#enforced: 5400) (#literals: 306545)

#kBoolOr: 1311 (#literals: 4413)

#kCumulative: 110

#kExactlyOne: 378 (#literals: 1250)

#kIntMax: 1

#kInterval: 2362

#kLinear1: 522808 (#enforced: 522808)

#kLinear2: 28277 (#enforced: 26867)

#kLinear3: 5525 (#enforced: 4930)

#kLinearN: 453 (#terms: 1812)

#kNoOverlap: 2

I1012 04:06:21.212646     1 synchronization.cc:121] #Bound  43.67s best:inf
next:[4369,4780] initial domain

I1012 04:06:21.255859     1 cp_model_solver.cc:3211] *** starting to load
the model at 43.67s

...


knowing the java calls the C++ solver, I am surprised.


With 12 workers on my laptop:


status: OPTIMAL

objective: 4369

best_bound: 4369

booleans: 682062

conflicts: 100

branches: 54351

propagations: 13595005

integer_propagations: 4937886

restarts: 7444

lp_iterations: 34670

walltime: 456.513

usertime: 456.513

deterministic_time: 811.617

primal_integral: 38.3594


With 32 workers on my workstation:


status: OPTIMAL

objective: 4369

best_bound: 4369

booleans: 681226

conflicts: 47

branches: 23852

propagations: 10575596

integer_propagations: 3596467

restarts: 7442

lp_iterations: 12056

walltime: 92.577

usertime: 1009.82

deterministic_time: 171.929

primal_integral: 39.7714


Can you log the search and look at the header parts, to see if you are
solving the same problem ?


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by prissky** [comment]
Thank you for your response. Yes, the initial counts of variables and constraints are the same. [This](https://github.com/google/or-tools/files/5923875/execute_proto.zip) is how I load the model and launch solver.

**Comment by lperron** [comment]
Can you check the model stats after presolve ?

I suspect the java layer is not using the same C++ library. All solving is
done in C++.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by prissky** [comment]
Yes, you are right. Java was using older version because I forgot it in env. variable path. Sorry about that. But my point is that if called from C++ on Windows, CP-SAT doesn't even reach past presolve (in reasonable time). Furthermore, I've just checked that the exact same procedure works just fine on Linux (C++ -> v8.1).

**Comment by lperron** [comment]
It takes 40s on my laptop on master.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by prissky** [comment]
Is it on Windows as well?

**Comment by lperron** [comment]
yes.

bin\sat_runner.exe --input ..\support\issue2375.pbtxt.gz --logtostderr --params log_search_progress:true,num_search_workers:16 --log_prefix
I00-1 -1:-1:-1.590087 17436 sat_runner.cc:172] Reading a CpModelProto.
^C
c:\Users\laure\Work\or-tools>
c:\Users\laure\Work\or-tools>
c:\Users\laure\Work\or-tools>bin\sat_runner.exe --input ..\support\issue2375.pbtxt.gz --logtostderr --params log_search_progress:true,num_search_workers:16 --log_prefix=false
Reading a CpModelProto.
Parameters: log_search_progress: true num_search_workers: 16
Optimization model '':
#Variables: 582431 (1 in objective)
 - 175 different domains in [0,5070] with a largest complexity of 1.
 - 15762 constants in {0,1,2,3,4,5,6,7,8,9,10,11,1 ... 2,309,324,332,342,388,401,427,480,492,568,70000}
#kCumulative: 119
#kIntMax: 1
#kInterval: 9622 (#enforced: 7260)
#kLinear1: 2118075 (#enforced: 2114285)
#kLinear2: 54098 (#enforced: 37623)
#kLinearN: 3846 (#terms: 80076)
*** starting model presolve at 1.11s
num removable Booleans: 354311 / 582439
num trivial clauses: 185119
 [0s] clauses:506757 literals:1017557 vars:181986 one_side_vars:178238 simple_definition:1870 singleton_clauses:0
 [0.0325619s] clauses:325009 literals:651809 vars:181986 one_side_vars:179097 simple_definition:1817 singleton_clauses:0
 [0.0785263s] clauses:320777 literals:643345 vars:180392 one_side_vars:179408 simple_definition:982 singleton_clauses:0
Merged 319466 into 312884 cliques.
num removable Booleans: 354330 / 582439
num trivial clauses: 0
 [0s] clauses:307860 literals:617511 vars:173826 one_side_vars:172842 simple_definition:982 singleton_clauses:0
 [0.016153s] clauses:307856 literals:617503 vars:173826 one_side_vars:172842 simple_definition:982 singleton_clauses:0
 [0.0567592s] clauses:307856 literals:617503 vars:173826 one_side_vars:172842 simple_definition:982 singleton_clauses:0
41 affine relations still in the model.
- 271528 affine relations were detected.
- 241471 variable equivalence relations were detected.
- rule 'TODO variables: only used in encoding.' was applied 66 times.
- rule 'affine: new relation' was applied 213947 times.
- rule 'at_most_one: transformed into max clique.' was applied 1 time.
- rule 'bool_and: always false' was applied 691 times.
- rule 'bool_and: fixed literals' was applied 2 times.
- rule 'bool_and: non-reified.' was applied 582 times.
- rule 'bool_or: always true' was applied 1022 times.
- rule 'bool_or: fixed literals' was applied 421 times.
- rule 'bool_or: implications' was applied 1253 times.
- rule 'bool_or: only one literal' was applied 115905 times.
- rule 'bool_or: removed enforcement literal' was applied 3652 times.
- rule 'cumulative: convert to no_overlap' was applied 8 times.
- rule 'cumulative: removed intervals with no demands' was applied 7 times.
- rule 'deductions: 1965318 stored' was applied 1 time.
- rule 'dual: reduced domain' was applied 355 times.
- rule 'exactly_one: duplicate literals' was applied 3 times.
- rule 'exactly_one: removed literals' was applied 285 times.
- rule 'exactly_one: size two' was applied 78 times.
- rule 'false enforcement literal' was applied 238219 times.
- rule 'int_max: reduced domains' was applied 1 time.
- rule 'int_max: removed dup' was applied 1 time.
- rule 'int_max: removed variables' was applied 14 times.
- rule 'interval: reduced domains' was applied 5241 times.
- rule 'interval: unused, converted to linear' was applied 6152 times.
- rule 'linear: always true' was applied 6016 times.
- rule 'linear: empty' was applied 9343 times.
- rule 'linear: enforcement literal in expression' was applied 552 times.
- rule 'linear: extracted enforcement literal' was applied 2 times.
- rule 'linear: fixed or dup variables' was applied 14367 times.
- rule 'linear: infeasible' was applied 115554 times.
- rule 'linear: negative reified and' was applied 3772 times.
- rule 'linear: positive clause' was applied 1752 times.
- rule 'linear: positive equal one' was applied 456 times.
- rule 'linear: positive reified and' was applied 829210 times.
- rule 'linear: reduced variable domains' was applied 2646 times.
- rule 'linear: remapped using affine relations' was applied 240468 times.
- rule 'linear: simplified rhs' was applied 1898366 times.
- rule 'linear: singleton column' was applied 2 times.
- rule 'linear: size one' was applied 123485 times.
- rule 'linear: small Boolean expression' was applied 1885 times.
- rule 'linear: split boxed constraint' was applied 1 time.
- rule 'no_overlap: no intervals' was applied 6 times.
- rule 'no_overlap: removed redundant intervals' was applied 6 times.
- rule 'presolve: iteration' was applied 2 times.
- rule 'removed duplicate constraints' was applied 424908 times.
- rule 'true enforcement literal' was applied 125800 times.
- rule 'variables with 2 values: create encoding literal' was applied 8 times.
- rule 'variables with 2 values: new affine relation' was applied 8 times.
- rule 'variables: detect fully reified value encoding' was applied 90150 times.
- rule 'variables: detect half reified value encoding' was applied 1181476 times.
- rule 'variables: merge equivalent var value encoding literals' was applied 2999 times.
Optimization model '':
#Variables: 226382 (1 in objective)
 - 4172 different domains in [0,4780] with a largest complexity of 3.
 - 167 constants in {1,2,3,4,5,6,7,8,9,10,11,12,13 ... 287,292,309,324,332,342,388,401,427,480,492,568}
#kAtMostOne: 6333 (#literals: 18999)
#kBoolAnd: 5400 (#enforced: 5400) (#literals: 306545)
#kBoolOr: 1311 (#literals: 4413)
#kCumulative: 110
#kExactlyOne: 378 (#literals: 1250)
#kIntMax: 1
#kInterval: 2362
#kLinear1: 522808 (#enforced: 522808)
#kLinear2: 28277 (#enforced: 26867)
#kLinear3: 5525 (#enforced: 4930)
#kLinearN: 453 (#terms: 1812)
#kNoOverlap: 2
#Bound  51.56s best:inf   next:[4369,4780] initial domain
*** starting Search at 52.13s with 16 workers and subsolvers: [ default_lp, reduced_costs, pseudo_costs, no_lp, max_lp, quick_restart, quick_restart_no_lp, probing, feasibility_pump, rnd_lns_default, var_lns_default, cst_lns_default, scheduling_time_window_lns_default, scheduling_random_lns_default, rins_lns_default, rens_lns_default ]
#1      69.58s best:4780  next:[4369,4779] no_lp fixed_bools:1/680156
#2      70.77s best:4778  next:[4369,4777] no_lp fixed_bools:2422/680160
#3      71.81s best:4773  next:[4369,4772] no_lp fixed_bools:2848/680163
#4      72.73s best:4772  next:[4369,4771] no_lp fixed_bools:4001/680163
#5      74.52s best:4771  next:[4369,4770] no_lp fixed_bools:4196/680179
#6      76.19s best:4765  next:[4369,4764] no_lp fixed_bools:5682/680184
#7      77.74s best:4764  next:[4369,4763] no_lp fixed_bools:11214/680193
#8      79.14s best:4759  next:[4369,4758] no_lp fixed_bools:11496/680204
#9      80.50s best:4758  next:[4369,4757] no_lp fixed_bools:15912/680209
#10     81.64s best:4757  next:[4369,4756] no_lp fixed_bools:17180/680213
#11     82.54s best:4756  next:[4369,4755] quick_restart_no_lp fixed_bools:17619/683328
#12     84.30s best:4755  next:[4369,4754] quick_restart_no_lp fixed_bools:17937/683797
#13     84.46s best:4754  next:[4369,4753] no_lp fixed_bools:17736/6802

**Comment by prissky** [comment]
I tried on other PCs and it works. The exact same code gets stuck on my workstation only. So far, no idea why. Anyways, thank you for your time.

**Comment by lperron** [comment]
Does your laptop have very little memory? You could swap a lot.

**Comment by prissky** [comment]
Good tip, but no. 64 GB is not the cause of the problem.
