### ISSUE TITLE
presolve is too slow

### ISSUE THREAD

**Issue by laohumultimedia** [google/or-tools#2377]
i use ortools 8.1.8487 and python version 3.8.1.
presolve cost too much time  and it used just one core,  is it possible to speed up presolve by multi core ?  any suggestion?

**Comment by lperron** [comment]
1) this is unprecise. You do not specify the solver.
2) how big is your model? 
3) how long does it take? Compared to the full solving time?

To answer your question, it is possible. But it requires a lot of code and is not a priority.

**Comment by laohumultimedia** [comment]
Hi,  i use cp-sat solver.  
time depends on the problem scope, sometime more than half of the full solving time. 
is it possible to use multi core ? i will be vary appreciated if you provide some documents for presolve configuration.

**Comment by Mizux** [comment]
For CP-Sat you must enable worker thread to 8

**Comment by lperron** [comment]
Presolve does not use parallelism.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
