### ISSUE TITLE
Building OR-Tools in a project that uses Google logging

### ISSUE THREAD

**Issue by joshburkart** [google/or-tools#2378]
**What language and solver does this apply to?**
C++

**Describe the problem you are trying to solve.**
I work in a project that I'm trying to import OR-Tools into, but which uses the Google logging framework extensively. This works fine with OR-Tools release 8.0, but fails in 8.1 AFAICT since the new OR-Tools logging library introduced in 8.1 has symbol/macro names that conflict with `glog`.

**Describe the solution you'd like**
I'm not sure...

**Describe alternatives you've considered**
We're using 8.0 for now!

**Additional context**

**Comment by lperron** [comment]
Tough question.

Can you use the logging re-implementation for or-tools in your project ? It uses the flags v2 API (absl::SetFlag, ABSL_FLAG...) API.

I have no time frame until abseil actually implements it and I can remove my patch.

And protecting by some prefix/namespace is complex because of the actual parsing of the command line parameters.

I am sorry, you are stuck with 8.0 for the near future.

**Comment by Mizux** [comment]
Few questions:
- On which platform are you working ?
- Did you use OR-Tools from source ?
- Which build system are you using ?

**Comment by joshburkart** [comment]
Interesting, thanks for the ideas -- that gives me a sense of what the path forward looks like. I'll probably use 8.0 for now and revisit as necessary.

* Linux
* Yes, from source via Bazel `WORKSPACE` rule
* Bazel

Thanks for the quick responses!

**Comment by sschnug** [comment]
For me, above questions would be answered with:

- Linux
- Yes, from source via cmake + add_subdirectory
- cmake

Something like (sry for some noise):

	# all provided by vcpkg (as most are used by non or-tools part of code) -> cmake toolchain script
	# -----------------------------------------------
	find_package(ZLIB REQUIRED)
	find_package(absl CONFIG REQUIRED)
	find_package(benchmark CONFIG REQUIRED)
	find_package(Boost REQUIRED)
	find_package(gflags CONFIG REQUIRED)
	find_package(glog CONFIG REQUIRED)
	find_package(GTest CONFIG REQUIRED)
	find_package(protobuf CONFIG REQUIRED)

	# Eigen               -> Git Submodule 
	add_subdirectory(third_party/eigen)

	# ortools             -> Git Submodule
	# ------------------------------------
	set(BUILD_FLATZINC OFF)
	set(USE_COINOR OFF)
	set(USE_SCIP OFF)
	set(BUILD_SAMPLES OFF)
	set(BUILD_EXAMPLES OFF)
	add_subdirectory(third_party/or-tools)

Above isn't the first iteration but something hacked together (after observing alloc errors in protoc when compiled as part of or-tool dependency which i don't need externally). In general, or-tools cmake config seems to work well / pick up all those vcpkg-provided dependencies (abseil, protobuf, ...).

**Comment by lperron** [comment]
Some news. 

I pushed on main the code that uses the newly released absl::log library.
I have just kept the vlog code, as it is not part of the current absl::log code.

At this point, the only official google logging code is the abseil one. So I will close this issue.

Thanks
