### ISSUE TITLE
Min capacity constraint not working

### ISSUE THREAD

**Issue by PranoyKumar3** [google/or-tools#2384]
Language: Python
Python Package version : ortools==8.1.8487
**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing Solver

**What did you do?**

Hi,
The minimum capacity constraint doesn't seem to be implemented by the solver, In this particular example I have used SetCumulVarSoftLowerBound to add a minimum capacity soft constraint to each of my vehicle due to which if any vehicle doesn't visit certain number of nodes then a penalty cost should be added to the objective cost. But in my case I have used 5 vehicles and the fifth vehicle doesn't visit any node but still no penalty cost is added to the objective cost. I have attached a google colab link to a mini problem i created, kindly go through it.

Google Colab Link: https://colab.research.google.com/drive/1zrBibaeAZErSuihjwSvlXeDNSHOZ1PwT?usp=sharing
Kindly let me know if this is a bug and if there is any alternative to achieve this functionality.

Edit: I apologize, the colab link wasn't public. You can visit it now. @Mizux 

Thank you in Advance

**Anything else we should know about your project / environment**

**Comment by Mizux** [comment]
By default empty vehicles are not considered, in your case simply add:

```python
    for vehicle_id in range(data['num_vehicles']):
        routing.ConsiderEmptyRouteCostsForVehicle(True, vehicle_id)
```
note: can also be added to your existing loop

potential output
```
Route for vehicle 0:
 0 Load(0) ->  8 Load(8) ->  0 Load(8)
Distance of the route: 616m
Load of the route: 8

Route for vehicle 1:
 0 Load(0) ->  13 Load(4) ->  15 Load(12) ->  11 Load(13) ->  12 Load(15) ->  0 Load(15)
Distance of the route: 1552m
Load of the route: 15

Route for vehicle 2:
 0 Load(0) ->  10 Load(2) ->  16 Load(10) ->  14 Load(14) ->  9 Load(15) ->  0 Load(15)
Distance of the route: 1552m
Load of the route: 15

Route for vehicle 3:
 0 Load(0) ->  7 Load(8) ->  0 Load(8)
Distance of the route: 388m
Load of the route: 8

Route for vehicle 4:
 0 Load(0) ->  4 Load(4) ->  3 Load(6) ->  1 Load(7) ->  2 Load(8) ->  6 Load(12) ->  5 Load(14) ->  0 Load(14)
Distance of the route: 2464m
Load of the route: 14

Total distance of all routes: 6572m
Total load of all routes: 60
The objective cost value is: 6572
```
