### ISSUE TITLE
C++ simple example not working

### ISSUE THREAD

**Issue by sampaiogil** [google/or-tools#2385]
**What version of OR-tools and what language are you using?**
Version: 8.1.
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

**What operating system (Linux, Windows, ...) and version?**
W10 - VS2019
**What did you do?**
1. Go to "Get Started with OR-Tools for C++"
2. Try to run the example:
```cpp
// Create the linear solver with the GLOP backend.
  MPSolver* solver = MPSolver::CreateSolver("GLOP");

  // Create the variables x and y.
  MPVariable* const x = solver->MakeNumVar(0.0, 1, "x");
  MPVariable* const y = solver->MakeNumVar(0.0, 2, "y");

  LOG(INFO) << "Number of variables = " << solver->NumVariables();

  // Create a linear constraint, 0 <= x + y <= 2.
  MPConstraint* const ct = solver->MakeRowConstraint(0.0, 2.0, "ct");
  ct->SetCoefficient(x, 1);
  ct->SetCoefficient(y, 1);

  LOG(INFO) << "Number of constraints = " << solver->NumConstraints();

  // Create the objective function, 3 * x + y.
  MPObjective* const objective = solver->MutableObjective();
  objective->SetCoefficient(x, 3);
  objective->SetCoefficient(y, 1);
  objective->SetMaximization();

  solver->Solve();

  LOG(INFO) << "Solution:" << std::endl;
  LOG(INFO) << "Objective value = " << objective->Value();
  LOG(INFO) << "x = " << x->solution_value();
  LOG(INFO) << "y = " << y->solution_value();
```
**What did you expect to see**
Should work.
**What did you see instead?**
```solver->NumConstraints();``` outputs 0. Exception thrown when setting the coefficients of the objective function. 

**Anything else we should know about your project / environment**

**Comment by Mizux** [comment]
Few questions:
- Did you build OR-Tools from source or use a prebuilt binary ?
- Did you use an IDE (e.g. Visual Studio) ?
- How did you try to run the example ? which command line ? did you use the Makefile ?
- What was the exact error message ?

**Comment by sampaiogil** [comment]
Hi,

I built it from source as described here: https://github.com/google/or-tools/issues/2335#issuecomment-773600256

It seemed to be working but when running my code in debug mode (Visual Studio 2019) it crashed. So, I put the example code inside my project and tried again. It crashed.

![ortoolscrash](https://user-images.githubusercontent.com/78749012/107253650-6de9a280-6a2e-11eb-9aa6-dd42cba48894.jpg)

**Comment by lperron** [comment]
tested it on release on master

I00-1 -1:-1:-1.842285 10228 lp_test.cc:133] MutableObjectiveCrash
I00-1 -1:-1:-1.578613 10228 lp_test.cc:141] Number of variables = 2
I00-1 -1:-1:-1.724121 10228 lp_test.cc:148] Number of constraints = 1
I00-1 -1:-1:-1.977294 10228 lp_test.cc:158] Solution:
I00-1 -1:-1:-1.129882 10228 lp_test.cc:159] Objective value = 4
I00-1 -1:-1:-1.249511 10228 lp_test.cc:160] x = 1
I00-1 -1:-1:-1.312744 10228 lp_test.cc:161] y = 1

works fine

**Comment by lperron** [comment]
is the solver object non null ?

**Comment by sampaiogil** [comment]
The solver is non null, but the objective is (```solver->MutableObjective()``` seems to return null)

.![ortoolssolver](https://user-images.githubusercontent.com/78749012/107259183-9aa0b880-6a34-11eb-88e7-2167e14b9258.jpg)

**Comment by sampaiogil** [comment]
Hi,

I ran the same code but now in Release mode and the problem remains. For instance, the number of constraints printed to the console is 0.

**Comment by lperron** [comment]
Not when I run it.

Your build process seems broke .

Le lun. 8 févr. 2021 à 20:13, sampaiogil <notifications@github.com> a
écrit :

**Comment by sampaiogil** [comment]
This is strange. I created a new project in Visual Studio and tried the following code (simple_lp_program.cc). It works with v7.8 but not with v8.0 or v8.1. However, if I run ```tools\make test_cc``` , this example works.

```
#include "ortools/linear_solver/linear_solver.h"
// [END import]

namespace operations_research {
void SimpleLpProgram() {
  // [START solver]
  // Create the linear solver with the GLOP backend.
  MPSolver solver("simple_lp_program", MPSolver::GLOP_LINEAR_PROGRAMMING);
  // [END solver]

  // [START variables]
  // Create the variables x and y.
  MPVariable* const x = solver.MakeNumVar(0.0, 1, "x");
  MPVariable* const y = solver.MakeNumVar(0.0, 2, "y");

  LOG(INFO) << "Number of variables = " << solver.NumVariables();
  // [END variables]

  // [START constraints]
  // Create a linear constraint, 0 <= x + y <= 2.
  MPConstraint* const ct = solver.MakeRowConstraint(0.0, 2.0, "ct");
  ct->SetCoefficient(x, 1);
  ct->SetCoefficient(y, 1);

  LOG(INFO) << "Number of constraints = " << solver.NumConstraints();
  // [END constraints]

  // [START objective]
  // Create the objective function, 3 * x + y.
  MPObjective* const objective = solver.MutableObjective();
  objective->SetCoefficient(x, 3);
  objective->SetCoefficient(y, 1);
  objective->SetMaximization();
  // [END objective]

  // [START solve]
  solver.Solve();
  // [END solve]

  // [START print_solution]
  LOG(INFO) << "Solution:" << std::endl;
  LOG(INFO) << "Objective value = " << objective->Value();
  LOG(INFO) << "x = " << x->solution_value();
  LOG(INFO) << "y = " << y->solution_value();
  // [END print_solution]
}
}  // namespace operations_research

int main() {
  operations_research::SimpleLpProgram();
  return EXIT_SUCCESS;
}
```

**Comment by Mizux** [comment]
so if i understand correctly you create a VS project from scratch ?
Did you replicate all compile flags and link flags ?

see: https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/tools/Makefile.cc.java.dotnet#L125-L135

**Comment by sampaiogil** [comment]
Since it was not even working in Release mode, I did the following:

1. Downloaded the binaries (v8.0, v7.8)
2. Created a new VS project using the simple_lp_program.cc example.
3. Linked against the binaries
4. Run

v8.0:
![image](https://user-images.githubusercontent.com/78749012/107354020-94a6e800-6ac5-11eb-9533-f9253b5ed002.png)

v7.8:
![image](https://user-images.githubusercontent.com/78749012/107354311-e8193600-6ac5-11eb-8304-5de2d895d518.png)

**Comment by lperron** [comment]
Are you compiling in C++17 ? That was the change between 7.x and 8.x.

As I said, when I compile it myself with the right flags, it works fine.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 9 févr. 2021 à 12:00, sampaiogil <notifications@github.com> a
écrit :

**Comment by sampaiogil** [comment]
I was using the default standard for VS 2019. With v8.0, if I try to change to C++17 I get several compilation errors. Changing to C++14, it runs but produces the output I posted above (so I assume this is the default).

> 
> As I said, when I compile it myself with the right flags, it works fine. 

What do you mean with the right flags? Right now I'm not compiling the library. I'm only compiling the example while linking against the binaries available on github.

**Comment by sampaiogil** [comment]
I got it working with C++17! That's it.

The compilation errors were removed with this in the VS command line: /D _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS

I'll go back now to the compilation of the library in Debug mode. Thanks!
