### ISSUE TITLE
Error in Customization of objective function

### ISSUE THREAD

**Issue by hrushk** [google/or-tools#2386]
**What version of OR-tools and what language are you using?**
Version: 7.8.7959
Language: Python

**Which solver are you using 
Routing Solver

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
Steps to reproduce the behaviour:
1. Working with VRPT
2. Modified the objective from :
`# Instantiate route start and end times to produce feasible times.
 for i in range(data['num_vehicles']):
        routing.AddVariableMinimizedByFinalizer(
            time_dimension.CumulVar(routing.Start(i)))
        routing.AddVariableMinimizedByFinalizer(
            time_dimension.CumulVar(routing.End(i)))`
to
`for i in range(data['num_vehicles']):
        routing.AddVariableMinimizedByFinalizer(
            ((time_dimension.CumulVar(routing.Start(i)))//10)*10)
        routing.AddVariableMinimizedByFinalizer(
            ((time_dimension.CumulVar(routing.End(i)))//10)*10)`

& following too:
`for i in range(data['num_vehicles']):
        routing.AddVariableMinimizedByFinalizer(
            ((time_dimension.CumulVar(routing.End(i)))//10)*10-((time_dimension.CumulVar(routing.Start(i)))//10)*10)`

**What did you expect to see**
Should work with modified objective

**What did you see instead?**
TypeError: in method 'RoutingModel_AddVariableMinimizedByFinalizer', argument 2 of type 'operations_research::IntVar *'

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
I understand that it is a type error caused because of division by 10. What I am trying to do is to optimize route cost in unit of 10. 
Eg. If a vehicle travel from time 11 to 34, the usual cost should be 23 units, but since I want to do in units of 10, the cost will be from 10 to 30 which is 20 units. Can anyone please tell me the correct way to do this?
Any help would be really appreciated.

**Comment by lperron** [comment]
time_dimension.CumulVar(routing.Start(i)))//10)*10 is not a variable.

Furthermore, AddVariableMinimizedByFinalizer does not modify the objective.
