### ISSUE TITLE
Warning: Model trivially infeasible by bound comparison in LowerOrEqual()

### ISSUE THREAD

**Issue by ktnr** [google/or-tools#2389]
Version: master/v8.2
Language: C++
Solver: CP-SAT
Windows Server 2012

We are repeatedly solving fairly large CP models in MIP callbacks (gurobi). Very rarely we see a warning:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
W00-1 -1:-1:-1.525878 38360 integer.h:1515] Model trivially infeasible, variable 2 has lower bound 57 and LowerOrEqual() was called with an upper bound of 31
```

We don't expect to see any warning of this kind, just for the model status to return infeasible without the warning. How must we interpret this warning? Can we safely ignore it? Or might this be indicative of an error in the model?

Unfortunately it's hard for us to reliably reproduce this warning in order to write the model that causes it.
Any suggestions on how to dig down to the root cause? We could modify the source code around [ortools/sat/integer.h#L1494](https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/ortools/sat/integer.h#L1494) and write the model to a file etc... Is there an easier way?

**Comment by lperron** [comment]
The warning is harmless. It just tells you that you are creating an
infeasible model.

We will clean that up.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
