### ISSUE TITLE
Different values of optimal solution from CP-SAT 8.1

### ISSUE THREAD

**Issue by prissky** [google/or-tools#2393]
**Version:** v8.1
**Language:** C++
**Solver:** CP-SAT
**OS:** Windows/Debian

**Steps to reproduce the behavior:**
1. Load [model.zip](https://github.com/google/or-tools/files/5971313/model.zip) from proto-file and solve repeatedly.
2. Observe different values of objective function declared OPTIMAL or even model to be INFEASIBLE.

**I expected to see:**
Same optimal value of objective function each run.

**Instead I saw:**
Inconsistent behavior. 

**Anything else we should know about your project / environment**
Issue is apparently already fixed on Master. 
Related to #2283?

**Comment by Mizux** [comment]
recall me #2340

**Comment by lperron** [comment]
No, this is the same OS.
Do you use multiple search workers ?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by prissky** [comment]
Yes, 8 search workers.

**Comment by lperron** [comment]
I ran multiple times with master. It reliably find the same solution.
Closing the issue, reopen if the big is still present.
