### ISSUE TITLE
AddMultipleEquality() does not exist in C#

### ISSUE THREAD

**Issue by ozizi1** [google/or-tools#2394]
**What version of OR-tools and what language are you using?**
Version: 8.1.8487
Language: C#
Solver ; CP-SAT
OS : Windows 10

**What did you expect to see**

I was expecting being able to call the function model.AddMultipleEquality() but it does not exist in c#

**What did you see instead?**

model.AddProdEquality() is available but I read online that it was depreciated.

**Comment by lperron** [comment]
The deprecation is just because of renaming.
I will add the missing method.

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Please note the correct name: AddMultiplicationEquality()

**Comment by ozizi1** [comment]
Thanks
