### ISSUE TITLE
incorrect range in add_soft_sequence_constraint function of shift_scheduling_sat.py

### ISSUE THREAD

**Issue by Fan-Han** [google/or-tools#2396]
**What version of OR-tools and what language are you using?**
Version: 7.4.7247
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you expect to see**
After running add_soft_sequence_constraint function with hard_max = 5, I expect to see length of consecutive true variables should be no more than 5.
`for start in range(len(works) - hard_max - 1):
        model.AddBoolOr(
            [works[i].Not() for i in range(start, start + hard_max + 1)])`

**What did you see instead?**
Sequences of true variables are longer than 5. This only happens in the last rolling subsequence.

I assume the issue is that the range in the outer loop should be `for start in range(len(works) - hard_max)`, otherwise the last subsequence at the end of sequence will not be covered.

**Comment by stradivari96** [comment]
There is a bug in your code:
your for loop should be `for start in range(len(works) - hard_max + 1):`

See see: https://github.com/google/or-tools/issues/1399

**Comment by lperron** [comment]
Indeed, this code was scrutinized multiple times.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 15 févr. 2021 à 15:48, Xiang Chen <notifications@github.com> a
écrit :

**Comment by stradivari96** [comment]
Ah my bad, you are right @Fan-Han , the `-1` should be removed here:
https://github.com/google/or-tools/blob/1d9174516f6a6f9ca87c741b01f216dbc661606e/examples/python/shift_scheduling_sat.py#L123

**Comment by Fan-Han** [comment]
Yes, just found the same issue has been mentioned in #1399. This bug is still in the stable branch.
Good to know it has been noticed.

**Comment by lperron** [comment]
Ok, maybe this is the right fix.

Will submit it right away.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
