### ISSUE TITLE
Add support for building with other C++ compilers?

### ISSUE THREAD

**Issue by pfetsch** [google/or-tools#2397]
`make CXX=<path to some gcc version>/bin/g++ third_party` seems to work, but
`make CXX=<path to some gcc version>/bin/g++ cc` does not, i.e., the changed compiler is ignored.

Can support for this be added?

I am asking because the standard compiler on one of the machine I am using is an old gcc (5.4.0), which does not work:
`./ortools/constraint_solver/local_search.cc: In member function ‘void operations_research::LocalSearchFilterManager::Revert()’:
./ortools/constraint_solver/local_search.cc:3896:10: error: expected unqualified-id before ‘[’ token
     auto [filter, event_type] = filter_events_[i];`

**Comment by lperron** [comment]
You need  c++17 mode.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
and you should use the cmake build.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by pfetsch** [comment]
O.k.  - thanks! This should work.
I followed the documentation which currently only lists `make`. But you will probably change this.
