### ISSUE TITLE
Cases for linear assignment algorithm

### ISSUE THREAD

**Issue by kaelchan** [google/or-tools#240]
I was trying to choose an algorithm for linear assignment problem (or bipartite maximum weight matching). I  found the csa algorithm as suggested in this library and compared it with the normal KM algorithm (n^3 version, the version with slack optimization).
Normally it's better, but when it comes to the cases when lefthand side and righthand side are quite different in size.
For example, I generate the input data as following:
100 left hand side nodes, 1000 right hand side nodes and the sparse rate from 1.0, 0.5, 0.1 to 0.01. (The arcs are randomly chosen with a cost randomly chosen from 0 ~ 10^6. The rest of the cost matrix are filled with 0.)
The csa runs approximately 20 times slower than KM.

Have you encountered this problem?

**Comment by lperron** [comment]
Yes. 

Have you tried min cost flow? I do not know how it would perform. But at least, you do not need to fill in with 0s.
