### ISSUE TITLE
Bazel build without SCIP

### ISSUE THREAD

**Issue by joshburkart** [google/or-tools#2402]
**What language and solver does this apply to?**

C++. Routing.

**Describe the problem you are trying to solve.**

I'd like to build and use OR-Tools' routing libraries (specifically traveling salesman) with Bazel, but I don't want to include SCIP if possible since it isn't permissively licensed. Is there some way this can be achieved? Is SCIP required for routing?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Mizux** [comment]
Hi,

- SCIP is not used by routing source code
- SCIP is default use by linear_solver
- Using CMake based build you can disable SCIP support
