### ISSUE TITLE
Minor memory leak in c++ samples using MPSolver::CreateSolver()

### ISSUE THREAD

**Issue by hevrard** [google/or-tools#2411]
**What version of OR-tools and what language are you using?**
Version: master
Language: C++

A few C++ samples such as `ortools/linear_solver/samples/basic_example.cc` use `MPSolver::CreateSolver()` to obtain a pointer to a solver object, which is effectively created with:

https://github.com/google/or-tools/blob/b77bd3ac69b7f3bb02f55b7bab6cbb4bab3917f2/ortools/linear_solver/linear_solver.cc#L613

and the resulting pointer is never `delete`'d by the sample, resulting in a leak:

```

valgrind ./bin/basic_example 
...
==284285== HEAP SUMMARY:
==284285==     in use at exit: 155,472 bytes in 2,319 blocks
==284285==   total heap usage: 9,863 allocs, 7,544 frees, 835,570 bytes allocated
==284285== 
==284285== LEAK SUMMARY:
==284285==    definitely lost: 400 bytes in 1 blocks
==284285==    indirectly lost: 3,207 bytes in 40 blocks
==284285==      possibly lost: 0 bytes in 0 blocks
==284285==    still reachable: 151,865 bytes in 2,278 blocks
==284285==         suppressed: 0 bytes in 0 blocks
==284285== Rerun with --leak-check=full to see details of leaked memory
==284285== 
==284285== For lists of detected and suppressed errors, rerun with: -s
==284285== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
...
```

One can think of using `std::unique_ptr` to track the MPSolver object and avoid the leak.

But also, it might be OK to not bother about this in such demo samples.

**Comment by Mizux** [comment]
good catch !

Since few people may use these samples as skeleton to integrate or-tools in their own apps/program I think we should fix it IMHO
