### ISSUE TITLE
Filtering redundant cumulatives

### ISSUE THREAD

**Issue by prissky** [google/or-tools#2413]
**What language and solver does this apply to?**
All / CP-SAT

**Describe the problem you are trying to solve.**
Adding cumulative constraint with a sum of demands lower than its capacity makes the model unnecessarily larger.

**Describe the solution you'd like**
_CpModelPresolver::PresolveCumulative()_ could detect redundant cumulative (as it already filters zero demands and empty intervals). 

**Describe alternatives you've considered**
Alternatively, validity of cumulative could be tested already when creating the model.

**Additional context**
This seems to be a common case in scheduling with renewable resources.

**Comment by lperron** [comment]
fixed. Thanks for the suggestion.

**Comment by lperron** [comment]
closed by: https://github.com/google/or-tools/commit/4e47a4b46c9b4718414ac7b3edc915b2556c8118
