### ISSUE TITLE
Where can i find full detailed documentation of this library?

### ISSUE THREAD

**Issue by goodvanity** [google/or-tools#2415]
I use or-tools for python and when i want to see the source code i find this:

```
def Solver_IntVar(*args, **kwargs): # real signature unknown
    """ Creates an integer variable. """
    pass
```
Where can i find full documentation of classes, methods which is used in examples? 
This docs https://developers.google.com/optimization/introduction/overview is very very poor. I want to see a list of methods and their full detailed description, and examples of usage of each method/class. 

For example if i use SCIP:
`solver = pywraplp.Solver.CreateSolver('SCIP')`

Where can i find list of methods of this solver and their description(how to use it and what for)?

**Comment by Mizux** [comment]
https://google.github.io/or-tools/
