### ISSUE TITLE
Negation of constants CP-SAT

### ISSUE THREAD

**Issue by stradivari96** [google/or-tools#2419]
**What version of OR-tools and what language are you using?**
Version: 8.1.8487
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
A weird model reported by someone on discord: https://discord.com/channels/693088862481678374/719201939971113001/816253290261250058
```python
from ortools.sat.python import cp_model

model = cp_model.CpModel()
a = model.NewConstant(1)
b = model.NewConstant(1)
c = model.NewBoolVar("")

model.AddBoolAnd([a, b]).OnlyEnforceIf(c)
model.AddBoolOr([a.Not(), b.Not()]).OnlyEnforceIf(c.Not())
# model.Add(c == 1)  # Returns OPTIMAL

solver = cp_model.CpSolver()
solver.Solve(model)
print(solver.StatusName())
```

**What did you expect to see**
`FEASIBLE/OPTIMAL`

**What did you see instead?**
`INFEASIBLE`

**Comment by lperron** [comment]
Thanks, looking at it.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
