### ISSUE TITLE
Java maven packaging error

### ISSUE THREAD

**Issue by roborobotheart** [google/or-tools#2428]
**What version of OR-Tools and what language are you using?**
Java 1.8, maven 3.6.0, ortools 8.1.8487 

**What operating system (Linux, Windows, ...) and version?**
macOS 10.15.4

**What did you do?**
1. Add released ortools jar in my project, with other dependency like: jna-platform, jna, protobuf-java

```pom.xml
        <dependency>
            <groupId>com.google.ortools</groupId>
            <artifactId>ortools-java</artifactId>
            <version>8.1.8487</version>
        </dependency>

        <dependency>
            <groupId>com.google.ortools</groupId>
            <artifactId>ortools-darwin</artifactId>
            <version>8.1.8487</version>
            <scope>runtime</scope>
        </dependency>
```

2. Run the project in IntelliJ IDEA. It works well

3. Packaging the project as jar file. And run "java -jar XXX.jar",  it throws following error:
```
  java.lang.RuntimeException: java.nio.file.NoSuchFileException: /BOOT-INF/lib/ortools-darwin-8.1.8487.jar!/darwin/
	at com.google.ortools.Loader.loadNativeLibraries(Loader.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
**What did you expect to see**
Any instructions or suggestions to help solve this issue

**Comment by Mizux** [comment]
Did you try `mvn package` instead ?

Currently I'm testing the integration with https://github.com/or-tools/java_or-tools 
todo(mizux): I should try to add a "mvn package"

**Comment by roborobotheart** [comment]
I made little adjustment of native-utils method to load native file in jar, and used `mvn package`, it works well

**Comment by Robot-1x** [comment]
I have reproduce this issue. In normal maven project, original released package works well. Test command is as follow:

`java -cp XXXXX.jar LinearProgramming`

But in my springframework restful service maven project, it does not work. My pom is as follow:

`<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.ortools</groupId>
            <artifactId>ortools-java</artifactId>
            <version>9.0.9048</version>
        </dependency>

        <dependency>
            <groupId>com.google.ortools</groupId>
            <artifactId>ortools-darwin</artifactId>
            <version>9.0.9048</version>
        </dependency>

        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna-platform</artifactId>
            <version>5.8.0</version>
        </dependency>

        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>5.8.0</version>
        </dependency>

        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.15.8</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>`

Test command is as follow:

`java -jar XXXX.jar`

And curl request URL get:

`
java.nio.file.NoSuchFileException: /BOOT-INF/lib/ortools-darwin-9.0.9048.jar!/darwin-x86-64/
	at com.sun.nio.zipfs.ZipPath.getAttributes(ZipPath.java:666) ~[zipfs.jar:1.8.0_192]
	at com.sun.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:294) ~[zipfs.jar:1.8.0_192]
`

My adjustment is add a loader file in native file jar package:

`
public class Loader {
    private static final int MIN_PREFIX_LENGTH = 3;
    public static final String NATIVE_FOLDER_PATH_PREFIX = "nativeutils_tmp";
    private static File temporaryDir;
    private static boolean loaded;
    
    public static void loadNativeLibraries() {
        if(!Loader.loaded){
            try {
                loadLibraryFromJar("/darwin");
                Loader.loaded = true;
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
    }
    
    public static void loadLibraryFromJar(String path) throws IOException {
        if (null == path || !path.startsWith("/")) {
            throw new IllegalArgumentException("The path has to be absolute (start with '/').");
        }
        if(!path.endsWith("/")){
            path += "/";
        }
        String[] files = { "libortools.dylib", "libjniortools.dylib"};
        if (temporaryDir == null) {
            temporaryDir = createTempDirectory(NATIVE_FOLDER_PATH_PREFIX);
            temporaryDir.deleteOnExit();
        }
        List<String> tempPathList = new ArrayList<>();
        for (String file : files) {
            File temp = new File(temporaryDir, file);
            try (InputStream is = NativeUtils.class.getResourceAsStream(path + file)) {
                Files.copy(is, temp.toPath(), StandardCopyOption.REPLACE_EXISTING);
                tempPathList.add(temp.getAbsolutePath());
            } catch (IOException e) {
                temp.delete();
                throw e;
            } catch (NullPointerException e) {
                temp.delete();
                throw new FileNotFoundException("File " + path + " was not found inside JAR.");
            }
        }

        for(String temPath : tempPathList){
            System.load(temPath);
        }
        for(String temPath : tempPathList){
            File temp = new File(temPath);
            if (isPosixCompliant()) {
                temp.delete();
            } else {
                temp.deleteOnExit();
            }
        }
    }

    private static boolean isPosixCompliant() {
        try {
            return FileSystems.getDefault()
                    .supportedFileAttributeViews()
                    .contains("posix");
        } catch (FileSystemNotFoundException
                | ProviderNotFoundException
                | SecurityException e) {
            return false;
        }
    }

    private static File createTempDirectory(String prefix) throws IOException {
        String tempDir = System.getProperty("java.io.tmpdir");
        File generatedDir = new File(tempDir, prefix);

        if(!generatedDir.exists()){
            if(!generatedDir.mkdir()){
                throw new IOException("Failed to create temp directory " + generatedDir.getName());
            }
        } else {
            System.out.println("Directory already exists.");
        }
        return generatedDir;
    }
    
    static {
        Loader.loaded = false;
    }
}
`

**Comment by diwayou** [comment]
if you use spring boot package,you can use the code below to replace the default lib loader
`
import com.sun.jna.Platform;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.*;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

public class SpringBootOrToolsNativeLoader {

    private static final String RESOURCE_PATH;
    private static boolean loaded;

    private static URI getNativeResourceURI() throws IOException {
        ClassLoader loader = com.google.ortools.Loader.class.getClassLoader();
        URL resourceURL = loader.getResource(RESOURCE_PATH);
        Objects.requireNonNull(resourceURL, String.format("Resource %s was not found in ClassLoader %s", RESOURCE_PATH, loader));

        try {
            URI resourceURI = resourceURL.toURI();
            return resourceURI;
        } catch (URISyntaxException var4) {
            throw new IOException(var4);
        }
    }

    private static Path unpackNativeResources(URI resourceURI) throws IOException {
        Path tempPath = Files.createTempDirectory("ortools-java");
        tempPath.toFile().deleteOnExit();
        PathConsumer<?> visitor = (sourcePath) -> {
            Files.walkFileTree(sourcePath, new SimpleFileVisitor<Path>() {
                public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
                    Path newPath = tempPath.resolve(sourcePath.getParent().relativize(file).toString());
                    Files.copy(file, newPath);
                    newPath.toFile().deleteOnExit();
                    return FileVisitResult.CONTINUE;
                }

                public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException {
                    Path newPath = tempPath.resolve(sourcePath.getParent().relativize(dir).toString());
                    Files.copy(dir, newPath);
                    newPath.toFile().deleteOnExit();
                    return FileVisitResult.CONTINUE;
                }
            });
        };

        List<URI> uris = prepURIs(resourceURI);
        visitUriRecursionHelper(FileSystems.getDefault(), uris, visitor);
        return tempPath;
    }

    private static <E extends IOException> void visitUriRecursionHelper(FileSystem fs, List<URI> uris, PathConsumer<E> visitor) throws IOException {
        URI uri = uris.get(0);

        Path path;
        if (fs.provider().getScheme().equals("jar")) {
            // Custom URI parsing here because of a JDK bug
            String spec = uri.getSchemeSpecificPart();
            int sep = spec.lastIndexOf("!/");
            if (sep == -1)
                throw new IllegalArgumentException("URI: "
                        + uri
                        + " does not contain path info ex. jar:file:/c:/foo.zip!/BAR");
            path = fs.getPath(spec.substring(sep + 1));
        } else {
            path = fs.provider().getPath(uri);
        }

        if (uris.size() <= 1) {
            visitor.accept(path);
        } else {
            try (FileSystem newFs = FileSystems.newFileSystem(path, (ClassLoader) null)) {
                visitUriRecursionHelper(newFs, uris.subList(1, uris.size()), visitor);
            } catch (Exception e) {
                Path tmpPath = Files.createTempFile(null,".jar");
                Files.copy(path, tmpPath, StandardCopyOption.REPLACE_EXISTING);
                tmpPath.toFile().deleteOnExit();
                try (FileSystem nestFs = FileSystems.newFileSystem(tmpPath, null)) {
                    visitUriRecursionHelper(nestFs, uris.subList(1, uris.size()), visitor);
                }
            }
        }
    }

    private static ArrayList<URI> prepURIs(URI uri) {
        uri = fixSpringUri(uri);
        ArrayList<URI> uris = new ArrayList<>();
        uris.add(uri);
        while (!uri.getScheme().equals("file")) {
            String end = uri.getRawSchemeSpecificPart();
            String newUri = end.substring(0, end.lastIndexOf("!/"));
            try {
                uri = new URI(newUri);
            } catch (URISyntaxException e) {
                throw new IllegalStateException(String.format("Unexpectedly formed an invalid URI: \"%s\"", newUri), e);
            }
            uris.add(uri);
        }
        Collections.reverse(uris);
        return uris;
    }

    private static URI fixSpringUri(URI uri) {
        int jars = numMatches(uri.toString(), "jar:");
        int jarEnds = numMatches(uri.toString(), "!/");

        while (jars < jarEnds) {
            try {
                uri = new URI("jar:" + uri);
            } catch (URISyntaxException e) {
                throw new IllegalStateException(String.format("Unexpectedly formed an invalid URI: \"jar:%s\"", uri), e);
            }
            jars++;
        }

        return uri;
    }

    private static int numMatches(final String s, final String toFind) {
        int num = 0;
        int index = 0;
        while ((index = s.indexOf(toFind, index)) != -1) {
            index += toFind.length();
            num++;
        }
        return num;
    }

    public static synchronized void loadNativeLibraries() {
        if (!loaded) {
            try {
                URI resourceURI = getNativeResourceURI();
                Path tempPath = unpackNativeResources(resourceURI);
                System.load(tempPath.resolve(RESOURCE_PATH).resolve(System.mapLibraryName("jniortools")).toString());
                loaded = true;
            } catch (IOException var2) {
                throw new RuntimeException(var2);
            }
        }

    }

    static {
        RESOURCE_PATH = "ortools-" + Platform.RESOURCE_PREFIX + "/";
        loaded = false;
    }

    @FunctionalInterface
    private interface PathConsumer<T extends IOException> {
        void accept(Path var1) throws T;
    }
}
`
