### ISSUE TITLE
Visual Studio Soln does not work

### ISSUE THREAD

**Issue by screig** [google/or-tools#243]
Unzipping the package....

sln file cannot find project files..... move solution file

the sln sits under the examples folder
below that are four folders, com, cpp, cshrp....

the sln looks for the project files here:
`Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "RabbitsPheasants", "solution\RabbitsPheasants.csproj", "{E7AFEF5F-7580-45B0-A8F1-8B63CDF73A51}"`
it omits the cshrp folder

projects are built with 4.0 client framework, the two dlls are incompatible

```
    <AssemblyName>Flow</AssemblyName>
    <TargetFrameworkVersion>v4.0</TargetFrameworkVersion>
    <TargetFrameworkProfile>Client</TargetFrameworkProfile>
```

all projects need to be changed to 4.5
all references to the dlls don't work, cant find them
dlls need to be moved and re included 

After that we can compile.

**Comment by Mizux** [comment]
Hi,

Now we only provide CMake, Makefile and Bazel based build.
