### ISSUE TITLE
No module named 'ortools'

### ISSUE THREAD

**Issue by C4PTUNAMUR1CA** [google/or-tools#2432]
Hey,

I have been working with ortools in the atom IDE for python, and it worked fine. I decided to switch to spyder IDE for python, and I get the error: No module named 'ortools' when i try to import ortools through 'from ortools.constraint_solver import routing_enums_pb2'.
I checked the other issues (like this one https://github.com/google/or-tools/issues/737) that had the same error message, but nothing seemed to work. I can install ortools through 'python -m pip install -U --user ortools', and I run python 3.9.0
![image](https://user-images.githubusercontent.com/80104196/110774567-3a34af00-825e-11eb-96b5-14a73971112e.png)

Thanks in advance!

With regards,
Nikita

**Comment by Mizux** [comment]
Are you sure to have the **VS 2019** redistributable on your system ?

**Comment by C4PTUNAMUR1CA** [comment]
Yes, I also have installed VS 2019, in November/December.

**Comment by Mizux** [comment]
can you try:
```
python -vb -c "from ortools.constraint_solver import routing_enums_pb2"
```
and give us the trace ?

**Comment by C4PTUNAMUR1CA** [comment]
What do you exactly mean with the trace? when entering above command, it gave me a long output several hundreds of lines, dont know what you are exactly searching for? I presume though that Spyder does not access my site-packages, I will check up on that.

**Comment by stradivari96** [comment]
My guess is that spyder is using another python environment

**Comment by C4PTUNAMUR1CA** [comment]
Yes, the problem was indeed that spyder was in a different environment. Opening in the same environment works now! Thanks!
