### ISSUE TITLE
 How to install Google OR-Tools on Eclipse on macOS?

### ISSUE THREAD

**Issue by Westlife1002** [google/or-tools#2435]
I was trying to add com.google.ortools.jar and protobuf.jar to the build path following the smilar way: https://stackoverflow.com/questions/56303148/how-to-install-google-or-tools-for-an-intellij-project-on-macos 
but there seems to be some errors in"

`import com.google.ortools.Loader;`

and
```
    Loader.loadNativeLibraries();
    // Create the linear solver with the GLOP backend.
    MPSolver solver = MPSolver.createSolver("GLOP");
```

BTW, in the latest binary version, there is no such jar file as "com.google.ortools.jar and protobuf.jar"

**Comment by Mizux** [comment]
Please take a look at: https://github.com/or-tools/java_or-tools

**Comment by Mizux** [comment]
strange, FYI our `Loader.java` rely on:
https://github.com/google/or-tools/blob/fa84bc05e72641dddfbb98164d81b8bc9bef6ea5/ortools/java/pom-local.xml.in#L65-L69

**Comment by Westlife1002** [comment]
I am new to java and have no idea about above. Could you provide more details? step by step guide?

**Comment by Westlife1002** [comment]
is it something to do with jna library missing?

**Comment by masmil1988** [comment]
> strange, FYI our `Loader.java` rely on:
> 
> https://github.com/google/or-tools/blob/fa84bc05e72641dddfbb98164d81b8bc9bef6ea5/ortools/java/pom-local.xml.in#L65-L69

For me, the problem has been solved by importing jna-platform
