### ISSUE TITLE
Incorrect time of a solution shown

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#2436]
**What version of OR-Tools and what language are you using?**
Version: v8.2
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Debian 10

**What did you do?**
I loaded proto file and executed it.
My extra code displayed every 10 seconds number of used memory and time in seconds from beginning of execution.

**What did you expect to see**
Correct time when a solution was found.

**What did you see instead?**
After 430s of execution, a time displayed by my code jumped to value 2675. Time of next solution of cp-sat solver had similar offset, a value 2805.60s althought it should be less than 600s based on number of lines with used memory.

**Anything else we should know about your project / environment**
I experienced the problem only once, maybe my usage of chrono library was not correct, but I think there's a still chance that something is wrong inside cp-sat solver.
[Files.zip](https://github.com/google/or-tools/files/6143215/Files.zip)

**Comment by lperron** [comment]
I am not doing anything fancy.
Just the right system call.

**Comment by gregy4** [comment]
I thought about reasons of incorrect time, there seems to be two candidates - virtualbox and changes of time during execution of cp-sat solver caused by daylight savings, sleep&resume of a computer.

An experiment with change of time during execution showed that a time of a solution is affected by this. It seems to me that steady_clock from chrono library should be used since it is not affected by changes of time during execution.

             https://en.cppreference.com/w/cpp/chrono/steady_clock

**Comment by Mizux** [comment]
Since we are using Google's abseil-cpp as C++ library wrapper for time management.
You should open  an issue there...

**Comment by Mizux** [comment]
https://github.com/abseil/abseil-cpp/blob/2e9532cc6c701a8323d0cffb468999ab804095ab/absl/time/clock.cc#L39-L47
and
https://github.com/abseil/abseil-cpp/blob/master/absl/time/internal/get_current_time_chrono.inc or
https://github.com/abseil/abseil-cpp/blob/master/absl/time/internal/get_current_time_posix.inc

**Comment by gregy4** [comment]
Thanks for links, the last two files showed that is used system_clock or CLOCK_REALTIME that are both worse variants to steady_clock and CLOCK_MONOTONIC_RAW.
    https://linux.die.net/man/2/clock_gettime

I looked briefly into abseil and steady_clock is mentioned only in one internal class so it seems that functionality to correctly measure time is not present in abseil library. In issue https://github.com/abseil/abseil-cpp/issues/172 is answered same question and the answer is use steady_clock from chrono library.

**Comment by Mizux** [comment]
```
[0]─[~/work/master/ortools/sat]
[*v*]─mizux@nuc10i7 %grepc -rIin "Now()" ..
../sat/cp_model_presolve.cc:5178:  context_->deductions.MarkProcessingAsDoneForNow();
../sat/presolve_util.h:67:  void MarkProcessingAsDoneForNow() {
../util/time_limit.h:65: * The call itself is as fast as CycleClock::Now() + a few trivial instructions,
../constraint_solver/routing.h:1338:    return limit_->AbsoluteSolverDeadline() - solver_->Now();
../constraint_solver/constraint_solver.cc:1524:absl::Time Solver::Now() const {
../constraint_solver/search.cc:3954:      solver_time_at_limit_start_(s->Now()),
../constraint_solver/search.cc:4013:  solver_time_at_limit_start_ = s->Now();
../constraint_solver/search.cc:4026:    duration_limit_ -= s->Now() - solver_time_at_limit_start_;
../constraint_solver/search.cc:4077:    absl::Duration elapsed = s->Now() - solver_time_at_limit_start_;
../constraint_solver/constraint_solver.h:980:  absl::Time Now() const;
../constraint_solver/constraint_solver.h:982:  /// DEPRECATED: Use Now() instead.
../gen/java/com/google/ortools/constraintsolver/Solver.java:533:   *  DEPRECATED: Use Now() instead.<br>
../base/logging_utilities.cc:231:int64 CycleClock_Now() { return absl::ToUnixMicros(absl::Now()); }
../base/logging_utilities.h:31:int64 CycleClock_Now();
../base/logging.cc:819:      logging_internal::CycleClock_Now() + logging_internal::UsecToCycles(next);
../base/logging.cc:1011:    if (logging_internal::CycleClock_Now() >= next_flush_time_)
../base/logging.cc:1019:      (logging_internal::CycleClock_Now() >= next_flush_time_)) {
../base/logging.cc:1142:  double now = ToUDate(absl::Now());
../linear_solver/linear_solver.cc:450:      construction_time_(absl::Now()) {
../linear_solver/linear_solver.h:706:    return absl::Now() - construction_time_;
```

I think relevant are:
```
../base/logging_utilities.cc:231:int64 CycleClock_Now() { return absl::ToUnixMicros(absl::Now()); }
../base/logging_utilities.h:31:int64 CycleClock_Now();
```
