### ISSUE TITLE
Help with CVRP Reload

### ISSUE THREAD

**Issue by mertbakir** [google/or-tools#2441]
Hi, I'm trying to use Routing Solver to solve a Multi Trip Capacitated VRP. What I need is 

- one depot, route starts and ends here.
- one unloading location
- to set time window and demand for each node

So the vehicles should pick up the good from each node until their capacity is filled. Go to "unloading location", unload all their weight and keep collecting the demand from nodes.

[CVRP Reload Example](https://github.com/google/or-tools/blob/master/ortools/constraint_solver/samples/cvrp_reload.py) seems very close but at the end of the route vehicles should visit the unloading location before the depot. How can I achieve that? In other words, depot and unloading locations are different nodes.

to illustrate:

```
0: Depot
1: Unloading Location
2, 3, 4, 5, 6, 7: Nodes to pick up demand


0 > 2 > 3 > 4 > 1 (unload) > 5 > 6 > 7 > 1 (unload) > 0
0 > 2 > 3 > 4 > 1 (unload) > 5 > 6 > 7 > 0 This is the result cvrp_reload returns.
```

I'm fairly new to or-tools, and trying to figure it out. Can you help me if you have any ideas?
PS. I'm using Python and or-tools v8.2

**Comment by lperron** [comment]
This is not an issue. Moving to discussions.
