### ISSUE TITLE
Breaks code (cvrptw_breaks.py) fails with 8.2.8710

### ISSUE THREAD

**Issue by jmarca** [google/or-tools#2444]
**What version of OR-Tools and what language are you using?**
Version: 8.2.8710
Language: Python

Fails (segfault) with 
* ortools 8.2.8710

Runs okay with 
* ortools   8.1.8487
* ortools git master, commit 193101786ecb527fb76a957ce5f2efe4016836c5
      
**Which solver are you using?**
Routing solver

**What operating system (Linux, Windows, ...) and version?**
Linux.  Docker container based on python 3.8

**What did you do?**

Using the corrected version of cvrptw_breaks.py from 3e40b17f5588cadefc4f3284f26c8ed4b60840f6
```
user@3b3d9b9e1ab0:~$ python cvrptw_break.py 
Segmentation fault
```

**What did you expect to see**

In the earlier version of ortools from an earlier, not updated docker container, I see

```
user@121474fa2ec7:~$ python cvrptw_break.py 
Objective: 6596
Breaks:
Break for vehicle 0: Start(15) Duration(2)
Break for vehicle 1: Start(15) Duration(2)
Break for vehicle 2: Start(42) Duration(2)
Break for vehicle 3: Start(15) Duration(2)
Route for vehicle 0:
 0 Load(0) Time(0,0) Slack(1,1) -> 12 Load(0) Time(5,5) Slack(2,3) -> 13 Load(2) Time(19,20) Slack(0,1) -> 15 Load(6) Time(45,45) Slack(0,0) -> 11 Load(14) Time(88,88) Slack(0,0) -> 0 Load(15) Time(99,99)
Distance of the route: 1780m
Load of the route: 15
Time of the route: 99

Route for vehicle 1:
 0 Load(0) Time(0,0) Slack(0,0) -> 5 Load(0) Time(3,3) Slack(2,2) -> 8 Load(2) Time(17,17) Slack(0,0) -> 6 Load(10) Time(59,59) Slack(0,0) -> 2 Load(14) Time(82,82) Slack(0,0) -> 0 Load(15) Time(96,96)
Distance of the route: 1712m
Load of the route: 15
Time of the route: 96

Route for vehicle 2:
 0 Load(0) Time(0,0) Slack(0,0) -> 7 Load(0) Time(2,2) Slack(2,2) -> 4 Load(8) Time(48,48) Slack(0,0) -> 3 Load(12) Time(69,69) Slack(0,0) -> 1 Load(14) Time(82,82) Slack(0,0) -> 0 Load(15) Time(93,93)
Distance of the route: 1552m
Load of the route: 15
Time of the route: 93

Route for vehicle 3:
 0 Load(0) Time(0,0) Slack(0,5) -> 9 Load(0) Time(2,7) Slack(2,7) -> 14 Load(1) Time(17,17) Slack(0,0) -> 16 Load(5) Time(39,39) Slack(0,0) -> 10 Load(13) Time(83,83) Slack(0,0) -> 0 Load(15) Time(99,99)
Distance of the route: 1552m
Load of the route: 15
Time of the route: 99

Total Distance of all routes: 6596m
Total Load of all routes: 60
Total Time of all routes: 387min
```

Ditto for the recent git master version as noted above

```
user@1ed462a51c40:/src$ pip list | grep ortool
ortools         8.2.9999
```

Again, this has been fixed at some point, so releasing a new 8.2 version would probably fix the problem

**Comment by jmarca** [comment]
Just double checked, and compiling the current "stable" branch (commit fa84bc05e72641dddfbb98164d81b8bc9bef6ea5) results in the segfault.

**Comment by Mizux** [comment]
FYI since users also spotted some performance regression in v8.2
["Routing performance between 8.0 vs 8.2"](https://groups.google.com/g/or-tools-discuss/c/P9GCXYsFi3c/m/TKs8SNRvAwAJ)

Before releasing any v8.3 I would like to understand fully all the regressions and see if we can generate a clean v8.3

ToDo list:
* [ ] Verify release script run cvrptw_break.py to check for segfault
* [ ] Investigate performance regression
  * [ ] See if we can add a performance/verification test
