### ISSUE TITLE
PDPTW disjunction constraints seem wrong

### ISSUE THREAD

**Issue by prinsherbert** [google/or-tools#246]
Why is are these disjunction constraints added in the PDPTW example like this:

    for all i in [1, n_nodes):
       disjunction([1, 2, ..., i], penalty)

As is done here:

https://github.com/google/or-tools/blob/master/examples/cpp/pdptw.cc#L276

Why, for example, is a disjunction added on nodes [1,2,3,4] ? Should the disjunction not be something like:

    for all i in [1, n_nodes):
       disjunction([ i ], penalty)

For the former, the solution typically is [0, 1] and for the latter it's a solution containing most or all nodes depending on the constraints and penalty.

**Comment by furnon** [comment]
Not sure I understand. In the C++ code you mention, the disjunction is
expressed as:
for (RoutingModel::NodeIndex order(1); order < routing.nodes(); ++order) {
    std::vector<RoutingModel::NodeIndex> orders(1, order);
    routing.AddDisjunction(orders, kPenalty);
}
which makes each order optional.
An equivalent C++11 code could be:
for (RoutingModel::NodeIndex order(1); order < routing.nodes(); ++order) {
    routing.AddDisjunction({order}, kPenalty);
}

**Comment by prinsherbert** [comment]
Good to know I misread the code, I was expecting the 4th constructor of this page was called:

http://en.cppreference.com/w/cpp/container/vector/vector
