### ISSUE TITLE
write constraint in or-tools format

### ISSUE THREAD

**Issue by Westlife1002** [google/or-tools#2461]
how to write constraint in or-tools as below kind, where both sides have decision variables.
`sum{j=1,...,m} x[i][j]w[i] <= W*y[i] | i=1,...,n   //(3)`

apparently, this is not working:
```cpp
	    for (int j = 0; j < numTruck; ++j) {
	    		MPConstraint constraint = solver.makeConstraint(0, capacity*y[j], "");
	    		for (int i = 0; i < numOrder; ++i) {
	    			constraint.setCoefficient(x[i][j], w.get(i));
	    		}
    	}
```
how to describe `capacity * y[j]` ?

**Comment by lperron** [comment]
this is not an issue
