### ISSUE TITLE
ShutdownGoogleLogging() in XPRESS

### ISSUE THREAD

**Issue by sergun** [google/or-tools#2462]
Hi folks!

I get core dump in Xpressinterface destructor:

https://github.com/google/or-tools/blob/fa84bc05e72641dddfbb98164d81b8bc9bef6ea5/ortools/linear_solver/xpress_interface.cc#L374-L377

```
F0430 03:51:40.292968 23206 logging_utilities.cc:318] Check failed: IsGoogleLoggingInitialized() You called ShutdownGoogleLogging() without calling InitGoogleLogging() first!
*** Check failure stack trace: ***
Aborted (core dumped)
```

Looks like it is because of google::ShutdownGoogleLogging() in destructor. I do not see this call in interfaces to other solvers (e.g.SCIP). Is it valid to remove this call from ~XpressInterface()?

**Comment by Mizux** [comment]
Double checked with:
```sh
grepc -rIin "::~" -A 5 *_interface.cc
```

Yes, should be removed

**Comment by Mizux** [comment]
usually you should call the Init in your main loop, so to keep consistency you should call the Shutdown here too
note: xpress is community supported so I suspect a lazy contributor who hacks the dtor ;)

E.g.
```cpp
int main(int argc, char** argv) {
  google::InitGoogleLogging(argv[0]);
  ...
  
  ...
  google::ShutdownGoogleLogging();
  return EXIT_SUCCESS;
}

**Comment by sergun** [comment]
@Mizux thanks!

I use interface to XPRESS through Python. Awaited that Initialization of logging should be called somewhere in module but didn’t go deep to check this.

BTW XPRESS is super fast. So community should love it :-) But unfortunately for money :-)
