### ISSUE TITLE
CPLEX Integration with .NET

### ISSUE THREAD

**Issue by akash-sambrekar** [google/or-tools#2470]
**What version of OR-Tools and what language are you using?**
Version: master/v7.3/v7.2 etc.
Language: C#

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

CPLEX

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
Steps to reproduce the behaviour
After cloning master branch, I execute the following commands
`tools\make third_party`
I added the `WINDOWS_CPLEX_DIR = C:\Program Files\IBM\ILOG\CPLEX_Studio1210` in Makefile.Local
`tools\make dotnet`
If I try to run a examples with cplex with the following command , it doesn't work
`make run SOURCE=examples/dotnet/BasicExample.cs`

The project seems to work fine GLOP , SCIP but not with CPLEX
Error received:
```sh
WARNING: Logging before InitGoogleLogging() is written to STDERR
W00-1 -1:-1:-1.373535 20160 linear_solver.cc:609] Support for CPLEX not linked in, or the license was not found.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at BasicExample.Main() in C:\or-tools\examples\dotnet\BasicExample.cs:line 12
make: *** [makefiles/Makefile.dotnet.mk:462: run] Error -1073741819
```

**Comment by lperron** [comment]
can you try 

make run SOURCE=examples/cpp/integer_programming.cc

**Comment by lperron** [comment]
Check the process. Make sure make clean is called after adding the WINDOWS_CPLEX_DIR to Makefile.local

I just did a fresh compilation from scratch.

Both examples/cpp/integer_programming.cc and examples/dotnet/csinteger_programming.cs works fine

(note that I tweaked the C# example to add the cplex option)

**Comment by akash-sambrekar** [comment]
Do I need to run tools\make clean_third_party or make clean after adding WINDOWS_CPLEX_DIR to Makefile.local ? 

 (Note :I have tweaked the C# example with the cplex option)

**Comment by lperron** [comment]
make clean

Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mer. 31 mars 2021 à 11:52, Akash Sambrekar ***@***.***> a
écrit :

**Comment by akash-sambrekar** [comment]
Yes it works now Laurent !..
Thank you for the help

**Comment by Mizux** [comment]
For the record stable (8.2) contains an harcoded version
https://github.com/google/or-tools/blob/fa84bc05e72641dddfbb98164d81b8bc9bef6ea5/makefiles/Makefile.win.mk#L120-L125
