### ISSUE TITLE
OR tools C++: solver.MutableObjective() returns null

### ISSUE THREAD

**Issue by xuyonglai** [google/or-tools#2472]
**What version of OR-Tools and what language are you using?**
Version: master/v7.3/v7.2 etc.
Language: C++/Java/Python/C#
C++
**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
GLOP
**What operating system (Linux, Windows, ...) and version?**
Windows
**What did you do?**

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by xuyonglai** [comment]
https://stackoverflow.com/questions/66020741/or-tools-c-solver-mutableobjective-returns-null

**Comment by Mizux** [comment]
When you integrate ortools in your C++ project did you also set all flags especially USE_SCIP ?

https://github.com/google/or-tools/blob/fa84bc05e72641dddfbb98164d81b8bc9bef6ea5/tools/Makefile.cc.java.dotnet#L126-L132

**Comment by xuyonglai** [comment]
> When you integrate ortools in your C++ project did you also set all flags especially USE_SCIP ?
> 
> https://github.com/google/or-tools/blob/fa84bc05e72641dddfbb98164d81b8bc9bef6ea5/tools/Makefile.cc.java.dotnet#L126-L132

how to set all flags......
