### ISSUE TITLE
The type initialiser for "Google.OrTools.Util.operations_research_utilPINVOKE" caused an exception

### ISSUE THREAD

**Issue by disl** [google/or-tools#2477]
Or-Tools version: 8.2.8710.0
Solver: Google.OrTools.Sat
Language: C#
Visual Studio 2019 16.9.3
Windows 10 Home,, 20H2

**Error does not happen in development environment, but only in published version.**

Error message:
**"The type initialiser for "Google.OrTools.Util.operations_research_utilPINVOKE" caused an exception at Google.OrTools.Util.operations_research_utilPINVOKE.new_Domain__SWIG_2(Int64 jarg1, Int64 jarg2) bei Google.OrTools.Sat.CpModel.NewBoolVar(String name) bei google_or_tools.ShiftSchedulingSat.SolveShiftScheduling(...)...**
.........My Stack trace..........

**Comment by disl** [comment]
![error](https://user-images.githubusercontent.com/1278236/114105114-71819480-98cc-11eb-9e6d-b8553455f654.PNG)

**Comment by lperron** [comment]
You miss either the native dll, or the visual studio 2019 redistributables.

**Comment by disl** [comment]
1. What do you mean by "native DLL" - I installed Google.OrTools normally via Nuget into the project?
2. Visual Studio 2019 redistributables i have installed  ([Link](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0)).

**Comment by lperron** [comment]
Is the deployed server 64bit?

**Comment by disl** [comment]
Ja

**Comment by disl** [comment]
German:
------------------------------
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2182,5): warning MSB3270: Konflikt zwischen der Prozessorarchitektur des Projekts "MSIL", das erstellt wird, und der Prozessorarchitektur des Verweises, "Google.OrTools, Version=8.2.8710.0, Culture=neutral, PublicKeyToken=53dbb1ea090cbef7, processorArchitecture=AMD64", "AMD64". Dieser Konflikt kann zu Laufzeitfehlern führen. Ändern Sie ggf. mithilfe des Konfigurations-Managers die als Ziel angegebene Prozessorarchitektur Ihres Projekts so, dass die Prozessorarchitekturen zwischen Ihrem Projekt und den Verweisen ausgerichtet werden, oder wählen Sie eine Abhängigkeit von Verweisen mit einer Prozessorarchitektur, die der als Ziel angegebene Prozessorarchitektur Ihres Projekts entspricht.

English:
--------------------------------
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion. targets(2182,5): warning MSB3270: conflict between the processor architecture of the project "MSIL" being built and the processor architecture of the reference, "Google.OrTools, Version=8.2.8710.0, Culture=neutral, PublicKeyToken=53dbb1ea090cbef7, processorArchitecture=AMD64", "AMD64". This conflict can lead to runtime errors. If necessary, use the Configuration Manager to change your project's target processor architecture to align the processor architectures between your project and the references, or select a reference dependency with a processor architecture that matches your project's target processor architecture.

-------------------------------
This is a warning when compiling, maybe this could help?

**Comment by Mizux** [comment]
What kind of 64bits ? x86_64 or itanium "true" x64 ?

**Comment by disl** [comment]
Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz   3.30 GHz

**Comment by disl** [comment]
Do you plan to implement Or-tools as a service (Web API), so that perhaps problems with adaptations for different platforms could be avoided?

**Comment by disl** [comment]
After a project porting from WinForms (.net Framework) to WinForms (.net 5) project works completely even after release

**Comment by lperron** [comment]
Seems I can close this. Please reopen if needed.
