### ISSUE TITLE
Known issue: Cbc 2.10.4 incorrectly reports infeasible (--> Update to Cbc 2.10.5?)

### ISSUE THREAD

**Issue by deiruch** [google/or-tools#2480]
**What version of OR-Tools and what language are you using?**
Version: Google.OrTools 8.2.8710 (from NuGet)
Language: C#

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Cbc

**What operating system (Linux, Windows, ...) and version?**
Windows x64 19042.870

**What did you do?**
I solved a MIP using Cbc with a timelimit.

**What did you expect to see**
Feasible solution or optimum.

**What did you see instead?**
Cbc reported "Infeasible" for the model.

**Anything else we should know about your project / environment**
This is a [known issue](https://github.com/coin-or/Cbc/releases/tag/releases%2F2.10.5) in Cbc 2.10.4 where it incorrectly reports "Infeasible" when using time limits. The following 2.10.5 release from March 2020 fixes the problem. I'd be great if you could update the bundled Cbc version to 2.10.5.

**Comment by lperron** [comment]
CBC 2.10.5 is know to be buggy.

**Comment by Mizux** [comment]
IIRC https://github.com/coin-or/Clp/issues/130 is blocking us from any upgrade...
