### ISSUE TITLE
Pickup&Delivery Visit Point Constraint

### ISSUE THREAD

**Issue by burbot48** [google/or-tools#2481]
Hi ,

I want to manage a constraint on a CVRPD with TW. I have 6 nodes , 3 of them are pick-up points and rest 3 points are delivery points. I want  that the vehicle can not carry the demands of some pickup nodes at the same time. Let me try to explain with an example : 
If the vehicle should have to visit point 1 before than point 2 according to time matrix and time window  , the vehicle should not visit point 2 without visiting point 4 ( Delivery point of point 1) or visa-versa  the vehicle should have to visit point 2 before point  1 , the vehicle should not visit point 1 without visiting point 5 ( Delivery point of point 2). this constrain does not seem manageable by time matrix due that there are two possibilities.  Of course this constraint will be valid that these two nodes (point1 and Point2 ) are assigned to the same vehicle 

Could you give me an advise to manage this constraint.

Thank you

**Inputs**
starts= [0]
pickups_deliveries=[[1, 4], [2, 5], [3, 6]]
demands=[0, 975, 1450, 975, -975, -1450, -975]
num_vehicle=1
vehicle_capacities=[3000]
time_matrix=[[0.0, 105.0, 56.0, 87.0, 1500.0, 1500.0, 1500.0],
 [0.0, 40.0, 1575.0, 73.0, 97.0, 83.0, 79.0],
 [0.0, 1590.0, 25.0, 1563.0, 63.0, 49.0, 36.0],
 [0.0, 88.0, 1563.0, 25.0, 94.0, 80.0, 68.0],
 [0.0, 115.0, 66.0, 97.0, 22.0, 26.0, 26.0],
 [0.0, 101.0, 52.0, 83.0, 26.0, 22.0, 26.0],
 [0.0, 97.0, 39.0, 71.0, 26.0, 26.0, 22.0]]
 time_windows=[(0, 5000), (0, 1200), (0, 1200), (0, 1380), (0, 1200), (0, 1200), (0, 1380)]

**Comment by lperron** [comment]
not an issue

**Comment by burbot48** [comment]
I dont understand why you closed this issue. If there needs more  info, I can supply.

**Comment by lperron** [comment]
This is for product bugs, not modelling questions.

**Comment by burbot48** [comment]
We developped a CVRPD with TW model in python. But unfortunately we could not know how we can manage visit constraint between nodes. Could you please guide me how can get an help about this issue. Thank you

**Comment by lperron** [comment]
as specified on the issue page, either use the github discussion or ask the
or-tools-discuss mailing list.

I am not an expert on routing.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
