### ISSUE TITLE
CP Sat is not optimizing my cost function

### ISSUE THREAD

**Issue by latkm** [google/or-tools#2490]
Hi,

I'm setting up a constrained optimization problem, with boolean vars, in CP Sat.
I notice that the returned solution satisfy all the constraints but returned "optimal" value f(x*) for objective function (ObjectiveValue), at the found "optimal" argument (x*) is not the real value for the objective function. E.g. f(x*) returned is 0, while the real value for f(x*) should be 23434. When I evaluate f(x*) by using the same function defined for computing the objective function, I do get the correct value. But when it is called by CP Sat through the optimization process, it seems to be computing wrongly. 

I post the definition of the objective function, which calls other previously defined functions.

`

def cost_function(z):

    value = 0
    tc = paths_of_z(z)
    time_requirements = read_times(tc, time_tables)
    cn = cost_of_paths(tc, costs)
    for m in np.arange(0, len(cn), 1):
        value = value + sum((np.array(cn[m]) - np.array(time_requirements[m]))**2)
    return value
model.Minimize(cost_function(z))
` 

In order to debug it, I'm trying to print the intermediate solutions, i.e. solutions attained during the sequence of iterations, with:
(I'm not sure if intermediate solutions, can be printed - please correct if I'm wrong)
 
`
class VarArrayAndObjectiveSolutionPrinter(cp_model.CpSolverSolutionCallback):
    """Print intermediate solutions."""

    def __init__(self, variables):
        cp_model.CpSolverSolutionCallback.__init__(self)
        self.__variables = variables
        self.__solution_count = 0

    def on_solution_callback(self):
        print('Solution %i' % self.__solution_count)
        print('  objective value = %i' % self.ObjectiveValue())
        for v in self.__variables:
            print('  %s = %i' % (v, self.Value(v)), end=' ')
        print()
        self.__solution_count += 1

    def solution_count(self):
        return self.__solution_count
        # [END print_solution]`

But I get only one solution printed, which seems to be the first guess that is feasible, and for which the value f(x*) is wrongly computed.

Any help will be greatly appreciated. 
Thank you very much,

**Comment by lperron** [comment]
You cannot pass an arbitrary function to the minimize code. 

In particular **2 is not supported.
