### ISSUE TITLE
Ortool routing

### ISSUE THREAD

**Issue by rzlyp** [google/or-tools#2513]
**What language and solver does this apply to?**
Python

is it possible to use the VRP/CVRP routing method with optimizing distance/time? for now if we're using VRP/AddDimensionWithVehicleCapacity, the average times/distance is not optimized, also sometimes if we put the vehicle to 10, it only returns 6 venhicle

**Describe the solution you'd like**
i want to return the results as many as the vehicle quantity but with an optimized route
example:
there're 50 routes,
if we need 10 vehicles, then it will return 10 vehicles  (5 route per vehicle) with the closest route per vehicle

i already tried using the "Counter" dimension, it works, but the route is not optimized.

**Comment by lperron** [comment]
Not an issue
