### ISSUE TITLE
Trivial solution not found with order-contraints

### ISSUE THREAD

**Issue by prinsherbert** [google/or-tools#252]
(from http://stackoverflow.com/questions/39507824/or-tools-routing-fails-to-find-trivial-optimal-solution-in-the-presence-of-ord)

In order to better understand the constraint-programming behind or-tools routing, I created a toy example of a depot and 4 other nodes configured to allow for two routes.

[![enter image description here](http://i.stack.imgur.com/SiZj1.jpg)](http://i.stack.imgur.com/SiZj1.jpg)

The idea is that a vehicle travels from the depot `0` to `1`, then either picks `2` or `3`, continues to `4` and returns to the depot `0`; the vehicle either picks the green or red path. My actual problem is more complicated and has multiple vehicles, but has similar constraints.

For this example I created a euclidean-distance function for the cost: 

```
class Distances:
    def __init__(self):
        self.locations = [
            [-1,  0], # source
            [ 0, -1], # waypoint 1
            [ 0,  1], # waypoint 2
            [ 1,  0], # destination
        ]

    def __len__(self):
        return len(self.locations) + 1

    def dist(self, x, y):
        return int(10000 * math.sqrt(
            (x[0] - y[0]) ** 2 +
            (x[1] - y[1]) ** 2))

    def __call__(self, i, j):
        if i == 0 and j == 0:
            return 0
        if j == 0 or i == 0:
            return 1 # very small distance between depot and non-depot, simulating 0
        return self.dist(self.locations[i - 1], self.locations[j - 1])


distance = Distances()
```

And a l0 distance function to constraint the order:

```
# l0-distance to add order constraints
class Order:
    def __call__(self, i, j):
        return 0 if i == j else 1


order = Order()
```

Then I create the model and try to solve this:

```
search_parameters = pywrapcp.RoutingModel.DefaultSearchParameters()
search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.ALL_UNPERFORMED)

search_parameters.local_search_metaheuristic = routing_enums_pb2.LocalSearchMetaheuristic.SIMULATED_ANNEALING
search_parameters.time_limit_ms = 3000

routing = pywrapcp.RoutingModel(len(distance), 1)

routing.SetArcCostEvaluatorOfAllVehicles(distance)
routing.SetDepot(0)
solver = routing.solver()

routing.AddDimension(order, int(1e18), int(1e18), True, "order")

# Since `ALL_UNPERFORMED` is used, each node must be allowed inactive
order_dimension = routing.GetDimensionOrDie("order")
routing.AddDisjunction([1], int(1e10))
routing.AddDisjunction([2, 3], int(1e10))
routing.AddDisjunction([4], int(1e10))

solver.AddConstraint(order_dimension.CumulVar(1) <= order_dimension.CumulVar(2))
solver.AddConstraint(order_dimension.CumulVar(1) <= order_dimension.CumulVar(3))

solver.AddConstraint(order_dimension.CumulVar(2) <= order_dimension.CumulVar(4))
solver.AddConstraint(order_dimension.CumulVar(3) <= order_dimension.CumulVar(4))

# routing.AddPickupAndDelivery(1, 2)
# routing.AddPickupAndDelivery(1, 3)
# routing.AddPickupAndDelivery(2, 4)
# routing.AddPickupAndDelivery(3, 4)

routing.CloseModelWithParameters(search_parameters)
assignment = routing.SolveWithParameters(search_parameters)

if assignment is not None:
    print('cost: ' + str(assignment.ObjectiveValue()))
    route = []
    index = routing.Start(0)
    while not routing.IsEnd(index):
        route.append(routing.IndexToNode(index))
        index = assignment.Value(routing.NextVar(index))
    for node in route:
        print(' - {:2d}'.format(node))
else:
    print('nothing found')
```

So `[1]` and `[4]` are disjunctions to allow for `ALL_UNPERFORMED` first solution to work, and the disjunction `[2, 3]` to state that either the green or red path should be chosen.

With these disjunctions the solver finds a solution, but if I add that `2`  and `3` should be visited after `1` and before `4`, the solver does not visit `2` or `3` at all. Why is this the case? Why can't the solver find the more optimal route `0 -> 1 -> 2/3 -> 4 -> 0` avoiding the `int(1e10)` disjunction penalty for `[2,3]`?

**EDIT:**

Soft-constraining the order-constraints by removing them and adding to `Distance.__call__`:

```
if (i == 2 or j == 1) or (i == 3 or j == 1) or (i == 4 or j == 2) or (i == 4 or j == 3):
    return int(1e10)
```

to penalize a disallowed order, results in the route `0 -> 2 -> 1 -> 4 -> 0`. So I wonder why or-tools won't swap `1` and `2`, even when explicitly enabling `use_swap_active` and `use_relocate_neighbors` in `search_parameters.local_search_operators`.

Concluding: the search-space is small, a better solution is in the neighborhood of `use_relocate_neighbors` of the returned solution, yet or-tools does not find it. Why?
# All code:

```
import pandas
import os.path

import numpy
import math
from ortools.constraint_solver import pywrapcp
from ortools.constraint_solver import routing_enums_pb2


class Distances:
    def __init__(self):
        self.locations = [
            [-1,  0], # source
            [ 0, -1], # waypoint 1
            [ 0,  1], # waypoint 2
            [ 1,  0], # destination
        ]

    def __len__(self):
        return len(self.locations) + 1

    def dist(self, x, y):
        return int(10000 * math.sqrt(
            (x[0] - y[0]) ** 2 +
            (x[1] - y[1]) ** 2))

    def __call__(self, i, j):
        if i == 0 and j == 0:
            return 0
        if j == 0 or i == 0:
            return 1 # very small distance between depot and non-depot, simulating 0
        return self.dist(self.locations[i - 1], self.locations[j - 1])


distance = Distances()


# l0-distance to add order constraints
class Order:
    def __call__(self, i, j):
        return 0 if i == j else 1


order = Order()

search_parameters = pywrapcp.RoutingModel.DefaultSearchParameters()
search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.ALL_UNPERFORMED)

search_parameters.local_search_metaheuristic = routing_enums_pb2.LocalSearchMetaheuristic.SIMULATED_ANNEALING
search_parameters.time_limit_ms = 3000

routing = pywrapcp.RoutingModel(len(distance), 1)

routing.SetArcCostEvaluatorOfAllVehicles(distance)
routing.SetDepot(0)
solver = routing.solver()

routing.AddDimension(order, int(1e18), int(1e18), True, "order")

# Since `ALL_UNPERFORMED` is used, each node must be allowed inactive
order_dimension = routing.GetDimensionOrDie("order")
routing.AddDisjunction([1], int(1e10))
routing.AddDisjunction([2, 3], int(1e10))
routing.AddDisjunction([4], int(1e10))

solver.AddConstraint(
    (routing.ActiveVar(2) == 0)
    or
    (order_dimension.CumulVar(1) <= order_dimension.CumulVar(2))
)
solver.AddConstraint(
    (routing.ActiveVar(3) == 0)
    or
    (order_dimension.CumulVar(1) <= order_dimension.CumulVar(3))
)


solver.AddConstraint(
    (routing.ActiveVar(2) == 0)
    or
    (order_dimension.CumulVar(2) <= order_dimension.CumulVar(4))
)
solver.AddConstraint(
    (routing.ActiveVar(3) == 0)
    or
    (order_dimension.CumulVar(3) <= order_dimension.CumulVar(4))
)

# routing.AddPickupAndDelivery(1, 2)
# routing.AddPickupAndDelivery(1, 3)
# routing.AddPickupAndDelivery(2, 4)
# routing.AddPickupAndDelivery(3, 4)

routing.CloseModelWithParameters(search_parameters)
assignment = routing.SolveWithParameters(search_parameters)

if assignment is not None:
    print('cost: ' + str(assignment.ObjectiveValue()))
    route = []
    index = routing.Start(0)
    while not routing.IsEnd(index):
        route.append(routing.IndexToNode(index))
        index = assignment.Value(routing.NextVar(index))
    for node in route:
        print(' - {:2d}'.format(node))
else:
    print('nothing found')
```

**Comment by furnon** [comment]
Hi,
Comments inline.

On Fri, Sep 23, 2016 at 4:54 PM, Herbert <notifications@github.com> wrote:

> (from http://stackoverflow.com/questions/39507824/or-tools-
> routing-fails-to-find-trivial-optimal-solution-in-the-presence-of-ord)
>
> In order to better understand the constraint-programming behind or-tools
> routing, I created a toy example of a depot and 4 other nodes configured to
> allow for two routes.
>
> [image: enter image description here] <http://i.stack.imgur.com/SiZj1.jpg>
>
> The idea is that a vehicle travels from the depot 0 to 1, then either
> picks 2 or 3, continues to 4 and returns to the depot 0; the vehicle
> either picks the green or red path. My actual problem is more complicated
> and has multiple vehicles, but has similar constraints.
>
> For this example I created a euclidean-distance function for the cost:
>
> class Distances:
>     def __init__(self):
>         self.locations = [
>             [-1,  0], # source
>             [ 0, -1], # waypoint 1
>             [ 0,  1], # waypoint 2
>             [ 1,  0], # destination
>         ]
>
>     def __len__(self):
>         return len(self.locations) + 1
>
>     def dist(self, x, y):
>         return int(10000 * math.sqrt(
>             (x[0] - y[0]) ** 2 +
>             (x[1] - y[1]) ** 2))
>
>     def __call__(self, i, j):
>         if i == 0 and j == 0:
>             return 0
>         if j == 0 or i == 0:
>             return 1 # very small distance between depot and non-depot, simulating 0
>         return self.dist(self.locations[i - 1], self.locations[j - 1])
>
>
> distance = Distances()
>
> And a l0 distance function to constraint the order:
>
> # l0-distance to add order constraints
> class Order:
>     def __call__(self, i, j):
>         return 0 if i == j else 1
>
>
> order = Order()
>
> Then I create the model and try to solve this:
>
> search_parameters = pywrapcp.RoutingModel.DefaultSearchParameters()
> search_parameters.first_solution_strategy = (
>         routing_enums_pb2.FirstSolutionStrategy.ALL_UNPERFORMED)
>
> search_parameters.local_search_metaheuristic = routing_enums_pb2.LocalSearchMetaheuristic.SIMULATED_ANNEALING
> search_parameters.time_limit_ms = 3000
>
> routing = pywrapcp.RoutingModel(len(distance), 1)
>
> routing.SetArcCostEvaluatorOfAllVehicles(distance)
> routing.SetDepot(0)
> solver = routing.solver()
>
> routing.AddDimension(order, int(1e18), int(1e18), True, "order")
>
> # Since `ALL_UNPERFORMED` is used, each node must be allowed inactive
> order_dimension = routing.GetDimensionOrDie("order")
> routing.AddDisjunction([1], int(1e10))
> routing.AddDisjunction([2, 3], int(1e10))
> routing.AddDisjunction([4], int(1e10))
>
> solver.AddConstraint(order_dimension.CumulVar(1) <= order_dimension.CumulVar(2))
> solver.AddConstraint(order_dimension.CumulVar(1) <= order_dimension.CumulVar(3))
>
> solver.AddConstraint(order_dimension.CumulVar(2) <= order_dimension.CumulVar(4))
> solver.AddConstraint(order_dimension.CumulVar(3) <= order_dimension.CumulVar(4))
>
> # routing.AddPickupAndDelivery(1, 2)
> # routing.AddPickupAndDelivery(1, 3)
> # routing.AddPickupAndDelivery(2, 4)
> # routing.AddPickupAndDelivery(3, 4)
>
> routing.CloseModelWithParameters(search_parameters)
> assignment = routing.SolveWithParameters(search_parameters)
>
> if assignment is not None:
>     print('cost: ' + str(assignment.ObjectiveValue()))
>     route = []
>     index = routing.Start(0)
>     while not routing.IsEnd(index):
>         route.append(routing.IndexToNode(index))
>         index = assignment.Value(routing.NextVar(index))
>     for node in route:
>         print(' - {:2d}'.format(node))
> else:
>     print('nothing found')
>
> So [1] and [4] are disjunctions to allow for ALL_UNPERFORMED first
> solution to work, and the disjunction [2, 3] to state that either the
> green or red path should be chosen.
>
> With these disjunctions the solver finds a solution, but if I add that 2
> and 3 should be visited after 1 and before 4, the solver does not visit 2
> or 3 at all. Why is this the case? Why can't the solver find the more
> optimal route 0 -> 1 -> 2/3 -> 4 -> 0 avoiding the int(1e10) disjunction
> penalty for [2,3]?
>
> *EDIT:*
>
> Soft-constraining the order-constraints by removing them and adding to
> Distance.__call__:
>
> if (i == 2 or j == 1) or (i == 3 or j == 1) or (i == 4 or j == 2) or (i == 4 or j == 3):
>     return int(1e10)
>
>

I guess you meant
 if (i == 2 and j == 1) or (i == 3 and j == 1) or (i == 4 and j == 2) or (i
== 4 and j == 3):
?

>  to penalize a disallowed order, results in the route 0 -> 2 -> 1 -> 4 ->
> 0. So I wonder why or-tools won't swap 1 and 2, even when explicitly
> enabling use_swap_active and use_relocate_neighbors in
> search_parameters.local_search_operators.
>
> Concluding: the search-space is small, a better solution is in the
> neighborhood of use_relocate_neighbors of the returned solution, yet
> or-tools does not find it. Why?
>

In the code below if you transform:

 solver.Add(

    (routing.ActiveVar(2) == 0)
    or
    (order_dimension.CumulVar(1) <= order_dimension.CumulVar(2))
)
solver.Add(
    (routing.ActiveVar(3) == 0)
    or
    (order_dimension.CumulVar(1) <= order_dimension.CumulVar(3))
)


solver.Add(
    (routing.ActiveVar(2) == 0)
    or
    (order_dimension.CumulVar(2) <= order_dimension.CumulVar(4))
)
solver.Add(
    (routing.ActiveVar(3) == 0)
    or
    (order_dimension.CumulVar(3) <= order_dimension.CumulVar(4))
)


into

solver.Add(

    (order_dimension.CumulVar(1) <= order_dimension.CumulVar(2))
)
solver.Add(
    (order_dimension.CumulVar(1) <= order_dimension.CumulVar(3))
)


solver.Add(
    (order_dimension.CumulVar(2) <= order_dimension.CumulVar(4))
)
solver.Add(
    (order_dimension.CumulVar(3) <= order_dimension.CumulVar(4))
)


then the solver may hang (this is due to a different issue we are
working on). Actually if you also give a lower upper bound to the
order dimension, such as

routing.AddDimension(order, len(distance) + 1 ,len(distance) + 1, True, "order")

then the code doesn't hang anymore and finds the expected solution.


I hope this helps,


Vincent

All code:

**Comment by prinsherbert** [comment]
@furnon I posted your answer on stackoverflow: http://stackoverflow.com/questions/39507824/or-tools-routing-fails-to-find-trivial-optimal-solution-in-the-presence-of-ord/39718730#39718730

Moreover, it works, thank you! The nested-or bug was well-spotted! Now I will determine how well this works for my actual problem with multiple of these type of disjunction constraints.

**Comment by furnon** [comment]
BTW the proper way to express "or" expressions on constraints is currently
the following:
solver.Add(
    (routing.ActiveVar(3) == 0)
    +
    (order_dimension.CumulVar(3) <= order_dimension.CumulVar(4)) >= 1
)

**Comment by prinsherbert** [comment]
Thank you! It makes sense that OR-tools get's confused when faced with or-expressions.
