### ISSUE TITLE
Check failed: SolutionIsFeasible in CP-SAT solver

### ISSUE THREAD

**Issue by cfsfifty** [google/or-tools#2525]
**What version of OR-Tools and what language are you using?**
Version: 8.2.8710 
Language: Python 3.8.5 64-bit

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Win10 64-bit

**What did you do?**
model solve see proto below

solver.parameters.log_search_progress = True 
solver.parameters.num_search_workers  = 16
solver.parameters.linearization_level = 2  
 
**What did you expect to see**
INFEASIBLE or OPTIMAL

**What did you see instead?**
"
#Bound 443.49s best:53    next:[45,52]    quick_restart_no_lp
#Done  443.50s  no_lp
Total cuts added: 9232 (out of 26479 calls) worker: 'reduced_costs'
  - num simplifications: 2068575
  - added 649 cuts of type 'CG'.
  - added 5708 cuts of type 'IB'.
  - added 325 cuts of type 'MIR_1'.
  - added 243 cuts of type 'MIR_2'.
  - added 255 cuts of type 'MIR_3'.
  - added 229 cuts of type 'MIR_4'.
  - added 85 cuts of type 'MIR_5'.
  - added 82 cuts of type 'MIR_6'.
  - added 1345 cuts of type 'ZERO_HALF'.
  - added 311 cuts of type 'clique'.
Total cuts added: 4672 (out of 12343 calls) worker: 'pseudo_costs'
  - num simplifications: 44179
  - added 197 cuts of type 'CG'.
  - added 3944 cuts of type 'IB'.
  - added 112 cuts of type 'MIR_1'.
  - added 49 cuts of type 'MIR_2'.
  - added 69 cuts of type 'MIR_3'.
  - added 42 cuts of type 'MIR_4'.
  - added 25 cuts of type 'MIR_5'.
  - added 15 cuts of type 'MIR_6'.
  - added 67 cuts of type 'ZERO_HALF'.
  - added 152 cuts of type 'clique'.
Total cuts added: 7253 (out of 18929 calls) worker: 'max_lp'
  - num simplifications: 431727
  - added 979 cuts of type 'CG'.
  - added 4870 cuts of type 'IB'.
  - added 176 cuts of type 'MIR_1'.
  - added 170 cuts of type 'MIR_2'.
  - added 256 cuts of type 'MIR_3'.
  - added 158 cuts of type 'MIR_4'.
  - added 73 cuts of type 'MIR_5'.
  - added 42 cuts of type 'MIR_6'.
  - added 450 cuts of type 'ZERO_HALF'.
  - added 79 cuts of type 'clique'.
Total cuts added: 40470 (out of 156970 calls) worker: 'quick_restart'
  - num simplifications: 2179549
  - added 2828 cuts of type 'CG'.
  - added 18393 cuts of type 'IB'.
  - added 1392 cuts of type 'MIR_1'.
  - added 4731 cuts of type 'MIR_2'.
  - added 3336 cuts of type 'MIR_3'.
  - added 1978 cuts of type 'MIR_4'.
  - added 726 cuts of type 'MIR_5'.
  - added 327 cuts of type 'MIR_6'.
  - added 6202 cuts of type 'ZERO_HALF'.
  - added 557 cuts of type 'clique'.
Total cuts added: 4191 (out of 71239 calls) worker: 'probing'
  - num simplifications: 892105
  - added 101 cuts of type 'CG'.
  - added 2853 cuts of type 'IB'.
  - added 321 cuts of type 'MIR_1'.
  - added 74 cuts of type 'MIR_2'.
  - added 64 cuts of type 'MIR_3'.
  - added 67 cuts of type 'MIR_4'.
  - added 28 cuts of type 'MIR_5'.
  - added 11 cuts of type 'MIR_6'.
  - added 478 cuts of type 'ZERO_HALF'.
  - added 194 cuts of type 'clique'.
Check failed: SolutionIsFeasible(model_proto, std::vector<int64>(response->solution().begin(), response->solution().end()), &mapping_proto, &postsolve_mapping) final postsolved solution
*** Check failure stack trace: ***
    @   00007FFD8A6BA205  (unknown)
    @   00007FFD8A6B86C9  (unknown)
    @   00007FFD8A76A901  (unknown)
    @   00007FFD8A77FE2B  (unknown)
    @   00007FFD8A784470  (unknown)
    @   00007FFD8A6956B5  (unknown)
    @   00007FFDC43D5192  (unknown)
    @   00007FFDC43E9D75  (unknown)
    @   00007FFDC43EBA07  (unknown)
    @   00007FFDC43E978E  (unknown)
    @   00007FFDC43EBA07  (unknown)
    @   00007FFDC43E978E  (unknown)
    @   00007FFDC43EB774  (unknown)
    @   00007FFDC43E6D18  (unknown)
    @   00007FFDC43F7C6F  (unknown)
    @   00007FFDC43F7BCD  (unknown)
    @   00007FFDC43F78FA  (unknown)
    @   00007FFDC43F7889  (unknown)
    @   00007FFDC4408230  (unknown)
    @   00007FFDC440873F  (unknown)
    @   00007FFDC4584FFF  (unknown)
    @   00007FFDC452F375  (unknown)
    @   00007FFDC440B9D8  (unknown)
    @   00007FFDC440B861  (unknown)
    @   00007FFDC440A716  (unknown)
    @   00007FFDC44D8FA5  (unknown)
    @   00007FF7B1971268  (unknown)
    @   00007FFE01767034  (unknown)
    @   00007FFE01B82651  (unknown)
"

[proto.txt](https://github.com/google/or-tools/files/6400297/proto.txt)

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
I confirm the bug. Thanks for the report.
