### ISSUE TITLE
CMake Error: CMake can not determine linker language for target: ortools_init

### ISSUE THREAD

**Issue by yurivict** [google/or-tools#2526]
**What version of OR-Tools and what language are you using?**
Version: 9.0
Language: C++

**Problem description**
cmake-3.19.6 fails:
```
-- Configuring done
CMake Error: CMake can not determine linker language for target: ortools_init
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
*** Error code 1
```
on FreeBSD 12.2

**Comment by tpimh** [comment]
I have solved it with simple `sed -i '11i \ \ LINKER_LANGUAGE Cxx' ortools/init/CMakeLists.txt`.

**Comment by yurivict** [comment]
@Mizux The problem is still present in 9.1 released 4 days ago.

**Comment by tpimh** [comment]
@yurivict My workaround should still work, I can create a pull request fixing this issue.

**Comment by Mizux** [comment]
Seems to work with FreeBSD 13 (vagrant box)
https://github.com/google/or-tools/runs/3788581120?check_suite_focus=true

I'll try to see if I can test locally on a FreeBSD 12 VM.
Otherwise @yurivict could you test with CMake 3.21.3 to see if it's an error fixed in CMake ?

**Comment by yurivict** [comment]
The workaround works on FreeBSD. It should just be committed.

**Comment by Mizux** [comment]
For the record: https://cmake.org/cmake/help/latest/prop_tgt/LINKER_LANGUAGE.html
