### ISSUE TITLE
libortools.so.8.2.9999 and libflatzinc.so.8.2.9999 don't have a SONAME

### ISSUE THREAD

**Issue by yurivict** [google/or-tools#2527]
**What version of OR-Tools and what language are you using?**
Version: 8.2
Language: C++

```
arning: /usr/ports/math/or-tools/work/stage/usr/local/lib/libflatzinc.so.8.2.9999 doesn't have a SONAME.
Warning: pkg(8) will not register it as being provided by the port.
Warning: If another port depend on it, pkg will not be able to know where it comes from.
Warning: It is directly in /usr/local/lib, it is probably used by other ports.
Warning: /usr/ports/math/or-tools/work/stage/usr/local/lib/libortools.so.8.2.9999 doesn't have a SONAME.
```

**Comment by Mizux** [comment]
Did you use the CMake based build ?

**Comment by yurivict** [comment]
> Did you use the CMake based build ?

Yes.

**Comment by Mizux** [comment]
According to https://cmake.org/cmake/help/latest/prop_tgt/NO_SONAME.html
So I would say libortools should have a soname, we also use
https://github.com/google/or-tools/blob/86d4c543f717fa8716a9d66c25143660668bf825/cmake/cpp.cmake#L111
and same for flatzinc:
https://github.com/google/or-tools/blob/86d4c543f717fa8716a9d66c25143660668bf825/cmake/flatzinc.cmake#L89
