### ISSUE TITLE
Add AddPickupAndDelivery with ApplyLocksToAllVehicles

### ISSUE THREAD

**Issue by 19fever** [google/or-tools#254]
Hi, 
I am working on a dynamic vehicle routing problem.
Here is what I am trying to do, first I create 15 vehicles and 20 orders, and use the constraint as [pdptw.cc](https://github.com/google/or-tools/blob/master/examples/cpp/pdptw.cc#L261), and get routes R.
Then I create a new routing model and lock first half of routes R I got last step by [ApplyLocksToAllVehicles](http://www.lia.disi.unibo.it/Staff/MicheleLombardi/or-tools-doc/user_manual/manual/vrp/partial_routes.html). It works if I don't add PickupAndDelivery constraint or lock the whole routes R, but if I add PickupAndDelivery constraint before apply locks I got segmentation fault by calling MakeRelocateNeighborsOperator::MakeNeighbor(), any idea what's going on?

**Comment by 19fever** [comment]
It seems there will be a problem when I was trying to make use the rides assigned to the same vehicle given by last solution. I first use VehicleVar(pickup_node)->SetValue(vehicle_var) and add  MakeEquality(VehicleVar(pickup_node), VehicleVar(delivery_node)), PickupAndDelivery(pickup_node, delivery_node) constraints.
Actually there is no need to add these constraints since we just use VehicleVar(pickup_node)->SetValue(vehicle_var), VehicleVar(delivery_node)->SetValue(vehicle_var) to get things done.

**Comment by 19fever** [comment]
After I remove PickupAndDelivery, there is efficiency issue.

**Comment by furnon** [comment]
PickupAndDelivery is essential to make the solver work fast. I guess you
still are getting the segfault in MakeNeighbor(). We will look into this.
In the meantime you can disable the faulty operator by
setting use_relocate_neighbors to false
in RoutingSearchParameters::local_search_operators (it should be the
default).

**Comment by furnon** [comment]
Actually you can't disable the operator with the setting only (you could
edit the code though as a temporary solution, look for
use_relocate_neighbors in routing.cc). Do you have a stack trace to share
(in debug)?

**Comment by furnon** [comment]
A fix for this issue has been pushed.

**Comment by 19fever** [comment]
👍

**Comment by furnon** [comment]
Thanks to sestegra@gmail.com for finding a fix to the issue.

**Comment by sestegra** [comment]
Your welcome !
