### ISSUE TITLE
vehicle assignment is not happening - when vehicle travels from start node to end node without any nodes in between.

### ISSUE THREAD

**Issue by Charan-S-Salian** [google/or-tools#2540]
**What version of OR-Tools and what language are you using?**
Version: 9.0.9048
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)?
Routing Solver

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**

I copied the exact example code from the following link:
https://developers.google.com/optimization/routing/routing_tasks#setting-start-and-end-locations-for-routes

I changed following in create_data_model() function:
   ```
 data['distance_matrix'] =  [
                                                [0 , 10], 
                                                [10,  0]
                                             ]
    data['num_vehicles'] = 1
    data['starts'] = [1]
    data['ends'] = [0]
```

Basically,  the vehicle starts at node 1 and ends at node 0.

Added below code @ line 34.
`print("Is Vehicle used ?"+ str(routing.IsVehicleUsed(vehicle=vehicle_id, assignment=solution)))
`
Then I added below code @ line 53. (i.e. after this line -->  routing = pywrapcp.RoutingModel(manager))

```
for vehicle_id in range(data['num_vehicles']):
        routing.ConsiderEmptyRouteCostsForVehicle(True, vehicle_id)

```
**What did you expect to see**

Objective: 1010
**IS Vehicle used ?True**
Route for vehicle 0:
 1 -> 0
Distance of the route: 10m

Maximum of the route distances: 10m

**What did you see instead?**

Objective: 1010
**IS Vehicle used ?False**
Route for vehicle 0:
 1 -> 0
Distance of the route: 10m

Maximum of the route distances: 10m

**Doubt: Why vehicle assignment is not happening for this route??**

Make sure you include information that can help us debug (full error message, model Proto).
**I have attached the full code**
[VRP issue.txt](https://github.com/google/or-tools/files/6473138/VRP.issue.txt)

**Anything else we should know about your project / environment**

**Comment by Mizux** [comment]
Vehicle travelling from its start node to its end node is not (and will never be) considered as used even if start and end are different.
As a workaround, if you are not satisfied with this definition/implementation, you can try to post process the solution to modify this behavior in your code...
