### ISSUE TITLE
Unable to execute '$make third_party' command on Google colab with "Source installation on linux"

### ISSUE THREAD

**Issue by Vikranth-Inti** [google/or-tools#2542]
**What version of OR-Tools and what language are you using?**
Version: or-tools 9.0.9048
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Not yet installed or-tools

**What operating system (Linux, Windows, ...) and version?**
Ubuntu-18.04-LTS on Google Colab

**What did you do?**
---On Colab---
1 : !sudo apt-get install python3-dev python3-pip python3-venv python3-six
2 : !python3 -c "import platform; print(platform.architecture()[0])"
3 : !git clone https://github.com/google/or-tools
4 : !ls
5 : !cd or-tools/
6 : !make third_party

**What did you expect to see**
I expected the make file to be executed by building the source of third party packages.

**What did you see instead?**
I saw the error message : 
'make: *** No rule to make target third_party.  Stop.'

Make sure you include information that can help us debug (full error message, model Proto).

My colab notebook on github is [here ](https://github.com/Vikranth-Inti/Apprenticeship-in-Python/blob/main/Rough-Notebook2.ipynb )

**Anything else we should know about your project / environment**

On Google cloud (gcp always free tier) : 
I attempted same steps on the gcp terminal  : 
Commands : 
$sudo apt-get install python3-dev python3-pip python3-venv python3-six
$python3 --version
$python3 -c "import platform; print(platform.architecture()[0])"
$python3 -m pip --version
$git clone https://github.com/google/or-tools
$cd or-tools
$make third_party

But for the final 'make third_party' command,  I again got an error : 
make: *** [makefiles/Makefile.third_party.unix.mk:210: dependencies/install/lib/libprotobuf.a] Error 1 : 

Output message on gcp is : 
cloudshell:~/or-tools$ make third_party
/bin/sh: - : invalid option
/bin/sh: - : invalid option
/bin/sh: - : invalid option

cd dependencies/sources/protobuf-v3.15.8 && \
   /usr/bin/cmake -Hcmake -Bbuild_cmake \
    -DCMAKE_PREFIX_PATH="/home/vikranth_info/or-tools/dependencies/install" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_STANDARD=17 \
    -DCMAKE_CXX_STANDARD_REQUIRED=ON \
    -DCMAKE_CXX_EXTENSIONS=OFF \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    -DBUILD_SHARED_LIBS=OFF \
    -DBUILD_TESTING=OFF \
    -Dprotobuf_BUILD_TESTS=OFF \
    -Dprotobuf_BUILD_EXAMPLES=OFF \
    -DCMAKE_CXX_FLAGS="" \
    -DCMAKE_INSTALL_PREFIX=../../install && \
  /usr/bin/cmake --build build_cmake --config Release -v -- -j 4 && \
  /usr/bin/cmake --build build_cmake --config Release --target install

-- 3.15.8.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user-name/or-tools/dependencies/sources/protobuf-v3.15.8/build_cmake

Unknown argument -v
Usage: cmake --build <dir> [options] [-- [native-options]]
Options:
  <dir>          = Project binary directory to be built.
  -j [<jobs>] --parallel [<jobs>] = Build in parallel using
                   the given number of jobs. If <jobs> is omitted
                   the native build tool's default number is used.
                   The CMAKE_BUILD_PARALLEL_LEVEL environment variable
                   specifies a default parallel level when this option
                   is not given.
  --target <tgt> = Build <tgt> instead of default targets.
                   May only be specified once.
  --config <cfg> = For multi-configuration tools, choose <cfg>.
  --clean-first  = Build target 'clean' first, then build.
                   (To clean only, use --target 'clean'.)
  --use-stderr   = Ignored.  Behavior is default in CMake >= 3.0.
  --             = Pass remaining options to the native tool.
**_make: *** [makefiles/Makefile.third_party.unix.mk:210: dependencies/install/lib/libprotobuf.a] Error 1_**

**Comment by Mizux** [comment]
Maybe you didn't notice but your notebook is a .ipynb I.e. this is running inside a "Python Kernel" (you can see it as a super python interpreter) so this is not a complete Linux VM, to have python or-tools simply use `!pip install ortools`
e.g.  https://github.com/google/or-tools/blob/stable/examples/notebook/constraint_solver/cvrp.ipynb

**Comment by Vikranth-Inti** [comment]
@Mizux , I followed the instructions after setting runtime to defaults and it worked strikingly in the first shot. Thank you so much !
