### ISSUE TITLE
Add differentiatied cost for each type of vehicle?

### ISSUE THREAD

**Issue by Westlife1002** [google/or-tools#2543]
I have a question about adding specific cost for a vehicle. each type of vehicle would inccur a different cost, which is to be multiplied by the travel distance to determine the total cost. the goal is to find the optimal type and number of trucks needed to minize the total cost, subject to all other constraints.

I saw a way to add an universal route cost for all vehicles regardless of their size: 
routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)
I guess the default objective function is: Min (Total Travel Distance)

how to make differentiatied cost for each vehicle? hence the object function is: Min (Total Transport Cost)
things need to consider:
1. one-off fixed cost for using each type of vehicle (e.g. hiring cost)
2. cost per km differentiated for each type of vehicle (e.g. fuel cost)

my lastest codes is here: 
https://gist.github.com/Westlife1002/03f5f2a1b03841a81221623bce63951e

**Comment by tcokyasar44** [comment]
Just to increase the complexity, how about adding different costs for the same vehicle type? For example, a hybrid vehicle runs the first x distance/time on EV-mode, and hence the cost is lower than the distance/time after x. Meanwhile, another vehicle type with a fixed cost can be a benchmark. Is it possible to model this?

**Comment by lperron** [comment]
Not an issue. Please repost as discussion

**Comment by Mizux** [comment]
You can have a specific arc cost per vehicle please use this method:
https://github.com/google/or-tools/blob/b37d9c786b69128f3505f15beca09e89bf078a89/ortools/constraint_solver/routing.h#L905-L906

I.e. register an evaluator cost function per vehicle type, then use it for each vehicle of the same type.

For Vehicle FixedCost use this: https://github.com/google/or-tools/blob/b37d9c786b69128f3505f15beca09e89bf078a89/ortools/constraint_solver/routing.h#L907-L911
again same cost for all vehicles or a specific cost per vehicle...

**Comment by Mizux** [comment]
You may be interested by this samples: https://gist.github.com/Mizux/6d9283388150020df7542adf63577786#file-vrp_multiple_transit-py-L61-L69 vrp_multiple_transit.py
