### ISSUE TITLE
Xamarin-Android: The type initializer for 'SWIGExceptionHelper' threw an exception

### ISSUE THREAD

**Issue by disl** [google/or-tools#2546]
**What version of OR-Tools and what language are you using?**
Version: 9.0.9048.
Language: C#, Xamarin, Android project, 

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Google.OrTools.Sat

**What operating system (Linux, Windows, ...) and version?**
Edition	Windows 10 Home
Version	20H2
Build	19042.985
Windows Feature Experience Pack 120.2212.2020.0

**What did you do?**
Nurse scheduling sample:

```cs
foreach (int e in Range(numEmployees))
{
    foreach (int s in Range(numShifts))
    {
         foreach (int d in Range(numDays))
         {			
              string name = $"work{e}_{s}_{d}";

			**-- Error happens here !!!!!!!!!**
                        work[e, s, d] = model.NewBoolVar(name);
          }
    }
}
```

**What did you expect to see**

**What did you see instead?**
Error message

Make sure you include information that can help us debug (full error message, model Proto).

```
System.TypeInitializationException
  Error message = The type initializer for 'SWIGExceptionHelper' threw an exception.

Stack trace:
-		$exception	{System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: google-ortools-native assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Google.OrTools.Util.operations_research_utilPINVOKE+SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_operations_research_util(Google.OrTools.Util.operations_research_utilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.Util.operations_research_utilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.Util.operations_research_utilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.Util.operations_research_utilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.Util.operations_research_utilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.Util.operations_research_utilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.Util.operations_research_utilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.Util.operations_research_utilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.Util.operations_research_utilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.Util.operations_research_utilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Google.OrTools.Util.operations_research_utilPINVOKE/SWIGExceptionHelper/ExceptionDelegate)
  at Google.OrTools.Util.operations_research_utilPINVOKE+SWIGExceptionHelper..cctor () [0x000ee] in <e9a70ce725e846a0a458f19f86d295d3>:0 
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at Google.OrTools.Util.operations_research_utilPINVOKE..cctor () [0x00000] in <e9a70ce725e846a0a458f19f86d295d3>:0 }	System.TypeInitializationException
```
`

**Anything else we should know about your project / environment**
Visual Studio 2019 
Xamarin C#-Project
Android, iOS

**Comment by lperron** [comment]
What  CPU are you using ?
Is it 64 bit?

**Comment by disl** [comment]
Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz   1.70 GHz

64-Bit-Betriebssystem, x64-basierter Prozessor

**Comment by lperron** [comment]
Have you installed visual studio 2019 redistributable libraries ?
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by disl** [comment]
Yes. Unfortunately without success.

**Comment by Mizux** [comment]
Which OS are you running ? we currently only support these RID
`linux-x64`, `osx-x64` and `win-x64`
ref: https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#using-rids

If you run `dotnet --info` which RID did you see ?
e.g.
```sh
[0]─[~]
[^v^]─mizux@nuc10i7 %dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.114
 Commit:    07ddd844dc

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64  <<<<<<<< HERE
 Base Path:   /usr/share/dotnet/sdk/3.1.114/

Host (useful for support):
  Version: 5.0.5
  Commit:  561d6ea60d

.NET SDKs installed:
  3.1.114 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.NETCore.App 3.1.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by disl** [comment]
.NET SDK (gemäß "global.json"):
 Version:   5.0.203
 Commit:    383637d63f

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.203\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.524 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.816 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  3.0.100-rc1-014190 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.409 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-rc1.19457.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-rc1-19456-20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-rc1-19456-20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by disl** [comment]
Do you plan to implement Or-tools as a service (Web API), so that perhaps problems with adaptations for different platforms could be avoided?

**Comment by lperron** [comment]
1) I notice a win10-x64 vs win-x64 rid mismatch.
2) About services, maybe. But do not hold your breath :-)

**Comment by lperron** [comment]
So we have released linux arm64 dotnet.
So deploying to such architecture should be possible.

I will close the bug now. Please reopen if needed.
