### ISSUE TITLE
Capacitated VRPTW with different types of orders

### ISSUE THREAD

**Issue by rajatjangir** [google/or-tools#255]
Hi, i have been working on vehicle routing problem and the library has been very good, i have been stuck at a place and cant find a working example in the repo nor on stackoverflow.

The problem : I have been successfully able to assign capacities to the individual vehicles along with pickup and delivery constraint but now i am trying to add capacity constraint such that vehicle can add capacities depending on the type of order. For example.
Consider a scenario when i have to pickup and deliver 10 orange and 3 watermelons from a place and drop at some other place, now i am only able to assign capacity to the vehicle using AddDimension() function but how to mention that a car is capable of carrying for example 50 oranges and 10 watermelons and check for those constraint on each node so that i can pickup multiple order from multiple nodes.

So in cases when at some node i would have to pickup 2 watermelons and my vehicle has filled its watermelon capacity but still has space for oranges then that vehicle should reject that node as the vehicle has available space for oranges only.

I hope i was not too confusing with my example. Let me know if you need more data or any other input. I'll promptly reply here.

**Comment by furnon** [comment]
Why don't you create 2 dimensions: one for oranges and one for watermelons
? The "demand" for an order of watermelons (resp. oranges) would be 0 for
oranges (resp. 0 for watermelons).
You can also add a third dimension if you have an overall capacity such as
total weight carried.

**Comment by rajatjangir** [comment]
Yeah that helped a lot and i tried to implement it but when i add multiple dimension according to different demands it works fine but how to associate those demands to the combined capacity of vehicle.
I am not able to figure out constraints to do that.
Also i don't want to set total capacity but capacity for a specific type of fruit for a particular vehicle.
Example car 1 can take 20 apples and 30 oranges or car 2 can take only 50 apples.

**Comment by furnon** [comment]
You can have capacities which are different for each vehicle and dimension
with AddDimensionWithVehicleCapacity; so car 1 would have a capacity of 20
on the apple dimension, 30 on the orange dimension, car 2 would have a
capacity of 50 on apples and 0 on oranges.
As for the third (optional) global capacity dimension, the trick is to have
its transit callback return the value of the orange callback and the apple
callback (if it makes sense).

**Comment by bendichter** [comment]
I have a similar problem. Say a pickup location has 50 apples and 50 oranges, but the vehicle can only hold 70 fruits. How do I set the dimensions such that a truck does not exceed its total weight capacity? Would I use a transit callback? Could you expand on how I would use this?
Thanks for the help!

**Comment by bendichter** [comment]
one solution might be to have 2 nodes for a single facility, each with two demands:

apple_node: {apples: 50, oranges: 0, weight: 50}
orange_node: {apples: 0, oranges: 50, weight: 50}

Is this what you would recommend?

**Comment by furnon** [comment]
On Nov 9, 2016 7:53 AM, "bendichter" <notifications@github.com> wrote:
>
> one solution might be to have 2 nodes for a single facility, each with
two demands:
>
> apple_node: {apples: 50, oranges: 0, weight: 50}
> orange_node: {apples: 0, oranges: 50, weight: 50}
>
> Is this what you would recommend?

I would recommend a single node with three demands:
node: {apples: 50, oranges: 50, weight: 100}
Or would you want to perform partial pickups?

**Comment by bendichter** [comment]
yes, I would like partial pickups. The vehicle in the example can only fit 70 fruits.

**Comment by furnon** [comment]
Then yes, you need 2 nodes.

**Comment by bendichter** [comment]
I got it working! Thanks so much for your help! :-)
