### ISSUE TITLE
Missing module routing_enums_pb2 when using pyinstaller to pack the model

### ISSUE THREAD

**Issue by Westlife1002** [google/or-tools#2551]
I am trying to pack my VRP model as a single exe file, using pyinstaller.

after the pyinstaller operations, when I run the exe there reports an erro concerning missing module routing_enums_pb2:

![image](https://user-images.githubusercontent.com/34776946/118438248-9f9d9400-b716-11eb-805c-49497567cef4.png)

where could be going wrong?

BTW: I have no problem to run the model in pycharm

my lastest full codes is here:
https://gist.github.com/Westlife1002/03f5f2a1b03841a81221623bce63951e

**Comment by lperron** [comment]
clearly you are not packing everything.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le lun. 17 mai 2021 à 07:51, Westlife1002 ***@***.***> a
écrit :

**Comment by Mizux** [comment]
On which platform (OS) are you running this script ? Windows 10 ?

**Comment by Mizux** [comment]
Also did you try to look at the dist directory generated or did you try to hack the pyinstaller command line to give the missing files ?
ref: https://pyinstaller.readthedocs.io/en/latest/operating-mode.html#analysis-finding-the-files-your-program-needs

**Comment by Westlife1002** [comment]
> Also did you try to look at the dist directory generated or did you try to hack the pyinstaller command line to give the missing files ?
> ref: https://pyinstaller.readthedocs.io/en/latest/operating-mode.html#analysis-finding-the-files-your-program-needs

I manage to manual add the missing module:
pyinstaller --onefile  --hiddenimport=ortools.constraint_solver.routing_parameters_pb2 --ico=truck.ico VRP_10.0.py
I can then run the exe sucessfully on my own computer. However, when change to another computer, it shows:
![image](https://user-images.githubusercontent.com/34776946/118473238-53fde100-b73c-11eb-9d24-2b0fdf9bfbb0.png)

and by looking at the command line, the reported issue is about missing pywrpcp.py
![image](https://user-images.githubusercontent.com/34776946/118473383-7abc1780-b73c-11eb-9bc9-291ad91bea2a.png)
