### ISSUE TITLE
ortools DLL load failed using PyInstaller 

### ISSUE THREAD

**Issue by Westlife1002** [google/or-tools#2552]
I am using pyinstaller to pack my model as a exe file.
after installation, the exe is running ok on my own computer. However, when change to another computer and click the exe, it pops up:

![image](https://user-images.githubusercontent.com/34776946/118475382-c53e9380-b73e-11eb-90b9-e14746d1ecaf.png)

and by looking at the command line, the reported issue is about missing pywrpcp.py

`File "ortools\constraint_solver\pywrapcp.py", line 13, in <module>`

**Comment by Mizux** [comment]
Does this "other" computer have the VS redistributable ?
My guess is pyinstaller won't pack system dll so you have to install it manually first

see: https://developers.google.com/optimization/install/python/windows#microsoft-visual-c++-redistributable

**Comment by Westlife1002** [comment]
> Does this "other" computer have the VS redistributable ?
> My guess is pyinstaller won't pack system dll so you have to install it manually first
> 
> see: https://developers.google.com/optimization/install/python/windows#microsoft-visual-c++-redistributable

Yes, I am now downloading from here: 
https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

how to check if any machine is installed with VS redistributable?  

I remember I packed the same model 3 years ago using pyinstaller, and run the exe on the machine without VS redistributable successfully. Are there any changes in ortools which is now very dependent on VS redistributable?

**Comment by Westlife1002** [comment]
> > Does this "other" computer have the VS redistributable ?
> > My guess is pyinstaller won't pack system dll so you have to install it manually first
> > see: https://developers.google.com/optimization/install/python/windows#microsoft-visual-c++-redistributable
> 
> Yes, I am now downloading from here: (please let me know if it is wrong. the file is very big to download and install)
> https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0
> 
> how to check if any machine is installed with VS redistributable?
> 
> I remember I packed the same model 3 years ago using pyinstaller, and run the exe on the machine without VS redistributable successfully. Are there any changes in ortools which is now very dependent on VS redistributable?

**Comment by lperron** [comment]
No. OR-tools always required redistributables.
Now, the visual studio version has changed.

**Comment by Westlife1002** [comment]
> No. OR-tools always required redistributables.
> Now, the visual studio version has changed.

show I install Visual Studio 2019 or Visual Studio Code?

**Comment by lperron** [comment]
visual studio code is just an editor.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le lun. 17 mai 2021 à 13:00, Westlife1002 ***@***.***> a
écrit :

**Comment by Mizux** [comment]
both are IDE, here you just need some C++ runtime libraries so you need the Visual Studio 2019 **REDISTRIBUTABLE**.
note: when installing Visual Studio 2019 you have a option to install it as well as a component for C++ dev.

**Comment by Westlife1002** [comment]
> note: when installing Visual Studio 2019 you have a option to also install the redistributable as an internal component for C++ dev.

what do you mean by internal component ?
