### ISSUE TITLE
Strange interaction between assumptions interface and using more than one search worker

### ISSUE THREAD

**Issue by lalithsuresh** [google/or-tools#2563]
**What version of OR-Tools and what language are you using?**
Version: 9.0.9048
Language: Java 12.0.1

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

CP-SAT

**What operating system (Linux, Windows, ...) and version?**

Mac OSX Big Sur 11.3.1

**What did you do?**

```java
@Test
    public void assumptionsTest() {
        final CpModel model = new CpModel();
        final IntVar i1 = model.newIntVar(0, 5, "i1");
        final IntVar i2 = model.newIntVar(0, 5, "i2");
        final IntVar v1 = model.newBoolVar("v1");
        final IntVar v2 = model.newBoolVar("v2");
        final IntVar v3 = model.newBoolVar("v3");

        model.addGreaterOrEqual(LinearExpr.sum(new IntVar[]{i1, i2}), 11).onlyEnforceIf(v1); // can't be satisfied
        model.addLessOrEqual(LinearExpr.sum(new IntVar[]{i1, i2}), 5).onlyEnforceIf(v2);
        model.addEquality(v3, 1);
        model.addAssumption(v1);
        model.addAssumption(v2);
        model.addAssumption(v3);
        final CpSolver solver = new CpSolver();
        // solver.getParameters().setNumSearchWorkers(4); // Uncommenting this line changes the behavior
        final CpSolverStatus status = solver.solve(model);

        assertEquals(CpSolverStatus.INFEASIBLE, status);
        for (final int varIndex: solver.sufficientAssumptionsForInfeasibility()) {
            System.out.println(model.getBuilder().getVariables(varIndex).getName()); // Should print variable "v1"
        }
    }
```

**What did you expect to see**

If I run the above code, as is, I get the expected result printed:

```
v1
```

**What did you see instead?**

If I uncomment the `solver.getParameters().setNumSearchWorkers(4);` line, I instead see:

```
v1
v2
v3
```

Sure, it is sufficient, but looks like a bug. Basically, `solver.sufficientAssumptionsForInfeasibility()` returns all configured assumption literals, even ones that are trivially unrelated to the actual unsat condition (like v3). This was happening in a much larger model where I began debugging this.

It seems to work fine with 1 search worker only.
 
**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
Indeed

see: https://github.com/google/or-tools/blob/b37d9c786b69128f3505f15beca09e89bf078a89/ortools/sat/cp_model_solver.cc#L3125

Assumptions will only work in single thread,

**Comment by lalithsuresh** [comment]
Thanks for the quick response. So for now, I'd need to re-run the model with a single thread and remove objective functions as well if UNSAT, to get a smaller set of assumptions.

Will these constraints be relaxed in the future?

**Comment by lperron** [comment]
We are not planning for it.

objective: you have a tradeoff between satisfying assumptions and improving
the objective. If you have an objective, move the assumptions to the
objective.

parallelism: the current algorithm is inherently sequential.  You could
imagine pre-assigning some assumptions to different workers. This can be
done outside the solver.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le sam. 22 mai 2021 à 19:57, Lalith Suresh ***@***.***> a
écrit :
