### ISSUE TITLE
missing SetDepot before AddDisjunction crashes

### ISSUE THREAD

**Issue by prinsherbert** [google/or-tools#257]
In python 2.7 I noticed that `AddDisjunction` called before `SetDepot` crashes the application, probably with a segfault (I'm using the python bindings, and python crashes).

A minimal failing example:

```
from ortools.constraint_solver import pywrapcp

routing = pywrapcp.RoutingModel(2, 1)
# routing.SetDepot(0)
routing.AddDisjunction([1], int(1e8))
```

Uncommenting the `SetDepot` solves the problem, but I would either expect an exception or the default behavior that `0` is the depot.

**Comment by dlahlou** [comment]
Hello @prinsherbert,

Thank you for your message, we will fix this soon.

Regards.

**Comment by dlahlou** [comment]
We pushed a commit concerning this bug. The RoutingModel constructor used in your example will not be available from now on under this signature `RoutingModel(int nodes, int vehicles)`, it was replaced by this [one](https://github.com/google/or-tools/blob/master/src/constraint_solver/routing.h#L353), which will fix the bug undirectly.

Thank you.
