### ISSUE TITLE
Flexible Job Shop Problem + jobs with minimum and maximum start time

### ISSUE THREAD

**Issue by asonesc** [google/or-tools#2574]
**What language and solver does this apply to?**
All

**Describe the problem you are trying to solve.**

I am trying to build a program that outputs time windows where a job could be done.
Before a new task is going to be scheduled, I want to simulate when that job could be done, considering all the pre-existing jobs.

- All jobs that can be done in any machine.
- Each job has a duration, a minimum start time and a maximum start time.
- I am using flexible_job_shop_sat.py as example (Thanks Laurent!), however, I have a question.

Is there a feature to add min and max start times for each job? How could that be implemented?

Thanks!

**Comment by lperron** [comment]
Not an issue.
