### ISSUE TITLE
Native resource loader should avoid loading the same resource path from other jars.

### ISSUE THREAD

**Issue by xianyinxin** [google/or-tools#2575]
**What version of OR-Tools and what language are you using?**
Version: v9.0.
Language: Java

**What did you expect to see**

JVM could load ortools lib correctly.

**What did you see instead?**

The ortools lib could not be loaded correctly.

The current native resource Loader (for Java) firstly `getNativeResourceURI()` from the class path. However, it just locates the native lib via a resource path: Platform.RESOURCE_PREFIX + "/", for eg, darwin-x86-64/, or linux-x86-64.

It is possible that other jars has the same resource directory. In this case, the loader could not load the native lib sometimes.

**Comment by Mizux** [comment]
https://github.com/google/or-tools/blob/b37d9c786b69128f3505f15beca09e89bf078a89/ortools/java/com/google/ortools/Loader.java#L35-L40

So what do you suggest we should try to use
`ortools-darwin-x86-64/` aka `"ortools-" + Platform.RESOURCE_PREFIX + "/"` or something like that ?

any suggestion is welcome...

**Comment by xianyinxin** [comment]
@Mizux Thanks for the reply. My original idea is use `loader.getResources(resource)` and filter it by `"ortools-darwin-x86-64"`. Comparing your suggestions, this may decrease the loading performance a little bit, so i think your idea is better.

**Comment by Mizux** [comment]
so we should change:
https://github.com/google/or-tools/blob/b37d9c786b69128f3505f15beca09e89bf078a89/cmake/java.cmake#L141
to
```cmake
 ${JAVA_RESOURCES_PATH}/ortools-${NATIVE_IDENTIFIER}/ 
```

and same for Makefile:
https://github.com/google/or-tools/blob/b37d9c786b69128f3505f15beca09e89bf078a89/makefiles/Makefile.java.mk#L440
to
```make
 $(COPY) $(subst /,$S,$(JAVA_ORTOOLS_NATIVE_LIBS)) $(JAVA_NATIVE_PATH)$Sresources$Sortools-$(JAVA_NATIVE_IDENTIFIER)
```

**Comment by xianyinxin** [comment]
Yep, I think so. I'll create a PR later.
