### ISSUE TITLE
Building or-tools for python from source fails with glpk with a amd64/ubuntu base image

### ISSUE THREAD

**Issue by sakha002** [google/or-tools#2579]
**What version of OR-Tools and what language are you using?**
Version: master/v7.3/v7.2 etc.
Language: C++/Java/Python/C#

building from stable branch
Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

GLPK

**What operating system (Linux, Windows, ...) and version?**

amd64/ubuntu base docker image

**What did you do?**

```dockerfile
FROM amd64/ubuntu
ENV DEBIAN_FRONTEND=noninteractiv
RUN  apt-get update &&  apt-get install -y  \
    git wget pkg-config build-essential cmake autoconf libtool zlib1g-dev lsb-release
RUN apt -y install swig
RUN apt-get update && apt-get install -y python3-dev python3-pip python3-venv python3-six
RUN git clone https://github.com/google/or-tools
WORKDIR /or-tools
RUN  make third_party
RUN apt-get update && apt-get install -y libglpk-dev glpk-utils glpk-doc  libgmp10 libgmpxx4ldbl
RUN sed -i "1 a UNIX_GLPK_DIR = \/usr\/lib\/x86_64-linux-gnu\n" ./Makefile.local
RUN make python
```

**What did you expect to see**

completing the build

**What did you see instead?**

ortools glpk g++: error: /usr/bin/lib/libglpk.a: No such file or directory

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

Also I did some search and found that the glpk installation via the apt-get does not place the libglpk.a under /lib/
so I tried to change that with
 RUN find . -type f -exec sed -i 's/lib\/libglpk.a/libglpk.a/g' {} +

but I got this error

#15 1015.4 /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libglpk.a(libglpk_la-tls.o): relocation R_X86_64_TPOFF32 against `tls' can not be used when making a shared object; recompile with -fPIC
#15 1015.4 /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libglpk.a(libglpk_la-stdc.o): relocation R_X86_64_TPOFF32 against `result.4651' can not be used when making a shared object; recompile with -fPIC
#15 1015.4 /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libglpk.a(libglpk_la-prob1.o): relocation R_X86_64_PC32 against symbol `glp_set_row_name' can not be used when making a shared object; recompile with -fPIC

I much appreciate if you could advise me on how to setup correctly.

**Comment by Mizux** [comment]
https://github.com/google/or-tools/blob/fa84bc05e72641dddfbb98164d81b8bc9bef6ea5/makefiles/Makefile.unix.mk#L131
