### ISSUE TITLE
[Win10] Attempting to install from source 

### ISSUE THREAD

**Issue by houmanchin** [google/or-tools#258]
Hi,

I'm attempting to install it from the source as per [here](https://developers.google.com/optimization/installing#compiling-libraries-from-source) after forking the or-tools repo on git. However I'm getting the following error. 

`C:\or-tools>make all
makefiles/Makefile.port:127: "Unrecognized visual studio version"
cl /EHsc /MD /nologo -nologo  /O2 -DNDEBUG /Isrc /Iexamples /Isrc\\gen /IC:\\or-tools\\dependencies\\install\\include /DGFLAGS_DLL_DECL= /DGFLAGS_DLL_DECLARE_FLAG= /DGFLAGS_DLL_DEFINE_FLAG= /IC:\\or-tools\\dependencies\\install\\include  /IC:\\or-tools\\dependencies\\install\\include /IC:\\or-tools\\dependencies\\install\\include /DUSE_CBC /IC:\\or-tools\\dependencies\\install\\include /DUSE_CLP     /DUSE_GLOP /DUSE_BOP /D__WIN32__  /IC:\\or-tools\\dependencies\\install\\include /DPSAPI_VERSION=1  -c src/base/bitmap.cc /Foobjs\\base\\bitmap.obj
bitmap.cc
src\base/bitmap.h(17): fatal error C1083: Cannot open include file: 'string.h': No such file or directory
make: *** [objs/base/bitmap.obj] Error 2`

Where do I get the missing file? Also, I have VS2015 installed which it doesn't seem to recognise...

Any help would be greatly appreciated, thanks!

**Comment by dlahlou** [comment]
Hello,

The "Unrecognized visual studio version" message makes me think that you're using a generic windows command line and not the one from Visual Studio, if it is the case, please open a command line from the Visual Studio installation folder and restart everything.

I hope this helps.

Driss

**Comment by bacalfa** [comment]
I'm having a similar problem. Just cloned the repository, so I have the latest version. Opened the "Developer Command Prompt for Visual Studio" and the following happened:

```
C:\Users\abreucb\Downloads\or-tools>echo %VisualStudioVersion%
14.0

C:\Users\abreucb\Downloads\or-tools>make all
makefiles/Makefile.port.mk:136: "Unrecognized visual studio version"
ERROR: Invalid pattern is specified in "path:pattern".
/bin/sh: c:UsersabreucbAppDataLocalContinuumanaconda3\python.exe: No such file o
r directory
/bin/sh: c:UsersabreucbAppDataLocalContinuumanaconda3\python: No such file or di
rectory
/bin/sh: c:UsersabreucbAppDataLocalContinuumanaconda3\python: No such file or di
rectory
One of the third party files was not found! did you run 'make third_party'?
make: *** [third_party_check] Error 1
```

**Comment by bacalfa** [comment]
It seems it depends on which `make.exe` you're using. I have both Cygwin and MinGW-x64 installed. Using the latter, I get:

```
C:\Users\abreucb\Downloads\or-tools>"C:\Program Files\mingw-w64\x86_64-7.2.0-win
32-seh-rt_v5-rev1\mingw64\bin\mingw32-make.exe" all
/bin/sh: toolssed.exe: command not found
ERROR: Invalid pattern is specified in "path:pattern".
/bin/sh: toolssed: command not found
/bin/sh: c:UsersabreucbAppDataLocalContinuumanaconda3\python.exe: No such file o
r directory
/bin/sh: c:UsersabreucbAppDataLocalContinuumanaconda3\python: No such file or di
rectory
/bin/sh: c:UsersabreucbAppDataLocalContinuumanaconda3\python: No such file or di
rectory
One of the third party files was not found! did you run 'make third_party'?
mingw32-make: *** [Makefile:72: third_party_check] Error 1
```

It doesn't recognize some commands.

**Comment by Mizux** [comment]
I guess is related to #576 where a "wrong" shell is used by Make.

I think I can close this issue since now we try to detect if we are using the correct shell (i.e. not git sh.exe).
Please test using the v6.7 Release
