### ISSUE TITLE
Are there any plans to add a wrapper for Julia language?

### ISSUE THREAD

**Issue by Lewis-Liu** [google/or-tools#2584]
**What language and solver does this apply to?**
[Julia](https://julialang.org/)   

**Describe the problem you are trying to solve.**
Use Julia to call **OR-Tools**.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lperron** [comment]
No. We will accept contributions. But I have no time for that effort.

**Comment by Mizux** [comment]
Currently wrapper for Python, Java and .Net are provided thanks to SWIG which can generate them.

SWIG doesn't support Julia, could be done by https://github.com/JuliaInterop/Cxx.jl

**Comment by dourouc05** [comment]
MathOpt should soon get a C API, which should be useful to get a Julia wrapper. It won't be have the same level of support as the existing Python, .Net, and Java wrappers, though.
