### ISSUE TITLE
Multiple Choice Knapsack Problem

### ISSUE THREAD

**Issue by Eddie-Hartman** [google/or-tools#2585]
**What language and solver does this apply to?**
All

**Describe the problem you are trying to solve.**
Multiple Choice Knapsack Problem.

Benefit Cost optimization where the options that I have can be exclusive. So I have multiple sets of options where I can either pick one or none of the options and must spend money to maximize benefit to the system.

**Describe the solution you'd like**
Any heuristic solution with reasonable accuracy and run time.

**Describe alternatives you've considered**
I've written a couple algorithms myself, but know that they can be improved upon. I've looked into some research papers regarding the topic as well, but feel overwhelmed with what is the best option or path to take.

**Additional context**
To reiterate the problem, I have a set of actions (A1, A2, A3) that I can perform on a set of assets (B1, B2, B3) where each of these have a benefit and cost to performing the action on the asset. I can only perform at most one action on each asset though. I want to maximize the benefit to the entire network while spending the entire budget available.

I do not know if this is currently possible with OR-Tools currently and am waiting to join the Google Group currently. From what I understand this is a Multiple Choice Knapsack Problem and I did not see documentation on solving this kind of problem with this tool.

**Comment by lperron** [comment]
This is not a product issue. Please use github discussions or the mailing list.

**Comment by Eddie-Hartman** [comment]
@lperron Apologies. I wasn't aware of Github discussions. I sent a request to join the google group and saw an unanswered question here:
https://groups.google.com/g/or-tools-discuss/c/1VcnJzEWKQA/m/PDTq2w_YiTAJ
I was assuming that the feature doesn't exist so was trying to put in a feature request for it which IS a Github issue type with a template. So if you don't want feature requests here it should probably be changed.
