### ISSUE TITLE
CP-SAT-Solving Infeasible Constraint

### ISSUE THREAD

**Issue by inf72** [google/or-tools#2590]
Version: 9.0.9048
Language: Python
Solver : CP-SAT 
OS : Ubuntu 16.04.6 LTS

Currently i work with CP-SAT or-tools to build with many of constraints, but there are a problem that the model that i build was unfeasible, so is there any features or method to get the bad constraints ?

thank you,

**Comment by lperron** [comment]
1) not a solver issue.
2) This was asked multiple times, and answered before.
