### ISSUE TITLE
Linear Sum Assignment return infeasible result for different number of worker and task

### ISSUE THREAD

**Issue by pradithya** [google/or-tools#2597]
**What version of OR-Tools and what language are you using?**
Version: v8.2
Language: Java/Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
LinearSumAssignment

**What operating system (Linux, Windows, ...) and version?**
MacOS 10.15.7

**What did you do?**
Run linear sum assignment sample https://developers.google.com/optimization/assignment/linear_assignment but with only 3 workers (see code snippet below). 

```
from __future__ import print_function
from ortools.graph import pywrapgraph
import time

def main():
  cost = create_data_array()
  rows = len(cost)
  cols = len(cost[0])

  assignment = pywrapgraph.LinearSumAssignment()
  for worker in range(rows):
    for task in range(cols):
      if cost[worker][task] != 'NA':
        assignment.AddArcWithCost(worker, task, cost[worker][task])
  solve_status = assignment.Solve()
  if solve_status == assignment.OPTIMAL:
    print('Total cost = ', assignment.OptimalCost())
    print()
    for i in range(0, assignment.NumNodes()):
      print('Worker %d assigned to task %d.  Cost = %d' % (
            i,
            assignment.RightMate(i),
            assignment.AssignmentCost(i)))
  elif solve_status == assignment.INFEASIBLE:
    print('No assignment is possible.')
  elif solve_status == assignment.POSSIBLE_OVERFLOW:
    print('Some input costs are too large and may cause an integer overflow.')
def create_data_array():
  cost = [[90, 76, 75, 70],
          [35, 85, 55, 65],
          [125, 95, 90, 105],
          # [45, 110, 95, 115] 
          ]
  return cost
if __name__ == "__main__":
  start_time = time.clock()
  main()
  print()
  print("Time =", time.clock() - start_time, "seconds")
```

**What did you expect to see**
Should return `OPTIMAL` result

**What did you see instead?**
It returns `INFEASIBLE`. It returns same result when I try with 4 workers 3 tasks, i.e.
```
  cost = [[90, 76, 75],
          [35, 85, 55,],
          [125, 95, 90,],
          [45, 110, 95] 
          ]
```
Is there limitation for LinearSumAssignment that number of workers must be same as number of tasks?

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
yes. The number of task must be equal to the number of workers.

**Comment by pradithya** [comment]
@lperron Thanks for clarifying, is it also not possible to have different list of worker id and task id?
For example
workers = [0,1,2,3]
tasks = [1,2,3,4]

**Comment by Mizux** [comment]
solver use zero indexed array but feel free to remap to anything you want in a post process.

Otherwise you should use the CP-SAT assignment sample so you'll be able to express one worker perform several tasks...
