### ISSUE TITLE
"SCIP was compiled without task processing. Parallel solve not possible"

### ISSUE THREAD

**Issue by RobTrifiletti** [google/or-tools#2598]
**What version of OR-Tools and what language are you using?**
Version: 9.0.9048
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
SCIP

**What operating system (Linux, Windows, ...) and version?**
Linux. Details:
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**What did you do?**
Ran the example on https://developers.google.com/optimization/assignment/assignment_example#complete_programs where I added "solver.setNumThreads(2);".

**What did you expect to see**
OPTIMAL result returned.
**What did you see instead?**
ABNORMAL. When I enabled logs (solver.enableOutput();) I saw the INFO message:
"SCIP was compiled without task processing. Parallel solve not possible"

**Anything else we should know about your project / environment**
Using the provided jars on maven:
- https://mvnrepository.com/artifact/com.google.ortools/ortools-java/9.0.9048
- https://mvnrepository.com/artifact/com.google.ortools/ortools-linux-x86-64/9.0.9048

Note that when I run the above on my osx setup everything works as expected.

**Comment by lperron** [comment]
Known issue.
We build scip with parallelism enabled on all platforms.  It does not work
on Linux.

Le mar. 15 juin 2021 à 12:59, RobTrifiletti ***@***.***> a
écrit :

**Comment by RobTrifiletti** [comment]
I see. Is there a way to fix it on the user side? We would like to be able to run the code with multiple threads.

**Comment by lperron** [comment]
No, I guess compilation flags have to be fixed. But I do not know how.
Side note, the benefits of parallelism are very limited. Getting more than
a 2x speedup is rare.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mar. 15 juin 2021 à 13:24, RobTrifiletti ***@***.***> a
écrit :

**Comment by Mizux** [comment]
if it doable you can also try to port your assignment model to CP-SAT which can be faster in some case AND support multi-threads...

**Comment by RobTrifiletti** [comment]
Thanks for the suggestion. I will look into CP-SAT. A side-comment. I just tried using CBC, which seems to work on linux. However, it is now crashing on osx (regardsless of thread count set). Is it know that CBC does not work on osx?

**Comment by Mizux** [comment]
CBC should work on OSX but CBC code base is..... so I'm not surprised by this kind of encounter.
