### ISSUE TITLE
IntVar == None Segfaults

### ISSUE THREAD

**Issue by illuzen** [google/or-tools#260]
I don't think this is the intended behavior. Comparison between an IntVar and None results in a SegFault. What is extra strange is that using 'is' instead of '==' doesn't segfault.

`uname -a
Linux 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

`bpython version 0.15 on top of Python 3.4.3 /usr/bin/python3

> > > import ortools
> > > ortools.**version**
> > > '4.3.3805'
> > > from ortools.constraint_solver import pywrapcp
> > > solver = pywrapcp.Solver('my solver')
> > > x = solver.IntVar(0, 3, 'var_name')
> > > x is None
> > > False
> > > x == None
> > > Segmentation fault (core dumped)`

**Comment by lperron** [comment]
Yes, I overloaded the == operator to support writing constraints.
I need to look at it.

**Comment by lperron** [comment]
I have fixed it for the CP-SAT solver.
