### ISSUE TITLE
Check failed: SolutionIsFeasible in CP-SAT solver - another issue

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#2602]
**What version of OR-Tools and what language are you using?**
Version: v8.2
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Linux(Debian 10), Windows 10

**What did you do?**
I executed attached proto file with 8 search workers.

**What did you expect to see**
No crash.

**What did you see instead?**
After some solutions, an error was thrown on check.

I0124 04:52:25.728271 22298 synchronization.cc:121] #215   141.21s best:10849 next:[8731,10848] no_lp fixed_bools:85875/762859
F0124 04:52:31.977050 22296 cp_model_solver.cc:2592] Check failed: SolutionIsFeasible( *shared_->model_proto, std::vector<int64>(local_response.solution().begin(), local_response.solution().end())) rnd_var_lns_default(d=0.94 s=84 t=0.10 p=1.00)
*** Check failure stack trace: ***
Aborted

Make sure you include information that can help us debug (full error message, model Proto).

[error_proto.zip](https://github.com/google/or-tools/files/6672469/error_proto.zip)

**Anything else we should know about your project / environment**
The issue seems same as issue in #2525 but I was not able to reproduce it in v9.0 (fix that closed #2525 was commited after v9.0) and current master.

**Comment by lperron** [comment]
Can you try with 9.0 ?
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by lperron** [comment]
How frequent is the crash ?
I ran a few times on my workstation with 16 workers. It never crashed and
proves the optimal is ~40s.


Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by gregy4** [comment]
I already tried it with 9.0 and today master. In both versions it works as I wrote in description of the issue.

Fix for #2525 was commited after 9.0 so it is quite surprise for me that version 9.0 works for me.

**Comment by gregy4** [comment]
With 8 workers it crashed everytime on windows 10 or debian 10 with ortools 8.2.

**Comment by lperron** [comment]
#2525 was a bug on the solution checker of the reservoir constraint.
Your new model does not contain reservoirs.

I will close the issue.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
