### ISSUE TITLE
Product constraint for variables spanning zero incorrectly leads to INFEASIBLE

### ISSUE THREAD

**Issue by lalithsuresh** [google/or-tools#2618]
**What version of OR-Tools and what language are you using?**
Version: master/v7.3/v7.2 etc.
Language: C++/Java/Python/C#

Version: 9.0
Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

CP-SAT

**What operating system (Linux, Windows, ...) and version?**

Mac OSX 11.4

**What did you do?**

Consider the two models, which are identical except for the domains of IntVars left and right.
```java
    @Test
    public void multVarsNoZeroInDomain() {
        final IntVar left = model.newIntVar(2, 6, "");
        final IntVar right = model.newIntVar(2, 6, "");
        final IntVar mult = model.newIntVar(-12, 12, "");
        model.addProductEquality(mult, new IntVar[]{left, right});
        model.addEquality(mult, 12);

        final CpSolver solver = new CpSolver();
        final CpSolverStatus solve = solver.solve(model);
        assertEquals(CpSolverStatus.OPTIMAL, solve);
        assertEquals(solver.value(mult), solver.value(left) * solver.value(right));
    }

```

```java
    @Test
    public void multVarsSpanningZero() {
        final IntVar left = model.newIntVar(-2, 6, "");
        final IntVar right = model.newIntVar(-2, 6, "");
        final IntVar mult = model.newIntVar(-12, 12, "");
        model.addProductEquality(mult, new IntVar[]{left, right});
        model.addEquality(mult, 12);

        final CpSolver solver = new CpSolver();
        final CpSolverStatus solve = solver.solve(model);
        assertEquals(CpSolverStatus.OPTIMAL, solve);
        assertEquals(solver.value(mult), solver.value(left) * solver.value(right));
    }

```

**What did you expect to see**

With https://github.com/google/or-tools/issues/2133 fixed, I expect both tests to pass.

**What did you see instead?**

For `multVarsSpanningZero()`, the solver says the problem is `INFEASIBLE`.

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
Thanks for the bug report. I will soon push the fix.
