### ISSUE TITLE
springboot jar 形式启动

### ISSUE THREAD

**Issue by wu603772498** [google/or-tools#2621]
java.lang.RuntimeException: java.nio.file.NoSuchFileException: /BOOT-INF/lib/ortools-linux-x86-64-9.0.9048.jar!/linux-x86-64/

**Comment by Mizux** [comment]
maybe related to #2330

**Comment by Robot-1x** [comment]
I think it is related to #2428. Maybe method works for you. 
I test in my Mac and Linux(centos 8.x) system. This method works well except M1 platform. :joy:
Besides, it is not fixed for jar file. I will provide a simple test project to describe this issue.

**Comment by lperron** [comment]
Solution found here: https://github.com/google/or-tools/discussions/3553

Please reopen if it does not work.
