### ISSUE TITLE
Add quadratic support for CPLEX

### ISSUE THREAD

**Issue by jonmather** [google/or-tools#2622]
Support currently exists for SCIP and Gurobi, but I'm wondering how difficult it would be to add support for CPLEX?

Ideally we'd be able to specify a quadratic problem for solving with CPLEX via the linear solver proto interface, using MPQuadraticObjective.

This issue was considered here https://github.com/google/or-tools/issues/1434, but the issue is now closed.

**Comment by lperron** [comment]
CPLEX is community based. We welcome contribution, but we will not spend time on it.

**Comment by amirmm11** [comment]
Thanks, @Mizux. Would you mind reopening the issue since you already added it to v9.1?
