### ISSUE TITLE
Linker error with CMake and externally-built abseil-cpp

### ISSUE THREAD

**Issue by marekp0** [google/or-tools#2623]
**What version of OR-Tools and what language are you using?**
Version: master
Language: C++
Build system: CMake

**What operating system (Linux, Windows, ...) and version?**

Ubuntu 20.04

**What did you do?**

Built abseil-cpp manually using CMake, then installed it. Then tried to build or-tools using CMake, pointing to the abseil I built. Here is a minimal set of commands that can reproduce the error I get:

```sh
# directory to "install" abseil (isolated here to make it easier to reset)
mkdir install

# build abseil 
git clone https://github.com/abseil/abseil-cpp.git
cd abseil-cpp
git checkout 20210324.2
mkdir build
cd build
cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_INSTALL_PREFIX=../../install
make -j $(nproc)
make install
cd ../..

# build or-tools
git clone https://github.com/google/or-tools.git
mkdir or-tools/build
cd or-tools/build
cmake .. -DCMAKE_PREFIX_PATH=$(realpath ../../install) -DBUILD_Cbc=ON -DBUILD_Cgl=ON -DBUILD_Clp=ON -DBUILD_CoinUtils=ON -DBUILD_Osi=ON -DBUILD_Protobuf=ON -DUSE_SCIP=OFF
make -j $(nproc)    # fails
```

**What did you expect to see**

A successful build of or-tools

**What did you see instead?**

The following error:

```
Scanning dependencies of target ortools
[ 77%] Linking CXX shared library lib/libortools.so
/usr/bin/ld: /home/mpokorny/reproduce/install/lib/libabsl_status.a(status.cc.o):(.rodata+0x620): multiple definition of `absl::lts_20210324::Status::kMovedFromString'; ortools/bop/CMakeFiles/ortools_bop.dir/bop_solver.cc.o:(.rodata._ZN4absl12lts_202103246Status16kMovedFromStringE[_ZN4absl12lts_202103246Status16kMovedFromStringE]+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ortools.dir/build.make:617: lib/libortools.so.9.0.9050] Error 1
make[1]: *** [CMakeFiles/Makefile2:1762: CMakeFiles/ortools.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Anything else we should know about your project / environment**

Everything seems to work correctly if I just set `BUILD_DEPS` on, but I can't do this because my project has another dependency that itself depends on abseil-cpp (namely grpc), so using `BUILD_DEPS` causes conflicts.

**Comment by lperron** [comment]
Most likely you need to force c++17 mode when building abseil.

**Comment by marekp0** [comment]
Adding `-DMAKE_CXX_STANDARD=17` to abseil's build flags did indeed fix the issue, thanks!

I feel like this and the position independent code flags should be documented somewhere, either here or in abseil's documentation. But since my issue is fixed I'll just close the issue.
