### ISSUE TITLE
Mypy-protobuf files missing on windows release

### ISSUE THREAD

**Issue by stradivari96** [google/or-tools#2627]
**What version of OR-Tools and what language are you using?**
Version: master
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows

**What did you do?**
Expected my IDE to autocomplete `solver.parameters.`

**What did you expect to see**
Autocompletion

**What did you see instead?**
The package did not contain `*.pyi` files

**Anything else we should know about**
I built from source and they were generated, so I believe you just have to add:
```
set PATH=%PATH%;C:\python3%%v-64\Scripts
```
in the `build_delivery_win.cmd` script, but I have **not** tested it.
https://github.com/google/or-tools/blob/b37d9c786b69128f3505f15beca09e89bf078a89/tools/release/build_delivery_win.cmd#L313-L314

**Comment by Mizux** [comment]
It seems `protoc-mymy-gen.exe` is installed in:
```cmd
%userprofile%\appdata\roaming\python\python3%%v\Scripts
```

**Comment by stradivari96** [comment]
Yep, autocompletion works like a charm in ortools-9.1.9490, thanks!
