### ISSUE TITLE
[Feature Request] Constraint prioritization

### ISSUE THREAD

**Issue by rohan-gt** [google/or-tools#2629]
**What language and solver does this apply to?**
All

**Describe the problem you are trying to solve.**
I'm trying to find a way to prioritize constraints so as to prevent conflicting constraints which might lead to an infeasible solution

**Describe the solution you'd like**
A priority parameter parameter while adding constraints similar to what [Python-MIP](https://python-mip.readthedocs.io/en/latest/classes.html) has

**Describe alternatives you've considered**
Python-MIP, code an alternative that will search through combinations which will not give an infeasible solution

**Comment by lperron** [comment]
Unfortunately, the linear solver wrapper is just a wrapper. We only support the solver features, and I do not want to add advanced features on top of solvers. I understand some of it can be done with indicator constraints.
