### ISSUE TITLE
Copy and paste errors in flatzinc/presolve.cc

### ISSUE THREAD

**Issue by dimbleby** [google/or-tools#263]
Errors reported by [`cppcheck`](https://github.com/danmar/cppcheck):

```
[or-tools/src/flatzinc/presolve.cc:1202]: (style) Expression is always false because 'else if' condition matches previous condition at line 1167.
[or-tools/src/flatzinc/presolve.cc:1191]: (style) Expression is always false because 'else if' condition matches previous condition at line 1173.
```

`cppcheck` reports a whole bunch of other stuff too that you might want to consider cleaning up; this one jumped out at me as being very clearly some sort of mistake.

**Comment by lperron** [comment]
Thanks, fixed  :-)
