### ISSUE TITLE
Error in Google Optimization Tools Guides

### ISSUE THREAD

**Issue by antoniomedrano** [google/or-tools#265]
[This page](https://developers.google.com/optimization/routing/tsp/vehicle_routing) details an example of a vehicle routing problem.

The python code works, but outputs incorrect information due to the way the route_demand is calculated. Every instance of this:
`route_demand += demands[node_index]`
should be replaced with this:
`route_demand += demands[node_index_next]`

And the example program output should be updated accordingly.

Is there somewhere I can make the edit with a pull request directly?

**Comment by orwant** [comment]
Hi Antonio,

Thanks for pointing this out! The documentation is internal to Google, so
there's no way for you to make the edit, but I'll take care of it now.

Jon

**Comment by antoniomedrano** [comment]
This has now been fixed on the website
