### ISSUE TITLE
Some unused enforcement literals aren't removed

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#2661]
**What version of OR-Tools and what language are you using?**
Version: master
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
I created a model with given java code.
The example contains only one interval with start and end variables, and fixed duration. I wanted to be sure that artificially created boolean variables for every position of start variable will be removed but it seems that minimally one boolean variable is still present and two constraints with enforcement variable are not removed.

[EnforcementTest.zip](https://github.com/google/or-tools/files/6817856/EnforcementTest.zip)

**What did you expect to see**
Presolved optimization model '':
#Variables: 2 (1 in objective)
  - 1 in [0,10]
  - 1 in [10,20]
#kLinear2: 1

**What did you see instead?**
Presolved optimization model '':
#Variables: 3 (1 in objective)
  - 1 in [0,1]
  - 1 in [0,10]
  - 1 in [10,20]
#kLinear1: 2 (#enforced: 2)
#kLinear2: 1

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by gregy4** [comment]
It is better but not fully fixed, when I created two intervals problem is here again.
In the example,
     for (int i = 0; i < 1; ++i) {
replaced by 
     for (int i = 0; i < 2; ++i) {

one boolean variable two #kLinear1: 2 (#enforced: 2) are still present.

**Comment by lperron** [comment]
I just pushed the second fix. Thanks a lot.
