### ISSUE TITLE
Is there any way that I can reproduce the numbers of iterations and branch-and-bound nodes when using MIP

### ISSUE THREAD

**Issue by middleyuan** [google/or-tools#2667]
**What language and solver does this apply to?**
I use python and SCIP backend to solve the MIP problem.

**Describe the problem you are trying to solve.**
I try to modify my MIP model, such as adding additional constraints, change the format of the constraints, and so on, to see if the modification will help with the solving procedure.  For example, I look at the number of interactions and branch-and-bound nodes to see whether it is helpful. If both numbers decrease, I will say the model is better.

However, when I don't change the model, e.g., constraints, variables, the iterations and nodes outputting by the solver are still different, which is bad if I want to manipulate the formulation because I cannot tell if these are affected by the modified model or the randomness in the solver.

I also try

`
model.SetSolverSpecificParametersAsString("randomization/lpseed=0")
model.SetSolverSpecificParametersAsString("randomization/permutationseed=0")
model.SetSolverSpecificParametersAsString("randomization/randomseedshift=0")
`

but still get different numbers of iterations and nodes after running the same piece of code.

**Describe the solution you'd like**
In the nutshell, I want a feature that can make the solver reproduce the numbers of iterations and nodes with the same piece of code. (Of course in the same setting)

**Comment by lperron** [comment]
Variable and constraint orders matters to. Can you check that the model you are building is strictly the same.

**Comment by middleyuan** [comment]
Yes, exactly the same piece of code!
