### ISSUE TITLE
VRP Feature support of various pickup & delivery scenarios

### ISSUE THREAD

**Issue by Westlife1002** [google/or-tools#2672]
There are several business scenarios which I believe belongs to the pickup & delivery problem (PDP). Does ortools already support all of these scenarios?

The basic bussiness scenario is that there are many goods from different customers at different locations, and need to be delivered to the different locations. In addition to this, there are different requirements regarding how to organize the pickup and delivery, as follows:

Scenario 1: 
Each truck can perform both pickup and delivery tasks in the same route and the sequence of task is open subject to optimal arrangement. i.e. load1->unload1->load2->unload2 or load1->load2->unload2->unload1
I have taken a read of the existing pickup & delivery example: https://developers.google.com/optimization/routing/pickup_delivery  I believe this scenario is already covered by it and ready to use.

Scenario 2:
Each truck has to load all goods (up to the maxum capacity of this truck, or less) before it can start to arrange visits to unload. i.e. load_all -> unload_all. This is due to some cargo conditions which is not convenient to arrange load and unload. So the driver need to perform all pickups in the first place, then plan to make to delivery.

Scenario 3:
Each truck has to load all goods (up to the maxum capacity of this truck, or less) before it can start to arrange visits to unload. In addition, the unloading sequence must be reverse of the loading sequence. i.e. load1->load2->load3->unload3->unload2->unload1. such arrangement makes sure the truck start to unload outlayer cargos before innerlayer cargos.

How do we manage to adapt the model, particularly for scenario 2 and scenario 3. Many thanks

**Comment by Mizux** [comment]
2) You can use `routing.NextVar(index)` to limit the list of available next node.
i.e. pickup node then can visit any node (nothing to do)
delivery node limit to any delivery node or end nodes (i.e. once you visit a delivery node you can't visit a pickup node)
note: this was already discussed on the mailing list...

3) You can use the PD Policy FIFO or LIFO
-> https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/doc/PDP.md#fifo-policy

note: This is not an issue, you should use the mailing list or the github discussion

**Comment by Westlife1002** [comment]
> 1. You can use `routing.NextVar(index)` to limit the list of available next node.
>    i.e. pickup node then can visit any node (nothing to do)
>    delivery node limit to any delivery node or end nodes (i.e. once you visit a delivery node you can't visit a pickup node)
>    note: this was already discussed on the mailing list...
> 2. You can use the PD Policy FIFO or LIFO
>    -> https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/doc/PDP.md#fifo-policy
> 
> note: This is not an issue, you should use the mailing list or the github discussion

thanks for your reply and help. 
1. Regarding scenario 2, I did not fully understand what you mean by "pickup node then can visit any node (nothing to do)". Could you please show me with a simple example?

2. how to use the mailing list. where can I find the discussion related to this problem in the mailinglist?

many thanks

**Comment by Mizux** [comment]
https://groups.google.com/g/or-tools-discuss

https://groups.google.com/g/or-tools-discuss/c/Vz4sJtwBM2Q/m/XirUtGPzAwAJ or
https://groups.google.com/g/or-tools-discuss/c/pbf1b_8fGt8/m/DNj8uyGgAgAJ to adapt to your problem
