### ISSUE TITLE
Vehicle Routing Problem - Disjunction

### ISSUE THREAD

**Issue by rahulj2409** [google/or-tools#2674]
Python

Im doing addDisjunction for the Vehicle Routing Problem with Time Windows. However, it just turns makes one vehicle do all of the tasks. I've tried adjusting the penalty value and whatnot, but not sure what the problem is. Is there a way to limit how many tasks a vehicle can get.

Thanks!

**Comment by lperron** [comment]
Not an issue. And answered multiple times in the mailing list.
