### ISSUE TITLE
Google OR with here.com integration for Middle East region

### ISSUE THREAD

**Issue by maxKarpovets2** [google/or-tools#2678]
Hi,
we're looking at using Google OR for our route optimisation tool targeted at the Middle East. We are planning to use here.com as the distance matrix input and want to understand if the OR tool will recognize the additional information received from here.com (such as open/closed roads, closed / temporarily prohibited points of passage) to build routes - can you please let us know? Thanks

**Comment by lperron** [comment]
As answered on S.O., the routing library is oblivious to the origin of the distance matrix. It only look at a distance call ack. Any semantic information has to be coded by you in the callback.

**Comment by lperron** [comment]
And technically, this is not an issue.
