### ISSUE TITLE
Can't load library when unrelated dll files exist in the same project

### ISSUE THREAD

**Issue by fzeng2012** [google/or-tools#2679]
**What version of OR-Tools and what language are you using?**
Version: 9.0.9048 of ortools-win32-x86-64 
Version: 9.0.9048 of ortools-java
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**

1. Add the following dependencies to a project Maven POM file

        
        <dependency>
            <groupId>com.google.ortools</groupId>
            <artifactId>ortools-win32-x86-64</artifactId>
            <version>9.0.9048</version>
        </dependency>

        
        <dependency>
            <groupId>com.google.ortools</groupId>
            <artifactId>ortools-java</artifactId>
            <version>9.0.9048</version>
        </dependency>

2. Add the following dependency to the same Maven POM file. Note: assert-j has dependency on byte buddy which has its now dlls file in the jar file.

        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>

3. Add the following sample to a project's test directory and run it
   https://developers.google.com/optimization/cp/cp_solver#java

4. See the following error

Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\fan\AppData\Local\Temp\ortools-java3978358333323320488\win32-x86-64\jniortools.dll
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.google.ortools.Loader.loadNativeLibraries(Loader.java:108)
	at cn.unisolution.cp.courseschedule.model.solver.SimpleSatProgram.main(SimpleSatProgram.java:12)

**What did you expect to see**

No error

**What did you see instead?**

Error

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

When debugging into line com.google.ortools.Loader.loadNativeLibraries(Loader.java:108), the values for the stack variables are

resourceURI = {URI@1181} "jar:file:/C:/Users/fan/.m2/repository/net/bytebuddy/byte-buddy-agent/1.10.10/byte-buddy-agent-1.10.10.jar!/win32-x86-64/"
tempPath = {WindowsPath@1182} "C:\Users\fan\AppData\Local\Temp\ortools-java18087726389391500749"

After removing file /c/Users/fan/.m2/repository/net/bytebuddy/byte-buddy-agent/1.10.10/byte-buddy-agent-1.10.10.jar, the error went away. 

I would like to have both ortools and assert-j in the same project hence the report

**Comment by Mizux** [comment]
could be related to this fix https://github.com/google/or-tools/commit/b72093332dde36d6c39941b635c6d3c517e5e432#diff-66730ac5d2a67f8387eeac1655e52846137b355e121a1c0f6d68b323f9f95af0 which is on master (next release)

**Comment by fzeng2012** [comment]
Based on the diffs, I believe it will fix my issue. Let me test it out.

**Comment by fzeng2012** [comment]
Thanks @Mizux

**Comment by fzeng2012** [comment]
Instead of building my own jar files from the master branch, I created a custom version of com.google.ortools.Loader that resolves to the correct URI in a loop. I will take the next released version in Maven Central. Thanks again for the quick response.

Here is my change if anyone is interested.

    private static URI getNativeResourceURI() throws IOException {
        ClassLoader loader = Loader.class.getClassLoader();
        Enumeration<URL> resourceURLs = loader.getResources(RESOURCE_PATH);

        try {
            while (resourceURLs.hasMoreElements()) {
                URL url = resourceURLs.nextElement();
                if (url.getPath().contains("ortools-"))
                    return url.toURI();
            }
        } catch (URISyntaxException e) {
            throw new IOException(e);
        }

        throw new RuntimeException(String.format("Resource %s was not found in ClassLoader %s", RESOURCE_PATH, loader));
    }
