### ISSUE TITLE
Problem in installing or-tools

### ISSUE THREAD

**Issue by ShivKJ** [google/or-tools#268]
using make third_party install  generates error:

Makefile:986: recipe for target 'CParse/parser.c' failed
make[2]: *** [CParse/parser.c] Error 127
make[2]: Leaving directory '/or-tools/dependencies/sources/swig-3.0.10/Source'
Makefile:37: recipe for target 'source' failed
make[1]: *** [source] Error 2
make[1]: Leaving directory '/or-tools/dependencies/sources/swig-3.0.10'
makefiles/Makefile.third_party.unix:307: recipe for target 'dependencies/install/bin/swig' failed
make: *** [dependencies/install/bin/swig] Error 2

**Comment by Mizux** [comment]
Issue too old..

Feel free to reopen/ping me if you still facing errors when using the latest release v6.7.
ps: please add info on your Operating System too !
