### ISSUE TITLE
VRP: Does every pickup node must correspond to an unique delivery node?

### ISSUE THREAD

**Issue by Gyantoshkumar** [google/or-tools#2685]
In pickup and delivery setting, does every pickup node must correspond to an unique delivery node?

In the pickup and delivery example:
https://developers.google.com/optimization/routing/pickup_delivery
each pickup-delivery pair is unique. i.e.
```python
data['pickups_deliveries'] = [
    [1, 6],
    [2, 10],
    [4, 3],
    [5, 9],
    [7, 8],
    [15, 11],
    [13, 12],
    [16, 14]
]
```
This works fine. However, if I make some pickups having the same deliveries (i.e. destinations/unload location) , like:
```python
data['pickups_deliveries'] = [
            [0, 3],
            [0, 10],
            [1, 4],
            [1, 5], 
            [1, 6],
            [1, 7],
            [2, 8],
            [2, 9],
]
```

**Comment by Mizux** [comment]
Yes, you must duplicate the node...

**Comment by nimishdesai1989** [comment]
Hello @Mizux . I have a similar problem. The problem I am trying to solve is to have one starting point which is the depot that will start with a full loaded truck and then deliver to all the other locations which will have their own demands. 

In this case do I need to  put the pickups_delivers data as below ?

            [0, 3],
            [0, 10],
            [0, 4],
            [0, 5], 
            [0, 6],
            [0, 7],
            [0, 8],
            [0, 9]

I a new to OR tools and I am missing some documentation from the CVRP example that is on google for pickups but nothing available for only deliveries . If you ca help me , it will be great.

**Comment by Mizux** [comment]
@nimishdesai1989 your problem seems to be a pure delivery problem, so don't try to use a P&D approach here + you can't have several pairs sharing the same index.
