### ISSUE TITLE
VRP error: OverflowError: in method 'RoutingIndexManager_IndexToNode', argument 2 of type 'int64_t'

### ISSUE THREAD

**Issue by Westlife1002** [google/or-tools#2688]
original post: https://groups.google.com/g/or-tools-discuss/c/RplMRoTdV78

I am trying to add Pickup_Delivery capability for my model.
However, I got some issues related to manager index conversion. I have no idea what's the root cause of below error:

Traceback (most recent call last):
```sh
  File "C:/Users/usr/Dropbox/usr/VRP_17.0.py", line 273, in vehicle_cost_callback
    from_node = manager.IndexToNode(from_index)
  File "C:\Users\usr\AppData\Roaming\Python\Python36\site-packages\ortools\constraint_solver\pywrapcp.py", line 2818, in IndexToNode
    return _pywrapcp.RoutingIndexManager_IndexToNode(self, index)
OverflowError: in method 'RoutingIndexManager_IndexToNode', argument 2 of type 'int64_t'
```

This error happens in below function, which is working fine before I make adjustment for Pickup_Delivery setting:
```python
def define_total_cost(self, data, routing, manager):
     for vehicle_idx in range(data.num_vehicles):
           def vehicle_cost_callback(from_index, to_index, i=vehicle_idx):
                 from_node = manager.IndexToNode(from_index)
                 to_node = manager.IndexToNode(to_index)
                 return cost_vector()[i] * self.dist_matrix[from_node][to_node]
           cost_callback_index = routing.RegisterTransitCallback(vehicle_cost_callback)
           routing.SetArcCostEvaluatorOfVehicle(cost_callback_index, vehicle_idx)
```

Here are all my codes and  3  input csv (i.e. order_info, dist_matrix, time_matrix)
https://gist.github.com/Westlife1002/3e4cce18dba6c6f8ac530934c011d920

Great thanks for your help.

**Comment by lperron** [comment]
Most likely your input is not integral.

**Comment by Westlife1002** [comment]
> Most likely your input is not integral.

 it's same input before I add new configurations for Pickup_Delivery. It's working fine for the prior version.

**Comment by Westlife1002** [comment]
I uploaded a wrong version of code. I have updated in my gist. It's still the same error.
