### ISSUE TITLE
Bad RangeConstraint for inequality operator in linear solver (C#)

### ISSUE THREAD

**Issue by uvbkq** [google/or-tools#2707]
I'm new OR-Tools but came across an issue with the inequality operator when building a _RangeConstraint_ for a linear solver.

https://github.com/google/or-tools/blob/b37d9c786b69128f3505f15beca09e89bf078a89/ortools/linear_solver/csharp/LinearExpr.cs#L91-L94

Assuming I declared variables **_x_** and **_y_**.
Defining a constraint **_x + y != 2_** will result in a _RangeConstraint_ **_1 <= (x + y) <= -1_**.

So there are several issues:
- the value **_2_** is completely dropped
- the resulting constraint will never be true

Running the solver with such a constraint leads to a _ResultStatus = INFEASIBLE_, which is correct.

**Comment by lperron** [comment]
Nice catch :-(

We will fix this.
