### ISSUE TITLE
Error Building from Source

### ISSUE THREAD

**Issue by amc6** [google/or-tools#271]
I'm getting an error when I try to build from source by calling `make all`. 

It fails almost immediately with this error: 
```
Adams-MacBook-Pro:or-tools adamcook$ make all
Makefile:46: Makefile.local: No such file or directory
makefiles/Makefile.unix:190: "cmake found: /usr/local/bin/cmake"
Generating Makefile.local
makefiles/Makefile.unix:190: "cmake found: /usr/local/bin/cmake"
clang++ -fPIC -std=c++11  -mmacosx-version-min=10.8 -stdlib=libc++ -O4 -DNDEBUG -Isrc -Iexamples -Isrc/gen -I/Users/adamcook/code/or-tools/dependencies/install/include -DARCH_K8 -Wno-deprecated -I/Users/adamcook/code/or-tools/dependencies/install/include -I/Users/adamcook/code/or-tools/dependencies/install/include -DUSE_CBC -I/Users/adamcook/code/or-tools/dependencies/install/include -DUSE_CLP      -DUSE_GLOP -DUSE_BOP -I/Users/adamcook/code/or-tools/dependencies/install/include -c src/base/bitmap.cc -o objs/base/bitmap.o
error: unable to open output file 'objs/base/bitmap.o': 'No such file or directory'
1 error generated.
make: *** [objs/base/bitmap.o] Error 1
```

I'm running this on a mac running 10.11.6 and I have the latest xcode (that's compatible with 10.11.6) installed.

**Comment by dlahlou** [comment]
Hello,

Users have first to run the commands from the installing section for [Unix](https://developers.google.com/optimization/installing#installing-from-source-on-unix) or [Windows](https://developers.google.com/optimization/installing#installing-from-source-on-windows) before running `make all`. In your case, you missed running `make third_party`.

I hope this helps.

Regards,

Driss
