### ISSUE TITLE
A Job processed by multiple machines simultaneously?

### ISSUE THREAD

**Issue by rlawnsdudwo** [google/or-tools#2712]
Hello, I'm working with "flexible_job_shop_sat.py", also I'm python newbie :(
It seem like A job must be worked with only one machine at a time.
However, I'd like to change that A job can be occupied with multiple machine at a time.
For easy to understand, I'd like to group machines as team.
And also, I want to differentiate machine type.

**For example:**
Task 0 require 3 basic machines occupied to start.
Task 1 require 2 basic machines + 1 advanced machine occupied to start.
Task 2 require 1 basic machine + 2 advanced machines occupied to start.

+ all tasks have predecessor and successor relationship. (Task 0 → Task 1 → Task 2)
+ If there are only 1 basic machine, 1 advanced machine left, no jobs can be started.
+ if there are only 1 basic machine, 2 advanced machines left, but Task 1 is not done yet, Task 2 cannot be started.

Please help me!

**Comment by lperron** [comment]
not an issue. Moving to discussions.
