### ISSUE TITLE
docker - dot.net core - alpine3.11  - Unable to load shared library 'google-ortools-native' or one of its dependencies

### ISSUE THREAD

**Issue by ey250015** [google/or-tools#2715]
**What version of OR-Tools and what language are you using?**
Version: 9.0.9048
Language: C#

GLOP

vs 2019 windows c#  - working good on the windows. The problem is while running in Docker for Linux.

**What did you do?**
1. Add the NuGet package of Google.OrTools 9.0.9048 (Includes Google.OrTools.runtime.linux-x64)
2. Add code to use it: _solver = new Solver("MyMax", OptimizationProblemType.GLOP_LINEAR_PROGRAMMING);        
3. Add dotnet in docker file: 
ARG REPO=mcr.microsoft.com/dotnet/core/runtime 
FROM $REPO:3.1-alpine3.11 
 
# Install ASP.NET Core 
RUN aspnetcore_version=3.1.3 \ 
    && wget -O aspnetcore.tar.gz https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/$aspnetcore_version/aspnetcore-runtime-$aspnetcore_version-linux-musl-x64.tar.gz \ 
    && aspnetcore_sha512='918bf1f2cd216d4bf337eb0e528d05c56c71e75f5452d8ad08f1ae53c9434a570f7608392872f1a2a55486b00b4d59216a5f7c081f332c707baba0c86e54efd9' \ 
    && echo "$aspnetcore_sha512  aspnetcore.tar.gz" | sha512sum -c - \ 
    && tar -ozxf aspnetcore.tar.gz -C /usr/share/dotnet ./shared/Microsoft.AspNetCore.App \ 
    && rm aspnetcore.tar.gz  
4. build image and run it.

**What did you expect to see**
Solver is creating and solve problems.

**What did you see instead?**
1. externalErrorHandler)\",\"The type initializer for 'SWIGExceptionHelper' threw an exception.\",\"   at Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE.SWIGExceptionHelper..ctor()\\n   at Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE..cctor()\",\"**Unable to load shared library 'google-ortools-native' or one of its dependencies.** In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libgoogle-ortools-native: No such file or directory\",\"   at Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_operations_research_linear_solver(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)\\n   at Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE.SWIGExceptionHelper..cctor()\"]}","

2. {\"errorType\":\"System.**TypeInitializationException**\",\"message\":\"Unhandled Exception. See logs for details.\",\"details\":[\"The type initializer for 'Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE' threw an exception.\",\"   at Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE.new_Solver(String jarg1, Int32 jarg2)\\n   at Google.OrTools.LinearSolver.Solver..ctor(String name, OptimizationProblemType problem_type)\\n
Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by Mizux** [comment]
could you extract the nupkg then ldd the library google-ortools-native.so so we can figure out which dependency(ies) is(are) missing ?

**Comment by ey250015** [comment]
To view runtimes.7z, sign in<https://ncr-my.sharepoint.com/personal/ey250015_ncr_com/_layouts/15/acceptinvite.aspx?invitation=%7BEBD8BEA7%2DE6C5%2D4761%2D9572%2DFD2336E5C47B%7D&listId=70a6a94f%2Dd6ff%2D49fc%2Da3de%2D1c017dab6527&itemId=7cd2c966%2D1a7f%2D477e%2Da38c%2Dee1a0c0c9a9d> or create an account.

**Comment by ey250015** [comment]
Yarden, Eldar has shared a OneDrive for Business file with you. To view it, click the link below.
<https://ncr-my.sharepoint.com/personal/ey250015_ncr_com/Documents/Attachments/runtimes.7z>
[https://r1.res.office365.com/owa/prem/images/dc-generic_20.png]<https://ncr-my.sharepoint.com/personal/ey250015_ncr_com/Documents/Attachments/runtimes.7z>
runtimes.7z<https://ncr-my.sharepoint.com/personal/ey250015_ncr_com/Documents/Attachments/runtimes.7z>

Hi here is the runtimes folder.
Thank you.
________________________________

**Comment by ey250015** [comment]
Here are the runtimes folder from the container
https://ncr-my.sharepoint.com/personal/ey250015_ncr_com/Documents/Attachments/runtimes.7z

**Comment by ey250015** [comment]
I tryed to use this:
apk --no-cache add ca-certificates wget
wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-2.28-r0.apk
apk add glibc-2.28-r0.apk
And to copy the runtimes to the root: cp /app/runtimes/linux-x64/native/* . 
And I steel have problem.
To figure out the problem I checked: ldd google-ortools-native.so
And got:         /lib/ld-musl-x86_64.so.1 (0x7f8511b7b000)
        libortools.so => ./libortools.so (0x7f850fd4c000)
        libz.so.1 => ./../lib/libz.so.1 (0x7f850fd32000)
        librt.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f8511b7b000)
        libpthread.so.0 => /lib/ld-musl-x86_64.so.1 (0x7f8511b7b000)
        libdl.so.2 => /lib/ld-musl-x86_64.so.1 (0x7f8511b7b000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f850fb99000)
        libm.so.6 => /lib/ld-musl-x86_64.so.1 (0x7f8511b7b000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f850fb85000)
        libc.so.6 => /lib/ld-musl-x86_64.so.1 (0x7f8511b7b000)
        ld-linux-x86-64.so.2 => ./../lib/ld-linux-x86-64.so.2 (0x7f850f95c000)
Error relocating ./libortools.so: __strtok_r: symbol not found
Error relocating ./libortools.so: __finite: symbol not found

**Comment by Mizux** [comment]
```
libc.so.6 => /lib/ld-musl-x86_64.so.1 (0x7f8511b7b000)
```
here your env/container (still) rely on libmusl for libc-6

https://github.com/lattera/glibc/blob/master/string/strtok_r.c

**Comment by ey250015** [comment]
To be clear - I still have the problem. These are my steps to try solve it and investigating result:

1. ldd google-ortools-native.so
/lib/ld-musl-x86_64.so.1: cannot load google-ortools-native.so: No such file or directory

2. cp /app/runtimes/linux-x64/native/* .
/app # ldd google-ortools-native.so
        /lib/ld-musl-x86_64.so.1 (0x7ff24a175000)
        libortools.so => ./libortools.so (0x7ff248346000)
        libz.so.1 => ./../lib/libz.so.1 (0x7ff24832c000)
        librt.so.1 => /lib/ld-musl-x86_64.so.1 (0x7ff24a175000)
        libpthread.so.0 => /lib/ld-musl-x86_64.so.1 (0x7ff24a175000)
        libdl.so.2 => /lib/ld-musl-x86_64.so.1 (0x7ff24a175000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7ff248193000)
        libm.so.6 => /lib/ld-musl-x86_64.so.1 (0x7ff24a175000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7ff24817f000)
        libc.so.6 => /lib/ld-musl-x86_64.so.1 (0x7ff24a175000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by ./libortools.so)
Error relocating ./libortools.so: __strtok_r: symbol not found
Error relocating ./libortools.so: __finite: symbol not found

3. apk add gcompat (from https://wiki.alpinelinux.org/wiki/Running_glibc_programs)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/2) Installing libucontext (0.1.3-r1)
(2/2) Installing gcompat (0.4.0-r0)
OK: 46 MiB in 34 packages
/app # ldd google-ortools-native.so
        /lib/ld-musl-x86_64.so.1 (0x7fbe6bf8c000)
        libortools.so => ./libortools.so (0x7fbe6a15d000)
        libz.so.1 => ./../lib/libz.so.1 (0x7fbe6a143000)
        librt.so.1 => /lib/ld-musl-x86_64.so.1 (0x7fbe6bf8c000)
        libpthread.so.0 => /lib/ld-musl-x86_64.so.1 (0x7fbe6bf8c000)
        libdl.so.2 => /lib/ld-musl-x86_64.so.1 (0x7fbe6bf8c000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7fbe69faa000)
        libm.so.6 => /lib/ld-musl-x86_64.so.1 (0x7fbe6bf8c000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fbe69f96000)
        libc.so.6 => /lib/ld-musl-x86_64.so.1 (0x7fbe6bf8c000)
        ld-linux-x86-64.so.2 => ./../lib/ld-linux-x86-64.so.2 (0x7fbe69f90000)
Error relocating ./libortools.so: __strtok_r: symbol not found
Error relocating ./libortools.so: __finite: symbol not found

**Comment by Mizux** [comment]
can you create a simple sample in a repo ?
i.e. I need the microsoft Dockerfile + a small application loading ortools to reproduce it

note: Otherwise, I'll try to do it this afternoon (Paris time)

**Comment by ey250015** [comment]
GM Mizux, Here is a rep solution for this problem - https://github.com/ae250219/GoogleOrToolsTester
Thank you very much.

**Comment by ey250015** [comment]
Oh, I didn't mean I found a solution, this is only a little project to show the problem.

**Comment by Mizux** [comment]
Hi, sorry for the delay....

As explained above , you need to use the nupkg in the alpine release archive...
https://github.com/google/or-tools/releases/tag/v9.0 -> or-tools_alpine-edge_v9.0.9048.tar.gz

Here a sample with the commit which fix the exact problem: https://github.com/Mizux/dotnet_alpine_or-tools/commit/ecaba5bd5751e451d55399113651b49f0b6824eb

Basically you need to:
* copy the "packages" from or-tools_alpine-edge_v9.0.9048.tar.gz in your docker
* Update your `.csproj` so `RestoreSources` will first look at it instead of trying to download the published one...

note: thx for your project, but it was a little bit too big...
note: You can join our discord (badge in the readme) if you need support

**Comment by ae250219** [comment]
@Mizux thanks a lot 👍

**Comment by ey250015** [comment]
Hi @Mizux, Thank you very much.
We have another problem with this solution. We can't configure the resources order, so, sometimes we are getting the package from nuget.org instead of from our packages source - could we have the package with another name/version?

**Comment by Mizux** [comment]
1. If you **prepend** the local package dir in your project csproj ?, does it still not work ?
```xml
<RestoreSources>packages;$(RestoreSources);https://api.nuget.org/v3/index.json</RestoreSources>
```
note: see `packages` is the first location...
ref: https://github.com/Mizux/dotnet_alpine_or-tools/blob/ecaba5bd5751e451d55399113651b49f0b6824eb/SimpleRoutingProgram.csproj#L9

2. According to RID catalog
https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#linux-rids
We should try to provide a `Google.OrTools.runtime.linux-musl-x64` version but I can't guaranty any ETA and/or if I will do it soon.

**Comment by ey250015** [comment]
Yes, while ordering it in the proj, or in another way it is working, but we have a more complex solution, so we prefer not to dill with that. Could I re pack the package to change its name/version, or is there any stable version that has no same version in nuget?

**Comment by ey250015** [comment]
Ordering didn't work for us, so we did a workaround -

restore the project/solution using all sources.
remove the packages that needed to be from the specific repository.
remove other repositories.
restore again the project/solution.

our code on docker file:
&& dotnet restore /src/GoogleOrToolsSolverWrapper/GoogleOrToolsSolverWrapper.csproj
&& rm -rf ~/.nuget/packages/google.ortools.runtime.linux-x64 \
&& rm -rf ~/.nuget/packages/google.ortools \
&& dotnet nuget remove source nuget.org
&& dotnet restore /src/GoogleOrToolsSolverWrapper/GoogleOrToolsSolverWrapper.csproj
&& dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
&& dotnet restore /src/AllMySolution.sln \
