### ISSUE TITLE
VRPTW waiting at every node, departure time

### ISSUE THREAD

**Issue by despondency** [google/or-tools#2716]
Hello, 

We have a case where we need to be waiting at every node X minutes, and it is different for each node. 

Currently we get the answer as following:
`
solution.min(timeVar), solution.max(timeVar) 
`
Which is the time window's min and max value to get to this node. 

However we get the same value for all our nodes, meaning that a 'courier' gets to the node and leaves immediately which is wrong, since he has to actually deliver the goods. 

I've seen that you can modify the distances between nodes by adding the service time there, but still how do you get a proper departure time? 

Much thanks!

**Comment by Mizux** [comment]
Basically, you have to recompute it.

Solver will only compute/need arrival time and the transit function should contains the service time + the travel time.

When displaying the solution, in your function simply do some post processing to calculate the service time and then departure time.

**Comment by despondency** [comment]
So basically, if we have our time matrix and we do for each node:

Calculate times:
`
  return routing.registerTransitCallback((long fromIndex, long toIndex) -> {
      // Convert from routing variable Index to user NodeIndex.
      int fromNode = manager.indexToNode(fromIndex);
      int toNode = manager.indexToNode(toIndex);
      return serviceTime[fromNode] + timeMatrix[fromNode][toNode];
    });
`
And at the end:
`
Arrival : solution.min(timeVar), 
Departure : serviceTime[index] + solution.max(timeVar)
`

Would that be correct?

**Comment by Mizux** [comment]
```py
node = manager.indexToNode(index);
Arrival = solution.min(timeVar), Departure = serviceTime[node] + solution.min(timeVar)
```

**Comment by despondency** [comment]
Thanks for the help @Mizux! Will open a new issue if anything arises.
