### ISSUE TITLE
CMake(Python): Add support for aarch64: publish Linux-aarch64 wheels for or-tools on PyPi

### ISSUE THREAD

**Issue by odidev** [google/or-tools#2719]
# Environment
## What language and solver does this apply to?
Python

## Describe the problem you are trying to solve.
`pip install ortools` is failing with below error message, on Linux AArch64 machine.

    ERROR: Could not find a version that satisfies the requirement ortools (from versions: none)
    ERROR: No matching distribution found for ortools

## Describe the solution you'd like
Releasing Linux AArch64 wheel should solve the problem.

## Describe alternatives you've considered
None

# Additional context
## Devnote
* May use https://github.com/multiarch/qemu-user-static to test aarch64 build in a docker on a x86_64 host machine to test.
* Should look at the [opencv-python package](https://pypi.org/project/opencv-python/#files) since they provide aarch64 support and also publish a python native package.
  * seems they use [skbuild](https://scikit-build.readthedocs.io/en/latest/usage.html)
* With PEP 599 we now have official manylinux2014 aarch64 base image
   ref: https://github.com/pypa/manylinux#readme
* Github workflow: https://github.com/spglib/spglib/pull/130/files

Related issue:
#2722 CMake(Python): Requesting prebuilt wheels for M1 macOS without SCIP
#2434 make: coin-or build fails on aarch64
https://aur.archlinux.org/packages/python-or-tools/#comment-801222

**Comment by Mizux** [comment]
ARM64 is not supported, or-tools is a native library so each platform is independent

**Comment by Mizux** [comment]
Update: 
Currently the aarch64 native compilation won't work using the Makefile based build since coin-or solver doesn't seems to support it.
see: #2434

On my way to test CMake based build and create manylinux artifact using the manylinux2014_aarch64 base image.
You can follow all development in my dev branch mizux/dev

**Comment by girardea** [comment]
@Mizux I used the 9.1.9552 you published for aarch64 and had no particular issue, thanks for that!

Are there any plans to publish Linux-aarch64 wheels for fresher or-tools versions like 9.4?

**Comment by Mizux** [comment]
erf my bad I supposed it was done, on my way to do it ASAP !

**Comment by girardea** [comment]
Thanks a lot for your quick answer!

**Comment by Mizux** [comment]
Uploading ortools-9.4.1874-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.9/14.9 MB • 00:01 • 22.6 MB/s
Uploading ortools-9.4.1874-cp36-cp36m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.9/14.9 MB • 00:01 • 29.4 MB/s
Uploading ortools-9.4.1874-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.9/14.9 MB • 00:01 • 28.3 MB/s
Uploading ortools-9.4.1874-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.9/14.9 MB • 00:01 • 27.9 MB/s
Uploading ortools-9.4.1874-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.9/14.9 MB • 00:00 • 38.7 MB/s

View at:
https://pypi.org/project/ortools/9.4.1874/

**Comment by girardea** [comment]
Thanks! I juste used it and it works great!
