### ISSUE TITLE
Minor design issue - type collision

### ISSUE THREAD

**Issue by illuzen** [google/or-tools#273]
There is overlap between some constants that actually mean different things. 

solver.CHOOSE_RANDOM == solver.ASSIGN_MAX_VALUE 

so I can make the mistake of telling the solver to CHOOSE_RANDOM when I really mean ASSIGN_RANDOM but instead it will ASSIGN_MAX, but everything will compile and it can be hard to catch. 

I recommend avoiding type collision issues like this by making the different enum sets disjoint. So, maybe the CHOOSES are 1 - 15 and the ASSIGNS are 16-20.

Thanks for making an awesome tool, btw.

**Comment by lperron** [comment]
Yeah, the enums were written before C++11.

Unfortunately I cannot break compatibility that easily.

So will not fix.

On the bright side, the CP-SAT solver is much better and does not use enums :-)

Closing the issue.
