### ISSUE TITLE
Pickup and Delivery depot node is pickup node?

### ISSUE THREAD

**Issue by vuongdanghuy** [google/or-tools#2732]
Hi.

I'm new to ortools and I'm solving a pickup and delivery problem. But when i set depot node is one of the pickup nodes, the tool fail with segmentation fault. I don't understand why it's needed for depot node to be different from pickup node. 

Could someone explain why?
Thanks.

**Comment by lperron** [comment]
Not an issue. Please use the discussion tan or or-tools-discuss.
