### ISSUE TITLE
fzn-or-tools: only half the solutions found

### ISSUE THREAD

**Issue by Dekker1** [google/or-tools#274]
I'm using `fzn-or-tools -all_solutions` on a simple minizinc model:
```
predicate rank_apart(var 1..52: a, var 1..52: b) = abs((a-b) mod 13) in {1, 12};
var 1..52: a;
var 1..52: b;
constraint rank_apart(a, b);
solve satisfy;
output ["a = ", show(a), ";\n", "b = ", show(b), ";\n"]
```
This model has 416 solutions (as found using other solvers) ; however, `fzn-or-tools` only reports 208 solutions.
When looking at the solutions found it seems that one side of the internal symmetry is missing: `a=2 & b=1` is found, but `a=1 & b=2` is not found.

The following FlatZinc model is produced from the MiniZinc model:
```
var 1..52: a:: output_var;
var 1..52: b:: output_var;
var -51..51: X_INTRODUCED_1 ::var_is_introduced :: is_defined_var;
var -13..13: X_INTRODUCED_2 ::var_is_introduced ;
var {1,12}: X_INTRODUCED_3 ::var_is_introduced ;
constraint int_mod(X_INTRODUCED_1,13,X_INTRODUCED_2);
constraint int_abs(X_INTRODUCED_2,X_INTRODUCED_3);
constraint int_lin_eq([1,-1,-1],[a,b,X_INTRODUCED_1],0):: defines_var(X_INTRODUCED_1);
solve  satisfy;
```
Let me know if I can provide any more information you might need.

**Comment by lperron** [comment]
Interesting, I suspect is int_mod is wrong with negative numbers.
I will look at our code

Thanks for the report.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2016-11-18 5:17 GMT+01:00 Jip J. Dekker <notifications@github.com>:

**Comment by lperron** [comment]
This CP solver is obsolete.
The CP-SAT solver does not accept mod() with negative numbers.

Closing the issue.
