### ISSUE TITLE
Incorrect Platform.RESOURCE_PREFIX leads to UnsatisfiedLinkError in one of my gradle projects

### ISSUE THREAD

**Issue by cbtum** [google/or-tools#2742]
Thank you very much for making ortools-java available as maven project, it is much easier to use now! While experimenting with it, I ran into the following problem:

**What version of OR-Tools and what language are you using?**
'com.google.ortools:ortools-java:9.0.9048'

**What operating system (Linux, Windows, ...) and version?**
MacOS, Java Gradle Project

**What did you do?**
I am experimenting with ortools-java in two different gradle projects.

**What did you expect to see**
Since both projects have the same dependency as specified above, both projects should behave the same way.

**What did you see instead?**
While ortools-java works fine in one project, I get an UnsatisfiedLinkError in the other.

**Anything else we should know about your project / environment**
- Debugging into the `Loader.loadNativeLibraries()`, I noticed that the `Platform.RESOURCE_PREFIX` differs between both projects.
- In the implementation that is working fine, the class loader uses `darwin-x86-64/` as resource to be loaded.
- In contrast, the project with the UnsatisfiedLinkError uses `darwin/` as resource. While a resource is found for `darwin/`, it seems to clash with some other library.
- When I copy your class loader and replace `Platform.RESOURCE_PREFIX` with `darwin-x86-64/`, both projects are working without any problem.

**Comment by Mizux** [comment]
Seems to be linked to https://github.com/google/or-tools/issues/2519

Which version of or-tools did you use ?
Same question with g:net.java.dev.jna a:jna-platform ?

**Comment by cbtum** [comment]
Since I am using 9.0, I am actually using jna-platform 5.8.0.

However, the [idea of prefixing darwin](https://github.com/google/or-tools/issues/2575#issuecomment-854906858) probably solves the issue of the clashing libraries.

**Comment by cbtum** [comment]
@Mizux , just tried the new `com.google.ortools:ortools-java:9.1.9490`. Seems the problem with the clashing library is solved by prefixing ortools. However, I still experience different behavior in two different projects. Again, `Platform.RESOURCE_PREFIX` differs in both projects. The working project now uses `ortools-darwin-x86-64`, the broken project uses `ortools-darwin` as ressource path. So I guess the difference is not so much in the complete path, but rather in the `Platform.RESOURCE_PREFIX`.

It might be relevant to mention, that the working project is meant to be a library for the broken project. When I override the `Platform.RESOURCE_PREFIX` in my working project, I can use it as a library for the other project without any problems. Any ideas why `Platform.RESOURCE_PREFIX` might be different on the same computer?

PS: As described https://github.com/google/or-tools/issues/2802, I also had problems with the linux dependency and solved it by saving com.google.ortools:ortools-linux-x86-64:9.1.9490 on maven local.

**Comment by Mizux** [comment]
@cbtum `Platform.RESOURCE_PREFIX` is computed by `g:net.java.dev.jna a:jna-platform` which has changed its behavior betzeen `5.5.0` and `5.8.0` so you can try to check which version you are using

see: https://github.com/google/or-tools/issues/2519#issue-864047066 for details and jna PR link.

note: it seems we are using 5.8.0 since v9.0 https://github.com/google/or-tools/commit/d6b3090d3a780d4536aa0c08cd8db4623384dc4a (see the tag list)
