### ISSUE TITLE
[Question] Using scheduling mechanism how can we schedule more ride in a van already scheduled. 

### ISSUE THREAD

**Issue by rajatjangir** [google/or-tools#275]
Hi,

Sorry, but I didn't know where to put questions so i am creating this issue.

I am trying to do capacitated vehicle routing with time window (CSVRPTW).

I have been able to input a set of data in the solver and able to get the schedule for the cars which i feed in the data.

The schedule is working nicely.
But now i have a problem at hand where i have to say put some more rides into the same cars , say i have to give user a choice that if he feels the schedule is not efficient then he can select some more locations and then try to schedule them in the same car.

Now i would like to know if there is way in which we can tell the program that these node have already been scheduled and just to look if the program can fit the rides which user wants to add without disturbing the existing schedule.

I have already tried rescheduling all the nodes but then it given an entirely new schedule for the car. I know i can do that but is there a way so that i can inform my program to not replace the existing nodes and just try and see if other rides can be accommodated or not.

Thanks !!

**Comment by dlahlou** [comment]
Hello,

To assign a vehicle to a given node N, you may use the [vehicle variable](https://github.com/google/or-tools/blob/master/src/constraint_solver/routing.h#L837) corresponding to N, like so : 

`routing.VehicleVar(N)->SetValues({vehicle_index});`

I hope this helps.

Regards,

Driss
