### ISSUE TITLE
Could the transit function accept three parameters? Such as the "previous" node, the "from" node and the "to" node

### ISSUE THREAD

**Issue by whatseven** [google/or-tools#2751]
**What language and solver does this apply to?**
C++

**Describe the problem you are trying to solve.**
Could the transit function accept three parameters? Such as the "previous" node, the "from" node and the "to" node. I want to define the distance matrix based on the previous node. E.g. The travel cost of a drone to the next node depends on the previous node since a sharp angle between two segments will introduce an additional cost.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
After digging into the "routing.h", I can only find the function "NextVar" to access the next node given a node index. Is there any method to access the previous node, or like a function "PreviousVar"?

Also, I tried to implement it using the dimension. However, I found that the value of dimension is accumulated. But I just want to replace the value of dimension every time it is updated. Is there any smarter way to do that?

**Comment by lperron** [comment]
No.
