### ISSUE TITLE
2GB Model size limit in CP-SAT Python

### ISSUE THREAD

**Issue by Tannex** [google/or-tools#2753]
**What language and solver does this apply to?**
Version: v9.0.9
Platform: Python (possibly others)

**Describe the problem you are trying to solve.**
I am generating some quite large models (~3GB).
These models cannot be sent to the solver due to the 2GB limit of ProtoBuf.
```
Message operations_research.sat.CpModelProto exceeds maximum protobuf size of 2GB: 3010170967
```

**Describe the solution you'd like**
Implement splitting of the model proto when it exceeds the 2GB limit such that the solver can still attempt solving.

**Describe alternatives you've considered**
My model could be split into two parts/phases, but that would significantly complicate the search for optimality.

**Additional context**
Some models slightly below the 2GB limit have given quite decent results, so I do not think the request is unreasonable, especially with the upcoming RAM density increase with DDR5.

**Comment by lperron** [comment]
This is a protobuf limitation. We cannot change it ourselves.

**Comment by Tannex** [comment]
Ok,

In the Protobuf repository, there is [this issue](https://github.com/protocolbuffers/protobuf/issues/1004#issuecomment-159423511), confirming that there are no plans for allowing messages larger than 2GB.

**Comment by lperron** [comment]
Note that if you remove all variable names, you can scrape a little memory.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
