### ISSUE TITLE
Warnings that can't be suppressed?

### ISSUE THREAD

**Issue by gdowdy3** [google/or-tools#2760]
**What version of OR-Tools and what language are you using?**
Version: 9.0.9048
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Gurobi

**What operating system (Linux, Windows, ...) and version?**
MacOS v11.5.2

**What did you do?**
1. Install ortools via pip
2. Install Gurobi following the instructions here: https://www.gurobi.com/documentation/9.1/quickstart_mac/software_installation_guid.html
3. Add the following to `~/.zshenv`: `export GUROBI_HOME=/Library/gurobi912/mac64`
4. Create a python script with the following lines:
```
from ortools.linear_solver import pywraplp
Solver = pywraplp.Solver.CreateSolver('GUROBI')
```
5. Run this script.

**What did you expect to see**
Preferably nothing

**What did you see instead?**
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0723 00:00:32.041015     1 environment.cc:737] Found the Gurobi library in '/Library/gurobi912/mac64/lib/libgurobi91.dylib.
Warning: parameter changes on this environment will not affect existing models.
```

Is there any way to suppress this output?

**Comment by gdowdy3** [comment]
Hello OR-Tools developers!  Thank you very much for the work you do on this software.  I find it very useful.

In particular, I'm currently using it to solve many similar optimization problems in parallel, using Python's `multiprocessing` library.  Unfortunately, this results in the above warnings being printed out many times, filling up the terminal.

The issue I've started here isn't a "bug" necessarily, because the excessive warning messages in the output don't stop the code from doing what it needs to do.  It's just an aesthetics thing.

So, I'm wondering:

1. Is there a way to suppress the warnings above?
2. If not, can I respectfully request that the good people at OR-Tools provide a way?

**Comment by Mizux** [comment]
You should try:

```python
from ortools.linear_solver import pywraplp
from ortools.init import pywrapinit

def main():
    solver = pywraplp.Solver.CreateSolver('GUROBI')
   ....

if __name__ == '__main__':
    pywrapinit.CppBridge.InitLogging('basic_example.py')
    cpp_flags = pywrapinit.CppFlags()
    cpp_flags.logtostderr = True
    cpp_flags.log_prefix = False
    pywrapinit.CppBridge.SetFlags(cpp_flags)

    main()
```

see: https://github.com/google/or-tools/blob/master/examples/python/integer_programming.py

note: `pywrapinit` is still young so any feedback is welcome ;)

**Comment by gdowdy3** [comment]
Thanks, @Mizux!  I'll give it a try...

**Comment by gdowdy3** [comment]
@Mizux, I got a chance to try your suggested fix.  Here's what I did:

1. Save the following code in a file called `SuggestedFix.py`:
```python
from ortools.linear_solver import pywraplp
from ortools.init import pywrapinit

def main():
    solver = pywraplp.Solver.CreateSolver('GUROBI')
    exit()

if __name__ == '__main__':
    pywrapinit.CppBridge.InitLogging('SuggestedFix.py')
    cpp_flags = pywrapinit.CppFlags()
    cpp_flags.logtostderr = True
    cpp_flags.log_prefix = False
    pywrapinit.CppBridge.SetFlags(cpp_flags)

    main()
```

2. Run this code from the terminal with `python3 SuggestedFix.py`.

The output is:
```
Found the Gurobi library in '/Library/gurobi912/mac64/lib/libgurobi91.dylib.
Warning: parameter changes on this environment will not affect existing models.
```

This is better than the previous output:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0723 00:00:32.041015     1 environment.cc:737] Found the Gurobi library in '/Library/gurobi912/mac64/lib/libgurobi91.dylib.
Warning: parameter changes on this environment will not affect existing models.
```

So we're making progress!  

I notice that if I set `cpp_flags.logtostderr = False` the output is further reduced to:
```
Warning: parameter changes on this environment will not affect existing models.
```

However, this last output is actually the one that I am most interested in eliminating, as it is the one that pops up most frequently in my original code.  Do you know how to eliminate this last warning message?

**Comment by Mizux** [comment]
looking at the source code of ortools/linear_solver/gurobi_interface.cc I can't found any trace of this sentences so my best guess: it comes from gurobi solver itself.
Open question: If yes, how can we "mute" the gurobi solver... ?

**Comment by gdowdy3** [comment]
Agreed, looking at Gurobi's list of "Recent Bug Fixes by Version" (https://www.gurobi.com/resource/fixes/), I see 

```
Added back missing warning "Warning: parameter changes on this environment will not affect existing models."
```

**Comment by gdowdy3** [comment]
There's some related text on page 6 of their documentation here: https://www.gurobi.com/wp-content/plugins/hd_documentations/documentation/9.0/refman.pdf

**Comment by Mizux** [comment]
We should expose the log level param
https://github.com/google/or-tools/blob/86d4c543f717fa8716a9d66c25143660668bf825/ortools/base/logging.cc#L130-L132
so we can ignore the gurobi log:
https://github.com/google/or-tools/blob/86d4c543f717fa8716a9d66c25143660668bf825/ortools/gurobi/environment.cc#L737

level being:
https://github.com/abseil/abseil-cpp/blob/1ae9b71c474628d60eb251a3f62967fe64151bb2/absl/base/log_severity.h#L69-L74

Note in java
```java
import com.google.ortools.init.CppBridge;
import com.google.ortools.init.CppFlags;
...
    CppBridge.initLogging("test");
    CppFlags myFlags = new CppFlags();
    myFlags.setLogtostderr(true);
    myFlags.setLog_prefix(false);
    CppBridge.setFlags(myFlags);
    CppBridge.shutdownLogging();
```
