### ISSUE TITLE
Customizing a VRP Problem

### ISSUE THREAD

**Issue by mearcstapa-gqz** [google/or-tools#2761]
Hi, I have a problem which could be formulated as a VRP problem, but with 2 additional constraints.

1. There are some disjoint set of locations. Locations in one set must be visited together (any vehicle will do, but by a same vehicle).
2. There is a constraint on how many sets a vehicle can visit. 

Are there any possible ways to add them or convert the problem into a MIP/CP? Could you refer me to some docs or examples? (I'm new to this field and OR-Tools.) Thanks a lot!

**Comment by Mizux** [comment]
You need to add some constraints using the underlying solver

1. You can add some constraint on the vehicleVar
```python
solver = routing.solver()
solver.Add(routing.VehicleVar(index_a) == routing.VehicleVar(index_b))
```
see: https://gist.github.com/Mizux/9e37c370a459bd472a6ac13c304f0b54

**Comment by mearcstapa-gqz** [comment]
Thanks! Though I'm still trying to put this together, I think that's the key snippet I need! Can I get back to you, should any further question arise? Thanks again!

**Comment by Mizux** [comment]
FYI we also have a discord (see badge in the readme)

**Comment by mearcstapa-gqz** [comment]
Cool! I didn't notice that. Thanks!
