### ISSUE TITLE
Simple Boolean constraint fails to return all valid solutions

### ISSUE THREAD

**Issue by krishvk** [google/or-tools#2762]
**What version of OR-Tools and what language are you using?**
Version: ortools==9.0.9048
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core) 
Release:        7.3.1611

**What did you do?**
Steps to reproduce the behavior: Run following program

```
from ortools.sat.python import cp_model


class VarArraySolutionPrinter(cp_model.CpSolverSolutionCallback):
    """Print intermediate solutions."""

    def __init__(self, variables):
        cp_model.CpSolverSolutionCallback.__init__(self)
        self.__variables = variables
        self.__solution_count = 0

    def on_solution_callback(self):
        self.__solution_count += 1
        print([self.Value(v) for v in self.__variables])
        
    def solution_count(self):
        return self.__solution_count


model = cp_model.CpModel()

vars = [
    model.NewIntVar(0, 1, 'a'),
    model.NewIntVar(0, 1, 'b'),
    model.NewIntVar(0, 1, 'c')
]

print(type((vars[0] != 0) or (vars[1] != 0)))
model.Add(((vars[0] != 0) or (vars[1] != 0)))
model.AddHint(vars[0], 0)

solver = cp_model.CpSolver()
status = solver.SearchForAllSolutions(model, VarArraySolutionPrinter(vars))

print(solver.StatusName(status))

```

**What did you expect to see**
```
<class 'ortools.sat.python.cp_model.BoundedLinearExpression'>
[0, 1, 1]
[0, 1, 0]
[1, 0, 0]
[1, 0, 1]
[1, 1, 1]
[1, 1, 0]
OPTIMAL

```
**What did you see instead?**
```
<class 'ortools.sat.python.cp_model.BoundedLinearExpression'>
[1, 0, 0]
[1, 0, 1]
[1, 1, 1]
[1, 1, 0]
OPTIMAL
```

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
model.Add(((vars[0] != 0) or (vars[1] != 0))) is not supported

You cannot use and, or, min, max, sort in constraints.
If you had updated to 9.0, it would have thrown an error.

**Comment by krishvk** [comment]
@lperron I am on `ortools==9.0.9048`, but no error is thrown

**Comment by krishvk** [comment]
@lperron Any other way to achieve this? Can I extend the code locally to define boolean operations?

**Comment by lperron** [comment]
Have you read https://github.com/google/or-tools/blob/stable/ortools/sat/doc/channeling.md ?

**Comment by lperron** [comment]
You are right about the error, != 0 is the only case we allow the __bool__ operator on a BoundedLinearExpression.

If you print the object, instead of its type, you will see: a in [-9223372036854775808..-1, 1..9223372036854775807]

which is vars[0] != 0. As this is an object (i.e. non null), python or does not evaluate the second term.

**Comment by lperron** [comment]
Thanks for the report. I have improved the code to properly raise an exception in that case.

**Comment by lperron** [comment]
```
NotImplementedError: Evaluating a BoundedLinearExpr 'a in [-9223372036854775808..-1, 1..9223372036854775807]' as a Boolean value is not supported.
```

**Comment by krishvk** [comment]
> Have you read https://github.com/google/or-tools/blob/stable/ortools/sat/doc/channeling.md ?

yeah @lperron, but it feels a bit of work to convert a simple implication in that format.

Here is the minimal code I needed (and had to spend quite a bit of time to get to it) to randomize 2 variables such that they both never will be 0 together

```
from ortools.sat.python import cp_model

class VarArraySolutionPrinter(cp_model.CpSolverSolutionCallback):
    """Print intermediate solutions."""

    def __init__(self, variables):
        cp_model.CpSolverSolutionCallback.__init__(self)
        self.__variables = variables
        self.__solution_count = 0

    def on_solution_callback(self):
        self.__solution_count += 1
        print([self.Value(v) for v in self.__variables])
        
    def solution_count(self):
        return self.__solution_count


model = cp_model.CpModel()

vars = [
    model.NewIntVar(0, 1, 'a'),
    model.NewIntVar(0, 1, 'b'),
    model.NewBoolVar('bool')
]

model.Add(vars[0] == 0).OnlyEnforceIf(vars[2])
model.Add(vars[0] != 0).OnlyEnforceIf(vars[2].Not())
model.Add(vars[1] != 0).OnlyEnforceIf(vars[2])

# model.Add(vars[0] != 2).OnlyEnforceIf(vars[2].Not())

solver = cp_model.CpSolver()
status = solver.SearchForAllSolutions(model, VarArraySolutionPrinter(vars))

print(solver.StatusName(status))
```

Output

```
[0, 1, 1]
[1, 0, 0]
[1, 1, 0]
OPTIMAL
```

The solver is quite fast and this feels like a major hurdle before aggressive usage by layman.

SystemVerilog is designed for constraints and has a very intuitive interface, where users can write constraints without having to know anything about implementation.

Can we overload more operators or do something else to get more boolean operators like we have linear boolean expression operators overloaded now?

I think that gives a big boost in usage

**Comment by lperron** [comment]
Sorry, this is a conscious decision not to do this.  It is either error
prone or impossible to do

Furthermore, i do not want the API to create additional constraints
silently.

**Comment by lperron** [comment]
```
from ortools.sat.python import cp_model

class VarArraySolutionPrinter(cp_model.CpSolverSolutionCallback):
    """Print intermediate solutions."""

    def __init__(self, variables):
        cp_model.CpSolverSolutionCallback.__init__(self)
        self.__variables = variables
        self.__solution_count = 0

    def on_solution_callback(self):
        self.__solution_count += 1
        print([self.Value(v) for v in self.__variables])

    def solution_count(self):
        return self.__solution_count


model = cp_model.CpModel()

vars = [
    model.NewIntVar(0, 1, 'a'),
    model.NewIntVar(0, 1, 'b')
]

model.AddBoolOr([vars[0], vars[1]])
model.AddHint(vars[0], 0)

solver = cp_model.CpSolver()
solver.parameters.enumerate_all_solutions = True
status = solver.Solve(model, VarArraySolutionPrinter(vars))

print(solver.StatusName(status))
```
