### ISSUE TITLE
or-tools make cc Error

### ISSUE THREAD

**Issue by dk12345677** [google/or-tools#2764]
**What version of OR-Tools and what language are you using?**
Version: master
Language: C++
solver:scip 7.0.3
operating system:linux

**What did you do?**
~/or-tools$ make cc

-lz -lrt -lpthread -Wl,--no-as-needed -ldl -Wl,-rpath,'$ORIGIN' -Wl,-rpath,'$ORIGIN/../lib' -Wl,-rpath,'$ORIGIN/../dependencies/install/lib64' -Wl,-rpath,'$ORIGIN/../dependencies/install/lib'
/usr/bin/ld: /usr/local/scip/lib/libscip.a(cons_linear.o): relocation R_X86_64_PC32 against symbol `SCIPincludeConshdlrLinear' can not be used when making a shared object; 以 -fPIC 選項重新編譯
/usr/bin/ld: 最後的鏈結失敗: 數值不符
collect2: error: ld returned 1 exit status
makefiles/Makefile.cpp.mk:208: recipe for target 'lib/libortools.so' failed
make: *** [lib/libortools.so] Error 1

**Comment by Mizux** [comment]
`/usr/local/scip/lib/libscip.a` seems you are using a system wide installed version of SCIP.

You should try to use/let or-tools build it for you IMHO
