### ISSUE TITLE
Another error in Google Optimization Tools Guides

### ISSUE THREAD

**Issue by antoniomedrano** [google/or-tools#278]
[This page](https://developers.google.com/optimization/routing/tsp/vehicle_routing) details an example of a vehicle routing problem.

New versions of or-tools require a depot to be specified when calling pywrapcp.RoutingModel(). New versions have also deprecated the routing.SetDepot() function.

Code on the website should reflect this.

I have also posted a version of this to be added to the github repo:
https://github.com/google/or-tools/pull/277

**Comment by dlahlou** [comment]
Hello Antonio,

Thank you for flagging this.

Your remark made us think about a way to systematically avoid having outdated examples in the future, and we are working on it, so this issue should be resolved soon.

Regards,

Driss

**Comment by Mizux** [comment]
Hi,

Example should have been fixed now -> I close this issue.

Thanks for the feedback !
