### ISSUE TITLE
Make documentation website open for contributions

### ISSUE THREAD

**Issue by Qwebeck** [google/or-tools#2781]
**What language and solver does this apply to?**
All

**Describe the problem you are trying to solve.**

Currently, I am actively learning an OR Tools framework, and I found, that actual documentation has some flaws. Few quick examples, all taken from [`RoutingModel` reference](https://developers.google.com/optimization/reference/constraint_solver/routing/RoutingModel?hl=en) :

1. Lack of links to classes used as return types of other functions (e.g. on screenshot there is no link to the `IntVar` class). 

![image](https://user-images.githubusercontent.com/21079319/134259012-624daf8a-b690-4f34-8557-e5bfef2bb345.png)

2. `TODO` comments in some function references

 ![image](https://user-images.githubusercontent.com/21079319/134258419-e5099182-a2bd-428c-b5d1-16d51b5858ab.png)

3.  Function references, that contain only information about function signature

![image](https://user-images.githubusercontent.com/21079319/134259310-ed60dbce-3551-4b04-a177-f475045838e3.png)

Moreover, I think, that documentation website lack of some useful pieces of information: e.g. information about all available ways to influence an objective function, which currently could be found on only google discussion [forum](https://groups.google.com/g/or-tools-discuss/c/YCUNTmWr8Us/m/IJhb3g0JAQAJ?utm_medium=email&utm_source=footer&pli=1).

All these things are not critical, but they do make work with the OR Tools documentation less pleasant.

**Describe the solution you'd like**
I know, that it is hard to maintain documentation, especially when it is done by few people in their free time, so I think that the best solution would be to make a code, that stands behind the current documentation website open-sourced, so every keen would be able to contribute.

Similar approaches were already applied by such famous tools as [`Angular`](https://angular.io/start) and [`Typescript`](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes-oop.html), where on each page of documentation you can click into a link, which will redirect you to that pages source code and you will be able to fork it, edit and make a Pull Request.

![image](https://user-images.githubusercontent.com/21079319/134260573-6faf01e8-a2d5-4773-b23c-5067c2c8c930.png)

**Additional context**

If this feature request will be considered positively I will be happy to become an active contributor to the documentation, because I think that `OR Tools` is a great product and I want to make it better.

**Comment by KeremAslan** [comment]
I concur. The documentation is fairly ambiguous and confusing when you go beyond the standard examples on the main website. Also, many functions are unclear in what they do because they either aren't either not explained or There is this website that contains a lot of excellent information, but it isn't complete and seems to not have been touched up in many years: https://acrogenesis.com/or-tools/documentation/user_manual/index.html

I also have learnt a lot over the last year or so since I have been using it and would like to contribute to documentation as well.

**Comment by lperron** [comment]
There are two parts in the documentation:

the user manual (guide, installation, ...) is hand-written, using examples. The source code is not open-source. You can contribute examples though, which is the best way to help others. Even better, contribute colab or jupyter notebooks with nice graphics. This would be awesome. 

the reference manual (as in your issue), This one is generated automatically from hand-written doxygen comments in the source code. It is also accessible here (http://google.github.io/or-tools/). You can contribute patches to the doxygen comments easily.
You can regenerate the documentation by running `make doc` at the root of a github cloned or-tools repository.

The acrogenesis doc is very nice, but it was never finished, and took too long, with no end in view. So unfortunately a failure.

**Comment by Mizux** [comment]
https://google.github.io/or-tools/cpp_routing/classoperations__research_1_1_routing_model.html#a3eab594188b170aac4b038bd7240096e
