### ISSUE TITLE
Best way to exclude intervals from an IntervalVar?

### ISSUE THREAD

**Issue by supermihi** [google/or-tools#279]
The current API has the `AVOID_DATE` relation to forbid an `IntervalVar` crossing a single date. For a scheduling problem with calendars, however, I need to model intervals that avoid fixed intervals (unavailabilities in the calendar, e.g. breaks).

I currently do this by adding fixed `IntervalVar`s for each break and then using one large disjunctive constraint, covering both the fixed intervals and all jobs to be scheduled. My feeling however is that this is not very efficient (the solver sometimes fails to propagate very "obvious" contradictions). Is there a more efficient way to model breaks?

**Comment by lperron** [comment]
Hi, 

If you already have a disjunctive for the jobs, then adding fixed intervals for the break is the best option.

In C++, for 1 interval, you can use  
 // Expr should not be in the list of forbidden intervals.
  Constraint* MakeNotMemberCt(IntExpr* expr, SortedDisjointIntervalList intervals);
 on the StartExpr() of the interval if always performed, or SafeStartExpr() if optional.

In the CP-SAT solver, when creating the IntVar for the start of the interval, you can give a list of intervals for the domain.
See https://github.com/google/or-tools/blob/master/ortools/sat/doc/integer_arithmetic.md#integer-variables
