### ISSUE TITLE
Random seed is not respected

### ISSUE THREAD

**Issue by ajouzali** [google/or-tools#2793]
**What version of OR-Tools and what language are you using?**
Version: ortools==7.4.7247
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What did you do?**
we set a random seed value using

`solver.parameters.random_seed `

**What did you expect to see**
we expect to be able to reproduce the results every time we run our code (based on solution id, not time).

**What did you see instead?**
We see different solutions and we are not able to reproduce the results on the same hardware

<img width="1353" alt="Bildschirmfoto 2021-09-27 um 11 49 45" src="https://user-images.githubusercontent.com/91462620/134886557-140d8d16-13cd-4636-adc8-9ff8579b98fc.png">
<img width="1353" alt="Bildschirmfoto 2021-09-27 um 11 49 38" src="https://user-images.githubusercontent.com/91462620/134886562-c4896f4c-085c-45ae-a146-720383bbae38.png">

Not sure if this is normal behavior or a bug. Unless it is a bug, is there another setting we can use to get the same first solution every time we run the code?

Thanks.

**Comment by lperron** [comment]
Please try with 9.0. It could have improved a little since then.

**Comment by lperron** [comment]
are you using parallelism ?

**Comment by ajouzali** [comment]
> Please try with 9.0. It could have improved a little since then.
The same problem in 9.0 version

> are you using parallelism ?
Yes, we use parallelism to speed-up the search.

**Comment by lperron** [comment]
Parallelism is not deterministic.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
