### ISSUE TITLE
9.1 release's maven dependency for linux-x86-64 has a different version than the rest of the jars

### ISSUE THREAD

**Issue by lalithsuresh** [google/or-tools#2802]
**What version of OR-Tools and what language are you using?**
Version: 9.1
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

CP-SAT

**What operating system (Linux, Windows, ...) and version?**

Mac 11.6

**What did you do?**
Use the latest ortools-java release [1] via gradle like so:

`implementation 'com.google.ortools:ortools-java:9.1.9490'`

[1] https://search.maven.org/artifact/com.google.ortools/ortools-java/9.1.9490/jar

**What did you expect to see**

Build would work just fine.

**What did you see instead?**

Gradle complains about not being able to find the linux dependency within the wrapper jar.
`Could not find com.google.ortools:ortools-linux-x86-64:9.1.9490.`

The reason is that the version number for the linux-x86 jar (9.1.9491) differs from that of the rest (9.1.9490).

See here: https://search.maven.org/search?q=com.google.ortools

**Anything else we should know about your project / environment**

**Comment by ugurakkurt** [comment]
I temporarily resolved this issue by manually putting the ortools-linux-x86-64:9.1.9491 dependency my pom file. 
`    
<dependency>
      <groupId>com.google.ortools</groupId>
      <artifactId>ortools-linux-x86-64</artifactId>
      <version>9.1.9491</version>
      <type>jar</type>
      <scope>runtime</scope>
    </dependency>
`

**Comment by Mizux** [comment]
Shame on me
should be fixed now: https://mvnrepository.com/artifact/com.google.ortools/ortools-linux-x86-64
