### ISSUE TITLE
mypy-protobuf isn't found

### ISSUE THREAD

**Issue by yurivict** [google/or-tools#2814]
**What version of OR-Tools and what language are you using?**
Version: 9.1
Language: Python

Relevant line: https://github.com/google/or-tools/blob/86d4c543f717fa8716a9d66c25143660668bf825/cmake/python.cmake#L33

configure fails:
```
-- Found Python3: /usr/local/bin/python3.8 (found suitable exact version "3.8.12") found components: Interpreter Development.Module
CMake Warning at cmake/python.cmake:42 (message):
  Can't find python module "mypy-protobuf", install it using pip...
Call Stack (most recent call first):
  cmake/python.cmake:67 (search_python_module)
  CMakeLists.txt:251 (include)
```

This is because ```py38-mypy-protobuf-2.10``` is installed as ```mypy_protobuf```, and it tries to import ```mypy-protobuf```. I think the same problem exists with ```absl-py``` which is installed as ```absl```.

**Comment by Mizux** [comment]
So I need to fix the function to take two arguments PACKAGE_NAME, MODULE_NAME ...

Thx for the report !
