### ISSUE TITLE
Builder Behavior Change in v9.1 [CpSat, Windows, Java]

### ISSUE THREAD

**Issue by prissky** [google/or-tools#2826]
**OR-Tools**
Version: v9.1 (vs v9.0)
Language: Java

**Solver**
CpSat

**Operating system and version**
Win 10

**Steps to reproduce**
1. Run [BuilderIssueTest.zip](https://github.com/google/or-tools/files/7310018/BuilderIssueTest.zip) on v9.1 and v9.0.

**What did you expect to see**
Same results from both versions.

**What did you see instead?**
v9.0:
Interval start idx = 0
Interval size idx = 1
Interval end idx = 2

v9.1:
Interval start idx = 0
Interval size idx = 0
Interval end idx = 0

**About our project**
We are using 
_callback.solutionIntegerValue(intervalVar.getBuilder().getStart())_ and 
_callback.solutionIntegerValue(intervalVar.getBuilder().getEnd())_
to get the results. Is this change of behavior a bug to be fixed or should we use auxiliary maps/lists to get the values from?

**Comment by lperron** [comment]
yes. We convert all intervals to the new format. See the proto for details:

https://github.com/google/or-tools/blob/8b607171852ba1eb53646d24c229f866b3634199/ortools/sat/cp_model.proto#L119

I missed the GetStart(). I will remove it in the next release. I did rename it to getStartExpr() on the C++ API.

**Comment by lperron** [comment]
Actually, you are calling the proto API. Please use the getStartView() to get a LinearExpressionProto().

As a general rule, you should not depend too much on how the model is stored. This is subject to change.

**Comment by prissky** [comment]
Ok, thanks for swift response. Have a nice weekend.
