### ISSUE TITLE
Recipe for installing python or-tools with SCIP on macOS

### ISSUE THREAD

**Issue by antoniomedrano** [google/or-tools#283]
UPDATE: Problems have been resolved, this recipe should work for others now. If someone tries and has issues, feel free to contact me and I'll see what I can do to help. Happy solving!

Preliminaries (on Mac):
* Uninstall all previous versions of or-tools
* Download the latest version of or-tools by doing a `git clone` on this repository
* Install the latest version of the command line tools for XCode (the full XCode isn't necessary).
* Install javac. To install javac, just run javac. This will download and install Java (likely only necessary if installing java or-tools)
* Install cmake. To install cmake, download the official .dmg archive from http://www.cmake.org/download.

Installation:
* Copy scipoptsuite archive in dependencies/archives. Make sure the version matches the one in the third_party makefile.
* `make third_party`
* `make install_python_modules`
* `make python`
* `make test_python` (to test if it works)

Note: If parts fail because of lack of permissions, run the above commands using `sudo`
Note: If you get an ImportError that it cannot find the module named ortools.constraint_solver or some other module, you probably have to add the pythonpath to your .bash_profile that points to the src folder of your ortools install,
e.g. `export PYTHONPATH=<<path to ortools>>/or-tools/src:${PYTHONPATH}`

**Comment by mjfwest** [comment]
I still refer back to this closed issue thread every time I install:
https://github.com/google/or-tools/issues/63 
although it does not specifically deal with SCIP it still works form python3 on OS X.

**Comment by antoniomedrano** [comment]
By the way, I'm using Python 2.7.12 and macOS Sierra 10.12.1

**Comment by antoniomedrano** [comment]
When I run `make test_python`, I get the following output:
```
[Tones-Lappy]~/Desktop/demos/or-tools-5.0 $ make test_python
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
PYTHONPATH=/Users/Antonio/Desktop/demos/or-tools-5.0/src:/Users/Antonio/Desktop/demos/or-tools-5.0/dependencies/sources/protobuf-3.0.0/python python2.7 examples/python/hidato_table.py
Traceback (most recent call last):
  File "examples/python/hidato_table.py", line 27, in <module>
    from ortools.constraint_solver import pywrapcp
  File "/Users/Antonio/Desktop/demos/or-tools-5.0/src/ortools/constraint_solver/../../gen/ortools/constraint_solver/pywrapcp.py", line 21, in <module>
    _pywrapcp = swig_import_helper()
  File "/Users/Antonio/Desktop/demos/or-tools-5.0/src/ortools/constraint_solver/../../gen/ortools/constraint_solver/pywrapcp.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrapcp')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _pywrapcp
```

**Comment by mjfwest** [comment]
Are you compiling from a clone/fork of the git repository, or from a downloaded release such as from here: https://github.com/google/or-tools/releases/tag/v5.0? I think it is expecting to be a clone of a git repository, but I am not sure why.

**Comment by antoniomedrano** [comment]
I compiled from the original repo release

**Comment by antoniomedrano** [comment]
Also, if I run `check_python_deps.py`, I get:

```
[Tones-Lappy]~/Desktop/demos/or-tools-5.0 $ python tools/check_python_deps.py 
INFO:root:Python path : /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
INFO:root:Python version : 2.7.12 (v2.7.12:d33e0cf91556, Jun 26 2016, 12:10:39) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

INFO:root:or-tools version : VVVV
INFO:root:/Users/Antonio/Desktop/demos/or-tools-5.0/src/ortools/__init__.pyc

INFO:root:protobuf version : 3.1.0.post1
INFO:root:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/__init__.pyc
```

**Comment by Mizux** [comment]
Is it fixed with the last version of ortools ?
