### ISSUE TITLE
In CpSolverSolutionCallback is missing value method with argument LinearExpressionProto

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#2832]
**What language and solver does this apply to?**
Java

**Describe the problem you are trying to solve.**
Get a value of linear expression in solution callback in cp-sat solver(ortools 9.1). For example intervals now deals with linear expression instead of intvar index.

**Describe the solution you'd like**
Add new method CpSolverSolutionCallback.value(LinearExpressionProto proto) that returns the value of linear expression.

**Describe alternatives you've considered**

**Additional context**

**Comment by prissky** [comment]
Is there a way to use this fix to get the values of interval? Since from java I can only get _LinearExpresionProto_ and there is only value() for _IntVar_ in callback...
