### ISSUE TITLE
Release problems with version 9.1.9552

### ISSUE THREAD

**Issue by benoit9126** [google/or-tools#2848]
**What version of OR-Tools and what language are you using?**
Version: ortools 9.1.9552
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Does not matter

**What operating system (Linux, Windows, ...) and version?**
Linux (Debien Bullseye)

**What did you do?**
I would like to install the last available version from Pypi (ortools 9.1.9552) but unfortunately, the only built wheels of this last version are for aarch64 architecture https://pypi.org/project/ortools/#files

**What did you expect to see**

I would like to have the usual wheels as for the version 9.1.9490 https://pypi.org/project/ortools/9.1.9490/#files (including x86_64 wheels)

**Comment by lperron** [comment]
This is the same release with the patches to build it on arm 64.
