### ISSUE TITLE
AddModuloEquality does not work with negative numbers

### ISSUE THREAD

**Issue by psarka** [google/or-tools#2864]
**What version of OR-Tools and what language are you using?**
Version: 9.1.9490
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Linux, Ubuntu 20.04.3 LTS

**What did you do?**
Try to solve this (full script below):
```py
m.AddLinearConstraint(a, -4, -4)
m.AddModuloEquality(0, a, 4)
```

**What did you expect to see**
solution `a = -4`

**What did you see instead?**
`INFEASIBLE`

Make sure you include information that can help us debug (full error message, model Proto).
Full script for repro:

```py
from ortools.sat.python.cp_model import CpModel
from ortools.sat.python.cp_model import CpSolver
from ortools.sat.python.cp_model import INFEASIBLE

m = CpModel()

a = m.NewIntVar(-100, 100, 'a')

m.AddLinearConstraint(a, -4, -4)
m.AddModuloEquality(0, a, 4)

solver = CpSolver()
print(solver.Solve(m) == INFEASIBLE)
```
(prints `True`)

**Comment by kasperdokter** [comment]
It seems that the docs should be changed to 

```
if expr >= 0:
    target = expr % mod
else:
    target == -(-expr % mod)
```

or the implementation of `add_modulo_equality` should be updated.

**Comment by lperron** [comment]
it depends on your convention. I will check.

C and python differ. We use the C convention.

I have updated the doc.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mar. 23 juil. 2024 à 19:17, Kasper Dokter ***@***.***> a
écrit :
