### ISSUE TITLE
Minor bug: NameError: name 'version_info' is not defined

### ISSUE THREAD

**Issue by antoniomedrano** [google/or-tools#288]
Installed from source on 12/12/2016 via a repo clone, and installing the python version with scip on a mac. When running `check_python_deps.py`, I get an error. This isn't affecting anything in use though.

```
[Tones-Lappy]~/Desktop/demos/or-tools $ python tools/check_python_deps.py
INFO:root:Python path : /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
INFO:root:Python version : 2.7.12 (v2.7.12:d33e0cf91556, Jun 26 2016, 12:10:39) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

Traceback (most recent call last):
  File "tools/check_python_deps.py", line 54, in <module>
    if version_info[0] >= 3:
NameError: name 'version_info' is not defined
```

**Comment by dlahlou** [comment]
Hello Antonio,
Thank you for flagging this. 
By the way, when using or-tools from source, `tools/check_python_deps.py` is not meant to be used. If you want to check the python dependencies, run `make rpy EX=examples/python/check_dependencies.py` instead.
We are about to publish a new version of the documentation with all the new commands.
Regards,
