### ISSUE TITLE
Check failed: 1 == ct.lin_max().target().vars_size() (1 vs. 0)

### ISSUE THREAD

**Issue by cfsfifty** [google/or-tools#2889]
**What version of OR-Tools and what language are you using?**
Version: 9.1.9490
Language: Python 3.8.5

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10 Pro, Build 19042.1288

**What did you do?**
Solving model in attached proto:
solver = cp_model.CpSolver() 
solver.parameters.num_search_workers  = 16 
solver.parameters.linearization_level     = 2  
solver.parameters.log_search_progress = True 
solver.parameters.log_to_response       = True 
solver.parameters.cp_model_presolve   = True 
solver.parameters.max_time_in_seconds = 1000 

**What did you expect to see**
Optimal solution, found with version 9.0.9048

**What did you see instead?**
..
#Bound  14.52s best:220   next:[20,219]   lb_tree_search #nodes:79
Check failed: 1 == ct.lin_max().target().vars_size() (1 vs. 0) 
*** Check failure stack trace: ***
    @   00007FF85717C206  (unknown)
    @   00007FF85717A6E9  (unknown)
    @   00007FF8574DB989  (unknown)
    @   00007FF8574E4E22  (unknown)
    @   00007FF8574E32FA  (unknown)
    @   00007FF8572363E1  (unknown)
    @   00007FF85723D21D  (unknown)
    @   00007FF857231465  (unknown)
    @   00007FF8573EBEA9  (unknown)
    @   00007FF857662C14  (unknown)
    @   00007FF85766194F  (unknown)
    @   00007FF8D0571BB2  (unknown)
    @   00007FF8D2AE7034  (unknown)
    @   00007FF8D2E82651  (unknown)

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
[modelProto.zip](https://github.com/google/or-tools/files/7499999/modelProto.zip)

**Comment by lperron** [comment]
Thanks, we will debug it.

**Comment by cfsfifty** [comment]
Thanks, the objective was merely an experiment.
Could you point me to the source for the processing of objective within the solver?
This would be very much appreciated!

**Comment by lperron** [comment]
I cannot load the model.
Can you try exporting as a text file (use a .txt suffix) ?

**Comment by lperron** [comment]
There is not one place where the objective is managed.

**Comment by cfsfifty** [comment]
Sorry, here it is a text file
[modelProto_txt.zip](https://github.com/google/or-tools/files/7512548/modelProto_txt.zip)
