### ISSUE TITLE
Support for M1 processors for OR-Tools C++

### ISSUE THREAD

**Issue by kevinfreyberg** [google/or-tools#2893]
**What language and solver does this apply to?**
C++

**Describe the problem you are trying to solve.**
Need support for M1 architectures, ortools required for a c++ project

**Describe the solution you'd like**
Support for M1 archs please

**Comment by lperron** [comment]
Duplicate

**Comment by Mizux** [comment]
#2722 #2732

**Comment by lperron** [comment]
Note that or-tools is available on brew for M1.
This is untested though.

https://formulae.brew.sh/formula/or-tools
