### ISSUE TITLE
Please keep both x86_64 and aarch wheels the same version

### ISSUE THREAD

**Issue by junli-lyft** [google/or-tools#2894]
**What language and solver does this apply to?**
Python

**Describe the problem you are trying to solve.**
x86_64 wheel is version 9.1.9490.
aarch wheel is version 9.1.9552.
This caused some confusion and inconsistency in our system.

**Describe the solution you'd like**
Please use the same version for both x86_64 and aarch wheels.

**Describe alternatives you've considered**
I could manually build both wheels myself for each version. But it introduces a lot of ongoing maintenance.

**Comment by lperron** [comment]
Should not happen in the future. But as aarch packages take nearly a day to build, we found problems after the release.
