### ISSUE TITLE
makefile: cl.exe not found when using VS 2022

### ISSUE THREAD

**Issue by lovemory** [google/or-tools#2895]
**What version of OR-Tools and what language are you using?**
or-tools_VisualStudio2019-64bit_v9.1.9490

**What did you do?**
1.  open x64 Native Tools Command Prompt for VS 2022 Current
2.  navigate to the directory:   F:\google_Or-Tools\or-tools_VisualStudio2019-64bit_v9.1.9490
3. run command:  tools\make test_cc
```

F:\google_Or-Tools\or-tools_VisualStudio2019-64bit_v9.1.9490>tools\make.exe test_cc
process_begin: CreateProcess(NULL, echo the cl command was not found in your PATH, ...) failed.
make (e=2): 系统找不到指定的文件。
make: *** [Makefile:266: test_cc] Error 2

F:\google_Or-Tools\or-tools_VisualStudio2019-64bit_v9.1.9490>
```

Solution:
modify Makefile , add a row

`SHELL = cmd.exe`

```

VERSION := 9.1.9490
# Let's discover something about where we run
ifeq ($(OS),Windows_NT)
OS = Windows
endif
ifeq ($(OS),Windows)
SYSTEM = win
SHELL = cmd.exe
else
SYSTEM = unix
endif

```
then run the command 
`tools\make test_cc`
fixed this bug.

**Comment by Mizux** [comment]
> 1. open x64 Native Tools Command Prompt for VS 2022 Current

Do you know if you can reproduce this error with Visual Studio **2019** and not the RC 2022 ?

**Comment by lovemory** [comment]
> > 1. open x64 Native Tools Command Prompt for VS 2022 Current
> 
> Do you know if you can reproduce this error with Visual Studio **2019** and not the RC 2022 ?

sorry, I don't have vs2019 now.
