### ISSUE TITLE
Circuit constraint with all loops selected is infeasible?

### ISSUE THREAD

**Issue by cfsfifty** [google/or-tools#2899]
**What version of OR-Tools and what language are you using?**
Version: 9.1.9490
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10 Pro, Build: 19042.1288

**What did you do?**
Please see Python example model with one circuit constraint.

**What did you expect to see**
This model with circuit constraint is infeasible.
But in my understanding of circuit, the model should be feasible,
as all loops are selected/true.

**What did you see instead?**
Infeasible.

Make sure you include information that can help us debug (full error message, model Proto).
[testCircuit_py.txt](https://github.com/google/or-tools/files/7541112/testCircuit_py.txt)

**Anything else we should know about your project / environment**

**Comment by stradivari96** [comment]
If both are false you also need a (0, 0) arc

**Comment by stradivari96** [comment]
If both are false you also need a (0, 0) arc

**Comment by cfsfifty** [comment]
Ah, that makes sense. Missed the node 0.
