### ISSUE TITLE
Invalid proto file in linux

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#2907]
**What version of OR-Tools and what language are you using?**
Version: v9.1
Language: C++/Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Debian 10, Windows 10

**What did you do?**
I created a model in java and windows 10. Before solve the model was saved in proto file and without any complaints from cp-sat solver walked through presolve and solve phases.
In c++ and linux cp-sat solver identified a model created from proto file as invalid due to solution hint that contains duplicate variables. This is true since some variables were reused - two tasks that should start in same time use same variable. I tried to execute proto file in java on windows 10 and there were no complains from cp-sat solver.

**What did you expect to see**
Both models (original and created from proto file) should be valid or invalid on all platforms. So far it seems that it is not true.

When I took care that only one hint per variable is added, no problems were identified.

[test-min.zip](https://github.com/google/or-tools/files/7573066/test-min.zip)
.

**Comment by lperron** [comment]
Are you sure both platforms run the same version of or-tools?

**Comment by gregy4** [comment]
I double checked and found that old jniortools.dll was present in current directory in java. After the fix all variants works same way.

Related to hints, maybe two or more hints per variable with same value should be allowed. In case someone like me reuse variables extra work to add only one hint per variable should be done.

**Comment by lperron** [comment]
Dual hinting is very likely to be a bug in the code.
So we prefer to be pedantic.
