### ISSUE TITLE
Unexpected crash in CP-SAT LNS

### ISSUE THREAD

**Issue by imalliar** [google/or-tools#2908]
**General Information**
Version: 9.1
Language: C#
Solver: CP-SAT
OS:  Windows

**Description**
We are trying to use CP-SAT to solve a Job shop problem. The model is rather big (see model.zip). The error is  **Infeasible LNS solution** which only happens after a while. 
From the output (see output.log) it looks like the error comes up after multiple feasible solutions.
There is no way to catch the exception with try/catch  block. The model and output files are included.
Is this happening because of fault in our model, or is it a bug?
[model.zip](https://github.com/google/or-tools/files/7580068/model.zip)
[output.log](https://github.com/google/or-tools/files/7580070/output.log)

**Comment by lperron** [comment]
Can you send us the original model and not the dump lns problem ?

**Comment by imalliar** [comment]
Yes of course. Thanks

[model.log](https://github.com/google/or-tools/files/7580310/model.log)

**Comment by lperron** [comment]
In txt mode please (zipped if needed)

**Comment by imalliar** [comment]
Sure

[model.zip](https://github.com/google/or-tools/files/7580981/model.zip)

**Comment by lperron** [comment]
Still not the full model (it does not have an objective).
Please do
` model.ExportToFile("mymodel.pb.txt");`

**Comment by imalliar** [comment]
Sorry I had the export just before the model.Minimize()

[mymodel.pb.zip](https://github.com/google/or-tools/files/7581595/mymodel.pb.zip)

**Comment by lperron** [comment]
Thanks. We can reproduce it.

**Comment by imalliar** [comment]
Hi Laurent. Sorry for the inconvenience but is there a chance for this bug to be fixed at the upcoming 9.2 version?

**Comment by lperron** [comment]
This has been fixed already.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le jeu. 2 déc. 2021 à 12:21, Jacob Malliaros ***@***.***> a
écrit :

**Comment by lperron** [comment]
I closed the bug with the patch 9 days ago.
