### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by ASmbat** [google/or-tools#2909]
Version 9.1.9490 
Language Java
**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing Solver
**What operating system (Linux, Windows, ...) and version?**
I use docker image in AWS
dockerfile system
FROM public.ecr.aws/lambda/java:11
**What did you do?**

I am create project with 2553 stops and 40 vehicle.
after run it get a lot of memory 8GB+
I think may be is there any memory leak?

**Comment by lperron** [comment]
Is the memory increasing if you repeat multiple solve with a smaller model ?
It is very unlikely this code leaks as we have powerful tools checking for leaks.

**Comment by ASmbat** [comment]
> Is the memory increasing if you repeat multiple solve with a smaller model ? It is very unlikely this code leaks as we have powerful tools checking for leaks.

I try with 990 stops and 20 vehicle too, and he use 8Gb+ memory, I check my code memory usage before call Or-tools solve method and it us ~ 600mb

**Comment by lperron** [comment]
You do not describe a memory leak, but a process that consumes a
significant amount of memory.

Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by ASmbat** [comment]
> You do not describe a memory leak, but a process that consumes a significant amount of memory

I do not know how much memory the or-tools uses to solve the problem. And I saw that at 1000-2500 stops the memory rises 
to 8gb. 
and one more detail on google compute engine with system debian its use 5-6gb on 2553 stops.
