### ISSUE TITLE
Set CPLEX parameters use setSolverSpecificParametersAsString

### ISSUE THREAD

**Issue by Robot-1x** [google/or-tools#2916]
**What version of OR-Tools and what language are you using?**
Version: 9.1.9490
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)
Cplex 12.9

**What operating system (Linux, Windows, ...) and version?**
MacOS 10.15.4

**What did you do?**
Set solver parameters use setSolverSpecificParametersAsString to solve [LinearProgramming.java](https://github.com/google/or-tools/blob/stable/examples/java/LinearProgramming.java) 
Switch solver with CPLEX and add set 
`solver.setSolverSpecificParametersAsString("CPLEX Parameter File Version 12.9.0.0 \n CPXPARAM_MIP_Tolerances_MIPGap 0");
`or
`solver.setSolverSpecificParametersAsString("CPXPARAM_MIP_Tolerances_MIPGap 0");`
Console just log:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0617 07:28:41.510009     1 linear_solver.cc:1815] SetSolverSpecificParametersAsString() not supported by CPLEX library version 12.09.00.00
W0617 07:28:41.918945     1 linear_solver.cc:1815] SetSolverSpecificParametersAsString() not supported by CPLEX library version 12.09.00.00
```

**Comment by Mizux** [comment]
Try to use:

https://github.com/google/or-tools/blob/86d4c543f717fa8716a9d66c25143660668bf825/ortools/linear_solver/cplex_interface.cc#L153

**Comment by Robot-1x** [comment]
Thanks for #2901 method. Add few changes in cplex_interface.cc:

```
bool SetSolverSpecificParametersAsString(const std::string& parameters) override;
```
```
bool CplexInterface::SetSolverSpecificParametersAsString(const std::string& parameters) {
        if (parameters.empty()) return true;
        for (const auto parameter : absl::StrSplit(parameters, absl::ByAnyChar(",\n"),
                                                   absl::SkipWhitespace())) {
            std::vector<std::string> key_value = absl::StrSplit(parameter, absl::ByAnyChar("= "), absl::SkipWhitespace());
            if (key_value.size() != 2) {
                LOG(WARNING) << absl::StrFormat("Cannot parse parameter '%s'. Expected format is 'parameter/name = value'", parameter);
                return false;
            }
            std::string name = key_value[0];
            absl::RemoveExtraAsciiWhitespace(&name);
            std::string value = key_value[1];
            absl::RemoveExtraAsciiWhitespace(&value);
            (void)CPXXsetintparam(mEnv, std::stoi(name), std::stoi(value));
            VLOG(2) << absl::StrFormat("Set parameter %s to %s", name, value);
        }
        return true;
    }
```
It works with restrictive condition. I want to make this setting more general, so use "CPXXsetintparam". It needs identifier([int number](https://www.ibm.com/docs/en/icos/12.9.0?topic=parameters-mip-emphasis-switch)) of parameters as following:
```
solver.setSolverSpecificParametersAsString("2058 = 5");
```
And the console print:
```
MIP emphasis: heuristic.
```
