### ISSUE TITLE
It'd be nice to have 32-bit (aka i386 aka i686) wheels for Windows and Linux

### ISSUE THREAD

**Issue by KOLANICH** [google/or-tools#2923]
**What language and solver does this apply to?**
Python

**Describe the problem you are trying to solve.**
No prebuilt wheels for 32-bit systems.

**Describe the solution you'd like**
Them being provided too.

**Describe alternatives you've considered**
Drop 32 bit and say "one must throw away a 32-bit devices into dumpster". Completely inacceptable.

**Additional context**
https://pypi.org/project/ortools/9.1.9490/

**Comment by Mizux** [comment]
No human power resources to maintain the 32bits support.

Feel free to fork the project, fix any 32bits related issues, setup 32bits github action workflow,  then send us a PR...
