### ISSUE TITLE
Bug or misunderstanding?

### ISSUE THREAD

**Issue by skonet** [google/or-tools#2924]
Hello,

I use OR-Tools since a few months and I find it quite exciting!

However I am a bit puzzled by sample code below (I simplified my original code):

```python
from ortools.sat.python import cp_model

if __name__ == '__main__':
    # Model
    model = cp_model.CpModel()

    # Variables
    qty1 = model.NewIntVar(0, 2, '')
    qty2 = model.NewIntVar(0, 2, '')
    qty3 = model.NewIntVar(0, 2, '')

    distance = model.NewIntVar(-1000, 1000, '')
    model.Add(distance == qty1 * 80 + qty2 * 100 + qty3 * 120 - 95)

    # Constraints
    model.Add(qty1 + qty2 + qty3 <= 1)
    model.Add(distance >= 0)

    # Objective
#    model.Minimize(qty1 * 80 + qty2 * 100 + qty3 * 120 - 95)
    model.Minimize(distance)

    # Solve
    solver = cp_model.CpSolver()
#    solver.parameters.log_search_progress = True
    status = solver.Solve(model)
    print("Solver returned status {0} after {1} ms.".format(solver.StatusName(), round(solver.WallTime() * 1000)))

```
With this code, I get INFEASIBLE status.
If I replace Minimize() line with the commented line above, I get a correct solution.
Why is `model.Minimize(distance)` uncorrect? Looks like an equivalent of commented line above.
Is this a bug or me being a newbie?

I use OR Tools v9.1.9490 with Python 3.9.6 on Win10 OS (64bit).

Thanks!

**Comment by lperron** [comment]
Bug. Thanks for the report

**Comment by lperron** [comment]
Thanks for the report.
