### ISSUE TITLE
or-tools failed to run test on Windows with MSVC of win32

### ISSUE THREAD

**Issue by YangYang129** [google/or-tools#2925]
or-tools failed to run test on Windows with MSVC of win32. It can reproduces on version https://github.com/google/or-tools/commit/86d4c543f717fa8716a9d66c25143660668bf825. Could you please help look at this issue? Thank you very much

**Environment**
Compiler version: VS2019 (16.11.5)
Operating system: Windows server 2019

**Reproduce steps:**
1. git clone https://github.com/google/or-tools C:\git-lfs
2. cd or-tool
3. mkdir build_x86
4. cd build_x86
5. cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DBUILD_DEPS=ON -DCMAKE_BUILD_TYPE=Release ..
6. cmake --build . --config Release --target ALL_BUILD -v -- /maxcpucount
7. ctest --build-config Release --output-on-failure

**Error log:**
[testa.log](https://github.com/google/or-tools/files/7606064/testa.log)

**Error info:**
The following tests FAILED:
	 19 - cxx_constraint_solver_simple_ls_program (SEGFAULT)
	 26 - cxx_constraint_solver_vrp (SEGFAULT)
	 27 - cxx_constraint_solver_vrp_breaks (SEGFAULT)
	 28 - cxx_constraint_solver_vrp_capacity (SEGFAULT)
	 29 - cxx_constraint_solver_vrp_drop_nodes (SEGFAULT)
	 30 - cxx_constraint_solver_vrp_global_span (SEGFAULT)
	 31 - cxx_constraint_solver_vrp_initial_routes (SEGFAULT)
	 32 - cxx_constraint_solver_vrp_pickup_delivery (SEGFAULT)
	 33 - cxx_constraint_solver_vrp_pickup_delivery_fifo (SEGFAULT)
	 34 - cxx_constraint_solver_vrp_pickup_delivery_lifo (SEGFAULT)
	 35 - cxx_constraint_solver_vrp_resources (SEGFAULT)
	 36 - cxx_constraint_solver_vrp_routes (SEGFAULT)
	 37 - cxx_constraint_solver_vrp_starts_ends (SEGFAULT)
	 38 - cxx_constraint_solver_vrp_time_windows (SEGFAULT)
	 39 - cxx_constraint_solver_vrp_with_time_limit (SEGFAULT)
	 40 - cxx_constraint_solver_vrptw_store_solution_data (SEGFAULT)
	 51 - cxx_sat_multiple_knapsack_sat (Exit code 0xc0000409
)
	 67 - cxx_cpp_cvrp_disjoint_tw (SEGFAULT)
	 68 - cxx_cpp_cvrptw (SEGFAULT)
	 69 - cxx_cpp_cvrptw_with_resources (SEGFAULT)
	 70 - cxx_cpp_cvrptw_with_stop_times_and_resources (SEGFAULT)
	 72 - cxx_cpp_golomb_sat (Exit code 0xc0000409)

**Comment by Mizux** [comment]
https://github.com/google/or-tools/issues/2923#issuecomment-977985630
