### ISSUE TITLE
External component has thrown an exception

### ISSUE THREAD

**Issue by huig-** [google/or-tools#2938]
Using ortools 9.1.9490 with C# the above exception is thrown, log below:

Starting CP-SAT solver.
Parameters: max_time_in_seconds: 21600 log_search_progress: true num_search_workers: 8 mip_max_bound: 1000000000000 relative_gap_limit: 0

Initial optimization model '':
#Variables: 23235861 (33574 in objective)
- 22602629 in [-2147483648,2147483647]
- 633232 in [0,1]
#kLinear1: 1428145 (#enforced: 12067)
#kLinear2: 698695 (#enforced: 10669)
#kLinear3: 1157503 (#enforced: 6689)
#kLinearN: 279637 (#enforced: 5368) (#terms: 1754076)

Starting presolve at 15.86s
External component has thrown an exception.
at Google.OrTools.Sat.operations_research_satPINVOKE.SolveWrapper_Solve(HandleRef jarg1, Int32 model_proto_size, Byte[] jarg2)
at Google.OrTools.Sat.SolveWrapper.Solve(CpModelProto model_proto)
at Google.OrTools.Sat.CpSolver.Solve(CpModel model, SolutionCallback cb)

**Comment by lperron** [comment]
we need a model to reproduce.

**Comment by Mizux** [comment]
`633232 in [0,1]` seems suspicious...

**Comment by lperron** [comment]
I am more worried with the 26M large variables

**Comment by huig-** [comment]
Any idea where can I attach the zip file with the model (cpModel.ExportToFile)?

**Comment by lperron** [comment]
does it comes from a mps file ?

Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mar. 30 nov. 2021 à 14:39, Ignacio Gago ***@***.***> a
écrit :

**Comment by huig-** [comment]
it comes from CP-SAT so I guess not, exported with https://google.github.io/or-tools/dotnet/classGoogle_1_1OrTools_1_1Sat_1_1CpModel.html#a75d882ad165a26668285c190c3778d6a

**Comment by lperron** [comment]
No, I meant the original problem is a linear one solved using the MPSolver class, with the CP-SAT backend.
It could be simpler if you send the us the linear model, instead of the transformed CP-SAT protobuf.

**Comment by huig-** [comment]
it has specific CP-SAT constraints (AddMaxEquality, AddBoolOr, etc.)

**Comment by lperron** [comment]
where ?

Starting CP-SAT solver.

Parameters: max_time_in_seconds: 21600 log_search_progress: true
num_search_workers: 8 mip_max_bound: 1000000000000 relative_gap_limit: 0

Initial optimization model '':
#Variables: 23235861 (33574 in objective)

   - 22602629 in [-2147483648,2147483647]
   - 633232 in [0,1]
   #kLinear1: 1428145 (#enforced: 12067)
   #kLinear2: 698695 (#enforced: 10669)
   #kLinear3: 1157503 (#enforced: 6689)
   #kLinearN: 279637 (#enforced: 5368) (#terms: 1754076)

Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mar. 30 nov. 2021 à 18:07, Ignacio Gago ***@***.***> a
écrit :

**Comment by lperron** [comment]
any news ?
