### ISSUE TITLE
ERROR 500 FUNCTON SEARCH

### ISSUE THREAD

**Issue by FarmAgri** [google/or-tools#2946]
Comunication error:
**500. That’s an error. The server encountered an error and could not complete your request.**
**Failed to load resource: the server responded with a status of 500 ()**

Note that it appears when you want to access the google profile, search functionality.
![image](https://user-images.githubusercontent.com/83114085/144554775-94fd439c-5b43-46cf-90ab-cd3f35eff1f8.png)
![image](https://user-images.githubusercontent.com/83114085/144554917-d3e9a854-1848-4fa8-aae3-5a5c7b23cdce.png)

**Comment by Mizux** [comment]
Seems unrelated to OR-Tools project -> closing
