### ISSUE TITLE
AddElement inconsistent behavior 

### ISSUE THREAD

**Issue by marchob** [google/or-tools#2947]
Version: v9.1.9490.
Language: Python

CP-SAT

macOS Big Sur version 11.5.2

1- Run the attached code (a toy problem) using OR-Tools version v9.1.9490.

Expected behavior: print(status.cp_model.OPTIMAL): True

Actual behavior:print(status.cp_model.OPTIMAL): False, print(status.cp_model.INFEASIBLE): True

I tried the same code with OR-Tools v9.0.9048 and the model is solved as expected.

[AddElement.zip](https://github.com/google/or-tools/files/7649851/AddElement.zip)

**Comment by lperron** [comment]
Cannot reproduce on master.
