### ISSUE TITLE
min cost flow loop forever

### ISSUE THREAD

**Issue by jason5fd** [google/or-tools#296]
When i used the minimum cost flow solver to solve the assignment problem, it didn't return with a few cases. Has anyone met the same problem?

**Comment by Deepblue129** [comment]
+1 The min cost flow has always returned for me but it may take awhile like 10 minutes long or so. At first, I thought it just did not return. 

Following on this bug, if this is the intended behavior for more difficult graphs, is it possible to input a max time such that ortools returns null values if it is unable to finish in a set amount of time.

**Comment by Deepblue129** [comment]
@jason5fd 

If it loops forever for you, reading their docs it says:

> // IMPORTANT:
// The algorithm is not able to detect the infeasibility of a problem (i.e.,
// when a bottleneck in the network prohibits sending all the supplies.)
// Worse, it could in some cases loop forever. This is why feasibility checking
// is enabled by default (FLAGS_min_cost_flow_check_feasibility=true.)
// Feasibility checking is implemented using a max-flow, which has a much lower
// complexity. The impact on performance is negligible, while the risk of being
// caught in an endless loop is removed. Note that using the feasibility checker
// roughly doubles the memory consumption.

More discussion here: https://developers.google.com/optimization/reference/graph/min_cost_flow/
