### ISSUE TITLE
TypeError in SimpleMinCostFlow_AddArcWithCapacityAndUnitCost

### ISSUE THREAD

**Issue by YisenWang** [google/or-tools#300]
I follow the examples in this page "https://developers.google.com/optimization/assignment/assignment_min_cost_flow", but when I try to write my own code, I am confused by the following error. 

Followed by the code:
```python 
for i in range(len(start_nodes)):
    min_cost_flow.AddArcWithCapacityAndUnitCost(start_nodes[i], end_nodes[i],
                                                capacities[i], costs[i])
```

I wrote my own code:
```python
for i, word in enumerate(word_to_id.keys()):
    min_cost_flow.AddArcWithCapacityAndUnitCost(0, i+1, 1, 0)
    min_cost_flow.SetNodeSupply(i+1, 0)
```

It raised the error:
```py
TypeError: in method 'SimpleMinCostFlow_AddArcWithCapacityAndUnitCost', argument 3 of type 'operations_research::NodeIndex'
```
What does it mean? I don't know where it's wrong? How to solve it ? Thanks

**Comment by aspencerpsu** [comment]
Can you show your entire script? it's hard to see exactly how you defined your node data

**Comment by YisenWang** [comment]
It has been solved. Thank you!

**Comment by ameeuw** [comment]
@YisenWang Could you be so kind to share your solution, just stumbled across the same error while starting with ortools.
Thank you

**Comment by akobre01** [comment]
I had the same issue.  It was being caused by the types of the values returned by a call numpy.where.  Before adding indices to the start_nodes list, I had to cast the indices to python ints (rather than numpy ints).

**Comment by skwalas** [comment]
I just confirmed this issue when using integers from a numpy array, even if reformatted to list.  Specific to Python 3.6.3. Casting to int (i.e. int(x)) resolves the problem.  This error does not appear when running the exact code in 2.7.14, even without the re-casting.

**Comment by simontamayo** [comment]
You need to cast the inputs to integers, but it seems that casting them to numpy ints does not work... I casted with python ints and it worked well:

`capacities = [int(i) for i in capacities] 
`costs = [int(i) for i in costs] 

and so on...

**Comment by KultiginX** [comment]
I have the same problem, although followed the instructions above. I am using python 3.7 on MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports) in conda env.  data['dist] is a dict of distances.  Here is the code. Would you please help me?
start_nodes=[]
end_nodes=[]
capacities=[]
unit_costs=[]
supplies_w=[]
supplies_c=[]
for w in data['WH']: 
    supplies_w.append(int(99))
    for c in data['CUST']:
        start_nodes.append(str(w))
        end_nodes.append(c)
        capacities.append(int(9))
        unit_costs.append(int(data['dist'][w][c]))
        supplies_c.append(-1)
        
capacities = [1000 for i in start_nodes]
unit_costs = [1 for i in start_nodes]

supplies=(supplies_w+supplies_c)

supplies = [int(i) for i in supplies]

**Comment by KultiginX** [comment]
[start_nodes=[]
end_nodes=[]
capacities=[]
unit_costs=[]
supplies_w=[]
supplies_c=[]
for w in data['WH']: 
    supplies_w.append(int(99))
    for c in data['CUST']:
        start_nodes.append(str(w))
        end_nodes.append(c)
        capacities.append(int(9))
        unit_costs.append(int(data['dist'][w][c]))
        supplies_c.append(-1)
        
capacities = [1000 for i in start_nodes]
unit_costs = [1 for i in start_nodes]

supplies=(supplies_w+supplies_c)

supplies = [int(i) for i in supplies]](url)

**Comment by KultiginX** [comment]
`for w in data['WH']: 
    supplies_w.append(int(99))
    for c in data['CUST']:`

**Comment by Mizux** [comment]
@KultiginX please avoid necro posting and you should put your code in a gist
e.g. https://gist.github.com/Mizux/5617f65a7be19449fa475cf04b45e50a

**Comment by KultiginX** [comment]
Thanks for the feedback. I solved the problem. It was not about ints of capacities or unit_costs, but node names. I changed the names of the nodes from strings to integers. It works now. Thanks.
