### ISSUE TITLE
Solver Output Cannot be Redirected to File?

### ISSUE THREAD

**Issue by gdowdy3** [google/or-tools#3006]
**What version of OR-Tools and what language are you using?**
Version: v9.0.9048
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
SCIP

**What operating system (Linux, Windows, ...) and version?**
Windows 10 Enterprise

**What did you do?**
1. Save the following python script to a working directory as `MWE.py`:

```python
from ortools.linear_solver import pywraplp
import sys


def main():
    # Create the mip solver with the SCIP backend.
    solver = pywraplp.Solver.CreateSolver('SCIP')

    infinity = solver.infinity()
    # x and y are integer non-negative variables.
    x = solver.IntVar(0.0, infinity, 'x')
    y = solver.IntVar(0.0, infinity, 'y')

    print('Number of variables =', solver.NumVariables())

    # x + 7 * y <= 17.5.
    solver.Add(x + 7 * y <= 17.5)

    # x <= 3.5.
    solver.Add(x <= 3.5)

    print('Number of constraints =', solver.NumConstraints())

    # Maximize x + 10 * y.
    solver.Maximize(x + 10 * y)

    status = solver.Solve()

    if status == pywraplp.Solver.OPTIMAL:
        print('Solution:')
        print('Objective value =', solver.Objective().Value())
        print('x =', x.solution_value())
        print('y =', y.solution_value())
    else:
        print('The problem does not have an optimal solution.')

    print('\nAdvanced usage:')
    print('Problem solved in %f milliseconds' % solver.wall_time())
    print('Problem solved in %d iterations' % solver.iterations())
    print('Problem solved in %d branch-and-bound nodes' % solver.nodes())


if __name__ == '__main__':

    sys.stdout = open('out.log', 'w')

    main()
```

2. Run the script from the command line using `python MWE.py`
3. Observe that nothing is printed to the terminal.
4. Open up the `out.log` file that has been created, and observe that all the print statements in the script wrote to that file:
```
Number of variables = 2
Number of constraints = 2
Solution:
Objective value = 23.0
x = 3.0
y = 2.0

Advanced usage:
Problem solved in 4.000000 milliseconds
Problem solved in 0 iterations
Problem solved in 1 branch-and-bound nodes
```
5. Modify the `MWE.py` script by enabling the solver output, as shown below:
```python
from ortools.linear_solver import pywraplp
import sys


def main():
    # Create the mip solver with the SCIP backend.
    solver = pywraplp.Solver.CreateSolver('SCIP')

    infinity = solver.infinity()
    # x and y are integer non-negative variables.
    x = solver.IntVar(0.0, infinity, 'x')
    y = solver.IntVar(0.0, infinity, 'y')

    print('Number of variables =', solver.NumVariables())

    # x + 7 * y <= 17.5.
    solver.Add(x + 7 * y <= 17.5)

    # x <= 3.5.
    solver.Add(x <= 3.5)

    print('Number of constraints =', solver.NumConstraints())

    # Maximize x + 10 * y.
    solver.Maximize(x + 10 * y)

    # Display output
    solver.EnableOutput()

    status = solver.Solve()

    if status == pywraplp.Solver.OPTIMAL:
        print('Solution:')
        print('Objective value =', solver.Objective().Value())
        print('x =', x.solution_value())
        print('y =', y.solution_value())
    else:
        print('The problem does not have an optimal solution.')

    print('\nAdvanced usage:')
    print('Problem solved in %f milliseconds' % solver.wall_time())
    print('Problem solved in %d iterations' % solver.iterations())
    print('Problem solved in %d branch-and-bound nodes' % solver.nodes())


if __name__ == '__main__':

    sys.stdout = open('out.log', 'w')

    main()
```
6. Run the script from the command line using `python MWE.py`
7. Observe that the solver output is printed to the terminal:
```
feasible solution found by trivial heuristic after 0.0 seconds, objective value 0.000000e+00
presolving:
(round 1, fast)       0 del vars, 1 del conss, 0 add conss, 3 chg bounds, 2 chg sides, 0 chg coeffs, 0 upgd conss, 0 impls, 0 clqs
presolving (2 rounds: 2 fast, 1 medium, 1 exhaustive):
 0 deleted vars, 2 deleted constraints, 0 added constraints, 3 tightened bounds, 0 added holes, 2 changed sides, 0 changed coefficients
 0 implications, 0 cliques
presolved problem has 2 variables (0 bin, 2 int, 0 impl, 0 cont) and 0 constraints
transformed objective value is always integral (scale: 1)
Presolving Time: 0.00
transformed 1/1 original solutions to the transformed problem space

 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl.
t 0.0s|     1 |     0 |     0 |     - | trivial|   0 |   2 |   0 |   0 |   0 |  0 |   0 |   0 | 2.300000e+01 | 2.300000e+01 |   0.00%| unknown

SCIP Status        : problem is solved [optimal solution found]
Solving Time (sec) : 0.00
Solving Nodes      : 1
Primal Bound       : +2.30000000000000e+01 (2 solutions)
Dual Bound         : +2.30000000000000e+01
Gap                : 0.00 %
```
8. Observe that the solver output does not appear in the `out.log` file.

**What did you expect to see?**
Since I've redirected `stdout` to the `out.log` file, I expected to see the solver output in the `out.log` file and not in the terminal.

**What did you see instead?**
The solver output is absent from `out.log`, but it is printed to the terminal.

**Make sure you include information that can help us debug (full error message, model Proto).**
I do not think this behavior is specific to SCIP.  I've seen similar behavior with Gurobi.

**Comment by gdowdy3** [comment]
This issue is apparently related to #1077, #1531, #1903, and #1889

**Comment by gdowdy3** [comment]
Hello good people at OR-Tools!

I'm basically trying to figure out how to redirect the solver output to the same file as the other print statements without resorting to command line tricks (e.g. `python MWE > out.log`).

I suspect there's a way to do this within my python script.  However, so far, it has alluded me.

I readily admit that I am not as familiar with the concept of `stdout` as I'd like to be, so forgive my ignorance.

Any help that you can give me would be greatly appreciated!

Garrett

**Comment by lperron** [comment]
Not currently. It can be done in c++, but the solver backend is invisible in non c++ languages. 

It is on our Todo list. But it will not happen soon. 

You best bet is to capture stout in python, it possible.

**Comment by gdowdy3** [comment]
Thanks for the quick response, @lperron!  I'll be eagerly awaiting that feature...

**Comment by Ozzah** [comment]
I suggest `Solver.EnableOutput()` needs an overhaul. Specifically, I may not want to write directly to the console and I may not want to write it to a file. In C#, it's common to use `ILogger` to record information, either to screen, file, database, Kafka, etc.

In C#, when we create and start a `Process`, we can override the `Process.StandardInput`, `Process.StandardOutput`, and `Process.StandardError` with our own `StreamReader` and `StreamWriter` implementations.

I think it would be useful to be able to supply a `StreamWriter` to `Solver.EnableOutput()`, and that way it's up to us to decide what to do with that output.

**Comment by Mizux** [comment]
@Ozzah thanks for your suggestion, but it should have been added to #2489
