### ISSUE TITLE
NoOverlap2D constraint gives replicate solutions

### ISSUE THREAD

**Issue by AliHebbal** [google/or-tools#3012]
Hi Everyone, 

**What version of OR-Tools and what language are you using?**
Version: 9.1.9490
Language: Python

**Which solver are you using:  CP-SAT

**What operating system (Linux, Windows, ...) and version?**

Windows 10

**What did you do?**
I'm trying to use the NoOverlap2D constraint for a geometrical problem to avoid overlap between objects on a 2D plane. 
However, when using the NoOverlap2D constraint it seems that it induces the same solution multiple times, which leads in the end in too many solutions with many replicate of the same one. 
For instance, I took a very simple example with two objects M1 and M2 that actually do not overlap. Each one has a decision variable that specify if the object is used or not. 

**What did you expect to see**

Since the  objects do not overlap we should have 4 solutions that are actually all the possible values for the decision variables (The two objects are used, no object is used, only object M1 is used, only object M2 is used).

**What did you see instead?**

However, by using the code below, we obtain a total of 15 solutions with many replicate. I can't quiet understand why we have this replicates.

Here is the code to replicate this simple example:
```python
from ortools.sat.python import cp_model
model = cp_model.CpModel()
M1 = {'x': 0,
      'y':0,
      'lx':5,
      'ly':2,
      'I': model.NewBoolVar('M1')

      }
M2 = {'x': 4,
      'y':3,
      'lx':2,
      'ly':1,
      'I': model.NewBoolVar('M2')
      }

Interval_M1_x = model.NewOptionalFixedSizeIntervalVar(M1['x'],M1['lx'],M1['I'],'interval_M1')
Interval_M2_x = model.NewOptionalFixedSizeIntervalVar(M2['x'],M2['lx'],M2['I'],'interval_M2')

Interval_M1_y = model.NewOptionalFixedSizeIntervalVar(M1['y'],M1['ly'],M1['I'],'interval_M1_y')
Interval_M2_y = model.NewOptionalFixedSizeIntervalVar(M2['y'],M2['ly'],M2['I'],'interval_M2_y')

Interval_Ms_x = [Interval_M1_x,Interval_M2_x]
Interval_Ms_y = [Interval_M1_y,Interval_M2_y]

model.AddNoOverlap2D(Interval_Ms_x, Interval_Ms_y)

class VarArraySolutionPrinter(cp_model.CpSolverSolutionCallback):
    """Print intermediate solutions."""
    def __init__(self, variables):
        cp_model.CpSolverSolutionCallback.__init__(self)
        self.__variables = variables
        self.__solution_count = 0
    def on_solution_callback(self):
        self.__solution_count += 1
        for v in self.__variables:
            print('%s=%i' % (v, self.Value(v)), end=' ')
    def solution_count(self):
        return self.__solution_count
solver = cp_model.CpSolver()
Ms = [M1, M2]
Vars = [M['I'] for M in Ms]
solution_printer = VarArraySolutionPrinter(Vars)
solver.parameters.enumerate_all_solutions = True
status = solver.Solve(model, solution_printer)
print('Number of solutions found: %i' % solution_printer.solution_count())
```

Thank you for your input.

Ali,

**Comment by lperron** [comment]
Optional intervals are currently not supported as the code is not tested for the no_ok overlap_2d. 

You can emulate that by saying that size = bool_var * fixed_ size.

**Comment by lperron** [comment]
Support for optional intervals in the no_overlap2 will come in the 9.3 release.

**Comment by AliHebbal** [comment]
Thanks @lperron for this quick response. 
Using  size = bool_var * fixed_ size does not work since the size has to be an integer for FixedSize intervals. And for regular intervals the end argument can't contain variables.
