### ISSUE TITLE
Annotation error in source code

### ISSUE THREAD

**Issue by jiang-yuan** [google/or-tools#3015]
def AddCumulative(self, intervals, demands, capacity):
        """Adds Cumulative(intervals, demands, capacity).
    This constraint enforces that:
        for all t:
          sum(demands[i]
            if (start(intervals[t]) <= t < end(intervals[t])) and
            (t is present)) <= capacity

I think it should be 

        for all t:
          for all i:
          sum(demands[i]
            if (start(intervals[i]) <= t < end(intervals[i])) and
            (t is present)) <= capacity

Right?

And I do not understand what is the energies in AddCumulativeWithEnergy.  Can anyone give me some example?

**Comment by lperron** [comment]
forget the energies. I removed the code, and reconstruct those automatically.

For the doc, it should be:

```
    for all t:
      sum(demands[i]
        if (start(intervals[i]) <= t < end(intervals[i])) and
        (t is present)) <= capacity
```

meaning that at any time t, the capacity must be respected.
