### ISSUE TITLE
SufficientAssumptionsForInfeasibility in or-tools 9.x doesn't work as 8.x version.

### ISSUE THREAD

**Issue by turtleizzy** [google/or-tools#3017]
Behavior change (bug?): SufficientAssumptionsForInfeasibility in ortools 9.x gives out all assumptions added.

```py
# this piece of code comes from here
# https://github.com/google/or-tools/issues/973#issuecomment-803971511
# need version 8.0 or higher, or definitly not 7.3
from ortools.sat.python import cp_model

if True:
    # Creates the model.
    model = cp_model.CpModel()

    # Creates the variables.
    v0 = model.NewBoolVar("buggyVarIndexToVarProto")
    # model.VarIndexToVarProto(0) always returns the last created variable...?
    v1 = model.NewBoolVar("v1")
    v2 = model.NewBoolVar("v2")
        
    i1 = model.NewIntVar(0, 5, "i1")
    i2 = model.NewIntVar(0, 5, "i2")
        
    # Creates the constraints.
    model.Add(i1+i2 >= 11).OnlyEnforceIf(v1) # can't be satisfied
    model.Add(i1+i2 <= 5).OnlyEnforceIf(v2)
    
    # define assumption literals
    model.Proto().assumptions.append(v1.Index())
    model.Proto().assumptions.append(v2.Index())
    
    # Creates a solver and solves the model.
    solver = cp_model.CpSolver()
    status = solver.Solve(model)
        
    assert status == cp_model.INFEASIBLE
    for var_index in solver.ResponseProto().sufficient_assumptions_for_infeasibility:
        print(var_index, model.VarIndexToVarProto(var_index)) # prints "v1"
```

Output for ortools-8.2.8710
```
1 name: "v1"
domain: 0
domain: 1
```

Output for ortools-9.1.9490 (latest version in pypi as of 2021-12-14)
```
1 name: "v1"
domain: 0
domain: 1

2 name: "v2"
domain: 0
domain: 1
```

**Comment by sschnug** [comment]
Is this really a bug?

Imho:
- if `{v1}` is *sufficient*, `{v1, v2}` is too
- I don't think the solver *guarantees* a *minimal* list
  - I would guess that guaranteeing this leads to a theoretically hard problem (co-NP... and co.?)
- If the solver does not *guarantee* a *minimal* list, it's based on *heuristics*
  - *Heuristics* can lead to observations like those where even a "newer / better" solver can show a less-good result for some specific instantiation of a problem

**Comment by turtleizzy** [comment]
>     * if `{v1}` is _sufficient_, `{v1, v2}` is too

This behavior change (or, bug) was actually discovered on another large project with thousands of assumptions, a proper (might not be *optimally* minimal but at least reasonable) set of infeasible assumptions was returned in the previous (8.2) version, while the *whole* added assumption set was returned in the current version. The output of the previous version was actually helpful for working out the condition that led to infeasibility. 

Despite the fact that returning the whole assumption set is a trivially correct output of sufficient_assumptions_for_infeasibility, I would expect a not-so-trivial output from this API as previous version.

**Comment by fdid-git** [comment]
Sorry for the late response and thanks for the report.

We have currently limited support for this feature, which "work" only in single-thread. Otherwise it just returns all assumptions which as noted is valid, but not really helpful. I think the default number of thread changed in the new version, so you will need to set by hand the number of thread to 1 for it to work.

The "requirement" is documented there:
https://github.com/google/or-tools/blob/stable/ortools/sat/cp_model.proto#L761-L763

We could return an error if you try to solve with assumption and multi-thread, but sometimes it can still be useful for testing and evaluation. The situation will improve when we support this feature better, but there are no such plans in the close future.

**Comment by fdid-git** [comment]
Small improvements: I will log a warning when assumptions are not fully supported, and also revert the default to one thread in case there are assumptions in the request. So hopefully, the situation will be clearer.

**Comment by turtleizzy** [comment]
> We have currently limited support for this feature, which "work" only in single-thread. Otherwise it just returns all assumptions which as noted is valid, but not really helpful. I think the default number of thread changed in the new version, so you will need to set by hand the number of thread to 1 for it to work.

Thank you so much for the reply. For the record, adding 
```
solver.parameters.num_search_workers = 1
```
solved the issue.


> Small improvements: I will log a warning when assumptions are not fully supported, and also revert the default to one thread in case there are assumptions in the request. So hopefully, the situation will be clearer.

That would be very helpful. Thank you.
