### ISSUE TITLE
AddProductEquality and ScaleObjectiveBy removed from C++ API in 9.2

### ISSUE THREAD

**Issue by ankane** [google/or-tools#3024]
Hey, congrats on the latest release. When updating the Ruby library, I noticed `AddProductEquality` and `ScaleObjectiveBy` were removed from `ortools/sat/cp_model.h`, but I didn't see it listed under breaking changes in the release notes. I imagine this was intentional, but would be good to include them (and their alternatives if available) in the release notes.

**Comment by lperron** [comment]
AddProductEquality has been deprecated for quite some time.
ScaleObjectiveBy was removed because we now accept floating point coefficients in the objective.

I will add that to the breaking change.

Thanks

**Comment by ankane** [comment]
Great, super helpful. Thanks!
