### ISSUE TITLE
Third Party Build without SCIP "USING_SCIP=OFF" Error with  lpi_glob.cc

### ISSUE THREAD

**Issue by LukasEDIBER** [google/or-tools#3029]
**What version of OR-Tools and what language are you using?**
Version: stable 9.2
Language: C++
Windows

Hello I am trying to install third party code without SCIP with command "tools\make USE_SCIP=OFF third_party all" in windows 10/ x64 Native Tools Command Prompt. 

I get the error 
"
...
ortools\gen\ortools\linear_solver\lpi_glop.cc(47): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "lpi/lpi.h": No such file or directory
make: *** [makefiles/Makefile.gen.mk:3811: objs/linear_solver/lpi_glop.obj] Error 2
"
In  lpi_glop.cc there are the two inlcudes 
#include "lpi/lpi.h"
#include "scip/pub_message.h"
which give the errores. Second include would result in the same error, becauso no lpi or scip folder exists as I use "USE_SCIP=OFF"
Comment Description of the file also says it belongs to SCIP. 

My question is, why is it still part of the build with "USE_SCIP=OFF" and how can I remove it?

Kind Regards,
Lukas.

**Comment by Mizux** [comment]
Seems you mix Makefile et CMake based build
`ortools\gen\ortools\linear_solver\lpi_glop.cc` this is a path only use by our legacy Makefile based build

and IIRC `-DUSE_SCIP=OFF` is an option only supported by our CMake based build system...
