### ISSUE TITLE
[QUESTION] Vendor Scheduling

### ISSUE THREAD

**Issue by aspencerpsu** [google/or-tools#303]
Is there a way to get into contact with the person who created the vendor_scheduling example? I'm having an extremely rough time comprehending how this problem is a scheduling problem, utilizing the constraint solver for python.

**Comment by lperron** [comment]
I forgot who it was.

I have added a SAT version of the same example. The API is quite close, and I recommend using this solver.

I will close this issue, please reopen it if needed.
