### ISSUE TITLE
PDPTW with OR-Tools 

### ISSUE THREAD

**Issue by Roosjeva** [google/or-tools#3035]
**What language and solver does this apply to?**
Python

**Describe the problem you are trying to solve.**
I'm trying to solve a PDPTW problem already tried I lot of stuf and now trying to use Google-OR tools to solve the problem

**Describe the solution you'd like**
I've found already something on internet and scripts of other persons that seem interesting, the only question I have is if in google OR-tools distance and time windows can be used as constraints or only one of the two? 

**Describe alternatives you've considered**

**Additional context**

**Comment by Mizux** [comment]
yes you can have any number of dimension you want so having distance cosntraint **AND** time (windows) constraint is possible

**Comment by Roosjeva** [comment]
Do you have an example for me?

**Comment by Mizux** [comment]
don't get it, simply merge samples, create a distance dimension then a time dimension...
https://gist.github.com/Mizux/4870e4af09b31dd45b7ac632d1830a73

**Comment by Roosjeva** [comment]
Thank you. 
Is there also the possibility to apply load and unload times at the pick up and delivery location?

**Comment by Mizux** [comment]
yes, anything you want, just **try** and if facing errors then let us know

**Comment by Roosjeva** [comment]
I will TRY , but is there a guide of explanation somewhere?

**Comment by Mizux** [comment]
https://developers.google.com/optimization/routing/dimensions ?

**Comment by Roosjeva** [comment]
Thanks, im trying to solve a problem of 56 nodes and 28 request. But I'm not gaining the optimal solution with help of the local search approach, because I get stuck in a local optimum. Is there a way to get out of the local optimum?
