### ISSUE TITLE
Build (v9.2) unsuccessful from source

### ISSUE THREAD

**Issue by gitAtOffice** [google/or-tools#3036]
**What version of OR-Tools and what language are you using?**
Version: v9.2
Language: C++, Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
SCIP, CPLEX

**What operating system (Linux, Windows, ...) and version?**
ubuntu:16.04

**What did you do?**

     wget https://github.com/google/or-tools/archive/refs/tags/v9.2.tar.gz
     tar xvf v9.2.tar.gz
     cd or-tools-9.2
     cmake -S. -Bbuild -DBUILD_GLOP:BOOL=ON -DBUILD_SCIP:BOOL=ON -DUSE_CPLEX:BOOL=ON -DCPLEX_ROOT=/opt/ibm/ILOG/CPLEX_Studio_Community201/ -DBUILD_PYTHON:BOOL=ON -DPython3_ROOT_DIR=/opt/Python/Python3.10.1/
     cmake --build build
     

**What did you expect to see**
should build all fine.

**What did you see instead?**

	[ 32%] Building CXX object ortools/util/CMakeFiles/ortools_util.dir/file_util.cc.o
	In file included from /home/Projects/softwares/or-tools-9.2/ortools/util/file_util.cc:26:0:
	/home/Projects/softwares/or-tools-9.2/ortools/util/file_util.cc: In function 'absl::lts_20211102::StatusOr<std::__cxx11::basic_string<char> > operations_research::ReadFileToString(absl::lts_20211102::string_view)':
	/home/Projects/softwares/or-tools-9.2/ortools/base/status_macros.h:33:45: error: expected ')' before ';' token
		 if (const ::absl::Status status = (expr); status.ok()) { \
												 ^
	/home/Projects/softwares/or-tools-9.2/ortools/util/file_util.cc:36:3: note: in expansion of macro 'RETURN_IF_ERROR'
	   RETURN_IF_ERROR(file::GetContents(filename, &contents, file::Defaults()));
	   ^
	/home/Projects/softwares/or-tools-9.2/ortools/base/status_macros.h:33:45: error: could not convert 'status' from 'const absl::lts_20211102::Status' to 'bool'
		 if (const ::absl::Status status = (expr); status.ok()) { \
												 ^
	/home/Projects/softwares/or-tools-9.2/ortools/util/file_util.cc:36:3: note: in expansion of macro 'RETURN_IF_ERROR'
	   RETURN_IF_ERROR(file::GetContents(filename, &contents, file::Defaults()));
	   ^
	/home/Projects/softwares/or-tools-9.2/ortools/base/status_macros.h:33:47: error: 'status' was not declared in this scope
		 if (const ::absl::Status status = (expr); status.ok()) { \
												   ^
	/home/Projects/softwares/or-tools-9.2/ortools/util/file_util.cc:36:3: note: in expansion of macro 'RETURN_IF_ERROR'
	   RETURN_IF_ERROR(file::GetContents(filename, &contents, file::Defaults()));
	   ^
	/home/Projects/softwares/or-tools-9.2/ortools/base/status_macros.h:34:7: error: 'else' without a previous 'if'
		 } else /* NOLINT */                                      \
		   ^
	/home/Projects/softwares/or-tools-9.2/ortools/util/file_util.cc:36:3: note: in expansion of macro 'RETURN_IF_ERROR'
	   RETURN_IF_ERROR(file::GetContents(filename, &contents, file::Defaults()));
	   ^
	ortools/util/CMakeFiles/ortools_util.dir/build.make:107: recipe for target 'ortools/util/CMakeFiles/ortools_util.dir/file_util.cc.o' failed
	make[2]: *** [ortools/util/CMakeFiles/ortools_util.dir/file_util.cc.o] Error 1
	CMakeFiles/Makefile2:5969: recipe for target 'ortools/util/CMakeFiles/ortools_util.dir/all' failed
	make[1]: *** [ortools/util/CMakeFiles/ortools_util.dir/all] Error 2
	Makefile:181: recipe for target 'all' failed
	make: *** [all] Error 2

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
Want to install OR-Tools for c++ and python that can use SCIP and CPLEX.
CMake version: cmake-3.19.1

Additionally, want to know what will be the default install location and how to change that?

**Comment by Mizux** [comment]
seems the `if` statement with an initializer is not correctly parsed by your compiler -> two questions:
1. Which compiler are you using ?
2. Did it support C++17 'if statements with initializer' ?

ref: https://en.cppreference.com/w/cpp/language/if#If_statements_with_initializer

**Comment by Mizux** [comment]
We are using the GNUInstallDir CMake built-in module (IIRC should be `/usr/share/...`

You can control the output with `-DCMAKE_INSTALL_PREFIX=install` which will prepend `install/` to the default directories (IIRC relative to build dir aka `build/install/usr/share/...`)
