### ISSUE TITLE
Bug in 2015 MiniZinc challenge

### ISSUE THREAD

**Issue by TheCoolRob** [google/or-tools#304]
Hi,
I thought I would log this here just as an additional test for the upcoming 2017 challenge. 
I noticed the following in the results for the "mapping" "ring_2" instance: Cplex, jaCoP, Chuffed and Choco all managed to prove they had the optimal solution at 1940. Or-tools beat them all at 1640. Assuming the group consensus is correct, this suggests there was an error in the flatzinc layer that year. 
Looking at the commits recently, I think Laurent has completely re-written this layer and probably fixed this but it may be worth confirming before the next challenge (we like or-tools and enjoy watching it do well in this event).
Thanks
Rob

![image001](https://cloud.githubusercontent.com/assets/3518425/22095766/1ac59c7e-de20-11e6-98f2-b39be3a2d4ce.png)

**Comment by Mizux** [comment]
Hi,

Thank you for noticing ! I don't know if it has been fixed since..

**Comment by lperron** [comment]
This is fixed.
