### ISSUE TITLE
[TYPO] Python MIP Sample

### ISSUE THREAD

**Issue by aspencerpsu** [google/or-tools#305]
On link 'Mixed-Integer Programming', there's a typo within the output code solution:

     $ python int_prog_py.html [error]
     Optimal objective value = 23
     Number of variables = 2
     Number of constraints = 2

     x = 3
     y = 2

The line structure should be `python int_prog.py` on [MIP](https://developers.google.com/optimization/mip/integer_opt/#invoke-the-solver) example section

**Comment by antoniomedrano** [comment]
More specifically, here: [https://developers.google.com/optimization/mip/integer_opt#invoke-the-solver](url)

**Comment by Mizux** [comment]
Hi,

Since the page https://developers.google.com/optimization/mip/integer_opt#invoke-the-solver-and-display-the-results has been rewritten, there is no more this error...

BTW thanks for the feedback
