### ISSUE TITLE
I am new to this

### ISSUE THREAD

**Issue by mtoczycki** [google/or-tools#3051]
I am new to or-tools and I am using the vrp to make vehicle runs, I am wondering is there a way for me to make some kind of dimension that when I put a person on a vehicle at a origin, can I put some kind of constraints so that I can say that their person that I have picked up cannot be on the vehicle for more than 60 minutes, as an example.  I am thinking maybe time windows to do this but, is it possible to add a dimension to allow this to work?  I am also using or-tools in java.

**Comment by lperron** [comment]
Please use the discussion and provide more details like code.
