### ISSUE TITLE
Fail to install or-tools on m1 mac

### ISSUE THREAD

**Issue by yymeowyy** [google/or-tools#3055]
I've followed the installation instruction on https://developers.google.com/optimization/install and tried `pip install ortools`; `conda install ortools`;  Could anyone help me with this issue?
![image](https://user-images.githubusercontent.com/50625477/147877219-280161bc-65a9-4fc3-b7a1-9daed70d9fbe.png)

**Comment by lperron** [comment]
Duplicate

**Comment by Mizux** [comment]
see #2722
