### ISSUE TITLE
Bazel target //ortools/base:recordio relies on system-installed zlib

### ISSUE THREAD

**Issue by kgreenek** [google/or-tools#3060]
**What version of OR-Tools and what language are you using?**
Version: master
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux Ubuntu 20.04

**What did you do?**
Build with bazel and deploy to a system without zlib installed.
In my case, I am using the `//ortools/graph:shortestpaths` library.
I am using [rules_docker](https://github.com/bazelbuild/rules_docker) to create an image for my cc_binary.
When I run the container, I get a runtime error, due to the reliance on z.so not being available at runtime.

**What did you expect to see**
Bazel-built libraries (if possible) should not rely on system-installed libraries.

**What did you see instead?**
Runtime error that z.so is not found.

**Anything else we should know about your project / environment**
It looks like `@zlib` is already a WORKSPACE dependency for windows, but on linux it uses the system library instead of the bazel-built one.

**Comment by lperron** [comment]
Why don't you install zlib in your docker?

**Comment by kgreenek** [comment]
I'm using rules_docker with the cc_image rule.

**Comment by kgreenek** [comment]
I don't know the full context for why the system-installed version is used here on linux. But if zlib is managed by bazel, then I don't have to use docker to package it -- it'll be statically linked and I can just package my binary. The cc_image rule is very cool in that it is distroless. It only has the c++ runtime and nothing else, so it is very tiny. But that does mean you can't just system install things easily. You  need to use bazel to manage your dependencies in order to use it out of the box.
