### ISSUE TITLE
error building from source on windows with CPLEX

### ISSUE THREAD

**Issue by qtbgo** [google/or-tools#3061]
**What version of OR-Tools and what language are you using?**
Version: master/v9.2
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
cplex

**What operating system (Linux, Windows, ...) and version?**
windows 10

**What did you do?**
to build from source.
I succeeded in tools\make third_party， but failed in tools\make python.

Here is the error messages:
ortools.lib(common.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(knapsack_solver_python_wrap.obj 中)
ortools.lib(status.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(knapsack_solver_python_wrap.obj 中)
ortools.lib(strutil.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(knapsack_solver_python_wrap.obj 中)
ortools.lib(int128.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(knapsack_solver_python_wrap.obj 中)
ortools.lib(arenastring.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(knapsack_solver_python_wrap.obj 中)
ortools.lib(repeated_ptr_field.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(knapsack_solver_python_wrap.obj 中)
ortools.lib(repeated_field.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(knapsack_solver_python_wrap.obj 中)
ortools.lib(descriptor.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(knapsack_solver_python_wrap.obj 中)
ortools.lib(generated_message_reflection.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(knapsack_solver_python_wrap.obj 中)

It seems that somthing wrong with knapsack solver. Since I do not need knapsack solver, I wonder if I can switch off knapsack solver build?

**Comment by Mizux** [comment]
Makefile and CMake based build currently only build a big fat ortools lib.
Bazel build do not support Python/Java/.Net but only C++ part (and CPLEX is not supported).

IIRC we try to build everything using `/MD`
https://github.com/google/or-tools/blob/2cb85b4eead4c38e1c54b48044f92087cf165bce/makefiles/Makefile.win.mk#L104
Is is possible that xpress is built using `/MT` thus your bug ?
note: i think we use the `stat_mda` (which could stand for static MD release ?)
https://github.com/google/or-tools/blob/2cb85b4eead4c38e1c54b48044f92087cf165bce/makefiles/Makefile.win.mk#L122
 
 Do you have this issue if you disable cplex support ?

**Comment by ktnr** [comment]
I have similar issues when disabling CPLEX (and more third party deps). After build with cmake:
```
cmake .. -DBUILD_DEPS=ON -DUSE_SCIP=OFF -DUSE_COINOR=OFF -DBUILD_SAMPLES=OFF -DBUILD_CXX_SAMPLES=OFF -DBUILD_PYTHON_SAMPLES=OFF -DBUILD_JAVA_SAMPLES=OFF -DBUILD_DOTNET_SAMPLES=OFF  -DBUILD_EXAMPLES=OFF -DBUILD_CXX_EXAMPLES=OFF -DBUILD_PYTHON_EXAMPLES=OFF -DBUILD_JAVA_EXAMPLES=OFF -DBUILD_DOTNET_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=install -DINSTALL_BUILD_DEPS=OFF

cmake --build .

cmake --build . --target install
```
I get many errors of the following category
```
2>ortools.lib(cp_model.obj) : error LNK2038: Konflikt ermittelt für "_ITERATOR_DEBUG_LEVEL": Der Wert "2" stimmt nicht mit dem Wert "0" in ContainerLoadingApplication.obj überein.
2>ortools.lib(cp_model.obj) : error LNK2038: Konflikt ermittelt für "RuntimeLibrary": Der Wert "MDd_DynamicDebug" stimmt nicht mit dem Wert "MD_DynamicRelease" in ContainerLoadingApplication.obj überein.
2>ContainerLoading.lib(file_util.obj) : error LNK2001: Unresolved external symbol ""public: enum absl::lts_20211102::StatusCode __cdecl absl::lts_20211102::Status::code(void)const " (?code@Status@lts_20211102@absl@@QEBA?AW4StatusCode@23@XZ)".
2>ContainerLoading.lib(file_util.obj) : error LNK2001: Unresolved external symbol ""public: bool __cdecl google::protobuf::MessageLite::SerializeToZeroCopyStream(class google::protobuf::io::ZeroCopyOutputStream *)const " (?SerializeToZeroCopyStream@MessageLite@protobuf@google@@QEBA_NPEAVZeroCopyOutputStream@io@23@@Z)".
2>ContainerLoading.lib(file_util.obj) : error LNK2001: Unresolved external symbol "inflate".
```
Also tried to built with `-DCMAKE_BUILD_TYPE=Release` but it yields the same errors.

**Comment by lperron** [comment]
Regrouped into https://github.com/google/or-tools/issues/3558

Please followup there.
