### ISSUE TITLE
Some implementations of LinearExpr operator-() are incorrect

### ISSUE THREAD

**Issue by yima77** [google/or-tools#3082]
**What version of OR-Tools and what language are you using?**
Version: master/v9.2
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Linux (Ubuntu 20.04.1)

**What did you do?**
I used the following call to add a new constraint, which causes the model to be infeasible:

// There is a list of BoolVar (up to 100) maintained in m_hasSecondaryList
auto my_var = m_cpModel.NewIntVar(Domain(0, 100));
m_cpModel.AddEquality(sat::LinearExpr(100) - sat::LinearExpr::Sum(m_hasSecondaryList), my_var);

**What did you expect to see**
I expect the model is feasible.

**What did you see instead?**
The model is infeasible. I believe it is caused by a bug in LinearExpr operator-(), which reverts the subtraction and causes the value to be negative. It then thus causes the model to be infeasible.

I believe the bug (highlighted) is in the following code in cp_model.h

inline LinearExpr operator-(const LinearExpr& lhs, LinearExpr&& rhs) {
  rhs -= lhs;
  **return std::move(rhs);**
}
inline LinearExpr operator-(LinearExpr&& lhs, LinearExpr&& rhs) {
  if (lhs.variables().size() < rhs.variables().size()) {
    rhs -= std::move(lhs);
    **return std::move(rhs);**
  } else {
    lhs -= std::move(rhs);
    return std::move(lhs);
  }
}

This code appears to be a copy/pasted from operator+(). The code in operator+() is fine since A + B always equates B + A. But A - B is most likely not equal to B - A. A possible fix would be to simply replace "return std::move(rhs);" with "return -rhs;".

**Comment by lperron** [comment]
Thanks. Can you look at the code on master to see if it is fixed ?

**Comment by yima77** [comment]
It appears to be so. Sorry, it was my bad. I was looking at the stable branch and thought it was the master. Let me try out the master version.

    On Friday, January 14, 2022, 03:43:34 p.m. EST, Laurent Perron ***@***.***> wrote:  
 
 


Thanks. Can you look at the code on master to see if it is fixed ?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yima77** [comment]
It appears to have been fixed in master branch. I have tried the same implementation of operator-() from the master branch and my model is now feasible.
