### ISSUE TITLE
tsp.cc is in a list of routing examples on page examples/cpp but the file is missing

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#3087]
**What version of OR-Tools and what language are you using?**
Version: master/stable

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing Solver

**What did you do?**
No tsp.cc present in examples/cpp although other routing examples cvrptw.cc and pdptw.cc are in the directory.

**Comment by Mizux** [comment]
which pages ? link welcome

otherwise we do have https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/samples/tsp.cc

**Comment by gregy4** [comment]
There's a link https://github.com/google/or-tools/tree/master/examples/cpp
