### ISSUE TITLE
CpSolverSolutionCallback.StopSearch() => CpSolverStatus.Optimal

### ISSUE THREAD

**Issue by CADBIMDeveloper** [google/or-tools#3089]
**What version of OR-Tools and what language are you using?**
Version: 9.2.9972
Language: C#

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
```cs
public override void OnSolutionCallback()
{
	...
	if ...
	{
		StopSearch();

		return;
	}

	...
}
...
var status = solver.Solve(model, solverCallback); // Optimal if StopSearch was invoked
```

**What did you expect to see**
Status is Unknown or Infeasible or Interrupted (new enum value)

**What did you see instead?**
CpSolverStatus.Optimal

**Comment by lperron** [comment]
does your model have an objective ?

**Comment by CADBIMDeveloper** [comment]
> does your model have an objective ?

Yes

**Comment by lperron** [comment]
Status should then be feasible, as you have found some solution.

**Comment by CADBIMDeveloper** [comment]
I'll try to prepare a mimal reproducible case.

**Comment by lperron** [comment]
because it works flawlessly on my code

**Comment by CADBIMDeveloper** [comment]
Strange thing, in a simple example it also works flawlessly on my side. Give me some time to figure out, please, don't close this issue now.

One more question. Could CP-SAT solver solution violate some constraints by design? 

I've been using or-tools for several years. I added solution validation some time ago (these invalid solutions could came from old or-tools version bug or from my code, I don't know now). Do I still need to have validation like that:
```cs
public override void OnSolutionCallback()
{
	if (token.IsCancellationRequested)
	{
		StopSearch();

		return;
	}

	RaiseSolutionFound();

	RaiseGapChanged();
}

private void RaiseSolutionFound()
{
	var solution = new FeasibleSolution();

	foreach (var variable in variables)
		solution.Add(new SolutionVariable(variable.Name(), variable.Index, SolutionIntegerValue(variable.Index)));

	if (IsFeasibleSolutionValid(solution))
		SolutionFound?.Invoke(this, new FeasibleSolutionFoundEventArgs(solution, ObjectiveValue()));
}

private bool IsFeasibleSolutionValid(ISolverVariables solution) => constraints.All(x => x.Validate(solution));
```
Perhaps I should also validate the solution?
```cs
var status = solver.Solve(model, solverCallback);
```

**Comment by lperron** [comment]
By default, we check all final solutions.
There is a C++ flag to check intermediate solutions too.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by CADBIMDeveloper** [comment]
I'm so sorry for wasting your time. Shame on me :-( With your help I figured out what was going wrong, you've mentioned all key points, thank you! I run multiple solvers in parallel where I build the optimization models in different ways, use some tricks and allow user to select feasible intermediate solution. So what's happening:
![изображение](https://user-images.githubusercontent.com/14212214/150360154-4328bf46-c813-4940-bf35-a62c90457887.png)

Thank you very much!
