### ISSUE TITLE
Slow execution on Virtualized machine

### ISSUE THREAD

**Issue by augustomarinho** [google/or-tools#309]
hello everyone,  I´m using or-tools with Java and I´ve an experience bad when I try to run in Virtualized Machine in Amazon Ec2. When I am running in physical machine (Windows and Linux) I´ve a good experience.
The difference of time for the same problem is so big. When I ran in AMI Ubuntu in Ec2, the time of resolution is +- 20 minutes and when I run in my physical machine, the worst case were 3 minutes. 
Has anyone ever experienced this?

**Comment by lperron** [comment]
I am guessing the VM is in a overloaded machine.

I have not seen this, and I reckon or-tools have nothing to do with it.

Closing the issue. Please reopen if needed.
