### ISSUE TITLE
Numerical instability creating wrong result on Mixed-Integer Linear Program using SCIP solver

### ISSUE THREAD

**Issue by MikaelCacote** [google/or-tools#3098]
**What version of OR-Tools and what language are you using?**
Version: ortools-java 9.2.9972
Language: Java 11

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
SCIP

**What operating system (Linux, Windows, ...) and version?**
Windows 10 Pro 10.0.19044 Build 19044 x64

**What did you do?**
```
        Loader.loadNativeLibraries();
        MPSolver solver = MPSolver.createSolver("SCIP");

        // variables
        MPVariable x = solver.makeIntVar(19, 23, "x");
        MPVariable y = solver.makeIntVar(21, 47, "y");
        MPVariable epsPlus = solver.makeNumVar(0, Double.POSITIVE_INFINITY, "epsPlus");
        MPVariable epsMinus = solver.makeNumVar(0, Double.POSITIVE_INFINITY, "epsMinus");

        // constraints
        MPConstraint constraint1 = solver.makeConstraint(60, 60, "constraint1");
        constraint1.setCoefficient(x, 1);
        constraint1.setCoefficient(y, 1);
        MPConstraint constraint2 = solver.makeConstraint(0, 0, "constraint2");
        constraint2.setCoefficient(x, 1);
        constraint2.setCoefficient(y, -0.499999999);
        constraint2.setCoefficient(epsPlus, -1);
        constraint2.setCoefficient(epsMinus, 1);

        // objective
        MPObjective objective = solver.objective();
        objective.setCoefficient(epsPlus, 1);
        objective.setCoefficient(epsMinus, 1);
        objective.setMinimization();

        // result
        solver.solve();
        System.out.println(String.format("objective=%f, x=%f, y=%f, epsPlus=%f, epsMinus=%f", objective.value(), x.solutionValue(), y.solutionValue(), epsPlus.solutionValue(), epsMinus.solutionValue()));
```

**What did you expect to see**
objective=0.000000, x=20.000000, y=40.000000, epsPlus=0.000000, epsMinus=0.000000

**What did you see instead?**
objective=1.500000, x=19.000000, y=41.000000, epsPlus=0.000000, epsMinus=1.500000

This is failing with 9 decimal digits on a coefficient : `constraint2.setCoefficient(y, -0.499999999);`
But working with 8 decimal digits `constraint2.setCoefficient(y, -0.49999999);`

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
This is not a bug but a feature of MIP solvers. They always work with a tolerance (usually around 1e-6).

**Comment by MikaelCacote** [comment]
Is SCIP's tolerance specified somewhere?
Because it is failing in a non linear way :
- 0.499999990 working
- 0.499999999 failing
- 0.500000000 working
I need to know to how many digits I have to run round every coefficient, so I don't get a bad solution.
Seams to be 1e-8 but is there a documentation ?
Thanks

**Comment by MikaelCacote** [comment]
> This is not a bug but a feature of MIP solvers. They always work with a tolerance (usually around 1e-6).

I would not have thought of tolerance, because it is failing in a non linear way :

```
0.499999990 working : objective=0.000000, x=20.000000, y=40.000000, epsPlus=0.000000, epsMinus=0.000000
0.499999999 failing : objective=1.500000, x=19.000000, y=41.000000, epsPlus=0.000000, epsMinus=1.500000
0.500000000 working : objective=0.000000, x=20.000000, y=40.000000, epsPlus=0.000000, epsMinus=0.000000
```

I need to know to how many digits I have to run round every coefficient, so I don't get a bad solution.
Seams to be 1e-8 but is there a documentation ?

Thanks

**Comment by HappyLoop** [comment]
Tested with CBC and it's working with any number of digit, so it's a bug in SCIP. Can you reopen the ticket ?

**Comment by lperron** [comment]
I can, but you should send the bug to the scip team.
