### ISSUE TITLE
libjniortools.so: failed to map segment from shared object: Operation not permitted

### ISSUE THREAD

**Issue by MikaelCacote** [google/or-tools#3099]
**What version of OR-Tools and what language are you using?**
Version: ortools-java 9.2.9972
Language: Java 11

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
SCIP

**What operating system (Linux, Windows, ...) and version?**
Linux CentOS release 6.10

**What did you do?**
`Loader.loadNativeLibraries();`

**What did you expect to see**
No error

**What did you see instead?**
`java.lang.UnsatisfiedLinkError: /tmp/ortools-java1915802101554471354/ortools-linux-x86-64/libjniortools.so: /tmp/ortools-java1915802101554471354/ortools-linux-x86-64/libjniortools.so: failed to map segment from shared object: Operation not permitted`

Could be that CentOS and other Red Hat related Linux distributions, requires execution permission on the shared libraries.
In ortools-linux-x86-64-9.2.9972.jar provided on Maven, `libjniortools.so` and `libortools.so` have read rights but not execution rights

**Comment by lperron** [comment]
It could also be that it uses a different version of glibc.

**Comment by Mizux** [comment]
try to uncompress the jar archives then `ldd libjniortools.so` does it resolve well ?

**Comment by lperron** [comment]
We do not support centos 6.x anymore. Gcc is to old.
