### ISSUE TITLE
Minimal set of infeasible assumptions doesn't work after version 9.0

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#3102]
**What version of OR-Tools and what language are you using?**
Version: v9.0/v9.1/v9.2
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
I called CpSolver.response().getSufficientAssumptionsForInfeasibilityList() to get a list of infeasible assumptions.

Until version 9.0.9048 I received 4 assumptions, since version 9.1.9490 returned number of infeasible assumptions is equal to total number of assumptions. In my case it is 4207.

**What did you expect to see**
Same functionality as in version 9.0.9048

**What did you see instead?**
Even simple assumption like constant less or equal to higher higher number is infeasible. So it seems that functionality was changed to return all assumptions.

Make sure you include information that can help us debug (full error message, model Proto).

Unfortunatelly I cannot share my code but I found that even very simple example doesn't work.
[TestAssumptions.zip](https://github.com/google/or-tools/files/7935917/TestAssumptions.zip)

**Comment by lperron** [comment]
did you set the number of workers to 1 ?

**Comment by gregy4** [comment]
With one worker it works. I missed information about new default value for number of used workers.

By the way algorithm that calculates number of used workers should consider hyperthreading. For 4 core cpu should be used 4 or 5 cores and not 8 cores.

**Comment by lperron** [comment]
Actually, I am sure 8 workers on a 4 core solver with hyperthread is faster that 4 workers on 4 cores.
