### ISSUE TITLE
Division makes model invalid despite being correct and solvable | EXAMPLE: r=x/y where y in Domain [-10,-1],[1, 20]

### ISSUE THREAD

**Issue by CodeToFreedom** [google/or-tools#3103]
**What version of OR-Tools and what language are you using?**
Version: master/v9.2.9972
Language: Python

**Which solver are you using: CP-SAT

**What operating system (Linux, Windows, ...) and version? Linux Ubuntu 20.04

**What did you do?**
I wanted to compute division result for
r=x/y where  x= 300 and y in Domain [-10,-1],[1, 20]

**What did you expect to see**
Result of x/y

**What did you see instead?**
Error: "The divisor cannot span across zero in constraint: int_div" 
I think the reason for this problem is that the function ValidateIntDivConstraint does not take into consideration that a divisor spanning across zero can also have a Domain where zero is not part of the DomainRange.
My proposition would be: Check wether zero is actually in the divisor-Domain instead of checking wether it spans across zero.

Make sure you include information that can help us debug (full error message, model Proto):
Proto:

variables {
  name: "x"
  domain: 300
  domain: 300
}
variables {
  name: "y"
  domain: -10
  domain: -1
  domain: 1
  domain: 20
}
variables {
  name: "r"
  domain: -30
  domain: 300
}
constraints {
  int_div {
    target {
      vars: 2
      coeffs: 1
    }
    exprs {
      vars: 0
      coeffs: 1
    }
    exprs {
      vars: 1
      coeffs: 1
    }
  }
}
objective {
  vars: 2
  scaling_factor: 1.0
  coeffs: 1
}

**Comment by lperron** [comment]
No. We refuse domains spanning across 0.

**Comment by lperron** [comment]
to be clear. This is not a bug, but a well known limitation. Division is a messy code, and I have yet to see a real application that needs this feature.
