### ISSUE TITLE
C# model feasible in 8.1 and infeasible in 9.2

### ISSUE THREAD

**Issue by JharPaat** [google/or-tools#3104]
Version: "9.2.9972"
Language: C#

CP-SAT, CpSolver

Windows C#

I am trying to update or-tools from 8.1.8487 to 9.2.9979. 
We are using callbacks to stop searching further solution on some of the problems. 
Since method cpSolver.SolveWithSolutionCallback is not available anymore replaced with new CpSolver.Solve() on 9.2 version. 
With 9.2.9979, it is not able to solve problems (which are feasible with 8.1.8497 version) throw infeasible error and callbacks are not also called anymore. 

**What did you expect to see**
Does anyone know how to use callback with CpSolver.Solve() method on 9.2.9972 version ?
Any documentation or examples would be great.

**Comment by lperron** [comment]
if the model is infeasible, by definition callbacks will not be called. So I changed the title of the issue. 
Can you print the log of the solve (log_search_progress:true and send us the model.

**Comment by lperron** [comment]
Can you send me the model ?

**Comment by JharPaat** [comment]
@Iperron, 
Please find the infeasible raw model with version [9.2.9972]. 
Sorry for the delay in reply I was in vacation.
[Infeasible RawModel with 9.2.9972.txt](https://github.com/google/or-tools/files/8081456/Infeasible.RawModel.with.9.2.9972.txt)

**Comment by JharPaat** [comment]
@lperron 
Due to regulatory regulation we must use stable version. 
Is there any plan to release next version soon ?

**Comment by lperron** [comment]
Next week normally
