### ISSUE TITLE
OR-Tools not working with Gurobi 9.5.0

### ISSUE THREAD

**Issue by GrigoriosKapriniotis** [google/or-tools#3110]
**What version of OR-Tools and what language are you using?**
Version:  9.2.9972
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Gurobi 9.5.0

**What operating system (Linux, Windows, ...) and version?**
Windows 10 Enterprise

**What did you do?**
1. Create a simple LP problem
2. Try to run

**What did you expect to see**
A regular run of Gurobi LP solver

**What did you see instead?**
`WARNING: Logging before InitGoogleLogging() is written to STDERR`
`I0202 13:21:00.758865 17160 environment.cc:738] Found the Gurobi library in 'C:\gurobi950\win64\bin\gurobi95.dll.`
`F0202 13:21:00.760135 17160 dynamic_library.h:68] Check failed: function_address != nullptr Error: could not find function GRBsetlogfile in C:\gurobi950\win64\bin\gurobi95.dll`

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
Fixed on master.
