### ISSUE TITLE
Breaking change in version bump from 8.0 to 8.1

### ISSUE THREAD

**Issue by hklarner** [google/or-tools#3115]
Version: [8.0.8283](https://developers.google.com/optimization/support/release_notes#announcing-the-release-of-or-tools-v8.0) and [8.1.8487](https://developers.google.com/optimization/support/release_notes#announcing-the-release-of-or-tools-v8.1)
Language: Python 3.8
Solver: Routing
System: Ubuntu 20.04

When I update to ortools version from 8.0.8283 to 8.1.8487 my code breaks. It is difficult for me to generate a MWE (I am working on it), but it is a vehicle routing problem that uses only a time dimension. I will post a MWE as soon as I have it, but in the mean time I was wondering if you already have a suggestion of what might be the cause from looking at the error message:

```
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
terminate called after throwing an instance of 'std::bad_function_call'
  what():  bad_function_call
Aborted (core dumped)
```

**Comment by lperron** [comment]
why not use 9.2 ? We will not fix 8.1.

**Comment by hklarner** [comment]
I want to use 9.2, yes. I bumped from 7 to 9.2 but noticed the break. 8.1 is the first breaking version for me.

**Comment by Mizux** [comment]
1. Google use internally a [mono repo][1] without a concept of version...
2. OR-Tools is an aggregate of several components (cp-sat, mpsolver etc..) so while some are stable/mature other are in development e.g. a breaking change in MPSolver is irrelevant for routing user... 
3. We don't have the (human) ressource to split the repo per components which would have their own semantic versionning.
4. This is research code without public/private code separation so eveything is virtually public so it is virtually impossible for us to NOT break any API each time a new commit is pushed...
ref: https://xkcd.com/1172/
5. Currently we use major when adding new component or large refactor and minor for regular (breaking change) update...

[1]: https://research.google/pubs/pub45424/ "Why Google Stores Billions of Lines of Code in a Single Repository"

**Comment by hklarner** [comment]
@Mizux thanks for the link, I did not know about this "mono repo".

I opened this issue because I hoped you might have a clue what is going on, given the error message. Like, generally speaking, what could be the cause? Garbage collection maybe?

But yeah, this issue is just a desperate attempt at speeding up my code changes for running v9.2.

**Comment by jmarca** [comment]
This is an old issue, so perhaps not relevant anymore, but one approach is to see what changed using git.

Clone OR Tools on your local machine, then do:

```
git diff v8.0 v8.1 ortools/constraint_solver/routing.*
```

of for 9.3, 
```
git diff v8.0 v9.3 ortools/constraint_solver/routing.*
```

Or similar.  This will give you a clue what changed in the routing solver without having to wade through all the other stuff that changed.

**Comment by Mizux** [comment]
nothing we can do here, beside trying to better advertise breaking changes in release note...
