### ISSUE TITLE
 make python fails on Debian 10 (python:3.8.12-slim-buster base image)

### ISSUE THREAD

**Issue by koljaLanger** [google/or-tools#3145]
**What version of OR-Tools and what language are you using?**
Version: master
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
I am planning to use the CP-SAT solver in Python but got stuck already in the build process

**What operating system (Linux, Windows, ...) and version?**
I am trying to install or-tools in docker container based on the python:3.8.12-slim-buster image.
`cat /etc/os-release` outputs:
```bash
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
```
However, I got this very same error when I tried to build or-tools on my virtualbox running with **ubuntu 20.04 LTS** and also in a container based on the **latest alpine-edge image**.

**What did you do?**
I try to build or-tools from source and use the official installation guide as a reference.
1. Strictly follow the instructions on [the installation page of or-tools](https://developers.google.com/optimization/install/python/source_linux#debian-10_2)
2. Install all prerequisites
3. Run `make third_party`
4. run `make python`

Until and including step 3, installing all third party tools, everything runs without problems.

**What did you expect to see**
I expected a successful build. On my virtualbox running on ubuntu, I actually succeeded in the third or fourth attempt. However, it is hard for me to say why it finished successfully because I did small changes here and there of which I was not sure if they have an impact. For sure, I can say that I had to explicitly install the python extensions.
But for sure, for the apline-edge and the python slim-buster images, I also installed these python extensions. 

**What did you see instead?**
The build process always exits at 96 % with the following error message:

```bash
make[3]: Entering directory '/or-tools/dependencies'
[ 96%] Building CXX object ortools/util/python/CMakeFiles/sorted_interval_list.dir/sorted_interval_list.cc.o
make[3]: Leaving directory '/or-tools/dependencies'
[ 96%] Generate Python 3 protocol buffer for ortools/constraint_solver/assignment.proto
make[3]: Entering directory '/or-tools/dependencies'
[ 96%] Building CXX object ortools/init/python/CMakeFiles/pywrapinit.dir/__/__/__/python/ortools/init/initPYTHON_wrap.cxx.o
protoc-gen-mypy: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--mypy_out: protoc-gen-mypy: Plugin failed with status code 1.
make[3]: *** [CMakeFiles/Pyortools_proto.dir/build.make:90: python/ortools/constraint_solver/assignment_pb2.py] Error 1
make[3]: Leaving directory '/or-tools/dependencies'
make[2]: *** [CMakeFiles/Makefile2:2105: CMakeFiles/Pyortools_proto.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 96%] Building CXX object CMakeFiles/flatzinc.dir/ortools/flatzinc/checker.cc.o
[ 96%] Building CXX object CMakeFiles/flatzinc.dir/ortools/flatzinc/cp_model_fz_solver.cc.o
In file included from /or-tools/dependencies/python/ortools/init/initPYTHON_wrap.cxx:3167:
/or-tools/ortools/base/python-swig.h: In function ‘bool PyObjAs(PyObject*, T*)’:
/or-tools/ortools/base/python-swig.h:59:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
/or-tools/ortools/base/python-swig.h: In function ‘PyObject* PyObjFrom(const T&)’:
/or-tools/ortools/base/python-swig.h:63:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
[ 96%] Linking CXX shared library ../../../lib/_pywrapinit.so
make[3]: Leaving directory '/or-tools/dependencies'
[ 96%] Built target pywrapinit
[ 96%] Building CXX object CMakeFiles/flatzinc.dir/ortools/flatzinc/model.cc.o
[ 96%] Building CXX object CMakeFiles/flatzinc.dir/ortools/flatzinc/parser.cc.o
[ 96%] Linking CXX shared module ../../../lib/sorted_interval_list.cpython-38-x86_64-linux-gnu.so
/or-tools/ortools/flatzinc/model.cc: In member function ‘bool operations_research::fz::Argument::IsArrayOfValues() const’:
/or-tools/ortools/flatzinc/model.cc:668:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
[ 96%] Building CXX object CMakeFiles/flatzinc.dir/ortools/flatzinc/parser.tab.cc.o
[ 96%] Building CXX object CMakeFiles/flatzinc.dir/ortools/flatzinc/parser.yy.cc.o
make[3]: Leaving directory '/or-tools/dependencies'
[ 96%] Built target sorted_interval_list
[ 96%] Building CXX object CMakeFiles/flatzinc.dir/ortools/flatzinc/presolve.cc.o
[ 96%] Linking CXX shared library lib/libflatzinc.so
make[3]: Leaving directory '/or-tools/dependencies'
[ 96%] Built target flatzinc
make[2]: Leaving directory '/or-tools/dependencies'
make[1]: *** [Makefile:166: all] Error 2
make[1]: Leaving directory '/or-tools/dependencies'
make: *** [makefiles/Makefile.cpp.mk:45: lib/libortools.so.9] Error 2
root@406f1f5c37c1:/or-tools# 
```

Let me know, if you need further information

**Comment by lperron** [comment]
Thanks. We need to to document that you need to install mypy-protobuf

**Comment by koljaLanger** [comment]
Many thanks for the fast reply. Apparently, I have mypy-protobuf already installed. Does this makes sense to you?
```bash
root@406f1f5c37c1:/or-tools# which python
/usr/local/bin/python
root@406f1f5c37c1:/or-tools# python --version
Python 3.8.12
root@406f1f5c37c1:/or-tools# python -m pip install mypy-protobuf
Requirement already satisfied: mypy-protobuf in /root/.local/lib/python3.8/site-packages (3.2.0)
Requirement already satisfied: protobuf>=3.19.3 in /root/.local/lib/python3.8/site-packages (from mypy-protobuf) (3.19.4)
Requirement already satisfied: types-protobuf>=3.19.5 in /root/.local/lib/python3.8/site-packages (from mypy-protobuf) (3.19.12)
```

**Comment by lperron** [comment]
make sure that is script is accessible on the path

Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le ven. 25 févr. 2022 à 09:50, koljaLanger ***@***.***> a
écrit :

**Comment by Mizux** [comment]
@koljaLanger you should check using:
```sh
which protoc-gen-mypy
```

ref: https://github.com/nipunn1313/mypy-protobuf/blob/3444fed9ac123c2e0d71d13b440665784a7950fc/setup.cfg#L22-L24

**Comment by koljaLanger** [comment]
Many thanks for your support! I added /root/.local/bin to the path and this solves all problems.

Sorry for the inconvenience
