### ISSUE TITLE
Error when importing ortools.graph.pywrapgraph in python (mach-o, but wrong architecture) 

### ISSUE THREAD

**Issue by Chia25** [google/or-tools#3146]
**What version of OR-Tools and what language are you using?**
Version: ortools==9.2.9972
Language: Python

**What operating system (Linux, Windows, ...) and version?**
MacOS BigSur (11.6.1) with M1 Chip

**What did you do?**

- import ortools
- import ortools.graph.pywrapgraph

**What did you see?**
error when importing ortools.graph.pywrapgraph

` from . import _pywrapgraph
ImportError: dlopen(/Users/temporaryadmin/.pyenv/versions/gfs-data-science-dev/lib/python3.10/site-packages/ortools/graph/_pywrapgraph.so, 2): no suitable image found.  Did find:
        /Users/temporaryadmin/.pyenv/versions/gfs-data-science-dev/lib/python3.10/site-packages/ortools/graph/_pywrapgraph.so: mach-o, but wrong architecture
        /Users/temporaryadmin/.pyenv/versions/3.10.0/envs/gfs-data-science-dev/lib/python3.10/site-packages/ortools/graph/_pywrapgraph.so: mach-o, but wrong architecture`

**Anything else we should know about your project / environment**
Virtual env (python version==3.10.0)

**Comment by lperron** [comment]
duplicate.

**Comment by Chia25** [comment]
Hi @lperron could you please relate this issue to the one considered as duplicate? As I have tried the solution provided here https://github.com/google/or-tools/issues/2722, but still ran into pywrapgraph related error.
