### ISSUE TITLE
Build (v9.2) unsuccessful from source

### ISSUE THREAD

**Issue by jazzbeaux59** [google/or-tools#3153]
**What version of OR-Tools and what language are you using?**
Version: v9.2
Language: C++, Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
SCIP

**What operating system (Linux, Windows, ...) and version?**
CentOS 7

**What did you do?**
1. wget https://github.com/google/or-tools/archive/refs/tags/v9.2.tar.gz
2.  tar xvf v9.2.tar.gz
3.  cd or-tools-9.2
4. cmake -S. -Bbuild -DBUILD_ZLIB:BOOL=ON -DBUILD_absl:BOOL=ON -DBUILD_Protobuf:BOOL=ON -DBUILD_SCIP:BOOL=ON
5. make --build build

**What did you expect to see**
A successful build without errors

**What did you see instead?**
`[ 37%] Building CXX object ortools/util/CMakeFiles/ortools_util.dir/file_util.cc.o
In file included from /home/jenkins/git/conan_packages/ortools/or-tools/or-tools-9.2/ortools/util/file_util.cc:26:0:
/home/jenkins/git/conan_packages/ortools/or-tools/or-tools-9.2/ortools/util/file_util.cc: In function ‘absl::lts_20211102::StatusOr<std::__cxx11::basic_string<char> > operations_research::ReadFileToString(absl::lts_20211102::string_view)’:
/home/jenkins/git/conan_packages/ortools/or-tools/or-tools-9.2/ortools/base/status_macros.h:33:45: error: expected ‘)’ before ‘;’ token
     if (const ::absl::Status status = (expr); status.ok()) { \
                                             ^
/home/jenkins/git/conan_packages/ortools/or-tools/or-tools-9.2/ortools/util/file_util.cc:36:3: note: in expansion of macro ‘RETURN_IF_ERROR’
   RETURN_IF_ERROR(file::GetContents(filename, &contents, file::Defaults()));
   ^~~~~~~~~~~~~~~
/home/jenkins/git/conan_packages/ortools/or-tools/or-tools-9.2/ortools/base/status_macros.h:33:45: error: could not convert ‘status’ from ‘const absl::lts_20211102::Status’ to ‘bool’
     if (const ::absl::Status status = (expr); status.ok()) { \
                                             ^
/home/jenkins/git/conan_packages/ortools/or-tools/or-tools-9.2/ortools/util/file_util.cc:36:3: note: in expansion of macro ‘RETURN_IF_ERROR’
   RETURN_IF_ERROR(file::GetContents(filename, &contents, file::Defaults()));
   ^~~~~~~~~~~~~~~
/home/jenkins/git/conan_packages/ortools/or-tools/or-tools-9.2/ortools/base/status_macros.h:33:47: error: ‘status’ was not declared in this scope
     if (const ::absl::Status status = (expr); status.ok()) { \
                                               ^
/home/jenkins/git/conan_packages/ortools/or-tools/or-tools-9.2/ortools/util/file_util.cc:36:3: note: in expansion of macro ‘RETURN_IF_ERROR’
   RETURN_IF_ERROR(file::GetContents(filename, &contents, file::Defaults()));
   ^~~~~~~~~~~~~~~
/home/jenkins/git/conan_packages/ortools/or-tools/or-tools-9.2/ortools/base/status_macros.h:34:7: error: ‘else’ without a previous ‘if’
     } else /* NOLINT */                                      \
       ^
/home/jenkins/git/conan_packages/ortools/or-tools/or-tools-9.2/ortools/util/file_util.cc:36:3: note: in expansion of macro ‘RETURN_IF_ERROR’
   RETURN_IF_ERROR(file::GetContents(filename, &contents, file::Defaults()));
   ^~~~~~~~~~~~~~~
gmake[2]: *** [ortools/util/CMakeFiles/ortools_util.dir/file_util.cc.o] Error 1
`

**Anything else we should know about your project / environment**
Using gcc 6.3, cmake 3.16.5, conan 1.44 (if that matters)

I have been unsuccessful getting to build with pre-compiled binaries for abseil, protobuf, and zlib. What is necessary to do that?

**Comment by lperron** [comment]
Gcc is too old.

**Comment by Mizux** [comment]
`if (const ::absl::Status status = (expr); status.ok())` this is an initialisation inside an if C++17 ?
https://en.cppreference.com/w/cpp/language/if

For centos-7 please look at
https://github.com/google/or-tools/blob/dd28bdf6e56f1d71dfc33a77657a99c69dc32efb/tools/docker/amd64/centos-7.Dockerfile#L13-L22
or
https://stackoverflow.com/questions/67090507/how-to-install-gcc-g-9-on-centos-7-docker-centos7
