### ISSUE TITLE
OR-Tools not finding Gurobi

### ISSUE THREAD

**Issue by igheorghita** [google/or-tools#3154]
**What version of OR-Tools and what language are you using?**
Version: ortools-9.2.9972
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Gurobi

**What operating system (Linux, Windows, ...) and version?**
macOS Big Sur (version 11.6)

**What did you do?**
Sorry if this isn't a bug, but I couldn't find a satisfactory answer anywhere. I installed ortools with pip and I downloaded Gurobi and I have a license. I can use Gurobi through gurobipy currently, but I'd like to create a solver using `pywraplp.Solver.CreateSolver('GUROBI')`. But when I make a solver this way, it returns `None`. Basically I'm experiencing the same issue as described [here](https://or.stackexchange.com/questions/5513/problem-with-setting-up-gurobi-with-or-tools), but reinstalling doesn't work. I tried setting GUROBI_HOME to `/Library/gurobi951/macos_universal2` but that didn't help. Should I set `GUROBI_HOME` to something else? I read this [page](https://developers.google.com/optimization/install/python/source_linux#gurobi) and it seems to imply that there's nothing I need to do to get them to see each other?

Thank you in advance!

**Comment by lperron** [comment]
following the code, it will search for:   
   potential_paths.push_back(
          absl::StrCat(gurobi_home_from_env, "/lib/libgurobi", lib, ".dylib"));

where lib will be 95.

Is it the case?

**Comment by igheorghita** [comment]
Yes, actually, that file exists (`/Library/gurobi951/macos_universal2/lib/libgurobi95.dylib`). So maybe that's not the issue? 

Thanks for the quick response by the way!

**Comment by lperron** [comment]
Are you ou on Mac M1?

Le jeu. 3 mars 2022, 19:04, Iulia Gheorghita ***@***.***> a
écrit :

**Comment by igheorghita** [comment]
No, Intel

**Comment by igheorghita** [comment]
Previously I was using a jupyter notebook and not getting any error (just `None` for the solver), but when I tried just creating the solver from the command line I got:

```
>>> from ortools.linear_solver import pywraplp
>>> solver = pywraplp.Solver.CreateSolver('GUROBI')
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0303 19:07:31.808168     1 environment.cc:738] Found the Gurobi library in '/Library/gurobi951/macos_universal2/lib/libgurobi95.dylib.
F0303 19:07:31.808506     1 dynamic_library.h:68] Check failed: function_address != nullptr Error: could not find function GRBsetlogfile in /Library/gurobi951/macos_universal2/lib/libgurobi95.dylib
*** Check failure stack trace: ***
zsh: abort      python
```

Any strangely, when I write those two lines:
```python
from ortools.linear_solver import pywraplp

solver = pywraplp.Solver.CreateSolver('GUROBI')
```
in a file in PyCharm and run it I get:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0303 19:14:51.082323     1 linear_solver.cc:616] Support for GUROBI not linked in, or the license was not found.
```

So I'm a bit confused...

**Comment by lperron** [comment]
Sorry, I forgot. known bug. It is fixed in 9.3 released tomorrow or early
next week.

Le jeu. 3 mars 2022, 19:18, Iulia Gheorghita ***@***.***> a
écrit :

**Comment by lperron** [comment]
The import should already be fixed.
I have added the new path to the master branch.

**Comment by igheorghita** [comment]
Great, thanks! I'm curious - which commit fixed it?

**Comment by lperron** [comment]
https://github.com/google/or-tools/commit/6f05109075aac7cf7b1868fdbb997deaf65b8cfc
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le ven. 4 mars 2022 à 02:27, Iulia Gheorghita ***@***.***> a
écrit :
