### ISSUE TITLE
AttributeError: type object 'LinearExpr' has no attribute 'ScalProd'

### ISSUE THREAD

**Issue by mw-point** [google/or-tools#3156]
**What version of OR-Tools and what language are you using?**
Version: 9.3.10459
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Happens on both Windows and Linux

**What did you do?**
Executed python script.

**What did you expect to see**
Script run without issue.

**What did you see instead?**
```
Traceback (most recent call last):
  File "generator_normalized.py", line 1946, in main
    model = buildModel(args=args, cfg=cfg, locid=locid)
  File "generator_normalized.py", line 1648, in buildModel
    model.Add(total_empserviceprefs == cp_model.LinearExpr.ScalProd([sched[k] for k in empserviceprefs_sched_keys], empserviceprefs_weights))
AttributeError: type object 'LinearExpr' has no attribute 'ScalProd'
```

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
Renamed to WeightedSum. We have not yet written the release notes.

**Comment by eric-yehl-ff** [comment]
Glad I found this issue :) the [Reference is still out of date, listing ScalProd](https://developers.google.com/optimization/reference/python/sat/python/cp_model#scalprod)

**Comment by Mizux** [comment]
Up to date ref (Should be re-generated each time a release is here) https://or-tools.github.io/docs/

**Comment by lesshaste** [comment]
ScalProd is still listed at https://developers.google.com/optimization/reference/python/sat/python/cp_model#scalprod

**Comment by lperron** [comment]
indeed.

Won't be solved soon though
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
