### ISSUE TITLE
v9.3 treat_binary_clauses_seperately

### ISSUE THREAD

**Issue by IgnaceBleukx** [google/or-tools#3166]
**What version of OR-Tools and what language are you using?**
Version: 9.3.10459 (pip)
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT
**What operating system (Linux, Windows, ...) and version?**
Ubuntu 20.04.4 LTS

**What did you do?**
Set `treat_binary_clauses_separately` using the following code:
```
from ortools.sat.python import cp_model as ort
solver = ort.CpSolver()
solver.parameters.treat_binary_clauses_separately = False
```

**What did you see instead?**
`AttributeError: 'SatParameters' object has no attribute 'treat_binary_clauses_separately'`

**Anything else we should know about your project / environment**
Running Python 3.9.7

The issue does not occur in version 9.2 of ortools.

**Comment by lperron** [comment]
yes we removed the parameter.
I am surprised you used this.
