### ISSUE TITLE
Presolve with NoOverlap2D

### ISSUE THREAD

**Issue by FelTam** [google/or-tools#3168]
**What version of OR-Tools and what language are you using?**
Version: v9.3.10459
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
Run proto Model_Original.txt with presolve enabled/disabled.
Run proto Model_Scaled.txt with presolve enabled.

**What did you expect to see**
All runs should result in status optimal (feasible, since we do not use an objective function).

**What did you see instead?**
Model_Original.txt with presolve **enabled** results in status infeasible. 
Model_Original.txt with presolve **disabled** results in status optimal. 
If we scale the input, i.e. divide all values by 10 (the resulting values are still integers), Model_Scaled.txt with presolve **enabled** results in status optimal.

See logs for runs on my machine and proto models
[Log_Original_PresolveOff_Feas.txt](https://github.com/google/or-tools/files/8232978/Log_Original_PresolveOff_Feas.txt)
[Log_Original_PresolveOn_Inf.txt](https://github.com/google/or-tools/files/8232979/Log_Original_PresolveOn_Inf.txt)
[Log_Scaled_PresolveOn_Feas_Scaled.txt](https://github.com/google/or-tools/files/8232980/Log_Scaled_PresolveOn_Feas_Scaled.txt)
[Model_Original.txt](https://github.com/google/or-tools/files/8232981/Model_Original.txt)
[Model_Scaled.txt](https://github.com/google/or-tools/files/8232982/Model_Scaled.txt)

**Comment by lperron** [comment]
Thanks for the report.

**Comment by lperron** [comment]
If you have the time, can you try to reduce the model ?

Maybe 3 rectangles, not 15.

**Comment by FelTam** [comment]
Brute force to the rescue. See attached files with 3 rectangles and the same behavior.

[Log_Small_PresolveOff_Feas.txt](https://github.com/google/or-tools/files/8238578/Log_Small_PresolveOff_Feas.txt)
[Log_Small_PresolveOn_Inf.txt](https://github.com/google/or-tools/files/8238579/Log_Small_PresolveOn_Inf.txt)
[Log_Small_Scaled_PresolveOn_Feas.txt](https://github.com/google/or-tools/files/8238580/Log_Small_Scaled_PresolveOn_Feas.txt)
[Model_Small.txt](https://github.com/google/or-tools/files/8238581/Model_Small.txt)
[Model_Small_Scaled.txt](https://github.com/google/or-tools/files/8238582/Model_Small_Scaled.txt)
.

**Comment by lperron** [comment]
Thanks,

If this is not too much trouble, can you try the same process, with the
parameter cp_model_probing_level:0 ?

Your example fails during probing, but not if you disable it.

I will continue trying to understand where this is failing.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by FelTam** [comment]
With probing level 0, the instance in _Model_Small.txt_ is feasible with presolve enabled. However, there are instances that still have the same problem:
[Log_Small_PresolveOff_Probing0_Feas.txt](https://github.com/google/or-tools/files/8243102/Log_Small_PresolveOff_Probing0_Feas.txt)
[Log_Small_PresolveOn_Probing0_Inf.txt](https://github.com/google/or-tools/files/8243103/Log_Small_PresolveOn_Probing0_Inf.txt)
[Model_Small_71.txt](https://github.com/google/or-tools/files/8243104/Model_Small_71.txt)

The problem does not occur when we scale the input data. In the non-scaled variant, there are a lot of "holes" in the ranges because we set placement points before optimization (0, 20, 50, etc.).  So maybe there is a problem in the automatic scaling and recombination. The two discrete points 70 and 80 become 7 and 8 and are combined to form the range [7,8]. But I can only guess.
