### ISSUE TITLE
another crash with v5.1 of flatzinc solver

### ISSUE THREAD

**Issue by edbarton1** [google/or-tools#317]
The attached MZN file (stripped down and no longer encoding a meaningful problem) gets a segmentation fault with either the CP or SAT version of the flatzinc interface in v5.1.  It still crashes after the fix for the a10 crash that I reported earlier.

[a12.zip](https://github.com/google/or-tools/files/750581/a12.zip)

The zip file includes both the CP and SAT versions of the FZN file.

In both cases fz gets a segmentation fault in operations_research::fz::Presolver::PresolveBoolNot.  I am running on Ubuntu 16.04 64-bit.

**Comment by lperron** [comment]
Oh, this slipped through.

I will have a look.

Thanks

**Comment by lperron** [comment]
I pushed the fixed (at last...)

Thanks
