### ISSUE TITLE
PDLP Performance

### ISSUE THREAD

**Issue by brentian** [google/or-tools#3173]
**What version of OR-Tools and what language are you using?**
Version: master/
Language: C++/

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
PDLP
**What operating system (Linux, Windows, ...) and version?**

**What did you do?**

I'm very interested in your recent PDLP features and I test a few instances by compiling examples/solve.cc by adding a new cmake target, then link to `ortools`,`ortools_pdlp`.

As far as I tested, the C++ version seems to be notably slower than the [Julia version](https://github.com/google-research/FirstOrderLp.jl). For example,  for `nug08-3rd`,  the solving time could be like `23.1s` vs. ` 4.11s` (on the same PC).

Is this typical for the current PDLP in Ortools?

**Comment by brentian** [comment]
I run the Julia code like this (with precision 1e-6)

```
julia --project=FirstOrderLp.jl/scripts FirstOrderLp.jl/scripts/solve_qp.jl   --time_sec_limit 1000   --relative_optimality_tol 1e-6 --eps_primal_infeasible 1e-6 --eps_dual_infeasible 1e-6   --method pdhg   --output_dir ../google-or-tools/sample/pdhg_sol_1e-6   --verbosity 4   --redirect_stdio true   --instance_path sample/nug08-3rd.mps
```

To run PDLP in ortools,  I compile `examples/cpp/solve.cc`, then run the command: 

export instance=nug08-3rd; bin/solve --solver=pdlp  --linear_solver_enable_verbose_output --dump_response ../sample/$instance.rep --dump_request ../sample/$instance.req --input ../sample/$instance.mps --dump_format json

The instance `nug08-3rd` is download from Mittelmann's benchmark.  I also tested a few other examples from netlib/miplib,  and got similar results, for example, `savsched1`, `perold`, etc.

**Comment by Mizux** [comment]
https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/ortools/pdlp/solvers.proto#L72-L96

**Comment by brentian** [comment]
Based on my experience, there is no big difference in solving time for PDLP to reach at 1e-6 and 1e-8, at least for the Julia version. So my guess is the parameters used in C++ like primal weight.

**Comment by mlubin** [comment]
Was solve.cc compiled with optimization flags or in debug mode?

**Comment by mlubin** [comment]
Nice! Is it outperforming the Julia code now?

**Comment by mlubin** [comment]
> Since I will do further tests on Netlib and Mittelmann instances, and if you are interested, I can update the status here once I finish.

No need for an exhaustive benchmark, but yes please confirm that you're observing the C++ version to be faster than Julia. You may also be interested in varying the number of threads. Netlib instances are generally too small for threads to help, but some Mittelmann instances may benefit.
