### ISSUE TITLE
Job shop requires minimum number of jobs

### ISSUE THREAD

**Issue by edders51** [google/or-tools#3190]
**What version of OR-Tools and what language are you using?**
Version: master/v9.2
Language: Python

**Which solver are you using - CP-SAT

**What operating system - Windows10

**What did you do?**
Using the flexible job shop with transition time and costs - https://github.com/google/or-tools/blob/stable/examples/contrib/scheduling_with_transitions_sat.py

i have made minimal changes to allow multiple tasks and change the solution print out.

There appears to be a minimum number of jobs required to produce a feasible solution.

This works:
  jobs = [[[(15, 0, 'L1')], [(100, 1, 'L1'), (100, 2, 'L1')], [(15, 0, 'L1')]],
           [[(15, 0, 'L2')], [(100, 1, 'L2'), (100, 2, 'L2')], [(15, 0, 'L2')]],
           [[(15, 0, 'L3')], [(100, 1, 'L3'), (100, 2, 'L3')], [(15, 0, 'L3')]],
           [[(14, 0, 'L4'), (14, 1, 'L4')]],
           [[(14, 0, 'L5'), (15, 2, 'L5')]],
           [[(14, 0, 'L6'), (13, 1, 'L6')]],
           [[(100, 0, 'L7'), (38, 2, 'L7')]]]

If i comment out any of the bottom 4 lines, it returns INFEASIBLE.
If i then add a new job, with zero time -  [[(0,0,'L8'),(0,1,'L8')]]  -it returns a solution again

**What did you expect to see**
Solution
**What did you see instead?**
Infeasible
Make sure you include information that can help us debug (full error message, model Proto).
Proto file included for the Infeasible case.
**Anything else we should know about your project / environment*
[proto.txt](https://github.com/google/or-tools/files/8288257/proto.txt)
[proto.txt](https://github.com/google/or-tools/files/8288260/proto.txt)
[proto.txt](https://github.com/google/or-tools/files/8288271/proto.txt)
*

**Comment by lperron** [comment]
It is because the circuit constraint is not protected against 0 or 1 intervals.

just change the code to:

```
  #----------------------------------------------------------------------------
  # Transition times and transition costs using a circuit constraint.
  switch_literals = []
  for machine_id in all_machines:
    machine_starts = starts_per_machines[machine_id]
    machine_ends = ends_per_machines[machine_id]
    machine_presences = presences_per_machines[machine_id]
    machine_resources = resources_per_machines[machine_id]
    machine_ranks = ranks_per_machines[machine_id]
    intervals = intervals_per_machines[machine_id]
    if len(intervals) > 1:      # New code
      continue                    # Code
```

**Comment by lperron** [comment]
the circuit code makes too many assumptions that are broken by your data

Here is the correct code:

```
  #----------------------------------------------------------------------------
  # Transition times and transition costs using a circuit constraint.
  switch_literals = []
  for machine_id in all_machines:
    machine_starts = starts_per_machines[machine_id]
    machine_ends = ends_per_machines[machine_id]
    machine_presences = presences_per_machines[machine_id]
    machine_resources = resources_per_machines[machine_id]
    machine_ranks = ranks_per_machines[machine_id]
    intervals = intervals_per_machines[machine_id]
    arcs = []
    num_machine_tasks = len(machine_starts)
    all_machine_tasks = range(num_machine_tasks)

    machine_not_used = model.NewBoolVar('machine_not_used')   # New code A
    arcs.append((0, 0, machine_not_used))

    for i in all_machine_tasks:
      # Initial arc from the dummy node (0) to a task.
      start_lit = model.NewBoolVar('')
      arcs.append([0, i + 1, start_lit])
      # If this task is the first, set both rank and start to 0.
      model.Add(machine_ranks[i] == 0).OnlyEnforceIf(start_lit)  
      #  Removed code B
      # Final arc from an arc to the dummy node.
      arcs.append([i + 1, 0, model.NewBoolVar('')])
      # Self arc if the task is not performed.
      arcs.append([i + 1, i + 1, machine_presences[i].Not()])
      model.Add(machine_ranks[i] == -1).OnlyEnforceIf(
          machine_presences[i].Not())
      model.AddImplication(machine_not_used, machine_presences[i].Not())  # New code C

      for j in all_machine_tasks:
        if i == j:
          continue

        lit = model.NewBoolVar('%i follows %i' % (j, i))
        arcs.append([i + 1, j + 1, lit])
        model.AddImplication(lit, machine_presences[i])
        model.AddImplication(lit, machine_presences[j])

        # Maintain rank incrementally.
        model.Add(machine_ranks[j] == machine_ranks[i] + 1).OnlyEnforceIf(lit)

        # Compute the transition time if task j is the successor of task i.
        if machine_resources[i] != machine_resources[j]:
          transition_time = 3
          switch_literals.append(lit)
        else:
          transition_time = 0
        # We add the reified transition to link the literals with the times
        # of the tasks.
        model.Add(machine_starts[j] >= machine_ends[i] +  # Fixed code D
                  transition_time).OnlyEnforceIf(lit)
    if arcs:
        model.AddCircuit(arcs)
```

new code A: a machine can have 0 performed intervals. The circuit must accomodate that.
removed code B: the first task on a machine may be forced to start after 0 if it is not the first task of a job
new code C: link the machine not used with the performed variable of each task
fixed code D: there can be some slack between 2 tasks on a machine. In that case, the == does not hold, you need >=.

**Comment by edders51** [comment]
Thank you for your help
