### ISSUE TITLE
cmake: v9.3 fails to find re2 installed with pkgconfig support only

### ISSUE THREAD

**Issue by yurivict** [google/or-tools#3191]
**What version of OR-Tools and what language are you using?**
Version: 9.3
Language: C++

**What operating system (Linux, Windows, ...) and version?**
FreeBSD

This line:
https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/cmake/deps.cmake#L52-L54
fails to find ```re2``` because it doesn't install cmake files (as of version 20220201).

You need to use pkg_check_modules(re2) instead.

---
EDIT(Mizux)
Todo:

* [x] Add a `Findre2.cmake`
* [x] Add jobs with system wide install package
   * [x] re2 without CMake config but only a pkgconfig/re2.pc (e.g. FreeBSD, Archlinux, Ubuntu)

**Comment by Mizux** [comment]
OK let's wrap it in a FindModule instead so we can first look for a cmake config file then fallback on pkg_check if needed.

e.g.
https://github.com/google/or-tools/blob/stable/cmake/FindEigen3.cmake

**Comment by yurivict** [comment]
This also makes the ```9.3``` release broken because ```re2``` doesn't install any cmake files and this configure check always breaks w/out a known workaround.

**Comment by Mizux** [comment]
you can provide your own FindRe2.cmake module and set the CMAKE_PREFIX_PATH.

**Comment by yurivict** [comment]
Setting ```CMAKE_PREFIX_PATH``` doesn't solve the problem for some reason. And providing FindRe2.cmake is too difficult as a fix for the port.

**Comment by scand1sk** [comment]
I don't know if this is related to this bug, but I can't manage to compile or-tools-9.4 with Debian due to re2.

```
CMake Error at cmake/deps.cmake:69 (message):
  Target re2::re2 not available.
```

I'm not a C/C++ person so I'm very helpless.
I have installed all C re2 related packages I could find.

```
ii  libpcre2-16-0:amd64                      10.40-1                                 amd64        New Perl Compatible Regular Expression Library - 16 bit runtime files
ii  libpcre2-8-0:amd64                       10.40-1                                 amd64        New Perl Compatible Regular Expression Library- 8 bit runtime files
ii  libpcre2-8-0:i386                        10.40-1                                 i386         New Perl Compatible Regular Expression Library- 8 bit runtime files
ii  libre2-9:amd64                           20220601+dfsg-1                         amd64        efficient, principled regular expression library
ii  libre2-dev:amd64                         20220601+dfsg-1                         amd64        efficient, principled regular expression library, development kit
ii  re2c                                     3.0-1                                   amd64        lexer generator for C, C++, Go and Rust
```
