### ISSUE TITLE
Minimising Time window

### ISSUE THREAD

**Issue by petestevens88** [google/or-tools#3198]
I have a problem where a node can be visited every 10 minutes. In order to enforce this I am using the constraint:
```py
routing.solver().Add(abs(time_dimension. CumulVar(dum_node_1)-time_dimension. CumulVar(dum_node_2))>=10)
```
This creates a solution where there is crossover in the time windows. 

eg vehicle one:
index: 26 Time: (922,1800)

vehicle two:
index: 27 Time: (922,1800)

while this is a feasible solution, there is a dependency between the two vehicle routes, which when using more vehicles becomes much more complicated.

is there a way to produce/ print one feasible solution from the solution, rather than all the full possible time windows?

**Comment by Mizux** [comment]
try to add one node (e.g. 26) to the finalizer to minimize it this may fixit.

**Comment by lperron** [comment]
Not an ossue

**Comment by petestevens88** [comment]
I have tried this

routing.AddVariableMinimizedByFinalizer(time_dimension.CumulVar(26))

this results in the one node selected being minimised, however the remaining have the same problem.

in addition I have tried:

        for i in range(data['num_vehicles']):
            routing.AddWeightedVariableMinimizedByFinalizer(time_dimension.CumulVar(routing.End(i)),i)

this slows the solver and means a optimal solution is not found. 

can something similar be used after a solution is found?
