### ISSUE TITLE
[Question][Python][CVRPTW] Constraint vehicle departure time from start depot

### ISSUE THREAD

**Issue by alanbato** [google/or-tools#320]
Hello,
I'm having trouble with a certain constraint in a CVRPTW problem in Python, and I'm looking for some advice on how to implement it.

I have a list of products to deliver to different places, and I have the date in which each is product was/will be finished.
I want to make it so a vehicle doesn't depart from the depot with a product that isn't finished yet.
That is, I want to constraint the start of the route so its greater than the earliest time in which all the products of the route are ready, while still arriving to the destinations by the delivery date.

Any advice or idea would be much appreciated,
Thanks in advance

**Comment by lperron** [comment]
Create a pickup and delivery pair, add the time on the first node.
