### ISSUE TITLE
C++: OR-Tools use a custom absl:string_view based version of RE2

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#3201]
Currently OR-Tools use a custom version of RE2 using `absl::string_view` instead of `re2::StringPiece` unfortunatelly this make difficult for the OSS community to integrate or-tools against a system wide installation of re2...

ref: https://github.com/google/or-tools/blob/stable/patches/re2-2021-11-01.patch

**Comment by Mizux** [comment]
Seems RE2 compiled in C++17 should have support for string_view
see:
https://github.com/google/re2/blob/4c7b561f1f2784fea7a4ac415575c3b080518006/re2/stringpiece.h#L55-L58

Macro name | Feature | Value | Header | Std
-- | -- | -- | -- | --
`__cpp_lib_string_view` | `std::string_view` | 201606L | `<string>`<br>`<string_view>` |( C++17)
`__cpp_lib_string_view` | `ConstexprIterator` | 201803L | `<string>`<br>`<string_view>` | (C++20)

[`std::string_view`](https://en.cppreference.com/w/cpp/string/basic_string_view)
[`<string>`](https://en.cppreference.com/w/cpp/header/string)
[`<string_view>`](https://en.cppreference.com/w/cpp/header/string_view)
[`ConstexprIterator`](https://en.cppreference.com/w/cpp/named_req/ConstexprIterator)

ref: https://en.cppreference.com/w/cpp/feature_test

**Comment by StefanBruens** [comment]
As far as I can see, this has not been merged, nor is there any open PR.

**Comment by Mizux** [comment]
@StefanBruens AFAIK this has been pushed on master...
