### ISSUE TITLE
 v9.3.10497 windows binary make test_cc fails with Visual Studio 2019 v16.11  

### ISSUE THREAD

**Issue by ronsoohyeong** [google/or-tools#3203]
**What version of OR-Tools and what language are you using?**
Version: or-tools_VisualStudio2019-64bit_v9.3.10497
Language: C++ Visual Studio 2019 version 16.11.11

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
any solver in the test_cc

**What operating system (Linux, Windows, ...) and version?**
Windows 10 Enterprise, 1909. Build 18363.2094

**What did you do?**
1. Download and unzip or-tools_flatzinc_VisualStudio2019-64bit_v9.3.10497.zip from  https://developers.google.com/optimization/install/cpp/windows
2. tools\make test_cc
3. it exits after failing simple_lp_program.exe

**What did you expect to see**
Validation succeeds as described in https://developers.google.com/optimization/install/cpp/windows
v8.1.8487 was successful on my computer using c++17 with Visual Studio Community 2019 v16.9.1

**What did you see instead?**
``
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.11
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

E:\lib\or-tools_VisualStudio2019-64bit_v9.3.10497>tools\make.exe test_cc
CC = cl
CC_BIN = C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.EXE
CXX = cl
CXX_BIN = C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.EXE
CXXFLAGS = /std:c++20 /EHsc /MD /nologo /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS -nologo /O2 -DNDEBUG /DPSAPI_VERSION=1 /D__WIN32__ /DNOMINMAX /DWIN32_LEAN_AND_MEAN=1 /D_CRT_SECURE_NO_WARNINGS /DGOOGLE_GLOG_DLL_DECL= /Iinclude\\src\\windows /Iinclude /I. /DUSE_BOP /DUSE_GLOP /DUSE_PDLP /DUSE_CBC /DUSE_CLP /DUSE_SCIP
LDFLAGS = psapi.lib ws2_32.lib
OR_TOOLS_LNK = lib\\ortools.lib

E:/lib/or-tools_VisualStudio2019-64bit_v9.3.10497/tools/make.exe run SOURCE=examples/cpp/simple_knapsack_program.cc
make[1]: Entering directory 'E:/lib/or-tools_VisualStudio2019-64bit_v9.3.10497'
bin\\simple_knapsack_program.exe
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0325 16:49:46.983430 22520 simple_knapsack_program.cc:69] Total value: 847
I0325 16:49:46.986834 22520 simple_knapsack_program.cc:70] Packed items: {2, 3, 6, 13}
I0325 16:49:46.987298 22520 simple_knapsack_program.cc:71] Total weight: 847
I0325 16:49:46.987661 22520 simple_knapsack_program.cc:72] Packed weights: {194, 130, 230, 293}
make[1]: Leaving directory 'E:/lib/or-tools_VisualStudio2019-64bit_v9.3.10497'
E:/lib/or-tools_VisualStudio2019-64bit_v9.3.10497/tools/make.exe run SOURCE=examples/cpp/simple_max_flow_program.cc
make[1]: Entering directory 'E:/lib/or-tools_VisualStudio2019-64bit_v9.3.10497'
bin\\simple_max_flow_program.exe
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0325 16:49:53.843820  3852 simple_max_flow_program.cc:61] Solving the max flow problem failed. Solver status: 0
make[1]: Leaving directory 'E:/lib/or-tools_VisualStudio2019-64bit_v9.3.10497'
E:/lib/or-tools_VisualStudio2019-64bit_v9.3.10497/tools/make.exe run SOURCE=examples/cpp/simple_min_cost_flow_program.cc
make[1]: Entering directory 'E:/lib/or-tools_VisualStudio2019-64bit_v9.3.10497'
bin\\simple_min_cost_flow_program.exe
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0325 16:50:00.639019 21564 simple_min_cost_flow_program.cc:64] Minimum cost flow: 150
I0325 16:50:00.642145 21564 simple_min_cost_flow_program.cc:65]
I0325 16:50:00.642430 21564 simple_min_cost_flow_program.cc:66]  Arc   Flow / Capacity  Cost
I0325 16:50:00.642728 21564 simple_min_cost_flow_program.cc:69] 0 -> 1  12  / 15       48
I0325 16:50:00.643063 21564 simple_min_cost_flow_program.cc:69] 0 -> 2  8  / 8       32
I0325 16:50:00.643351 21564 simple_min_cost_flow_program.cc:69] 1 -> 2  8  / 20       16
I0325 16:50:00.643650 21564 simple_min_cost_flow_program.cc:69] 1 -> 3  4  / 4       8
I0325 16:50:00.644025 21564 simple_min_cost_flow_program.cc:69] 1 -> 4  0  / 10       0
I0325 16:50:00.644323 21564 simple_min_cost_flow_program.cc:69] 2 -> 3  12  / 15       12
I0325 16:50:00.644625 21564 simple_min_cost_flow_program.cc:69] 2 -> 4  4  / 4       12
I0325 16:50:00.644953 21564 simple_min_cost_flow_program.cc:69] 3 -> 4  11  / 20       22
I0325 16:50:00.645222 21564 simple_min_cost_flow_program.cc:69] 4 -> 2  0  / 5       0
make[1]: Leaving directory 'E:/lib/or-tools_VisualStudio2019-64bit_v9.3.10497'
E:/lib/or-tools_VisualStudio2019-64bit_v9.3.10497/tools/make.exe run SOURCE=examples/cpp/simple_lp_program.cc
make[1]: Entering directory 'E:/lib/or-tools_VisualStudio2019-64bit_v9.3.10497'
bin\\simple_lp_program.exe
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0325 16:50:07.299830 20672 simple_lp_program.cc:33] Number of variables = 2
I0325 16:50:07.303096 20672 simple_lp_program.cc:47] Number of constraints = 0
make[1]: *** [Makefile:316: run] Error -1073741819
make[1]: Leaving directory 'E:/lib/or-tools_VisualStudio2019-64bit_v9.3.10497'
make: *** [Makefile:278: test_cc] Error 2

**Anything else we should know about your project / environment**

Microsoft Visual Studio Community 2019 version 16.11.11
VisualStudio.16.Release/16.11.11+32228.343
Microsoft .NET Framework version 4.8.03752

Visual C++ 2019   00435-00000-00000-AA947
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.11.106.23128
ASP.NET and Web Tools 2019

C# tool   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1

IntelliCode expansion   1.0

Microsoft JVM Debugger   1.0

Microsoft MI-Based Debugger   1.0

Microsoft Visual C++ Wizards   1.0

Microsoft Visual Studio VC package 1.0

NuGet package manager 5.11.0

ProjectServicesPackage Extension   1.0

Test Adapter for Boost.Test   1.0

Test Adapter for Google Test   1.0

TypeScript tool   16.0.30526.2002

Visual Basic tool   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1

Visual Studio Code debug adaptor host package 1.0

Visual Studio Tools for CMake   1.0

**Comment by Mizux** [comment]
@ronsoohyeong can you try with the v9.4 ?
link: https://github.com/google/or-tools/releases/download/v9.4/or-tools_cpp_VisualStudio2019-64bit_v9.4.1874.zip

**Comment by Mizux** [comment]
obsolete, no news from user on v9.4 -> closing
