### ISSUE TITLE
linear_solver: Add methods getBInvARow, getBInvRow, getBInvACol, getBInvCol

### ISSUE THREAD

**Issue by mkoeppe** [google/or-tools#3205]
**What language and solver does this apply to?**
Linear Solver

**Describe the problem you are trying to solve.**
Access tableau information of simplex-based solvers

**Describe the solution you'd like**
API similar to https://github.com/coin-or/Osi/blob/master/src/Osi/OsiSolverInterface.hpp#L1985

**Describe alternatives you've considered**

**Additional context**
https://trac.sagemath.org/ticket/33493

**Comment by lperron** [comment]
Sorry, there is no way I can make that in a cross solver portable way.
