### ISSUE TITLE
LinearSumAssignment Python interface constrained by AddArcWithCost time

### ISSUE THREAD

**Issue by kylemcdonald** [google/or-tools#321]
When solving `LinearSumAssignment` problems with or-tools in Python, it always takes longer to add the arcs than it does to solve the problem. 

```Python
from ortools.graph.pywrapgraph import LinearSumAssignment
import numpy

n = 16
max_cost = 10000
costs = numpy.random.randint(0, max_cost, (n, n))

def construct(costs, n):
    lap = LinearSumAssignment()
    for source in range(n):
        for target in range(n):
            lap.AddArcWithCost(source, target, costs[source][target])
    return lap

%time lap = construct(costs, n)
%time solve_status = lap.Solve()
```

For n=16:

```
CPU times: user 297 µs, sys: 88 µs, total: 385 µs
Wall time: 322 µs
CPU times: user 35 µs, sys: 14 µs, total: 49 µs
Wall time: 37 µs
```

For n=512:

```
CPU times: user 207 ms, sys: 650 µs, total: 208 ms
Wall time: 208 ms
CPU times: user 17.8 ms, sys: 234 µs, total: 18 ms
Wall time: 18 ms
```

For n=1024:

```
CPU times: user 894 ms, sys: 9.15 ms, total: 903 ms
Wall time: 903 ms
CPU times: user 91.9 ms, sys: 5.06 ms, total: 96.9 ms
Wall time: 97 ms
```

For n=8192:

```
CPU times: user 55.4 s, sys: 955 ms, total: 56.4 s
Wall time: 56.5 s
CPU times: user 8.42 s, sys: 426 ms, total: 8.85 s
Wall time: 8.99 s
```

This makes the Python wrapper for or-tools a poor choice for problems with a large number of arcs.

I don't know a lot about how the Python code wraps the native code, but I'm wondering if the overhead of Python interacting with native code is the bottleneck. If so, perhaps there's some way to add a method that allows the user to add arcs in a single big batch?

**Comment by joshlk** [comment]
Hi,

I have had a similar issue with `SimpleMinCostFlow`. Adding the network using the `AddArcWithCapacityAndUnitCost` function takes much longer than solving the actual problem.

The current implementation is slow as you have to iterate through each edge one-by-one in Python - Python is terrabile with large for-loops. A better implementation would be to pass a whole block of data at once (i.e. a Numpy array) which is then processed within the C-code.

I have created a prototype which does this using Cython. It sees moderate performance boosts as it still relies on Python objects within the Cython code (mainly `self`). I have created a [notebook](https://gist.github.com/joshlk/6e83d51d808ce30a74f1757d23bd15e5) which outlines and benchmarks this approach.

Here are the results:

| Step          | Current interface | Cython interface |
|---------------|-------------------|------------------|
| AddArc        | 90 s              | 12.4 s           |
| SetNodeSupply | 18.2 s            | 3.39 ms          |
| Solve         | 23.3 s            | 20 s             |
| Flow          | 23.4 s            | 9.07 s           |
| **Total**         | **154.9 s**           | **41.1 s**          |

As the Python interfaces are automatically created using SWIG, a better approach would be to utilise SWIG to automatically create Numpy/vectorised interfaces. [Numpy outlines](https://docs.scipy.org/doc/numpy-1.13.0/reference/swig.interface-file.html#introduction) something simular but I have not looked into the details of it.

This is something I could work on, however,  it would be good to get a gauge of appetite within the project to support this?

@Mizux is this worth pursing?

**Comment by viig99** [comment]
Running into similar issues, i have 4e2 x 1e6 matrix, that needs to be optimised and the python loops take forever, can anyone please help in exploring ways to plug numpy arrays ?

**Comment by viig99** [comment]
Thank you @Mizux for taking this up, could you please provide any pointers i can take a look at to get this to work on [CBC MIP](https://developers.google.com/optimization/assignment/assignment_mip)

**Comment by kylemcdonald** [comment]
Still super interested in this. It makes images like this possible.

![kkanji2-grid-128x128](https://user-images.githubusercontent.com/157106/49839030-1a9e3b80-fd62-11e8-94a0-96e837a5ee45.png)

This is based on finding a matching between an 2d embedding (point cloud) and a 2d grid. The CSA solver behind or-tools is faster than the other options out there, but only if an "AddArcsWithCosts" or similar batch-adding method is introduced.

More info on the picture here https://twitter.com/kcimc/status/1072218450519441413
