### ISSUE TITLE
Memory leak on CP SAT solver

### ISSUE THREAD

**Issue by florianobpsher** [google/or-tools#3212]
**What version of OR-Tools and what language are you using?**
Version: v9.2
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 21.10

**What did you do?**
1. Compile the first example found in https://developers.google.com/optimization/cp/cp_solver#c++_6
2. Launch valgrind on executable with --leak-check=full

**What did you expect to see**
I expected no "possibly lost" memory leak.
I think "still reachable" come from some singleton for logging ? Is it possible to suppress them by by-passing the logger ?

**What did you see instead?**

Here is output of valgrind:

`==142748== Memcheck, a memory error detector
==142748== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==142748== Using Valgrind-3.17.0 and LibVEX; rerun with -h for copyright info
==142748== Command: ./build/bin/unit_test
==142748== 
==142748== 
==142748== HEAP SUMMARY:
==142748==     in use at exit: 229,723 bytes in 2,946 blocks
==142748==   total heap usage: 106,898 allocs, 103,952 frees, 32,687,561 bytes allocated
==142748== 
==142748== 1,760 bytes in 5 blocks are possibly lost in loss record 73 of 104
==142748==    at 0x4845293: operator new[](unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==142748==    by 0x12942DB: absl::lts_20211102::random_internal::(anonymous namespace)::PoolAlignedAlloc() (pool_urbg.cc:198)
==142748==    by 0x12943C8: absl::lts_20211102::random_internal::(anonymous namespace)::InitPoolURBG() (pool_urbg.cc:219)
==142748==    by 0x129537B: decltype (((declval<void (&)()>)())()) absl::lts_20211102::base_internal::Callable::Invoke<void (&)()>(void (&)()) (invoke.h:153)
==142748==    by 0x129535A: decltype (absl::lts_20211102::base_internal::Invoker<void (&)()>::type::Invoke((declval<void (&)()>)())) absl::lts_20211102::base_internal::invoke<void (&)()>(void (&)()) (invoke.h:180)
==142748==    by 0x1295265: void absl::lts_20211102::base_internal::CallOnceImpl<void (&)()>(std::atomic<unsigned int>*, absl::lts_20211102::base_internal::SchedulingMode, void (&)()) (call_once.h:178)
==142748==    by 0x129501A: void absl::lts_20211102::call_once<void (&)()>(absl::lts_20211102::once_flag&, void (&)()) (call_once.h:210)
==142748==    by 0x12944B9: absl::lts_20211102::random_internal::(anonymous namespace)::GetPoolForCurrentThread() (pool_urbg.cc:227)
==142748==    by 0x1294CB1: absl::lts_20211102::random_internal::RandenPool<unsigned int>::Fill(absl::lts_20211102::Span<unsigned int>) (pool_urbg.cc:241)
==142748==    by 0x3B478B: void absl::lts_20211102::random_internal::NonsecureURBGBase<absl::lts_20211102::random_internal::randen_engine<unsigned long> >::Seeder::generate_impl<unsigned int*>(std::integral_constant<bool, true>, unsigned int*, unsigned int*) (nonsecure_base.h:116)
==142748==    by 0x3B2884: void absl::lts_20211102::random_internal::NonsecureURBGBase<absl::lts_20211102::random_internal::randen_engine<unsigned long> >::Seeder::generate<unsigned int*>(unsigned int*, unsigned int*) (nonsecure_base.h:102)
==142748==    by 0x3AF770: void absl::lts_20211102::random_internal::randen_engine<unsigned long>::reseed<absl::lts_20211102::random_internal::NonsecureURBGBase<absl::lts_20211102::random_internal::randen_engine<unsigned long> >::Seeder>(absl::lts_20211102::random_internal::NonsecureURBGBase<absl::lts_20211102::random_internal::randen_engine<unsigned long> >::Seeder&) (randen_engine.h:123)
==142748== 
==142748== LEAK SUMMARY:
==142748==    definitely lost: 0 bytes in 0 blocks
==142748==    indirectly lost: 0 bytes in 0 blocks
==142748==      possibly lost: 1,760 bytes in 5 blocks
==142748==    still reachable: 227,963 bytes in 2,941 blocks
==142748==         suppressed: 0 bytes in 0 blocks
==142748== Reachable blocks (those to which a pointer was found) are not shown.
==142748== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==142748== 
==142748== For lists of detected and suppressed errors, rerun with: -s
==142748== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)`

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
So this is a one time hold object in an or-tools dependency.

So I cannot fix it from or-tools.
