### ISSUE TITLE
TSP problem library import issue ortools.constraint_solver

### ISSUE THREAD

**Issue by Rhinni** [google/or-tools#322]
I am trying to use https://developers.google.com/optimization/routing/tsp/tsp to solve the Traveling Salesman Problem using Python. 

I have installed according to https://developers.google.com/optimization/introduction/installing.html
I have tried both Binary and Source installations for Linux (Ubuntu 14.04). 
With the Binary installation it installs fine and I can perform the example (tsp.py) through commandline just fine (ssh) and get the expected output.

I use Symfony as my framework and tried to call the Python script with shell_exec and a command through a Symfony function (https://symfony.com/doc/current/components/process.html). Executing a random Python script works as expected, however the tsp.py returns 
`<module> from ortools.constraint_solver import pywrapcp ImportError: No module named ortools.constraint_solver`

Full error:
`"The command "python /var/www/html/Symfony/web/python/or-tools-5.1/tsp.py --tsp_size=8 2>&1" failed. Exit Code: 1(General error) Working directory: /var/www/html/Symfony/web Output: ================ Traceback (most recent call last): File "/var/www/html/Symfony/web/python/or-tools-5.1/tsp.py", line 35, in <module> from ortools.constraint_solver import pywrapcp ImportError: No module named ortools.constraint_solver Error Output: ================ " at /var/www/html/Symfony/src/AppBundle/Controller/DefaultController.php line 153 `

Installing through source gave the same result, however I had to perform make python with the following command: make python ADD_PYTHON_INC="-I/usr/lib/python2.7 -I/usr/include/python2.7" otherwise it would give the error `fatal error: 'Python.h' file not found` like in https://github.com/google/or-tools/issues/207#issuecomment-235017750 

I am calling the python script like this: 
`'python ' . $doc_root . '/python/or-tools-5.1/tsp.py 2>&1'`
or
`python python/or-tools-5.1/tsp.py 2>&1`

Do I need to prepend my console command like in https://github.com/google/or-tools/issues/207#issuecomment-235047864 and if so can you give me pointers?

**Comment by Rhinni** [comment]
Running PYTHONPATH=python/or-tools-5.1/src python python/or-tools-5.1/tsp.py 2>&1 seems to get a me a step further,
resulting in:
`Uncaught PHP Exception Symfony\Component\Process\Exception\ProcessFailedException: "The command "PYTHONPATH=python/or-tools-5.1/src python python/or-tools-5.1/tsp.py 2>&1" failed. Exit Code: 1(General error) Working directory: /var/www/html/Symfony/web Output: ================ Traceback (most recent call last): File "python/or-tools-5.1/tsp.py", line 37, in <module> from ortools.constraint_solver import routing_enums_pb2 File "/var/www/html/Symfony/web/python/or-tools-5.1/src/ortools/constraint_solver/../../gen/ortools/constraint_solver/routing_enums_pb2.py", line 6, in <module> from google.protobuf import descriptor as _descriptor ImportError: No module named google.protobuf Error Output: ================ " at /var/www/html/Symfony/src/AppBundle/Controller/DefaultController.php line 154 `

after apt-get install python-protobuf and pip install --upgrade protobuf I get the following error:
`Uncaught PHP Exception Symfony\Component\Process\Exception\ProcessFailedException: "The command "PYTHONPATH=python/or-tools-5.1/src python python/or-tools-5.1/tsp.py 2>&1" failed. Exit Code: 1(General error) Working directory: /var/www/html/Symfony/web Output: ================ Traceback (most recent call last): File "python/or-tools-5.1/tsp.py", line 37, in <module> from ortools.constraint_solver import routing_enums_pb2 File "/var/www/html/Symfony/web/python/or-tools-5.1/src/ortools/constraint_solver/../../gen/ortools/constraint_solver/routing_enums_pb2.py", line 9, in <module> from google.protobuf import symbol_database as _symbol_database File "/usr/local/lib/python2.7/dist-packages/google/protobuf/symbol_database.py", line 165, in <module> _DEFAULT = SymbolDatabase(pool=descriptor_pool.Default()) AttributeError: 'module' object has no attribute 'Default' Error Output: ================ " at /var/www/html/Symfony/src/AppBundle/Controller/DefaultController.php line 154 `

I did pip install protobuf --upgrade
Running libprotoc 2.5.0, setuptools 3.3

**Comment by Rhinni** [comment]
After removing python-protobuf with apt-get remove python-protobuf it suddenly works.

**Comment by sudobum** [comment]
pip uninstall protobuf  helped me

i think brew and pip installs are messing with each other
