### ISSUE TITLE
Idea: use constexpr for int version functions

### ISSUE THREAD

**Issue by ankane** [google/or-tools#3222]
**What language and solver does this apply to?** C++

**Describe the problem you are trying to solve.**

Hi, I'd like to check the OR-Tools version during compilation to make sure it's compatible with the C++ code that uses it.

**Describe the solution you'd like**

Use `constexpr` for `int` version functions

```cpp
constexpr int OrToolsMajorVersion();

constexpr int OrToolsMinorVersion();

constexpr int OrToolsPatchVersion();
```

so users can do

```cpp
static_assert(
  operations_research::OrToolsMajorVersion() == 9 &&
  operations_research::OrToolsMinorVersion() == 3,
  "Incompatible OR-Tools version"
);
```

**Describe alternatives you've considered**

Another option would be to export the `OR_TOOLS_MAJOR`, `OR_TOOLS_MINOR`, and `OR_TOOLS_PATCH` constants.

**Comment by Mizux** [comment]
I would like to use `#cmakedefine` since it would exactly fix this issue BUT we also need to support the bazel build `-_-;`
ref: https://cmake.org/cmake/help/latest/command/configure_file.html#example

**Comment by lperron** [comment]
Interesting link: https://dev.to/davidb31/experimentations-on-bazel-version-txt-g1k
