### ISSUE TITLE
.NET assembly does not have AssemblyInfo

### ISSUE THREAD

**Issue by mwpowellhtx** [google/or-tools#323]
Awhile back I submitted a patch that included an AssemblyInfo. I'm not sure what happened with that, or how/why you (Google?) aren't including it in your build targeting C# and .NET. This is absolutely essential to help with traceability, reporting issues, against what DLL version(s), and so on.

**Comment by mwpowellhtx** [comment]
By way of example, this is what is currently built in the VS2015 archive:

![image](https://cloud.githubusercontent.com/assets/1824187/23271316/0e06cdd0-f9c5-11e6-8576-4e5a2046e637.png)

Whereas, something alone these lines is what I would expect:

![image](https://cloud.githubusercontent.com/assets/1824187/23271336/29f5cd8e-f9c5-11e6-919e-fe8ec746becc.png)

**Comment by mwpowellhtx** [comment]
Include AssemblyInfo in the C# / .NET build, please. Thank you.

**Comment by mwpowellhtx** [comment]
If I were to integrate an *AssemblyInfo* and/or packaging step in the build, it seems to me like I would want to look into the [Makefile.csharp.mk](http://github.com/google/or-tools/blob/master/makefiles/Makefile.csharp.mk) file? The trick would be to connect the file at the same moment(s) when the [or-tools.nuspec](http://github.com/google/or-tools/blob/master/tools/or-tools.nuspec) *VVVV* replacement is done.

**Comment by lperron** [comment]
Hi, 

I do generate a file with all the data.


src/gen/com/google/ortools/CommonAssemblyInfo.cs

with the following content:
Using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
[assembly:System.Reflection.AssemblyTitle( "OR-Tools Assembly" )]
[assembly:System.Reflection.AssemblyDescription( ".NET Assembly for the OR-Tools project" )]
[assembly:System.Reflection.AssemblyConfiguration( "" )]
[assembly:System.Reflection.AssemblyCompany( "Google" )]
[assembly:System.Reflection.AssemblyProduct( "OR-Tools" )]
[assembly:System.Reflection.AssemblyCopyright( "Copyright (c) 2010-2017 Google" )]
[assembly:System.Reflection.AssemblyCulture( "" )]
[assembly:System.Reflection.AssemblyVersion( "5.1.*" )]
[assembly:System.Reflection.AssemblyFileVersion( "5.1.4066" )]
[assembly:System.Reflection.AssemblyInformationalVersion( "OR-Tools 5.1.4066" )]
[assembly:ComVisible(false)]
[assembly:Guid("0a227c4c-8bb3-4db0-808f-55dae227d8c5")]
[assembly:AssemblyKeyFile ("bin/or-tools.snk")]

And this file in included in the assembly during the target:module compilation.
I just don't know what to change line 256-257 of Makefile.csharp.mk?
Do you suggest I would have only one compilation line that includes both .cs and .obj files?

**Comment by mwpowellhtx** [comment]
@lperron That's one possibility I am looking into: i.e. a single *CSC* line with direct *DLL* output, but I am not finding an obvious option that accepts the ``obj`` files is the issue there. And/or how to allow the *AssemblyInfo* to pass through the *CSC MODULE* intermediate file. I was at least able to confirm that a one *CSC* line does allow for *AssemblyInfo* output in the output *DLL*.

I will poke at that a bit more this morning, but unless obvious options jump out that allow for this, at this point I am leaning towards possibly introducing a template *CSPROJ* that can be built. Hopefully that allows the *OBJ* files, and simply build via *MSBUILD*. That should be fairly simple to gather together and can't be any worse, so to speak, than what is there now with no *AssemblyInfo* output.

Tangential to that, I discovered that both the *Flatzinc* and *OrTools* DLL's are sharing the same *AssemblyInfo*. So I am separating some common lines out for both, and isolating unique *GuidAttributes* for each, for example.

While I am there, instead of echoing the content, I am simply copying a template with replaceable parts from the ``tools`` folder, i.e. for version details (i.e. ``VVVV``), as well as a couple of other bits, such as key file (i.e. ``KKKK``), borrowing from the same approach.

Will let you know how that goes. All this will culminate with a *NuGet* package eventually. I may split that process into a couple of make targets. The first being to pack the output(s), including *Flatzinc*. The second to actually publish them.

**Comment by mwpowellhtx** [comment]
Resolved. Could follow up with *FlatZinc* efforts, though.
