### ISSUE TITLE
Segmentation fault when importing tensorflow before ortools

### ISSUE THREAD

**Issue by youchangkim** [google/or-tools#3230]
**What version of OR-Tools and what language are you using?**
Version: v9.3
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
macOS BigSur x86-64

**What did you do?**
1. Download https://github.com/google/or-tools/blob/stable/ortools/sat/samples/simple_sat_program.py
2. Insert `import tensorflow` before `from ortools.sat.python import cp_model`

**What did you expect to see**
```
x = 1
y = 0
z = 0
```

**What did you see instead?**
```
Segmentation fault: 11
```

**Anything else we should know about your project / environment**
1. any tensorflow versions between v2.2.0 and v2.8.0 (available for py38) can reproduce the issue.
2. or-tools v9.2 works fine with any tensorflow versions.
3. importing tensorflow after ortools works fine.

**Comment by lperron** [comment]
It usually means that tf is linked with an older version of protobuf.

What happens if you import tf after or-tools ?

There is nothing we can do about it.

**Comment by Mizux** [comment]
related to #2047

**Comment by youchangkim** [comment]
@Mizux This is slightly different from #2047 because importing packages actually succeeded but segmentation fault happened during `Solve`.

```
Current thread 0x0000000118e9fdc0 (most recent call first):
  File "[REDACTED]/venv/lib/python3.7/site-packages/ortools/sat/python/cp_model.py", line 2168 in Solve
```

**Comment by youchangkim** [comment]
@lperron @Mizux Is it possible to do something similar to these?
https://github.com/protocolbuffers/protobuf/pull/8346
https://github.com/grpc/grpc/pull/24992

**Comment by Mizux** [comment]
For next release v9.4 no, I want to release it ASAP.
For v9.5 we can take a look and see if we can 1) easily reproduce the bug 2) fix it reusing the technique you suggest.

**Comment by lperron** [comment]
Yes, we bumped to 3.9.14.

Nothing in our code has changed

Le ven. 8 avr. 2022, 18:15, Youchang Kim ***@***.***> a
écrit :

**Comment by lperron** [comment]
Works fine now.

**Comment by bear24rw** [comment]
This still seems broken

```bash
% uv run python
Python 3.13.7 (main, Aug 14 2025, 11:12:11) [Clang 17.0.0 (clang-1700.0.13.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ortools
>>> ortools.__version__
'9.15.6755'
>>> import tensorflow
>>> tensorflow.__version__
'2.20.0'
>>> from ortools.sat.python import cp_model
[segfault]
```

**Comment by lperron** [comment]
Yes, it will until tf updates its proto version. AFAIK, this has not
happened in years

Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
