### ISSUE TITLE
Glop solver giving different optimal values in Linux and windows environment but optimal solution is same with slight changes after decimal point.

### ISSUE THREAD

**Issue by mygit-prash** [google/or-tools#3233]
Glop solver giving different optimal values in Linux and windows environment but optimal solution is same with slight changes after decimal point.

How can we achieve same results in both Linux and windows environment while using Glop solver for linear optimization problem. 

Do we need to add any tolerance value to get only one type of solution irrespective of environment and change in order of constraints.

Even changing the order of soft and hard constraints we get different outcome. 

Any solutions for these will be appreciated.

_Originally posted by @mygit-prash in https://github.com/google/or-tools/discussions/3232_

**Comment by lperron** [comment]
You can't. floating point operations are os-specific.

Now, changing the order also changes the numerical operations, and thus changes the optimal solution.
