### ISSUE TITLE
Breaking behavior in NextVar()

### ISSUE THREAD

**Issue by Pol-Zeimet** [google/or-tools#3238]
**What version of OR-Tools and what language are you using?**
Version: 9.3.10497
Language:Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing Solver

**What operating system (Linux, Windows, ...) and version?**
Linux (ubuntu 18.04)

**What did you do?**
1. Use Example from https://developers.google.com/optimization/routing/routing_tasks#setting-start-and-end-locations-for-routes
2.  Got to line 150.
3. Insert the following Code before the solving call to iterate over NextVar of each node:
  ```python
   for i in range(manager.GetNumberOfIndices()):
         print(i)
         print(routing.NextVar(i))
```
5. See error
6. Replace code from step 3 with the following code:
 ```python
   import time
   for i in range(manager.GetNumberOfIndices()):
         print(i)
         time.sleep(1)
         print(routing.NextVar(i))
```
7. Watch how some of the output is now generated until the iterator reaches indices of  **end nodes**
8. See error

**Note**
This seems to be a memory issue. On random occasions the print for NextVar(i) returns unrelated objects such as ' TrueConstraint()' or simply `None' 

**For additional Testing**
1. Repeat the steps from above.
2. Replace line 82 with  `data['ends'] = [1,2,15,16]`
3. You now get the aforementioned effect of NextVar returning `TrueConstraint()` and `FalseConstraint()` for index 17 and 18.
4. Replace lines 82 and 81 with the following code:
 ```py
    data['starts'] = [0,0,0,0]
    data['ends'] = [0,0,0,0]
```
5. The print statements now function as intended.

**Note**
Please note how after the last step, some variables for nextVar are duplicates.
In more complex examples we tested, we noticed this is a reoccuring event. It seems that nextVar(x) will be named NextsX in most cases, but not when it comes to end nodes. End nodes seem to follow a naming convention where for vehicle v in [0,1,2,3] they will be named Nexts[v+1] => [Nexts1, Nexts2, Nexts3, Nexts4] accordingly.
This results in an endnode having the same nextVar Variable an unrelated node.

We know it is the same nextVar Variable not just a duplicated name, since removing or adding a value to the variable using `routing.NextVar(some_index).RemoveValue(some_other_index)` will remove `some_other_index` from both variables.

1. Use Example from https://developers.google.com/optimization/routing/routing_tasks#setting-start-and-end-locations-for-routes
2. . Replace lines 82 and 81 with the following code:
 ```py
    data['starts'] = [0,0,0,0]
    data['ends'] = [0,0,0,0]
```
3. Add the following code in line 150:
    ```py
    print(routing.NextVar(1))
    print(routing.NextVar(20))
    routing.NextVar(1).RemoveValue(10)
    print(routing.NextVar(1))
    print(routing.NextVar(20))
   ```
4. See the following output:
```py
Nexts1(0..23)
Nexts1(0..23)
Nexts1(0..9 11..23)
Nexts1(0..9 11..23)
```

**What did you expect to see**
A print of every index and its possible connections in the graph
Each Index having its own Set of possible connections.

**What did you see instead?**
Segmentation Fault at most times. 
Seemingly Random Memory content(?).
Shared NextVar Variables inbetween nodes

Make sure you include information that can help us debug (full error message, model Proto).

Behavior was tested both in python scripts aswell as in jupyter notebooks

**Comment by Pol-Zeimet** [comment]
The chosen nodes may give the impression that the behavior is to be expected.
I.e. with Endnodes not having NextVar except for cases where a depot is used, since it is a start node at the same time.
However we encountered this issue while using different nodevalues aswell.
For instance with dedicated endnodes for  vehicles having NextVar() variables and them overlapping with variables of other nodes.
The chosen node values are for easy reproduction of errors.

**Comment by Mizux** [comment]
you should have use `routing.NextVar(manager.NodeToIndex(i))` and yes NextVar() is not defined for end **indices**.

see: https://github.com/google/or-tools/issues/2773#issuecomment-923765550

**Comment by lperron** [comment]
And you should not try to reverse engineer the node to index mapping. This may change at any time.

**Comment by Pol-Zeimet** [comment]
Thank you for the quick replies.
I used the terms of node and index interchangeably, which may lead to confusion. I am sorry for that.
However, I am well aware of the difference. As you can see in the report, I am exclusively using the term `index` in my code snippets.
I agree on the meaninglessness of NextVar on End Indices. The issue here is the unexpected behaviour, sometimes triggering a segmentation faul or returning other objects. 
A consistent behaviour, for instance checking internally for IsEnd() and returning None may be an option?
