### ISSUE TITLE
max_time_in_seconds has no effect in a model

### ISSUE THREAD

**Issue by arno-id** [google/or-tools#3243]
**What version of OR-Tools and what language are you using?**
Version: 9.3.10497 (.net 4.6.1 built version as demonstrated by Mizux under the 9.3 release notes)
Language: C# 

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10 

**What did you do?**
Tested a model with extreme amount of intervals with a simple objective. 60s max_time_in_seconds limit.

**What did you expect to see**
On my pc there should be at least one feasible result in a few seconds
#Bound   1.02s best:inf   next:[1,58]     am1_presolve num_literals:58 num_am1:1 increase:1 work_done:1726
#1       1.04s best:1     next:[]         core fixed_bools:0/2434

So at least this solution after the 60s mark

**What did you see instead?**
The optimizer just keeps running:
#Bound   1.02s best:inf   next:[1,58]     am1_presolve num_literals:58 num_am1:1 increase:1 work_done:1726
#1       1.04s best:1     next:[]         core fixed_bools:0/2434
#Done  475.43s core
#Done  475.44s default_lp [hint]
#Done  475.44s fixed [hint]

16 thread run:
Starting Search at 0.91s with 16 workers.
11 full subsolvers: [default_lp, fixed, no_lp, max_lp, core, reduced_costs, pseudo_costs, quick_restart, quick_restart_no_lp, lb_tree_search, probing]
Interleaved subsolvers: [feasibility_pump, rnd_var_lns_default, rnd_cst_lns_default, graph_var_lns_default, graph_cst_lns_default, scheduling_time_window_lns_default, scheduling_random_lns_default, rins_lns_default, rens_lns_default]
#Bound   1.25s best:inf   next:[1,58]     reduced_costs
#1       1.31s best:35    next:[1,34]     no_lp [hint] fixed_bools:0/2505
The thread 0x3a98 has exited with code 0 (0x0).
#2     496.60s best:1     next:[]         core fixed_bools:0/2434

I don't have any other example model, it only happened with this one. I know you are optimizing for 16 threads, and this one done with 7 threads, but this happens with 16 threads aswell. model.ExportToFile and log attached.
[mymodel.pb.zip](https://github.com/google/or-tools/files/8479399/mymodel.pb.zip)
[log.txt](https://github.com/google/or-tools/files/8479420/log.txt)
.

**Comment by lperron** [comment]
With the master branch:

```
Preloading model.
[Symmetry] Graph for symmetry has 40667 nodes and 41125 arcs.
[Symmetry] Symmetry computation done. time: 0.00474769 dtime: 0.00469921
[Symmetry] #generators: 26, average support size: 6.07692
[Symmetry] The model contains 61 duplicate constraints !
[Symmetry] Found orbitope of size 4 x 4
#Bound   0.66s best:inf   next:[0,58]     initial_domain

Starting Search at 0.67s with 8 workers.
6 full subsolvers: [default_lp, fixed, no_lp, max_lp, core, reduced_costs]
Interleaved subsolvers: [feasibility_pump, rnd_var_lns_default, rnd_cst_lns_default, graph_var_lns_default, graph_cst_lns_default, scheduling_time_window_lns_default, scheduling_random_lns_default, rins_lns_default, rens_lns_default]
#Bound   0.75s best:inf   next:[1,58]     am1_presolve num_literals:58 num_am1:1 increase:1 work_done:1726
#1       0.76s best:1     next:[]         core fixed_bools:0/2434
#Done    0.76s core

Sub-solver search statistics:
  'max_lp':
     LP statistics:
       final dimension: 149 rows, 181 columns, 361 entries with magnitude in [8.325504e-03, 1.000000e+00]
       total number of simplex iterations: 34
       num solves: 
         - #OPTIMAL: 1
       managed constraints: 149
       total cuts added: 0 (out of 0 calls)
     LP statistics:
       final dimension: 0 rows, 8 columns, 0 entries with magnitude in [0.000000e+00, 0.000000e+00]
       total number of simplex iterations: 0
       num solves: 
         - #OPTIMAL: 1
       managed constraints: 0
       total cuts added: 0 (out of 0 calls)

  'reduced_costs':
     LP statistics:
       final dimension: 33 rows, 181 columns, 129 entries with magnitude in [1.000000e+00, 1.000000e+00]
       total number of simplex iterations: 34
       num solves: 
         - #OPTIMAL: 2
       managed constraints: 149
       total cuts added: 0 (out of 0 calls)
     LP statistics:
       final dimension: 0 rows, 8 columns, 0 entries with magnitude in [0.000000e+00, 0.000000e+00]
       total number of simplex iterations: 0
       num solves: 
         - #OPTIMAL: 1
       managed constraints: 0
       total cuts added: 0 (out of 0 calls)


Solutions found per subsolver:
  'core': 1

Objective bounds found per subsolver:
  'am1_presolve': 1
  'initial_domain': 1

CpSolverResponse summary:
status: OPTIMAL
objective: 1
best_bound: 1
booleans: 2434
conflicts: 0
branches: 4247
propagations: 100477
integer_propagations: 15144
restarts: 3629
lp_iterations: 0
walltime: 0.816456
usertime: 1.37447
deterministic_time: 0.147377
gap_integral: 0.00205065
```

**Comment by arno-id** [comment]
Thank you for testing!

I double checked everything and it turns out we have a callback which ran for all the 500s. 
Looks like a long running callback disables the  max_time_in_seconds. Good to keep in mind.

After disabling:
`CpSolverResponse summary:
status: OPTIMAL
objective: 1
best_bound: 1
booleans: 2505
conflicts: 0
branches: 4408
propagations: 100387
integer_propagations: 15286
restarts: 3629
lp_iterations: 0
walltime: 1.17913
usertime: 1.17913
deterministic_time: 0.147361
gap_integral: 0.00102913`
