### ISSUE TITLE
Unstable (in 9.2) and infeasible (in 9.3) proto file that is feasible on master

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#3246]
**What version of OR-Tools and what language are you using?**
Version: v9.2/v9.3
Language: C++/Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Debian 11, Windows 10

**What did you do?**
Run attached proto file. The file was generated in version 9.2

**What did you expect to see**
Optimal solution 19.

**What did you see instead?**
In version 9.2 variable optimal value between 19 and 24 on Windows 10.
In version 9.3 infeasible result on Debian.

In master branch from yesterday everything seems right. I have also alternative code without cumulatives that works correctly in version 9.2. It seems to me that a lot happened around this but I didn't find an issue that fixes it. I want to be sure that version 9.4 will work without problems with cumulative constraints. 

Make sure you include information that can help us debug (full error message, model Proto).

[9.2-unstable-proto.zip](https://github.com/google/or-tools/files/8495020/9.2-unstable-proto.zip)

**Comment by lperron** [comment]
Indeed, we fixed a feu bugs.
