### ISSUE TITLE
build failure with CPLEX

### ISSUE THREAD

**Issue by samdoolin** [google/or-tools#3252]
**What version of OR-Tools and what language are you using?**
Version: stable branch
Language: C++/Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CPLEX

**What operating system (Linux, Windows, ...) and version?**
docker linux debian bullseye

**What did you do?**
try to build ortools with CPLEX into a docker image from the stable branch dockerfiles [1](https://github.com/google/or-tools/blob/stable/makefiles/docker/debian/Dockerfile) + [2](https://github.com/google/or-tools/blob/stable/makefiles/docker/debian/python.Dockerfile). CPLEX is installed first and seems to be ok.

**What did you expect to see**
ortools build successfully

**What did you see instead?**
```
# git status
On branch stable
Your branch is up to date with 'origin/stable'.

nothing to commit, working tree clean
# cmake --version
cmake version 3.21.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
# make third_party BUILD_DOTNET=OFF BUILD_JAVA=OFF BUILD_PYTHON=ON USE_CPLEX=ON CPLEX_ROOT=/opt/ibm/ILOG/CPLEX_Studio1210
...
CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0111 is not set: An imported target missing its location property
  fails during generation.  Run "cmake --help-policy CMP0111" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  IMPORTED_LOCATION not set for imported target "CPLEX::CPLEX" configuration
  "Release".
This warning is for project developers.  Use -Wno-dev to suppress it.
...
# cat -n dependencies/CMakeFiles/ortools.dir/build.make | grep CPLEX
   634	lib/libortools.so.9.3.1: CPLEX::CPLEX-NOTFOUND
```

continuing the build with `make python` fails with

```
CMakeFiles/ortools.dir/build.make:634: *** target pattern contains no '%'.  Stop.
```

Some poking around (please ignore if not relevant)...

[cmake docs](https://cmake.org/cmake/help/latest/command/add_library.html):

> The IMPORTED_LOCATION target property … specifies the location of the main library file on disk

So perhaps something like
```
set_target_properties(CPLEX::CPLEX PROPERTIES IMPORTED_LOCATION <path>)
```
is needed in [FindCPLEX.cmake](https://github.com/google/or-tools/blob/stable/cmake/FindCPLEX.cmake)?

It looks like a windows variant of this was removed in 70db1c1ff6aa7de8cea9ee96dd3769e25a3fe89a

**Anything else we should know about your project / environment**

**Comment by fbahr** [comment]
Same here (see [https://groups.google.com/g/or-tools-discuss/c/Yjf_kMN5ZzE](https://groups.google.com/g/or-tools-discuss/c/Yjf_kMN5ZzE)) [except: this is on an up-to-date Manjaro machine and using CPLEX Studio v22.1].

**Comment by pboerr** [comment]
Exactly the same problem here!

**Comment by PixelAmp** [comment]
I was able to work around this by manually setting the target in `cmake/FindCPLEX.cmake` 
`set_property(TARGET CPLEX::CPLEX 
             PROPERTY IMPORTED_LOCATION 
             "${CPLEX_ROOT}/cplex/lib/x86-64_linux/static_pic/libcplex.a")`

**Comment by Robot-1x** [comment]
After the following two steps, it works normally in MacOS environment.
1、Modify  `USE_CPLEX ?= ON` in `or-tools/makefiles/Makefile.cpp.mk`
2、Add `set_property(TARGET CPLEX::CPLEX PROPERTY IMPORTED_LOCATION "${CPLEX_ROOT}/cplex/lib/x86-64_osx/static_pic/libcplex.a")` just at the next line of `if(APPLE)` in `or-tools/cmake/FindCPLEX.cmake`.  And I set `CPLEX_ROOT` in environment paths, it can also be set in `FindCPLEX.cmake`

**Comment by Mizux** [comment]
@Robot-1x for 1) you should be able to pass it in the terminal or as env variable e.g.
```sh
USE_CPLEX=ON make ...
``` 
Make will catch it and since we use `?=` it should take precedence over the default `OFF` value...

**Comment by Mizux** [comment]
I've just integrated feedback from @PixelAmp and @Robot-1x to `main` branch, will see if it help you.

ps: any feedback are welcome

**Comment by lperron** [comment]
No news. Closing. Please reopen if needed.
