### ISSUE TITLE
Problem with Channeling in Scheduling by CP-Sat [Java, Win]

### ISSUE THREAD

**Issue by prissky** [google/or-tools#3253]
**Version:** v9.2
**Language:** Java
**Solver:** CP-SAT
**OS:** Windows

**Steps to reproduce the behavior:**
1. I created model for scheduling problem of few tasks using channeling. Model (attached) turned out to be INFEASIBLE.
2. When channeling the placement of the first task, I set the auxiliary boolVar to true by _model.addEquality(b, 1);_. After this only change, the solver was able to prove optimum (second attached model). Same result was achieved by fixing start of the task.

**What did you expect to see**
1. Initial model to be tractable. 
3. Setting start variable to a desired value not to change infeasibility of the model.

**What did you see instead?**
Surprising behavior. May it be a bug on the scheduling part?
[models.zip](https://github.com/google/or-tools/files/8518661/models.zip)

**Comment by lperron** [comment]
can you try with 9.3 ?

**Comment by prissky** [comment]
Most likely, this behavior persists on both versions. My colleague reproduced it yesterday on master (with Debian 11).
