### ISSUE TITLE
Savings Method not providing solution to A-n32-k5 (CVRP Instance)

### ISSUE THREAD

**Issue by Regista6** [google/or-tools#3254]
Hello,

I am trying to solve the CVRP instance [A-n32-k5](http://vrp.galgos.inf.puc-rio.br/media/com_vrp/instances//A/A-n32-k5.vrp) with the savings method as the first solution strategy. However, no solution is displayed when I run the code.  When I change the first solution strategy to say PATH_CHEAPEST_ARC, I am getting a solution.

Language: Tried in Python (Collab) and C++17 (VS 2022) (Same Result)

OR Tools Version: 9.3 

OS: Windows 

Relevant Code:  

    search_parameters = pywrapcp.DefaultRoutingSearchParameters()
    search_parameters.first_solution_strategy = (routing_enums_pb2.FirstSolutionStrategy.SAVINGS)
    solution = routing.SolveWithParameters(search_parameters)
    print_solution(data, manager, routing, solution)

The same program seems to work for a different instance.

**Comment by lperron** [comment]
These are heuristics. They may not find solutions for different instances, especially with capacity constraints.
