### ISSUE TITLE
Constraints in Assignment Problems with MIP or CPAT

### ISSUE THREAD

**Issue by amitbcp** [google/or-tools#3255]
**What language and solver does this apply to?**
All, Python, Java, C#, C++ / CP-SAT, Routing, Linear Solver

**Describe the problem you are trying to solve.**
I am trying to solve a Linear assignment problem with ```m``` tasks and ```n``` workers, where ```m!=n```
Also some edges are not possible. From the example  : https://developers.google.com/optimization/assignment/assignment_example

My sample cost matrix is as follows : 
```
costs = [
    [90, 80, 75, 70],
    [35, 85, 55, 65],
    [125, 'NA', 90, 95],
    [45, 110, 95, 115],
    [50, 100, 90, 'NA'],
]
```

Can you please recommend the changes while adding archs or constraints.

**Comment by lperron** [comment]
Not a product issue.
