### ISSUE TITLE
CBC solver cannot be stopped by setTimeLimit nor interrupt

### ISSUE THREAD

**Issue by qnhant5010** [google/or-tools#3256]
**What version of OR-Tools and what language are you using?**
Version: 9.3.10497
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CBC
**What operating system (Linux, Windows, ...) and version?**
Windows 10 Professionnal. Version 21H2. Build 19044.1645.

**What did you do?**
Snippet of code:
````java
ResolutionAttempt runInternalSolver(SubConfig subConfig, EntityMapping entityMapping, Parameters params,
                                    String tagLog, MPSolver solver, MPVariable[][][][] assignVar) {
    var solver = MPSolver.createSolver("CBC");
    if (solver == null)
         return ResolutionAttempt.failedWithException(new SolverInitException(approachEnum.name(), input.getId()));
    // Init variables, constraints and objective here
    // The construction code is omitted due to its size
    debug(tagLog, "Attempting to resolve");
    var status = MPSolver.ResultStatus.INFEASIBLE;
    if (subConfig.isDebug())
        solver.enableOutput();
    solver.setNumThreads(subConfig.getNumThreads());
    solver.setTimeLimit(subConfig.getTimeLimit() * 1000L);
    status = solver.solve();
    // Construct the solution
    if (status != MPSolver.ResultStatus.OPTIMAL && status != MPSolver.ResultStatus.FEASIBLE) {
        debug(tagLog, "No solution found");
        // No feasible or optimal solution
        return ResolutionAttempt.failedWithException(new InfeasibleInstanceException());
    } else {
        debug(tagLog, "Constructing the solution");
        AlgorithmSolution solution = constructSolution(entityMapping, params, assignVar);
        if (solution.getStatus() == SolutionStatus.SOLVED)
            return ResolutionAttempt.succeedsWithSolution(solution);
        else
            return ResolutionAttempt.failedWithException(new InfeasibleInstanceException());
    }
}
````
**What did you expect to see**
The solver should stop after the time limit is met or the problem instance is infeasible.
**What did you see instead?**
The process kept going indefinitely, even though the problem instance is infeasible. Seemingly it tries to solve the relaxed problem.
````
Presolve determined that the problem was infeasible with tolerance of 1e-08
Analysis indicates model infeasible or unbounded
````
Now that I look up in the doc at https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/ortools/linear_solver/linear_solver.h ,
````c
  static bool SolverTypeSupportsInterruption(
      const MPModelRequest::SolverType solver) {
    // Interruption requires that MPSolver::InterruptSolve is supported for the
    // underlying solver. Interrupting requests using SCIP is also not supported
    // as of 2021/08/23, since InterruptSolve is not go/thread-safe
    // for SCIP (see e.g. cl/350545631 for details).
    return solver == MPModelRequest::GLOP_LINEAR_PROGRAMMING ||
           solver == MPModelRequest::GUROBI_LINEAR_PROGRAMMING ||
           solver == MPModelRequest::GUROBI_MIXED_INTEGER_PROGRAMMING ||
           solver == MPModelRequest::SAT_INTEGER_PROGRAMMING ||
           solver == MPModelRequest::PDLP_LINEAR_PROGRAMMING;
  }
````
I can see that CBC solver does not support the time limit. I tried to stop the solver via `MPSolver.interruptSolve()` but to no avail. I also tried to stop the `ExecutorService` of the process through Java but the process did not stop anyway.

Switching to `SAT` solver seems to solve the problem, but it is a pity because `CBC` solver performs much better in my test cases.

**Anything else we should know about your project / environment**
I import Google OR-tools using gradle: https://mvnrepository.com/artifact/com.google.ortools/ortools-java

**Comment by lperron** [comment]
we have no time to extend the CBC interface. It is too complex to use.
Does your problem has continuous variables ?

**Comment by qnhant5010** [comment]
Yes, it has simultaneously boolean, integer and continuous variables.

**Comment by qnhant5010** [comment]
Apparently the method `SetSolverSpecificParametersAsString` is not implemented in the interface of CBC, whereas the others have this method. It might help passing some parameters like `timeLimit` inside the CBC solver (denoted as `seconds`).

**Comment by abeham** [comment]
Hmm, my observation is that SetTimeLimit works with CBC as it does with other solvers (SCIP, Gurobi) using the dotnet interface. Even though I don't see this in the commands being passed. I also assume CBC isn't compiled with CBC_THREAD on windows and thus no support for SetNumThreads:

> Welcome to the CBC MILP Solver 
> Version: 2.10.7 
> Build Date: May 12 2022 
> 
> command line - cbc -threads 4 -solve -quit (default strategy 1)
> No match for threads - ? for list of commands
> No match for 4 - ? for list of commands

With a build of or-tools from the tip of master (9.4.177) just yesterday.

**Comment by ddotsdot** [comment]
Using current or-tools release 9.4.1874 (Java) I observe the behaviour of CBC as described by @qnhant5010. However, in my case this behaviour appears to depend directly on the number of seconds passed to `setTimeLimit`. That means with lower time limits (e.g. less than 20 secs) CBC interrupts solution process as expected, but it does not when time limits are higher (e.g. greater than 25 secs). In one case, CBC ignored the time limit of 25 secs and stopped after 543 secs with a feasible solution.

Highly appreciating any ideas for working around or fix this major issue... :confused:

**Comment by lperron** [comment]
We will not work on CBC, and drop it as soon as SCIP is released with the new license.
