### ISSUE TITLE
Building third_party fails for VS2015

### ISSUE THREAD

**Issue by mwpowellhtx** [google/or-tools#326]
It's failing: see attached log file. This is a re-run after the initial attempt. Hopefully highlighting just the errors that are relevant.

```
tools\mkdir.exe -p dependencies\install\lib\coin
tools\mkdir.exe -p dependencies\install\include\coin
copy dependencies\sources\zlib-1.2.11\zlib.h dependencies\install\include
        1 file(s) copied.
cd dependencies/sources/gflags-master && \
  cmake -D CMAKE_INSTALL_PREFIX=..\..\install \
           -D CMAKE_BUILD_TYPE=Release \
           -G "NMake Makefiles" \
           .
-- Configuring done
-- Generating done
-- Build files have been written to: G:/Source/Spikes/Google/or-tools-google/dependencies/sources/gflags-master
cd dependencies/sources/gflags-master && nmake install
[ 50%] Built target gflags_nothreads_static
[100%] Built target gflags_static
Install the project...
-- Install configuration: "Release"
-- Up-to-date: G:/Source/Spikes/Google/or-tools-google/dependencies/install/Lib/gflags_static.lib
-- Up-to-date: G:/Source/Spikes/Google/or-tools-google/dependencies/install/Lib/gflags_nothreads_static.lib
-- Up-to-date: G:/Source/Spikes/Google/or-tools-google/dependencies/install/Include/gflags/gflags.h
-- Up-to-date: G:/Source/Spikes/Google/or-tools-google/dependencies/install/Include/gflags/gflags_declare.h
-- Up-to-date: G:/Source/Spikes/Google/or-tools-google/dependencies/install/Include/gflags/gflags_completions.h
-- Up-to-date: G:/Source/Spikes/Google/or-tools-google/dependencies/install/Include/gflags/gflags_gflags.h
-- Up-to-date: G:/Source/Spikes/Google/or-tools-google/dependencies/install/CMake/gflags-config.cmake
-- Up-to-date: G:/Source/Spikes/Google/or-tools-google/dependencies/install/CMake/gflags-config-version.cmake
-- Up-to-date: G:/Source/Spikes/Google/or-tools-google/dependencies/install/CMake/gflags-targets.cmake
-- Installing: G:/Source/Spikes/Google/or-tools-google/dependencies/install/CMake/gflags-targets-release.cmake
-- Register:   Added HKEY_CURRENT_USER\Software\Kitware\CMake\Packages\gflags\9db9e88568767dcb2b741244a999fc09
tools\touch.exe dependencies/install/lib/gflags_static.lib
tools\wget -P dependencies\archives http://prdownloads.sourceforge.net/swig/swigwin-3.0.10.zip || (@echo wget failed to dowload http://prdownloads.sourceforge.net/swig/swigwin-3.0.10.zip, try running 'tools\wget -P dependencies\archives --no-check-certificate http://prdownloads.sourceforge.net/swig/swigwin-3.0.10.zip' then rerun 'make third_party' && exit 1)
wget failed to dowload http://prdownloads.sourceforge.net/swig/swigwin-3.0.10.zip, try running 'tools\wget -P dependencies\archives --no-check-certificate http://prdownloads.sourceforge.net/swig/swigwin-3.0.10.zip' then rerun 'make third_party' 
```

**Comment by mwpowellhtx** [comment]
Perhaps another question worth asking is this: how much of ``third_party`` is necessary in order for the rest of the build, i.e. ``make csharp`` to work?

**Comment by mwpowellhtx** [comment]
I continue with the next step, and again I get errors:

```
make csharp

...\\or-tools\\dependencies\\install\\swigwin-3.0.10\\swig.exe  -DUSE_CLP -DUSE_CBC    -DUSE_GLOP -DUSE_BOP -Isrc -c++ -csharp -o src\\gen\\linear_solver\\linear_solver_csharp_wrap.cc -module operations_research_linear_solver -namespace Google.OrTools.LinearSolver -dllimport "Google.OrTools.dll" -outdir src\\gen\\com\\google\\ortools\\linearsolver src/linear_solver\\csharp\\linear_solver.swig

'python' is not recognized as an internal or external command, operable program or batch file.
'git' is not recognized as an internal or external command, operable program or batch file.
process_begin: CreateProcess((null), git log --pretty=format:%h -n 1, ...) failed.
The filename, directory name, or volume label syntax is incorrect.
'\python' is not recognized as an internal or external command, operable program or batch file.
'\python' is not recognized as an internal or external command, operable program or batch file.
The system cannot find the path specified.
make: *** [src\\gen/linear_solver/linear_solver_csharp_wrap.cc] Error 1
```

So it would seem that at least ``python`` and/or ``git`` is necessary?

I have ``Git`` installed, but as far as I know it is the Linux command prompt only. Not sure about Python; I think so, but I'd have to double check. I do not see that listed in the [requirements](http://developers.google.com/optimization/introduction/installing.html#requirements_windows).

Anything else we should know about?

Thank you...

**Comment by lperron** [comment]
Hi,

You need git to be accessible from the command prompt.
We need it to get release info, and thus versions for libraries.

The python errors are here because we try to detect the python version.
Most of our support on python is based to issues with python dependencies
(conflicting protobuf packages, missing six package...). So we make an
extra effort to query and check everything.
Unfortunately, if python is not installed, it breaks.

I have pushed the --no-check-certificate on github.
I just make a fresh github clone on windows, and ran make third_party. I
went flawlessly.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-02-27 2:12 GMT+01:00 Michael Powell <notifications@github.com>:

**Comment by mwpowellhtx** [comment]
@lperron Thanks very much for the follow up.

Re: ``git``, very well. I will need to reinstall, probably.

Re: ``python``, fair enough. Which version(s)? Or does it matter? I'm not well versed in the ``python`` environment apart from there being a ``2.x`` versus ``3.x`` breakage, at the time? Probably obsolete information by this point.

Will follow up as needed.

**Comment by mwpowellhtx** [comment]
I got past the ``git`` issue. Still the ``python`` issue is an open question. Thanks!

**Comment by mwpowellhtx** [comment]
@lperron Which version(s) of ``Python``? Thank you...

**Comment by ilo2008** [comment]
Hello,

As the last line of the error says, try running `tools\wget -P dependencies\archives --no-check-certificate http://prdownloads.sourceforge.net/swig/swigwin-3.0.10.zip`, then rerun `make third_party`.

I hope this helps.

Driss

**Comment by mwpowellhtx** [comment]
On Mon, Feb 27, 2017 at 5:44 AM, lperron <notifications@github.com> wrote:

> Hi,
>
> You need git to be accessible from the command prompt.
> We need it to get release info, and thus versions for libraries.
>
> The python errors are here because we try to detect the python version.
> Most of our support on python is based to issues with python dependencies
> (conflicting protobuf packages, missing six package...). So we make an
> extra effort to query and check everything.
> Unfortunately, if python is not installed, it breaks.


I installed Python 3.6.0 (64-bit) and included that in my PATH. Still
getting the error(s). I even set WINDOWS_PATH_TO_PYTHON, still errors.

The filename, directory name, or volume label syntax is incorrect.
'\python' is not recognized as an internal or external command, operable
program or batch file.
'\python' is not recognized as an internal or external command, operable
program or batch file.
tools\mkdir.exe -p dependencies\install\lib\coin
tools\mkdir.exe -p dependencies\install\include
copy dependencies\sources\zlib-1.2.11\zlib.h dependencies\install\include
        1 file(s) copied.
cd dependencies/sources/gflags-master && \
  cmake -D CMAKE_INSTALL_PREFIX=..\..\install \
           -D CMAKE_BUILD_TYPE=Release \
           -G "NMake Makefiles" \
           .
-- Configuring done
-- Generating done
-- Build files have been written to:
G:/Source/Spikes/Google/or-tools-google/dependencies/sources/gflags-master
cd dependencies/sources/gflags-master && nmake install

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

[ 50%] Built target gflags_static
[100%] Built target gflags_nothreads_static
Install the project...
-- Install configuration: "Release"
-- Installing:
G:/Source/Spikes/Google/or-tools-google/dependencies/install/Lib/gflags_static.lib
-- Up-to-date:
G:/Source/Spikes/Google/or-tools-google/dependencies/install/Lib/gflags_nothreads_static.lib
-- Up-to-date:
G:/Source/Spikes/Google/or-tools-google/dependencies/install/Include/gflags/gflags.h
-- Up-to-date:
G:/Source/Spikes/Google/or-tools-google/dependencies/install/Include/gflags/gflags_declare.h
-- Up-to-date:
G:/Source/Spikes/Google/or-tools-google/dependencies/install/Include/gflags/gflags_completions.h
-- Up-to-date:
G:/Source/Spikes/Google/or-tools-google/dependencies/install/Include/gflags/gflags_gflags.h
-- Up-to-date:
G:/Source/Spikes/Google/or-tools-google/dependencies/install/CMake/gflags-config.cmake
-- Up-to-date:
G:/Source/Spikes/Google/or-tools-google/dependencies/install/CMake/gflags-config-version.cmake
-- Up-to-date:
G:/Source/Spikes/Google/or-tools-google/dependencies/install/CMake/gflags-targets.cmake
-- Installing:
G:/Source/Spikes/Google/or-tools-google/dependencies/install/CMake/gflags-targets-release.cmake
-- Register:   Added
HKEY_CURRENT_USER\Software\Kitware\CMake\Packages\gflags\9db9e88568767dcb2b741244a999fc09
tools\touch.exe dependencies/install/lib/gflags_static.lib

**Comment by ilo2008** [comment]
Try removing `Makefile.local`. It will be regenerated again when you run `make third_party`, and it will detect the right path to python.

**Comment by mwpowellhtx** [comment]
Okay, I believe the make request succeeded this time.

I re-cloned from source origin and re-ran make. No obvious errors this
time, Python paths appear to be correct, third party gets are a bit hard to
follow, but I think they succeeded.

Attached Command Prompt on screen log as well as off screen log.

**Comment by mwpowellhtx** [comment]
@lperron Natural follow up question: is the SWIG output also committed as "source" in the repository?

**Comment by mwpowellhtx** [comment]
Then I followed on with ``make csharp``, with the [attached output](https://github.com/google/or-tools/files/809283/make_csharp.zip).

Now, a ``Google.OrTools.DLL`` did land in the ``bin`` folder, however, not without a couple of suspect reports.

Several errors such as this were reported, which is at least a yellow flag:

```
src\constraint_solver\constraint_solver.h(2268) : Warning 845: Unmanaged code contains a call to a SWIG_CSharpSetPendingException method and C# code does not handle pending exceptions via the canthrow attribute.
```

One solution file could not be found:

```
Could Not Find G:\Source\Spikes\Google\or-tools-test\examples\csharp\Csharp_examples.sln
```

Possible SWIG confusion in one of the types:

```
src\constraint_solver\csharp\routing.swig(263) : Warning 516: Overloaded methodoperations_research::RoutingModel::AddVectorDimension(std::vector< int64 > const &,int64,bool,std::string const &) ignored, src\constraint_solver\routing.h(439) : Warning 516: using operations_research::RoutingModel::AddVectorDimension(std::vector< int64 >,int64,bool,std::string const &) instead.
```

If I were to integrate an AssemblyInfo and/or packaging step in the build, it seems to me like I would want to look into the [Makefile.csharp.mk](http://github.com/google/or-tools/blob/master/makefiles/Makefile.python.mk) file?

For my purposes, I think this is a "successful" build, with potentially a couple of follow up items for you. But I could be wrong, pending feedback from the log files.

**Comment by mwpowellhtx** [comment]
Resolved.

**Comment by lperron** [comment]
No it is not.
It is generated in src/gen/...

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-03-01 0:05 GMT+01:00 Michael Powell <notifications@github.com>:

**Comment by lperron** [comment]
I know, tedious to correct. Not sure about the gain :-)

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-03-01 0:42 GMT+01:00 Michael Powell <notifications@github.com>:

**Comment by mwpowellhtx** [comment]
@lperron "What" is generated in ``src/gen/``?

**Comment by lperron** [comment]
every swig files (c++, and python, java, c#), protobuf files (in all
languages), assemblyinfo files.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-03-14 21:45 GMT+01:00 Michael Powell <notifications@github.com>:

**Comment by mwpowellhtx** [comment]
For my part, in particular, I did find that adding a WINDOWS_PATH_TO_PYTHON to my System Environment Variables was necessary. After which point, things flowed more smoothly.

In context, however, the question went from resolved, to no it is not, to what is not. The build is "working" save for compiler and linker warnings. However, and output does happen, the DLL lands in the correct place and with a plausible size expectation. I'd like for there not to be warnings, of course, and I'm not concerned with Java (at all) or Python (possibly in the future, TBD) at the moment: i.e. this topic is about restoring the VS2015, minimally the Visual Studio / C# build path. Which, excepting for a couple of potential follow up items in the Microsoft side of things exposing AssemblyInfo through and through, it is in fact working. After which point I can successfully stage and pack a NuGet package for further local testing.

Can you show me where it is not otherwise working?
