### ISSUE TITLE
Use an or-tools specific name for libflatzinc/fz binary

### ISSUE THREAD

**Issue by StefanBruens** [google/or-tools#3270]
Version: master

Currently, the tool and library use quite unspecific names, although both are or-tools specific.

E.g. chuffed and gecode use `fzn-chuffed` resp. `fzn-gecode` for the binaries, likewise for the libraries.

```sh
cmake; make; make install
```

**What did you expect to see**
`/usr/bin/fzn-ortools`
`/usr/lib64/libortools_flatzinc.so.9`

**What did you see instead?**
`/usr/bin/fz`
`/usr/lib64/libflatzinc.so.9`

ref:
* https://github.com/chuffed/chuffed/blob/master/README.md
* https://www.gecode.org/doc-latest/reference/fzn-gecode_8cpp.html

**Comment by Mizux** [comment]
AFAIK we currently don't have strong requirement on naming so renaming should be doable, plus this request seems legit.

Thx for the feedback !

**Comment by StefanBruens** [comment]
:+1: 
And extra thanks for taking care of the additional details, like the parser_test.
