### ISSUE TITLE
Ubuntu 22.04 LTS: won't be able to install dotnet-sdk-3.1 (only 6.0)

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#3276]
So currently, we can't install dotnet sdk on Ubuntu 22.04 => waiting for Microsoft to release it.

workaround: install it from script `-_-`.

blocking by:
* [x] https://github.com/dotnet/core/issues/7038
* [x] cmake(dotnet): Be able to disable a Target Framework Moniker (https://github.com/google/or-tools/commit/5f1cb90617c7e853ddb4c8cc350357742f3d4c16)
* [x] Update tools/docker to disable .Net SDK 3.1 on Ubuntu 22.04
Dev Note:
```sh
$ apt-get install -yq  dotnet-sdk-3.1 dotnet-sdk-6.0
...
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-deps-3.1 : Depends: libssl1.0.0 but it is not installable or
                                    libssl1.0.2 but it is not installable or
                                    libssl1.1 but it is not installable
 dotnet-runtime-deps-6.0 : Depends: libssl1.0.0 but it is not installable or
                                    libssl1.0.2 but it is not installable or
                                    libssl1.1 but it is not installable
```

**Comment by richlander** [comment]
Hey @Mizux -- I wrote this comment about the current situation. I hope it clarifies how to approach .NET on Ubuntu 22.04.

https://github.com/dotnet/core/issues/7038#issuecomment-1110377345

**Comment by Mizux** [comment]
@richlander Thanks for the update !

My take away:
* If I follow correctly .Net 3.1 won't be available on ubuntu 22.04 LTS since the distro only support openSSL 3.
* Fortunately now or-tools do support to enable/disable dotnet 3.1 or net 6.0 => just need to adapt CI and release script accordingly
* So we could provide support for both when distro support it or only a net6.0 support when needed.

**Comment by richlander** [comment]
I think you have it. Happy to help when you folks need it. You can just at-mention me.

**Comment by StefanBruens** [comment]
Another issue with dotNet 3.1 (as provided by Microsoft) is the missing compatibility with ICU >= 70, as can be seen here:
https://github.com/google/or-tools/runs/6644968336?check_suite_focus=true

Upstream reference:
https://github.com/dotnet/runtime/pull/34095

**Comment by richlander** [comment]
Is it possible to move to .NET 6?
