### ISSUE TITLE
PDLP logging behavior different from Glop

### ISSUE THREAD

**Issue by matbesancon** [google/or-tools#3279]
`WARNING: Logging before InitGoogleLogging() is written to STDERR`
-> as the Warning states everything is written to STDERR.

This behavior is not similar to GLOP for which the info log is printed normally without any action

**Comment by mlubin** [comment]
This is intended behavior (for now). You can fix the warning by initializing the logging library before calling PDLP.
C++ example: https://github.com/google/or-tools/blob/stable/examples/cpp/vector_bin_packing_solver.cc#L100
Python example: https://github.com/google/or-tools/blob/stable/examples/python/integer_programming.py#L120
