### ISSUE TITLE
Binary distributions contains multiple copies of a shared library

### ISSUE THREAD

**Issue by jam7** [google/or-tools#3281]
Version: v9.3
Language: C++/Java/C#/FlatZinc

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Not related to the solver type.

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you do?**
1. Download one of binary distribution.  `wget https://github.com/google/or-tools/releases/download/v9.3/or-tools_amd64_flatzinc_ubuntu-20.04_v9.3.10497.tar.gz`
2. Extract it.  `tar xfp or-tools_amd64_flatzinc_ubuntu-20.04_v9.3.10497.tar.gz`
3. Check inode.  `ls -li or-tools_flatzinc_Ubuntu-20.04-64bit_v9.3.10497/lib`
```
$ ls -li or-tools_flatzinc_Ubuntu-20.04-64bit_v9.3.10497/lib
total 114192
43933 -rw-r--r-- 1 jam jam   587816 Mar 17 03:37 libflatzinc.so
43938 -rw-r--r-- 1 jam jam   587816 Mar 17 03:37 libflatzinc.so.9
43935 -rw-r--r-- 1 jam jam   587816 Mar 17 03:37 libflatzinc.so.9.3.10497
43934 -rw-r--r-- 1 jam jam 38385712 Mar 17 03:37 libortools.so
43937 -rw-r--r-- 1 jam jam 38385712 Mar 17 03:37 libortools.so.9
43936 -rw-r--r-- 1 jam jam 38385712 Mar 17 03:37 libortools.so.9.3.10497
```

**What did you expect to see**
Identical inode that refers hard link originally created.

**What did you see instead?**
Copied multiple files.

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
It looks all binary distributions contains multiple copies, not only ubuntu but also alpine and others.

**Comment by jam7** [comment]
In addition, I was trying binary packages listed at https://developers.google.com/optimization/install.

**Comment by kaz7** [comment]
Ping.

**Comment by Mizux** [comment]
```sh
[0]─[.../or-tools_cpp_archlinux-64bit_v9.4.1874/lib]
[^u^]─mizux@nuc10i7 %ls -l | grep "\(flatzinc\|ortools\)"
libortools_flatzinc.so -> libortools_flatzinc.so.9
libortools_flatzinc.so.9 -> libortools_flatzinc.so.9.4.1874
libortools_flatzinc.so.9.4.1874
libortools.so -> libortools.so.9
libortools.so.9 -> libortools.so.9.4.1874
libortools.so.9.4.1874
```
