### ISSUE TITLE
cp-sat optimization crashes with: weights[root.Index()] == 0 (5 vs. 0)

### ISSUE THREAD

**Issue by eyaler** [google/or-tools#3288]
Version: both master (9.4.170) and 9.3
Language: Python 3.9
OS: Windows 10 64
Solver: CP-SAT

[proto.txt](https://drive.google.com/file/d/1yvAfbqlAwTNvlfYFwRu6X5D0kQa9pwxf/view?usp=sharing)
error message below
the crash is not deterministic - the exact same run will sometimes crash or not.
can happen with either num_workers = 1 or num_workers = 8
 
btw, can we have model.ImportFromFile() for the python API?

your work is much appreciated. thanks!

```
Check failed: weights[root.Index()] == 0 (5 vs. 0) 
*** Check failure stack trace: ***
    @   00007FFED28C23ED  (unknown)
    @   00007FFED28C1839  (unknown)
    @   00007FFED2A63E6B  (unknown)
    @   00007FFED2A602F5  (unknown)
    @   00007FFED29030A5  (unknown)
    @   00007FFED28EE1EF  (unknown)
    @   00007FFED29A7F19  (unknown)
    @   00007FFED2A9B114  (unknown)
    @   00007FFED2A9A70F  (unknown)
    @   00007FFF54AA1BB2  (unknown)
    @   00007FFF56A77034  (unknown)
    @   00007FFF56C22651  (unknown)

Process finished with exit code -1073740791 (0xC0000409)
```

**Comment by lperron** [comment]
Thanks. We will have a look.

**Comment by lperron** [comment]
I can reproduce with num_search_workers:1,optimize_with_core:true

**Comment by lperron** [comment]
Fixed on master.

Thanks for the report.

**Comment by eyaler** [comment]
I confirm that I on master I no longer see the issue

thank you @lperron, your issue turnaround rate is truly amazing!

**Comment by lperron** [comment]
Actually fdid-git fixed the issue :-)

Thanks again for the report.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
