### ISSUE TITLE
v9.0: Can't find Gurobi 9.5.1

### ISSUE THREAD

**Issue by gdowdy3** [google/or-tools#3293]
**What version of OR-Tools and what language are you using?**
Version: 9.0.9048
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Gurobi

**What operating system (Linux, Windows, ...) and version?**
Linux, details below:
```
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**What did you do?**
1. Install Gurobi 9.5.1.
2. Install a Gurobi license file.
3. Install or-tools with `pip3 install ortools`
4. Open up a python interactive terminal with `python3`.
5. Import `pywraplp` with `from ortools.linear_solver import pywraplp`.
6. Attempt to create a solver object based on gurobi with the line `pywraplp.Solver.CreateSolver('GUROBI')`

**What did you expect to see**
Successful creation of the solver object

**What did you see instead?**
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0127 08:05:56.613769 52491 linear_solver.cc:612] Support for GUROBI not linked in, or the license was not found.
```

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by gdowdy3** [comment]
If I enter `gurobi_cl`, I get the following output:

```
Set parameter LogFile to value "gurobi.log"
Using license file /opt/gurobi/gurobi.lic

Usage: gurobi_cl [--command]* [param=value]* filename
Type 'gurobi_cl --help' for more information.
```

This suggests that the gurobi and the license are both appropriately installed.

**Comment by gdowdy3** [comment]
The various Gurobi installation files can be found under `/opt/gurobi951/linux64`.

**Comment by Mizux** [comment]
Did you try to set GUROBI_HOME ?

https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/ortools/gurobi/environment.cc#L662-L688

Please also note the 951 was not supported by v9.0 nor v9.1
https://github.com/google/or-tools/blob/b37d9c786b69128f3505f15beca09e89bf078a89/ortools/gurobi/environment.cc#L666-L669
seems to appear in v9.2
https://github.com/google/or-tools/blob/2cb85b4eead4c38e1c54b48044f92087cf165bce/ortools/gurobi/environment.cc#L667-L670

**Comment by lperron** [comment]
You can set the path directly.

from ortools.init.python import init

init.LoadGurobiSharedLibrary('full_path_to_.so')

before creating the MPSolver.

**Comment by gdowdy3** [comment]
Thanks for the quick response, guys!  

@Mizux, I did try manually setting the `GUROBI_HOME` environment variable, but, truth be told, I'm not 100% sure I know what value I should set it to.  I tried `export GUROBI_HOME=/opt/gurobi951/linux64`, and this did not resolve the issue.  If there's some other value I should be using, please let me know.

@lperron, thanks for suggesting an alternative route to resolve the problem.  To which `.so` file should I be pointing?  Under `/opt/gurobi951/linux64/lib`, I see a few candidates:
```
gurobi95.netstandard20.dll  gurobi.jar          gurobi.py             libgurobi95.so   libgurobi_g++4.8.a  libGurobiJni95.so   python2.7_utf16  python3.10_utf32  python3.7_utf32  python3.9_utf32
gurobi95.netstandard20.xml  gurobi-javadoc.jar  libgurobi95_light.so  libgurobi_c++.a  libgurobi_g++5.2.a  libgurobi.so.9.5.1  python2.7_utf32  python3.7         python3.8_utf32  rootcert.pem
```
Should I be pointing to one of these?  If so, which one?

**Comment by gdowdy3** [comment]
Thanks, again for the quick response!  Unfortunately, when I enter `from ortools.init.python import init` in the Python interactive prompt, I'm getting an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ortools.init.python'
```
Any ideas what might be causing that?

**Comment by Mizux** [comment]
there is no `ortools/init/python/__init__.py`
https://github.com/google/or-tools/blob/71336d84b849711637271f1bc75d19fadcf2b712/cmake/python.cmake#L194

Where did you find this call ?

**Comment by gdowdy3** [comment]
@Mizux, I'm assuming your question

> Where did you find this call ?

is for @lperron, but let me know if you're looking for additional information from me.

**Comment by lperron** [comment]
My bad, try

from ortools.init import pywrapinit

then

pywrapinit.CppBridge.LoadGurobiSharedLibrary('path')

Sorry for the approximations.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mer. 11 mai 2022 à 17:08, Garrett R Dowdy ***@***.***> a
écrit :

**Comment by gdowdy3** [comment]
Thanks, @Mizux!  We are getting closer, but not quite there... `pywrapinit.CppBridge.LoadGurobiSharedLibrary('/opt/gurobi951/linux64/lib/libgurobi95.so')` yields
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1011 23:55:53.855957 33959 environment.cc:737] Found the Gurobi library in '/opt/gurobi951/linux64/lib/libgurobi95.so.
F1011 23:55:54.134033 33959 dynamic_library.h:68] Check failed: function_address != nullptr Error: could not find function GRBsetlogfile in /opt/gurobi951/linux64/lib/libgurobi95.so
*** Check failure stack trace: ***
Aborted (core dumped)
```
Any ideas on how to fix that?

**Comment by Mizux** [comment]
FYI:
https://github.com/google/or-tools/commit/762aaaecd9fd00a3a6c1de814dea4d71b0fa5a91
which should be in v9.3 so you may test the v9.3

For v9.4 we'll have the fix:
https://github.com/google/or-tools/commit/d6e0feb8ae96368523deb99fe4318d32e80e8145

**Comment by gdowdy3** [comment]
OK, two follow-up questions:

1. Should I expect the code to work if I roll back to a previous version of Gurobi (e.g. v9.5.0)?
2. If I wanted to test Gurobi v9.5.1 with OR-Tools v9.3, would I need to build OR-Tools from source?  I ask because it looks like version 9.0.9048 is the latest version available via pip.

**Comment by lperron** [comment]
1) 9.5.0 broke it.
2) https://pypi.org/project/ortools/ -> 9.3 is on pip. Are you using an
older version of python ?



Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mer. 11 mai 2022 à 17:55, Garrett R Dowdy ***@***.***> a
écrit :

**Comment by lperron** [comment]
I do not understand why you do not find a better version of or-tools.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mer. 11 mai 2022 à 18:01, Garrett R Dowdy ***@***.***> a
écrit :

**Comment by gdowdy3** [comment]
Ah, it seems that I needed to upgrade pip with `python3 -m pip install --upgrade pip`.

I'm now running `or-tools v9.3.10497`.  However, when I enter `pywraplp.Solver.CreateSolver('GUROBI')`, I'm still getting an error:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0511 12:55:37.845215 77024 environment.cc:736] Found the Gurobi library in '/opt/gurobi951/linux64/lib/libgurobi95.so.
F0511 12:55:37.845553 77024 dynamic_library.h:68] Check failed: function_address != nullptr Error: could not find function GRBtunemodeladv in /opt/gurobi951/linux64/lib/libgurobi95.so
*** Check failure stack trace: ***
Aborted (core dumped)
```
Any idea how to fix that?

**Comment by Mizux** [comment]
Yes, no prebuilt available yet

**Comment by gdowdy3** [comment]
Update: I've built `ortools v9.4.179` from the master branch.

Now, when I do the following:
1. Open up a python interactive terminal with `python3`.
2. Import pywraplp with from `ortools.linear_solver import pywraplp`.
3. Attempt to create a solver object based on gurobi with the line `pywraplp.Solver.CreateSolver('GUROBI')`

I get a different error message:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0518 16:32:38.531427 16620 environment.cc:733] Found the Gurobi library in '/opt/gurobi951/linux64/lib/libgurobi95.so.
W0518 16:32:38.534896 16620 linear_solver.cc:621] Support for GUROBI not linked in, or the license was not found.
```

In case it is relevant, `echo $GUROBI_HOME` returns `/opt/gurobi951/linux64`, and I have a copy of `gurobi.lic` saved in this directory.

Any thoughts on how I can resolve this?

**Comment by gdowdy3** [comment]
I don't know if this is relevant, but, when I run `make test_python`, I get the following error:

```
.testLoadSolutionFromProto
E0518 16:45:32.532724 23132 linear_solverPYTHON_wrap.cxx:3593] LoadSolutionFromProto() failed: INVALID_ARGUMENT: Cannot load a solution unless its status is OPTIMAL or FEASIBLE (status was: MPSOLVER_UNKNOWN_STATUS)
.testSetHint
.testSolveFromProto
E
======================================================================
ERROR: testSolveFromProto (__main__.PyWrapLpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "examples/tests/lp_test.py", line 305, in testSolveFromProto
    pywraplp.Solver.SolveWithProto(model_request=request, response=response)
TypeError: Solver_SolveWithProto() takes no keyword arguments

----------------------------------------------------------------------
Ran 5 tests in 0.030s

FAILED (errors=1)
makefiles/Makefile.python.mk:91: recipe for target 'rpy_lp_test' failed
make: *** [rpy_lp_test] Error 1

```

**Comment by gdowdy3** [comment]
> Update: I've built `ortools v9.4.179` from the master branch.
> 
> Now, when I do the following:
> 
> 1. Open up a python interactive terminal with `python3`.
> 2. Import pywraplp with `from ortools.linear_solver import pywraplp`.
> 3. Attempt to create a solver object based on gurobi with the line `pywraplp.Solver.CreateSolver('GUROBI')`
> 
> I get a different error message:
> 
> ```
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> I0518 16:32:38.531427 16620 environment.cc:733] Found the Gurobi library in '/opt/gurobi951/linux64/lib/libgurobi95.so.
> W0518 16:32:38.534896 16620 linear_solver.cc:621] Support for GUROBI not linked in, or the license was not found.
> ```
> 
> In case it is relevant, `echo $GUROBI_HOME` returns `/opt/gurobi951/linux64`, and I have a copy of `gurobi.lic` saved in this directory.
> 
> Any thoughts on how I can resolve this?

Sorry, ignore the above.  It was apparently caused by the fact that I had a single-use license.

**Comment by gdowdy3** [comment]
The error that I observed when running `make test_python` is still a concern.

**Comment by RichardOberdieck** [comment]
May I ask what the status is on this? Is it fixed on master? If yes, when can we expect a release?

**Comment by Mizux** [comment]
@RichardOberdieck AFAIK
* last fix was https://github.com/google/or-tools/commit/d6e0feb8ae96368523deb99fe4318d32e80e8145 and it should fix the issue with the drop of the API method `GRBtunemodeladv` in Gurobi `9.5.?`
* I still need to finish to setup my Apple M1 (new platform supported in v9.4) and adapt tools/release scripts so we can generate artifact for this platform using a script

Then we should be OKish for a release, please follow  https://github.com/google/or-tools/issues/3341 to see the remaining issues/task blocking the release...

**Comment by torressa** [comment]
I am confused: why is this hard coded and not handled with CMake?
Like done for CPLEX and friends, could add a `FindGUROBI.cmake` (see below taken from [here](https://support.gurobi.com/hc/en-us/articles/360039499751-How-do-I-use-CMake-to-build-Gurobi-C-C-projects-)).
Wouldn't need these version bumps or hard-coded library paths and architecture-related folder naming.

<details>
  <summary>example FindGUROBI.cmake</summary>

```cmake
find_path(
  GUROBI_INCLUDE_DIRS
  NAMES gurobi_c.h
  HINTS ${GUROBI_DIR} $ENV{GUROBI_HOME}
  PATH_SUFFIXES include)

find_library(
  GUROBI_LIBRARY
  NAMES gurobi gurobi81 gurobi90 gurobi95
  HINTS ${GUROBI_DIR} $ENV{GUROBI_HOME}
  PATH_SUFFIXES lib)

if(MSVC)
  # determine Visual Studio year
  if(MSVC_TOOLSET_VERSION EQUAL 142)
    set(MSVC_YEAR "2019")
  elseif(MSVC_TOOLSET_VERSION EQUAL 141)
    set(MSVC_YEAR "2017")
  elseif(MSVC_TOOLSET_VERSION EQUAL 140)
    set(MSVC_YEAR "2015")
  endif()

  if(MT)
    set(M_FLAG "mt")
  else()
    set(M_FLAG "md")
  endif()

  find_library(
    GUROBI_CXX_LIBRARY
    NAMES gurobi_c++${M_FLAG}${MSVC_YEAR}
    HINTS ${GUROBI_DIR} $ENV{GUROBI_HOME}
    PATH_SUFFIXES lib)
  find_library(
    GUROBI_CXX_DEBUG_LIBRARY
    NAMES gurobi_c++${M_FLAG}d${MSVC_YEAR}
    HINTS ${GUROBI_DIR} $ENV{GUROBI_HOME}
    PATH_SUFFIXES lib)
else()
  find_library(
    GUROBI_CXX_LIBRARY
    NAMES gurobi_c++
    HINTS ${GUROBI_DIR} $ENV{GUROBI_HOME}
    PATH_SUFFIXES lib)
  set(GUROBI_CXX_DEBUG_LIBRARY ${GUROBI_CXX_LIBRARY})
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GUROBI DEFAULT_MSG GUROBI_LIBRARY
                                  GUROBI_INCLUDE_DIRS)
```

</details>

**Comment by lperron** [comment]
No, we do not need recompilation to run gurobi.  We just need to find the
shared library dynamically.

Le mer. 17 août 2022, 16:42, David Torres ***@***.***> a
écrit :

**Comment by torressa** [comment]
Sure, it's just confusing that every other solver is handled by CMake. e.g. SCIP, CPLEX, XPRESS, Cbc, all a `FindSOLVER.cmake` and corresponding `USE_SOLVER` build option.

**Comment by lperron** [comment]
The goal would be not to recompile to be able to use any solver.

We did the pre-loading work for gurobi.
We include SCIP by default
Our solvers (glop, pdlp, cp-sat) are included by default

CPLEX is no longer developed.
XPRESS integration is incomplete, and nobody is interested in upgrading it.
CLP/CBC are included but unreliable (CLP is quite good though). We will
drop them as soon as possible.
GLPK is not competitive at all.
The next in the list will be Highs. We need their help to do the
integration.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mer. 17 août 2022 à 17:16, David Torres ***@***.***> a
écrit :

**Comment by lperron** [comment]
9.4 is out.

**Comment by RichardOberdieck** [comment]
Thanks for the heads-up Laurent, I will let you know if we hear of any more issues.

**Comment by lperron** [comment]
Can you get what are your requirements ?
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mer. 11 mai 2022 à 19:17, Garrett R Dowdy ***@***.***> a
écrit :

**Comment by lperron** [comment]
No, most likely a bad test.
I do not think it uses gurobi.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le jeu. 19 mai 2022 à 01:53, Garrett R Dowdy ***@***.***> a
écrit :
