### ISSUE TITLE
Change Parameters in PDLP

### ISSUE THREAD

**Issue by xinyufei** [google/or-tools#3306]
**What version of OR-Tools and what language are you using?**
Version: v9.3.10497
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
PDLP

**What operating system (Linux, Windows, ...) and version?**
Mac OS 12.3.1

**What did you do?**
I want to set the parameter like eps_optimal_absolute to control the precision of solution obtained from PDLP. Are there any ways to do it?

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by mlubin** [comment]
See my answer [here](https://groups.google.com/g/or-tools-discuss/c/XbSxNpWWwdE/m/Qvb3k3IEHgAJ) for C++:

> An example of non-default termination criteria are:
> 
> std::string pdlp_params_str = "termination_criteria: {  time_limit_sec: 60 eps_optimal_absolute: 1e-4 eps_optimal_relative: 1e-4 }";
> If you're using MPSolver, pass the parameters as: solver.SetSolverSpecificParametersAsString(pdlp_params_str);
> If you're using MPModelRequest, set the solver_specific_parameters field instead.
> 
> See the documentation on PrimalDualHybridGradientParams for the precise definitions of the termination criteria and other parameters you can set.

I'm not familiar with the Java interface, but based on my reading of https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/ortools/linear_solver/java/linear_solver.i#L365
the java equivalent of `SetSolverSpecificParametersAsString` is `setSolverSpecificParametersAsString`.
