### ISSUE TITLE
[Question] Checking already Scheduled Vehicles for taking ADD ON ride - CSVRPTW

### ISSUE THREAD

**Issue by rajatjangir** [google/or-tools#332]
While using the CSVRPTW i have been successfully able to schedule the rides in different vans.

**I am facing following problem:** 

1. How can i check the existing scheduled ride from my database and try to fit any new ride entered in the system keeping the hard constraint not to remove any existing ride. [UNABLE TO SOLVE]

2. How to make sure that i have a fixed length of drop and pickup load time added to each the vehicle according to the type of capacity. Example if i am carrying a heavy load than it will take more time to load and unload than a lighter one. I am able to add load times using timedimention.SetRange function but when the pickup or drop location of two units is same then if adds load time twice which should only be added once. [FOUND A WORKAROUND]

3.[NOT ABLE TO UNDERSTAND] How does the program calculate cost and how can i input those cost based on my billing model so that i will drop first the rides which are less valuable instead of the ones which costs more.

Any help would be appreciated, thanks.

**Comment by furnon** [comment]
For 1), you can use the assignment returned by
RoutingModel:: MutablePreAssignment() to fix any part of the problem you
want (be it next, or vehicle variables for instance). You could
alternatively add constraints directly in the model, such as vehicle_var !=
-1 if the node must remain performed.
For 2), load/unload times should be taken into account in the time
dimension callback (typically returning time(a,b) + load_time(a);
load_time(a) can depend on a and its actual weight). I'm not sure I
understand the second part of your question: if you are doing two
consecutive loads at the same location do you want the load time to be the
sum of the load times or only the load time of the first load ?

**Comment by lperron** [comment]
Answered by Vincent.
