### ISSUE TITLE
 [WASM] Memory Limit exceeded exception thrown while using cibc solver in the backend for mixed integer problem using or tools

### ISSUE THREAD

**Issue by abhijith96** [google/or-tools#3335]
**What version of OR-Tools and what language are you using?**
Version: 8.1
Language: C++ 17

Using CIBC Solver

OS - Macos Monterey

I created a problem using 100 decision variables all them having integer constraints and some complex constraints. The problem is expected to be infeasible. I set time limit as 500 seconds. I am getting an os SIGKILL exception before 500 seconds. When I set time limit to 100 seconds I am getting time limit exceeded exception as expected.

"macos 137 (interrupted by signal 9: SIGKILL)" This is the exception. I think it is because os is killing the process for using too much memory.

Is there a way in which we can catch these memory usage exceptions in the code itself when a threshold is breached.

I am using mac m1 with armv8 architecture.

**Comment by lperron** [comment]
No. Memory allocation is most likely done in a dependency (CBC).

Do you have a stacktrace when it fails ?

Question: 
  - why not use 9.3 ? 
  - Did you try the CP-SAT backend ? It should have better performance

**Comment by abhijith96** [comment]
> No. Memory allocation is most likely done in a dependency (CBC).
> Ok
> Do you have a stacktrace when it fails ?
> No, i was not able to recreate it, as this error occurs only when there is high memory usage in the system I think.
> Question:
> 
> * why not use 9.3 ?
Not sure if 9.3 has wasm support.
> * Did you try the CP-SAT backend ? It should have better performance
 Will try it.Some of the problems in my use case are purely linear without any mip. Can CP_SAT support them too.

**Comment by lperron** [comment]
None of this codes (or-tools, cbc) are protected against OOM exceptions. None track memory used.

So I guess there is nothing we can do at this point.

I suppose you need to build limits in the models you are building to be sure they will not OOM.
