### ISSUE TITLE
Or-tools failed to run test on Windows with MSVC

### ISSUE THREAD

**Issue by Apriltanq** [google/or-tools#3344]
or-tools failed to run test on Windows with MSVC. It can reproduces on version https://github.com/google/or-tools/commit/49b6301e1e1e231d654d79b6032e79809868a70e. Could you please help look at this issue? Thank you very much

**Environment**
Compiler version: VS2019
Operating system: Windows server 2019

**Reproduce steps:**
git clone https://github.com/google/or-tools F:\gitP\google\or-tools
cd F:\gitP\google\or-tools
mkdir build_x86
cd build_x86
copy "F:\gitP\google\fixed_array--20211102.0.patch" F:\gitP\google\or-tools\patches
cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DBUILD_DEPS=ON -DCMAKE_BUILD_TYPE=Release .. 2>&1
cmake --build . --config Release --target ALL_BUILD -v -- /maxcpucount 2>&1
ctest --build-config Release --output-on-failure -E "simple_ls_program|vrp|binpacking_problem_sat|multiple_knapsack_sat|cvrp_disjoint_tw|cvrptw|golomb_sat|uncapacitated_facility_location" 2>&1

**Error log:**

[test.0.log](https://github.com/google/or-tools/files/8905354/test.0.log)
[test.2.log](https://github.com/google/or-tools/files/8905356/test.2.log)
[test.log](https://github.com/google/or-tools/files/8905357/test.log)

Error info:
The following tests FAILED:
	 68 - cxx_cpp_linear_programming (Exit code 0xc0000409
)
	 85 - cxx_tests_lp_test (Exit code 0xc0000409
)
Errors while running CTest

**Comment by lperron** [comment]
32 bit builds are not supported.

**Comment by Apriltanq** [comment]
> 3
you mean Or_tools project cannot build and run test on x86?

**Comment by lperron** [comment]
No. We only support 64 bit builds (x86_64 in your case). This has been the
case for many years now.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by Apriltanq** [comment]
> 

Got it, thanks.

**Comment by Apriltanq** [comment]
> 32 bit builds are not supported

Got it, thanks.
