### ISSUE TITLE
[BUG] Cannot customize the EbertGraph for GenericMinCostFlow (changing default template parameters makes error)?

### ISSUE THREAD

**Issue by jcyk** [google/or-tools#335]
I want to solve a min cost flow problem with enormous edges, of which the number is beyond the range of int32.
So I decide to use int64 instead.

After read the source code, I found that I could change the template parameters of class EberGraph, say to declare ```operations_research::EbertGraph<int32, int64>```, and use ```operations_research::GenericMinCostFlow< operations_research::EbertGraph<int32, int64> > flow(&graph)``` to make a new solver. 
Then the full code is that
```
operations_research::EbertGraph<int32, int64> graph( 60000, 3000000000);
operations_research::GenericMinCostFlow< operations_research::EbertGraph<int32, int64> > flow(&graph)
```
However, I got the following error.

```undefined reference to `operations_research::GenericMinCostFlow<operations_research::EbertGraph<int, long long>, long long , long long>::GenericMinCostFlow(operations_research::EbertGraph<int, long long> const*)'```

Any idea to fix that?

**Comment by jcyk** [comment]
EbertGraph just does NOT work.
I add a line to ```include/min_cost_flow.cc```, that is ```template class GenericMinCostFlow<ReverseArcListGraph<int32, int64> >;``` (I tried EbertGraph, it failed.)
Recompiling the source code, the problem is solved.

**Comment by lperron** [comment]
Yes, ebert graph are subsumed by the new graphs.

You have your solution, I will close the issue.

Thanks
