### ISSUE TITLE
build ortools/graph:shortestpaths with -Werror complains about unused function

### ISSUE THREAD

**Issue by ek345** [google/or-tools#3357]
Specifically, `ShellEscape(...)` in `ortools/base/logging.cc` is the complaint (it does appear to be unused).

**Comment by lperron** [comment]
yes, and so ?

**Comment by ek345** [comment]
I certainly didn't mean to appear rude, and if that's the impression I gave then I certainly apologise for it.

I had thought that using the various compiler `-Wall`, `-Werror`, and other such options was considered helpful for code cleanliness checks and whatnot.  I meant no disrespect.

**Comment by lperron** [comment]
Ok, just a mail or a small pr.
I try to keep issues for real bugs :-)
