### ISSUE TITLE
RoutingModel not using vehicleStarts and vehicleEnds

### ISSUE THREAD

**Issue by julienroubieu** [google/or-tools#338]
Hello,

I've stumbled across an issue while running the VRP Java example, which uses `new RoutingModel(numberOfLocations, numberOfVehicles, vehicleStarts, vehicleEnds);`.
By looking at the solution, it seems that the model does not use the indexes passed into `vehicleStarts` and `vehicleEnds`, but consider instead that all orders locations will be followed by start locations, and then end locations.

For example, using 50 orders and 5 vehicles, routes are:
- Vehicle 0: 50 -> ... -> 55
- Vehicle 1: 51 -> ... -> 56
...

You can verify it by running the simplified example [there](https://gist.github.com/julienroubieu/12e2eb137b815aa9593e7e17c7db2c23), which prints for each route the start and end indexes.
I'm using or-tools_MacOsX-10.12.2_v5.1.4045.

Am I missing something?

**Comment by furnon** [comment]
The values of the next variables in the solution assignment do not
represent the node indices but the internal variable indices. To get the
nodes you should do something like this, using IndexToNode to get the nodes:
order = model.IndexToNode(solution.value(model.nextVar(order)));
Note: in some cases both indices match but in general they don't especially
when you have different start/end nodes for each vehicle.
Note bis: the Java VRP example delivered with or-tools displays variable
indices, not nodes.

**Comment by julienroubieu** [comment]
I see, that explains my mistake. Thank you!
