### ISSUE TITLE
OR-Tools v9.3 not working with Gurobi 9.5.2 

### ISSUE THREAD

**Issue by Regista6** [google/or-tools#3382]
**What version of OR-Tools and what language are you using?**
Version: v9.3
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Gurobi
**What operating system (Linux, Windows, ...) and version?**
Windows 10
**What did you do?**
1. Install Gurobi 9.5.2
2. Setup OR-Tools v9.3 with VS 2022
3. Solve a basic [MIP Problem](https://developers.google.com/optimization/mip/mip_example#complete-programs)

**What did you expect to see**
Solution
**What did you see instead?**

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0715 20:09:32.871677 15656 environment.cc:736] Found the Gurobi library in 'C:\gurobi952\win64\bin\gurobi95.dll.
F0715 20:09:32.872823 15656 dynamic_library.h:68] Check failed: function_address != nullptr Error: could not find function GRBtunemodeladv in C:\gurobi952\win64\bin\gurobi95.dll
*** Check failure stack trace: ***
```

**Comment by lperron** [comment]
well known.
