### ISSUE TITLE
CP-SAT solver: Does RANDOM var_selection_strategy and domain_reduction_strategy supported in the near future?

### ISSUE THREAD

**Issue by EvenHigher** [google/or-tools#3384]
**What language and solver does this apply to?**
All, Python, Java, C#, C++ / CP-SAT, Routing, Linear Solver

**Describe the problem you are trying to solve.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by EvenHigher** [comment]
Hi, I find cp-sat solver does not support CHOOSE_RANDOM and ASSIGN_RANDOM_VALUE strategy which is supported in original cp solver. Is there any plan to support this in cp-sat solver? Thanks!

**Comment by lperron** [comment]
Short time no. We never use decision strategies.

**Comment by lperron** [comment]
We accept PR :-)
