### ISSUE TITLE
AddDimensionDependentDimensionWithVehicleCapacity() support in Python and C#

### ISSUE THREAD

**Issue by peterlau** [google/or-tools#339]
Are there any plans in the immediate roadmap to support dimensions that depend on the cumul of another (i.e. `AddDimensionDependentDimensionWithVehicleCapacity()`) in the python bindings?

If not, what approach could I use to accomplish the same effect (by using lower-level constructs underneath RoutingModel)?  Thanks for any guidance - I'm new to or-tools and CP.

https://github.com/google/or-tools/blob/554cbccaa95b4c11eced13f145de1bf468e1f919/ortools/constraint_solver/routing.h#L448-L486

Duplicated by: #574 #480 #969

**Comment by Mizux** [comment]
Hi,

Unfortunately not AFAIK..
Please notice there is already #574

**Comment by tarbaig** [comment]
Hi,
looking at routing.i and the definitions of "AddDimensionDependentDimensionWithVehicleCapacity"
it seems to me that the only thing missing  is an input mapping for  "std::vector<VariableNodeEvaluator2*>&".

Is this the only reason this is currently not supported? If yes I'll happily try to implement one.

**Comment by quinlivanb** [comment]
This would be a very useful addition for python!

**Comment by lperron** [comment]
time dependent dimensions are highly experimental, and currently not working very well.
There are no plan currently to support in python.

**Comment by JackCloudman** [comment]
some news about this feature in python?

**Comment by lperron** [comment]
No, the c++ feature is not mature enough.

**Comment by matej14086** [comment]
Is this feature in python, if no is there any workaround for time-depented distance matirx?

**Comment by lperron** [comment]
No and no.

**Comment by Mizux** [comment]
The only workaround I see would be:
* duplicate each node per trafic time range
e.g. node A with TimeWindow `[A, D]` would become A1 TW `[A,B]`, A2 TW `[B,C]`, A3 TW `[C,D]`. then
* add a Disjunction so only one node need to be visited `routing.AddDisjunction([A1, A2, A3], penalty, 1)`.
Use A1 for traffic time 1, A2 for traffic time 2 etc...

note: AddDependentDimension just create a k * N*N matrix with k being the range of time so if your time go from 0 to 1000, solver will precompute 1000 * NxN matrix killing memory and performance.... even if you only have 2 mode: rush hour, quiet mode...
note2: you could also have A1 TW [A,B] + [C, D], and A2 TW [B, C] to even reduce duplicates nodes...

**Comment by lperron** [comment]
No necro-posting,, and search the mailing list as this is a recurring
question.

Short answer: it is forbidden.

Le ven. 12 avr. 2024, 10:15, sandipkrgupta ***@***.***> a
écrit :
