### ISSUE TITLE
Or_tools failed to build with "error LNK2001: unresolved external symbol "private: virtual void const * __cdecl google::protobuf::MessageLite::InternalGetTable(void)const " (?InternalGetTable@MessageLite@protobuf@google@@$$hEEBAPEBXXZ) (EC Symbol)" with MSVC on Windows arm64ec

### ISSUE THREAD

**Issue by YangYang129** [google/or-tools#3390]
Or_tools failed to build with "error LNK2001: unresolved external symbol "private: virtual void const * __cdecl google::protobuf::MessageLite::InternalGetTable(void)const " (?InternalGetTable@MessageLite@protobuf@google@@$$hEEBAPEBXXZ) (EC Symbol)" with MSVC on Windows arm64ec. It can reproduce on latest version on stable branch. Could you please help look at this issue?

**Repro steps:**
1. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
2. cd F:\gitP\Microsoft\vcpkg
3. bootstrap-vcpkg.bat 2>&1
4. vcpkg.exe install --recurse protobuf zlib --triplet arm64-windows --clean-after-build 2>&1
5. git clone https://github.com/google/or-tools F:\gitP\google/or-tools
6. cd F:\gitP\google/or-tools
7. mkdir build_arm64ec && cd build_arm64ec
8. copy "F:\gitP\google\fixed_array--20211102.0.patch" F:\gitP\google\or-tools\patches
9. cmake -G "Visual Studio 16 2019" -A ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22618.0 -DBUILD_DEPS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=F:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=arm64-windows -DUSE_SCIP=OFF .. 2>&1
10. cmake --build . --config Release --target ALL_BUILD -v -- /maxcpucount 2>&1

**Error info:**
```
200>ortools.lib(boolean_problem.pb.obj) : error LNK2001: unresolved external symbol "private: virtual void const * __cdecl google::protobuf::MessageLite::InternalGetTable(void)const " (?InternalGetTable@MessageLite@protobuf@google@@$$hEEBAPEBXXZ) (EC Symbol) [F:\gitP\google\or-tools\build_arm64ec\ortools\sat\samples\simple_sat_program.vcxproj]
   200>ortools.lib(cp_model.pb.obj) : error LNK2001: unresolved external symbol "private: virtual void const * __cdecl google::protobuf::MessageLite::InternalGetTable(void)const " (?InternalGetTable@MessageLite@protobuf@google@@$$hEEBAPEBXXZ) (EC Symbol) [F:\gitP\google\or-tools\build_arm64ec\ortools\sat\samples\simple_sat_program.vcxproj]
   200>ortools.lib(sat_parameters.pb.obj) : error LNK2001: unresolved external symbol "private: virtual void const * __cdecl google::protobuf::MessageLite::InternalGetTable(void)const " (?InternalGetTable@MessageLite@protobuf@google@@$$hEEBAPEBXXZ) (EC Symbol) [F:\gitP\google\or-tools\build_arm64ec\ortools\sat\samples\simple_sat_program.vcxproj]
   200>ortools.lib(linear_solver.pb.obj) : error LNK2001: unresolved external symbol "private: virtual void const * __cdecl google::protobuf::MessageLite::InternalGetTable(void)const " (?InternalGetTable@MessageLite@protobuf@google@@$$hEEBAPEBXXZ) (EC Symbol) [F:\gitP\google\or-tools\build_arm64ec\ortools\sat\samples\simple_sat_program.vcxproj]
   200>ortools.lib(parameters.pb.obj) : error LNK2001: unresolved external symbol "private: virtual void const * __cdecl google::protobuf::MessageLite::InternalGetTable(void)const " (?InternalGetTable@MessageLite@protobuf@google@@$$hEEBAPEBXXZ) (EC Symbol) [F:\gitP\google\or-tools\build_arm64ec\ortools\sat\samples\simple_sat_program.vcxproj]
```

**Comment by lperron** [comment]
Not yet supported. We will not be working on that anytime soon

**Comment by YangYang129** [comment]
@lperron Thanks for your reply.

**Comment by Mizux** [comment]
please note `-DBUILD_DEPS=ON` will force to build all our dependencies aka protobuf and zlib but since here you are trying to use protobuf and zlib from vcpkg you may want to **NOT** use this options and instead list deps you want to build or not
`-DBUILD_SCIP=ON -DBUILD_absl=ON -DBUILD_re2=ON ...` or pull everything from the vcpkg if available.
ref: https://github.com/google/or-tools/blob/4a0cf8b9e7966cdb213176f8d27c392ad00ab091/CMakeLists.txt#L143-L154

note: our CMakeLists.txt is vcpkg agnostic and IIRC you may need to add some vcpkg specific command hack for CMake to be able to find_package packages installed through vcpkg.
note2: it is on my todo list to integrate or-tools to the vcpkg ecosystem but I can't provide any ETA (maybe 2077) ...
