### ISSUE TITLE
Requirements for ortools is not compatible for Python3.7

### ISSUE THREAD

**Issue by ed9w2in6** [google/or-tools#3409]
The requirements for `protobuf` on the setup of `ortools` for python does not seems to be valid for Python3.7.
The current requirements for protobuf on ortools version 9.3.10497 is `protobuf>=3.19.4`, which will produce the following error.

```
/opt/conda/lib/python3.7/site-packages/ortools/constraint_solver/pywrapcp.py in DefaultRoutingModelParameters()
   4655         return _pywrapcp.RoutingIndexManager_GetNumberOfVehicles(self)
   4656 
-> 4657     def GetNumberOfIndices(self) -> "int":
   4658         return _pywrapcp.RoutingIndexManager_GetNumberOfIndices(self)
   4659 

/opt/conda/lib/python3.7/site-packages/ortools/constraint_solver/routing_parameters_pb2.py in <module>
     13 
     14 
---> 15 from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
     16 from ortools.constraint_solver import routing_enums_pb2 as ortools_dot_constraint__solver_dot_routing__enums__pb2
     17 from ortools.constraint_solver import solver_parameters_pb2 as ortools_dot_constraint__solver_dot_solver__parameters__pb2

/opt/conda/lib/python3.7/site-packages/google/protobuf/duration_pb2.py in <module>
     17 
     18 _builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
---> 19 _builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.protobuf.duration_pb2', globals())
     20 if _descriptor._USE_C_DESCRIPTORS == False:
     21 

/opt/conda/lib/python3.7/site-packages/google/protobuf/internal/builder.py in BuildTopDescriptorsAndMessages(file_des, module_name, module)
    106   # Build messages.
    107   for (name, msg_des) in file_des.message_types_by_name.items():
--> 108     module[name] = BuildMessage(msg_des)
    109 
    110 

/opt/conda/lib/python3.7/site-packages/google/protobuf/internal/builder.py in BuildMessage(msg_des)
     84     create_dict['__module__'] = module_name
     85     message_class = _reflection.GeneratedProtocolMessageType(
---> 86         msg_des.name, (_message.Message,), create_dict)
     87     _sym_db.RegisterMessage(message_class)
     88     return message_class

TypeError: A Message class can only inherit from Message
```

Locking `protobuf==3.20.1` seems to have fixed this issue. Therefore I would suggest updating the requirement to `protobuf>=3.20.1`.

**What version of OR-Tools and what language are you using?**
Version: 9.3.10497 (stable)
Language: Python

```bash
$ pip list | egrep '(protobuf|ortools)'
ortools                       9.3.10497
protobuf                      4.21.4
protobuf3-to-dict             0.1.5
```

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing Solver

**What operating system (Linux, Windows, ...) and version?**
Linux

```bash
$ uname -a
Linux <image-name> #1 SMP Thu May 26 09:52:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**What did you do?**
See above error message, calling `DefaultRoutingModelParameters()`.

**What did you expect to see**
No errors when calling `DefaultRoutingModelParameters()`.

**What did you see instead?**
Failed on calling `DefaultRoutingModelParameters()`.

**Anything else we should know about your project / environment**
As some point we also have the error in #3346, but only the error in this issue can be consistently reproduced.
Locking `protobuf==3.20.1` seems to have fixed this issue.

May also have relations with this issue: https://github.com/protocolbuffers/protobuf/issues/3276

**Comment by Mizux** [comment]
we currently still use Protobuf 3.19.4 to build or-tools python wheel package (the C++ part) thus our requirement on the python package.

ref:
https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/cmake/dependencies/CMakeLists.txt#L90

We will try to bump to Protobuf 3.20.1 ASAP...
