### ISSUE TITLE
makefile is broken

### ISSUE THREAD

**Issue by dimbleby** [google/or-tools#341]
Since c6a750b0:

```
$ make clean
make: *** No rule to make target 'makefiles/Makefile.third_party.unix', needed by 'Makefile.local'.  Stop.
```

So far as I can see, the fix should just be add the .mk suffix at [this line](https://github.com/google/or-tools/blob/f4d007098d421500c683248626eb0389d195c479/makefiles/Makefile.third_party.unix.mk#L475).  

Maybe consider setting up CI...?

**Comment by lperron** [comment]
THis is fixed. Sorry for the delay.

**Comment by lperron** [comment]
Hi,

I fixed that some time ago, but never reported it.



Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-03-12 8:30 GMT-04:00 David Hotham <notifications@github.com>:
