### ISSUE TITLE
Tuples must have the same arity error [Python]

### ISSUE THREAD

**Issue by dsgkirkby** [google/or-tools#342]
When attempting to call ReadAssignmentFromRoutes or ApplyLocksToAllVehicles in Python, I encounter the error 'Tuples must have the same arity' - why is it required that each driver in a preassignment services the same number of locations?

This error is also thrown when un-commenting the preassignment code in the python plot example: https://github.com/google/or-tools/blob/master/examples/python/cvrptw_plot.py#L695.

**Comment by hagilemha** [comment]
I am running into this issue as well trying to use ApplyLocksToAllVehicles. Anyone know of a workaround?

**Comment by hagilemha** [comment]
Seems to be working with the current source code on github

**Comment by Mizux** [comment]
Good to know it has been fixed somehow
