### ISSUE TITLE
Solver Fails due to constraints added by MakeModulo

### ISSUE THREAD

**Issue by TheEternalToast** [google/or-tools#3423]
I recently encountered unexpected model failures due to modulo-based constraints.
The docs state that the modulo operator follows the python convention for modulo (the result has the same sign as the divisor).

I looked into the definition of the operator and found out that it adds a constraints making sure that the result of the operation is within the expected range:
```cpp
IntExpr* Solver::MakeModulo(IntExpr* const x, int64_t mod) {
  IntVar* const result =
      MakeDifference(x, MakeProd(MakeDiv(x, mod), mod))->Var();
  if (mod >= 0) {
    AddConstraint(MakeBetweenCt(result, 0, mod - 1));
  } else {
    AddConstraint(MakeBetweenCt(result, mod + 1, 0));
  }
  return result;
}
```
However, the way this is currently implemented, it will simply add a constraint that fails if ```x``` and ```mod``` have different signs:

If ```x``` assumes a negative value, ```MakeProd(MakeDiv(x, mod), mod)``` will assume a smaller **absolute value** than ```x``` (meaning a larger value than ```x```, since it is negative).
Therefore, ```result``` will assume a negative value regardless of ```mod```, causing the constraint to fail for negative ```x``` and positive ```mod```.

This operation should not add any constraints, but instead produce results with the same sign as ```mod```.
I suggest the following fix:
```cpp
IntExpr* Solver::MakeModulo(IntExpr* const x, int64_t mod) {
  IntExpr* rawResult = MakeDifference(x, MakeProd(MakeDiv(x, mod), mod));
  IntExpr* signFix = MakeProd(mod > 0 ? MakeLessOrEqual(x, 0) : MakeGreater(x, 0), mod);
  IntVar* const result = MakeSum(rawResult, signFix)->Var();
  return result;
}
```
analogue for modulo with ```IntExpr``` mod:
```cpp
IntExpr* Solver::MakeModulo(IntExpr* const x, IntExpr* const mod) {
  if (mod->Bound()) {
    return MakeModulo(x, mod->Min());
  }
  IntExpr* rawResult = MakeDifference(x, MakeProd(MakeDiv(x, mod), mod));
  IntExpr* signFix = MakeProd(MakeEquality(MakeGreater(mod, 0), MakeLessOrEqual(x, 0)), mod);
  IntVar* const result = MakeSum(rawResult, signFix)->Var();
  return result;
}
```

In any case ```rawResult``` will have the same sign as ```x```. ```signFix``` will be ```mod``` if ```x``` and ```mod``` have different signs and ```0``` otherwise.
Because of this, ```rawResult + signFix``` will always have the same sign as ```mod``` and have a smaller absolute value than ```mod```.
With this, MakeModulo will follow the python convention for modulo and the Constraints will be unnecessary.

**Comment by Mizux** [comment]
which solver (MPSolver or CP-SAT) ?

**Comment by lperron** [comment]
you should not use the original CP solver.

**Comment by TheEternalToast** [comment]
It's the CP-Solver returned by RoutingModel.solver()
And I actually used the C#-Wrapper, but the above code is copied from [https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/expressions.cc](expressions.cc) lines 7271 to 7294

**Comment by TheEternalToast** [comment]
Why should I not use the original CP solver and how do I avoid it?
You're very welcome to refer me to a discussion/issue or whereever this was mentioned, since it's not directly related to this issue

**Comment by lperron** [comment]
CP-SAT is orders of magnitude faster.

but if you are using the routing library, you must use the original solver.

Still, using modulo is rare, using modulo with negative value is just evil.
There are actually 2 conventions on the result, the C and the python one. I
do not know which one is implemented on the CP solver.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mer. 10 août 2022 à 18:22, TheEternalToast ***@***.***> a
écrit :

**Comment by TheEternalToast** [comment]
Ah okay, so there's nothing to be done about that then...

The modulo is due to a requirement that the visits must start and stop at full 15 minute windows, but their time window may not be round and refers to a (visit-specific) amount of time after the visit start...
I was able to work around allowing negative values for the dividend, but there may be other cases, where it is harder. I agree that modulo with negative values is evil. But even so, it is possible.

Currently the CP solver uses the C convention but  on making the operator it adds a constraint that fails for all values where the conventions differ. According to the docs it should use the python convention.

**Comment by TheEternalToast** [comment]
You mean the suggested fix in my initial post?

Or the workaround in my model? Because that wouldn't help you, I worked around it by modelling the problem differently...
