### ISSUE TITLE
Error with installing OR-Tools from Source on Windows 11

### ISSUE THREAD

**Issue by AugustinBassaye** [google/or-tools#3427]
**What version of OR-Tools and what language are you using?**
Version: master/v7.3/v7.2 etc.
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

**What operating system (Linux, Windows, ...) and version?**
Windows11
**What did you do?**
1. ...
2. ...
3. ...
4. No error in step \make python but 177 warning
5. See error when I run \make test_python
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0812 15:35:12.612436 16440 environment.cc:736] Found the Gurobi library in 'C:\gurobi952\win64\bin\gurobi95.dll.
F0812 15:35:12.614614 16440 dynamic_library.h:68] Check failed: function_address != nullptr Error: could not find function GRBtunemodeladv in C:\gurobi952\win64\bin\gurobi95.dll
*** Check failure stack trace: ***
make: *** [makefiles/Makefile.python.mk:58: rpy_lp_test] Error -1073740791
**What did you expect to see**
Help me to solve this error
**What did you see instead?**

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
this is fixed on 9.4
