### ISSUE TITLE
4 linear and pdlp tests fail

### ISSUE THREAD

**Issue by yurivict** [google/or-tools#3429]
**What version of OR-Tools and what language are you using?**
Version: 
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
n/a

**What operating system (Linux, Windows, ...) and version?**
FreeBSD 13.1

**What did you do?**
regular build/test

**What did you expect to see**
n/a

**What did you see instead?**
```
The following tests FAILED:
	 12 - cxx_cpp_linear_programming (Subprocess aborted)
	 13 - cxx_cpp_linear_solver_protocol_buffers (Subprocess aborted)
	 19 - cxx_cpp_pdlp_solve (Subprocess aborted)
	 31 - cxx_tests_lp_test (Subprocess aborted)
```

**Anything else we should know about your project / environment**
[LastTest.log](https://github.com/google/or-tools/files/9330122/LastTest.log)

**Comment by lperron** [comment]
most likely pdlp. To be investigated

**Comment by mlubin** [comment]
```
19/32 Testing: cxx_cpp_pdlp_solve
19/32 Test: cxx_cpp_pdlp_solve
Command: "/disk-samsung/freebsd-ports/math/or-tools/work/.build/bin/pdlp_solve"
Directory: /disk-samsung/freebsd-ports/math/or-tools/work/.build/examples/cpp
"cxx_cpp_pdlp_solve" start time: Aug 12 15:18 PDT
Output:
----------------------------------------------------------
F0812 15:18:47.733934     1 pdlp_solve.cc:76] Check failed: !input.empty() --input is required
*** Check failure stack trace: ***
<end of output>
Test time =   0.32 sec

```
As the error suggests, this test isn't set up with the correct arguments. Where is it coming from?
