### ISSUE TITLE
Specify explicit first solution for routing problem (feature request)

### ISSUE THREAD

**Issue by expz** [google/or-tools#343]
An online routing problem requires solving a sequence of problems, each of which is almost identical to the previous one. It would presumably save significant computation time if a first solution could be explicitly specified. The first solution would be a small modification of the previous problem's final solution.

It is currently possible to specify a first solution algorithm, but this is a request for a way to specify an explicit first solution. It would require functions for building/modifying explicit solutions if they don't already exist.

For reference, there is the `mips` command line option to CBC that takes the filename of a solution file (the same format as it outputs) to use as a first solution.

**Comment by furnon** [comment]
You can pass an Assignment to both RoutingModel::Solve() and
RoutingModel::SolveFromAssignmentWithParameters() methods. The assignment
you pass will be used as the first solution and will bypass any specified
first solution heuristic. Have a look here
<https://github.com/google/or-tools/blob/master/src/constraint_solver/constraint_solver.h#L5019>
to get an idea of the API of the Assignment class.
