### ISSUE TITLE
A problem with 1 variable and 2 constraints that is incorrectly infeasable

### ISSUE THREAD

**Issue by boblucas** [google/or-tools#3433]
```python
from ortools.sat.python import cp_model

model = cp_model.CpModel()
c1 = model.NewConstant(1)
c2 = model.NewConstant(2)
var = model.NewIntVar(0, 5, f'example')
# turning arround c1,c2 in this constraint makes the result OPTIMAL
model.Add(var == c1 or var == c2)
model.Add(var != c2)

solver = cp_model.CpSolver()
status = solver.Solve(model)
print(solver.StatusName(status))
```

**What version of OR-Tools and what language are you using?**
Version: main
Language: python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Reproduced on an M1 Mac and X86 ubuntu environment.

**What did you do?**
Found an unexpected infeasably result and managed to distil it to this trivial example, reproduce by just running the script presumably.

**What did you expect to see**
Model should be feasible/optimal

**Comment by boblucas** [comment]
I presume the constraint is just invalid but I "tricked" the asserts by using the constants, so you could also see this as a feature request, to throw an error in such a case.

**Comment by lperron** [comment]
This is the limit of the python typing.

I want to accept code like

if var1 == var2:
  ...

Thus the bool() operator is defined in this case and this case only.

So won't fix.

**Comment by boblucas** [comment]
Ah I see, that makes sense. Thanks for your reply.
