### ISSUE TITLE
AddMultiplicationEquality(LinearExpr target, LinearExpr left, LinearExpr right) leads to infeasibility

### ISSUE THREAD

**Issue by NicolasLook** [google/or-tools#3438]
**What version of OR-Tools and what language are you using?**
Version: 9.3.10497
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 20.04.4 LTS

**What did you do?**

Modify SearchAllSolutionsSampleSat from the guides section with the following AddMultiplicationConstraint:

        void SearchAllSolutionsSampleSat() {
            CpModelBuilder cp_model;

            IntVar v1 = cp_model.NewIntVar(Domain(2));
            LinearExpr l1 = v1;
            LinearExpr l2{};
            cp_model.AddMultiplicationEquality(l2, l1, l1);

            const Domain domain(0, 2);
            const IntVar x = cp_model.NewIntVar(domain).WithName("x");
            const IntVar y = cp_model.NewIntVar(domain).WithName("y");
            const IntVar z = cp_model.NewIntVar(domain).WithName("z");

            cp_model.AddNotEqual(x, y);

            Model model;

            int num_solutions = 0;
            model.Add(NewFeasibleSolutionObserver([&](const CpSolverResponse& r) {
                LOG(INFO) << "Solution " << num_solutions;
                LOG(INFO) << "  x = " << SolutionIntegerValue(r, x);
                LOG(INFO) << "  y = " << SolutionIntegerValue(r, y);
                LOG(INFO) << "  z = " << SolutionIntegerValue(r, z);
                num_solutions++;
            }));

            // Tell the solver to enumerate all solutions.
            SatParameters parameters;
            parameters.set_enumerate_all_solutions(true);
            model.Add(NewSatParameters(parameters));
            const CpSolverResponse response = SolveCpModel(cp_model.Build(), &model);

            LOG(INFO) << "Number of solutions found: " << num_solutions;
        }
 

**What did you expect to see**
The same set of results that is produced in the unmodified example, since l2 = 4 would still be a valid assignment.

**What did you see instead?**
Number of solutions found: 0

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
I'm working on a bigger project which uses AddMultiplicationEquality several times, in most cases it seems to work but sometimes it leads to unexpected infeasibility or segmentation faults, I wasn't able to replicate those occurrences in a small example project though.

**Comment by lperron** [comment]
you add the constraint 0 == 2 * 2 and you expect to find a feasible solution ?

**Comment by NicolasLook** [comment]
I misunderstood what AddMultiplicationEquality does then. I thought it would lead to target being assigned the value left * right (analogous to AddElement for example). What is the best way to multipy two IntVars then? As IntVar * IntVar is not valid.

**Comment by lperron** [comment]
Addelement does not create the target expression. It must be supplied.

Le jeu. 18 août 2022, 21:25, NicolasLook ***@***.***> a
écrit :

**Comment by NicolasLook** [comment]
The target expression must be supplied but AddElement leads to it being assigned the respective value, if target was just initialized with 
IntVar target = cp_model.NewIntVar(Domain(a, b)). 
If AddElement worked like AddMultiplicationConstraint, then the model would be infeasible if target didn't have the the correct value already assigned, no?

**Comment by lperron** [comment]
They both work exactly the same.

**Comment by NicolasLook** [comment]
But then how do I construct a LinearExpr instance that gets assigned the value of the product of other LinearExpr instances?

**Comment by lperron** [comment]
You give it a variable with a domain

Le jeu. 18 août 2022, 21:56, NicolasLook ***@***.***> a
écrit :

**Comment by NicolasLook** [comment]
Thank you very much.

**Comment by lperron** [comment]
Target = model.NewIntVar(...));
Model.addmultiplicationequality(target, var1, var1);

**Comment by lperron** [comment]
A simple search yields https://xiang.dev/cp-sat/#variable-product-non-linear
