### ISSUE TITLE
SetHint on IntVar for MIP solver

### ISSUE THREAD

**Issue by nhartland** [google/or-tools#3442]
**What version of OR-Tools and what language are you using?**
Version: v9.4.1874
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
SCIP

**What operating system (Linux, Windows, ...) and version?**
macos 12.5

**What did you do?**

Set solution hints for IntVars in a MIP problem:
```py
solver.SetHint([List of IntVar], [List of Integer Hints])    
```

**What did you expect to see**

The solver works ok for my problem without hints, but solutions can take a little while, I was hoping to speed the solver
up by providing an initial feasible solution.

**What did you see instead?**

The solver immediately errors out with
```py
  File "[path]/lib/python3.9/site-packages/ortools/linear_solver/pywraplp.py", line 475, in SetHint
    return _pywraplp.Solver_SetHint(self, variables, values)
TypeError: an integer is required
```

**Anything else we should know about your project / environment**

I can [see in the SCIP interface](https://github.com/google/or-tools/blob/82750ac12f1ee5354e1c7869894d9af3508778f2/ortools/linear_solver/scip_interface.cc#L762)
that solution hints are explicitly stored as a variable-double pair. I'm guessing that my (integer-valued) hints are getting cast to doubles and then passed to SCIP where the error is thrown.
https://github.com/google/or-tools/blob/82750ac12f1ee5354e1c7869894d9af3508778f2/ortools/linear_solver/scip_interface.cc#L761-L763

Is it possible to assign solution hints to IntVars for SCIP?

**Comment by lperron** [comment]
There is nothing in the code that checks for integers.
Are you sure all elements of variables are actually `Variable` ?

**Comment by Mizux** [comment]
https://github.com/google/or-tools/blob/611997a08ec2246de741155d08edda242e0a59f4/ortools/linear_solver/python/linear_solver.i#L124-L147

**Comment by Mizux** [comment]
@nhartland are you using basic python array or numpy/panda array ?

**Comment by nhartland** [comment]
All basic python arrays (I'm explicitly casting them) + should all be variables.

If there is no explicit check for integer-ness then I guess I'm on the wrong track here and there is something else going on.
Thanks for the super quick responses, I'll continue digging and come back and close if I resolve it.

**Comment by nhartland** [comment]
So I think I spotted it, the list of hints I was using was in fact a list of `numpy.int64` rather than a plain list of python `int` values. Just 

```
solver.SetHint([List of IntVar], [int(h) for h in hints])    
```

Appears to solve the problem.
