### ISSUE TITLE
Confusion about duplicate functions such as wall_time and WallTime

### ISSUE THREAD

**Issue by Zhou-Yucheng** [google/or-tools#3447]
**What version of OR-Tools and what language are you using?**
Version: main/v9.4.1874
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
linear_solver, SCIP

Hi, 
I found there are some duplicate functions with inconsistent naming format in the [reference manual](https://developers.google.com/optimization/reference/python/linear_solver/pywraplp), such as [wall_time](https://developers.google.com/optimization/reference/python/linear_solver/pywraplp#walltime)/[WallTime](https://developers.google.com/optimization/reference/python/linear_solver/pywraplp#wall_time), set_time_limit/SetTimeLimit, solution_value/SolutionValue.
I also found both of them work fine. So I'm confused why these "duplicated" functions exit (just have a different naming format of CamelCase and under_score)? Which one should I use?

**Comment by lperron** [comment]
They are exact duplicate functions.  Sorry for the confusion. You can use whatever you prefer.
