### ISSUE TITLE
Multiple GitVersions landing in gen'ed code

### ISSUE THREAD

**Issue by mwpowellhtx** [google/or-tools#345]
I noticed this while pursuing another issue. There are a couple (at least?) GitVersions landing in the gen'ed code. This makes its way through the gen'ed code, including version replacements, and is not selecting the correct value(s), i.e. version numbers, for replacement. This will eventually lead to inaccurate or destructive releases. Probably unintentional, but I just wanted to bring it to your attention in order to avert an innocent versioning disaster. Thanks!

**Comment by mwpowellhtx** [comment]
Attached for sake of artifact tracking:

[GitVersion5.1.4082.txt](https://github.com/google/or-tools/files/858790/GitVersion5.1.4082.txt)
[GitVersion5.1.4102.txt](https://github.com/google/or-tools/files/858791/GitVersion5.1.4102.txt)

Of which the 5.1.4082 file seems to be used, which is probably incorrect. At the time of build, we probably want the latest possible version, in this case 5.1.4102. I'm not sure why we would want anything but that one, i.e. the latest one, to be honest.

Hope that helps clarify.

**Comment by lperron** [comment]
No, I use GitVersion presence to decide if we need to redo the assembly
info files (version).

make printport

will print out the version of the build (along other info).
We always use this one.

--Laurent

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-03-21 12:10 GMT-04:00 Michael Powell <notifications@github.com>:

**Comment by mwpowellhtx** [comment]
@lperron Question wasn't whether it was necessary. I assumed as much. The question is which one is necessary. It seems like the older version number is being used, not the newer one. That could be a bad assumption on my part.

**Comment by lperron** [comment]
I don't think this is the case.
As I said, I check if a file that matches the current version exists, and then decide to overwrite the assemblyinfo files.

This being said, maybe I missed a dependency in the makefile. If you type make csharp, the resulting assemblyinfo version should match the info in make printport.

Thanks

**Comment by mwpowellhtx** [comment]
@lperron I'll have a second look at it. Couple of key thoughts, perhaps some steps need to be added to the clean_csharp and/or clean_third_party. In other words, that perhaps these files are piling up somehow. At minimum, would need to identify the last file. Or name the file such that the content is utilized and not the file name.

**Comment by mwpowellhtx** [comment]
@lperron I confirmed during the build, the following two files landed, one at 8:08 PM, the later one just at the end at 8:18 PM. However, the "earlier" version only is used. Shouldn't the latter version be used instead?

[GitVersion5.1.4095.txt](https://github.com/google/or-tools/files/863325/GitVersion5.1.4095.txt)
[GitVersion5.1.4119.txt](https://github.com/google/or-tools/files/863326/GitVersion5.1.4119.txt)

**Comment by Mizux** [comment]
I think this patch 76809379dff0da89b09effc33b45784c353f77d9 fix the issue.

**Comment by mwpowellhtx** [comment]
Good catch!
