### ISSUE TITLE
Install issues with make install_cc

### ISSUE THREAD

**Issue by kevinsouthxu** [google/or-tools#3455]
I build the or-tools with master branch by 
```shell
git clone -b master https://github.com/google/or-tools
```
but when I enter
```shell
make install_cc
```
it occurs
```shell
make: *** No rule to make target 'install_cc'.  Stop.
```
How do I handle this issue?

**Comment by kevinsouthxu** [comment]
The operating system is Ubuntu 18.04 with a amazon instance p3.8xlarge

**Comment by lperron** [comment]
Make install_cpp ?

**Comment by kevinsouthxu** [comment]
> Make install_cpp ?

it's also
```shell
make: *** No rule to make target 'install_cpp'.  Stop.
```

**Comment by pandermatt** [comment]
Looks like they renamed it to `cpp # Build C++ OR-Tools library`

```
make cpp
```

you can use `make | grep cpp` to list all cpp available commands

But I would recommend using the binary files, which are easier to work with: https://developers.google.com/optimization/install/cpp/linux

**Comment by Mizux** [comment]
Few thinks,
0. Everything is still in the migration process from Makefile to CMake.
1. yes, I renamed it "cpp" for  consistency
2. you can see all C++ available command using `help_cpp` target
    ```sh
    %make help_cpp
    Use one of the following C++ targets:
    help_cpp            Generate list of C++ targets with descriptions.
    detect_cpp          Show variables used to build C++ OR-Tools.
    third_party         Build OR-Tools Prerequisite
    cpp                 Build C++ OR-Tools library.
    check_cpp           Run all C++ OR-Tools samples and examples targets.
    test_cpp            Run all C++ OR-Tools test targets.
    test_fz             Run all Flatzinc test targets.
    archive_cpp         Add C++ OR-Tools to archive.
    clean_cpp           Clean C++ output from previous build.
    build               Build a C++ program.
    run                 Run a C++ program.
    test_cpp_algorithms_samples             Build and Run all C++ Algorithms Samples (located in ortools/algorithms/samples)
    test_cpp_graph_samples                  Build and Run all C++ Graph Samples (located in ortools/graph/samples)
    test_cpp_constraint_solver_samples      Build and Run all C++ CP Samples (located in ortools/constraint_solver/samples)
    test_cpp_linear_solver_samples          Build and Run all C++ LP Samples (located in ortools/linear_solver/samples)
    test_cc_model_builder_samples           Build and Run all C++ CP Samples (located in ortools/model_builder/samples)
    test_cpp_sat_samples                    Build and Run all C++ Sat Samples (located in ortools/sat/samples)
    test_cc_tests       Build and Run all C++ Tests (located in ortools/examples/tests)
    test_cc_contrib     Build and Run all C++ Contrib (located in ortools/examples/contrib)
    test_cc_cpp         Build and Run all C++ Examples (located in ortools/examples/cpp)
    test_archive_cpp    Test C++ OR-Tools archive is OK.
    ```
3. now Make only call the CMake based build under the hood
    see: https://github.com/google/or-tools/blob/0faf9251d7ef7fd00b7e14d260614f2ceea2a687/makefiles/Makefile.cpp.mk#L59-L82
    https://github.com/google/or-tools/blob/0faf9251d7ef7fd00b7e14d260614f2ceea2a687/makefiles/Makefile.port.mk#L281-L282
4. So you can notice that now we perform a local install in `install_make` directory to avoid to pollute user system.
5. If you want to perform a system wide install, you should use CMake directly and remove the `-DCMAKE_INSTALL_PREFIX=` directive
see: https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html
6. FYI, when build/run C++ test we actually create a CMake project which depends on `install_make` to found libortools.
https://github.com/google/or-tools/blob/0faf9251d7ef7fd00b7e14d260614f2ceea2a687/makefiles/Makefile.cpp.mk#L149-L192
note: see the line 175 `-DCMAKE_PREFIX_PATH=$(OR_ROOT_FULL)/$(INSTALL_DIR)` so our generated CMake project will be able to `find_package(ortools)`...

**Comment by lperron** [comment]
Regrouped into https://github.com/google/or-tools/issues/3558

Please follow up there.
