### ISSUE TITLE
OR Tools 9.4 Flatzinc release

### ISSUE THREAD

**Issue by scand1sk** [google/or-tools#3457]
Are you going to release binaries for OR-Tools FlatZinc 9.4? 
I'm particularily interested in a Debian version but the release of 9.3 for Ubuntu 20.04 works just fine on Debian Sid (> 11).
Alternatively, build instructions would be fine, too.

**Comment by Mizux** [comment]
bad news: flatzinc support in Makefile has been removed so we can't generate flatzinc archive anymore
good new: you can still build it using the CMake based build by enabling it using `-DBUILD_FLATZINC=ON`
https://github.com/google/or-tools/blob/ae7e6b59e8efb358aebc0e746fb4a261b2c1d1cc/CMakeLists.txt#L96-L97

**Comment by Mizux** [comment]
cpp archives contains a `bin/fzn-ortools` binary which should be the flatzinc binary.
Is it sufficient for you ?

**Comment by scand1sk** [comment]
Yes, the binary from the CPP archive works on my current Debian Sid installation.
Thank you very much for your input.
