### ISSUE TITLE
Not constant matrices

### ISSUE THREAD

**Issue by TeodoraBogdan** [google/or-tools#3458]
**What language and solver does this apply to?**
C++

**Describe the problem you are trying to solve.**
I am trying to solve a problem were as the car moves along the route and the cargo is unloaded by customers, its weight decreases and it can move at a faster speed.

The time of arrival at a particular point should depend on the number of route points visited by the car before this.

I know that this wasn't possible because the matrices are constant. Has this changed (maybe new feature was added that I am not aware of) or is there a way to simulate a solution for this?

Please help.

**Comment by lperron** [comment]
Currently no.

**Comment by Mizux** [comment]
In C++ you may use:
https://github.com/google/or-tools/blob/82750ac12f1ee5354e1c7869894d9af3508778f2/ortools/constraint_solver/routing.h#L598-L613
but its clunky, basically for each value in the base dimension range it will recompute the distance matrix e.g. for a N nodes problem with a load varying from 0 to 1000 (kg?) you'll end up with a 1000 `N*N` matrices... which are precomputed at the beginning of the `solve()` (aka very long warm up).

**Comment by TeodoraBogdan** [comment]
Thank you for the info!

So right now I have:
`timeCallback = m_routing->RegisterTransitCallback(
			[this](int64 from_index, int64 to_index) -> int64 {
				auto from_node = manager->IndexToNode(from_index);
				auto to_node = manager->IndexToNode(to_index);

				int64 time = 0;
				if (!m_vServiceTime.empty())
					time = m_vServiceTime[from_node.value()];
				if (!m_timeMatrix.empty())
					time += m_timeMatrix[from_node.value()][to_node.value()];

				return time;
			});
		m_routing->AddDimensionWithVehicleCapacity(timeCallback, m_stops->GetMaxWaitTime(), m_vehicles->GetEndTimes(), false, "Time");

const int64 weightsCallback = m_routing->RegisterTransitCallback(
			[weights, this](int64 from_index, int64 to_index) -> int64
			{
				auto from_node = manager->IndexToNode(from_index);
				auto to_node = manager->IndexToNode(to_index);

				return weights[from_node.value()];
			});
		m_routing->AddDimensionWithVehicleCapacity(weightsCallback, 0, m_vehicles->GetMaxWeights(), true, "Weights");`

What I have to change to make the "Time" dimension depending on the "Weights" dimenstion?

**Comment by TeodoraBogdan** [comment]
> In C++ you may use:
> 
> https://github.com/google/or-tools/blob/82750ac12f1ee5354e1c7869894d9af3508778f2/ortools/constraint_solver/routing.h#L598-L613
> 
> 
> but its clunky, basically for each value in the base dimension range it will recompute the distance matrix e.g. for a N nodes problem with a load varying from 0 to 1000 (kg?) you'll end up with a 1000 `N*N` matrices... which are precomputed at the beginning of the `solve()` (aka very long warm up).
> ref:
> 
> https://github.com/google/or-tools/blob/82750ac12f1ee5354e1c7869894d9af3508778f2/ortools/constraint_solver/routing.h#L506
> 
> 
> https://github.com/google/or-tools/blob/82750ac12f1ee5354e1c7869894d9af3508778f2/ortools/constraint_solver/routing.h#L631-L634

Thank you for the info!

So right now I have:

```
timeCallback = m_routing->RegisterTransitCallback(
			[this](int64 from_index, int64 to_index) -> int64 {
				auto from_node = manager->IndexToNode(from_index);
				auto to_node = manager->IndexToNode(to_index);

				int64 time = 0;
				if (!m_vServiceTime.empty())
					time = m_vServiceTime[from_node.value()];
				if (!m_timeMatrix.empty())
					time += m_timeMatrix[from_node.value()][to_node.value()];

				return time;
			});
		m_routing->AddDimensionWithVehicleCapacity(timeCallback, m_stops->GetMaxWaitTime(), m_vehicles->GetEndTimes(), false, "Time");

const int64 weightsCallback = m_routing->RegisterTransitCallback(
			[weights, this](int64 from_index, int64 to_index) -> int64
			{
				auto from_node = manager->IndexToNode(from_index);
				auto to_node = manager->IndexToNode(to_index);

				return weights[from_node.value()];
			});
		m_routing->AddDimensionWithVehicleCapacity(weightsCallback, 0, m_vehicles->GetMaxWeights(), true, "Weights");
```
What I have to change/add to make the "Time" dimension depending on the "Weights" dimension?

**Comment by TeodoraBogdan** [comment]
Hello! 
I need an example on how to use AddDimensionDependentDimensionWithVehicleCapacity(). Can you show me?

**Comment by lperron** [comment]
This feature is experimental and not meant to be used.

Le lun. 14 nov. 2022, 14:32, TeodoraBogdan ***@***.***> a
écrit :

**Comment by TeodoraBogdan** [comment]
I want to test it...
