### ISSUE TITLE
No rule to make target '..../libCoinUtils.la' needed by 'clp'

### ISSUE THREAD

**Issue by bryanmaina** [google/or-tools#346]
OS: `Arch Linux x86_64`
I am running into this error while trying to run `make third_party`.
```
make[2]: Entering directory '/home/dumy/Téléchargements/datastuf/or-tools/dependencies/sources/cbc-2.9.8/Clp'
Making install in src
make[3]: Entering directory '/home/dumy/Téléchargements/datastuf/or-tools/dependencies/sources/cbc-2.9.8/Clp/src'
make[3]: *** No rule to make target '/home/dumy/T\�\�l\�\�chargements/datastuf/or-tools/dependencies/sources/cbc-2.9.8/CoinUtils/src/libCoinUtils.la', needed by 'clp'.  Stop.
make[3]: Leaving directory '/home/dumy/Téléchargements/datastuf/or-tools/dependencies/sources/cbc-2.9.8/Clp/src'
make[2]: *** [Makefile:519: install-recursive] Error 1
make[2]: Leaving directory '/home/dumy/Téléchargements/datastuf/or-tools/dependencies/sources/cbc-2.9.8/Clp'
make[1]: *** [Makefile:323: install-recursive] Error 1
make[1]: Leaving directory '/home/dumy/Téléchargements/datastuf/or-tools/dependencies/sources/cbc-2.9.8'
make: *** [makefiles/Makefile.third_party.unix.mk:269: dependencies/install/bin/cbc] Error 2
```
**Extra information**
I have the following packages([follow the link](https://www.archlinux.org/groups/x86_64/coin-or/)) installed too and things aren't any different with or without them.
https://www.archlinux.org/groups/x86_64/coin-or/

**Comment by dlahlou** [comment]
Hello,

My guess is that the "Téléchargements" part in the directory name is the problem. Can you try with a name without french accents?

I hope this helps.

Driss

**Comment by bryanmaina** [comment]
Hi Driss,
It worked and I am confused about it because I have been doing this for 2 years without dealing with this error. I still have a problem with `flex` that doesn't fit to this issue. So I will close this issue and open another one if I don't figure out how to get rid of that one.

Thank you very much.
