### ISSUE TITLE
SIGBUS fault using CP-SAT solver on M1 mac with specific virtual environment configuration

### ISSUE THREAD

**Issue by tboddyspargo** [google/or-tools#3485]
**What version of OR-Tools and what language are you using?**
Version: v9.4.1874
Language: Python

> **OTHER ENVIRONMENT INFORMATION:**
>- `pyenv` installed via arm64 homebrew _no Rosetta2 emulation_
>- `python` version `3.8.13` installed via `pyenv`

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
MacOS 12.6 (Monterey)

**What did you do?**
> **NOTE:** The issue is _NOT_ reproducible with an extremely minimal set of dependencies ([ortools-working.txt](https://github.com/google/or-tools/files/9734807/ortools-working.txt)), but it _IS_ reproducible with the complete set of dependencies that my application uses (see below).

```sh
python -m venv binning-error
source binning-error/bin/activate
pip install --upgrade pip wheel
pip install optbinning==0.15.1 ortools==9.4.1874 pyarrow==5.0.0
```
Then run the following python script:
```python
# repro.py - requires pyarrow to be installed.
import optbinning
from ortools.sat.python import cp_model

print("testing cp_model.CpSolver()")
model = cp_model.CpModel()
num_vals = 3
x = model.NewIntVar(0, num_vals - 1, 'x')
y = model.NewIntVar(0, num_vals - 1, 'y')
z = model.NewIntVar(0, num_vals - 1, 'z')
model.Add(x != y)
solver = cp_model.CpSolver()
print("Running solver.Solve(model)")
# NOTE: The following line will provoke a SIGBUS Fault
status = solver.Solve(model)
print(status)
```

> **IMPORTANT:** If you simply comment out the `import optbinning`, the issue goes away. If you leave `import optbinning` and uninstall `pyarrow`, the issue goes away.

**What did you expect to see**
I expected to see the continuous optimal binner complete successfully.

**What did you see instead?**
The process crashed with a `SIGBUS` fault.

Make sure you include information that can help us debug (full error message, model Proto).
My apologies, but don't understand enough about the model creation to create a reproduction without using `optbinning`.

**Anything else we should know about your project / environment**

**Comment by tboddyspargo** [comment]
**UPDATE** I was able to get some help creating a more targeted reproduction example. I'm working on trimming down the dependencies of the repro to make it easier to track down the issue. 

If you simply comment out the `import optbinning` in the repro example, then the issue goes away. I think this indicates a weird package import/initialization conflict between `ortools` and one of the other packages.

**Comment by tboddyspargo** [comment]
**UPDATE:**

I was able to find the key variable! The issue is reproducible if `pyarrow` is installed in the environment and if `optbinning` has been imported. If `pyarrow` is not installed, then the issue cannot be reproduced (or if it _is_ installed, but `optbinning` isn't imported). I will update the reproduction example in the main issue description.

Here's a more straightforward reproduction:
```sh
python -m venv binning-error
source binning-error/bin/activate
pip install --upgrade pip wheel
pip install optbinning pyarrow
```
Then run the following python script:
```python
# repro.py - requires pyarrow to be installed.
import optbinning
from ortools.sat.python import cp_model

print("testing cp_model.CpSolver()")
model = cp_model.CpModel()
num_vals = 3
x = model.NewIntVar(0, num_vals - 1, 'x')
y = model.NewIntVar(0, num_vals - 1, 'y')
z = model.NewIntVar(0, num_vals - 1, 'z')
model.Add(x != y)
solver = cp_model.CpSolver()
print("Running solver.Solve(model)")
# NOTE: The following line will provoke a SIGBUS Fault
status = solver.Solve(model)
print(status)
```

When running these tests with `python`'s `-v` option, we can see the following extra import behaviors in the "failure" scenarios:
```
# ~/venv-test2/lib/python3.8/site-packages/pyarrow/__pycache__/__init__.cpython-38.pyc matches ~/venv-test2/lib/python3.8/site-packages/pyarrow/__init__.py
# code object from '~/venv-test2/lib/python3.8/site-packages/pyarrow/__pycache__/__init__.cpython-38.pyc'
# ~/venv-test2/lib/python3.8/site-packages/pyarrow/__pycache__/_generated_version.cpython-38.pyc matches ~/venv-test2/lib/python3.8/site-packages/pyarrow/_generated_version.py
# code object from '~/venv-test2/lib/python3.8/site-packages/pyarrow/__pycache__/_generated_version.cpython-38.pyc'
import 'pyarrow._generated_version' # <_frozen_importlib_external.SourceFileLoader object at 0xFAKE_ADDRESS>
# extension module 'pyarrow.lib' loaded from '~/venv-test2/lib/python3.8/site-packages/pyarrow/lib.cpython-38-darwin.so'
# ~/venv-test2/lib/python3.8/site-packages/pyarrow/__pycache__/util.cpython-38.pyc matches ~/venv-test2/lib/python3.8/site-packages/pyarrow/util.py
# code object from '~/venv-test2/lib/python3.8/site-packages/pyarrow/__pycache__/util.cpython-38.pyc'
import 'pyarrow.util' # <_frozen_importlib_external.SourceFileLoader object at 0xFAKE_ADDRESS>
# extension module 'pyarrow.lib' executed from '~/venv-test2/lib/python3.8/site-packages/pyarrow/lib.cpython-38-darwin.so'
import 'pyarrow.lib' # <_frozen_importlib_external.ExtensionFileLoader object at 0xFAKE_ADDRESS>
# extension module 'pyarrow._hdfsio' loaded from '~/venv-test2/lib/python3.8/site-packages/pyarrow/_hdfsio.cpython-38-darwin.so'
# extension module 'pyarrow._hdfsio' executed from '~/venv-test2/lib/python3.8/site-packages/pyarrow/_hdfsio.cpython-38-darwin.so'
import 'pyarrow._hdfsio' # <_frozen_importlib_external.ExtensionFileLoader object at 0xFAKE_ADDRESS>
# ~/venv-test2/lib/python3.8/site-packages/pyarrow/__pycache__/hdfs.cpython-38.pyc matches ~/venv-test2/lib/python3.8/site-packages/pyarrow/hdfs.py
# code object from '~/venv-test2/lib/python3.8/site-packages/pyarrow/__pycache__/hdfs.cpython-38.pyc'
# ~/venv-test2/lib/python3.8/site-packages/pyarrow/__pycache__/filesystem.cpython-38.pyc matches ~/venv-test2/lib/python3.8/site-packages/pyarrow/filesystem.py
# code object from '~/venv-test2/lib/python3.8/site-packages/pyarrow/__pycache__/filesystem.cpython-38.pyc'
import 'pyarrow.filesystem' # <_frozen_importlib_external.SourceFileLoader object at 0xFAKE_ADDRESS>
import 'pyarrow.hdfs' # <_frozen_importlib_external.SourceFileLoader object at 0xFAKE_ADDRESS>
# ~/venv-test2/lib/python3.8/site-packages/pyarrow/__pycache__/ipc.cpython-38.pyc matches ~/venv-test2/lib/python3.8/site-packages/pyarrow/ipc.py
# code object from '~/venv-test2/lib/python3.8/site-packages/pyarrow/__pycache__/ipc.cpython-38.pyc'
import 'pyarrow.ipc' # <_frozen_importlib_external.SourceFileLoader object at 0xFAKE_ADDRESS>
# ~/venv-test2/lib/python3.8/site-packages/pyarrow/__pycache__/serialization.cpython-38.pyc matches ~/venv-test2/lib/python3.8/site-packages/pyarrow/serialization.py
# code object from '~/venv-test2/lib/python3.8/site-packages/pyarrow/__pycache__/serialization.cpython-38.pyc'
import 'pyarrow.serialization' # <_frozen_importlib_external.SourceFileLoader object at 0xFAKE_ADDRESS>
# ~/venv-test2/lib/python3.8/site-packages/pyarrow/__pycache__/types.cpython-38.pyc matches ~/venv-test2/lib/python3.8/site-packages/pyarrow/types.py
# code object from '~/venv-test2/lib/python3.8/site-packages/pyarrow/__pycache__/types.cpython-38.pyc'
import 'pyarrow.types' # <_frozen_importlib_external.SourceFileLoader object at 0xFAKE_ADDRESS>
import 'pyarrow' # <_frozen_importlib_external.SourceFileLoader object at 0xFAKE_ADDRESS>
...
# ~/venv-test2/lib/python3.8/site-packages/pyarrow/__pycache__/compute.cpython-38.pyc matches ~/venv-test2/lib/python3.8/site-packages/pyarrow/compute.py
# code object from '~/venv-test2/lib/python3.8/site-packages/pyarrow/__pycache__/compute.cpython-38.pyc'
# extension module 'pyarrow._compute' loaded from '~/venv-test2/lib/python3.8/site-packages/pyarrow/_compute.cpython-38-darwin.so'
# extension module 'pyarrow._compute' executed from '~/venv-test2/lib/python3.8/site-packages/pyarrow/_compute.cpython-38-darwin.so'
import 'pyarrow._compute' # <_frozen_importlib_external.ExtensionFileLoader object at 0xFAKE_ADDRESS>
import 'pyarrow.compute' # <_frozen_importlib_external.SourceFileLoader object at 0xFAKE_ADDRESS>
# ~/venv-test2/lib/python3.8/site-packages/pandas/core/arrays/arrow/__pycache__/_arrow_utils.cpython-38.pyc matches ~/venv-test2/lib/python3.8/site-packages/pandas/core/arrays/arrow/_arrow_utils.py
# code object from '~/venv-test2/lib/python3.8/site-packages/pandas/core/arrays/arrow/__pycache__/_arrow_utils.cpython-38.pyc'
import 'pandas.core.arrays.arrow._arrow_utils' # <_frozen_importlib_external.SourceFileLoader object at 0xFAKE_ADDRESS>
```

When `pyarrow` is uninstalled, or `optbinning` isn't imported, then those extra import behaviors are not present.

This is an odd interaction between modules given that `pyarrow` is not a dependency of `ortools` or `optbinning`. I'm not exactly sure what's reasonable in terms of next steps. Does this indicate a problem that `numpy` or `pyarrow` should address, or is it possible for `ortools` or `optbinning` to isolate themselves from this particular side-effect?

**Comment by tboddyspargo** [comment]
**UPDATE:** The version of `pyarrow` matters. I'm unable to reproduce the issue if I use `pyarrow==9.0.0` but using `pyarrow==6.0.1` (from my application's original lockfile) will provoke the problematic behavior.

I think this indicates a problem ultimately related to the version of `numpy` that was used to build `pyarrow` vs what's available in the runtime environment, but it's still surprising to me that this impact is felt given that `pyarrow` is not a direct dependency of `optbinning` or `ortools`.

**Comment by lperron** [comment]
don't know. But the M1 transition was not smooth for python. 
I suspect the pinned version forced an intel version of numpy. We had a crash like ths reported before.

Thanks. I will close the issue know.

**Comment by Mizux** [comment]
IIRC conda forge maintainer @BastianZim have to perform some pinning for numpy. Since or-tools end numpy will try to interoperate at C++/binary level to share matrix/vector you may have some hidden ABI constraint between both...
