### ISSUE TITLE
Elaborate on Constraint Solver ExportModel API

### ISSUE THREAD

**Issue by mwpowellhtx** [google/or-tools#349]
Following on from general [serialization](http://github.com/google/or-tools/issues/325) issue. Provide non-ConstraintSolverParameter-bound ExportModel API.

**Comment by mwpowellhtx** [comment]
Closed initial pass at solution PR. I like the [simplified CpModel return approach](http://github.com/google/or-tools/commit/15bc5959cd7f42e5aff3f0309cd2cd2d5a7d5c18) much better. It's cleaner and leverages .NET side client streams.

**Comment by mwpowellhtx** [comment]
@lperron Found a *MergeFrom* opposite the *WriteTo* extension method. There are a couple of non-trivial implications of exporting/loading models that needs to be address I think.

**Comment by yingzong** [comment]
This and the reference issue are very interesting and useful. Any more progress on that?
