### ISSUE TITLE
AttributeError: 'ortools.model_builder.python.pywrap_model_builder_' object has no attribute 'EnableOutput'

### ISSUE THREAD

**Issue by torressa** [google/or-tools#3490]
**What version of OR-Tools and what language are you using?**
Version: v9.4
Language: Python

**Which solver are you using: none error from model_builder**

**What did you do?**

To replicate: 

```python
from ortools.model_builder.python.model_builder import ModelSolver

solver = ModelSolver("glop")
solver.enable_output(True)
```

https://github.com/google/or-tools/blob/82750ac12f1ee5354e1c7869894d9af3508778f2/ortools/model_builder/python/model_builder.py#L930 

Needs to be `self.__solve_helper.enable_output(enabled)`

**Comment by lperron** [comment]
Fixed on main.
