### ISSUE TITLE
Issue with the "Get started" guide for cpp

### ISSUE THREAD

**Issue by IIKris** [google/or-tools#3494]
**What version of OR-Tools and what language are you using?**
Version: v9.4
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 22.04

**What did you do?**
1. used command `sudo apt install build-essential zlib1g-dev`
2. Installed binaries as described [here](https://developers.google.com/optimization/install/cpp/linux) and executed command `make test` successfully
3. Copy and pasted the program from [here](https://developers.google.com/optimization/introduction/cpp) into the folder `opt_03` 
4. used `~/opt_03/or-tools# make build SOURCE="../program.cc"`

**What did you expect to see**
Nothing

**What did you see instead?**
make: *** No rule to make target 'examples/program/CMakeLists.txt', needed by 'build'.  Stop.

**Comment by lperron** [comment]
make build and make run are only defined for a few directories. It does not support compiling from everywhere.
There are 2 approaches:
  - move program.cc to examples/contrib
  - have a full cmake project (see https://github.com/or-tools/cmake_or-tools) and compile you project that will fetch or-tools

**Comment by lperron** [comment]
Note: make is going away in the next release.
