### ISSUE TITLE
Trouble Running Solver Under IIS

### ISSUE THREAD

**Issue by orwant** [google/or-tools#35]
Originally reported on Google Code with ID 19

```
I have built a .net project under Visual Studio 12, and with the 32-bit version (the
development web server with Visual Studio is 32 bit), I am able to run my web application
in debug mode. However, when I publish it to a web server running IIS on Windows Server
2008 (IIS 7.5), on running the web site I get the following error:

Could not load file or assembly 'Google.OrTools.LinearSolver.DLL' or one of its dependencies.
The specified module could not be found

I have tried all permutations of the following:

* 32/64 bit versions of the tool
* project compile to platform target CPU (any, 86, 64 - in both debug and release (used
for publishing a web application) configurations)
* IIS application pool allow 32-bit applications, and app-pool (and application) restarted

Has anyone else managed to get it working in IIS, please?

To reproduce the issue:

* add the DLL as a reference to a .NET project
* in a C# file in the project, add: using Google.OrTools.LinearSolver
* in the same file, add: Solver solver = Solver.CreateSolver("IntegerProgramming",
"CBC_MIXED_INTEGER_PROGRAMMING");
* publish the application to an IIS web server
* try to open the application in a browser
```

Reported by `GLaight` on 2013-01-23 14:31:28

**Comment by viruslab1** [comment]
The library does not work on IIS Express. I can not imagine what I'm doing wrong.
Throws an error - "Could not load file or assembly" Google.OrTools "or one of its dependencies attempt was made to load a program with an incorrect format.".

**Comment by lperron** [comment]
I would expect 64b versus 32b libraries.
Alternatively, we require visual studio redistributables libraries. (vs2013
or vs2015 depending on the archive you used, or the compiler you used.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-03-02 13:27 GMT+01:00 viruslab1 <notifications@github.com>:

**Comment by viruslab1** [comment]
It really helped! I changed the ISS on x64 in Visual Studio options and it worked! 
Thank you.

**Comment by GuyBenhaim** [comment]
Hello,
I'm experiencing a similar issue. IIS crashes immediately when creating or calling the Solver model. 
Both in IIS and IIS express. I believe all the parameters are set correctly to 64-bit:  VS build (x64) and IIS application pool (32-bit =false).
I removed all old version of Visual C++ Redistributable Package and installed 64-bit for VS2015.

Any tips?

**Comment by AaronLangley** [comment]
Hi @GuyBenhaim ,  any tips on how did you solve your problem?

**Comment by GuyBenhaim** [comment]
As far as I remember, there was an issue of providing a wrong vector of start points for the vehicles, the other was to make sure all settings are 64b :  IIS, Project Properties in VS
