### ISSUE TITLE
Very long time after the search process

### ISSUE THREAD

**Issue by Seldnor** [google/or-tools#3509]
I'm using CP-SAT v9.4.1874 in Windows with quite a large problem ( ~3M variables ), and I have a weird issue after the solving process.
I can see that the algorithm found a solution within the time limit on the logs, I can see the default statistics on the logs but it is sort of stuck there (up to "Clauses shared per subsolver") and still running for 12 hours now and I can't access the values of the solution. 

It happened before that it was stuck at this step for few minutes/hours before but never that long. 

![image](https://user-images.githubusercontent.com/45877549/196950928-1107e84f-0042-4c1f-92e9-63df158ecc1f.png)

**Comment by lperron** [comment]
We fixed a few issues after 9.4. can you send me the proto of the model ?

**Comment by Seldnor** [comment]
What do you mean by proto of the model ? 
By the way, it finally finished after 20 hours.

**Comment by lperron** [comment]
yes, the proto of the model.
Can you also send me the beginning of the log (with the model statistics)?
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by Seldnor** [comment]
![image](https://user-images.githubusercontent.com/45877549/197200207-cb634a69-bf39-410e-ab99-c9e431c76740.png)

You mean the code with all the variables and constraints ?

**Comment by lperron** [comment]
No news. Please reopen is the problem persists.
