### ISSUE TITLE
The Assignment variable : `solution `  returns **null** whenever the vehicle number is less than 4. 

### ISSUE THREAD

**Issue by azaharudue** [google/or-tools#3518]
Hi, 
For a time window dependent VRP task I encountered a problem, 
The Assignment variable : `solution `  returns **null** whenever the vehicle number is less than 4. 
For testing simple case, 
I was trying to run the [example in documentation]( https://developers.google.com/optimization/routing/vrptw) too just like @ra-esmith mentioned [here](https://github.com/google/or-tools/discussions/3385?sort=top#discussion-4225465)
But in my case I didn't change anything other than just the vehicleNumber reducing  from 4 to 1. 
Could anyone please help me out in this issue ?

_Originally posted by @azaharudue in https://github.com/google/or-tools/discussions/3385#discussioncomment-3964974_

**Comment by Regista6** [comment]
print(routing.status()) gives 2 which means ROUTING_FAIL: No solution found to the problem, that's why solution is null.

**Comment by lperron** [comment]
it means the problems cannot drop nodes, and they cannot all fit. So there
is no feasible solution.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mer. 26 oct. 2022 à 10:10, Azahar Hossain ***@***.***> a
écrit :
