### ISSUE TITLE
Add Random Restart local search meta-heuristic

### ISSUE THREAD

**Issue by rc-eddy** [google/or-tools#352]
Would it be possible to add the "random restart" heuristic to local search meta-heuristics and a simple "random" as a first solution strategy to the vehicle routing problem solver? It's a very simple and efficient technique to avoid local minima.

As an alternative, what's the simplest way to reset the routing solution after an assignment has been found in Python?

**Comment by lperron** [comment]
I suggest to just use greedy descent as meta-heuristics, then generate your random first solution using random tree search (or any heuristics). And then launch greedy descent alone, after each random solution.
