### ISSUE TITLE
Building from source failing

### ISSUE THREAD

**Issue by nicktrav** [google/or-tools#353]
Running through the installation guide, I'm running into an incorrect path when building the `thrid_party` target:

```bash
$ make third_party
... snip ...
+ autoreconf -f -i -Wall,no-obsolete
aclocal: error: configure.ac:1: file 'gtest/m4/acx_pthread.m4' does not exist
autoreconf: aclocal failed with exit status: 1
```

The following diff fixed it for me:

```
$ diff dependencies/sources/protobuf-3.0.0/gmock/configure.ac{.old,}
1c1
< m4_include(gtest/m4/acx_pthread.m4)
---
> m4_include(../m4/acx_pthread.m4)
```

This seems to be in the protobuf source, which is a dependency, so I'm not sure if the issue is with the build for this repo, or somewhere else.

Platform: OS X 10.12.1
Building from master, as well as v5.1.

**Comment by lperron** [comment]
I updated the protobuf requirement to 3.2.0.

Can you retry?

**Comment by nicktrav** [comment]
Looks good! Thanks for looking into it!
