### ISSUE TITLE
FlatZinc: --num_solutions command line argument has no effect

### ISSUE THREAD

**Issue by lr210** [google/or-tools#3532]
The --num-solutions command line argument has no effect, with only a single solution being generated. Using --all_solutions works correctly and produces multiple solutions.

**Comment by lperron** [comment]
We only support the minimum for the minizinc challenge.
I do not plan to support --num-solutions. PR welcome :-)

**Comment by lr210** [comment]
Thanks for the reply. The help message indicates that --num_solutions is supported. Would it be possible to update this?
