### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by jeremydover** [google/or-tools#3535]
**What language and solver does this apply to?**
Python 3.11

**Describe the problem you are trying to solve.**
Installation of ortools via pip

**Describe the solution you'd like**
pip install ortools works to install package

**Describe alternatives you've considered**
downgrading to python 3.10

**Additional context**
Just bad luck on my part...got a new computer yesterday, and in setting up my environment, I got the newly released python version. I'd rather not downgrade if I can avoid it, but ortools is my main use case.

**Comment by lperron** [comment]
Duplicate
