### ISSUE TITLE
MPSolver (Gurobi) crashes when running multiple instances in parallel

### ISSUE THREAD

**Issue by skollmann** [google/or-tools#354]
When running multiple instances of MPSolver from different threads (using Gurobi from Java on Linux), I sometimes experience random crashes in the native part of the code. For example:

`src/linear_solver/gurobi_interface.cc:178: Error: could not create environment: User name mismatch (licensed to 'stephan', current user is 'list')` (other times, "list" is replaced by random parts of /etc/passwd, and other times it crashes in other ways)

Is running multiple MPSolver instances in parallel supported?

**Comment by lperron** [comment]
knowing gurobi licenses, I am not sure.

**Comment by skollmann** [comment]
I don't think the (named user) license disallows this ("Single machine license for a single named person/**unlimited simultaneous uses**."). 
This looks like an or-tools issue as I have not had any such problems when using multiple Gurobi instances simultaneously using the Gurobi Java API.

**Comment by lperron** [comment]
I guess creating the gurobi env is not MT-Safe.
You need to protect the creation of the linear solver my a mutex.
