### ISSUE TITLE
wall_time() returns the sum of times to build and to solve the model ?

### ISSUE THREAD

**Issue by AhmedKhassiba** [google/or-tools#3544]
**What version of OR-Tools and what language are you using?**
Version: main/v9.3 
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
SCIP

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
I build an optimization model through: 
solver = pywraplp.Solver.CreateSolver('SCIP')

I add variables, constraints, and an objective.

I call the function wall_time():
cpu = solver.wall_time()

**What did you expect to see**
Since I do not call the solve function, I expect that cpu = 0.000 sec. 

**What did you see instead?**
The value returned by wall_time() is not null (zero). It equals to the time spent building the model/ Solver object.

1. Is there any function to get only the solve time, or should I use Python module "time" instead ?

Additional question:
2. When I solve my problem after setting a time limit through Solver.set_time_limit(tilim), is the time limit passed to the solver (SCIP in my case) equal to tilim or to (tilim - build time) ? 

Thank you very much for your help.

**Comment by lperron** [comment]
1) this is by design. It is especially important for python as it is very slow
2) tilim
