### ISSUE TITLE
Cp-sat solver fails with Check failed: SolutionIsFeasible after first solution

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#3547]
**What version of OR-Tools and what language are you using?**
Version: main (maven version 9.5.2191)
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 11

**What did you do?**
Execute attached proto file with interleave search.

**What did you expect to see**
No fail.

**What did you see instead?**

Starting deterministic search at 3.21s with 16 workers.
8 full subsolvers: [default_lp, fixed, no_lp, max_lp, reduced_costs, pseudo_costs, quick_restart, quick_restart_no_lp]
Interleaved subsolvers: [rnd_var_lns_default, rnd_cst_lns_default, graph_var_lns_default, graph_cst_lns_default, scheduling_random_intervals_lns_default, scheduling_random_precedences_lns_default, scheduling_time_window_lns_default, scheduling_resource_windows_lns_default]
Setting number of tasks in each batch of interleaved search to 48
#Bound 431.11s best:inf   next:[3267,94144] reduced_costs initial_propagation
#1     431.91s best:4446  next:[3267,4445] quick_restart_no_lp fixed_bools:0/12792
Check failed: SolutionIsFeasible( model_proto, std::vector<int64_t>(response->solution().begin(), response->solution().end()), &mapping_proto, &postsolve_mapping) postsolved solution
*** Check failure stack trace: ***
    @   00007FFD0150A3CD  (unknown)
    @   00007FFD01509889  (unknown)
    @   00007FFD015553EC  (unknown)
    @   00007FFD018331AF  (unknown)
    @   00007FFD018351E2  (unknown)
    @   00007FFD01554599  (unknown)
    @   00007FFD018E5C67  (unknown)
    @   00007FFD01566A9A  (unknown)
    @   00007FFD01550C5B  (unknown)
    @   00007FFD018F64C4  (unknown)
    @   00007FFD018F5B0F  (unknown)
    @   00007FFD71689363  (unknown)
    @   00007FFD71F6244D  (unknown)
    @   00007FFD73A4DFB8  (unknown)

Process finished with exit code -1073740791 (0xC0000409)

[proto.zip](https://github.com/google/or-tools/files/9995307/proto.zip)

**Comment by lperron** [comment]
I am trying to reproduce, without any success currently.
non-interleaved search will have a much better performance.

**Comment by gregy4** [comment]
I found that number of search workers should be 2 or more.
Yes, non-interleaved search is much faster/

**Comment by lperron** [comment]
tried with 2, 16...
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by gregy4** [comment]
Reproduced on different cpu and debian 11.

[execute_proto.zip](https://github.com/google/or-tools/files/9998123/execute_proto.zip)

**Comment by lperron** [comment]
examples/cpp/sat_runner.cc can already solve all CP-SAT protos
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by lperron** [comment]
We just fixed a bug that can affect your problem. Can you rebuild and retry on HEAD ?

**Comment by gregy4** [comment]
It didn't helped in debian 11. It fails everytime.

By the way bulding of sat_runner.cc via make build SOURCE=examples/cpp/sat_runner.cc fails with fatal error: examples/cpp/opb_reader.h: No such file or directory

**Comment by lperron** [comment]
mkdir build
cd build
cmake -DBUILD_DEPS=ON ..
make -j 8

sat_runner should be in bin/
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by lperron** [comment]
I still cannot reproduce the bug. 

On a side note, please have a look at the rcpsp_sat.py example, and in particular at the makespan interval.
This special construct is recognized by the solver, and should help solving the problem.

**Comment by gregy4** [comment]
Thanks, I will look at it.

I checked it again, my code (execute_proto) found an error. With sat_runner I wasn't successful.

Finally I found that error depends on presence of solution callback, in case it is used the error is present. Otherwise not.

[runproto_java.zip](https://github.com/google/or-tools/files/10066781/runproto_java.zip)

**Comment by gregy4** [comment]
Can you reproduce it ?  I reproduced it again on another debian (freshly installed), it fails everytime.

**Comment by lperron** [comment]
I have not looked at the java version, so no.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by gregy4** [comment]
Today verified in c++ in 9.5 and another model, when I commented adding of NewFeasibleSolutionObserver to a model everything worked.

**Comment by ozan-cb** [comment]
I am hitting the same problem, and can reproduce it on two different machines (on a Mac and a Linux). It does seem like it's related to adding `NewFeasibleSolutionObserver` indeed, and it only happens with interleaved search with at least 3 workers.

Moreover, setting FLAGS_v level to 1 shows this error:
```
I1219 08:51:55.740993  2369 cp_model_checker.cc:1537] Wrong number of variables (178) in the solution vector. It should be 126.
```
where 126 is the number of variables in the model, and 178 is the number of variables in the preprocessed model. It feels like the solution found by one of the workers is not mapped to the original variables.

Please see the attached proto, the log, and the runner Python script pasted below.
[model.proto.txt](https://github.com/google/or-tools/files/10261644/model.proto.txt)
[output.log](https://github.com/google/or-tools/files/10261689/output.log)

```python3
import sys

from ortools.sat.python import cp_model
from google.protobuf import text_format

class Callback(cp_model.CpSolverSolutionCallback):
    def on_solution_callback(self):
        pass

filename = sys.argv[1]

model = cp_model.CpModel()
text_format.Parse(open(filename).read(), model.Proto())

s = cp_model.CpSolver()
s.parameters.num_search_workers = 3
s.parameters.interleave_search = True
s.parameters.interleave_batch_size = 3
s.parameters.log_search_progress = True

callback = Callback()
s.Solve(model, callback)
```

**Comment by lperron** [comment]
Thanks, I can reproduce in C++ with parameters and without a callback

interleave_search:true,num_search_workers:3,stop_after_first_solution:true,interleave_batch_size:3,log_search_progress:true
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le lun. 19 déc. 2022 à 19:16, Ozan Erdem ***@***.***> a
écrit :
