### ISSUE TITLE
Current OR-Tools version not working with Gurobi 10

### ISSUE THREAD

**Issue by RichardOberdieck** [google/or-tools#3548]
**What version of OR-Tools and what language are you using?**
Version: main
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Gurobi

**What operating system (Linux, Windows, ...) and version?**
Linux (in a docker container on a mac)

**What did you do?**
Consider the following Dockerfile:
```Dockerfile
FROM gurobi/optimizer:10.0.0

RUN pip install ortools

COPY test.py test.py
COPY gurobi.lic /opt/gurobi/gurobi.lic
RUN python test.py
```

The file `test.py` looks as follows:
```python
from ortools.linear_solver import pywraplp


solver = pywraplp.Solver.CreateSolver('Gurobi')
infinity = solver.infinity()
# x and y are integer non-negative variables.
x = solver.IntVar(0.0, infinity, 'x')
y = solver.IntVar(0.0, infinity, 'y')
solver.Add(x + 7 * y <= 17.5)

# x <= 3.5.
solver.Add(x <= 3.5)
solver.Maximize(x + 10 * y)
status = solver.Solve()
```

The file `gurobi.lic` is the Gurobi license file.

**What did you expect to see**
That it runs without an exception.

**What did you see instead?**

If you run this with `docker build -t test .`, then the following exception is thrown:

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1116 08:39:36.348453     7 linear_solver.cc:625] Support for Gurobi not linked in, or the license was not found.
Traceback (most recent call last):
  File "/opt/gurobi/linux64/test.py", line 5, in <module>
    infinity = solver.infinity()
AttributeError: 'NoneType' object has no attribute 'infinity'
```

However, if we change the image to `gurobi/optimizer:9.5.2`, then it works

**Comment by Mizux** [comment]
https://github.com/google/or-tools/blob/82750ac12f1ee5354e1c7869894d9af3508778f2/ortools/gurobi/environment.cc#L659-L662

**Comment by RichardOberdieck** [comment]
`/opt/gurobi/linux64/lib/libgurobi.so.10.0.0`

**Comment by lperron** [comment]
Still, you can specify the full path to the library manually.

ortools.init.CppBridge.LoadGurobiSharedLibrary('full path to library')
