### ISSUE TITLE
install issue on Windows

### ISSUE THREAD

**Issue by frascaria** [google/or-tools#3549]
**What version of OR-Tools and what language are you using?**
Version: tried both main and stable
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Gurobi

**What did you do?**
1. followed this guide https://developers.google.com/optimization/install/python/source_windows until the point 'tools\make third_party'
2. this gives me error (see attached file)

**What did you expect to see**
successful initiallization

**What did you see instead?**
  Completed 'zlib-populate'
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for 'C:\or-tools-stable\build_make\_deps\zlib-subbuild\CMakeFiles\333cfe941636ee85928db688745cc5b4\zlib-populate-mkdir.rule;C:\or-tools-stable\build_make\_deps\zlib-subbuild\CMakeFiles\333cfe941636ee85928db688745cc5b4\zlib-populate-download.rule;C:\or-tools-stable\build_make\_deps\zlib-subbuild\CMakeFiles\333cfe941636ee85928db688745cc5b4\zlib-populate-patch.rule;C:\or-tools-stable\build_make\_deps\zlib-subbuild\CMakeFiles\333cfe941636ee85928db688745cc5b4\zlib-populate-configure.rule;C:\or-tools-stable\build_make\_deps\zlib-subbuild\CMakeFiles\333cfe941636ee85928db688745cc5b4\zlib-populate-build.rule;C:\or-tools-stable\build_make\_deps\zlib-subbuild\CMakeFiles\333cfe941636ee85928db688745cc5b4\zlib-populate-install.rule;C:\or-tools-stable\build_make\_deps\zlib-subbuild\CMakeFiles\333cfe941636ee85928db688745cc5b4\zlib-populate-test.rule;C:\or-tools-stable\build_make\_deps\zlib-subbuild\CMakeFiles\8708551589a2279ccd65d66c72dad5db\zlib-populate-complete.rule;C:\or-tools-stable\build_make\_deps\zlib-subbuild\CMakeFiles\a7eff27e30ce7217ae96681c8f33a804\zlib-populate.rule;C:\or-tools-stable\build_make\_deps\zlib-subbuild\CMakeLists.txt' exited with code -1. [C:\or-tools-stable\build_make\_deps\zlib-subbuild\zlib-populate.vcxproj]
CMake Error at C:/Program Files/CMake/share/cmake-3.25/Modules/FetchContent.cmake:1616 (message):
  Build step for zlib failed: 1
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.25/Modules/FetchContent.cmake:1756:EVAL:2 (__FetchContent_directPopulate)
  C:/Program Files/CMake/share/cmake-3.25/Modules/FetchContent.cmake:1756 (cmake_language)
  C:/Program Files/CMake/share/cmake-3.25/Modules/FetchContent.cmake:1970 (FetchContent_Populate)
  cmake/dependencies/CMakeLists.txt:68 (FetchContent_MakeAvailable)

-- Configuring incomplete, errors occurred!
See also "C:/or-tools-stable/build_make/CMakeFiles/CMakeOutput.log".
make: *** [makefiles/Makefile.cpp.mk:60: third_party] Error 1

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
[CmakeOutputlog.txt](https://github.com/google/or-tools/files/10019861/CmakeOutputlog.txt)

**Comment by Mizux** [comment]
Are you sure to provide the full CMakeOutput.log ?  I can't see any error in the trace.

Otherwise try to use the main branch and build using the CMake based build directly.
see: https://github.com/google/or-tools/blob/main/cmake/README.md

**Comment by lperron** [comment]
Regrouped into https://github.com/google/or-tools/issues/3558
