### ISSUE TITLE
Possible incorrect input of pdptw example data

### ISSUE THREAD

**Issue by jmarca** [google/or-tools#355]
in the pdptw example, the data input code make the demand quantity negative if the node is a delivery node.  Specifically, line https://github.com/google/or-tools/blame/master/examples/cpp/pdptw.cc#L223 says:

```
const int64 demand = delivery == 0 ? -parsed_int[3] : parsed_int[3];
```

**However** in the example pdptw data files, the demand appears to be negative already when the node is a delivery node.  For example, from file https://github.com/google/or-tools/blob/master/examples/data/pdptw/lc108.txt, 

```
25	200	1
0	40	50	0	0	1236	0	0	0
1	45	68	-10	912	967	90	11	0
2	45	70	-20	825	870	90	6	0
3	42	66	10	65	146	90	0	75
4	42	68	-10	727	782	90	9	0
5	42	65	10	15	67	90	0	7
6	40	69	20	621	702	90	0	2
7	40	66	-10	170	225	90	5	0
8	38	68	20	255	324	90	0	10
...
```

Customer 5 is a pickup, with a demand of 10 and a destination at customer 7.  Customer 7 in turn has a demand of -10.

Similarly in all of the other files that I spot checked.  There are too many files to check them all by hand. 

The docs on the sintec site say nothing about this convention.  

It appears that the code was written as if the demand quantities were expected to all be positive, such that the accumulator will add a positive number at the pickup, and add a negative number at delivery.  What is happening in practice is the line of code referenced above makes the delivery demand quantity positive, which in turn means that the vehicle just adds more and more until it hits capacity.

What I expect is that at the end of the tour, each vehicle should have zero goods on board, as all pickups must be paired with a delivery.  What is happening in practice is the quantity on board increases at all steps of the tour.

Given the current formulation, the output of running the model on lc101.txt is as follows (just showing the vehicle that picks up and delivers node 5 to node 7:

```
james@emma or-tools[master]$ ./bin/pdptw --pdp_file=examples/data/pdptw/lc101.txt 
[16:09:50] examples/cpp/pdptw.cc:298: Cost: 983413
[16:09:50] examples/cpp/pdptw.cc:299: Vehicle 0: 0 Vehicle(0) Time(0..0) Load(0..0) Transit(15132) 5 Vehicle(0) Time(15132..36328) Load(0..0) Transit(91000) 3 Vehicle(0) Time(106132..127328) Load(10..10) Transit(92000) 7 Vehicle(0) Time(198132..219328) Load(20..20) Transit(92828) 8 Vehicle(0) Time(290960..312156) Load(30..30) ...   75 Vehicle(0) Time(1033804..1068000) Load(150..150) Transit(105811) Route end Vehicle(0) Time(1139615..1236000) Load(160..160) 
...
```

Note at node 8, the load has *not* decreased by 10, and at Route end the load is 160.

If I change line https://github.com/google/or-tools/blame/master/examples/cpp/pdptw.cc#L223 to read

```
// demand is already negative at delivery nodes
const int64 demand = parsed_int[3];
```

Then the solution now reads:

```
james@emma or-tools[master]$ ./bin/pdptw --pdp_file=examples/data/pdptw/lc101.txt 
[16:13:43] examples/cpp/pdptw.cc:298: Cost: 828919
[16:13:43] examples/cpp/pdptw.cc:299: Vehicle 0: 0 Vehicle(0) Time(0..0) Load(0..0) Transit(15132) 5 Vehicle(0) Time(15132..36328) Load(0..0) Transit(91000) 3 Vehicle(0) Time(106132..127328) Load(10..10) Transit(92000) 7 Vehicle(0) Time(198132..219328) Load(20..20) Transit(92828) 8 Vehicle(0) Time(290960..312156) Load(10..10) Transit(93605) 10 Vehicle(0) Time(384565..405761) Load(30..30) Transit(93000) ...  75 Vehicle(0) Time(1033804..1068000) Load(10..10) Transit(105811) Route end Vehicle(0) Time(1139615..1236000) Load(0..0) 
...
``` 

In this case, the load at node 8 has dropped from 20 to 10, indicating that 10 units were dropped off at node 7.  Further, at the end of the tour, the load is zero.

Should I submit a pull request for this correction?  Or am I missing something that should cause the pdptw to need ever increasing loads in vehicles?

**Comment by jmarca** [comment]
Also, I forgot to add that the as-currently-written pdptw code ends up with using 12 vehicles in the solution:

```
...
Vehicle 10: 0 Vehicle(10) Time(0..0) Load(0..0) Transit(20615) 90 Vehicle(10) Time(20615..45000) Load(0..0) Transit(95000)  ... Route end Vehicle(10) Time(976066..1236000) Load(160..160) 
Vehicle 11: 0 Vehicle(11) Time(0..0) Load(0..0) Transit(30805) 98 Vehicle(11) Time(30805..51405) Load(0..0) Transit(95385)  ... Route end Vehicle(11) Time(905941..1236000) Load(200..200) 
Vehicle 12: empty
...
```

Whereas with my correction, the revised solution uses just 10 vehicles:

```
Vehicle 8: 0 Vehicle(8) Time(0..0) Load(0..0) Transit(20615) 90 Vehicle(8) Time(20615..45000) Load(0..0) Transit(95000) ... Route end Vehicle(8) Time(976066..1236000) Load(0..0) 
Vehicle 9: 0 Vehicle(9) Time(0..0) Load(0..0) Transit(30805) 98 Vehicle(9) Time(30805..51405) Load(0..0) Transit(95385) ... Route end Vehicle(9) Time(905941..1236000) Load(0..0) 
Vehicle 10: empty
Vehicle 11: empty
```
The current "winner" at the sintef site also uses just 10 vehicles:  https://www.sintef.no/contentassets/abb42d6b3f82453cb1908ed546b24fca/lc101.txt

Um, and hey, I just noticed, the travel distance with my correction is 828919 (see comment above), which should really be 828.919 because the code multiplies integers by 1000 (https://github.com/google/or-tools/blob/master/examples/cpp/pdptw.cc#L61).  The current "best" on the sintef site is 828.94.  So the Google OR tools code should be in the lead, right?





don't mean to brag, but the travel distance with

**Comment by furnon** [comment]
There's a bug in the parser in pdptw (we detected it recently). We'll
update the code soon. In any case I guess the result reported on the Sintef
site is probably equivalent to the one you found; even scaling values by
1000 may result in slightly different cost values.

**Comment by furnon** [comment]
Fix pushed to github.

**Comment by jmarca** [comment]
The fix should work---is exactly the same as my code change, so I'm going to close this issue if you don't mind.

However, I can't test because something else is breaking the local compilation on my laptop...src/glop/basis_representation.cc:555:51: error: call of overloaded ‘abs ... blah blah that I have to run down first.
