### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'google-ortools-native': The specified module could not be found. (Exception from HRESULT: 0x8007007E) 

### ISSUE THREAD

**Issue by MhmdRamadan** [google/or-tools#3551]
OR-Tools Version: v7.8.7959.0
Language: C#

 
currently i'm using .net 4.8 framework 

and i get this error DllNotFoundException: Unable to load DLL 'google-ortools-native': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

note i installed microsoft c++ redistributable and it didn't work

**Comment by lperron** [comment]
4.8; ia currently not supported. We are trying to add support in the next release.

**Comment by Mizux** [comment]
see:
* #3503

**Comment by MhmdRamadan** [comment]
> 4.8; ia currently not supported. We are trying to add support in the next release.

when will be the next release ?

**Comment by divieurora** [comment]
sorry to randomly reply on this issue since i cannot found any information anywhere else regarding whether or tools supported for .net framework 4.8 yet. is now or tools supported for .net framework 4.8?
