### ISSUE TITLE
CMake build instructions (Make is deprecated)

### ISSUE THREAD

**Issue by lperron** [google/or-tools#3558]
Make based build has been stripped down. It is only a thin wrapper on top of CMake.
It has less functionalities. 

In particular, all documentation on developers.google.com about installations from sources, or running examples is not up to date.

See https://github.com/google/or-tools/blob/main/cmake/README.md for the CMake HOWTO.

**Comment by Mizux** [comment]
Now the doc is CMake based
https://developers.google.com/optimization/install/cpp/source_linux#configure_the_build

todo: Add a "Bazel based build from source"
todo: Get feedback and iterate over this "first" version of the CMake based build
