### ISSUE TITLE
example of MakeStateDependentTransit usage

### ISSUE THREAD

**Issue by 19fever** [google/or-tools#357]
I am trying to add cost for waiting time(slackvar) in tsp problem, I know that we can use SetSpanCostCoefficientForVehicle to do this, but the running time is not good.
So I here is what I am trying to do, add a new dimension(waiting_dimension) to keep track of the cumulative waiting time for all the nodes and set the cumulative lower bound of the end node to zero.
The new dimension(wating_dimension) is dependent on time_dimension, can we use MakeStateDependentTransit to create this new dimension.

I use route_nodes_(list of RouteNode) to keep all nodes in the routing model, and RouteNode class contains timestamp(pickup or delivery time) and nodeType(Courier, Pickup or Delivery)

```cpp
int64 RoutingCallback::TravelTime(RoutingModel::NodeIndex from, RoutingModel::NodeIndex to) const {
    return ceil(Distance(from, to) / 5/*m/s*/);
}

int64 RoutingCallback::WatingTime(RoutingModel::NodeIndex from, RoutingModel::NodeIndex to) const {
    time_t cumulative_time = //get cumulative travel time in time_dimension;
    const RouteNode& route_node = route_nodes_[from.value()];
    if (src_node.nodeType == NodeType::PICKUP) {
        if (pickup_time < route_node.timestamp) {
              return route_node.timestamp - cumulative_time;
        }
    }
    return 0;
}

routing.AddDimension(NewPermanentCallback(callback, &RoutingCallback::TravelTime),
        kHorizon, kHorizon, /*fix_start_cumul_to_zero=*/true, "time");
RoutingDimension* time_dimension = routing.GetMutableDimension("time");

for (size_t i = 0; i < route_nodes.size(); ++i) {
        const RouteNode& route_node = route_nodes[i];
        if (route_node.nodeType == NodeType::PICKUP) {
                // hard pickup time constraint
                solver->AddConstraint(
                    solver->MakeGreaterOrEqual(
                        time_dimension->CumulVar(i), 
                        route_node.timestamp));
        }
}
waiting_dimension = // create waiting_dimension depend on time_dimension
waiting_dimension->SetCumulVarSoftLowerBoundFromIndex(route_nodes.size()-1, 0, 1/*penalty coefficient*/);
```

**Comment by Mizux** [comment]
You can find an example here: https://github.com/google/or-tools/issues/574#issuecomment-430203076

But sinc, at start, the solver will compile `N * N * horizon` Matrix values, not sure it is worth it.

Did you try to use the finalizer to minimize the slack on the road by minimizing time at each node ?
https://github.com/google/or-tools/blob/2b36515b43e6ce11d26e3a8ac8e97f30d66a3ccf/ortools/constraint_solver/samples/vrp_time_windows.cc#L171-L179

IMHO, using the Span cost is the way to go...

**Comment by AMPechero** [comment]
Good morning I'm trying to use 
time_dimension.SetCumulVarSoftLowerBoundFromIndex(index, data['soft_time_windows'][location_idx][0], 10)
being time_dimension time_dimension = routing.GetDimensionOrDie('time'), 

However I get the following error: 
AttributeError: 'RoutingDimension' object has no attribute 'SetCumulVarSoftLowerBoundFromIndex'

Could someone give me any tip of what's going on , since in most of the examples, routing.GetDimensionOrDie('time').SetCumulVarSoftLowerBoundFromIndex works
