### ISSUE TITLE
Java: GLIBC_2.32 not found with ortools v9.5

### ISSUE THREAD

**Issue by pnoe** [google/or-tools#3577]
Hi,
with ortools 9.5 and java language, Routing Solver, Debian 11,
migrating from ortools 9.4 to 9.5 give me the following error :

`GLIBC_2.32' not found (required by /tmp/ortools-java8621248852489426541/ortools-linux-x86-64/libjniortools.so)]

So I will stay with 9.4 which is perfect !
Thank you for ortools;

**Comment by Mizux** [comment]
My bad, seems the linux runtime have been generated with a recent glibc...

You can try the Debian 11 archive otherwise: https://github.com/google/or-tools/releases/download/v9.5/or-tools_amd64_debian-11_java_v9.5.2237.tar.gz

**Comment by Mizux** [comment]
recall me https://github.com/google/or-tools/issues/2520#issuecomment-825119882

**Comment by juntek** [comment]
It is a substantial issue as it breaks building docker images.

**Comment by Mizux** [comment]
> It's a significant issue as it breaks building docker images.

Out of curiosity, which base image do you use to be impacted ?

also you can use pre-built archives which are built using various base image distro to be compatible with any up to date distro supported.

**Comment by ClaudioConsolmagno** [comment]
Dropping a line for information, had the exact same issue with version 9.5 running on Amazon's Elastic Beanstalk env= `Corretto 11 running on 64bit Amazon Linux 2/3.4.4`.
Fixed it temporarily by downgrading to version 9.4
