### ISSUE TITLE
cp-sat solver slowly finishes when asked to stop in callback listener

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#3585]
**What version of OR-Tools and what language are you using?**
Version: v9.5
Language: C++/Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Debian 11, Windows 11

**What did you do?**
Run attached proto file, stop after first solution by calling stopSearch in callback (java) or setting stop variable to true in observer (c++).

**What did you expect to see**
A solver stops short time after fist solution was found.

**What did you see instead?**
A solver stops more than one minute after first solution was found in case of linux and c++, in windows and java it was nearly 2 minutes on same computer. During that time one core was fully used by a process. Since first solution is found under 10 seconds, waiting minutes to stop solver is not acceptable.

[long_time_to_stop.zip](https://github.com/google/or-tools/files/10147477/long_time_to_stop.zip)

**Comment by lperron** [comment]
please do not use sentence like 'not acceptable' :-)

**Comment by gregy4** [comment]
I mean it as not pleasing used by the way in Webster dictionary for definition of unacceptable. But now I see that it can be understand as more offending. Sorry

**Comment by lperron** [comment]
No harm done. I decided not to let these miscommunications unreported. Even if sometimes, it is a cultural/language mismatch.
