### ISSUE TITLE
Mixed vehicles

### ISSUE THREAD

**Issue by TeodoraBogdan** [google/or-tools#3589]
**What language and solver does this apply to?**
C++ /Routing

**Describe the problem you are trying to solve.**

Hello!

Can someone help me with a solution to this problem?

For example I have 100 stops (some are inside of a city and some are outside) and 2 vehicles, one car and one truck. Because truck does not have access to the same roads as a car I have 2 different distance matrices.

Please tell me any idea you might have...I really need to make this work. Maybe there is a workaround...

**Describe the solution you'd like**

I want to optimize this problem, so the stops outside of the city to be assigned to the truck and the ones inside the city to the car.

Please tell me any idea you might have...I really need to make this work. Maybe there is a workaround...

**Comment by lperron** [comment]
Not an issue
