### ISSUE TITLE
CP-SAT produces nondeterministic results

### ISSUE THREAD

**Issue by Mapiarz** [google/or-tools#3590]
**What version of OR-Tools and what language are you using?**
Version: v9.5 and v9.4
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 18 lts

**What did you do?**
I have some tests that check for correctness of the optimal solution with fixed input. During testing, I disable parallelism by setting `num_search_workers` to `1`. All other params have their default value. This works just fine on ortools 9.0. With 9.4 and 9.5 the solution given by solver becomes nondeterministic and tests fail most of the time. I'm aware of `num_search_workers` to `num_workers` rename, I tried setting both (including one at a time and both at the same time).

**What did you expect to see**
The same solver solution each time test is ran.

**What did you see instead?**
Different solver solutions each time test was ran.

Am I doing something wrong or have ortools regressed on that?

Here's model generated using v9.0: https://www.dropbox.com/s/9p9c7zn08qtl4if/model_9.0.proto?dl=1
Here's model generated using v9.5: https://www.dropbox.com/s/s9b61e1vj511ya2/model_9.5.proto?dl=1

**Comment by lperron** [comment]
Can you attach the logs of 2 runs that do not find the same solution?

**Comment by lperron** [comment]
I ran the model 10 times. It returns the same solution.
This is easy to check now as the log prints the fingerprint of the input model, and the fingerprint of the output solution.

I suspect your model building method is not deterministic (usually from hash_maps).

You can check on your side by looking at the first fingerprint in the log:

```
Parameters: log_search_progress: true num_search_workers: 1

Initial optimization model '': (model_fingerprint: 0x17f955ab0e9f41c4)
#Variables: 2849 (#bools:643 #ints:291 in objective)
```

**Comment by Mapiarz** [comment]
@lperron Thanks for your response. I was able to dig a little deeper.

I ran tests twice on v9.0:
1. https://www.dropbox.com/s/92jlnexve143yu5/test1_v9.0.log?dl=1
2. https://www.dropbox.com/s/kj6dkimxzoxr5n9/test2_v9.0.log?dl=1

If you diff the logs, you can clearly see the only difference between the 2 runs are timings. In both cases we get the expected solution and it is the same solution for 2 runs.

I ran the same tests twice on v9.5:
1. https://www.dropbox.com/s/km8fs9yhlwdiptb/test1_v9.5.log?dl=1
2. https://www.dropbox.com/s/0uc2ue1lm10cxjo/test2_v9.5.log?dl=1

Here, you can observe 2 things. First, the tests failed so the solver produced a different solution from v9.0. Second, for each test run, solver came up with different solutions even though the model fingerprint is the same.

Any idea how to explain this?

**Comment by CADBIMDeveloper** [comment]
Hi, as far as I remember, if you want to get the same solution from CP-SAT each time you run it, you should also set "random_seed" parameter

**Comment by lperron** [comment]
1) We do not guarantee the same solution across versions.
2) Can you send me the first model that fails in 9.5 ?
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by Mapiarz** [comment]
Here are the failing models and associated logs of the test run that generated them. The model fingerprint is the same even though the actual proto file sha1sum is different (but maybe that's normal? I don't know how the model is serialized). Solutions are different.

1. First run: 
    - https://www.dropbox.com/s/fwmjvkcpfi3ylgt/test5_v9.5.log?dl=1
    - https://www.dropbox.com/s/helnlg52o2dp2bd/test5_v9.5.proto?dl=0
2.  Second run:
    - https://www.dropbox.com/s/wtdofuk6pmeuhe9/test6_v9.5.log?dl=0
    - https://www.dropbox.com/s/1sw5pk38i8n06bv/test6_v9.5.proto?dl=0

**Comment by lperron** [comment]
So,

your 2 models are vastly different (different order of constraints). So it
is natural we do not find the same solution.

bad news: the fingerprint is the same. Something is rotten there :-)
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by Mapiarz** [comment]
Thanks. I did not realize that order of constraints matters. I will check on my end if there's any nondeterminism in model generation. But this leads to the question, how come v9.0 was able to produce the same solution each time?
