### ISSUE TITLE
AddBoolOr(emptyVector).OnlyEnforceIf(never) infeasible

### ISSUE THREAD

**Issue by ctmcdo** [google/or-tools#3591]
**What version of OR-Tools and what language are you using?**
Version: v9.4.1874
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Ubuntu-20.04-64bit

**What did you do?**
```cpp
CpModelBuilder cp_model;
BoolVar b = cp_model.NewBoolVar();
cp_model.FixVariable(b, false);
vector<BoolVar> emptyVector;
cp_model.AddBoolOr(emptyVector).OnlyEnforceIf(b);
```

**What did you expect to see**
A feasible solution

**What did you see instead?**
No feasible solution

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
No

**Comment by lperron** [comment]
fixed on 9.5
