### ISSUE TITLE
OR-Tools incompatible with Gurobi 10

### ISSUE THREAD

**Issue by abeham** [google/or-tools#3594]
When trying to solve a MIP model with Or-Tools and using GUROBI_MIXED_INTEGER_PROGRAMMING as solver with Gurobi 10 installed, the following error is thrown:

> I1215 14:35:39.740749  4040 environment.cc:744] Found the Gurobi library in 'C:\gurobi1000\win64\bin\gurobi100.dll.
> F1215 14:35:39.741414  4040 dynamic_library.h:68] Check failed: function_address != nullptr Error: could not find function GRBloadenvsyscb in C:\gurobi1000\win64\bin\gurobi100.dll

**Comment by lperron** [comment]
So, they have removed more public functions.
Sorry about that, we will fix in in the next release.

**Comment by abeham** [comment]
Not your fault! Will Or-Tools remain compatible with both Gurobi 10 and 9 after that change?

**Comment by lperron** [comment]
It should.

Le jeu. 15 déc. 2022, 17:50, Andreas Beham ***@***.***> a
écrit :

**Comment by Mizux** [comment]
@abeham seems you are on windows just few questions:
Q1: Which language do you use (i.e. ortools python package, C++ project...) ?
Q2: If I regenerate a new package could you check it  ?
Q3: and/or If we add a patch on a dev branch could you "rebuild from source" and test the fix ?

**Comment by abeham** [comment]
1) I am using the nuget package for C# for research and development projects and the Python package for teaching. I used the routing API, as well as linear_solver. I have experience with CP in CPLEX, but not used CP (aside the routing API) in or-tools. I did some models with MiniZinc.
2) If you mean by "check" to see if it builds, sure. Or do you mean running through my projects and checking results?
3) I usually have my own build of or-tools maintained at a private package repository, because I need support for CPLEX 22.1 in my projects. I can do an occasional rebuild, it depends on what you want from me with respect to testing the fix.

**Comment by lperron** [comment]
You should really look at CP-SAT.
It is a good (non mixed) integer solver, and also a CP solver.

Just saying :-)
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le ven. 16 déc. 2022 à 11:10, Andreas Beham ***@***.***> a
écrit :
