### ISSUE TITLE
SolverVersion() is not informative

### ISSUE THREAD

**Issue by Diddlik** [google/or-tools#3596]
**What version of OR-Tools and what language are you using?**
Version: v9.5/v9.4
Language: C++

**Which solver are you using (GLOP)**

**What operating system (Windows)**

**What did you do?**
I try to write in the logs for auditability with which version was just calculated.
The solver I use is GLOP, the function SovlerVersion() always returns Glop0-0.
is there a possibility to get at least at runtime the global version of the tool? For example: FrameworkVersion() returns 9.5
The environment is c++ in Visual Studio.

**What did you expect to see**
any version number

**What did you see instead?**

Glop0-0

**Comment by lperron** [comment]
You can use https://github.com/google/or-tools/blob/stable/ortools/base/version.h

**Comment by lperron** [comment]
Fixed by the latest push.

```
Solving with Glop 9.5.2295
```
