### ISSUE TITLE
dotnet with CPLEX: not linked or license not found

### ISSUE THREAD

**Issue by GeniusTian** [google/or-tools#3599]
**What version of OR-Tools and what language are you using?**
Version: v9.5.2237
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CPLEX 20.1
**What operating system (Linux, Windows, ...) and version?**
windows 10
**What did you do?**
1.use maven import ortools dependency
2.execute my own program

**What did you expect to see**
Execute with success with my  IP problem.
**What did you see instead?**
MPSolver.createSolver("CPLEX_LP") is NullPointerException
Exception in thread "main" java.lang.NullPointerException
Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by Mizux** [comment]
CPLEX is linked at compile time and since it is proprietary we don't ship or-tools with CPLEX support.
You'll have to rebuild from source with CPLEX enabled

**Comment by GeniusTian** [comment]
Is it the same for gurobi?

**Comment by Mizux** [comment]
No, for gurobi, laurent (and a contributor IIRC) did a dynamic loading at runtime so there is no issue at link time to enable it...
Feel free to send us a PR to transform the integration using a dynamic linking style ;)

ref:
* https://github.com/google/or-tools/blob/main/ortools/gurobi/environment.h
* https://github.com/google/or-tools/blob/main/ortools/gurobi/environment.cc
