### ISSUE TITLE
Merging models does not update the variable indices in the aggregated constraints

### ISSUE THREAD

**Issue by magi-1** [google/or-tools#3603]
Version: 9.4.1874
Language: Python

Solver: CP-SAT
OS: Ubuntu 18.04

**Problem Setup**

A helper function to make the models. Forces the i-th variable to zero if the index is in indices_to_force.

```python
def small_model(model_name, num_vars, indices_to_force):
    model = cp.CpModel()
    variables = []
    for index in range(num_vars):
        var_name = f"({model_name}: {index})"
        var = model.NewBoolVar(var_name)
        variables.append(var)
        if index in indices_to_force:
            print(f"Added constraint to {var_name}")
            model.Add(var==0)
    return model, variables
```

Initializing models and variables

```python
m1, v1s = small_model(
    model_name="Model1", 
    num_vars=3, 
    indices_to_force=[1]
)
m2, v2s = small_model(
    model_name="Model2", 
    num_vars=4, 
    indices_to_force=[0, 1]
)
```

Merging models

```python
m3 = cp.CpModel()
m3.Proto().MergeFrom(m1.Proto())
m3.Proto().MergeFrom(m2.Proto())
```

Using variables in m3 to create objective

```python
# Side question: Would sum(v1s) + sum(v2s) be valid, or does m3 have new vars?
objective = 0
for index in range(7):
    objective += m3.GetBoolVarFromProtoIndex(index)
    
# Solving and printing solution
m3.Maximize(objective)
solver = cp.CpSolver()
solver.Solve(m3)

for index in range(7):
    var = m3.GetBoolVarFromProtoIndex(index)
    print(var.Name(), solver.Value(var))

```

**Expected Behavior**

```
(Model1: 0) 1
(Model1: 1) 0
(Model1: 2) 1
(Model2: 0) 0
(Model2: 1) 0
(Model2: 2) 1
(Model2: 3) 1
```

**Observed Behavior**

```
(Model1: 0) 0
(Model1: 1) 0
(Model1: 2) 1
(Model2: 0) 1
(Model2: 1) 1
(Model2: 2) 1
(Model2: 3) 1
```

I found this bug(?) when trying to solve K shortest path algorithms in a large network When merging and solving the models, it turns out that the constraints that make it into the merged model, are those from the first model  added with `CpModel.Proto().MergFrom`. Above, the same behavior is occuring! My idea is to presolve the K subproblems then use `CpModel.AddHint`, to initialize their solutions and subsequently provide the solver a good starting point, considering I am applying global constraints (paths cannot use an edge more that M times). Note that I can easily solve this model if I initialize the model directly (no merging). My motivation is that I have a large problem, and the speed ups from initializing the sub-models / constraints in parallel could be huge.

Here are some interesting observations:

The following var names should be 1, 2, 3, which would be inline with the behavior of the merged model variable's proto indexes being the index after concatenation. I.e. (pseudocode) `m1.var_index = [0, 1, 2]` and `m1.var_index = [0, 1, 2, 3]` giving `m3.var_index = [0, 1, 2, 3, 4, 5, 6]`. I know this is the behavior from the print loop in the above example. 

```python
print(m3.Proto().constraints)

[linear {
  vars: 1
  coeffs: 1
  domain: 0
  domain: 0
}
, linear {
  vars: 0
  coeffs: 1
  domain: 0
  domain: 0
}
, linear {
  vars: 1
  coeffs: 1
  domain: 0
  domain: 0
}
]
```

My thought is that when the models are merged, the variable indices are getting updated but not the constraints that are involved!

I realize that the standard documentation does not even mention the methods on the `Proto()` object, so the fundamental issue here might be that I am using the api incorrectly. Posting here on the off chance this is indeed a bug.

Additionally, I would appreciate any advice on how to achieve the desired behavior of mergin the models. It would be really nice if the only overhead of merging the models was from calling `MergeFrom`, instead of solving the solutions and completely re-initializing all of the constraints and adding the hints on another parent model.

**Comment by lperron** [comment]
the merge is just an append. It does not understand any semantics.

You will have to write more code to do the right thing.

Good luck.

**Comment by magi-1** [comment]
Thanks @lperron, would be a nice feature to have though.

**Comment by stradivari96** [comment]
Do note that the mergeFrom you are using is from the [protobuf api](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message#Message.MergeFrom.details).

> Merge the fields from the given message into this message.
> Singular fields will be overwritten, if specified in from, except for embedded messages which will be merged. Repeated fields will be concatenated. The given message must be of the same type as this message (i.e. the exact same class).

**Comment by magi-1** [comment]
@stradivari96 Figured out that I can access the var indices in the constraints via: 

```python
# maid_model is the parent model
num_vars = len(main_model.Proto().variables)

constraints = other_model.Proto().constraints
for c_proto in constraints:
    descriptor, linexpr_c_proto = c_proto.ListFields()[0]
    var_names = lin_c_proto.vars
    for index in range(len(var_names)):
        var_names[index] += num_vars
```

I am about to test if this works. Assuming there is not internal initialization methods called before `solver.Solve(model)`, I think it should work.

**Comment by lperron** [comment]
Because it is better done at the business model level (task, activities, objectives, partial assignment, orders, ongoing work) and having a builder method that takes data and then build the cp_model.

I believe this is too error-prone to be in the library.

Thanks for the offer though.

**Comment by magi-1** [comment]
@lperron That's fair. Given the example of solving K-subproblems in parallel that are to be merged, there's nothing wrong with just making a new model that is the equivalent to merging the K other models and doing hinting as needed. I went ahead and implimented the merge functionality myself for my specifc use case, and it wasn't too hard. I'm probably not seeing the full picture though. Personally, I had to dig pretty deep to understand the underlying implimentation. 

```python
def merge(self, problem: "CpProblem") -> None:      
        num_vars = len(self.var_indices)
        
        # Updating constraint variable indices
        for c_proto in problem.model.Proto().constraints:
            _, lin_c_proto = c_proto.ListFields()[0]
            var_indices = lin_c_proto.vars
            for i in range(len(var_indices)):
                var_indices[i] += num_vars
        
        # Updating var indices in objective
        var_indices = problem.model.Proto().objective.vars
        for i in range(len(var_indices)):
            var_indices[i] += num_vars
        
        # Appending model vars, constraints, and solutions
        if problem.solved:
            if not self.solver.ResponseProto():
                self.solver.Solve(self.model)
            self.solver.ResponseProto().MergeFrom(problem.solver.ResponseProto())
        self.model.Proto().MergeFrom(problem.model.Proto())
```

Thank you for reading my issue. If it's not too much to ask, since I have your attention, I'm somewhat confused about the `AddHint()` method. Say I have a network that I am using CpModel to find the shortest path between two nodes with. 

1. I initialize `model1` from scratch and solve it
2. I initialize the exact same model, `model2`, and add apply hinting for every single variable in the problem, since I know the solution. 
3. Observed: Same exact solve time - Expected: Drastically reduced solve time.

My uneducated guess is that it has to "verify" that the hints are in fact optimal. If this is the case, how does apply hint ever improve solve times? For what kind of problems / scenarios is hinting the most effective?

**Comment by magi-1** [comment]
Here is chatGPT's response:

"ApplyHint is a method in the CpSolver class of the ortools library that can be used to provide a "hint" to the solver about a possible value for a variable in a constraint programming (CP) model. This can potentially help the solver find a solution faster by providing additional information about the problem. However, it is not guaranteed to improve the solve time for every problem, and in some cases it may even make the solve time worse.

There are a few reasons why ApplyHint might not improve the solve time for a particular CpModel:

The hint may be incorrect: If the hint provided to ApplyHint is incorrect or leads the solver down a suboptimal path, it may actually make the solve time worse.

The model may be too complex: For very large or complex models, ApplyHint may not be able to make a significant impact on the solve time.

The model may already be well-constrained: If the CpModel is already well-constrained and there are few degrees of freedom for the solver to explore, then ApplyHint may not have much of an effect on the solve time.

Overall, it is important to carefully consider whether using ApplyHint is likely to be beneficial for a particular CpModel, and to carefully test its effectiveness in different scenarios."
