### ISSUE TITLE
Infeasible model using presolve

### ISSUE THREAD

**Issue by ctmcdo** [google/or-tools#3607]
**What version of OR-Tools and what language are you using?**
9.5.2237

Language: C++/Java/Python/C#
C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 22.04.1

**What did you do?**
With presolve produces 0/2 feasible models and no presolve produces 2/2 feasible models.

1. git clone https://github.com/ctmcdo/Jessica
2. cd Jessica
3. git checkout baa02b249d9bcca94005cca3445412951b49bc7c
4. sed -i 's/model.GetOrCreate<SatParameters>()->set_cp_model_presolve(false);/model.GetOrCreate<SatParameters>()->set_cp_model_presolve(true);/' filter_pawn/filter_pawn.cc
5. Create shared library from filter_pawn/filter_pawn.cc, which for me entails `(cd ~/ortools/ && make build SOURCE_NAME=/abs/path/to/Jessica/filter_pawn/ SOURCE=/abs/path/to/Jessica/filter_pawn/filter_pawn.cc)`
6. echo -e "11brq11r111p111p1pp1kp1N1pQ1p111111P1111NP11KP111P11P1PPR1B11B1R b - -\nr11q1bnr1p111k1pp111bp1111p1p1p1P1PBP1PP1P111P11n11P1QB11N11K1NR w K -" > myfile
7. sed -i 's/\/home\/colin\/dev\/Jessica\/weirdsample/\/abs\/path\/to\/Jessica\/myfile/' main.c # replace with abs path to Jessica/myfile
8. `make`
9. ./Jessica

**What did you expect to see**
```
Sampling from test file.
Potentially reachable positions:
11brq11r/111p111p/1pp1kp1N/1pQ1p111/111P1111/NP11KP11/1P11P1PP/R1B11B1R b - -
r11q1bnr/1p111k1p/p111bp11/11p1p1p1/P1PBP1PP/1P111P11/n11P1QB1/1N11K1NR w K -

Number of potentially reachable positions from sample: 2
```

**What did you see instead?**
```
Sampling from test file.
Potentially reachable positions:

Number of potentially reachable positions from sample: 0
```

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
My cpu is AMD Ryzen 5 3500U

I know there are a lot of steps to reproduce. It seems like it would be a large investment of time for me to come up with a more minimal example

**Comment by lperron** [comment]
Why don't you just export the model that fails?

**Comment by lperron** [comment]
cp_model.ExportToFile("bad_presolve.pb.txt");

**Comment by lperron** [comment]
Sorry

    #include "ortools/sat/swig_helper.h"

then

    CpModelBuilder cp_model;
    // Build model.
    operations_research::sat::CpSatHelper::WriteModelToFile(cp_model.Proto(), "bad_presolve.pb.txt");

I will add the API to the CpModelBuilder class.

**Comment by lperron** [comment]
I ran both models on the main branch with and without presolve. They all
return optimal.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Thanks for the bug report. I will close it now.
