### ISSUE TITLE
Unsatisfied linear constraint with no free enforcement literal: enforcement_literal: 236 linear { vars: 1423 coeffs: 1 domain: 1 domain: 1 }

### ISSUE THREAD

**Issue by gbmm** [google/or-tools#3617]
**What version of OR-Tools and what language are you using?**
Version: v9.2
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Linux centos7

**What did you do?**
I use CP-SAT solver .  Most of the time, it is normal, and sometimes "Unsatisfied linear constraint with no free enforcement literal: enforcement_literal: 236 linear { vars: 1423 coeffs: 1 domain: 1 domain: 1 }
*** Check failure stack trace:" appears in the solution process,  and then the process exits.
The model has never changed.

**Comment by lperron** [comment]
Please try with 9.5 and reopen the bug if still there.
