### ISSUE TITLE
Update SCIP to latest version (8.0.3+) for SCIP Apache 2.0 License

### ISSUE THREAD

**Issue by creiht** [google/or-tools#3619]
**What language and solver does this apply to?**
Python and SCIP solver

**Describe the problem you are trying to solve.**
Previously the SCIP library was licensed with a proprietary license that makes it difficult to use pre-built or-tools packages outside of academic use cases.

**Describe the solution you'd like**
The SCIP library has moved to be Apache 2.0 licensed in the latest release.  I would like to see the SCIP dependency bumped to the latest version so that the pre-built or-tools will not be hindered by the legacy SCIP license.

**Describe alternatives you've considered**
I could maintain my own build of or-tools that disables SCIP but would prefer to use the official builds.

**Additional context**

**Comment by lperron** [comment]
already done on main.

**Comment by creiht** [comment]
Oh apologies that I didn't check the main branch, and thanks!  Looking forward to the next release :)
