### ISSUE TITLE
CP-SAT: stopSearch() before starting solve (non c++)

### ISSUE THREAD

**Issue by lgroleaz** [google/or-tools#3621]
Hello,

I am using CP-SAT solver through Java API (rev=9.4.1874)
It seems that if the search has not yet begun then stopSearch is not considered.

A minimal example consists in doing :
CpSolver solver = new CpSolver();
solver.stopSearch();
solver.solve(model);

My use case is this: I have 2 threads. In the first one, I build a model and solve it with the CP-SAT solver. In the second one, I handle some events. Depending on the events, the second thread needs to stop the CP-SAT search. However, if I call stopSearch in the second thread before the first thread has called solved() on the solver, when the first thread will call solve() it will run until it finds the optimal solution.

**Comment by lperron** [comment]
stopSearch only works during search.
I recommend you periodically call stopSearch() in your second thread, until the solver has acknowledged and exited the search.
