### ISSUE TITLE
Gurobi version 10.0.0 does not work with ortools 9.4.* or ortools 9.5.*

### ISSUE THREAD

**Issue by ZedTDean** [google/or-tools#3631]
**What version of OR-Tools and what language are you using?**
Version: main/v9.5/v9.4 etc.
Language: Python

**Which solver are you using (Gurobi)*

**What operating system (Linux, Windows, ...) and version?*
Both windows and linux 

**What did you do?**
Install Gurobi full binary + python package 
install ortools from PIP 
test example 

**What did you expect to see**
run normally 
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0110 12:39:14.192021 12204 environment.cc:744] Found the Gurobi library in 'C:\gurobi952\win64\bin\gurobi95.dll.   
Number of variables = 2
Number of constraints = 2
Solution:
Objective value = 23.0
x = 3.0
y = 2.0

Advanced usage:
Problem solved in 5.000000 milliseconds
Problem solved in 0 iterations
Problem solved in 0 branch-and-bound nodes

**What did you see instead?**
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0110 12:44:39.968797 31088 environment.cc:744] Found the Gurobi library in 'C:\gurobi1000\win64\bin\gurobi100.dll. 
F0110 12:44:39.969797 31088 dynamic_library.h:68] Check failed: function_address != nullptr Error: could not find function GRBloadenvsyscb in C:\gurobi1000\win64\bin\gurobi100.dll
*** Check failure stack trace: ***

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
Yes. Known and fixed on main.
