### ISSUE TITLE
why delete examples/data  folder. all test project need  data files in this folder

### ISSUE THREAD

**Issue by YggSky** [google/or-tools#3634]
**What version of OR-Tools and what language are you using?**
Version: main/v9.5/v9.4 etc.
Language: C++/Java/Python/C#

old verison can include this folder. but 9.5 not include.  all your test Example need this folder's data file. the folder path is "or-tools/examoles/data" but it not exist in new vison

**Comment by lperron** [comment]
It is too big for GitHub.

**Comment by Mizux** [comment]
* https://github.com/google/or-tools/issues/3635#issuecomment-1381923092
