### ISSUE TITLE
Directory "examples/data" disapper

### ISSUE THREAD

**Issue by mingcaixiao** [google/or-tools#3635]
**Describe the problem you are trying to solve.**
I'm new to or-tools,when i try to run some examples,find that some examples don't have data which mentioned in the code comments.Then I review at tag v9.3,it did has data files in directory "examples/data".I don't know why it been deleted?
**Describe the solution you'd like**
I wish you can re-add these examples data.Beacuase this help newer more easy to learn how to use or-tools.

**Comment by lperron** [comment]
Too big for simple users and too big cumulatively for GitHub

**Comment by Mizux** [comment]
see https://or-tools.dev/data
