### ISSUE TITLE
CP-SAT solver not finding solution

### ISSUE THREAD

**Issue by IgnaceBleukx** [google/or-tools#3643]
**What version of OR-Tools and what language are you using?**
Version: v9.5
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT solver

**What operating system (Linux, Windows, ...) and version?**
Mac OS v13.0.1

**What did you do?**
I made a model the Python version of OR-tools as seen below which has a solution.

``` python
from ortools.sat.python import cp_model as ort

model = ort.CpModel()

a = model.NewIntVar(0,3,"a")
b = model.NewIntVar(0,3,"b")
c = model.NewIntVar(0,3,"c")
d = model.NewIntVar(0,3,"d")

p = model.NewIntVar(0,3,"p")
q = model.NewIntVar(0,3,"q")
r = model.NewIntVar(0,3,"r")
s = model.NewIntVar(0,3,"s")

bv1 = model.NewBoolVar("bv1")
bv2 = model.NewBoolVar("bv2")
bv3 = model.NewBoolVar("bv3")


model.Add(b != 1)
model.Add(b != 2)

model.Add(c != 0)
model.Add(c != 3)

model.Add(d != 0)

model.Add(p != 2)
model.Add(p != 3)

model.Add(q != 1)

model.Add(r != 1)

model.Add(s != 2)

model.AddAllDifferent([a,b,c,d])
model.AddAllDifferent([p,q,r,s])

model.Add(a == 0).OnlyEnforceIf(bv1)
model.Add(r == 0).OnlyEnforceIf(bv2)
model.AddBoolOr([bv2,bv3])
model.Add(a == 2).OnlyEnforceIf(bv3)
model.Add(p == 0).OnlyEnforceIf(bv1.Not())

# add solution
# model.AddBoolOr(bv1)
# model.AddBoolOr(bv2)
# model.AddBoolOr(bv3.Not())

status = ort.CpSolver().Solve(model)

if status == ort.INFEASIBLE:
    print("Model is UNSAT")
else:
    print("Model is not UNSAT")
   
model.Proto()
```

Solving the model returns UNSAT, but by commenting in the `# add solution` part of the file, the solver does find a solution.
I attached the proto file as well to reproduce.
[unsat_proto.txt](https://github.com/google/or-tools/files/10467453/unsat_proto.txt)

**Comment by lperron** [comment]
Thanks for the bug report.

**Comment by lperron** [comment]
workaround: 

    solver.parameters.cp_model_probing_level:0

We are still  investigating.
