### ISSUE TITLE
After the solver updates less logs is written out

### ISSUE THREAD

**Issue by Diddlik** [google/or-tools#3644]
**What version of OR-Tools and what language are you using?**
Version: main/v9.5 and 8,2
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
GLOP

**What operating system (Linux, Windows, ...) and version?**
Windows

**What did you do?**

I have updated the solver from 8.2 to 9.5 and noticed that now significantly fewer logs are written out.
See the picture. Left is glop with ortools 9.5, right glop with ortools 8.2
Has something happened to logging in the time?

```
		//turn_on_GLOP_logging_if_necessary();
		if (solver_args.verbose > 0 && solver_args.mode_type != MODETYPE::MULTI) {
			{
				my_cout << "Initializing google logging\n";
				char myargv[256];
				sprintf(myargv, "GLOP_%s_%d_", _solver_parameter_ptr->optname, id);
				google::InitGoogleLogging(myargv);
				FLAGS_log_dir.Set(folder_path);
				my_cout << "Setting Glop output folder to " << FLAGS_log_dir.Get() << endl;
				//FLAGS_v.Set(2);
				FLAGS_v.Set(solver_args.verbose);
				FLAGS_minloglevel.Set(0);
			}
		}

```

**What did you expect to see**
I except to see similar logs

**What did you see instead?**
fewer logs as expected

![grafik](https://user-images.githubusercontent.com/6010713/213803667-2136b080-0d2b-432d-9bf9-0fe1e0824bd0.png)

**Comment by lperron** [comment]
Most of the logs are printed on stout.

**Comment by Diddlik** [comment]
> Most of the logs are printed on stout.

is it possible to forward logs from stout?

**Comment by Mizux** [comment]
FYI: Once we get the new release https://github.com/abseil/abseil-cpp we will migrate to each absl::log implementation which could support logging callback.
Let's ping us once the release and the integration is done...
current status: stall (waiting abseil-cpp release)

**Comment by Diddlik** [comment]
@Mizux 
Hello, as agreed, there is a new version absl. Here is the ping!

Thanks in advance!

**Comment by Mizux** [comment]
FYI, last abseil-cpp 20230125.0 has just been integrated on `main` by Laurent last week...

**Comment by Diddlik** [comment]
@Mizux but a compiled lib does not exist yet?
