### ISSUE TITLE
Incorrect `INFEASIBLE` status reported

### ISSUE THREAD

**Issue by matteosantama** [google/or-tools#3654]
**What version of OR-Tools and what language are you using?**
Version: 9.4.1874
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
GLOP

**What operating system (Linux, Windows, ...) and version?**

macOS M1 Pro Ventura 13.1

**What did you do?**
```python
from ortools.linear_solver import pywraplp

solver = pywraplp.Solver.CreateSolver('GLOP')

a = solver.NumVar(1, solver.infinity(), "a")
b = solver.NumVar(1, solver.infinity(), "b")
c = solver.NumVar(1, solver.infinity(), "c")

solver.Add(a - b + c == 0)

solver.Minimize(11 * a - 9.5 * b + 7.27 * c)

solver.Solve()
Out[8]: 2

pywraplp.Solver.INFEASIBLE
Out[9]: 2
```

**What did you expect to see**

This problem is clearly feasible, ie. `a = 1`, `b = 2`, `c = 1`.

**What did you see instead?**

`pywraplp.Solver.INFEASIBLE`

**Comment by matteosantama** [comment]
Strangely enough, when I comment out `solver.Minimize(11 * a - 9.5 * b + 7.27 * c)`, the solver reports a successful `0` status.

**Comment by lperron** [comment]
Problem is unbound. 
So the status is unfeasible or unbound.
