### ISSUE TITLE
or-tools 9.5 regression build failure

### ISSUE THREAD

**Issue by chenrui333** [google/or-tools#3655]
**What version of OR-Tools and what language are you using?**
Version: v9.5
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

**What operating system (Linux, Windows, ...) and version?**
macOS

**What did you do?**

**What did you expect to see**
build passed

**What did you see instead?**
```
  /tmp/or-tools-20230129-27850-1n6w029/or-tools-9.5/ortools/base/log.cc:1271:30: error: expected function body after function declarator
  void LogMessage::SendToLog() EXCLUSIVE_LOCKS_REQUIRED(log_mutex) {
                               ^
  /tmp/or-tools-20230129-27850-1n6w029/or-tools-9.5/ortools/base/log.cc:1386:21: error: cannot initialize a variable of type 'google::logging_fail_func_t' (aka 'void (*)() __attribute__((noreturn))') with an rvalue of type 'void (*)()'
  logging_fail_func_t g_logging_fail_func = &logging_fail;
                      ^                     ~~~~~~~~~~~~~
  /tmp/or-tools-20230129-27850-1n6w029/or-tools-9.5/ortools/base/log.cc:1395:31: error: expected function body after function declarator
  void LogMessage::SendToSink() EXCLUSIVE_LOCKS_REQUIRED(log_mutex) {
                                ^
  /tmp/or-tools-20230129-27850-1n6w029/or-tools-9.5/ortools/base/log.cc:1605:29: error: use of undeclared identifier 'kDontNeedShellEscapeChars'
        src.find_first_not_of(kDontNeedShellEscapeChars) == string::npos) {
                              ^
  4 errors generated.
```

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/4038312117/jobs/6942259866
relates to https://github.com/Homebrew/homebrew-core/pull/121718

**Comment by lperron** [comment]
You can define ABSL_LEGACY_THREAD_ANNOTATIONS to support the old code. 
We will support absl without the flag in the next release (9.6)

**Comment by lperron** [comment]
Or you can patch EXCLUSIVE_LOCKS_REQUIRED into ABSL_EXCLUSIVE_LOCK_REQUIRED

**Comment by chenrui333** [comment]
> You can define ABSL_LEGACY_THREAD_ANNOTATIONS to support the old code. We will support absl without the flag in the next release (9.6)

I will try the suggested options in here later.

**Comment by chenrui333** [comment]
> You can define ABSL_LEGACY_THREAD_ANNOTATIONS to support the old code. We will support absl without the flag in the next release (9.6)

I actually dont know how to add this env into the cmake build.
