### ISSUE TITLE
CP-SAT solver couldn't prove the solution is optimal if num_workers < 5 but otherwise it did instantly.

### ISSUE THREAD

**Issue by lucidfrontier45** [google/or-tools#3662]
**What version of OR-Tools and what language are you using?**
Version: 9.5.2237
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 22.04, Debian 11 on WSL

**What did you do?**

1. build a model for my problem (see attached pb file)
2. create a `cp_model.CpSolver`
3. set `solver.parameters.max_time_in_second = 60`
4. set `solver.parameters.num_workers` to 4 or 5
5. solve the model

**What did you expect to see**

In both cases of `num_workers=4` and `num_workers=5` the solver can find optimal solution within 60 seconds.  

**What did you see instead?**

In the case of `num_workers=5` the solver found the optimal solution in less than 1 second.
In the case of `num_workers=4` the solver spent whole 60 seconds and only returned a feasible solution.

By checking the attached logs, I found in both case the objective value is the same but in the case of  `num_workers=4`  the best_bound was still higher than objective. That is, both solver found the the true optimal solution but in the case of `num_workers=4` the solver failed to prove it is optimal.

Note that I re-ran the program multiple times but the results were always the same. I also tried num_workers=6,7,8 and the solver found the optimal solution instantly. But with num_workers=1,2,3 the solver only returned a feasible solution like num_workers=4 case.

**Attachments**

[model.pb.txt](https://github.com/google/or-tools/files/10568295/model.pb.txt)
[4_workers.log](https://github.com/google/or-tools/files/10568296/4_workers.log)
[5_workers.log](https://github.com/google/or-tools/files/10568297/5_workers.log)

**Comment by lperron** [comment]
this is expected.

CP-SAT is a portfolio based solver, not a work sharing one.
Recommended number of workers is at least 8.

**Comment by lucidfrontier45** [comment]
@lperron Thank you for the explanation.

I checked the lof and found these messages.

```
Starting  search at 0.02s with 12 workers.
10 full subsolvers: [default_lp, no_lp, max_lp, core, reduced_costs, pseudo_costs, quick_restart, quick_restart_no_lp, lb_tree_search, probing]
Interleaved subsolvers: [feasibility_pump, rnd_var_lns_default, rnd_cst_lns_default, graph_var_lns_default, graph_cst_lns_default, rins_lns_default, rens_lns_default]
```

The variation of full subsolvers increased as I use more workers. I guess this is what you mentioned by portfolio based solver.

Please let me ask a few more questions.  

1. What are full subsolvers and Interleaved subsolvers?
2. The number of full subsolvers didn't increase after it reached 10.  Is this the limit?
3. If I'm going to run in a machine whose number of CPU cores is less than 8, should I still set `num_workers` to 8 or higher to leverage more different subsolvers?

I didn't find any explanation for them in the OrTools documentation. If I missed something, please kindly let me know.

Thank you.

**Comment by lperron** [comment]
1) Full solver: complete search
Interleaved solver: more or less large neighborhood search. Can be a
feasibility pump.

2) There is only a limited number of possible full solvers. If you use more
workers. we gradually add extra full solvers.

3) use 8.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le jeu. 2 févr. 2023 à 16:13, 杜世橋 Du Shiqiao ***@***.***> a
écrit :
