### ISSUE TITLE
IntVar issue

### ISSUE THREAD

**Issue by Lapetite165** [google/or-tools#3669]
Version: main/v9.5/v9.4 etc.
Language: Python v3.6.6
GLOP and SCIP
Windows 10 Éducation Version 21H2
1. Go to favorite IDE to use or-tools;
2. Create a file;
3. Copy and paste the proposed LP program on Python;
4. Modify the file like the example in my github repository Solver [https://github.com/Lapetite165/Solver](url)
5. Defined vars with solver.IntVar and not solver.NumVar;
6. Run the file;
7. See error.

I was expecting to see an integer solution as describe in the or-tools documentation.
I saw a float solution instead. (1.99...6 instead of 2 for GLOP and 2.0 instead of 2 for SCIP).
You can also use my file instead of step 2. to 5..

**Comment by Regista6** [comment]
Glop is an LP solver, your problem has got integer variables. Also solution_value returns double so that's why 2.0.

**Comment by Lapetite165** [comment]
So is there a Solution_Value like which can return integers ?

**Comment by Mizux** [comment]
you can probably round it `int(round(...))`
