### ISSUE TITLE
DijkstraShortestPath missing in python in new ortools 9.5

### ISSUE THREAD

**Issue by mmmoussa96** [google/or-tools#3673]
**What version of OR-Tools and what language are you using?**
Version: 9.5.2237
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
N/A

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you do?**
N/A; package is missing from repo

**What did you expect to see**
Expected to be able to import and use DijkstraShortestPath. Previously was able to import pywrapgraph, but according to the changelogs, this was split between 3 different libraries. However, it seems DijkstraShortestPath was left out

**What did you see instead?**
Saw nothing

Make sure you include information that can help us debug (full error message, model Proto).
N/A

**Anything else we should know about your project / environment**
I am using Python 3.10, so downgrading to the last ortools version that has pywrapgraph (including DijkstraShortestPath) is no longer possible for me
Edit: Actually is possible to use ortools 9.3 on Python 10

**Comment by Mizux** [comment]
dev note:
Last SWIG based version:
https://github.com/google/or-tools/tree/v9.3/ortools/graph/python

Currently pybind11, only contains
* `linear_sum_assignment`
* `min_cost_gflow`
* `max_flow`
https://github.com/google/or-tools/tree/main/ortools/graph/python

**Comment by lperron** [comment]
the code is so trivial, not worth export IMO.
There are plenty of python code out there.

**Comment by dourouc05** [comment]
There is one fewer incentive to work on this code: the API is going away, to be replaced with a nicer interface, based on the graph data structure (defined in `graph/graph.h`), instead of the current awkward interface with callbacks. It will arrive soonish, but Java/Python/C# wrappers will be done when we find time to do it.
