### ISSUE TITLE
Error:  unresolved external symbol "void __cdecl absl::lts_20220623

### ISSUE THREAD

**Issue by JacintaDFerreira** [google/or-tools#3674]
**What version of OR-Tools and what language are you using?**
Version: stable
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
Built OR-Tools from source, as in https://developers.google.com/optimization/install/cpp/source_windows. All the examples ran successfully. 
Created a program, as in https://developers.google.com/optimization/introduction/cpp,  in Visual Studio 2022

When I run it, I get these erros:

`
1>ortools_d.lib(log.obj) : error LNK2019: unresolved external symbol "void __cdecl absl::lts_20220623::raw_logging_internal::RawLog(enum absl::lts_20220623::LogSeverity,char const *,int,char const *,...)" (?RawLog@raw_logging_internal@lts_20220623@absl@@YAXW4LogSeverity@23@PEBDH1ZZ) referenced in function "public: void __cdecl google::LogMessage::SendToLog(void)" (?SendToLog@LogMessage@google@@QEAAXXZ)
1>ortools_d.lib(timetable_edgefinding.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl absl::lts_20220623::CommandLineFlag::IsRetired(void)const " (?IsRetired@CommandLineFlag@lts_20220623@absl@@UEBA_NXZ)
1>ortools_d.lib(zero_half_cuts.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl absl::lts_20220623::CommandLineFlag::IsRetired(void)const " (?IsRetired@CommandLineFlag@lts_20220623@absl@@UEBA_NXZ)
1>ortools_d.lib(pseudo_costs.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl absl::lts_20220623::CommandLineFlag::IsRetired(void)const " (?IsRetired@CommandLineFlag@lts_20220623@absl@@UEBA_NXZ)
`

**Comment by Mizux** [comment]
which command, build system did you use to:
* build/run working example aka what has working.
* build/run your own program.

**Comment by JacintaDFerreira** [comment]
I built the working tests using  `cmake --build build --config Debug --target RUN_TESTS -v`, and my own program using visual studio.

**Comment by JacintaDFerreira** [comment]
I solved the problem by changing the library directories
