### ISSUE TITLE
CVRP doesn't accept float numbers in the distance matrix

### ISSUE THREAD

**Issue by skkirtonia** [google/or-tools#3675]
**What version of OR-Tools and what language are you using?**
Version: main/v9.5.2237
Language: Python

**Which solver are you using (Routing Solver)

**What operating system (Windows 10)?

**What did you do?**

1. trying to replicate the complete program of https://developers.google.com/optimization/routing/cvrp page
2. Changed the type of the values in the distance matrix to float
3. Solve the problem

**What did you expect to see**
same result as the example 

**What did you see instead?**
the distance_callback function is not called and the objective is always 0

**Comment by Mizux** [comment]
Solver implementation in C++ only use `int64_t` -> you must use python integer (`int()`).

note: If you have some floating values try to offset them by 10 100 1000 to stay in the "integer space"

**Comment by skkirtonia** [comment]
Can the C++ implementation be changed to floating values instead of int64?

**Comment by Mizux** [comment]
no, solver is hardcoded with int, aka code is not templated on type so you can't have a float/double version of cp solver.
