### ISSUE TITLE
CPSAT returning "INFEASIBLE" for a satisfiable problem

### ISSUE THREAD

**Issue by mwahbi** [google/or-tools#3681]
**What version of OR-Tools and what language are you using?**
Version: v9.5 (9.5.2237)
Language: Python 3.10.5

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows & Linux

**What did you do?**

```
from google.protobuf import text_format
from ortools.sat.python import cp_model


def main():
    run = 0
    states = {"OPTIMAL", "INFEASIBLE"}
    model = cp_model.CpModel()
    text_format.Parse(open("model_bug.txt").read(), model.Proto())
    # model.ClearObjective()  # ALWAYS OPTIMAL (the problem is SAT)
    while run < 1000 and states:
        solver = cp_model.CpSolver()
        status = solver.Solve(model)
        status = solver.StatusName(status)
        objective = solver.ObjectiveValue()
        print(f"{run=:2d} {status=} {objective=}")
        states.discard(status)
        run += 1


if __name__ == '__main__':
    main()
```

**What did you expect to see**
I am expecting the problem to be satisfiable all the time, however, it is returning "INFEASIBLE" in some runs. 

**What did you see instead?**

The problem is sometime solvable ("OPTIMAL") and sometimes ("INFEASIBLE")

Make sure you include information that can help us debug (full error message, model Proto).
[model Proto](https://github.com/google/or-tools/files/10787714/model_bug.txt)

**Anything else we should know about your project / environment**
Nothing

**Comment by lperron** [comment]
just ran it on the main branch

CpSolverResponse summary:
status: OPTIMAL
objective: 0
best_bound: 0
integers: 77
booleans: 9
conflicts: 0
branches: 8
propagations: 0
integer_propagations: 33
restarts: 0
lp_iterations: 16
walltime: 0.019605
usertime: 0.019605
deterministic_time: 8.7302e-05
gap_integral: 0.000622693
solution_fingerprint: 0x4a62d2114457578f

**Comment by mwahbi** [comment]
Bonjour @lperron,

In some runs, it is optimal and others infeasible. Can you try multiple runs?

**Comment by lperron** [comment]
I did.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le lun. 20 févr. 2023 à 22:07, Mohamed Wahbi ***@***.***> a
écrit :

**Comment by mwahbi** [comment]
Do you mean reproduce the issue? or reach run=1000. 
For me, this is the output I get on my runs:
```
run= 0 status='INFEASIBLE' objective=0.0
run= 1 status='INFEASIBLE' objective=0.0
run= 2 status='OPTIMAL' objective=0.0
```

**Comment by lperron** [comment]
Did you try with the main branch?

Le lun. 20 févr. 2023, 22:12, Mohamed Wahbi ***@***.***> a
écrit :

**Comment by mwahbi** [comment]
No I didn't, I tried only with the released to pypi server. 
I collected the logs for both cases and I see that there is a difference with LP solver. If you want I can share them with you.

**Comment by mwahbi** [comment]
Bonjour Laurent, 
I tried with the main branch and the problem is not there anymore. 
Many thanks
