### ISSUE TITLE
Exceptions are returned, not raised in Reservoir Constraints

### ISSUE THREAD

**Issue by mficek** [google/or-tools#3682]
**What version of OR-Tools and what language are you using?**
Version: v9.5
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 20.04

**What did you do?**
```
from ortools.sat.python import cp_model
model = cp_model.CpModel()
model.AddReservoirConstraint([],[], min_level=100, max_level=300)
```

**What did you expect to see**
**Raised** `ValueError` because min_level > 0

**What did you see instead?**
**Returned** `ValueError`, which is pretty non-standard behavior for errors as it can not be handled in a try-except block.

The issue is in file `ortools/sat/python/cp_model.py` function `AddReservoirConstraint`, lines `1410-1418`; and function `AddReservoirConstraintWithActive`, lines `1476-1484`

**Comment by lperron** [comment]
Indeed :-)
