### ISSUE TITLE
Traffic factor in vehicle routing problems

### ISSUE THREAD

**Issue by rc-eddy** [google/or-tools#369]
Is there a way to accommodate traffic in vehicle routing problems? That is to evaluate the transit time between two node indices as a function of index A, index B _and_ the accumulated time instead of just the indices?

**Comment by dkourilov** [comment]
See RoutingModel::AddDimensionDependentDimensionWithVehicleCapacity (note, it's not exported in swig, so C++ only).

**Comment by Mizux** [comment]
related to #480 #461 #339

**Comment by lperron** [comment]
Duplicate of many issues.

The feature is experimental, and will not be wrapped by swig in the foreseable future.
