### ISSUE TITLE
New Release ?

### ISSUE THREAD

**Issue by pocman** [google/or-tools#370]
Hi, 

We would really like a new release in order to have access to this functionality : 
https://github.com/google/or-tools/commit/d3a6ed9787c2664b81931550a9fff0577a463ab6

We are waiting on it since mars 2016 and are currently working on this [challenge](https://datacity.numa.co/city-planning-to-simplify-logistics/) with a fixed deadline...

**Comment by lperron** [comment]
I just released it.
I will announce it soon.
