### ISSUE TITLE
9.6v Ignoring pseudo_costs subsolver returns Invalid parameters.

### ISSUE THREAD

**Issue by Krabii** [google/or-tools#3706]
**What version of OR-Tools and what language are you using?**
Version: v9.6
Language: Python 3.8

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

CP-SAT

**What operating system (Linux, Windows, ...) and version?**

Linux Ubuntu 20.20

**What did you do?**

Added pseudo_costs in ignored_subsolvers list:

solver.parameters.ignore_subsolvers.append('pseudo_costs')

**What did you expect to see**

**What did you see instead?**

An error message is returned:

"Invalid parameters: subsolver 'pseudo_costs' is not valid"

Make sure you include information that can help us debug (full error message, model Proto).

The below will work in 9.5v but not in 9.6v

```python
from ortools.sat.python import cp_model

model = cp_model.CpModel()

x = model.NewIntVar(0, 10, 'x')
model.Add(x <= 9)
model.Maximize(x)

solver = cp_model.CpSolver()
solver.parameters.log_search_progress = True
solver.parameters.ignore_subsolvers.append('pseudo_costs')

solver.Solve(model)
```

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
Indeed. My bad.
