### ISSUE TITLE
Ubuntu and Debian C++ binary distributions for v9.6

### ISSUE THREAD

**Issue by ankane** [google/or-tools#3707]
**What language and solver does this apply to?**
C++

**Describe the problem you are trying to solve.**
Hey, congrats on the 9.6 release! I went to upgrade the Ruby gem and couldn't find C++ binary distributions for Ubuntu and Debian like previous releases. Is this intentional?

**Describe the solution you'd like**
C++ binary distributions for Ubuntu and Debian

**Describe alternatives you've considered**
Create binary distributions manually

**Comment by lperron** [comment]
Not yet uploaded.

**Comment by ankane** [comment]
Thanks @Mizux
