### ISSUE TITLE
Can't find feasible solution to simple AddDivisionEquality constraint.

### ISSUE THREAD

**Issue by SYury** [google/or-tools#3708]
**What version of OR-Tools and what language are you using?**
Version: v9.5
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT
**What operating system (Linux, Windows, ...) and version?**
Ubuntu 20.04 under WSL
**What did you do?**

Run the following code:
```
#include <assert.h>

#include "ortools/sat/cp_model.h"
#include "ortools/sat/cp_model_solver.h"

int main() {
    using namespace operations_research;

    sat::CpModelBuilder builder;

    auto a = builder.NewBoolVar();
    auto b = builder.NewBoolVar();
    auto c = builder.NewIntVar(Domain(-100, 100));

    auto expr = sat::LinearExpr(10);

    expr -= sat::LinearExpr::Term(a, 1);
    expr -= sat::LinearExpr::Term(b, 1);

    builder.AddDivisionEquality(c, expr, 5);

    sat::Model model;
    auto response = sat::SolveCpModel(builder.Build(), &model);

    assert(response.status() == sat::CpSolverStatus::OPTIMAL || response.status() == sat::CpSolverStatus::FEASIBLE);
}

```

**What did you expect to see**
The program runs without any problems.
**What did you see instead?**
Assert fails. 

P. S. It doesn't fail if I remove variable b from the model.
**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
You should print the status of the solver.
It will tell you that the model is invalid.

All these constraints expect 1-var expressions. (a * x + b). We will improve documentation.
