### ISSUE TITLE
Possible link error when using or-tools on MacOS

### ISSUE THREAD

**Issue by eder-matheus** [google/or-tools#3709]
**What version of OR-Tools and what language are you using?**
Version: v9.5
Language: C++ - Apple clang version 14.0.0 (clang-1400.0.29.202)

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
ILP solver

**What operating system (Linux, Windows, ...) and version?**
macOS Ventura 13.2.1

**What did you do?**
1. Downloaded or-tools from https://github.com/google/or-tools/releases/download/v9.5/or-tools_x86_64_macOS-13.0.1_cpp_v9.5.2237.tar.gz
2. Run "tar --strip 1 --dir /usr/local/opt/or-tools -xf or-tools_x86_64_macOS-13.0.1_cpp_v9.5.2237.tar.gz"
3. Run "export CMAKE_PREFIX_PATH=$(brew --prefix or-tools)"
4. Run cmake and make in my project, build have no errors.
5. Execute the generated binary

**What did you expect to see**
The binary should run with no errors.

**What did you see instead?**
`ERROR: Something is wrong with flag 'flagfile' in file 'Users/corentinl/work/or-tools/build_make/_deps/absl-src/absl/flags/parse.cc'. One possibility: file 'Users/corentinl/work/or-tools/build_make/_deps/absl-src/absl/flags/parse.cc' is being linked both statically and dynamically into this executable. e.g. some files listed as srcs to a test and also listed as srcs of some shared lib deps of the same test.`
Note that this error happens without executing a specific script, or even calling an or-tool functionality. The error happens when the application starts.

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
The project I'm working on is The OpenROAD Project. The repository with the project code is available here: https://github.com/The-OpenROAD-Project/OpenROAD.

**Comment by lperron** [comment]
can you try with 9.6 ? (once the binary artefact is uploaded to github)

**Comment by eder-matheus** [comment]
> can you try with 9.6 ? (once the binary artefact is uploaded to github)

I've tried this package: https://github.com/google/or-tools/releases/download/v9.6/or-tools_x86_64_macOS-13.2.1_cpp_v9.6.2534.tar.gz. I've made the same steps described above, but I still have the same error:
`ERROR: Something is wrong with flag 'flagfile' in file 'Users/corentinl/work/or-tools/build_make/_deps/absl-src/absl/flags/parse.cc'. One possibility: file 'Users/corentinl/work/or-tools/build_make/_deps/absl-src/absl/flags/parse.cc' is being linked both statically and dynamically into this executable. e.g. some files listed as srcs to a test and also listed as srcs of some shared lib deps of the same test.`

**Comment by tjtaill** [comment]
I had this problem and wanted to share my work around for it when I build or tools I know use
-DBUILD_SHARED_LIBS=OFF as a cmake configure flag this causes it to build a static version of ortools lib and avoids the error

```sh
cmake -S. -Bbuild -DBUILD_SHARED_LIBS=OFF -DBUILD_DEPS:BOOL=ON -DUSE_SCIP=OFF -DUSE_GLPK=OFF -DUSE_COINOR=OFF -DCMAKE_BUILD_TYPE=Release
cmake --build build --target install -j 8 --config Release
```

**Comment by maliberty** [comment]
@stefanottili found in https://github.com/The-OpenROAD-Project/OpenROAD/pull/3643

> All that seems to matter in order to be able to run openroad or mpl2_test on MacOS M1 is that they are linked with ortool.9.6.dylib placed after libabsl_flags_reflection.a in the link command.

> .../opt/homebrew/opt/or-tools/lib/libabsl_flags_reflection.a /opt/homebrew/opt/or-tools/lib/libortools.9.6.dylib /opt/homebrew/opt/or-tools/lib/libortools.9.6.dylib ....

> so even with a duplicate libortools.9.6.dylib it will link and openroad and mpl2_test will run.

**Comment by maliberty** [comment]
It seems that or-tools itself controls the cmake library ordering.  Does this give anyone a hint on how to resolve this?

**Comment by stefanottili** [comment]
When linking the openroad app, there are two sets of libabslxx.a and libortool.dylub in the link command, the linking works, but the openroad application throws the runtime error mentioned above.
Placing libortools.9.6.dylib after libabsl_flags_reflection.a creates a working executable.

Here is how ortools are used in the OpenROAD CMakeLists.txt files.

OpenROAD/src/mpl2/CMakeLists.txt

42 find_package(ortools REQUIRED)
..
 59 target_link_libraries(mpl2_lib
 60     utl_lib
 61     dbSta_lib
 62     OpenSTA
 63     odb
 64     ortools::ortools
 65     dl
 66     par_lib
 67 )

OpenROAD/src/par/CMakeLists.txt

55 find_package(ortools REQUIRED)
..
 79 target_link_libraries(par_lib
 80   PUBLIC
 81     ortools::ortools
 82   PRIVATE
 83     odb
 84     OpenSTA
 85     utl_lib
 86     dbSta_lib
 87 )

**Comment by maliberty** [comment]
I don't know how to accomplish what you keep suggesting.  If you have a solution please make a PR.

**Comment by stefanottili** [comment]
Mea culpa, this was supposed to go to the ortools bug-report, which is back on TODO status.

**Comment by stefanottili** [comment]
@Mizux This has been on the TODO list for a while now, is there a chance that this will be addressed for the next release ?
The fix is to "put the ortools.dylib at the end of the link list" that get's used by cmake "find_package(ortools)".

**Comment by Mizux** [comment]
> @Mizux This has been on the TODO list for a while now, is there a chance that this will be addressed for the next release ? The fix is to "put the ortools.dylib at the end of the link list" that get's used by cmake "find_package(ortools)".

Would like to fix it, but I'm still not sure what we could do, seems an openroad integration issue and I don't know how we could fix it from ortools src.

note: `find_package(ortools)` should load this file
https://github.com/google/or-tools/blob/main/cmake/ortoolsConfig.cmake.in
Will be happy to have a minimal reproducible example of the issue also I'm curious to know if Homebrew package is impacted as well since we would like to remove makefile based archive and move to homebrew package as our main MacOS user workflow.

**Comment by stefanottili** [comment]
How is this an openroad integration issue when cmake “find_package(ortools REQUIRED)” returns the libraries to be linked with in an order that allows linking to succeed, but that leads to a runtime error ?

In order to get an executable without runtime error one has to put libortools.9.6.dylib after libabsl_flags_reflection.a during linking.

**Comment by Mizux** [comment]
Does this issue still relevant in v9.8 ?
commit 9239362 may have fix it...

**Comment by eder-matheus** [comment]
> Does this issue still relevant in v9.8 ? commit [9239362](https://github.com/google/or-tools/commit/923936279234b324af5903adbf0e3cbff2059aa8) may have fix it...

Unfortunately I still have this issue when using v9.8:
`ERROR: Something is wrong with flag 'flagfile' in file 'Users/corentinl/work/or-tools/build_make/_deps/absl-src/absl/flags/parse.cc'. One possibility: file 'Users/corentinl/work/or-tools/build_make/_deps/absl-src/absl/flags/parse.cc' is being linked both statically and dynamically into this executable. e.g. some files listed as srcs to a test and also listed as srcs of some shared lib deps of the same test.`

It happens after compiling OpenROAD with ortools. The build end with no errors, but the error above happens when executing the binary.

I installed ortools this way:
1. Downloaded this file: https://github.com/google/or-tools/releases/download/v9.8/or-tools_arm64_macOS-14.1_cpp_v9.8.3296.tar.gz
2. Uncompressed the .tar.gz
3. Added the directory of the ortools file on my CMAKE_PREFIX_PATH

Is there something missing from my end?

**Comment by stefanottili** [comment]
> All that seems to matter in order to be able to run openroad or mpl2_test on MacOS M1 is that they are linked with ortool.9.6.dylib placed after libabsl_flags_reflection.a in the link command.

This still holds true.

The current workaround to get an OpenRoad executable without the runtime error is to ‘make VERBOSE=1’ , copy/paste the final link command in a file called ‘link_openroad’ and edit it so that the ortools dylib is last in line.

**Comment by Mizux** [comment]
in generated `ortoolsTargets.cmake` we have:

```cmake
...
# Create imported target ortools::ortools
add_library(ortools::ortools SHARED IMPORTED)

set_target_properties(ortools::ortools PROPERTIES
  COMPATIBLE_INTERFACE_STRING "ortools_MAJOR_VERSION"
  INTERFACE_COMPILE_DEFINITIONS "OR_TOOLS_AS_DYNAMIC_LIB;USE_LP_PARSER;USE_MATH_OPT;USE_BOP;USE_CBC;USE_CLP;USE_GLOP;USE_PDLP;USE_SCIP"
  INTERFACE_COMPILE_FEATURES "\$<IF:\$<CXX_COMPILER_ID:MSVC>,cxx_std_20,cxx_std_17>"
  INTERFACE_COMPILE_OPTIONS "-fwrapv"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "dl;ZLIB::ZLIB;absl::base;absl::core_headers;absl::absl_check;absl::absl_log;absl::check;absl::die_if_null;absl::flags;absl::flags_commandlineflag;absl::flags_marshalling;absl::flags_parse;absl::flags_reflection;absl::flags_usage;absl::log;absl::log_flags;absl::log_globals;absl::log_initialize;absl::log_internal_message;absl::cord;absl::random_random;absl::raw_hash_set;absl::hash;absl::leak_check;absl::memory;absl::meta;absl::stacktrace;absl::status;absl::statusor;absl::str_format;absl::strings;absl::synchronization;absl::time;absl::any;protobuf::libprotobuf;re2::re2;Coin::CbcSolver;Coin::OsiCbc;Coin::ClpSolver;Coin::OsiClp;\$<\$<BOOL:OFF>:CPLEX::CPLEX>;\$<\$<BOOL:OFF>:GLPK::GLPK>;\$<\$<BOOL:OFF>:HIGHS::HIGHS>;Eigen3::Eigen;\$<\$<BOOL:ON>:libscip>;Threads::Threads"
  INTERFACE_POSITION_INDEPENDENT_CODE "ON"
  INTERFACE_ortools_MAJOR_VERSION "9"
)

**Comment by stefanottili** [comment]
Any reason why the “dl”, which currently is first in the INTERFACE_LINK_LIBRARIES can’t be last ?
All assuming that “dl” will somehow be converted to “ortool.9.8.dylib”

**Comment by Mizux** [comment]
Should come from here, order was arbitrary, at best alphabetical
https://github.com/google/or-tools/blob/136d180aba09ef61ee65bd07b81048a875f23e16/cmake/cpp.cmake#L352-L364

**Comment by stefanottili** [comment]
find . | grep cpp.cmake
shows nothing, no cpp.cmake in [https://github.com/google/or-tools/releases/download/v9.8/or-tools_arm64_macOS-14.1_cpp_v9.8.3296.tar.gz](https://github.com/google/or-tools/releases/download/v9.8/or-tools_arm64_macOS-14.1_cpp_v9.8.3296.tar.gz)

(disclaimer: without any cmake knowledge)
or-tools/lib/cmake/ortools/ortoolsTargets.cmake sets
INTERFACE_LINK_LIBRARIES
but I don't see where ortool.9.8.dylib is set ...

**Comment by Mizux** [comment]
`CMAKE_DL_LIBS` is for `dlopen` and `dlclose` see:
https://cmake.org/cmake/help/latest/variable/CMAKE_DL_LIBS.html

**Comment by stefanottili** [comment]
Any chance to find somebody with enough cmake knowledge on the or-tools side to put the libortools.dylib at the end of the link information that ortools cmake provides to OpenRoad cmake via the "find_package(ortools REQUIRED)" command ?

**Comment by Mizux** [comment]
> ```cmake
> RFACE_LINK_LI
> ```

cpp.cmake in only use to BUILD ortools, it is not part of the install artifact

**Comment by Mizux** [comment]
DevNote:
https://github.com/The-OpenROAD-Project/OpenROAD/blob/8bd7e793e69b9f1fc434f3dc76bc019d4486164a/etc/DependencyInstaller.sh#L219-L221

HomeBrew built or-tools and abseil-cpp as SHARED libraries, while in our archives we built everything static to get rid of unused symbols and reduce total size.
Will it be possible that messing ortools archive with brew install may lead to abseil-cpp static and dynamic linked...

**Comment by stefanottili** [comment]
In the cmake generated OpenRoad Makefile, the openroad executable link command has libortools.dylib ahead of libabseilxxx.a …

This links, but throws a runtime error.

Moving the libortools.dylib after libabsl_flags_reflection.a (or just at the end) will link and generate an executable without runtime error.

**Comment by maliberty** [comment]
> I just noticed that I can use "brew install or-tools" and with that openroad can build an executable that works "out of the box".

Including mpl2 and par?

**Comment by stefanottili** [comment]
OpenROAD v2.0-13237-g874ac1a7c 
Features included (+) or not (-):  +Charts +GPU +GUI +MPL2 +PAR +Python

Using "brew install or-tools" which installs ortools 9.9 I was able to link an openroad executable without the previous or-tools related runtime error with MPL2 and PAR compiled in.

**Comment by eder-matheus** [comment]
@stefanottili Thanks for this tip! I installed it with brew and I could also compile and run OpenROAD with MPL2 and PAR without any issues. I think we can close this issue for now, since the necessary update is on the OpenROAD side now.
