### ISSUE TITLE
No warehouse_run.cc in C++ samples directory?

### ISSUE THREAD

**Issue by YuriWerewolf** [google/or-tools#371]
No warehouse_run.cc in C++ samples directory despite being mentioned in READ.ME? Does it have another name?

**Comment by orwant** [comment]
Looks like that's one of our internal examples that we didn't push to
github. We'll huddle and see if it makes sense to do so.

Thanks for pointing this out!

Jon

**Comment by lperron** [comment]
I removed the example from the README.
