### ISSUE TITLE
Crash with `use_pb_resolution` and `binary_search_num_conflicts`

### ISSUE THREAD

**Issue by magneticflux-** [google/or-tools#3711]
**What version of OR-Tools and what language are you using?**
Version: v9.6
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 11 x86_64

**What did you do?**
1. Set `use_pb_resolution = true` and `binary_search_num_conflicts = 1000`
2. Try to solve a model involving pseudo-Boolean constraints
3. See error

**What did you expect to see**
No crash

**What did you see instead?**
```
...
#Bound  23.51s best:-8812 next:[-8811,-7707] quick_restart
#Bound  23.86s best:-8812 next:[-8811,-8235] reduced_costs
#16     25.13s best:-8802 next:[-8801,-8235] graph_cst_lns_default(d=0.44 s=71 t=0.10 p=0.43)
Check failed: slack < 0 (1 vs. 0) We don't have a conflict!
*** Check failure stack trace: ***
    @   00007FF903632E49  (unknown)
    @   00007FF9033496A4  (unknown)
    @   00007FF90334C9CC  (unknown)
    @   00007FF903349E00  (unknown)
    @   00007FF903349AAF  (unknown)
    @   00007FF9033F4F50  (unknown)
    @   00007FF9033F486E  (unknown)
    @   00007FF9033F409A  (unknown)
    @   00007FF903421168  (unknown)
    @   00007FF90309D35F  (unknown)
    @   00007FF9030873AB  (unknown)
    @   00007FF90336260B  (unknown)
    @   00007FF90342E634  (unknown)
    @   00007FF90342DC7F  (unknown)
    @   00007FF9A6939363  (unknown)
    @   00007FF9A88826BD  (unknown)
    @   00007FF9A8EEA9F8  (unknown)
```

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

Large model that causes the issue: [model.zip](https://github.com/google/or-tools/files/10986028/model.zip)

**Comment by lperron** [comment]
Yes. This is mostly untested. Do not use the option. 

Thanks for the model.

**Comment by magneticflux-** [comment]
I just got a similar error only using `use_pb_resolution = true`, so I assume that's the parameter that's untested right now.

**Comment by lperron** [comment]
Yes, and you do not need it.

Just use multiple workers, at least 8.

Le jeu. 16 mars 2023, 09:52, Mitchell Skaggs ***@***.***> a
écrit :

**Comment by lperron** [comment]
I cannot load the model. How did you generate it ?

**Comment by magneticflux-** [comment]
I think that model was actually generated using a build from the `main` branch. I exported the binary protobuf using `CpSatHelper.writeModelToFile`.

**Comment by lperron** [comment]
Can you try exporting with a name in txt.

The API is model.exportToFile(filename).

Thanks

Le jeu. 16 mars 2023, 22:31, Mitchell Skaggs ***@***.***> a
écrit :

**Comment by magneticflux-** [comment]
Here's the model text: [model.txt](https://github.com/google/or-tools/files/10996372/model.txt)

Using these parameters `Parameters: log_search_progress: true use_pb_resolution: true binary_search_num_conflicts: 100 log_subsolver_statistics: true num_workers: 20 log_frequency_in_seconds: 10` causes this error:
```
...
#Bound  12.56s best:-55131 next:[-55130,-6729] default_lp
#Bound  12.89s best:-55131 next:[-55130,-6730] probing_max_lp
#Bound  12.92s best:-55131 next:[-55130,-6809] objective_lb_search
Check failed: slack < 0 (0 vs. 0) We don't have a conflict!
*** Check failure stack trace: ***
    @   00007FF951319039  (unknown)
    @   00007FF951027304  (unknown)
    @   00007FF95102A62C  (unknown)
    @   00007FF951027A60  (unknown)
    @   00007FF95102770F  (unknown)
    @   00007FF9510D4060  (unknown)
    @   00007FF9510D394E  (unknown)
    @   00007FF9510D317A  (unknown)
    @   00007FF9511014F8  (unknown)
    @   00007FF950D64844  (unknown)
    @   00007FF950D4D603  (unknown)
    @   00007FF95104063B  (unknown)
    @   00007FF9511125E4  (unknown)
    @   00007FF951111D2F  (unknown)
    @   00007FF9EE079363  (unknown)
    @   00007FF9EE6426BD  (unknown)
    @   00007FF9F078A9F8  (unknown)
```
