### ISSUE TITLE
Ability to add solution callback to SCIP in Python when solving from MPS file.

### ISSUE THREAD

**Issue by erdos4d** [google/or-tools#3715]
**What language and solver does this apply to?**
Python, SCIP

**Describe the problem you are trying to solve.**
I am using the example [here](https://github.com/google/or-tools/issues/523#issuecomment-1432794861) to read an MPS file and call SCIP on it. I can't see how to add a solution callback or pass any other params to the solver. Is this possible?
**Describe the solution you'd like**
I'd like to add a solution callback so I can process each solution found as it solves. Being able to pass parameters to the solver would be nice too.
**Describe alternatives you've considered**
Trying to build SCIP myself in a container, which has not been very successful so far. 
**Additional context**
No other context but I will say this is an awesome library, it has been very helpful.

**Comment by lperron** [comment]
Model builder will never support callbacks. Math_opt will offer this feature in the future.

You can pass parameters as strings.
