### ISSUE TITLE
Windows CMake build fail on Target re2

### ISSUE THREAD

**Issue by mmjkelso** [google/or-tools#3720]
What version of OR-Tools and what language are you using?
Version: 9.6
Language: C++

Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)
CP-SAT

What operating system (Linux, Windows, ...) and version?
Windows 10 Pro build 19045.2728

What did you do?
Downloaded source zip, unpacked.
Tried to build with this script (modified from last version that worked, 9.2 I think):

```sh
set MMDEV=C:/Users/jkelso/Documents/master
set GENERATOR="Visual Studio 17 2022"
set ORTOOLS_DIR=or-tools-9.6

mkdir build64
cd build64
cmake ^
-Wno-dev ^
  -G %GENERATOR% ^
  -A x64 ^
  -D CMAKE_CXX_FLAGS="/EHsc /MD /O2 /DNDEBUG /Zi /Gy /DEBUG /INCREMENTAL:NO" ^
  -D ZLIB_LIBRARY=%MMDEV%/Components/zlib/lib/x64/zlibwapi.lib ^
  -D ZLIB_INCLUDE_DIR=%MMDEV%/Components/zlib/include/zlib ^
  -D USE_SCIP=OFF ^
  -D USE_COINOR=OFF ^
  -D BUILD_absl=ON ^
  -D BUILD_gflags=ON ^
  -D BUILD_glog=ON ^
  -D BUILD_Protobuf=ON ^
  -D protobuf_MSVC_STATIC_RUNTIME=OFF ^
  -D BUILD_Cbc=OFF ^
  -D BUILD_Cgl=OFF ^
  -D BUILD_Clp=OFF ^
  -D BUILD_CoinUtils=OFF ^
  -D BUILD_Osi=OFF ^
  -D BUILD_ZLIB=OFF ^
  -D BUILD_DEPS=OFF ^
  -D CMAKE_BUILD_TYPE=Release ^
  -D BUILD_TESTING=OFF ^
  -D BUILD_SAMPLES=OFF ^
  -D BUILD_EXAMPLES=OFF ^
  -D CMAKE_INSTALL_PREFIX="../install64" ^
  ../%ORTOOLS_DIR%
cmake --build . --config Release
cmake --build . --config Release --target Install
cd ..
```
What did you expect to see?
Build our usual targets

What did you see instead?

(Lots of C++ standard warning eg
ABSL_CXX_STANDARD: 20 , CMAKE_CXX_STANDARD: 20, Force CXX_FLAGS flags to cxx_std_17)

Build halted while fetching Protobuf with:

...
-- Check size of int * - done
-- Found int * size: 8
CMake Error at cmake/deps.cmake:81 (message):
  Target re2::re2 not available.
Call Stack (most recent call first):
  CMakeLists.txt:376 (include)

Make sure you include information that can help us debug (full error message, model Proto).

Anything else we should know about your project / environment
Using Visual Studio 17.3.6

**Comment by mmjkelso** [comment]
This report was a bit premature, sorry.
Since we are using BUILD_DEPS=OFF, and I did not build the last few versions, I needed to add:

BUILD_re2=ON
BUILD_Eigen3=ON

and possibly

ABSL_PROPAGATE_CXX_STD=ON

I am still getting failure in finding ZLIB, but I imagine that might be to do with our existing ZLIB setup.

**Comment by Mizux** [comment]
1. For ZLIB who is failing ? I mean is it or-tools or one of our deps (e.g. protobuf) ?

2. Beware, ABSL_PROPAGATE_CXX_STD=ON is broken if using CMake 3.19+
long story short: they use try_check/compile but since CMake 3.19 the CMAKE_CXX_STANDARD is not passed so for example on debian gcc default to pre 2017 so `ABSL_PROPAGATE=ON` + `CMAKE_CXX_STANDARD=17` will make absl propagate c++14...
thus my ugly patch to check their implem: https://github.com/google/or-tools/blob/main/patches/abseil-cpp-20230125.0.patch

also: https://github.com/google/or-tools/blob/main/patches/re2-2022-02-01.patch
IIRC re2 is still not using string_view and do not play well with absl

**Comment by mmjkelso** [comment]
Actually it nearly builds everything fine, only failing during install. Protobuf finds our ZLIB as before:

...
Completed 'protobuf-populate'
Building Custom Rule C:/Users/jkelso/Documents/master/Components/ortools/build64/_deps/protobuf-subbuild/CMakeLists.txt

--   3.21.12.0
--   Performing Test protobuf_HAVE_LD_VERSION_SCRIPT
--   Performing Test protobuf_HAVE_LD_VERSION_SCRIPT - Failed
--   Found ZLIB: C:/Users/jkelso/Documents/master/Components/zlib/lib/x64/zlibwapi.lib (found version "1.2.11")
-- Fetching Protobuf - fetched
-- Fetching re2
...

but at the end during install it is trying to link with zlib.lib not zlibwapi.lib :

  Create bundled lib...
  'C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cm
  ake.exe' '-E' 'rm' '-f' 'ortools_full.lib'
  'C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.31.31103/bin/HostX64/x64/lib.exe' '/NOLO
  GO' '/OUT:ortools_full.lib' 'ortools.lib' 'absl_*.lib' 'zlib.lib' 're2.lib' '*protobuf.lib'
LINK : fatal error LNK1181: cannot open input file 'zlib.lib' [C:\Users\jkelso\Documents\master\Components\ortools\buil
d64\Install.vcxproj]

There are then some MSBuild errors after that; I don't know if they are the result of the ortools_full.lib link failure or not.

**Comment by mmjkelso** [comment]
Closing this as neither zlib nor re2 have turned out to be a problem.
