### ISSUE TITLE
CP-SAT wrong optimal solution in v9.6

### ISSUE THREAD

**Issue by arnabadas** [google/or-tools#3735]
**What version of OR-Tools and what language are you using?**
Version: v9.6
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 11 Latest

**What did you do?**
I was maximizing the objective function of a CP-SAT problem.

**What did you expect to see**
 v9.5 was giving the correct output of 4

**What did you see instead?**
v9.6 is giving the wrong output of 3

Make sure you include information that can help us debug (full error message, model Proto).

The problem is confidential. I will try to come up with a minimal version of the problem to replicate the issue when I have the time.

**Anything else we should know about your project / environment**
NA

**Comment by lperron** [comment]
Closing. Please reopen when you can send a proto.
