### ISSUE TITLE
Wrong optimal solution in CP-SAT (or-tools v9.6)

### ISSUE THREAD

**Issue by arnabanimesh** [google/or-tools#3738]
**What version of OR-Tools and what language are you using?**
Version: v9.6
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 11 latest

**What did you do?**
Ran a CP-SAT model in ortools v9.6. It was showing the optimal output in v9.5 but not in v9.6.

I am trying to maximize the objective function. The objective value comes out to be 4 in v9.5 and 3 in v9.6.

**What did you expect to see**
[log_search_progress_9.5.2237.txt](https://github.com/google/or-tools/files/11151600/log_search_progress_9.5.2237.txt)
[model_9.5.2237.txt](https://github.com/google/or-tools/files/11151601/model_9.5.2237.txt)

**What did you see instead?**
[log_search_progress_9.6.2534.txt](https://github.com/google/or-tools/files/11151603/log_search_progress_9.6.2534.txt)
[model_9.6.2534.txt](https://github.com/google/or-tools/files/11151604/model_9.6.2534.txt)

**Anything else we should know about your project / environment**
NA

**Comment by lperron** [comment]
On the main  branch, it returns 4 correctly.
