### ISSUE TITLE
RoutingSearchParameters for big CPDPTW

### ISSUE THREAD

**Issue by pocman** [google/or-tools#374]
Hi, 

I have a RoutingModel with 100 Vehicles (3 ou 4 different cost matrix) and 3500 Nodes.
I'm modeling a Capacited Pickup and Delivery Problem with Time Windows.
All vehicles share the same depot location (but I model them as different nodes) and the pickup point location is identical for all deliveries.

I'm currently using the `setFirstSolutionStrategy(ALL_UNPERFORMED)` and after some time, I have the first solution (all skipped).
Using the solver logs, I can see that each new iteration (every 2s) result in on delivery being assigned to a vehicle. The 10minutes timeout kick in before the solver found any solution without skipped nodes.

Do you have any optimisation idea of a strategy that will allow for a faster solution without skipped nodes ?

**Comment by pocman** [comment]
Strangely, removing :
```
    for (int node = 0; node < deliveriesPoints.size(); node++) {
      routingModel.addDisjunction(new int[]{node}, initialValues.skippingCostInCents());
    }
```
Will result in ROUTING_FAIL on an instance that can be solve without unperforming any node.

**Comment by dapp1990** [comment]
Hi @pocman,

I was trying to test a large scenario like yours (100 drivers and 2000 optional nodes). My implementation couldn't find a first solution in a reasonable time. I tried  different heuristics, included `ALL_UNPERFORMED`. Unfortunately, none was good enough.

I didn't set the timeout parameter, so the algorithm could keep going and, after around 3 hours, I got a result.

I was wondering you could manage to get a solution in less time and, if that is the case, if you have any suggestion to speed up my current implementation.

Thanks!
