### ISSUE TITLE
Gurobi environment errors are not shown

### ISSUE THREAD

**Issue by ianr15** [google/or-tools#3743]
**What language and solver does this apply to?**
All languages, linear solver / Gurobi

**Describe the problem you are trying to solve.**
Gurobi errors arising when loading the Gurobi environment are not logged in OR-Tools, which makes troubleshooting hard.

**Describe the solution you'd like**
Logging of Gurobi loading errors

**Describe alternatives you've considered**
NA

**Additional context**
Based on github.com/google/or-tools/discussions/3739

**Comment by ianr15** [comment]
I will make a PR to fix this (I already have a local installation of OR-Tools doing it)

**Comment by ianr15** [comment]
https://github.com/google/or-tools/pull/3744

**Comment by lperron** [comment]
Here is the output I gen now:

Found the Gurobi library in '/Library/gurobi1000/macos_universal2/lib/libgurobi100.dylib.
FAILED_PRECONDITION: Found the Gurobi shared library, but could not create Gurobi environment: is Gurobi licensed on this machine?No Gurobi license found
