### ISSUE TITLE
CP-SAT solver produces different results for the same model on different machines

### ISSUE THREAD

**Issue by PME93** [google/or-tools#3748]
**What version of OR-Tools and what language are you using?**
Version: 9.6.2534
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
ubuntu:latest, Windows 10

**What did you do?**
I wrote a test function which solves a (simple) model with a fixed input and checks whether the result is as expected. 

**What did you expect to see**
The test should pass in both environments with the same solution. There are 4 boolean variables which should have a value of 1 for the expected optimal solution.

**What did you see instead?**
The test always passes on my local windows machine (all 4 boolean values are equal to 1) and fails always on the Linux machine (3 of 4 boolean values are equal to 1).

If I check the attached logs I find that the initial model fingerprints are different. Also there are slightly differences in presolving phase:
- line 61: [Probing]  - new integer holes: 25 (vs 26)
- line 111:  - rule 'linear: simplified rhs' was applied 72 times.

[linux_log.txt](https://github.com/google/or-tools/files/11231137/linux_log.txt)
[windows_log.txt](https://github.com/google/or-tools/files/11231174/windows_log.txt)

**Comment by lperron** [comment]
Known result. Floating points are different across platforms.

**Comment by lperron** [comment]
If the fingerprints are different, then the models are different. Please create the same models.

**Comment by PME93** [comment]
Hi @lperron,
thx for your answer. From what I know, both models should be identical since they have been created using the same code & inputs. Could there be an other influencing factor leading to a different model?

**Comment by lperron** [comment]
Code is not always deterministic.
Hash tables are memory address dependent, and can differ across platforms,
sorting can differ...

If the fingerprints are different, the models are different.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
