### ISSUE TITLE
CP-SAT, UNKNOWN status with complete solution hint

### ISSUE THREAD

**Issue by AlexeyTrefilov** [google/or-tools#3750]
Version: v9.5.2237
Language: Python
Solver: CP-SAT
Operating system Windows 10.

I am using the solution hint as warm start. It is complete and feasible. But looks like it doesn't work porperly.
If solver stopped by time limit in presolve, CP-SAT can't provide solution from hints.
Is it expected behavior?

There is a log:
Starting CP-SAT solver v9.5.2237
Parameters: max_time_in_seconds: 20 log_search_progress: true relative_gap_limit: 0.1 num_workers: 4

Initial optimization model '': (model_fingerprint: 0xe2fafecb911a9924)
#Variables: 506216 (#bools:284 #ints:8045 in floating point objective)
  - 497729 Booleans in [0,1]
  - 72 in [0,5]
  - 72 in [0,27]
  - 6 in [0,73]
  - 219 in [0,100]
  - 7899 in [0,186]
  - 219 in [0,211]
#kEmpty: 16666
#kLinear1: 33665
#kLinear2: 21457
#kLinear3: 9550
#kLinearN: 20993 (#terms: 1537132)

Starting presolve at 0.38s
The solution hint is complete and is feasible.
[Scaling] Floating point objective has 8329 terms with magnitude in [3.45972, 1000] average = 20.8423
[Scaling] Objective coefficient relative error: 1.11022e-16
[Scaling] Objective worst-case absolute error: 1.65983e-11
[Scaling] Objective scaling factor: 21.1
[ExtractEncodingFromLinear] #potential_supersets=20468 #potential_subsets=302 #at_most_one_encodings=100 #exactly_one_encodings=129 #unique_terms=812 #multiple_terms=643 #literals=1764 time=0.0585241s
[Probing] deterministic_time: 1.00014 (limit: 1) wall_time: 1.07314 (Aborted 2039/485224)
[Probing]  - new fixed Boolean: 4006 (26028/507246)
[Probing]  - new integer bounds: 300
[Probing]  - new binary clause: 4655
[Probing] implications and bool_or (work_done=472846).
[SAT presolve] num removable Booleans: 27401 / 506863
[SAT presolve] num trivial clauses: 0
[SAT presolve] [0s] clauses:32178 literals:80000 vars:32009 one_side_vars:15265 simple_definition:16614 singleton_clauses:0
[SAT presolve] [0.00969226s] clauses:32178 literals:80000 vars:32009 one_side_vars:15265 simple_definition:16614 singleton_clauses:0
[SAT presolve] [0.0385407s] clauses:32178 literals:80000 vars:32009 one_side_vars:15265 simple_definition:16614 singleton_clauses:0
[MaxClique] Merged 44851(1010583 literals) into 37016(1040059 literals) at_most_ones.
[DetectDuplicateConstraints] #duplicates=73 #without_enforcements=190 time=0.0677236s
[DetectDominatedLinearConstraints] #relevant_constraints=292 #work_done=56110 #num_inclusions=0 #num_redundant=0 time=0.0150344s
[DetectOverlappingColumns] #processed_columns=114 #work_done=23669 #nz_reduction=0 time=0.0607821s
[ProcessSetPPC] #relevant_constraints=44865 #num_inclusions=25028 work=8251173 time=0.523842s
[Symmetry] Graph for symmetry has 570049 nodes and 1088257 arcs.
[Symmetry] Symmetry computation done. time: 1.77478 dtime: 0.853725
[Symmetry] #generators: 56, average support size: 5667.46
[Symmetry] 102841 orbits with sizes: 30,30,30,30,30,30,30,30,30,18,...
[Symmetry] Num fixable by binary propagation in orbit: 14 / 30
[Symmetry] Num fixable by intersecting at_most_one with orbits: 27 largest_orbit: 30
[Symmetry] Found orbitope of size 139 x 15
[Probing] deterministic_time: 1.00049 (limit: 1) wall_time: 1.16046 (Aborted 2234/472888)
[Probing]  - new fixed Boolean: 1106 (34965/506747)
[Probing]  - new integer bounds: 57
[Probing]  - new binary clause: 4946
[Probing] implications and bool_or (work_done=490560).
[SAT presolve] num removable Booleans: 36640 / 506864
[SAT presolve] num trivial clauses: 0
[SAT presolve] [0s] clauses:17756 literals:46886 vars:17701 one_side_vars:5360 simple_definition:12284 singleton_clauses:0
[SAT presolve] [0.00598683s] clauses:17756 literals:46886 vars:17701 one_side_vars:5360 simple_definition:12284 singleton_clauses:0
[SAT presolve] [0.0309566s] clauses:17756 literals:46886 vars:17701 one_side_vars:5360 simple_definition:12284 singleton_clauses:0
[DetectDuplicateConstraints] #duplicates=0 #without_enforcements=190 time=0.0519132s
[DetectDominatedLinearConstraints] #relevant_constraints=272 #work_done=56780 #num_inclusions=30 #num_redundant=0 time=0.018217s
[DetectOverlappingColumns] #processed_columns=109 #work_done=8161 #nz_reduction=0 time=0.045209s
[ProcessSetPPC] #relevant_constraints=13983 #num_inclusions=0 work=3072617 time=0.28856s
[Symmetry] Graph for symmetry has 568225 nodes and 1064124 arcs.
[Symmetry] Symmetry computation done. time: 1.7259 dtime: 0.840827
[Symmetry] #generators: 41, average support size: 7551.8
[Symmetry] 101451 orbits with sizes: 18,18,18,18,14,14,14,14,14,14,...
[Symmetry] Num fixable by binary propagation in orbit: 9 / 18
[Symmetry] Num fixable by intersecting at_most_one with orbits: 27 largest_orbit: 18
[Symmetry] Found orbitope of size 106 x 6

Presolve summary:
  - 1388 affine relations were detected.
  - rule 'TODO dual: add implied bound' was applied 2 times.
  - rule 'TODO dual: make encoding equiv?' was applied 500 times.
  - rule 'TODO dual: only one blocking constraint?' was applied 3699958 times.
  - rule 'TODO dual: only one blocking enforced constraint?' was applied 2 times.
  - rule 'TODO dual: only one unspecified blocking constraint?' was applied 25448 times.
  - rule 'TODO dual: tighten at most one' was applied 3 times.
  - rule 'TODO duplicate: identical constraint with different enforcements' was applied 380 times.
  - rule 'TODO linear2: contains a Boolean.' was applied 39434 times.
  - rule 'TODO variables: only used in linear1.' was applied 331 times.
  - rule 'affine: new relation' was applied 1388 times.
  - rule 'at_most_one: removed literals' was applied 1683 times.
  - rule 'at_most_one: satisfied' was applied 192 times.
  - rule 'at_most_one: size one' was applied 50 times.
  - rule 'at_most_one: transformed into max clique.' was applied 1 time.
  - rule 'at_most_one: x and not(x)' was applied 3509 times.
  - rule 'bool_and: non-reified.' was applied 20 times.
  - rule 'bool_and: x => x' was applied 38 times.
  - rule 'bool_or: always true' was applied 3 times.
  - rule 'bool_or: fixed literals' was applied 38 times.
  - rule 'bool_or: implications' was applied 19251 times.
  - rule 'bool_or: only one literal' was applied 4 times.
  - rule 'deductions: 3399 stored' was applied 1 time.
  - rule 'dual: enforced equivalence' was applied 3 times.
  - rule 'dual: reduced domain' was applied 261 times.
  - rule 'duplicate: merged rhs of linear constraint' was applied 73 times.
  - rule 'duplicate: removed constraint' was applied 73 times.
  - rule 'encoding: extracted from linear' was applied 229 times.
  - rule 'encoding: reduced target domain' was applied 229 times.
  - rule 'enforcement: false literal' was applied 4123 times.
  - rule 'enforcement: true literal' was applied 80 times.
  - rule 'exactly_one: removed literals' was applied 3022 times.
  - rule 'exactly_one: satisfied' was applied 16 times.
  - rule 'exactly_one: simplified objective' was applied 32 times.
  - rule 'exactly_one: singleton' was applied 210 times.
  - rule 'exactly_one: size one' was applied 75 times.
  - rule 'exactly_one: size two' was applied 143 times.
  - rule 'linear + amo: trivial linear constraint' was applied 1 time.
  - rule 'linear1: is boolean implication' was applied 4 times.
  - rule 'linear1: without enforcement' was applied 3555 times.
  - rule 'linear: always true' was applied 32574 times.
  - rule 'linear: divide by GCD' was applied 8214 times.
  - rule 'linear: empty' was applied 7583 times.
  - rule 'linear: extracted enforcement literal' was applied 501 times.
  - rule 'linear: fixed or dup variables' was applied 26740 times.
  - rule 'linear: negative at most one' was applied 13274 times.
  - rule 'linear: negative clause' was applied 12080 times.
  - rule 'linear: negative equal one' was applied 6913 times.
  - rule 'linear: positive at most one' was applied 189 times.
  - rule 'linear: positive clause' was applied 7209 times.
  - rule 'linear: positive equal one' was applied 282 times.
  - rule 'linear: reduce rhs with DP' was applied 6 times.
  - rule 'linear: reduced variable domains' was applied 11660 times.
  - rule 'linear: reduced variable domains in derived constraint' was applied 79 times.
  - rule 'linear: remapped using affine relations' was applied 1182 times.
  - rule 'linear: simplified rhs' was applied 39828 times.
  - rule 'linear: simplify using approximate gcd' was applied 600 times.
  - rule 'linear: singleton column' was applied 73 times.
  - rule 'linear: tightened into equality' was applied 1 time.
  - rule 'linear: variable substitution 0' was applied 31 times.
  - rule 'linear: variable substitution 2' was applied 19 times.
  - rule 'objective: variable not used elsewhere' was applied 128 times.
  - rule 'presolve: 35205 unused variables removed.' was applied 1 time.
  - rule 'presolve: iteration' was applied 2 times.
  - rule 'probing: simplified clauses.' was applied 51 times.
  - rule 'setppc: bool_or in at_most_one.' was applied 1066 times.
  - rule 'setppc: fixed variables' was applied 2783 times.
  - rule 'setppc: removed dominated constraints' was applied 11826 times.
  - rule 'symmetry: fixed to false' was applied 105 times.
  - rule 'symmetry: fixed to false in general orbit' was applied 27 times.
  - rule 'variables with 2 values: create encoding literal' was applied 2 times.
  - rule 'variables with 2 values: new affine relation' was applied 2 times.
  - rule 'variables: add encoding constraint' was applied 1457 times.
  - rule 'variables: canonicalize domain' was applied 1 time.
  - rule 'variables: detect half reified value encoding' was applied 223 times.
  - rule 'variables: only used in encoding' was applied 1 time.

Presolved optimization model '': (model_fingerprint: 0x7cbf853ee58764a4)
#Variables: 470007 (#bools:7843 #ints:365 in objective)
  - 469533 Booleans in [0,1]
  - 14 in [0][2][5][8][15,16]
  - 1 in [0][2][5][8,9][15,16]
  - 1 in [0][2][5][11][15]
  - 6 in [0][2][5][11][15][18]
  - 10 in [0][2][5][11][15,16]
  - 3 in [0][2][5][11][15,16][18]
  - 12 in [0][2][5][15,16]
  - 1 in [0][2][5][16][18]
  - 8 in [0][2][7][9][12][15][17]
  - 1 in [0][2][7][15]
  - 9 in [0][2][9][12][15][17]
  - 3 in [0][2][15]
  - 1 in [0][2,3][17]
  - 4 in [0][2,4][11][14]
  - 4 in [0][2,4][11][14][16]
  - 9 in [0][2,4][11][14][16,17]
  - 9 in [0][2,4][11][14][17]
  - 1 in [0][2,4][11][14][17,18]
  - 1 in [0][2,4][16,17]
  - 3 in [0][2,4][17]
  - 1 in [0][3,5][10][13][15,16]
  - 5 in [0][4][6,8][10,11]
  - 2 in [0][4][6,8][11]
  - 8 in [0][4][6,11]
  - 3 in [0][4][17]
  - 13 in [0][4,5][9][13,15]
  - 8 in [0][4,5][9,13]
  - 7 in [0][4,5][10][13][15,16]
  - 5 in [0][4,5][13][15,16]
  - 1 in [0][4,5][13,15]
  - 6 in [0][5][9][11,13]
  - 14 in [0][5][9][13,15]
  - 1 in [0][5][9,13]
  - 3 in [0][5][11][15]
  - 2 in [0][5][13][15,16]
  - 3 in [0][5][13,15]
  - 1 in [0][5][14,15]
  - 3 in [0][5][18]
  - 5 in [0][7][9][12][15][17]
  - 4 in [0][8][15]
  - 5 in [0][9][12][15][17]
  - 8 in [0,1][4][11][14]
  - 10 in [0,1][4][11][14][16]
  - 3 in [0,1][4][11][14][16,17]
  - 6 in [0,1][4][11][14][17]
  - 1 in [0,1][4][16,17]
  - 69 in [0,3]
  - 5 in [0,4]
  - 24 in [0,5]
  - 2 in [0,12]
  - 1 in [0,16]
  - 1 in [0,17]
  - 18 in [0,19]
  - 10 in [0,24]
  - 13 in [0,27]
  - 7 in [0,63]
  - 2 in [0,66]
  - 5 in [0,67]
  - 1 in [0,133]
  - 1 in [0,134]
  - 23 in [0,139]
  - 1 in [0,142]
  - 2 in [0,145]
  - 6 in [0,148]
  - 15 in [0,152]
  - 1 in [0,173]
  - 4 in [0,183]
  - 1 in [0,184]
  - 1 in [0,186]
  - 2 in [0,188]
  - 2 in [0,189]
  - 2 in [0,191]
  - 1 in [0,192]
  - 1 in [0,194]
  - 4 in [0,195]
  - 1 in [0,197]
  - 2 in [0,198]
  - 1 in [0,201]
  - 1 in [0,202]
  - 1 in [0,204]
  - 1 in [0,207]
  - 1 in [0,208]
  - 7 in [1,4]
  - 2 in [1,5]
  - 2 in [2,5]
  - 1 constants in {0} 
#kAtMostOne: 6515 (#literals: 478780)
#kBoolAnd: 17262 (#enforced: 17262) (#literals: 17262)
#kBoolOr: 502 (#literals: 12378)
#kExactlyOne: 6823 (#literals: 472315)
#kLinear1: 3248 (#enforced: 3248)
#kLinear2: 136
#kLinearN: 135 (#terms: 15356)
Stopped after presolve.
PresolvedNumVariables: 470007
PresolvedNumConstraints: 34621
PresolvedNumTerms: 1020092

CpSolverResponse summary:
status: UNKNOWN
objective: 0
best_bound: 0
booleans: 0
conflicts: 0
branches: 0
propagations: 0
integer_propagations: 0
restarts: 0
lp_iterations: 0
walltime: 21.096
usertime: 21.096
deterministic_time: 2.0007
gap_integral: 0

**Comment by lperron** [comment]
Can you try with 9.6?

**Comment by lperron** [comment]
Actually, presolve takes more time than the time limit. So technically, no solution has been found.

**Comment by AlexeyTrefilov** [comment]
> Actually, presolve takes more time than the time limit. So technically, no solution has been found.

Yes, but in log was:
"The solution hint is complete and is feasible."
So, in that point we already have a solution, isn't it?

**Comment by lperron** [comment]
Yes, but I do not consider this a bug.

Le mar. 18 avr. 2023, 18:47, AlexeyTrefilov ***@***.***> a
écrit :

**Comment by lperron** [comment]
A feature request. But not a priority.

You can work around easily.

Le mar. 18 avr. 2023, 19:33, AlexeyTrefilov ***@***.***> a
écrit :
