### ISSUE TITLE
cplex_interface.cc: Check failed: last_variable_index_ == cols

### ISSUE THREAD

**Issue by rajgoel** [google/or-tools#3757]
**What version of OR-Tools and what language are you using?**
Version: v9.6
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CPLEX 22.10

**What operating system (Linux, Windows, ...) and version?**
Ubuntu Linux 18.04

**What did you do?**

- I use the API to create a solver
```c++
  #define MIPSOLVER "CPLEX"
  solver = std::unique_ptr<ORTools::MPSolver>( ORTools::MPSolver::CreateSolver(MIPSOLVER) );
```
and add variables, constraints, and objective function.
- I can successfully write the model to a file
```c++
  std::string MIP;
  solver->ExportModelAsLpFormat(false,&MIP); 
  std::ofstream myfile;
  myfile.open ("MIP.lp");
  myfile << MIP;
  myfile.close();
```
and solve the problem using the interactive prompt of cplex.
- When I solve the problem programmtically, however, via
```c++
const ORTools::MPSolver::ResultStatus result_status = solver->Solve();
```
the check in 
https://github.com/google/or-tools/blob/5425dedcfbb22cb74c636c1374a9b5ad684b1eb5/ortools/linear_solver/cplex_interface.cc#L866
fails because `last_variable_index_` is zero.

**What did you expect to see**

The solver should run without problem. It does so if I use
```c++
  #define MIPSOLVER "SCIP"
  solver = std::unique_ptr<ORTools::MPSolver>( ORTools::MPSolver::CreateSolver(MIPSOLVER) );
```

**What did you see instead?**

I got an error message like this
```
cplex_interface.cc:866
Check failed: last_variable_index_ == cols (0 vs. 450)
```

**Anything else we should know about your project / environment**

When I removed 
https://github.com/google/or-tools/blob/5425dedcfbb22cb74c636c1374a9b5ad684b1eb5/ortools/linear_solver/cplex_interface.cc#L866
and
https://github.com/google/or-tools/blob/5425dedcfbb22cb74c636c1374a9b5ad684b1eb5/ortools/linear_solver/cplex_interface.cc#L953
the solver worked as expected.

At other places in`cplex_interface.cc` the code can deal with `last_variable_index_` being zero, e.g.

https://github.com/google/or-tools/blob/5425dedcfbb22cb74c636c1374a9b5ad684b1eb5/ortools/linear_solver/cplex_interface.cc#L850-L851
Probably, a similar check should be used in lines 866 and 953.

Possibly the root cause of the problem is here:
https://github.com/google/or-tools/blob/5425dedcfbb22cb74c636c1374a9b5ad684b1eb5/ortools/linear_solver/linear_solver.cc#L1875-L1882
as `last_variable_index_` is set to zero.

**Comment by lperron** [comment]
As a rule, we do not work on the cplex interface, but gladly accepts PR.

Do you think the code is in a stable state, or does it need more fixes ?

**Comment by rajgoel** [comment]
P.S. Why does
https://github.com/google/or-tools/blob/5425dedcfbb22cb74c636c1374a9b5ad684b1eb5/ortools/linear_solver/linear_solver.cc#L1875-L1882
set the `last_variable_index_`to zero and not to `solver_->variables_.size()`. Does the comment above the method indicate a problem with the method?

**Comment by lperron** [comment]
There is a pending PR from one of the xpress developer that fixes most of the problems. Unfortunately, signing the contributor licence agreement is complex.
