### ISSUE TITLE
or-tools JNI runtime linking error

### ISSUE THREAD

**Issue by fokdiekul** [google/or-tools#376]
Hello,

I'm trying to use or-tools in eclipse (java). I build the path to the external jar-file (com.google.ortools) and my program finds it (gives no errors) but when i try to run it i get the following errror:

![error](https://cloud.githubusercontent.com/assets/5549177/25806948/5c5f91e0-3405-11e7-9376-942dfdeb1c13.png)

Can somebody please help me?

Kind regards,

Nicholas

**Comment by Bhuvanamitra** [comment]
I have this problem as well. Can someone respond on this and help in running the code?

**Comment by Mizux** [comment]
Hi,
Did you add the ‑Djava.library.path=PATH_TO_or‑tools/lib to your command line ?
cf https://developers.google.com/optimization/introduction/installing/binary#installing-on-windows

**Comment by lperron** [comment]
This thread is dead.  I am closing the issue. We will check the fix is visible in the documentation.
