### ISSUE TITLE
Build errors when compiling log.cc in or-tools

### ISSUE THREAD

**Issue by 2biias** [google/or-tools#3760]
**What version of OR-Tools and what language are you using?**
Version: main
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
I wan't to use GLOP or similar to solve a linear programming problem.

**What operating system (Linux, Windows, ...) and version?**
MacOS Monterey 12.6.2

**What did you do?**
Steps to reproduce the behavior.
1. Trying to install the binary directly and seeing same issue as stated in https://github.com/google/or-tools/issues/3709
2. To Circumvent the abseil related problem above, manually install abseil using homebrew to allow for static linking only.
3. Similarly, to minimise compilation time, I pre-fetched other dependencies protobuf, re2, zlib, scip and HIGHS using homebrew.
4.  Integrating or-tools into a cmake project using FetchContent and fetching main in my CMakeLists.txt.
5. Running "cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_Eigen3=ON -DBUILD_CoinUtils=ON -DBUILD_Osi=ON -DBUILD_Clp=ON -DBUILD_Cgl=ON -DBUILD_Cbc=ON -DBUILD_SCIP=OFF -DBUILD_EXAMPLES=OFF -DBUILD_CXX_EXAMPLES=OFF -DBUILD_SAMPLES=OFF -DBUILD_CXX_SAMPLES=OFF -DBUILD_GLOP=ON"
6. Running "cmake --build build -j -v"

**What did you expect to see**
Compilation completes.

**What did you see instead?**
Build fails with following errors:

```
.../build/_deps/or-tools-src/ortools/base/log.cc:1271:30: error: expected function body after function declarator
void LogMessage::SendToLog() EXCLUSIVE_LOCKS_REQUIRED(log_mutex) { ...

.../build/_deps/or-tools-src/ortools/base/log.cc:1386:21: error: cannot initialize a variable of type 'google::logging_fail_func_t' (aka 'void (*)() __attribute__((noreturn))') with an rvalue of type 'void (*)()'
logging_fail_func_t g_logging_fail_func = &logging_fail; ...

.../build/_deps/or-tools-src/ortools/base/log.cc:1605:29: error: use of undeclared identifier 'kDontNeedShellEscapeChars'
      src.find_first_not_of(kDontNeedShellEscapeChars) == string::npos) { ....
```

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
I have cmake version 3.26.3.

**Comment by Mizux** [comment]
https://github.com/google/or-tools/actions/runs/4764566633 seems the yesterday main HEAD pass.

Which version of abeil-cpp did you use (aka is provided by homebrew) ?
we are currently using:

https://github.com/google/or-tools/blob/7fad4a14a537025c114242ba59438e33cf596525/cmake/dependencies/CMakeLists.txt#L84-L86

**Comment by 2biias** [comment]
I see that Homebrew installed abseil 20230125.2 as well.
My CMakeLists.txt:
`# Cmake version
cmake_minimum_required(VERSION 3.22)
# C++ standard
set(CMAKE_CXX_STANDARD 17)

# Project setup
project(CSapp)
set(CMAKE_BUILD_TYPE Release)

# Files and libraries

# Fetch OR-tools library and create the alias ortools::ortools.
include(FetchContent)
FetchContent_Declare(
        or-tools
        GIT_REPOSITORY https://github.com/google/or-tools.git
        GIT_TAG        main
)
FetchContent_MakeAvailable(or-tools)
add_subdirectory(src)

include_directories(
    include
)

set(SOURCE_FILES
    src/Field.cpp
    src/FusionCenter.cpp
    src/Sensor.cpp
    src/CSVReader.cpp
    main.cpp)
add_executable(CSapp ${SOURCE_FILES})

target_link_libraries(CSapp ortools::ortools)`

**Comment by 2biias** [comment]
I have tried explicitly turning off the build abseil flag by:

cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_absl=OFF -DBUILD_Eigen3=ON -DBUILD_CoinUtils=ON -DBUILD_Osi=ON -DBUILD_Clp=ON -DBUILD_Cgl=ON -DBUILD_Cbc=ON -DBUILD_SCIP=OFF -DBUILD_EXAMPLES=OFF -DBUILD_CXX_EXAMPLES=OFF -DBUILD_SAMPLES=OFF -DBUILD_CXX_SAMPLES=OFF -DBUILD_GLOP=ON

and now i get a new error:
`In file included from ...CSAPP/build/_deps/or-tools-src/ortools/base/logging.h:23:
In file included from /usr/local/include/absl/log/check.h:37:
In file included from /usr/local/include/absl/log/internal/check_impl.h:19:
In file included from /usr/local/include/absl/log/internal/check_op.h:37:
In file included from /usr/local/include/absl/log/internal/strip.h:24:
/usr/local/include/absl/log/internal/log_message.h:289:17: error: invalid operands to binary expression ('std::ostream' (aka 'basic_ostream<char>') and 'const operations_research::scheduling::rcpsp::RcpspProblem')
  view.stream() << log_internal::NullGuard<T>().Guard(v);`

I still seems to be related to abseil, but now the error comes from the local library

**Comment by lperron** [comment]
obsolete. I removed log.cc
