### ISSUE TITLE
fzn-ortools: seems to give up on div and mod if divisor can be negative

### ISSUE THREAD

**Issue by matsc-at-sics-se** [google/or-tools#3767]
**What version of OR-Tools and what language are you using?**
Version: 9.6
Language: MiniZinc
Linux Ubuntu 22.04

**What did you do?**
```
$ cat /tmp/latest.mzn
var -10..10: A;
var -10..10: B;
var -10..10: C;
constraint
  A div C=B;
$ minizinc --solver ortools /tmp/latest.mzn
=====UNKNOWN=====
```
The same thing happens for `mod`.

**Comment by lperron** [comment]
yes. We reject models where divisor or mod span across 0.
