### ISSUE TITLE
Constraint Solver Null Reference Error

### ISSUE THREAD

**Issue by rajatjangir** [google/or-tools#377]
Hi,

I have been working on Capacitated Vehicle Routing Problem with time windows.

My scheduler was running fine till last month i.e april 2017.
Recently i have been getting the following error when i try to schedule about 600+ nodes.
**"Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.RoutingModel_SolveWithParameters(HandleRef jarg1, Int32 proto_size, Byte[] jarg2)"**

Not able to understand why this error is occurring as the error only says null reference exception and does not gives much description.

Now surprisingly when i keep trying the same schedule a few time then sometimes it gets scheduled and sometimes not.

Not able to pinpoint what is the error, also can't inspect the elements using visual studio as the dll is made using some kind of wrapper.

**Comment by lperron** [comment]
Definitely a GC related issue.

Every callback you give to the solver must be stored somewhere, otherwise, they will be garbage collected.

I will close this issue. Please reopen if you still have problems.

**Comment by Mizux** [comment]
Seems to be the same issue than #270
