### ISSUE TITLE
SetCallback usage for mip model

### ISSUE THREAD

**Issue by Robot-1x** [google/or-tools#3776]
**What language and solver does this apply to?**
Java

**Describe the problem you are trying to solve.**
MIP model, I want to add lazy constraints in mip model.

**Describe the solution you'd like**
Used MPConstraint.SetIsLazy and it worked. Find MPSolver.SetCallback method. If I want to add lazy constraints as needed and more dynamically, what should I do?

**Comment by lperron** [comment]
This is not implemented with MPSolver.
It will be with math_opt, but not yet.
