### ISSUE TITLE
different solution in Vehicle Routing problems

### ISSUE THREAD

**Issue by bl75** [google/or-tools#3784]
Version: 9.6.2534
Language: Python

Routing Solver

Ubuntu 22.04.2 LTS

Suppose we solve vehicle routing problems with capacity constraints and use five vehicles in standard is given data. The solver uses only four vehicles and gives the optimal solution of 6460; if we give four vehicles, the optimal solution is 6208. Both solutions use only four vehicles but provide different solutions. 

So it should provide the same solution.

**Comment by hklarner** [comment]
But ORTOOLs uses a heuristic search algorithm that depends on the initial conditions. If you start the search from another starting place you, unfortunately, might end up with a different solution.

**Comment by bl75** [comment]
But still, it should provide the best solution, which is 6208

**Comment by bl75** [comment]
And is there any way that the solver doesn't minimize the vehicles and utilize all the vehicles

**Comment by lperron** [comment]
So: 
 - this is an approximate solver. It does not guarantee optimality. You can use meta-heuristics like gls to improve the solution you get at the expanse of using a mandatory time limit
 - the solver minimizes the cost which is a combination of many things. If you do not specify a fixed cost per vehicle, the solver does not favor more or less vehicles for the sake of it.
 - this is not an issue. So I will close for now.
