### ISSUE TITLE
Downtimes in coin-or.org

### ISSUE THREAD

**Issue by navidR** [google/or-tools#379]
I do experience regular downtimes in projects.coin-or.org host (last night was the second time), and it is very annoying when you have to clean build and you notice their server is down. Since there is official (at least it seems) mirror : 
https://github.com/coin-or/Cbc

How about we change Makefiles to do a clone from their mirror from github via git.

**Comment by lperron** [comment]
Unfortunately, github does not support reliably nested repository.
When you checkout cbc, it drags clp, CoinUtils.... Which it does not do.

There were a build script that should take care of everything, but last
time I checked, it did not work at all :-(

So, I will look into this, but I have low hope.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-05-13 1:39 GMT+02:00 Navid Rahimi <notifications@github.com>:

**Comment by DevNamedZed** [comment]
Its down right now :(


svn co https://projects.coin-or.org/svn/Cbc/releases/2.9.9 dependencies/sources/cbc-2.9.9
svn: E170013: Unable to connect to a repository at URL 'https://projects.coin-or.org/svn/Cbc/releases/2.9.9'
svn: E000011: Error running context: Resource temporarily unavailable
makefiles/Makefile.third_party.unix.mk:228: recipe for target 'dependencies/sources/cbc-2.9.9/Makefile.in' failed
make: *** [dependencies/sources/cbc-2.9.9/Makefile.in] Error 1

**Comment by hagilemha** [comment]
Down now

**Comment by Mizux** [comment]
Currently I've "forked" https://github.com/Mizux/Cbc mainly to add CMake support but maybe we should use this repo for Makefile also.

note: I started from the svn tar.gz provided https://www.coin-or.org/download/source/Cbc/Cbc-2.9.9.tgz since github "mirror" has a borken layout...
