### ISSUE TITLE
terminate called after throwing an instance of 'Swig::DirectorException'   what():  Index: 0, Size: 0

### ISSUE THREAD

**Issue by rapinchen** [google/or-tools#3800]
<dependency>
	<groupId>com.google.ortools</groupId>
	<artifactId>ortools-java</artifactId>
	<version>9.6.2534</version>
</dependency>

Some conditions may have this error, and then the program collapses.

terminate called after throwing an instance of 'Swig::DirectorException'   what():  Index: 0, Size: 0

The above is running in CentOS

It collapsed like Windows, and the mistake was as follows

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363) at pc=0x00007ffbc20c536c, pid=8792, tid=0x00000000000079e0
#
# JRE version: Java(TM) SE Runtime Environment (8.0_231-b11) (build 1.8.0_231-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.231-b11 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [KERNELBASE.dll+0x6536c]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\project\test\hs_err_pid8792.log
Compiled method (c1)   11557  912  s    3       java.lang.Throwable::fillInStackTrace (29 bytes)
 total in heap  [0x0000000003d4b250,0x0000000003d4b800] = 1456
 relocation     [0x0000000003d4b370,0x0000000003d4b3b8] = 72
 main code      [0x0000000003d4b3c0,0x0000000003d4b6c0] = 768
 stub code      [0x0000000003d4b6c0,0x0000000003d4b768] = 168
 metadata       [0x0000000003d4b768,0x0000000003d4b770] = 8
 scopes data    [0x0000000003d4b770,0x0000000003d4b7a8] = 56
 scopes pcs     [0x0000000003d4b7a8,0x0000000003d4b7f8] = 80
 dependencies   [0x0000000003d4b7f8,0x0000000003d4b800] = 8
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

Process finished with exit code 1

**Comment by lperron** [comment]
I cannot act of this. Please send us a code that reproduces the error and reopen the bug report.
