### ISSUE TITLE
CP-SAT not multiprocessing

### ISSUE THREAD

**Issue by p-ebert** [google/or-tools#3801]
**What version of OR-Tools and what language are you using?**
Version: ortools==9.3.10497
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Operating System: Debian GNU/Linux 10 (buster)
Kernel: Linux 4.19.0-24-cloud-amd64
Architecture: x86-64
16 core 

**What did you do?**

I replicated the toy problem from the docs, expanding the search space of the variable so that it would take longer to find the solution, giving us time to inspect the processes used. 

```python
from ortools.sat.python import cp_model

def main():
    """Minimal CP-SAT example to showcase calling the solver."""
    # Creates the model.
    model = cp_model.CpModel()

    # Creates the variables.
    var_upper_bound = max(50, 45, 37)
    x = {}
    for i in range(1000000):
        x[i] = model.NewIntVar(0, var_upper_bound, f'x_{i}')

    model.Maximize(cp_model.LinearExpr.Sum([x[i] for i in range(1000000)]))

    # Creates a solver and solves the model.
    solver = cp_model.CpSolver()
    solver.parameters.num_search_workers = 8

    status = solver.Solve(model)

    if status == cp_model.OPTIMAL or status == cp_model.FEASIBLE:
        print(f'Maximum of objective function: {solver.ObjectiveValue()}\n')
    else:
        print('No solution found.')

    # Statistics.
    print('\nStatistics')
    print(f'  status   : {solver.StatusName(status)}')
    print(f'  conflicts: {solver.NumConflicts()}')
    print(f'  branches : {solver.NumBranches()}')
    print(f'  wall time: {solver.WallTime()} s')


if __name__ == '__main__':
    main()
```
**What did you expect to see**

As I set set solver.parameters.num_search_workers = 8, I expected to see 8 cores utilised when I run the htop command and an increase in performance. 

**What did you see instead?**

Only a single core is being utilised, as shown below.

![Capture d’écran 2023-05-26 à 15 28 52](https://github.com/google/or-tools/assets/55658288/9ca74caa-1063-4e01-936d-c56619a3656d)

**Comment by lperron** [comment]
I guess you have not exited presolve, which is currently mono-thread. 
Search will use multiple workers
