### ISSUE TITLE
CP-SAT should provide feasible solution before crashing (due to less RAM or any other reason which can be detected early on)

### ISSUE THREAD

**Issue by arnabadas** [google/or-tools#3802]
**What language and solver does this apply to?**
All / CP-SAT

**Describe the problem you are trying to solve.**
The application should not crash before providing a feasible solution (if any)

**Describe the solution you'd like**
The application provides a solution before crash

**Describe alternatives you've considered**
Call solution callback when RAM usage reaches 99%, but don't know how to implement.

**Additional context**

**Comment by lperron** [comment]
Don't know how to implement.
