### ISSUE TITLE
CMake: Windows cl.exe can't build or-tools anymore

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#3807]
trace example: 
```sh
4758 "D:\a\or-tools\or-tools\build\ALL_BUILD.vcxproj" (default target) (1) ->
4759 "D:\a\or-tools\or-tools\build\ortools\glop\ortools_glop.vcxproj" (default target) (76) ->
4760 (ClCompile target) -> 
4761 D:\a\or-tools\or-tools\build\_deps\absl-src\absl\container\internal\compressed_tuple.h(88): fatal  error C1001: Internal compiler error. [D:\a\or-tools\or-tools\build\ortools\glop\ortools_glop.vcxproj]
4762 cl : command line  error D8040: error creating or communicating with child process [D:\a\or-tools\or-tools\build\ortools\glop\ortools_glop.vcxproj]
4763
4764 13 Warning(s)
4765 2 Error(s)
```
ref: https://github.com/google/or-tools/actions/runs/5132839527/jobs/9234655226

**Comment by Mizux** [comment]
dev note: May be due to the last google3 sync, on my way to debug it...

**Comment by magneticflux-** [comment]
I am able to build `main` using Visual Studio 17.7.0 Preview 1, although I had to manually fix some function signatures that had `const` removed in https://github.com/google/or-tools/commit/f25897b5668b63e94088fac8a19cbd32897c0cc7 since they caused linker errors.

**Comment by Mizux** [comment]
> I am able to build `main` ([85fc6ef](https://github.com/google/or-tools/commit/85fc6ef2d45d25bd4310ef9e69f24fe0057d10ad)) using Visual Studio 17.7.0 Preview 1, although I had to manually fix some function signatures that had `const` removed in [f25897b](https://github.com/google/or-tools/commit/f25897b5668b63e94088fac8a19cbd32897c0cc7) since they caused linker errors.

Yup, I spotted few of them in our CI already but the above crash block me to build locally and fix them... `-_-`
ref:
https://github.com/google/or-tools/actions/runs/5168581137/jobs/9310266516
https://github.com/google/or-tools/actions/runs/5168581160/jobs/9310266633

Otherwise concerning `const` in function declaration it is an issue raise by clang-tidy on linux internally so googlers try to fix them (from gcc/clang compiler pov `const` is unneeded in function **declaration**, only in function **definition** it ~~is~~ can be useful and both methods are equivalent btw). **BUT** when using cl.exe microsoft is more picky in mangling and const seems to be part of the prototype somehow.
see:
https://github.com/google/or-tools/blob/85fc6ef2d45d25bd4310ef9e69f24fe0057d10ad/ortools/constraint_solver/constraint_solver.cc#L173-L179
and
https://github.com/google/or-tools/blob/85fc6ef2d45d25bd4310ef9e69f24fe0057d10ad/ortools/constraint_solver/demon_profiler.cc#L442
https://github.com/google/or-tools/blob/85fc6ef2d45d25bd4310ef9e69f24fe0057d10ad/ortools/constraint_solver/demon_profiler.cc#L444
https://github.com/google/or-tools/blob/85fc6ef2d45d25bd4310ef9e69f24fe0057d10ad/ortools/constraint_solver/demon_profiler.cc#L452
...

On my way to fix them if I manage to update VisualStudio 17 to prevent cl.exe to crash ;)

**Comment by Mizux** [comment]
UPDATE:
* Visual Studio Community 2022: 17.6.33723 (17.6.2): be able to reproduce the cl.exe crash
* Visual Studio Enterprise 2022: 17.6.33712.159: linkage error (see above)
* Visual Studio Community 2022 17.7.0 preview 1.0:  1.17.33711.374: linkage error (see above)

dev note:
```sh
"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest
"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -prerelease
```

**Comment by Mizux** [comment]
seems github windows runner is playing with the VS Version

2 weeks ago: 
VS Enterprise 2022 19.**36**.32532.0: Build Fail
Since Yesterday
VS Enterprise 2022 19.**35**.32217: Build Pass

**Comment by Mizux** [comment]
Failing again since runner reuse 14.36 version...

```
2023-09-04T14:57:30.7025838Z -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.36.32532/bin/HostX64/x64/cl.exe - skipped
```
ref: https://github.com/google/or-tools/actions/runs/6075019490/job/16480348923
