### ISSUE TITLE
Upgrading to protobuf==3.2.0 in the Python client

### ISSUE THREAD

**Issue by mxr** [google/or-tools#381]
Hello, we'd love to use `or-tools` in Python, but we have a dependency on `protobuf==3.2.0`. I see that the `PROTOBUF_TAG` is set to `3.2.0` across Makefiles, but there are a few hardcoded references to `protobuf-3.0.0` in the [Python Makefile](https://github.com/google/or-tools/blob/b6632140a5559aa2a6d45448edc3802ab83e013d/makefiles/Makefile.python.mk#L57-L59), causing `or-tools` to depend on `3.0.0`. Because of this we get downgraded when we install `or-tools` (leading to other libraries breaking).

```
(venv) ~/tmp $ pip install protobuf==3.2.0
<snip>
Successfully installed protobuf-3.2.0
(venv) ~/tmp $ pip freeze -l | grep protobuf
protobuf==3.2.0
(venv) ~/tmp $ pip install ortools
<snip>
Successfully installed ortools-5.1.4045 protobuf-3.0.0
(venv) ~/tmp $ pip freeze -l | grep protobuf
protobuf==3.0.0
```
Are there plans to update `or-tools` to `protobuf==3.2.0`?

Thanks!

**Comment by lperron** [comment]
It should be fixed now.

I did a release yesterday, it should be announced soon.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-05-17 6:15 GMT+02:00 Max Rozentsveyg <notifications@github.com>:

**Comment by mxr** [comment]
Thanks @lperron this is great news! Do you have a timeline for when the next release will be announced? Will it be published as a wheel on pypi as well?

**Comment by lperron** [comment]
It is already pushed on pypi.
I am writing the release notes today.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-05-18 7:52 GMT+02:00 Max Rozentsveyg <notifications@github.com>:

**Comment by mxr** [comment]
Can you clarify? I don't see a Linux wheel on [pypi](https://pypi.python.org/pypi/ortools) yet.

<img width="916" alt="screen shot 2017-05-18 at 8 57 59 am" src="https://cloud.githubusercontent.com/assets/252209/26211825/4fb89d92-3ba8-11e7-859c-c89584ba3881.png">

**Comment by chiragchheda** [comment]
Hi @lperron. Thanks for quickly upgrading the protobuf dependency. Like @mxr mentioned in his previous comment, it would be awesome if you can help with releasing the wheels for ortools on Linux.

Thank you.

**Comment by lperron** [comment]
I tried, you need to install manylinux on a centOS docker, compile multiple
versions and merge them :-(
I kindly propose you install or-tools from sources and build .egg file
locally (make python_archive).

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-05-23 3:02 GMT+02:00 Chirag Chheda <notifications@github.com>:
