### ISSUE TITLE
Version 9.6 on python adds a dependency to scipy even if it's not used.

### ISSUE THREAD

**Issue by CaselIT** [google/or-tools#3818]
**What language and solver does this apply to?**
Python

**Describe the problem you are trying to solve.**
Version 9.6 installs scipy but it's not used by the library.
The only usage that are defined are in the test and the sample, that are not in the pypi package.
https://github.com/search?q=repo%3Agoogle%2For-tools+scipy+language%3APython&type=code&l=Python

**Describe the solution you'd like**
scipy is not defined as a dependency

**Describe alternatives you've considered**
--

**Additional context**

While it's really a big problem having it, scipy is quite large as a library and it has an impact on docker contain sizes etc.
thanks

**Comment by Mizux** [comment]
Then if SCIPY is only needed for testing we should change:

Remove deps from package
https://github.com/google/or-tools/blob/5425dedcfbb22cb74c636c1374a9b5ad684b1eb5/ortools/python/setup.py.in#L49

Install it in our venv when testing:
https://github.com/google/or-tools/blob/5425dedcfbb22cb74c636c1374a9b5ad684b1eb5/cmake/python.cmake#L385

**Comment by CaselIT** [comment]
thanks for confirming
