### ISSUE TITLE
Correct architecture spec in Makefile of Java binary installation for macOS M1

### ISSUE THREAD

**Issue by antononcube** [google/or-tools#3824]
**What version of OR-Tools and what language are you using?**

Version: or-tools_arm64_macOS-13.2.1_java_v9.6.2534

Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

Any

**What operating system (Linux, Windows, ...) and version?**

macOS 

**What did you do?**

I followed the installation directions here :
["Installing OR-Tools for Java from Binary on MacOS"](https://developers.google.com/optimization/install/java/binary_mac)

1. Go to 

https://developers.google.com/optimization/install/java/binary_mac

3. Click on 

[MacOS M1](https://github.com/google/or-tools/releases/download/v9.6/or-tools_arm64_macOS-13.2.1_java_v9.6.2534.tar.gz)

4. Open Terminal, go to Downloads, Unzip and untar.
5. Execute the command:

```
make test
```

7. See error:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make run SOURCE=examples/LinearProgramming/src/main/java/com/google/ortools/LinearProgramming.java
make[1]: *** No rule to make target `ortools-darwin-x86-64-9.6.2534.jar', needed by `java.log'.  Stop.
make: *** [test] Error 2
```

**What did you expect to see**

The tests to be executed.

**What did you see instead?**

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make run SOURCE=examples/LinearProgramming/src/main/java/com/google/ortools/LinearProgramming.java
make[1]: *** No rule to make target `ortools-darwin-x86-64-9.6.2534.jar', needed by `java.log'.  Stop.
make: *** [test] Error 2
```

**Anything else we should know about your project / environment**

The tests were executed after I changed the Makefile  line 128 that specifies `JAVA_NATIVE_IDENTIFIER ` for Darwin/macOS to have the value `darwin-aarch64` :

```
    ifeq ($(OS),Darwin)
    JAVA_NATIVE_IDENTIFIER=darwin-aarch64
```

**Comment by Mizux** [comment]
Good Catch !

Code to change:
https://github.com/google/or-tools/blob/24ea806809ca62e98401954a3c43b406eb337c4e/tools/Makefile.java.mk#L127-L128

may need:
https://github.com/google/or-tools/blob/24ea806809ca62e98401954a3c43b406eb337c4e/makefiles/Makefile.java.mk#L74-L78

**Comment by antononcube** [comment]
Thank you!
