### ISSUE TITLE
There is no AddProductEquality implementation for python

### ISSUE THREAD

**Issue by ArthurMor4is** [google/or-tools#3825]
Language: Python
Solver: CP-SAT

The documentation exemplifies the use of AddProductEquality() in this section here: https://github.com/google/or-tools/blob/stable/ortools/sat/docs/integer_arithmetic.md#limitations

But this method do not exists in this current implementation.

I think that one option is using the AddMultiplicationEquality() method here: https://github.com/google/or-tools/blob/5425dedcfbb22cb74c636c1374a9b5ad684b1eb5/ortools/sat/python/cp_model.py#L1637

I think that one update in the current documentation is necessary

**Comment by Mizux** [comment]
@lperron to change:

https://github.com/google/or-tools/blob/496af9f36456ca621eccb910539ce4452b73f9fe/ortools/sat/docs/integer_arithmetic.md?plain=1#L132-L133
