### ISSUE TITLE
Build failure with Protobuf 22+

### ISSUE THREAD

**Issue by carlocab** [google/or-tools#3826]
**What version of OR-Tools and what language are you using?**
Version: v9.6
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

N/A

**What operating system (Linux, Windows, ...) and version?**

Linux (Ubuntu 22.04) and macOS (11, 12, and 13)

**What did you do?**
- Build or-tools with Protobuf 22+.

**What did you expect to see**
Successful build.

**What did you see instead?**
Build failure. On Linux:
```
  /tmp/or-tools-20230617-12206-1wpcyx0/or-tools-9.6/ortools/base/logging.h:60:6: error: redefinition of ‘template<class Sink> void google::protobuf::AbslStringify(Sink&, const google::protobuf::Message&)’
     60 | void AbslStringify(Sink& sink, const Message& msg) {
        |      ^~~~~~~~~~~~~
  In file included from /tmp/or-tools-20230617-12206-1wpcyx0/or-tools-9.6/ortools/base/logging.h:29,
                   from /tmp/or-tools-20230617-12206-1wpcyx0/or-tools-9.6/ortools/algorithms/dynamic_partition.h:38,
                   from /tmp/or-tools-20230617-12206-1wpcyx0/or-tools-9.6/ortools/algorithms/dynamic_partition.cc:14:
  /home/linuxbrew/.linuxbrew/include/google/protobuf/message.h:342:15: note: ‘template<class Sink> void google::protobuf::AbslStringify(Sink&, const google::protobuf::Message&)’ previously declared here
    342 |   friend void AbslStringify(Sink& sink, const google::protobuf::Message& message) {
        |               ^~~~~~~~~~~~~
```
On macOS:
```
  In file included from /tmp/or-tools-20230617-9813-dpqj82/or-tools-9.6/ortools/algorithms/dynamic_partition.cc:14:
  In file included from /tmp/or-tools-20230617-9813-dpqj82/or-tools-9.6/ortools/algorithms/dynamic_partition.h:38:
  /tmp/or-tools-20230617-9813-dpqj82/or-tools-9.6/ortools/base/logging.h:60:6: error: redefinition of 'AbslStringify'
  void AbslStringify(Sink& sink, const Message& msg) {
       ^
  /opt/homebrew/include/google/protobuf/message.h:342:15: note: previous definition is here
    friend void AbslStringify(Sink& sink, const google::protobuf::Message& message) {
                ^
```

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

The error was generated from an attempt to build against Protobuf 23.3 at Homebrew/homebrew-core#134013. Build logs are available [here](https://github.com/Homebrew/homebrew-core/actions/runs/5296614525).

----

We can see that Protobuf defines `AbslStringify` starting from protocolbuffers/protobuf@afaf93b85db8ab9b25a1910ffbec59a2d80bfc12.

This conflicts with the definition of `AbslStringify` at

https://github.com/google/or-tools/blob/5425dedcfbb22cb74c636c1374a9b5ad684b1eb5/ortools/base/logging.h#L55-L64

Removing the definition from or-tools allows the build to succeed. Alternatively, one may wrap it with an appropriate macro that conditions on whether the definition is needed. A quick and dirty solution would be to check whether [`GOOGLE_PROTOBUF_VERSION`](https://github.com/protocolbuffers/protobuf/blob/8997b54c32a4a2133536ce73be67108ec507c8bd/src/google/protobuf/stubs/common.h#L69) is less than or equal to `3021012` but it's not clear that this works when building against an unreleased version of Protobuf (e.g. from an arbitrary commit).

One can probably use CMake's [`check_symbol_exists`](https://cmake.org/cmake/help/latest/module/CheckSymbolExists.html#module:CheckSymbolExists) to see if Protobuf defines `AbslStringify` and then use that result with the preprocessor, but then this strategy does not work for Bazel builds. (I know nothing about Bazel, so I am unable to offer a solution there.)

**Comment by lperron** [comment]
protobuf requires the latest version of abseil

**Comment by lperron** [comment]
and or-tools has not been release with support to the latest version

**Comment by carlocab** [comment]
At Homebrew, we've been using or-tools with the latest version of Abseil without any problems.

**Comment by lperron** [comment]
I think you have a patch for the stable branch. Next week, we should release 9.7 that does not need this patch.

**Comment by carlocab** [comment]
Thanks!

**Comment by 0xfadead** [comment]
I still have the same issue while building.
