### ISSUE TITLE
linear_solver.cc:1886] The model has been changed since the solution was last computed. MPSolverInterface::sync_status_ = 0

### ISSUE THREAD

**Issue by gabriel-gehrke** [google/or-tools#3830]
Version: 9.6.2534 (installed via pip)
Language: Python 3.10.6
Environment: Inside Jupyter Notebook

Solver: GLOP from ortools.linear_solver.pywraplp
OS: Linux Mint 21

1. Build linear model, solve it.
2. Add constraints after solving, solve again.

Expected behavior: No internal errors on console, just a returned status after every call to Solve().

Actual behavior:
Works correctly (at least it seems so), but dozens of identical log messages such as below are printed
```
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1687455038.113376   14812 linear_solver.cc:1886] The model has been changed since the solution was last computed. MPSolverInterface::sync_status_ = 0
E0000 00:00:1687455038.113405   14812 linear_solver.cc:1886] The model has been changed since the solution was last computed. MPSolverInterface::sync_status_ = 0
E0000 00:00:1687455038.113407   14812 linear_solver.cc:1886] The model has been changed since the solution was last computed. MPSolverInterface::sync_status_ = 0
...
```

I use the lp solver as a tool to calculate an upper bound based on linear relaxation to a specific graph problem, similar to the TSP. I iteratively solve the model and add constraints that enforce stricter rules. 

The solver always returns OPTIMAL as status and also seems to work correctly, but the console is filled with these errors/warnings. I made sure that the solver is actually called, as there was a similar issue were it turned out that the Solve() method was never called.

If needed, I can provide the whole source code.

**Comment by gabriel-gehrke** [comment]
I found the problem. I was reading solution values from some variables after adding constraints to the solver. When moving all solution reading to before new constraints are added, no errors are logged.

**Comment by Mizux** [comment]
Thx for taking time to share the solution ! Hope it will help someone in the future ;)
