### ISSUE TITLE
Windows build fails (checked while building python wheel)

### ISSUE THREAD

**Issue by arnabadas** [google/or-tools#3832]
**What version of OR-Tools and what language are you using?**
Version: main
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
NA

**What operating system (Linux, Windows, ...) and version?**
Windows 10 22H2

**What did you do?**
Follow install OR-Tools from source in Python instructions

**What did you expect to see**
Successful build

**What did you see instead?**
[error.txt](https://github.com/google/or-tools/files/11848170/error.txt)

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
I am using msvc 17.7 preview 2

**Comment by Mizux** [comment]
`--mypy_out: protoc-gen-mypy: Plugin failed with status code 1.`
Please verify you have `mypy-protobuf` installed AND in your path so protoc can call it...

**Comment by arnabadas** [comment]
Corrupted the Path while creating an updated temporary path. Fixed it by starting a new session. Thanks for the help.
