### ISSUE TITLE
sat_runner.exe is 2 times slower on Windows than on WSL on the same machine

### ISSUE THREAD

**Issue by proshkin** [google/or-tools#3834]
**What version of OR-Tools and what language are you using?**
Version: main
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

**What operating system (Linux, Windows, ...) and version?**
Windows

**What did you do?**
1. compile main branch from the source both in Windows and WSL (Ubuntu 22.04)
2. run sat_runner --input=big_model2.txt
3. I Also tried sat_runner.exe from the stable binary and source build with the same problem

**What did you expect to see**
Similar execution time 
**What did you see instead?**
WSL (main) solving time: 58s
WSL (stable): 21s!
Windows (main): 489s.!!

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
[wsl_main_result.log](https://github.com/google/or-tools/files/11857792/wsl_main_result.log)
[big_model2.txt](https://github.com/google/or-tools/files/11857819/big_model2.txt)
[wsl_result_stable.log](https://github.com/google/or-tools/files/11857821/wsl_result_stable.log)
[windows_result_main.log](https://github.com/google/or-tools/files/11857822/windows_result_main.log)

**Comment by Regista6** [comment]
With 8 workers, sat_runner (9.6 stable binary windows) gives me [optimal ](https://gist.github.com/Regista6/9bcd8efb661d57d0ddbd58e4efb41bd3)in ~55 sec! and with 12 workers, it's around ~77 sec.

Side Note: I had to delete my comment on google group as I ran it on big_model1. Are both models the same as the fingerprint remains the same?

**Comment by lperron** [comment]
I just compiled everything on my laptop. I used the command lines in the github action.
I use the head of the main branch, visual studio community 2022 preview 1.7.0 rc2 (to fix a compilation crash)
I use 8 cores. My laptop is 8 cores + 8 hyperthread

wsl: 

CpSolverResponse summary:
status: OPTIMAL
objective: 1025920100
best_bound: 1025920100
integers: 4006
booleans: 27647
conflicts: 201
branches: 33360
propagations: 64914
integer_propagations: 9148128
restarts: 34
lp_iterations: 4087
walltime: 62.4596
usertime: 62.4596
deterministic_time: 8.83922
gap_integral: 49.6309
solution_fingerprint: 0x2742c7df705300fa

Windows: 

CpSolverResponse summary:
status: OPTIMAL
objective: 1025920100
best_bound: 1025920100
integers: 4006
booleans: 22379
conflicts: 382
branches: 28938
propagations: 76470
integer_propagations: 7927420
restarts: 38
lp_iterations: 4123
walltime: 114.497
usertime: 114.497
deterministic_time: 12.7118
gap_integral: 83.3673
solution_fingerprint: 0x2742c7df705300fa

Windows is 2x slower. It is either the community edition optimizing less, or some flag that is different on windows.
I will investigate further.

**Comment by proshkin** [comment]
I found the reason for the extreme slowness in the pre-solve stage: My terminal was configured to run in Compatability Mode (Windows 8). After turning it off, pre-solve is consistently fast.  
My latest timing test results on Rizen5950X (16 cores, 32 threads)  (I ran each case 3 times with different num_workers parameters) below. They much better, especially for num_workers = 8, but still significantly slower than WSL. 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/prosh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/prosh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



System | Branch | num_workers | time1 | time2 | time3
-- | -- | -- | -- | -- | --
Windows | main | 8 | 58 | 64 | 67
  |   | 16 | 80 | 75 | 78
  |   | 32 | 174 | 142 | 330
WSL | main | 8 | 33 | 34 | 33
  |   | 16 | 39 | 40 | 40
  |   | 32 | 41 | 57 | 24
WSL | stable | 8 | 22 | 21 | 22
  |   | 16 | 23 | 24 | 23
  |   | 32 | 24 | 26 | 27



</body>

</html>

**Comment by proshkin** [comment]
I have/had three issues on Windows:
1. Running in Compatability mode (fixed)
2. Running with 32 workers. It is still much slower (more than ten times in some cases) than running with the same number of workers on WSL
3. Even running with eight workers is two times slower.

Also, the main is 1.5-2 times slower than the stable. Is it expected?

I also noticed that if the number of workers is set to 15 or more, then performance drops and some values in the model summary changed to 0:
14 workers:
status: OPTIMAL
objective: 1025920100
best_bound: 1025920100
integers: 4006
booleans: 13539
conflicts: 259
branches: 17734
propagations: 75254
integer_propagations: 3845309
restarts: 35
lp_iterations: 7973
walltime: 63.1078
usertime: 63.1078
deterministic_time: 23.6404
gap_integral: 204.327
solution_fingerprint: 0x2742c7df705300fa

15 workers:
status: OPTIMAL
objective: 1025920100
best_bound: 1025920100
integers: 4006
_**booleans: 0
conflicts: 0
branches: 0
propagations: 0
integer_propagations: 0
restarts: 0
lp_iterations: 0**_
walltime: 83.7771
usertime: 83.7771
deterministic_time: 39.6087
gap_integral: 363.282
solution_fingerprint: 0x2742c7df705300fa

**Comment by lperron** [comment]
Summary is meaningless. Ignore it.
Above 16 workers, you start to use hyperthreads. This slows down the
successful workers, and can help or not.

About the slowdown by 2 w.r.t. main, we will investigate.

About the slowdown w.r.t. wsl, are you using the community edition ?
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by proshkin** [comment]
Yes, I am using Community Edition Preview 2

**Comment by lperron** [comment]
I assume code optimization is much lower with the community edition
compared to the enterprise version.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by lperron** [comment]
I will close the issue. There is not much I can do.The code is compiled in opt model
