### ISSUE TITLE
Unable to install OR-tools- no version attribute

### ISSUE THREAD

**Issue by Gomorrah76** [google/or-tools#384]
I'm having some issues installing OR-tools, if someone could give me hand that would be great :)

Using a freshly downloaded VM (Ubuntu 16.10 Yakkety Yak from OS boxes), have done nothing to it except:

sudo apt-get install python-setuptools
sudo apt-get install g++
downloaded Python—tar.gz, extracted in Downloads 
run make install from Downloads

I get an error "You are using a ortools module that doesn't have a __version__ attribute"

Running /usr/bin/python setup.py install --user works, but the error "warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no Python modules to install" pops up. 

Removing the __init__.pyc file tells me to remove the __init__.py file, and then it says or-tools isn't found. 

Any assistance is greatly appreciated, still learning Linux so I'm sure I'm doing something dumb....

Full output of make install: 

python setup.py install --user
running install
running bdist_egg
running egg_info
writing requirements to ortools_examples.egg-info/requires.txt
writing ortools_examples.egg-info/PKG-INFO
writing top-level names to ortools_examples.egg-info/top_level.txt
writing dependency_links to ortools_examples.egg-info/dependency_links.txt
reading manifest file 'ortools_examples.egg-info/SOURCES.txt'
writing manifest file 'ortools_examples.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no Python modules to install

creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/ortools_examples-6.0.4217-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ortools_examples-6.0.4217-py2.7.egg
Removing /home/osboxes/.local/lib/python2.7/site-packages/ortools_examples-6.0.4217-py2.7.egg
Copying ortools_examples-6.0.4217-py2.7.egg to /home/osboxes/.local/lib/python2.7/site-packages
ortools-examples 6.0.4217 is already the active version in easy-install.pth

Installed /home/osboxes/.local/lib/python2.7/site-packages/ortools_examples-6.0.4217-py2.7.egg
Processing dependencies for ortools-examples==6.0.4217
Searching for ortools==6.0.4217
Best match: ortools 6.0.4217
Processing ortools-6.0.4217-py2.7-linux-x86_64.egg
ortools 6.0.4217 is already the active version in easy-install.pth

Using /home/osboxes/.local/lib/python2.7/site-packages/ortools-6.0.4217-py2.7-linux-x86_64.egg
Searching for protobuf==3.2.0
Best match: protobuf 3.2.0
Processing protobuf-3.2.0-py2.7.egg
protobuf 3.2.0 is already the active version in easy-install.pth

Using /home/osboxes/.local/lib/python2.7/site-packages/protobuf-3.2.0-py2.7.egg
Searching for setuptools==26.1.1
Best match: setuptools 26.1.1
Adding setuptools 26.1.1 to easy-install.pth file
Installing easy_install script to /home/osboxes/.local/bin

Using /usr/lib/python2.7/dist-packages
Searching for six==1.10.0
Best match: six 1.10.0
Processing six-1.10.0-py2.7.egg
six 1.10.0 is already the active version in easy-install.pth

Using /home/osboxes/.local/lib/python2.7/site-packages/six-1.10.0-py2.7.egg
Finished processing dependencies for ortools-examples==6.0.4217
python check_python_deps.py --log=ERROR
[ERROR] You are using a ortools module that doesn't have a __version__ attribute : /home/osboxes/.local/lib/python2.7/site-packages/ortools-6.0.4217-py2.7-linux-x86_64.egg/ortools/__init__.pyc"
Run "/usr/bin/python setup.py install --user" to upgrade.
If the problem persists, remove the site-package that contains "/home/osboxes/.local/lib/python2.7/site-packages/ortools-6.0.4217-py2.7-linux-x86_64.egg/ortools/__init__.pyc". You can do so either manually or by using pip.

**Comment by diegoalberione** [comment]
Hi, I have the same problem. Could you solve it? thks!

**Comment by lperron** [comment]
Yes, I will regenerate new pypi modules with the version attribute.
Expect it next monday.

If you are in a hurry, you can build from source and build the python
module.

See another mail I just posted.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-05-24 18:08 GMT+02:00 diegoalberione <notifications@github.com>:

**Comment by maxisawesome** [comment]
I also got this error message. I haven't tried to build from source yet but I will next.
The prompt reads "If the problem persists, remove the site-package that contains "/home/max/.local/lib/python2.7/site-packages/ortools-6.0.4217-py2.7-linux-x86_64.egg/ortools/__init__.pyc". You can do so either manually or by using pip." How would I maually "remove the site-package" that has that file?

**Comment by lperron** [comment]
The latest source dir contains the fix that adds the __version__ to the
__init__.py.

Sorry about that.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-05-31 1:43 GMT+02:00 maxisawesome <notifications@github.com>:

**Comment by maxisawesome** [comment]
Still getting the error after downloading the .zip under "Binary installation with support for Python" on the installing page. Gonna try building from source. Here's a copy of what the terminal spits out:

python setup.py install --user
running install
running bdist_egg
running egg_info
writing requirements to ortools_examples.egg-info/requires.txt
writing ortools_examples.egg-info/PKG-INFO
writing top-level names to ortools_examples.egg-info/top_level.txt
writing dependency_links to ortools_examples.egg-info/dependency_links.txt
reading manifest file 'ortools_examples.egg-info/SOURCES.txt'
writing manifest file 'ortools_examples.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/ortools_examples-6.0.4217-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ortools_examples-6.0.4217-py2.7.egg
Removing /home/max/.local/lib/python2.7/site-packages/ortools_examples-6.0.4217-py2.7.egg
Copying ortools_examples-6.0.4217-py2.7.egg to /home/max/.local/lib/python2.7/site-packages
ortools-examples 6.0.4217 is already the active version in easy-install.pth

Installed /home/max/.local/lib/python2.7/site-packages/ortools_examples-6.0.4217-py2.7.egg
Processing dependencies for ortools-examples==6.0.4217
Searching for ortools==6.0.4217
Best match: ortools 6.0.4217
Processing ortools-6.0.4217-py2.7-linux-x86_64.egg
ortools 6.0.4217 is already the active version in easy-install.pth

Using /home/max/.local/lib/python2.7/site-packages/ortools-6.0.4217-py2.7-linux-x86_64.egg
Searching for protobuf==3.2.0
Best match: protobuf 3.2.0
Processing protobuf-3.2.0-py2.7.egg
protobuf 3.2.0 is already the active version in easy-install.pth

Using /home/max/.local/lib/python2.7/site-packages/protobuf-3.2.0-py2.7.egg
Searching for setuptools==27.2.0
Best match: setuptools 27.2.0
Processing setuptools-27.2.0-py2.7.egg
setuptools 27.2.0 is already the active version in easy-install.pth
Installing easy_install script to /home/max/.local/bin
Installing easy_install-2.7 script to /home/max/.local/bin

Using /home/max/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using /home/max/anaconda2/lib/python2.7/site-packages
Finished processing dependencies for ortools-examples==6.0.4217
python check_python_deps.py --log=ERROR
[ERROR] You are using a ortools module that doesn't have a __version__ attribute : /home/max/.local/lib/python2.7/site-packages/ortools-6.0.4217-py2.7-linux-x86_64.egg/ortools/__init__.pyc"
Run "/home/max/anaconda2/bin/python setup.py install --user" to upgrade.
If the problem persists, remove the site-package that contains "/home/max/.local/lib/python2.7/site-packages/ortools-6.0.4217-py2.7-linux-x86_64.egg/ortools/__init__.pyc". You can do so either manually or by using pip.

**Comment by maxisawesome** [comment]
It sounds like you've solved this problem, but I'm not downloading the most recent/correct version. I used the tar.gz file from both "Download OR-Tools for Linux" "OR-TOOLS for Python" and the download on the install page and still got the same error. Where can I get "latest source dir" that contains the fix? This is probably a noob mistake from me - sorry!

**Comment by lisariccardi** [comment]
Hi! I am encountering the same error if downloading the 6.0 package

[ERROR] You are using a ortools module that doesn't have a __version__ attribute : /home/annalisa/.local/lib/python2.7/site-packages/ortools-6.0.4217-py2.7-linux-x86_64.egg/ortools/__init__.pyc"
Run "/usr/bin/python2.7 setup.py install --user" to upgrade.
If the problem persists, remove the site-package that contains "/home/annalisa/.local/lib/python2.7/site-packages/ortools-6.0.4217-py2.7-linux-x86_64.egg/ortools/__init__.pyc". You can do so either manually or by using pip.

I tried to compile from sources the Python-C++ version but I get this other error

running build
running build_py
swig -I. -c++ -python  -o ortools/gen/ortools/constraint_solver/constraint_solver_python_wrap.cc -module pywrapcp ./ortools/constraint_solver/python/routing.i
ortools/constraint_solver/constraint_solver.h:267: Warning 325: Nested struct not currently supported (IntegerCastInfo ignored)
ortools/constraint_solver/constraint_solver.h:1756: Error: Syntax error in input(3).
make: *** [ortools/gen/ortools/constraint_solver/pywrapcp.py] Error 1

how can I solve one of the two errors?
Thanks in advance for your help.
Annalisa

**Comment by YangChaoKiKa** [comment]
trying to do some light rnn, it seems like the ortools is a popular choices.  But or-tools seems like very hard to use.  encountered similar problems. 
Using /Users/xm/anaconda3/envs/python27TF_GPU/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg
Finished processing dependencies for ortools-examples==6.0.4217
python check_python_deps.py --log=ERROR
[ERROR] You are using a ortools module that doesn't have a __version__ attribute : /Users/xm/anaconda3/envs/python27TF_GPU/lib/python2.7/site-packages/ortools/__init__.pyc"
Run "/Users/xm/anaconda3/envs/python27TF_GPU/bin/python setup.py install --user" to upgrade.
If the problem persists, remove the site-package that contains "/Users/xm/anaconda3/envs/python27TF_GPU/lib/python2.7/site-packages/ortools/__init__.pyc". You can do so either manually or by using pip.

**Comment by jiangj001** [comment]
Exactly problems as  lisariccardi

**Comment by swethmandava** [comment]
I have the same problem. Were any of you able to fix it?

**Comment by luisdelatorre012** [comment]
No. I added a watch to the or-tools repository and I'll test it when the
update gets made and respond, since was the originator of the question.

**Comment by lperron** [comment]
Hi, 

I have added support for docker to build binary artefacts.
You do not need anything special, except docker, and it will spit out python egg and wheel files for different linux distros.

This way, you do not have to wait for me to build egg of whl files.

I hope this helps.

**Comment by CnApTaK** [comment]
same problem. win 10
`Finished processing dependencies for ortools-examples==6.2.4388
[ERROR] You are using a ortools module that doesn't have a __version__ attribute : C:\Users\brain\AppData\Roaming\Python\Python36\site-packages\py3_ortools-6.2.4388-py3.6-win-amd64.egg\ortools\__init__.py"
Run "C:\Program Files\Python36\python.exe setup.py install --user" to upgrade.
If the problem persists, remove the site-package that contains "C:\Users\brain\AppData\Roaming\Python\Python36\site-packages\py3_ortools-6.2.4388-py3.6-win-amd64.egg\ortools\__init__.py". You can do so either manually or by using pip.`

**Comment by lperron** [comment]
I found the error. It is bad escaping when creating the __version__
attribute.
On windows, it was written: "__version__ = \"6.2.4388\""

I pushed the fix on github.
It will create the 6.3 august release at the beginning of next month.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-07-20 13:23 GMT-07:00 CnApTaK <notifications@github.com>:

**Comment by lperron** [comment]
6.3 is live.
Can you check it?

Thanks

**Comment by maxisawesome** [comment]
Seemed to get farther this time, but I ran into another error. after running 'make install', this the output:

python2.7  setup.py install --user
running install
running bdist_egg
running egg_info
writing requirements to ortools_examples.egg-info/requires.txt
writing ortools_examples.egg-info/PKG-INFO
writing top-level names to ortools_examples.egg-info/top_level.txt
writing dependency_links to ortools_examples.egg-info/dependency_links.txt
reading manifest file 'ortools_examples.egg-info/SOURCES.txt'
writing manifest file 'ortools_examples.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/ortools_examples-6.2.4388-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ortools_examples-6.2.4388-py2.7.egg
Removing /home/m3/.local/lib/python2.7/site-packages/ortools_examples-6.2.4388-py2.7.egg
Copying ortools_examples-6.2.4388-py2.7.egg to /home/m3/.local/lib/python2.7/site-packages
ortools-examples 6.2.4388 is already the active version in easy-install.pth

Installed /home/m3/.local/lib/python2.7/site-packages/ortools_examples-6.2.4388-py2.7.egg
Processing dependencies for ortools-examples==6.2.4388
Searching for ortools==6.2.4388
Reading https://pypi.python.org/simple/ortools/
No local packages or working download links found for ortools==6.2.4388
error: Could not find suitable distribution for Requirement.parse('ortools==6.2.4388')
Makefile:51: recipe for target 'install' failed
make: *** [install] Error 1


In the makefile, should the python path be a string in quotes? I tried with and without, it didn't seem to change anything.... Currnetly reads like this: "UNIX_PYTHONPATH = /home/m3/anaconda2/lib/python2.7"

**Comment by lperron** [comment]
On linux, you need to download the ortools_examples-<linuxdistro>*

from 

https://github.com/google/or-tools/releases/tag/v6.3

for instance: https://github.com/google/or-tools/releases/download/v6.3/or-tools_python_examples-ubuntu-16.04_v6.3.4431.tar.gz

**Comment by maxisawesome** [comment]
Seems to have installed correctly. Thanks for the help and the fix!

**Comment by lperron** [comment]
Good. 

Closing the issue.

**Comment by hunt82** [comment]
Im having this problem trying to run the VRP example 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-57-6e92db605fbe> in <module>()
     11  return data
     12 if __name__ == '__main__':
---> 13  main()

<ipython-input-56-2dbd994070f8> in main()
     10   if num_locations > 0:
     11     routing = pywrapcp.RoutingModel(num_locations, num_vehicles, depot)
---> 12     search_parameters = pywrapcp.DefaultRoutingSearchParameters()
     13      # Callback to the distance function.
     14     dist_between_locations = CreateDistanceCallback(locations)

AttributeError: module 'ortools.constraint_solver.pywrapcp' has no attribute 'DefaultRoutingSearchParameters'

please any help

**Comment by Mizux** [comment]
Hi,

Could you open a new issue concerning the DefaultRoutingSearchParameters() missing than reusing this closed issue ?

Thanks !
