### ISSUE TITLE
How can subtract a Linear Expression from another Linear Expression

### ISSUE THREAD

**Issue by pardeep632** [google/or-tools#3860]
**What version of OR-Tools and what language are you using?**
Version: v9.6
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT
**What operating system (Linux, Windows, ...) and version?**
Mac 12.6.4
**What did you do?**
I Created two Linear Expression say LE1, LE2. I have an equation of the form of LE1-LE2.
So basically i want to subtract LE2 from LE1. There is a sum function in CPModel to create sum of Linear Expressions. I want to use that , But how do i create the expression -LE2 from LE2. 

**What did you expect to see**
I want to create negative of Linear expression
**What did you see instead?**
I do not see any way to create a Negative linear expression from a Linear Expression.
Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
No

**Comment by lperron** [comment]
LinearExprBuilder().add(l1).addTerm(l2, -1).build()

**Comment by pardeep632** [comment]
LinearExpr.newBuilder().add(expression1).addTerm(expression2, -1).build()
this worked for me . thanks @lperron
