### ISSUE TITLE
Solver crash when adding a new Constraints (Check failed: StringToProtobuf(serialized_model, model_proto) )

### ISSUE THREAD

**Issue by naziarmisto** [google/or-tools#3861]
**What version of OR-Tools and what language are you using?**
Version: main/v9.6/v9.5 etc.
9.5
Language: C++/Java/Python/C#
Python
**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows

**What did you do?**

 x1 = {}
 for j in list1:
      for i in list2:
           x1[i, j] = model.NewBoolVar(f'x1[{i},{j}]')      
 

for j in list1:
      model.Add(x1[i, j] for i in list2)
             

**What did you expect to see**
Solution

**What did you see instead?**
Check failed: StringToProtobuf(serialized_model, model_proto) 
Make sure you include information that can help us debug (full error message, model Proto).
Check failed: StringToProtobuf(serialized_model, model_proto) 
*** Check failure stack trace: ***
    @   00007FFF0395F649  (unknown)
    @   00007FFF0357F1AF  (unknown)
    @   00007FFF0358A991  (unknown)
    @   00007FFF0357C303  (unknown)
    @   00007FFF1446F43C  (unknown)
    @   00007FFF1443F128  (unknown)
    @   00007FFF144408D4  (unknown)
    @   00007FFF144BBBD3  (unknown)
    @   00007FFF144BB453  (unknown)
    @   00007FFF144DF83E  (unknown)
    @   00007FFF144DF7BA  (unknown)
    @   00007FFF145D4666  (unknown)
    @   00007FFF1452AC89  (unknown)
    @   00007FFF14561A18  (unknown)
    @   00007FFF1456165B  (unknown)
    @   00007FFF14561517  (unknown)
    @   00007FFF144F442C  (unknown)
    @   00007FFF144F42BD  (unknown)
    @   00007FFF1447E76D  (unknown)
    @   00007FF7817C1230  (unknown)
    @   00007FFF6EE87614  (unknown)
    @   00007FFF70B626B1  (unknown)
**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
please attach a working code, not some pseudo-code

**Comment by naziarmisto** [comment]
The both list are big List1=3500 elements, List2 =8000 elements and all elements in the both lists are string. 
ex: list1=['a','b','c'],  list2=['e','f','g']
model.AddAtMostOne should produce the error.

**Comment by lperron** [comment]
Most likely you are hitting the 2GB limit when crossing from python to c++.
These are 28M variables, so you have 71 bytes to store the variable info,
its name, and the ct they appear in.
This is a limitation of protobufs. I cannot do anything about it currently.

If you use C++ directly, there are no such limitations.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by naziarmisto** [comment]
I just use Python. no c++,

**Comment by Mizux** [comment]
What Laurent means, is OR-Tools is a c++ library with python wrapper so when you "use" python actually data are sent to the C++ implementation and this "transfert" between both is limited to 2 Go (protobuf message size limitation IIRC).

i.e. ortools is a native python package.
ps: You can found here a minimal example explaining the tech/language stack https://github.com/Mizux/python-native/tree/main
