### ISSUE TITLE
MPSolver callback misordered

### ISSUE THREAD

**Issue by 837951602** [google/or-tools#3872]
**What version of OR-Tools and what language are you using?**
Version: 9.6.2534
Language: C++
**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
SCIP
**What operating system (Linux, Windows, ...) and version?**
Windows 10
**What did you do?**
(https://stackoverflow.com/questions/76784439/mpsolver-callback-misordered)

I'm not sure whose fault, ortools or SCIP

**Comment by 837951602** [comment]
Tested on raw SCIP and order is correct so it's like or's fault

**Comment by lperron** [comment]
So from what I understand, the order from scip is valid for Boolean variables, and scrambled for integer variables.

**Comment by Mizux** [comment]
oops miss this one, yes MPCallback are broken since internal variables are "sorted", this issue is fixed with Math_opt which take care of the mapping....

**Comment by Mizux** [comment]
Closing this known bug since it won't be possible to fix it without rewriting a large part of linear solver... which is the only
purpose of math_opt.
i.e. If facing this problem, please migrate to math_opt.
