### ISSUE TITLE
Unable to plot the results of "cvrptw.py" using matplotlib (a file from or-tools/examples/python)

### ISSUE THREAD

**Issue by daruni** [google/or-tools#389]
Hi, all. I want to plot the results of this single-depot vrp, which are the routes of all vehicles starting from the same depot and returning to the same depot, where 'depot=0' as written in the code. 

Therefore, does anyone here know how to deal with this problem? Your help is highly appreciated.
@lperron

**Comment by lperron** [comment]
See #1098
