### ISSUE TITLE
Facing "MODEL_INVALID" error on trying to update the hints of variables for a multistage solve

### ISSUE THREAD

**Issue by arnabadas** [google/or-tools#3890]
**What version of OR-Tools and what language are you using?**
Version: v9.6.2873
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
The problem requires CP-SAT to solve for 3 objectives one after the other.
1. Solve for the 1st objective function
2. After the 1st solve, add hint to a variable (in my case it was a boolvar) and then again solve for the 2nd objective function.
3. After the 2nd solve, add hint to the same variable (but now a different value) and then again solve for the 3rd objective function.

**What did you expect to see**
Hint should have been updated when I am adding the hint to the same variable for the second time.

**What did you see instead?**
"MODEL_INVALID" error while solving for the 3rd stage.

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
NA

**Comment by lperron** [comment]
Please provide the full error message: 

Either parameter log_search_progress: true

Or call Validate() on the model.

Most likely, you have entered duplicate hints for the same variable,  which is forbidden.

You can clear hints by calling ClearHints() on the model.

**Comment by arnabadas** [comment]
@lperron This function is not present in this page: [CP-SAT Python reference page](https://developers.google.com/optimization/reference/python/sat/python/cp_model). Is this page outdated?

**Comment by lperron** [comment]
yes. We are updating it.

In the meantime, this one is up todate

https://or-tools.github.io/docs/python/ortools/sat/python/cp_model.html
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
