### ISSUE TITLE
Throw an error on unsupported OnlyEnforceIf()

### ISSUE THREAD

**Issue by dimbleby** [google/or-tools#3902]
**What language and solver does this apply to?**

CP-SAT.  I'm writing in Python but I suppose this holds in other languages too.

**Describe the problem you are trying to solve.**

I'm trying to write `model.AddAllowedAssignments(...).OnlyEnforceIf(...)`

**Describe the solution you'd like**

Well ideally I'd like that to work!  But I've found a couple of threads saying that it doesn't, and hinting that it's never going to happen.  So what I'm instead asking for is that at least some sort of error be thrown if we write `OnlyEnforceIf()` on a constraint where that will be ineffective.

It's extremely easy at the moment to write code that looks fine and doesn't error, but also simply doesn't do what it looks as though it ought to do.  I've just lost a chunk of time to this myself...

**Describe alternatives you've considered**

Obviously having `OnlyEnforceIf()` be available for more constraints - with my particular interest being `AddAllowedAssignments()` - would be great...

**Additional context**

- Here's a 2018 thread saying that this is not supported: https://groups.google.com/g/or-tools-discuss/c/FFY15023bhU/m/AcumgQarCAAJ
- Here's a 2021 feature request asking for support: https://github.com/google/or-tools/issues/2752.  
  - So far as I can tell converted to a discusson without support being added.  
  - Not sure why it didn't just stay as an open feature request: I guess that this was an implicit rejection (which is why I've not tried the exact same thing again)

**Comment by lperron** [comment]
Sorry about the lost time. 
But this will not happen. I do not believe this should throw an error. 

I understand this is a feature request and we are thinking about it. But raising an exception is not the solution.

Thanks
