### ISSUE TITLE
IntVar() crashing [Python] 

### ISSUE THREAD

**Issue by Hanamuke** [google/or-tools#391]
The IntVar method, MakeIntVar in the C++ version, seems to crash when fed an empty domain.
Minimal code : 
`from ortools.constraint_solver import pywrapcp `
`solver=pywrapcp.Solver('minimalCode')`
`tmp=solver.IntVar([])`

**Comment by lperron** [comment]
Indeed. I agree the crash is not nice, but the solver does not support it
anyway.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-05-23 15:53 GMT+02:00 Hanamuke <notifications@github.com>:
