### ISSUE TITLE
CP-SAT 9.7.2996 via Python crashes during solve

### ISSUE THREAD

**Issue by vilumaa** [google/or-tools#3917]
**What version of OR-Tools and what language are you using?**
OR-Tools 9.7.2996 
Python 3.10.11

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT 

**What operating system (Linux, Windows, ...) and version?**
Windows 11

**What did you do?**
Solve the attached model
[solver_crashes.pb.txt](https://github.com/google/or-tools/files/12575744/solver_crashes.pb.txt)

```
print("Just before .Solve()")
solver.Solve(model)
print("Just after .Solve()")
```
outputs
```
\freezer> poetry run py run.py
Just before .Solve()
\freezer>
```

**What did you expect to see**
.Solve() finished, used to work with OR-Tools 9.5

**Comment by lperron** [comment]
Thanks. We will debug it.
