### ISSUE TITLE
v6.0.4217 [ERROR] ortools module that doesn't have a versión

### ISSUE THREAD

**Issue by diegoalberione** [google/or-tools#392]
Hello, I am trying to install OrTools as the documentation says and I get the following error:

python check_python_deps.py --log=ERROR
[ERROR] You are using a ortools module that doesn't have a __version__ attribute : /root/.local/lib/python2.7/site-packages/ortools-6.0.4217-py2.7-linux-x86_64.egg/
ortools/__init__.pyc"
Run "/usr/bin/python setup.py install --user" to upgrade.
If the problem persists, remove the site-package that contains "/root/.local/lib/python2.7/site-packages/ortools-6.0.4217-py2.7-linux-x86_64.egg/ortools/__init__.py
c". You can do so either manually or by using pip.

I have tried with python version 2.7, 3.5 and 3.6. I use Ubuntu 14.04

I appreciate any help !!

**Comment by lperron** [comment]
Hi, 

I pushed version 6.3 with support for ubuntu 14.04, 16.04, and 17.04.
Can you test it?

Thanks

**Comment by lperron** [comment]
I checked it is correct in the latest version (v6.4).
Closing the issue.

Thanks
