### ISSUE TITLE
 uesd  `AddAtMostOne(literals)`  and `Add(sum(literals) <= 1)`  have different results

### ISSUE THREAD

**Issue by xubzhlin** [google/or-tools#3923]
**What version of OR-Tools and what language are you using?**
Version: v9.7.
Language: Python(3.8.8)

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10 

**What did you do?**
1. I have some Boolean constraints as `literasls`
2. Used `AddAtMostOne(literals).OnlyEnforceIf()` did not return a solution
3. But used `Add(sum(literals) <= 1).OnlyEnforceIf()` return a solution
4. Notes: Adds `AtMostOne(literals)`: `Sum(literals) <= 1`. Why have different results

**The example code**

1. Used `AddAtMostOne(literals).OnlyEnforceIf()` did not return a solution

```
    model = cp_model.CpModel()
    x1 = model.NewBoolVar("")
    x2 = model.NewBoolVar("")
    x3 = model.NewIntVar(0, 8, "")
    span = [x1, x2]
    lte = model.NewBoolVar("")
    model.AddAtMostOne(span).OnlyEnforceIf(lte)
    model.AddBoolAnd(lte)
    model.Add(x1 * 2 + x2 * 3 + x3 == 9)
    solver = cp_model.CpSolver()
    solution_printer = SolutionPrinter(10)
    status = solver.Solve(model, solution_printer)
    if status == cp_model.OPTIMAL or status == cp_model.FEASIBLE:
        print(f"x1={int(solver.Value(x1))}  x2={int(solver.Value(x2))}  x3={int(solver.Value(x3))}")
```

2. Used `Add(sum(literals) <= 1).OnlyEnforceIf()` return a solution
```
    model = cp_model.CpModel()
    x1 = model.NewBoolVar("")
    x2 = model.NewBoolVar("")
    x3 = model.NewIntVar(0, 8, "")
    span = [x1, x2]
    lte = model.NewBoolVar("")
    model.Add(sum(literals) <= 1).OnlyEnforceIf(lte)
    model.AddBoolAnd(lte)
    model.Add(x1 * 2 + x2 * 3 + x3 == 9)
    solver = cp_model.CpSolver()
    solution_printer = SolutionPrinter(10)
    status = solver.Solve(model, solution_printer)
    if status == cp_model.OPTIMAL or status == cp_model.FEASIBLE:
        print(f"x1={int(solver.Value(x1))}  x2={int(solver.Value(x2))}  x3={int(solver.Value(x3))}")
```

**Comment by lperron** [comment]
At most one currently does not accept only enforce if. The solver returns invalid model
