### ISSUE TITLE
CP-sat getting (much) slower on my program with new versions ?

### ISSUE THREAD

**Issue by cedounet** [google/or-tools#3925]
**What version of OR-Tools and what language are you using?**
Version:  9.5.2237 and 9.7.2996
Language: python 3.11

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Linux 6.4.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.4.13-1 (2023-08-31) x86_64 GNU/Linux

**What did you do?**
Install version 9.5 of ortools in virtual env, run the code.  another venv with latest version, run same code with same data.  Compare results (same) compare Walltime.  Running with 16 workers. 

``
Optimising F
Using 16 workers

Solution is: OPTIMAL
NumConflicts: 16857
NumBranches: 294999
WallTime: 10.900124584
``

vs 
``
Optimising F
Using 16 workers

Solution is: OPTIMAL
NumConflicts: 2
NumBranches: 12546
WallTime: 149.30623909000002
``
 Full logs here 
[new.txt](https://github.com/google/or-tools/files/12659201/new.txt)
[old.txt](https://github.com/google/or-tools/files/12659202/old.txt)
Same code for F, D, N, P etc... different input data.  Same code on both old and new just changed the ortools version when creating virtual environment.

**What did you expect to see**
Same-ish time, obviously there is randomness so it will vary for each run but not 10x slower.

There are heuristics so things can go up and down of course... but maybe that level of slowing down was not expected?

*Make sure you include information that can help us debug (full error message, model Proto).

[F_pb.txt](https://github.com/google/or-tools/files/12659373/F_pb.txt)
renamed but that is a txt file (same for both... I checked)

Thanks!

C/

**Comment by lperron** [comment]
Indeed. Thanks.

**Comment by cedounet** [comment]
Sorry @lperron.. what do you mean by indeed? It is expected to be slower?  Wa it already known, i could not find a report… 

I just would like to understand what is happening and ideally what I could do to regain original speed.

thanks again,

C/

**Comment by lperron** [comment]
Each time we do a release, we evaluate the gains on a set of benchmarks,
and we cut the features  that globally improve the performance on these
benchmarks.

We aim at global improvements, but there could be outliers that suffers.
Yours is one example.

So we will add this in our suite of problems, and try to regain performance
for the next release.

**Comment by cedounet** [comment]
Perfect thanks... brevity sometimes is confusing.

**Comment by fdid-git** [comment]
I investigated. You problem is closed by the "core based search", and indeed we now spend more effort on each core which explain the slow-down you see. I will add a parameter "core_minimization_level" with a default of 2, if you set that to level 1, you will recover original performance on that particular problem [Note that this is not pushed yet].

Getting back the original perf with the default parameters might or might not happen, but in any case it will not happen soon...
