### ISSUE TITLE
Undocumented syntax / operation of AddMultiplicationEquality()

### ISSUE THREAD

**Issue by gilirosenberg12** [google/or-tools#3931]
**What version of OR-Tools and what language are you using?**
Version: 9.7.2996
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
MacOS, 13.5.2

**What did you do?**

I executed this code:
```python
from ortools.sat.python import cp_model
model = cp_model.CpModel()
x = model.NewIntVar(0, 100, "x")
y = model.NewIntVar(0, 100, "y")
xy = model.NewIntVar(0, 10000, "xy")
model.AddMultiplicationEquality(xy, x, y)
model.Add(xy==20)
solver = cp_model.CpSolver()
solver.Solve(model)
print("x =", solver.Value(x))
print("y =", solver.Value(y))
print("xy =", solver.Value(xy))
```
and it ran through and gave me this:
```
x = 1
y = 20
xy = 20
```

**What did you expect to see**
An error, since the [documentation](https://developers.google.com/optimization/reference/python/sat/python/cp_model#addmultiplicationequality) gives the signature of `AddMultiplicationEquality()` as:
`def AddMultiplicationEquality(self, target, variables)`. But in the above I'm doing `AddMultiplicationEquality(target, variable1, variable2)`. 

![Screenshot 2023-09-27 at 9 46 11 PM](https://github.com/google/or-tools/assets/108100824/bad8a46d-7324-45c1-8ddc-ea395265ea0e)

**What did you see instead?**
It seems to work the way I'd intuitively expected it to work, but I can't be sure and it's not documented. If this is expected behavior, I think it should be documented. If it's not expected, I think it should raise an error.

**Comment by Mizux** [comment]
Please prefer to use the up to date with the last release ref doc here: https://or-tools.github.io/docs

=> https://or-tools.github.io/docs/pdoc/ortools/sat/python/cp_model.html#CpModel.AddMultiplicationEquality

**Comment by gilirosenberg12** [comment]
Thank you - so, the new signature is `AddMultiplicationEquality(target, *expressions)`? That seems like a problematic breaking change...? Or is the previous usage still supported? I tried, and indeed, as far as I can tell, both seem to work. Should the former be preferred then, going forward? And why aren't the docs updated in the link I used?

**Comment by gilirosenberg12** [comment]
Thanks, @lperron - would it make sense to update the documentation to cover this usage as well?

**Comment by lperron** [comment]
Yes, but we need to support more than 2 terms before that.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le jeu. 28 sept. 2023 à 16:16, Gili Rosenberg ***@***.***> a
écrit :
