### ISSUE TITLE
Support for Generalized Network Flow model

### ISSUE THREAD

**Issue by jianzhe-luo** [google/or-tools#394]
Hi,

I find this tool super useful and wonder if it currently or will support Generalized Network Flow model? Specifically, I am trying to build a Network Flow model where the flow along each arc can be adjusted by a scaler, e.g., along arc A->C, every unit flow from node A becomes two units when it reaches node C. I know this can be formulated by MIP but my understanding is that Network Flow model is more efficient.

Thanks!

**Comment by drhops** [comment]
Hi @jianzhe-luo,

It's my understanding that (generally speaking, not just for or-tools) it's very difficult to find implementations of algorithms specifically for GNF (e.g. generalized network simplex) and that it's commonly formulated as a LP (mixed-integer not necessarily required).  Please let me know if you find otherwise though!

**Comment by jianzhe-luo** [comment]
Hi @drhops ,

Thanks for your feedback! I did my homework and so far found no out-of-the-box solver that can handle GNF. Can you elaborate why this can be formulated by LP? I guess the resulting coefficient matrix in the LP formulation is totally unimodular?

**Comment by drhops** [comment]
Do you require integer solutions?  Sorry, I was assuming continuous solutions in my comment and I don't know the integral properties of GNF.  There's a nice treatment on the generalized flows topic though in Network Flows by Ahuja, Ch. 15.

**Comment by jianzhe-luo** [comment]
Yes I want integer solutions but I am not sure if the LP relaxation guarantees integrality. I will take a look at the reference you mentioned. Thanks!
