### ISSUE TITLE
Dual values not available for LP models

### ISSUE THREAD

**Issue by SanPen** [google/or-tools#3940]
Version: 9.7.2996 (lattest as of the time of writing)
Language: Python
Solver: SCIP (or whatever the default is)
OS: Linux (Ubuntu 22.04)

**What did you do?**
In the software I'm developing (GridCal) there is a module for optimizing electrical grids. The [model preparation is quite complex](https://github.com/SanPen/GridCal/blob/devel/src/GridCalEngine/Simulations/OPF/linear_opf_ts.py), but I attach the LP and MPS exports which should suffice to reproduce the issue: [Lynn 5 Bus pv (OPF).lp](https://github.com/google/or-tools/files/12846459/Lynn.5.Bus.pv.OPF.lp.txt) and [Lynn 5 Bus pv (OPF).mps](https://github.com/google/or-tools/files/12846557/Lynn.5.Bus.pv.OPF.mps.txt)

```python
import os
from ortools.linear_solver.python import model_builder

path = os.path.dirname(__file__)
mps_path = "Lynn 5 Bus pv (OPF).mps"
model = model_builder.ModelBuilder()
model.import_from_mps_file(mps_path)
solver = model_builder.ModelSolver('SCIP')
solver.solve(model)

print(model.name)
print(solver.objective_value)
for cts in model.get_linear_constraints():
    print(cts.name + ' ->', solver.dual_value(cts))
```

**What did you expect to see**
The model does not have any integer variable, so I'd expect to be able to access the dual values of the constraints labeled as `kirchoff`. Instead I`m getting: 

```
Dual value only available for continuous problems
```

The provided code does not print the warning, but all the dual values are zero, which is unexpected.

Any guidance here is appreciated.

**Comment by lperron** [comment]
Do not use SCIP which is a MIP solver, even if it can solve LP models.
