### ISSUE TITLE
Non-deterministic Behavior for CP-SAT with num_workers=1

### ISSUE THREAD

**Issue by tony-nowatzki** [google/or-tools#3943]
Version: CP-SAT solver v9.7.2996
Language: C++
OS: Ubuntu 22.04.2 LTS

I have a CP-SAT model that sometimes produces different optimal solutions with each run, even with num_workers=1 and setting the random seed.  

Here is the model proto: 
[model-non-det.pb.txt](https://github.com/google/or-tools/files/12854319/model-non-det.pb.txt)

I'm also including the logs of two runs that produce different solutions in case its helpful:
[log1.txt](https://github.com/google/or-tools/files/12854369/log1.txt)
[log2.txt](https://github.com/google/or-tools/files/12854371/log2.txt)

**Comment by lperron** [comment]
We will assumes these assumptions true while solving, but if the model is infeasible, you will not get a useful 'sufficient_assumptions_for_infeasibility' field in the response, it will include all assumptions.

Can you try without the objective? Objective and assumptions in the same model is not supported.

**Comment by lperron** [comment]
This being said, I ran it 30 times on the main branch, and it always return the same solution.

**Comment by tony-nowatzki** [comment]
I will open a new issue for this, thanks again!
