### ISSUE TITLE
pyi file for `ortools.sat.python.swig_helper`

### ISSUE THREAD

**Issue by Dr-Irv** [google/or-tools#3944]
**What language and solver does this apply to?**
python, CP-SAT

**Describe the problem you are trying to solve.**

Would like types for `ortools.sat.python.swig_helper`

**Describe the solution you'd like**

A PYI file that corresponds to the classes and methods in the file `swig_helper.cp310-win_amd64.pyd`

**Describe alternatives you've considered**

None

**Additional context**

When creating my own subclass of `CpSolverSolutionCallback`, calling the method `ObjectiveValue()` shows that it has no type, and it should have a type.

**Comment by lperron** [comment]
I am not sure this is possible. This is created by pybind11.

**Comment by Dr-Irv** [comment]
You can just add the `.pyi` file by hand to correspond to what is in https://github.com/google/or-tools/blob/stable/ortools/sat/python/swig_helper.cc .  For example,
```python
class SolutionCallback:
    def BestObjectiveBound(self) -> float: ...
    def DeterministicTime(self) -> float: ...
#  etc
```

**Comment by Dr-Irv** [comment]
> OK, stubgen does a decent job

Looks like it.  Looking forward to a new release with that `pyi` file.  :-)

**Comment by stradivari96** [comment]
Related: https://github.com/google/or-tools/discussions/3186#discussioncomment-3418732

**Comment by Dr-Irv** [comment]
Also, would like PYI for `sorted_interval_list.Domain` as well.

**Comment by Mizux** [comment]
I'm currently thinking to work on a CMake `PYTHON_GENERATE_STUBGEN` option, should work on it next week...

**Comment by Dr-Irv** [comment]
Any sense as to when you will create a release that includes the auto-generated PYI files?

**Comment by lperron** [comment]
Friday or next week.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mer. 25 oct. 2023 à 15:41, Irv Lustig ***@***.***> a
écrit :
