### ISSUE TITLE
min_cost_flow.flow() segfaults on supply mismatch

### ISSUE THREAD

**Issue by skosch** [google/or-tools#3947]
**What version of OR-Tools and what language are you using?**
Version: 9.7.2996
Language: Python
OS: Linux

**Solver**: MinCostFlow

**What did you do?**
```python
import ortools.graph.python.min_cost_flow

def get_flow():
    flow = ortools.graph.python.min_cost_flow.SimpleMinCostFlow()
    flow.add_arc_with_capacity_and_unit_cost(0, 1, 1, 0)
    flow.set_node_supply(0, 2)
    flow.set_node_supply(1, -1)
    return flow

# This works
flow = get_flow()
flow.solve_max_flow_with_min_cost()
print(flow.optimal_cost())
print(flow.flow(0))

# This crashes
flow = get_flow()
flow.solve()  # <--- works fine, suprisingly
print(flow.optimal_cost())  # <--- also works fine
print(flow.flow(0))  # <--- SEGFAULT!
```

Currently, if supply and demand don't match, the `solve()` function runs but the `flow(arc_index)` function crashes the whole script.

It would be a nice quality of life improvement if instead, the `solve()` function gently failed with an error informing me that
* between all sink nodes reachable from the source nodes, the total supply doesn't equal the total demand, and
* a function `solve_max_flow_with_min_cost` is available as an alternative if I want to solve it anyway.

Thank you!

**Comment by lperron** [comment]
From the doc (not sure if it applies though):


  // Solves the problem, and returns the problem status. This function
  // requires that the sum of all node supply minus node demand is zero and
  // that the graph has enough capacity to send all supplies and serve all
  // demands. Otherwise, it will return INFEASIBLE.
  Status Solve() {
    return SolveWithPossibleAdjustment(SupplyAdjustment::DONT_ADJUST);
  }

  // Same as Solve(), but does not have the restriction that the supply
  // must match the demand or that the graph has enough capacity to serve
  // all the demand or use all the supply. This will compute a maximum-flow
  // with minimum cost. The value of the maximum-flow will be given by
  // MaximumFlow().
  Status SolveMaxFlowWithMinCost() {
    return SolveWithPossibleAdjustment(SupplyAdjustment::ADJUST);
  }

**Comment by skosch** [comment]
Aha, I see I missed the explicit status check. Thank you, Laurent. Still, it would be nice if the call to `flow()` didn't crash the whole script, and instead returned 0 if the status is infeasible. Or was this an intentional choice?

**Comment by lperron** [comment]
Not sure. But we are not allowed to use exceptions in C++. So a bit tricky
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le jeu. 12 oct. 2023 à 10:05, Sebastian Kosch ***@***.***> a
écrit :

**Comment by Mizux** [comment]
`Solve()` return a `SimpleMinCostFlow.Status` you can check for OPTIMAL etc....

tips: `print(type(out))` and `print(dir(out))`

```diff
--- orig.py	2024-02-26 14:46:09.465691680 +0100
+++ new.py	2024-02-26 14:44:54.866042975 +0100
@@ -1,7 +1,7 @@
-import ortools.graph.python.min_cost_flow
+import ortools.graph.python.min_cost_flow as mcf
 
 def get_flow():
-    flow = ortools.graph.python.min_cost_flow.SimpleMinCostFlow()
+    flow = mcf.SimpleMinCostFlow()
     flow.add_arc_with_capacity_and_unit_cost(0, 1, 1, 0)
     flow.set_node_supply(0, 2)
     flow.set_node_supply(1, -1)
@@ -9,12 +9,18 @@
 
 # This works
 flow = get_flow()
-flow.solve_max_flow_with_min_cost()
-print(flow.optimal_cost())
-print(flow.flow(0))
+out = flow.solve_max_flow_with_min_cost()
+if out == flow.Status.OPTIMAL:
+  print(flow.optimal_cost())
+  print(flow.flow(0))
+else:
+    print(f"error: {out}")
 
 # This crashes
 flow = get_flow()
-flow.solve()  # <--- works fine, suprisingly
-print(flow.optimal_cost())  # <--- also works fine
-print(flow.flow(0))  # <--- SEGFAULT!
+out = flow.solve()  # <--- works fine, suprisingly
+if out == flow.Status.OPTIMAL:
+    print(flow.optimal_cost())  # <--- also works fine
+    print(flow.flow(0))  # <--- SEGFAULT!
+else:
+    print(f"error: {out}")
```

out:
```sh
$ build/python/venv/bin/python3 new.py
0
1
error: Status.UNBALANCED
```
