### ISSUE TITLE
 Non-determinism for CP-SAT with num_workers=1

### ISSUE THREAD

**Issue by tony-nowatzki** [google/or-tools#3948]
Version: CP-SAT solver v9.7.3120
Language: C++
OS: Ubuntu 22.04.2 LTS

I have a CP-SAT model that sometimes produces different optimal solutions with each run, even with num_workers=1 and setting the random seed.  (unlike #3943, no assumptions are used, and I am using the latest code from the main branch).

model: [model-non-det.pb.txt](https://github.com/google/or-tools/files/12874507/model-non-det.pb.txt)

Two logs showing different optimal solution fingerprints, but same presolve fingerprint:
log1: [log1.txt](https://github.com/google/or-tools/files/12874510/log1.txt)
log2: [log2.txt](https://github.com/google/or-tools/files/12874512/log2.txt)

**Comment by lperron** [comment]
Reproduced.

Thanks

**Comment by tony-nowatzki** [comment]
Great! Thanks again for looking at this.
