### ISSUE TITLE
In `prize_collecting_vrp.py` vehicle index should be dynamic for printing

### ISSUE THREAD

**Issue by vecxoz** [google/or-tools#3949]
Hello,

Thank you very much for the great set of examples. They are very useful.
I found a tiny issue. Inside the `print_solution` function index of the vehicle is hard coded as `0`, but it should be dynamic i.e. `v`.

https://github.com/google/or-tools/blob/1d696f9108a0ebfd99feb73b9211e2f5a6b0812b/examples/python/prize_collecting_vrp.py#L95

**Comment by lperron** [comment]
Thanks
