### ISSUE TITLE
Routing, C# lib : SetSpanUpperBoundForVehicle() behaviour.

### ISSUE THREAD

**Issue by sergn-n** [google/or-tools#395]
I've noticed under circumstances SetSpanUpperBoundForVehicle() requires disjunctions to be set up with a penalty.  Kind of
```
for (int order = 0; order < number_of_orders; ++order) {
   int[] orders = { order };
   model.AddDisjunction(orders, highPenalty);
}
```
In my sample RTW problem (see [gist](https://gist.github.com/sergn-n/fe65b24a735a20cd4af6a06101d5b895) ) when no disjunction is set up the solver founds no solution, when disjunctions are set up with a low penalty some orders are dropped. Finally when disjunctions are set up with a high penalty solution includes all orders. The question is why  disjunctions are required while a solution including all orders does exist ?

**Comment by sergn-n** [comment]
Another workaround: use SolveFromAssignmentWithParameters()  with a blank Assignment.
```
    var ass = new Assignment(model.solver());
    Assignment solution = model.SolveFromAssignmentWithParameters(ass, search_parameters);
```

**Comment by lperron** [comment]
code has changed a lot. Disjunction semantics too.
Closing the issue.
