### ISSUE TITLE
MiniZinc free-search, all-solutions and satisfy result in crash

### ISSUE THREAD

**Issue by CervEdin** [google/or-tools#3951]
**What version of OR-Tools and what language are you using?**
Version: OR-Tools 9.1.9490 
Language: MiniZinc 2.7.6

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

Should be CP-SAT?

**What operating system (Linux, Windows, ...) and version?**

Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**What did you do?**

Something along the lines

```sh
minizinc \
  --solver or-tools \
  --free-search \
  --all-solutions \
  model.mzn
```

where the model specifies `solve satisfy`, to solve for satisfaction.

**What did you expect to see**

Not sure. Maybe calling like this doesn't make sense, I came across this by mistake.

**What did you see instead?**

```
F1012 17:16:45.281053 11759 cp_model_solver.cc:2622] Check failed: !parameters.enumerate_all_solutions() Enumerating all solutions in parallel is not supported.
*** Check failure stack trace: ***
```

**Anything else we should know about your project / environment**

Happy to provide an actual Minimal reproducible problem, try newer versions of Or-Tools etc.
Just wanted to post the issue first, in case this isn't actually a bug

**Comment by lperron** [comment]
I tried it. It did not crash on 9.7, but returned model_invalid.
This is fixed now.
