### ISSUE TITLE
Mac OS broken build (std::min unable to implic cast)

### ISSUE THREAD

**Issue by sgatto** [google/or-tools#3953]
I'm preparing a PR to integrate new developments on the Xpress interface (by RTE).
I am working by using your main branch, the MacOS CI actions are broken.
It looks `size_t` (returned by `size()`) is different from `uint64_t` (returned by model.VehicleVar(node)->Size())  and the `std::min` function is not found

https://github.com/google/or-tools/blob/c00c6a65dd0b696295e71bf2645b88e3c61c1907/ortools/constraint_solver/routing_search.cc#L586

A explicit cast (redundant for Windows and Linux) seems necessary.

**Comment by Mizux** [comment]
yup, saw it too yesterday, need to fix it ASAP

I fear it is related to macos clang uint64_t def
see:

**Comment by sgatto** [comment]
Yep, exactly.
I wonder, how do plan to fix it? Simply explicitly casting `static_cast<uint64_t>(vehicles.size())`?
I don't think you need a PR for this,
