### ISSUE TITLE
unable to install ortools on python 3.12

### ISSUE THREAD

**Issue by turbopape** [google/or-tools#3955]
**What version of OR-Tools and what language are you using?**

Version: v9.7
Language: python 3.12

**Which solver are you using

CP-SAT

**What operating system (Linux, Windows, ...) and version?**

mac osx 14.0 

**What did you do?**

1. install python 3.12 toolchain
2. created a pytohn3.12 virtualenv
3. ACtivate it : source venv/bin/activate
4. install ortools: python3.12 -m pip install --upgrade ortools

**What did you expect to see**

ortools installed

**What did you see instead?**

ERROR: Could not find a version that satisfies the requirement ortools (from versions: none)
ERROR: No matching distribution found for ortools

**Anything else we should know about your project / environment**
It used to work with Python 3.11

**Comment by lperron** [comment]
3.12 was released after our last release. It will be available for 9.8 (in the next 2 weeks).

**Comment by turbopape** [comment]
Well noted, reverting to 3.11, nice job guys, thanks :)

**Comment by haseeb5555** [comment]
I am unable to install ortools in a virtual environment, but I can install them outside of it. How can I fix this? My Python version is 3.13.

**Comment by lperron** [comment]
1) please no necro-posting.
2) 3.13 is not yet supported.
