### ISSUE TITLE
PDLP fails to solve a problem except if constraints are defined as bounded variables

### ISSUE THREAD

**Issue by RIVOIRA** [google/or-tools#3956]
**What version of OR-Tools and what language are you using?**
Version: main
Language: C++/Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
PDLP

**What operating system (Linux, Windows, ...) and version?**
Microsoft Windows 10 Enterprise

**What did you do?**
I have created the following Problem:
Minimize  ObjectiveGradient[0] * X + ObjectiveGradient[1] *Y + ObjectiveGradient[2] * Z
subject to 
{
Linear bounds
{
> X >= -Bounds[0]
> Y >= -Bounds[1]
> Z >= -Bounds[2]
}
Norm Bounds
{
> NormGradient[0] * |X| + NormGradient[1] * |Y| + NormGradient[2] * |Z| <= NormUpperBound
}
}
where
|x| is the absolute value of x
ObjectiveGradient{1000000., -150000., 500000.};
Bounds{75.0, 25.0, 0.0};
NormGradient{0.0004, 0.0003, 0.2};
NormUpperBound{1.0};
I have turned that non linear problem into a linear one introducing non negative variables V+, V- to handle the absolute value using V = V+ - V- and |V| = V+ +  V-
Depending on whether I model the linear bounds (X > -Bounds[0], etc.) as a bound on the variables or as a constraints, I get either the expected solution or a failure. 
Please see attached some C++ code benchmarking PDLP with GLOP in the case where bounds are set as constraints or as variables and for the case where the objective gradient is positive i.e. ObjectiveGradient{1000000., -150000., 500000.};
The case where the objective gradient is made positive is interesting because it prevents LPDP from failing brutally  when constraints are used to set bounds on variables but the returned solutions are still very uncanny.

**What did you expect to see**
I would expect to find the exact same output, regardless of the particular encoding of the constraints on the model variables (written directly as bounded variables or as constraints on free variables). 
**What did you see instead?**
I see PDLP fails when the problem is described using free variables combined with constraints making them bounded, not when variables are directly defined as bounded variables.
Here the expected solutions is -5.6e+08 reached for x = -75, y = 3233.33, z = 0.-5.6e+08
![image](https://github.com/google/or-tools/assets/46496312/e17d115f-ff18-4ddb-b153-dc9263d966fb)

**C++ Code**
For whatever purpose it may serve, I have attached a text document enclosing some C++ code testing the same problem with differently modelling solved by both PDLP and GLOP (used as benchmark) 
[PDLPTesting.txt](https://github.com/google/or-tools/files/12929581/PDLPTesting.txt)

**Comment by mlubin** [comment]
> I would expect to find the exact same output, regardless of the particular encoding of the constraints on the model variables (written directly as bounded variables or as constraints on free variables).

This isn't an appropriate assumption for PDLP. PDLP is much more sensitive to the formulation of the problem and numerical ill conditioning than GLOP. You can try setting `presolve_options.use_glop = True` in `PrimalDualHybridGradientParams` to make PDLP behave a bit more like GLOP.

**Comment by RIVOIRA** [comment]
Thanks for you quick answer.
Are those presolve options documented somewhere?

**Comment by RIVOIRA** [comment]
And, yes, I agree that my sentence was poorly formulated. The bug is not that PDLP does not behave like GLOP. The bug is that it does not find the solution. GLOP finds it, CLP too, and even PDLP finds it too but for that we need to recast the constraints in terms of bounded variables. Two ways of stating the exact same problem, one leads to a failure and the other to a success. Somewhat worrying to me.

Could that presolving process be run at least by default so that constraints formally equivalent to bounds on variables be converted automatically?
Are there cases where such a conversion could do any harm?

Thanks in advance,
Regards

**Comment by mlubin** [comment]
All of PDLP's options are documented in `solvers.proto`: https://github.com/google/or-tools/blob/1d696f9108a0ebfd99feb73b9211e2f5a6b0812b/ortools/pdlp/solvers.proto#L224

Through the MPSolver interface you set this via `SetSolverSpecificParametersAsString`, e.g.,
`solver.SetSolverSpecificParametersAsString("presolve_options { use_glop: true }")` (I didn't test this snippet.)

> Could that presolving process be run at least by default so that constraints formally equivalent to bounds on variables be converted automatically?
Are there cases where such a conversion could do any harm?

Glop's presolve is single threaded and won't scale to the same size problems that PDLP is capable of handling. There are scenarios where the presolve would become a bottleneck in the solve.
