### ISSUE TITLE
Slow cover optimization

### ISSUE THREAD

**Issue by ozan-cb** [google/or-tools#3958]
**What version of OR-Tools and what language are you using?**
Version: Both v9.7 and main (commit: 01dd97f64e588621093a1e71bd32f9832ca06035)
Language: Language agnostic

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you do?**

Refer to the attached proto file for the `cp_model` details, along with the two logs provided.

**What did you expect to see**

This is an easy problem that can be solved with a single threaded solver (no_lp, max_lp, quick_restart, ...) in a few seconds.

**What did you see instead?**

When `interleave_search` is on, using 6 workers and a very low deterministic time limit, `core` takes close to two minutes to complete. See attached log, `baseline.log`.

If I profile the solver, it appears that `CoverOptimization` takes 99% of the process time. By setting `cover_optimization: false`, the solving time can be reduced to 18 seconds, as seen in `no_cover_opt.log`. 

Could `CoverOptimization` be made faster without entirely disabling it? I have several other instances where cover optimization provides to be highly beneficial, thus I am not inclined to disable it completely.

**Anything else we should know about your project / environment**

Model:
[cp_model.proto.txt](https://github.com/google/or-tools/files/13044404/cp_model.proto.txt)

Logs with and without cover optimization:
[baseline.log](https://github.com/google/or-tools/files/13044429/baseline.log)
[no_cover_opt.log](https://github.com/google/or-tools/files/13044432/no_cover_opt.log)

**Comment by lperron** [comment]
do you really need interleave search ?

**Comment by ozan-cb** [comment]
Unfortunately, yes.

**Comment by lperron** [comment]
the crux of the problem is that int_div and int_prod are counted in the deterministic time. So I believe the issue is more the core batch of solves runs for too long, than cover takes time.

**Comment by ozan-cb** [comment]
Doesn't `core` have the same `int_div` and `int_prod`s as the rest of the subsolvers though, why does that affect only that subsolver?

**Comment by lperron** [comment]
In interleave mode, we give all subsolvers the same deterministic time,
then wait for all of them to finish in order to synchronize.
I guess most of them find the optimal solution very fast, except the core
one. And because of the very imprecise time limit, it takes 30s instead of
2 before exiting its batch to synchronize.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le jeu. 19 oct. 2023 à 21:20, Ozan Erdem ***@***.***> a
écrit :

**Comment by lperron** [comment]
status: OPTIMAL
objective: 7738162918
best_bound: 7738162918
integers: 1655
booleans: 1867
conflicts: 67
branches: 12978
propagations: 12995
integer_propagations: 216095
restarts: 70
lp_iterations: 0
walltime: 2.38871
usertime: 2.38871
deterministic_time: 3.16717
gap_integral: 76.8854
