### ISSUE TITLE
ModuleNotFoundError: No module named 'ortools.linear_solver'

### ISSUE THREAD

**Issue by gmarchi** [google/or-tools#396]
I'm working on macOS Sierra with anaconda python 3.6 distribution. I installed or-tools from source because i need to use GLPK and everything seems going well when i run something like:
`make rpy EX=examples/python/integer_programming.py`
Troubles arrived when i run same example with:
`python examples/python/integer_programming.py`

It seems that python can't find ortools module:
```
Traceback (most recent call last):
  File "examples/python/integer_programming.py", line 17, in <module>
    from ortools.linear_solver import pywraplp
ModuleNotFoundError: No module named 'ortools.linear_solver'
```
So how can i workaround this? @lperron please help me!

**Comment by gmarchi** [comment]
I found a possible solution after inspecting `Makefile.python.mk.`

From the or-tools main directory:
1. `make pypi_archive`
2. `cd temp-pythonX.Y/ortools` where X.Y must be substituted with your python version
3. `python setup.py build`
4. `python setup.py install`

I hope this can be useful to someone else.

**Comment by helanhalvan** [comment]
This should make its way into some install trix list or something.

**Comment by lperron** [comment]
Normally, everything was fixed in the last release (v6.5).
So running pip install ortools should work provided you have a recent pip version (>= 9.0.1)

**Comment by helanhalvan** [comment]
If you are using some other solvers, like gurobi, you need to install from source anyway, and `make python` did not do the trick for me. Running ubuntu mate 16.04, 64 bit, python 2.7 that comes with the distribution. To get gurobi and or-tools to work in python, I followed https://github.com/google/or-tools/issues/421 instructions first, and then this.

**Comment by gmarchi** [comment]
Obviously commercial solvers like Gurobi need to be installed separately and are not shipped with or-tools. To use external solvers you need to compile the suite from source, providing required paths to external libraries  in Makefile.local.

**Comment by Sledge-** [comment]
I'm also having this issue with the latest version of ortools.

**Comment by gmarchi** [comment]
Installed via pip or compiled from source? Consider that this issue refers
to an outdated version of OR-Tools...so maybe you should raise a new issue.

Il Ven 17 Mag 2019, 17:25 Sledge- <notifications@github.com> ha scritto:
