### ISSUE TITLE
Consistently causing solver to terminate with "Infeasible LNS solution".

### ISSUE THREAD

**Issue by forceoffire** [google/or-tools#3965]
**What version of OR-Tools and what language are you using?**
Version: main/v9.7
Language: MiniZinc

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows

**What did you do?**
I've been working on a model for a while now.   Recently I added a few constraints that suddenly caused the whole model to start terminating with the "Infeasible LNS solution!" error message.  It typically finds ~50 solutions before terminating with this error message.  The solver consistently converges onto the error-state.

**What did you expect to see** 
Is it necessary to terminate if LNS solution is infeasible? Would it be possible to continue trying different neighbourhoods rather than terminating or skipping the infeasible solution and trying a different LNS parameter combination instead?

**Example of error message**
FZN solver plugin, compiled  Jun 20 2023  16:29:07
F1027 06:59:35.933344   14600 cp_model_solver.cc:3237] Infeasible LNS solution! graph_dec_lns(d=0.94 s=338 t=0.10 p=0.64 stall=0) solved with params log_search_progress: false max_deterministic_time: 0.1 cp_model_presolve: true stop_after_first_solution: false num_search_workers: 20 cp_model_probing_level: 0 symmetry_level: 0 log_to_stdout: false max_domain_size_when_encoding_eq_neq_constraints: 32 solution_pool_size: 1 num_workers: 20 find_big_linear_overlap: false
*** Check failure stack trace: ***
    @   00007FF642F8C2F9  (unknown)
    @   00007FF642B0CDF2  (unknown)
    @   00007FF642B81A7F  (unknown)
    @   00007FF642CF90A4  (unknown)
    @   00007FF642CF887F  (unknown)
    @   00007FFB97171BB2  (unknown)
    @   00007FFB98887614  (unknown)
    @   00007FFB993026B1  (unknown)
%%%mzn-stat: nSolutions=57
%%%mzn-stat-end

In this example the graph_dec_lns failed, but it varies for different runs.  I've attached this particular proto as example together with a feasible result (graph_cst_lns).

**Anything else we should know about your project / environment**
I'm using MiniZinc 2.7.6 with -O1 optimisation level (higher level optimisation does not influence outcome). 

[lns_examples.zip](https://github.com/google/or-tools/files/13186042/lns_examples.zip)

**Comment by lperron** [comment]
If I run both model on the main branch, I get an OPTIMAL solution.

Do you get something different ?

Can you send me the (mzn,dzn) or fzn model?

**Comment by forceoffire** [comment]
Dear Laurent,

Thank you so much for such a quick reply!   It is strange; the version I'm using is the release version.   I typically run it from the MiniZinc IDE.  Here is a typical output that I generate when using sat_runner.exe from the command line:

c:\MiniZinc\or-tools_x64_VisualStudio2022_cpp_v9.7.2996\bin>sat_runner.exe --input=lns_338_graph_dec_lns.pb.problematic.txt

Starting CP-SAT solver v9.7.2996
Parameters: log_search_progress: true
Setting number of workers to 24

Initial optimization model 'lns_338_graph_dec_lns': (model_fingerprint: 0x381c2eed80102c23)
#Variables: 319'938 (#bools: 1'003 #ints: 1'299 in objective)
  - 188'893 Booleans in [0,1]
  - 2'261 different domains in [-546,90420] with a largest complexity of 45.
  - 113203 constants in {-326,-320,-300,-280,-248, ... 20,325,338,370,490,608,623,624,631,636,881,1148}
#kAtMostOne: 772 (#literals: 7'738)
#kBoolAnd: 24'799 (#enforced: 24'432 #multi: 7'407) (#literals: 325'696)
#kBoolOr: 31'231 (#literals: 318'743)
#kExactlyOne: 4'865 (#literals: 158'234)
#kIntDiv: 783
#kIntProd: 305
#kLinMax: 1'252 (#expressions: 2'960)
#kLinear1: 335'221 (#enforced: 311'268 #multi: 102)
#kLinear2: 36'782 (#enforced: 34'775)
#kLinear3: 1'586 (#enforced: 371)
#kLinearN: 484 (#terms: 2'364)

Starting presolve at 0.12s
[ExtractEncodingFromLinear] #potential_supersets=1035 #potential_subsets=1 #at_most_one_encodings=0 #exactly_one_encodings=0 #unique_terms=0 #multiple_terms=0 #literals=0 time=0.00933303s
[SAT presolve] num removable Booleans: 310834 / 322040
[SAT presolve] num trivial clauses: 0
[SAT presolve] [0s] clauses:8973 literals:21979 vars:5275 one_side_vars:1859 simple_definition:1034 singleton_clauses:0
[SAT presolve] [0.003094s] clauses:7832 literals:18644 vars:5248 one_side_vars:2214 simple_definition:1075 singleton_clauses:371
[SAT presolve] [0.0137767s] clauses:7316 literals:17556 vars:4981 one_side_vars:2219 simple_definition:994 singleton_clauses:362
[Probing] implications and bool_or (work_done=31558).
[MaxClique] Merged 5177(10757 literals) into 4947(10417 literals) at_most_ones. time=0.02165s
[AllDiffInference] #different=8 #cliques=0 #size=0 time=0.0648558s
[DetectDuplicateConstraints] #duplicates=593 #without_enforcements=53 time=0.0844038s
[DetectDominatedLinearConstraints] #relevant_constraints=90 #work_done=947 #num_inclusions=11 #num_redundant=10 time=0.00806398s
[ProcessSetPPC] #relevant_constraints=783 #num_inclusions=186 work=9083 time=0.0266318s
[FindBigHorizontalLinearOverlap] #blocks=0 #saved_nz=0 #linears=4 #work_done=46/1e+09 time=0.0049856s
[FindBigVerticalLinearOverlap] #blocks=0 #nz_reduction=0 #work_done=13664 time=0.00586663s
[MergeClauses] #num_collisions=16 #num_merges=16 #num_saved_literals=32 work=710/100000000 time=0.0132695s
[SAT presolve] num removable Booleans: 317777 / 322327
[SAT presolve] num trivial clauses: 0
[SAT presolve] [0s] clauses:723 literals:1678 vars:642 one_side_vars:454 simple_definition:109 singleton_clauses:0
[SAT presolve] [0.0017627s] clauses:661 literals:1519 vars:642 one_side_vars:454 simple_definition:119 singleton_clauses:0
[SAT presolve] [0.00949869s] clauses:641 literals:1477 vars:632 one_side_vars:456 simple_definition:109 singleton_clauses:0
[Probing] implications and bool_or (work_done=10708).
[MaxClique] Merged 522(1147 literals) into 386(979 literals) at_most_ones. time=0.0183601s
[AllDiffInference] #different=3 #cliques=0 #size=0 time=0.0669139s
[DetectDuplicateConstraints] #duplicates=63 #without_enforcements=52 time=0.0867184s
[DetectDominatedLinearConstraints] #relevant_constraints=80 #work_done=808 #num_inclusions=1 #num_redundant=0 time=0.00930203s
[ProcessSetPPC] #relevant_constraints=538 #num_inclusions=69 work=5809 time=0.0314859s
[FindBigHorizontalLinearOverlap] #blocks=0 #saved_nz=0 #linears=3 #work_done=41/1e+09 time=0.00428981s
[FindBigVerticalLinearOverlap] #blocks=0 #nz_reduction=0 #work_done=12003 time=0.00513726s
[MergeClauses] #num_collisions=13 #num_merges=13 #num_saved_literals=26 work=534/100000000 time=0.0137932s
[SAT presolve] num removable Booleans: 317939 / 322327
[SAT presolve] num trivial clauses: 0
[SAT presolve] [0s] clauses:301 literals:782 vars:346 one_side_vars:246 simple_definition:63 singleton_clauses:0
[SAT presolve] [0.0016307s] clauses:274 literals:728 vars:346 one_side_vars:246 simple_definition:64 singleton_clauses:0
[SAT presolve] [0.00983137s] clauses:274 literals:728 vars:346 one_side_vars:246 simple_definition:64 singleton_clauses:0
[Probing] implications and bool_or (work_done=9101).
[MaxClique] Merged 160(415 literals) into 159(421 literals) at_most_ones. time=0.0190469s
[AllDiffInference] #different=3 #cliques=0 #size=0 time=0.0666784s
[DetectDuplicateConstraints] #duplicates=1 #without_enforcements=52 time=0.0856812s
[DetectDominatedLinearConstraints] #relevant_constraints=80 #work_done=808 #num_inclusions=1 #num_redundant=0 time=0.00835218s
[ProcessSetPPC] #relevant_constraints=499 #num_inclusions=34 work=4933 time=0.0355717s
[FindBigHorizontalLinearOverlap] #blocks=0 #saved_nz=0 #linears=3 #work_done=41/1e+09 time=0.00382808s
[FindBigVerticalLinearOverlap] #blocks=0 #nz_reduction=0 #work_done=11989 time=0.00510274s
[MergeClauses] #num_collisions=13 #num_merges=13 #num_saved_literals=26 work=534/100000000 time=0.0123504s
[ExpandObjective] #propagations=0 #entries=2078 #tight_variables=741 #tight_constraints=219 #expands=51 #issues=0 time=0.0146865s
3 affine relations still in the model.

Presolve summary:
  - 9495 affine relations were detected.
  - rule 'TODO dual: add implied bound' was applied 1914 times.
  - rule 'TODO dual: make linear1 equiv' was applied 1662 times.
  - rule 'TODO dual: only one blocking constraint?' was applied 6167 times.
  - rule 'TODO dual: only one blocking enforced constraint?' was applied 4575 times.
  - rule 'TODO dual: only one unspecified blocking constraint?' was applied 69 times.
  - rule 'TODO dual: tighten at most one' was applied 84 times.
  - rule 'TODO duplicate: identical constraint with different enforcements' was applied 157 times.
  - rule 'TODO linear2: contains a Boolean.' was applied 2738 times.
  - rule 'TODO variables: only used in linear1.' was applied 648 times.
  - rule 'affine: fixed' was applied 36 times.
  - rule 'affine: new relation' was applied 9495 times.
  - rule 'at_most_one: dominated singleton' was applied 1 time.
  - rule 'at_most_one: empty or all false' was applied 557 times.
  - rule 'at_most_one: removed literals' was applied 1995 times.
  - rule 'at_most_one: resolved two constraints with opposite literal' was applied 44 times.
  - rule 'at_most_one: satisfied' was applied 3395 times.
  - rule 'at_most_one: singleton' was applied 6 times.
  - rule 'at_most_one: size one' was applied 1991 times.
  - rule 'at_most_one: transformed into max clique.' was applied 3 times.
  - rule 'at_most_one: x and not(x)' was applied 43 times.
  - rule 'bool_and: always false' was applied 9960 times.
  - rule 'bool_and: cannot be enforced' was applied 22 times.
  - rule 'bool_and: fixed literals' was applied 10182 times.
  - rule 'bool_and: non-reified.' was applied 21931 times.
  - rule 'bool_and: removed duplicate literal' was applied 1 time.
  - rule 'bool_and: x => not x' was applied 5 times.
  - rule 'bool_and: x => x' was applied 3016 times.
  - rule 'bool_or: always true' was applied 16836 times.
  - rule 'bool_or: fixed literals' was applied 5204 times.
  - rule 'bool_or: implications' was applied 9047 times.
  - rule 'bool_or: only one literal' was applied 93281 times.
  - rule 'bool_or: removed enforcement literal' was applied 158 times.
  - rule 'bool_or: singleton' was applied 2342 times.
  - rule 'deductions: 338042 stored' was applied 1 time.
  - rule 'deductions: reduced variable domain' was applied 10 times.
  - rule 'domination: fixed to lb.' was applied 35 times.
  - rule 'domination: in exactly one' was applied 43 times.
  - rule 'domination: in implication' was applied 18 times.
  - rule 'domination: reduced ub.' was applied 7 times.
  - rule 'dual: add implication' was applied 140 times.
  - rule 'dual: affine relation' was applied 17 times.
  - rule 'dual: enforced equivalence' was applied 1238 times.
  - rule 'dual: fix variable' was applied 1209 times.
  - rule 'dual: make encoding equiv' was applied 1779 times.
  - rule 'dual: reduced domain' was applied 492 times.
  - rule 'duplicate: merged rhs of linear constraint' was applied 8 times.
  - rule 'duplicate: removed constraint' was applied 657 times.
  - rule 'enforcement: can never be true' was applied 24 times.
  - rule 'enforcement: false literal' was applied 92888 times.
  - rule 'enforcement: literal not used' was applied 4869 times.
  - rule 'enforcement: literal with unique direction' was applied 3 times.
  - rule 'enforcement: true literal' was applied 176246 times.
  - rule 'exactly_one: removed literals' was applied 5324 times.
  - rule 'exactly_one: satisfied' was applied 2570 times.
  - rule 'exactly_one: simplified objective' was applied 14 times.
  - rule 'exactly_one: singleton' was applied 27 times.
  - rule 'exactly_one: size one' was applied 294 times.
  - rule 'exactly_one: size two' was applied 1694 times.
  - rule 'exactly_one: x and not(x)' was applied 934 times.
  - rule 'incompatible linear: add implication' was applied 85 times.
  - rule 'int_abs: converted to equality' was applied 262 times.
  - rule 'int_abs: fixed expression' was applied 9 times.
  - rule 'int_abs: fixed target' was applied 12 times.
  - rule 'int_abs: propagate domain from abs(x) to x' was applied 6 times.
  - rule 'int_abs: propagate domain from x to abs(x)' was applied 235 times.
  - rule 'int_abs: store abs(x) == y' was applied 289 times.
  - rule 'int_abs: unused target' was applied 6 times.
  - rule 'int_div: always true' was applied 330 times.
  - rule 'int_div: linearize positive division with a constant divisor' was applied 181 times.
  - rule 'int_div: rewrite to equality' was applied 146 times.
  - rule 'int_div: target and divisor are fixed' was applied 26 times.
  - rule 'int_div: target has been fixed by propagating X / cte' was applied 162 times.
  - rule 'int_div: updated domain of target in target = X / cte' was applied 177 times.
  - rule 'int_prod: constant product' was applied 148 times.
  - rule 'int_prod: divide product by constant factor' was applied 1 time.
  - rule 'int_prod: expression is constant.' was applied 10 times.
  - rule 'int_prod: linearize product by constant.' was applied 147 times.
  - rule 'int_prod: reduced target domain.' was applied 388 times.
  - rule 'int_prod: removed constant expressions.' was applied 412 times.
  - rule 'lin_max: all Booleans.' was applied 42 times.
  - rule 'lin_max: always satisfied' was applied 24 times.
  - rule 'lin_max: converted to equality' was applied 598 times.
  - rule 'lin_max: fixed target and all booleans' was applied 3 times.
  - rule 'lin_max: reduced expression domain.' was applied 189 times.
  - rule 'lin_max: removed exprs' was applied 874 times.
  - rule 'lin_max: target domain reduced' was applied 1936 times.
  - rule 'lin_max: unused affine target' was applied 7 times.
  - rule 'lin_max: x = max(x, ...)' was applied 309 times.
  - rule 'linear inclusion: redundant included constraint' was applied 6 times.
  - rule 'linear inclusion: subset + singleton is equality' was applied 4 times.
  - rule 'linear1: always true' was applied 31 times.
  - rule 'linear1: is boolean implication' was applied 2017 times.
  - rule 'linear1: remove abs from abs(x) in domain' was applied 444 times.
  - rule 'linear1: transformed to implication' was applied 21041 times.
  - rule 'linear1: without enforcement' was applied 40622 times.
  - rule 'linear2: Boolean with one feasible value.' was applied 40 times.
  - rule 'linear2: contains a Boolean.' was applied 87 times.
  - rule 'linear2: implied ax + by = cte has only one solution' was applied 388 times.
  - rule 'linear: always true' was applied 130027 times.
  - rule 'linear: coefficient strenghtening.' was applied 63 times.
  - rule 'linear: divide by GCD' was applied 34358 times.
  - rule 'linear: empty' was applied 8295 times.
  - rule 'linear: enforcement literal in expression' was applied 1348 times.
  - rule 'linear: extracted enforcement literal' was applied 27 times.
  - rule 'linear: fixed or dup variables' was applied 127519 times.
  - rule 'linear: infeasible' was applied 70076 times.
  - rule 'linear: negative clause' was applied 2 times.
  - rule 'linear: negative equal one' was applied 27 times.
  - rule 'linear: only two odd Booleans in equality' was applied 2 times.
  - rule 'linear: positive clause' was applied 1 time.
  - rule 'linear: positive equal one' was applied 20 times.
  - rule 'linear: reduce rhs with DP' was applied 8 times.
  - rule 'linear: reduced variable domains' was applied 55728 times.
  - rule 'linear: reduced variable domains in derived constraint' was applied 2 times.
  - rule 'linear: remapped using affine relations' was applied 130651 times.
  - rule 'linear: remove irrelevant part' was applied 11 times.
  - rule 'linear: simplified rhs' was applied 195688 times.
  - rule 'linear: simplify using approximate gcd' was applied 36 times.
  - rule 'linear: singleton column' was applied 19 times.
  - rule 'linear: small Boolean expression' was applied 44 times.
  - rule 'linear: variable substitution 0' was applied 61 times.
  - rule 'linear: variable substitution 1' was applied 65 times.
  - rule 'linear: variable substitution 2' was applied 33 times.
  - rule 'linear: variable substitution 3' was applied 23 times.
  - rule 'objective: expanded via tight equality' was applied 51 times.
  - rule 'objective: shifted cost with exactly ones' was applied 35 times.
  - rule 'objective: variable not used elsewhere' was applied 6 times.
  - rule 'presolve: 312053 unused variables removed.' was applied 1 time.
  - rule 'presolve: iteration' was applied 3 times.
  - rule 'probing: bool_or reduced to implication' was applied 538 times.
  - rule 'probing: simplified clauses.' was applied 40 times.
  - rule 'setppc: bool_or in at_most_one.' was applied 113 times.
  - rule 'setppc: removed dominated constraints' was applied 78 times.
  - rule 'variables with 2 values: create encoding literal' was applied 368 times.
  - rule 'variables with 2 values: fixed encoding' was applied 45 times.
  - rule 'variables with 2 values: merge encoding literals' was applied 153 times.
  - rule 'variables with 2 values: new affine relation' was applied 706 times.
  - rule 'variables with 2 values: register other encoding' was applied 73 times.
  - rule 'variables: add encoding constraint' was applied 1453 times.
  - rule 'variables: canonicalize affine domain' was applied 271 times.
  - rule 'variables: canonicalize domain' was applied 297 times.
  - rule 'variables: detect fully reified value encoding' was applied 134182 times.
  - rule 'variables: detect half reified value encoding' was applied 285377 times.
  - rule 'variables: only used in encoding' was applied 1326 times.
  - rule 'variables: only used in objective and in encoding' was applied 5 times.
  - rule 'variables: removable enforcement literal' was applied 117 times.

Presolved optimization model 'lns_338_graph_dec_lns': (model_fingerprint: 0x7c6b4c7dee718657)
#Variables: 1'046 (#bools: 162 #ints: 155 in objective)
  - 558 Booleans in [0,1]
  - 179 different domains in [-320,1600] with a largest complexity of 8.
#kAtMostOne: 63 (#literals: 220)
#kBoolAnd: 104 (#enforced: 104 #multi: 6) (#literals: 242)
#kBoolOr: 158 (#literals: 477)
#kExactlyOne: 163 (#literals: 608)
#kIntDiv: 88
#kLinMax: 119 (#expressions: 238)
#kLinear1: 1'162 (#enforced: 1'162)
#kLinear2: 231 (#enforced: 210)
#kLinear3: 46
#kLinearN: 16 (#terms: 93)

Preloading model.
#Bound   5.47s best:-inf  next:[2425670,2521860] initial_domain
#Model   5.48s var:1046/1046 constraints:2150/2150 compo:915,22,18,17,13,8,8,7,7,7,...

Starting search at 5.48s with 24 workers.
13 full problem subsolvers: [core, default_lp, lb_tree_search, max_lp, no_lp, objective_lb_search, objective_shaving_search, probing, probing_max_lp, pseudo_costs, quick_restart, quick_restart_no_lp, reduced_costs]
9 first solution subsolvers: [jump, jump_decay_no_rst, jump_decay_perturb, jump_decay_rnd_on_rst, jump_no_rst, random(2), random_quick_restart(2)]
8 incomplete subsolvers: [feasibility_pump, graph_arc_lns, graph_cst_lns, graph_dec_lns, graph_var_lns, rins/rens, rnd_cst_lns, rnd_var_lns]
3 helper subsolvers: [neighborhood_helper, synchronization_agent, update_gap_integral]
#Bound   5.50s best:-inf  next:[2425670,2521855] objective_shaving_search #vars=1047 #csts=2151
#Bound   5.51s best:-inf  next:[2425675,2521660] no_lp initial_propagation
#1       5.51s best:2501710 next:[2501715,2521660] no_lp [hint] fixed_bools:0/898
#2       5.51s best:2502235 next:[2502240,2521660] no_lp fixed_bools:0/909
#Bound   5.51s best:2502235 next:[2502240,2517055] objective_lb_search initial_propagation
#Bound   5.52s best:2502235 next:[2502240,2515295] objective_lb_search
#Bound   5.53s best:2502235 next:[2502240,2513010] objective_lb_search
#Bound   5.54s best:2502235 next:[2502240,2512500] probing
#Bound   5.55s best:2502235 next:[2502240,2512445] probing
#Bound   5.55s best:2502235 next:[2502240,2512395] probing
#3       5.59s best:2502485 next:[2502490,2512395] rnd_cst_lns(d=0.81 s=38 t=0.10 p=1.00 stall=2) [hint]
#Bound   5.60s best:2502485 next:[2502490,2506605] lb_tree_search initial_propagation
#4       5.67s best:2503235 next:[2503240,2506605] graph_cst_lns(d=0.71 s=49 t=0.10 p=1.00 stall=1)
#Bound   5.70s best:2503235 next:[2503240,2505275] max_lp
#5       5.73s best:2504225 next:[2504230,2505275] graph_var_lns(d=0.71 s=47 t=0.10 p=1.00 stall=1)
#6       5.87s best:2504475 next:[2504480,2505275] rnd_var_lns(d=0.94 s=61 t=0.10 p=1.00 stall=5)
#Bound   5.88s best:2504475 next:[2504480,2504685] lb_tree_search
#Bound   6.04s best:2504475 next:[2504480,2504565] lb_tree_search
#Bound   6.12s best:2504475 next:[2504480,2504515] lb_tree_search
#Done    6.16s lb_tree_search
#Done    6.16s quick_restart_no_lp
#Done    6.16s core
#Done    6.17s probing

Task timing                           n [     min,      max]      avg      dev     time         n [     min,      max]      avg      dev    dtime
     'synchronization_agent':         0 [  0.00ns,   0.00ns]   0.00ns   0.00ns   0.00ns         0 [  0.00ns,   0.00ns]   0.00ns   0.00ns   0.00ns
       'neighborhood_helper':         0 [  0.00ns,   0.00ns]   0.00ns   0.00ns   0.00ns         0 [  0.00ns,   0.00ns]   0.00ns   0.00ns   0.00ns
                'default_lp':         1 [683.95ms, 683.95ms] 683.95ms   0.00ns 683.95ms         1 [  8.45ms,   8.45ms]   8.45ms   0.00ns   8.45ms
                     'no_lp':         1 [683.75ms, 683.75ms] 683.75ms   0.00ns 683.75ms         1 [ 94.19ms,  94.19ms]  94.19ms   0.00ns  94.19ms
                    'max_lp':         1 [693.80ms, 693.80ms] 693.80ms   0.00ns 693.80ms         0 [  0.00ns,   0.00ns]   0.00ns   0.00ns   0.00ns
                      'core':         1 [681.68ms, 681.68ms] 681.68ms   0.00ns 681.68ms         1 [ 36.26ms,  36.26ms]  36.26ms   0.00ns  36.26ms
             'reduced_costs':         1 [686.55ms, 686.55ms] 686.55ms   0.00ns 686.55ms         1 [ 10.77ms,  10.77ms]  10.77ms   0.00ns  10.77ms
              'pseudo_costs':         1 [687.65ms, 687.65ms] 687.65ms   0.00ns 687.65ms         1 [  5.40ms,   5.40ms]   5.40ms   0.00ns   5.40ms
             'quick_restart':         1 [684.95ms, 684.95ms] 684.95ms   0.00ns 684.95ms         1 [  9.98ms,   9.98ms]   9.98ms   0.00ns   9.98ms
       'quick_restart_no_lp':         1 [680.67ms, 680.67ms] 680.67ms   0.00ns 680.67ms         1 [ 24.91ms,  24.91ms]  24.91ms   0.00ns  24.91ms
            'lb_tree_search':         1 [686.22ms, 686.22ms] 686.22ms   0.00ns 686.22ms         0 [  0.00ns,   0.00ns]   0.00ns   0.00ns   0.00ns
       'objective_lb_search':         1 [684.68ms, 684.68ms] 684.68ms   0.00ns 684.68ms         1 [ 21.23ms,  21.23ms]  21.23ms   0.00ns  21.23ms
                   'probing':         1 [687.29ms, 687.29ms] 687.29ms   0.00ns 687.29ms         1 [ 11.54ms,  11.54ms]  11.54ms   0.00ns  11.54ms
            'probing_max_lp':         1 [692.73ms, 692.73ms] 692.73ms   0.00ns 692.73ms         1 [  6.94ms,   6.94ms]   6.94ms   0.00ns   6.94ms
  'objective_shaving_search':         7 [ 15.79ms, 179.69ms]  96.67ms  50.13ms 676.68ms         6 [233.48us, 287.13us] 260.21us  20.29us   1.56ms
          'feasibility_pump':         8 [  9.63ms,  57.77ms]  37.09ms  13.71ms 296.73ms         7 [  5.98ms,  11.33ms]   6.78ms   1.86ms  47.49ms
                 'rins/rens':         8 [ 13.48ms,  87.72ms]  41.53ms  27.43ms 332.27ms         6 [ 31.77us, 579.05us] 237.38us 214.70us   1.42ms
               'rnd_var_lns':         7 [ 10.25ms, 143.14ms]  56.81ms  44.54ms 397.67ms         6 [  8.11us,   5.55ms]   1.19ms   2.02ms   7.16ms
               'rnd_cst_lns':         7 [ 12.01ms, 173.67ms]  74.97ms  58.38ms 524.79ms         7 [439.40ns,   3.56ms] 997.88us   1.48ms   6.99ms
             'graph_var_lns':         7 [  8.48ms, 313.29ms] 210.81ms 102.20ms    1.48s         7 [  9.70us,  14.90ms]   7.02ms   4.86ms  49.16ms
             'graph_arc_lns':         7 [  4.32ms, 610.04ms] 300.57ms 235.86ms    2.10s         4 [834.40ns,  84.69ms]  22.56ms  35.93ms  90.25ms
             'graph_cst_lns':         7 [ 43.44ms, 500.29ms] 163.66ms 152.11ms    1.15s         5 [201.60us,  38.27ms]   8.17ms  15.05ms  40.86ms
             'graph_dec_lns':         7 [  8.58ms, 373.58ms]  97.50ms 116.94ms 682.51ms         6 [ 21.38us,  15.14ms]   2.79ms   5.53ms  16.77ms
       'update_gap_integral':         0 [  0.00ns,   0.00ns]   0.00ns   0.00ns   0.00ns         0 [  0.00ns,   0.00ns]   0.00ns   0.00ns   0.00ns

Search stats              Bools  Conflicts  Branches  Restarts  BoolPropag  IntegerPropag
           'default_lp':    873        121     1'955     1'699      25'697         65'591
                'no_lp':    943      6'511    10'367     1'697     589'453      1'270'902
               'max_lp':    909          0     1'690     1'690      11'537         26'613
                 'core':  1'308        287    51'662     2'182     260'320        475'349
        'reduced_costs':    961          8     1'909     1'691      12'493         29'745
         'pseudo_costs':    961          7     1'910     1'691      12'491         29'627
        'quick_restart':    876         93     2'103     1'701      21'097         53'812
  'quick_restart_no_lp':  1'021      1'479    12'183     1'839     171'622        477'818
       'lb_tree_search':    909          0     1'696     1'690      11'540         26'666
  'objective_lb_search':    874        414     2'304     1'694      60'477        169'833
              'probing':    876         95     2'002     1'719      24'230         59'100
       'probing_max_lp':    961          6     1'908     1'691      12'920         30'478

LNS stats           Improv/Calls  Closed  Difficulty  TimeLimit
      'rins/rens':           0/8     88%        0.96       0.10
    'rnd_var_lns':           1/7    100%        0.97       0.10
    'rnd_cst_lns':           1/7    100%        0.97       0.10
  'graph_var_lns':           4/7     86%        0.94       0.10
  'graph_arc_lns':           3/7     43%        0.53       0.10
  'graph_cst_lns':           3/7     57%        0.78       0.10
  'graph_dec_lns':           1/7     86%        0.94       0.10

Solutions (6)       Num   Rank
  'graph_cst_lns':    1  [4,4]
  'graph_var_lns':    1  [5,5]
          'no_lp':    2  [1,2]
    'rnd_cst_lns':    1  [3,3]
    'rnd_var_lns':    1  [6,6]

Objective bounds               Num
            'initial_domain':    1
            'lb_tree_search':    4
                    'max_lp':    1
                     'no_lp':    1
       'objective_lb_search':    3
  'objective_shaving_search':    1
                   'probing':    3

Solution repositories    Added  Queried  Ignored  Synchro
  'feasible solutions':     44      107        3       33
        'lp solutions':      6        8        0        3
                'pump':      0        0

Improving bounds shared    Num
                  'core':   10
            'default_lp':   77
                'max_lp':    1
                 'no_lp':    5
   'objective_lb_search':   22
         'quick_restart':    9
   'quick_restart_no_lp':   12
         'reduced_costs':  145

Clauses shared            Num
                 'core':   10
                'no_lp':    2
              'probing':   26
        'quick_restart':    1
  'quick_restart_no_lp':    4

F1027 15:47:57.454898   37648 cp_model_solver.cc:4380] Check failed: SolutionIsFeasible( model_proto, std::vector<int64_t>(response->solution().begin(), response->solution().end()), mapping_proto, &postsolve_mapping) postsolved solution
*** Check failure stack trace: ***
    @   00007FF62D59A3F9  (unknown)
    @   00007FF62D0FD262  (unknown)
    @   00007FF62D19E617  (unknown)
    @   00007FF62D19DD7A  (unknown)
    @   00007FF62D10D647  (unknown)
    @   00007FF62D0A9D02  (unknown)
    @   00007FF62DDC6AF8  (unknown)
    @   00007FFB98887614  (unknown)
    @   00007FFB993026B1  (unknown)

I've appended three more pb files, which on my side cause a similar error in sat_runner; and, also the compiled fzn.  In the most recent run I tried, it crashed after finding 24 solutions:

minizinc --json-stream --push-working-directory C:/b_v4.0 --param-file-no-push C:/Users/v/AppData/Local/Temp/mzn_YPLBGj.mpc --pop-working-directory C:/b_v4.0/full_model_v402.mzn C:/b_v4.0/example_data_2023_10_27T06_00_00.dzn
...
	CompilePass: Flatten with 'c:\MiniZinc\or-tools_x64_VisualStudio2022_cpp_v9.7.2996\share\minizinc\ortools' library ...
MIP domains ...
 done (6.33 s)
Optimizing ... done (6.69 s)
Converting to old FlatZinc ... done (7.18 s)
 done (7.18 s)
 done (7.21 s), max stack depth 51
%%%mzn-stat: eliminatedImplications=19876
%%%mzn-stat: evaluatedHalfReifiedConstraints=61287
%%%mzn-stat: evaluatedReifiedConstraints=76957
%%%mzn-stat: flatBoolConstraints=101231
%%%mzn-stat: flatBoolVars=138310
%%%mzn-stat: flatIntConstraints=153409
%%%mzn-stat: flatIntVars=54691
%%%mzn-stat: flatTime=7.23041
%%%mzn-stat: method=maximize
%%%mzn-stat: paths=0
%%%mzn-stat-end
Maximum memory 295 Mbytes.
      % SOLVING PHASE
FZN solver plugin, compiled  Jun 20 2023  16:29:07
F1027 15:57:24.217621    3336 cp_model_solver.cc:3237] Infeasible LNS solution! rnd_cst_lns(d=0.97 s=234 t=0.10 p=0.89 stall=0) solved with params log_search_progress: false max_deterministic_time: 0.1 cp_model_presolve: true stop_after_first_solution: false num_search_workers: 22 cp_model_probing_level: 0 symmetry_level: 0 log_to_stdout: false max_domain_size_when_encoding_eq_neq_constraints: 32 solution_pool_size: 1 num_workers: 22 find_big_linear_overlap: false
*** Check failure stack trace: ***
    @   00007FF642F8C2F9  (unknown)
    @   00007FF642B0CDF2  (unknown)
    @   00007FF642B81A7F  (unknown)
    @   00007FF642CF90A4  (unknown)
    @   00007FF642CF887F  (unknown)
    @   00007FFB97171BB2  (unknown)
    @   00007FFB98887614  (unknown)
    @   00007FFB993026B1  (unknown)
%%%mzn-stat: nSolutions=24
%%%mzn-stat-end

[fzn_more_pb_examples.zip](https://github.com/google/or-tools/files/13191080/fzn_more_pb_examples.zip)

**Comment by lperron** [comment]
I am on main which is ahead of 9.7
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le ven. 27 oct. 2023 à 18:12, forceoffire ***@***.***> a
écrit :

**Comment by lperron** [comment]
I can reproduce it from the fzn. Thanks

**Comment by forceoffire** [comment]
Thank you.  I thought I might be flagging something you already addressed.

**Comment by lperron** [comment]
Thanks again for the report.
This was a nasty one.
