### ISSUE TITLE
Install Python step fail on Windows 10 MSVC

### ISSUE THREAD

**Issue by arnabadas** [google/or-tools#3967]
**What version of OR-Tools and what language are you using?**
Version: main
Language: C++/Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
NA

**What operating system (Linux, Windows, ...) and version?**
Windows 10 Pro 22H2

**What did you do?**
Run Install step of or-tools (C++ and Python) using a custom `CMAKE_INSTALL_PREFIX` path with no spaces

**What did you expect to see**
No error message

**What did you see instead?**
End section of the error message:
[error_endsection.txt](https://github.com/google/or-tools/files/13193558/error_endsection.txt)

**Anything else we should know about your project / environment**
 Visual Studio Community 17.7.6

**Comment by Mizux** [comment]
line 7299

```
 self.initialize_options()
EXEC : error : can't create or remove files in install directory [D:\user\or-tools\build\INSTALL.vcxproj]

  The following error occurred while trying to add or remove files in the
  installation directory:

      [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'd:\\user\\or-tools\\build\\python\\"
  d:'

  The installation directory you specified (via --install-dir, --prefix, or
  the distutils default setting) was:

      "D:\User\or-tools\install_latest"\Lib\site-packages

  This directory does not currently exist.  Please create it and try again, or
  choose a different installation directory (using the -d or --install-dir
  option).
  ```
  
I think it is the python install step which only support posix like OS...
https://github.com/google/or-tools/blob/003f9f54cecf0dc2da4ab1ae83ba189fa641d965/cmake/python-install.cmake.in#L25-L31
I think on windows we should rely  on pip install since we have a wheel package + `setpu.py install` is deprecated....
