### ISSUE TITLE
Duration of task should be 0 for Cumulative constraint when capacity is insufficient

### ISSUE THREAD

**Issue by IgnaceBleukx** [google/or-tools#3970]
Hi,

I am trying to use the CP-SAT solver to find a solution for a Cumulative constraint where the durations are integer variables.
When the required resource of a task exceeds the total capacity I would assume the duration of the task is put to 0.
However, in the following example this is not the case and the solver does not find a solution:

```python
from ortools.sat.python import cp_model as ort

model = ort.CpModel()
solver = ort.CpSolver()

start = [model.NewIntVar(0,4,f"start_{i}") for i in range(3)]
end = [model.NewIntVar(0,4,f"end_{i}") for i in range(3)]

dur = [model.NewIntVar(0,1,f"dur_{i}") for i in range(3)]
# dur = [1,0,1]

intervals = [model.NewIntervalVar(s,d,e,f"{s}-{d}-{e}") for s,d,e in zip(start,dur,end)]

model.AddCumulative(intervals, [1,5,1],1) # requirement of second task exceeds capacity

# solver.parameters.cp_model_presolve=False
status = solver.Solve(model)

if status == ort.INFEASIBLE:
    print("Model is UNSAT")
else:
    print("Found solution")

>> Output: 'Model is UNSAT'
```

By uncommenting the line forcing the durations to [1,0,1] the model becomes SAT.
Also by disabling presolve the solver finds a solution.

I am using OR-tools version 9.7.2996 on Ubuntu 22.04.

Kind regards,
Ignace

**Comment by lperron** [comment]
Fixed on main.

Thanks for the report.
