### ISSUE TITLE
Cumulative solution checking is slow with long durations

### ISSUE THREAD

**Issue by ozan-cb** [google/or-tools#3982]
**What version of OR-Tools and what language are you using?**
Version: v9.7, main
Language: All

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
All platforms

**What did you do?**
I have a very small scheduling problem with very large domains for intervals. CP-SAT is very fast on it, however it hangs for about 15 minutes while it checks the solution after solving.

This is the loop that's taking too long (`CumulativeConstraintIsFeasible`):
https://github.com/Cerebras/or-tools/blob/202bc5414a6462a725824821adb55e0840e41301/ortools/sat/cp_model_checker.cc#L861
and with durations of billions of cycles that takes too long. This would ideally be O(tasks) instead of O(T).

Also, there's a `todo` about the same thing :)
https://github.com/Cerebras/or-tools/blob/202bc5414a6462a725824821adb55e0840e41301/ortools/sat/cp_model_checker.cc#L848

**Anything else we should know about your project / environment**

Proto is attached, however this would be easily replicated on any instance with a solution spanning a large interval.
[model.proto.zip](https://github.com/google/or-tools/files/13322892/model.proto.zip)

**Comment by ozan-cb** [comment]
A side note, as a workaround I can divide the durations by 1000 to get a fast run without affecting the solution quality much, however it would be nice if this can still be optimized.

**Comment by lperron** [comment]
Fixed on main.

**Comment by ozan-cb** [comment]
Thank you. Is this supposed to be already on Github? I don't think I see any changes in `main` with respect to `stable`.

**Comment by lperron** [comment]
development is not in stable. It is on main. Stable is sync on release.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le ven. 10 nov. 2023 à 23:05, Ozan Erdem ***@***.***> a
écrit :

**Comment by ozan-cb** [comment]
Hi @lperron, what I meant is that `main` seems to still have the bug, as I already specifically used `main` when I filed the bug and there have been no changes to it since then. I still see the time based checking here on `main`, along with the todo comment:
https://github.com/google/or-tools/blob/main/ortools/sat/cp_model_checker.cc#L1361

**Comment by lperron** [comment]
My bad. I fixed another part of the code.

**Comment by lperron** [comment]
Thanks

**Comment by ozan-cb** [comment]
No problem, thanks a lot for the quick fix.
