### ISSUE TITLE
SufficientAssumptionsForInfeasibility in C#/.Net returns the original set.

### ISSUE THREAD

**Issue by sergey-polyakovskiy** [google/or-tools#3983]
Dear all,

I am testing a classic example to let the solver heuristically determine a sufficient set of constraints causing infeasibility. The following example is common in the Internet (usually provided in Python, https://github.com/google/or-tools/blob/master/ortools/sat/samples/assumptions_sample_sat.py). I would expect it to return a subset of less than 3 literals. However, in C# the solver still returns the full (original) set of 3 literals (a, b, and c). I wonder whether I am doing something wrong or more flag options are required before starting the solver. I would appreciate your help.

            CpModel model = new CpModel();
            IntVar x = model.NewIntVar(0, 10, "x");
            IntVar y = model.NewIntVar(0, 10, "y");
            IntVar z = model.NewIntVar(0, 10, "z");

            ILiteral a = model.NewBoolVar("a");
            ILiteral b = model.NewBoolVar("b");
            ILiteral c = model.NewBoolVar("c");

            model.Add(x > y).OnlyEnforceIf(a);
            model.Add(y > z).OnlyEnforceIf(b);
            model.Add(z > x).OnlyEnforceIf(c);

            model.AddAssumptions(new ILiteral[] { a, b, c });
            CpSolver solver = new CpSolver();
            solver.StringParameters = "log_search_progress: true, num_search_workers: 1";
            CpSolverStatus status = solver.Solve(model);
            List<int> infeasibilities = solver.SufficientAssumptionsForInfeasibility().ToList();
            foreach (int index in infeasibilities)
            {
                Console.WriteLine("Variable: {0}\n", model.Model.Variables[index]);
            }

**Comment by lperron** [comment]
Read the.log. you either have an objective, or use more than 1 worker.

**Comment by sergey-polyakovskiy** [comment]
Thank you, Laurent. I am aware of those settings. Therefore, there is no objective function in the example; it is a satisfiability problem. As you can see, I set num_search_workers to 1 in the solver's parameters and can observe this being active in the log. 

The example creates an infeasible circuit: x > y > z > x. Of course, if we exclude all three literals, the problem becomes feasible (it is a valid solution for SufficientAssumptionsForInfeasibility). But this is not the solution we want. It is enough to eliminate one constraint to break the circuit. Therefore, the function should return either a, or b, or c. There are to be 3 sets of singletons.

Am I missing something?

**Comment by lperron** [comment]
No, the system returns a minimal unsatisfiable set, not a minimal
correction set.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by lperron** [comment]
(minimal is not guaranteed)
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by sergey-polyakovskiy** [comment]
Thank you. I now can see my problem with this example.

Actually, I came from a larger model that has many different constraints including implications, ExactlyOne, AtMostOne, and cumulative scheduling constraints; that is, not just linear expressions. A feasible solution is only when all literals are set to TRUE. For each decision boolean variable I add the following: model.Add(x == 1).OnlyEnforceIf(a). I am trying to find the minimal unsatisfiable set (generally to strengthen the Bender's cut). The model itself has been tested and is correct; I mainly want to find the set now. I get it infeasible, but SufficientAssumptionsForInfeasibility returns an empty set. Could this be because of mixing various constraint types? Are there any limitations on the use of SufficientAssumptionsForInfeasibility?
