### ISSUE TITLE
Performance Degradation When Solving Multiple GLOP Problems in Parallel

### ISSUE THREAD

**Issue by Diddlik** [google/or-tools#3996]
**What version of OR-Tools and what language are you using?**
Version: main/v9.7/v9.6/v8.1
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
GLOP

**What operating system (Linux, Windows, ...) and version?**
Windows

I am experiencing a significant decrease in performance when attempting to solve multiple problems in parallel using the GLOP solver in my tool. While individual problem solving performs as expected, parallel processing leads to drastically increased computation times.

Details:

    Single Problem: When solving a single problem, the process takes approximately 50 seconds with about 1GB of memory usage, which is within expected parameters.

    Two Problems in Parallel: However, when I run two problems in parallel, the solving time for each increases to around 70 seconds.

    Four Problems in Parallel: With four parallel problems, the computation time further escalates to 120 seconds.

    Ten Problems in Parallel: Most notably, with ten parallel problems, the solving time skyrockets to approximately 600 seconds.

Contrastingly, when I run ten separate instances with one problem each, the average solving time per problem remains at a more reasonable 55 seconds.

System Specifications:

    32 Core CPU
    64 GB RAM
    NVMe storage, ensuring no hardware bottlenecks

Question:
This behavior suggests a possible issue with parallel processing efficiency in the GLOP solver. How can this problem be addressed or mitigated? Are there any configurations or optimizations I can apply to improve parallel processing performance with the GLOP solver?

**Comment by Mizux** [comment]
What is the size of one problem in RAM ? Did you see some swap ?
Also having several GLOP in // you must increase the cache miss ratio between process...

**Comment by lperron** [comment]
GLOP is memory intensive.
I guess your computer is memory bandwidth bound.

**Comment by Diddlik** [comment]
> GLOP is memory intensive. I guess your computer is memory bandwidth bound.

from 64GB it uses only 12Gb for 10 threads, the memory should not be a bottleneck.

**Comment by sschnug** [comment]
> > GLOP is memory intensive. I guess your computer is memory bandwidth bound.
> 
> from 64GB it uses only 12Gb for 10 threads, the memory should not be a bottleneck.

That's imho not whats meant by "memory-bound" here.

The question is how much memory needs to be read for doing x cycles of computation.
GLOP being memory intensive could mean, that some operation which is relatively cheap, e.g. an accumulation which would take 1 microsec without waiting for data, but needs to fetch 20MB of memory/data which might be much slower... 

Now one can sometimes recognize that something is compute bound (ALU work at cpu is bottleneck) or memory-bound (waiting for memory is bottleneck: e.g. well-optimized matrix-multiplication).

GLOP "seems" to be memory-bound or near that (lots of data is touched for relatively simple calculations) and issues related to that will get much more worse when you overcommit by parallel work as thread-scheduling will lead to cache-invalidation (and maybe less good prefetching) further worsening your memory-fetching.

As this is lots of guessing, one being interested should probably analyze this more by:
- Comparing low-bandwith systems (consumer cpus) with high-bandwith systems (server cpus with many memory-channels)
- Using valgrind or similar "simulation-based" tools
- Using CPU-supported profiling
  - Hardware-counter based analysis of cache-misses and co.

**Comment by gregy4** [comment]
For xeon cpu no need to guess, https://github.com/opcm/pcm gives information about bandwidth, cache-misses ... unfortunatelly for amd cpu probably nothing like that exists.
