### ISSUE TITLE
Can't get or-tools to build Windows 10

### ISSUE THREAD

**Issue by shmigy429** [google/or-tools#400]
Downloaded the source, got all the dependencies down (I think) and following the installation guide, get to running the command 'tools\make third_party' and start the build. Going smoothly till I get to building utilities_unittest.cc and I get a bunch of linking errors:

Trying to figure out if i'm doing something wrong here, tried multiple times with a fresh copy of source and get here dead in the water; Any ideas?

[ 62%] Linking CXX executable utilities_unittest.exe
utilities_unittest.cc.obj : error LNK2019: unresolved external symbol "public: __cdecl google::FlagSaver::FlagSaver(void)" (??0FlagSaver@google@@QEAA@XZ) referenced in function "public: static void __cdecl Test_utilities_InitGoogleLoggingDeathTest::Run(void)" (?Run@Test_utilities_InitGoogleLoggingDeathTest@@SAXXZ)
utilities_unittest.cc.obj : error LNK2019: unresolved external symbol "public: __cdecl google::FlagSaver::~FlagSaver(void)" (??1FlagSaver@google@@QEAA@XZ) referenced in function "public: static void __cdecl Test_utilities_InitGoogleLoggingDeathTest::Run(void)" (?Run@Test_utilities_InitGoogleLoggingDeathTest@@SAXXZ)
utilities_unittest.cc.obj : error LNK2019: unresolved external symbol "public: __cdecl google::FlagRegisterer::FlagRegisterer<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(char const *,char const *,char const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (??$?0V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@FlagRegisterer@google@@QEAA@PEBD00PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z) referenced in function "void __cdecl fLS::`dynamic initializer for 'o_test_srcdir''(void)" (??__Eo_test_srcdir@fLS@@YAXXZ)
glog.lib(logging.cc.obj) : error LNK2001: unresolved external symbol "public: __cdecl google::FlagRegisterer::FlagRegisterer<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(char const *,char const *,char const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (??$?0V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@FlagRegisterer@google@@QEAA@PEBD00PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z)
glog.lib(vlog_is_on.cc.obj) : error LNK2001: unresolved external symbol "public: __cdecl google::FlagRegisterer::FlagRegisterer<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(char const *,char const *,char const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (??$?0V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@FlagRegisterer@google@@QEAA@PEBD00PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z)
utilities_unittest.cc.obj : error LNK2019: unresolved external symbol "public: __cdecl google::FlagRegisterer::FlagRegisterer<bool>(char const *,char const *,char const *,bool *,bool *)" (??$?0_N@FlagRegisterer@google@@QEAA@PEBD00PEA_N1@Z) referenced in function "void __cdecl fLB::`dynamic initializer for 'o_run_benchmark''(void)" (??__Eo_run_benchmark@fLB@@YAXXZ)
glog.lib(logging.cc.obj) : error LNK2001: unresolved external symbol "public: __cdecl google::FlagRegisterer::FlagRegisterer<bool>(char const *,char const *,char const *,bool *,bool *)" (??$?0_N@FlagRegisterer@google@@QEAA@PEBD00PEA_N1@Z)
utilities_unittest.cc.obj : error LNK2019: unresolved external symbol "public: __cdecl google::FlagRegisterer::FlagRegisterer<int>(char const *,char const *,char const *,int *,int *)" (??$?0H@FlagRegisterer@google@@QEAA@PEBD00PEAH1@Z) referenced in function "void __cdecl fLI::`dynamic initializer for 'o_benchmark_iters''(void)" (??__Eo_benchmark_iters@fLI@@YAXXZ)
glog.lib(logging.cc.obj) : error LNK2001: unresolved external symbol "public: __cdecl google::FlagRegisterer::FlagRegisterer<int>(char const *,char const *,char const *,int *,int *)" (??$?0H@FlagRegisterer@google@@QEAA@PEBD00PEAH1@Z)
glog.lib(vlog_is_on.cc.obj) : error LNK2001: unresolved external symbol "public: __cdecl google::FlagRegisterer::FlagRegisterer<int>(char const *,char const *,char const *,int *,int *)" (??$?0H@FlagRegisterer@google@@QEAA@PEBD00PEAH1@Z)
C:\Program Files (x86)\gflags\Lib\gflags_static.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'
utilities_unittest.exe : fatal error LNK1120: 5 unresolved externals
LINK failed. with 1120
NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
make: *** [dependencies/install/include/glog/logging.h] Error 2

**Comment by lperron** [comment]
cmake is barely better than configure :-(

I will have a look at it.

Thanks for the report.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-06-02 16:49 GMT+02:00 shmigy429 <notifications@github.com>:

**Comment by lperron** [comment]
I just pushed a tentative fix.
Can you try it out?

--Laurent


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-06-02 17:05 GMT+02:00 Laurent Perron <lperron@google.com>:

**Comment by shmigy429** [comment]
Pulled it down and it fixed the linker errors, so 'third_party' was successful, thanks! 

Sadly, following the next step of 'tools\make cc' or 'tools\make test' I get another failure:

cl /EHsc /MD /nologo /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS -nologo  /O2 -DNDEBUG /I. /Iortools\\gen /IC:\\Users\\jac\\Downloads\\or-tools-master\\dependencies\\install\\include /DGFLAGS_DLL_DECL= /DGFLAGS_DLL_DECLARE_FLAG= /DGFLAGS_DLL_DEFINE_FLAG= /IC:\\Users\\jac\\Downloads\\or-tools-master\\dependencies\\install\\include  /IC:\\Users\\jac\\Downloads\\or-tools-master\\dependencies\\install\\include /I\\include /DGOOGLE_GLOG_DLL_DECL= /IC:\\Users\\jac\\Downloads\\or-tools-master\\dependencies\\install\\include /DUSE_CBC /IC:\\Users\\jac\\Downloads\\or-tools-master\\dependencies\\install\\include /DUSE_CLP    /DUSE_GLOP /DUSE_BOP /D__WIN32__   /DPSAPI_VERSION=1 /DARCH_K8 -c .\\ortools\\constraint_solver\\expressions.cc /Foobjs\\constraint_solver\\expressions.obj
expressions.cc
c:\users\jac\downloads\or-tools-master\ortools\constraint_solver\expressions.cc(4922) : fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 255)
 To work around this problem, try simplifying or changing the program near the locations listed above.
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information

INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
tools\make: *** [objs/constraint_solver/expressions.obj] Error 1 

Looking at this line its just defining a Min() function, not seeing anything glaringly wrong here...

**Comment by lperron** [comment]
This is a bug in the compiler.
Unfortunately, I could never reproduce it (I have visual studio 2015 pro edition).

You can do

tools\make objs/constraint_solver/expressions.obj DEBUG="/O1 /DNDEBUG"

then restart tools\make cc from there.

**Comment by shmigy429** [comment]
(VS 2015 Enterprise) Had to use:

'tools\make objs/constraint_solver/expressions.obj DEBUG="/Od -DNDEBUG"'

'tools\make cc' did its thing and 'tools\make test' got a:

"Or-tools have been built and tested for C++ , python , C#"

Whew, what an adventure...

Now to see if there are any fun defects to look into, thanks for the help!
