### ISSUE TITLE
Inconsistent MiniZinc statistics output between reports

### ISSUE THREAD

**Issue by zayenz** [google/or-tools#4000]
**What version of OR-Tools and what language are you using?**
Version: 9.8.3296 (bundled with MiniZinc 2.8.0)
Language: MiniZinc 2.8.0

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

CP-SAT with teh FlatZinc interface

**What operating system (Linux, Windows, ...) and version?**

Mac Sonoma

**What did you do?**

When I run a model in the MiniZinc IDE and I set the options to 
* Output solving statistics
* 10 threads for search (M1 Max)
* Free search

The statistics reported are seemingly inconsistent. For example, in an intermediate solution, the following statistics are reported
```
----------
%%%mzn-stat: boolVariables=1614
%%%mzn-stat: failures=0
%%%mzn-stat: objective=43
%%%mzn-stat: objectiveBound=45
%%%mzn-stat: propagations=0
%%%mzn-stat: solveTime=1.72833
%%%mzn-stat-end
```
For the optimal solution, the following statistics are reported
```
----------
%%%mzn-stat: boolVariables=1692
%%%mzn-stat: failures=53545
%%%mzn-stat: objective=44
%%%mzn-stat: objectiveBound=44
%%%mzn-stat: propagations=9834370
%%%mzn-stat: solveTime=2.98301
%%%mzn-stat-end
```
and at the end, the following statistics are reported
```
----------
==========
%%%mzn-stat: nSolutions=17
%%%mzn-stat-end
%%%mzn-stat: boolVariables=1614
%%%mzn-stat: failures=0
%%%mzn-stat: objective=44
%%%mzn-stat: objectiveBound=44
%%%mzn-stat: propagations=0
%%%mzn-stat: solveTime=3.02376
%%%mzn-stat-end
```

**What did you expect to see**

I would have expected the number of failures and propagations to be mostly monotonically increasing. At the very least, I would have expected the final output to have more failures and propagations reported than a previous set of statistics.

**What did you see instead?**

I am guessing that the reported statistics are for the portfolio asset that is used, and not global statistics. This makes it not very useful for understanding progress.

**Comment by lperron** [comment]
Intermediate solutions display the stats of the worker that finds the solution. So, no monotonicity between solutions. 

We need to  the final report.

**Comment by zayenz** [comment]
Ok. 

If it is possible, then perhaps adding a name/identifier for the solver that produces a certain solution would both make it clearer and provide easily accessible and valuable feedback.

**Comment by lperron** [comment]
Enable logging: -l
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
