### ISSUE TITLE
Typing is incorrect for `cp_model.CpModel.AddDecisionStrategy`

### ISSUE THREAD

**Issue by Dr-Irv** [google/or-tools#4001]
**What version of OR-Tools and what language are you using?**
Version:  9.8.3296
Language: Python 3.10.13

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
- Used the example `cp_sat_example.py` in Visual Studio Code
- Added the line `    model.AddDecisionStrategy([x, y, z], cp_model.CHOOSE_FIRST, cp_model.CHOOSE_LOWEST_MIN)`

Note that error also appears if you install command line pyright version 1.1.336

**What did you expect to see**
Not see a typing complaint from pyright:

**What did you see instead?**
```text
Argument of type "ValueType" cannot be assigned to parameter "var_strategy" of type "VariableSelectionStrategy" in function "AddDecisionStrategy"
  "ValueType" is incompatible with "VariableSelectionStrategy"
Argument of type "ValueType" cannot be assigned to parameter "domain_strategy" of type "DomainReductionStrategy" in function "AddDecisionStrategy"
  "ValueType" is incompatible with "DomainReductionStrategy"
```

My hunch here is that your PYI files for the enumerated types are incorrect.

**Comment by lperron** [comment]
Thanks, we will have a look.

**Comment by lperron** [comment]
Fixed in the code.
