### ISSUE TITLE
const correctness in CpModelBuilder

### ISSUE THREAD

**Issue by ozan-cb** [google/or-tools#4005]
**What language and solver does this apply to?**
C++, CP-SAT

**Describe the problem you are trying to solve.**
`CpModelBuilder::Get*VarFromProto` functions are not const: https://github.com/google/or-tools/blob/stable/ortools/sat/cp_model.h#L1104

I use these functions to extract a solution value for the start/end/presence variables of intervals from a response. Without const-correctness I need to pass a non-const `CpModelBuilder` around, which is essentially "constant" after solving (or store all the variable components of interval variables to prevent the need of accessing them through these `Get*VarFromProto` functions).

**Describe the solution you'd like**
This is only a very minor nuisance, but it would be good if they can be made const.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lperron** [comment]
Infeasible.

GetVarFromProto calls Var(index, builder_ptr); and stores the builder in the builder_ field.
But this field cannot be const as there are setters on the Var class.
