### ISSUE TITLE
Add Gurobi version 11 (and other minor versions)

### ISSUE THREAD

**Issue by torressa** [google/or-tools#4008]
**Describe the solution you'd like**

Gurobi 11 has been released so it would be good to add it to the list of Gurobi versions.
Additionally, a few minor versions are missing.

```diff
--- a/ortools/gurobi/environment.cc
+++ b/ortools/gurobi/environment.cc
@@ -342,9 +342,9 @@ void LoadGurobiFunctions(DynamicLibrary* gurobi_dynamic_library) {

 std::vector<std::string> GurobiDynamicLibraryPotentialPaths() {
   std::vector<std::string> potential_paths;
-  const std::vector<std::string> kGurobiVersions = {"1000", "952", "951", "950",
-                                                    "911",  "910", "903", "902",
-                                                    "811",  "801", "752"};
+  const std::vector<std::string> kGurobiVersions = {
+      "1100", "1003", "1002", "1001", "1000", "952", "951", "950",
+      "911",  "910",  "903",  "902",  "811",  "801", "752"};

```

There are a few new parameters for this version so the header (`ortools/gurobi/environment.h`) also needs updating but I can't find the `parse_headers.py` file mentioned in [ortools/gurobi/environment.h#L58](https://github.com/google/or-tools/blob/stable/ortools/gurobi/environment.h#L58C1-L58C1)

**Comment by lperron** [comment]
of course, next release.
You can setup the path manually to the shared library.

**Comment by Mizux** [comment]
https://github.com/google/or-tools/commit/aab1514a4eda4511fee1d6faf190aa74edfec1c8
