### ISSUE TITLE
Infeasible LNS solution! graph_dec_lns (d=0.97 s=575 t=0.10 p=0.61 stall=32 h=folio_rnd)

### ISSUE THREAD

**Issue by disonvon** [google/or-tools#4013]
**What version of OR-Tools and what language are you using?**
Version: 9.8.3296
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT
**What operating system (Linux, Windows, ...) and version?**
Linux
**What did you do?**
solve the model, and i will get the following error:
Infeasible LNS solution! graph_dec_lns (d=0.97 s=575 t=0.10 p=0.61 stall=32 h=folio_rnd) [hint] solved with params max_time_in_seconds: 120
max_memory_in_mb: 3072
log_search_progress: false
max_deterministic_time: 0.1
search_branching: PORTFOLIO_SEARCH
cp_model_presolve: true
stop_after_first_solution: false
num_search_workers: 12
search_random_variable_pool_size: 5
cp_model_probing_level: 0
symmetry_level: 0
log_to_stdout: false
solution_pool_size: 1
num_workers: 12
find_big_linear_overlap: false

*** Check failure stack trace: ***

I got the above error randomly on the server, but i cannot reproduce it with the same model file locally. 
Any ideas to handle this?
the model file are attached below. 
If you need more info, please let me know. 
[Uploading model.pd.txt…]()

**Comment by disonvon** [comment]
[Uploading model.pd.txt…]()

**Comment by lperron** [comment]
the model is not attached

**Comment by disonvon** [comment]
[model.pd.txt](https://github.com/google/or-tools/files/13560032/model.pd.txt)

**Comment by disonvon** [comment]
it seems I didn't upload the model successfully, uploaded it again. Thanks

**Comment by lperron** [comment]
OK, I can reproduce it. 
We will debug it.
