### ISSUE TITLE
Converge customized abseil-logging with upstream vlog-enriched abseil-logging

### ISSUE THREAD

**Issue by sschnug** [google/or-tools#4028]
Afaik or-tools introduced some customized logging due to GLOG deprecation and the then-available abseil-logging did not support `VLOG` which is heavily used.

Abseil now contains VLOG support on it's master branch it seems:

- https://github.com/abseil/abseil-cpp/commit/7b6c17e378224844d8663a410da2da5353b205b9

Some background on their repo:

- https://github.com/abseil/abseil-cpp/discussions/1343
- https://github.com/abseil/abseil-cpp/issues/1579

As the whole GLOG/Abseil-Logging/Abseil-Logging-Customization situation has been sometimes an issue for some users (when combining or-tools with other big libraries) it should make sense to fully adopt abseil.

_As there is no release yet with those changes, this ticket might be more of a near-future feature-request / reminder._

It seems you guys did intend to do it anyway as seen in https://github.com/google/or-tools/issues/3298 :

> At this point, I will close the bug as the way forward is just to wait for vlog to be implemented in abseil to remove our code.

**Comment by Mizux** [comment]
Still need/wait for a release but good to know is coming !

ref: https://github.com/abseil/abseil-cpp/releases
