### ISSUE TITLE
Zero-crossing linear expressions in addMultiplicationEquality yield infeasible solution unless using intermediate variables

### ISSUE THREAD

**Issue by eyaler** [google/or-tools#4031]
Version: 9.4 and 9.7
Language: Python
CP-SAT
Windows 11 64

I get infeasible solution when using zero-crossing linear expressions directly in addMultiplicationEquality, although they work fine if i use intermediate variables.

The issue can be easily recreated by changing https://github.com/google/or-tools/blob/8768ed7a43f8899848effb71295a790f3ecbe2f2/examples/python/spread_robots_sat.py#L78 to:

`model.AddMultiplicationEquality(x_diff_sq, x[i] - x[j], x_diff)`

This is just a minimal change to show the issue, my original motivation was to not require the intermediate x_diff, y_diff at all.

Wild guess: maybe this is a manifestation of https://github.com/google/or-tools/issues/2133 where the cross-zero logic is not inferred when taking the difference of positive variables?

**Comment by lperron** [comment]
Can you check with 9.8?

**Comment by lperron** [comment]
You do not get infeasible, you get invalid. 
As documented, it accepts arguments of the form a*x + b, not general linear expressions.

**Comment by eyaler** [comment]
thanks! i could not find this limitation in the docs. could you kindly point me out?
I've only seen `*expressions: simple expressions of the form a * var + constant.` for AddAllDifferent
otherwise the docs give x + 2 * (y - z + 1) as an example for LinearExpr
which functions take a general linear expression and which take a univariate one?
could we have these function explicitly validate instead of failing silently?
could we have a dedicated type annotation?
