### ISSUE TITLE
ORTools installs without pywrapinit

### ISSUE THREAD

**Issue by Tom-lister** [google/or-tools#4039]
**What version of OR-Tools and what language are you using?**
Version: 9.8.3296
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
n/a

**What operating system (Linux, Windows, ...) and version?**
Windows 11

**What did you do?**
1. Installed Microsoft Visual Studio 2022
2. Installer ORTools using "python3 -m pip install -U --user ortools" in Command Prompt
3. Downloaded the python example code
4. Opened and ran the python example code using Visual Studio
5. Error on line 18:
```
cannot import name 'pywrapinit' from 'ortools.init' (C:\Users\thesu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python\site-packages\ortools\init\__init__.py)"
```

**What did you expect to see?**
The example code should run, and there should be some reference to 'pywrapinit' in the ortools\init folder

**What did you see instead?**
The code did not run, __init__.py is blank, and there is no file or folder named 'pywrapinit' anywhere in the installation folder

**Comment by lperron** [comment]
I switched to pybind11. The module is called init now.

**Comment by lperron** [comment]
from ortools.*init*.python import *init*
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by Tom-lister** [comment]
Thank you. This results in another error on line 68:
```
type object 'ortools.init.python.init.CppBridge' has no attribute 'InitLogging'
```

Is the basic_example.py file just out of date?

**Comment by lperron** [comment]
which example ?

Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by Tom-lister** [comment]
The example stored in [this repository](https://github.com/or-tools/python_or-tools) and referenced in the [installation guide](https://developers.google.com/optimization/install/python/pkg_windows).

**Comment by lperron** [comment]
https://github.com/google/or-tools/blob/stable/ortools/init/python/init_test.py

tests all APIs.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by lperron** [comment]
it does not contain a pywrapinit


Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by Tom-lister** [comment]
Thank you. If the previous example is out-of-date, perhaps it should be removed from the installation guide?

**Comment by lperron** [comment]
the example works fine.
I just checked out python-or-tools, ran it with the or-tools 9.8

Number of variables = 2

Number of constraints = 1

Solution:

Objective value = 4.0

x = 1.0

y = 1.0
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by Tom-lister** [comment]
That is odd. So your or-tools 9.8 installed with pywrapinit?

**Comment by lperron** [comment]
Look at the code:

https://github.com/or-tools/python_or-tools/blob/main/basic_example.py

it does not contain pywrapinit

Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by lperron** [comment]
did you update python_or-tools ?

Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by Tom-lister** [comment]
I have identified the problem. On [this page](https://developers.google.com/optimization/install/python/pkg_windows), under 'Get the Python example code', the link to the repo works as intended.

However, it is accompanied by another link titled 'Download the repo as a zip file', which downloads (presumably) an earlier, outdated version of the repo. This link should be updated.

**Comment by Mizux** [comment]
> I have identified the problem. On [this page](https://developers.google.com/optimization/install/python/pkg_windows), under 'Get the Python example code', the link to the repo works as intended.
> 
> However, it is accompanied by another link titled 'Download the repo as a zip file', which downloads (presumably) an earlier, outdated version of the repo. This link should be updated.

Good catch the zip point to the v9.5 archive... on my way to fix it...
