### ISSUE TITLE
cmake-build fails on Windows 10/ VS Community 2022

### ISSUE THREAD

**Issue by Tombox2018** [google/or-tools#4044]
Version: main/v9.8.

Language: C++ (Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.8.3)
cmake version 3.28.0-rc4

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows [Version 10.0.19045.3803]

**What did you do?**
I tried to build the or-tools C++ libraries following the instructions on https://developers.google.com/optimization/install/cpp/source_windows
I used the following commands (with folder \build2):

1. **cmake -S . -B build2 -DUSE_SCIP=OFF -DBUILD_SAMPLES=ON -DBUILD_DEPS=ON**
That worked fine: cmake downloaded all the dependencies including the protobuf compiler (version number libprotoc 25.1)

2. **cmake --build build2 --config Release --target ALL_BUILD -j -v**
That worked until the ortools_proto subproject. Albeit, the first step compiling the .proto files worked:
         Generate C++ protocol buffer for ortools/bop/bop_parameters.proto
         Generate C++ protocol buffer for ortools/constraint_solver/assignment.proto
         ...
         Generate C++ protocol buffer for ortools/pdlp/solvers.proto
         Generate C++ protocol buffer for ortools/gscip/gscip.proto

The subsequent C++ compilation step first generated several hundreds of errors of the four following types, ranging over all .pb.cc files:

or-tools-9.8\build2\ortools\sat\cp_model.pb.cc(896,5): error C2248: 'operations_research::sat::RoutesConstraintProto::_impl_': cannot access private member declared in class 'operations_research::sat::RoutesConstraintProto' [.\or-tools-9.8\build\ortools_proto.vcxproj]

.\or-tools-9.8\build2\ortools\sat\cp_model.pb.cc(840,5): error C2248: 'google::protobuf::MessageLite::_internal_metadata_': cannot access protected member declared in class 'google::protobuf::MessageLite' [.\or-tools-9.8\build2\ortools_proto.vcxproj]

.\or-tools-9.8\build2\ortools\sat\sat_parameters.pb.cc(282,18): error C2653: 'TableStruct_ortools_2fsat_2fsat_5fparameters_2eproto': is not a class or namespace name [.\or-tools-9.8\build2\ortools_proto.vcxproj]

.\or-tools-9.8\build2\ortools\sat\cp_model_service.pb.cc(92,45): error C2737: 'descriptor_table_ortools_2fsat_2fcp_5fmodel_5fservice_2eproto_deps': const object must be initialized [.\or-tools-9.8\build2\ortools_proto.vcxproj]

Consequently, no ortools.lib was generated under build2\RELEASE\bin

IMHO it's not a problem with or-tools per se, but with the code generated by the protoc compiler.

Alternativly, I also used the ortools.sln with the Visual Studio IDE, with the same error messages.

What could I possibly try? Any help is appreciated!

**Comment by lperron** [comment]
Bizarre, it works on github actions: https://github.com/google/or-tools/actions/runs/7409655688

**Comment by arnabadas** [comment]
In MSVC Community 2022 v17.8.3, or-tools 9.8.3649 (Python) built fine on Windows 10 x64 Pro 22H2 (19045.3803) without any issues.

**Comment by Mizux** [comment]
> In MSVC Community 2022 v17.8.3, or-tools 9.8.3649 (Python) built fine on Windows 10 x64 Pro 22H2 (19045.3803) without any issues.
> 
> Though math-opt did not work via python even though examples are already out there in the ortools guide. Did not have time to investigate and manually link additional libraries.

About mathopt currently only bazel based build support it while the python packaging stuff is only available on the CMake based build.
On my way to integrate math_opt python in cmake based build thus should be available in the next release

**Comment by lperron** [comment]
Any progress ? 

As I said, works fine on our github runners. check your environment.
