### ISSUE TITLE
use or-tools in a project

### ISSUE THREAD

**Issue by flyover-26** [google/or-tools#4050]
cmake version 3.17
g++ version:7.5.0
 or-tools Version: v9.1
Language: C++
**What operating system (Linux, Windows, ...) and version?**
linux18.04

hi!I download or-tools with cmake.And it can run test demo well.
However,when i want to use it in a project,it give me error below:

  Add the installation prefix of "Protobuf" to CMAKE_PREFIX_PATH or set
  "Protobuf_DIR" to a directory containing one of the above files.  If
  "Protobuf" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  /home/zr/software/or-tools-9.1/my_instal/lib/cmake/ortools/ortoolsConfig.cmake:35 (find_dependency)
  CMakeLists.txt:27 (find_package)

it seems that it can not find these dependecy,it can not find scip either.
My cmakelists shows below:

 cmake_minimum_required(VERSION 3.14)
project(myproj VERSION 1.0)

set(ortools_DIR "/home/zr/software/or-tools-9.1/my_instal/lib/cmake/ortools")
find_package(ortools CONFIG REQUIRED)

add_executable(myapp main.cpp)
target_link_libraries(myapp ortools::ortools)

**Comment by lperron** [comment]
bump to 9.8.
