### ISSUE TITLE
Solving the max flow problem failed

### ISSUE THREAD

**Issue by flyover-26** [google/or-tools#4051]
or-tools version 9.1
ubuntu 18.04

I run Maximum Flows example following or-tools guide.Howerver ,the result is not good as below:

I0115 17:11:32.286363 29150 main.cpp:37] Solving the max flow problem failed. Solver status: 0

it seems it can not solve the result.
Minimum Cost Flows example run well and get the same result with or-tools guide.

My cmakelist is below:

```cmake
cmake_minimum_required(VERSION 3.17)
project(orTools)
set(CMAKE_CXX_STANDARD 20)
# Build OR-tools dependencies.
set(BUILD_DEPS ON)
# Disable SCIP solver.
include(FetchContent)
set(FETCHCONTENT_QUIET OFF)
set(FETCHCONTENT_BASE_DIR ${_deps})
FetchContent_Declare(
        or-tools
        GIT_REPOSITORY https://github.com/google/or-tools.git
        GIT_TAG v9.1
)
FetchContent_MakeAvailable(or-tools)
add_executable(orTools main.cpp)
target_link_libraries(orTools ortools::ortools)
```

**Comment by lperron** [comment]
Can you try with 9.8. we do note support/patch older versions.

**Comment by lperron** [comment]
Please reopen if the problem still exists in 9.8
