### ISSUE TITLE
RuntimeError('Unrecognized new version of ortools (9.8.3296). Expected < 9.8.0. Please open a feature request on cvxpy to enable support for this version.')

### ISSUE THREAD

**Issue by sbrownjngroup** [google/or-tools#4052]
(CVXPY) Jan 15 12:41:11 PM: Encountered unexpected exception importing solver GLOP:
RuntimeError('Unrecognized new version of ortools (9.8.3296). Expected < 9.8.0. Please open a feature request on cvxpy to enable support for this version.')
(CVXPY) Jan 15 12:41:11 PM: Encountered unexpected exception importing solver PDLP:
RuntimeError('Unrecognized new version of ortools (9.8.3296). Expected < 9.8.0. Please open a feature request on cvxpy to enable support for this version.')

**Comment by lperron** [comment]
blocked on https://github.com/cvxpy/cvxpy/pull/2316#issuecomment-1882792870

**Comment by lperron** [comment]
I believe this is fixed.
