### ISSUE TITLE
Python builds are failing in the current `main` branch

### ISSUE THREAD

**Issue by arnabadas** [google/or-tools#4054]
**What version of OR-Tools and what language are you using?**
Version: main
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
NA

**What operating system (Linux, Windows, ...) and version?**
Windows

**What did you do?**
Check the github runner: [Link](https://github.com/google/or-tools/actions/runs/7538213570/job/20518392730)

**What did you expect to see**
Successful build

**What did you see instead?**
Error

**Anything else we should know about your project / environment**
Everything is mentioned in the linked github run. Also it is not a Windows specific issue.

**Comment by lperron** [comment]
We know
