### ISSUE TITLE
Building from source OR-Tools C++ on Windows generates "Internal compilation error" at build

### ISSUE THREAD

**Issue by sarafrim** [google/or-tools#4055]
**What version of OR-Tools and what language are you using?**
Version: stable 
Language: C++

**What operating system and version?**
Windows10
Microsoft Visual Studio Enterprise 2022
CMake 3.28.1. 
x64 Native Tools Command Prompt for VS 2022

**What did you do?**
1. Download the source code by cloning from git: `git clone https://github.com/google/or-tools`
3. Configure the build: `cmake -S . -B build -DBUILD_DEPS=ON`
4. Build the source code: `cmake --build build --config Release --target ALL_BUILD -j -v`

**What did you expect to see**
Successful build.

**What did you see instead?**
Internal compiler error:
```
"C:\git\or-tools\build\ALL_BUILD.vcxproj" (default target) (1) ->
       "C:\git\or-tools\build\ortools\sat\samples\assignment_teams_sat.vcxproj" (default target) (58) ->
       "C:\git\or-tools\build\ortools.vcxproj" (default target) (94) ->
       "C:\git\or-tools\build\ortools\glop\ortools_glop.vcxproj" (default target) (244) ->
       (ClCompile target) ->
         C:\git\or-tools\build\_deps\absl-src\absl\container\internal\compressed_tuple.h(75): fatal  error C1001: Internal compiler error. [C:\git\or-tools\build\ortools\glop\ortools_glop.vcxproj]
         cl : command line  error D8040: error creating or communicating with child process [C:\git\or-tools\build\ortools\glop\ortools_glop.vcxproj]

    18 Warning(s)
    2 Error(s)
```

**Comment by lperron** [comment]
It is a visual studio bug.
Try different vs 2022 patches. It comes and go with versions.
