### ISSUE TITLE
How IntExpr().Var() affect the search process.

### ISSUE THREAD

**Issue by hlee13** [google/or-tools#4061]
Version: v9.6.
Language: java

**Which solver are you using **
Routing Solver

What is the difference between IntExpr().Var().setMax(upperBound) and IntExpr().setMax(upperBound), in my case, IntExpr().Var().setMax(upperBound) resulted in no solution, but IntExpr( ).setMax(upperBound) has a solution

How IntExpr().Var() affect the search process.

**Comment by lperron** [comment]
Not an issue
