### ISSUE TITLE
AddNoverlap2D does not work with OnlyEnforceIf

### ISSUE THREAD

**Issue by MatteoMagnani95** [google/or-tools#4064]
**Version: v9.6.
Language: Python**

**CP-SAT**

**Windows11**

I am modeling a **3D bin packing problem** with constraints from a real-world application. I am attempting to solve the problem using a **layerized** strategy. Specifically, I need to solve a **2D bin packing** problem along with variables that indicate whether a box is loaded on a specific layer on a specific pallet (b_{i,l,p} = 1 if box i is loaded on layer l on pallet p, 0 otherwise) and with the possibility that box i can be **rotated**. In practice, I would impose the **2D NoOverlapping constraints** only on those rectangles representing boxes loaded on the same layer on the same pallet.
I am trying to use CP and OR-tools to solve the MILP, but I am encountering difficulties with the 2D constraints on layers, particularly with the AddNoOverlap2D constraints.

**_Is there a way to model the NoOverlap2D constraint along with the OnlyEnforceIf constraint?_**

In particular, I would like to have something like this:

```python
xl = [model.NewIntVarFromDomain(cp_model.Domain.FromIntervals([[0, 0], [length[i], length[i]]]), f"xw{i}") for i in range(n)]
yw = [model.NewIntVarFromDomain(cp_model.Domain.FromIntervals([[0, 0], [width[i], width[i]]]), f"yl{i}") for i in range(n)]

# interval variables
X_interval = [model.NewIntervalVar(x1[i], xl[i], x2[i], f"xival{i}") for i in range(n)]
Y_interval = [model.NewIntervalVar(y1[i], yw[i], y2[i], f"yival{i}") for i in range(n)]

model.AddNoOverlap2D(X_interval[i], Y_interval[i]).OnlyEnforceIf(b[i,l,p] == 1)
```
Alternatively, I considered a solution integrating the OptionalIntervalVar (but it is still not working):

```python
xl = [model.NewIntVarFromDomain(cp_model.Domain.FromIntervals([[0, 0], [length[i], length[i]]]), f"xw{i}") for i in range(n)]
yw = [model.NewIntVarFromDomain(cp_model.Domain.FromIntervals([[0, 0], [width[i], width[i]]]), f"yl{i}") for i in range(n)]

# optional interval variables
X_OPT_interval = [model.OptionalIntervalVar(x1[i], xl[i], x2[i], b[i,l,p] == 1) for i in range(n)]
Y_OPT_interval = [model.OptionalIntervalVar(y1[i], yw[i], y2[i], b[i,l,p] == 1) for i in range(n)]

model.AddNoOverlap2D(X_OPT_interval[i], Y_OPT_interval[i])
```

Moreover, I would like to introduce the possibility for rectangles to rotate by 90°.

**Comment by Mizux** [comment]
Did you take a look at ?
https://github.com/MrBenGriffin/or-tools-fun?tab=readme-ov-file#polycube-puzzle-solver

**Comment by lperron** [comment]
Yes. But you can make the rectangles optional. 

This is not planned.
