### ISSUE TITLE
Support for Gurobi v11

### ISSUE THREAD

**Issue by venaturum** [google/or-tools#4071]
It appears that the versions of Gurobi that OR-TOOLS will search for do not include the latest release V11

https://github.com/google/or-tools/blob/d37317b17ca16658451cafe05085fc22c39dd6c8/ortools/gurobi/environment.cc#L321

Is there someway to force OR-TOOLS to use a library from v11?  Or is an update to this project required?

**Comment by lperron** [comment]
Already asked. 
You can specify a path to the shared library in the search ortools/init module.

**Comment by venaturum** [comment]
Thank you, and sorry for not noticing the prior issue.  


> You can specify a path to the shared library in the search ortools/init module.

Can you give more details on this?  I tried the following in the java source code and it failed with java.lang.UnsatisfiedLinkError

```
import com.google.ortools.init.CppBridge;

CppBridge.logGurobiSharedLibrary("/Library/gurobi1100/macos_universal2/lib/libgurobi110.dylib");
```

**Comment by Mizux** [comment]
also alreqady patched on `main` branch, ready for next release ;)
https://github.com/google/or-tools/blob/ab64c92906597601fd2360f17e247caf43411c9c/ortools/gurobi/environment.cc#L345-L347

**Comment by venaturum** [comment]
Turns out 

```
CppBridge.logGurobiSharedLibrary("/Library/gurobi1100/macos_universal2/lib/libgurobi110.dylib");
```
does work, but needs to come after
```
Loader.loadNativeLibraries();
```
not before.
