### ISSUE TITLE
Build error: patch for pybind11_protobuf is outdated

### ISSUE THREAD

**Issue by mb64** [google/or-tools#4075]
On all recent releases and current main, the patch file `patches/pybind11_protobuf.patch` is outdated.

It removes a conditional in the `PyProtoIsCompatible` function in `pybind11_protobuf/proto_cast_util.cc` which is already removed in upstream as of a couple months ago: see https://github.com/pybind/pybind11_protobuf/commit/8359a091a9b0bc7deb0233de986c06c885a3ff2d.

Concretely, when trying to build the Python tool set, it results in this error:

```
[ 44%] Performing patch_disconnected step for 'pybind11_protobuf-populate'
error: patch failed: pybind11_protobuf/proto_cast_util.cc:599
error: pybind11_protobuf/proto_cast_util.cc: patch does not apply
make[2]: *** [CMakeFiles/pybind11_protobuf-populate.dir/build.make:115: pybind11_protobuf-populate-prefix/src/pybind11_protobuf-populate-stamp/pybind11_protobuf-populate-patch_disconnected] Error 1
```

**Comment by lperron** [comment]
Which version? I believe this is fixed on main.

**Comment by mb64** [comment]
Ah you are right! I thought I checked main, but I only looked at the stable branch. (I ran into the issue with the 9.7 and 9.8 release tarballs.) Sorry for the mistake!

Feel free to close.
