### ISSUE TITLE
OR-Tools Arm64 Ubuntu 22.04 LTS for Java

### ISSUE THREAD

**Issue by ffays** [google/or-tools#4082]
Would it be possible to provide a compiled version of the latest OR-Tools release for **Arm64** architecture for at least the latest Long Term Support version of Ubuntu (22.04), for Java (and possibly other  language bindings)?

I'm currently using a Macbook silicon (i.e. aarch64) and I would like to put OR-Tools in a Docker image based on Ubuntu 22.04 LTS.

I guess this packaging might be used for other platforms with Arm64 architecture, e.g. Ampere servers and Raspberry Pi 5.

Thank you.

**Comment by Mizux** [comment]
Will try to see if it possible, by the way you should be able to build your own release, since I try hard to make all our release script agnostic of our internal infra.

Everything is in tools/docker

```sh
# check your docker support
docker buildx ls
# add docker qemu support on x86_64
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx ls

cd tools/docker
# get Usage
make

# Build arm64 release using docker/qemu
make arm64_ubuntu-22.04_cpp_export 
# note: should take ~1hour on apple and 5h on x86_64 host
```
You should have your package/archive in export/

ref: https://github.com/google/or-tools/blob/stable/tools/docker/README.md

**Comment by Mizux** [comment]
Note: For Java, .Net and Python we already publish package which support manylinux arm64 target...

ref:
* https://www.nuget.org/packages/Google.OrTools/#dependencies-body-tab
* https://mvnrepository.com/artifact/com.google.ortools/ortools-java/9.8.3296
* https://pypi.org/project/ortools/9.8.3296/#files

**Comment by ffays** [comment]
Good to know, I've to admit I didn't not explored the Maven repository
