### ISSUE TITLE
Cancellations of IntVar in IntExpr for Constraint Solver

### ISSUE THREAD

**Issue by keithyipkw** [google/or-tools#409]
The speeds of using one of the following expressions are wildly different
```
expr1 = var1 - var2 - 1;
solver.Add(expr1 == 10);
```
```
expr2 = varX + 10 - varX - 11 + var1 - var2;
solver.Add(expr2 == 10);
```
Using them in my more complex problem, the first one runs less than 5s but the second one runs 45min. It seems that the solver does not cancel/merge/collapse the redundent variables. Is it by design (varX is not redundent) or a missing feature?

**Comment by lperron** [comment]
Indeed, when I first designed the CP solver, I wanted it to be minimal and straightforward.
Later, when working on the minizinc challenge, I realized the importance of presolve and did a lot on that subject. But I agree it is inconsistent.

Now, if you look at the cp_model.proto in the sat/ directory, you will find our latest solver. It contains all the bells and whistle.

Unfortunately, the API is rough and should benefit from nice helpers, especially in python.

**Comment by keithyipkw** [comment]
While testing different representations of my problem, I noticed that if there were more than 2 variables in some of the constraints, the computational time changed from 1 minute to 1 hour. For example,

```
var t1, t2
t1 <= t2 

// became

var t1, delay2
t2 = t1 + delay2
```
```
(((end (0, 16)(0..45324) + -(start (0, 18)(0..45324))) + 20) <= 0)
(((-(end (0, 14)(0..45324)) + start (0, 18)(0..45324)) + -1181) <= 0)

// became

TrueConstraint()
((((end (0, 16)(0..45324) + -(end (0, 14)(0..45324))) + delay (0, 18)(0..45324)) + -1161) <= 0)
```

I have tried adding a phase for the delay variables but the computations were so long that I terminated it. Is this problem the same as the redundant variables?

**Comment by lperron** [comment]
Yes, we do some simplification along the way. But the objects are already created in your example, so we use them.

The CP-SAT is now fully mature, and is recommended over the CP solver.
And it implementes variable simplification.
