### ISSUE TITLE
`AddCumulative` `demands` argument has inconsistency between types and docs

### ISSUE THREAD

**Issue by Dr-Irv** [google/or-tools#4093]
**What version of OR-Tools and what language are you using?**
Version: 9.8.3296
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10

The docs https://or-tools.github.io/docs/pdoc/ortools/sat/python/cp_model.html#CpModel.AddCumulative for `AddCumulative` say this:
```python
def AddCumulative(
	self,
	intervals: Iterable[IntervalVar],
	demands: Iterable[Union[LinearExpr, IntVar, numbers.Integral, numpy.integer, int]],
	capacity: Union[LinearExpr, IntVar, numbers.Integral, numpy.integer, int]
) -> Constraint:
```
with the text description saying:
```text
demands: The list of demands for each interval. Each demand must be >= 0. Each demand can be an integer value, or an integer variable.
```
I have a complex code where we used a linear expression for the demands, and CP-SAT generated a solution that is not feasible.  I used a linear expression based on the typing description for the demands.  I think it should be
```python
demands: Iterable[Union[IntVar, numbers.Integral, numpy.integer, int]],
```
i.e., based on the verbal description a `LinearExpr` should not be allowed as a component of `demands`

Which is correct, the verbal or the typing?

If the verbal description is correct, then the typing should be updated in the docs as well as in the code.
If the typing description is correct, then the verbal description should be updated in the docs and the code.

My hunch right now is that the verbal description is correct.  It would be really hard to give a test case where using any linear expression is correct based on our code, because it takes over 2.5 hours to generate a solution, and CP-SAT is non-deterministic.

**Comment by Mizux** [comment]
v9.8
https://github.com/google/or-tools/blob/43e400c4f2749268d6a53d39be8f019906fd19c9/ortools/sat/python/cp_model.py#L2392-L2397

v9.9/main
https://github.com/google/or-tools/blob/34c2f6179dcfe4c1dca5c30d869ca1cdcec636ac/ortools/sat/python/cp_model.py#L2994
https://github.com/google/or-tools/blob/34c2f6179dcfe4c1dca5c30d869ca1cdcec636ac/ortools/sat/python/cp_model.py#L2625-L2630

**Comment by lperron** [comment]
as with all the API, the code accepts 1 var affine expressions: a * x + b

**Comment by Dr-Irv** [comment]
> as with all the API, the code accepts 1 var affine expressions: a * x + b

So that means the verbal description is wrong, but it also means there is a bug in CP-SAT, because I have a case where it generates a solution, and if I fix all the variables to that solution, presolve says it  is infeasible (which is correct).

I'm going to change our code to not use the 1 var affine expression.

**Comment by lperron** [comment]
I use 1-var affine expressions all the time.

**Comment by lperron** [comment]
Can you send me a faulty code?

**Comment by lperron** [comment]
https://github.com/google/or-tools/commit/eb4e996cf3d3da786ab3c09bab04ba6ff98f5d67

**Comment by Dr-Irv** [comment]
> Can you send me a faulty code?

Not easily.  The particular project has over 12,000 lines of code, of which about a third are the solver, another third is data preparation, and another third are utilities.  

The case that failed involved a huge dataset that created a problem with about 350,000 variables, over 1,000,000 constraints.  A set of sequential solves using a hierarchical objective were done.  After the 11th solve, a number of variables were fixed from that solution, and the 12th solve became infeasible.  It takes almost 3 hours on 32 CPUs to get to that point, and we don't even know if the non-deterministic nature of the solver would produce the infeasible solution after 11 solves.

The expressions were all of the form `1 - boolean_var`, so I am doing a test with `boolean_var.Not()` to see if that works.

**Comment by Dr-Irv** [comment]
> The expressions were all of the form `1 - boolean_var`, so I am doing a test with `boolean_var.Not()` to see if that works.

That also failed.  However, it failed on a different test set, so it seems that it is hard to reproduce due to the non-deterministic nature of the solver.

When I created a new variable `rev_boolean_var` and added the constraint `rev_boolean_var == 1 - boolean_var`, all of our tests passed.  So either we were lucky and avoided the bug, or there is a real bug when using an affine expression as the demands in the `AddCumulative` constraint.

We're on a paid contract here, and we don't have budget to create a test case for you that illustrates the problem.  If it turns out that we are unlucky, and a test fails in the future due to the same issue, then we'll discuss with our client getting budget to create a test case for you to investigate.

**Comment by lperron** [comment]
We have fixed a bug recently.

Worth trying the main branch.

Le mer. 21 févr. 2024, 23:24, Irv Lustig ***@***.***> a
écrit :

**Comment by Dr-Irv** [comment]
> We have fixed a bug recently. Worth trying the main branch.

Well, that's not so easy, because building OR Tools seems to be non-trivial because it requires a compiler, etc.  Do you publish binaries of the main branch prior to release on `pypi` ?
