### ISSUE TITLE
Upstream abseil now has logging

### ISSUE THREAD

**Issue by grebe** [google/or-tools#4094]
**What language and solver does this apply to?**
C++

**Describe the problem you are trying to solve.**
Abseil has released logging (see [20240116.1](https://github.com/abseil/abseil-cpp/releases/tag/20240116.1) which adds `VLOG`) which leads to conflicts w/ the logging support in this repo. There are macro redefinition errors and linker errors from duplicated flags.

**Describe the solution you'd like**
Ideally there'd be some sort of feature detection so that old abseil versions would still work.

**Describe alternatives you've considered**
If it's OK to drop support for old abseils, then it could be simpler just to rip out the or-tools logging and move over to abseil logging.

**Comment by lperron** [comment]
I do not see how not to be in lockstep with abseil code. 
There are so many subtle bugs.

We do not have the resource to to all the patches.

Note that we already ripped out OR-Tools logging.

**Comment by Mizux** [comment]
we do our best to target the last abseil-cpp release, so each time abseil-cpp finaly release a new feature then we remove our mock...

Out of curiosity did you use `main` branch ?

**Comment by grebe** [comment]
Ah, my bad. I was building a project that depends on an older release of or-tools and when I went to github to see if the logging stuff was still present, I didn't realize I was looking at the stable branch. Sorry for the confusion!
