### ISSUE TITLE
"Infeasible LNS solution" on CP-SAT model

### ISSUE THREAD

**Issue by ltsstar** [google/or-tools#4099]
**What version of OR-Tools and what language are you using?**
Version: main (9.9.3883) and 9.8.3309
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Linux, Fedora 39

**What did you do?**
I am running a simulation that sequentially creates scheduling models and calls the solve function.
I have been running the same script simultaneously on 18 older Intel i7-4765T CPUs for a week without an error, but when I run the same script on any of two AMD Ryzen 9 7950X3D CPUs, after thousands of times of successfully solving the models, the script crashes eventually (after a few hours) with the error message: "Infeasible LNS solution".

[model.pd.txt](https://github.com/google/or-tools/files/14379019/model.pd.txt)

**Comment by lperron** [comment]
Which parameters do you use ?
How many cores both you machines have ? (the old and the new one)

**Comment by ltsstar** [comment]
You can see the models code here: [](https://github.com/ltsstar/BPO_Batching/blob/b3aed3ede05dc1d843a81e2dc8add0ad3bc7c866/src/ilp_policy_non_assign.py)

And here is the full error message (from other model values though):

```
Infeasible LNS solution! graph_dec_lns (d=0.87 s=229 t=0.10 p=0.67 stall=12 h=folio_rnd) solved with params max_time_in_seconds: 2
log_search_progress: false
max_deterministic_time: 0.1
search_branching: PORTFOLIO_SEARCH
cp_model_presolve: true
stop_after_first_solution: false
search_random_variable_pool_size: 5
cp_model_probing_level: 0
symmetry_level: 0
solution_pool_size: 1
num_workers: 32
find_big_linear_overlap: false

*** Check failure stack trace: ***

```

The failing CPUs have 32 cores, the working ones have 8 cores.

**Comment by lperron** [comment]
OK, I can reproduce it.
In 9.9, I have made it so that the error message is printed out, but the solve does not stop.

**Comment by ltsstar** [comment]
I noticed that I also get the problem when I use another model without intervals.

**Comment by lperron** [comment]
I have not yet debugged the error.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le ven. 23 févr. 2024 à 16:26, Michel Kunkler ***@***.***> a
écrit :
