### ISSUE TITLE
Signed integer overflow: undefined behavior vs wraparound

### ISSUE THREAD

**Issue by daniel-j-h** [google/or-tools#410]
I can see `-fwrapv` getting passed to the compiler changing signed integer wraparound from undefined behavior to two's complement e.g. [here](https://github.com/google/or-tools/blob/5f23b5ff7c0faec3da5ac87ebd7b56c2a322f39f/makefiles/Makefile.unix.mk#L132). Is there a reason for doing so? Or better: is the code base working with this assumption or is it only used to prevent running into undefined behavior?

The wraparound behavior hides undefined behavior one could otherwise detect with the sanitizers (ubsan) and prevents some compiler optimizations. Curious as to why you pass the flag.

---

Side note: I can see a `CMakeLists.txt` appearing - is the plan to switch to CMake completely or is it fine to open tickets and pull requests wrt. the existing Makefiles? For example the Unix Makefile should honor `CXX` and `CXXFLAGS` (for C++ compiler and C++ compiler flags, respectively) and not hard-code g++.

**Comment by lperron** [comment]
Hi, 

wrapv, I forgot from where it comes. A good portion of our code implements saturated arithmetics, and thus we should never overflow, or maybe this code requires wrapv. I need to dig that up.

about makefiles, we plan to switch to cmake as soon as possible, but we are not there yet.

Feel free to open bugs, or to send pull requests.

Thanks

**Comment by lperron** [comment]
Actually, see https://github.com/google/or-tools/issues/57

**Comment by daniel-j-h** [comment]
Yeah I found the saturated arithmetic functions, that's why I was curious.

Not sure how the ticket #57 you linked is related to `-fwrapv` - did you want to post a different one?

**Comment by lperron** [comment]
Sorry,

https://github.com/google/or-tools/issues/73



Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-06-09 12:37 GMT+02:00 Daniel J. H. <notifications@github.com>:

**Comment by daniel-j-h** [comment]
Ah I see - great that you are aware of it. I'm closing this issue.

Feel free to re-open if you think the `-fwrapv` is an issue and needs to be fixed.
