### ISSUE TITLE
domain from_values cause floating point exception error

### ISSUE THREAD

**Issue by arnabadas** [google/or-tools#4106]
**What version of OR-Tools and what language are you using?**
Version: v9.9.3903
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows

**What did you do?**
I will prepare a test case, but most likely using from_values with an equality constraint where multiplication with an integer is happening will replicate the issue in some scenarios. I simply wanted to let know beforehand. Maybe a quick look will help identify the problem.

**What did you expect to see**
No error

**What did you see instead?**
Floating point exception error

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
NA

**Comment by lperron** [comment]
please provide actionable feedback.
