### ISSUE TITLE
Floating point exception error in CP-SAT solver

### ISSUE THREAD

**Issue by arnabadas** [google/or-tools#4108]
**What version of OR-Tools and what language are you using?**
Version: v9.9.3903
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 22.04 LTS (WSL2 on Windows 11)

**What did you do?**
Run this model:

[test_model.txt](https://github.com/google/or-tools/files/14457036/test_model.txt)

**What did you expect to see**
Solution

**What did you see instead?**
Floating point exception error

Make sure you include information that can help us debug (full error message, model Proto).
[test_log.txt](https://github.com/google/or-tools/files/14457039/test_log.txt)

**Anything else we should know about your project / environment**
NA

**Comment by lperron** [comment]
Thanks. I will have a look

**Comment by arnabadas** [comment]
Also, another thing is that "Floating point exception" error is not printed in Windows. It just ends abruptly.

**Comment by lperron** [comment]
Thanks a lot.
