### ISSUE TITLE
different results solver excel 

### ISSUE THREAD

**Issue by duytv14** [google/or-tools#4123]
**What version of OR-Tools and what language are you using?**
Version: ortools-9.9.3963
Language: Python

**Which solver are you using (e.g. CLP)**

**What operating system (Windows) and version? Windows 10 Version 22H2 x64**

**What did you do?**
[19.py.txt](https://github.com/google/or-tools/files/14557800/19.py.txt)
[19.xlsx](https://github.com/google/or-tools/files/14557831/19.xlsx)

1. Go to file excel '19.xlsx'
2. Click on 'Solver' and results 1,191,892,387
3. Run code python file '19.py' results 1,191,892,386
4. different results solver excel and OR-Tools

**What did you expect to see** 1,191,892,387

**What did you see instead?**  1,191,892,386

Why is the result of excel solver different from OR-Tools?

**Comment by lperron** [comment]
as answered,

**Comment by duytv14** [comment]
> as answered,

Thank @lperron
