### ISSUE TITLE
Typing for linear expressions in CP-SAT is all wrong in version 9.9.3963

### ISSUE THREAD

**Issue by Dr-Irv** [google/or-tools#4130]
**What version of OR-Tools and what language are you using?**
Version:  9.9.3963
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
```python
from ortools.sat.python import cp_model

model = cp_model.CpModel()

x = model.NewIntVar(0, 10, "x")
y = model.NewIntVar(0, 10, "y")
z = model.NewIntVar(0, 10, "z")

model.Add(x + y - z <= 1)

```

**What did you expect to see**
No errors in typing

**What did you see instead?**
With "basic" setting in VSCode, the following is reported:
```
Operator "<=" not supported for types "LinearExprT | _ComplexLike" and "Literal[1]"
  Operator "<=" not supported for types "_ComplexLike" and "Literal[1]" when expected type is "BoundedLinearExpression | bool"
```

The overloads in `class LinExpr` in `cp_model.py` for `__add__()`, `__rmul__()` and `__sub__()` and `__rmul__()`, should return `"LinearExpr"` not `LinearExprT`

The overloads for `__mul__()` and `__rmul__()` need to be totally redone, because you only want to return a `"LinearExpr"` when multiplying another `LinExpr` by an `int` .  Right now, it is allowing multiplications of linear expressions times linear expressions.

This needs an IMMEDIATE fix on `pypi` .  It is creating a large amount of typing issues on a large code base.

**Comment by lperron** [comment]
it is a mess. We use pytype and the code passes. I ran mypy, and it asks for changes that are incompatible with pytype.

I just pushed an improved version that removes the warning with complex.

**Comment by Dr-Irv** [comment]
> it is a mess. We use pytype and the code passes. I ran mypy, and it asks for changes that are incompatible with pytype.

I'm the leader on `pandas-stubs`.  We use `pyright` and `mypy` as our type checkers.  Our experience has shown that `pyright` is better than `mypy`, and both of them are far better than `pytype`.

> 
> I just pushed an improved version that removes the warning with complex.

Where?  When can you update the released version on `pypi` ?

**Comment by lperron** [comment]
1-2 months minimum.

We need to make math-opt works on python...
