### ISSUE TITLE
 object has no attribute 'NewFixedSizeIntervalVar' in ortools 9.9

### ISSUE THREAD

**Issue by SalvatoreDamicis** [google/or-tools#4131]
**What version of OR-Tools and what language are you using?**
Version: main/v9.9.3963
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT
**What operating system (Linux, Windows, ...) and version?**
linux
**What did you do?**
**REFERENCE**:ortools/sat/python/cp_model.py:2980
The function "_NewFixedSizedIntervalVar_" isn't present in previuos version (9.8.3296).  I think that there is a typo because the method was  "_NewFixedSizeIntervalVar_"

**What did you expect to see**

**What did you see instead?**
 object has no attribute 'NewFixedSizeIntervalVar'
Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by Mizux** [comment]
https://github.com/google/or-tools/blob/3ed2b2d963014f285108058a7354b0afd9d81c00/ortools/sat/python/cp_model.py#L2980

**Comment by lperron** [comment]
Thanks. I will fix it

**Comment by lperron** [comment]
Thanks again
