### ISSUE TITLE
ARM C++ build for Debian 11

### ISSUE THREAD

**Issue by ankane** [google/or-tools#4136]
Hi @Mizux and @lperron, hope things are good.

I wanted see if an ARM C++ build for Debian 11 could be added to the release process. This was manually done for v9.8 in #4007, but don't see one for v9.9.

(If not, no worries, but will remove support for it from the Ruby gem)

**Comment by Mizux** [comment]
Will try to do it on Wednesday, forget my M1 at office ^^;

**Comment by ankane** [comment]
Thanks @Mizux!

**Comment by Mizux** [comment]
here it is: https://github.com/google/or-tools/releases/download/v9.9/or-tools_arm64_debian-11_cpp_v9.9.3963.tar.gz

**Comment by ankane** [comment]
Awesome, thank you!
