### ISSUE TITLE
Crash in destruction of constraint solvers

### ISSUE THREAD

**Issue by keithyipkw** [google/or-tools#414]
The key lines are
```
# startMax = startMin + 1 # not crash
startMax = startMin # crash
solver = None
```
It seems to be a memory issue.

or-tools_MacOsX-10.12.2_v5.1.4048
OS X 10.12.5 (16F73)
Python 2.7.13

```
from __future__ import print_function

# Import Python wrapper for or-tools constraint solver.
from ortools.constraint_solver import pywrapcp

special_machine = 1

def main():

    calculated_starts = []
    solvers = []

    machines_count = 4
    jobs_count = 0
    while True:
        jobs_count += 1
        print("Current job size: ", jobs_count)
        
        # Create the solver.
        solver = pywrapcp.Solver('jobshop' + str(jobs_count))

        all_machines = range(0, machines_count)
        all_jobs = range(0, jobs_count)

        processing_time_template = [32, 60 * 10, 3, 47, 3, 5, 3]
        machine_template = [0, 1, 0, 2, 0, 3, 0]
        processing_times = []
        machines = []
        for i in range(0, jobs_count):
            processing_times.append(processing_time_template)
            machines.append(machine_template)

        # Computes horizon.
        horizon = 0
        for i in all_jobs:
            horizon += sum(processing_times[i])
        # Creates jobs.
        all_tasks = {}
        for i in all_jobs:
            for j in range(0, len(machines[i])):
                startMin = 0
                startMax = horizon
                if j == 0 and len(calculated_starts) > 0:
                    if i < len(calculated_starts):
                        startMin = calculated_starts[i]
                        # startMax = startMin + 1 # not crash
                        startMax = startMin # crash
                all_tasks[(i, j)] = solver.FixedDurationIntervalVar(startMin,
                                                                    startMax,
                                                                    processing_times[i][j],
                                                                    False,
                                                                    'Job_%i_%i' % (i, j))

        # Creates sequence variables and add disjuctive constraints.
        all_sequences = {}
        all_machines_jobs = []
        for i in all_machines:
            if i == special_machine:
                continue
            machines_jobs = []
            for j in all_jobs:
                for k in range(0, len(machines[j])):
                    if machines[j][k] == i:
                        machines_jobs.append(all_tasks[(j, k)])
            disj = solver.DisjunctiveConstraint(
                machines_jobs, 'machine %i' % i)
            all_sequences[i] = disj.SequenceVar()
            solver.Add(disj)

        # Add conjunctive contraints.
        for i in all_jobs:
            for j in range(0, len(machines[i]) - 1):
                solver.Add(
                    all_tasks[(i, j + 1)].StartsAtEnd(all_tasks[(i, j)]))

        # Set the objective.
        obj_var = solver.Max([all_tasks[(i, len(machines[i]) - 1)].EndExpr()
                              for i in all_jobs])
        objective_monitor = solver.Minimize(obj_var, 1)
        # Create search phases.
        sequence_phase = solver.Phase(all_sequences.values(),
                                      solver.SEQUENCE_DEFAULT)
        vars_phase = solver.Phase([obj_var],
                                  solver.CHOOSE_FIRST_UNBOUND,
                                  solver.ASSIGN_MIN_VALUE)
        main_phase = solver.Compose([vars_phase, sequence_phase])
        # Create the solution collector.
        collector = solver.LastSolutionCollector()

        # Add the interesting variables to the SolutionCollector.
        collector.Add(all_sequences.values())
        collector.AddObjective(obj_var)

        for i in all_machines:
            if i not in all_sequences:
                continue
            sequence = all_sequences[i]
            sequence_count = sequence.Size()
            for j in range(0, sequence_count):
                t = sequence.Interval(j)
        for key in all_tasks:
            t = all_tasks[key]
            collector.Add(t.StartExpr().Var())
            collector.Add(t.EndExpr().Var())
        # Solve the problem.
        disp_col_width = 10

        if solver.Solve(main_phase, [objective_monitor, collector]):
            sol_line = ""
            sol_line_tasks = ""
            print("Optimal Schedule")

            for i in all_machines:
                if i not in all_sequences:
                    continue
                seq = all_sequences[i]
                sol_line += "Machine " + str(i) + ": "
                sol_line_tasks += "Machine " + str(i) + ": "
                sequence = collector.ForwardSequence(0, seq)
                seq_size = len(sequence)

                for j in range(0, seq_size):
                    t = seq.Interval(sequence[j])
                    # Add spaces to output to align columns.
                    sol_line_tasks += t.Name() + " " * (disp_col_width - len(t.Name()))

                for j in range(0, seq_size):
                    t = seq.Interval(sequence[j])
                    sol_tmp = "[" + str(collector.Value(0,
                                                        t.StartExpr().Var())) + ","
                    sol_tmp += str(collector.Value(0,
                                                   t.EndExpr().Var())) + "] "
                    # Add spaces to output to align columns.
                    sol_line += sol_tmp + " " * (disp_col_width - len(sol_tmp))

                sol_line += "\n"
                sol_line_tasks += "\n"
            for i in all_jobs:
                for j in range(0, len(processing_times[i])):
                    key = (i, j)
                    v = all_tasks[key]
                    sol_tmp=v.Name() + "[" + str(collector.Value(0, v.StartExpr().Var())) + ","
                    sol_tmp += str(str(collector.Value(0, v.EndExpr().Var()))) + "] "
                    # Add spaces to output to align columns.
                    sol_line += sol_tmp + " " * (disp_col_width - len(sol_tmp))
                sol_line += "\n"
            
            calculated_starts.append(collector.Value(0, all_tasks[(jobs_count - 1, 0)].StartExpr().Var()))
            print(sol_line_tasks)
            print("Time Intervals for Tasks\n")
            print(sol_line)
            print("Time = ", solver.WallTime(), "milliseconds")
            total_time = collector.ObjectiveValue(0)
            print("Optimal Schedule Length: ", total_time)
        solver = None

if __name__ == '__main__':
    main()

```

**Comment by lperron** [comment]
Thanks, I will have a look.

**Comment by lperron** [comment]
Here is a working solution: in the collect, use StartValue, EndValue and add intervals instead of interval start and end expr.

from __future__ import print_function

# Import Python wrapper for or-tools constraint solver.
from ortools.constraint_solver import pywrapcp

special_machine = 1

def main():

    calculated_starts = []
    solvers = []

    machines_count = 4
    jobs_count = 0
    while True:
        jobs_count += 1
        print("Current job size: ", jobs_count)

        # Create the solver.
        solver = pywrapcp.Solver('jobshop' + str(jobs_count))

        all_machines = range(0, machines_count)
        all_jobs = range(0, jobs_count)

        processing_time_template = [32, 60 * 10, 3, 47, 3, 5, 3]
        machine_template = [0, 1, 0, 2, 0, 3, 0]
        processing_times = []
        machines = []
        for i in range(0, jobs_count):
            processing_times.append(processing_time_template)
            machines.append(machine_template)

        # Computes horizon.
        horizon = 0
        for i in all_jobs:
            horizon += sum(processing_times[i])
        # Creates jobs.
        all_tasks = {}
        for i in all_jobs:
            for j in range(0, len(machines[i])):
                startMin = 0
                startMax = horizon
                if j == 0 and len(calculated_starts) > 0:
                    if i < len(calculated_starts):
                        startMin = calculated_starts[i]
                        # startMax = startMin + 1 # not crash
                        startMax = startMin # crash
                all_tasks[(i, j)] = solver.FixedDurationIntervalVar(startMin,
                                                                    startMax,
                                                                    processing_times[i][j],
                                                                    False,
                                                                    'Job_%i_%i' % (i, j))

        # Creates sequence variables and add disjuctive constraints.
        all_sequences = {}
        all_machines_jobs = []
        for i in all_machines:
            if i == special_machine:
                continue
            machines_jobs = []
            for j in all_jobs:
                for k in range(0, len(machines[j])):
                    if machines[j][k] == i:
                        machines_jobs.append(all_tasks[(j, k)])
            disj = solver.DisjunctiveConstraint(
                machines_jobs, 'machine %i' % i)
            all_sequences[i] = disj.SequenceVar()
            solver.Add(disj)

        # Add conjunctive contraints.
        for i in all_jobs:
            for j in range(0, len(machines[i]) - 1):
                solver.Add(
                    all_tasks[(i, j + 1)].StartsAtEnd(all_tasks[(i, j)]))

        # Set the objective.
        obj_var = solver.Max([all_tasks[(i, len(machines[i]) - 1)].EndExpr()
                              for i in all_jobs])
        objective_monitor = solver.Minimize(obj_var, 1)
        # Create search phases.
        sequence_phase = solver.Phase(all_sequences.values(),
                                      solver.SEQUENCE_DEFAULT)
        vars_phase = solver.Phase([obj_var],
                                  solver.CHOOSE_FIRST_UNBOUND,
                                  solver.ASSIGN_MIN_VALUE)
        main_phase = solver.Compose([vars_phase, sequence_phase])
        # Create the solution collector.
        collector = solver.LastSolutionCollector()

        # Add the interesting variables to the SolutionCollector.
        collector.Add(all_sequences.values())
        collector.AddObjective(obj_var)

        for i in all_machines:
            if i not in all_sequences:
                continue
            sequence = all_sequences[i]
            sequence_count = sequence.Size()
            for j in range(0, sequence_count):
                t = sequence.Interval(j)
        for key in all_tasks:
            t = all_tasks[key]
            collector.Add(t)
        # Solve the problem.
        disp_col_width = 10

        if solver.Solve(main_phase, [objective_monitor, collector]):
            sol_line = ""
            sol_line_tasks = ""
            print("Optimal Schedule")

            for i in all_machines:
                if i not in all_sequences:
                    continue
                seq = all_sequences[i]
                sol_line += "Machine " + str(i) + ": "
                sol_line_tasks += "Machine " + str(i) + ": "
                sequence = collector.ForwardSequence(0, seq)
                seq_size = len(sequence)

                for j in range(0, seq_size):
                    t = seq.Interval(sequence[j])
                    # Add spaces to output to align columns.
                    sol_line_tasks += t.Name() + " " * (disp_col_width - len(t.Name()))

                for j in range(0, seq_size):
                    t = seq.Interval(sequence[j])
                    sol_tmp = "[" + str(collector.StartValue(0, t)) + ","
                    sol_tmp += str(collector.StartValue(0, t)) + "] "
                    # Add spaces to output to align columns.
                    sol_line += sol_tmp + " " * (disp_col_width - len(sol_tmp))

                sol_line += "\n"
                sol_line_tasks += "\n"
            for i in all_jobs:
                for j in range(0, len(processing_times[i])):
                    key = (i, j)
                    v = all_tasks[key]
                    sol_tmp=v.Name() + "[" + str(collector.StartValue(0, v)) + ","
                    sol_tmp += str(str(collector.EndValue(0, v))) + "] "
                    # Add spaces to output to align columns.
                    sol_line += sol_tmp + " " * (disp_col_width - len(sol_tmp))
                sol_line += "\n"

            calculated_starts.append(collector.StartValue(0, all_tasks[(jobs_count - 1, 0)]))
            print(sol_line_tasks)
            print("Time Intervals for Tasks\n")
            print(sol_line)
            print("Time = ", solver.WallTime(), "milliseconds")
            total_time = collector.ObjectiveValue(0)
            print("Optimal Schedule Length: ", total_time)
        solver = None

if __name__ == '__main__':
    main()

**Comment by keithyipkw** [comment]
Is it illegal to use StartExpr to a collector?

**Comment by keithyipkw** [comment]
If I use StartValue in C++ for intervals with different min and max, sometimes my program crashes because of this `CHECK_EQ(start_max_, start_min_);`. Does it mean that StartValue is for constant starts and Value is for varying starts?

**Comment by lperron** [comment]
No, 

- there seems to be a bug with const variables in collectors. I will look into it.
- startExpr tends to create new objects, so it is better not to use them in general. They are useful though.
- If startvalue crashes, it means that the interval is not fixed at a leaf. You could add a MakePhase(all_intervals, DEFAULT_INTERVAL) decision builder to push everything towards the start.
I hope this helps.

**Comment by lperron** [comment]
No, StartValue works on interval, Value on integer variables.
Both need the corresponding var to be fixed at a leaf.

--Laurent

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-06-11 10:39 GMT+02:00 keithyipkw <notifications@github.com>:

**Comment by lperron** [comment]
I believe I can close this issue. The given code works, and I strongly encourage you to use the CP-SAT version.
