### ISSUE TITLE
Renaming of python methods leads to confusion

### ISSUE THREAD

**Issue by Dr-Irv** [google/or-tools#4143]
**What version of OR-Tools and what language are you using?**
Version: 9.9.3963
Language: python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

CP-SAT

**What operating system (Linux, Windows, ...) and version?**

Windows, Linux

It seems that the new version has renamed all the python methods from PascalCase to camel case.  The docs were updated, but are inconsistent. For example, the job scheduling example at https://developers.google.com/optimization/scheduling/job_shop uses camel case in the example code, but the words that describe how this works use PascalCase.  I will bet there are other places where this inconsistency is present in the documentation.  For members of my team that are learning CP-SAT, this is very confusing.

Are there release notes that explain changes like these so we know how much of our existing code we need to change to be compliant with the new API?  

While it's true that the old API works with our current code, I see that people are reporting issues, e.g.
* #4131 and
* #4137,
and I'm concerned that more will possibly turn up.

Fix the docs.  Provide release notes (or maybe you did and they are not easy to find)

**Comment by lperron** [comment]
https://github.com/google/or-tools/discussions/4119

**Comment by lperron** [comment]
Note: here is the sed rules to change the code to the new API. 

s/\bAddAbsEquality\b/add_abs_equality/g
s/\bAddAllDifferent\b/add_all_different/g
s/\bAddAllowedAssignments\b/add_allowed_assignments/g
s/\bAddAssumption\b/add_assumption/g
s/\bAddAssumptions\b/add_assumptions/g
s/\bAddAtLeastOne\b/add_at_least_one/g
s/\bAddAtMostOne\b/add_at_most_one/g
s/\bAddAutomaton\b/add_automaton/g
s/\bAddBoolAnd\b/add_bool_and/g
s/\bAddBoolOr\b/add_bool_or/g
s/\bAddBoolXOr\b/add_bool_xor/g
s/\bAddCircuit\b/add_circuit/g
s/\bAddCumulative\b/add_cumulative/g
s/\bAddDecisionStrategy\b/add_decision_strategy/g
s/\bAddDivisionEquality\b/add_division_equality/g
s/\bAddElement\b/add_element/g
s/\bAddExactlyOne\b/add_exactly_one/g
s/\bAddForbiddenAssignments\b/add_forbidden_assignments/g
s/\bAddHint\b/add_hint/g
s/\bAddImplication\b/add_implication/g
s/\bAddInverse\b/add_inverse/g
s/\bAddLinearConstraint\b/add_linear_constraint/g
s/\bAddLinearExpressionInDomain\b/add_linear_expression_in_domain/g
s/\bAddMapDomain\b/add_map_domain/g
s/\bAddMaxEquality\b/add_max_equality/g
s/\bAddMinEquality\b/add_min_equality/g
s/\bAddModuloEquality\b/add_modulo_equality/g
s/\bAddMultipleCircuit\b/add_multiple_circuit/g
s/\bAddMultiplicationEquality\b/add_multiplication_equality/g
s/\bAddNoOverlap2D\b/add_no_overlap2_d/g
s/\bAddNoOverlap\b/add_no_overlap/g
s/\bAddReservoirConstraintWithActive\b/add_reservoir_constraint_with_active/g
s/\bAddReservoirConstraint\b/add_reservoir_constraint/g
s/\bAdd\b/add/g
s/\bAssertIsBooleanVariable\b/assert_is_boolean_variable/g
s/\bBestObjectiveBound\(\)\b/best_objective_bound/g
s/\bBooleanValue\b/boolean_value/g
s/\bBooleanValues\b/boolean_values/g
s/\bBounds\b/bounds/g
s/\bClearAssumptions\b/clear_assumptions/g
s/\bClearHints\b/clear_hints/g
s/\bClearObjective\b/clear_objective/g
s/\bClone\b/clone/g
s/\bCoefficient\b/coefficient/g
s/\bCoefficients\b/coefficients/g
s/\bConstant\b/constant/g
s/\bDisplayBounds\b/display_bounds/g
s/\bEndExpr\b/end_expr/g
s/\bEvaluateBooleanExpression\b/evaluate_boolean_expression/g
s/\bEvaluateLinearExpr\b/evaluate_linear_expr/g
s/\bExpandGeneratorOrTuple\b/expand_generator_or_tuple/g
s/\bExportToFile\b/export_to_file/g
s/\bExpression\b/expression/g
s/\bExpressions\b/expressions/g
s/\bFlattenedIntervals\b/flattened_intervals/g
s/\bFromFlatIntervals\b/from_flat_intervals/g
s/\bFromIntervals\b/from_intervals/g
s/\bFromValues\b/from_values/g
s/\bGetBoolVarFromProtoIndex\b/get_bool_var_from_proto_index/g
s/\bGetFloatVarValueMap\b/get_float_var_value_map/g
s/\bGetIntVarFromProtoIndex\b/get_int_var_from_proto_index/g
s/\bGetIntegerVarValueMap\b/get_integer_var_value_map/g
s/\bGetIntervalIndex\b/get_interval_index/g
s/\bGetIntervalVarFromProtoIndex\b/get_interval_var_from_proto_index/g
s/\bGetOrMakeBooleanIndex\b/get_or_make_boolean_index/g
s/\bGetOrMakeIndexFromConstant\b/get_or_make_index_from_constant/g
s/\bGetOrMakeIndex\b/get_or_make_index/g
s/\bHasObjective\b/has_objective/g
s/\bHasResponse\b/has_response/g
s/\bIndex\(\)\b/index/g
s/\bIsEmptyOrAllNull\b/is_empty_or_all_null/g
s/\bIsEqualTo\b/is_equal_to/g
s/\bLeft\b/left/g
s/\bMaximize\b/maximize/g
s/\bMinimize\b/minimize/g
s/\bModelStats\b/model_stats/g
s/\bName\(\)\b/name/g
s/\bNegated\b/negated/g
s/\bNewBoolVarSeries\b/new_bool_var_series/g
s/\bNewBoolVar\b/new_bool_var/g
s/\bNewConstant\b/new_constant/g
s/\bNewFixedSizeIntervalVarSeries\b/new_fixed_size_interval_var_series/g
s/\bNewFixedSizeIntervalVar\b/new_fixed_size_interval_var/g
s/\bNewIntVarFromDomain\b/new_int_var_from_domain/g
s/\bNewIntVarSeries\b/new_int_var_series/g
s/\bNewIntVar\b/new_int_var/g
s/\bNewIntervalVarSeries\b/new_interval_var_series/g
s/\bNewIntervalVar\b/new_interval_var/g
s/\bNewOptionalFixedSizeIntervalVarSeries\b/new_optional_fixed_size_interval_var_series/g
s/\bNewOptionalFixedSizeIntervalVar\b/new_optional_fixed_size_interval_var/g
s/\bNewOptionalIntervalVarSeries\b/new_optional_interval_var_series/g
s/\bNewOptionalIntervalVar\b/new_optional_interval_var/g
s/\bNot\b/negated/g
s/\bNumBooleans\(\)\b/num_booleans/g
s/\bNumBranches\(\)\b/num_branches/g
s/\bNumConflicts\(\)\b/num_conflicts/g
s/\bObjectIsAFalseLiteral\b/object_is_a_false_literal/g
s/\bObjectIsATrueLiteral\b/object_is_a_true_literal/g
s/\bObjectiveValue\(\)\b/objective_value/g
s/\bOnSolutionCallback\b/on_solution_callback/g
s/\bOnlyEnforceIf\b/only_enforce_if/g
s/\bParseLinearExpression\b/parse_linear_expression/g
s/\bProto\(\)\b/proto/g
s/\bRebuildConstantMap\b/rebuild_constant_map/g
s/\bRebuildFromLinearExpressionProto\b/rebuild_from_linear_expression_proto/g
s/\bResponseProto\b/response_proto/g
s/\bResponseStats\b/response_stats/g
s/\bResponse\b/response/g
s/\bRight\b/right/g
s/\bSearchForAllSolutions\b/search_for_all_solutions/g
s/\bSetName\b/set_name/g
s/\bShortExprName\b/short_expr_name/g
s/\bShortName\b/short_name/g
s/\bSizeExpr\b/size_expr/g
s/\bSolutionCount\b/solution_count/g
s/\bSolutionInfo\b/solution_info/g
s/\bSolveWithSolutionCallback\b/solve_with_solution_callback/g
s/\bSolve\b/solve/g
s/\bStartExpr\b/start_expr/g
s/\bStatusName\b/status_name/g
s/\bStopSearch\b/stop_search/g
s/\bSufficientAssumptionsForInfeasibility\b/sufficient_assumptions_for_infeasibility/g
s/\bSum\b/sum/g
s/\bTerm\b/term/g
s/\bUserTime\(\)\b/user_time/g
s/\bValidate\b/validate/g
s/\bValue\b/value/g
s/\bValues\b/values/g
s/\bVarIndexToVarProto\b/var_index_to_var_proto/g
s/\bWallTime\(\)\b/wall_time/g
s/\bWeightedSum\b/weighted_sum/g
s/\bWithName\b/with_name/g

**Comment by lperron** [comment]
I fixed the doc and made sure the 2 copies of the release notes are up to date.
