### ISSUE TITLE
0<=1 not accept by math_opt

### ISSUE THREAD

**Issue by quantcn** [google/or-tools#4147]
Hello, the following model gives error:
Traceback (most recent call last):
```
  File "e:\mypyoptimize\py-smart-roster\test2.py", line 11, in <module>
    model.add_linear_constraint(sum([x[i2,j] for (i2,j) in setIJ if i2==i]) <= 1)
  File "E:\anaconda3\envs\optim\lib\site-packages\ortools\math_opt\python\model.py", line 1758, in add_linear_constraint
    normalized_inequality = as_normalized_linear_inequality(
  File "E:\anaconda3\envs\optim\lib\site-packages\ortools\math_opt\python\model.py", line 2263, in as_normalized_linear_inequality
    raise TypeError(
TypeError: unsupported type for bounded_expr argument: bool.
This error can occur when trying to add != constraints (which are not supported) or
inequalities/equalities with constant left-hand-side and right-hand-side
 (which are redundant or make a model infeasible).
```
In pywraplp, there is no error with this model.  I know in the constraint, if i=10, it becomes 0<=1 which is accepted by pywraplp,
but not accepted by mathOpt. I want that mathOpt also accept it.

The model:

```py
from ortools.math_opt.python import mathopt
 
model = mathopt.Model()
setIJ = {(i,j) for i in range(10) for j in range(10)}

x = {(i,j): model.add_integer_variable(lb=0.0, name=f"x_{i}_{j}") for (i,j) in setIJ}

for i in range(11):
    model.add_linear_constraint(sum([x[i2,j] for (i2,j) in setIJ if i2==i]) <= 1)

model.minimize(sum(x[i,j] for (i,j) in setIJ))

result = mathopt.solve(model, mathopt.SolverType.CP_SAT)
```

**Comment by Mizux** [comment]
in your loop `for i in range(11)` last loop i.e. `i == 10` there is no `(i, j) in setIJ if i==10` so sum is empty...
try to change the range to `range(10)`...

**Comment by quantcn** [comment]
thank you, fast_sum is exactly what I want.

> Here I would recommend:
> 
> * either using `mathopt.fast_sum()` instead of `sum()`, which returns a linear expression instead of 0 when there are no operands:
>   ```python
>   for i in range(11):
>     model.add_linear_constraint(mathopt.fast_sum([x[i2,j] for (i2,j) in setIJ if i2==i]) <= 1)
>   ```
> * or use the `start` optional parameter of Python's `sum` and set the start value as zero linear expression:
>   ```python
>   for i in range(11):
>     model.add_linear_constraint(sum([x[i2,j] for (i2,j) in setIJ if i2==i],
>                                     start=mathopt.LinearExpression()) <= 1)
>   ```
> 
> The rationales for these two alternatives is that in Python, if you have 0 instead of `LinearExpression()`, there is no way for MathOpt to do anything when calling `add_linear_constraint(0 <= 1)` as Python will transform `0 <= 1` to `False`.
> 
> Does this makes sense?

thank you, fast_sum is exactly what I want.
