### ISSUE TITLE
Improve the pointer size checking

### ISSUE THREAD

**Issue by keithyipkw** [google/or-tools#415]
When using the or-tools in a new Xcode project, there is a compilation error for the size of the pointer. In constraint_solveri.h
```
inline uint64 Hash1(void* const ptr) {
#if defined(ARCH_K8) || defined(__powerpc64__) || defined(__aarch64__)
  return Hash1(reinterpret_cast<uint64>(ptr));
#else
  return Hash1(reinterpret_cast<uint32>(ptr));
#endif
}
```
None of the macros are defined in clang. The checking from platform_macros.h in the Protobuf is better. I tried to build from the source to check the macros but the cmake settings were quite messy on OS X. I could not finish the build even after multiple patches.

**Comment by lperron** [comment]
I pushed a fix for that.

Thanks for the suggestion.
