### ISSUE TITLE
description of how ortools roughly works?

### ISSUE THREAD

**Issue by EstherJohanna** [google/or-tools#416]
Hi all,

I am using ortools for my master's thesis. Right now I'm simply using it and I'm happy it somehow does what I want, but of course in the thesis I have to describe how ortools solves the problem. Does anyone know where I could find an answer? Looking through the code doesn't really make me understand anything at all. 
Thanks for your help :)!

**Comment by orwant** [comment]
The answer depends on what type of problem you're trying to solve. If you
can tell us more about that, we might be able to help.

Jon

**Comment by EstherJohanna** [comment]
I'm using pyschedule (https://github.com/timnon/pyschedule) and with that I'm scheduling tasks to be solved by certain resources, as fast as possible :). ortools is a function that is called in pyschedule.

**Comment by orwant** [comment]
Based on
https://github.com/timnon/pyschedule/blob/master/docs/pyschedule-overview.md,
it seems that pyschedule is a wrapper around several solvers.

OR-tools is itself a wrapper around solvers, but pyschedule uses only the
OR-tools CP solver
<https://github.com/timnon/pyschedule/blob/master/src/pyschedule/solvers/ortools.py>.
For information on how that CP solver works, see
https://developers.google.com/optimization/cp/cp_solver.

Hope this helps,

Jon

**Comment by EstherJohanna** [comment]
great! thank you so much!
