### ISSUE TITLE
solver crash; Check failed: SolutionIsFeasible

### ISSUE THREAD

**Issue by Wout4** [google/or-tools#4169]
**What version of OR-Tools and what language are you using?**
Version: v9.9
Language:Python
**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT
**What operating system (Linux, Windows, ...) and version?**
Windows
**What did you do?**
solving the attached model resulted in a crash. I hope this format is helpful for debugging, since it's not a python exception that i can catch it's hard to find a smaller example.

**What did you expect to see**
solving the model
**What did you see instead?**
following error message:
```
Check failed: SolutionIsFeasible( model_proto, std::vector<int64_t>(response->solution().begin(), response->solution().end()), mapping_proto, &postsolve_mapping) postsolved solution
*** Check failure stack trace: ***
    @   00007FF9C7422E39  (unknown)
    @   00007FF9C68F83C8  (unknown)
    @   00007FF9C675E2B7  (unknown)
    @   00007FF9C675DA1A  (unknown)
    @   00007FF9C690D1DD  (unknown)
    @   00007FF9C676941C  (unknown)
    @   00007FF9C662D950  (unknown)
    @   00007FF9C662DA24  (unknown)
    @   00007FF9C661EB23  (unknown)
    @   00007FF9EDF250B2  (unknown)
    @   00007FF9EDEF3189  (unknown)
    @   00007FF9EE0531C6  (unknown)
    @   00007FF9EDEFEDA4  (unknown)
    @   00007FF9EDF07D4B  (unknown)
    @   00007FF9EDF01586  (unknown)
    @   00007FF9EDEFF40C  (unknown)
    @   00007FF9EDF07B23  (unknown)
    @   00007FF9EDF01586  (unknown)
    @   00007FF9EDEFD68A  (unknown)
    @   00007FF9EDEFEDA4  (unknown)
    @   00007FF9EDF082B8  (unknown)
    @   00007FF9EDF01586  (unknown)
    @   00007FF9EDEFD68A  (unknown)
    @   00007FF9EDEFEDA4  (unknown)
    @   00007FF9EDF082B8  (unknown)
    @   00007FF9EDF01586  (unknown)
    @   00007FF9EDEFF40C  (unknown)
    @   00007FF9EDF07B23  (unknown)
    @   00007FF9EDF01586  (unknown)
    @   00007FF9EDF13899  (unknown)
    @   00007FF9EDF879CB  (unknown)
    @   00007FF9EDF87929  (unknown)
    @   00007FF9EDF8764A  (unknown)
    @   00007FF9EDF875CA  (unknown)
    @   00007FF9EDFCE55F  (unknown)
    @   00007FF9EDFCE2E4  (unknown)
    @   00007FF9EDFCCAA3  (unknown)
    @   00007FF9EDFCC858  (unknown)
    @   00007FF9EDFCC28A  (unknown)
    @   00007FF9EDFAB5C8  (unknown)
    @   00007FF9EDFAB451  (unknown)
    @   00007FF9EDFAB317  (unknown)
    @   00007FF9EE03DB21  (unknown)
    @   00007FF64AA21268  (unknown)
    @   00007FFA92E1257D  (unknown)
    @   00007FFA94B8AA58  (unknown)

```
[model.txt](https://github.com/google/or-tools/files/14883332/model.txt)

p.s. this might be related to https://github.com/google/or-tools/issues/4168 so maybe it's already solved on main..

**Comment by lperron** [comment]
What params did you use ?
Was it deterministic ?

I tried on main: 

CpSolverResponse summary:
status: OPTIMAL
objective: NA
best_bound: NA
integers: 17
booleans: 87
conflicts: 0
branches: 0
propagations: 0
integer_propagations: 0
restarts: 0
lp_iterations: 0
walltime: 0.017133
usertime: 0.017133
deterministic_time: 0.000850184
gap_integral: 0
solution_fingerprint: 0x28893e8a2b260110

But if this is flaky, this is not enough of a test.

**Comment by lperron** [comment]
the empty model does not crash for me.

**Comment by Wout4** [comment]
Ofcourse, sorry, I was trying to demonstrate how I call the solver, the model still has to be initialised as in the txt file.

**Comment by lperron** [comment]
OK :-)
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
