### ISSUE TITLE
Multi-core

### ISSUE THREAD

**Issue by GiovanniConserva** [google/or-tools#417]
Hi all,
is there any support for multicore utilization? I've noticed that only a single processor is used.
In particular, I'm asking for CP, but it'd be useful to get an answer about other solvers too.
Thanks!

**Comment by CarsonRoscoe** [comment]
I, too, would like to know the answer to this.

We are looking at replacing GECODE with the CP in OrTools. We love the C# syntax and getting to program in our .NET world without needing to make separate C++ wrappers every time we need to solve a problem.

I rewrote one of our main GECODE solvers in OrTools to compare. With small data sets, the two perform identically. However, once we reach a larger data set, GECODE out performs using all but two of your cores (in our implementation). So what takes GECODE 28 seconds takes about 4-5 minutes with OrTools.

If we could take advantage of multiple cores, like we can with GECODE and most commercial solvers, that would be fantastic.

**Comment by lperron** [comment]
Actually, I would use the sat solver, which outperforms or-tools CP
consistently. (and I believe Gecode, but I did not test it).

The API is very different, and I did not write the C# wrapper yet, but it
should be easy.

You need to create a cp_model protobuf (see ortools/sat/cp_model.proto),
and solve it using ortools/sat/cp_model_solver.h

We have ported one example to use it:

see examples/cpp/weighted_tardiness_sat.cc

I know the transition is not trivial, but it is worth it IMO.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-08-01 11:28 GMT-07:00 Carson Roscoe <notifications@github.com>:

**Comment by lperron** [comment]
I have pushed examples/test/testsat.cs which showcases the protobuf based
solver + some trivial helper.

As I said, very low level, but the solver is very good.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-08-01 11:39 GMT-07:00 Laurent Perron <lperron@google.com>:

**Comment by gregy4** [comment]
Is it possible to invoke multiple instances (processes) of cp solver ?  In case it is possible I think it is more about definition of multiple deterministic searching strategies or stochastic strategy and a communication between solvers. I succesfully implemented it for choco solver (pure java) and no support from the solver was needed.

Related to sat solver and not 100% sure that all cp problems can be converted to sat solver. I plan to try sat solver also but expect that only parts of my scheduling problem can be solved by sat solver.

**Comment by lperron** [comment]
There are no reason why you couldn't invoke multiple solvers at the same
time. You can always decompose, or run a portfolio of solvers manually.

The API of the SAT solver and the CP solver are very close. You can have a
look at ortools/sat/python/cp_model.py and all files in
examples/python/*sat.py

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2018-01-31 15:02 GMT+01:00 gregy4 <notifications@github.com>:

**Comment by jfjensen** [comment]
Multicore support for MIP solvers (when using the Python wrapper) would be great to have too.
Would that be possible in the future?

**Comment by lperron** [comment]
The CP-SAT solver now support parallelism and c#. Closing this issue. I will create a new issue to support parallelism in MIPs.
