### ISSUE TITLE
Unsatisfied linear constraint with no free enforcement literal: enforcement_literal [occurs sometimes]

### ISSUE THREAD

**Issue by forceoffire** [google/or-tools#4176]
**What version of OR-Tools and what language are you using?**
CP-SAT solver v9.9.3963 Release version
Language: Minizinc

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows

**What did you do?**
The original minizinc mzn/dzn combination was compiled to fzn and executed against fzn-cp-sat.exe.  I typically run the model in parallel with 24 CPUs.  

**What did you expect to see**
Most of the time the solver completes successfully [see attached result_successful_solve.txt].  

**What did you see instead?**
About once every five runs, the executable terminates with an error:
F0410 10:29:09.107739   44632 cp_model_postsolve.cc:105] Unsatisfied linear constraint with no free enforcement literal: enforcement_literal: 2323 linear { vars: 2305 coeffs: 1 domain: 0 domain: 0 }

Make sure you include information that can help us debug (full error message, model Proto).
I've included the fzn file.

**Anything else we should know about your project / environment**
I'm currently running fzn-cp-sat in a Windows 10 environment.

[ortools_error.zip](https://github.com/google/or-tools/files/14931621/ortools_error.zip)

**Comment by lperron** [comment]
I can reproduce.

It would be super nice if you could reduce the size of the model.

**Comment by forceoffire** [comment]
Dear Laurent,

I've attempted to reduce the model's size, but it seems that the likelihood of the error now occurring is lower.  However, I could repeat the issue with the attached model as well:

fzn-cp-sat.exe error_2024_04_10_reduced.fzn --time_limit=120 --threads=24 --cp_model_stats=true --display_all_solutions=true --statistics=true --cp_trace_search=true  --v=99999  1>result_002.txt
F0411 09:35:05.807726   14216 cp_model_postsolve.cc:106] Unsatisfied linear constraint with no free enforcement literal: enforcement_literal: -1191 linear { vars: 1184 coeffs: 1 domain: 0 domain: 0 }
*** Check failure stack trace: ***
    @   00007FF66DC8BFE9  (unknown)
    @   00007FF66D9B58ED  (unknown)
    @   00007FF66D9B4620  (unknown)
    @   00007FF66D9B5392  (unknown)
    @   00007FF66D93392B  (unknown)
    @   00007FF66D7A26A2  (unknown)
    @   00007FF66DB3AB24  (unknown)
    @   00007FF66DB3A55F  (unknown)
    @   00007FFEEC381BB2  (unknown)
    @   00007FFEECF87614  (unknown)
    @   00007FFEEEA026B1  (unknown)

I've included two additional txt files: result_001.txt shows where it succeeded, and result_002.txt where it failed.

I have not been able to reduce the size of the model further as yet.

Sincere regards.


[ortools_error_2.zip](https://github.com/google/or-tools/files/14944335/ortools_error_2.zip)

**Comment by lperron** [comment]
Thanks.
