### ISSUE TITLE
CI for project

### ISSUE THREAD

**Issue by dkourilov** [google/or-tools#418]
Hi,
Are there any plans to introduce Travis CI or integration with another CI system? I'm maintaining my own private builds from master, other users possibly do so as well. Having a CI working here will greatly simplify the workflows and provide community with up-to-date version in pypi.

**Comment by mjfwest** [comment]
Hi, 
Can I second that.  I started with a Travis CI about a year ago, but the difficulty of patching and writing the build script defeated me then. I was very recently thinking about trying again after the transition to cmake.   Does anyone have enough experience to advise against this?

**Comment by lperron** [comment]
Hi,

no, we cannot use travis.

--Laurent

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-06-14 10:31 GMT+02:00 Martin West <notifications@github.com>:

**Comment by mjfwest** [comment]
Can you clarify, is that because you know it will not work specifically with Travis,  because of a policy you/(we) have against using Travis, or because you/(we) cannot use any CI system?

**Comment by lperron** [comment]
We have a policy against third party integration like travis.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-06-14 14:47 GMT+02:00 Martin West <notifications@github.com>:

**Comment by dkourilov** [comment]
I can roll out an automatically synced fork on github (via http://backstroke.us/), and set up test+build targets in Travis CI, but this raises a question on pypi package name conflict. What I want to avoid is full name-spacing of fork, including pypi package name, file system location, shared library name, etc.  Any ideas here on how to avoid namespacing will be much appreciated.

Also, @lperron, can I ask you what is your criteria to release updated pypi packages? Is this about code stability?

**Comment by lperron** [comment]
We release pypi along github releases.
We aim (and fail) at releasing once per month.



Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-06-19 23:17 GMT+02:00 Denis Kurilov <notifications@github.com>:

**Comment by Mizux** [comment]
Hi,

We now use Travis CI (linux, osx) and Appveyor (windows) to test OR-Tools build.

For pypi package since we are pushing on master, I guess we prefer to provide release from time to time when it's stable.
And if you want a bleeding edge package you can still build master from source and/or using tools\Docker job to build manylinux pypi package...

note: don't know if pypi provide a 999/testing package flavor or maybe we should create an ortools-nightly package.
