### ISSUE TITLE
Check failed: Assignment().LiteralIsAssigned() Has this bug been fixed?

### ISSUE THREAD

**Issue by mengfanli** [google/or-tools#4186]
My problem is similar to this ：
https://groups.google.com/g/or-tools-discuss/c/szUZaQTTsvg/m/YKO37RMAAgAJ

**What version of OR-Tools and what language are you using?**
Version: v9.8
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Linux redhat 7.8

**What did you do?**

I used Or-tools version 9.2 before this week and this problem never occurred. After upgrading the version to 9.8 with performance optimization in mind, this problem occurred. It is a probabilistic event that occurs 1-3 times during the execution of 144 tasks per day.Etch task has about dozens model to solve(These models were inherited). The problems all arise when solving the later models.

Check failed: Assignment().LiteralIsAssigned(a) 
***check failure stack trace***
Check failed: Assignment().LiteralIsAssigned(a) 
***check failure stack trace***
ORA-24550:signal received:[si_signo=6][si_errno=0][si_code=-6][si_int=0][si_ptr=(nil)][si_addr=0xbbb3]
Process 'Forkpool worker-7' pid xxx exited with 'signal 6(SIGABRT)'

**Comment by lperron** [comment]
I think it has been fixed.
Can you send me the model ?

**Comment by mengfanli** [comment]
Sorry, The model file cannot be provided. I have tried re-executing it with the same input data and no error was reported. Has this issue been fixed in V9.9, or is it planned to be fixed in 10.0?

**Comment by mengfanli** [comment]
> Sorry, The model file cannot be provided. I have tried re-executing it with the same input data and no error was reported. Has this issue been fixed in V9.9, or is it planned to be fixed in 10.0?


I tried logging in the logs to monitor the memory usage, but the content looked normal and did not exceed 2GB.

**Comment by mengfanli** [comment]
> Sorry, The model file cannot be provided. I have tried re-executing it with the same input data and no error was reported. Has this issue been fixed in V9.9, or is it planned to be fixed in 10.0?

I tried logging in the logs to monitor the memory usage, but the memory seemed to be normal, no more than 2GB. Just like any other tasks.

**Comment by lperron** [comment]
I cannot answer without testing.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
