### ISSUE TITLE
CP-SAT (v9.9) crashes silently (regression from 9.8)

### ISSUE THREAD

**Issue by CADBIMDeveloper** [google/or-tools#4187]
**What version of OR-Tools and what language are you using?**
Version: 9.9.3963.
Language: C#

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
Trying to solve the following model:
[model.txt](https://github.com/google/or-tools/files/14995656/model.txt)

**What did you expect to see**

Solution :-)

**What did you see instead?**

The app crashes silently, no errors in the log.

Version 9,9 log:
[v99.log](https://github.com/google/or-tools/files/14995669/v99.log)

Previous 9,8 is able to solve this model:
[v98.log](https://github.com/google/or-tools/files/14995677/v98.log)

**Comment by lperron** [comment]
Yes, my bad,  A stupid crash in the LNS for no_overlap_2d.
It is fixed on main. We hope to release 9.10 soon with the fix. We just have 2 more bugs to crush.
