### ISSUE TITLE
Performance regression after 9.9.4133 (3194fd5)

### ISSUE THREAD

**Issue by magneticflux-** [google/or-tools#4189]
**What version of OR-Tools and what language are you using?**
Version: main, 9ed0074090aacba704afd420234a6083e2644b5b, 3194fd5bb2017957dd3460719ba08affaa803511
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you do?**
1. Solve the attached model using 9.9.4132 (9ed0074090aacba704afd420234a6083e2644b5b) (it takes ~20 seconds on an i9-10900K)
2. Solve the attached model using 9.9.4133 (3194fd5bb2017957dd3460719ba08affaa803511) (it takes ~40 seconds on the same hardware)

**What did you expect to see**

[log_9ed0074090aacba704afd420234a6083e2644b5b.txt](https://github.com/google/or-tools/files/15019094/log_9ed0074090aacba704afd420234a6083e2644b5b.txt)

**What did you see instead?**

[log_3194fd5bb2017957dd3460719ba08affaa803511.txt](https://github.com/google/or-tools/files/15019095/log_3194fd5bb2017957dd3460719ba08affaa803511.txt)

The model I used for comparison:
[model.zip](https://github.com/google/or-tools/files/15019020/model.zip)

Some differences I noticed in the logs:
- \# vars in presolve went down (different propagation changing probing order?)
- \# propagations under "Search stats" went up, but the summary stayed the same
- approx gap integral went up
- all SAT stats increased significantly

**Comment by fdid-git** [comment]
I think there is a high variance on your model (like it is often the case, especially in multithread). If you try to solve it many times with different random seed, you can get various solve time. I attached an histogram of 1k runs with the latest version. 

![Histogram of walltime](https://github.com/google/or-tools/assets/11074342/7d39b378-c4ba-40b2-8c6f-5ccbe7244b2a)

Also, solving it with one thread, like with --params subsolvers:\"max_lp\" seems to work better now.
So I don't think there is much we can do here.

**Comment by fdid-git** [comment]
Yes, I think the new code adds more  "randomness" which explain the higher variance, especially if you test with different random seed. On another hand, the code should be more robust to future change in other places.

**Comment by lperron** [comment]
Can you retry ?

I have good results with main. So try with 9.11.

**Comment by lperron** [comment]
I ran it multiple times with 16 workers on my workstation, runtime was between 12 and 18 seconds with HEAD.
