### ISSUE TITLE
VRP 

### ISSUE THREAD

**Issue by ganhy1218** [google/or-tools#4197]
**What language and solver does this apply to?**
Python

**Describe the problem you are trying to solve.**
i want to solve the problem that how to append time dimension into the cost function

**Comment by lperron** [comment]
not an issue

**Comment by Mizux** [comment]
set the SpanCost coeff of the dimension to `1` (0 by default thus not participating to the objective value)

https://github.com/google/or-tools/blob/a0690fc79db6a49a14610697996fa73993d12012/ortools/constraint_solver/routing.h#L3204-L3211
