### ISSUE TITLE
a feasible model turns out to be infeasible randomly

### ISSUE THREAD

**Issue by disonvon** [google/or-tools#4199]
**What version of OR-Tools and what language are you using?**
Version: 9.8
Language: python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT
**What operating system (Linux, Windows, ...) and version?**
Mac Apple M2 Mac Os 13.0
**What did you do?**
a text model file return different solution status, sometimes it is feasible, sometimes not

**What did you expect to see**
the feasible status should be consistent, which is feasible in my case
**What did you see instead?**
as above mentioned
Make sure you include information that can help us debug (full error message, model Proto).
`#coding=utf-8
from ortools.sat.python import cp_model
from google.protobuf import text_format
import pickle
import os

def solve(file):
    model = cp_model.CpModel()
    with open(file, "r") as file:
        text_format.Parse(file.read(), model.Proto())

    # Create a solver and solve
    solver = cp_model.CpSolver()
    solver.parameters.max_time_in_seconds = 120
    # solver.parameters.log_search_progress = True
    status = solver.Solve(model)

    # Check the solution
    if status == cp_model.OPTIMAL:
        print('Objective value =', solver.ObjectiveValue())
    elif status == cp_model.FEASIBLE:
        print('A potentially suboptimal solution was found.')
    elif status == cp_model.INFEASIBLE:
        print('The problem is infeasible.')
    else:
        print('ohter status')

if __name__ == '__main__':
    file = './../../output/test.pd.txt'
    for i in range(1, 10):
        print(f'----------iteration: {i}----------')
        solve(file)

    print('done')`

----------iteration: 1----------
Objective value = 283621783174.0
----------iteration: 2----------
The problem is infeasible.
----------iteration: 3----------
The problem is infeasible.
----------iteration: 4----------
The problem is infeasible.
----------iteration: 5----------
The problem is infeasible.
----------iteration: 6----------
The problem is infeasible.
----------iteration: 7----------
The problem is infeasible.
----------iteration: 8----------
The problem is infeasible.
----------iteration: 9----------
The problem is infeasible.
done

**Anything else we should know about your project / environment**

**Comment by disonvon** [comment]
[Uploading test.pd.txt.zip…]()

**Comment by disonvon** [comment]
model file attached above

**Comment by lperron** [comment]
Can you try with 9.9 ?

**Comment by disonvon** [comment]
> Can you try with 9.9 ?

9.9 is always feasible(optimal) for this model.
BTW, i also encountered the similar cases months ago with 9.4

**Comment by lperron** [comment]
Yes, bugs + nondeterminism happen.

Le jeu. 25 avr. 2024, 07:33, Zhiwei Feng ***@***.***> a
écrit :
