### ISSUE TITLE
Conflict with glog

### ISSUE THREAD

**Issue by JasonMarechal25** [google/or-tools#4200]
**What version of OR-Tools and what language are you using?**
Version: v9.9
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
N/A

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 22.04

**What did you do?**
Create a project and depend on both glog 0.7 and ortools 9.9

**What did you expect to see**
Build properly

**What did you see instead?**
Build error :
```glog/install/include/glog/flags.h:124:1: error: ‘bool fLB::FLAGS_logtostderr’ conflicts with a previous declaration
  124 | DECLARE_bool(logtostderr);

or-tools_9.9/include/ortools/base/logging.h:30:1: note: previous declaration ‘absl::lts_20240116::Flag<bool> FLAGS_logtostderr’
   30 | ABSL_DECLARE_FLAG(bool, logtostderr);
```

**Anything else we should know about your project / environment**

I didn't find any information or clear stance on what should be or not used when wanting to use google logging facilities.
On one hand we have this topic https://github.com/google/or-tools/issues/2378 and this comment particulary:

> At this point, the only official google logging code is the abseil one. So I will close this issue.

On the other hand glog seems actively maintained. Also I've asked a question on the topic to the glog repo https://github.com/google/glog/issues/1095

In a simple cas of a new project it's just a matter of choosing one or the other. However for projects already using one it's an issue when trying to incorporate the other.
My cas specifically is that I have an application A using glog and I can't integrate a lib B using ortools because of this issue

**Comment by lperron** [comment]
The two options are not incompatible. the official google logging code is the abseil one, and glog is a community maintained project.

Now the question is that what compatibility or-tools will offer with previous flags (logtostderr). 

I will remove it for 9.10.
