### ISSUE TITLE
[python ]MathOpt solver_test timeout on macOS

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#4209]
## Branches/Version
On `main` or `v99bugfix` (v9.10 branch)

## OS

* Mac Intel/M1,
* Python [3.8,3.12]

## Protocol:
```sh
git checkout main
git pull -r
cmake -S. -Bbuild -DBUILD_PYTHON=ON
cmake --build build -j
(cd build && ctest -R "python_math_opt_solver_test")
```

## Expected:
Like on Linux
```
Test project /usr/local/google/home/corentinl/work/main/build
    Start 20: python_math_opt_solver_test
1/1 Test #20: python_math_opt_solver_test ......   Passed    0.47 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.51 sec
```

## Observed:
```
Test project /usr/local/google/home/corentinl/work/main/build
    Start 20: python_math_opt_solver_test
# blocking...
```

## Hypotheses

The GIL management is not done correctly (contrary to MPSolver or CP-SAT) making the callback test hang forever...

**Comment by rma350** [comment]
this is on linux or mac?

**Comment by arnabanimesh** [comment]
@rma350 mac

**Comment by Mizux** [comment]
seems fixed on `main` and `v99bugfix`

**Comment by Mizux** [comment]
> Do we have any idea what changed? I did not change the code. Is the change caused by a different version of pybind11/absl/python/proto? Or just unknown?

a little bit of all of this + MathOpt  do change since v9.10
```sh
git diff --shortstat v9.10..main ortools/math_opt/ 
 151 files changed, 5394 insertions(+), 1000 deletions(-)
```
