### ISSUE TITLE
How to configure or-tools to work with Gurobi?

### ISSUE THREAD

**Issue by gmarchi** [google/or-tools#421]
I suppose I have to setup UNIX_GUROBI_DIR in Makefile.local and then do 'make clean' and 'make cc', right? I've seen also GUROBI_LIB_VERSION, what kind of parameters does it refer?

**Comment by reinoldus** [comment]
this is my working config for Gurobi:

echo "UNIX_GUROBI_DIR = /opt/gurobi/" >> /opt/or-tools/or-tools-6.0/Makefile.local
echo "GUROBI_LIB_VERSION = 70" >> /opt/or-tools/or-tools-6.0/Makefile.local

I assume that GUROBI_LIB_VERSION stands for the major version:
7.0.2 -> 70

If I recall correctly the number is required to find the appropriate lib: libgurobi70.so

hope it helps!

**Comment by lperron** [comment]
Yes, thanks!

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-07-05 20:39 GMT-07:00 Stefan Hesse <notifications@github.com>:

**Comment by gmarchi** [comment]
> this is what I write in to the Makefile and it is working with Gurobi:
> 
> echo "UNIX_GUROBI_DIR = /opt/gurobi/" >> /opt/or-tools/or-tools-6.0/Makefile.local
> echo "GUROBI_LIB_VERSION = 70" >> /opt/or-tools/or-tools-6.0/Makefile.local
> 
> I assume that GUROBI_LIB_VERSION stands for the major version:
> 7.0.2 -> 70
> 
> If I recall correctly the number is required to find the appropriate lib: libgurobi70.so
> 
> hope it helps!

Thanks @reinoldus !!!

**Comment by helanhalvan** [comment]
I don't think this should be closed until some documentation about how to do this is put somewhere easier to find.

**Comment by antoniomedrano** [comment]
So to clarify, this is similar to the procedure for installing SCIP? On a mac with python, this would be:
1. Download the latest or-tools release (after installing the latest cmake and command line tools)
2. `make third_party`
3. `make python`
4. Edit `Makefile.local` by adding the following lines at the end (assuming or-tools v6.5 and gurobi v7.5.2):
`echo "UNIX_GUROBI_DIR = /opt/gurobi/" >> /opt/or-tools/or-tools-6.5/Makefile.local
echo "GUROBI_LIB_VERSION = 75" >> /opt/or-tools/or-tools-6.5/Makefile.local`
5. `make clean && make cc`

Please confirm if this is correct. Thanks.

**Comment by gmarchi** [comment]
I think there are some mistakes in your procedure.

If you are have to install or-tools from zero:

1. Download them (of course check dependencies).
2. `make third_party`
3. Edit Makefile.local as you correctly said (however on my mac i have a different “UNIX_GUROBI_DIR”, so check your path to gurobi).
4. Now `make python` (after would be useful also a `make test`)

If instead you’d like to modify a current or tools installation, i think you should:

1. `make clean`
2. Edit Makefile.local
3. `make python` (`make cc` creates only c++ interface…..oh and of course remember to check that everything is working with `make test`)

I hope it helps!

**Comment by gdowdy3** [comment]
This page is highly relevant:
https://developers.google.com/optimization/install/python/source_linux

**Comment by Mizux** [comment]
You can test python using `make check_python` (only run few samples to cover each libraries)
