### ISSUE TITLE
Abnormal resolution after upgrading from version 9.5 to 9.6/9.7/9.8 or 9.9

### ISSUE THREAD

**Issue by francescgirbau** [google/or-tools#4210]
**What version of OR-Tools and what language are you using?**
9.5
Version: main/v9.6/v9.5 etc.
Language: 
C#
**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
SCIP
**What operating system (Linux, Windows, ...) and version?**
Windows/Linux
**What did you do?**

We have some test cases to validate the optimization implementation after upgrading the or-tools version to the latest one. 
We have observed that the test cases don't pass anymore. 

We have tried using 9.6, 9.7, and 9.8, and we have the same problem, so we guess it relates to a change from version 9.5 to 9.6.
Could you help us?
I am attaching a simple problem in which the problem is manifested. 

**What did you expect to see**
OPTIMAL
**What did you see instead?**
ABNORMAL
Make sure you include information that can help us debug (full error message, model Proto).
The same problem is being adequately resolved using version 9.5.

\ Generated bx_bool MPModelProtoExporter
\   Name             : 
\   Format           : Free
\   Constraints      : 12
\   Variables        : 15
\     Binarx_bool         : 3
\     Integer        : 0
\     Continuous     : 12
Minimize

 Obj: +10 x_up - 10 x_down + 100 y_up -100 y_down +50 z_up -50 z_down 
 
Subject to

 auto_c_000000000: +1 x -1 x_up -1 x_down  = -0
 auto_c_000000001: +1 x_up -10 x_bool  <= 0
 auto_c_000000002: +1 x_down -10 x_bool  >= -10
 
 auto_c_000000003: +1 y -1 y_up -1 y_down  = -0
 auto_c_000000004: +1 y_up -inf y_bool  <= 0
 auto_c_000000005: +1 y_down -inf y_bool  <= nan
 
 auto_c_000000006: +1 z -1 z_up -1 z_down  = -0
 auto_c_000000007: +1 z_up -inf z_bool  <= 0
 auto_c_000000008: +1 z_down -inf z_bool  <= nan
 
 auto_c_000000009: +1 x +1 y -1 sub_goal  = -0
 auto_c_000000010: +1 z -1 slack  = -0
 auto_c_000000011: +1 x +1 z -1 goal  = -0
 
Bounds

 -10 <= x <= 10
 0 <= x_up <= 10
 -10 <= x_down <= 0
 0 <= x_bool <= 1
 
 y free
 0 <= y_up
 y_down <= 0
 0 <= y_bool <= 1
 
 z free
 0 <= z_up
 z_down <= 0
 0 <= z_bool <= 1
 
 -50 <= sub_goal <= 50
 slack free
 100 <= goal <= 100
 
Binaries
 x_bool
 y_bool
 z_bool
End

**Comment by lperron** [comment]
have you enabled the log ?

**Comment by lperron** [comment]
Nan are really bad. Do not create a model with nans.

Second, Scip really does not like infinity. Use 1e20 instead of infinity.

**Comment by lperron** [comment]
Last, if you do not have continuous variables just use CP-SAT.

**Comment by lperron** [comment]
good. SCIP is very picky with bounds.
