### ISSUE TITLE
v9.10 release of Java OR-Tools contains a binary-breaking upgrade to protobuf-java

### ISSUE THREAD

**Issue by DavidGregory084** [google/or-tools#4218]
Version: v9.10
Language: Java

The Java bindings for OR-Tools v9.9 depend upon protobuf-java 3.25.x.

The Java bindings for OR-Tools v9.10 depend upon protobuf-java 4.26.1, which isn't binary-compatible with 3.x.

It's not a big deal, as users can simply downgrade, but should this release be relabelled v10?

**Comment by lperron** [comment]
no, 10.0 will be really API incompatible. We will update the release notes.

**Comment by lperron** [comment]
Our internal code follows abseil, protobuf, re2 in lockstep. We have no choice in the matter.
And we do not guarantee ABI compatibility between minor releases, only API compatibility.

**Comment by DavidGregory084** [comment]
> no, the use of protobuf is only internal. So even if its API change, it does not impact OR-Tools.

The public API of the Java bindings is full of proto classes, like [MPSolver#solveWithProto](https://javadoc.io/static/com.google.ortools/ortools-java/9.10.4067/com/google/ortools/linearsolver/MPSolver.html#solveWithProto(com.google.ortools.linearsolver.MPModelRequest)), which returns an [MPSolutionResponse](https://javadoc.io/static/com.google.ortools/ortools-java/9.10.4067/com/google/ortools/linearsolver/MPSolutionResponse.html) that extends [GeneratedMessage](https://javadoc.io/doc/com.google.protobuf/protobuf-java/3.25.3/com/google/protobuf/GeneratedMessage.html).

Unfortunately the protobuf 3.x runtime is still used in [OpenTelemetry](https://mvnrepository.com/artifact/io.opentelemetry.proto/opentelemetry-proto/1.2.0-alpha), [grpc](https://github.com/grpc/grpc-java/issues/11015) and [many other open source projects](https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java).

Users trying to run OR-Tools Java v9.10 alongside any of those libraries will most likely run into `ClassNotFoundException: com.google.protobuf.GeneratedMessageV3`.

I think that this is a manifestation of https://github.com/protocolbuffers/protobuf/issues/16452.

**Comment by lperron** [comment]
for many reasons, we have no choice but to follow closely the releases of abseil, protobuf and re2.
Unfortunately, if other projects do not release updated versions, you are stuck with an older version.

**Comment by lperron** [comment]
Grpc has also been updated to use protobuf 26.1
