### ISSUE TITLE
java crashes with EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by ztgoto** [google/or-tools#4235]
**What version of OR-Tools and what language are you using?**
Version: 9.10.4067
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
windows10

**What did you do?**
Run the java demo code of https://developers.google.cn/optimization/assignment/assignment_example#cp_sat_solution.

**What did you expect to see**

**What did you see instead?**
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe9ae62f58, pid=20328, tid=0x0000000000002c20

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
Can you check the solution with #4225
