### ISSUE TITLE
Minimum Route Stops

### ISSUE THREAD

**Issue by khangthinh-huynh19** [google/or-tools#4238]
**What version of OR-Tools and what language are you using?**
Version: v9.10
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Vehicle Routing Problem
**What operating system (Linux, Windows, ...) and version?**
Linux and WIndow
**What did you do?**
I have a VRP problem that need to be solved, however, the constraint is that each vehicle should visit at least 2 stops. How can I show that ?

Is there any method or solution to add that constraint to the model ?

**Comment by lperron** [comment]
Asked many times. Search for soft lower bound.
