### ISSUE TITLE
lp_data is missing in ubuntu tarball (v6.1)

### ISSUE THREAD

**Issue by jakobwitzig** [google/or-tools#424]
I try to integrate Glop as an LP solver to SCIP. The interface is developed by google and was sent to us. Unfortunately, the lp_data directory (which is included by the interface) is missing, so I'm not able to compile.

Thanks,
Jakob

**Comment by jakobwitzig** [comment]
Btw. using the lp_data directory from the repository works fine.

**Comment by lperron** [comment]
Hi,
I updated the archive script.
Can you build from source until the next release (normally next month)?

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-06-30 11:30 GMT+02:00 jakobwitzig <notifications@github.com>:

**Comment by jakobwitzig** [comment]
Thanks for the quick responds. Yes, I cloned the repository and compiled or-tools successfully. 

When I now try to compile SCIP with your interface I get other errors, e.g., `lp_solver.h` includes `ortools/glop/parameters.pb.h` which is not in `glop`. This is probably I bit off topic here. We can continue by mail (witzig@zib.de) if you want.

**Comment by lperron** [comment]
I should be in or-tools/ortools/gen/ortools/glop

so add both -I<path to or-tools> -I<path to or-tools>/ortools/gen to cflags.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-06-30 15:26 GMT+02:00 jakobwitzig <notifications@github.com>:

**Comment by jakobwitzig** [comment]
> I should be in or-tools/ortools/gen/ortools/glop

Perfect, thanks!
