### ISSUE TITLE
CP-SAT: Support floating-point objective in Minizinc parser

### ISSUE THREAD

**Issue by SYury** [google/or-tools#4246]
Currently the CP-SAT solver supports optimizing a linear objective with floating-point coefficients. However, when solving such problem via Minizinc model, the parser crashes with `Check failed: !fz_var->domain.is_float CP-SAT does not support float variables` even though there are no float variables in the original model. This happens because Minizinc converts the objective variables to floats and adds an auxiliary float variable that stores the objective function value. It would be nice if CP-SAT Minizinc parser could detect such cases and create the floating-point objective without crashing.

**Comment by lperron** [comment]
Clearly a substantial amount of work.

**Comment by lperron** [comment]
Can you attach small fzn you would like CP-SAT to support them ?

**Comment by SYury** [comment]
Here is a simple example:
<details>
<summary>fzn</summary>

```
var 0..1: x:: output_var;
var 0..1: y:: output_var;
var -1.5..0.5: X_INTRODUCED_0_:: output_var:: is_defined_var;
var 0.0..1.0: X_INTRODUCED_1_ ::var_is_introduced :: is_defined_var;
var 0.0..1.0: X_INTRODUCED_2_ ::var_is_introduced :: is_defined_var;
constraint float_lin_eq([0.5,-1.5,-1.0],[X_INTRODUCED_2_,X_INTRODUCED_1_,X_INTRODUCED_0_],-0.0):: defines_var(X_INTRODUCED_0_):: ctx_neg;
constraint int2float(y,X_INTRODUCED_1_):: defines_var(X_INTRODUCED_1_);
constraint int2float(x,X_INTRODUCED_2_):: defines_var(X_INTRODUCED_2_);
solve  minimize X_INTRODUCED_0_;
```
</details>

compiled from:

<details>
<summary>mzn</summary>

```
var 0..1: x;
var 0..1: y;

solve minimize 0.5 * x - 1.5 * y;
```
</details>
