### ISSUE TITLE
flexible_jobshop.cc defined wrong data file format in the comments

### ISSUE THREAD

**Issue by jiangj001** [google/or-tools#425]
When I parse a file of jssp, ex. data/jobshop/abz8 which can be parsed correctly by the jobshop.h, the flexible_jobshop.h couldn't parse it correctly. 
Current one:
    "Required: input file description the scheduling problem to solve, "
    "in our jssp format:\n"
    "  - the first line is \"instance <instance name>\"\n"
    "  - the second line is \"<number of jobs> <number of machines>\"\n"
    "  - then one line per job, with a single space-separated "
    "list of \"<machine index> <duration>\"\n"
    "note: jobs with one task are not supported");

correct one should be:
    "  - the first line is \"<number of jobs> <number of machines> <I DON'T KNOW ABOUT THE THIRD NUMBER>\"\n"
    "  - then one line per job, with a single space-separated "  "list of \"<alternative task counts N> N of (<machine index> <duration>), e. g. 1 2 4 or 2 2 4 9 4 or 3 2 4 9 4 8 4\"\n"

In addition, from my compiler, word.size() in the flexible_jobshop.h always return one more than actual number of words, not sure it happens to others or not.

**Comment by lperron** [comment]
flexible jobshop will parse .fjs file (I fixed the comment which said .fjp).
It will not parse regular jssp files.

Please note that this has been rewritten for the CP-SAT solver.  
I have a complete protobuf file in ortools/data/jobshop_scheduling.proto, a reader alongside it that read most of the formats directly, and a solver in examples/cpp/jobshop_sat.cc
