### ISSUE TITLE
recurrent crash on MacOS: libc++abi: std::out_of_range

### ISSUE THREAD

**Issue by amm0x41r** [google/or-tools#4250]
**What version of OR-Tools and what language are you using?**
Version: v9.8.3296
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT
**What operating system (Linux, Windows, ...) and version?**
MacOS 14.5
**What did you do?**
Create a large model, solve, sometimes the solving process crashes with message:
`libc++abi: terminating due to uncaught exception of type std::out_of_range: absl::container_internal::raw_hash_map<>::at`
<img width="452" alt="image" src="https://github.com/google/or-tools/assets/129093387/fa6eb2ac-caad-4147-bdc4-9ba2e0e6cfae">

Issue happens very randomly while solving. Usually after I've had a number of solutions, but my models find a first feasible quickly so I'm not sure if that is a constant.

**What did you expect to see**
Solving continues to completion.

**What did you see instead?**
Crashes with message `libc++abi: terminating due to uncaught exception of type std::out_of_range: absl::container_internal::raw_hash_map<>::at`

**Anything else we should know about your project / environment**
The issue is resolved temporarily with a reboot, so I guess related to memory usage, but it only ever happens on a Mac

**Comment by lperron** [comment]
Please try with 9.10

**Comment by lperron** [comment]
I am pretty sure this was fixed. Please re-open if not.
