### ISSUE TITLE
Lin-Kernighan operator error

### ISSUE THREAD

**Issue by vuongdanghuy** [google/or-tools#4264]
**What version of OR-Tools and what language are you using?**
Version: v9.10/stable
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing Solver

**What operating system (Linux, Windows, ...) and version?**
Linux Mint 21.3

**What did you do?**
Reading **LinKernighan** path operator source code.

**What did you expect to see**
In the LinKernighan operator, when making 2-opt change the value of the `node` and `next` variable are set incorrectly.
https://github.com/google/or-tools/blob/ef7bb07d57bbe73c5e2ff5bcff9894e0e3164f56/ortools/constraint_solver/local_search.cc#L1871-L1892

It should be `node = out` on line 1884 and `next = chain_last` on line 1888. And also on line 1876, it should be `ReverseChain(base, out, &chain_last)`

**What did you see instead?**
- Wrong value: `node = chain_last` and `next = out`
- Wrong exchange: `ReverseChain(node, out, &chain_last)`

Consider the following example: We have a path 1 -> 2 -> 3 -> 4 -> 5 -> 6 -> 7 -> 8 -> 9 -> 10 -> 11 -> 12 -> 13 -> 14 -> 15 (15 is the same as depot 1)
![image](https://github.com/google/or-tools/assets/25819962/fb4861c4-550f-4a41-94e5-344d9e0c71d2)

**Step 1**: Let's `base = node = 1` and `next = Next(node) = 2`. Assume that `InFromOut()` find out that `out = 7` is best neighbor of 2.
Now we reverse the chain and got:
- new path: 1 -> 6 -> 5 -> 4 -> 3 -> 2 -> 7 -> 8 -> 9 -> 10 -> 11 -> 12 -> 13 -> 14 -> 1 (it's still correct here because `node = base`)
- chain_last = 6

Assume that new path isn't satisfied the if condition on line 1881. Now the code set `node = chain_last = 6` and `next = out = 7` and continue the while loop on line 1872. It'll cause the wrong result on **Step 2**

**Step 2**: On line 1872, `InFromOut()` method will find best neighbor of `next = 7` meanwhile if correct, it should find neighbor of 6.

**Step 3**: Assume if `node` and `next` value are correctly set on **Step 1** (it means `node = 7`, `next = 6`) and in **Step 2** we found the best neighbor of 6 is 11.
![image](https://github.com/google/or-tools/assets/25819962/c77cb55a-bc42-4ca2-a968-b855eae62fb4)

Now if we `ReverseChain(node, out, &chain_last)` the path we got from **Step 1**, we will have the new path: 1 -> 6 -> 5 -> 4 -> 3 -> 2 -> 7 -> 10 -> 9 -> 8 -> 11 -> 12 -> 13 -> 14 -> 15 which is incorrect.
Instead, it should be `ReverseChain(base, out, &chain_last)` to get the path: 1 -> 10 -> 9 -> 8 -> 7 -> 2 -> 3 -> 4 -> 5 -> 6 -> 11 -> 12 -> 13 -> 14 -> 15

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
I believe this is fixed on the main branch.
