### ISSUE TITLE
Make shallow clone when fetching dependencies

### ISSUE THREAD

**Issue by SYury** [google/or-tools#4272]
**What language and solver does this apply to?**
CMake build

**Describe the problem you are trying to solve.**
I tried building OR-Tools with all dependencies on a machine with slow and unreliable internet access (very strict corporate proxy) and `git clone` couldn't fetch some of the largest dependencies (e. g. protobuf) because of their size. The problem went away when I forced CMake to reduce the size by making shallow clone.
**Describe the solution you'd like**
Add GIT_SHALLOW 1 to `FetchContent_Declare` for large dependencies in [dependencies CMakeLists](https://github.com/google/or-tools/blob/stable/cmake/dependencies/CMakeLists.txt). It shouldn't break anything because CMake only needs the latest commit to build a dependency.

**Comment by Mizux** [comment]
Done with https://github.com/google/or-tools/commit/f5d9ea77be10a8d33f1e1afbcd9201fcdc9828f3

note: `GIT_SHALLOW` do **not** work when using commit sha1
