### ISSUE TITLE
CpModel run crash while using 9.10

### ISSUE THREAD

**Issue by sendreams** [google/or-tools#4275]
**What version of OR-Tools and what language are you using?**
Version: 9.10
Language: java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
windows server 2022

**What did you do?**
using the testing code in [https://developers.google.cn/optimization/assignment/assignment_example?hl=zh-cn#complete_programs_2](url)
run AssignmentSat class will made crash.

**What did you expect to see**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
Already answered.  Look at 9.10 release notes on GitHub.
