### ISSUE TITLE
Java: MPSolverParameters LpAlgorithmValues

### ISSUE THREAD

**Issue by tzaretskaya** [google/or-tools#4277]
Version: 9.10.4067
Language: Java

The same issue as https://github.com/google/or-tools/issues/97
MPSolverParameters.java contain enums to change the LP algorithm of CLP, e.g. PRIMAL, DUAL, BARRIER. These enums seem to be missing in IntegerParam.

**Comment by lperron** [comment]
from the code:

// Expose the MPSolverParameters::LpAlgorithmValues enum.
%unignore operations_research::MPSolverParameters::LpAlgorithmValues;  // no test
%unignore operations_research::MPSolverParameters::DUAL;  // no test
%unignore operations_research::MPSolverParameters::PRIMAL;  // no test
%unignore operations_research::MPSolverParameters::BARRIER;  // no test

**Comment by lperron** [comment]
from the generated code:  (MPSolverParameters.java)

  /**
   *  LP algorithm to use.
   */
  public enum LpAlgorithmValues {
    /** 
     *  Dual simplex.
     */
    DUAL(mainJNI.MPSolverParameters_DUAL_get()),
    /**
     *  Primal simplex.
     */ 
    PRIMAL(mainJNI.MPSolverParameters_PRIMAL_get()),
    /** 
     *  Barrier algorithm.
     */
    BARRIER(mainJNI.MPSolverParameters_BARRIER_get());
