### ISSUE TITLE
Issues using HiGHS solver with Java

### ISSUE THREAD

**Issue by ChrisMLikesMath** [google/or-tools#4297]
**What version of OR-Tools and what language are you using?**
Version: 9.10
Language: Java

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
HiGHS MIP

**What operating system (Linux, Windows, ...) and version?**
Windows

**What did you do?**
I've encountered some issues with the HiGHS solver that may be related when trying to build HiGHS solvers or run an integer optimization with highs.

1) When trying to use the MPSolver interface to build a HiGHS solver
`MPSolver solver = MPSolver.createSolver("HIGHS_MIP")  // happens if I use simply "HIGHS" too`
`System.out.println("Solving with " + solver.solverVersion());`

2) I find I can get a HIGHS solver running if I use the MPModelRequest pattern with protos. (It's new to me since I'm more of a C# guy.) If I set up a "simple" MIP problem like given N variables, take exactly M non-zero, with a minimum threshold or else it's zero:

 - max x dot v, subject to 1 dot x = M, l < x < u or x = 0, M non-zero entries

I can get a successful-ish result using HiGHS when using small values like M = 10, N = 100. Larger values like M = 100, N = 1000 will crash. Note it works just fine with SCIP.

Here's an example code to get started

`

    public static void main(String[] args) {
    
    Loader.loadnativeLibraries();
    MPSolver solver = MPSolver.createSolver("HIGHS_MIP") // just a hack to use the MPSolver interface to get the proto later
    solver.enableOutput();

    int M = 100; // take M
    int N = 1000;  // of N
    double upper_lim = 2.0;  // upper limit per variable
    double min_thresh = 0.5;  // min amount per variable

    Random R = new Random(1);  // used to generate objective vector
    MPObjective v = solver.objective();

    double infinity = Double.POSITIVE_INFINITY;

    MPVariable[] b = solver.makeBookvarArray(N, "b");  // same outcome if I use solver.makeIntVaryArray(N, 0, 1)
    MPVariable[] x = solver.makeNumVaryArray(N, 0.0, upper_lim); 

    // must sum to M
    MPConstraint one = solver.makeConstraint(M, M, "one");
    for (int i = 0; i < x.length; i++) {
        one.setCoefficient(x[i], 1.0);
    }

    // everything greater than min_thresh or else zero
    // and also take M of them

    MPConstraint two = solver.makeConstraint(M, M, "two");
    for (int i = 0; i < x.length; i++){
        MPConstraint l = solver.makeConstraint(0.0, infinity, "l" +i);
        l.setCoefficient(x[i], 1.0);
        l.setCoefficient(b[i], -min_thresh);
        MPConstraint u = solver.makeConstraint(-infnity, 0.0, "u" + i);
        u.setCoefficient(x[i], 1.0);
        u.setCoefficient(b[i], -upper_lim * 100.0);  // big M
        two.setCoefficient(b[i], 1.0);
    }

    // random linear objective
    for (int i = 0; i < x.length; i++){
        v.setCoefficient(x[i], R.nextGaussian());
    }
    v.setMaximization();

    MPModelProto proto = solver.exportModelToProto();
    MPModelRequest mpMOdelRequest = MPModelRequest.newBuilder()
        .setEnableInternalSolverOutput(true)
        .setSolverType(MPModelRequest.SolverType.HIGHS_MIXED_INTEGER_PROGRAMMING)  // SCIP_MIXED_INTEGER_PROGRAMMING works fine
        .setModel(proto)
        .build();
    MPSolutionResponse resp = MPSOlver.solverWithProto(mpModelRequest);
    System.out.println("Objective value " + resp.getObjectiveValue());
    System.out.println("done")
    }
`

**What did you expect to see**
1) When using the MPSolver interface calling HIGHS or HIGHS_MIP
`Solving with HiGHS_MIP solver`

2) When solving this problem with HIGHS MIP, I'd expect to see
`Objective value 190.14...`
`done`
`Process finished with exit code 0`

**What did you see instead?**
1) I see something unexpected. It says PDLP solver instead of HIGHS.
`Solving with PDLP solver`

2) When attempting the problem, it simply crashes.
`Process finished with exit code -1073741819 (0xC0000005)`

- However if I take small `N = 100, M = 10`, I get a result but still the error code
`Objective value 22.63...`
`done`
`Process finished with exit code -1073741819 (0xC0000005)`

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
Using Maven/IntelliJ.
Dependency: com.google.orgtools,   / ortools-java / 9.10.4067

**Comment by lperron** [comment]
Highs is only supported in math opt. Which is not in java yet.

I welcome and PR that implements highs support in MPSolver or Model builder.

**Comment by Mizux** [comment]
i.e. need to "fix" the placeholder: https://github.com/google/or-tools/blob/main/ortools/linear_solver/highs_interface.cc

**Comment by ChrisMLikesMath** [comment]
@Mizux @lperron Thanks for the speedy reply! I took a look at the highs_interface.cc file and it's not obvious to me what's missing but I will be taking an interest in the future.
