### ISSUE TITLE
Using or-tools with SCIP

### ISSUE THREAD

**Issue by jlo1** [google/or-tools#431]
When trying to use SCIP, I got this error:
```
java.lang.IllegalArgumentException: No enum constant com.google.ortools.linearsolver.MPSolver.OptimizationProblemType.SCIP_MIXED_INTEGER_PROGRAMMING
```
I've done the following, but could use some help in figuring out how to get scip working.

1. Download the [SCIP Optimization Suite](http://scip.zib.de/#download) tar file
2. `> tar xvf scipoptsuite-4.0.0.tgz`
3. `> cd scipoptsuite-4.0.0 && make GMP=false READLINE=false`
3. `> cd ~/or-tools && make third_party`
4. open `Makefile.local` and add line 
```UNIX_SCIP_DIR = /<abs-path-to-scipoptsuite>/scipoptsuite-4.0.0/scip-4.0.0```
5. make java

FWIW, when running `make test_java`, the tests run successfully and I see this as part of the output:
```
...
---- Integer programming example with SCIP (recommended) ----
Problem solved in 91 milliseconds
Optimal objective value = 6.0
x1 = 6.0
x2 = -0.0
Advanced usage:
Problem solved in 1 branch-and-bound nodes
---- Integer programming example with CBC ----
Problem solved in 42 milliseconds
...
```

**Comment by lperron** [comment]
Did you add the correct path to the DLL in the java command line:
  -Djava.library.path=<path-to-ortools>/lib

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-07-16 4:19 GMT-07:00 jlo1 <notifications@github.com>:

**Comment by jlo1** [comment]
Yes, the `java.library.path` is set to point to the directory with the libs. (Though instead of pointing the path to `<or-tools-dir>/lib`, I've copied everything in the lib directory to a different directory in my project and pointed it to that path.

or-tools works fine with the project without using `SCIP_MIXED_INTEGER_PROGRAMMING` (e.g. if I use CBC or GLOP).

**Comment by jlo1** [comment]
Thanks @lperron -- may mistake, I actually didn't update the `.jar` file, only the other libs. The code compiles fine now, but I now get a "fatal error detected by the Java Runtime Environment", whenever I try using SCIP. The same problem solves fine with CBC.

I've attached the logs: [hs_err_pid71274.txt](https://github.com/google/or-tools/files/1160466/hs_err_pid71274.txt)

**Comment by lperron** [comment]
Which platforms are you one?
For instance on Mac, the path of the libraries are hardcoded into the library. You cannot move them manually.

Furthermore, I have updated the instructions to build scip:

see http://or-tools.blogspot.com/2017/03/changing-way-we-link-with-scip.html

Finally, if it works when you do make java, and not after your manipulation, then something is wrong.

**Comment by yingzong** [comment]
Do you need the entire SCIP optimization suite for this or just SCIP?

**Comment by lperron** [comment]
at least scip + soplex.

    SCIP_LNK = $(UNIX_SCIP_DIR)/lib/static/libscip.$(SCIP_ARCH).a
$(UNIX_SCIP_DIR)/lib/static/libnlpi.cppad.$(SCIP_ARCH).a
$(UNIX_SCIP_DIR)/lib/static/liblpispx2.$(SCIP_ARCH).a
$(UNIX_SCIP_DIR)/lib/static/libsoplex.$(SCIP_ARCH).a
$(UNIX_SCIP_DIR)/lib/static/libtpitny.$(SCIP_ARCH).a

These are the libraries we link with.

We do not link with zimpl.

I recommend compiling SCIP opt suite.

Please note that very soon, we will require scip 5.0.1, and link against
the unified library (libscipopt).

--Laurent
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
If your application crashes with scip after the move, it is because the system is finding the default one, that is compiled without scip, first.

Please use ldd on linux, otool on mac to check which one is found.
