### ISSUE TITLE
Publish latest nuget package

### ISSUE THREAD

**Issue by mwpowellhtx** [google/or-tools#432]
Per Laurent's [announcements](http://groups.google.com/forum/#!topic/or-tools-discuss/Ln2CLIJ3mtw); could we please have a Nuget package published as well?

It's not 100% a show stopper for me since I can build locally, but it would be nice to have the uninterrupted pipeline delivering.

Thank you...

**Comment by lperron** [comment]
Done, thanks for the reminder.

**Comment by mwpowellhtx** [comment]
@lperron No problem. [Thank you!](http://www.nuget.org/packages/Google.OrTools/6.2.4388)
