### ISSUE TITLE
solver.Minimize(....) define complex objective with maximum values among an array of variables.

### ISSUE THREAD

**Issue by zollen** [google/or-tools#4325]
**What version of OR-Tools and what language are you using?**
Version: v9.5 
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
pywraplp.Solver('Minimize the storage area', pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING)

**What operating system (Linux, Windows, ...) and version?**
Window 10

**What did you do?**
x = [ solver.IntVar(0, MAX_VALUE, f'x{i}') for i in ITEMS_INDEX ]
y = [ solver.IntVar(0, MAX_VALUE, f'y{i}') for i in ITEMS_INDEX ]

solver.Minimize(solver.Sum(x) * solver.Sum(y))

I am able to sum all variables in x and y using solver.Sum(), but I am unable to multiple the result of both solver.Sum().
Ideally I want to locate the maximum value in x array and y array, then multiple these two maximum values. Is it even possible to do so as part of the Minimize objective equation?

**What did you expect to see**
I expected solver.Minimize(solver.Sum(x) * solver.Sum(y)) works

**What did you see instead?**
I got error
 File "C:\Users\STEPHEN\eclipse-workspace\Python-ML\best_optim\assetstorage3.py", line 80, in <module>
    solver.Minimize(solver.Sum(x) * solver.Sum(y))
  File "C:\Users\STEPHEN\AppData\Local\Programs\Python\Python310\lib\site-packages\ortools\linear_solver\python\linear_solver_natural_api.py", line 133, in __mul__
    return ProductCst(self, cst)
  File "C:\Users\STEPHEN\AppData\Local\Programs\Python\Python310\lib\site-packages\ortools\linear_solver\python\linear_solver_natural_api.py", line 196, in __init__
    raise TypeError

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
this is not linear, so notsupported.
