### ISSUE TITLE
diversify_lns_params SAT parameter has no effect

### ISSUE THREAD

**Issue by iamthad** [google/or-tools#4326]
The `diversify_lns_params` parameter in `sat_parameters.proto` has no effect as of commit 2264cb9059.

**What version of OR-Tools and what language are you using?**
Version: v9.10
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you do?**
1. Search codebase for `diversify_lns_params` with `git grep`:
    ```console
    $ git grep -l diversify_lns_params
    ortools/julia/ORToolsGenerated.jl/src/genproto/operations_research/sat/sat_parameters_pb.jl
    ortools/sat/sat_parameters.proto
    ```
2. Search git history using pickaxe to find relevant commits:
    ```console
    $ git log --oneline -S diversify_lns_params
    7574421541 export julia wrappers
    2264cb9059 [CP-SAT] more aggregate presolve; fix bug with no_overlap and duplicated intervals; add parameter for the probing time limit; use all threads to find the first solution while the lns workers are idle; tweak lb_tree_search by allowing more glop iterations at the root node
    ...
    ```
3. Inspect commit 2264cb9059 to see that the relevant code was removed from `ortools/sat/cp_model_solver.cc`

**What did you expect to see**
Code implementing the documented behavior ("registers more lns subsolvers with different parameters")

**What did you see instead?**
Only the `sat_parameters.proto` file and a generated Julia version of the same contain the string `diversify_lns_params`.

**Anything else we should know about your project / environment**
This parameter looked promising to me, and I would have benefited from a comment mentioning it no longer has an effect.

**Comment by lperron** [comment]
clearly not an issue. It may come back at some point.
