### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ZhikangLai** [google/or-tools#4330]
**Operating System:** Windows 10 (x64)

**Issue:** Error when running OR-Tools C++ example(C++ 17)

**Description:**I am installing OR-Tools for C++ from Binary on Windows. After installation, I tested the example "dijkstra_one_to_all.cc". However, it produces some error messages as shown in the image below:
![fig1](https://github.com/user-attachments/assets/e7037466-4f4e-451b-8f4d-5d3edea5de05)
I am not sure why this is happening, and I believe I followed all the installation steps correctly.

**Actual Behavior:**
![fig2](https://github.com/user-attachments/assets/d85e824f-8b06-488d-b589-f9a413aaa115)

![fig3](https://github.com/user-attachments/assets/02a51bf8-ce8b-4bc6-910b-cc446f1724c3)
![fig4](https://github.com/user-attachments/assets/e5a60867-5083-46ab-83d1-f5bac706ec14)

**Comment by lperron** [comment]
This is a warning. You can define the macro

**Comment by Mizux** [comment]
ref https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?view=msvc-170
