### ISSUE TITLE
DebugString[abi:cxx11] abi seems not compatible

### ISSUE THREAD

**Issue by Dufgui** [google/or-tools#4351]
**What version of OR-Tools and what language are you using?**
Version: v9.10
Language: C++
GCC: 10.4.0

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
NA

**What operating system (Linux, Windows, ...) and version?**
Linux Centos 7.9

**What did you do?**
I switch from 9.5 to 9.10 and I have the following compilation error:
`undefined reference to `google::protobuf::Message::DebugString[abi:cxx11]() const'`
when I do:
`LOG_ERROR("MY_LOG")<<response.DebugString();`

`[abi:cxx11]` seems to be error relative to ABI according to 
#https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

I build ortools like this
```
make ${ORTOOLS_SRC_DIR} -B ${ORTOOLS_BUILD_DIR} \
                -DCMAKE_C_COMPILER=${CC} \
		-DCMAKE_CXX_COMPILER=${CXX} \
		-DBUILD_DEPS=ON
```
I try to fix it, by adding 

```
make ${ORTOOLS_SRC_DIR} -B ${ORTOOLS_BUILD_DIR} \
                -DCMAKE_C_COMPILER=${CC} \
		-DCMAKE_CXX_COMPILER=${CXX} \
		-DBUILD_DEPS=ON \
		-DCMAKE_CXX_STANDARD=17 \
		-DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=1
```
But I still have this issue on my binary compilation.
I do `g++ --std=c++1z -g -O3 -fPIC -Wall -D_GLIBCXX_USE_CXX11_ABI=1 .....`

And I still have 
```
undefined reference to `google::protobuf::Message::DebugString[abi:cxx11]() const'
```

**What did you expect to see**
No error

**What did you see instead?**

```
undefined reference to `google::protobuf::Message::DebugString[abi:cxx11]() const'
```

**Anything else we should know about your project / environment**
I think it's quite the same as

https://github.com/google/or-tools/issues/592

**Comment by lperron** [comment]
OR-Tools needs and is compiled with cxx17.

**Comment by Dufgui** [comment]
Ok but I do not understood why I have this reference on cxx11 in protobuf object

**Comment by Dufgui** [comment]
We found the problem! Protobuf change his visibility.
```
    # For -fvisibility=hidden and -fvisibility-inlines-hidden
    C_VISIBILITY_PRESET hidden
    CXX_VISIBILITY_PRESET hidden
    VISIBILITY_INLINES_HIDDEN ON
```
So we must not use protobuf like my example:
```
LOG_ERROR("MY_LOG")<<response.DebugString();
```
Instead we must use content of protobuf object:
```
LOG_ERROR("MY_LOG")<<response.solution_info();
```
