### ISSUE TITLE
Routing with FirstSolutionStrategy::CHRISTOFIDES fails immediately with any large number of points

### ISSUE THREAD

**Issue by jarodhanko-crafco** [google/or-tools#4354]
**What version of OR-Tools and what language are you using?**
Version: 9.10.4096
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing with FirstSolutionSolver as CHRISTOFIDES

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 22.04

**What did you do?**
Follow tutorial code at https://developers.google.com/optimization/routing/tsp, but replacing the first solution solver as CHRISTOFIDES

**What did you expect to see**
I expected the result to take exponentially longer but with an eventual solution. I can specify a timeout, and all the other strategies will run until completion or timeout, but Christofides still fails in about 50ms.

**What did you see instead?**
Routing simply returns the failed status nearly immediately anytime there is more than 20 points as input. I have tried many different points, including different subsets of the points in the tutorial, and nothing >20 works.

Are there any hard limits on running Christofides algorithmn as the solver? I tried clearing out any default time or solution limits, but I haven't found any way around the hard 20 point limit. I am not sure if the exact limit is tied to my hardware, but I can get a solution for 20 or fewer points in less than 50ms but any more points is an immediate failure.

**Comment by lperron** [comment]
this is expected. 

The space complexity is such that > 23 is out of the question.

**Comment by jarodhanko-crafco** [comment]
Ok, thanks for the clarification. Perhaps it would be helpful to add to the documentation since I couldn't find any explanation of the limitations. Maybe I just missed it though.

**Comment by lperron** [comment]
I may be completely wrong there :-)

We will follow up.

**Comment by jarodhanko-crafco** [comment]
Did anything change on this at all, or are there any plans to? Just wanted to double check before ruling out using christofides completely
