### ISSUE TITLE
Build fails: error: unknown type name 'stderrthreshold'

### ISSUE THREAD

**Issue by yurivict** [google/or-tools#4355]
**What version of OR-Tools and what language are you using?**
Version: 9.10

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
n/a

**What operating system (Linux, Windows, ...) and version?**
FreeBSD 14.1

**What did you do?**
Regular cmake build.

**What did you expect to see**
Successful build.

**What did you see instead?**
```
In file included from /usr/ports/math/or-tools/work/or-tools-9.10/ortools/base/logging.cc:14:
/usr/ports/math/or-tools/work/or-tools-9.10/ortools/base/logging.h:27:24: error: unknown type name 'stderrthreshold'
   27 | ABSL_DECLARE_FLAG(int, stderrthreshold);
      |                        ^
/usr/ports/math/or-tools/work/or-tools-9.10/ortools/base/logging.h:27:1: error: a type specifier is required for all declarations
   27 | ABSL_DECLARE_FLAG(int, stderrthreshold);
      | ^
/usr/ports/math/or-tools/work/or-tools-9.10/ortools/base/logging.cc:37:41: error: use of undeclared identifier 'FLAGS_stderrthreshold'
   37 | void KeepAbslSymbols() { absl::SetFlag(&FLAGS_stderrthreshold, 0); }
      |                                         ^
3 errors generated.
```

**Anything else we should know about your project / environment**
abseil-20240722.0

**Comment by lperron** [comment]
Or-tools and abseil must be in lockstep. 

Try with the head of the v99buffix branch.

**Comment by yurivict** [comment]
@lperron 

The 9fa25b3 revision in the v99bugfix branch has the same problem.

> Or-tools and abseil must be in lockstep.

What does this exactly mean? Is there a list of which or-tools releases compatible with which abseil releases?

Why doesn't cmake configure fail to detect such incompatibility and suggest a solution?

We have abseil-20240722.0 available on FreeBSD, and or-tools-9.11 fails to build with it.

**Comment by lperron** [comment]
abseil breaks compatibility at each release. So we keep scrambling to patch
OR-Tools to support the latest release.

One example: in one version, abseil supported int128, but not uint128. So
we added the code in OR-Tools.
Next release, the add the support, so we must remove it.
Next release, the change the way pretty print is done with the introduction
of AbslStringify, but int128 is not covered
Next release they add it, so we must remove it.
Note that this also happened with protobuf...
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le dim. 15 sept. 2024 à 04:14, ***@***.*** ***@***.***> a
écrit :

**Comment by lperron** [comment]
that particular revision is broken. Please use the 9.11 official tag.

**Comment by yurivict** [comment]
Is the table of compatible versions published anywhere?

9.11 isn't compatible with the latest abseil-20250127.0 for the same reason.
How can one know which version are compatible?

**Comment by lperron** [comment]
No. We try to be in lockstep. Abseil breaks API compatibility with most
releases.

see https://github.com/google/or-tools/releases/tag/v9.11

We are releasing 9.12 today. It will not be compatible either. The fix
should be to remove status_matchers from ortools/base and use the abseil
ones in math_opt.
We will start this right away.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le lun. 17 févr. 2025 à 10:55, ***@***.*** ***@***.***> a
écrit :

**Comment by Mizux** [comment]
> Is the table of compatible versions published anywhere?

While we don't have a "compatibility table" you can look at
`Dependencices.txt` or `cmake/dependencies/CMakeLists.txt` file to get the version of abseil-cpp we use to build each release...

e.g. for v9.12 tag:
https://github.com/google/or-tools/blob/b8e881fbde473a9e33e0dac475e498559eb0459d/cmake/dependencies/CMakeLists.txt#L85-L91
and
https://github.com/google/or-tools/blob/b8e881fbde473a9e33e0dac475e498559eb0459d/Dependencies.txt#L2

**Comment by yurivict** [comment]
The build of 9.12 fails with the same error when I use the externally installed abseil-20240722.0

**Comment by lperron** [comment]
So two components define the same -v flag ?

Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00


Le lun. 17 févr. 2025, 19:06, ***@***.*** ***@***.***> a
écrit :
