### ISSUE TITLE
swig error when building from Source

### ISSUE THREAD

**Issue by bunelr** [google/or-tools#437]
Hello,

I am attempting to build or-tools from source, on Ubuntu 14.04.
I am doing everything inside a virtualenv, with python3.6 as my version of python. I have tried both cloning the repository and downloading the release from the [release page](https://github.com/google/or-tools/releases/tag/v6.2)
I am following the instructions from [here](https://developers.google.com/optimization/introduction/installing.html#unix_source) and have additionally installed `swig` from the ubuntu repositories as it seemed necessary

`make third_party` and `make cc` both run fine without errors but I start to encounter troubles when I run `make python`

```
$ make python
swig -I. -c++ -python -py3 -DPY3 -o ortools/gen/ortools/constraint_solver/constraint_solver_python_wrap.cc -module pywrapcp ./ortools/constraint_solver/python/routing.i
ortools/constraint_solver/constraint_solver.h:267: Warning 325: Nested struct not currently supported (IntegerCastInfo ignored)
ortools/constraint_solver/constraint_solver.h:1756: Error: Syntax error in input(3).
make: *** [ortools/gen/ortools/constraint_solver/pywrapcp.py] Error 1
```

I get the same output if I run the swig command by itself. The place at which the error points is [here](https://github.com/google/or-tools/blob/master/ortools/constraint_solver/constraint_solver.h#L1756), which judging by the `define` is some swig related code.

Is there something that I'm doing wrong?

In case it helps:

```
$ swig -version

SWIG Version 2.0.11

Compiled with g++ [x86_64-unknown-linux-gnu]

Configured options: +pcre

$ python --version
Python 3.6.1+

```

Let me know if I can provide more information.

**Comment by lperron** [comment]
You need swig 3.0.


You can have a look at tools/docker

If you have docker installed, it will build python modules, binary archives
easily.
The Ubuntu14.04 dockerfile also tells you how to build the or-tools from
source.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-07-20 3:45 GMT-07:00 Rudy Bunel <notifications@github.com>:

**Comment by bunelr** [comment]
Thank you for the quick reply, that was the problem!

Are the [installation instructions](https://developers.google.com/optimization/introduction/installing) somewhere where I could send a pull request to update the documentation?
