### ISSUE TITLE
Model is feasible in 9.8 but infeasible in 9.10. Disabling presolve in 9.10 makes the model feasible again.

### ISSUE THREAD

**Issue by aleberr** [google/or-tools#4370]
**What version of OR-Tools and what language are you using?**
Version: 9.10
Language: Python

I'm using the CP-SAT solver on Windows 11.

Use [this model](https://github.com/user-attachments/files/16955781/model9p10.txt) and this code:
```
from google.protobuf.text_format import Parse
from ortools.sat.python import cp_model

file_path = "model9p10.txt"

with open(file_path, "r") as file:
    s = file.read()

model = cp_model.CpModel()
Parse(s, model.Proto())
solver = cp_model.CpSolver()

status1 = solver.Solve(model)
print("Solved the model and got status", solver.StatusName(status1))


# Now do the same but disable the presolve

model = cp_model.CpModel()
Parse(s, model.Proto())
solver = cp_model.CpSolver()
solver.parameters.cp_model_presolve = False

status2 = solver.Solve(model)
print("Solved the model and got status", solver.StatusName(status2))
```

The first status is infeasible ("closed by presolve") and the second one is optimal.

Additionally, if I use the code that I used to generate the above model to generate and solve the model in 9.8 ([here](https://github.com/user-attachments/files/16955785/model9p8.txt)), then both statuses are optimal. Note: [as of 9.10, the linear part of intervals is handled in the presolve](https://github.com/google/or-tools/commit/382ab5d35beaa984ee20b1429e3abbdda86f9df2), and this causes some differences between the model protos generated for each version.

**Comment by lperron** [comment]
Returns optimal on the v99bugfix branch which will be release 9.11
