### ISSUE TITLE
Active Test runner crashed with  OR-Tools 9.10.4067/v9.9.3963/v9.8.3296 working fine with v8.1.8487

### ISSUE THREAD

**Issue by JharPaat** [google/or-tools#4371]
**OR-Tools C#**
Version: CP-SAT solver v9.10.4067/v9.9.3963/v9.8.3296.
Language: C#

**CP-SAT**

**Windows 10 Enterprise 22H2 19045.4651 
Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.11.3 **

**For some of the unit test which are running fine on previous version(v8.1.8487) are crashing in CpSolver.Solve(CpModel model, SolutionCallback cb = null)  with newer version of  OR-Tools 9.10.4067/v9.9.3963/v9.8.3296**

**Test run should **NOT** be crashed stopping the other test to run complete**

**Currently 80% (total 420) are passing and when running some tests Active Test runner was crashed and no further run possible**

Please find the test output error in the attachment.
[RawModel.txt](https://github.com/user-attachments/files/16975759/RawModel.txt)
[Test host process crash log.txt](https://github.com/user-attachments/files/16975762/Test.host.process.crash.log.txt)

**Comment by lperron** [comment]
can you send us the proto of the model that crashes ?

**Comment by JharPaat** [comment]
Please find RawModel as follows:
[RawModel.txt](https://github.com/user-attachments/files/16975770/RawModel.txt)

**Comment by lperron** [comment]
Please use model.ExportToFile('issue4371.pb.txt') or equivalent according
to the language you are using.

RawModel.txt contains text, data,...
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by lperron** [comment]
And it contains multiple models.

Which one is failing ?
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by JharPaat** [comment]
We are using CpSolver.Solve(CpModel model, SolutionCallback cb = null) CpSolverSolutionCallback. 
It is failing on **model7_issue4371.pb.txt**
Please find all models in the attachments
[issue4371_ModelExport.zip](https://github.com/user-attachments/files/16979101/issue4371_ModelExport.zip)

**Comment by lperron** [comment]
I ran all models, and the number 7 100 times without a crash on the main
branch.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by lperron** [comment]
without a crash. So I will assume the bug is fixed. When 9.11 is out
(soon), please test again.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
