### ISSUE TITLE
How to disable HiGHS logs? 

### ISSUE THREAD

**Issue by quantcn** [google/or-tools#4377]
I use ortools 9.11.421, python api. I use solver HiGHS as follows, I didn't set solver.EnableOutput():
solverType = "HiGHS" 
solver = pywraplp.Solver.CreateSolver(solverType)

when solving, it always output logs as follows, How to disable this logs? 
variable_value: 0
variable_value: 1
variable_value: 0
variable_value: 1
variable_value: 1
variable_value: 1
variable_value: 1
variable_value: 1
variable_value: 1
variable_value: 0
...

**Comment by lperron** [comment]
highs is not supported with pywraplp. I am not sure what the code is doing. But do not use it.

**Comment by lperron** [comment]
It is incomplete. There are a few TODOs in the code (names, some returns status,  indicator constraints).
