### ISSUE TITLE
Resource ortools-darwin/ was not found in ClassLoader

### ISSUE THREAD

**Issue by rathee1x** [google/or-tools#4381]
Version: v9.11.4210
Language: Java
Mac OS (aarch64)

<img width="364" alt="Screenshot 2024-09-20 at 2 35 52 AM" src="https://github.com/user-attachments/assets/b60eac05-a787-4e66-827c-b6c101d6896e">

<img width="1148" alt="Screenshot 2024-09-20 at 2 36 14 AM" src="https://github.com/user-attachments/assets/83b818e4-4456-4086-9c37-6dd2618f43f3">

<img width="563" alt="Screenshot 2024-09-20 at 2 36 48 AM" src="https://github.com/user-attachments/assets/3f9aa214-ba34-4df5-854e-2edce2c5d683">

Platform.Resource_prefix says darwin, I think it needs to say darwin-aarch64 to read the correct resource folder. not able to understand what the issue is, ortools Loader class looks fine.

getting this error in both cases i.e., mvn clean install and even when running the JUnit independently. 

Please advise.

**Comment by Mizux** [comment]
did you use Spring ? AFAIK it is changing the root dir so our loader didn't work with it in a project.

**Comment by jehadnasser** [comment]
I downgrade from 9.11.4210 to 9.5.2237 and it works fine

`<dependency>
            <groupId>com.google.ortools</groupId>
            <artifactId>ortools-java</artifactId>
            <version>9.5.2237</version>
</dependency>`

**Comment by Mizux** [comment]
IIRC jna-platform change the prefix return when they integrate the M1 few years ago to make difference between x86_64 and aarch64 (M1+).

I would say 9.5.2237 use an older loader.java and jna-platform which was only returning `darwin`. Try to verify if the jna deps is correctly loaded or if an other deps load a previous version...

note: you may try to create a small example on your machine to confirm this hypothesis...
