### ISSUE TITLE
MPS reader parses wrong objective sense without new line

### ISSUE THREAD

**Issue by torressa** [google/or-tools#4386]
**What version of OR-Tools and what language are you using?**

Version: v9.11.
Language: all

**What did you do?**

1. save an MPS file as:

```raw
NAME          SupportedMaximizationProblem
OBJSENSE MAX
ROWS
 N  COST
COLUMNS
    X_ONE   COST         1
BOUNDS
 UP BOUND   X_ONE        4
ENDATA
```

Similar to the [test_import_from_mps_string](https://github.com/google/or-tools/blob/ed94162b910fa58896db99191378d3b71a5313af/ortools/linear_solver/python/model_builder_test.py#L143) but without the new line after the `OBJSENSE`. 

2. Read this using `model.import_from_mps_file(mps_file)` (or `import_from_mps_string`)
3. Solve. 

**What did you expect to see**

The problem is correctly read as a maximization problem and solving it leads to an objective value of 4.0, not 0.0 (minimization). Please update the parser and tests to account for this as this is common MPS syntax.

**Comment by lperron** [comment]
I can support this, but this is not in the CPLEX, Mosek or LPSolve doc.
Gurobi is not precise.

So who generates this kind of MPS ?

**Comment by torressa** [comment]
Gurobi and Xpress both use this.
