### ISSUE TITLE
MakeModulo affecting variable domain 

### ISSUE THREAD

**Issue by Hanamuke** [google/or-tools#439]
Hello,
I am running or-tools 6.2 on Ubuntu 17.04. I am using a constant seed (0) for the solver's RNG.

I have implemented a custom decision builder, nothing complex. I've spotted that when using 
`IntExpr *foo = s.MakeModulo(vars[i], N);`
in my constraint generation routine, where N is a preprocessor constant, the search tree is vastly different, although the solver contains the exact same constraints and varibales. I'm not adding a constraint to the solver/model, but just declaring (IntExpr* foo) and i'm not using it any further. 

It's quite hard to pinpoint where the solver starts to behave differently, but i observe that none of the variables take negative values anymore. Is it possible that MakeModule is in fact not usable with variables whose domains contain negative numbers ?

Thank you.

**Comment by Hanamuke** [comment]
Edit : I tried, to used the default decision builder, with variable that have only negative values in their domain. A solution is found when `IntExpr *foo = s.MakeModulo(vars[i], N);` is commented, and no solution is found when it is uncommented. There clearly seems to be a bug/undocumented behaviour with MakeModulo on negative values.

**Comment by lperron** [comment]
Hi, 

two comments.

yes, creating the expression will constrain the domain. This is a weakness of the design of the CP solver. There are no easy way around.

Now, there are two semantics for modulo, and I believe I have implemented the less common one w.r.t. negative numbers.

One idea would be to use abs, to compute modulo on positive value, and then sign it accordingly.
Another solution is to create a AllowedAssignment constraint with positive tuples, provided the domains are not too big.
