### ISSUE TITLE
HIGHS DEBUG Optimization RUN always DFATAL because of  response->has_solver_specific_info() returns false

### ISSUE THREAD

**Issue by lmw-untis** [google/or-tools#4393]
**What version of OR-Tools and what language are you using?**
Version: v9.11
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
HIGHS

**What operating system (Linux, Windows, ...) and version?**
Windows and Linux v9.11 Debug x64

**What did you do?**
Run in Debug x64 Build
```cpp
#include <omp.h>
#include "iostream"
#include <ortools/base/logging.h>
#include <ortools/linear_solver/linear_solver.h>

double run(operations_research::MPSolver::OptimizationProblemType problemType, bool log)
{
    // Create the linear solver with the GLOP backend.
    operations_research::MPSolver solver("simple_lp_program", problemType);

    // Create the variables x and y.
    auto *const x = solver.MakeNumVar(0.0, 1, "x");
    auto *const y = solver.MakeNumVar(0.0, 2, "y");

    if (log)
        LOG(INFO) << "Number of variables = " << solver.NumVariables();

    // Create a linear constraint, 0 <= x + y <= 2.
    auto *const ct = solver.MakeRowConstraint(0.0, 2.0, "ct");
    ct->SetCoefficient(x, 1);
    ct->SetCoefficient(y, 1);

    if (log)
        LOG(INFO) << "Number of constraints = " << solver.NumConstraints();

    // Create the objective function, 3 * x + y.
    operations_research::MPObjective *const objective = solver.MutableObjective();
    objective->SetCoefficient(x, 3);
    objective->SetCoefficient(y, 1);
    objective->SetMaximization();

    solver.Solve();

    if (log)
    {
        LOG(INFO) << "Solution:" << std::endl;
        LOG(INFO) << "Objective value = " << objective->Value();
        LOG(INFO) << "x = " << x->solution_value();
        LOG(INFO) << "y = " << y->solution_value();
    }

    return y->solution_value();
}

int main()
{
    bool log_output = true;
    absl::SetFlag(&FLAGS_stderrthreshold, true);
    std::cout << "HIGHS" << std::endl;
    auto certificate = run(operations_research::MPSolver::HIGHS_LINEAR_PROGRAMMING, log_output);
    std::cout << "\n\n\n"
              << std::endl;
    return EXIT_SUCCESS;
}
```

**What did you expect to see**
Return EXIT_SUCCESS

**What did you see instead?**

> Running HiGHS 1.7.2 (git hash: 5ce7a275): Copyright (c) 2024 HiGHS under MIT licence terms
> F0000 00:00:1727692120.824884   12772 highs_interface.cc:166] status: MPSOLVER_OPTIMAL
> objective_value: 4
> variable_value: 1
> variable_value: 1
> dual_value: 2
> best_objective_bound: 4
> solve_info {
>   solve_wall_time_seconds: 0.000685164
>   solve_user_time_seconds: 0.000685976
> }
> *** Check failure stack trace: ***
>     @     0x5572e501f42b  absl::lts_20240722::log_internal::LogMessage::PrepareToDie()
>     @     0x5572e501f4a3  absl::lts_20240722::log_internal::LogMessage::SendToLog()
>     @     0x5572e501eebf  absl::lts_20240722::log_internal::LogMessage::Flush()
>     @     0x5572e501e236  absl::lts_20240722::log_internal::LogMessage::~LogMessage()
>     @     0x5572e40216c8  operations_research::HighsInterface::Solve()
>     @     0x5572e389234d  operations_research::MPSolver::Solve()
>     @     0x5572e389229a  operations_research::MPSolver::Solve()
>     @     0x5572e3887793  run()
>     @     0x5572e3887c5c  main
>     @     0x7efe0f9b71ca  (unknown)
>     @     0x7efe0f9b728b  __libc_start_main
>     @     0x5572e38872f5  _start

Fatal Error through Line 166 in highs_interface.cc

I also don't see any code that sets response->set_solver_specific_info() in any case in the HIGHS Solve in highs_proto_solver.cc
Please tell me what the reason is for this DFATAL Log

**Comment by lperron** [comment]
Highs is not supported in MPSolver.
It is partiallly supported in ModelBuilder.
It has a better support with MathOpt. But we have memory errors.
