### ISSUE TITLE
or-tools_VisualStudio2017-64bit_v6.3.4431 windows  problem. compiled, but binaries don't work

### ISSUE THREAD

**Issue by CnApTaK** [google/or-tools#440]
`G:\or-tools_VisualStudio2017-64bit_v6.3.4431\examples\csharp\solution\bin\x64\Release>G:\or-tools_VisualStudio2017-64bit_v6.3.4431\examples\csharp\solution\bin\x64\Release\Cscvrptw.exe
Building orders.
Building fleet.
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Google.OrTools.dll' or one of its dependencies. The specified module could not be found.
   at CapacitatedVehicleRoutingProblemWithTimeWindows.Solve(Int32 number_of_orders, Int32 number_of_vehicles)
   at CapacitatedVehicleRoutingProblemWithTimeWindows.Main(String[] args) in G:\or-tools_VisualStudio2017-64bit_v6.3.4431\examples\csharp\cscvrptw.cs:line 345`
but dll is there.. in the same folder with exe

**Comment by CnApTaK** [comment]
doing the same with previous version don't cause any problems... i can see result of runnig exe:
Building orders.
Building fleet.
Creating model with 100 orders and 20 vehicles.
Search
Total cost: 529
Vehicle 0: Empty
Vehicle 1: Empty
...

**Comment by lperron** [comment]
and nothing has changed in the way we build these libraries :-(

I will debug that.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-08-02 10:13 GMT-07:00 CnApTaK <notifications@github.com>:

**Comment by lperron** [comment]
the dll is build on visual studio 2015.
Can you try adding the vs2015 redistributable libraries?

**Comment by CnApTaK** [comment]
you mean vc2015?
i have only vs2017
and vc2015 libraries wont install.. Error 0x80070666: Cannot install a product when a newer version is installed. vc2017 installed

**Comment by lperron** [comment]
Ok. just checking, did you try to install these:

https://www.microsoft.com/en-us/download/details.aspx?id=48145

Thanks

**Comment by CnApTaK** [comment]
yes. exactly.

**Comment by lperron** [comment]
I just released version 6.4.

Can you try again?

Thanks
