### ISSUE TITLE
StrongVector iterators do not work with std::shuffle

### ISSUE THREAD

**Issue by vuongdanghuy** [google/or-tools#4404]
**What version of OR-Tools and what language are you using?**
Version: v9.11
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
GLOP

**What operating system (Linux, Windows, ...) and version?**
Linux Mint 21.3

**What did you do?**
1. Create an **ColumnPermutation** with arbitraty size n
2. Populate the permutation by calling **PopulateRandomly()** method. This will first populate the **perm_** vector with value from 0 to n - 1 and then shuffle it

**What did you expect to see**
Compile successfully

**What did you see instead?**
error: no matching function for call to ‘shuffle(std::vector<operations_research::StrongIndex<operations_research::glop::ColIndex_index_tag_> >::iterator, std::vector<operations_research::StrongIndex<operations_research::glop::ColIndex_index_tag_> >::iterator)’

Make sure you include information that can help us debug (full error message, model Proto).

Minimum sample code
```cpp
#include <iostream>

#include "ortools/lp_data/lp_data.h"
#include "ortools/lp_data/lp_types.h"
#include "ortools/lp_data/permutation.h"

namespace mio {
using namespace operations_research::glop;

void TestPermutation() {
  ColumnPermutation col_permution(ColIndex(4));
  col_permution.PopulateRandomly();
  std::cout << "Column permutation:\n";
  for (ColIndex i(0); i < col_permution.size(); ++i) {
    std::cout << col_permution[i] << ", ";
  }
  std::cout << '\n';
}

}

int main(int argc, char *argv[]) {
  using namespace mio;
  TestPermutation();
  return 0;
}
```

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
Actually, this function is not used.
We might just remove it.

**Comment by lperron** [comment]
In compiles fine on mac.

**Comment by vuongdanghuy** [comment]
That's weird. In order to make the code work, i need to change the source code to something like this
```cpp
template <typename IndexType>
void Permutation<IndexType>::PopulateRandomly() {
  PopulateFromIdentity();
  std::random_device rd;
  std::mt19937 g{rd()};
  std::shuffle(perm_.begin(), perm_.end(), g);
}
```
The signature of [std::shuffle](https://en.cppreference.com/w/cpp/algorithm/random_shuffle) also requires a third generator object.

Which code compiles fine on your mac? The whole library also compiles fine on my machine whether the generator object **g** is passed or not. But the sample code is not. I don't have a mac to test though.

Actually I am playing around with the source code to understand it. So if this function is not important and will be removed, feel free to ignore this issue :))

**Comment by lperron** [comment]
I compiled and executed the code that calls the PopulateRandomly.

Le mer. 9 oct. 2024, 06:07, Mio The Best Girl ***@***.***> a
écrit :

**Comment by vuongdanghuy** [comment]
Oh, I think it's because you're on the 'main' branch and I'm on v9.11 branch :))
On the main branch a generator is already passed to std::shuffle
https://github.com/google/or-tools/blob/792e3362b7e29c943fda9b826959edf6e5a818c3/ortools/lp_data/permutation.h#L154-L158
I'll close the issue.
