### ISSUE TITLE
Have problem running my_program

### ISSUE THREAD

**Issue by Yifan-Tang** [google/or-tools#441]
I was trying to run my_program as the tour Guide shows, but it showed me this error:

```
clang++ -fPIC -std=c++11 -O4 -DNDEBUG -Iinclude -I. -DARCH_K8 -Wno-deprecated -DUSE_CBC -DUSE_CLP -DUSE_GLOP -DUSE_BOP -c Netlib_Test.cc -o objs/Netlib_Test.o
clang++ -fPIC -std=c++11 -O4 -DNDEBUG -Iinclude -I. -DARCH_K8 -Wno-deprecated -DUSE_CBC -DUSE_CLP -DUSE_GLOP -DUSE_BOP objsetlib_Test.o -Wl,-rpath /Users/tang/Desktop/Solver/or-tools_MacOsX/lib -L/Users/tang/Desktop/Solver/or-tools_MacOsX/lib -lortools -Wl,-rpath /Users/tang/Desktop/Solver/or-tools_MacOsX/lib -L/Users/tang/Desktop/Solver/or-tools_MacOsX/lib -lcvrptw_lib -Wl,-rpath /Users/tang/Desktop/Solver/or-tools_MacOsX/lib -L/Users/tang/Desktop/Solver/or-tools_MacOsX/lib -lortools -Wl,-rpath /Users/tang/Desktop/Solver/or-tools_MacOsX/lib -L/Users/tang/Desktop/Solver/or-tools_MacOsX/lib -ldimacs -Wl,-rpath /Users/tang/Desktop/Solver/or-tools_MacOsX/lib -L/Users/tang/Desktop/Solver/or-tools_MacOsX/lib -lortools \
	-Wl,-rpath /Users/tang/Desktop/Solver/or-tools_MacOsX/lib -L/Users/tang/Desktop/Solver/or-tools_MacOsX/lib -lfap -Wl,-rpath /Users/tang/Desktop/Solver/or-tools_MacOsX/lib -L/Users/tang/Desktop/Solver/or-tools_MacOsX/lib -lortools  -o binetlib_Test
clang: error: no such file or directory: 'objsetlib_Test.o'
make: *** [bin/Netlib_Test] Error 1
```

I don't know how to fix it, how to workaround it?

**Comment by lperron** [comment]
It does not find objsetlib_Test.o, there is a problem in your command line.

Anyway, this is not part of or-tools, so check your files.

--Laurent

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-08-02 19:37 GMT-07:00 Yifan-Tang <notifications@github.com>:

**Comment by Yifan-Tang** [comment]
I'm using macOS and I have installed xcode-select as the Guide says, are there anything more I need to install?

**Comment by lperron** [comment]
but binnetlib_Test, objsetlib_test are not part of or-tools.
So please check this part of the makefiles.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-08-02 22:16 GMT-07:00 Yifan-Tang <notifications@github.com>:

**Comment by Yifan-Tang** [comment]
Oh, I found the problem. I change the name "my_program" to other name, and I also changed the instances of my_program in Makefile.user. Then it doesn't work, I changed the name back to my_program and it works, thank you!
