### ISSUE TITLE
Segmentation fault running CP-SAT with 1 worker using free-search in 9.11

### ISSUE THREAD

**Issue by CervEdin** [google/or-tools#4412]
**What version of OR-Tools and what language are you using?**
Version: 9.11
Language: flatzinc

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 22.04 Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 GNU/Linux

**What did you do?**
Working on steps to create repro but it's hard.
I originally posted the issue in MiniZinc
https://github.com/MiniZinc/libminizinc/issues/855
I'm working on getting a flat-zinc file I can share.

The segfault only happens when using 1 thread, free-search and not displaying all solutions `fzn-cp-sat -p 1 -f`
```
%% Starting CP-SAT solver v9.11.4210
%% Parameters: log_search_progress: true search_branching: AUTOMATIC_SEARCH interleave_search: true log_to_stdout: false max_domain_size_when_encoding_eq_neq_constraints: 32 num_workers: 1 subsolvers: "default_lp" subsolvers: "fixed" subsolvers: "core_or_no_lp" subsolvers: "max_lp"
```

**What did you expect to see**

In 9.10 the log looks like this
```
%% #Bound   8.85s best:inf   next:[408,3757] default_lp (initial_propagation)
%% #Model   8.86s var:6181/7068 constraints:10417/11543 compo:6175,3,3
%% #1      15.49s best:1986  next:[408,1985] default_lp (fixed_bools=1043/8783)
%% #Model  16.07s var:4701/7068 constraints:8651/11543 compo:4695,3,3
%% #2      16.25s best:408   next:[]         fixed (fixed_bools=2800/8785)
%% #Done   16.25s fixed
```

**What did you see instead?**
In 9.11 the log looks like this
```
%% #Bound   8.81s best:inf   next:[408,3757] default_lp (initial_propagation)
%% #1      15.00s best:1986  next:[408,1985] default_lp (fixed_bools=1043/8675)
```
followed by a segfault

**Anything else we should know about your project / environment**

I will work on getting a flatzinc file that I can share to repro.

**Comment by CervEdin** [comment]
Seems related to #4400, if I set ` --params 'use_lns_only:true'` I get a segfault but I don't if I `--params 'use_lns:false`

**Comment by lperron** [comment]
I still need a fzn or a model. You can run --cp_model_dump_models and send me the /tmp/model.pb.txt (if on linux/mac)

**Comment by CervEdin** [comment]
I think I have managed to narrow down the issue, the segfault seems to happen here
https://github.com/google/or-tools/blob/ed94162b910fa58896db99191378d3b71a5313af/ortools/sat/cp_model_solver.cc#L1362C1-L1364C74
because the `shared_->bounds` is `nullptr`.

See
https://github.com/google/or-tools/pull/4413
but I suspect there is a better (and prefer solution)

I think this is happening because bounds sharing is disabled
https://github.com/google/or-tools/blob/ed94162b910fa58896db99191378d3b71a5313af/ortools/sat/cp_model_solver_helpers.cc#L1762C1-L1767C4
so I suspect the `SharedBoundsManager` is not initialized here
https://github.com/google/or-tools/blob/ed94162b910fa58896db99191378d3b71a5313af/ortools/sat/cp_model_solver_helpers.cc#L1780C1-L1784C4

Sharing the model dump of the smallest repro I could produce
[bug.pb.txt](https://github.com/user-attachments/files/17392443/bug.pb.txt)

This error is hard to reproduce.
Things like changing the order of variables/constraints was enough to trigger the segfault or not.

I can probably share a bigger/other repro if needed
