### ISSUE TITLE
CP-SAT: Parameter for symmetry finding dtime limit

### ISSUE THREAD

**Issue by iamthad** [google/or-tools#4419]
**What language and solver does this apply to?**
All languages, CP-SAT

**Describe the problem you are trying to solve.**
Symmetry finding can be forced on for large problems by setting `symmetry_level:3`. However, it will time out after a hard-coded 1 second of deterministic time, which is identified as an [error during the initial refinement](https://github.com/google/or-tools/blob/stable/ortools/algorithms/find_graph_symmetries.cc#L469-L472). This prevents symmetry finding from actually working in large enough problems and seems to reduce the value of `symmetry_level:3`.

**Describe the solution you'd like**
Expose a parameter in `sat_parameters.proto` to allow configuring the deterministic time limit for symmetry finding.

**Describe alternatives you've considered**
- Increase the hard-coded value. This doesn't seem like a good idea to me; presumably the original time limit had some justification.
- Disable the time limit when `symmetry_level > 2`. I am not sure if this is possible, and it seems like _some_ time limit might still be desired.
- Do nothing. This would prevent large enough problems from benefit from symmetry finding even when the user has attempted to force it by setting `symmetry_level` to 3

**Additional context**
I have tried increasing the hard-coded limit locally and found that at least for my particular problem, doing so results in a substantial net decrease in solve time.
The hardcoded time limits are defined at [`cp_model_symmetries.cc:749`](https://github.com/google/or-tools/blob/stable/ortools/sat/cp_model_symmetries.cc#L749) and [`cp_model_symmetries.cc:936`](https://github.com/google/or-tools/blob/stable/ortools/sat/cp_model_symmetries.cc#L936).

**Comment by CervEdin** [comment]
I'll piggy back on this to ask the question regarding

>   // breaking during search. At level 3, we also detect symmetries for very
>   // large models, which can be slow. At level 4, we try to break as much

https://github.com/google/or-tools/blob/ed94162b910fa58896db99191378d3b71a5313af/ortools/sat/sat_parameters.proto#L1312C30-L1313C18

What is a "large model"?
Is it determined by this timeout or the amount of variables or something else?

**Comment by lperron** [comment]
https://github.com/google/or-tools/blob/stable/ortools/sat/cp_model_symmetries.cc#L671  -> size

I have pushed the new parameter.
