### ISSUE TITLE
Won't install in a clean Windows machine with python 3.13

### ISSUE THREAD

**Issue by ericoporto** [google/or-tools#4422]
running `pip install ortools` fails in a new machine using python 3.13, can you provide a new release that includes also python 3.13? Thanks!

**Comment by lperron** [comment]
planned

**Comment by ericoporto** [comment]
Any idea when it would be released? Is this project main branch always in release state?

**Comment by lperron** [comment]
Main is completely broken.

We have been trying to fix it for for at least 2 weeks.

We will release from the v99bugfix branch, which is equally broken.

Le mer. 23 oct. 2024, 21:08, Érico Porto ***@***.***> a
écrit :
