### ISSUE TITLE
VRP: Solves with soft bounds and breaks fail

### ISSUE THREAD

**Issue by AdamLithgow** [google/or-tools#4423]
**What version of OR-Tools and what language are you using?**
Version: 9.11
Language: C#

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing Solver

**What operating system (Linux, Windows, ...) and version?**
Windows 11 Pro version 10.0.26100 Build 26100

**What did you do?**
Set up a solution with a time dimension, pickup/deliveries, time windows, and a break.
Add a soft upper/lower bound for all transit nodes.
Add disjunction to allow all transit nodes to be optional (I used a drop penalty of 10,000 in my case)

I've included a sample repo showing the exact setup I'm using and problem I'm running into.
Simply pull the repo and run: https://github.com/AdamLithgow/OrToolsBugDemo

**What did you expect to see**
The solve should succeed, all nodes should be visited, and the break should be taken

**What did you see instead?**
On versions 9.6-9.11, this results in a "ROUTING_FAIL" status. On version 8.0-9.5, this results in a "ROUTING_PARTIAL_SUCCESS_LOCAL_OPTIMUM_NOT_REACHED". However, on version 7.8, this solve gives a "ROUTING_SUCCESS" status as expected.

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
I've tried doing crazy things that still result in no solve being found, such as:
- Making the time dimension's slack time in the dozens of hours
- Making the break duration 0
- Making the break's window larger than the route's run window
- Making the break optional
- Setting the coefficient of the soft bound to 0

Doing any, or even all, of these still results in no solution being found, or any change in status at all. On versions newer than 7.8, the only thing that seems to work is removing either the break or the soft bounds on the transit nodes.

**Comment by Mizux** [comment]
remove the `17216` "prefix" i.e. simply offset value

```diff
%git diff
diff --git a/OrToolsBugDemo/Program.cs b/OrToolsBugDemo/Program.cs
index 0adeac1..fc9d937 100644
--- a/OrToolsBugDemo/Program.cs
+++ b/OrToolsBugDemo/Program.cs
@@ -19,10 +19,10 @@ class Program
 
                long[,] timeWindows =
                {
-                       { 1721638800, 1721665800 },
-                       { 1721638800, 1721665800 },
-                       { 1721649252, 1721652792 },
-                       { 1721651640, 1721653440 },
+                       { 38800, 65800 },
+                       { 38800, 65800 },
+                       { 49252, 52792 },
+                       { 51640, 53440 },
                };
 
                int[][] pickupDropOffs = [[2, 3]];
@@ -49,7 +49,7 @@ class Program
                routing.AddDimensionWithVehicleCapacity(
                        transitTimeCallbackIndex,                                               // transit callback
                        5400,                                                                   // allow waiting time
-                       [1721665800],                                                                         // vehicle maximum capacities - this is the vehicle end time
+                       [65800],                                                                              // vehicle maximum capacities - this is the vehicle end time
                        false,                                          // start cumul to zero - determines if the cumulative variable is set to zero at the start of each vehicle's route
                        "Time"
                );
@@ -119,8 +119,8 @@ class Program
                for (var i = 0; i < manager.GetNumberOfVehicles(); i++)
                {
                        IntervalVar breakVarOfVehicle = solver.MakeFixedDurationIntervalVar(
-                               start_min: 1721646300,
-                               start_max: 1721649600,
+                               start_min: 46300,
+                               start_max: 49600,
                                duration: 1800,
                                optional: false,
                                name: $"Route{i}Break"
@@ -275,4 +275,4 @@ class Program
                        _ => "UNKNOWN_STATUS"
                };
        }
-}
\ No newline at end of file
+}
```

```sh
dotnet run -r linux-x64 -c Release 
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1729844451.850910 3917678 routing.cc:2767] All Unperformed Solution (48400, time = 5 ms, memory used = 65.17 GB)
I0000 00:00:1729844451.851047 3917678 search.cc:285] Start search (memory used = 65.17 GB)
I0000 00:00:1729844451.851121 3917678 search.cc:285] Root node processed (time = 0 ms, constraints = 42, memory used = 65.17 GB)
I0000 00:00:1729844451.855549 3917678 search.cc:285] Solution #0 (32016, time = 4 ms, branches = 36, failures = 0, depth = 33, memory used = 65.17 GB, limit = 0%)
I0000 00:00:1729844451.856534 3917678 search.cc:285] Finished search tree (time = 5 ms, branches = 71, failures = 36, neighbors = 13, filtered neighbors = 0, accepted neigbors = 0, memory used = 65.17 GB)
I0000 00:00:1729844451.856583 3917678 search.cc:285] End search (time = 5 ms, branches = 71, failures = 36, memory used = 65.17 GB, speed = 14200 branches/s)
ROUTING_SUCCESS
Objective: 32016
Dropped nodes:

Route 0:
Break start: 1/1/1970 12:51:40 PM
0 -> 
    Arrival: 1/1/1970 1:28:42 PM
    Departure: 1/1/1970 1:28:42 PM
    Elapsed: 00:00:00
2 -> 
    Arrival: 1/1/1970 1:40:52 PM
    Departure: 1/1/1970 1:40:52 PM
    Elapsed: 00:00:00
Break end: 1/1/1970 2:16:40 PM
3 -> 
    Arrival: 1/1/1970 2:20:40 PM
    Departure: 1/1/1970 2:20:40 PM
    Elapsed: 00:00:00
1 -> 
    Arrival: 1/1/1970 2:27:00 PM
    Departure: 1/1/1970 2:27:00 PM
    Elapsed: 00:00:00
Distance of the route: 15.10m
Time of the route: 00:58:18


Total Distance of all routes: 15.10m
Total time of all routes: 00:58:18
```

**Comment by AdamLithgow** [comment]
The number I'm using is the number of seconds since epoch. Is there a particular reason this would work in the earlier version, but not the current one? I'm not trying to refute this. I'm very glad there's a way to get it to work on the newer version. I'm just trying to understand, so I can avoid similar issues in the future.

**Comment by Mizux** [comment]
Your numbers are close to max `int32_t` so maybe internally some limit/clamp have been tweak thus the behavior you saw...
