### ISSUE TITLE
Fixed non zero demand at depot in routing solver

### ISSUE THREAD

**Issue by arnabanimesh** [google/or-tools#4424]
**What language and solver does this apply to?**
All

**Describe the problem you are trying to solve.**

Pickup some items from depot and deliver those items to the delivery locations. Some items will get picked up from those delivery locations too for delivery at the depot. The model only has to care about the difference between delivery and pick up quantities at each location. So it is not an issue.

**Describe the solution you'd like**
set cumulvar at location just after a location (e.g. the location visited just after depot should have a capacity cumulvar of depot demand)

**Describe alternatives you've considered**
Create dummy locations with demand as the demand at the depot, set route restrictions so that these new dummy locations are only visited just after visiting depots (both route start and reload depots similar to the cvrp_reload example). The conditions are complex to model, the solver becomes very slow and reloads don't happen properly.

Model custom routing solver using CP-SAT. It is the last resort.

**Additional context**
NA

**Comment by lperron** [comment]
This is not an issue. Please use discussions

**Comment by arnabanimesh** [comment]
Converted it to a discussion #4425
