### ISSUE TITLE
cp_model_presolve=True, model is infeasible, cp_model_presolve=False, model is feasible

### ISSUE THREAD

**Issue by disonvon** [google/or-tools#4426]
[test_presolve.pd.txt](https://github.com/user-attachments/files/17550492/test_presolve.pd.txt)
**What version of OR-Tools and what language are you using?**
Version: 9.10.4067
Language: C++/Java/Python/C#
Python
**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT
**What operating system (Linux, Windows, ...) and version?**
Mac Os
**What did you do?**
for the attached model file, when cp_model_presolve=True, the model is infeasible, while when we set it to false, it is feasible

**What did you expect to see**
the result should be the same
**What did you see instead?**
self-contradiction
Make sure you include information that can help us debug (full error message, model Proto).

**Comment by lperron** [comment]
Can you try with 9.11?

**Comment by lperron** [comment]
Fixed on main.

**Comment by disonvon** [comment]
Thanks Laurent!
