### ISSUE TITLE
wrong status reported after calling stop_search

### ISSUE THREAD

**Issue by BrannonKing** [google/or-tools#4430]
**What version of OR-Tools and what language are you using?**
Version: 9.11.4210 installed via pip
Language: Python 3.12.7

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT (CpSolver)

**What operating system and version?**
Up-to-date Arch Linux

**What did you do?**
I added this callback:
```python
class LocalCallback(orcp.CpSolverSolutionCallback):
    def __init__(self, timeout=45) -> None:
        super().__init__()
        self._timer = None
        self._timeout = timeout

    def stop_running(self):
        self.stop_search()
        print("   Stopped via timeout since last solution! Timeout seconds:", self._timeout)

    def on_solution_callback(self):
        print("   Found a new solution!")
        if self._timer is not None:
            self._timer.cancel()
        self._timer = th.Timer(self._timeout, self.stop_running)
        self._timer.start()

status = solver.solve(model, solution_callback=LocalCallback())
...
```

**What did you expect to see**
I expect to see FEASIBLE. I expect Ctrl+C to work like it did before I added the callback.

**What did you see instead?**
The output is reported as OPTIMAL whenever my timeout triggers, although that seems unlikely. And if it knew it was optimal, why didn't it exit of its own accord? It does exit immediately when calling `stop_search`. A second thing I find strange: Ctrl+C works fine when I use it without any callbacks set. It even reports FEASIBLE in that scenario. When I set `solution_callback=...`, Ctrl+C stops working.

**Comment by lperron** [comment]
I think I fixed it on main. Can you send me a full code to reproduce ?

**Comment by BrannonKing** [comment]
This code below reproduces the issue with Ctrl+C, but it reports the correct status. I discovered that can't reproduce the status issue without my more complex model (that has many no-overlap constraints), and I'm not willing to share it yet as it's for a competition.

```python
import threading as th
import job_shop_lib as jsl
import job_shop_lib.benchmarking as jslb
import job_shop_lib.cp_sat as jslc
from ortools.sat.python import cp_model as orcp

instance = jslb.load_benchmark_instance("abz9")
tool = jslc.ORToolsSolver(10000, True)
tool._initialize_model(instance)
solver = tool.solver

status = solver.solve(tool.model, solution_callback=LocalCallback(3))
print("Status:", solver.status_name(status))
```
(Use the LocalCallback from the top post.)

**Comment by lperron** [comment]
I assume it is closed.
