### ISSUE TITLE
Please help to solve the problem

### ISSUE THREAD

**Issue by CnApTaK** [google/or-tools#444]
https://snag.gy/AUHJPq.jpg
Just one vehicle with work time 00:00-24:00 and capacity = 100, and 5 orders with work time 00:00-24:00 for orders№1-4 and 18:00-24:00 for order №5 and all need cargo size = 10. I’m using strategy PathCheapestArc.
If I set orders with small penalty value in AddDisjunction, for example 100, I got all orders dropped:
Solution info: Total cost: 500
Dropped orders: 1 2 3 4 5
Vehicle 0: Empty
If I set value = 1000, I got one order dropped:
Solution info: Total cost: 1984
Dropped orders: 5
Vehicle 0: 0 Time(0, 0) -> 4 Time(278, 278) -> 3 Time(18475, 18475) -> 2 Time(36682, 36682) -> 1 Time(54800, 54800) -> 0 Time(72984, 72984)
And result is looks like this
https://snag.gy/PHDlFh.jpg
Right now, this solution is fine, but I got first question – how I must choose penalty value? How this value correlates with problem? with 24-day limit? It is obvious that you can’t serve all orders because of serve time 5h in each order so in solution one order is dropped, but I don’t understand why it is number 5?
Second question: is it possible to make some kind of priority for custom orders? Not for only one of them but for two or more? Or even all?
For example, I need to make priority on order№5 to get solution like this, where I’m just delete the order№2
https://snag.gy/vIoWC4.jpg
Solution info: Total cost: 1332
Vehicle 0: 0 Time(0, 0) -> 2 Time(400, 400) -> 4 Time(18673, 18673) -> 1 Time(36870, 36870) -> 3 Time(55148, 55148) -> 0 Time(73332, 73332)
And why is lower? 1332 < 1984
Ok. Now the main problem. I need somehow set priority to order№5 and order№1, to get solution where solver will never drop order №1 and №5, but drops on of the other.
I was trying to penalty values = 2000 to orders №1 and №5 and I get this working only if I don’t use time window in order№5 (when I set in to 00:00-24:00). In this case I get solution like this
https://snag.gy/Zs8Ny2.jpg
Solution info: Total cost: 2278
Dropped orders: 2
Vehicle 0: 0 Time(0, 0) -> 5 Time(400, 400) -> 3 Time(18673, 18673) -> 1 Time(36976, 36976) -> 4 Time(55094, 55094) -> 0 Time(73278, 73278)
Solution is ok. Logic is ok. If I put penalty 2000 to order№3 it drops order№4. And again, it is OK.
BUT. If I set time window to order№5 16:00-24:00 - it is still possible to fulfill an order№5.
For example 1->2->3->5 or 1->2->4->5.. etc
But solver give me this
https://snag.gy/eXylvA.jpg
Solution info: Total cost: 2984
Dropped orders: 5
Vehicle 0: 0 Time(0, 0) -> 2 Time(278, 278) -> 4 Time(18475, 18475) -> 1 Time(36682, 36682) -> 3 Time(54800, 54800) -> 0 Time(72984, 72984)
Why order№5 is dropped? It has 2000 penalty like order№1 and it is 2x bigger than other orders penalties.
Please help to understand how to use these penalties correctly to solve my problem.
P.S. using C#

**Comment by Gankov** [comment]
For first question. I think cost for delivery order 5 more that 1000. So order 5 is dropped, because it is more profitable not to deliver the order. In first case cost of delivery orders 1-4 was more 100.

**Comment by Gankov** [comment]
For second question. If you don't want drop 1 and 5 orders. Try simply not add Disjunction with these orders.

**Comment by CnApTaK** [comment]
about 1. you mean the higher penalty value - more reasons to drop? i thought it works in oposite way
about 2. but how?? without adding Disjunction it is not working. no solution found.

**Comment by CnApTaK** [comment]
yes. if i put 100 to #2 and 200 to the other orders then dropper is #5, but if i put 1000 to #2 and 2000 to the others then #2 is dropped

**Comment by CnApTaK** [comment]
i don't understand this logic at all

**Comment by braktar** [comment]
What cost did you apply to your time dimension ?
Did you force your dimension to start at 0 ?

**Comment by CnApTaK** [comment]
model.AddDimension(new TotalTime(costMatrix, timeMatrix), kHorizon, kHorizon, false, "time");
costMatrix is {N,N} array containing time between each point including vehicles (in seconds)
timeMatrix is {N,3} array containing order service time and time windows start and finish (in seconds)

**Comment by braktar** [comment]
Did you set a SpanCostCoefficient to your dimension "time" ?

What are your service time ? Those didn't appear in your solution info

**Comment by CnApTaK** [comment]
appear only TotalTime. it's like a drive time + service time.
SpanCostCoefficient ? don't know how to use such thing

**Comment by braktar** [comment]
https://github.com/google/or-tools/blob/40ce0077f5a4c1ba3e742dc5c2987a3a8ed63f0d/ortools/constraint_solver/routing.h#L1411

model.GetMutableDimension("time")->SetSpanCostCoefficientForAllVehicles(coefficient);
The cost of your route will be (end-start)* coefficient + Sum(exclusion costs)

Which language, did you use for having such evaluator "new TotalTime(costMatrix, timeMatrix)" ? It doesn't seems to do what you expect.

**Comment by Gankov** [comment]
I don't know what used to calculate cost of solution. If you use time in seconds for it, when you add Disjunction with penality 100. This means that the algorithm is cheaper(cost 100) drop order, if go to order for example 150 seconds.

**Comment by CnApTaK** [comment]
i don't use coefficient. why? probably it's 1 by default.
TotalTime = route time + service time. nothing more.
