### ISSUE TITLE
Gurobi version 12.0.0 does not work with ortools version 9.6

### ISSUE THREAD

**Issue by udotneb** [google/or-tools#4451]
**What version of OR-Tools and what language are you using?**
Version: 9.6
Language: C++

**Which solver are you using (Gutobi)**

**What operating system (Linux, Windows, ...) and version?**
Linux 

**What did you do?**
Install gurobi full binary
install ortools from PIP
test example

**What did you expect to see**
(when running on version 11)

I0000 00:00:1732564292.966002  594675 environment.cc:401] Found the Gurobi library in '/usr/local/home/as-gurobi/gurobi1100/linux64/lib/libgurobi110.so.

Gurobi Optimizer version 11.0.0 build v11.0.0rc2 (linux64 - "Rocky Linux 8.10 (Green Obsidian)")

**What did you see instead?**
(when running on version 12)

I0000 00:00:1732050348.296406 1391437 environment.cc:401] Found the Gurobi library in '/usr/local/home/as-gurobi/gurobi1200/linux64/lib/libgurobi120.so.

F0000 00:00:1732050348.296491 1391437 dynamic_library.h:68] Check failed: function_address != nullptr Error: could not find function GRBisqp in /usr/local/home/as-gurobi/gurobi1200/linux64/lib/libgurobi120.so
*** Check failure stack trace: ***

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
we will not fix 9.6.

**Comment by udotneb** [comment]
@Mizux Just to check, does adding this to the v10.0 milestone mean that this will be fixed in the v10 version?

**Comment by Mizux** [comment]
Just mean, we want to release a 9.12 this week so this is postponed to the next release which could be v9.13 (i.e. branch v99bugfix/stable) or v10.0 (i.e. main branch)
