### ISSUE TITLE
Circuit documentation: Hamiltonian path vs. cycle

### ISSUE THREAD

**Issue by KyleBooth** [google/or-tools#4454]
**What version of OR-Tools and what language are you using?**
Version: 9.10
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Mac

**What did you do?**
The Python reference says that a circuit is a **unique Hamiltonian path**.

**What did you expect to see**
This is incorrect and the documentation should be updated to use ht term **Hamiltonian cycle**. When I was using this constraint, I thought it would produce paths from a source to a sink through a graph, but it really produces cycles that end at the node they start at. You can of course introduce dummy arcs to model a Hamiltonian path, but the documentation in its current state is a little misleading.

**What did you see instead?**

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
Which python reference?

**Comment by Mizux** [comment]
https://github.com/google/or-tools/blob/a24341498c6bea6da1751ef024fa161ba9bb8569/ortools/sat/python/cp_model.py#L1632-L1653 ?

**Comment by lperron** [comment]
fixed on main and v99bugfix
