### ISSUE TITLE
Float-point exception (SIGFPE, divide-by-zero) in cumulative_energy presolve since v9.11

### ISSUE THREAD

**Issue by sjindel** [google/or-tools#4456]
**What version of OR-Tools and what language are you using?**
Version: v9.11 (commit ed94162b910fa58896db99191378d3b71a5313af)
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you do?**
Solve the attached model.

**What did you expect to see**
sat result

**What did you see instead?**
SIGFPE during presolve

**Make sure you include information that can help us debug (full error message, model Proto).**
Model attached: [model.pb.txt](https://github.com/user-attachments/files/17950152/model.pb.txt)
On v9.10 the model solves fine.

**Anything else we should know about your project / environment**
Nothing special, using the Bazel build system (similarly to https://github.com/or-tools/bazel_or-tools).

**Comment by lperron** [comment]
I cannot reproduce. What parameters are you using ?

**Comment by sjindel** [comment]
I was using the default parameters originally, but I noticed it only reproduces in a "debug" build (`bazel build -c dbg`). I found that I can get it to reproduce in `-c opt` as well with `num_workers=1` and `interleave_search=true`.

The attached patch can be applied to the bazel demo repo (https://github.com/or-tools/bazel_or-tools) on `main`/`v9.11` to reproduce the crash (e.g. `bazel run //:repro /tmp/model.pb.txt`).

[repro.patch.txt](https://github.com/user-attachments/files/17951107/repro.patch.txt)

**Comment by lperron** [comment]
Thanks. I managed to reproduce it.

Le jeu. 28 nov. 2024, 18:37, Samir Jindel ***@***.***> a
écrit :

**Comment by sjindel** [comment]
I think the fix may not be complete. Attached is a similar model which exhibits the same crash (post-fix):
[fpe.pb.txt](https://github.com/user-attachments/files/17962186/fpe.pb.txt)

Also, the original model is now solved incorrectly -- the optimum is 2, but CP-SAT gives 4.

**Comment by lperron** [comment]
Ok, I'll check it out.

Le ven. 29 nov. 2024, 19:09, Samir Jindel ***@***.***> a
écrit :

**Comment by lperron** [comment]
Should be ok now.

Please check.

Thanks a lot!!!

**Comment by sjindel** [comment]
All my tests for this family of models are passing now (on `main`).
Thanks for fixing this!
