### ISSUE TITLE
Non-deterministic results with deterministic parameters

### ISSUE THREAD

**Issue by sjindel** [google/or-tools#4458]
**What version of OR-Tools and what language are you using?**
Version: main
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Linux 5.10

**What did you do?**
Solve the following model:
[model.pb.txt](https://github.com/user-attachments/files/17970048/model.pb.txt)

Parameters:
```c++
sat::SatParameters params;
params.set_num_workers(8);
params.set_random_seed(42);
params.set_interleave_search(true);
params.set_share_binary_clauses(false);
params.set_log_search_progress(true);
params.set_log_to_stdout(true);
model.Add(NewSatParameters(params));
```

**What did you expect to see**
Consistent solution with optimum value 80.

**What did you see instead?**
Varying solutions (different each time) with optimum value 80.

Here are the response protos and log files for two runs:
[0.log.txt](https://github.com/user-attachments/files/17970049/0.log.txt) [0.pb.txt](https://github.com/user-attachments/files/17970051/0.pb.txt)
[1.log.txt](https://github.com/user-attachments/files/17970052/1.log.txt) [1.pb.txt](https://github.com/user-attachments/files/17970050/1.pb.txt)

**Comment by lperron** [comment]
Please indicate the or-tools version.

**Comment by sjindel** [comment]
main, specifically this commit: https://github.com/google/or-tools/commit/c1a80243875c91a78ba7dea86351806c1f43a66e

**Comment by sjindel** [comment]
I also reproduced the issue on v9.11, if it's helpful.
