### ISSUE TITLE
How to install the cplex solver in or_tools using c++?

### ISSUE THREAD

**Issue by Yifan-Tang** [google/or-tools#446]
I have installed the previous version of cplex in my computer, and which archive should I zip and put into the archive folder of or-tools? I tried a lot, but nothing works.

Thanks in advance!

**Comment by lperron** [comment]
please install it somewhere, and define UNIX_CPLEX_DIR or WINDOWS_CPLEX_DIR
in Makefile.local to point to the root of the cplex directory.


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-08-03 20:05 GMT-07:00 Yifan-Tang <notifications@github.com>:

**Comment by Yifan-Tang** [comment]
I have downloaded CPLEX_Studio1251, and I tried to add the root directory, but it failed with Linear solver not recognized. Under the root directory, there are some subfolders:

concert, cplex, cpoptimizer, doc, license, properties and Uninstall.

Which one should I add to the Makefile.local?

**Comment by lperron** [comment]
You should add the directory that contains cplex, concert...
You need to do make clean, make after that.

Please try it out.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-08-03 21:49 GMT-07:00 Yifan-Tang <notifications@github.com>:

**Comment by Yifan-Tang** [comment]
After I do make clean and make cc,
I got the following error from cplex_interface:
`./ortools/linear_solver/cplex_interface.cc:254:20: error: use of undeclared identifier 'CPXXversionnumber'
      CHECK_STATUS(CPXXversionnumber(mEnv, &version));
                   ^
In file included from ./ortools/linear_solver/cplex_interface.cc:20:
In file included from ./ortools/base/logging.h:23:
/Users/tang/Desktop/Solver/or-tools-6.3/dependencies/install/include/glog/logging.h:718:32: error: comparison between pointer and integer ('int' and 'cpxenv *')
DEFINE_CHECK_OP_IMPL(Check_NE, !=)  // Use CHECK(x == NULL) instead.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/tang/Desktop/Solver/or-tools-6.3/dependencies/install/include/glog/logging.h:706:32: note: expanded from macro 'DEFINE_CHECK_OP_IMPL'
    if (GOOGLE_PREDICT_TRUE(v1 op v2)) return NULL; \
                            ~~ ^  ~~
/Users/tang/Desktop/Solver/or-tools-6.3/dependencies/install/include/glog/logging.h:148:53: note: expanded from macro 'GOOGLE_PREDICT_TRUE'
#define GOOGLE_PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                    ^
./ortools/linear_solver/cplex_interface.cc:232:7: note: in instantiation of function template specialization 'google::Check_NEImpl<int, cpxenv *>' requested here
      DCHECK_NE(0, mEnv); // should not be NULL if status=0
      ^
/Users/tang/Desktop/Solver/or-tools-6.3/dependencies/install/include/glog/logging.h:1044:29: note: expanded from macro 'DCHECK_NE'
    GLOG_MSVC_POP_WARNING() CHECK_NE(val1, val2)
                            ^
/Users/tang/Desktop/Solver/or-tools-6.3/dependencies/install/include/glog/logging.h:789:30: note: expanded from macro 'CHECK_NE'
#define CHECK_NE(val1, val2) CHECK_OP(_NE, !=, val1, val2)
                             ^
/Users/tang/Desktop/Solver/or-tools-6.3/dependencies/install/include/glog/logging.h:764:3: note: expanded from macro 'CHECK_OP'
  CHECK_OP_LOG(name, op, val1, val2, google::LogMessageFatal)
  ^
/Users/tang/Desktop/Solver/or-tools-6.3/dependencies/install/include/glog/logging.h:755:18: note: expanded from macro 'CHECK_OP_LOG'
         google::Check##name##Impl(                      \
                 ^
<scratch space>:90:1: note: expanded from here
Check_NEImpl
^
In file included from ./ortools/linear_solver/cplex_interface.cc:20:
In file included from ./ortools/base/logging.h:23:
/Users/tang/Desktop/Solver/or-tools-6.3/dependencies/install/include/glog/logging.h:718:32: error: comparison between pointer and integer ('int' and 'cpxlp *')
DEFINE_CHECK_OP_IMPL(Check_NE, !=)  // Use CHECK(x == NULL) instead.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/tang/Desktop/Solver/or-tools-6.3/dependencies/install/include/glog/logging.h:706:32: note: expanded from macro 'DEFINE_CHECK_OP_IMPL'
    if (GOOGLE_PREDICT_TRUE(v1 op v2)) return NULL; \
                            ~~ ^  ~~
/Users/tang/Desktop/Solver/or-tools-6.3/dependencies/install/include/glog/logging.h:148:53: note: expanded from macro 'GOOGLE_PREDICT_TRUE'
#define GOOGLE_PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                    ^
./ortools/linear_solver/cplex_interface.cc:237:7: note: in instantiation of function template specialization 'google::Check_NEImpl<int, cpxlp *>' requested here
      DCHECK_NE(0, mLp); // should not be NULL if status=0
      ^
/Users/tang/Desktop/Solver/or-tools-6.3/dependencies/install/include/glog/logging.h:1044:29: note: expanded from macro 'DCHECK_NE'
    GLOG_MSVC_POP_WARNING() CHECK_NE(val1, val2)
                            ^
/Users/tang/Desktop/Solver/or-tools-6.3/dependencies/install/include/glog/logging.h:789:30: note: expanded from macro 'CHECK_NE'
#define CHECK_NE(val1, val2) CHECK_OP(_NE, !=, val1, val2)
                             ^
/Users/tang/Desktop/Solver/or-tools-6.3/dependencies/install/include/glog/logging.h:764:3: note: expanded from macro 'CHECK_OP'
  CHECK_OP_LOG(name, op, val1, val2, google::LogMessageFatal)
  ^
/Users/tang/Desktop/Solver/or-tools-6.3/dependencies/install/include/glog/logging.h:755:18: note: expanded from macro 'CHECK_OP_LOG'
         google::Check##name##Impl(                      \
                 ^
<scratch space>:104:1: note: expanded from here
Check_NEImpl
^
3 errors generated.
make: *** [objs/linear_solver/cplex_interface.o] Error 1`

**Comment by lperron** [comment]
I have fixed the DCHECK_NE errors in github after the 6.3 release.
I will look at the CPXXversionnumber error.

**Comment by lperron** [comment]
can you try replacing CPXXversionnumber into CPXversionnumber?

This XX api may have been added after the 12.5.1. I do not know, the cplex_interface file was written by the cplex team :-)

**Comment by yingzong** [comment]
Did this ever work out? I followed the instructions above and built with no errors, but in the `pywraplp.Solver` module I do not get `CPLEX_...` options like I should. Where could I look to see what went wrong?

**Comment by lperron** [comment]
You are right, cplex was visible in C++ but not in python.

I have pushed a fix.

please run git pull; make clean_python; make python

It should work now.

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Only local.

The cloud version has a specific API, and is not supported by OR-Tools.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by N-Wouda** [comment]
@lperron Related to this - when may we expect a release that exposes CPLEX in Python? I'd like to use it in one of my projects, but - if at all possible - refrain from building the package myself.

**Comment by yingzong** [comment]
@N-Wouda I don't think that's possible, since the compilation involves specifying where the dynamic library provided by CPLEX is located, and CPLEX can't be packaged into ortools for licensing reasons.

**Comment by harlem87** [comment]
Hi teams, thanks in advance, but regarding to this issue, I have a problem, I don't find the file Makefile.local, where is this file ?

**Comment by Mizux** [comment]
@harlem87 please avoid necro posting BTW there is no more auto generated Makefile.local
please take a look at: https://github.com/google/or-tools/tree/main/cmake#enabling-cplex-support
