### ISSUE TITLE
Unable to export large LP models as MPS or LP

### ISSUE THREAD

**Issue by kasvas-ee** [google/or-tools#4468]
**What version of OR-Tools and what language are you using?**
Version: v9.11.4210
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
GLOP, PDLP

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What did you do?**
1. Prepare a large model (15Million variables and 12Million constraints, or larger)
2. Export model as mps using `solver.ExportModelAsMpsFormat(fixed_format=False, obfuscated=True)`

**What did you expect to see**

_TL;DR; The return of ExportModelAsMpsFormat in a format that can be written into a txt file._

ExportModelAsMpsFormat returns a string that can be easily written into a .txt file for smaller models. However, for larger models, the string may not be sufficient to store the entire model in MPS format. It would be beneficial to have the function return a list of split strings or another appropriate format to facilitate writing the model into a .txt file.

**What did you see instead?**
ExportModelAsMpsFormat returns a SwigPyObject for large models. Expecting it to be a string and trying to write it into a txt file throws error:

![Image](https://github.com/user-attachments/assets/214acca3-b766-4f28-8957-9d9a36ad8892)

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**
It looks like 2GB is the current limit, i.e. upto 2GB of exported model gets returned as a string and can be written into a .txt file. Anything larger is returned as a SwigPyObject.

**Comment by lperron** [comment]
use solver.WriteModelToMpsFile()

**Comment by kasvas-ee** [comment]
@lperron thank you for the quick response.

I gave this a try, and got a 'no such attribute' error 

![Image](https://github.com/user-attachments/assets/38cbe99d-9f37-4b7d-b316-ad53a8aa6d85)

Could you please confirm whether this is currently compatible with Python?
