### ISSUE TITLE
Used memory for given two models increased significantly from 9.11

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#4469]
**What version of OR-Tools and what language are you using?**
Version: main/v9.11/v9.10
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 20.04.6 lts, Debian 12

**What did you do?**
1. Execute given proto files
2. Measure used memory

**What did you expect to see**
Similarity in consumed memory between versions.

**What did you see instead?**
Multiplication of used memory from 9.10.

Make sure you include information that can help us debug (full error message, model Proto).
[compare.zip](https://github.com/user-attachments/files/18037965/compare.zip)

The two models differ only by sharing/not sharing of start and end variables of optional intervals with task interval. Sharing of variables lead in v9.10 to using less memory (around 13gb) but new cp-sat versions use 35gb (main) or 44gb (v9.11). Model with not shared variables is also strongly affected. Attached are proto files, output from log and consumed memory in 10 seconds intervals in time.txt file. Finally I verified the problem on main branch today and found that the problem is still here although it seems that it was little bit minimized.

**Anything else we should know about your project / environment**

**Comment by lperron** [comment]
not a bug :-)
