### ISSUE TITLE
fzn-or-tools "Cannot call Constains() on selected_inputs"

### ISSUE THREAD

**Issue by RHavar** [google/or-tools#447]
I'm running:

./fzn-or-tools model.fzn

which fails with:

```
Cannot call Constains() on selected_inputs
*** Check failure stack trace: ***
    @        0x109545bba  google::LogMessage::Fail()
    @        0x10954304a  google::LogMessage::SendToLog()
    @        0x1095448ff  google::LogMessage::Flush()
    @        0x10954d6b8  google::LogMessageFatal::~LogMessageFatal()
    @        0x109546165  google::LogMessageFatal::~LogMessageFatal()
    @        0x108943987  operations_research::fz::Argument::Contains()
    @        0x108959ab5  operations_research::fz::Presolver::PresolveSetInReif()
    @        0x108957f4b  operations_research::fz::Presolver::ApplyRule()
    @        0x10896a1f0  operations_research::fz::Presolver::PresolveOneConstraint()
    @        0x108970c01  operations_research::fz::Presolver::Run()
    @        0x1088f7b1e  operations_research::fz::ParseFlatzincModel()
    @        0x1088f8896  main
Abort trap: 6
```

model.fzn can be found here: https://gist.github.com/anonymous/bdf9debb10ae00f71f3550ee57be6711

---
FWIW I'm using v6.3.4431 on OSX; and the file runs fine with `flatzinc`

**Comment by lperron** [comment]
I believe you are using set variables, and they are not supported.

Sorry.

--Laurent

PS: BTW, using --use_cp_sat is a much better solver.


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-08-06 15:49 GMT-07:00 Ryan Havar <notifications@github.com>:

**Comment by RHavar** [comment]
Yeah, it does use a set. Is this something that's going to be supported in the future?  If not, I guess returning an error message instead of a stack would be the expected behavior =)

**Comment by lperron** [comment]
Not in the near future, and yes about the error message :-)

Now, with the sat solver backend, the path may be simpler than with the CP
solver.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-08-07 9:33 GMT-07:00 Ryan Havar <notifications@github.com>:

**Comment by lperron** [comment]
We have added support for sets using the nosets,mzn redefinition file.
I will close this issue.
