### ISSUE TITLE
No Module named linear_solver 

### ISSUE THREAD

**Issue by maxisawesome** [google/or-tools#448]
It appears my or-tools isn't reading thing right. On an ubunutu 16.04 machine. 

I got ortools to install correctly, and I even got a few examples to run, but now whenever I try to run any python file, I get "ImportError: No module named linear_solver" or "ImportError: No module named constraint_solver". I get this error for files in ortools_examples/examples/python AND for files I got from the tutorials part. I think it's an issue with my path or pythonpath, but I'm not good enough at linux to really understand. 

I looked at issue #396 but I didn't understand it enough for it to help me. 

Traceback (most recent call last):
  File "kakuro.py", line 61, in <module>
    from ortools.constraint_solver import pywrapcp
  File "/home/m3/summer/ortools_examples/examples/python/ortools.py", line 2, in <module>
ImportError: No module named linear_solver

**Comment by maxisawesome** [comment]
Ok, I tried running "sudo make install" instead of just "make install" and got the following error in traceback: 

Using /home/m3/.local/lib/python2.7/site-packages/six-1.10.0-py2.7.egg
Finished processing dependencies for ortools-examples==6.3.4431
Traceback (most recent call last):
  File "check_python_deps.py", line 7, in <module>
    from setuptools.command import easy_install
  File "/home/m3/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 52, in <module>
  File "/home/m3/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/package_index.py", line 15, in <module>
  File "/home/m3/anaconda2/lib/python2.7/urllib2.py", line 94, in <module>
    import httplib
  File "/home/m3/anaconda2/lib/python2.7/httplib.py", line 1230, in <module>
    import ssl
  File "/home/m3/anaconda2/lib/python2.7/ssl.py", line 133, in <module>
    PROTOCOL_SSLv23 = PROTOCOL_TLS
NameError: name 'PROTOCOL_TLS' is not defined
Makefile:52: recipe for target 'install' failed
make: *** [install] Error 1

Looks like I didn't install correctly like I thought I did.

**Comment by lperron** [comment]
this is a problem with anaconda python.
Can you try with a default python (not anaconda)?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-08-16 13:45 GMT-07:00 maxisawesome <notifications@github.com>:

**Comment by gmarchi** [comment]
I'm the guy who wrote a possibile solution to this kind of problem at issue #396. I also use anaconda. Let me help you. What did you not understand?

**Comment by maxisawesome** [comment]
It was a problem with anaconda. I didn't do the #396 thing. Instead I deleted anaconda and now run things with the command '/usr/bin/python my_program.py' instead of just 'python my_program.py'. I did do 'make install' with the makefile directed towards '/usr/bin/python.' Or-tools functions properly like this, however.....

This was totally wrong. Not only was deleting anaconda extra as I think '/usr/bin/python my_program.py' would have worked without deleting it, but now when using '/usr/bin/python my_program.py' I dont have numpy. In order to install it, I need to do pip install numpy, but that still directs to anaconda ('bash: /home/m3/anaconda2/bin/pip: No such file or directory' This is the same message I get if I do just 'python my_program.py').

I totally screwed everything up. Feels like this happens everytime I have to install anything!! Agh, one day I'll figure all this linux stuff out and not mess everything up.......

**Comment by gmarchi** [comment]
Don't be discouraged. Probably you still have some broken links in a directory of your PATH, pointing to some inexistent anaconda binaries. Try to reinstall anaconda directory in the same previuos path `/home/m3` and everything should work as before.

If anaconda binaries still don't work. Then try doing `echo "export PATH=\"/home/m3/anaconda2/bin:\$PATH\"" >> ~/.bash_profile`. This appends the path to anaconda binaries to your PATH variable. Close and open a new terminal. Now if you type `which python` or `which pip` you should see the corrected path. This was the corrected way to install anaconda from the first time, I don't know why it seems you have links to it from an other directory of your PATH, this is not recommended.

Now, assuming you are using python 2.7 and ubuntu 16.04, simply type `pip install ortools-ubuntu-16.04` to install precompiled ortools python package.

**Comment by maxisawesome** [comment]
I reinstalled anaconda in the same location as you instructed and everything is fine. pip install ortools-ubuntu-16.04 gave me a message that was basically "you already have it installed!," so I tried 'python k8_ortools.py' and it worked fine, ortools and numpy.

If I can install with a simple 'pip install ortools-ubuntu-16.04,' why does the installation guide tell me to download the package then install by running a makefile?

I'm happy everything works and I can do the fun math part now, I'm annoyed that I messed it up in the first place (also that I did it in some convoluted way that I don't understand) but most thankful for the help yall provided. Open source communities are awesome.

**Comment by lperron** [comment]
Because sometimes setuptools, or pip does not find the correct ortools
module.

I do not know if pip install ... works. But even if it works, it has the
same effect as the running setup.py in the or-tools examples directory.

The makefile does some additional checks for errors that bit us in the past.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-08-18 15:53 GMT-07:00 maxisawesome <notifications@github.com>:

**Comment by gmarchi** [comment]
i'm glad we were able to help you. You can close the issue now if you want.
