### ISSUE TITLE
Add methods to IntervalVar class to get the interval's `end` variable

### ISSUE THREAD

**Issue by mbUSC** [google/or-tools#4482]
**What language and solver does this apply to?**
Python

**Describe the problem you are trying to solve.**
Oftentimes, I have to specify constraints on the end of an interval. For that, I have to manually define a new `endOfInterval` variable and set it equal to `startOfInterval` + `intervalSize`.

**Describe the solution you'd like**
A convenience method to access the end of the interval from the `IntervalVar`.

**Describe alternatives you've considered**
See above.

**Comment by lperron** [comment]
no.
There are no such variable.

You can get the end expression.
