### ISSUE TITLE
Plans for exposing PiecewiseLinearFunction to swig interface?

### ISSUE THREAD

**Issue by michaelarakel** [google/or-tools#449]
Hello, I'd like to ask whether there plans for exposing PiecewiseLinearFunction and related methods (such as SetCumulVarPiecewiseLinearCost, etc) to the swig interface?

Thank you in advance

ref:
https://github.com/google/or-tools/blob/f3fd201e68cf75b7720ff5c3cadc599a1d02b54b/ortools/util/piecewise_linear_function.h#L101

**Comment by Mizux** [comment]
Hi,

Currently no plan for the foreseeable future.
In which language would you want it (i.e. python, java, .Net) ?

**Comment by smagafurov** [comment]
Python

**Comment by GuyBenhaim** [comment]
Hi,
Any updates on this?   C# for me.
Thx

**Comment by lperron** [comment]
No.
I welcome PR.
