### ISSUE TITLE
py3-ortools 6.3.4431, solver.MakeEquality method Attribute error

### ISSUE THREAD

**Issue by niks660097** [google/or-tools#450]
https://github.com/google/or-tools/blob/master/ortools/constraint_solver/python/constraint_solver.i#L429
According to this, solver has this method?
Traceback (most recent call last):
  File "/Users/nirmalsingh/Repos/NetworkOptimization/NetworkOptimization/optimization/GoogleOr/asdf.py", line 25, in <module>
    optimum_route_solver()
  File "/Users/nirmalsingh/Repos/NetworkOptimization/NetworkOptimization/optimization/GoogleOr/asdf.py", line 22, in optimum_route_solver
    solver.Add(solver.MakeEquality(routing.VehicleVar(routing.NodeToIndex(start_node)),
  File "/Users/nirmalsingh/Venvs/google_or/lib/python3.6/site-packages/ortools/constraint_solver/pywrapcp.py", line 247, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Solver, name)
  File "/Users/nirmalsingh/Venvs/google_or/lib/python3.6/site-packages/ortools/constraint_solver/pywrapcp.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'Solver' object has no attribute 'MakeEquality'

```python
import sys
from ortools.constraint_solver import pywrapcp
from ortools.constraint_solver import routing_enums_pb2


def add_depot(graph, bus_stops, passenger_drop_map):
    '''
    depot ind will be len(graph)+1
    :param graph:
    :return:
    '''
    for row in graph:
        row.append(1)
    graph.append([1]*len(graph)+[0])
    bus_stops.append('Depot')
    passenger_drop_map.append({})


def get_test_data():
    '''
    :return:
    '''
    readable_passenger_drop_map = [{'B': 2, 'D': 2, 'C': 1}, {'C': 1}, {'D': 1}, {}]#DICT repr who wants drop where
    passenger_drop_map = [{1: 2, 3: 2, 2: 1}, {2: 1}, {3: 1}, {}]#DICT repr who wants drop where, dest_node:no_of_people
    bus_stops = ['A', 'B', 'C', 'D']
    graph = [[0 for i in range(4)] for i in range(4)]
    for ind, i in enumerate(bus_stops):#not full graph
        drop_obj = passenger_drop_map[ind]
        drop_obj_keys = list(drop_obj.keys())
        for nb_ind, nb in enumerate(drop_obj_keys):
            graph[ind][nb] = 1
            if nb_ind+1 < len(drop_obj_keys):
                for _nb_ind in range(nb_ind+1, len(drop_obj_keys)):#creating edges b/w all nodes with same origin
                    real_new_nb_ind = drop_obj_keys[_nb_ind]
                    graph[nb][real_new_nb_ind] = 1
                    graph[real_new_nb_ind][nb] = 1

    add_depot(graph, bus_stops, passenger_drop_map)
    print(graph, 'Input graph')
    depot = len(graph)-1
    return [graph, bus_stops, passenger_drop_map, depot]

def optimum_route_solver():
    depotDistance = 1
    data = get_test_data()
    graph = data[0]
    bus_stops = data[1]
    drop_map = data[2]
    depot = data[3]
    num_locations = len(graph)
    num_vehicles = 1
    vehicle_capacities = [9]#todo list/vector for later use
    print(num_locations, num_vehicles, depot)

    routing = pywrapcp.RoutingModel(num_locations, num_vehicles, depot)
    start_node = 1
    dest_node = 2
    solver = routing.solver()
    solver.Add(solver.MakeEquality(routing.VehicleVar(routing.NodeToIndex(start_node)),
                       routing.VehicleVar(routing.NodeToIndex(dest_node))))

optimum_route_solver()
```

**Comment by michaelarakel** [comment]
@niks660097 you get an Attribute error, because there is no `MakeEquality` defined for python bindings. According to `constraint_solver.i`, `MakeEquality` is called from inside python `__eq__`, so what you should actually do is:
```python
solver.Add(
    routing.VehicleVar(routing.NodeToIndex(start_node)) ==
    routing.VehicleVar(routing.NodeToIndex(dest_node))
)
```

**Comment by furnon** [comment]
Why don't you use the == operator directly ?

solver.Add(routing.VehicleVar(routing.NodeToIndex(start_node)) ==
                       routing.VehicleVar(routing.NodeToIndex(dest_node)))
