### ISSUE TITLE
Python Tutorials (Acrogenesis)

### ISSUE THREAD

**Issue by valmunos** [google/or-tools#453]
Not sure if this is the correct place to bring this issue up - if not, I apologize.

I have been trying to access the documentation for the Python examples on the acrogenesis blog but keep getting a code 404 error (http://or-tools.googlecode.com/svn/trunk/documentation/documentation_hub.html#tutorial_Python).  If there is newer documentation that I am unaware of, please send me a link to it.

Thank you.

**Comment by lperron** [comment]
googlecode is obsolete, and has been replaced by github.
The doc is on developer.google.com/optimization

I do not believe this particular tutorial is still exists.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-08-21 8:01 GMT-07:00 Vincent Lingle-Munos <notifications@github.com>:

**Comment by valmunos** [comment]
Is there any other documentation on how to use the Python or-tools API?  I
believe there are more solvers than what is documented in the link you
sent, correct?

**Comment by eballes** [comment]
Documentation on the python module is just on the examples... and it feels like there's a gap between the C++ API and the Python wrapper.

For example, is there any way I can link a callback function to the solver in Python? SearchLogWithCallback is implemented but documentation is lacking.

**Comment by lperron** [comment]
We do document a lot of things here: https://developers.google.com/optimization/

For the CP-SAT solver, I have also started a set of recipes:
  https://github.com/google/or-tools/blob/master/ortools/sat/doc/index.md

For the rest, just ask.

I will close this bug as it is quite old now and probably obsolete.
