### ISSUE TITLE
Install issue on python 2.7

### ISSUE THREAD

**Issue by arita37** [google/or-tools#454]
On Ubuntu 16.0, Anaconda 2.7,
when doing :
pip install ortools

I have this message :  

```
(python2) ubuntu@:/root$ pip install ortools
Collecting ortools
  Could not find a version that satisfies the requirement ortools (from versions: )
No matching distribution found for ortools
```

**Comment by lperron** [comment]
I just release version 6.4 with manylinux wheel files.

Can you retry?

Thanks

**Comment by lperron** [comment]
Hi, 

It should work fine.
Just make sure you have a up to date version of pip (9.0.1)

Thanks
