### ISSUE TITLE
VRP with Time Windows - More than 1 time window per location

### ISSUE THREAD

**Issue by ilaif** [google/or-tools#456]
Hey guys,

Amazing library!

I have a situation where a location (or "customer") has two or more available time windows (let's say it's open in the morning, closed for siesta, and then open again until the evening).
The following SetRange line of code: time_dimension.CumulVar(order).SetRange(start, end) gives one such constraint, how can I add two with "OR" logic between them?

Thanks,
Ilai

**Comment by michaelarakel** [comment]
@ilaif I had the same problem and here is how I approached it:
- First construct 2 lists of starts and ends of ranges that the `CumulVar` cannot take
- Then use the `NotMemberCt` of constraint solver as follows (assuming `routing` is your `RoutingModel`:
```python
solver = routing.solver()
solver.AddConstraint(
    solver.NotMemberCt(
        time_dimension.CumulVar(order), 
        forbidden_time_frame_starts, forbidden_time_frame_ends
    )
)
```

**Comment by ilaif** [comment]
Thanks @michaelarakel !
1. Just to make sure I understand: Your solution was to use De Morgan Rules: (A OR B) = NOT(NOT(A) AND NOT(B)) and chain a list of "AND" constraints on a variable?
2. The two lists (forbidden_time_frame_starts and ..._ends) are plain lists of numbers?

**Comment by michaelarakel** [comment]
@ilaif 

1. Yes you can think of it as using De Morgan's rule
2. Yes they are just lists of numbers. Let me give an example to make this clearer. Suppose `forbidden_time_frame_starts  = [0, 34000]` and `forbidden_time_frame_starts = [26999, 57000]`. This means that the CumulVar will not be allowed to take values in ranges `[0, 26999]` and `[34000, 57000]`
3. These 2 functions are not part of the routing, but belong to the constraint solver. I have been using the code as documentation :) You can have a look at the `constraint_solver.h` for other constraints (in c++). `constraint_solver.i` contains the python bindings

**Comment by furnon** [comment]
I confirm this is the proper way to model multiple time windows (and the
routing solver will take them into account actively in the local search).

**Comment by ilaif** [comment]
Hey, guys,

I think there might be a bug with this method.
I've used the instructions above to create forbidden time windows:
```python
solver = routing.solver()
solver.AddConstraint(
    solver.NotMemberCt(
        time_dimension.CumulVar(order), 
        forbidden_time_frame_starts, forbidden_time_frame_ends
    )
)
```
In the test I have 6 locations:
- index: 0, forbidden time windows: None (Not inserted as a constraint)
- index: 1, forbidden time windows: None (Not inserted as a constraint)
- index: 2, forbidden time windows: [10801], [86400]
- index: 3, forbidden time windows: [10801], [86400]
- **index: 4, forbidden time windows: [0, 46801], [20999, 86400]**
- index: 5, forbidden time windows: [0, 46801], [20999, 86400]

Where 86400 is the horizon, index 0 is the start location and index 1 is the end location.

The assignment is the following order:
- index: 0, max_arrive_time: 0, min_arrive_time: 0
- index: 3, max_arrive_time: 6482, min_arrive_time: 672
- **index: 4, max_arrive_time: 10800, min_arrive_time: 4990**
- index: 5, max_arrive_time: 41831, min_arrive_time: 21000
- index: 2, max_arrive_time: 43317, min_arrive_time: 22486
- index: 1, max_arrive_time: 46800, min_arrive_time: 25969

As you can see node index 4 is arriving during the forbidden time window.

The full source code:
https://gist.github.com/ilaif/a79dfd8c41b2924d4d74758e342c88f5

Command I've called (with the relevant input parameters):
```bash
python vrpsolver.py --data {\"locations\":[{\"time_windows\":[],\"service_time\":0},{\"time_windows\":[],\"service_time\":0},{\"time_windows\":[[0,10800]],\"service_time\":900},{\"time_windows\":[[0,10800]],\"service_time\":900},{\"time_windows\":[[21000,46800]],\"service_time\":900},{\"time_windows\":[[18000,46800]],\"service_time\":900}],\"distance_matrix\":[[0,0,2553,672,3561,2372],[0,0,2553,672,3561,2372],[2583,2583,0,2288,2063,741],[812,812,2410,0,3418,2229],[3585,3585,1906,3290,0,1756],[2452,2452,586,2157,1732,0]],\"start_location_index\":0,\"end_location_index\":1}
```

Appreciate the effort,
Thanks, Ilai

**Comment by furnon** [comment]
The issue with your code is that node and variable are mixed. In particular
when you set the time windows, it should be:
solver.Add(
            solver.NotMemberCt(
                time_dimension.CumulVar(routing.NodeToIndex(order)),   <--
note the conversion here
                [tw[0] for tw in closed_time_windows], [tw[1] for tw in
closed_time_windows]
            )
        )

Also note that there's probably a typo in the forbidden time windows you
displayed; it's actually:
index: 4, forbidden time windows: [0, 20999], [46801, 86400]
index: 5, forbidden time windows: [0, 17999], [46801, 86400]
(at least from the command line you  specified).

**Comment by ilaif** [comment]
@furnon thanks a lot! It solved the problem. The forbidden time windows are indeed a type :)

**Comment by JacobenVosloo** [comment]
In this post - https://groups.google.com/forum/#!topic/or-tools-discuss/MBq1TcqSQTI they suggest a different approach. 
Instead of using the 'solver.NotMemberCt()' function they simply remove the forbidden intervals using

' time_dimension.CumulVar(index).RemoveInterval(time_window_end, next_time_window_start)'

Here is a link to another implementation https://stackoverflow.com/questions/61456895/multiple-time-windows-vrp-or-tools

which approach is better or more correct?
The latter definitely looks easier...

**Comment by Mizux** [comment]
see https://github.com/Mizux/tsp_multiple_days/blob/feature/morning_nodes/40_Locations_3_days.py

**Comment by ywang1110** [comment]
> see https://github.com/Mizux/tsp_multiple_days/blob/feature/morning_nodes/40_Locations_3_days.py

Hey Mizux, Thanks for your contribution and I've learnt a lot.  
Regarding the repo you mentioned, could you please answer these two questions at your earliest convenience? Thanks in advance. 

1. Why all tasks tend to be scheduled at day 3 instead of day 1?
2. It seems that the output doesn't make sense since all location at last day share the exactly same time slots. 
![multiple_days](https://user-images.githubusercontent.com/32408164/180471000-f5574878-c10a-4f26-9d21-7b79fa812386.png)

**Comment by Mizux** [comment]
@ywang1110 Because the code is broken ^^;, here the fix:
https://github.com/Mizux/tsp_multiple_days/commit/a7810f969312c80fe4191e9d9faaf84a67615ad8

potential output:
```
./40_Locations_3_days.py   
Objective: 483266
droped: [40, 41, 44, 45]
Route for vehicle 0:
0 [0d 8:0:0;0d 8:0:0] -> 43 [0d 8:21:37;0d 8:48:21] -> 39 [0d 9:35:34;0d 10:2:18] -> 18 [0d 10:49:57;0d 11:16:41] -> 19 [0d 11:12:48;0d 11:39:32] -> 14 [0d 11:35:1;0d 12:1:45] -> 16 [0d 11:53:47;0d 12:20:31] -> 15 [0d 12:13:21;0d 12:40:5] -> 17 [0d 12:33:30;0d 13:0:14] -> 27 [0d 12:55:2;0d 13:21:46] -> 13 [0d 13:43:1;0d 14:9:45] -> 34 [0d 14:7:40;0d 14:34:24] -> 35 [0d 14:49:38;0d 15:16:22] -> 1 [0d 16:0:0;0d 16:0:0] -> 

2 [1d 6:0:0;1d 6:0:0] -> 12 [1d 6:43:21;1d 6:45:39] -> 28 [1d 7:7:23;1d 7:9:41] -> 33 [1d 7:41:52;1d 7:44:10] -> 31 [1d 8:22:31;1d 8:24:49] -> 36 [1d 8:57:7;1d 8:59:25] -> 37 [1d 9:35:36;1d 9:37:54] -> 38 [1d 10:9:34;1d 10:11:52] -> 42 [1d 10:43:35;1d 10:45:53] -> 30 [1d 11:52:18;1d 11:54:36] -> 22 [1d 12:26:39;1d 12:28:57] -> 23 [1d 13:3:52;1d 13:6:10] -> 29 [1d 13:41:11;1d 13:43:29] -> 9 [1d 14:26:17;1d 14:28:35] -> 24 [1d 15:1:41;1d 15:3:59] -> 25 [1d 15:38:28;1d 15:40:46] -> 32 [1d 16:31:1;1d 16:33:19] -> 3 [1d 18:0:0;1d 18:0:0] -> 

4 [2d 10:0:0;2d 10:0:0] -> 26 [2d 10:13:18;2d 10:13:18] -> 11 [2d 10:58:3;2d 10:58:3] -> 7 [2d 11:24:28;2d 11:24:28] -> 6 [2d 11:48:56;2d 11:48:56] -> 8 [2d 12:14:4;2d 12:14:4] -> 10 [2d 12:49:2;2d 12:49:2] -> 21 [2d 13:11:31;2d 13:11:31] -> 20 [2d 13:52:9;2d 13:52:9] -> [2d 14:26:48;2d 14:26:48]
```

**Comment by ywang1110** [comment]
> @ywang1110 Because the code is broken ^^;, here the fix: [Mizux/tsp_multiple_days@a7810f9](https://github.com/Mizux/tsp_multiple_days/commit/a7810f969312c80fe4191e9d9faaf84a67615ad8)
> 
> potential output:
> 
> ```
> ./40_Locations_3_days.py   
> Objective: 483266
> droped: [40, 41, 44, 45]
> Route for vehicle 0:
> 0 [0d 8:0:0;0d 8:0:0] -> 43 [0d 8:21:37;0d 8:48:21] -> 39 [0d 9:35:34;0d 10:2:18] -> 18 [0d 10:49:57;0d 11:16:41] -> 19 [0d 11:12:48;0d 11:39:32] -> 14 [0d 11:35:1;0d 12:1:45] -> 16 [0d 11:53:47;0d 12:20:31] -> 15 [0d 12:13:21;0d 12:40:5] -> 17 [0d 12:33:30;0d 13:0:14] -> 27 [0d 12:55:2;0d 13:21:46] -> 13 [0d 13:43:1;0d 14:9:45] -> 34 [0d 14:7:40;0d 14:34:24] -> 35 [0d 14:49:38;0d 15:16:22] -> 1 [0d 16:0:0;0d 16:0:0] -> 
> 
> 2 [1d 6:0:0;1d 6:0:0] -> 12 [1d 6:43:21;1d 6:45:39] -> 28 [1d 7:7:23;1d 7:9:41] -> 33 [1d 7:41:52;1d 7:44:10] -> 31 [1d 8:22:31;1d 8:24:49] -> 36 [1d 8:57:7;1d 8:59:25] -> 37 [1d 9:35:36;1d 9:37:54] -> 38 [1d 10:9:34;1d 10:11:52] -> 42 [1d 10:43:35;1d 10:45:53] -> 30 [1d 11:52:18;1d 11:54:36] -> 22 [1d 12:26:39;1d 12:28:57] -> 23 [1d 13:3:52;1d 13:6:10] -> 29 [1d 13:41:11;1d 13:43:29] -> 9 [1d 14:26:17;1d 14:28:35] -> 24 [1d 15:1:41;1d 15:3:59] -> 25 [1d 15:38:28;1d 15:40:46] -> 32 [1d 16:31:1;1d 16:33:19] -> 3 [1d 18:0:0;1d 18:0:0] -> 
> 
> 4 [2d 10:0:0;2d 10:0:0] -> 26 [2d 10:13:18;2d 10:13:18] -> 11 [2d 10:58:3;2d 10:58:3] -> 7 [2d 11:24:28;2d 11:24:28] -> 6 [2d 11:48:56;2d 11:48:56] -> 8 [2d 12:14:4;2d 12:14:4] -> 10 [2d 12:49:2;2d 12:49:2] -> 21 [2d 13:11:31;2d 13:11:31] -> 20 [2d 13:52:9;2d 13:52:9] -> [2d 14:26:48;2d 14:26:48]
> ```
> 
> EDIT: if running for 30s solver manage to add one more location ! note: on my machine the solver manage to add it after 8/9s since when I enable the log I can see the objective drop from 488k to 388k...
> 
> ```
> Objective: 388656
> droped: [40, 41, 44]
> Route for vehicle 0:
> 0 [0d 8:0:0;0d 8:0:0] -> 19 [0d 8:8:2;0d 8:19:10] -> 14 [0d 8:30:15;0d 8:41:23] -> 17 [0d 8:52:55;0d 9:4:3] -> 27 [0d 9:14:27;0d 9:25:35] -> 11 [0d 9:55:17;0d 10:6:25] -> 28 [0d 10:19:36;0d 10:30:44] -> 13 [0d 11:5:8;0d 11:16:16] -> 34 [0d 11:29:47;0d 11:40:55] -> 35 [0d 12:11:45;0d 12:22:53] -> 31 [0d 12:50:43;0d 13:1:51] -> 36 [0d 13:25:19;0d 13:36:27] -> 45 [0d 14:19:42;0d 14:30:50] -> 1 [0d 16:0:0;0d 16:0:0] -> 
> 
> 2 [1d 6:0:0;1d 6:0:0] -> 12 [1d 6:43:21;1d 6:45:24] -> 33 [1d 7:8:43;1d 7:10:46] -> 26 [1d 7:43:34;1d 7:45:37] -> 37 [1d 8:27:28;1d 8:29:31] -> 38 [1d 9:1:26;1d 9:3:29] -> 42 [1d 9:35:27;1d 9:37:30] -> 18 [1d 10:43:36;1d 10:45:39] -> 20 [1d 11:3:19;1d 11:5:22] -> 30 [1d 11:39:26;1d 11:41:29] -> 22 [1d 12:13:47;1d 12:15:50] -> 10 [1d 12:56:23;1d 12:58:26] -> 9 [1d 13:30:19;1d 13:32:22] -> 29 [1d 14:0:14;1d 14:2:17] -> 23 [1d 14:37:13;1d 14:39:16] -> 25 [1d 15:14:53;1d 15:16:56] -> 24 [1d 15:50:40;1d 15:52:43] -> 43 [1d 16:31:16;1d 16:33:19] -> 3 [1d 18:0:0;1d 18:0:0] -> 
> 
> 4 [2d 10:0:0;2d 10:0:0] -> 32 [2d 10:14:37;2d 10:14:37] -> 16 [2d 11:6:0;2d 11:6:0] -> 15 [2d 11:25:34;2d 11:25:34] -> 7 [2d 11:48:48;2d 11:48:48] -> 6 [2d 12:13:16;2d 12:13:16] -> 8 [2d 12:38:24;2d 12:38:24] -> 21 [2d 13:13:55;2d 13:13:55] -> 39 [2d 13:56:0;2d 13:56:0] -> [2d 15:6:14;2d 15:6:14]
> ```

Thank you so much. I appreciate your help.

**Comment by ywang1110** [comment]
Hey @Mizux, I have another question, is it possible to expand the scope a little bit. For example:
1. Expand to VRP instead of TSP
2. NUM_DAYS varies among different locations. e.g., #1 location should be visited between 8:00-12:00 at the first day (day 0). #2 location should be visited  between 8:00-12:00 within the first two days (day 0 or day 1).

**Comment by ywang1110** [comment]
> Hey @Mizux, I have another question, is it possible to expand the scope a little bit. For example:
> 
> 1. Expand to VRP instead of TSP
> 2. NUM_DAYS varies at different locations. e.g., The 1st location should be visited between 8:00-12:00 at the first day (day 0). The 2nd location should be visited  between 10:00-14:00 within the first two days (day 0 or day 1).
> 
> I tried these ideas based on your code. But the result doesn't seem correct. I'd appreciate it if you could provide any guidance. Thank you so much.
> 
> ![1658765914(1)](https://user-images.githubusercontent.com/32408164/180826614-aafd7288-4219-44b5-a46d-9a053f659e25.png)

https://github.com/ywang1110/tsp_multiple_days/commit/c1e5c2b387e185b5dd6a0b1ac875acc022464a48
