### ISSUE TITLE
Unable to run python example after installing from source

### ISSUE THREAD

**Issue by gyang1011** [google/or-tools#457]
I have followed the installation instruction on this website (https://developers.google.com/optimization/introduction/installing.html#unix_source) and successfully passed the test after running `make test` on my Mac (OS Version 10.12.6). However, when I try to run a python example `or-tools/examples/python/coins_grid.py` , I keep getting the following error ```File "coins_grid.py", line 57, in <module>
    from ortools.constraint_solver import pywrapcp
ImportError: No module named ortools.constraint_solver```

It is really strange because when I do ` make test_python`, I did not get any errors.

**Comment by lperron** [comment]
Did you set the PYTHONPATH?

Please look at the make rpy target to see how to run a python file.

Thanks

**Comment by bacalfa** [comment]
Is there a way to install `ortools` to the Anaconda site-packages folder as if we were installing a module from source (e.g., with `python setup.py install`)?

**Comment by bacalfa** [comment]
I think I figured it out.

- Make the python version and create the PyPI files
`make python pypi_archive`
- A folder named "temp-python3.6" (the Python version is specific to your system) is created in the root directory
- Go two levels into that directory
`cd  temp-python3.6/ortools`
- Install the `ortools` Python package
`python setup.py install`

Now I can import the `ortools` module from anywhere:
`python -c "import ortools"`

**Comment by Mizux** [comment]
@bacalfa it seems you are using ortools 6.6.4806, please try to use this new version https://pypi.python.org/pypi/ortools/6.6.4659 
I guess this version don't have this patch: https://github.com/google/or-tools/issues/556

**Comment by Mizux** [comment]
seems a symbol is missing:
```bash
$ c++filt __ZNSt15basic_streambufIcSt11char_traitsIcEE5imbueERKSt6locale
std::basic_streambuf<char, std::char_traits<char> >::imbue(std::locale const&)
```

**Comment by bacalfa** [comment]
Thanks, @Mizux. I had just cloned the repository last night, so I believe I have the latest version. Do you have an idea of what it takes to fix this issue? I was able to build everything without getting errors.

**Comment by Mizux** [comment]
could be due to bad/incompatible libstdc++6 , did you turn on/off your machine and did an upgrade recently ?

**Comment by bacalfa** [comment]
Well, I did reboot the computer, run `make clean`, and again `make python pip_archive`, but still getting the same error. I noticed it calls `clang++` and I'm using the latest Xcode (Version 9.3 beta 2 (9Q107o)). What's happening? :(

**Comment by bacalfa** [comment]
I tried the following:
- Commented out line https://github.com/google/or-tools/blob/acbbd2a2f3fd0a398a6e419f051f7321cd1c3bfb/makefiles/Makefile.unix.mk#L195
and replaced it with
`CCC = g++ -fPIC -std=c++11  $(MAC_VERSION)`
By the way, I have gcc version 7.2.0 (Homebrew GCC 7.2.0).
- Attempted to run `make python pypi_archive` and ran into errors:
```
./ortools/base/random.cc: In static member function 'static int32 operations_research::ACMRandom::HostnamePidTimeSeed()':
./ortools/base/random.cc:74:13: error: 'PATH_MAX' was not declared in this scope
   char name[PATH_MAX + 20];  // need 12 bytes for 3 'empty' uint32's
```
- That was fixed by adding the following include to the `#else` block containing https://github.com/google/or-tools/blob/acbbd2a2f3fd0a398a6e419f051f7321cd1c3bfb/ortools/base/random.cc#L25
`#include <sys/syslimits.h>`
- Finally, building is complete, setup.py runs without errors, but then the same missing symbol error appears when running that example.

**Comment by bacalfa** [comment]
Just FYI, I'm able to build the C++ version with `make cc` (only works with `clang++`, not with HomeBrew's `g++` (see (*) below)), but then I get the same error:

```
iMac:or-tools bacalfa$ ./bin/integer_programming 
dyld: Symbol not found: __ZNSt15basic_streambufIcSt11char_traitsIcEE5imbueERKSt6locale
  Referenced from: /Users/bacalfa/Downloads/or-tools/lib/libortools.dylib
  Expected in: flat namespace
 in /Users/bacalfa/Downloads/or-tools/lib/libortools.dylib
Abort trap: 6
```

(*) Using `g++` gives me the following error:

```
Undefined symbols for architecture x86_64:
  "google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)", referenced from:
      __GLOBAL__sub_I_costas_array.cc in costas_array.o
  "google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()", referenced from:
      std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<int, int>(int const&, int const&, char const*) in costas_array.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [bin/costas_array] Error 1
```

**Comment by bacalfa** [comment]
Sorry for the many messages, but it's frustrating that I'm unable to run the built project or even build it in certain cases. :( I'm curious to know the compiler and interpreter versions of those who are able to build and run the project.

```
iMac:or-tools bacalfa$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/7.3.0/libexec/gcc/x86_64-apple-darwin17.3.0/7.3.0/lto-wrapper
Target: x86_64-apple-darwin17.3.0
Configured with: ../configure --build=x86_64-apple-darwin17.3.0 --prefix=/usr/local/Cellar/gcc/7.3.0 --libdir=/usr/local/Cellar/gcc/7.3.0/lib/gcc/7 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-7 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-checking=release --with-pkgversion='Homebrew GCC 7.3.0' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --disable-nls
Thread model: posix
gcc version 7.3.0 (Homebrew GCC 7.3.0) 
```

```
iMac:or-tools bacalfa$ clang++ -v
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

```
iMac:or-tools bacalfa$ python -V
Python 3.6.4 :: Anaconda custom (64-bit)
```

**Comment by lperron** [comment]
I use xcode command line tools. I do not have any other compuler installed.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2018-02-10 21:06 GMT+01:00 Bruno Abreu Calfa <notifications@github.com>:

**Comment by lperron** [comment]
lperron-macbookpro4:or-tools lperron$ clang -v

Apple LLVM version 9.0.0 (clang-900.0.39.2)

Target: x86_64-apple-darwin17.4.0

Thread model: posix

InstalledDir: /Library/Developer/CommandLineTools/usr/bin


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2018-02-10 22:46 GMT+01:00 Bruno Abreu Calfa <notifications@github.com>:

**Comment by bacalfa** [comment]
Same `clang` as mine... are you able to `make python pypi_archive` and run `examples/python/integer_programming.py` as I mentioned above?

**Comment by lperron** [comment]
what seems to happen is that during make third_party, cmake picks another
compiler with an incompatible libstdc++.
I believe you can force the C++ compiler by setting the right env variable.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2018-02-10 22:48 GMT+01:00 Laurent Perron <lperron@google.com>:

**Comment by lperron** [comment]
I build and test or-tools daily

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2018-02-10 22:52 GMT+01:00 Bruno Abreu Calfa <notifications@github.com>:

**Comment by bacalfa** [comment]
I installed cmake via HomeBrew. What about you, @lperron? What's the version?

```
iMac:or-tools bacalfa$ cmake -version
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by bacalfa** [comment]
**Update**

I decided to start from scratch. Completely removed gcc from HomeBrew and ensured that every call to "gcc" points to "clang". Recloned the repository. Ran `make third_party`, updated Makefile.local to add support for SCIP (described [here](http://or-tools.blogspot.com/2017/03/changing-way-we-link-with-scip.html)), ran `make cc python pypi_archive`. No errors. Then:

```
iMac:or-tools bacalfa$ ./bin/integer_programming 
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0210 20:49:02.833678 2877076288 integer_programming.cc:67] ---- Integer programming example with CBC ----
I0210 20:49:02.838654 2877076288 integer_programming.cc:47] Problem solved in 4 milliseconds
I0210 20:49:02.838670 2877076288 integer_programming.cc:50] Optimal objective value = 6
I0210 20:49:02.838691 2877076288 integer_programming.cc:53] x1 = 6
I0210 20:49:02.838703 2877076288 integer_programming.cc:54] x2 = 0
I0210 20:49:02.838708 2877076288 integer_programming.cc:56] Advanced usage:
I0210 20:49:02.838713 2877076288 integer_programming.cc:57] Problem solved in 0 branch-and-bound nodes
I0210 20:49:02.838821 2877076288 integer_programming.cc:71] ---- Integer programming example with SCIP ----
I0210 20:49:02.844872 2877076288 integer_programming.cc:47] Problem solved in 6 milliseconds
I0210 20:49:02.844887 2877076288 integer_programming.cc:50] Optimal objective value = 6
I0210 20:49:02.844894 2877076288 integer_programming.cc:53] x1 = 6
I0210 20:49:02.844900 2877076288 integer_programming.cc:54] x2 = -0
I0210 20:49:02.844905 2877076288 integer_programming.cc:56] Advanced usage:
I0210 20:49:02.844910 2877076288 integer_programming.cc:57] Problem solved in 1 branch-and-bound nodes
```

Great! Then I installed the Python distribution with:

`iMac:or-tools bacalfa$ python temp-python3.6/ortools/setup.py install`

No errors. However:

```
iMac:~ bacalfa$ python Downloads/or-tools/examples/python/integer_programming.py 
Traceback (most recent call last):
  File "Downloads/or-tools/examples/python/integer_programming.py", line 17, in <module>
    from ortools.linear_solver import pywraplp
ImportError: cannot import name 'pywraplp'
```

This is because the install command doesn't copy over some of the files from the temp folder. This is what I have under "/Users/bacalfa/Downloads/or-tools/temp-python3.6/ortools/ortools/linear_solver":

![image](https://user-images.githubusercontent.com/1297074/36068595-c853fa90-0ea6-11e8-8181-5a6898a6358d.png)

and this is what I have under "/Users/bacalfa/anaconda3/lib/python3.6/site-packages/ortools-6.6.4830-py3.6-macosx-10.7-x86_64.egg/ortools/linear_solver":

![image](https://user-images.githubusercontent.com/1297074/36068603-f7ad4620-0ea6-11e8-992a-a838d246ceab.png)

What's going on?

Here's the full log of the python install command:

```
iMac:or-tools bacalfa$ python temp-python3.6/ortools/setup.py install
running install
running bdist_egg
running egg_info
writing ortools.egg-info/PKG-INFO
writing dependency_links to ortools.egg-info/dependency_links.txt
writing requirements to ortools.egg-info/requires.txt
writing top-level names to ortools.egg-info/top_level.txt
reading manifest file 'ortools.egg-info/SOURCES.txt'
writing manifest file 'ortools.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.macosx-10.7-x86_64/egg
creating build/bdist.macosx-10.7-x86_64/egg/ortools
creating build/bdist.macosx-10.7-x86_64/egg/ortools/util
copying build/lib/ortools/util/__init__.py -> build/bdist.macosx-10.7-x86_64/egg/ortools/util
creating build/bdist.macosx-10.7-x86_64/egg/ortools/graph
copying build/lib/ortools/graph/__init__.py -> build/bdist.macosx-10.7-x86_64/egg/ortools/graph
creating build/bdist.macosx-10.7-x86_64/egg/ortools/algorithms
copying build/lib/ortools/algorithms/__init__.py -> build/bdist.macosx-10.7-x86_64/egg/ortools/algorithms
copying build/lib/ortools/__init__.py -> build/bdist.macosx-10.7-x86_64/egg/ortools
creating build/bdist.macosx-10.7-x86_64/egg/ortools/sat
creating build/bdist.macosx-10.7-x86_64/egg/ortools/sat/python
copying build/lib/ortools/sat/python/__init__.py -> build/bdist.macosx-10.7-x86_64/egg/ortools/sat/python
copying build/lib/ortools/sat/python/visualization.py -> build/bdist.macosx-10.7-x86_64/egg/ortools/sat/python
copying build/lib/ortools/sat/python/cp_model.py -> build/bdist.macosx-10.7-x86_64/egg/ortools/sat/python
copying build/lib/ortools/sat/__init__.py -> build/bdist.macosx-10.7-x86_64/egg/ortools/sat
creating build/bdist.macosx-10.7-x86_64/egg/ortools/constraint_solver
copying build/lib/ortools/constraint_solver/__init__.py -> build/bdist.macosx-10.7-x86_64/egg/ortools/constraint_solver
creating build/bdist.macosx-10.7-x86_64/egg/ortools/data
copying build/lib/ortools/data/__init__.py -> build/bdist.macosx-10.7-x86_64/egg/ortools/data
creating build/bdist.macosx-10.7-x86_64/egg/ortools/linear_solver
copying build/lib/ortools/linear_solver/__init__.py -> build/bdist.macosx-10.7-x86_64/egg/ortools/linear_solver
copying build/lib/ortools/linear_solver/linear_solver_natural_api.py -> build/bdist.macosx-10.7-x86_64/egg/ortools/linear_solver
byte-compiling build/bdist.macosx-10.7-x86_64/egg/ortools/util/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/ortools/graph/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/ortools/algorithms/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/ortools/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/ortools/sat/python/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/ortools/sat/python/visualization.py to visualization.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/ortools/sat/python/cp_model.py to cp_model.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/ortools/sat/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/ortools/constraint_solver/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/ortools/data/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/ortools/linear_solver/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/ortools/linear_solver/linear_solver_natural_api.py to linear_solver_natural_api.cpython-36.pyc
creating build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying ortools.egg-info/PKG-INFO -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying ortools.egg-info/SOURCES.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying ortools.egg-info/dependency_links.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying ortools.egg-info/requires.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying ortools.egg-info/top_level.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
ortools.algorithms.__pycache__.__init__.cpython-36: module references __path__
ortools.constraint_solver.__pycache__.__init__.cpython-36: module references __path__
ortools.data.__pycache__.__init__.cpython-36: module references __path__
ortools.graph.__pycache__.__init__.cpython-36: module references __path__
ortools.linear_solver.__pycache__.__init__.cpython-36: module references __path__
ortools.sat.__pycache__.__init__.cpython-36: module references __path__
ortools.util.__pycache__.__init__.cpython-36: module references __path__
creating 'dist/ortools-6.6.4830-py3.6-macosx-10.7-x86_64.egg' and adding 'build/bdist.macosx-10.7-x86_64/egg' to it
removing 'build/bdist.macosx-10.7-x86_64/egg' (and everything under it)
Processing ortools-6.6.4830-py3.6-macosx-10.7-x86_64.egg
creating /Users/bacalfa/anaconda3/lib/python3.6/site-packages/ortools-6.6.4830-py3.6-macosx-10.7-x86_64.egg
Extracting ortools-6.6.4830-py3.6-macosx-10.7-x86_64.egg to /Users/bacalfa/anaconda3/lib/python3.6/site-packages
Adding ortools 6.6.4830 to easy-install.pth file

Installed /Users/bacalfa/anaconda3/lib/python3.6/site-packages/ortools-6.6.4830-py3.6-macosx-10.7-x86_64.egg
Processing dependencies for ortools==6.6.4830
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using /Users/bacalfa/anaconda3/lib/python3.6/site-packages
Searching for protobuf==3.5.1
Best match: protobuf 3.5.1
Processing protobuf-3.5.1-py3.6.egg
protobuf 3.5.1 is already the active version in easy-install.pth

Using /Users/bacalfa/anaconda3/lib/python3.6/site-packages/protobuf-3.5.1-py3.6.egg
Searching for setuptools==38.4.0
Best match: setuptools 38.4.0
Adding setuptools 38.4.0 to easy-install.pth file
Installing easy_install script to /Users/bacalfa/anaconda3/bin
Installing easy_install-3.6 script to /Users/bacalfa/anaconda3/bin

Using /Users/bacalfa/anaconda3/lib/python3.6/site-packages
Finished processing dependencies for ortools==6.6.4830
```

**Comment by Mizux** [comment]
Hi,

If you want to run "python setup.py install", you must have your working directory to be the directory of setup.py (i.e. path are relative to the setup.py directory)
cf: https://github.com/google/or-tools/blob/master/tools/build_delivery_mac.sh#L48

Currently, I'm thinking about adding a target `make install_python`, something like:
```Makefile
.PHONY: install_python # Install Python OR-Tools in the host system
install_python: pypi_archive
	@cd "$(PYPI_ARCHIVE_TEMP_DIR)$Sortools" &&  "$(PYTHON_EXECUTABLE)" setup.py install
```
**/!\\ not tested yet. /!\\**

ToDo: also use MAKEFILE_DIR := $(realpath $(dir $(lastword $(MAKEFILE_LIST))))

**Comment by Mizux** [comment]
I think, now this issue is fixed !

@bacalfa feel free to open a new issue concerning GCC issue on MacOS, but I don't know if it will be fixed...
