### ISSUE TITLE
Job Shop Tardiness - Python

### ISSUE THREAD

**Issue by Runslow** [google/or-tools#459]
I am trying to create a tardiness objective for a job shop problem in python. I see that there is an example in C++, however I am having trouble folowing the methodology to convert it to python.
example: https://github.com/google/or-tools/blob/master/examples/cpp/jobshop_earlytardy.cc

If anyone could help me out it would be appreciated. My problem is in how to create an IntVar that takes into account the end of the job including the due date. (starting with a simple completion - due date).

**Comment by Runslow** [comment]
I am currently stuck on how to create a tardiness IntVar to feed into the CP solver. I want to add an integer value for the due date to the IntVar value for the task completion. Using solver.Sum() I can add two IntVar values, however I am stuck on how to best convert the due date into an intVar.

**Comment by lperron** [comment]
I recommend looking at examples/cpp/jobshop_sat.cc

It supports tardiness, alternative resources, and most bells and whistles.

The tardiness is just a max((date - due date) * penalty_per_unit_of_time, 0)
