### ISSUE TITLE
cplusplus exampe of chap9 does not exist in the trunk

### ISSUE THREAD

**Issue by orwant** [google/or-tools#46]
Originally reported on Google Code with ID 30

```
What steps will reproduce the problem?
1. I can not find the tsptw code of chap9 in tutorials.

What is the expected output? What do you see instead?

I want to see the code example and if possible in C#, thanks.

What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Reported by `HotWingDelft` on 2013-08-06 13:08:12

**Comment by bloudermilk** [comment]
I wanted to piggy back on this, since it seems like the example code was never actually in the repo. Very useful utility classes like `TSPTWData` and the associated function `LoadTSPTWFile` are nowhere to be found. Is there an old archive somewhere that contains these?

**Comment by lperron** [comment]
Obsolote, closing
