### ISSUE TITLE
How do I install google or-tools for python in Ubuntu 16.04?

### ISSUE THREAD

**Issue by ashrafulhaq** [google/or-tools#460]
I was try to download google or-tools from https://developers.google.com/optimization/introduction/installing.html#unix_binary
but it show like to this https://github.com/google/or-tools/releases/download/v6.2/or-tools_python_examples_v6.2.4392.tar.gz
how to solve it?

**Comment by ilaif** [comment]
Hey @ashrafulhaq 

I've also encountered this problem. pip doesn't recognize the module for ubuntu 16.04, so I've searched pip repo for other modules.

Finally, I've found [ortools-ubuntu-16.04](https://pypi.python.org/pypi/ortools-ubuntu-16.04/6.3.4431).

So you can just type:
```bash
wget https://pypi.python.org/packages/e3/e5/b996057f4965fa98038c7b42f707e29ef0f08e33c635bf3b5887209239a0/ortools_ubuntu_16.04-6.3.4431-py2.7-linux-x86_64.egg#md5=34ef49fb6bdb32665b3d7c3ed168510c
sudo easy_install ortools_ubuntu_16.04-6.3.4431-py2.7-linux-x86_64.egg 
```

And it should install just fine (64-bit version).

Hope it helps,
Ilai.

**Comment by ashrafulhaq** [comment]
Thank you for your response I have already switched or-tools into MiniZinc.
