### ISSUE TITLE
VRP with updating distance matrix per accumulated time (traffic)

### ISSUE THREAD

**Issue by ilaif** [google/or-tools#461]
Hey guys,

I want to solve the VRP problem with duration-between-locations instead of the usual distance. Since traffic is very different at 10 am and 4 pm then the "optimal" solution should account for different duration-between-locations in different times.
I'm still new to constraint solving and I would like your help on how to implement this.
The new inputs to this problem are:
1. list of nodes with time windows.
2. a 3 dimensional (?) matrix of dimensions from_node, to_node, hour(binned seconds) and the cells will contain the duration (distance measure) between the nodes for every hour.

Now theoretically, using the cumulated variable we can know which distance to give.

Let me know if this is feasible with constraint solving and how to use the API to solve it.

Thanks a lot, 
Ilai

**Comment by ilaif** [comment]
@lperron , @furnon , @orwant - Any idea?

**Comment by emakarov** [comment]
I thought about this problem also. Issue is that callback for solver is formulated as a function with two variables.
Approximate solution might be if you estimate traffic-dependant time on pickup and delivery times for each pickup-delivery pair of nodes

**Comment by ilaif** [comment]
Thanks, @emakarov, it's indeed an improvement.
But mostly the time windows are too large to give a relevant average, and once there's traffic in the morning, it's very different than 2-3 hours afterward.
One hacky idea that I have after reading your suggestion, an iterative attempt:
- Load average traffic for the relevant time windows.
- Until some criterion is met (For example 5 times):
  - Find the best route.
  - Load average traffic for the now smaller "arriving time window" based on the computed route and times.
Then we might take the best solution of the 5, what this without mathematical reasoning does is to "check" the result by loading the new average traffic data for the result, and then if we hit a bad routing due to high traffic, then the solution will change since the current weights will be really bad, otherwise we will stay in the same solution.
But as I said it's kind of hacky, and I can imagine the hours as an additional constraint to the system that can be added to the original library.

**Comment by emakarov** [comment]
@ilaif the cpp api contains several functions that are not exposed to SWIG, which dedicated for this problem actually (transit-dependant travel times)

**Comment by ilaif** [comment]
@emakarov thanks! Can you point me in the right direction in the docs? Would appreciate that.

**Comment by emakarov** [comment]
I suppose its' routing.h#L448 and below (AddDimensionDependentDimensionWithVehicleCapacity ...)

**Comment by emakarov** [comment]
I also interested in this functionality, so created #480

**Comment by ilaif** [comment]
@lperron @Mizux any updates on this? Can this be done using `AddDimensionDependentDimensionWithVehicleCapacity`?
Thanks in advance.

**Comment by lperron** [comment]
This is still experimental. So I would advice not to use it for the time being.

**Comment by ilaif** [comment]
Thanks for keeping up with this @lperron, is there a suggested implementation for this? Even if experimental? I would like to try it out, thanks!

**Comment by lperron** [comment]
None.

Let's imagine you have 2 time matrices :

Heavy 7AM -> 9 AM, 4PM -> 7 PM
Light otherwise.

I would try an iterative approach, use a medium traffic matrix, compute a
solution, Reduce the time windows of the jobs to be inside their computed
time zone (heavy or light). Update the time matrix accordingly: heavy
between jobs in the heavy period, light between jobs in the light period,
blended when trips crosses the boundaries.

And resolve.

It will not be more inexact that forecasted traffic anyway.

Le mer. 7 août 2019 à 00:01, Ilai Fallach <notifications@github.com> a
écrit :

**Comment by ilaif** [comment]
Thanks, @lperron !
The problem that I see with this approach is that if during the first run, a route will be chosen in some time such that when running the second time with the updated matrix, the traffic will be the worst during that time in that specific route, then due to the time window constraints, the solution will be "stuck" in this geo-area, which is very likely all in heavy traffic.
So in a way, it's very susceptible to get stuck in a local optimum.
What do you think?

**Comment by lperron** [comment]
yes, it could be, but will it be worse than the error in forecasted traffic
times ?

Last time I looked at maps, for a 50km trip in the Silicon Valley, the
forecasted time was between 1hour and 2 hours.

You could imagine schedule everything with the peak hour traffic, then
relax visits in the non peak hour period, then add as many of those as
possible using the lift traffic distance matrix.

My point is that an iterative approach is simple to code/test.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 7 août 2019 à 10:41, Ilai Fallach <notifications@github.com> a
écrit :

**Comment by ilaif** [comment]
I totally agree with you, starting from peak hour weights sounds the best as it will surely make the solution "evade" from the worst-case which is what I truly fear. Thanks!

**Comment by mertbakir** [comment]
This is issue is very old, but I'm thinking about the implementation of the same problem. I wonder if there is some update or any new ideas you have? @lperron 

@ilaif Have you solve the issue?

**Comment by lperron** [comment]
No, and we will not for the foreseeable future.

**Comment by lperron** [comment]
That is the better solution.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le jeu. 17 juin 2021 à 10:29, Ilai Fallach ***@***.***> a
écrit :

**Comment by mertbakir** [comment]
Thanks for the answers.

**Comment by AMPechero** [comment]
Hi all! I was wondering if there are any updates about this (now in 2024), personally, I would like to use a different time matrix for each hour of the day so iterating the optimizer as proposed by ilaif doesn't seem enough accurate for my objective.
