### ISSUE TITLE
AddDisjunction with negative penalty - crashes the solver

### ISSUE THREAD

**Issue by emakarov** [google/or-tools#469]
Seems like #91 had the same problem. But proposed solution with SetDepot is no longer working, because SetDepot was removed from API.
So here's simplest case (ortools for python3, installed by pip, latest version):
```
from ortools.constraint_solver import pywrapcp
routing = pywrapcp.RoutingModel(101, 10, 0)
routing.AddDisjunction([1, 2], -1)
```

leads to
`
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0904 08:51:20.853919 2529715136 routing.cc:1326] Check failed: penalty >= 0 (-1 vs. 0) Penalty must be positive
*** Check failure stack trace: ***
Abort trap: 6
`

**Comment by furnon** [comment]
AddDisjunction does not support negative penalties (and never has). #91 was
a different problem.

**Comment by emakarov** [comment]
I see. but then, seems like documentation here
https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing.h#L520 is not very clear:
```
 "penalty" must be positive to make the disjunction optional; a negative
  // penalty will force one node of the disjunction to be performed, and
  // therefore p == 0.
```
sounds like penalty can be negative and in this case one node will be performed.

So, to achieve result when only one node can be performed, should I just use `AddDisjunction` without penalty argument?

**Comment by furnon** [comment]
You are correct that the doc does not match what the code does. Let me
check.

**Comment by furnon** [comment]
We pushed a fix which makes the code and the doc consistent. You can now
use any negative penalty value for mandatory nodes. Let us know if this
fixes your issue.

**Comment by emakarov** [comment]
thanks @furnon 
could you kindly update the https://pypi.python.org/pypi/py3-ortools package?

**Comment by furnon** [comment]
If you can wait until next week, a new release will be done then.

**Comment by emakarov** [comment]
sure, thanks.

**Comment by lperron** [comment]
release 6.4 is out with the fix.
