### ISSUE TITLE
VRP with time window constraints - Detect "problematic" constraints

### ISSUE THREAD

**Issue by ilaif** [google/or-tools#470]
Hey again guys,

When I'm solving a VRP problem with time window constraints, sometimes there is no feasible solution, or alternatively, the optimal solution is really bad because of a little portion of the locations' relative distance or time window constraints.

I want to be able, to some extent, extract from the solver after it failed or gave a bad solution, what are the main problems with the solution. Possible output:
1. No Solution: "Loosening" node index i constraints will allow a feasible solution.
2. Weak Solution: Optimal solution cost without constraints is much lower than current solution with constraints, "Loosening" node index i constraints will result in a relatively much better solution.

We can separate the discussion between No Solution at all and "Weak" Solution.

Let me know if it makes any sense and what are some possible ways to solve this problem.

Thanks!
Ilai.

**Comment by lperron** [comment]
With 7.0, you can selectively add disjunctions on visits 1 by 1.
This will help pinpoint the problematic nodes.
