### ISSUE TITLE
Can't install on CentOS 6.8

### ISSUE THREAD

**Issue by Gouravchawla** [google/or-tools#477]
I've tried installing it through binary, source, egg file given on pypi for centos but none of them seem to work. Any help on this would be much appreciated.

### Egg file installation:

Processing ortools_centos_7-6.3.4431-py2.7-linux-x86_64.egg
creating /home/apps/.virtualenvs/test1/lib/python2.7/site-packages/ortools_centos_7-6.3.4431-py2.7-linux-x86_64.egg
Extracting ortools_centos_7-6.3.4431-py2.7-linux-x86_64.egg to /home/apps/.virtualenvs/test1/lib/python2.7/site-packages
Adding ortools-centos-7 6.3.4431 to easy-install.pth file

Installed /home/apps/.virtualenvs/test1/lib/python2.7/site-packages/ortools_centos_7-6.3.4431-py2.7-linux-x86_64.egg
Processing dependencies for ortools-centos-7==6.3.4431
Searching for protobuf==3.3.0
Reading https://pypi.python.org/simple/protobuf/
Downloading https://pypi.python.org/packages/56/28/6263d846f60dad93939fd3a22d712d6bae3bf3484332d22bd5933dec8c99/protobuf-3.3.0.tar.gz#md5=27941e8e42e83d5183605054576882dd
Best match: protobuf 3.3.0
Processing protobuf-3.3.0.tar.gz
Writing /tmp/easy_install-9cUe75/protobuf-3.3.0/setup.cfg
Running protobuf-3.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-9cUe75/protobuf-3.3.0/egg-dist-tmp-GFBcYN
no previously-included directories found matching 'google/protobuf/internal/import_test_package'
warning: no previously-included files found matching 'google/protobuf/internal/*_pb2.py'
warning: no previously-included files found matching 'google/protobuf/internal/*_test.py'
warning: no previously-included files found matching 'google/protobuf/internal/*.proto'
warning: no previously-included files found matching 'google/protobuf/internal/test_util.py'
warning: no previously-included files matching '*_test.py' found under directory 'google'
warning: no previously-included files matching '*_test.proto' found under directory 'google'
warning: no previously-included files matching 'unittest*_pb2.py' found under directory 'google'
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
zip_safe flag not set; analyzing archive contents...
google.__init__: module references __path__
google.protobuf.__init__: module references __path__
google.protobuf.pyext.__init__: module references __path__
creating /home/apps/.virtualenvs/test1/lib/python2.7/site-packages/protobuf-3.3.0-py2.7.egg
Extracting protobuf-3.3.0-py2.7.egg to /home/apps/.virtualenvs/test1/lib/python2.7/site-packages
Adding protobuf 3.3.0 to easy-install.pth file

Installed /home/apps/.virtualenvs/test1/lib/python2.7/site-packages/protobuf-3.3.0-py2.7.egg
Searching for six>=1.9
Reading https://pypi.python.org/simple/six/
Downloading https://pypi.python.org/packages/b3/b2/238e2590826bfdd113244a40d9d3eb26918bd798fc187e2360a8367068db/six-1.10.0.tar.gz#md5=34eed507548117b2ab523ab14b2f8b55
Best match: six 1.10.0
Processing six-1.10.0.tar.gz
Writing /tmp/easy_install-PTDTg4/six-1.10.0/setup.cfg
Running six-1.10.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-PTDTg4/six-1.10.0/egg-dist-tmp-Gn7_9l
no previously-included directories found matching 'documentation/_build'
zip_safe flag not set; analyzing archive contents...
six: module references __path__
creating /home/apps/.virtualenvs/test1/lib/python2.7/site-packages/six-1.10.0-py2.7.egg
Extracting six-1.10.0-py2.7.egg to /home/apps/.virtualenvs/test1/lib/python2.7/site-packages
Adding six 1.10.0 to easy-install.pth file

Installed /home/apps/.virtualenvs/test1/lib/python2.7/site-packages/six-1.10.0-py2.7.egg
Finished processing dependencies for ortools-centos-7==6.3.4431

### Error on running the program using Ortools:
Traceback (most recent call last):
  File "vrp/api.py", line 3, in <module>
    import cvrp
  File "/home/apps/vrp/cvrp.py", line 2, in <module>
    from ortools.constraint_solver import pywrapcp
  File "/home/apps/.virtualenvs/test1/lib/python2.7/site-packages/ortools_centos_7-6.3.4431-py2.7-linux-x86_64.egg/ortools/constraint_solver/pywrapcp.py", line 17, in <module>
    _pywrapcp = swig_import_helper()
  File "/home/apps/.virtualenvs/test1/lib/python2.7/site-packages/ortools_centos_7-6.3.4431-py2.7-linux-x86_64.egg/ortools/constraint_solver/pywrapcp.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrapcp')
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _pywrapcp

**Comment by lperron** [comment]
Hi,

Clearly a mismatch in the system libraries.
Next release will use manylinux1 wheel files, and thus be portable.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-09-10 13:57 GMT+02:00 Gourav Chawla <notifications@github.com>:

**Comment by Gouravchawla** [comment]
That means I can't use it on CentOS 6.8 for now? I was able to install it on Ubuntu 14.04 though. But the production system has CentOS installed on it. 

When are you planning to make the next  release?

Thanks!

**Comment by lperron** [comment]
I just pushed the release.
The module name is just ortools (no suffix).

Can you try it out?

**Comment by Gouravchawla** [comment]
I'll be glad to. I'll report back after trying it.

**Comment by Gouravchawla** [comment]
The new package works. I've tried it on Centos 6.8 and Ubuntu 16.04.

Thank you so much for the quick response.
