### ISSUE TITLE
Transits depending on the cumuls of another dimension in python

### ISSUE THREAD

**Issue by emakarov** [google/or-tools#480]
Is there any plans to expose API to create dimension with transits depending on the cumuls of another dimension into SWIG?, i.e. AddDimensionDependentDimensionWithVehicleCapacity and corresponding functions in `routing.h` are now available only in cpp. 
As I understand from description, this API provides ability to solve VRP with traffic conditions.
Would be great to have this api in swig, in particular in python

**Comment by TheZepto** [comment]
I am interested in this also. Haven't been able to find a workaround that performs the specific task of this method.

**Comment by Mizux** [comment]
Seems a dupliate of #339

**Comment by lperron** [comment]
1) Not available in non C++ language.
2) still experimental.
