### ISSUE TITLE
Import error on Windows in py3-ortools 6.4.4495

### ISSUE THREAD

**Issue by CaselIT** [google/or-tools#487]
I've updated py3-ortools in windows 10 from version 6.3.4431 to 6.4.4495 in python 3.6.2 and I cannot import the new version:
```py
from ortools.linear_solver import pywraplp
...
ImportError: DLL load failed: The specified module could not be found.
During handling of the above exception, another exception occurred:
...
ModuleNotFoundError: No module named '_pywraplp'
```
The same error happens when importing the constraint_solver `from ortools.constraint_solver import pywrapcp`
The older version worked correctly

**Comment by lperron** [comment]
I think I updated the compiler from vs2015 to vs2017.
Can you check that you have the redistributable libraries for visual studio
2017 installed?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-09-20 23:33 GMT+02:00 Federico Caselli <notifications@github.com>:

**Comment by CaselIT** [comment]
Hi, I did not have visual c++ 2017 installed. I've installed from here https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads version 14.11.25325.0, but the problem is still present

I've rebooted after installing the redistributable as requested ( 😒 ) and uninstalled and reinstalled py3-ortools, but the same problem is still there.
Version 6.3 continues to work.

BTW I do not have VSC++ 2015 installed, the only other redistributable I have is, only the 2013 (12.0.30501.0),

**Comment by lperron** [comment]
I could build a full delivery locally on my windows machine.
Hopefully, everything will be fixed in the next release.
It that release, the dll was mixed and the delivered modules was linked against python 3.5.

**Comment by CaselIT** [comment]
Thanks @lperron 
I'll update the package once it's available and report back if it solves the issue

**Comment by lperron** [comment]
I just uploaded it.

Please note that I removed the py3 prefix.
So pip install ortools should work and pull release 6.5

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-02 16:15 GMT+02:00 Federico Caselli <notifications@github.com>:

**Comment by CaselIT** [comment]
Version 6.5.4527 is working fine on my system.
Thanks!
As a side note, __version__ is now correctly printed now

**Comment by lperron** [comment]
Good news :-)

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-02 16:42 GMT+02:00 Federico Caselli <notifications@github.com>:
