### ISSUE TITLE
Error in TSP solver

### ISSUE THREAD

**Issue by zenrshon** [google/or-tools#488]
May I get some help?

I installed or-tools and source code of or-tools-master in accordance with https://developers.google.com/optimization/introduction/installing.

And I typed "make test" in or-tools-master directory.
I got error described below.

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Python ver 3.5.2

..................
,,,,,
In Refute
sum([0, 2, 4, 6, 8]) = 20
sum([0, 2, 4, 6, 8]) = 20
cd dependencies/sources/protobuf-3.3.0/java && \
  ../../../install/bin/protoc --java_out=core/src/main/java -I../src \
  ../src/google/protobuf/descriptor.proto
cd dependencies/sources/protobuf-3.3.0/java/core/src/main/java && jar cvf ../../../../../../../install/lib/protobuf.jar com/google/protobuf/*java
/bin/sh: 1: jar: not found
makefiles/Makefile.third_party.unix.mk:246: recipe for target 'dependencies/install/lib/protobuf.jar' 
make: *** [dependencies/install/lib/protobuf.jar] error 127
..................

I can't understand what is shortage.

Please give me tips. Thanks.

**Comment by lperron** [comment]
can you print the result of 'make printport'

seems java is not correctly installed. It cannot find the jar executable.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-09-23 18:24 GMT+02:00 zenrshon <notifications@github.com>:

**Comment by zenrshon** [comment]
Thank you for answer.

I typed it and get below.

-------------------------
$ make print port
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
SHELL = /bin/sh
OR_TOOLS_TOP = /home/user/or-tools-master
SYSTEM = unix
PLATFORM = LINUX
PTRLENGTH = 64
GIT_REVISION = 0
GIT_HASH =
PORT = Ubuntu-16.04-64bit
OR_TOOLS_VERSION = 6.4.0
OR_TOOLS_SHORT_VERSION = 6.4
PATH_TO_CSHARP_COMPILER =
DETECTED_PYTHON_VERSION = 2.7
JDK_DIRECTORY = /usr/lib/jvm/java-8-openjdk-amd64 
-------------------------

I want to use or-tools by C++ and Python.

Should I install java?

Thanks.

**Comment by lperron** [comment]
No, but don't run make test but make test_cc test_python

and instead of make all, run make cc python



Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-09-24 8:10 GMT+02:00 zenrshon <notifications@github.com>:

**Comment by zenrshon** [comment]
Thank you for reply.

I re-installed or-tools-master and typed "make cc python" after "make third-party".

But, I get same error when I typed "make test".

I can not use "make test" without "make all"?

In this case, how to use this solver?

Sorry for rudimentary questions.

Thanks.

**Comment by lperron** [comment]
make test test everything, type make test_cc test_python



Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-09-25 6:39 GMT+02:00 zenrshon <notifications@github.com>:

**Comment by zenrshon** [comment]
Tried it.
And success!

Thank you very much!! :)
