### ISSUE TITLE
Install issue on Windows from ZIP. Saying I need 6.4.4495 when that is what is installed

### ISSUE THREAD

**Issue by matthewcrews** [google/or-tools#489]
I am trying to install on a Windows 10 machine. I am getting the following error at the end of the installation:

`Using c:\users\matthew-ws\anaconda3\lib\site-packages
Finished processing dependencies for ortools-examples==6.4.4495
[ERROR] You are using py3-ortools-(OR_TOOLS_VERSION) : C:\Users\Matthew-WS\AppData\Roaming\Python\Python36\site-packages\py3_ortools-6.4.4495-py3.6-win-amd64.egg\ortools\__init__.py, while the required version is : 6.4.4495
Run "C:\Users\Matthew-WS\Anaconda3\python.exe setup.py install --user" to upgrade.
If the problem persists, remove the site-package that contains "C:\Users\Matthew-WS\AppData\Roaming\Python\Python36\site-packages\py3_ortools-6.4.4495-py3.6-win-amd64.egg\ortools\__init__.py". You can do so either manually or by using pip.`

I try running the command that it suggests to fix this issue and it comes back saying everything is successful. I tried deleting the directory which containts the package and reinstalling but I get the same error.

When I run 'make check' I get this error:

`C:\Users\Matthew-WS\Downloads\or-tools_python_examples_v6.4.4495\ortools_examples>make check
[INFO] Python path : C:\Users\Matthew-WS\Anaconda3\python.exe
[INFO] Python version : 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]
[ERROR] You are using py3-ortools-(OR_TOOLS_VERSION) : C:\Users\Matthew-WS\AppData\Roaming\Python\Python36\site-packages\py3_ortools-6.4.4495-py3.6-win-amd64.egg\ortools\__init__.py, while the required version is : 6.4.4495
Run "C:\Users\Matthew-WS\Anaconda3\python.exe setup.py install --user" to upgrade.
If the problem persists, remove the site-package that contains "C:\Users\Matthew-WS\AppData\Roaming\Python\Python36\site-packages\py3_ortools-6.4.4495-py3.6-win-amd64.egg\ortools\__init__.py". You can do so either manually or by using pip.`

What is confusing is that it is saying that I am using 6.4.4495 but that I am supposed to use 6.4.4495. These are the same version number. Somewhere I must be doing something wrong. Is the fact that I am using Anaconda a problem?

**Comment by lperron** [comment]
yes I made (again) an error on the __version__ tag in the library.

One dirty hack would be to unzip the egg file, edit the ortools/__init__.py
to change the version tag, and rezip the egg file and install it locally.

It will be fixed in the next release (early october).

Sorry about that.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-09-24 6:04 GMT+02:00 Matthew <notifications@github.com>:

**Comment by matthewcrews** [comment]
Is this a problem only for Anaconda or any Windows Python 3.6 install?

**Comment by lperron** [comment]
I believe it is my modules which is incorrectly tagged.

You can also download the whl file and install it manually.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-09-26 0:33 GMT+02:00 Matthew <notifications@github.com>:

**Comment by lperron** [comment]
Hopefully, I fixed the problem in the source.
It should be fixed in the next release.

**Comment by lperron** [comment]
I have pushed the new release.
Please note that I merged py3-ortools into ortools. There is now only one module.

Thanks
