### ISSUE TITLE
Error building on Windows 10: tools\make: *** [objs/bop/bop_lns.obj] Error 2

### ISSUE THREAD

**Issue by pricebenjamin** [google/or-tools#493]
I've freshly installed VS Community 2017, cloned the repository, and executed `tools\make third_party`. However, when attempting `tools\make python`, the build exits with Error 2 when compiling `bop_lns.obj`.

Here's the full output:

`C:\ProgramData\or-tools>tools\make python`
<pre>
copy dependencies\\install\\bin\\protoc.exe dependencies\\sources\\protobuf-3.2.0\\src
        1 file(s) copied.
cd dependencies\\sources\\protobuf-3.2.0\\python && C:\ProgramData\Anaconda3\\python.exe setup.py build
running build
running build_py
cl /EHsc /MD /nologo -nologo  /O2 -DNDEBUG /I. /Iortools\\gen /IC:\\ProgramData\\or-tools\\dependencies\\install\\include /DGFLAGS_DLL_DECL= /DGFLAGS_DLL_DECLARE_FLAG= /DGFLAGS_DLL_DEFINE_FLAG= /IC:\\ProgramData\\or-tools\\dependencies\\install\\include  /IC:\\ProgramData\\or-tools\\dependencies\\install\\include /I\\include /DGOOGLE_GLOG_DLL_DECL= /IC:\\ProgramData\\or-tools\\dependencies\\install\\include /IC:\\ProgramData\\or-tools\\dependencies\\install\\include\\coin /DUSE_CBC /IC:\\ProgramData\\or-tools\\dependencies\\install\\include /IC:\\ProgramData\\or-tools\\dependencies\\install\\include\\coin /DUSE_CLP    /DUSE_GLOP /DUSE_BOP /D__WIN32__ /DPSAPI_VERSION=1 -c .\\ortools\\bop\\bop_lns.cc /Foobjs\\bop\\bop_lns.obj
bop_lns.cc
.\ortools/lp_data/sparse_vector.h(306): error C2039: 'IntegerRange': is not a member of 'operations_research::util'
.\ortools/base/cleanup.h(20): note: see declaration of 'operations_research::util'
.\ortools/lp_data/sparse_vector.h(305): note: while compiling class template member function 'util::IntegerRange<operations_research::glop::EntryIndex> operations_research::glop::SparseVector<operations_research::glop::ColIndex,operations_research::glop::SparseRowIterator>::AllEntryIndices(void) const'
.\ortools/lp_data/sparse_vector.h(963): note: see reference to function template instantiation 'util::IntegerRange<operations_research::glop::EntryIndex> operations_research::glop::SparseVector<operations_research::glop::ColIndex,operations_research::glop::SparseRowIterator>::AllEntryIndices(void) const' being compiled
.\ortools/lp_data/sparse_row.h(42): note: see reference to class template instantiation 'operations_research::glop::SparseVector<operations_research::glop::ColIndex,operations_research::glop::SparseRowIterator>' being compiled
.\ortools/lp_data/sparse_vector.h(306): error C2065: 'IntegerRange': undeclared identifier
.\ortools/lp_data/sparse_vector.h(306): error C2275: 'operations_research::glop::EntryIndex': illegal use of this type as an expression
.\ortools/lp_data/lp_types.h(64): note: see declaration of 'operations_research::glop::EntryIndex'
tools\make: *** [objs/bop/bop_lns.obj] Error 2
</pre>

I had a successful build earlier today on my desktop, but can't seem to reproduce my success on my Surface. The build has errored out at this same spot even after recloning the repo and reinstalling VS Community.

**Comment by pricebenjamin** [comment]
I was able to `git reset` back to commit `bb3ec00b0b40afc4e966c421f7ff8dc13bee2493` and successfully build and test. The above error occurred when attempting to build commit `bc46de013ff6f806d45a05680074ff39e22952ca`.

**Comment by lperron** [comment]
Thanks, I will have a look.

**Comment by lperron** [comment]
I just fixed it.

Thanks for the report.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-01 3:50 GMT+02:00 Ben Price <notifications@github.com>:

**Comment by pricebenjamin** [comment]
Thank you for your work! The issue is resolved.
