### ISSUE TITLE
CP-solver, `or` and `and` in Python are confusing.

### ISSUE THREAD

**Issue by helanhalvan** [google/or-tools#495]
Hi, 

I am very new to these tools, but found something that makes very little sense to me. With this code:
```
  con1=solver.FalseConstraint()
  con2=solver.TrueConstraint()
  con3=(con1 or con2)
  con4=(con1 and con2)
  print(con1,con2,con3,con4)
```
I would expect `con3` to be a `TrueConstraint()` and `con4` to be a `FalseConstraint()`, however the reverse it true. Full code:

```
from __future__ import print_function
import sys
import json
from ortools.constraint_solver import pywrapcp


def main():
  # Creates the solver.
  solver = pywrapcp.Solver("derp")

  con1=solver.FalseConstraint()
  con2=solver.TrueConstraint()
  con3=(con1 or con2)
  con4=(con1 and con2)
  solver.Add(con3)
  print(con1,con2,con3,con4)
  TST = [solver.IntVar(0, 1, "TST%i" % i) for i in range(2)]

  db = solver.Phase(TST,
                    solver.CHOOSE_FIRST_UNBOUND,
                    solver.ASSIGN_MIN_VALUE)
  solver.NewSearch(db)

  # Iterates through the solutions, displaying each.
  num_solutions = 0
  while solver.NextSolution(): #lets just print the entire solution space!
    # Displays the solution just computed.
    num_solutions += 1
  solver.EndSearch()
  print(res)
  print("Solutions found:", num_solutions)
  print("Time:", solver.WallTime(), "ms")
main()
```
Sample output:
```
$ python bug.py
FalseConstraint() TrueConstraint() FalseConstraint() TrueConstraint()

Solutions found: 0
Time: 0 ms
```
I got Or-tools from pip3, and is using it with Ubuntu Mate 16.04 and Python 3.5.2. 

EDIT:

It seems like it is just that python allows `or` and `and` to have anything as operands, and both `FalseConstraint` and `TrueConstraint` are considered true.

Anyway, say that I would like this behavior, I have some constraint `conNa` and `conNb`, any you need `conNa` and `conNb` to be true, for some N.

**Comment by JKBehrens** [comment]
Please check the section "Combining constraints by "and" versus "or"" in the Documentation: https://developers.google.com/optimization/cp/cp_solver

**Comment by lperron** [comment]
What is the problem?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-11-13 20:05 GMT+01:00 Jan Behrens <notifications@github.com>:

**Comment by JKBehrens** [comment]
I guess @helanhalvan has not read the following:

>  Caution: Combining constraints using the Boolean "and" or "or" operators (such as solver.Add(constraint1 and constraint2) does not give the expected results — the solver simply ignores the second constraint.

**Comment by helanhalvan** [comment]
@JKBehrens I did find that, but I have not found suitable workarounds. For other systems like Gecode I have worked with before, there are ways of adding implications between constraints, things like: if ConstraintA is true ConstraintB also have to be true. 

I would expect your constraint solver had similar functionality, but haven't found it. If you read under `EDIT:` I have a case where I generate 2N constraints, (where N is determined by the instance data), constraints of type `AN` and `BN`, and need only a single pair for constraints `AN` and `BN` to hold, but for the same N, so for example, N=3, constraints are: A1, B1, A2, B2, A3, B3, I need to express that `(A1 and B1) or (A2 and B2) or (A3 and B3)` hold.

**Comment by lperron** [comment]
Bottomline, use the SAT backend :-)

The code is in ortools/sat/python/cp_model.py

Examples are in examples/python/*sat.py.

The idea is the following

You have boolean variables.
Boolean variables (x) or its negation (x.Not()) can be use to imply the
constraint:

x  => constraint

These are half reified constraints as this is only an implication.

If you want to have a full equivalence, you need 2 implication.

x => (y > 10)
x.Not() => (y <= 9)

Compared to the pure CP code you have looked at, it is a bit more code.
But you can express boolean => complex constraint (like alldifferent) which
was impossible with the pure CP approach.

Then you have boolean or and and directly in the model.

I hope this helps.

On the bonus side, performance of the SAT backend is much better than the
performance of the CP backend.

--Laurent

PS: I will do a or-tools release (likely this week) that contains the whole
code. Until then, you need to build from sources.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-11-14 13:07 GMT+01:00 helanhalvan <notifications@github.com>:

**Comment by helanhalvan** [comment]
@lperron Is there any documentation for this magical SAT backend?

**Comment by lperron** [comment]
Everything is document in the cp_model.py (even in a terse way).

Run pydoc on it.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-11-14 13:36 GMT+01:00 helanhalvan <notifications@github.com>:
