### ISSUE TITLE
min_cost_flow fails with 'std::bad_alloc' while adding arc with capacity in graph

### ISSUE THREAD

**Issue by swapnilushinde** [google/or-tools#497]
Hello 
I am running min_cost_flow on very large graph that has around 30M edges, Running or-tools with java. 
_minCostFlow.addArcWithCapacityAndUnitCost_ fails with 'std::bad_alloc' after adding around 1M edges. I am allocating huge java heap memory so it's definitely not a memory problem from java heap. same code runs fine when my graph has 50M edges. I am running it on ubuntu host with compiled binaries.

Any suggestions are very much appreciated. Let me know if you need any further info.

**Comment by lperron** [comment]
You have exceeded the memory limit of the STL (2GB).

Nothing I can do.
