### ISSUE TITLE
VRPTW . Service time problem

### ISSUE THREAD

**Issue by LevchenkoKI** [google/or-tools#498]
Hi, thanks, library is amazing.
I use c# version and got problem, which can not solve. In example on a python there is a solution with service time as part of total time:

```csharp
 service_times = CreateServiceTimeCallback(demands, time_per_demand_unit)
 service_time_callback = service_times.ServiceTime

 travel_times = CreateTravelTimeCallback(dist_callback, speed)
 travel_time_callback = travel_times.TravelTime

 total_times = CreateTotalTimeCallback(service_time_callback, travel_time_callback)
 total_time_callback = total_times.TotalTime

 routing.AddDimension(total_time_callback,  # total time function callback
                         horizon,
                         horizon,
                         fix_start_cumul_to_zero,
                         time).
```
But I don't need to travel time and total time.
I solve situation not as delivery , but as plumber's work, I mean, that plumber needs to have a service time in each order. Supposably, that service time is constant. I created 
       
```csharp
class ServiceTimeCallback : NodeEvaluator2 {
  public ServiceTimeCallback(int time_per_demand_unit) {
    this.time_per_demand_unit = time_per_demand_unit;
  }
  public override long Run(int first_index, int second_index) {
     return time_per_demand_unit;
  }
  private int time_per_demand_unit;
};
```
And call it in solver

```csharp
var sevice_time_callback = new ServiceTimeCallback(1*60);
model.AddDimension(sevice_time_callback, 24*60,24*60, false, "sevice_time");
```

The solver returns solution as if service time would not declared. The situation repeats while I dont change ServiceTimeCallback argument to 10 hour (ServiceTimeCallback(10*60)) . After that 1 order can service 1 plumber per day(that is logical) .  What should I do to solve this problem?

**Comment by mendoza9805** [comment]
from __future__ import print_function
from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp

def create_data_model():
	"""Stores the data for the problem."""
	data = {}
	data['time_matrix'] = [
	  [0, 25, 26, 37, 19, 42, 35, 37, 34, 14, 39, 43],
		[25, 0, 18, 12, 6, 31, 23, 25, 22, 11, 27, 18],
		[26, 18, 0, 30, 20, 16, 19, 12, 12, 18, 21, 36],
		[37, 12, 30, 0, 18, 32, 24, 26, 23, 23, 28, 13],
		[19, 6, 20, 18, 0, 36, 29, 31, 28, 6, 33, 24],
		[42, 31, 16, 32, 36, 0, 8, 6, 9, 34, 8, 23],
		[35, 23, 19, 24, 29, 8, 0, 7, 7, 27, 4, 17],
		[37, 25, 12, 26, 31, 6, 7, 0, 3, 29, 10, 24],
		[34, 22, 12, 23, 28, 9, 7, 3, 0, 26, 9, 24],
		[14, 11, 18, 23, 6, 34, 27, 29, 26, 0, 31, 29],
		[39, 27, 21, 28, 33, 8, 4, 10, 9, 31, 0, 15],
		[43, 18, 36, 13, 24, 23, 17, 24, 24, 29, 15, 0],
	]
	data['time_windows'] = [
	    (0, 1000), 	#depot
		(30, 120),	#1
		(30, 120),	#2
		(30, 120),	#3
		(30, 120),	#4
		(30, 120),	#5
		(30, 120),	#6
		(120, 360),	#7	
		(90, 270),	#8
		(90, 270),	#9
		(150, 210),	#10
		(150, 210),	#11
	]
	data['num_vehicles'] = 10
	data['depot'] = 0
	data['demands'] = [0, 39, 40, 37, 20, 4, 55, 50, 37, 36, 58, 19]
	data['vehicle_capacities'] = [120, 120, 120, 120, 120, 120, 120, 120, 120, 120]
  data['atention_time']=[0, 45, 45, 45, 45, 45, 45, 30, 45, 45, 30, 30]
  data['vehicle_speed'] = 0,33  # Travel speed: 20km/h converted in m/min
	return data

def print_solution(data, manager, routing, assignment):
	"""Prints assignment on console."""
	time_dimension = routing.GetDimensionOrDie('Time')
	total_time = 0
	for vehicle_id in range(data['num_vehicles']):
		index = routing.Start(vehicle_id)
		plan_output = 'Route for vehicle {}:\n'.format(vehicle_id)
		while not routing.IsEnd(index):
			time_var = time_dimension.CumulVar(index)
			plan_output += '{0} Time({1},{2}) -> '.format(
				manager.IndexToNode(index), assignment.Min(time_var),
				assignment.Max(time_var))
			index = assignment.Value(routing.NextVar(index))
		time_var = time_dimension.CumulVar(index)
		plan_output += '{0} Time({1},{2})\n'.format(
			manager.IndexToNode(index), assignment.Min(time_var),
			assignment.Max(time_var))
		plan_output += 'Time of the route: {}min\n'.format(
			assignment.Min(time_var))
		print(plan_output)
		total_time += assignment.Min(time_var)
	print('Total time of all routes: {}min'.format(total_time))

def main():
	"""Solve the VRP with time windows."""
	data = create_data_model()
	manager = pywrapcp.RoutingIndexManager(
		len(data['time_matrix']), data['num_vehicles'], data['depot'])
	routing = pywrapcp.RoutingModel(manager)
  
	# Add Capacity constraint.
	def demand_callback(from_index):
		"""Returns the demand of the node."""
		# Convert from routing variable Index to demands NodeIndex.
		from_node = manager.IndexToNode(from_index)
		return data['demands'][from_node]

	demand_callback_index = routing.RegisterUnaryTransitCallback(
		demand_callback)
	routing.AddDimensionWithVehicleCapacity(
		demand_callback_index,
		0,  # null capacity slack
		data['vehicle_capacities'],  # vehicle maximum capacities
		True,  # start cumul to zero
		'Capacity')

	def time_callback(from_index, to_index):
		"""Returns the travel time between the two nodes."""
		# Convert from routing variable Index to time matrix NodeIndex.
		from_node = manager.IndexToNode(from_index)
		to_node = manager.IndexToNode(to_index)
		return data['time_matrix'][from_node][to_node]

	transit_callback_index = routing.RegisterTransitCallback(time_callback)
	routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)
	time = 'Time'
	routing.AddDimension(
		transit_callback_index,
		3000,  # allow waiting time
		3000,  # maximum time per vehicle
		False,  # Don't force start cumul to zero.
		time)
	time_dimension = routing.GetDimensionOrDie(time)
 
	# Add time window constraints for each location except depot.
	for location_idx, time_window in enumerate(data['time_windows']):
		if location_idx == 0:
			continue
		index = manager.NodeToIndex(location_idx)
		time_dimension.CumulVar(index).SetRange(time_window[0], time_window[1])
	# Add time window constraints for each vehicle start node.
	for vehicle_id in range(data['num_vehicles']):
		index = routing.Start(vehicle_id)
		time_dimension.CumulVar(index).SetRange(data['time_windows'][0][0],
												data['time_windows'][0][1])
	for i in range(data['num_vehicles']):
		routing.AddVariableMinimizedByFinalizer(
			time_dimension.CumulVar(routing.Start(i)))
		routing.AddVariableMinimizedByFinalizer(
			time_dimension.CumulVar(routing.End(i)))
	search_parameters = pywrapcp.DefaultRoutingSearchParameters()
	search_parameters.first_solution_strategy = (
		routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)
	assignment = routing.SolveWithParameters(search_parameters)
	if assignment:
		print_solution(data, manager, routing, assignment)

**Comment by Mizux** [comment]
In this case you should take a look at Capacity VRP example and register an unary function callback (since your service time(i.e. quantity) only depend on the current node).
ref: https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/doc/VRP.md#capacity-constraints

i.e. the capacity/load can be seen as a service time duration IMHO...

I think the slack var should be zero and you should set `/*start_cumul_to_zero=*/True` instead.

**Comment by AschkanOmidvar** [comment]
I have a similar problem as LevchenkoKI: 

In my routing problem the service time at nodes have much larger magnitude than travel times between nodes. For example service time at node _i_ is 10 days and at node _j_ is 13 days but the travel time between nodes is 15 minutes. I need to minimize the distance (or travel time) while putting time windows on nodes. So travel time is ignorable and cumul (_j_) should be cumul (_i_) + service_time (_i_). 

I cannot add service time to travel distance as mentioned here: https://github.com/google/or-tools/issues/1202) because service time will dominate the travel time and the solution won't be the shortest path. 

So is there a way to keep the objective function as minimize travel distance and define a dimension that tracks the cumulative service time and set time-windows on nodes using that cumulative service time?

Thanks.

**Comment by Mizux** [comment]
@AschkanOmidvar Yes you can use setArcCost to use a distance transit callback.
then add A Time Dimension with an other time matrix cost (service time + travel time)., by default all dimensions are just "constraint" since the coefficient of make span is 0, i.e. they won't participate to the objective function

**Comment by AschkanOmidvar** [comment]
I appreciate your responsiveness @Mizux
