### ISSUE TITLE
Hours of Service Regulations

### ISSUE THREAD

**Issue by bendichter** [google/or-tools#500]
I am interested in implementing Hours of Service Regulations, which limit the hours a driver can operate a truck as constraints in my optimization:

https://www.fmcsa.dot.gov/regulations/hours-service/summary-hours-service-regulations

I do not think this is covered in the examples, but it seems like a problem many people will have with vehicle routing. Has anyone implemented this or does anyone have ideas how one would go about it?

Thanks.

**Comment by orwant** [comment]
Hi Ben, these are typically called time windows. We've got an example here:

https://developers.google.com/optimization/routing/tsp/vehicle_routing_time_windows

If there's anything we can do to make the documentation clearer, let us
know!

Jon

**Comment by bendichter** [comment]
Hi Jon,

Thanks for the help. I think these time windows are referring to constraints on shipments i.e. when they need to be delivered. 

The constraints I am looking for are on the vehicles. I want to say something like "this vehicle must take a break after driving 11 hours". I think I found a lead [here](https://github.com/google/or-tools/blob/v6.0/examples/cpp/cvrptw_with_breaks.cc), however there are two issues I still can't figure out. The first is how I set up the proper relation between constraints. This example enforces that two breaks are *at least* 1 hour apart, but I want one that is *at most* 11 hours apart. The second issue is that I have written the rest of this in python, and I am not sure how to port this over. Specifically, I am looking for `operations_research::Solver::STARTS_AFTER_END` (or another condition if it handles my needs).

**Comment by bendichter** [comment]
I figured it out. In python it's a method of InvervalVar

**Comment by Abhi001vj** [comment]
Would you please tell how did you implement it? I am not finding a method named  InvervalVar under ortools.constraint_solver import pywrapcp or in pywrapcp.RoutingModel and I am not sure how I can add that as a constraint.

**Comment by lperron** [comment]
It is a method of pywrapcp.Solver
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
