### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by WillAyd** [google/or-tools#503]
After a source installation when running:
`from or tools.linear_solver import pywraplp`

I get:
`ModuleNotFoundError: No module named 'six'`

This is easily resolved using a package manager and installing the six package, but is there any reason why we wouldn't include this in setup.py as an installation requirement?

**Comment by lperron** [comment]
Just a bug. Thanks for the report.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-13 15:40 GMT-07:00 William Ayd <notifications@github.com>:

**Comment by lperron** [comment]
I fixed it in the source code.
It will be available in the next release.

**Comment by Mizux** [comment]
for the record fixed by 3735e730318773876541ff02d7629fc69948d946
