### ISSUE TITLE
use SetCumulVarSoftLowerBound in java

### ISSUE THREAD

**Issue by jaja7** [google/or-tools#505]
i want to use `SetCumulVarSoftLowerBound` in tsp with java, but i cannot find this function. Is there any one who has used it before?

**Comment by furnon** [comment]
Did you try both SetCumulVarSoftLowerBound and setCumulVarSoftLowerBound ?

**Comment by jaja7** [comment]
@furnon thank u for replying. I have tried both of these two functions, but it doesn't work.
In addition, i can use setCumulVarSoftUpperBound  successfully, but cannot find SetCumulVarSoftLowerBound. This is  so strange.

**Comment by lperron** [comment]
Checked it is i 7.3
