### ISSUE TITLE
LP Constraints and Variables as Instance Methods in Python

### ISSUE THREAD

**Issue by WillAyd** [google/or-tools#506]
The linear solver Python wrapper would be aided by exposing the "variables" and "constraints" that have been added to the solver as instance methods. I've created the code to do this (and cleaned up the appropriate test module) in my fork of ortools - any interest in merging this into the actual codebase?

https://github.com/WillAyd/or-tools/commit/57a5327de5dc9064cb766a6486e303ed16bb419c

**Comment by lperron** [comment]
Interesting. Let me think about it.

**Comment by lperron** [comment]
OK, I will implement it, but not with your PR.
