### ISSUE TITLE
libprotobuf.a: No such file or directory

### ISSUE THREAD

**Issue by cgalleguillosm** [google/or-tools#508]
Hi, I'm installing from the source in a Fedora x64 machine. After trying to generate the python lib, the following error appears:
```
g++: error: or-tools/dependencies/install/lib/libprotobuf.a: No such file or directory
make: *** [makefiles/Makefile.cpp.mk:625: lib/libortools.so] Error 1
```
Looking into the makefiles, in the **Makefile.unix.mk**, seem to be an incorrect if statement:
```
  ifeq ($(DISTRIBUTION_ID),CentOS)
    PROTOBUF_LNK = $(UNIX_PROTOBUF_DIR)/lib64/libprotobuf.a
  else
    PROTOBUF_LNK = $(UNIX_PROTOBUF_DIR)/lib/libprotobuf.a
  endif
```
I changed the if statement for 
`  ifeq ($(PTRLENGTH),64)`
then, it was possible to generate the python lib.

**Comment by lperron** [comment]
Yes and no.
On ubuntu, debian, even on 64 bit platforms, the libs are in lib/, not
lib64/.

Can you give me the DISTRIBUTION_ID on fedora?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-21 16:40 GMT+00:00 cgalleguillosm <notifications@github.com>:

**Comment by cgalleguillosm** [comment]
It's Fedora 

Sent from my ASUS

-------- Mensaje original --------
De:lperron <notifications@github.com>
Enviado:Sun, 22 Oct 2017 10:26:55 +0200
Para:google/or-tools <or-tools@noreply.github.com>
Cc:cgalleguillosm <cristian.galleguillos.m@mail.pucv.cl>,Author <author@noreply.github.com>
Asunto:Re: [google/or-tools] libprotobuf.a: No such file or directory (#508)

**Comment by lperron** [comment]
I just pushed the fix in Makefile.unix.
Can you check it?

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-22 16:00 GMT+02:00 cgalleguillosm <notifications@github.com>:

**Comment by cgalleguillosm** [comment]
>
> makefiles/Makefile.unix.mk:145: *** missing separator.  Stop.
>

the problem is the *elif* conditional, it must be replaced by *else ifeq*

Best regards,
Cristian

2017-10-23 10:22 GMT+02:00 lperron <notifications@github.com>:

**Comment by lperron** [comment]
Done.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-23 18:25 GMT+00:00 cgalleguillosm <notifications@github.com>:

**Comment by cgalleguillosm** [comment]
>
> makefiles/Makefile.unix.mk:197: *** extraneous 'endif'.  Stop.
>
Only one *endif* is required.


2017-10-23 21:59 GMT+02:00 lperron <notifications@github.com>:

**Comment by jmarca** [comment]
I just hit this bug in slackware linux.  Protobuf was installed into `./dependencies/install/lib64`, and `make python` failed claiming that protobuf could not be found in `./dependencies/install/lib/libprotobuf.a`.

My hacked solution was just to symlink the contents of `dependencies/install/lib64/libprotobuf...` into `dependencies/install/lib`.  Then `make python` worked fine.

**Comment by Mizux** [comment]
I'll try to add Docker for Fedora, Alpine, Slackware if possible. But first I need to clean a little the [Docker Makefile](https://github.com/google/or-tools/blob/master/tools/docker/Makefile).

**Comment by jmarca** [comment]
Forgot I posted this!  Anyway I'm just running this with Docker these days. Much less friction than running in Slackware and more easily deployable for production.

**Comment by Mizux** [comment]
We are now using shared library and Fedora is not officially supported.
I'm closing this issue, don't hesitate to reopen it after testing with a recent release if problem still occur...
