### ISSUE TITLE
docker installation error on ubuntu, libprotobuf.a not found

### ISSUE THREAD

**Issue by saglammurat** [google/or-tools#511]
in ubuntu 16.04

got or-tools with git clone,

then did this:
```sh
cd or-tools/tools/docker
make python
```
got this error:
```sh
g++: error: /root/src/dependencies/install/lib/libprotobuf.a: No such file or directory
make: *** [lib/libortools.so] Error 1
Makefile:127: recipe for target 'manylinux1-pypi' failed
make: *** [manylinux1-pypi] Error 2
```
any ideas? 

many thanks...

**Comment by lperron** [comment]
Let me check.


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-25 15:10 GMT+02:00 saglammurat <notifications@github.com>:

**Comment by saglammurat** [comment]
thanks, it works now.

**Comment by Mizux** [comment]
Now depends on #838

**Comment by Mizux** [comment]
1) tools/docker is only use for building package on different distro is not a docker for having a ortools solver.

2) You should look to https://github.com/google/or-tools/blob/master/tools/docker/ubuntu-16.04.Dockerfile as base to build an Ubuntu docker...

**Comment by Mizux** [comment]
Can't reproduce it and fix compile concerning non ASCII characters
