### ISSUE TITLE
How to use or-tools and the latest protobuf in the same project?

### ISSUE THREAD

**Issue by Zhouxing-Su** [google/or-tools#514]
It seems that the or-tools integrates protobuf 3.2 whose latest version is 3.4.

The `GOOGLE_PROTOBUF_VERSION` and `GOOGLE_PROTOBUF_MIN_PROTOC_VERSION` checks are quite strict that both of them require the library and the generated code to be exactly the same version.

Is it possible to use or-tools and the latest protobuf in the same project?

**Comment by lperron** [comment]
Which language/platform?

python, nuget?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-26 13:33 GMT+00:00 Kirk <notifications@github.com>:

**Comment by Zhouxing-Su** [comment]
Sorry for that.
I thought the version check on library and the generated code should be consistent in every language/platform so I forgot to mention it.

I was using or-tools 6.5 x64 and protobuf 3.4.1 x64 via C++ interface in Visual Studio 2015 on Windows 10.

There is already a stand-alone protobuf in the project, and I just found out that I could utilize some algorithms in the or-tools. But putting them together and adding them to the include directories lead to compilation errors.

The directory organization looks like:
```
lib/
  protobuf/
    bin/
    include/
    lib/
  ortools/
    bin/
    include/
    lib/
```

**Comment by lperron** [comment]
I see two solutions:
  - hack the delivered lib to remove the protobuf obj files.
  - build from source specifying an alternate WINDOWS_PROTOBUF_DIR in
Makefile.local.

The second option may be hacky too as I link with static versions of the
protobuf lib.

I will update the protobuf tag in dependency files for the next release.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-27 1:09 GMT+00:00 Kirk <notifications@github.com>:

**Comment by Zhouxing-Su** [comment]
That will be great. Thanks!

**Comment by lperron** [comment]
Fixed. We use the latest version of protobuf.
