### ISSUE TITLE
[Question] How to set 'hard' lower bound for a vehicle/route 

### ISSUE THREAD

**Issue by thucnc** [google/or-tools#515]
In the routing library, I found the method 
[void SetEndCumulVarSoftLowerBound(int vehicle, int64 lower_bound, int64 ((coefficient);](https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing.h#L1002), but this method does not strictly enforce the vehicle to have cumulvar value greater than the lower bound as I expected. 

In the same file, I found the following comment: 
> // Returns the soft lower bound of a cumul variable for a given node. The
  // "hard" lower bound of the variable is returned if no soft lower bound has
  // been set.

So I wonder if there is any way to set a "hard" lower bound, that forces the routes must be greater or equal a defined value.

**Comment by thucnc** [comment]
PS: I tried `dimension.CumulVar(routing.End(vehicle)).SetMin(10)` but it doesn't work (no solution), so I think it's because there are empty vehicles that can't satisfy this condition.

**Comment by andersonjeemon** [comment]
how can one achieve  SetEndCumulVarSoftLowerBound by using  RemoveInterval . can you please explain. I have similar issue

**Comment by duylamasd** [comment]
By using the RemoveInterval method, we forced the solver to solve for all vehicles, the cumulVar of the dimension at the end of route must be out of the interval [0, lower_boundd]. Since the cumulVar can not be less than 0, the condition becomes: 'the cumulVar must be greater than the lower_bound'.

Sorry for my bad English.

**Comment by andersonjeemon** [comment]
Do you have any related documents which you can share?

**Comment by junquant** [comment]
> Hey,
> I am trying to implement a minimum used capacity as well, but I have a problem with the solution proposed by @duylamasd. The solver doesn't find any solutions because some vehicles will not be used. Is there any solution to this?
> Thank you

Instead of (0, lower_bound), set it to (1, lower_bound) like
`dimension.CumulVar(routing.End(vehicle)).RemoveInterval(0, lower_bound)`
such that routes with 0 (vehicles that are not used) as included and anything between 1 and the lower_bound is not.

**Comment by mitanshu001** [comment]
SetEndCumulVarSoftUpperBound(int, const std::string&, int64, int64) is currently not available for python. How to set 'soft' lower bound on the destination node in python?
Thanks in advance

**Comment by yerimchoi** [comment]
The solution proposed by @junquant seems working on Python.

`location_dimension = routing.GetDimensionOrDie('Location')
    for vehicle_id in range(data['num_vehicles']):
        index = routing.End(vehicle_id)
        location_dimension.CumulVar(index).RemoveInterval(1, 3)`

**Comment by ksinght86** [comment]
Thanks @junquant 
Wanted to add one more thing here looking for answers, make sure you are setting the right slack for the cumulVar, else it will let the engine skip the interval using the slack provided.
For me even removing the interval was not giving the desired result, but later realized the slack variable was letting the engine bring the cumulVal's value in the valid range.
model.addDimensionWithVehicleTransitAndCapacity(weightLoadDimensionArr, 0<<I made the slack 0>>, solverRequest.vehicleWeights, true, Constants.TOTAL_LOAD_WEIGHT);
weightDimension.cumulVar(model.end(vehicle)).removeInterval(1, 80000);
