### ISSUE TITLE
fzn-or-tools: Closer objective bounds make problem unsatisfiable

### ISSUE THREAD

**Issue by HelgeS** [google/or-tools#517]
Hi,

I have set close bounds on the objective variable of a minizinc model to speed-up the solving process.
These bounds lead or-tools to (wrongly) declare the instance as unsatisfiable, although the actual optimal value is still within the bounds.

Output without additional constraints:
```
s = 4;
objective = 433;
a = array2d(1..10, 1..25, [5, 3, 2, 3, 3, 2, 2, 2, 5, 1, 1, 3, 5, 1, 4, 1, 1, 3, 3, 4, 4, 4, 5, 5, 5, 5, 3, 2, 3, 1, 5, 2, 2, 4, 1, 1, 3, 4, 1, 4, 1, 1, 3, 3, 5, 5, 2, 4, 4, 4, 1, 2, 2, 3, 1, 5, 3, 5, 4, 1, 3, 2, 4, 1, 4, 1, 1, 5, 1, 3, 5, 2, 4, 4, 4, 4, 1, 5, 1, 1, 5, 3, 5, 4, 2, 3, 2, 4, 2, 2, 1, 3, 5, 2, 3, 5, 1, 4, 4, 4, 4, 1, 5, 1, 1, 5, 3, 5, 4, 2, 3, 2, 4, 2, 2, 1, 3, 5, 2, 3, 5, 1, 4, 4, 4, 4, 1, 5, 1, 1, 5, 3, 5, 4, 2, 3, 2, 4, 2, 2, 1, 3, 5, 2, 3, 5, 1, 4, 4, 4, 4, 1, 5, 1, 1, 5, 3, 5, 4, 2, 3, 2, 4, 2, 2, 1, 3, 5, 2, 3, 5, 1, 4, 4, 4, 4, 1, 5, 1, 1, 5, 3, 5, 4, 2, 3, 2, 4, 2, 2, 1, 3, 5, 2, 3, 5, 1, 4, 4, 4, 4, 1, 5, 1, 1, 5, 3, 5, 4, 2, 3, 2, 4, 2, 2, 1, 3, 5, 2, 3, 5, 1, 4, 4, 4, 4, 1, 5, 1, 1, 5, 3, 5, 4, 2, 3, 2, 4, 2, 2, 1, 3, 5, 2, 3, 5, 1, 4, 4, 4]);
----------
==========
```

I'm setting the bounds with these constraints:
`constraint 400 <= objective /\ objective <= 500;`

Output with the addtional constraints:
```
=====UNSATISFIABLE=====
```

Here is the original minizinc model: http://www.minizinc.org/challenge2017/mznc2017_probs/tc-graph-color/tcgc2.mzn
Here is the corresponding data file: http://www.minizinc.org/challenge2017/mznc2017_probs/tc-graph-color/k10_34.dzn
Here are the generated flatzinc files (identical except for the domain of the objective): [flatzinc.tar.gz](https://github.com/google/or-tools/files/1427191/flatzinc.tar.gz)
or-tools version: v6.5
Minizinc version: 2.1.6

Thanks!

**Comment by lperron** [comment]
I just checked and the bug is fixed.

Closing the issue.
