### ISSUE TITLE
problem with "binary installation with support for Python" on Ubuntu 16.04

### ISSUE THREAD

**Issue by alexandercyrus** [google/or-tools#519]
after following the instructions for installing "binary installation with support for Python" on a Ubuntu 16.04 machine, and running  "make install"  command, i get the following error after:

python3.5  setup.py install --user
running install
running bdist_egg
running egg_info
writing top-level names to ortools_examples.egg-info/top_level.txt
writing ortools_examples.egg-info/PKG-INFO
writing dependency_links to ortools_examples.egg-info/dependency_links.txt
writing requirements to ortools_examples.egg-info/requires.txt
reading manifest file 'ortools_examples.egg-info/SOURCES.txt'
writing manifest file 'ortools_examples.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/ortools_examples-6.4.4495-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ortools_examples-6.4.4495-py3.5.egg
Removing /home/se612/.local/lib/python3.5/site-packages/ortools_examples-6.4.4495-py3.5.egg
Copying ortools_examples-6.4.4495-py3.5.egg to /home/se612/.local/lib/python3.5/site-packages
ortools-examples 6.4.4495 is already the active version in easy-install.pth

Installed /home/se612/.local/lib/python3.5/site-packages/ortools_examples-6.4.4495-py3.5.egg
Processing dependencies for ortools-examples==6.4.4495
Searching for py3-ortools==6.4.4495
Reading https://pypi.python.org/simple/py3-ortools/
No local packages or working download links found for py3-ortools==6.4.4495
error: Could not find suitable distribution for Requirement.parse('py3-ortools==6.4.4495')
Makefile:51: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by lperron** [comment]
We are updating the documentation

Make sure pip is installed and pip -V returns 9.0.1 (or at least 8.x)

then pip install --upgrade ortools

This should pull the 6.5 release.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-11-01 6:05 GMT+00:00 samaneskandarzadeh <notifications@github.com>:
