### ISSUE TITLE
How to print the model used? (Python)

### ISSUE THREAD

**Issue by DiegoZurita** [google/or-tools#520]
After add the vars and the constraints, how to print the model used by the solver?

**Comment by dapp1990** [comment]
Check the example in [the documentation](https://developers.google.com/optimization/routing/tsp/vehicle_routing)

**Comment by mlh621** [comment]
I'm not sure the original question was answered. I am looking for the same thing. The link in the example shows how to print the values of a final solution after solving the optimization problem. For example x_gt = 1, y_gt = 2, etc. What I would like is a simple way to efficiently print out all constraints in the model. For example x_gt + ygt >=1, sum(t, x_gt) = 1, etc. Even though we code the constraints and add them via a solver.add() command, it is still easy to miss small mistakes you make when coding them. It'd be nice to verify the constraint I add with the intended mathematical formulation. 
Thanks!

**Comment by lperron** [comment]
Which solver ?

**Comment by mlh621** [comment]
Right now I’m experimenting with the default COIN-OR Mixed Integer Programming solver

**Comment by lperron** [comment]
You can export the model as a string in the lp format

http://google.github.io/or-tools/python/ortools/linear_solver/pywraplp.html

**Comment by mlh621** [comment]
I did see that function and tried using it, but the documentation doesn’t list what type of objects and args it accepts. It just says “**args.” I tried a solver object and that didn’t work! Do you know what type of object it is looking for? Thanks!!

**Comment by mlh621** [comment]
I finally got it. Somehow the API for ExportModelAsLpFormat was not clear to me, but I found a random website with an example. The confusion was over how the solver object interacted with the function.

I found the below works and is a "pretty" way or printing the whole model!
`print(solver.ExportModelAsLpFormat(False).replace('\\', '').replace(',_', ','), sep='\n')`

**Comment by caxupin** [comment]
is there a way to print a cp_model in c++?

**Comment by lperron** [comment]
std::cout << cp_model.Build().DebugString() << std::endl;

Do not expect a super nice output. But it is readable.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
