### ISSUE TITLE
Implement XOR statement on break_intervals using Python

### ISSUE THREAD

**Issue by dapp1990** [google/or-tools#521]
I've been recently working with or-tools and now I'm playing around with break intervals for CVRP using python.

What I want to achieve is creating N number of breaks for a vehicle and place on top a XOR constraint, so one and only one of the breaks is performed.

I've create the breaks  and a list of the performed values of each break interval as follow:

```python
 for i in xrange(len(self.breaks)):
         name_break = "break_{}".format(i)
         start_min, start_max, duration_break = breaks[i]
         optional_break = True

         break_intervals.append(solver.FixedDurationIntervalVar(start_min, start_max, duration_break, optional_break, name_break))
         performed_values.add(break_intervals[i].PerformedExpr())
```

Then I use the syntactic sugar of 'solver' to add a constraint using the 'SumEquality' method and add the break intervals to the vehicle:

```python
solver.Add(solver.SumEquality(performed_values, 1))             

routing.GetDimensionOrDie("Time").SetBreakIntervalsOfVehicle(break_intervals, 0)
```
The constraint works perfectly when there is only one break in 'breaks' (which is the same as change the value of 'optional_break' to 'False'). Problem is when I add a new break in 'breaks', there is no solution. 'Assignment' is empty. 

The solution is feasible, with the first break I get an assignment and adding one _optional_  break shouldn't return a null assignment.

I've followed pretty much this [cpp tutorial](https://github.com/google/or-tools/blob/master/examples/cpp/cvrptw_with_breaks.cc#L84), except for the break interval constraints and _Minimize time variables_ statements.

Perhaps I'm missing something. Do you have any insight about the issue?

**Comment by lperron** [comment]
So, the semantics of xor is not his.

Xor is equivalent to the sum is odd.

And the code has changed a lot since 7.0

Closing the issue.
