### ISSUE TITLE
Python:Read MPS for MIP

### ISSUE THREAD

**Issue by hpswalters** [google/or-tools#523]
Is there a method exposed in python to read a .mps file

**Comment by lperron** [comment]
We do. It is a bit convoluted :-)

See examples/cpp/solve.cc

**Comment by tramelon** [comment]
I actually think this is a good feature to have. Gurobi, CPLEX, FICO all have this feature built-in, even SAS/OR has it. This feature comes extremely handy when evaluating the solver capabilities.

**Comment by lperron** [comment]
As discussed on this thread, I belive the main feature is to run a solver
on it. This is done by the examples/cpp/solve.cc exe.

Now, importing a model in a python interpreter does not give you a handle
on the object. so you cannot inspect the model, can inspect the solution.

Do you need it for something else?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Yes, but the solve() binary can read MPS and LP files.

So what is the workflow?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by snkas** [comment]
To be clear, is this what you mean with "solve() binary"?:

(1) Download binary (https://developers.google.com/optimization/install/) & extract it somewhere
(2) Go to directory where it was extracted
(3) Run `make build SOURCE=examples/cpp/solve.cc` which generates it as `bin/solve`
(4) Open the Python file where you initially wanted to solve a .mps file, and add:
```python
import subprocess
result = subprocess.run(
        [
            "/path/to/bin/solve",  # Might have to be sure to run with working directory as or-tools to make sure the dynamic libraries are linked, but just to simplify
            "--input",
            lp_mps_filename,
            "--output_csv",
            csv_filename
        ],
        stdout=subprocess.PIPE
    )
# ... now parse the csv file etc. etc.
```

I'm not saying the above pipeline does not work, but isn't it more convenient to just do:

(1) `pip install ortools`
(2) Add to the code:
```python
import ortools
solution = ortools.linear_solver.pywraplp.solve(lp_mps_filename)  # Something in this trend
```

Which also avoids the need to do all the "solve() binary" steps on each platform on which the Python project is deployed.

I can't seem to find the ability to import an LP formatted file.. I do see the ability to export [1], which states to adhere to the lpsolve 5.1 LP format [2].

[1] https://developers.google.com/optimization/reference/lp_data/lp_data/LinearProgram/
[2] http://lpsolve.sourceforge.net/5.1/lp-format.htm

**Comment by lperron** [comment]
Ok, I see.

Fair point, won't be in 7.0, but I will look at it.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by snkas** [comment]
Happy to see it got some traction, I really appreciate the interaction -- I think it's great that there is a one-line import for an LP solver in Python! :+1: I couldn't unfortunately find which function in the v7.4 release enables the import of LP or MPS file?
http://google.github.io/or-tools/python/ortools/linear_solver/pywraplp.html

I've in the meanwhile a small Python module to do the .lp file parsing -- it's not perfect nor production quality but performed reasonably well so far for my use cases. If you have any feedback, that'd be greatly appreciated!
https://github.com/snkas/python-ortools-lp-parser

**Comment by nandi6uc** [comment]
I would like this function as well. Most of what we do is to build models in python but sometimes we may have a LP file using Cplex or Gurobi code that we need to just solve and get a solution to compare.

**Comment by dxyzxi** [comment]
Any update on this thread? I cannot find any function related to the problem in the API documentation.

**Comment by Mizux** [comment]
FYI
reader is here:
https://github.com/google/or-tools/blob/stable/ortools/lp_data/mps_reader.h

it is integrated in the model_builder_helper
https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/ortools/model_builder/wrappers/model_builder_helper.cc#L23

So I expect lperron to add it the the model_builder (kind of replacement of pywraplp/MPSolver on the model of the cp-sat python wrapper)
https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/ortools/model_builder/python/model_builder_helper.py#L73-L80

**Comment by lperron** [comment]
Hopefully, 9.4, but I am not sure.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by lesshaste** [comment]
I am a little confused by this thread. Is there currently no python way to import an mps file?

**Comment by dawiepoolman** [comment]
Hi guys
This looks exactly like the functionality I have been searching for.
Can we please get an example on how an .mps file can be called with this Python functionality?

**Comment by w601sxs** [comment]
After trying and failing for 2 hrs, here's what I have for others on the list. On the latest pip install for ortools as of writing this comment:

```
from ortools.linear_solver.python.pywrap_model_builder_helper import ModelBuilderHelper as mbh
```

works. Great, now when I try:

```
mbh.import_from_mps_file(mps_file="sample.mps")
```

it fails with:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_13996/2455268783.py in <cell line: 1>()
----> 1 mbh.import_from_mps_file(mps_file="sample.mps")

TypeError: import_from_mps_file(): incompatible function arguments. The following argument types are supported:
    1. (self: ortools.linear_solver.python.pywrap_model_builder_helper.ModelBuilderHelper, mps_file: str) -> bool

Invoked with: kwargs: mps_file='sample.mps' 
```

`sample.mps` is a valid mps file and is in the right directory, and as far as I can tell, I am expected to pass in a string with the filename/path

Also tried:

```
with open('sample.mps') as f:
    mps_string = f.read()

model_string = mbh.import_from_mps_string(mps_string)
```

which gives the same error pretty much. Really need guidance from the ortools team on a fully working example here.

**Comment by lperron** [comment]
Tested in
https://github.com/google/or-tools/blob/main/ortools/linear_solver/python/model_builder_test.py

**Comment by dawiepoolman** [comment]
I managed to write this small sample script to solve the sample \or-tools\ortools\linear_solver\python\maximization.mps file:

```
import os
from ortools.linear_solver.python import model_builder

class SolveMe():
    path = os.path.dirname(__file__)
    mps_path = f'{path}/maximization.mps'
    model = model_builder.ModelBuilder()
    model.import_from_mps_file(mps_path)
    solver = model_builder.ModelSolver('SCIP')
    solver.solve(model)
    
    print(model.name)
    print(solver.objective_value)
    # for variable in model.variables:
    #     print(f'{variable.name} = {solver.solution_value(variable)}')   
    print("End")  
      
def main():
    print("Start")
    SolveMe
```
 I need help with the the piece that is commented out that is supposed to print the decision variable names and values please.
 If we can get such a comprehensive example on how to interact with the model_builder library it will be a great contribution for non-coders like myself since there is no documentation yet.

**Comment by lperron** [comment]
you need to use:

def var_from_index(self, index):
"""Rebuilds a variable object from the model and its index."""
return Variable(self.__helper, index, None, None, None)

@property
def num_variables(self):
"""Returns the number of variables in the model."""
return self.__helper.num_variables()
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mer. 15 févr. 2023 à 23:46, CypherShrugged ***@***.***> a
écrit :

**Comment by dawiepoolman** [comment]
That is what I am looking at but would you mind giving an example on how to call the method e.g. I cannot seem to get the variable value:

```
import os
from ortools.linear_solver.python import model_builder

def SolveMe():
    
    path = os.path.dirname(__file__)
    mps_path = f'{path}/maximization.mps'
    
    model = model_builder.ModelBuilder()
    model.import_from_mps_file(mps_path)
    
    solver = model_builder.ModelSolver('SCIP')
    solver.solve(model)

    print(model.name)
    print(solver.objective_value)
    print(model.num_variables)
    
    # Print variables
    variables = [model.var_from_index(i) for i in range(model.num_variables)]
    for variable in variables:
        print("variable.index: ",variable.index)
        print("variable.name: ",variable.name)
        # variable value?
    
    print("End")
    
if __name__ == "__main__":
    print("Start")
    SolveMe()
```

**Comment by lperron** [comment]
The API is on the solver.

Should be solver.value(variable).

Le jeu. 16 févr. 2023, 10:28, CypherShrugged ***@***.***> a
écrit :

**Comment by dawiepoolman** [comment]
Now that is what we are talking about!
Full sample script:

```
import os
from ortools.linear_solver.python import model_builder

def SolveMe():
    
    path = os.path.dirname(__file__)
    mps_path = f'{path}/maximization.mps'
    
    model = model_builder.ModelBuilder()
    model.import_from_mps_file(mps_path)
    
    solver = model_builder.ModelSolver('SCIP')
    solver.solve(model)

    print("model.name: ",model.name)
    print("solver.objective_value: ", solver.objective_value)
    print("model.num_variables: ", model.num_variables)
    
    variables = [model.var_from_index(i) for i in range(model.num_variables)]
    for variable in variables:
        print("variable.index: ",variable.index)
        print("variable.name: ",variable.name)
        print("variable value: ",solver.value(variable))
    
    print("End")
    
if __name__ == "__main__":
    print("Start")
    SolveMe()
```

**Comment by yp757078635** [comment]
Hello, may I ask model_builder. Does ModelSolver ('SCIP') currently only support SCIP, I tried using CBC, GLOP, none of which are supported

**Comment by lperron** [comment]
It supports Scip, glop, pdlp, gurobi and cp-sat.

**Comment by lperron** [comment]
And please do not do necro-posting.
