### ISSUE TITLE
ScheduleOrPostopone in Python, type error

### ISSUE THREAD

**Issue by valrem93** [google/or-tools#524]
Hi everyone,

I'm trying to use the function ScheduleOrPostpone with Python 3.6 , in my case the invoked function is : ScheduleOrPostpone(var,est,support[i]) where var is an IntervalVar, est is an Int, support is a Dictionary and i is an index.

The error is: TypeError: in method 'Solver_ScheduleOrPostpone', argument 4 of type 'int64 *const'

Then after this error, I saw default arguments types of this function which are IntervalVar* const var, int64 est, int64* const.

Now what I am asking about is, how do i create an int64 *const in python and let my invoked function works without errors? I tried to use the ctypes python library and made a pointer through the byref function  "byref(c_longlong(markers__[i]))" and then pass this to ScheduleOrPostpone but the error still occurs.

Thanks
Valerio

**Comment by lperron** [comment]
This function is not meant to be used directly as the support is passed by
the decision builder in C++.

If you are interested in scheduling and python, I would suggest you look at
our CP/SAT solver.
There are a few scheduling examples:

examples/python/gate_scheduling_sat.py
examples/python/jobshop_ft06_sat.py
examples/python/rcpsp_sat.py

The API is simpler, and the performance would be much better IMO.

The full modeling API is in ortools/sat/python/cp_model.py

--Laurent


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-11-07 10:32 GMT+01:00 valrem93 <notifications@github.com>:
