### ISSUE TITLE
FixedDurationIntervalVar.StartsBeforeEndWithDelay

### ISSUE THREAD

**Issue by bendichter** [google/or-tools#525]
I need `FixedDurationIntervalVar.StartsBeforeEndWithDelay`, but it looks like this isn't offered by the api. Is there a way to building this with existing parts? In English, the problem I am trying to solve is "A vehicle must not wait more than xx hours between breaks."

Thanks for the help!

**Comment by lperron** [comment]
There is :

EndsAfterStartWithDelay,

just use the negation of the delay IMO.
