### ISSUE TITLE
installation problem with docker on ubuntu 16.04, got cp: cannot stat `ortools/gen/ortools/util/*.py': No such file or directory Error 1

### ISSUE THREAD

**Issue by thomasmurayama** [google/or-tools#527]
Hi, 

I got this error, when I tried to install or-tools with docker. 

Any help would be appreciated

**_Error:_**
> cp: cannot stat `ortools/gen/ortools/util/*.py': No such file or directory
> make: *** [temp-python2.7] Error 1
> Makefile:130: recipe for target 'manylinux1-pypi' failed
> make: *** [manylinux1-pypi] Error 2

**_Detailed Explanation:_**
I literally started from scratch on an Ubuntu 16.04.02

First installed Docker

1. `sudo apt-get update`
2. `sudo apt-get install  apt-transport-https ca-certificates curl software-properties-common`
3. `curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -`
4. `sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
 $(lsb_release -cs) stable"`
6.    `sudo apt-get update`
7.    `sudo apt-get install docker-ce`
8.    `sudo docker run hello-world`
Docker ran successfully 

9. `sudo usermod -aG docker $USER` where `$USER` is my linux user 

10. restarted the machine

Then, got or-tools:

11. `git clone https://github.com/google/or-tools.git` 

12. `cd or-tools/tools/docker`
13. `make python`

It ran and ran, I observed that towards the end some models were tested

It seems it solved ---- Integer programming example with CBC (C++ style API) -----

Then, last terminal output is:

> cp dependencies/install/bin/protoc dependencies/sources/protobuf-3.4.1/src
> cd dependencies/sources/protobuf-3.4.1/python && /root/build/cp27-cp27m/bin/python2.7 setup.py build
> running build
> running build_py
> rm -rf temp-python2.7
> mkdir temp-python2.7
> mkdir temp-python2.7/ortools
> mkdir temp-python2.7/ortools/ortools
> mkdir temp-python2.7/ortools/ortools/constraint_solver
> mkdir temp-python2.7/ortools/ortools/linear_solver
> mkdir temp-python2.7/ortools/ortools/sat
> mkdir temp-python2.7/ortools/ortools/graph
> mkdir temp-python2.7/ortools/ortools/algorithms
> mkdir temp-python2.7/ortools/ortools/util
> mkdir temp-python2.7/ortools/dummy
> cp ortools/gen/ortools/constraint_solver/*.py temp-python2.7/ortools/ortools/constraint_solver
> cp ortools/linear_solver/*.py temp-python2.7/ortools/ortools/linear_solver
> cp ortools/gen/ortools/linear_solver/*.py temp-python2.7/ortools/ortools/linear_solver
> cp ortools/sat/*.py temp-python2.7/ortools/ortools/sat
> cp ortools/gen/ortools/sat/*.py temp-python2.7/ortools/ortools/sat
> cp ortools/gen/ortools/graph/pywrapgraph.py temp-python2.7/ortools/ortools/graph
> cp ortools/gen/ortools/algorithms/pywrapknapsack_solver.py temp-python2.7/ortools/ortools/algorithms
> cp ortools/gen/ortools/util/*.py temp-python2.7/ortools/ortools/util
> cp: cannot stat `ortools/gen/ortools/util/*.py': No such file or directory
> make: *** [temp-python2.7] Error 1
> Makefile:130: recipe for target 'manylinux1-pypi' failed
> make: *** [manylinux1-pypi] Error 2
>

**Comment by lperron** [comment]
It should be fixed.
Please update the sources.

Thanks for the report.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-11-14 10:49 GMT+01:00 thomasmurayama <notifications@github.com>:

**Comment by thomasmurayama** [comment]
Thanks, 

I got this error now: 

> error: package directory 'ortools/util' does not exist
> Makefile:130: recipe for target 'manylinux1-pypi' failed
> make: *** [manylinux1-pypi] Error 1

after doing the following to update : 

`cd or-tools`
`git pull origin master`
updated the soruces

`cd /tools/docker`
`make python`

detailed terminal output:

> cp dependencies/install/bin/protoc dependencies/sources/protobuf-3.4.1/src
> cd dependencies/sources/protobuf-3.4.1/python && /root/build/cp27-cp27m/bin/python2.7 setup.py build
> running build
> running build_py
> rm -rf temp-python2.7
> mkdir temp-python2.7
> mkdir temp-python2.7/ortools
> mkdir temp-python2.7/ortools/ortools
> mkdir temp-python2.7/ortools/ortools/constraint_solver
> mkdir temp-python2.7/ortools/ortools/linear_solver
> mkdir temp-python2.7/ortools/ortools/sat
> mkdir temp-python2.7/ortools/ortools/graph
> mkdir temp-python2.7/ortools/ortools/algorithms
> mkdir temp-python2.7/ortools/ortools/data
> mkdir temp-python2.7/ortools/dummy
> cp ortools/gen/ortools/constraint_solver/*.py temp-python2.7/ortools/ortools/constraint_solver
> cp ortools/linear_solver/*.py temp-python2.7/ortools/ortools/linear_solver
> cp ortools/gen/ortools/linear_solver/*.py temp-python2.7/ortools/ortools/linear_solver
> cp ortools/sat/*.py temp-python2.7/ortools/ortools/sat
> cp ortools/gen/ortools/sat/*.py temp-python2.7/ortools/ortools/sat
> cp ortools/gen/ortools/graph/pywrapgraph.py temp-python2.7/ortools/ortools/graph
> cp ortools/gen/ortools/algorithms/pywrapknapsack_solver.py temp-python2.7/ortools/ortools/algorithms
> cp ortools/gen/ortools/data/*.py temp-python2.7/ortools/ortools/data
> cp ortools/gen/ortools/__init__.py temp-python2.7/ortools/ortools/__init__.py
> echo "__version__ = \"6.6.4596\"" >> temp-python2.7/ortools/ortools/__init__.py
> sed -i -e 's/VVVV/6.6.4596/' temp-python2.7/ortools/ortools/__init__.py
> touch temp-python2.7/ortools/ortools/constraint_solver/__init__.py
> touch temp-python2.7/ortools/ortools/linear_solver/__init__.py
> touch temp-python2.7/ortools/ortools/sat/__init__.py
> touch temp-python2.7/ortools/ortools/graph/__init__.py
> touch temp-python2.7/ortools/ortools/algorithms/__init__.py
> touch temp-python2.7/ortools/ortools/data/__init__.py
> cp tools/dummy_ortools_dependency.cc temp-python2.7/ortools/dummy
> cp tools/README.pypi temp-python2.7/ortools/README.txt
> cp LICENSE-2.0.txt temp-python2.7/ortools
> cp tools/setup.py temp-python2.7/ortools
> sed -i -e 's/ORTOOLS_PYTHON_VERSION/ortools/' temp-python2.7/ortools/setup.py
> sed -i -e 's/VVVV/6.6.4596/' temp-python2.7/ortools/setup.py
> sed -i -e 's/PROTOBUF_TAG/3.4.1/' temp-python2.7/ortools/setup.py
> cp lib/_pywrapcp.so temp-python2.7/ortools/ortools/constraint_solver
> cp lib/_pywraplp.so temp-python2.7/ortools/ortools/linear_solver
> cp lib/_pywrapsat.so temp-python2.7/ortools/ortools/sat
> cp lib/_pywrapgraph.so temp-python2.7/ortools/ortools/graph
> cp lib/_pywrapknapsack_solver.so temp-python2.7/ortools/ortools/algorithms
> cp lib/_pywraprcpsp.so temp-python2.7/ortools/ortools/data
> sed -i -e 's/\.dll/\.so/' temp-python2.7/ortools/setup.py
> sed -i -e 's/DELETEWIN //g' temp-python2.7/ortools/setup.py
> sed -i -e '/DELETEUNIX/d' temp-python2.7/ortools/setup.py
> sed -i -e 's/DLL/so/g' temp-python2.7/ortools/setup.py
> running bdist_wheel
> running build
> running build_py
> creating build
> creating build/lib.linux-x86_64-2.7
> creating build/lib.linux-x86_64-2.7/ortools
> copying ortools/__init__.py -> build/lib.linux-x86_64-2.7/ortools
> creating build/lib.linux-x86_64-2.7/ortools/algorithms
> copying ortools/algorithms/pywrapknapsack_solver.py -> build/lib.linux-x86_64-2.7/ortools/algorithms
> copying ortools/algorithms/__init__.py -> build/lib.linux-x86_64-2.7/ortools/algorithms
> creating build/lib.linux-x86_64-2.7/ortools/constraint_solver
> copying ortools/constraint_solver/pywrapcp.py -> build/lib.linux-x86_64-2.7/ortools/constraint_solver
> copying ortools/constraint_solver/solver_parameters_pb2.py -> build/lib.linux-x86_64-2.7/ortools/constraint_solver
> copying ortools/constraint_solver/routing_enums_pb2.py -> build/lib.linux-x86_64-2.7/ortools/constraint_solver
> copying ortools/constraint_solver/search_limit_pb2.py -> build/lib.linux-x86_64-2.7/ortools/constraint_solver
> copying ortools/constraint_solver/assignment_pb2.py -> build/lib.linux-x86_64-2.7/ortools/constraint_solver
> copying ortools/constraint_solver/routing_parameters_pb2.py -> build/lib.linux-x86_64-2.7/ortools/constraint_solver
> copying ortools/constraint_solver/model_pb2.py -> build/lib.linux-x86_64-2.7/ortools/constraint_solver
> copying ortools/constraint_solver/__init__.py -> build/lib.linux-x86_64-2.7/ortools/constraint_solver
> creating build/lib.linux-x86_64-2.7/ortools/graph
> copying ortools/graph/__init__.py -> build/lib.linux-x86_64-2.7/ortools/graph
> copying ortools/graph/pywrapgraph.py -> build/lib.linux-x86_64-2.7/ortools/graph
> creating build/lib.linux-x86_64-2.7/ortools/linear_solver
> copying ortools/linear_solver/linear_solver_natural_api.py -> build/lib.linux-x86_64-2.7/ortools/linear_solver
> copying ortools/linear_solver/linear_solver_pb2.py -> build/lib.linux-x86_64-2.7/ortools/linear_solver
> copying ortools/linear_solver/__init__.py -> build/lib.linux-x86_64-2.7/ortools/linear_solver
> copying ortools/linear_solver/pywraplp.py -> build/lib.linux-x86_64-2.7/ortools/linear_solver
> creating build/lib.linux-x86_64-2.7/ortools/sat
> copying ortools/sat/pywrapsat.py -> build/lib.linux-x86_64-2.7/ortools/sat
> copying ortools/sat/__init__.py -> build/lib.linux-x86_64-2.7/ortools/sat
> copying ortools/sat/cp_model_pb2.py -> build/lib.linux-x86_64-2.7/ortools/sat
> copying ortools/sat/sat_parameters_pb2.py -> build/lib.linux-x86_64-2.7/ortools/sat
> error: package directory 'ortools/util' does not exist
> Makefile:130: recipe for target 'manylinux1-pypi' failed
> make: *** [manylinux1-pypi] Error 1

**Comment by lperron** [comment]
Thanks for testing this.
Should be fixed now.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-11-14 15:06 GMT+01:00 thomasmurayama <notifications@github.com>:

**Comment by thomasmurayama** [comment]
tried the same routine above to update, here is the current error: 

> Fixed-up wheel written to /export/ortools-6.6.4598-cp27-cp27m-manylinux1_x86_64.whl
> which: no mcs in (/root/build/cp27-cp27m/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
> rm -f ortools/gen/ortools/__init__.py
> rm -f ortools/gen/ortools/algorithms/*python_wrap*
> rm -f ortools/gen/ortools/constraint_solver/*python_wrap*
> rm -f ortools/gen/ortools/data/*python_wrap*
> rm -f ortools/gen/ortools/graph/*python_wrap*
> rm -f ortools/gen/ortools/linear_solver/*python_wrap*
> rm -f ortools/gen/ortools/sat/*python_wrap*
> rm -f ortools/gen/ortools/util/*python_wrap*
> rm -f ortools/gen/ortools/algorithms/*.py
> rm -f ortools/gen/ortools/constraint_solver/*.py
> rm -f ortools/gen/ortools/data/*.py
> rm -f ortools/gen/ortools/graph/*.py
> rm -f ortools/gen/ortools/linear_solver/*.py
> rm -f ortools/gen/ortools/sat/*.py
> rm -f ortools/gen/ortools/util/*.py
> rm -f ortools/gen/ortools/algorithms/*.pyc
> rm -f ortools/gen/ortools/constraint_solver/*.pyc
> rm -f ortools/gen/ortools/data/*.pyc
> rm -f ortools/gen/ortools/graph/*.pyc
> rm -f ortools/gen/ortools/linear_solver/*.pyc
> rm -f ortools/gen/ortools/sat/*.pyc
> rm -f ortools/gen/ortools/util/*.pyc
> rm -f ortools/gen/ortools/algorithms/_pywrap*
> rm -f ortools/gen/ortools/constraint_solver/_pywrap*
> rm -f ortools/gen/ortools/data/_pywrap*
> rm -f ortools/gen/ortools/graph/_pywrap*
> rm -f ortools/gen/ortools/linear_solver/_pywrap*
> rm -f ortools/gen/ortools/sat/_pywrap*
> rm -f ortools/gen/ortools/util/_pywrap*
> rm -f lib/_pywrap*.so
> rm -f objs/swig/*python_wrap.o
> rm -rf temp-python2.7
> New python executable in /root/build/cp27-cp27m-test/bin/python
> Installing setuptools, pip, wheel...done.
> Running virtualenv with interpreter /opt/python/cp27-cp27m/bin/python
> Requirement already up-to-date: pip in /root/build/cp27-cp27m-test/lib/python2.7/site-packages
> Requirement already up-to-date: setuptools in /root/build/cp27-cp27m-test/lib/python2.7/site-packages
> Requirement already up-to-date: wheel in /root/build/cp27-cp27m-test/lib/python2.7/site-packages
> Collecting six
>   Using cached six-1.11.0-py2.py3-none-any.whl
> Installing collected packages: six
> Successfully installed six-1.11.0
> Processing /export/ortools-6.6.4598-cp27-cp27m-manylinux1_x86_64.whl
> Requirement already satisfied: six>=1.10 in /root/build/cp27-cp27m-test/lib/python2.7/site-packages (from ortools==6.6.4598)
> Collecting protobuf>=3.4.1 (from ortools==6.6.4598)
>   Could not find a version that satisfies the requirement protobuf>=3.4.1 (from ortools==6.6.4598) (from versions: 2.0.0b0, 2.0.3, 2.3.0, 2.4.1, 2.5.0, 2.6.0, 2.6.1, 3.0.0a2, 3.0.0a3, 3.0.0b1, 3.0.0b1.post1, 3.0.0b1.post2, 3.0.0b2, 3.0.0b2.post1, 3.0.0b2.post2, 3.0.0b3, 3.0.0b4, 3.0.0, 3.1.0, 3.1.0.post1, 3.2.0rc1, 3.2.0rc1.post1, 3.2.0rc2, 3.2.0, 3.3.0, 3.4.0)
> No matching distribution found for protobuf>=3.4.1 (from ortools==6.6.4598)
> Makefile:130: recipe for target 'manylinux1-pypi' failed

**Comment by lperron** [comment]
sh*t, 3.4.1 is not yet in pypi.

I will downgrade to 3.4.0.



Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-11-14 18:19 GMT+01:00 thomasmurayama <notifications@github.com>:

**Comment by lperron** [comment]
Actually, I will bump to 3.5.0 instead, but it is not yet on pypi.

In the meantime, can you locally change manylinux1.Dockerfile to add a
command

RUN sed -i -e 's/3.4.1/3.4.0/g' makefiles/Makefile.third_party_unix.mk

after the git clone and before the make third_party?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-11-14 20:13 GMT+01:00 Laurent Perron <lperron@google.com>:

**Comment by thomasmurayama** [comment]
thanks, did that, now got this:

> error: Your local changes to the following files would be overwritten by merge:
>         makefiles/Makefile.third_party.unix.mk
> Please, commit your changes or stash them before you can merge.
> Aborting
> Updating 14564c0..456bb22
> Makefile:130: recipe for target 'manylinux1-pypi' failed
> make: *** [manylinux1-pypi] Error 1
> 

any ideas how to circumvent this?

**Comment by lperron** [comment]
I bumped protobuf to 3.5.0 :-)

Please replace 3.4.1 by 3.5.0 and regenerate the manylinux1 image by
running make manylinux1-image-no-cache and then make python

--Laurent

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-11-14 22:20 GMT+01:00 thomasmurayama <notifications@github.com>:

**Comment by thomasmurayama** [comment]
Maybe I misunderstood, I pulled the latest version, started from scratch again, I assume that when start from a scratch from a clean OS, do not have to 

>  replace 3.4.1 by 3.5.0 and regenerate the manylinux1 image by running make manylinux1-image-no-cache

If I should still replace 3.4.1 by 3.50, I don't know how

starting from scratch I got this:

> New python executable in /root/build/cp27-cp27m-test/bin/python
> Installing setuptools, pip, wheel...done.
> Running virtualenv with interpreter /opt/python/cp27-cp27m/bin/python
> Requirement already up-to-date: pip in /root/build/cp27-cp27m-test/lib/python2.7/site-packages
> Requirement already up-to-date: setuptools in /root/build/cp27-cp27m-test/lib/python2.7/site-packages
> Requirement already up-to-date: wheel in /root/build/cp27-cp27m-test/lib/python2.7/site-packages
> Collecting six
>   Using cached six-1.11.0-py2.py3-none-any.whl
> Installing collected packages: six
> Successfully installed six-1.11.0
> Processing /export/ortools-6.6.4599-cp27-cp27m-manylinux1_x86_64.whl
> Collecting protobuf>=3.5.0 (from ortools==6.6.4599)
>   Could not find a version that satisfies the requirement protobuf>=3.5.0 (from ortools==6.6.4599) (from versions: 2.0.0b0, 2.0.3, 2.3.0, 2.4.1, 2.5.0, 2.6.0, 2.6.1, 3.0.0a2, 3.0.0a3, 3.0.0b1, 3.0.0b1.post1, 3.0.0b1.post2, 3.0.0b2, 3.0.0b2.post1, 3.0.0b2.post2, 3.0.0b3, 3.0.0b4, 3.0.0, 3.1.0, 3.1.0.post1, 3.2.0rc1, 3.2.0rc1.post1, 3.2.0rc2, 3.2.0, 3.3.0, 3.4.0)
> No matching distribution found for protobuf>=3.5.0 (from ortools==6.6.4599)
> Makefile:130: recipe for target 'manylinux1-pypi' failed
> make: *** [manylinux1-pypi] Error 1
>

**Comment by lperron** [comment]
No, replace 3.5.0 by 3.4.0 :-)

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-11-15 9:01 GMT+01:00 thomasmurayama <notifications@github.com>:

**Comment by thomasmurayama** [comment]
I'm kind of lost here.

I replaced 3.5.0 by 3.4.0 at `/or-tools/makefiles/Makefile.third_party.unix.mk`
Namely, the tag there reads now `PROTOBUF_TAG = 3.4.0`

Then I did: 
`make manylinux1-image-no-cache`
then,
`make python`

but I still get:

```
Collecting protobuf>=3.5.0 (from ortools==6.6.4599)
  Could not find a version that satisfies the requirement protobuf>=3.5.0 (from ortools==6.6.4599) (from versions: 2.0.0b0, 2.0.3, 2.3.0, 2.4.1, 2.5.0, 2.6.0, 2.6.1, 3.0.0a2, 3.0.0a3, 3.0.0b1, 3.0.0b1.post1, 3.0.0b1.post2, 3.0.0b2, 3.0.0b2.post1, 3.0.0b2.post2, 3.0.0b3, 3.0.0b4, 3.0.0, 3.1.0, 3.1.0.post1, 3.2.0rc1, 3.2.0rc1.post1, 3.2.0rc2, 3.2.0, 3.3.0, 3.4.0)
No matching distribution found for protobuf>=3.5.0 (from ortools==6.6.4599)
Makefile:130: recipe for target 'manylinux1-pypi' failed
make: *** [manylinux1-pypi] Error 1
```

**Comment by lperron** [comment]
no, docker does not read your source files, it reads from github.
So you need to patch the version number inside the manylinux1.Dockerfile

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-11-15 13:05 GMT+01:00 thomasmurayama <notifications@github.com>:

**Comment by thomasmurayama** [comment]
Would the following flow be correct for starting from scratch? 

1. `git clone https://github.com/google/or-tools.git`

2. go to `or-tools/tools/docker`

3. Modify manylinux1.Dockerfile by adding,
`RUN sed -i -e 's/3.5.0/3.4.0/g' makefiles/Makefile.third_party_unix.mk`
so that, it reads:
```
RUN git clone -b "$SRC_GIT_BRANCH" --single-branch "$SRC_GIT_URL" "$SRC_ROOT"
WORKDIR "$SRC_ROOT"
RUN sed -i -e 's/3.5.0/3.4.0/g' makefiles/Makefile.third_party.unix.mk
RUN make third_party
```
4. `make python`

Is it enough? Or should I also `make manylinux1-image-no-cache` before 4. ?

Thanks...

**Comment by lperron** [comment]
if you ran docker before, even on another git clone, you need to cleanup
the image cache. I do it every time I upgrade third_party.

otherwise, it should work fine.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-11-15 15:06 GMT+01:00 thomasmurayama <notifications@github.com>:
