### ISSUE TITLE
System.AccessViolationException when accessing variable solution value

### ISSUE THREAD

**Issue by ndcomplete** [google/or-tools#528]
We've been utilizing the OR tools to solve linear optimizations in a real-time, .NET application. That is, solving linear optimizations regularly using different inputs as time progresses.

Recently we ran into an issue that we haven't seen before while running our application on a server for extended periods of time, in which seemingly random attempts to solve the optimizations were causing AccessViolationExceptions. Specifically,

```
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Google.OrTools.LinearSolver.operations_research_linear_solverPINVOKE.Variable_SolutionValue(System.Runtime.InteropServices.HandleRef)
...
```

I'm trying to find out more specifically where this is happening in the pipeline, but given the output there I believe it is a section in which we are trying to retrieve the variable solution values out of the solver after solving the optimization.

We are using a wide variety of constraints over a decent sized number of variables.

Has anyone seen this before?

**Comment by ndcomplete** [comment]
After some testing we found that what appears to have been happening is that the garbage collector was collecting some of the Variables we were using during the P/Invoke, as per [this](https://reformatcode.com/code/c/c-async-arraycopy-throwing-access-violations-intermittently).

Unfortunately, this seems to be a side effect of the way that SWIG creates its .NET wrappers and their IDisposable implementations, using HandleRefs instead of something like [SafeHandle](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.safehandle(v=vs.110).aspx)s, which 'handle' this as per the documentation:

> Platform invoke operations automatically increment the reference count of handles encapsulated by a SafeHandle and decrement them upon completion. This ensures that the handle will not be recycled or closed unexpectedly.

More information [here](https://stackoverflow.com/a/526792/1822415).

Without wanting to get into the business of creating our own SWIG typemap or compiling a new version of SWIG, .NET provides a way of keeping objects 'alive' with regard to the Garbage Collector. That is, calling [`GC.KeepAlive`](https://msdn.microsoft.com/en-us/library/system.gc.keepalive(v=vs.110).aspx) on all of the objects which we will be accessing values from via P/Invoke (in our case the Solver and our Variables) at the *end* of the optimization procedure, prevents the garbage collector from thinking that they are collectible until the end of the scope of the `KeepAlive` method without side effects (as per their documentation). 

Preliminary testing has shown this to work, though given that it was already intermittently occurring before, we'll be watching for this happening going forward.

Going forward, I think either making a request of SWIG to use `SafeHandle`s is probably the best idea (it has been discussed [before](https://github.com/swig/swig/issues/455) and is still an open issue) or changing the typemap to use `SafeHandle`s directly, is likely the best option. I may try investigating the later option myself, but because this fix ended up only adding 3 lines of code (plus a host of comments) to our code base for what seems like a full fix, it's going to be low priority for me. That said, a fix for this would be nice for an upcoming version.

**Comment by ndcomplete** [comment]
Update: It seems that it may not be the `SafeHandle` vs `HandleRef` that may be at issue, but instead that the `Solver` instance was being disposed of before the `Variable` instance. Using `GC.KeepAlive` on the solver should also solve this problem. Alternatively, utilizing the `IDisposable` pattern may also solve this problem, as it will ensure deterministic finalization of the `Solver`.

**Comment by Mizux** [comment]
"Duplicate" of #308
