### ISSUE TITLE
installation from source and SAT module

### ISSUE THREAD

**Issue by thomasmurayama** [google/or-tools#529]
Is SAT module not available with the source installation? 

```
    from ortools.sat.python import cp_model
ImportError: No module named sat.python
```

**Comment by lperron** [comment]
Do you specify PYTHONPATH?

You need it to point to the rootdir of or-tools.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-11-17 12:31 GMT+01:00 thomasmurayama <notifications@github.com>:

**Comment by thomasmurayama** [comment]
The other examples which are not SAT worked. 
But I did not specify the PYTHONPATH.

**Comment by lperron** [comment]
this is because python is reusing an installed ortools package.
Older pypi packages did not contain SAT, thus the other examples worked.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-11-17 16:38 GMT+01:00 thomasmurayama <notifications@github.com>:
