### ISSUE TITLE
Is MakeIndexOfConstraint missing in Java library?

### ISSUE THREAD

**Issue by chatrees** [google/or-tools#530]
Hello,

I would like to implement [Employee Scheduling](https://developers.google.com/optimization/scheduling/employee_scheduling) in Java but I don't see a Java method to make **IndexOf** constraint like in Python: `solver.Add(s.IndexOf(nurses_for_day) == j)`.

I expect to use something like `solver.makeIndexOf(..)` in Java.

Does Java library have a solution to make **IndexOf** constraint?

Thank you!

**Comment by lperron** [comment]
It is makeElement(index_variable, array, target_variable) on the Solver
class.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-11-17 14:34 GMT+01:00 chatrees <notifications@github.com>:

**Comment by chatrees** [comment]
Thank you @Iperron
