### ISSUE TITLE
Job shop example: how to solve problem with some same machines

### ISSUE THREAD

**Issue by roborobotheart** [google/or-tools#532]
The examples shows problem with unique machine, if all the machines can be divided in several groups. Machines in the same groups are same. Could you please give some examples like this?

**Comment by sandeepbodanapu** [comment]
I am working on the similar problem and need your help if you have already found the answer. Knapsack algorithm is what I think would solve this problem

**Comment by lperron** [comment]
Which langage? Which solver?

In c++, you have flexible_jobshop that works on the constraint_solver
backend.

In python, examples/python/rcpsp_sat.py works on the new sat backend.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-11-24 7:06 GMT+01:00 sandeepbodanapu <notifications@github.com>:

**Comment by ketan4373** [comment]
Can you please tell me the input file structure, I mean how is the data being fed.

**Comment by lperron** [comment]
See ortools/data/rcpsp.proto, there is a list of format it understands.

Please note that the rcpsp was given as an example, I did not meant for you to use it.
In C++, there is examples/cpp/jobshop_sat.cc which can parse ortools/data/jobshop_scheduling.proto.

RCPSP is about cumulative constraints (see PSPLib).
Jobshop scheduling is about disjunctive constraints.

I hope this helps.

I will close the issue as it is quite old. Please reopen if needed.
