### ISSUE TITLE
How open depot time windows?

### ISSUE THREAD

**Issue by paraCRM** [google/or-tools#533]
And I have the same mistake.
I need to solve the problem with total time constraint. I know, that this is solving by time_horizon in AddDimension.
But my nodes have over day time windows, for example it open at 23:00 and close at 01:00 next day.
So I convert it to 82800 and 90000.
But total time constraint is only 12 hours, 43200.
So I want open depot from 0 to 259200 (not to 43200, thats how AddDimension works) and add 1 day to all customers, so that this customer will be 169200 and 176400.
In this case i understand, that dimension of time_horizon have to be equal as max dimension of time windows.
For example, if my max time windows dimension (on customers, not on depot) will be = 176400 (6 characters) time_horizon 43200 (5 characters) will raise an error

Traceback (most recent call last):
  File "D:/Work/VRPTW/VRPTW3/cvrptw.py", line 342, in <module>
    main()
  File "D:/Work/VRPTW/VRPTW3/cvrptw.py", line 235, in main
    time_dimension.CumulVar(locations).SetRange(start, end)
  File "C:\Users\MDesh\.virtualenvs\VRPTW3-rmdLUytm\lib\site-packages\ortools\constraint_solver\pywrapcp.py", line 1339, in SetRange
    return _pywrapcp.IntExpr_SetRange(self, l, u)
Exception: CP Solver fail

But if time_horizon will be , for example, 143200 (6 characters) - everything will be ok.
So that there are two ways:
1. Probably, repair this error - i have already ask about it here https://github.com/google/or-tools/issues/162
2. Open the depot for my task.
So this issue is about way №2, may be, another way to solve my problem. 
Will be grateful for any help.
Thanks.

**Comment by tatadyj** [comment]
Hi Guys, I have the same problem and issues when I implemented my model.
Please check If you set fix_start_cumul_to_zero == false, whether the problem will be solved.
We need to set this value to FALSE, if we do not want to cumulate from zero, which is the lower bound.
