### ISSUE TITLE
Python install from source

### ISSUE THREAD

**Issue by kilcoole** [google/or-tools#534]
Having issues with the SAT solver after installing from source:

`from ortools.sat.python import cp_model` 

gives the following error

`from ortools.sat import cp_model_pb2
ImportError: cannot import name 'cp_model_pb2'`

**Comment by lperron** [comment]
I do not know, we have been compiling or-tools continuously for the last
week and many different setups and platforms, and we did not see that
problem.

Which platform?
What is the command line to run the example?

Are you adding a PYTHONPATH? are you using make rpy?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-11-28 10:28 GMT+01:00 ciarán <notifications@github.com>:

**Comment by kilcoole** [comment]
Hi,

it is on mac os x 10.12.6.

I follwed the exact guide [here](https://developers.google.com/optimization/introduction/installing/source) using make python. 

It is in the python terminal session when I try to do the import, even when adding directory to PYTHONPATH

**Comment by kilcoole** [comment]
My bad... seems like there was an issue with my SWIG installation. Fixed that and it's all good now, thanks!
