### ISSUE TITLE
Minizinc global constraints "not supported" in the CentOS release

### ISSUE THREAD

**Issue by skosch** [google/or-tools#536]
Try running, for example, `bobs_sale.fzn` with the CentOS `fzn-or-tools` binary. I get
```
 Not supported global_cardinality_low_up_closed 
*** Check failure stack trace: ***
    @     0x7f4cfc819f92  google::LogMessage::Fail()                              
    @     0x7f4cfc819eee  google::LogMessage::SendToLog()                         
    @     0x7f4cfc819872  google::LogMessage::Flush()                             
    @     0x7f4cfc81c919  google::LogMessageFatal::~LogMessageFatal()             
    @     0x7f4cfcd3e2b6  operations_research::sat::(anonymous namespace)::CpModelP
rotoWithMapping::FillConstraint()
    @     0x7f4cfcd413fc  operations_research::sat::SolveFzWithCpModelProto()     
    @           0x402e63  main
    @     0x7f4cfa818c05  __libc_start_main                                       
    @           0x402f57  (unknown)
    @              (nil)  (unknown)
```
The same seems to work fine for me on Ubuntu.

**Comment by Mizux** [comment]
Hi skosch,

I generated the CentOS binaries using docker with the latest CentOS:7 image (yesterday).
-> Could you run `ldd fzn-or-tools` to check if all dependencies are found ?

Also try to update your distro if possible...

**Comment by lperron** [comment]
bobs was created for the CP solver, not the sat solver.

You can run it will fz --use_cp_sat=false.

Unfortunately, I cannot find the original mzn file to generate it for sat.




Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-12-01 11:06 GMT+01:00 Mizux <notifications@github.com>:

**Comment by skosch** [comment]
Merci beaucoup, à vous deux!

First off, apologies for a mistake in my original post (I'll edit it) – it turns out I wasn't running the latest release on Ubuntu even though I thought I was. This is an issue with the latest release, not with the platform at all.

`--use_cp_sat=false` works. I missed the change in default from CP to SAT solver (06dcefa). I'm surprised I'm the only one for whom suddenly everything stopped working without explanation; maybe an error message beyond "not supported" would be helpful.

**Comment by lperron** [comment]
The constraint is supported in minizinc.

But minizinc expands each mzn file into a solver specific fzn file.
Most of the files in examples/flatzinc are CP specific. So they may not
work directly with SAT.
But they should always work if we go back to the original mzn file.



Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-12-01 15:50 GMT+01:00 Sebastian Kosch <notifications@github.com>:
