### ISSUE TITLE
How do i use or-tool linear solver for android

### ISSUE THREAD

**Issue by prabinshrestha** [google/or-tools#537]
I am trying to use linear solver and i have added the com.google.ortools.jar on my lib folder inside my android application project .

I have given the source code and exception.Could you look at it or give me some fine way or some suggestion to do it.

Here is my code :

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        MPSolver solver = createSolver("GLOP_LINEAR_PROGRAMMING");
        if (solver == null) {
            Log.v("test", "Could not create solver " + "GLOP_LINEAR_PROGRAMMING");
            return;
        }

        double infinity = MPSolver.infinity();
        // x and y are continuous non-negative variables.
        MPVariable x = solver.makeNumVar(0.0, infinity, "x");
        MPVariable y = solver.makeNumVar(0.0, infinity, "y");

        // x + 2y <= 14.
        MPConstraint c0 = solver.makeConstraint(-infinity, 14.0);
        c0.setCoefficient(x, 1);
        c0.setCoefficient(y, 2);

        // 3x - y >= 0.
        MPConstraint c1 = solver.makeConstraint(0.0, infinity);
        c1.setCoefficient(x, 3);
        c1.setCoefficient(y, -1);

        // x - y <= 2.
        MPConstraint c2 = solver.makeConstraint(-infinity, 2.0);
        c2.setCoefficient(x, 1);
        c2.setCoefficient(y, -1);

        Log.v("test", "Number of variables = " + solver.numVariables());
        Log.v("test", "Number of constraints = " + solver.numConstraints());
        solver.solve();

        // The value of each variable in the solution.
        Log.v("test", "Solution");
        Log.v("test", "x = " + x.solutionValue());
        Log.v("test", "y = " + y.solutionValue());

        // The objective value of the solution.
        Log.v("test", "Optimal objective value = " + solver.objective().value());

    }

    private static MPSolver createSolver(String solverType) {
        try {
            return new MPSolver("LinearProgrammingExample",
                    MPSolver.OptimizationProblemType.valueOf(solverType));
        } catch (Exception e) {
            Log.v("test",e.getMessage());
            return null;
        }
    }

}

 java.lang.UnsatisfiedLinkError: No implementation found for int com.google.ortools.linearsolver.operations_research_linear_solverJNI.MPSolver_CLP_LINEAR_PROGRAMMING_get() (tried 

Java_com_google_ortools_linearsolver_operations_1research_1linear_1solverJNI_MPSolver_1CLP_1LINEAR_1PROGRAMMING_1get and Java_com_google_ortools_linearsolver_operations_1research_1linear_1solverJNI_MPSolver_1CLP_1LINEAR_1PROGRAMMING_1get__)
                                                                              at com.google.ortools.linearsolver.operations_research_linear_solverJNI.MPSolver_CLP_LINEAR_PROGRAMMING_get(Native Method)
                                                                              at com.google.ortools.linearsolver.MPSolver$OptimizationProblemType.<clinit>(MPSolver.java:221)

**Comment by lperron** [comment]
The jar needs a native library that is not compiled for android.
It is possible, but I do not know the public toolchain for that.

So bottom line, you need to recompile from source with either cross
compilation, or a native toolchain (if it exists).

--Laurent

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-12-05 7:31 GMT+01:00 prabinshrestha <notifications@github.com>:

**Comment by prabinshrestha** [comment]
After a lot of research some developer has these recommendation :
*     static {
        System.loadLibrary("jniortools");
    }
* add jniLibs folder on main folder of android application they say to add these folder called armabi,armabi-v7a,x86 and inside these folder we have to add the *.so library

The *.so library i have put here inside each folder is as follows :
1. libcvrptw_lib.so
2. libdimacs.so
3. libfap.so
4. libjniortools.so
5. libortools.so

******************************** the code *********************************

public class MainActivity extends AppCompatActivity {

 static {
        System.loadLibrary("jniortools");
    }


@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    MPSolver solver = createSolver("GLOP_LINEAR_PROGRAMMING");
    if (solver == null) {
        Log.v("test", "Could not create solver " + "GLOP_LINEAR_PROGRAMMING");
        return;
    }

    double infinity = MPSolver.infinity();
    // x and y are continuous non-negative variables.
    MPVariable x = solver.makeNumVar(0.0, infinity, "x");
    MPVariable y = solver.makeNumVar(0.0, infinity, "y");

    // x + 2y <= 14.
    MPConstraint c0 = solver.makeConstraint(-infinity, 14.0);
    c0.setCoefficient(x, 1);
    c0.setCoefficient(y, 2);

    // 3x - y >= 0.
    MPConstraint c1 = solver.makeConstraint(0.0, infinity);
    c1.setCoefficient(x, 3);
    c1.setCoefficient(y, -1);

    // x - y <= 2.
    MPConstraint c2 = solver.makeConstraint(-infinity, 2.0);
    c2.setCoefficient(x, 1);
    c2.setCoefficient(y, -1);


    Log.v("test", "Number of variables = " + solver.numVariables());
    Log.v("test", "Number of constraints = " + solver.numConstraints());
    solver.solve();

    // The value of each variable in the solution.
    Log.v("test", "Solution");
    Log.v("test", "x = " + x.solutionValue());
    Log.v("test", "y = " + y.solutionValue());

    // The objective value of the solution.
    Log.v("test", "Optimal objective value = " + solver.objective().value());

}

private static MPSolver createSolver(String solverType) {
    try {
        return new MPSolver("LinearProgrammingExample",
                MPSolver.OptimizationProblemType.valueOf(solverType));
    } catch (Exception e) {
        Log.v("test",e.getMessage());
        return null;
    }
}

}


* I think everything is on the right track but it still throw this error because of compatibilty issue with 32 bit as follows 

   java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.company.heifersolver-1/lib/arm/libjniortools.so" is 64-bit instead of 32-bit
                                                                              at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                              at java.lang.System.loadLibrary(System.java:1076)


* And i have checked that this distribution is 64bit so it gives this error, where do i find 32 bit one then?

I would feel very grateful if you guys resolve this issue and make the life of android developer life easy.
Hoping to get good answer and reply soon, may be with some example and doucmentation ;)

**Comment by Mizux** [comment]
Just for info I'm working (i.e. WIP) on CMake for ortools and since android provide CMake toolchain....

Look at mizux/cmake branch...

**Comment by prabinshrestha** [comment]
:Mizux

Thank you so much.Looking forward to see good changes.

**Comment by prabinshrestha** [comment]
Also one more thing, in excel when we use solver and it gives following output
* best case scenario (found feasible solution and meet all constraints)
- it gives the optimal solution value

* worst case scenario(no feasible solution found)
- but it still gives the output (not a optimal solution) but it helps user to check his data and verify with its constraint.

Therefore like the second case 
* Does Glop gives  such solution ?
* If yes what is the api available ?
* If no please consider this as well .

Thanks

**Comment by lperron** [comment]
Short answer, you need to write a full stack on android. This is not on our plans for now.

**Comment by ChenhuaWANG22** [comment]
@lperron 

Could you please confirm if using C++ source then add it to android can be a valid solution ?

below is the document for how to add C and C++ code to android project.
https://developer.android.com/studio/projects/add-native-code

**Comment by lperron** [comment]
Theoretically, you can.
In practice, the makefiles do not support cross compilation, si it will be
a complex process.

**Comment by ChenhuaWANG22** [comment]
@lperron
As I only want to use glop linear solver, if I only copy and compile source file used by this solver, do you think it can be feasible ? Or I better search for something else?

**Comment by lperron** [comment]
You need a few dependencies (glog, gflags, absl, protobuf). You can ignore
coin cbc.
And you need to define __PORTABLE_PLATFORM__ when compiling C++ code.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
