### ISSUE TITLE
CVRP with same demand and different reward at each location

### ISSUE THREAD

**Issue by minhhai2209** [google/or-tools#538]
I have a CVRP with `capacity = n `and each location has `demand = 1`, as in [this example](https://developers.google.com/optimization/routing/tsp/vehicle_routing), but at each location, the delivery man will receive a different amount of tip (reward), and he wants to maximize his tip. The distance between two locations is either `0` or `1`. How should I model the reward requirement in Google OR-Tools?

**Comment by braktar** [comment]
You could align the disjunction penalty on your reward. A reward not received is a strict loss.

https://github.com/google/or-tools/blob/2c7a8bf8f621ea82d26c5f68af1495b6eabb43f8/ortools/constraint_solver/routing.h#L525
