### ISSUE TITLE
how to use or-tool to solve a mutli depot open vehicle routing problem?

### ISSUE THREAD

**Issue by AlirezaH320** [google/or-tools#543]

**Comment by furnon** [comment]
Using the vehicle routing library, you can express this by specifying
vehicle start nodes corresponding to each depot. All vehicles should share
the same end node which should be a dummy node at distance/time 0 of all
other nodes (take that into account in various callbacks).

**Comment by AlirezaH320** [comment]
thank you for quick answering
i used it to solve this:
![photo_2017-12-23_03-51-05](https://user-images.githubusercontent.com/17493246/34315649-0c886132-e798-11e7-97d3-3322ca2b7c06.png)
which locations are:
`locations = [[9, 9], [11, 11], [10, 2], [10, 18], [2, 10], [18, 10], [2, 2], [18, 2], [2, 18], [18, 18],[1000, 1000]]`
and the last location is a dummy node
and here is start and end locations:
`start_locations = [0, 1]`
`end_locations = [10, 10]`
but the solver give me this:
`Route for vehicle 0:
[9, 9]
Distance of route 0: 0`
`Route for vehicle 1:
[11, 11] -> [18, 10] -> [18, 18] -> [10, 18] -> [2, 18] -> [2, 10] -> [2, 2] -> [10, 2] -> [18, 2]`
the answer dos not make any sense because the first vehicle got nothing
how to fix this?

**Comment by AlirezaH320** [comment]
@furnon  @willnorris @ambasta @glennon @supermihi
