### ISSUE TITLE
or-tools LCG is going to be released soon?

### ISSUE THREAD

**Issue by hooman650** [google/or-tools#545]
Hi!

I was very excited when I saw in Minizinc Challenge that Or-Tools is now using Lazy Clause Generation technique and based on the results the performance looks very promising! I was wondering if or-tools-LCG has been released or going to be released soon?

Thanks 
Hooman

**Comment by lperron** [comment]
I has been released a few months ago.
The minizinc backend is available on the github release page.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-12-22 19:47 GMT+01:00 hooman650 <notifications@github.com>:

**Comment by hooman650** [comment]
Thanks for the reply. So the LCG method can be accessed with fzn-or-tools? is there a specific flag that needs to be set on?

**Comment by lperron** [comment]
This is the default.

./bin/fz --helpshort
fz: Usage: see flags.
This program parses and solve a flatzinc problem.

  Flags from ./ortools/flatzinc/fz.cc:
...
    -use_cp_sat (Use the CP/SAT solver.) type: bool default: true
...


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-12-25 17:59 GMT+01:00 hooman650 <notifications@github.com>:
