### ISSUE TITLE
how to use or-tool to solve a dynamic mutli depot open vehicle routing problem?

### ISSUE THREAD

**Issue by AlirezaH320** [google/or-tools#546]
dynamic vehicle routing problem contains an optimization model, which minimizes the total travel time spent on the network which means that the time of vehicle that spent maximum time between vehicles should be minimize

**Comment by SamNgu** [comment]
Seems like there is no support for multi-depot in the current OR-Tools version (version 7.0)

**Comment by lperron** [comment]
https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/doc/VRP.md#multiple-starts-ends
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
