### ISSUE TITLE
Python SAT Solver: ImportError: No module named _pywrapsat

### ISSUE THREAD

**Issue by teocomi** [google/or-tools#547]
When running the SAT Python examples on a Mac I get the following error, it works fine on a windows machine. Not sure if it's a misconfiguration, but I could replicate it on a couple of machines already.

Python 2.7.14
ortools-6.6.4656

  ```File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ortools/sat/python/cp_model.py", line 29, in <module>
    from ortools.sat import pywrapsat
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ortools/sat/pywrapsat.py", line 17, in <module>
    _pywrapsat = swig_import_helper()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ortools/sat/pywrapsat.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrapsat')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _pywrapsat```

**Comment by lperron** [comment]
First check that the version installed by pip is the correct one.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-12-24 15:08 GMT+01:00 Matteo Cominetti <notifications@github.com>:

**Comment by lperron** [comment]
I did replicate the problem.

I will look into it.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-12-25 16:56 GMT+01:00 Laurent Perron <lperron@google.com>:

**Comment by lperron** [comment]
I found it.
I missed a otool step in the sat libraries.

Can you build from sources? or patch the installed libraries?

To patch, you need to replicate the following script:

Find the patched ortools.dylib path

export P=`otool -L <path to installed module
package>/ortools/libortools.dylib`
install_name_tool -change $P @loader_path/../libortools.dylib <path to
installed module package>/ortools/linear_solver/_pywrapsat.so

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-12-25 16:58 GMT+01:00 Laurent Perron <lperron@google.com>:

**Comment by teocomi** [comment]
Thanks Laurent, really appreciate your reply, I can wait until the bug is fixed.

I tried running your commands but I get an error in the second one.

The command:
```install_name_tool -change $P @loader_path/../libortools.dylib /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ortools/linear_solver/_pywrapsat.so```

Gives:
```error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: more than one input file specified (version and (compatibility)
Usage: /Library/Developer/CommandLineTools/usr/bin/install_name_tool [-change old new] ... [-rpath old new] ... [-add_rpath new] ... [-delete_rpath old] ... [-id name] input```

Also, I suspect the path should be to the `sat` folder instead than `linear_solver`? In any case, as I said, I can wait for the updated package.
Thanks

**Comment by lperron** [comment]
Hi,

we will try to push an updated module this week.

Thanks for the report.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-12-25 21:07 GMT+01:00 Matteo Cominetti <notifications@github.com>:

**Comment by Mizux** [comment]
Hi,

I just uploaded for MacOS [ortools v6.6.4659](https://pypi.python.org/pypi/ortools/6.6.4659)

Please try a `pip install --user --upgrade ortools` and everything should work !
note: you can also `pip uninstall ortools; pip list | grep ortools` first to be sure...

**Comment by teocomi** [comment]
Awesome, thanks!
