### ISSUE TITLE
Python2.7: import not working (missing library files)

### ISSUE THREAD

**Issue by gunners009** [google/or-tools#551]
Hi
I am using Jupyter on win 8 Python 2.7
I have already installed ortools
Checked it in Python sitepackage folder. But when I call
```python
from ortools .graph import pywrapgraph
```
It gives me error that there is no module -pywrapgraph
But in the folder the pywrapgraph.py, .yc and .pyd files are present.

**Comment by Mizux** [comment]
Could you verify your python version using https://github.com/google/or-tools/issues/509#issuecomment-359383409

**Comment by vdvdd** [comment]
I was using python 2.7 as mentioned above.
Is there an issue with python 2.7?
Updated to 3.6 and now everything is fine.

**Comment by Mizux** [comment]
Don't know if related, but I spot a bug where the version of python executable was not the same of the python include and python library. cf c4bfef2

What is the full output of `make detect_python` and `make test_python` ?
Could you try with the last master version ?

**Comment by Mizux** [comment]
On python2.7 into "setup.py" a call to `include_package_data=True,` is mandatory, seems to be the default behaviour with Python 3...
