### ISSUE TITLE
Use ortools to build complex MIP model

### ISSUE THREAD

**Issue by cuiyouzhi0000** [google/or-tools#553]
Dears, 

Do we have interface like IloScalProd and IloSum functions to build complex constraints in ortools?

`model.add(IloMinimize(env, IloScalProd(cost, x)
                               + IloScalProd(fused, fixedCost)));`

`model.add(IloSum(x) == demand);`

I saw in ortools' python sample, we do have solver.Sum function, do we have Sum function in C++ and Java?
Thanks.

**Comment by Mizux** [comment]
Since Python and Java are binding of the C++. You should have everything on C++.
Which solver do you use ?
For Java not sure about sum everything is not yet bind in every languages (SWIG or language limitation).

**Comment by cuiyouzhi0000** [comment]
Thanks a lot!
I am using MIP solver to solve MIP problem. Below code comes from ortools' python sample diet1_mip.py, can we write like this in C++ and Java? Looks like global_arith is the thing, while it is in example, not in include header file?
Could I know if somebody used global_arith in both MIP, and CP modeling?

`solver.Add(solver.Sum([x[i] * calories[i]
                         for i in range(n)]) >= limits[0])
  solver.Add(solver.Sum([x[i] * chocolate[i]
                         for i in range(n)]) >= limits[1])
  solver.Add(solver.Sum([x[i] * sugar[i]
                         for i in range(n)]) >= limits[2])
  solver.Add(solver.Sum([x[i] * fat[i]
                         for i in range(n)]) >= limits[3])
`

**Comment by cuiyouzhi0000** [comment]
Another questions: 
1. Could we define multiple dimensions(2D, 3D, 4D, etc) decision variable array in ortools?
2. Could we use class object as index of decision variable array, and multiple dimensions array?

These features are useful to build complex MIP models.

Thanks.

**Comment by lperron** [comment]
I Python and C#, we do have these features.
In C++, we have some of it, see ortools/linear_solver/linear_expr.h

These do not propose IloSum and IloScalProd, but these are trivial to implement.
The important thing is that you can write LinearExpr == LinearExpr.
