### ISSUE TITLE
Use or-tools to build delivery system

### ISSUE THREAD

**Issue by MohamedTaher** [google/or-tools#555]
Dear's
I have a number of vehicles which get some orders to deliver and these vehicles Located in different locations in my city,
So each vehicle should go to the restaurant first before delivering orders, to load the order content

How can I do that using or-tools?

**Comment by furnon** [comment]
Hi,
There are different ways of modeling this with the routing library
depending on your actual constraints.
If the vehicles can perform several pickups before delivering, then this
can be modeled as a pickup and delivery problem; see this
<https://github.com/google/or-tools/blob/master/examples/cpp/pdptw.cc>
example.
If the vehicles can only load a single order at a time, it is more
efficient to model it as a standard vehicle routing problem where a node is
actually the trip from the pickup location to its delivery. You can look at
this <https://github.com/google/or-tools/blob/master/examples/cpp/cvrptw.cc>
example.

Vincent

**Comment by MohamedTaher** [comment]
Thanks,
