### ISSUE TITLE
Missing two .so files in tools/fix_python_libraries_on_linux.sh

### ISSUE THREAD

**Issue by chofchof** [google/or-tools#556]
After building `or-tools 6.6` successfully on Lunux platforms (CentOS 7 & openSUSE 42.3), I found a strange result.

1. First running `import ortools.sat.pywrapsat` gives me **an error** that `libortools.so` could not find.
2. But running `import ortools.linear_solver.pywraplp` and then `import ortools.sat.pywrapsat` generates **no error**.

I tried to find the reason, and found that two .so files are missing in [`tools/fix_python_libraries_on_linux.sh`](https://github.com/google/or-tools/blob/master/tools/fix_python_libraries_on_linux.sh) as follows:
```
dependencies/install/bin/patchelf --set-rpath '$ORIGIN/../../ortools' $1/ortools/ortools/data/_pywraprcpsp.so
dependencies/install/bin/patchelf --set-rpath '$ORIGIN/../../ortools' $1/ortools/ortools/sat/_pywrapsat.so
```
After adding the two lines, I could see no error.

It seems that it is quite related to the commit, [fix python problem on mac](https://github.com/google/or-tools/commit/b9ed70d18284d4b672d80b2ef5085a3a7b3cb682).

**Comment by lperron** [comment]
Indeed.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2018-01-10 15:17 GMT+01:00 Jin-Hwan CHO <notifications@github.com>:

**Comment by Mizux** [comment]
@chofchof Thanks !
