### ISSUE TITLE
KnapsackSolver crashes Jupyter notebook kernel

### ISSUE THREAD

**Issue by chofchof** [google/or-tools#560]
### System environment
- Mac OS X 10.13.2
- Anaconda 5.0.1 (Python 3.6.1)
- ortools (6.6.4659) installed by `pip install ortools`

### Test code (`knapsack_brute_force.py`)
```
from ortools.algorithms import pywrapknapsack_solver

N = 31 # set over 30 to generate a failure
profits = [1 for _ in range(N)]
weights = [list(range(N))]
capacities = [100]

solver = pywrapknapsack_solver.KnapsackSolver(
    pywrapknapsack_solver.KnapsackSolver.KNAPSACK_BRUTE_FORCE_SOLVER,
    'brute_force_test'
)
solver.Init(profits, weights, capacities)
computed_profit = solver.Solve()
print(computed_profit)
```

### Problem
- Running `python knapsack_brute_force.py` generates the following message:
```
(base) ~$ python knapsack_brute_force.py 
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0119 14:36:00.402519 3055862592 knapsack_solver.cc:588] Check failed: num_items_ <= kMaxNumberOfBruteForceItems (31 vs. 30) To use KnapsackBruteForceSolver the number of items should be less than 30. Current value: 31.
*** Check failure stack trace: ***
Abort trap: 6
```
- Notice the last line `Abort trap: 6`. It informs of the abnormal state of python.
- So if the test code above is run in Jupyter notebook (as below), it crashes the current kernel of Jupyter notebook.
```
In [1]: %run knapsack_brute_force.py
```
- Is there any way to avoid this kind of crash (especially in Jupyter notebook)?

**Comment by Mizux** [comment]
Hi,
As written, Brute Force solver can't work above 30. Unless you have to modify the source code.
A check is perform in the code (see below), I guess python didn't catch the error.

[knapsack_solver.cc:L588](https://github.com/google/or-tools/blob/master/ortools/algorithms/knapsack_solver.cc#L588)

**Comment by chofchof** [comment]
@Mizux: You are right. Python cannot catch the fatal error because the glog library just call `abort()`.

This issue is quite related to the question "[Custom InstallFailureFunction does not prevent exit](https://github.com/google/glog/issues/249)" in [google/glog](https://github.com/google/glog).

**Comment by lperron** [comment]
Nothing we can do currently. Closing the issue.
