### ISSUE TITLE
OR-Tools, Increase Resource Consumption

### ISSUE THREAD

**Issue by Migaelh** [google/or-tools#561]
This is not an issue but rather than a question. 

I am using OR-Tools (c# version) with a CVRPTW solution. 

It is a fantastic library! However, I am running the solution with 1400-2000 locations so that translates to about 1 960 000 - 4 000 000 possible distances between the locations, thus the processing time can take a while. 

Is there a way to give more resources to the application to do this processing faster? At the moment it only uses 18%-20% of my CPU usage and < 8% memory. I want to increase these usages with a lot as I have a dedicated server for this solution. 

My current specs are: 
CPU: Intel i7 7th gen, quad core 2.8ghz
Ram: 16gb DDR3
Disk: 500GB SSD

**Comment by Mizux** [comment]
Hi, which solver do you use ?

I guess some solvers are not multi-threaded which could explain the CPU usage.
Usually AFAIK free OSS solver are mono thread while commercial "could be" multi-threaded.

note: Cbc (CoinUtils) check for pthread but I don't know why...

**Comment by Migaelh** [comment]
I am using the ConstraintSolver (as this was used in the examples)

I am also using a 2d array for the distances, will a hashmap aso increase
the performance (theres about 2 000 000 elements in the 2d array)?

On 19 Jan 2018 16:27, "Mizux" <notifications@github.com> wrote:

Hi, which solver do you use ?

I guess some solvers are not multi-threaded which could explain the CPU
usage.
Usually AFAIK free OSS solver are mono thread while commercial "could be"
multi-threaded.

note: Cbc (CoinUtils) check for pthread but I don't know why...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/or-tools/issues/561#issuecomment-358980185>, or mute
the thread

**Comment by furnon** [comment]
A 2d matrix should be the fastest option. There might be some overhead due
to the distance function being in C# and the solver running in C++. The
overhead can be reduced (at the cost of memory consumption) by telling the
solver to cache distances (and any other callback for that matter). For
that specify RoutingModelParameters (built from DefaultModelParameters())
when building your RoutingModel and set  max_callback_cache_size to a value
greater than the number of nodes in the problem.

**Comment by Migaelh** [comment]
Thank you I will try it

**Comment by Migaelh** [comment]
I have tried  @furnon's feedback, it did use more memory (went up from 17mb to 1.3GB). I managed to run the solution with 1400 nodes in 16minutes.

Thanks for the help

**Comment by olushako** [comment]
@furnon @Migaelh hi! I have tried this approach for a similar problem but the app is still using ~16-20MB. Number of nodes - 3600. Could you please tell how you implemented this?

`
var nr_vehicle = nb_trucks;

            var searchParameters = RoutingModel.DefaultSearchParameters();
            var modelParameters = RoutingModel.DefaultModelParameters();

            modelParameters.MaxCallbackCacheSize = 7200;

            var routing = new RoutingModel(unit.Count, nr_vehicle, 0, modelParameters);
            NodeEvaluator2 demandCallback = new Demand();
            routing.AddDimension(demandCallback, 0, maxCapacity, true, "capacity");

            
            NodeEvaluator2 lenghtcallback = new RouteLenght();
            routing.AddDimension(lenghtcallback, 0, maxCapacity, true, "routelenght");
            var dist_dimension = routing.GetDimensionOrDie("routelenght");
            for(long i=0; i<routing.Nodes();i++)
                dist_dimension.CumulVar(i).SetMax((long)Math.Truncate(Parameters.maxLength));

            NodeEvaluator2 nodesCount = new NodesCounter();
            routing.AddDimension(nodesCount, 0, maxCapacity, true, "nodescounter");
            var nodes_dimension = routing.GetDimensionOrDie("nodescounter");
            for (long i = 0; i < routing.Nodes(); i++)
                nodes_dimension.CumulVar(i).SetMax((long)Parameters.maxNodes-1);

            var distances = new RandomManhattan();
            routing.SetCost(distances);

            searchParameters.TimeLimitMs = Parameters.maxOptSearchTime;
            
            searchParameters.FirstSolutionStrategy = FirstSolutionStrategy.Types.Value.PathCheapestArc;

            var solution = routing.SolveWithParameters(searchParameters);`
