### ISSUE TITLE
A question on implementation of "SimpleMinCostFlow()"

### ISSUE THREAD

**Issue by maestrojeong** [google/or-tools#562]
I'm using "pywrapgraph.SimpleMinCostFlow()".

As I understand, it only takes integer cost, and capacity. Also, the optimal solution by solved with this function only has integer flow. And, I checked multi edges are allowed. 

Multi edges mean that there are several edges with capacity and cost between two vertexes.

My questions are 
(1) Is the optimal solution solved by this function really the optimal solution on given condition(flow of solution is integer)?

(2) Which method is used to implement the function?

Thank you

**Comment by lperron** [comment]
1) yes, The corresponding matrix is uni-modular.
2) From ortools/graph/min_cost_flow.h:

// An implementation of a cost-scaling push-relabel algorithm for
// the min-cost flow problem.
