### ISSUE TITLE
Max duration of searching

### ISSUE THREAD

**Issue by Nassimmd** [google/or-tools#572]
The variable "search_time_limit" in the code for the "Vehicle Routing with Time Windows" is created but never used again. How can a search time limit be added to the optimization problem?
My motivation for stopping the search is given by the fact, that for tight time width durations "tw_durations" the search for the optimal routes does not seem to come to an end.
Is there a changeable default value after which the search terminates? And if yes, how can that value be modified?

**Comment by pmateusz** [comment]
There are 2 parameters that constrain the duration of search: the limit on the number of solutions and the limit on duration of the search. For information how to set them see the example below.

```
operations_research::RoutingSearchParameters parameters = operations_research::BuildSearchParametersFromFlags();
        parameters.set_first_solution_strategy(operations_research::FirstSolutionStrategy::PARALLEL_CHEAPEST_INSERTION);
parameters.set_solution_limit(32);
parameters.set_time_limit_ms(boost::posix_time::minutes(3).total_milliseconds());
```

Once parameters are set, make sure that the search is run by the `SolveWithParameters` method.

```
model.SolveWithParameters(parameters );
```

To make sure that limits are set correctly execute a program with verbose logging (`-v 1`) and check the output stream.

```
first_solution_strategy: PARALLEL_CHEAPEST_INSERTION
use_filtered_first_solution_strategy: true
local_search_operators {
  use_relocate: true
  use_relocate_pair: true
  use_exchange: true
  use_cross: true
  use_two_opt: true
  use_or_opt: true
  use_lin_kernighan: true
  use_make_active: true
  use_make_inactive: true
  use_swap_active: true
  use_path_lns: true
  use_inactive_lns: true
}
guided_local_search_lambda_coefficient: 0.1
optimization_step: 1
solution_limit: 32
time_limit_ms: 180000
lns_time_limit_ms: 100
use_light_propagation: true
fingerprint_arc_cost_evaluators: true
```

See that limits are recognized by the solver.
```
time_limit_ms: 180000
lns_time_limit_ms: 100
```

If it works for you, please mark the issue as resolved and close it.

**Comment by Nassimmd** [comment]
Thanks! it worked.
