### ISSUE TITLE
Pickup Delivery Problem

### ISSUE THREAD

**Issue by johny8228** [google/or-tools#587]
Hello,

I want to solve a pickup and delivery problem with or-tools with no luck.The constraints I need are the followings:

1) Min service time + travel time per vehicle to be equal with  MIN hours
2) Max service time + travel time per vehicle to be equal with  MAX hours
3) The distribution of delivered items should be set to a MIN items per vehicle (balanced if possible).

All this with minimizing the total time to service all deliveries and minimizing the number of vehicles.

I searched a lot the internet and tried different approaches but none of them seems to work.Most of the time the solver tries to distribute all deliveries on one vehicle or he doesn't find a solution. 

Help with this problem will be highly appreciated.

Cheers,
Ionut

**Comment by antoniopaisfernandes** [comment]
Hey,

If you want, check out https://github.com/graphhopper/jsprit and https://github.com/kiegroup/optaplanner

Best regards

**Comment by johny8228** [comment]
Hi @antoniopaisfernandes ,

thank you for your reply.I investigated the possibility of using jsprit or optaplanner but since I'm using C# my first option now is or-tools.

Best regards

**Comment by ifle** [comment]
you can check the itinero project, maybe already has this option
https://github.com/itinero/optimization

**Comment by johny8228** [comment]
Hi ifle,

I know Itinero very well and it doesn't have this option :).

Thanks,
IOnut

**Comment by lperron** [comment]
There are hard and soft limit to deliveries + fixed cost per vehicles.
You should be able to model with or-tools.
