### ISSUE TITLE
Linker abi:cxx11 issues when or-tools is used as a library 

### ISSUE THREAD

**Issue by pmateusz** [google/or-tools#592]
When or-tools is used as a library, some functionality related to string manipulation cannot be used as is in C++11 code.

I am getting the following linker errors:
```
(.text+0xd9f): undefined reference to `StrCat[abi:cxx11](AlphaNum const&, AlphaNum const&)
```

Environment:
gcc 6.3.0
Debian Stretch

Investigation:
Seems that the problem can be solved by adding `-D_GLIBCXX_USE_CXX11_ABI=1`.

Workaround:
Use different functions for string manipulation.

**Comment by lperron** [comment]
2 answers:
  - We have integrated abseil-cpp in the library. This will help using these libraries.
  - or-tools needs c++11 support.

Closing the issue.
