### ISSUE TITLE
Pickup and Delivery: no solution

### ISSUE THREAD

**Issue by kalhusak** [google/or-tools#594]
Hi. I need to resolve simple problem using or-tools. It consists in calculating the optimal route for transporting passengers. I added one constraint to ensure that the passenger is first taken from the house and then delivered. I have two instances of relations between nodes: 

- OK. The solution is found within a millisecond: 1 -> 2, 3 -> 4, 5 -> 6, 7 -> 8, 9 -> 10, 13 -> 14, 11 -> 12, 15 -> 16, 17 -> 18

- FAILED. With some additional relations: 1 -> 2, 1 -> 3, 3 -> 4, 3 -> 5, 5 -> 6, 5 -> 7, 7 -> 8, 7 -> 9, 9 -> 10, 9 -> 11, 11 -> 12, 11 -> 13, 13 -> 14, 13 -> 15, 15 -> 16, 15 -> 17, 17 -> 18

1 -> 2 means that the node with index 1 must be visited before the node with index 2.

Node with index 0 is start depot and with index 19 is end depot.
I've tried to use different first solution strategies but result was the same.

It's my first time with or-tool and maybe I didn't read anything in the documentation.
Thanks for all the advice.

    std::vector<std::pair<RoutingModel::NodeIndex, RoutingModel::NodeIndex>> depots(1);
    depots[0] = std::make_pair(RoutingModel::NodeIndex(0), RoutingModel::NodeIndex(size - 1));
    
    // Create routing model for 'size' nodes and one vehicle
    routing = new RoutingModel(size, 1, depots);

    // SimpleRoadResolver::evaluateCost returns travel time from one node to another from matrix
    routing->SetArcCostEvaluatorOfAllVehicles(NewPermanentCallback(this, &SimpleRoadResolver::evaluateCost));

    // Create "time" dimension used to ensure order. It uses the same method as the main cost.
    int64 someBigValue = 2147483647;
    routing->AddDimension(NewPermanentCallback(this, &SimpleRoadResolver::evaluateCost), someBigValue, someBigValue, true, "time");
    const RoutingDimension &timeDimension = routing->GetDimensionOrDie("time");

    // For each relation add constraint. Pair {4, 7} means that the fourth node must be visited before the seventh node.
    Solver *solver = routing->solver();
    for (std::pair<int, int> relation : relations)
    {
        int64 pickUpNodeIndex = routing->NodeToIndex(RoutingModel::NodeIndex(relation.first));
        int64 deliveryNodeIndex = routing->NodeToIndex(RoutingModel::NodeIndex(relation.second));
        solver->AddConstraint(solver->MakeLessOrEqual(
            timeDimension.CumulVar(pickUpNodeIndex),
            timeDimension.CumulVar(deliveryNodeIndex)));
    }

    RoutingSearchParameters parameters = RoutingModel::DefaultSearchParameters();
    parameters.set_first_solution_strategy(FirstSolutionStrategy::PATH_CHEAPEST_ARC);
    parameters.set_time_limit_ms(5000);

    // solution is NULL
    const Assignment *solution = routing->SolveWithParameters(parameters);

**Comment by lperron** [comment]
The API has changed a lot since 7.0.

I hope the new API removed the problems.
