### ISSUE TITLE
Need to know internal design and limitation of VRP solver

### ISSUE THREAD

**Issue by bigtreeljc** [google/or-tools#596]
Hello, I am an algorithm engineer and responsible for deploying a VPR solver for our Sanitation workers. Note that we have 6 hundred plus garbage points and 30 garbage trucks in the current situation. We will have more. Currently I am doing experiment with 3 vehicles and their 70 garbage points. The VRP solver is doing great in such a condition. 
So I need to know what algorithm do you use in the VRP solver. Is that GA, Ant Colony Optimization or Neural Networks? Which part of the source should I take a closer look? What is the limitation of such an implementation?

**Comment by Mizux** [comment]
I would say, look for `Routing` files e.g. https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing_search.cc

**Comment by lperron** [comment]
Neither, Local search and meta heuristics.

Looking at your numbers, I would say you are fine.
