### ISSUE TITLE
Set CumulVar for each vehicle in VRP

### ISSUE THREAD

**Issue by bujol12** [google/or-tools#597]
Hi!

I need to set different starting times for each vehicle. Is there any way to set the initial value of a CumulVar for each vehicle?

Or maybe is it possible to set different Time Windows at the same node for different vehicles?

**Comment by hkerkhoff** [comment]
Hi,
perhaps a little bit late - in the Java Examples they set a Time-Window for the vehicles:

```
model.cumulVar(model.end(vehicle), "time").setMax(vehicleEndTime.get(vehicle));
```
See [https://github.com/google/or-tools/blob/6961e303a8a1ff2595bc095e598f4c153ff52bfd/examples/com/google/ortools/samples/CapacitatedVehicleRoutingProblemWithTimeWindows.java#L220](url)

If you want to a start and an end it's (hope so) like this:
```
model.cumulVar(model.start(vehicle), "time").setRange(start, end);
model.cumulVar(model.end(vehicle), "time").setRange(start, end);
```
(Start & End-Times are 'open' limited to a start-end range)

**Comment by bujol12** [comment]
Works - Thanks a lot @hkerkhoff ! :)

**Comment by Arun0013** [comment]
Hi

Similar to the above requirement, I also have a VRP problem where I need to set different time windows for the same node for different vehicles. For example, consider a node (say A), if node A is visited by Vehicle 1 then Time Window is [9,12] and if it is visited by Vehicle 2 then Time Window is [2,5]. Is there any way to do it?

```
model.cumulVar(model.start(vehicle), "time").setRange(start, end);
model.cumulVar(model.end(vehicle), "time").setRange(start, end);

``` 

The above works only for the start and the end nodes. But in the my case, the node could be an intermediate point as well.

**Comment by Mizux** [comment]
@Arun0013 simply:

* duplicate your node say A1, A2.
* add disjunction so only one among them need to be visited `routing.AddDisjunction([A1, A2,...])`
* constraint vehicle set to each node using `routing.VehicleVar(a1_index).SetValues([-1, vehicle_1])`
ref: https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/ortools/constraint_solver/routing.h#L1380-L1382
* Add TW for each node as usual `time_dimension.CumulVar(a1_index).setRange(start, end)`

**Comment by Arun0013** [comment]
@Mizux Thanks. Will try the same.
