### ISSUE TITLE
Problem with Sequence Var in Python

### ISSUE THREAD

**Issue by orwant** [google/or-tools#62]
Originally reported on Google Code with ID 46
```
I have some problem that I don't understand with the SequenceVar created by the DisjunctivConstraint.
One example : 
def main():
    solver = pywrapcp.Solver('Ordo')
    tasks = []
    [tasks.append(solver.FixedDurationIntervalVar(0, 25, 5, False, 'Tasks%i' %i)) for
i in range(3)]
    print tasks
    disj = solver.DisjunctiveConstraint(tasks, 'Disjunctive')
    solver.Add(disj)
    collector = solver.AllSolutionCollector()
    collector.Add(tasks)
    intervalPhase = solver.Phase(tasks, solver.INTERVAL_DEFAULT)
    solver.Solve(intervalPhase, [ collector])
    print collector.SolutionCount()
    for i in range(collector.SolutionCount()):
        print "Solution " , i
        print collector.ObjectiveValue(i)
        print [collector.StartValue(i, tasks[j]) for j in range(3)]
        print [collector.EndValue(i, tasks[j]) for j in range(3)]
With this code all is good, I have 6 solutions and it's what I expected.
But when I want call SequenceVar (for example make first the first task) that doesn't
work :
def main():
    solver = pywrapcp.Solver('Ordo')
    tasks = []
    [tasks.append(solver.FixedDurationIntervalVar(0, 25, 5, False, 'Tasks%i' %i)) for
i in range(3)]
    print tasks
    disj = solver.DisjunctiveConstraint(tasks, 'Disjunctive')
    sequence = []
    sequence.append(disj.SequenceVar())
    sequence[0].RankFirst(0)
    solver.Add(disj)
    collector = solver.AllSolutionCollector()
    collector.Add(sequence)
    collector.Add(tasks)
    sequencePhase = solver.Phase(sequence, solver.SEQUENCE_DEFAULT)
    intervalPhase = solver.Phase(tasks, solver.INTERVAL_DEFAULT)
    mainPhase = solver.Compose([sequencePhase, intervalPhase])
    solver.Solve(mainPhase, [ collector])
    print collector.SolutionCount()
    for i in range(collector.SolutionCount()):
        print "Solution " , i
        print collector.ObjectiveValue(i)
        print [collector.StartValue(i, tasks[j]) for j in range(3)]
        print [collector.EndValue(i, tasks[j]) for j in range(3)]

So how can I use SequenceVar from the disjunctivConstraint and what is the use of the
SequenceVar ?

```

Reported by `lperron@google.com` on 2014-07-21 17:25:50

**Comment by lperron** [comment]
Actually, the problem is in the sequence var.
The canonical way is to sequence all tasks with the sequencePhase, then do a time placement.
In this case, a PushLeft() strategy is good.

Here is a working code:

from ortools.constraint_solver import pywrapcp


class PushLeft(pywrapcp.PyDecisionBuilder):

  def __init__(self, vars):
    pywrapcp.PyDecisionBuilder.__init__(self)
    self.__vars = vars

  def Next(self, Solver):
    for v in self.__vars:
      v.SetStartMax(v.StartMin())
    return None

  def DebugString():
    return 'PushLeft'


def main():
    solver = pywrapcp.Solver('Ordo')
    tasks = [solver.FixedDurationIntervalVar(0, 25, 5, False, 'Tasks%i' %i)
             for i in range(3)]
    print tasks
    disj = solver.DisjunctiveConstraint(tasks, 'Disjunctive')
    sequence = []
    sequence.append(disj.SequenceVar())
    solver.Add(disj)
    collector = solver.AllSolutionCollector()
    collector.Add(sequence)
    collector.Add(tasks)
    sequencePhase = solver.Phase(sequence, solver.SEQUENCE_DEFAULT)
    intervalPhase = PushLeft(tasks)
    mainPhase = solver.Compose([sequencePhase, intervalPhase])
    solver.Solve(mainPhase, [ collector])
    print collector.SolutionCount()
    for i in range(collector.SolutionCount()):
        print "Solution " , i
        print [collector.StartValue(i, tasks[j]) for j in range(3)]
        print [collector.EndValue(i, tasks[j]) for j in range(3)]


if __name__ == '__main__':
  main()

**Comment by lperron** [comment]
Actually, I fixed the SEQUENCE_DEFAULT code to make it work, even if it is not the optimal way of doing it.
