### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION in java

### ISSUE THREAD

**Issue by shufflebump** [google/or-tools#621]
Hi.
I'm using the RoutingModel.
For the NodeEvaluator2, I tell it to return a value from a `List<List<Integer>>` object.
* If I fill this object with random numbers, it works fine.
* If I run another library that gets numbers that have real drive times (numbers that are very similar to the random numbers, between 0 and 30), it crashes when I tell the OR-Tools to `solve()`.

I believe it has to do with memory allocation, but I'm not sure. This is the error:

```sh
A fatal error has been detected by the Java Runtime Environment:
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff999348e68, pid=17512, tid=0x0000000000003bcc

 JRE version: Java(TM) SE Runtime Environment (8.0_161-b12) (build 1.8.0_161-b12)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.161-b12 mixed mode windows-amd64 compressed oops)
 Problematic frame:
 C  [jniortools.dll+0xd8e68]

 Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

 An error report file with more information is saved as:
 C:\Users\snbud\Documents\Ford\GORTools\hs_err_pid17512.log

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.
```

**Comment by lperron** [comment]
Most likely GC collected the callback during solve.
Please make sure it is still alive after the call to Solve.
