### ISSUE TITLE
Problem with negative capacities

### ISSUE THREAD

**Issue by josemazo** [google/or-tools#622]
Hi! While prototyping a VRP problem using this awesome library (kudos to the team) I've faced a problem in a kind of pickup & delivery problem.

For each node, the transit values for the capacity dimension are mixed (deliveries are positive and pickups are negative), so they can be, for example:

- 1 = 10 deliveries & 9 pickups _or_ only 1 delivery
- -2 = 4 deliveries & 6 pickups _or_ 3 deliveries & 5 pickups
- 0 = the same number deliveries and pickups

I create the capacity dimension with `fix_start_cumul_to_zero = False` and `slack_max = <The max capacity of a vehicle>`. For checking that the capacity constraint of a vehicle is respected after optimizing, I obtain the total capacity used with something like:
`used_capacity = max(cumul_capacities) - min(cumul_capacities)`,
where `cumul_capacities` is an array of the accumulated capacity of a vehicle while traversing its solution.
But sometimes, `used_capacity` is greater than the max capacity of the vehicle.

How can I ensure the capacity constraint is respected?

**Comment by braktar** [comment]
Did you define your capacity dimension using AddDimensionWithVehicleCapacity ?
This way, you can define the maximum value of this dimension for each vehicle.

**Comment by josemazo** [comment]
Hi @braktar, thanks for answering.

Yes, I used that dimension definition.

**Comment by furnon** [comment]
Even with the basic AddDimension, the argument after slack_max is capacity
(if the capacity is the same for all vehicles). Did you set it ?

**Comment by josemazo** [comment]
Hi @furnon, thanks for answering too.

Yes, I used this call (Python code):

```
capacity_callback = ...  # A function accepting two parameters, i and j
vehicles_capacity = [<random integers between 100 and 120>]
slack_max_capacity = max(vehicles_capacity)  # I've tried with also with min()
fix_start_cumul_to_zero = False

routing.AddDimensionWithVehicleCapacity(
    capacity_callback, slack_max_capacity, vehicles_capacity,
    fix_start_cumul_to_zero, 'Capacity')
```

**Comment by braktar** [comment]
Did you have a route example with a capacity violation ?

**Comment by josemazo** [comment]
Hi!

Sorry, I couldn't access the full code until today. [Here is a Gist](https://gist.github.com/josemazo/6ca2f67313364022876c8bc8dfa16172) with the full code.
In the [line 145](https://gist.github.com/josemazo/6ca2f67313364022876c8bc8dfa16172#file-vrp_solver-py-L145) the `Capacity` dimension is created using a callback with random (seeded) bases.

In that example, the vehicle 24 has 102 has capacity, but 104 is used. Its accumulated capacity array (the current capacity when passing by each node) is the next one.

```python
[0, -5, -9, -5, 4, 11, 2, 0, -2, 1, 3, 13, 20, 19, 28, 18, 14, 8, 4, -6, 4, 5, 13, 5, 11, 20, 24, 16, 6, -2, 5, 0, -9, -7, -9, -5, -5, -1, -3, -6, -3, 0, 7, -1, 9, 7, 16, 6, 2, 8, 4, 12, 7, 7, 1, 7, 9, 5, -3, -10, -1, 0, -7, -3, 3, -4, 1, -4, -5, 2, 9, -1, -6, -3, 4, -5, 3, 6, 16, 18, 15, 14, 7, 12, 9, 11, 6, 9, 15, 24, 17, 18, 27, 20, 16, 6, -4, -13, -21, -27, -33, -34, -44, -53, -60, -65, -60, -64, -74, -72, -69, -71, -73, -76, -68, -72, -71, -64, -63, -73, -69, -71, -71]
```

Because it starts with 0, for getting the actual used capacity I use this:

```python
real_used_capacity = max(cumul_capacity_list) - min(cumul_capacity_list)
```

And it shows over capacity 😢

**Comment by jaume-ferrarons** [comment]
Any update on this issue?
@josemazo have you managed to bypass the problem?

**Comment by josemazo** [comment]
Hi @jaume-ferrarons. Yes, it's still happening with version 6.8.5452.

**Comment by ChadiMezz** [comment]
hi @josemazo ! Did you find a solution for your problem ?

**Comment by lperron** [comment]
Just a comment for everybody, cumul variables cannot be negative.

**Comment by lperron** [comment]
The capacity of a dimension is equivalent to the volume used at any visit. After a delivery, the used capacity decreases. So it is normal, that the number of delivery done can be greater than the capacity of the dimension.

If you want to limit the number of deliveries, just create another dimension, and increase by 1 for each delivery.

Am I missing something ?

Please reopen if needed.

**Comment by haudarren** [comment]
Hi @lperron does this mean that the value returned by the callback used by `AddDimensionWithVehicleCapacity` cannot be negative, even if the cumulative dimension is still between 0 and the positive specified vehicle capacity? If so, that might explain the issue I'm seeing here:
https://stackoverflow.com/questions/70602988/google-or-tools-pickup-deliveries-with-optional-nodes-for-refueling

In this case I'm trying to enable a vehicle to recharge (or refuel), by having the `energy_callback` return a negative value to keep the dimension below the vehicle capacity.

**Comment by lperron** [comment]
The value can be negative. It is used in multiple places (cvrp_reload, pdp).

**Comment by haudarren** [comment]
Thanks @lperron. Is there a reference example somewhere showing this kind of refueling, or replenishing some other vehicle capacity constraint?

**Comment by lperron** [comment]
Cvrp_reload, pdptw...
