### ISSUE TITLE
Only empty vehicles on the depot

### ISSUE THREAD

**Issue by josemazo** [google/or-tools#623]
Me again (https://github.com/google/or-tools/issues/622) 🤦‍♂️ , sorry.

I'm prototyping a waste collection problem where the vehicles can go a few times to a disposal plant (there are a few of them), but they need to come back empty to the depot.

The empty of the vehicle can be modelled like the fuel example, it's not a problem.
The thing is, how can I model the constraint for coming back empty to the depot? I'm a little bit lost.

**Comment by braktar** [comment]
Hello,

By my side, I define a node or a set of node which must be performed just before the end node.
And because, i'm sure there is no collecting point after those, it doesn't require to define a quantity to reload.

**Comment by josemazo** [comment]
Hi, thanks again @braktar, you guys are awesome.

I understand what you say about defining a `constraint` for a node or a set of nodes that need to be performed before de depot. The thing is I don't know how to specify it with `NextVar`.

I 'am looking to this [example](https://acrogenesis.com/or-tools/documentation/user_manual/manual/vrp/first_vrp_implementation.html#how-to-force-all-vehicles-to-service-cities) but I don't get how to use it for this case.

**Comment by braktar** [comment]
Our implementation could maybe help you : https://github.com/Mapotempo/optimizer-ortools/blob/master/tsp_simple.cc#L445

**Comment by josemazo** [comment]
Hi @braktar,

Nice! I totally got it now!! Thanks a lot, you're the best!

**Comment by morruth** [comment]
@braktar, you mean  

case MaximumDurationLapse: part
 or
case ForceLast: ?

**Comment by braktar** [comment]
At the time, I pointed ForceLast. I've updated the link to be unsensitive to change
