### ISSUE TITLE
VRP (For Trucks) with 2D Bin Packing Constraints

### ISSUE THREAD

**Issue by mu4farooqi** [google/or-tools#625]
So currently we can find optimal routes with weight and volume dimensions/constraints but how can we make sure that items will fit it a vehicle/truck too i.e. (2D bin packing).

I'm able to do optimized routing using or-tools and I'm also done with 2-D bin packing using heuristic approaches but how can we combine them.

Thanks

**Comment by lokeshlal** [comment]
Hi, Did you found a solution to this.

Thanks,

**Comment by Mizux** [comment]
please use the mailing list for this kind of question, you will reach much more users...
