### ISSUE TITLE
Experience running `tools\make netstandard`

### ISSUE THREAD

**Issue by flashfm** [google/or-tools#631]
Hi,
first of all, thanks a lot for the great library 👍 
I want to share my experience of running `tools\make netstandard`.
My environment is:
- Win 10 ver 1709 build 16299.309
- VS 2017 (using x64 Native Tools Command prompt)

So, the things what were not smooth:
1. Lack of information about now to build netstandard library :) Really, I spent a lot of time before I found that `netstandard` is a valid option for `tools\make` digging inside the `Makefile.csharp.mk`. It would be great to see it in the `tools\make` output.
2. The prerequisites list on https://developers.google.com/optimization/introduction/installing/source.html#requirements_windows does not contain a lot of stuff to be installed: Windows SDK 8.1, Windows CRT and others. Probably it's because I did not have complete version of VS installed.
There is also no info about what to do with the output (i.e. that Core dll should be referenced, and Native dll should be copied). It would be great to have it described as well.
3. Building OrTools.NetCore.csproj failed with 2 errors:
a)
```
C:\Program Files\dotnet\sdk\2.1.103\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(114,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly. [c:\Work\or-tools-master\objs\netstandard\OrTools.NetCore.csproj]
C:\Program Files\dotnet\sdk\2.1.103\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(114,5): error MSB4018: System.UnauthorizedAccessException: Access to the path 'c:\Google.OrTools.Core.deps.json' is denied. [c:\Work\or-tools-master\objs\netstandard\OrTools.NetCore.csproj]
```
I had to create this file manually on the root of C: disk. Probably it would not be a problem if I run `tools\make` under Admin account, but anyway, why it uses root folder?
b) The next time it failed with 
```
C:\Program Files\dotnet\sdk\2.1.103\Microsoft.Common.CurrentVersion.targets(4118,5): error MSB3021: Unable to copy file "obj\x64\Debug\netstandard2.0\Google.OrTools.Core.dll" to "\Google.OrTools.Core.dll". Access to the path 'c:\Google.OrTools.Core.dll' is denied. [c:\Work\or-tools-master\objs\netstandard\OrTools.NetCore.csproj]
```
However, the dll was already in the `obj` folder, so I just took it and it worked.

**Comment by Mizux** [comment]
Hi, 

Thanks a lot for your feedback !
Currently .Netstandard is still Experimental (and I'm still learning .Net stuff and .Net languages relationship)

1) I'm currently thinking of moving it to its own `makefiles/Makefile.netstandard.mk` and add its targets to `make help`. (I guess netstandard don't need csharp output files contrary to F# which rely on C# library)
note: people would want to have one nuget package for net40 and netstandard2.0 cf #588 (currently we only provide C# net40)

2) I would say, the long term goal is to use a ortools nuget package to integrate ortools to your .Net project and only build using Makefile/CMake if you want to build a custom local version.
I won't say adding/hacking an example then call `make netstandard; make test_netstandard` to use ortools netstandard is a good workflow to integrate it...

3) I need to figure out what is the purpose of this .csproj... Is it really needed if you have a nupkg ? (I didn't check if nuget package need it)

So still not sure how to deal with all of this (any experience/proposal are welcome)

**Comment by flashfm** [comment]
> I need to figure out what is the purpose of this .csproj... Is it really needed if you have a nupkg ? (I didn't check if nuget package need it)

I think that OrTools.NetCore.csproj is the one which produces Google.OrTools.Core.dll and then a nupkg with it. For some reason it tries to write that dll in to C:\ not into the relative bin\ directory.

**Comment by Mizux** [comment]
All configuration files are located in `<rootdir>/tools/netstandard`. .csproj seems to be use by dotnet build/pack to create/copy artifacts...
It seems `OutputPath` is not defined which Cmaybe could explain why `<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>` copy to `C:\`
Need to do some test...

src: https://msdn.microsoft.com/en-us/library/bb629394.aspx

**Comment by Mizux** [comment]
With the merge on master now `make dotnet` should be more user friendly

doc here: https://github.com/google/or-tools/blob/master/ortools/dotnet/README.md
