### ISSUE TITLE
Solver check fails on solution for the vrptw with breaks

### ISSUE THREAD

**Issue by tomika** [google/or-tools#633]
Program terminates with message:
expressions.cc:1338] Check failed: min_.Value() == max_.Value() (-2880 vs. -135)  variable Time fixed transit(-2880..-135) is not bound.

I attached most simple code I could create to reproduce the problem.
(Renamed to txt to be accepted by github)

[bug.cc.txt](https://github.com/google/or-tools/files/1859037/bug.cc.txt)

**Comment by Mika-5** [comment]
Hi tomika,
I recently encountered the same problem when i set up the breaks constraints. Have you got any idea where does that come from ?

**Comment by tomika** [comment]
Not really. I totally ignored the built-in break since it is clearly not working and use another one suggested by pmateusz. I got message from the authors on another forum few weeks ago that a brand new, rewritten from scratch break handling will be in the next release of or-tools, hopefully in this year.

**Comment by Mizux** [comment]
You can look at branch abseil for the coming v7.0 ortools ETA Christmas 2018 containing the up to date routing library with break fix...

note: before we will release v6.10 (minor change)

**Comment by Mika-5** [comment]
Thank you  both for your response. I already implement the pmateusz suggestion and it is a bit odd because sometimes I get the issue ans sometimes I do not. 
I will await Christmas then !

**Comment by lperron** [comment]
Both the routing API and the break code has changed completely since 7.0.

Can you have a look at:
