### ISSUE TITLE
Wrong path of dotnet on Ubuntu 16.04

### ISSUE THREAD

**Issue by flashfm** [google/or-tools#634]
Hi,
when running `make netstandard` on Ubuntu 16.04 it fails with
```
The dotnet sdk path was not set properly. Check Makefile.local for more information.
```
The line from Makefile.local:
```
DOTNET_INSTALL_PATH = /usr/local/share/dotnet/sdk
```
However the current placement of SDK is `/usr/share/dotnet/` if installed from official manual (https://www.microsoft.com/net/learn/get-started/linux/ubuntu16-04).
So I had to do `ln -s` as a workaround to make it working.

**Comment by Mizux** [comment]
Hi,

Yes for dotnet executable mamangement I'll do some fix soon currently the way to find it is not good especyally on linux where you can use `which` (I did it for csharp fsharp nuget but dotnet)

**Comment by Mizux** [comment]
Waiting for #668 first

**Comment by Mizux** [comment]
Now we only look for `dotnet` command in your PATH using bin/sh's `which` (to replace by `command -v`).
if you installed dotnet cli using windows package cf https://www.microsoft.com/net/learn/get-started-with-dotnet-tutorial#install it should works on master and in v6.8
