### ISSUE TITLE
Crashes when using c# (ucrtbase.dll)

### ISSUE THREAD

**Issue by srowan** [google/or-tools#636]
I'm seeing consistent crashes when developing / executing CP Solver via c# when I attempt to use advanced scenarios such as custom local search or search monitors.

Just to show one example, consider the following SearchMonitor:

```cs
class NullSearchMonitor : SearchMonitor
    {
        public NullSearchMonitor(Solver s) : base(s)
        {
        }

        public override void AfterDecision(Decision d, bool apply)
        {
            // do nothing
        }
}
```

When I add this as a search monitor to my jobshop solver:
```
var nullMonitor = new NullSearchMonitor(_solver);
bool solutionFound = _solver.Solve(somePhase, nullMonitor);
```

..The application crashes after a few seconds with a vanilla windows "Has stopped responding" error, and the following appears in the event log:

```
Faulting application name: LearnConsole.exe, version: 1.0.0.0, time stamp: 0x5abd697d
Faulting module name: ucrtbase.dll, version: 10.0.16299.248, time stamp: 0xe71e5dfe
Exception code: 0xc0000409
Fault offset: 0x000000000006b79e
Faulting process id: 0xea0
Faulting application start time: 0x01d3c7add26e6be7
Faulting application path: C:\Users\itzle\Desktop\or-tools_VisualStudio2017-64bit_v6.4.4495\MyTests\UnitTestProject2\LearnConsole\bin\Debug\LearnConsole.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 9dcb4e41-ccf0-44ff-a3c7-fbaa5a711cac
Faulting package full name: 
Faulting package-relative application ID: 
```

Anything I can do to help track down what might be causing these crashes, please let me know...

**Comment by srowan** [comment]
As an additiona note, I'm also seeing this with custom symmetrybreakers, etc.   But not always.

I suspect there may be exceptions occurring in ortools that aren't bubbled up to c# in any way.  Is there any troubleshooting steps I can follow?

**Comment by atisnz** [comment]
I have a similar problem, I have a QGis plugin to solve a vehicle routing problem using ORTools.  
When the program gets to the ORTools part, Qgis crashes and leaves an Error Event in Eventviewer, but no stacktrace.   
According to this event the crash is caused by ucrtbase.dll. See the screenshot below. 
The OS is Windows server 2012 with latest updates. 
I have created the user mode crash dump which is uploaded to onedrive including the WER report file here: 
https://1drv.ms/f/s!ApOUFM1sYj1FhRT5NvmpmrWYYWum

event log: [https://1drv.ms/u/s!ApOUFM1sYj1FhR5JCHEptJHp86nY](https://1drv.ms/u/s!ApOUFM1sYj1FhR5JCHEptJHp86nY)

**Comment by lperron** [comment]
I would say distance callbacks and custom C# objects passed to the solver a
GC'd away while the C++ code is running.
You can try adding gc.keepalive() for all your c# objects you pass to the
solver.

The keepalive call keeps the object alive until the call, therefore it
needs to be put after the call to the solver solve().
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
We start to have xunit for search monitor on master
https://github.com/google/or-tools/blob/842d1a4d24273acd3a091037eefcf545cc5a1ad1/examples/tests/ConstraintSolverTests.cs#L741-L827
