### ISSUE TITLE
Incorrect warning message whenever solver-specific parameters are set

### ISSUE THREAD

**Issue by yingzong** [google/or-tools#639]
Whichever backend is used, solver-specific parameters are passed by writing a temporary file. The temporary file is read by the backend interface, and then deleted in `linear_solver.cc`. However, the following warning is printed, despite that the file is deleted.

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0330 20:00:45.343852 1962688512 linear_solver.cc:1479] Couldn't delete temporary parameters file: /tmp/parameters-tempfile-7b-44055-227b4761928bb.tmp
```

This seems wrong. Related to #57 .

**Comment by lperron** [comment]
Fixed in 7.3
