### ISSUE TITLE
Vehicle Capacity (Weight, height and Bin fitting) and Disposal sites with VRP

### ISSUE THREAD

**Issue by lokeshlal** [google/or-tools#643]
Hi,

I am working on a routing problem for a waste management company.

Requirement is to deliver empty bins to different locations and collect filled bins from locations.

Bins comes in different size (such as 2 ton bin, 4 ton bin...etc).

Plus vehicles can stack empty bins to be delivered to locations, however they will receive filled bins from locations and cannot be stacked. Bins can stack on one another partially inserted. Plus every vehicle is also constrained by maximum weight it can carry.

They have different type of vehicles as well with different capacity.

Each vehicle can load different type of bins.

Plus, there could be multiple disposal sites. 

There is also a possibility that vehicle could pick up some waste from some locations and then dispose the waste and then deliver the empty bins (already picked at depot) to locations. 

1) how vehicle capacity should be done
2) how disposal sites should be handled.

Thanks,

**Comment by lokeshlal** [comment]
Hi, I think AddDimensionDependentDimensionWithVehicleCapacity can help me in this. However, AddDimensionDependentDimensionWithVehicleCapacity is not available in C#. Will this be added soon in C# or any alternate to this function in C#.

Thanks,

**Comment by Mizux** [comment]
Then it's related to #339

**Comment by lokeshlal** [comment]
Anyone struggling to solve this...

Add constraint saying a particular pick up can be dropped to multiple location using solver. Makemax ... such as solver.makemax(vehiclevar(pickup) == vehiclevar(drop1), ...) == 1

Next add condition drop location time should b greater than pickup...

Thanks

**Comment by theholyrock** [comment]
Hi, I'm looking into creating a similar routing system for a waste removal company. Have you solved this issue?
