### ISSUE TITLE
Passing solver parameters 

### ISSUE THREAD

**Issue by prezaei85** [google/or-tools#644]
Currently, SetSolverSpecificParametersAsString() does not work, at least in C# for SCIP. I have passed "limits/time = 60" to limit optimization time to 60 seconds or set "limits/totalnodes = 100" to limit the number of nodes, but none of them work successfully. There seems to be no other way to pass parameters also to other solvers, e.g., CPLEX, right now. Solving MIP problems usually requires to pass at least some solver tuning parameters to improve performance.

**Comment by lperron** [comment]
For time limits, you can use MpSolver.SetTimeLimit(int64 time_limit_in_ms).

Now I wonder why it does not work as the function is implemented. I will
have a look.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 5 avr. 2018 à 16:52, Pooya Rezaei <notifications@github.com> a
écrit :

**Comment by praveenxrao** [comment]
Hello, any update? I am trying to set GAP limit but unable to find a way to set it. Help is appreciated. Thank you

**Comment by prezaei85** [comment]
Relative MIP Gap is probably the only parameter that can be set directly using SetDoubleParam, and does not need to passed as string. For other parameters, there is still no way.

namespace Google.OrTools.LinearSolver
{
    public class MPSolverParameters : IDisposable
    {
        public static readonly int RELATIVE_MIP_GAP;
        protected bool swigCMemOwn;

        public MPSolverParameters();

        ~MPSolverParameters();

        public static double kDefaultPrimalTolerance { get; }

        public virtual void Dispose();
        public double GetDoubleParam(int param);
        public void SetDoubleParam(int param, double value);
    }
}

**Comment by prezaei85** [comment]
It is not under Solver. It is under MPSolverParameters. You need to instantiate that object, set MIP Gap and then pass MPSolverParameters to the Solve() method.

**Comment by lperron** [comment]
I assume this is fixed.

**Comment by danmarinescu** [comment]
See my answer here #603 for how to use `SetSolverSpecificParametersAsString` (with CPLEX, same concept might also apply to SCIP)

**Comment by rlloretb** [comment]
Any news on how to pass any solver parameters for SCIP solver? I mean not just time limit and relative MIP gap.

**Comment by lperron** [comment]
Relative mip gap can be set directly on the solver.

create a MPSolverParameters,
SetDoubleParam(MPSolverParameters.RELATIVE_MIP_GAP,  value)

then pass to Solve(parameters)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by rlloretb** [comment]
And what about any other command that it is not time_limit or relative_MIP_gap (via set SetSolverSpecificParametersAsString?)
I am particularly interested in CBC and SCIP.

**Comment by DanieleVeri** [comment]
How can I use `SetSolverSpecificParametersAsString` to set  the verbosity and the deterministic time limit? The documentation is not clear.

**Comment by rishikeshkushwaha** [comment]
I am also facing same issue. Is there any work around for this?
