### ISSUE TITLE
Custom constraints in C# for VRP

### ISSUE THREAD

**Issue by lokeshlal** [google/or-tools#646]
Hi,

I am looking for examples of writing custom constraints in C#.

I need to achieve following 

```
// add a contrating
// if j is next location to i
if (model.NextVar(i) == j)
{
    // check commulative value
    var configurationAtNodeI = model.CumulVar(i, "configuration");
    var vehicleInRoute = model.VehicleVar(i);
    var vehicleIndex = Convert.ToInt32(vehicleInRoute.Value());
    var vehicleConfiguration = vehicleCapacities_2[vehicleIndex];

    // check vechileConfiguration against configurationAtNodeI
    // if it validates, then set constraint True otherwise False
}
```

for this I want to create a custom constraint (may be for all possible combinations of nodes).

Custom constraint will accept following in contructor

```
public CustomVehicleCapcityDemand(Solver solver, 
    RoutingModel model, // model
    int i, //current node
    int j, // next node
    int[] vehicleCapacities_2 // this is vehicle configuration
    ) : base(solver)
{
    this.model = model;
}
```

Can someone please help me in writing the correct constraint (as I am not able to find the documentation).

I need to know what will go in `InitialPropagateWrapper`, `Post` and `Var` method

Thanks

**Comment by lokeshlal** [comment]
Hello,

Any pointer or references will be very helpful.

Thanks,

**Comment by Mizux** [comment]
Hi, try to look at Routing example in python and adapt to C#.
What you need is to add a new Dimension
https://developers.google.com/optimization/routing/tsp/vehicle_routing#vehicle_capacity

**Comment by lokeshlal** [comment]
Hi Mizux,

I am trying to solve the container fitting in the truck. 

For this I would require configuration of each vehicle and then if solver is going from node i -> node j, then check the cumulative value at node i and check against the vehicle configuration. If it fits in then pass the constraint otherwise fail the constraint.

Vehicle configuration would be like "1" for type 1 filled container, "10" for type 2 filled container..etc..
and similarly "1000" for type 1 empty container (empty containers can be stacked on top of each other and will be partially inserted)....

In dimension, is it possible to do calculation or pass custom logic.

Thanks

**Comment by lokeshlal** [comment]
for example

demand = [1, 10, 1000, 10000, 1000, 1000]

vehicle_capactiy = [11111111, 1111111] this will be value representing vehicle type could be any value

then demands will be added after every node...and will represent a the exact value a truck is holding at any point. This value will be checked against the configuration using custom function (logic).

Thanks,

**Comment by Mizux** [comment]
Usually dimension are one dimension "quantity" like weight, distance, time, number of node visited etc...
and you define the quantity increase/decrease for each edge of the graph (i.e. you give a callback "transit(i, j) -> value")
then solver do some computation on the lower/upper bound and verify the quantity stay in the limit of the vehicle.

It seems here you want to use a kind of bit field....

my 2 cents:
For each vehicles I would specified:
- how many empty containers of type 1 each vehicles can support in a Dimension A
- how many empty containers of type 2 each vehicles can support in Dimension B
- how many full containers of type 1 each vehicles can support in a Dimension C
- how many full containers of type 2 each vehicles can support in a Dimension D
then add constraints mixing different dimension.

Or supposing a vehicle have max three "slots" and type1 use one "slot", and type2 use two "slots"
then add a Dimension E which is `nb_type1*1(slot) + nb_type2*2(slots) <= 3(vehicles slot capacity)`


ps: There is also a  AddDimensionDependentDimensionWithVehicleCapacity #574 which could fulfill your requirement but I don't know yet how to use it, sorry...

**Comment by lokeshlal** [comment]
Found a stackoverflow question

[https://stackoverflow.com/questions/27814935/boolean-operations-on-constraints-in-google-or-tools-library/38901246#38901246](https://stackoverflow.com/questions/27814935/boolean-operations-on-constraints-in-google-or-tools-library/38901246#38901246)

However in this case model.VehicleVar(i) this would return the index of vehicle...so the condition should be `model.VehicleVar(i) - i == 0` and  will this return 1 if success and 0 if failure `nb_type1*1(slot) + nb_type2*2(slots) <= 3(vehicles slot capacity)` ?

Thanks

**Comment by lokeshlal** [comment]
Thanks Mizux. I am able to solve the problem using your suggestion.
