### ISSUE TITLE
How to stop SAT search after a first (n-th) solution found?

### ISSUE THREAD

**Issue by Motorrat** [google/or-tools#651]
Running https://github.com/google/or-tools/blob/master/examples/python/school_scheduling_sat.py
seems to go on indefinitely printing "Found Solution!". Is there a way to specify that the search should stop after finding the first (or n first) solution(s)?
I see that there is an issue open since 2015 on stopping the process with the Ctrl+C  - i.e. that also doesn't help. https://github.com/google/or-tools/issues/18
SAT solver method called in the example is explicitly called SearchForAllSolutions https://github.com/google/or-tools/blob/6961e303a8a1ff2595bc095e598f4c153ff52bfd/ortools/sat/python/cp_model.py#L1114 so ...

**Comment by Mizux** [comment]
For routing model you can use different `SearchLimits` options https://developers.google.com/optimization/routing/tsp/routing_options#search-limits

which seems to bind [Solver::MakeLimit](https://github.com/google/or-tools/blob/master/ortools/constraint_solver/search.cc#L4002)...

**Comment by Motorrat** [comment]
@Mizux While I see how this could be useful aren't SAT and Routing two different codebases? 
What I found though is the comment from @lperron   removing time limit https://github.com/google/or-tools/commit/4cd6ecccb3a6a9f645db5ce0a3770513a8b0cb20#diff-59a2a7bc3737a3a9a3fa9f4448e4ed32
-        const SatSolver::Status status = solver->SolveWithTimeLimit(time_limit);
+        const SatSolver::Status status = solver->Solve();
https://github.com/google/or-tools/blob/master/ortools/sat/cp_model_solver.h#L47

**Comment by Motorrat** [comment]
Also to clarify - the root problem is that the search in the example https://github.com/google/or-tools/blob/master/examples/python/school_scheduling_sat.py doesn't seem to stop after some tens of minutes elapsed. This doesn't look like a helpful example, specifically because it is not clear if it will ever stop.

**Comment by lperron** [comment]
You are right.

We will look at how to add this API on the python API.

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Motorrat** [comment]
It seems like SolveWithSolutionObserver https://github.com/google/or-tools/blob/master/ortools/sat/python/cp_model.py#L1107 is the one I was looking for for this example. it could be just substituted for SearchForAllSolutions https://github.com/google/or-tools/blob/master/examples/python/school_scheduling_sat.py#L123 
Could you please confirm?

**Comment by lperron** [comment]
Code is submitted and documented:

https://github.com/google/or-tools/blob/master/ortools/sat/doc/solver.md#stopping-search-early

It should be available in v6.9

Closing the issue now.

Thanks
