### ISSUE TITLE
How To collect and print a solution in school_scheduling_sat.py ?

### ISSUE THREAD

**Issue by Motorrat** [google/or-tools#652]
https://github.com/google/or-tools/blob/0027a1a1929aebd33f95d983a3d671c77dfdf5ea/examples/python/school_scheduling_sat.py#L117
shows `self.collector = None` and there is nothing like `LastSolutionCollector` in the https://github.com/google/or-tools/blob/master/ortools/sat/python/cp_model.py if one would try to go as advised in the tutorial https://developers.google.com/optimization/scheduling/job_shop

**Comment by lperron** [comment]
If you just need to access the last solution. Do no use a solution
observer, and just query the values from the solver. (see
gate_scheduling_sat.py).
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 16 avr. 2018 à 22:31, Diego Kobylkin <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
Just do solver.Value(int_var), or solver.BooleanValue(literal).

See https://github.com/google/or-tools/blob/master/ortools/sat/doc/integer_arithmetic.md#python-code
