### ISSUE TITLE
how to get extreme ray for unbounded lp?

### ISSUE THREAD

**Issue by YuyangZhangFTD** [google/or-tools#653]
Hey, I'm working on a problem with benders decomposition.
So I wonder whether there are any methods like getRays() in cplex ?

**Comment by lperron** [comment]
unfortunately no, at least for the time being.

**Comment by Miraclelucy** [comment]
Has it been resolved?

**Comment by lperron** [comment]
Check the MathOpt API.

**Comment by soppera** [comment]
> Check the MathOpt API.

See https://github.com/google/or-tools/discussions/4248 for an example on how to do that.
