### ISSUE TITLE
Issue with pywraplp

### ISSUE THREAD

**Issue by manzo1991** [google/or-tools#654]
Hi, i'm running a code implemented in Python 3.6 and ortools==6.7.4973.
I'm getting this error while the solver is searching the solution:

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0417 11:18:48.094962  8616 revised_simplex.cc:1015] Reverting to Bixby's initial basis algorithm.
W0417 11:18:50.741611  8616 revised_simplex.cc:1015] Reverting to Bixby's initial basis algorithm.
W0417 11:18:52.886440  8616 revised_simplex.cc:1015] Reverting to Bixby's initial basis algorithm.
W0417 11:18:58.409821  8616 revised_simplex.cc:1015] Reverting to Bixby's initial basis algorithm.
...
```

What does it means? It continues to print this message never finding the final solution

**Comment by Mizux** [comment]
seems to come from here: https://github.com/google/or-tools/blob/master/ortools/glop/revised_simplex.cc#L1015

**Comment by manzo1991** [comment]
BTW, i have that error while using pywraplp.Solver.BOP_INTEGER_PROGRAMMING. It doesn't occur while using pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING

**Comment by Mizux** [comment]
BOP is a solver for [Boolean Optimization Problem](https://developers.google.com/optimization/reference/bop/bop_solver/). Maybe that could explain why it doesn't work with your model ?
