### ISSUE TITLE
How can i use multiple processor cores in CVRPTW problem?

### ISSUE THREAD

**Issue by morruth** [google/or-tools#656]
How can i use multiple processor cores in CVRPTW problem?

I've tried some experiments based on cvrptw.py form examples
there is 100% load on one core and no work on another cores

Is there a way to utilize power of all cores on multicore/multicpu system, solving this problem?

**Comment by pmateusz** [comment]
No. Parallel computation is not part of the routing library. You may build something yourself, such as the parallel for-loop, to run computations on several cores, since the search is not deterministic.
