### ISSUE TITLE
Is there any way to get strategy, automatically selected by solver in routing problem?

### ISSUE THREAD

**Issue by morruth** [google/or-tools#658]
if i don't set first_solution_strategy for solver, how can I receive strategy, selected automatically?
Is there one preferred, or solver try different strategies and select best?

**Comment by pmateusz** [comment]
You may see issue #294 for some guidance.

**Comment by Mizux** [comment]
Looking at the code quickly I would say

[void RoutingModel::CreateFirstSolutionDecisionBuilders](https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing.cc#L4070) will build it using:

```cpp
  // Automatic
  // TODO(user): make this smarter.
  if (pickup_delivery_pairs_.empty()) {
    first_solution_decision_builders_[FirstSolutionStrategy::AUTOMATIC] =
        first_solution_decision_builders_
            [FirstSolutionStrategy::PATH_CHEAPEST_ARC];
  } else {
    first_solution_decision_builders_[FirstSolutionStrategy::AUTOMATIC] =
        first_solution_decision_builders_
            [FirstSolutionStrategy::PARALLEL_CHEAPEST_INSERTION];
  }
```
src: https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing.cc#L4244

Which is what vfurnon said in https://github.com/google/or-tools/issues/294#issuecomment-270167683
