### ISSUE TITLE
Export optimization problem in CPLEX LP format

### ISSUE THREAD

**Issue by prezaei85** [google/or-tools#662]
The variables that do not have any bounds, need to have the word "free" in front of them when they are mentioned in the Bounds section of the LP file. Otherwise, the solver cannot read the problem and reports infeasible problem:
From http://lpsolve.sourceforge.net/5.0/CPLEX-format.htm:
A variable with a negative infinity lower bound and positive infinity upper bound may be entered as free, in any mix of upper- and lower-case characters, with a space separating the variable name and the word free. For example, `x7 free` is equivalent to `- infinity <= x7 <= + infinity`.

**Comment by Mizux** [comment]
Hi, I don't think we export/use the CPLEX format.
I guess you can compile or-tools with flatzink format support and the CPLEX solver as backend but that's all...

Why do you think or-tools use this format ? (please point us to the source where you saw it thanks !)

**Comment by prezaei85** [comment]
The LP format is a standard optimization model format similar to MPS for (mixed integer) linear programming models, and Google OR is able to export the optimization problem in LP format. The LP (similar to MPS) can then be fed to any optimization solver. There is a small bug with the export that causes the solvers to report infeasibility. I think I fixed the issue. Here is the pull request: https://github.com/google/or-tools/pull/664

**Comment by Mizux** [comment]
#664 merged -> close this issue
