### ISSUE TITLE
Seg fault in weighted_tardiness_sat.cc

### ISSUE THREAD

**Issue by TheCoolRob** [google/or-tools#663]
Hi
Was running through some examples and it seems like the proto schema is a bit out of sync with the weighted_tardiness_sat example. It runs correctly but fails when parsing back a solution to the anonymous function (line 221) on the master branch (https://github.com/google/or-tools/commit/8ae61b6feb64c6193b4706535f8d06ee6e4e7270) . 

Heres the trace from my test instance:

```
I0424 00:24:56.930763 24332 weighted_tardiness_sat.cc:266] 15000 numbers in 'examples/data/weighted_tardiness/wt40.txt'.
I0424 00:24:56.930918 24332 weighted_tardiness_sat.cc:267] This correspond to 125 instances of size 40
I0424 00:24:56.930930 24332 weighted_tardiness_sat.cc:269] Loading instance #28
I0424 00:24:56.930948 24332 weighted_tardiness_sat.cc:53] #0 duration:27 due_date:1829 weight:10
<squanched stuff>
I0424 00:24:56.931286 24332 weighted_tardiness_sat.cc:53] #39 duration:38 due_date:1566 weight:6
I0424 00:24:56.931308 24332 weighted_tardiness_sat.cc:78] num_tasks: 40
I0424 00:24:56.931319 24332 weighted_tardiness_sat.cc:79] The time horizon is 2006
I0424 00:24:56.931329 24332 weighted_tardiness_sat.cc:80] Trival cost bound = 15
I0424 00:24:56.931605 24332 weighted_tardiness_sat.cc:205] Added 284 precedences that will not affect the optimal solution value.
I0424 00:24:56.935345 24332 weighted_tardiness_sat.cc:249] Model 'weighted_tardiness':
Search strategy: on 40 variables, CHOOSE_HIGHEST_MAX, SELECT_MAX_VALUE
#Variables: 160
 - 112 different domains in [0,2006] with a largest complexity of 1.
 - 40 constants in {1,6,12,18,19,20,22,26,27,29,30 ... 50,54,60,63,64,66,67,70,75,76,78,80,81,84,94,99} 
#kInterval: 40 (0 with enforcement literal)
#kLinear: 324 (0 with enforcement literal)
#kNoOverlap: 1 (0 with enforcement literal)
[1]    24332 segmentation fault (core dumped)  ./bin/weighted_tardiness_sat

```

**Comment by TheCoolRob** [comment]
Spent a bit more time with this. It seems like the CpSolverResponse has values populated in the lower_bounds and upper_bounds but not the actual response solution vector. I did a quick check and all the lower bounds are equal to the upper bounds. Seems like at some point that vector was populated with values because the solution observer references it quite liberally?

**Comment by lperron** [comment]
Hi,

Actually the examples described the needed implementation, while the code
was not following that.
I have updated the example:

https://github.com/google/or-tools/blob/master/examples/cpp/weighted_tardiness_sat.cc

where I changed the solution observer.

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
fixed after https://github.com/google/or-tools/commit/1ec337d9c041ed03960d3a9bfc3e50c076b573bd

Thanks
