### ISSUE TITLE
MinimizeIntegerVariableWithLinearScan failure

### ISSUE THREAD

**Issue by TheCoolRob** [google/or-tools#666]
I'm not sure if my usage is correct but when I attempt to use this method I get a failure:
```
terminate called after throwing an instance of 'std::bad_function_call'
  what():  bad_function_call
```
It seems that the solver is attempting to iterate over a list of heuristics which hasn't been populated.
The error is in on the function invokation on line 74 of `integer_search.cc` in the SequentialSearch method. 
When I use MinimizeIntegerVariableWithLinearScanAndLazyEncoding and provide a "NextDecision" function, the solver runs as expected. I'm using default sat parameters.

I suppose my question is: what is the correct usage of this entry point to the solver? It currently isn't obvious how to load heuristics if they are required by this call into the solver and I couldn't find a sensible way to load heuristics to the solver through the model.Add api. I'm hoping this is a documentation issue it seems likely that it could be a bug.

**Comment by TheCoolRob** [comment]
Thanks for the response. I was getting acquainted with the new functionality that you've been building up on the SAT side so I was simply testing basic functions and doing some performance profiling. 

I think what's perhaps a bit counter-intuitive to your audience (just based on the questions I've been seeing on the forums) is how the cp_model relates to SAT. So when you say "support static heuristics in the cp_model" - do you actually mean using the grammar of the cp framework you can access certain heuristics into a SAT model?

If this is the case, that would then answer my question on how to add heuristics into the SAT layer. I know this is very rude of me to ask, but perhaps a diagram explaining how the pieces of or-tools are currently related to one another, with the objects that are being used to switch between projections, might be a nice addition to the online introduction to or-tools?

**Comment by TheCoolRob** [comment]
Hi Laurent,
Thanks for the link and reply. I'll dig up the example I was working with at the time - I recall it just felt like an edge case that hadn't been handled (the edge case potentially being my usage too!).

But from what you're saying one should ideally steer away from using the SAT layer directly and rather go through the cp_model. I'll revert this week with a concrete example. :+1:

**Comment by lperron** [comment]
Yes, the direct SAT layer is not recommended.
The only usage we have is for very small online problems, where you have a few ms of time limit.
In that case, the setup of the cp_model API is killing you (copy, presolve, ...).

For any other usage, we recommend the cp_model API as it is simpler, and in fact faster, thanks to presolve, potential parallelism...

**Comment by lperron** [comment]
I will close this issue now.
Open a new one if you have new issues.
