### ISSUE TITLE
Can i somehow get info about time spend in route from callback?

### ISSUE THREAD

**Issue by morruth** [google/or-tools#667]
it's useful if we need to consider information about traffic situation
f. e if we have 3 locations
A , B, C (A is depot)and want to build fastest route starting at 12:00
A→B & B→A &A→C &C→A is 1 hour(always) B→C is 1 hour and C→B is 2 hour (at 12:00)
so fastest route 'll be A→B→C→A (3hour), but we know that at 13:00 begins traffic jam
and B→C then will be 3 hours, so really it'll be 5 hour, but A→C→B→A still 4 hours, so
optimal route is different

**Comment by Mizux** [comment]
I think you'll want to use [`AddDimensionDependentDimensionWithVehicleCapacity`](https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing.h#L456), which is only available on C++ currently.

So your distance function depend on a "Time" Dimension cumul var.

related to #369 #461 #480 #574
