### ISSUE TITLE
[Help Needed] Minimum number of orders

### ISSUE THREAD

**Issue by Spantouris** [google/or-tools#669]
Hello, 

I would like to make a constraint that if a vehicle is used to have at least a specific minimum number of orders done or not be used at all.

In my attempt to model this I used the below and neither worked as expected: 

`solver.AddConstraint(solver.NotMemberCt(routing.CumulVar(routing.End(v), "CompletedOrders"),list(range(1, vehicles[v]["MinimumNumberOfOrders"]))))`

or this:

`routing.CumulVar(routing.End(v), "CompletedOrders").RemoveValues(list(range(1, vehicles[v]["MinimumNumberOfOrders"])))`

CompletedOrders is a Dimension that calculates the orders a vehicle makes.

Any idea is appreciated. 

Thanks in advance,
John

**Comment by Lagousis** [comment]
I have the same problem, have you found any solutions?
