### ISSUE TITLE
install from source unix: missing wget and git dependencies

### ISSUE THREAD

**Issue by sandrotosi** [google/or-tools#675]
Hello,
at https://developers.google.com/optimization/introduction/installing/source there is a list of dependencies to install:

`sudo apt-get -y install git build-essential cmake autoconf libtool zlib1g-dev lsb-release`

but also `wget` and `git` are required, to be able to successfully run `make third_party`

can you please update the doc? thanks

**Comment by Mizux** [comment]
git is in the list for wget I should check...

**Comment by sandrotosi** [comment]
gaah you're right about `git`, i thought there was nothing else before `build-essential` on that line, guess i was wrong :)

**Comment by sandrotosi** [comment]
hehe i see, i'm working on Debian, so we dont really use `ubuntu-dev-tools`, so adding explicitly the dependency on `wget` would be useful i think
