### ISSUE TITLE
make clean doesnt clean all artifacts

### ISSUE THREAD

**Issue by sandrotosi** [google/or-tools#676]
Hello,
after running a built, it looks like `make clean` misses to clean some artifacts like:

* `dependencies/sources/`
* `dependencies/install/`
* `dependencies/archives/`
* `*.pyc` files as generated by running tests via `make test`

**Comment by Mizux** [comment]
Well fore dependencies this is intended please use `make clean_third_party`

for *.pyc, I should take a look.

Thanks for the feedback !

**Comment by sandrotosi** [comment]
oh the doc didnt mention to use `make clearn_third_party` (while it's explicitly required to use `make third_party`) - should that target be a dependency of `clean` so that it will be run everytime (i imagine is a no-op if nobody ran `make third_party`?)

**Comment by Mizux** [comment]
`make third_party` imply **downloading** and rebuilding all dependencies (usually you use package on host system) while `clean` only remove compilation files of or-tools.

And the use case is people are (want to) working on or-tools source code not dependencies. so first you `make third_party` "once in you life" then multiple iterations of make/test/clean of OR-Tools. At least this has been intended

**Comment by sandrotosi** [comment]
oh, i see what you mean - thanks for the explanation!
