### ISSUE TITLE
libprotobuf ERROR protocol message too big in school_scheduling_sat

### ISSUE THREAD

**Issue by Motorrat** [google/or-tools#677]
While testing the scalability of an essentially this particular example  https://github.com/google/or-tools/blob/e452a83dc40b02b2cc93117ea5b94dd38cec278d/examples/python/school_scheduling_sat.py#L171

I get this error message:

`[libprotobuf ERROR /root/src/dependencies/sources/protobuf-3.5.1/src/google/protobuf/io/coded_stream.cc:207] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
`
there are 1836000 cells in my assignment matrix of 6x17x40x30x15 (75 rows in the original data list)
and it have successfully run through with 1332000 cells (from 62 rows)

Is this expected? What should I do?

**Comment by Motorrat** [comment]
found this https://stackoverflow.com/questions/13849434/how-to-change-the-buffer-limit-in-googles-protobuf

**Comment by billzhong** [comment]
Google increased protobuf's limit from 64MB to 2GB since version 3.2. So I am not sure changing protobuf's source code and recompile will work. Any one has a working workaround about this issue? Appreciate it.

**Comment by lperron** [comment]
I just ran it and it is fine.
I am closing this issue. Do not hesitate to reopen it if the problem still occurs.

**Comment by aggresss** [comment]
strip -g libprotobuf.a 
will strip debug section in static library. after strip only 5MB.
