### ISSUE TITLE
Protobuf version problem with Python when using tensorflow==1.5.0

### ISSUE THREAD

**Issue by neykov** [google/or-tools#681]
Related to https://github.com/google/or-tools/issues/620

On MacOS after upgrading to ortools v6.7.1 I get the following error:
```
[libprotobuf FATAL external/protobuf_archive/src/google/protobuf/stubs/common.cc:68] This program requires version 3.5.0 of the Protocol Buffer runtime library, but the installed version is 3.4.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "ortools/gen/ortools/data/rcpsp.pb.cc".)
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: This program requires version 3.5.0 of the Protocol Buffer runtime library, but the installed version is 3.4.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "ortools/gen/ortools/data/rcpsp.pb.cc".)
```

I can reproduce this on multiple machines with cleanly installed environment. There is no system install of the protobuf library.

```
> pip show ortools
Name: ortools
Version: 6.7.4973
Summary: Google OR-Tools python libraries and modules
Home-page: https://developers.google.com/optimization/
Author: Google Inc
Author-email: lperron@google.com
License: Apache 2.0
Location: /Users/svet/.pyenv/versions/3.5.3/envs/tests/lib/python3.5/site-packages
Requires: protobuf, six

> pip show protobuf
Name: protobuf
Version: 3.5.2.post1
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: 3-Clause BSD License
Location: /Users/svet/.pyenv/versions/3.5.3/envs/tests/lib/python3.5/site-packages
Requires: six, setuptools
Required-by: tensorflow, tensorflow-tensorboard, ortools
```

After building and installing the package locally (as documented in the previous issue) the problem goes away.

**Comment by neykov** [comment]
Some more info:
```
> otool -L libortools.dylib 
libortools.dylib:
	/Users/corentinl/work/or-tools/lib/libortools.dylib (compatibility version 6.7.0, current version 6.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
```

Any idea why this shows version `6.7.0`?

**Comment by Mizux** [comment]
Hi, usually we use the git rev-list as minor (i.e. 4973) unfortunately on MacOS max allowed number is 255 so we force it to 0 on mac (i.e. don't care of it in libortools.dylib).

Also we build ortools with static dependencies in order to ship a standalone python package that's why libortools has "no" dependencies...

**Comment by Mizux** [comment]
@neykov to be sure are you working with official pypi packages on MacOS ?

Can you confirm that `brew info protobuf` return `Not installed` ?

**Comment by neykov** [comment]
> Are you working with official pypi packages on MacOS ?

Yes.

> Can you confirm that brew info protobuf return Not installed ?

```
$ brew info protobuf
protobuf: stable 3.5.1 (bottled), HEAD
Protocol buffers (Google's data interchange format)
https://github.com/google/protobuf/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/protobuf.rb
==> Dependencies
Build: autoconf ✔, automake ✘, libtool ✔
Optional: python ✘
==> Options
--with-python
	Build with python support
--with-test
	Run build-time check
--without-python@2
	Build without python2 support
--HEAD
	Install HEAD version
==> Caveats
Editor support and examples have been installed to:
  /usr/local/Cellar/protobuf/3.5.1_1/share/doc/protobuf
```

Since `libortools.dylib` is static, it seems that it has been built using 3.5.0 protobuf headers, but then linked to a 3.4.0 protobuf library. Also a local rebuild fixes it because it gets linked to the correct library version.

**Comment by Mizux** [comment]
Hi sorry for the delay,
Do you have a not working example which fail ?
I can't reproduce it on my MacOS...

Once you pip install he or-tools package, does this command work for you ?
```sh
cd <or-tools_DIR>/examples/python
python rcpsp_sat.py
python rcpsp_sat.py --input ../data/rcpsp/single_mode/j12010_10.sm
```

**Comment by neykov** [comment]
Thanks for getting back.
Running the `rcpsp_sat.py` example works for me as well.

I was able to reproduce the crash with a minimal test case (in a clean env):
```
pip install tensorflow==1.5.0
pip install -U ortools

$ python <<EOF
> import tensorflow.python
> import ortools.linear_solver.pywraplp
> EOF
```

Installing tensorflow-1.6.0 makes the problem go away (dependent libraries stay at the same versions).

Not sure what to think of it. Obviously tensorflow influences ortools library loading in some way, but it's not clear how to me.

**Comment by Mizux** [comment]
I would say tensorflow also dlopen() protobuf so python instance has an other protobuf version and everything start to blow up...

I need to verify my assertion by looking at requirement of tensorflow==1.5.0 or if it already embed protobuf as static library...

**Comment by Mizux** [comment]
Bonus this won't work because lib is a .so instead of .dylib which is mandatory since python interpreter load `.so` even on mac :( (hard coded) 
```
DYLD_INSERT_LIBRARIES=venv/lib/python2.7/site-packages/ortools/linear_solver/_pywraplp.so venv/bin/python <<EOF
import tensorflow.python
import ortools.linear_solver.pywraplp
EOF
```

**Comment by neykov** [comment]
I'm ok to close this. I still don't have a good explanation why rebuilding ortools locally fixes the problem, but I don't think it's worth the trouble investigating.

**Comment by neykov** [comment]
After hitting a symbol conflict with ortools and another library again (on MacOS), here's a solution that fixes it in a general way:

```
flags = sys.getdlopenflags()
sys.setdlopenflags(flags | ctypes.RTLD_LOCAL)
```
