### ISSUE TITLE
How to exclude some edges/arcs

### ISSUE THREAD

**Issue by tatadyj** [google/or-tools#688]
Hi all, 
I am using OR-Tools to solve multi-depot VRP problem. For my case, one important constraint is that some depot can only service some of the customers and there are also overlap between those depots' service coverage. For example, I have A, B, C three depots and a, b, c, d four customers
A can serve {a, b}
B can serve {a, b, c}
C can serve {a, b, c, d}

My understanding is that it is can be treated as an incomplete graph, essentially making some depot, customer pair distance infinity as discussed here:
https://acrogenesis.com/or-tools/documentation/user_manual/manual/tsp/first_tsp_implementation.html#tsp-avoid-some-edges

But how to use the forbidden edges constraints in python? Or is there other way to implement this constraint?

One another possible way that I can thinking of is to add a new dimension. However I notice the dimension constraint puts a upper bound on the cumulative Var rather the transit Var. Does anyone know how to put a upper bound on Transit Var in the new dimension. 

Thanks a lot

YD

**Comment by lperron** [comment]
I would use one dimension for c and one for d with capacity 1. 
Depot B consumes the one for d.
Depot C consumes both dimensions for c and d.
