### ISSUE TITLE
Initial solution ignored

### ISSUE THREAD

**Issue by fonsecadeline** [google/or-tools#693]
Hi, 

I am trying to solve a CVRP with constraint programming while providing an initial solution.

In some cases resolution starts with my initial solution (CheckAssignment returns _true_ ) but immediately returns no solution (status = ROUTING_FAIL) even though my time limit is set to 2000000 ms.

What could be the reason of this (absence of) result ?

**Comment by lperron** [comment]
Are you sure the initial solution is valid w.r.t. the model ?
