### ISSUE TITLE
Python CBC MIP - is there a way to set GAP limit parameter

### ISSUE THREAD

**Issue by praveenxrao** [google/or-tools#694]
Hello,

I am trying to set the GAP limit parameter using CBC solver. I can set the Time Limit parameter using:
solver = pywraplp.Solver('Solver',
        pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING)
solver.SetTimeLimit(4000) ## set to 4 seconds

Instead of using TimeLimit, can I set a GAP limit?

Thanks

**Comment by Mizux** [comment]
Seems now a duplicate of #644
