### ISSUE TITLE
Includes bits of abseil - breaks bazel projects that already use abseil

### ISSUE THREAD

**Issue by nicolov** [google/or-tools#696]
The or-tools source tree includes some bits of abseil under the same `absl` namespace: https://github.com/google/or-tools/search?p=1&q=%22namespace+absl%22&type=&utf8=✓

Since our bazel project already includes abseil, we are violating the one definition rule and getting segfaults.

I guess a solution would be to remove the checked-in sources and use bazel to download them instead. Do you want a PR for that?

**Comment by lperron** [comment]
We are actively working on that, but the integration with abseil is complex
if you live outside bazel.

I would love a PR that protects the offending code in ortools/base and
loads abseil instead.

Something like (ortools/base/string_view.h)

#ifndef OR_TOOLS_BASE_STRING_VIEW_H_
#define OR_TOOLS_BASE_STRING_VIEW_H_

// New code
#if defined(USE_ABSEIL)
#include <absl/strings/string_view.h>  // Not sure about the exact path
# else
// Start of old code
#include <string.h>

#include <algorithm>
#include <cstddef>
#include <iosfwd>
#include <string>

namespace absl {
...
}
#endif
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by nicolov** [comment]
Thanks. I wasn't sure my version of abseil was compatible (since I was getting the segfaults in the first place), so I went ahead and ran:

```
for x in `grep -r 'absl_ortools' -l`; do sed -i '' -e 's/absl::/absl_ortools::/g' $x ; done
for x in `grep -r 'namespace absl' -l`; do sed -i '' -e 's/namespace absl/namespace absl_ortools/g' $x ; done
```

**Comment by lperron** [comment]
Good workaround :-)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
We now build with abseil.
I will close this issue.
