### ISSUE TITLE
Need help for selecting at least one item of group - Constraint Programming

### ISSUE THREAD

**Issue by nikhilsarvaiye** [google/or-tools#698]
Hi All,

I am new to Linear/Constraint Programming and have one scenario which I am trying to solve.
I have set of promotions as

Input   some promotion examples with each Promotion tactics |   |  
-- | -- | --
Promotion Id | Name | Sales | Sales Lift
1 | P1 | 1000 | 10%
1 | P1 | 2000 | 20%
1 | P1 | 1500 | 15%
2 | P2 | 3000 | 30%
2 | P2 | 4000 | 40%
2 | P2 | 5000 | 50%
3 | P3 | 2500 | 25%
3 | P3 | 4500 | 45%
3 | P3 | 6500 | 65%

Output   |   |  
-- | -- | --
Promotion Id | Name | Sales | Sales Lift
1 | P1 | 2000 | 20%
2 | P2 | 5000 | 50%
3 | P3 | 6500 | 65%

Constraint is that, i need at least on promotion combination, as shown, P1, P2 and P3 needs to be in output.

I created below variables,

```csharp
int[][] sales =
			{
				new[] { 1000, 2000, 1500 },
				new[] { 3000, 4000, 5000 },
				new[] { 2500, 4500, 6500 }
			};
string[] promotions = { "P1", "P2", "P3" };

var allSales = sales.Select(
	forecastedSale => forecastedSale.Select(
		value => solver.MakeIntVar(value, value, $"s{value}")).ToArray()).ToArray();

DecisionBuilder db =
	solver.MakePhase(
		allSales,
		Solver.CHOOSE_PATH,
		Solver.ASSIGN_MAX_VALUE);
solver.NewSearch(db);
```

The problem is, I always get all the sales values
like, 1000, 2000, 1500, 3000, 4000, 5000, 2500, 4500, 6500

where as i want 3 results, each from single promotion combination.

can anybody please suggest?

**Comment by pmateusz** [comment]
If I were you I would define a constraint for each group of promotions. Sum over all items in the same promotion group should be lower or equal to one.

**Comment by nikhilsarvaiye** [comment]
thnx @pmateusz for answer, however, i have created below solution,

`			var solver = new Solver("CheckHorizantal");

			// Declarations
			int[][] budget =
			{
				new[] { 4000, 5000, 6000 }, // P1 - Combinations
				new[] { 2000, 3000, 4000 }, // P2 - Combinations
				new[] { 1000, 3000, 6000 } // P3 - Combinations
			};
			int[][] salesLifts =
			{
				new[] { 40, 50, 60 }, // P1 - Combinations
				new[] { 20, 30, 40 }, // P2 - Combinations
				new[] { 10, 30, 60 } // P3 - Combinations
			};
			string[] promotions = { "P1", "P2", "P3" };
			// Decision variables
			var salesLiftVars = salesLifts.Select(value => solver.MakeIntVar(value, $"sl{value.Length}")).ToArray();
			var budgetVars = budget.Select(value => solver.MakeIntVar(value, $"s{value.Length}")).ToArray();
			var totalBudget = budgetVars.Sum().Var();

			var totalSalesLift = salesLiftVars.Sum().Var();

			// Constraints
			salesLiftVars.ToList().ForEach(var =>
											{
												var i = salesLiftVars.IndexOf(var);
// TODO: write constraint to map budget and salesLift 1:1
												// solver.Add(salesLiftVars[i] * 100 == budgetVars[i]);
											});
			solver.Add(totalBudget <= 14000);

			// Objective
			var obj = totalSalesLift.Maximize(1);

			// Search
			var vector = new IntVarVector();
			budgetVars.ToList().ForEach(var => vector.Add(var));
			salesLiftVars.ToList().ForEach(var => vector.Add(var));

			// dataVars.ToList().ForEach(var => var.ToList().ForEach(v => vector.Add(v)));

			// Decision builder
			var db = solver.MakePhase(vector, Solver.CHOOSE_PATH, Solver.ASSIGN_MAX_VALUE);

			// Search/Solve
			solver.NewSearch(db, obj);

			while (solver.NextSolution())
			{
				Console.WriteLine("Total Budget: {0}", totalBudget.Value());
				Console.WriteLine("Maximum Sales Lift: {0}", totalSalesLift.Value());
				Console.WriteLine();

				for (var i = 0; i < salesLiftVars.Length; i++)
				{
					Console.Write("For Promotion {0} Values: ", promotions[i]);
					Console.WriteLine("Lift: {0}, Sales: {1}", salesLiftVars[i].Value(), budgetVars[i].Value());
					Console.WriteLine();
				}
			}

`

I am only facing one issue, where my objective and constraint both are working but independently.
I wanted associate my salesLift to budget as one to one mapping, any help?

**Comment by lperron** [comment]
Seems like a hitting set problem.
Please refine the problem, and reopen if needed.
