### ISSUE TITLE
glog FATAL level logging exits process and causes Python program to exit as well

### ISSUE THREAD

**Issue by yingzong** [google/or-tools#699]
There are parts in the ortools library where FATAL severity errors are logged through the glog library. It turns out glog forces the calling process to exit after logging, on such errors, see:
http://rpg.ifi.uzh.ch/docs/glog.html

This is a fairly annoying pattern, especially for a library like ortools that is expected to be called by others (including Python programs). Many times the error is something like network connection failure or something that should be retried and is recoverable. I think there won't be an easy fix here but have there been thoughts on how to address this? Ideally even fatal severity errors raise exceptions so that they can be handled differently depending on the calling program (the default can be to exit, of course).

N.B.: There is also a DFATAL severity that only exits the program in debug mode but converts to ERROR severity in production. Might that be appropriate?

**Comment by lperron** [comment]
PR was merged.
Closing the issue.
