### ISSUE TITLE
Constraint Solver Random Restart Strategies

### ISSUE THREAD

**Issue by sebastianfast** [google/or-tools#702]
I would like to implement the Rapid Random Restart strategy by [Gomes et al](https://link.springer.com/article/10.1023%2FA%3A1006314320276). I am using the Python interface and saw that there is a `ConstantRestart Search Monitor` that allows for restarting the search. 

As I understand the underlying source code, when a specified number **n** of failures is reached, the search is backtracked to the root and restarted. Is this correct? I want to employ a random variable and value search strategy. Consistent with issue #291, a `constantRestart` would not reseed the search strategy. The search would use the same seed and visit the same random variables with the same random values. With a small enough **n** I could get stuck in a search tree forever. Is that correct?

Also, assuming I have randomly preset a number of variables by limiting their domains or imposing fixed constraints PRIOR to beginning search, how would I reset these when the search monitor restarts the search? Does the search monitor expose some kind of restart event that I could hook myself to in order to reseed the solver or randomly reset the preset variables?

Thanks

**Comment by lperron** [comment]
I would recommend using the CP-SAT interface, where this is build in.
What kind of problems are you trying to solve?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
No answer, closing the issue now. Please reopen if needed.
