### ISSUE TITLE
Same node for Pickup and Delivery problem causes errors (VRP)

### ISSUE THREAD

**Issue by justanothergithubber** [google/or-tools#703]
Hello Google, I love this library and hope to see it improve more and more so as to develop open source capabilities.

I am coding in Python. More specifically, I am using [Google Colab's](https://colab.research.google.com/) Python 3, which I can pip install OR-Tools with. I'm not sure if this has been raised before, or if this has already been documented (I have checked https://developers.google.com/optimization/routing/).

When using `routing.AddPickupAndDelivery`, it seems that the node used for Pickup cannot be used for Delivery as another constraint. For example, given nodes 0,1,2,3,4,5,6 and constraints 0→1, 1→2, 3→4, 4→5, 5→6 with the obvious solution 0→1→2→3→4→5→6, it seems that OR-Tools will return No Solution. 

To resolve this, I have created duplicates for the set of Pickups and the set of Deliveries, but this comes at a memory cost I believe, as I would have a bigger distance matrix. I am not sure if the cost increase will be significant as I am planning to increase the scale of the problems. It would be best if the model allows for nodes to be both a pickup and a delivery point.

**Comment by Mizux** [comment]
Need to double check but i don't think it is forbidden by the solver cf https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing.h#L590 ...
Do you have a snippet code ?

**Comment by justanothergithubber** [comment]
I will add this
```
routing.solver().Add(routing.VehicleVar(1) == routing.VehicleVar(2))
```
when I am generalising my code to MVRP (M for multiple), when I am solving for multiple vehicles. Currently I'm not too sure how my team will develop the project further, as we are looking at sub-minute solutions, so I am not sure how much the computer can compute within that time.

Adding the `search_parameters.first_solution_strategy = ( routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)` helped a lot, I am getting a solution when giving 5000ms as the time parameter. It does seem that the first solution (to begin the local search, I assume) was not found in the previous case.

Thank you a lot for your help!
I am closing this issue as there seems to be no issue.

**Comment by Mizux** [comment]
ERRATUM:  For writing a Pickup&Delivery you need **three** statements

* addPickupDelivery() # solver use this hint internally
* add the precedence constraint # my bad thinking it was done by the previous method
* add the vehicle(loc_A) == vehicle(loc_B) constraint

e.g.
```python
routing.AddPickupAndDelivery(1, 2)
routing.solver().Add(routing.CumulVar(1) < routing.CumulVar(2))
routing.solver().Add(routing.VehicleVar(1) == routing.VehicleVar(2))
```

**Comment by Deruijter** [comment]
I'd like to reiterate that for this specific problem, `FirstSolutionStrategy.PARALLEL_CHEAPEST_INSERTION` won't find a solution while `FirstSolutionStrategy.PATH_CHEAPEST_ARC` will. 

It's unfortunate because PARALLEL_CHEAPEST_INSERTION seems to be a lot faster.

**Comment by LCDMMartin** [comment]
Hello,
Sorry to reopen an old post but I have the same issue, with version 8.2 except that changing first solution strategy to PATH_CHEAPEST_ARC does not solve the problem, I have a "Process finished with exit code -1073741819 (0xC0000005)" output

I am using the same code as https://developers.google.com/optimization/routing/pickup_delivery
with the following simplified data function:
`def create_data_model():
    """Stores the data for the problem."""
    data = {}
    data['distance_matrix'] = [[0, 11, 0, 13, 20, 11],
                               [11, 0, 11, 5, 11, 0],
                               [0, 11, 0, 13, 20, 11],
                               [13, 5, 13, 0, 11, 4],
                               [20, 11, 20, 11, 0, 10],
                               [11, 0, 11, 4, 10, 0]]
    data['pickups_deliveries'] = [
        [2, 3],
        [2, 4],
        [4, 5]
    ]
    data['num_vehicles'] = 1
    data['depot'] = 0
    return data`

**Comment by LCDMMartin** [comment]
Thanks for you very quick answer.
That is exactly what I did and it works, except on biggest datasets I use (too many duplicates makes the problem harder). As I did not find it explicitly forbidden in the documentation, I was wondering if maybe it was a bug or even if the feature is plan ?

**Comment by lperron** [comment]
One node can only be visited once and only one action can be performed at a
node.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mar. 15 juin 2021 à 18:06, LCDMMartin ***@***.***> a
écrit :

**Comment by LCDMMartin** [comment]
noted, thank you
