### ISSUE TITLE
Capacitated Vehicle Routing Problem with variable maximum capacity

### ISSUE THREAD

**Issue by MidnightP** [google/or-tools#704]
Hi there! I'm very happy with OR-tools and I would in a later stage be glad to share the resulting webapp here! I have one question that keeps troubling me and hoped someone could answer it or assist.

So far it looks like OR-tools can only assign one maximum capacity to a vehicle routing problem as a whole, as can be read here: https://developers.google.com/optimization/routing/cvrp

```
routing.AddDimension(
        demand_evaluator,
        0, # null capacity slack
        data.vehicle.capacity, # vehicle maximum capacity
        True, # start cumul to zero
        capacity)
```

I wish to solve a problem with a variable max capacity. Since a fleet of vehicles do not always have the same size, this seems to be a very relevant feature. I couldn't find any issue about this so opening this one.

Is it possible to accomplish a variable capacity? If yes, how? If meh, is there a known workaround or will it be a feature in the future?

**Comment by mjfwest** [comment]
Do you mean a fleet of vehicles with different maximum capacities, or a fleet of vehicles that get smaller and larger during the route?
The first one is easy as shown here https://github.com/google/or-tools/blob/master/examples/python/cvrptw_plot.py#L603

**Comment by MidnightP** [comment]
And then use it in the function ```AddDimensionWithVehicleCapacity``` as seen on line 662:

```
routing.AddDimensionWithVehicleCapacity(dem_fn,  # demand callback
                                            null_capacity_slack,
                                            capacity,  # capacity array
                                            True,
                                            "Capacity")
```

Looks like that's it indeed; "a fleet of vehicles with different maximum capacities".
