### ISSUE TITLE
How can I combine pickup|delivery and delivery from/to depot with capacity?

### ISSUE THREAD

**Issue by morruth** [google/or-tools#707]
if I have only pickup/delivery i can just make demands >0(parcel weight) in pickup points and < 0(-weight) in delivery points
if i'm pickup all from depot and delivery to different points (or vice versa), im just set demands to parcel weigth
But what should I do if i need to combine this approaches?
(get some parcels from depot, deliver some to make free space, pickup some on the way and deliver all which left)

**Comment by Mizux** [comment]
Well you can:
- create a dimension which return negative "capacity" at delivery point and positive "capacity" aka load at pickup.
- Add pickup and delivery constraints

You could see it like the refuel example in c++ https://github.com/google/or-tools/blob/master/examples/cpp/cvrptw_with_refueling.cc

**Comment by morruth** [comment]
>create a dimension which return negative "capacity" at delivery point and positive "capacity" aka load at pickup.

Is it the same as i wrote?
«i can just make demands >0(parcel weight) in pickup points and < 0(-weight) in delivery points»

>Also add a slackvar at "depot" and "refill station node" and set slack to zero otherwise...
Where can I read about the purpose of slackvar? (what is it and how it used, i'm not understand it)

**Comment by Mizux** [comment]
Well, [slack variable](https://en.wikipedia.org/wiki/Slack_variable) definition is not so helping here.
In routing, constraint between two consecutive nodes are as follow:  
`if j == next(i), cumul(j) = cumul(i) + transit(i) + slack(i)`
cf https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing.h#L385

Example: Time dimension, slack var could be seen as a waiting time to be on time for the next node.
cf question https://stackoverflow.com/questions/50483447/definition-of-slack-variable-in-time-window-routing

In the fuel example. each transit is negative i.e. you consume oil along the edge. So here you see non zero slack node like a "gas station" which can refill the vehicle fuel capacity.

In your problem I'm just thinking of using slack variable at depot to simulate extra parcel you can grab.
Pickup and delivery is just here to force precedence between nodes (don't forget the constraint on vehicle also cf #703 i.e. routing.solver().Add(routing.VehicleVar(P) == routing.VehicleVar(D)) which is not enforced by the PickAndDelivery constraint).

Your question seems to be close to #659...

**Comment by Mizux** [comment]
For SlackVar take a look at #1051

**Comment by Mizux** [comment]
For the record to manage independent pickup and delivery you may use two dimensions:
* one to track the deliveries only load/unload (don't start at zero, at delivery: -1, at pickup: nothing)
* one to track the vehicle total load/unload (don't start at zero, at delivery: -1, at pickup: +1)

note: add constraint so both dimensions start with the same value
```python
for i in range(data['num_vehicles']):
  index = routing.Start(i)
  routing.solver().Add(delivery_dimension.CumulVar(index) == capacity_dimension.CumulVar(index))
```

example: https://gist.github.com/Mizux/5617f65a7be19449fa475cf04b45e50a#file-abhik-py-L282-L289
