### ISSUE TITLE
Endless loop when calling AddDimensionDependentDimensionWithVehicleCapacity

### ISSUE THREAD

**Issue by chliul** [google/or-tools#713]
I'm doing some experiments for the dependent dimension, and I change the code in example prptw.cc trying to make a  dependent dimension which works similar to demand dimension.
And here is what I wrote:
```cpp
RoutingModel::StateDependentTransit ClientWaitTime(
  RoutingModel::NodeIndex from,
  RoutingModel::NodeIndex to) {
    std::function<int64(int64)> transit = [](int64 load)->int64 {
         return 1;
    };
    return RoutingModel::MakeStateDependentTransit(transit, 0, 100);
}
```
Add dependent dimension:
```cpp
const RoutingDimension& demand_dimension = routing.GetDimensionOrDie("demand");
routing.AddDimensionDependentDimensionWithVehicleCapacity(
    NewPermanentCallback(&ClientWaitTime),
    &demand_dimension,
    0, 100, true, "load");
```
These Code compile and build successfully but then fall into endless loop. Is there an example for dependent dimension usage, or any suggestion on what I did wrong?
Thank you!

**Comment by Mizux** [comment]
Are you sure your data problem as an easy First Solution ?
Sometime solver can take time to find the first one...

I'll try to reproduce it...

**Comment by chliul** [comment]
After I reduce the problem size, and set routing_solution_limit 1, I got one solution about five minutes, which is 10s before I add this dimension. But after all, it's not an endless loop, I will try to see if I can reduce some time.
Thank you for your help!
