### ISSUE TITLE
Depot with time windows

### ISSUE THREAD

**Issue by bertop89** [google/or-tools#714]
I took the CVRPTW example and tried to implement time window constraints for the depot. For that, I commented the `customers.zero_depot_demands(depot)` so that it doesn't set the `tw_close` and `tw_open` to `None` for the depot. This code:

> `time_dimension.CumulVar(routing.NodeToIndex(cust.index)).SetRange(
                cust.tw_open.seconds,
                cust.tw_close.seconds)`

should do the trick, but still time windows for the depot are not respected. Any ideas?

**Comment by Mizux** [comment]
You must set the time window for each start node of each vehicle using
vehicle (idx).start()

Le jeu. 7 juin 2018 à 18:23, Alberto Polidura <notifications@github.com> a
écrit :

**Comment by bertop89** [comment]
Thank you very much @Mizux , I have managed to implement it successfully with:

`start_index = routing.Start(int(veh.index))`
`time_dimension.CumulVar(start_index).SetRange(0, 82800)`

However, the moment I increase the left time window interval to something other than 0, the solver crashes with the following error:

~/.local/lib/python3.6/site-packages/ortools/constraint_solver/pywrapcp.py in SetRange(self, l, u)
   1337 
   1338     def SetRange(self, l: 'int64', u: 'int64') -> "void":
-> 1339         return _pywrapcp.IntExpr_SetRange(self, l, u)
   1340 
   1341     def SetValue(self, v: 'int64') -> "void":

Exception: CP Solver

Any ideas?

**Comment by Mizux** [comment]
You must set the time window for each start node of each vehicle using:
```python
for vehicle_id in xrange(num_vehicles):
 index = routing.Start(vehicle_id)
 dimension.CumulVar(index).SetRange(min, max)
```
src: https://github.com/google/or-tools/blob/master/examples/python/cvrptw.py#L263

Also verify you are not setting `set_cumulvar_to_zero` (i.e. set to `false`) when creating your dimension...

EDIT: rework my answer once a get  desktop instead of my email reply

**Comment by bertop89** [comment]
Thank you @Mizux , that solved the issue! Congratulations on the nice work with the library.
