### ISSUE TITLE
Handle exceptions from C++ via SWIG to Java

### ISSUE THREAD

**Issue by orwant** [google/or-tools#72]
Originally reported on Google Code with ID 56

```
Using Ortools Java on OS X.  Exception from C++ simply crashes the JVM with core dump.
 It's very desirable for Java code to be able to catch exceptions from C++ code.  


Can we add exception handling (re-throwing C++ exception as Java exception) in SWIG?
 If would sufficient to simply re-throw as Java RuntimeException.

http://www.swig.org/Doc3.0/SWIGDocumentation.html#SWIGPlus_exception_specifications
```

Reported by `yunjun.mu` on 2014-11-14 15:47:11

clickable url: http://www.swig.org/Doc3.0/SWIGDocumentation.html#SWIGPlus_exception_specifications

**Comment by nklein-1** [comment]
Is there currently a work around to handle exceptions?  I have run into a few occasions where the JVM crashes in a production environment causing that server to be unavailable until it is restarted.  It would be very helpful to be able to catch these exceptions and report them without bringing down the entire JVM.

**Comment by lperron** [comment]
I do not know how to do it.
In swig, you need to know which exception are going to be thrown, but or-tools does not use exceptions, thus it does not throw any.
