### ISSUE TITLE
Trying to work CVRP with single vehicle (num_vehicles = 1)

### ISSUE THREAD

**Issue by lucasmengual92** [google/or-tools#721]
I´m doing the Capacitated Vehicle Routing Problem, with my modifications. Using API to get distances from coordinates, and printing out the RoutingModel, also with slight modifications to print out the correct total distance and will do total duration soon too.

But the problem I´m having is that when I set to `num_vehicles = 1` it doesn´t let me print out. so, I´m stuck trying to find that out, I´m guessing it has something to do with the heuristic solution only accepts 2 or more vehicles. But my ideal problem is to have just one vehicle (salesman) but giving the shortes/quickest route based on the demand weight in the nodes.

You can download the .csv I´m using [here](https://drive.google.com/open?id=1iRXM6LHjOloo5PiMBxfo9eZGm3cNzFI4). And would only need to add your own Google API key in the Callback class().

Here´s the code I´ve got so far...

**Comment by lucasmengual92** [comment]
'''
Created on 13 jun. 2018

@author: trlume
'''
 
from ortools.constraint_solver import pywrapcp
from ortools.constraint_solver import routing_enums_pb2
import googlemaps
from datetime import datetime
import csv
import numpy as np
import pandas as pd
import math
import random
from __builtin__ import str
from googlemaps.distance_matrix import distance_matrix

parquimetros_test = pd.read_csv('parquimetros_test.csv', sep = ';')
parquimetros_test = pd.DataFrame(parquimetros_test)
#parquimetros_test = parquimetros_test.sample(n=5) #Using only 5 parkingmeters at random
parquimetros_test = parquimetros_test[(parquimetros_test.Freguesia == 'Avenidas Novas') | (parquimetros_test.Freguesia == 'Estrela')]
#Lista con los IDs/Nombres:
names_parquimetros = parquimetros_test['Parcometro'].tolist()
names_parquimetros.insert(0,'salesman')
#long_lat_parquimetros = np.column_stack((parquimetros_test['Latitude'],parquimetros_test['Longitude']))
#long_lat_parquimetros=[[round(float(lon_lat[0].replace(',','.')),2), round(float(lon_lat[1].replace(',','.')),2)] for lon_lat in long_lat_parquimetros]
#lat_long_parquimetros = np.column_stack((parquimetros_test['Coor_Lat'],parquimetros_test['Coor_Long']))
lat_long_parquimetros = parquimetros_test[['Coor_Lat','Coor_Long']]
#long_lat_parquimetros = long_lat_parquimetros[[1,0]]
#print(names_parquimetros)
#Random salesman coordinates generation:
salesman = pd.DataFrame([[38.75,-9.1]], columns= ('Coor_Lat','Coor_Long'))
#salesman = pd.DataFrame([[random.uniform(38.7, 38.8),random.uniform(-9.2, -9.0)]], columns= ('Coor_Lat','Coor_Long'))
lat_long_parquimetros = salesman.append(lat_long_parquimetros, ignore_index=True)
lat_long_parquimetros = np.column_stack((lat_long_parquimetros['Coor_Lat'],lat_long_parquimetros['Coor_Long']))
#print(lat_long_parquimetros)
#Lista con los Demands/Pesos de cada nodo/parquimetro:
salesman_depot = 0
demand_parquimetros = parquimetros_test['Demand'].tolist()
demand_parquimetros = map(int, demand_parquimetros)
demand_parquimetros = [salesman_depot] + demand_parquimetros

class Vehicle():
    """Stores the property of a vehicle"""
    def __init__(self):
        """Initializes the vehicle properties"""
        self._capacity = 10
        # Travel speed: 5km/h to convert in m/min
        #self._speed = 5 * 60 / 3.6

    @property
    def capacity(self):
        """Gets vehicle capacity"""
        return self._capacity

    #@property
    #def speed(self):
        #"""Gets the average travel speed of a vehicle"""
    #    return self._speed

###NO SE UTILIZA###
class CityBlock():
    #City block definition
    @property
    def width(self):
        #Gets Block size West to East
        return 228/2

    @property
    def height(self):
        #Gets Block size North to South
        return 80 
   
class DataProblem():
    """Stores the data for the problem"""
    def __init__(self):
        """Initializes the data for the problem"""
        self._vehicle = Vehicle()
        self._num_vehicles = 1
        
        # Locations in block unit
        locations = lat_long_parquimetros
        """\
                [(4, 4), # depot
                 (2, 0), (8, 0), # row 0
                 (0, 1), (1, 1),
                 (5, 2), (7, 2),
                 (3, 3), (6, 3),
                 (5, 5), (8, 5),
                 (1, 6), (2, 6),
                 (3, 7), (6, 7),
                 (0, 8), (7, 8)]
                 
        # locations in meters using the city block dimension
        city_block = CityBlock()
        self._locations = [(
            loc[0]*city_block.width,
            loc[1]*city_block.height) for loc in locations]
        """
        self._locations = locations
        self._depot = 0

        #Iniciar los pesos/demands de los nodos -> 0 = nodo salesman
        self._demands = demand_parquimetros
            
    @property
    def vehicle(self):
        """Gets a vehicle"""
        return self._vehicle

    @property
    def num_vehicles(self):
        """Gets number of vehicles"""
        return self._num_vehicles

    @property
    def locations(self):
        """Gets locations"""
        return self._locations

    @property
    def num_locations(self):
        """Gets number of locations"""
        return len(self.locations)

    @property
    def depot(self):
        """Gets depot location index"""
        return self._depot

    @property
    def demands(self):
        """Gets demands at each location"""
        return self._demands

#####################
#Problem Constraints#
#####################
###NO SE UTILIZA###
def manhattan_distance(position_1, position_2):
    """Computes the Manhattan distance between two points"""
    return (abs(position_1[0] - position_2[0]) +
            abs(position_1[1] - position_2[1]))

def distance_api(lat1, long1, lat2, long2):
    
    gmaps = googlemaps.Client(key='XXXX')
    
    now = datetime.now()
    directions_result = gmaps.directions((str(lat1),str(long1)),
                                         (str(lat2),str(long2)),
                                         mode="driving",
                                         avoid="ferries",
                                         departure_time=now
                                         )
    
    distance = directions_result[0]['legs'][0]['distance']['value']/1000.0 #Distance A-B in kilometers
    time = directions_result[0]['legs'][0]['duration']['value']/60.0 #Time between A-B in minutes    
    return distance, time

###NO SE UTILIZA###   
class CreateDistanceEvaluator(object): # pylint: disable=too-few-public-methods
    """Creates callback to return distance between points."""
    def __init__(self, data):
        """Initializes the distance matrix."""
        self._distances = {}

        # precompute distance between location to have distance callback in O(1)
        for from_node in xrange(data.num_locations):
            self._distances[from_node] = {}
            for to_node in xrange(data.num_locations):
                if from_node == to_node:
                    self._distances[from_node][to_node] = 0
                else:
                    self._distances[from_node][to_node] = (
                        manhattan_distance(
                            data.locations[from_node],
                            data.locations[to_node]))

    def distance_evaluator(self, from_node, to_node):
        """Returns the manhattan distance between the two nodes"""
        return self._distances[from_node][to_node]

#Distance and Time Callback
class CreateCallback(object):
    """Create callback to calculate distances between points."""

    def __init__(self):
        
    # Latitudes and longitudes of selected EMEL parkingmeters
        locations = lat_long_parquimetros

        """Create the distance matrix."""
        size = len(locations)
        self.distance_matrix = {}
        self.time_matrix = {}

        for from_node in xrange(size):
            self.distance_matrix[from_node] = {}
            self.time_matrix[from_node] = {}
            
            for to_node in xrange(size):
                if from_node == to_node:
                    self.distance_matrix[from_node][to_node] = 0
                    self.time_matrix[from_node][to_node] = 0
                else:             
                    x1 = locations[from_node][0]
                    y1 = locations[from_node][1]
                    x2 = locations[to_node][0]
                    y2 = locations[to_node][1]
                    self.distance_matrix[from_node][to_node], self.time_matrix[from_node][to_node]  = distance_api(x1, y1, x2, y2)
    
    #Calling distance from_node-TO-to_node
    def Distance(self, from_node, to_node):
        return int(self.distance_matrix[from_node][to_node])
    
    #Calling time from_node-TO-to_node
    def Time(self, from_node, to_node):
        return int(self.time_matrix[from_node][to_node])

class CreateDemandEvaluator(object): # pylint: disable=too-few-public-methods
    """Creates callback to get demands at each location."""
    def __init__(self, data):
        """Initializes the demand array."""
        self._demands = data.demands

    def demand_evaluator(self, from_node, to_node):
        """Returns the demand of the current node"""
        del to_node
        return self._demands[from_node]

def add_capacity_constraints(routing, data, demand_evaluator):
    """Adds capacity constraint"""
    capacity = "Capacity"
    routing.AddDimension(
        demand_evaluator,
        0, # null capacity slack
        data.vehicle.capacity, # vehicle maximum capacity
        True, # start cumul to zero
        capacity)

#########
#Printer#
#########
class ConsolePrinter():
    """Print solution to console"""
    def __init__(self, data, routing, assignment):
        """Initializes the printer"""
        self._data = data
        self._routing = routing
        self._assignment = assignment

    @property
    def data(self):
        """Gets problem data"""
        return self._data

    @property
    def routing(self):
        """Gets routing model"""
        return self._routing

    @property
    def assignment(self):
        """Gets routing model"""
        return self._assignment


    def imprimir(self, distance_matrix):
        """Prints assignment on console"""
        # Inspect solution.
        total_dist = 0
        for vehicle_id in xrange(self.data.num_vehicles):
            index = self.routing.Start(vehicle_id)
            plan_output = 'Route for vehicle {0}:\n'.format(vehicle_id)
            route_dist = 0
            route_load = 0
            while not self.routing.IsEnd(index):
                node_index = self.routing.IndexToNode(index)
                next_node_index = self.routing.IndexToNode(
                    self.assignment.Value(self.routing.NextVar(index)))
                route_dist += distance_matrix[node_index][next_node_index]
                """route_dist += distance_api(
                    self.data.locations[node_index][0],
                    self.data.locations[node_index][1],
                    self.data.locations[next_node_index][0],
                    self.data.locations[next_node_index][1])[0]"""
                route_load += self.data.demands[node_index]
                plan_output += ' {0} Load({1}) -> '.format(node_index, route_load)
                index = self.assignment.Value(self.routing.NextVar(index))

            node_index = self.routing.IndexToNode(index)
            total_dist += route_dist
            plan_output += ' {0} Load({1})\n'.format(node_index, route_load)
            plan_output += 'Distance of the route: {0}km\n'.format(route_dist)
            plan_output += 'Load of the route: {0}\n'.format(route_load)
            print(plan_output)
        print('Total Distance of all routes: {0}m'.format(total_dist))

######
#Main#
######
def main():
    """Entry point of the program"""
    # Instantiate the data problem.
    data = DataProblem()

    # Create Routing Model
    routing = pywrapcp.RoutingModel(data.num_locations, data.num_vehicles, data.depot)
    
    # Create the distance/time callback, which takes two arguments (the from and to node indices)
    # and returns the distance or time between these nodes.
    dist_time_between_nodes = CreateCallback()
    dist_time_callback = dist_time_between_nodes.Distance #dist_between_nodes.Time 
    routing.SetArcCostEvaluatorOfAllVehicles(dist_time_callback)
    #distance_evaluator = CreateCallback(data).Distance
    #routing.SetArcCostEvaluatorOfAllVehicles(distance_evaluator)
    
    # Add Capacity constraint
    demand_evaluator = CreateDemandEvaluator(data).demand_evaluator
    add_capacity_constraints(routing, data, demand_evaluator)

    # Setting first solution heuristic (cheapest addition).
    search_parameters = pywrapcp.RoutingModel.DefaultSearchParameters()
    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)
    # Solve the problem.
    assignment = routing.SolveWithParameters(search_parameters)
    printer = ConsolePrinter(data, routing, assignment)
    printer.imprimir(dist_time_between_nodes.distance_matrix)

if __name__ == '__main__':
  main()

**Comment by Mizux** [comment]
Can you post the output of the program ?

**Comment by lucasmengual92** [comment]
With self._num_vehicle = 2 #or more

Route for vehicle 0:
 0 Load(0) ->  2 Load(3) ->  1 Load(5) ->  0 Load(5)
Distance of the route: 15.954km
Load of the route: 5

Route for vehicle 1:
 0 Load(0) ->  3 Load(4) ->  5 Load(7) ->  4 Load(8) ->  0 Load(8)
Distance of the route: 23.785km
Load of the route: 8

Total Distance of all routes: 39.739m

BUT with self._num_vehicle = 1

self.assignment.Value(self.routing.NextVar(index)))
AttributeError: 'NoneType' object has no attribute 'Value'

**Comment by lucasmengual92** [comment]
That's what I'm not entirely sure. I jumped from the TSP > CVRP method because I needed to find the shortest route based on completing the capacity. Is there any way to do the same as CVRP but with a single vehicle? Or giving a specific capacity per vehicle (i.e giving = 0 to that 2nd vehicle)?

**Comment by Mizux** [comment]
There are several overload for the [`AddDimension()`](https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing.h#L403) method.
You can pass a vector of capacity if each vehicle has a different capacity...

**Comment by lucasmengual92** [comment]
Been trying to do the next step, is it correct for my problem? It´s giving me an error in the 4th argument: "TypeError: in method 'RoutingModel_AddDimension', argument 4 of type 'int64'".

```
routing.AddDimension(
        demand_evaluator,
        0, # null capacity slack
        [int64(10), int64(0)], # vehicle maximum capacity
        True, # start cumul to zero
        capacity)
```

**Comment by lucasmengual92** [comment]
Finally got to solve it, incase anyone is wondering...
I realised that it was giving me an error because the total demand was higher than vehicle´s capacity. I chnaged the capacity really high to try and work, but that wasn´t realistic. So by using AddDisjunction I could add a penalty (positive number) to each node based on their demand, like:
```
for node in xrange(data.num_locations):
        routing.AddDisjunction([node], data.penalties[node]
```
And now I started a new help [issue](https://github.com/google/or-tools/issues/726), because my next step is to use output route using gmaps.directions_layer()
