### ISSUE TITLE
Release Google.OrTools.FSharp.dll out of box?

### ISSUE THREAD

**Issue by zyzhu** [google/or-tools#722]
I have just found out about Google.OrTools yesterday. The FSharp examples are very concise to use. However Google.OrTools.FSharp.dll is not included in the released bin folder. 

Is it possible to get it directly in the release zip file and through Nuget?

**Comment by Mizux** [comment]
Hi, for the coming 6.8 we will try to add it in the binary archive.

Concerning the Nuget Package, I think it will come at little bit later, sorry for that.

**Comment by zyzhu** [comment]
That's awesome! .Net Standard 2.0 support is great! Look forward to the next release!

**Comment by Mizux** [comment]
Closing since FSharp is now shipped with the archive for release v6.8.

Please note that currently the nuget package is broken will be fixed for a 6.8.1 or 6.9 you can follow #744 for discussion on the subject ;)
