### ISSUE TITLE
Restricting vehicles max travel time

### ISSUE THREAD

**Issue by bertop89** [google/or-tools#724]
This comes from #685 , basically what I'm trying to achieve is restricting the time each of the vehicles is allowed to travel before coming back to the depot. In my case, I'd like all of them to have a `max travel time` of 12 hours.

I'm using the [/examples/python/cvrptw_plot.py](https://github.com/google/or-tools/blob/master/examples/python/cvrptw_plot.py) as template:

```python
  # Add a dimension for time and a limit on the total time_horizon
  routing.AddDimension(
      tot_time_fn,  # total time function callback
      customers.time_horizon,
      customers.time_horizon,
      True,
      'Time')

  time_dimension = routing.GetDimensionOrDie('Time')
  for cust in customers.customers:
    if cust.tw_open is not None:
      time_dimension.CumulVar(routing.NodeToIndex(cust.index)).SetRange(
          cust.tw_open.seconds, cust.tw_close.seconds)
```

As @Mizux pointed out, I should modifiy the `max travel time` parameter. However when I modify `customer.time_horizon` from 24 hours (default) to 12 hours I get the following crash:

```python
~/.local/lib/python3.6/site-packages/ortools/constraint_solver/pywrapcp.py in SetRange(self, l, u)
   1337 
   1338     def SetRange(self, l: 'int64', u: 'int64') -> "void":
-> 1339         return _pywrapcp.IntExpr_SetRange(self, l, u)
   1340 
   1341     def SetValue(self, v: 'int64') -> "void":

Exception: CP Solver fail
```

I believe the error is coming because some of the time windows begin after the end of my new time horizon (12h) which should not be related.

Is there something I'm doing wrong? Thanks in advance!

**Comment by Mizux** [comment]
What is the value of `cust.tw_open.seconds` and `cust.tw_close.seconds` ?

SetRange has a lot of check internally see https://github.com/google/or-tools/blob/master/ortools/constraint_solver/expressions.cc#L2302

**Comment by bertop89** [comment]
@Mizux the values are 54000 and 64800 respectively. The first one being later than 12h (43200 seconds).

**Comment by Mizux** [comment]
When a Dimension is created it call RoutingDimension() ctor which calls [`void RoutingDimension::InitializeCumuls()`](https://github.com/google/or-tools/blob/9487eb85f4620f93abfed64899371be88d65c6ec/ortools/constraint_solver/routing.cc#L4736) which set the `max_capacity` as `max value` of the IntVar.

And as seen previously SetRange do some check against max value...

**Comment by bertop89** [comment]
Thank you again @Mizux , I followed your advice and created a new "time duration" dimension the following way:

```python
routing.AddDimension(tot_time_fn,
                             12 * 3600,
                             12 * 3600,
                             True,
                             "Duration")

duration_dimension = routing.GetDimensionOrDie("Duration")
```

And then added the following restrictions:

```python 
dur_expr = duration_dimension.CumulVar(routing.NodeToIndex(cust.index))
routing.solver().Add(dur_expr <= int(10*3600))
```

```python
end_index = routing.End(int(veh.index))
duration_dimension.CumulVar(end_index).SetRange(0, 10*3600)
```

But none of them seems to achieve what I want. Any ideas?

**Comment by Mizux** [comment]
What do you mean by not achieve what you want, I think
```python
duration_dimension = routing.GetDimensionOrDie("Duration")
for v_idx in len(vehicles):
    routing.solver().Add(duration_dimension.CumulVar(routing.End(v_idx) <= int(10*3600)))
```

Would force each vehicle to finish in less than 36000.
if you have a solution aka `assignment != None`
try to print the value of:
```python
for v_idx in len(vehicles):
    end_duration = assignment.Value(duration_dimension.CumulVar(routing.End(v_idx)))
    print('vehicle {0}, duration: {1}'.format(v_idx, end_duration))
```

**Comment by bertop89** [comment]
Thanks @Mizux, it worked even without adding this hard restriction:

```python
duration_dimension = routing.GetDimensionOrDie("Duration")
for v_idx in len(vehicles):
    routing.solver().Add(duration_dimension.CumulVar(routing.End(v_idx) <= int(10*3600)))
```

Only that I was not taking into account the slack variable when checking the ending times of each vehicle.

**Comment by JacobenVosloo** [comment]
@bertop89 could you please elaborate on how you added the slack variable when checking the ending times of each vehicle?

I assume you made adjustments to the `tot_time_fn` function?

**Comment by qiniuweihe** [comment]
My problem is that the vehicle start time is not fixed, how to calculate the vehicle's travel time?
