### ISSUE TITLE
BadImageFormatException on Azure Web Application

### ISSUE THREAD

**Issue by Kieken72** [google/or-tools#728]
Greetings,

My client has been using this library already for years but we recently started moving our old cloud services on Azure from 'Cloud Service' to Azure Web Applications. Thus, moving a worker role to an Azure Web Job. Since then the Google.OrTools does not work anymore. (I've been looking for this issue for a week now and I have already checked that the environment is indeed 64bit.) 
Error:
```
System.BadImageFormatException: Could not load file or assembly 'Google.OrTools, Version=6.7.4973.32602, Culture=neutral, PublicKeyToken=8976cf6a4a76bd5f' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: 'Google.OrTools, Version=6.7.4973.32602, Culture=neutral, PublicKeyToken=8976cf6a4a76bd5f'
   at Bluecrux.Lop.Optimization.Optimizer.DefaultOptimizer.Optimize(Input input)
   at Bluecrux.Lop.Optimization.OptimizationRunner.RunOptimizer(String connectionString, Int32 scenarioAnalysisId, Boolean localTest, Nullable`1 timeout)
   at Bluecrux.Lop.Optimization.OptimizationRunner.<Run>d__12.MoveNext()
```

Azure Web App Settings
<img width="567" alt="screen shot 2018-06-20 at 15 00 17" src="https://user-images.githubusercontent.com/9077926/41659855-ba95b380-749a-11e8-8499-f78e6a55f93b.png">

Looking forward to a solution! Kind regards,

**Comment by Mizux** [comment]
Hi, how did you get OR-Tools ? Can you enable an higher level of verbosity when running your app ?

e.g. `dotnet run -v n`
> -v, --verbosity                       Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].

**Comment by Kieken72** [comment]
Thanks! I noticed my run configuration did not exist when running the application so this automatically created a new one that used 32 bit.

Sorry for the inconvenience!

**Comment by ss-markmontesa** [comment]
> 
> 
> Thanks! I noticed my run configuration did not exist when running the application so this automatically created a new one that used 32 bit.
> 
> Sorry for the inconvenience!

Hi, 
Sorry for the inconvenience but were also experiencing the same issue stated above.
What do mean by 'configuration did not exist'? And where we can update it so that we can run Google.OrTools on azure web app.

Thanks in advance.
