### ISSUE TITLE
'IntVar' object has no attribute '__array_priority__'

### ISSUE THREAD

**Issue by robertrenecker** [google/or-tools#729]
Trying to do MIP method of ortools using a constraint solver...
when trying solver.Maximize function got error

'IntVar' object has no attribute '__array_priority__'

with a break at this function:
def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))

**Comment by Mizux** [comment]
Which language are you using ? Does examples work on your system ?

**Comment by robertrenecker** [comment]
I am using Python 3, I seem to have it fixed but before I think the issue arose from different sized array comparisons.

**Comment by lperron** [comment]
Ok. Closing the issue
