### ISSUE TITLE
Invalid signed integer overflow in saturated_arithmetic.h

### ISSUE THREAD

**Issue by orwant** [google/or-tools#73]
Originally reported on Google Code with ID 57

```
What steps will reproduce the problem?

I don't have a handy model to reproduce the problem, but the following should expose
it: create two variables (x, y) with domains [kint64min, kint64max], then their difference
z = x - y and try to register constraint z > 10. This constraint is assumed to be always
true and, thus, ignored by the solver.

I myself got this problem with a more complicated model, where the real domains of
x and y were not known in advance and had to be set at "infinity" values.

I also attached a file to isolate the problem. Read below for the explanation.



What is the expected output? What do you see instead?

The constraint should be handled by the solver properly.



What version of the product are you using? On what operating system?

Should be true for the current version of or-tools, GCC 4.7 (at least)



Please provide any additional information below.

The problem is within saturated_arithmetic.h, function CapWithSignOf. Signed integer
overflow is undefined as by C++ standard, so some compilers make use of this during
optimization. In this case, GCC (4.7 and possibly others) during the VRP optimization
completely ignores "sign_bit". Thus, CapWithSignOf always returns kint64max, ignoring
the sign of x.

This doesn't happen in clang, it seems. For GCC the solution is to enforce the wrap
signed arithmetic by using -fwrapv option. I don't know about other compilers or any
remedies that might exist there.

I attached the file to reproduce the problem, where I cut the functions from saturated_arithmetic.h
Assembly compiled with -O2-3 shows that GCC always uses the kint64max constant. Running
it with x=-9223372036854775808, y=1
produces x-y = 7fffffffffffffff, which is incorrect.
```

Reported by `allex2001` on 2014-12-29 20:24:43

<hr>
- _Attachment: [or-tools-signed.cpp](https://storage.googleapis.com/google-code-attachments/or-tools/issue-57/comment-0/or-tools-signed.cpp)_

**Comment by CodeToFreedom** [comment]
Hello, 
I have the same problem with the current python package (version ortools  8.2.8710). 
The toy model below cannot be solved probably because of this or a related issue.
```
from ortools.sat.python import cp_model

model = cp_model.CpModel()
ub = int(cp_model.INT_MAX - 2)

x = model.NewIntVar(lb=0, ub=ub, name='x')
y = model.NewIntVar(lb=0, ub=ub, name='y')
z = model.NewIntVar(lb=0, ub=ub, name='z')

model.Add(z == x - y)
model.Add(z > 10)
model.Minimize(x)
solver = cp_model.CpSolver()
status = solver.Solve(model)

if status == cp_model.OPTIMAL:
    print("x:", solver.Value(x))
    print("y:", solver.Value(y))
    print("z:", solver.Value(z))
else:
    print("Model cannot be solved:", model.Validate())
```
This results in the following error:

> Model cannot be solved: Possible integer overflow in constraint: linear {
  vars: 1
  vars: 0
  vars: 2
  coeffs: 1
  coeffs: -1
  coeffs: 1
  domain: 0
  domain: 0
}

In the real model I unfortunately cannot use cp_model.INT32_MAX because some results exceed this limit. 
Do you have any idea on how to fix or circumvent this problem? Is there an error in the pip package?

Many thanks in advance

**Comment by lperron** [comment]
int_max / 16 ?
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le sam. 3 avr. 2021 à 13:37, CodeToFreedom ***@***.***> a
écrit :

**Comment by lperron** [comment]
an please do not use an old issue that has no link to your problem.

**Comment by CodeToFreedom** [comment]
@lperron: Many thanks for your instant reply. In the toy model setting this to int_max/16 works but in the more complicated model I get the same "possible overflow" error. 
I'll try to isolate the problem further and create another simplified toy model in case the error persists (but this time in a new issue). 

Please excuse me for having posted my issue under the old one. I really thought that it would be related and therefore created a toy implementation of the exact x,y,z problem orwant posted 2015.
Again thank you very much for your efforts.

**Comment by lperron** [comment]
The solver will refuse all models that can overflow. You need to work our
constant and ranges on your own.

Le sam. 3 avr. 2021 à 14:56, CodeToFreedom ***@***.***> a
écrit :
