### ISSUE TITLE
Document build dependency on `git`

### ISSUE THREAD

**Issue by asottile** [google/or-tools#731]
I'm following this: https://developers.google.com/optimization/introduction/installing/source

My `make` invocation terminates with:

```
git clone --quiet -b v2.2.1 https://github.com/gflags/gflags.git dependencies/sources/gflags-2.2.1
make: git: Command not found
makefiles/Makefile.third_party.unix.mk:205: recipe for target 'dependencies/sources/gflags-2.2.1/CMakeLists.txt' failed
make: *** [dependencies/sources/gflags-2.2.1/CMakeLists.txt] Error 127
```

I'd just update this myself but I'm not finding the docs source (to be honest, I didn't try very hard to find it, sorry!)

**Comment by Mizux** [comment]
Did you install the prerequisite software ? https://developers.google.com/optimization/introduction/installing/source#install-prerequisite-software

it seems you don't have `git` installed....

**Comment by asottile** [comment]
@Mizux you're misunderstanding me I think.  I did install the prerequisite software, however it _doesn't list `git`_ and it _should list `git`_.

I'm requesting an update to the documentation to add `git` to the `apt` install lines

**Comment by Mizux** [comment]
Can you point which line doesn't list `git` ? could you also try to refresh your browser ?
Seems git is on each line for linux install...

Or are you using MacOS ? (in this case I think the `xcode-select --install` or `brew install` install it as a dependency)

**Comment by Mizux** [comment]
Seems related to #675

**Comment by asottile** [comment]
I see it there now, strange! Perhaps I was viewing an old copy of the docs
