### ISSUE TITLE
[Help Needed] Parallel Cheapest Insertion doesn't work with less vehicles

### ISSUE THREAD

**Issue by Spantouris** [google/or-tools#733]
Hello,

I have modeled a CVRPTW problem with ortools and I use Parallel Cheapest Insertion as my first solution strategy. 

When I run an example with 500 orders and 1-9 vehicles the algorithm fails at execution. If I increase the vehicles to 10+ the algorithm returns an answer. I want to ask if this first solution strategy needs a specific ratio of Orders/Vehicles in order to run or something else that I missed. I can't understand why it fails with 6 vehicles as I expect to return an answer independent of the number of vehicles. 

Any answer is appreciated.

Thanks,
John

**Comment by Mizux** [comment]
Is your problem feasible with few vehicles ? I mean if you not add disjunction then solver **must** find a solution which visit **all** order i.e. it can't drop some orders, and thus it may not found any solution.
`number_of_vehicle * capacity >= sum(orders)`.

Also since you are using TW solver must also find routes which also guaranty your time windows constraints...

ps: Which language do you use ?

**Comment by Spantouris** [comment]
I use Disjunctions for all my orders and only some of them are mandatory and they can be completed. I don't have a problem with time windows because the orders they have it are not mandatory. I am using Python. 

How can the increase of vehicles affect so much the problem? 

Something else I forgot to mention is that when all my Disjunctions have the same penalty(I also model a priority for the orders and ignore it in the specific example) the program is running normally independently of vehicles(even with one vehicle). For the priorities I use the following(PriorityBucket is a number from 1 to 5): 
`routing.AddDisjunction([node], int(math.pow(10, 11- orders[node]['PriorityBucket']) +orders[node]['Penalty']))`

**Comment by Mizux** [comment]
Could you try to enable some log using:
```python
search_parameters.log_search = True
```
for example just after defining the first strategy in your routing model and before calling `SolveWithParameters()`

**Comment by GuyBenhaim** [comment]
Interesting.
I'm also experiencing cases where one would expect the Solver to provide a solution while dropping some (or many ...) orders.
Yet, it seems to run forever w/o result (e.g. 2 hours). 
Is there a way to identify whether it is still exploring the state-space or whether it is stuck? 
(there are probably several types of "stuck")

**Comment by Spantouris** [comment]
My problem was that I had some constraints that made the algorithm broke. I solved it changing the constrain and now the algorithm runs fine. 

I have seen some cases that the algorithm can return an answer after many hours(like 2+ as you mention) but I don't know a way that you can see if it explores the state-space.

I will close the issue cause my problem is solved.

Thanks @Mizux for your time.

**Comment by GuyBenhaim** [comment]
In my case the Solvers solves 200 orders in less than a minute but, feeding another 100 to the original 200 causes the Solver to hang. 
I would expect it to solve all 300, or solve >200 and drop the rest. But not hang.

**Comment by turing95** [comment]
I'd like to add that the solver sometimes needs more vehicles than the ones it actually uses to solve the problem. If I try to remove these vehicles the solver is not able to find any solution.
