### ISSUE TITLE
Allow Java standard infinity

### ISSUE THREAD

**Issue by oliviercailloux** [google/or-tools#736]
The [doc](https://developers.google.com/optimization/introduction/using#java) says to use `MPSolver.infinity();` to obtain a double value representing infinity. But Java already has such [values](https://docs.oracle.com/javase/9/docs/api/java/lang/Double.html#POSITIVE_INFINITY). Can we use those instead of `MPSolver.infinity();`? If so, please update the doc. If not, please consider supporting this. This makes one less thing to learn to use; is more elegant; and integrates better with existing code (eg I use Guava Ranges of Double and this sometimes involve Double Infinite values, not having to convert back and forth from MPSolver would be handy).

(I am aware I might just try it out to obtain a possible answer, but I am interested in writing code that conforms to the specs; trying does not tell what the spec intents to permit and what will be supported in the future.)

**Comment by lperron** [comment]
I believe they are the same object.
We will update ther doc.

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 27 juin 2018 à 01:09, Olivier Cailloux <notifications@github.com> a
écrit :

**Comment by Mizux** [comment]
Or-Tools is built in C++ with wrapper in Java using SWIG.
so `MPSolver.infinity()` is binded on C++ code
src: https://github.com/google/or-tools/blob/master/ortools/linear_solver/java/linear_solver.i#L170

And we define infinity in C++ as 
```cpp
 // Infinity. You can use -MPSolver::infinity() for negative infinity.
  static double infinity() { return std::numeric_limits<double>::infinity(); }
```
src: https://github.com/google/or-tools/blob/master/ortools/linear_solver/linear_solver.h#L499

Which should be equal to `HUGE_VAL` which is `#define HUGE_VAL  /*implementation defined*/`
src: https://en.cppreference.com/w/cpp/types/numeric_limits/infinity
https://en.cppreference.com/w/cpp/numeric/math/HUGE_VAL

So it may or may not be the same value...

Best: Need to tweak the swig wrapper to do the convertion on the fly in/out between C++ and Java but not sure if it is easily doable...

**Comment by lperron** [comment]
This is the same value. 
Closing the issue.

**Comment by oliviercailloux** [comment]
Part of the request was about mentioning this fact in the doc, if indeed using Java proper Double values is allowed instead of `MPSolver.infinity()`. But the [doc](https://developers.google.com/optimization/introduction/java#java) still mentions the latter, it seems.
