### ISSUE TITLE
Speeding up ReadAssignmentFromRoute

### ISSUE THREAD

**Issue by avadamn** [google/or-tools#739]
Currently I'm working on a VRP model with the following additional characteristics
1. Nodes are mostly disjunctive and only a single node from each set need to be visited
2. These nodes need to be visited in a certain sequence (time dimension + CumulVar)
3. Additional resources from shared pool required for each nodes if visited

I have some heuristic implemented to generate the initial routing - due to the additional constraints highlighted above, most of the slacks are non-zero. 

I'm trying to utilize ReadAssignmentFromRoute to improve on the initial routing, however, regenerating the assignment took a lot longer than expected.

Any tips and hint to speed this up?

**Comment by lperron** [comment]
This is not helping.
Are you sure the time is spent in the loading part ?
Are you sure the solution is valid.

Please provide a working example.

Closing for now. Do not hesitate to reopen with a working sample.
