### ISSUE TITLE
Glop/LP Usage Page is 404

### ISSUE THREAD

**Issue by rummens** [google/or-tools#740]
I would like to have a look into the LP part of the OR-Tools but unfortunately the usage page (which is linked to by every page) seems offline as it only shows an 404.

Is there anyone at Google here to fix this?

The link is: https://developers.google.com/optimization/introduction/using#lp

Thanks
Kind Regards
Rummens

**Comment by Mizux** [comment]
Hi,

Seems odd,
The link should be https://developers.google.com/optimization/lp/glop did you refresh your browser ?

Also could you point me a page where the link is broken ?
Thx for the feedback !!!!

**Comment by rummens** [comment]
Hi, thanks for the fast response.
I know those pages but for example the Glop Page links to the missing page in the first paragraph: 

> To learn how to use Glop to solve a simple linear problem in all of the supported languages, see A simple linear optimization example.

Also on the main page of this repository under Quick Start:

> The best way to learn how to use OR-Tools is to follow the tutorials in our developer guide:
> https://developers.google.com/optimization/introduction/using
> 
> If you want to learn from code examples, take a look at the examples in the examples directory.
> 

Is there another using page or are the pages provided by you the only examples available? It seems to me that there must be?

Thanks
Rummens

**Comment by Mizux** [comment]
We have merged rework "using|running page" into "Get Started" page. and we have split it by languages.

For LP I think the link I give you are the only documentation available.
note: if you start to mix with integer maybe https://developers.google.com/optimization/mip/integer_opt could be interesting to you.

What are you looking for exactly ?

there is also examples on github to "learn from code" -> https://github.com/google/or-tools/blob/master/examples/cpp/linear_programming.cc
note: example on devsite and github are not in sync (yet?)

**Comment by rummens** [comment]
I just had a look at the Get-Started Page, it seems to be something close to what I was looking for. I just thought there would another example, as the only one I could find was the "The Stigler diet" example. 

To fix the links look through the Linear Optimization Tab and search for " A simple linear optimization example." That should give you most of the dead links. If that would point onto the Get-Started page it makes it easier to find the information.

Thanks for your help.

**Comment by rummens** [comment]
Found another dead link pointing to "https://developers.google.com/optimization/introduction/simple_example". It on the Get-Started Page in section "Running the program":

> You can run the program as described in A simple program.

**Comment by Mizux** [comment]
Should be fixed now !

Thanks for the feedback
