### ISSUE TITLE
Missing pip packages for python 3.7

### ISSUE THREAD

**Issue by CaselIT** [google/or-tools#745]
Ortools cannot be installed using pip with python 3.7 since the required files are missing from https://pypi.org/project/ortools/#files

**Comment by Mizux** [comment]
Yup, I'll try to add it to our build delivery script for the v6.8 (intended for June now July)

cf: https://github.com/google/or-tools/blob/master/tools/build_delivery_unix.sh
and https://github.com/google/or-tools/blob/master/tools/build_delivery_win.cmd

**Comment by CaselIT** [comment]
thanks @Mizux 

> BTW you can still build it from source and create a python 3.7 package ;)

Of course, but it's way easier using pypi, especially on windows! (Btw thanks for maintaining also the windows version :) )

**Comment by Mizux** [comment]
I've just generated manylinux python 3.7 package for release 6.8

**Comment by CaselIT** [comment]
@Mizux thank you!
