### ISSUE TITLE
Solving OVRP?

### ISSUE THREAD

**Issue by hopewise** [google/or-tools#750]
Provided that at OVRP, the vehicle does not return to the depot,
Is it possible to solve Open Vehicle Routing Problem with or-tools?

**Comment by hopewise** [comment]
thanks, so at your example above, all ends are dummy nodes? _(as OVRP has no end locations provided)_ while starts are real nodes as all busses starts from specific location?

that's it to have OVRP?

**Comment by Mizux** [comment]
Depends to what you want but since you said you want open ends (but not necessary open start)
So I use two node one start node as depot, and one dummy node as end. After you can mix as you want or even use a differents location node for each vehicles...

**Comment by hopewise** [comment]
So, as for `num_locations` at your example, I suppose it will be populated as:

[0] = depot (the start location)
[1] = dummy
[2 .. n ] = location, where n is number of students that busses will be picking up.

correct?

**Comment by paultrow** [comment]
See https://developers.google.com/optimization/routing/routing_tasks#allowing-arbitrary-start-and-end-locations

**Comment by hopewise** [comment]
Thanks!
