### ISSUE TITLE
CPSolver crashing with intervals of length 1

### ISSUE THREAD

**Issue by Haukinger** [google/or-tools#751]
I'm experimenting with the C# CPSolver, starting from the Job-Shop-Example. I'm incrementally scheduling new jobs, each consisting of about ten tasks, each of which has to be done on one of about four machines and some of which have a variable duration. I have lots of tasks that have a fixed duration of 1. I can not schedule a hundred tasks before crashing with an unhandled exception, some times I got "infeasible" as result without a crash although there's an obvious solution I can create by hand.

Now for the interesting part: if I multiply all durations by ten, the solver finds the correct solution. Is there a problem with the NoOverlapConstraint with lots of IntervalVars of length 1?

**Comment by lperron** [comment]
Hi,

Can you send me a code that exhibits the crash?

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 11 juil. 2018 à 11:49, Haukinger <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
Still waiting :-)

**Comment by Haukinger** [comment]
I sent an email to lperron@google.com on the 11th... I can as well post it here, just to be on the safe side:

> here’s the code that shows the behaviour. I compiled the master-branch from source, if you put the three dlls beside the sln, it should build (nuget won’t work because of #552). Change JobShopFt10Sat.TimeFactor to 1 to see it crash.

Attachment: [Scheduler.ZIP](https://github.com/google/or-tools/files/2228992/Scheduler.ZIP)

**Comment by lperron** [comment]
lperron@lperron:~/Work/bugs/scheduling$
LD_LIBRARY_PATH=~/Work/or-tools/bin/ dotnet run
Statistics
  - solve status : Optimal
  - makespan     : 225
  - conflicts    : 1
  - branches     : 65
  - wall time    : 0.005487609 s
Statistics
  - solve status : Optimal
  - makespan     : 146
  - conflicts    : 0
  - branches     : 4
  - wall time    : 0.000752594 s
Statistics
  - solve status : Optimal
  - makespan     : 248
  - conflicts    : 1
  - branches     : 30
  - wall time    : 0.004375261 s
Statistics
  - solve status : Optimal
  - makespan     : 260
  - conflicts    : 22
  - branches     : 93
  - wall time    : 0.032871712 s
Statistics
  - solve status : Optimal
  - makespan     : 277
  - conflicts    : 1
  - branches     : 8
  - wall time    : 0.002099537 s
Statistics
  - solve status : Optimal
  - makespan     : 291
  - conflicts    : 1
  - branches     : 8
  - wall time    : 0.00225347 s
Statistics
  - solve status : Optimal
  - makespan     : 326
  - conflicts    : 2
  - branches     : 18
  - wall time    : 0.003895251 s
Statistics
  - solve status : Optimal
  - makespan     : 366
  - conflicts    : 1
  - branches     : 7
  - wall time    : 0.002540916 s


Seems to be working fine with the latest release.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 25 juil. 2018 à 10:50, Haukinger <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
I closed the issue as I cannot reproduce the problem.
Please reopen if needed.
