### ISSUE TITLE
VRP with partial solution 

### ISSUE THREAD

**Issue by Westlife1002** [google/or-tools#753]
Hi,

Where there is no solution returned, which means the constraints are violated such as out of loading capacity, max distance exceeded.   

In such case, is it possible to see the partial fulfilment result? i.e. if I just have only one truck which is not possible to deliver to all customers, can I still get the result showing how many customers I can serve using only one truck? This information indicating the coverage achieved with limited resources would be highly useful for evaluation of customer service strategy.  In many real world use cases we just don’t target to achieve 100% delivery. To find out how far we can make with the existing resources are more often the case.

Thus the things I want to achieve most is to have a list of customers(nodes) that are not served under the constraints(either violating the capacity or distance or time window, or all of them). So I could visualise them with a different colour and get the % that are not served. 

Thanks for your help.
Jerry

**Comment by boooch** [comment]
any news??

**Comment by hklarner** [comment]
i can see two possible workarounds:

(1) relax constraints systematically and call again
(2) use cost function instead of hard yes/no constraints

any thoughts?

**Comment by boooch** [comment]
Now Im using several fake vehicles with high cost and all tasks distributed on this vehicles marked as cannot distribute

**Comment by Mizux** [comment]
Why don't adding disjunction on node so you can see how many node are dropped ?
see: https://developers.google.com/optimization/routing/penalties
