### ISSUE TITLE
Cost calculation

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#755]
Hello,
Is there a way to expose to the Node Evaluator not just two Nodes indices (for cost callback), but list several previous Nodes the Solver had explored for the route - such that the cost calculation can consider 'history'?
Alternatively, get the accumulated value for N-Nodes back.

**Comment by Mizux** [comment]
I'm not aware of any way to get it.

The closest thing will be to use [`AddDimensionDependentDimensionWithVehicleCapacity()`](https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing.h#L448) but it is unfortunately currently not exported in SWIG.

cf #339 status

**Comment by GuyBenhaim** [comment]
Thx,
I'll need to better understand the Dependant Dimansion trick, and consider if useful.

Still, would be interesting to expose additional state information to NE2 for more 'aware' cost evaluation.

**Comment by GuyBenhaim** [comment]
How can I access AddDimensionDependentDimensionWithVehicleCapacity() from C# to add to the model, Even if with proprietary code or function

Or maybe some trick the bypasses C# and sets  AddDimensionDependentDimensionWithVehicleCapacity(), and includes in the model that is used by the C# program.

**Comment by Mizux** [comment]
close it since it is related (duplicate) to #339
