### ISSUE TITLE
Feasibility depends on order of input

### ISSUE THREAD

**Issue by Haukinger** [google/or-tools#758]
I'm incrementally adding more tasks to my schedule, each of which contains steps that may have flexible durations or fixed durations. In the first run, the CPSolver can freely plan the first batch of tasks, in the subsequent runs, the previously planned batches are kept as fixed.

Depending on the order of my batches, the solver finds a solution or fails to. I don't understand why it fails, because the trivial solution of adding the new batch after all the previuos ones are done is always possible.

EDIT: when I set linearization_level to 0, it seems to always find the solution independent of order.

**Comment by lperron** [comment]
Hi, 

Can you me some code that exhibits the problem?

**Comment by lperron** [comment]
Dead issue. Closing

**Comment by Haukinger** [comment]
Solved, too, not only dead :-) It was a non-linear problem, and depending on the input the linearization worked or did not work. With linearization disabled, it always worked.
