### ISSUE TITLE
Why do unsatisfiable range constraints raise exceptions?

### ISSUE THREAD

**Issue by hklarner** [google/or-tools#762]
I noticed that range constraints that are obviously not satisfiable cause CP solver fail exceptions. Below are the relevant lines. I enable `fix_start_cumul_to_zero` and also add a set range that excludes 0. Can't work. But instead of allowing a solve call that returns the `None` assignment an exception is raised. Is there any particular reasoning behind this?

	evaluator = cost_function
	slack_max = 0
	capacity = 100
	fix_start_cumul_to_zero = True
	name = "time"
	routing.AddDimension(evaluator, slack_max, capacity, fix_start_cumul_to_zero, name)

	time_dimension = routing.GetDimensionOrDie("time")

	for vehicle in range(vehicles):
		index = routing.Start(vehicle)
		time_dimension.CumulVar(index).SetRange(1, 100)

The exception is

> Traceback (most recent call last):
>   File "jobs.py", line 45, in <module>
>     time_dimension.CumulVar(index).SetRange(1, 100)
>   File "~/python3.5/site-packages/ortools/constraint_solver/pywrapcp.py", line 1339, in SetRange
>     return _pywrapcp.IntExpr_SetRange(self, l, u)
> Exception: CP Solver fail

**Comment by Mizux** [comment]
CumulVar is a [IntVar](https://github.com/google/or-tools/blob/master/ortools/constraint_solver/constraint_solver.h#L4067) Interface which inherit from [IntExpr](https://github.com/google/or-tools/blob/master/ortools/constraint_solver/constraint_solver.h#L3906) where you have the `SetRange()` using `setMin()` & `setMax()`

Now the CumulVar is built using [`MakeIntVarArray()`](https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing.cc#L4744)

[Solver::MakeIntVar](https://github.com/google/or-tools/blob/master/ortools/constraint_solver/expressions.cc#L6411)
which in your case build a [DomainVar()](https://github.com/google/or-tools/blob/master/ortools/constraint_solver/expressions.cc#L201)
which define setMin as 
```cpp
void DomainIntVar::SetMin(int64 m) {
  if (m <= min_.Value()) return;
  if (m > max_.Value()) solver()->Fail();
  if (in_process_) {
    if (m > new_min_) {
      new_min_ = m;
      if (new_min_ > new_max_) {
        solver()->Fail();
      }
    }
  } else {
    CheckOldMin();
    const int64 new_min =
        (bits_ == nullptr
             ? m
             : bits_->ComputeNewMin(m, min_.Value(), max_.Value()));
    min_.SetValue(solver(), new_min);
    if (min_.Value() > max_.Value()) {
      solver()->Fail();
    }
    Push();
  }
}
```
src: https://github.com/google/or-tools/blob/master/ortools/constraint_solver/expressions.cc#L2254

`solver->Fail()` will set a flag so `solve()` will return an exception. And if I remember well it is currently not catch/managed by the SWIG python wrapper

**Comment by hklarner** [comment]
thanks, that answers my question
