### ISSUE TITLE
Error in installing ortools from source 

### ISSUE THREAD

**Issue by Hebro05** [google/or-tools#764]
I try to install or-tools for python on windows from the source file as indicated in the installation guide (https://developers.google.com/optimization/introduction/installing/source#build-the-source-code_8).

I installed all prerequired software (Visual Studio 17, Git, SVN, CMake).

However, opening the VS command prompt and running the "tools\make third_party" command in the or tools file directory leads to the following error message:

```
C:\Users\hendrik.braun\or-tools-6.7.2>tools\make third_party
tools\which.exe: no java in (\bin)
tools\mkdir.exe -p dependencies\\archives
tools\wget --quiet -P dependencies\\archives http://zlib.net/zlib1211.zip
tools\make: *** [dependencies/archives/zlib1211.zip] Error 4
```

**Comment by lperron** [comment]
The java message is a spurrious message.
The Error 4 is just zlib being down, please retry.
