### ISSUE TITLE
Monitor Solver Progress

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#766]
Hello,
For C# is there a good way to monitor/present/log, during the search, the progress of the Solver search process (or lack of it)?
Thx

**Comment by lperron** [comment]
Which solver?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
The VRP Solver

**Comment by lperron** [comment]
There is a log_search parameters on the routing solver.

Search for RoutingSearchParameters in the examples.

--Laurent
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
see https://github.com/google/or-tools/issues/733#issuecomment-400219554
