### ISSUE TITLE
Same Location Orders not picked up together in VRP

### ISSUE THREAD

**Issue by nepsi** [google/or-tools#767]
Hi,

I ran into a problem while using vehicle routing library.

I have 10 orders-C1,C2....C10. Order C1,C2,C3 have same location and another orders have different locations.

Sequence in which vehicle is picking orders -C1,C2,C4  and then C3. Why it is not picking C1,C2 ,C3 (as three orders have same location) together and then go to C4. Time  window is large for all orders so there should be any problem related to time window constraint.
What constraint should I add so that a vehicle picks same location orders together.
Thanks.

**Comment by nepsi** [comment]
Hi,

Any suggestion or reference will be very helpful.

Thanks.

**Comment by GuyBenhaim** [comment]
That may not necessarily be wrong, depending on where the next Node served is located.
Are you sure ArcCost between any pair in 1,2,3 is absolutely 0 ?

Some combination of  PickDrop and forcing same CumulVar("distance") could work
