### ISSUE TITLE
Debugging in VS2017 (C++)

### ISSUE THREAD

**Issue by rereradu** [google/or-tools#768]
I am trying to include **or-tools** in an existing C++ project in VS2017 and run it in debug mode.
I've tried including both the binary and building from source code, following [these instructions](https://developers.google.com/optimization/install/cpp/source_windows).

When building my project in VS2017, I get this error:

```shell
LNK2038    mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in ortools.lib(linear_solver.obj
```

I've changing the project's properties for the Runtime Library but none of the options seem to work.

How can I include the library / build from the sources for Debug mode in VS2017?

**Comment by lperron** [comment]
We build with /MD. So you need to set your project to /MD too, even with
debug options enables (/Od /Zi).

I hope this is feasible in your project.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by rereradu** [comment]
I did try to set the project to /MD. Unfortunately this still throws the error. 
Do you know if building the library from sources using the CMake option could help with this issue (using CMAKE_BUILD_TYPE)?

**Comment by lperron** [comment]
After setting the /MD, you need to recompile or-tools (not third_party).
If you still see an error with MDd_xxx, you have not cleaned enough :-)

**Comment by Mizux** [comment]
For CMake we use
```cmake
if(MSVC)
  ...
  if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    add_definitions(/MDd)
  else()
    add_definitions(/MD /DNDEBUG)
  endif()
```
src: https://github.com/google/or-tools/blob/master/cmake/cpp.cmake#L18
