### ISSUE TITLE
Load-time dynamic linking of solver libraries causes problems

### ISSUE THREAD

**Issue by ddorfmeister** [google/or-tools#770]
The currently used load-time dynamic linking of solver libraries causes some problems:
1. If you want to use third-party solvers such as GLPK, SCIP, Gurobi or CPLEX, you have to build OR-Tools yourself, which can be quite cumbersome.
2. If you want to use a new version of a solver with OR-Tool, you have to rebuild OR-Tools.
3. If you enable several solvers while building OR-Tools and you want to use the resulting library on another PC that lacks some solvers (especially the commercial ones), you can't use the OR-Tools library at all (not even the built-in CBC) because all the solver libraries are loaded at start-up, which causes an error immediately.

Replacing load-time with run-time dynamic linking could solve the above-mentioned problems as follows:
1. OR-Tools with out-of-the-box support for all solvers could be distributed as binaries. If you want to use any of the external solvers, you simply have to install them on your computer.
2. Assuming the solver libraries are at least somehow backwards compatible, OR-Tools could link against several versions of a solver (starting with a minimum required version). This way, solvers could be upgraded easily, which, e.g., allows for easy comparisons of different versions of the same solver using a single version of the OR-Tools library.
3. Since the solver library must be present only when the solver is actually instantiated, other solvers could still be used even if a solver library is missing on a specific computer.

I am currently working on a project where we use OR-Tools to compare all of OR-Tools’ supported solvers regarding their ability to solve certain MIP models. I have access to academic licenses but our partner company does not and it is a bit cumbersome to distribute new versions of our application to them so they can have an in-detail look at the solvers, as we have to rebuild OR-Tools for their solver setup. In addition, we consider integrating OR-Tools in [HeuristicLab](https://dev.heuristiclab.com/) (a framework for heuristic and evolutionary algorithms) so a broader audience could use solvers easily (run-time dynamic linking of solver libraries is an absolute necessity in this case).

To see whether my ideas could be realized without too much effort, I forked OR-Tools and implemented run-time dynamic linking for the Gurobi interface for LP (_linear_solver/gurobi_interface.cc_). Actually, I just created a single class to hide the OS-specific aspects (_base/dynamic_library.h/.cc_) and added only a small amount of code to the Gurobi interface. The maintaining should not be too complicated, you just need to add two lines of code for each additional function of the solver API you want to use in the interface. My tests showed that it works as expected on Windows and Linux (I could not test this on macOS).

You can have a look at the changes in my branch [runtimelinking](https://github.com/ddorfmeister/or-tools/tree/runtimelinking), the changes described above you can find in my [first commit](https://github.com/ddorfmeister/or-tools/commit/b7fc1d061f90e77a09a732712a40b77fabf1b356). I will possibly implement run-time linking for other LP interfaces in the next weeks and as I do not consider my changes trivial, I wanted to have a discussion on the issue and my possible solution before I create a pull request.

**Comment by lperron** [comment]
Thanks. I need to check how it works with licences.
And we must ensure it is fully portable.

But this is very interesting. Thanks a lot.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by ddorfmeister** [comment]
Thanks for getting back to me so quickly.
Do you know how long the legal review will take?

In the meantime, I implemented run-time dynamic linking for CPLEX, SCIP and GLPK and cleaned up the original code a bit - maybe you want to have a look.

**Comment by lperron** [comment]
Sorry for the late answer, but please I would like to review the code.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by ddorfmeister** [comment]
The latest version of my code is available on my [runtimelinking](https://github.com/ddorfmeister/or-tools/tree/runtimelinking) branch.
In the meantime, I added the possibility to pass the name of the library to use to the constructor. This means that you can decide which version(s) of a solver should be used at runtime.
Note that there is a bug when using CPLEX: If you try to solve a more complex model, it crashes - simple models worked fine for me, though. I'll try to figure this out in the upcoming weeks.
Do you have any news regarding the licenses?

**Comment by ddorfmeister** [comment]
I fixed the bug in the CPLEX interface: https://github.com/ddorfmeister/or-tools/commit/62b433751564a627416143c3ba9469d855c098de

**Comment by lperron** [comment]
Done for SCIP (included by default) and Gurobi (sideloading).
No plan for CPLEX.
