### ISSUE TITLE
Compilation error when running make python

### ISSUE THREAD

**Issue by danmarinescu** [google/or-tools#772]
I am looking to use OR-Tools with Gurobi and/or Cplex. My understanding is that to achieve that I need to build OR-Tools from source. When building version 6.8 of OR-Tools Python from source on Mac OS, following the instructions [here](https://developers.google.com/optimization/install/python/mac), I get a compilation error when running `make python`. The error points to this line (among others in that file)
https://github.com/google/or-tools/blob/9487eb85f4620f93abfed64899371be88d65c6ec/ortools/linear_solver/cplex_interface.cc#L521 

Looking for the declaration of `CoeffMap` it looks like it was removed in this commit 
https://github.com/google/or-tools/commit/a9dd4aec9a4a2a5cf1b6a241ae760a213a9f9d2e

I am afraid that my limited understanding of C++ doesn't allow me to propose a solution via a PR hence I created the issue here

**Comment by lperron** [comment]
I will fix this,

Thanks for the report.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 31 juil. 2018 à 00:02, danmarinescu <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
I just pushed the fix.
Please update the sources and recompile.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by danmarinescu** [comment]
Thanks @lperron, I can confirm I am no longer getting any compilation errors with `make python` which now completes successfully. 

I have found the following additional issue, though it is not clear to me if they apply to or-tools in general or my specific setup. I am running python 3, and have set `UNIX_PYTHON_VER = 3` in `Makefile.local`. When I run `make install_python` I get the following error:

> cd "temp-python3/ortools" && "/usr/local/bin/python3" setup.py install --user
running install
error: can't combine user with prefix, exec_prefix/home, or install_(plat)base
make: *** [install_python] Error 1

After a bit of googling around I found that adding `--prefix=` to `cd "$(PYPI_ARCHIVE_TEMP_DIR)$Sortools" && "$(PYTHON_EXECUTABLE)" setup.py install --user` inside `makefiles/Makefile.python.mk` "fixed" the issue and `make install_python` now completes successfully. However, when I now try to run my model through CPLEX, I get the following error:

>ImportError: dlopen(/Users/dan/Library/Python/3.7/lib/python/site-packages/ortools-6.8.5475-py3.7-macosx-10.13-x86_64.egg/ortools/linear_solver/_pywraplp.so, 2): Library not loaded: @rpath/libortools.dylib
  Referenced from: /Users/dan/Library/Python/3.7/lib/python/site-packages/ortools-6.8.5475-py3.7-macosx-10.13-x86_64.egg/ortools/linear_solver/_pywraplp.so
  Reason: Incompatible library version: _pywraplp.so requires version 6.8.0 or later, but libortools.dylib provides version 6.7.0

Running `otool -L /Users/dan/Library/Python/3.7/lib/python/site-packages/ortools-6.8.5475-py3.7-macosx-10.13-x86_64.egg/ortools/libortools.dylib` returns

>/Users/dan/Library/Python/3.7/lib/python/site-packages/ortools-6.8.5475-py3.7-macosx-10.13-x86_64.egg/ortools/libortools.dylib:
	/Users/dan/work/glidebooks/smart_scheduler/or-tools/lib/libortools.dylib (compatibility version 6.7.0, current version 6.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	libgurobi80.so (compatibility version 8.0.0, current version 8.0.1)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1454.90.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)

However, running `otool -L /Users/dan/work/glidebooks/smart_scheduler/or-tools/lib/libortools.dylib` returns

>@rpath/libortools.dylib (compatibility version 6.8.0, current version 6.8.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	libgurobi80.so (compatibility version 8.0.0, current version 8.0.1)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1454.90.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	@rpath/libgflags.2.2.dylib (compatibility version 2.2.0, current version 2.2.1)
	@rpath/libglog.0.3.5.dylib (compatibility version 0.3.5, current version 0.0.0)
	@rpath/libprotobuf.3.5.1.dylib (compatibility version 0.0.0, current version 3.5.1)
	@rpath/libCbcSolver.3.dylib (compatibility version 13.0.0, current version 13.9.0)
	@rpath/libCbc.3.dylib (compatibility version 13.0.0, current version 13.9.0)
	@rpath/libOsiCbc.3.dylib (compatibility version 13.0.0, current version 13.9.0)
	@rpath/libCgl.1.dylib (compatibility version 11.0.0, current version 11.10.0)
	@rpath/libClpSolver.1.dylib (compatibility version 15.0.0, current version 15.11.0)
	@rpath/libClp.1.dylib (compatibility version 15.0.0, current version 15.11.0)
	@rpath/libOsiClp.1.dylib (compatibility version 15.0.0, current version 15.11.0)
	@rpath/libOsi.1.dylib (compatibility version 14.0.0, current version 14.9.0)
	@rpath/libCoinUtils.3.dylib (compatibility version 14.0.0, current version 14.14.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)

Notice how the latter has version 6.8, while the former has version 6.7. 

Furthermore, I found that if I `rm /Users/dan/Library/Python/3.7/lib/python/site-packages/ortools-6.8.5475-py3.7-macosx-10.13-x86_64.egg/ortools/libortools.dylib` then my model is successfully run by CPLEX.

Not sure if I am doing something wrong here, any help would be appreciated.

Many thanks,
Dan

**Comment by lperron** [comment]
Can you removing the or-tools module, make clean in the source tree and
rebuild?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 2 août 2018 à 01:49, danmarinescu <notifications@github.com> a
écrit :

**Comment by danmarinescu** [comment]
just built OR-tools from scratch on a different machine. While I had to add `--prefix=` for `make install_python` to work everything else worked fine, i.e. I didn't have any issues with a mismatch in version numbers of the `libortools.dylib`

**Comment by lperron** [comment]
Great.

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 3 août 2018 à 01:52, danmarinescu <notifications@github.com> a
écrit :
