### ISSUE TITLE
C# problem with MakeDifference

### ISSUE THREAD

**Issue by eticssrl** [google/or-tools#773]
Good evening,
I'm new to Google OR Tools and I've a problem if I try to use Constraint Solver with complex constraints.
In particular my problem is the classic JobShop problem with this constraints:
1. I need to limit usage of machines to particolar hours of day (machine's calendar)
2. With some type of tasks, the task must start the first Wednesday after the end of previous task and must end on friday

I resolve the first point with:
```cs
var mCalendar = config.MachineCalendars[task.MachineId];

var constraints = new List<Constraint>();
foreach (var c in mCalendar.Intervals)
{
   var startConstraint = task.Interval.StartExpr() >= c.Start;
   var endConstraint = task.Interval.EndExpr() <= c.Stop;

   var both = solver.MakeSum(startConstraint, endConstraint) == 2;
   constraints.Add(both);
}

var or = solver.MakeSum(constraints.Select(s => s.Var()).ToArray()) > 0;
solver.Add(or);
```

For the second point, say IntExpr next the startExpr of the task that mus start on specific day and IntExpr previous the EndExpr of the previous task.
All variables contains times in minutes.
The code is (I split all operations in more than one line for test purpose):
```cs
// number of days from beginning of period of interest (0 = first day)
// the result is always an integer value
// with test data this is 0
var dayEndFromBeginning = previous / Constants.MINUTESINDAY;
// minutes to midnight from the beginning of period
var midnightEnd = (dayEndFromBeginning + 1) * Constants.MINUTESINDAY;
// BeginDay is the first day of period of interest
DayOfWeek startDay = config.BeginDate.DayOfWeek;
var dayEnd1 = solver.MakeIntConst((int)startDay);
var dayEnd2 = dayEnd1 + dayEndFromBeginning;
var dayEnd = dayEnd2 % 7;
// weekday request to delivery (for example Wednesday)
var cweekdayDelivery = solver.MakeIntConst(weekdayDelivery);
// add to collector so I can check the values...
varlog.Add(cweekdayDelivery.Var());
varlog.Add(dayEnd.Var());

// HERE THERE IS A PROBLEM
var thenExpr1 = solver.MakeDifference(cweekdayDelivery, dayEnd);
varlog.Add(thenExpr1.Var());
var thenExpr2 = thenExpr1 * Constants.MINUTESINDAY;
varlog.Add(thenExpr2.Var());
var thenExpr = midnightEnd + thenExpr2;
varlog.Add(thenExpr.Var());
var ct = solver.MakeGreaterOrEqual(next, thenExpr);
solver.Add(ct);
...
...
```

My problem is that when I comment out solver.Add(ct) and I print variable values I obtain:
cweekdayDelivery = 3
dayEnd = 2
thenExpr1  = 1 ( and this is correct 3-2 = 1)
but if I add the constraint to the solver using the last line of code solver.Add(ct) and I print variables, I obtain:
cweekdayDelivery = 3
dayEnd = 2
thenExpr1  = -1 (with minus!!!)
So the constraint is wrong.
What is the problem? cweekdayDelivery  and dayEnd  has the same values!

Thank you very much.
Bye, Nicola

**Comment by Mizux** [comment]
My 2 cents,
Did you check that solver actually find a solution (i.e. the solver status). Maybe the values you're reading are the values when solver stop searching for a solution due to some unfeasible constraints ?

**Comment by eticssrl** [comment]
No, In both cases there is a solution.
Thanks.

**Comment by eticssrl** [comment]
Sorry, Anyone has a hint for my problem?
Thank you

**Comment by eticssrl** [comment]
Here is a VS2017 solution where you can find a FixedDayRelation function that calculates diff incorrectly.
There is also a CalendarConstraints function that limits activities on working days ... but works only if you avoid running FixedDayRelation.
The solution load data from json files in bin folder ad save OR tools solution in solution.txt.

[GoogleORCP.zip](https://github.com/google/or-tools/files/2305695/GoogleORCP.zip)

**Comment by eticssrl** [comment]
Here is a VS2017 solution where you can find a FixedDayRelation function that calculates diff incorrectly.
There is also a CalendarConstraints function that limits tasks on working days ... but works only if you avoid running FixedDayRelation.
The VS solution load data from json files in bin folder and save OR tools solution in solutions.txt.
Last rows in solutions.txt reppresent the values of variables added in valog list.
Here I consider 0 time at 2018/08/20 (monday), and the second tasks must start on wednesday (start>=2880 minutes).
[GoogleORCP1.zip](https://github.com/google/or-tools/files/2305901/GoogleORCP1.zip)

**Comment by eticssrl** [comment]
I found the problem but I don't know how to resolve.
I add the FixedDayRelation constraint to the second task but, for some reason, the constraint is applied always to the last task of the job.

Thanks.
Bye, Nicola

**Comment by eticssrl** [comment]
It seem that the problem is the negation itself.
If I negate previous (that has value 1) with -previous or with solver.MakeOpposite(previous) the result is -3.
If previous has value 0, the negation return -2
Why?

Thank you.

**Comment by lperron** [comment]
The CP solver is on maintenance mode.
So, even if it is a bug, it will likely be 'won't fix'.

Closing the issue now.
