### ISSUE TITLE
c# SAT JobShop crash

### ISSUE THREAD

**Issue by eticssrl** [google/or-tools#774]
If I try your sat job shop examples with more data then those used in the example, the process crashes with NullReferenceException

**Comment by lperron** [comment]
Can you send me a code that exhibits the problem.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by eticssrl** [comment]
I've another similar problem.
If try to solve passing some parameters (I need to stop optimization after some solution found or a time limit):
```
var response = SatHelper.SolveWithStringParameters(model.Model, "stop_after_first_solution:true"); // stop_after_first_solution:true enumerate_all_solutions:false
CpSolverStatus status = response.Status;
...
```
I get a NullReferenceException in Google.OrTools.Sat.CpSolver.get_ObjectiveValue().
What is wrong?
How can I stop SAT in order to have a solution as soon as possible even if it is not optimal?

Thank you very much.
Bye, Nicola

**Comment by lperron** [comment]
The code sample is clearly not complete.

Can you send me an archive with the full code and the data you are using?

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by eticssrl** [comment]
Sorry for the delay but I had to extrapolate the data from the database and create a clean project (data are stored in json files in bin folder).
I try to recompile google or tools (with git version of 12 of july) and now the problem appear later. The dlls that I recompile are in bin folder.
[GoogleORSAT.zip](https://github.com/google/or-tools/files/2254435/GoogleORSAT.zip)

I attach the example and this is the error that, with the data in the examples, it causes the problem even in debug with VS2017:
```
Eccezione non gestita: System.Runtime.InteropServices.SEHException: Eccezione lanciata da un componente esterno.
   in Google.OrTools.Sat.operations_research_satPINVOKE.SatHelper_Solve(Int32 model_proto_size, Byte[] jarg1)
   in Google.OrTools.Sat.SatHelper.Solve(CpModelProto model_proto)
   in Google.OrTools.Sat.CpSolver.Solve(CpModel model)
```

The error appear after 8 minutes executing manually in powershell console.
Thank you very much.
Bye, Nicola

**Comment by lperron** [comment]
Yes, I was on vacation.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by eticssrl** [comment]
Ok, thank you.
Bye, Nicola

**Comment by eticssrl** [comment]
Good morning,
Excuse my insistence, do you have a solution for my problem?

Thank you very much.
Bye, Nicola Milani

Il giorno lun 27 ago 2018 alle ore 15:09 Laurent Perron <
notifications@github.com> ha scritto:

**Comment by lperron** [comment]
I am not on windows, I have trouble running your code.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by eticssrl** [comment]
What can I do?
In the project, all the solver logics is in the file
Optimizer/JobShopCP.cs, maybe you can see if there is an error.

Thank you.
Bye,
Nicola Milani


Il giorno lun 3 set 2018 alle ore 11:06 Laurent Perron <
notifications@github.com> ha scritto:

**Comment by lperron** [comment]
Hi,

I managed to build and run JobshopSat.cs with everything on my linux box.
Do you have a small dataset such that I can try to optimize the model?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
But a jopshop is 350000 tasks is most likely untractable, unless you use
techniques like decomposition and Large Neighborhood Search, the best thing
you can do is sort you activities, and push them one by one on you tasks.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
From what I have seen on my machine, you are just hitting the memory limit of your computer.

**Comment by eticssrl** [comment]
So,what do you advise me to do?
Maybe break task collection in smaller parts and optimize any singular part?

Thank you.
Bye.

Il giorno mer 5 set 2018 alle ore 23:27 Laurent Perron <
notifications@github.com> ha scritto:

**Comment by lperron** [comment]
yes.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
