### ISSUE TITLE
Cost per vehicle

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#775]
Hello. C# 

Unclear to me how to assign a specific function or to parameterize the cost callback, **per vehicle.**

What does the **vehicleIndex** point to in setArcCostEvaluatorOfVehicle(arcCostCallback, **vehicleIndex**);

Can you provide an example?

**Comment by GuyBenhaim** [comment]
Tips anyone?

**Comment by GuyBenhaim** [comment]
Seems to work ok, after quick testing.

**Comment by Mizux** [comment]
Should be the index (i.e. id) of vehicle when you create your model with:
```python 
routing = pywrapcp.RoutingModel(num_locations, num_vehicles, depot)
```
**vehicleIndex** should be in `[0,num_vehicles[` so here you can set a specific arc cost callback for each vehicles (note you can reuse the same callback several time e.g. 10 vehicles like 
 6 bikes,  3 cars, 1 trucks)
