### ISSUE TITLE
Python Suppress Output doesn't work

### ISSUE THREAD

**Issue by rummens** [google/or-tools#776]
Hello,

I am trying to disable the output of the Google Opt Tools in Python. I don't want to have the dozens of Solution Infeasible entries on the console since this can be a normal state that should be handled by the program.

I tried to deactivate the output using the function Suppress Output but this does not work. (solver.SuppressOutput())

Any suggestions what goes wrong?

Thank you!

**Comment by lperron** [comment]
This is incomplete.

Which solver? I guess the linear solver.
Which underlying solver?

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by rummens** [comment]
Sorry, yes its about the linear solver. The underlying solver is Glop

**Comment by lperron** [comment]
I guess some warnings are too verbose.

Can you paste the spurious output?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by rummens** [comment]
Yes, sure:
The code looks as follows:
`solver = pywraplp.Solver('LinearProgram', pywraplp.Solver.GLOP_LINEAR_PROGRAMMING)
     solver.Clear()
    solver.SuppressOutput()`

And in a sub function of that:
`result_status = solver.Solve()`

The output is then:

`E0802 07:07:01.384132  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.384227  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.384320  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.384413  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.384640  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.384737  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.384830  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.384924  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385017  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385110  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385305  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385327  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385370  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385386  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385408  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385426  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385572  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385594  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385646  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385664  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385679  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385694  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385715  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385735  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385869  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385891  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385953  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.385972  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.386039  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.386056  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.386070  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.386085  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.386111  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE
E0802 07:07:01.386132  3332 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE`

I know why no solution exists, I just want to prevent the output :-)

Thanks

**Comment by lperron** [comment]
Actually,

bool MPSolverInterface::CheckSolutionExists() const {
  if (result_status_ != MPSolver::OPTIMAL &&
      result_status_ != MPSolver::FEASIBLE) {
    LOG(DFATAL) << "No solution exists. MPSolverInterface::result_status_ =
"
                << result_status_;
    return false;
  }
  return true;
}

You are trying to access the solution (value, dual value, reduces cost...)
while the status is not optimal or feasible.
Can you check the status before accessing solution values?


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by rummens** [comment]
Hello,
thanks for the answer. That was the solution, sorry for this stupid mistake and thanks again for your help :-)

**Comment by mlh621** [comment]
Hello! I am having the same issue, but using the python interface to the solver. 

If I understand the solution to this problem , it seems the recommendation is to call CheckSolutionExists before solving the problem with Solve(). Is this correct? If so, what is the python (pywraplp) interface that does the same? I am using the COIN-OR CBC MIP solver.

I am finding the github repo for the ortools project difficult to navigate since the python interface is a wrapper for the C++ & related code. It is not always clear what is objects and data are being passed back and forth with the wrapper, what is available in python, and what is just part of the C++ code base. 
Thanks for your help!

**Comment by stradivari96** [comment]
You have make sure that a solutions exists
```python
if status in [pywraplp.Solver.OPTIMAL, pywraplp.Solver.FEASIBLE]:
```
before calling:
```
variable.solution_value()
```

**Comment by mlh621** [comment]
Ahhh, ok! I was using/saving the status after using running an equivalent to `myvar = mypywrapsolver.Solve()`, but did not use that to before calling `solution_value()`. I was doing this in some experiments I was running and expected to receive some with "infeasible" returned given the nature of the problem, but did not know that is what/how it would return the infeasible information. That makes sense - Infeasible problem means no variable values to retrieve. Great. Thanks for the quick reply!

**Comment by psarka** [comment]
Hi all,

I can't get any advice in this thread to work, or I don't understand it. Here are two examples, where I can't suppress neither a warning, nor an error:

```python
from ortools.linear_solver import pywraplp

solver = pywraplp.Solver('LP', pywraplp.Solver.GLOP_LINEAR_PROGRAMMING)
solver.SuppressOutput()

solver.Constraint(1, -1).SetCoefficient(solver.NumVar(-1, 1, 'x'), 1)

if solver.Solve() in [pywraplp.Solver.OPTIMAL, pywraplp.Solver.FEASIBLE]:
    print('success!')
```
Result is 
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1015 16:07:23.521478 97332 linear_solver.cc:1218] Constraint auto_c_000000000 (0) has contradictory bounds: lower bound = 1 upper bound = -1
```

And for this one
```python
from ortools.linear_solver import pywraplp

solver = pywraplp.Solver('LP', pywraplp.Solver.GLOP_LINEAR_PROGRAMMING)
solver.SuppressOutput()

x = solver.NumVar(1, -1, 'x')

if solver.Solve() in [pywraplp.Solver.OPTIMAL, pywraplp.Solver.FEASIBLE]:
    print('success!')
```

I get
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
E1015 16:11:45.878917 97536 lp_solver.cc:143] The given linear program is invalid. It contains NaNs, infinite coefficients or invalid bounds specification. You can construct it in debug mode to get the exact cause.
```

I would like to be able to suppress both of these, and I can't. I don't seem to have access to InitGoogleLogging from python, and contextmanager.redirect_stderr does not work as well (probably a different process is created somewhere).

**Comment by lperron** [comment]
I have a workaround.

import ortools.sat.python.cp_model

model = cp_model.CpModel()
solver = cp_model.CpSolver()
solver.solve(CpModel)

This will call InitGoogleLogging() and should disable the warnings.

Le jeu. 15 oct. 2020 à 16:16, Paulius Šarka <notifications@github.com> a
écrit :

**Comment by psarka** [comment]
Some progress, but not there yet. With this addition, the `Logging before InitGoogleLogging ...` line goes away, so the InitGoogleLogging is indeed called. However, the other lines still remain, but without the timestamps and line numbers. 


So the full program

```python
from ortools.sat.python import cp_model
from ortools.linear_solver import pywraplp

cp_model.CpSolver().Solve(cp_model.CpModel())

solver = pywraplp.Solver('LP', pywraplp.Solver.GLOP_LINEAR_PROGRAMMING)
solver.SuppressOutput()

x = solver.NumVar(1, -1, 'x')

if solver.Solve() in [pywraplp.Solver.OPTIMAL, pywraplp.Solver.FEASIBLE]:
    print('success!')
```

Now prints
```
The given linear program is invalid. It contains NaNs, infinite coefficients or invalid bounds specification. You can construct it in debug mode to get the exact cause.
```
to stderr.
