### ISSUE TITLE
several solutions in routingmodel?

### ISSUE THREAD

**Issue by bcoghe** [google/or-tools#777]
I'm using google OR tools (python) to solve a vehicle routing problem. Now, as the solution given is not optimal, is there a way to get several solutions meeting the requirements?

At this moment I am using following functions to solve the problem:

```
routing = pywrapcp.RoutingModel(tsp_size, num_routes, depot)
assignment = routing.SolveWithParameters(search_parameters)
```

**Comment by lperron** [comment]
No and no plans.

Sorry
