### ISSUE TITLE
Update Notebooks?

### ISSUE THREAD

**Issue by kmader** [google/or-tools#778]
Many of the jupyter notebooks appear to be copy and pasted python scripts and contain code that is a little bit unusual in jupyter notebooks like ```if __name__=="__main__"``` it might be good to update some of these. As this is a google project it would also probably be cool to have collaboratory links for a few notebooks as well.

**Comment by lperron** [comment]
Note that I convert python examples into notebooks with tools/export_to_ipynb.py.
So we could improve the script to remove the __name__ and just call main.

**Comment by kmader** [comment]
I hadn't seen that script. It would probably be cool to split cells at every double blank line and put comments into markdown cells. It might also make sense to add notebook testing to Travis to make sure errors/refactors get noted

**Comment by lperron** [comment]
ambitious :-) but great
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 2 août 2018 à 11:26, Kevin Mader <notifications@github.com> a
écrit :

**Comment by kmader** [comment]
Also it might be interesting to have a few colab examples which work natively from github
https://colab.research.google.com/github/google/or-tools/blob/master/examples/notebook/jobshop_ft06_sat.ipynb

but it would require prepending the first cell with 
```
!pip install ortools svgwrite
!pip install 'plotly>=2.0'
``` 
which would be considered pretty bad form for the standard notebooks.

**Comment by lperron** [comment]
Actually, you need a local server.
We just need instructions to setup a local server with ortools loaded,
along with dependencies.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by kmader** [comment]
@lperron so colab runs both locally and on google compute engine (most people run it on GCE since they give you free GPUs). The standard-ish practice seems to be just adding a `!pip` command to the first cell (https://github.com/tensorflow/hub/blob/master/examples/colab/action_recognition_with_tf_hub.ipynb)

**Comment by lperron** [comment]
I meant to run notebooks on github, you need to have a local backend.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 3 août 2018 à 01:35, Kevin Mader <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
I have updated most of the notebooks to remove the main() and if __app__ == main() parts.
Splitting into blocks need to be improved and I disabled it for the time being.

**Comment by kmader** [comment]
Cool! Thanks
