### ISSUE TITLE
Symlinks flattened for libraries on new macOS release packages

### ISSUE THREAD

**Issue by kspinka** [google/or-tools#784]
Symbolic links are flattened into actual copies on macOS.

Example:
```
-rwxr-xr-x@ 1 kris  staff   310K Jul 24 19:56 libOsi.1.12.9.dylib
-rwxr-xr-x@ 1 kris  staff   310K Jul 24 19:56 libOsi.1.dylib
-rwxr-xr-x@ 1 kris  staff   310K Jul 24 19:56 libOsi.dylib
```

Linux builds look fine however:
```
-rwxr-xr-x@ 1 kris  staff   395K Jul 24 22:13 libOsi.so.1.12.9
lrwxr-xr-x@ 1 kris  staff    16B Jul 24 22:13 libOsi.so.1 -> libOsi.so.1.12.9
lrwxr-xr-x@ 1 kris  staff    16B Jul 24 22:13 libOsi.so -> libOsi.so.1.12.9
```

**Comment by lperron** [comment]
Thanks for the report. We should fix it in the next release.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 2 août 2018 à 13:26, Kristofer Spinka <notifications@github.com> a
écrit :

**Comment by Mizux** [comment]
To be sure are you talking about this archive: https://github.com/google/or-tools/releases/download/v6.8/or-tools_MacOsX-10.13.6_v6.8.5452.tar.gz ?
