### ISSUE TITLE
MPSolver::SetStartingLpBasis not available in JAVA

### ISSUE THREAD

**Issue by ddeSide** [google/or-tools#789]
In the C++ interface, the MPSolver used to solve LP problems have a function `SetStartingLpBasis()`
https://github.com/google/or-tools/blob/842d1a4d24273acd3a091037eefcf545cc5a1ad1/ortools/linear_solver/linear_solver.h#L509-L529
used to force the starting point of the search. I'm using the Java version of OR-Tools and unfortunately this function isn't available in Java.

Would it be possible to add it?

I tried to add it myself by editing the file [ortools/linear_solver/java/linear_solver.i](https://github.com/google/or-tools/blob/master/ortools/linear_solver/java/linear_solver.i) but this function use vectors as input and I didn't succeed to correctly map the C++ `const std::vector<MPSolver::BasisStatus>&` into a Java `BasisStatus[]`. Any advice?

Thanks for your help.

**Comment by Mizux** [comment]
need to update vector.i + add test unit to check.
I prefer to postpone to v7.1 than breaking the incoming v7.0

**Comment by lperron** [comment]
Tough on the SWIG part when wrapping enums.

**Comment by lperron** [comment]
Will not happen in MPSolver as it is in maintenance mode.

I hope this is planned for MathOpt
