### ISSUE TITLE
Applying state-dependent ArcCost

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#791]
Please consider the specific ambition:  Penalize any vehicle that travels empty (no load) between any 2 Nodes per each mile/minute traveled.  Any way to achieve this w/o using DependentDimension (#339) ?

Naturally, I do not know in advance which vehicle will travel between which nodes ...

**Comment by Mizux** [comment]
If you have AddDimensionDependentDimensionWithVehicleCapacity binded in your language does it fix your problem ?

**Comment by GuyBenhaim** [comment]
This feature should allow many interesting things!

But can that DependentDimension affect the ArcCost (which the solver minimizes) or should be used to apply additional contraints?
If the latter, we could probably apply Max on the cumulative value of this dimension, or maybe try to minimize that value? Not sure ...

**Comment by Mizux** [comment]
You're right `AddDimensionDependentDimensionWithVehicleCapacity()` will affect the local search when trying to optimize the route not the "ArcCost" used during the first strategy step.

also unfortunately this "cost dimension" has no name so you can't use `Dimension* GetDimensionOrDie("name")` on it :disappointed:

**Comment by GuyBenhaim** [comment]
(hoping it will be added ...) So using AddDimensionDependentDimensionWithVehicleCapacity() can still allow directing the solver to minimize travel with zero-load during the local search?

Is there any better explanation/example of using DependantDimension, on top of a few lines found in Routing.h 

(  // Creates a dimension with transits depending on the cumuls of another
  // dimension. 'pure_transits' are the per-vehicle fixed transits as above.
  // 'dependent_transits' is a vector containing for each vehicle a function
  // taking two nodes and returning a function taking a dimension cumul value
  // and returning a transit value. 'base_dimension' indicates the dimension
  // from which the cumul variable is taken. If 'base_dimension' is nullptr,
  // then the newly created dimension is self-based.)

**Comment by Mizux** [comment]
Unfortunately I didn't have time to work on #574 currently

**Comment by GuyBenhaim** [comment]
Any partial modules/steps that I could help with and make this happen?

**Comment by Mizux** [comment]
I would say yes since the ArcCost are part of the objective cost computation and the solver will try to minimize it...

**Comment by lperron** [comment]
This feature is still experimental.
I recommend not using it for the time being.
