### ISSUE TITLE
Missing Python implementation of MakeAbs for LP

### ISSUE THREAD

**Issue by rummens** [google/or-tools#792]
Hi, 
i am using the GLOP solver to solve a linear problem and I need to add a constraint which depends on the difference of two values. These values are not fixed but are both equations of other VariableExpr objects and NumVars. 

So I need the absolute difference of those values but it seems that the implementation for the abs function is missing in the or-tools Python wrapper? The [documentation](https://developers.google.com/optimization/reference/constraint_solver/constraint_solver/Solver/) states that in C++ a function MakeAbs exists. Where is this in Python, I can't find it in the files?

Thanks

**Comment by Mizux** [comment]
Hi,

usually python methods are defined in the swig file https://github.com/google/or-tools/blob/master/ortools/linear_solver/python/linear_solver.i

However on python we provide a natural language API here: https://github.com/google/or-tools/blob/master/ortools/linear_solver/linear_solver_natural_api.py

I think you want to add (PR welcome) an `abs` opname...

**Comment by rummens** [comment]
Hi, 
I looked through both of the files but there is no reference to an abs function, nor an implementation of it.

**Comment by lperron** [comment]
abs is not linear.
You need to linearize it.

This is the first link found by Google :-)

https://optimization.mccormick.northwestern.edu/index.php/Optimization_with_absolute_values
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
