### ISSUE TITLE
CP solver - Use Add(Bool,Implication,etc) with BoundIntegerExpression

### ISSUE THREAD

**Issue by Phibedy** [google/or-tools#793]
Hi,
I am trying to use the new cp solver, but I am not sure if or how it is possible:
``` python3
from ortools.sat.python import cp_model
model = cp_model.CpModel()
solver = cp_model.CpSolver()

a = model.NewIntVar(0,1,"")
b = model.NewIntVar(0,1,"")
model.AddImplication(a != 0,b > 0)
```
throws
```
NotSupported: model.GetOrMakeBooleanIndex(b >= 1)
```

Is there a workaround to make `b > 0` a BoolVar or do I have to use the old solver?

**Comment by Mizux** [comment]
Does this could fix your issue ?
```python
model.Add(b > 0).OnlyEnforceIf(a.Not())
```
src: https://github.com/google/or-tools/blob/master/ortools/sat/doc/channeling.md

**Comment by Phibedy** [comment]
@Mizux Thank you for answering that fast. In my case `a` is a timestamp and -1 says that no timestamp is set.

**Comment by Phibedy** [comment]
@Mizux Thank you again :)
