### ISSUE TITLE
setspancoefficient with slackvar?

### ISSUE THREAD

**Issue by bcoghe** [google/or-tools#795]
It says that the slack_max variable in a Dimension can be used to impose a constraint on waiting times (which is nice). But is it also possible to add these slack variables (or a term depending on them) to the cost of the solution? If so, can anyone give me a hint how?

I have found out that you can use setspancoefficient to nudge the solution to have shorter tours (in time), which uses cumulvar. But that does not really mean that you reduce the waiting times as it might just activate more vehicles. What I am looking for is something similar but with the slack variables.

The best possible solution that I can think of right now is to use setspancoefficient in combination with fixedcost for vehicles but it's then hard to find a good tradeoff between both values.

Thx in advance!

**Comment by Mizux** [comment]
Since `Cumul(nextNode) = Cumul(previousNode) + transitCost(previousNode, nextNode) + SlackVar(previousNode)`
I would say that an objectif on the CumulVar already take into account the slack value (yes with the same unit cost than the "regular" transit cost).

So the routing solver will try to minimize the SlackVar already...

**Comment by bcoghe** [comment]
But no option to set a different coefficient?

In my use case, it might be that a taxi while driving costs: wage of taxi driver + fuel
while waiting time only costs: wage

**Comment by hklarner** [comment]
to my understanding, extra dimensions do not affect the objective function directly, they are - as far as I can see - only used to formulate additional constraints, for example time windows. If you want to minimize `slack_max` for one of your dimensions I suggest to incrementally lower the value until no more solutions are found.
note: by lowering `slack_max` your solutions tend to have a higher total cost.

**Comment by bcoghe** [comment]
@hklarner , I'm pretty sure with setSpanCostCoefficient (or setGlobalSpanCostCoefficient) you can add a term to the objective function.
I'm also not looking to minize slack_max over all vehicles, but the sum of the slack_var over all vehicles.

**Comment by Mizux** [comment]
By default all "other" dimensions have a `setCoefficient()` to 0 so the are not taking into account in the objective.
For fuel, let's create a fuel dimension and add a coefficient to it -> here you need to find your trade off `N fuel unit == one unit of arc cost` (with N being your coefficient)...

**Comment by bcoghe** [comment]
ok, that makes sense. Thanks!
