### ISSUE TITLE
CP solver: (a == 0)==(b==0) constraint not working

### ISSUE THREAD

**Issue by Phibedy** [google/or-tools#796]
Hi,
I wonder why (a == 0)==(b==0) constraint is not working (finds no result) but no error is thrown.
```python3
from ortools.sat.python import cp_model
class SolutionPrinter(cp_model.CpSolverSolutionCallback):
    """Print intermediate solutions."""

    def __init__(self, variables):
        self.__variables = variables
        self.__solution_count = 0

    def NewSolution(self):
        self.__solution_count += 1
        for v in self.__variables:
            print('%s = %i' % (v, self.Value(v)), end = ' ')
        print()

    def SolutionCount(self):
        return self.__solution_count


model = cp_model.CpModel()
solver = cp_model.CpSolver()

a = model.NewIntVar(0,1,"a")
b = model.NewIntVar(0,1,"b")
model.Add((a == 0) == (b==0))

# Call the solver.
solution_printer = SolutionPrinter([a, b])
status = solver.SearchForAllSolutions(model, solution_printer)
```
Using the old cp solver it works.

**Comment by lperron** [comment]
No, model.Add() accepts linear in/equations.

(a == 0) is not a variable.

Please have a look at
https://github.com/google/or-tools/blob/master/ortools/sat/doc/channeling.md
to define a boolean variable equal to (a == 0).

Thanks.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Phibedy** [comment]
@lperron Thank you, but that code is quite messy for the simple task or am I doing it wrong?
```python
a = model.NewIntVar(0,1,"a")
b = model.NewIntVar(0,1,"b")

a_bool = model.NewBoolVar("a_bool")
b_bool = model.NewBoolVar("b_bool")
model.Add((a==1)).OnlyEnforceIf(a_bool)
model.Add((a!=1)).OnlyEnforceIf(a_bool.Not())
model.Add((b==1)).OnlyEnforceIf(b_bool)
model.Add((b!=1)).OnlyEnforceIf(b_bool.Not())
model.Add(a_bool == b_bool)
```

I am new to or-tools, but shouldn't it be possible to overload == < operators to do this automatically or somehow different?

**Comment by Mizux** [comment]
mmm I think you must use the same "bool" literal

```python
a = model.NewIntVar(0,1,"a")
b = model.NewIntVar(0,1,"b")
c_bool = model.NewBoolVar("a_bool")

model.Add((a==1)).OnlyEnforceIf(c_bool)
model.Add((a!=1)).OnlyEnforceIf(c_bool.Not())
model.Add((b==1)).OnlyEnforceIf(c_bool)
model.Add((b!=1)).OnlyEnforceIf(c_bool.Not())
```

when c is true both `a==1` and `b==1` are true, and both false otherwise.

**Comment by Phibedy** [comment]
@Mizux yes you are right, quite stupid that I used two bools and forced them to be the same at the end `
model.Add(a_bool == b_bool)`...
Thank you :+1:
