### ISSUE TITLE
R package/interface

### ISSUE THREAD

**Issue by edi-bice** [google/or-tools#798]
Please consider implementing an R package/interface.

**Comment by lperron** [comment]
This is a large effort, and we have nobody in the team with R expertise.

If you are on windows, you can have a look at:

https://stackoverflow.com/questions/51860181/how-can-i-use-r-cran-roi-to-replace-google-ortools-linear-solver

**Comment by jtelleriar** [comment]
Could you consider such implementation? R has a number of advantages over Python for Dynamic Programming, such as:
a) Copy-On-Modify Semantics: Less Error Prone.
b) Automatic Method Dispatch (You do not have to think which Library and Objects goes with each function, this is handled automatically), and Automatic Conflict Resolution with different libraries methods (https://github.com/r-lib/conflicted). 
c) Infix Notation: Successive Method and Function Chaining with Pipe Operator (%>%), creating readable   code and allowing to code dynamically faster.
d) Each function normally better Documented than Python, with code examples and demos.

**Comment by lperron** [comment]
I do not have the time not the expertise to develop a R interface.

I will accept pull request though.

Le lun. 8 juil. 2019 à 09:28, jtelleriar <notifications@github.com> a
écrit :

**Comment by lejarx** [comment]
Hope for an R interface as well. Otherwise, anyone has alternatives which use R? Thanks
