### ISSUE TITLE
While cross compiling or-tools for aarch64 getting Linking error.

### ISSUE THREAD

**Issue by TaherLkdw** [google/or-tools#799]
Hi,
I have downloaded the or-tools source code of c++ for UBUNTU 16.04 and built it and it generated the libraries.
But when i tried to link that libraries in my project it says incompatible library as below:

```bash
skipping incompatible /path to lib/libortools.so when searching for -lortools
cannot find -lortools
collect2: error: ld returned 1 exit status
```
When I tried to debug i got to know the compiler used in my project is different. 

How to make these libraries compatible to my project environment or how to change compiler for the source code and where and what to change?

**Comment by Mizux** [comment]
ubuntu 16.04 we use the default gcc compiler.

You have to rebuild from source try to look at:
https://github.com/google/or-tools/blob/master/makefiles/Makefile.unix.mk#L105

**Comment by TaherLkdw** [comment]
Thank you for the quick response!

After updating my compiler there is make third_party command is sufficient?

**Comment by TaherLkdw** [comment]
That was really helpful. After tweaking the build command for my compiler and disabling the zlib building, i am getting the new error while Linking CXX shared library libprotobuf.so as below:

[ 53%] Generating /home/lat6kor/samba/IntelligentRoutingCode/googleOrTools/ortoolsUbuntu14/or-tools/dependencies/sources/protobuf-3.5.1/src/google/protobuf/compiler/js/well_known_types_embed.cc
./js_embed: 2: ./js_embed: Syntax error: ")" unexpected
CMakeFiles/libprotoc.dir/build.make:64: recipe for target '/home/lat6kor/samba/IntelligentRoutingCode/googleOrTools/ortoolsUbuntu14/or-tools/dependencies/sources/protobuf-3.5.1/src/google/protobuf/compiler/js/well_known_types_embed.cc' failed
make[3]: *** [/home/lat6kor/samba/IntelligentRoutingCode/googleOrTools/ortoolsUbuntu14/or-tools/dependencies/sources/protobuf-3.5.1/src/google/protobuf/compiler/js/well_known_types_embed.cc] Error 2
make[3]: *** Deleting file '/home/lat6kor/samba/IntelligentRoutingCode/googleOrTools/ortoolsUbuntu14/or-tools/dependencies/sources/protobuf-3.5.1/src/google/protobuf/compiler/js/well_known_types_embed.cc'
make[3]: Leaving directory '/home/lat6kor/samba/IntelligentRoutingCode/googleOrTools/ortoolsUbuntu14/or-tools/dependencies/sources/protobuf-3.5.1/build_cmake'
CMakeFiles/Makefile2:147: recipe for target 'CMakeFiles/libprotoc.dir/all' failed
make[2]: *** [CMakeFiles/libprotoc.dir/all] Error 2
make[2]: Leaving directory '/home/lat6kor/samba/IntelligentRoutingCode/googleOrTools/ortoolsUbuntu14/or-tools/dependencies/sources/protobuf-3.5.1/build_cmake'
Makefile:129: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/lat6kor/samba/IntelligentRoutingCode/googleOrTools/ortoolsUbuntu14/or-tools/dependencies/sources/protobuf-3.5.1/build_cmake'
makefiles/Makefile.third_party.unix.mk:198: recipe for target 'dependencies/install/lib/libprotobuf.so' failed
make: *** [dependencies/install/lib/libprotobuf.so] Error 2
./js_embed: 1: ./js_embed: ELF��@@�N@@: not found

Please provide any clue.

**Comment by Mizux** [comment]
Well cross compiling is not just changing the compiler...

I don't want to be rude, but seriously you should try to first understand how the cross compilation work on Makefile/CMake. e.g. take a look at https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html

Here you can found a C++ CMake project cross compiling:
https://github.com/google/cpu_features look at the travis.xml and log on travis to understand how it works.
note: Or-Tools will use this scheme also once I find time to do it...

Here an unfinished CMake C++ Android Ndk/Qt test
https://gitlab.com/Mizux/qtdroid
