### ISSUE TITLE
CP solver: XOr with OnlyEnforceIf not supported

### ISSUE THREAD

**Issue by Phibedy** [google/or-tools#800]
I need a lot of `XOrs` for my model which are `OnlyEnforceIf`, but I can't get them to work (Not implemented?). I wonder because it is the equal to `AddSumConstraint([...,1,1])` which supports `OnlyEnforceIf`.

``` python
from ortools.sat.python import cp_model
class SolutionPrinter(cp_model.CpSolverSolutionCallback):
    """Print intermediate solutions."""

    def __init__(self, variables):
        self.__variables = variables
        self.__solution_count = 0

    def NewSolution(self):
        self.__solution_count += 1
        for v in self.__variables:
            print('%s = %i' % (v, self.Value(v)), end = ' ')
        print()

    def SolutionCount(self):
        return self.__solution_count


model = cp_model.CpModel()
solver = cp_model.CpSolver()
a = model.NewBoolVar("a")
b = model.NewBoolVar("b")
c = model.NewBoolVar("c")
model.AddSumConstraint([a,b],1,1).OnlyEnforceIf(c) #works
model.AddBoolXOr([a,b]).OnlyEnforceIf(c) #does not work
solution_printer = SolutionPrinter([a,b,c])
# Call the solver.
solver.Solve(model)
status = solver.SearchForAllSolutions(model, solution_printer)
```

XOr with OnlyEnforceIf gives:
`cp_model_solver.cc:888] Check failed: !HasEnforcementLiteral(ct) Not supported.`

**Comment by Mizux** [comment]
Def of `AddSumConstraint()`
https://github.com/google/or-tools/blob/master/ortools/sat/python/cp_model.py#L560

Def of `AddBoolXOr()`
https://github.com/google/or-tools/blob/master/ortools/sat/python/cp_model.py#L968

**Comment by lperron** [comment]
actually, it is a bit more tricky

xor(bool_var_array) is equivalent to sum(bool_var_array) % 2 == 1.

In your case, this is trivial. I need to change the propagator. I will have a look at it.

**Comment by lperron** [comment]
I have clarified the documentation about which constraints support enforcement literals.

I will close the issue now as I have no plan right now to implement this, as you request is much simpler than a reified general xor.

**Comment by lperron** [comment]
http://google.github.io/or-tools/python/ortools/sat/python/cp_model.html#Constraint.OnlyEnforceIf
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le lun. 27 sept. 2021 à 15:00, Tias Guns ***@***.***> a
écrit :

**Comment by lperron** [comment]
and source of truth:

https://github.com/google/or-tools/blob/b37d9c786b69128f3505f15beca09e89bf078a89/ortools/sat/cp_model.proto#L298
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
