### ISSUE TITLE
Pack VRP model via pyinstaller - Tkinter callback error

### ISSUE THREAD

**Issue by Westlife1002** [google/or-tools#802]
I packed the VRP model via pyinstaller (ver.3.3.1). When I run the .exe it reported below error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1702, in __call__
  File "VRP.py", line 530, in main
    search_parameters = pywrapcp.RoutingModel.DefaultSearchParameters()
ModuleNotFoundError: No module named 'ortools.constraint_solver.routing_parameters_pb2'

I could operate Tkinter GUI to control the running of VRP model without any issue if I run directly on the .py scripts. What is the problem here? How to fix?
Thanks

**Comment by KingDoum** [comment]
I have this problem, too. How did you solve it

**Comment by sghb** [comment]
Adding `--hidden-import ortools.constraint_solver.routing_parameters_pb2` to the pyinstaller call worked for me.  Under Windows, also `--hidden-import pkg_resources.py2_warn` was needed.
