### ISSUE TITLE
Linear solver

### ISSUE THREAD

**Issue by abvg9** [google/or-tools#803]
Hello :) 

I would like to know if it is possible to take all the solutions found with the resolver
MPSolver :: GLOP_LINEAR_PROGRAMMING. 

Thank you

**Comment by lperron** [comment]
I assume you mean all equivalent optimal solutions, as this is a LP, not a
MIP.

But, unfortunately no,
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
