### ISSUE TITLE
CP Sat: Maximize/Minimize early stopping on good solution

### ISSUE THREAD

**Issue by Phibedy** [google/or-tools#804]
I searched the source and could not find any method to stop the solver if the cost function meets a threshold or a `BoolVar` is true (related to #651).

Does adding an objective function change the search strategy, or does it just brute force all solutions?
Adding an objective function causes the `CpSolverSolutionCallback` to only be called if the objective is optimized and then only once, even if some results have the same objective value.

If it just brute forces the "optimal" solution, adding a `IntVar(INT_MIN,INT_MAX)` which represents objective instead of calling `model.Minimize(...)` function and a `CpSolverSolutionCallback` which evaluates the objective (terminates the process if threshold is reached) for each solution would be the way to go? My problem has a lot of solutions so finding a "optimal" solution is not possible. I just want a "good" one.

Adding a constraint like `model.Add(objective < threshold)` isn't something I would like to do as I still want a result if there are only bad solutions.

**Comment by Phibedy** [comment]
@lperron that's nice, didn't know one could add external bools. Never checked the C++ interface before but it seems to be more powerful. But I think I am or there is something missing:

What I would like to do:
```
while(timer < time_limit):
    state = solve(...)
    if objective(state) < threshold:
        break

```
* If I minimize the objective, the solution callback is not called so I can't trigger the `std::atomic<bool>` on a threshold, so it would run till `timer >= time_limit`
* If I add a `constraint obj >= threshold - 1` I would still need to stop it somehow if the threshold is satisfied if I use minimize, so I would just need to call solve? In addition I would not get a feasible solution if the threshold can't be satisfied in time.

A workaround I could think of is calculating the solution step by step (decrease the threshold). But I think it would be rather slow as it would always start with a new solution instead of reusing the old solution. Is it possible to reuse a solution?
``` python
model = ...
objective = ...
start = timer()
while True:
    time_limit = timer()-start
    #set time limit (C++ needed as not possible in python)
    state = solver.Solve(model)
    if state != 2: #no new feasible solution
      break
    obj_val = solver.Value(objective)
    model.Add(objective<obj_val)
```

**Comment by lperron** [comment]
This is not optimal as you loose the state of the sat solver after adding the new objective part.
The model do support hinting. You need to access the underlying cp_model proto inside the CpModel class. But even then, you loose the conflicts learned previously.

Why don't you just add 

    model.add(objective >= threshold)

This will stop as soon as objective < threshold. It is a bit weaker than what you proposed, but could do the trick.

The correct solution is to implement StopSearch() in the cp solution callback. I need to to it correctly.

**Comment by lperron** [comment]
I have pushed StopSearch in java, C#
I need to tweak the python layer to make it work, it should happen this
week.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Phibedy** [comment]
Thank you very much :+1:

**Comment by lperron** [comment]
Implemented and documented in all 4 languages.

[(https://github.com/google/or-tools/blob/master/ortools/sat/doc/solver.md#stopping-search-early)]

Closing the issue.

**Comment by Phibedy** [comment]
That's great, when will the pip package be updated?

**Comment by lperron** [comment]
early september I guess.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by giuseppe-coco** [comment]
> https://github.com/google/or-tools/blob/master/ortools/sat/doc/solver.md

Hi, this is not available.

``` c++
Model model;
std::atomic<bool> stopped(false);
model.GetOrCreate<TimeLimit>()->RegisterExternalBooleanAsLimit(&stopped);

// .....

if (num_solutions >= kSolutionLimit) {
  stopped = true;
}
```

The solver does not stop printing solutions when it reaches k solution. It prints all solutions. 
Could you please help me?

**Comment by lperron** [comment]
https://github.com/google/or-tools/issues/4997
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le jeu. 22 janv. 2026 à 11:35, Giuseppe Coco ***@***.***> a
écrit :
