### ISSUE TITLE
How to see which constraint rejects initial solution

### ISSUE THREAD

**Issue by fonsecadeline** [google/or-tools#811]
Hi, 

I am trying to provide a customized initial solution to my ORtools CP model but this solution is rejected.
The only message I get is 

> Failing constraint = IsDiffCstCt(Nexts14(437), 14, Active14(0))

Is there a way to output the model, or something, in order to understand which particular constraint is violated in my solution?

Thank you in advance

**Comment by lperron** [comment]
I suppose you are using the routing library.
There are no way to display the model in a useful way. It is large and mostly unparseable.

I suggest you pass gradually part of the solutions. 1 vehicle at a time, one part of the route at the time. It will be a more useful approach.
