### ISSUE TITLE
Missing wheel package for Python 3.6 for OS X

### ISSUE THREAD

**Issue by billzhong** [google/or-tools#812]
```
$ pip install ortools==6.8.5452
Collecting ortools==6.8.5452
  Could not find a version that satisfies the requirement ortools==6.8.5452 (from versions: 6.5.4527, 6.6.4656, 6.6.4659, 6.7.4957, 6.7.4973)
No matching distribution found for ortools==6.8.5452
```

> https://pypi.org/project/ortools/6.8.5452/#files

Only 2.7 and 3.7 wheel package available for Mac OS X.

**Comment by Mizux** [comment]
Yes 2.7 and 3.7 are the current brew available `python@2` and `python` package version.

**Comment by vpontis** [comment]
I understand the reasoning behind this -- it's annoying to maintain too many versions. 

But in the future, it might be nice to keep around a few different versions of Python. Right now Python 3.7 is pretty immature and a lot of libraries don't work with 3.7. Lots of things broke with `async` as a reserved keyword...

But I love OR Tools! Keep up the good work :).
