### ISSUE TITLE
CallBack

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#817]
Is there a way to use the Manhattan Callback and get its returned value? (not by the Solver itself.)
Something like:
```cpp
NodeEvaluator2 manhattan_cost_callback = new Manhattan(location, coeff);
int distance = manhattan_cost_callback(i , j);
```

Or must I copy the distance calculation into a dedicated function?

Guy

**Comment by Mizux** [comment]
I think it should work, why do you want to do it ?

**Comment by GuyBenhaim** [comment]
Thx
I would like to list the solution's Nodes and provide the distance/cost between each consecutive pair.
Not clear how to pass the first Node and second Node indices to the callback.

Also if it's just:  
int distance = manhattan_cost_callback

then VS indicates: Error	CS0029	Cannot implicitly convert type 'Google.OrTools.ConstraintSolver.NodeEvaluator2' to 'double'

**Comment by Mizux** [comment]
Well
`typedef RoutingNodeEvaluator2 NodeEvaluator2`
src: https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing.h#L216
Then
`typedef ResultCallback2<int64, RoutingNodeIndex, RoutingNodeIndex> RoutingNodeEvaluator2;`
src: https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing_types.h#L40
Then
```cpp
template <class R, class A1, class A2> class ResultCallback2 {
...
  virtual R Run(A1, A2) = 0;
```
src: https://github.com/google/or-tools/blob/master/ortools/base/callback.h#L76

So once you have instantiated your callback object:
```cpp
RoutingModel::NodeEvaluator2 manhattan_cost_callback = new Manhattan(location, coeff);
```
You can call it using:
```cpp
int distance = manhattan_cost_callback.Run(node_idx1, node_idx2);
```

**Comment by GuyBenhaim** [comment]
Using long no compiler error. (not int)
Will test later.
Thx
