### ISSUE TITLE
Pickup Delivery Problem Question

### ISSUE THREAD

**Issue by johny8228** [google/or-tools#818]
Hi,

I'm currently working on the implementation of PDP using C# and I have some issues.

In my use case I have a list of orders with pickups and deliveries which should be made by the same vehicle along the same route (no depot).What I want to achieve through my implementation is : 
- Minimize the number of vehicles used to deliver all orders. I achieved this by using SetFixedCostForAllVehicles. However I noticed one issue when unit testing this.
If the weight matrix has same distance/time between all nodes or the difference between the distance/time values is very small. The minimization of total number of vehicles fails. For 10 orders I have a solution with 10 vehicles even if I could deliver all with just one vehicle.
- Max time for a vehicle to complete the job to be 4h or around 4h.For this I used SetMax on the CumulVar for the time dimension I have setup. However in some scenarios if it's more optimal I would like to allow the algorithm to group the orders for more than 4h let's say 4h and 17 min. The SetMax it's a hard limit now and I would like to have a coefficient of flexibility.
- Min time of the job to be 2h for a vehicle. I tried to use SetMin on the CumulVar of the time dimension but in this case when using SetMin and SetMax it returns no solution.
In this case the algorithm should be intelligent enough to balance the orders in routes between 2h and 4h but to be flexible.

Use case exemple:
I have 10 orders and 8 orders can be delivered in 4 hours and 2 orders in 1 hour.
My current implementation will distribute these orders to two vehicles one for 4h and one for 1h.
I would prefer that the algorithm distributes them to 1 vehicle for 5h or for 2 vehicles with 2.5h instead.

Any indication on this it will be highly appreciated.

Thanks,
Ionut

**Comment by lperron** [comment]
1) Increase the penalty.
2) Use soft upper bounds.
3) Not sure there is always a solution for these. Maybe a soft lower bound somewhere.
