### ISSUE TITLE
How to pass seed route to TSP Solver

### ISSUE THREAD

**Issue by saj1919** [google/or-tools#819]
Is there any way to pass seed route to TSP solver ??
With some optimization I am getting a sub-sub-optimal path and now I want to use or-tools tsp solver to make it sub-optimal. But I didn't see any option to do that. 

I think if it is possible, ortool can save much time and produce good optimal route.
Please let me know about the same.

I am using python and referring to this page -->  https://developers.google.com/optimization/routing/routing_options

**Comment by lperron** [comment]
You can pass an assignment to Solve.
