### ISSUE TITLE
C# JobShop CP Solver: precedence with fixed days

### ISSUE THREAD

**Issue by eticssrl** [google/or-tools#823]
Hi,
I try to setup a jobshop solver that implement standard precedence (conjunctive constraints) but with a particular behaviour.
Some machine can start task at a particular day of week and stop task in another day.
For example:
I have a job with two task, the first one (T1) must be executed on machine 1 (M1) and the second one (T2) must be executed on machine 2 (M2). 
M2 can start task only on wednesday  and stop only on friday.
One solution can be T1 on M1 executed and completed on tuesday, T2 started on M2 on wednesday  and  finished on friday.

I try creating a constraint that calculate the day on T1End and then add all necessary day to reach the first wednesday.
There are two problems:
1. calculating the difference from first wednesday and the day of previous task has a bug and not always return the correct value (for example if previous task end on monday = 1 and I want to start next at wednesday = 3, the difference 3-1 return -2 and if I use abs, return 0...)
```
DayOfWeek startDay = config.BeginDate.DayOfWeek;
var dayEnd = ((long)startDay + dayPreviousFromBeginning) % 7;
// dayEnd = 1

// weekday request to delivery (constant value = 3)
var cweekdayDelivery = solver.MakeIntConst((long)weekdayDelivery);

var diff =solver.MakeAbs (cweekdayDelivery - dayEnd);
// diff = 0 and without MakeAbs diff = -2 ????
```
2. how can I constraint task 2 to start on first FREE wednesday? (the first wednesday may be a festivity day or may be overloaded)

Thank you,
Bye, Nicola

**Comment by lperron** [comment]
To set an availability schedule on a machine, just add fixed intervals to the no_overlap/disjunctive constraint that will forbid other tasks to execute on those day.

See https://github.com/google/or-tools/blob/master/ortools/sat/doc/scheduling.md#nooverlap-constraint

Now, you can have a look at the gate scheduling problem. In this example, 2 optional intervals var are created for each task, And a boolean variable is created to specify which of the two machines are performing this task.

To implement start schedule, just restrict the domain of the start of the task on m2.

start_on_m2 = model.NewEnumeratedIntVar([first Wed 0:00, first Wed 23:59, second Wed 0:00, second Wed 23:59...]

I use the CP-SAT for this. Does this solve your problem?

**Comment by eticssrl** [comment]
Thank you.
I create a set of interval in CP that corrisponds to "no working" time and
than I added to a non overlapping contraint.

Il giorno mer 5 set 2018 alle ore 23:43 Laurent Perron <
notifications@github.com> ha scritto:
