### ISSUE TITLE
nosets, bool_lin_eq, int_mod, indomain_random, and more

### ISSUE THREAD

**Issue by glebbelov** [google/or-tools#826]
Hi, it would be great to get my model solved.
To get it compiled (with current minizinc develop), including "nosets.mzn" is necessary in `minizinc_cp/redefinitions.mzn` but also handling `bool_lin_eq`, `int_mod`, and `indomain_random` at least. I successfully redefined `bool_lin_eq` and `int_mod` but cannot `indomain_random` (it is essential). However, replacing `indomain_random` by `indomain_int` still results in error:

Not supported
```bash
*** Check failure stack trace: ***
    @     0x7f938eb752f8  google::LogMessage::Fail()
    @     0x7f938eb7523f  google::LogMessage::SendToLog()
    @     0x7f938eb74bb4  google::LogMessage::Flush()
    @     0x7f938eb77da9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f938e2c7bbb  _ZZN19operations_research3sat17ProductConstraintE7IntTypeINS0_20IntegerVaria
ble_tag_EiES3_S3_ENKUlPNS0_5ModelEE_clES5_
    @     0x7f938e2a1d8d  operations_research::sat::(anonymous namespace)::LoadIntProdConstraint()
    @     0x7f938e2a8b0a  operations_research::sat::(anonymous namespace)::LoadConstraint()
    @     0x7f938e2b2d75  operations_research::sat::(anonymous namespace)::SolveCpModelInternal()
```

Attaching 
[TEST_StemA.tar.gz](https://github.com/google/or-tools/files/2309108/TEST_StemA.tar.gz)

Thank you,
Gleb

**Comment by glebbelov** [comment]
Debian 8.11 (used binary: https://github.com/google/or-tools/releases/download/v6.7.2/or-tools_flatzinc_Ubuntu-14.04-64bit_v6.7.4981.tar.gz)

**Comment by lperron** [comment]
Hi, 

I have added nosets to redefinitions.
I have added support for bool_lin_eq and bool_lin_le.

I will have a look at indomain_random.

**Comment by glebbelov** [comment]
Hi,

thank you. int_mod was missing as well.

**Comment by lperron** [comment]
I added that in July.
It is not in 6.8. I will be in v6.9 (normally early September).

--Laurent
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
I tried to run the attached code, I get:

MiniZinc: evaluation error:

  model_3tLimVis.mzn:629:

  in call 'forall'

  in array comprehension expression

    with s = 2411

  model_3tLimVis.mzn:630:

  in binary '=' operator expression

  in call 'card'

  /Users/lperron/Work/or-tools/ortools/flatzinc/mznlib_sat//nosets.mzn:237:

  in let expression

  /Users/lperron/Work/or-tools/ortools/flatzinc/mznlib_sat//nosets.mzn:238:

  in call 'set2bools'

  /Users/lperron/Work/or-tools/ortools/flatzinc/mznlib_sat//nosets.mzn:15:

  in if-then-else expression

  /Users/lperron/Work/or-tools/ortools/flatzinc/mznlib_sat//nosets.mzn:16:

  in let expression

  Index set mismatch
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Nosets is a copy of the minizinc std.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
In the meantime, can you try without any search?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

Question, you have product of variables which are both positive and
negative?
This would be the first time this is used :-)

**Comment by glebbelov** [comment]
Yes I think I have such product.

Where is the attached code?

**Comment by lperron** [comment]
Then we did not implement it, as this was never requested, and it is quite
tedious.

I will see what I can do.

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Hello,

I have just pushed some presolve rule that translate x * b == y (where b is
a boolean variable) into b implies x == y, not b implies y == 0

+ I have pushed a fixed nosets,mzn file.

WIth this, I solve the problem you sent me in 3 seconds using 8 threads.

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by glebbelov** [comment]
Hi, thank you.

I get a feasible solution quickly, but not optimality proof.

I ran:
`mzn2fzn -G or-tools-sat TEST_StemA/MZN_CPX/model_3tLimVis_indMin.mzn TEST_StemA/MZN_CPX/3tLimVis_1_2618__.dzn -v -s && fzn-or-tools TEST_StemA/MZN_CPX/model_3tLimVis_indMin.fzn -a.
`

On Debian 8.11 (gcc 4.9.2), I get 'FLoating point exception'.

I obtained similar results to Opturion CPX 1.0.2 but I'd like to see how much can be improved when using indomain_random. These models are rolling horizons, so random choices can be better.

BTW I assume citing your CP2011 paper is ok.

**Comment by glebbelov** [comment]
Yes -p 8 or 3 solves optimally but not single-threaded. In Kubuntu 16.04.5.

What I mean by rolling horizons is that I solve many models representing a long schedule. Each previous solution is "previous fixed data" and affects new decisions. I'll check with Opturion if indomain_random helps

**Comment by lperron** [comment]
Single threaded, you would like to change the sat parameters

on the command line:

./bin/fz -l -s -p 1 ../../tmp/issue826.fzn  --params=linearization_level:0
-f


----------

==========

%% CpSolverResponse:

%% status: OPTIMAL

%% objective: 1051.000000

%% best_bound: 1051.000000

%% booleans: 18333

%% conflicts: 10043

%% branches: 771027

%% propagations: 44695171

%% integer_propagations: 17559025

%% walltime: 15.318000

%% usertime: 15.318000



The fact that -f improves it, IMO indicates that the random part is not a
good idea.


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by glebbelov** [comment]
I just heard you were at CP. Me too....

Is there a publication stating OR-Tools has LCG? I want to describe it, in particular in contrast to Gecode

**Comment by lperron** [comment]
No, source code. Just state the the last flatzinc solver uses sat, and cite
the or-tools web page on github.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by glebbelov** [comment]
Thank you Laurent, some feedback.

`-l -a -p 3 -s` is much worse than `-l -a -p 1 -s  --params=linearization_level:0`: on many horizons (there are about 260) the solution is very bad, although using the same CPU time limit. However the latter performs on average similar to just `-l -a -p 1 -s` (I use a 30s time limit).

indomain_random makes a few percent improvement for Opturion CPX, I think due to inter-horizon relations. OR-Tools' results are similar to CPX now, it's ok to leave the results as is, just letting you know.

**Comment by lperron** [comment]
Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
