### ISSUE TITLE
Provide initialization to pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING?

### ISSUE THREAD

**Issue by mucun1988** [google/or-tools#829]
When solving mixed integer programming using `or-tools`, I am wondering whether it is possible to provide an initialization/starting point to `pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING` to facilitate the solver towards faster solving.

**Comment by lperron** [comment]
This is supported in SCIP, Gurobi, and BOP.

Not in CBC.

I have no plan for CBC as it is unreliable, especially on small problems. (See #814).
