### ISSUE TITLE
How to speed up sat cp using strategies (counting elements in list and adding counts)

### ISSUE THREAD

**Issue by Phibedy** [google/or-tools#830]
I have a list of `IntVars` and want to count elements in it. Afterwards I want to add those counts.
Therefore I create a `BoolVar` for each element and possible element I want to count.
In my case:
 * without counting it takes 6 seconds
 * with counting each element it takes 10 seconds
 * adding all element counts to one total count takes 95 seconds

I also tried to add some redundant constraints which seems to make it even worse.
Are there some in-builds to do it, like count it without creating bools?

Example to show what I am doing in principle:
``` python
from ortools.sat.python import cp_model
from ortools.sat import sat_parameters_pb2
from timeit import default_timer as timer

##########################################
#Helper functions
def negate_boundary_interval(bounds):
    #max/min values from https://github.com/google/or-tools/blob/b535ae2ab1980a76ad808e309eab4a587ff25d92/ortools/sat/python/cp_model.py
    INT_MIN = -9223372036854775808
    INT_MAX = 9223372036854775807
    
    def checkbounds(a,b):
        return a <= b
    
    def cap_int_64(v):
        """Restrict v within [INT_MIN..INT_MAX] range."""
        if v > INT_MAX:
            return INT_MAX
        if v < INT_MIN:
            return INT_MIN
        return v
            
    res = []
    #check beginning
    a = INT_MIN
    b = bounds[0]-1
    if checkbounds(a,b):
        res += [cap_int_64(a),cap_int_64(b)]
    for i in range(1,len(bounds)-1,2):
        a = bounds[i]+1
        b = bounds[i+1]-1
        if checkbounds(a,b):
            res += [cap_int_64(a),cap_int_64(b)]
    #check end
    a = bounds[len(bounds)-1]+1
    b = INT_MAX
    if checkbounds(a,b):
        res += [cap_int_64(a),cap_int_64(b)]
    return res

def negate_boundary_integer_expression(bid):
    return cp_model.BoundIntegerExpression(bid.Expression(),negate_boundary_interval(bid.Bounds()))

def expr_to_bool(expr,model):
    eq = model.NewBoolVar("")
    if isinstance(expr,cp_model.IntVar):
        expr = expr >= 1
    elif isinstance(expr,cp_model.BoundIntegerExpression):
        pass
    else:
        raise ValueError("unsupported type {}".format(type(e)))
    model.Add(expr).OnlyEnforceIf(eq)
    model.Add(negate_boundary_integer_expression(expr)).OnlyEnforceIf(eq.Not())
    return eq

def exprs_to_bool(exprs,model):
    eqs = []
    for e in exprs:
        eq = expr_to_bool(e,model)
        eqs.append(eq)
    return eqs

#Helper functions end
##########################################


model = cp_model.CpModel()
jobs = []
for dt in range(0,24*4):
    jobs.append(model.NewIntVar(0,3,""))
counts = []

for c in range(3):
    c_count = model.NewIntVar(0,24*4,"")
    bools = exprs_to_bool([j==c for j in jobs],model)
    model.Add(c_count==sum(bools))
    counts.append((c_count,bools))

total_count = model.NewIntVar(0,24*4,"")
model.Add(total_count==sum([c[0] for c in counts]))

#makes it even slower?
#for i in range(len(jobs)):
#    model.AddBoolXOr([counts[c][1][i] for c in range(len(counts))])
    
      
solver = cp_model.CpSolver()
solver.parameters = sat_parameters_pb2.SatParameters(num_search_workers=3)
t = timer()
state = solver.Solve(model)
state,timer()-t

```

If I just add the intvar `total_count` without the constraint that it is the sum it is even slower(300 seconds). If I add another intvar `foo` it just needs 10 seconds?! :confused:
Therefore I think it is because of the selection type used but I am not sure how `AddDecisionStrategy` works.
* What happens if I have multiple `cp_model.CHOOSE_FIRST`. The first one in the model creation order is chosen?
* By default all variables are added to a selection:
  * Are all variables by default in one selection or has each one its own?
  * Are they removed from the default selection if they are set in one selection manually?
* What happens if one variable is in multiple selections? Is the first selection of a variable used? (I found it for another cp solver but I am unsure about cp sat)

For the list element counting `DecisionStrategyProto::CHOOSE_LAST` might be quite fast.
https://github.com/google/or-tools/blob/507cfbea267358e7cfea752e3ac8d14cf08a93f6/ortools/sat/cp_model.proto
Although I am not sure how to implement it in the `integer_search`.

Thank you :)

**Comment by lperron** [comment]
Here is my version:

    from ortools.sat.python import cp_model
    from ortools.sat import sat_parameters_pb2
    from timeit import default_timer as timer
    
    def add_count_eq(vars, value, count, model):
        boolvars = []
        for var in vars:
            boolvar = model.NewBoolVar('')
            model.Add(var == value).OnlyEnforceIf(boolvar)
            model.Add(var != value).OnlyEnforceIf(boolvar.Not())
            boolvars.append(boolvar)
        model.Add(count == sum(boolvars))
    
    model = cp_model.CpModel()
    jobs = []
    for dt in range(0,24*4):
        jobs.append(model.NewIntVar(0,3,""))
    counts = []
    
    for c in range(3):
        c_count = model.NewIntVar(0,24*4,"")
        add_count_eq(jobs, c, c_count, model)
        counts.append(c_count)
    
    total_count = model.NewIntVar(0,24*4,"")
    model.Add(total_count==sum(counts))
    
    solver = cp_model.CpSolver()
    solver.parameters.num_search_workers = 1
    t = timer()
    state = solver.Solve(model)
    print(state,timer()-t)

It outputs:
(2, 0.057016849517822266)

**Comment by Phibedy** [comment]
@lperron Thank you. The problem I think I have is, that the list with the numbers is linked to some other constraints, which causes really inefficient branching. I couldn't figure a way out for a small slow working example.

I tried to improve it using `DecisionStrategy`s but I am unsure how they work.
How I think they work:
* If more then one strategy is added, the variables of the first strategy are set first.
* If a variable is added to more then one strategy it is set using the first strategy in which it occures
* In each strategy each variables is assigned a `value` where the best (+random) variable is chosen using its value 
* If 'assign_all_variables` is set, variables with no strategy are added to a strategy using `FirstUnassignedVarAtItsMinHeuristic`, which is solved last.
* If multiprocessing is enabled, **the strategies are still calculated in order,** but some parameters are changed so it explores the search space by changing more or less random variable assignments.  
* The best way to calculate group of variables in order is to create strategies for each group and add them in the correct order.

If that's the case my helper functions are rather bad and overwriting operators make no sense (#810), as I can't use strategies on the created variables.

Thank you for your help

**Comment by Phibedy** [comment]
@lperron Thank you, I also checked C++ src, but I haven't understood how the sat combined with the cp solver works in detail yet. Are there any papers about the implemented solver?

**Comment by lperron** [comment]
https://people.eng.unimelb.edu.au/pstuckey/PPDP2013.pdf
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Phibedy** [comment]
Thank you,
for discrete optimization newbies like me, I found this also quite helpful:
* original paper: https://people.eng.unimelb.edu.au/pstuckey/COMP90046/lec/s9_lcg.pdf
* lecture from author (section 9): https://people.eng.unimelb.edu.au/pstuckey/COMP90046/lec/

**Comment by lperron** [comment]
Definitely.
