### ISSUE TITLE
Missing method SetLpAlgorithm(int value) for linear_solver/python bindings

### ISSUE THREAD

**Issue by petrochenkoav** [google/or-tools#832]
In swig file linear_solver.i we have some LP algorithms, such as MPSolverParameters::DUAL (PRIMAL, BARRIER),
https://github.com/google/or-tools/blob/842d1a4d24273acd3a091037eefcf545cc5a1ad1/ortools/linear_solver/python/linear_solver.i#L351-L355
which map
https://github.com/google/or-tools/blob/842d1a4d24273acd3a091037eefcf545cc5a1ad1/ortools/linear_solver/linear_solver.h#L1113-L1117

BUT we can't set them, because we don't have bindings for method SetLpAlgorithm() there.
https://github.com/google/or-tools/blob/842d1a4d24273acd3a091037eefcf545cc5a1ad1/ortools/linear_solver/linear_solver.h#L1481

**Comment by Mizux** [comment]
Method `virtual void SetLpAlgorithm(int value) = 0; ` is protected and from MPSolverInterface class.

To set LP algorithms you must use these methods:
https://github.com/google/or-tools/blob/842d1a4d24273acd3a091037eefcf545cc5a1ad1/ortools/linear_solver/python/linear_solver.i#L339-L340
which are:
https://github.com/google/or-tools/blob/842d1a4d24273acd3a091037eefcf545cc5a1ad1/ortools/linear_solver/linear_solver.h#L1164

so in Python it should be (not tested):
```python
from __future__ import print_function
from ortools.linear_solver import pywraplp

if __name__ == '__main__':
    # Create the linear solver with the GLOP backend.
    solver = pywraplp.Solver('simple_lp_program',
                             pywraplp.Solver.GLOP_LINEAR_PROGRAMMING)

    parameters = pywraplp.MPSolverParameters()
    parameters.SetIntegerParam(
            pywraplp.MPSolverParameters.LP_ALGORITHM,
            pywraplp.MPSolverParameters.DUAL)

    print('LP_ALGORITHM: {}'.format(
        parameters.GetIntegerParam(
            pywraplp.MPSolverParameters.LP_ALGORITHM)))

    parameters.SetIntegerParam(
            pywraplp.MPSolverParameters.LP_ALGORITHM,
            pywraplp.MPSolverParameters.PRIMAL)

    print('LP_ALGORITHM: {}'.format(
        parameters.GetIntegerParam(
            pywraplp.MPSolverParameters.LP_ALGORITHM)))

    parameters.SetIntegerParam(
            pywraplp.MPSolverParameters.LP_ALGORITHM,
            pywraplp.MPSolverParameters.BARRIER)

    print('LP_ALGORITHM: {}'.format(
        parameters.GetIntegerParam(
            pywraplp.MPSolverParameters.LP_ALGORITHM)))
```

should return
```sh
%make run SOURCE=tmp.py
PYTHONPATH=.:dependencies/sources/protobuf-3.6.1/python "/usr/bin/python3.5" tmp.py 
LP_ALGORITHM: 10
LP_ALGORITHM: 11
LP_ALGORITHM: 12
```
