### ISSUE TITLE
OptionalIntVar inconsisten behavior

### ISSUE THREAD

**Issue by Phibedy** [google/or-tools#834]
I am currently writing some test-cases to make sure I understand what I am doing, but I am not sure about the `OptionalIntVar`.
## If an `OptionalIntVar` is compared to a number instead of a `Variable` the result is different.

``` python
from ortools.sat.python import cp_model
class SolutionPrinter(cp_model.CpSolverSolutionCallback):
    """Print intermediate solutions."""

    def __init__(self, variables):
        self.__variables = variables
        self.__solution_count = 0

    def NewSolution(self):
        self.__solution_count += 1
        for v in self.__variables:
            print('%s = %i' % (v, self.Value(v)), end = ' ')
        print()

    def SolutionCount(self):
        return self.__solution_count


model = cp_model.CpModel()
solver = cp_model.CpSolver()

a = model.NewBoolVar("a")
b = model.NewIntVar(2,2,"b")
c = model.NewOptionalIntVar(1,1,a,"c")
model.Add(c>b)

solution_printer = SolutionPrinter([a,b,c])
solver.SearchForAllSolutions(model, solution_printer)
```
Results:
```a = 0 b = 2 c = 1```

``` python
a = model.NewBoolVar("a")
b = model.NewIntVar(2,2,"b")
c = model.NewOptionalIntVar(1,1,a,"c")
model.Add(c>2) #Causes infeasibility
```
Results:
```
INFEASIBLE
```

## If an `OptionalIntVar` is compared to a `Variable` the result depends on Variable bounds.
``` python
a = model.NewBoolVar("a")
b = model.NewIntVar(2,2,"b")
c = model.NewOptionalIntVar(1,1,a,"c")
model.Add(c>b)
```
Results:
```a = 0 b = 2 c = 1```

``` python
a = model.NewBoolVar("a")
b = model.NewIntVar(1,2,"b")
c = model.NewOptionalIntVar(1,1,a,"c")
model.Add(c>b)
```
Results:
```
a = 0 b = 1 c = 1 
a = 0 b = 2 c = 1 
```

```
a = model.NewBoolVar("a")
b = model.NewIntVar(1,2,"b")
c = model.NewOptionalIntVar(1,1,a,"c")
model.Add(c>b)
model.Add(b==1)
```
Result
```
a = 0 b = 1 c = 1 
```

``` python
a = model.NewBoolVar("a")
b = model.NewIntVar(1,1,"b")
c = model.NewOptionalIntVar(1,1,a,"c")
model.Add(c>b)
```
Results:
```
INFEASIBLE
```
This seems to be weird as it showed b=1 as a valid result in the example above.

## Others
It seems to ignore `b+c<1`
```
a = model.NewBoolVar("a")
b = model.NewIntVar(1,2,"b")
c = model.NewOptionalIntVar(1,1,a,"c")
model.Add(b+c<1)
```
Results:
```
a = 0 b = 1 c = 1 
a = 0 b = 2 c = 1 
```
but that is not the case as 
```
a = model.NewBoolVar("a")
b = model.NewIntVar(1,1,"b")
c = model.NewOptionalIntVar(1,1,a,"c")
model.Add(b+c<1)
```
Results
```
INFEASIBLE
```

Error with no Stacktrace
```
a = model.NewBoolVar("a")
b = model.NewIntVar(2,2,"b")
c = model.NewOptionalIntVar(1,1,a,"c")
model.Add(c>b+c)
```
Results:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0831 13:13:52.744407 17262 cp_model_solver.cc:3376] Check failed: SolutionIsFeasible(model_proto, std::vector<int64>(response.solution().begin(), response.solution().end())) 
*** Check failure stack trace: ***
```

### What I would expect (this is really subjective):
In the following `F` is a `OptionalVariable` where is_present is False.
`x <,>,>=,<= F`
x can take all values in its bounds (always true)

`x==F`
x can't take any value (always false)

`x!=F`
x can take all values in its bounds (always true)

`x+F < 1`
x values < 1

The sum of none present variables is same as just one none present variable:
`F1 + F2` < 1`
returns always true

`x==F1+F2`
x can't take any value (always false)

What if only none_present variables are in clause?
`F1 ==,!=,<,... F2`
Maybe the constraint should always be satisfied.

``` python
p = model.NewBoolVar("p")
v = model.NewOptionalIntVar(1,3,p,"v")
is_1 =model.NewBoolVar("1")
model.Add(v==1).OnlyEnforceIf(is_1)
model.Add(v!=1).OnlyEnforceIf(is_1.Not())
```
Returns currently
```
p = 0 v = 1 1 = 1 
p = 1 v = 1 1 = 1 
p = 1 v = 2 1 = 0 
p = 1 v = 3 1 = 0 
p = 0 v = 1 1 = 0 
```
But I think that p = 0 v = 1 1 = 1 should not be there.

I looked at the src and it seems to be rather difficult to implement a consistent behavior in the linearization part. What do you think about it?

**Comment by lperron** [comment]
Please do not use optional integer variable anymore, we are thinking of
removing them from the API.
The behavior is too complex, as you can see.

Any constraint that contains an optional variable will be ignored until the
enforcement literal is set to true.
Small linear constraint will propagate back to the literal, but this is all.

Any default behavior (optional = false => var is 0) is too problem
dependant.

So just remove that option. And add the optional literal of the variable on
the constraints it appears in.
Maybe implementing And(lit1, .., litn) <==> lit0 if there are multiple
optional variables in this constraint.

I will remove that from the API asap.

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Phibedy** [comment]
That's good to know,
maybe let this issue open till optional is removed for others :+1:

**Comment by lperron** [comment]
I have removed the code and changed all examples. Closing the issue.
