### ISSUE TITLE
Any way to add list of values instead of range in NewIntVar, Python

### ISSUE THREAD

**Issue by nikhilsarvaiye** [google/or-tools#835]
Hi Team,

I am trying to create a int variable with possible list of values instead of range, for CP Solver wrapper

what we have, ```python model.NewIntVar(4, 6, "y")```

what I want something like, ```python model.NewIntVar([4, 5,14,20,100], "list")```

The same type of variable is available in .Net as

```csharp public IntVar MakeIntVar(CpInt64Vector values)``` 

but I am not able to find like one in python.

Please suggest if I am missing anything?

**Comment by lperron** [comment]
NewEnumeratedIntVar

https://github.com/google/or-tools/blob/e6013f3e6dde822a185497f9fd49999360f2e82a/ortools/sat/python/cp_model.py#L514

Please note that the format is a flattened list of intervals
in you case
[4, 5, 14, 14, 20, 20, 100, 100] corresponding to [4,5] U [14, 14] U [20,
20] U [100, 100]

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 31 août 2018 à 15:52, Nikhil Sarvaiye <notifications@github.com> a
écrit :
