### ISSUE TITLE
The problem with Min function in CP solver

### ISSUE THREAD

**Issue by minaghavipour** [google/or-tools#839]
I have the following python code:

solver.Add(solver.Min([X[i, j] * D[i, j] for i, j in X if graph[i][j]['type'] == 'flight']) == a * 1440 + T)

where X, a and T are decision variables. Although the value returned by Min function can not be zero, but the solver assigns zero value to the decision variables a and T. The point is that this code works correctly with Max function.
Could you please help me about this problem?

**Comment by lperron** [comment]
Can you send me a full example ?

**Comment by minaghavipour** [comment]
The full code is very long and complicated. I just can explain the before-mentioned code in more detail. The constant D specifies the minutes spent since 2000 and by that code I want the decision variable T to have the minutes in that specific day, i.e. for date 09/04/2018 10:42, T must be equal to 10 * 60 +42.   
```
    a = solver.IntVar(0, 365, 'a')
    T = solver.IntVar(0, 1439, 'T')
    X[i, j] = solver.BoolVar('x[%s,%s]' % (i, j))
    solver.Add(solver.Min([X[i, j] * D[i, j] for i, j in X if graph[i][j]['type'] == 'flight']) == a * 1440 + T)
```

**Comment by lperron** [comment]
You should not do the date computation in the model, do the translation
before.

Just solve your planning/scheduling problem in minutes from the start of
the schedule, and convert that to date  after the solution is found.
Same thing for your data, convert all input data into minutes from the
start.

On the Min part,

X[i, j] is boolean. If one is false, its value is 0. Thus the Min() will
likely be 0 if the D[i, j] >= 0.


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 4 sept. 2018 à 08:16, minaghavipour <notifications@github.com> a
écrit :

**Comment by minaghavipour** [comment]
as I said in the previous comment, I solve the planning problem in minutes. The decision variable X[i,j] specifies that task i,j has been taken (one) or not (zero), and the constant D[i,j] presents the time (in minutes) at which task i ,j starts. By the before-mentioned constraint, I want to obtain the minimum start time for the taken tasks. I need to have the hour when the task with minimum start time starts in a day in terms of minutes. 
For example, if the minimum start time is 456000, T must be equal to 960 which means the task starts at 16:00.

**Comment by lperron** [comment]
Maybe, but Min( ...) will return 0 if one X[i, j] is 0.
Perhaps, your code should be:

solver.Add(solver.Min([X[i, j] * D[i, j] + (1 - X[i, j]) * BigConstant) for
i, j in X if graph[i][j]['type'] == 'flight']) == a * 1440 + T)

provided at least one D[i, j] is true, and provided BigConstant is big
enough, I will compute what you want.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 4 sept. 2018 à 12:07, minaghavipour <notifications@github.com> a
écrit :
