### ISSUE TITLE
Calculate makespan scheduling problem

### ISSUE THREAD

**Issue by ChlAlejandro** [google/or-tools#843]
Hi!
I'm having some troubles calculating the makespan in a scheduling problem.
The problem is `Rm|Sijk|Cmax`, that is to say I have to schedule n jobs on m independant unrelated machines, where the set up times are not symmetric and depend on the machine (`for all jobs i,j and all machine k, Sijk =! Sjik`). 
Moreover, each job can only be processed on a subset of the m machines. 
There is no preemption. 
The objective is to minimize the makespan.

For now, my code is like this:
```cpp
            for (int jobIndex = 0; jobIndex < nbJobs ; jobIndex++) {
             // Each BooleanVar indicates if the corresponding IntervalVar is performed or not.
            IntVar[] performedArray = solver.makeBoolVarArray(nbMachines);

            for (int machineIndex = 0; lineIndex < nbMachines; machineIndex++) {

                if (job[jobIndex].canBeProcessedOn(machine[machineIndex])) {
                    
                    IntVar startingTime = solver.makeIntVar(0,
                            getCapacity(machineIndex) - getProcessingTime(jobIndex, machineIndex));
                    
                    intervalArray[machineIndex][jobIndex] = solver.makeFixedDurationIntervalVar(startingTime,
                            getProcessingTime(jobIndex, machineIndex), performedArray[machineIndex]);

                } else {
                    // Case where the job can't be processed on the machine. The 4th parameter is positive because this
                    // variable has to be unperformed.
                    intervalArray[machineIndex][jobIndex] = solver.makeFixedDurationIntervalVar(0, -1, -1, true);
                    performedArray[lineIndex].setValue(0);
                }
            }
            // Only one performed variable per job has to be true because a job has to be processed on exactly
            // one machine.
            solver.makeSumEquality(performedArray, 1);
        }

        for (int machineIndex = 0; machineIndex < nbMachines; machineIndex++) {
            // This contraint forces all interval vars in a machine not to overlap.
            solver.makeDisjunctiveConstraint(intervalArray[machineIndex]);

        }
        // Objective Function??
```

I looked for a special function to calculate the makespan and tried different techniques but with no success. 
Does anyone know how to dot that?

**Comment by lperron** [comment]
Can you precise what is the setup time? The minimum time a job can start on
a machine?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 6 sept. 2018 à 16:37, ChlAlejandro <notifications@github.com> a
écrit :

**Comment by ChlAlejandro** [comment]
The setup time S_ijk is the time that is needed (for adjusting, cleaning, ... the machine) between processing job i and processing job j on the machine k.
________________________________
De : Laurent Perron <notifications@github.com>
Envoyé : jeudi 6 septembre 2018 17:13
À : google/or-tools
Cc : ChlAlejandro; Author
Objet : Re: [google/or-tools] Calculate makespan scheduling problem (#843)

Can you precise what is the setup time? The minimum time a job can start on
a machine?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 6 sept. 2018 à 16:37, ChlAlejandro <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
This is implemented in examples/cpp/jobshop_sat.cc

It currently read the data in ortools/data/jobshop_scheduling,proto, but
you can adapt the code to read your data.

--Laurent
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 6 sept. 2018 à 20:55, ChlAlejandro <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
Here is a complete python example that implements transition time and
transition costs.

https://github.com/google/or-tools/blob/master/examples/python/scheduling_with_transitions_sat.py
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 12 sept. 2018 à 16:48, ChlAlejandro <notifications@github.com> a
écrit :
