### ISSUE TITLE
VRP - Making two nodes never be assigned on the same route

### ISSUE THREAD

**Issue by marcelobveras** [google/or-tools#848]
Hey guys, I was working at a VRP problem and realized that add a disjunction made all nodes on disjunction optional, but my intention is to make only a pair of (or a set of pairs) don't be on the same route. So, do you guys have any idea of how can I do this?

Thanks in advance.
Best regards.

**Comment by Mizux** [comment]
Just a note concerning disjuntion(), only at most one node can be active !
src: https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing.h#L516
so if you put Pickup and Delivery in the same list for the addDisjunction/penalty, solver can only drop both in order to fulfill both constraints i.e. "at most one node active", and "both nodes on the same vehicle"...

otherwise you could use the overload where you can set the cardinality...
src: https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing.h#L532

**Comment by marcelobveras** [comment]
Sorry, @Mizux, I'm trying to understand your solution. How a function that forcing a set of nodes to be in the same vehicle help me to do the opposite of it? What I want is: making two specific nodes never be in the same vehicle/route.

Thanks for your help.

**Comment by Mizux** [comment]
Ha sorry, i was thinking you want pair of node on the same route but having this constraint constraint i.e. could not be respected.

In this case did you simply try:
```python
model.solver().Add(
  model.VehicleVar(routing.NodeToIndex(node_1)) !=
  model.VehicleVar(routing.NodeToIndex(node_2)));
```

**Comment by marcelobveras** [comment]
This seems to be exactly what I want. I'm gonna make some tests and post in details to help others.
Many thanks, @Mizux, for your help.

**Comment by marcelobveras** [comment]
Hey I tried the code below, 
`def addDisjunction(node, ngh_list,routing): 

    for ngh_node in ngh_list:        
        routing.solver().Add(
            routing.VehicleVar(routing.NodeToIndex(node)) != 
            routing.VehicleVar(routing.NodeToIndex((ngh_node)))
`
in this function, I give a node and a list of nodes, they add a constraint for each element in this list to not be in the same vehicle of the node. But when I use SolveFromAssignmentWithParameters the assigned vehicles return the same vehicle to a pair of nodes that was not supposed to be on the same route.  Them I tried to use AddSoftSameVehicleConstraint with a negative cost, but I had the same problem.

**Comment by 270ajay** [comment]
try using PARALLEL_CHEAPEST_INSERTION as First Solution Strategy and SolveWithParameters 
(try not to use SolveFromAssignmentWithParameters with Initial Route and see if it works...)

**Comment by KeremAslan** [comment]
> Ha sorry, i was thinking you want pair of node on the same route but having this constraint optional i.e. could not be respected.
> 
> In this case you can simply try:
> 
> ```python
> model.solver().Add(
>   model.VehicleVar(routing.NodeToIndex(1)) !=
>   model.VehicleVar(routing.NodeToIndex(2)));
> ```
> 
> note: you may be interested by [#847 (comment)](https://github.com/google/or-tools/issues/847#issuecomment-420608114)

I stumbled upon this problem and thought that this constraint would do the trick. However, due to how OR-Tools is implemented this example is not entirely correct. The `VehicleVar` for an unassigned delivery is `-1`. So if both nodes are unassigned the equation will read `-1 != -1`, thus violating this constraint. 

How it actually needs to be formulated is that if "both nodes are active, then activate this contraint". Expressed as code:

```python
firstNodeIndex = routingNodeToIndex(node)
secondNodeIndex = routingNodeToIndex(node)
vehicleIndexForFirstNode = routing.ConditionalExpression(routing.ActiveVar(firstNodeIndex), routing.VehicleVar(firstNodeIndex), -10)

vehicleIndexForSecondNode = routing.ConditionalExpression(routing.ActiveVar(secondNodeIndex), routing.VehicleVar(secondNodeIndex), -20)

model.solver().Add(
   vehicleIndexForFirstNode != vehicleIndexForSecondNode
)
```

Note here that values `-10` and `-20` are arbitrary. We need a negative value as all values that are `>=0` can be assigned to a vehicle and `-1` is already occupied. Whatever value you chose doesn't matter that much I think.

**Comment by Mizux** [comment]
or this ?
https://gist.github.com/Mizux/9e37c370a459bd472a6ac13c304f0b54#file-same_vehicle-py-L51-L56

**Comment by KeremAslan** [comment]
Yeah, that is slightly neater as it avoids magic numbers.

**Comment by Woodz** [comment]
Perhaps I'm missing something, but can't we use boolean logic to avoid numeric calculations?
```
UNASSIGNED_INDEX = -1

first_index = manager.NodeToIndex(first_node)
second_index = manager.NodeToIndex(second_node)
first_is_active = routing.ActiveVar(first_index) != UNASSIGNED_INDEX
second_is_active = routing.ActiveVar(second_index) != UNASSIGNED_INDEX
routing.solver().Add(
  first_is_active && second_is_active && (routing.VehicleVar(first_index) != routing.VehicleVar(second_index)))
)
```

**Comment by Mizux** [comment]
@Woodz any constraint added by solver.Add() must be fulfilled so in your code above you force both node to be active and to be visited by a different vehicle. While user want to express IF locations are actives then we want a different vehicle

note: also don't sure "&&" operator is overloaded correctly and `first_is_active * second_is_active` is identical to `first_is_active && second_is_active`
you may also use `solver.Add(solver.Sum([first_is_active, second_is_active, (routing.VehicleVar(first_index) != routing.VehicleVar(second_index)) ]) == 3)`
note the use of the custom `solver.Sum()` method

**Comment by Woodz** [comment]
> @Woodz any constraint added by solver.Add() must be fulfilled so in your code above you force both node to be active and to be visited by a different vehicle. While user want to express IF locations are actives then we want a different vehicle

Understood - thanks! So it should be like

```
UNASSIGNED_INDEX = -1 first_index = manager.NodeToIndex(first_node) second_index = manager.NodeToIndex(second_node) first_is_active = routing.ActiveVar(first_index) != UNASSIGNED_INDEX second_is_active = routing.ActiveVar(second_index) != UNASSIGNED_INDEX routing.solver().Add( !first_is_active || !second_is_active || (routing.VehicleVar(first_index) != routing.VehicleVar(second_index))) )
```
So the constraint is:
- first node is not active or
- second node is not active or
- first and second nodes have different vehicles

**Comment by Mizux** [comment]
seems better in the idea IMHO, but again not sure `||` is supported
see: https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/python/constraint_solver.i
and `||` is not overloadable (ed only `|` could be overloaded https://github.com/python/cpython/blob/46b16d0bdbb1722daed10389e27226a2370f1635/Lib/operator.py#L116-L118 )

Also here python will try to interpret it directly while for instance "second_is_active" value (True or False) will only be known when a solution is found.
