### ISSUE TITLE
Transition times

### ISSUE THREAD

**Issue by ChlAlejandro** [google/or-tools#849]
Hello!
I'm working on Java on a scheduling problem. I'm using `intervalVars` and `sequenceVars` and this works.

The problem is that I have to add transition times between the different jobs in each machine. These transition times are not symmetric and depend on the machine. I'm using a disjunctive contraint to force all intervals not to overlap and I saw that I could use the methods `SetTransitionTime(LongLongToLong)` and `TransitionTime(int, int)`.

My questions are:
- How should I create the `LongLongToLong` parameter of `SetTransitionTime` that represents the transition time between the jobs? 
I have already read the documentation but there is only one method that seems useful for my problem in `LongLongToLong` class which is `run(int, int)`. Do I have to use this method?

-The method `TransitionTime(int job1, int job2)` returns the value of the transition time between `job1` and `job2`, but how can I get this value if I have never set it?

Thanks for your help!

**Comment by Mizux** [comment]
Hi, Which solver did you use ?

**Comment by ChlAlejandro** [comment]
Hi Mizux, thanks for your help!
Yes I use the CP solver. I tried to do what you said :  I created my own TransitionTime class which extends LongLongToLong. But I got this message error: 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe53bb8e0d, pid=19680, tid=0x00000000000047fc
#
# JRE version: Java(TM) SE Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.171-b11 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# [15:52:27] src/constraint_solver/search.cc:240: Start search (memory used = 75.27 MB)
C  [jniortools.dll+0x208e0d]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# hs_err_pid19680.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

This is the log error :

[hs_err_pid19680.log](https://github.com/google/or-tools/files/2383598/hs_err_pid19680.log)

**Comment by Mizux** [comment]
did you keep a reference on the callback instance to avoid the GC to reclaim it ?

Do you have a minimal example to reproduce it ?

**Comment by lperron** [comment]
Most likely the callback was garbaged away.
I recommend using the CP-SAT solver. There are examples now with transition times in scheduling.

I will close the issue now. Please reopen if needed.
