### ISSUE TITLE
CP SAT: Add DecisionStrategyProto::DEGREE heuristic

### ISSUE THREAD

**Issue by Phibedy** [google/or-tools#851]
For some problems the degree heuristic, choose variables first which are involved in the most constraints, is rather helpful. But I am not sure how to count the constraints as it might take some time, therefore it would be better to calculate them once after model creation (maybe in solve?).
Adding it afterwards to `cp_model_search.cc` is straight forward.

Where and how would you count the constraints?

**Comment by lperron** [comment]
On the cp_model proto directly. Counting time will be negligible compared
to presolve + solve time anyway.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
https://github.com/google/or-tools/blob/490360f4431225f497703de588246ccf0700edcc/ortools/sat/integer_search.cc#L290

Automatic search = activity based search alternating with lp search if
possible.

 I believe fixed_search is off by default. There is no randomness by
default.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Phibedy** [comment]
Ah I see, `randomize_search` is disabled by default. I got confused by `fixed_search` as I thought that it is the opposite of `randomize_search`. But those are two different things as you can have randomized fixed search. Thank you :+1:
