### ISSUE TITLE
Segmetation fault linear_solver.cc 

### ISSUE THREAD

**Issue by JohanJu** [google/or-tools#852]
When I run CBC solver and the result is MPSOLVER_INFEASIBLE i get a segmentation fault in the following code

https://github.com/google/or-tools/blob/0a357d7a480b68c865f9a66adbf0c0f63202be8e/ortools/linear_solver/linear_solver.cc#L1146-L1150

My quickfix is to change
`for (int i = 0; i < constraints_.size(); ++i)` to 
`for (int i = 0; i < constraints_.size() && i < activities.size(); ++i)`

**Comment by Mizux** [comment]
Strange since, activities is built from `constraints_size()`

https://github.com/google/or-tools/blob/aa0d4d023f34775ee1fb5994d3bbaee86bba4bf1/ortools/linear_solver/linear_solver.cc#L1078-L1091

**Comment by lperron** [comment]
This code should not be called if there are no solutions.

Do you call it manually?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by JohanJu** [comment]
I reran with gdb and -Og -g
```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
operations_research::MPSolver::VerifySolution (this=this@entry=0x17f2340, tolerance=tolerance@entry=9.9999999999999995e-08, log_errors=true) at ./ortools/linear_solver/linear_solver.cc:1150
1150	    const double activity = activities[i];
(gdb) p i
$1 = 0
(gdb) p activities
$2 = std::vector of length 0, capacity 0
(gdb) bt
#0  operations_research::MPSolver::VerifySolution (this=this@entry=0x17f2340, tolerance=tolerance@entry=9.9999999999999995e-08, log_errors=true) at ./ortools/linear_solver/linear_solver.cc:1150
#1  0x00007fffe508ceef in _wrap_Solver_VerifySolution (args=<optimized out>) at ortools/gen/ortools/linear_solver/linear_solver_python_wrap.cc:5663
#2  0x00000000004c53cd in _PyCFunction_FastCallKeywords ()
```

I probably did a mistake when I called or-tools but it would ber nice with an error message instead of segfault.
