### ISSUE TITLE
CBC_MIXED_INTEGER_PROGRAMMING in Python How to set Relaxation?

### ISSUE THREAD

**Issue by ebellumat** [google/or-tools#859]
How to set Relaxation in Constraint or in Variables using CBC_MIXED_INTEGER_PROGRAMMING?

Sample: `solver.Constraint(600000, solver.infinity(), 'Vol_Minimo' + str(j))`

**Comment by lperron** [comment]
what is 'relaxation' ?

**Comment by ebellumat** [comment]
Slack

**Comment by lperron** [comment]
There is no API for that. 
We do not expose it in the linear solver.
