### ISSUE TITLE
Bad links in sat README.md leading to internal google servers

### ISSUE THREAD

**Issue by pmateusz** [google/or-tools#861]
**Bug**
Some links in the [sat readme file](https://github.com/google/or-tools/blob/master/ortools/sat/README.md) lead to internal servers that are not available for users outside the Google organization. For example, an attempt to open the http://google3/ortools/sat/pb_constraint.h link by an external user fails with ERR_NAME_NOT_RESOLVED.

**Suggested solution**
As a long term fix one could develop an integration test that all links in readme files are resolvable.

**Comment by lperron** [comment]
Actually, this is a partially transformed paths. (invalid both internally
and externally).
Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le ven. 28 sept. 2018 à 11:01, Mateusz Polnik <notifications@github.com> a
écrit :
