### ISSUE TITLE
cp_is_fun_sat.py result is always wrong

### ISSUE THREAD

**Issue by stevenfrog** [google/or-tools#863]
I run `examples/python/cp_is_fun_sat.py`, and always get this:

> Statistics
>   - conflicts       : 146
>   - branches        : 468
>   - wall time       : 0.004273 ms
>   - solutions found : 0
> [Finished in 0.2s]

I do not change any codes, just run example.
My env:

> Linux M4700 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
> Python 3.5.2
> ortools          6.8.5452 

But if I run code at https://developers.google.cn/optimization/cp/cryptarithmetic, the result is right.

**Comment by lperron** [comment]
interesting :-)  6.9 is out. Can you try it?

python3.6 examples/python/cp_is_fun_sat.py

C=2 P=3 I=7 S=4 F=9 U=6 N=8 T=1 R=0 E=5

C=2 P=4 I=7 S=3 F=9 U=6 N=8 T=1 R=0 E=5

C=2 P=5 I=7 S=3 F=9 U=4 N=8 T=1 R=0 E=6

C=2 P=8 I=7 S=3 F=9 U=4 N=5 T=1 R=0 E=6

C=2 P=8 I=7 S=3 F=9 U=6 N=4 T=1 R=0 E=5

C=3 P=7 I=6 S=2 F=9 U=8 N=5 T=1 R=0 E=4

C=6 P=7 I=3 S=2 F=9 U=8 N=5 T=1 R=0 E=4

C=6 P=7 I=3 S=5 F=9 U=8 N=2 T=1 R=0 E=4

C=3 P=7 I=6 S=5 F=9 U=8 N=2 T=1 R=0 E=4

C=4 P=8 I=5 S=6 F=9 U=2 N=3 T=1 R=0 E=7

C=4 P=8 I=5 S=3 F=9 U=2 N=6 T=1 R=0 E=7

C=6 P=8 I=3 S=5 F=9 U=2 N=4 T=1 R=0 E=7

C=6 P=8 I=3 S=4 F=9 U=2 N=5 T=1 R=0 E=7

C=5 P=8 I=4 S=3 F=9 U=2 N=6 T=1 R=0 E=7

C=7 P=8 I=2 S=3 F=9 U=4 N=5 T=1 R=0 E=6

C=7 P=8 I=2 S=3 F=9 U=6 N=4 T=1 R=0 E=5

C=3 P=8 I=6 S=4 F=9 U=2 N=5 T=1 R=0 E=7

C=3 P=8 I=6 S=5 F=9 U=2 N=4 T=1 R=0 E=7

C=5 P=8 I=4 S=6 F=9 U=2 N=3 T=1 R=0 E=7

C=7 P=8 I=2 S=5 F=9 U=4 N=3 T=1 R=0 E=6

C=7 P=8 I=2 S=4 F=9 U=6 N=3 T=1 R=0 E=5

C=2 P=8 I=7 S=5 F=9 U=4 N=3 T=1 R=0 E=6

C=2 P=8 I=7 S=4 F=9 U=6 N=3 T=1 R=0 E=5

C=2 P=6 I=7 S=5 F=9 U=8 N=3 T=1 R=0 E=4

C=2 P=5 I=7 S=6 F=9 U=8 N=3 T=1 R=0 E=4

C=2 P=3 I=7 S=5 F=9 U=8 N=6 T=1 R=0 E=4

C=2 P=3 I=7 S=6 F=9 U=8 N=5 T=1 R=0 E=4

C=2 P=5 I=7 S=3 F=9 U=8 N=6 T=1 R=0 E=4

C=2 P=6 I=7 S=3 F=9 U=8 N=5 T=1 R=0 E=4

C=2 P=3 I=7 S=5 F=9 U=4 N=8 T=1 R=0 E=6

C=7 P=3 I=2 S=5 F=9 U=4 N=8 T=1 R=0 E=6

C=7 P=3 I=2 S=4 F=9 U=6 N=8 T=1 R=0 E=5

C=5 P=3 I=4 S=6 F=9 U=2 N=8 T=1 R=0 E=7

C=6 P=2 I=3 S=5 F=9 U=8 N=7 T=1 R=0 E=4

C=3 P=2 I=6 S=5 F=9 U=8 N=7 T=1 R=0 E=4

C=4 P=3 I=5 S=6 F=9 U=2 N=8 T=1 R=0 E=7

C=3 P=4 I=6 S=5 F=9 U=2 N=8 T=1 R=0 E=7

C=3 P=5 I=6 S=4 F=9 U=2 N=8 T=1 R=0 E=7

C=3 P=5 I=6 S=2 F=9 U=8 N=7 T=1 R=0 E=4

C=6 P=5 I=3 S=2 F=9 U=8 N=7 T=1 R=0 E=4

C=7 P=4 I=2 S=3 F=9 U=6 N=8 T=1 R=0 E=5

C=4 P=6 I=5 S=3 F=9 U=2 N=8 T=1 R=0 E=7

C=5 P=6 I=4 S=3 F=9 U=2 N=8 T=1 R=0 E=7

C=7 P=5 I=2 S=3 F=9 U=4 N=8 T=1 R=0 E=6

C=6 P=5 I=3 S=4 F=9 U=2 N=8 T=1 R=0 E=7

C=6 P=4 I=3 S=5 F=9 U=2 N=8 T=1 R=0 E=7

C=4 P=6 I=5 S=8 F=9 U=2 N=3 T=1 R=0 E=7

C=3 P=5 I=6 S=8 F=9 U=2 N=4 T=1 R=0 E=7

C=2 P=5 I=7 S=8 F=9 U=4 N=3 T=1 R=0 E=6

C=3 P=5 I=6 S=7 F=9 U=8 N=2 T=1 R=0 E=4

C=5 P=6 I=4 S=8 F=9 U=2 N=3 T=1 R=0 E=7

C=7 P=6 I=2 S=5 F=9 U=8 N=3 T=1 R=0 E=4

C=7 P=5 I=2 S=6 F=9 U=8 N=3 T=1 R=0 E=4

C=7 P=6 I=2 S=3 F=9 U=8 N=5 T=1 R=0 E=4

C=7 P=5 I=2 S=3 F=9 U=8 N=6 T=1 R=0 E=4

C=6 P=5 I=3 S=7 F=9 U=8 N=2 T=1 R=0 E=4

C=6 P=5 I=3 S=8 F=9 U=2 N=4 T=1 R=0 E=7

C=7 P=5 I=2 S=8 F=9 U=4 N=3 T=1 R=0 E=6

C=7 P=4 I=2 S=8 F=9 U=6 N=3 T=1 R=0 E=5

C=7 P=3 I=2 S=8 F=9 U=6 N=4 T=1 R=0 E=5

C=7 P=3 I=2 S=8 F=9 U=4 N=5 T=1 R=0 E=6

C=5 P=3 I=4 S=8 F=9 U=2 N=6 T=1 R=0 E=7

C=4 P=3 I=5 S=8 F=9 U=2 N=6 T=1 R=0 E=7

C=3 P=4 I=6 S=8 F=9 U=2 N=5 T=1 R=0 E=7

C=6 P=4 I=3 S=8 F=9 U=2 N=5 T=1 R=0 E=7

C=2 P=3 I=7 S=8 F=9 U=4 N=5 T=1 R=0 E=6

C=2 P=3 I=7 S=8 F=9 U=6 N=4 T=1 R=0 E=5

C=2 P=4 I=7 S=8 F=9 U=6 N=3 T=1 R=0 E=5

C=6 P=2 I=3 S=7 F=9 U=8 N=5 T=1 R=0 E=4

C=3 P=2 I=6 S=7 F=9 U=8 N=5 T=1 R=0 E=4

C=7 P=3 I=2 S=5 F=9 U=8 N=6 T=1 R=0 E=4

C=7 P=3 I=2 S=6 F=9 U=8 N=5 T=1 R=0 E=4


Statistics

  - conflicts       : 146

  - branches        : 468

  - wall time       : 0.071401 ms

  - solutions found : 72
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le sam. 29 sept. 2018 à 05:51, stevenfrog <notifications@github.com> a
écrit :

**Comment by stevenfrog** [comment]
OK, I installed python 3.6.6
The result is right.
