### ISSUE TITLE
Using half-reified constraint for channeling and chained constraints (Help needed!)

### ISSUE THREAD

**Issue by hooman650** [google/or-tools#864]
Hi, 

Here is a constraint that I have been trying to implement in ortools python cp_sat that is driving me crazy cause it becomes unsatisfiable... Is there something that I am doing wrong? Any help is highly appreciated...

I have three decision variables namely : X an integer, A an integer and B a bool, I would like to state the following complex decision constraint with Boolean output O;
```
if (X>=A /\ B) \/ (X<A /\ not(B)) then

  O = true       # Output Yes!

else

  O = false      # Output No!

endif;
```

Here is how I have been trying to implement it in ortools sat python;
```python
                 X = model.NewIntVar(0, 10, 'X')                         # Decision Variable
                 A = model.NewIntVar(0, 10, 'A')                         # Decision Variable
                 B = model.NewBoolVar('B')                               # Decision Variable
                 O = model.NewBoolVar('O')                              # Output Bool O
                 ## ===Channeling Flags === ##
                 Literal1  = model.NewBoolVar('Literal1')          # Bool flag for X>=A
                 Literal2  = model.NewBoolVar('Literal2')          # Bool flag for taking the AND with Literal1 and B
                 Literal3 =  model.NewBoolVar('Literal3')          # Bool flag for negation of AND with literal1               

                 model.Add(X >= A).OnlyEnforceIf(Literal1)
                 model.Add(X < A).OnlyEnforceIf(Literal1.Not())
                 
                 model.AddBoolAnd([Literal1,B]).OnlyEnforceIf(Literal2)
                 model.AddBoolAnd([Literal1.Not(),B]).OnlyEnforceIf(Literal2.Not())

                 model.AddBoolAnd([Literal1.Not(),B.Not()]).OnlyEnforceIf(Literal3 )
                 model.AddBoolAnd([Literal1,B.Not()]).OnlyEnforceIf(Literal3 .Not())

                 model.AddBoolOr([Literal2,Literal3]).OnlyEnforceIf(O)     # Output!
```

**Comment by hooman650** [comment]
@lperron makes sense! Thank you!

**Comment by hooman650** [comment]
@lperron Thank you again for helping out with this question... As a suggestion...does it make sense to add a function to the library that does the following?
```
If Condition1 then
Constraint 1
elseif Condition2 then
Constraint 2
else
true
endif

mode.AddIfThenElse([condition1,constraint1,condition2 constraint2,...])
```

This would be helpful in many complex CSP problems that otherwise would become complicated if we just might want to use the half-reified constraint. For instance another constraint that I have had problem with is:
```
if X > A then
X = X + 1
elseif X < A then
X = X - 1
else     % X == A
X = X
endif

```

Thanks again for your help....

**Comment by lperron** [comment]
Hi,

I try to keep the library small. Therefore I prefer not to add it.
It is also well demonstrated here:

https://github.com/google/or-tools/blob/master/ortools/sat/doc/channeling.md#implementing-an-if-then-else-expression
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 1 oct. 2018 à 19:50, Hooman Sedghamiz <notifications@github.com> a
écrit :

**Comment by hooman650** [comment]
@lperron sure, I understand... Do you have any suggestion as what might be the best strategy to implement three conditional scenarios (like the one I mentioned in my previous comment e.g. "elseif"). Sorry for taking your time.... But I think these examples would help others dealing with reified constraints as well....
Does the following implementation makes sense?
Say Literal is a 3 bit vector:
```
model.Add(X > A).OnlyEnforceIf(literal[0])
model.Add(X == C + 1).OnlyEnforceIf(literal[0])

model.Add(X < A).OnlyEnforceIf(literal[1])
model.Add(X == C - 1).OnlyEnforceIf(literal[1])

model.Add(X == A).OnlyEnforceIf(literal[2])
model.Add(X == C).OnlyEnforceIf(literal[2])

model.Add(sum(literal[i] for i in range(3)) == 1)
```
Thanks again fro your time!

**Comment by lperron** [comment]
It seems fine.

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 1 oct. 2018 à 22:08, Hooman Sedghamiz <notifications@github.com> a
écrit :
