### ISSUE TITLE
Build failure: error: reinterpret_cast from 'nullptr_t' to 'int *' is not allowed

### ISSUE THREAD

**Issue by yurivict** [google/or-tools#865]
On FreeBSD with clang-6:
```
cbc-src/Clp/src/OsiClp/OsiClpSolverInterface.cpp:1451:50: error: reinterpret_cast from 'nullptr_t' to 'int *' is not allowed
    messagesPointer->setDetailMessages(100,10000,reinterpret_cast<int *> (NULL));
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by lperron** [comment]
This is third_party source code. You can patch it by hand into static_cast,
or a double cast with a cast to void* before int*.
Then redo make third_party.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le dim. 30 sept. 2018 à 08:40, yuri@FreeBSD <notifications@github.com> a
écrit :

**Comment by yurivict** [comment]
I already have the ```clp``` package installed.
How to use the external package instead?

**Comment by Mizux** [comment]
Then redefine `UNIX_CLP_DIR` etc....
src: https://github.com/google/or-tools/blob/master/makefiles/Makefile.third_party.unix.mk#L12

**Comment by yurivict** [comment]
cmake build doesn't know about ```UNIX_CLP_DIR```, and gmake build breaks:
```
makefiles/Makefile.cpp.mk:37: Cannot find 'cc' command which is needed for build. Please make sure it is installed and in system PATH.
gmake[1]: *** No rule to make target 'dependencies/sources/protobuf-3.6.1/python/setup.py', needed by 'dependencies/sources/protobuf-3.6.1/python/google/protobuf/descriptor_pb2.py'.  Stop.
gmake[1]: *** Waiting for unfinished jobs....
```

**Comment by Mizux** [comment]
on unix we use `gcc`
src:  https://github.com/google/or-tools/blob/master/makefiles/Makefile.unix.mk#L117

**Comment by lperron** [comment]
I suppose I can close this issue.

**Comment by Mizux** [comment]
fixed in CLP see https://github.com/coin-or/Clp/issues/93

**Comment by Mizux** [comment]
got the same kind of error in Cgl see https://github.com/google/or-tools/issues/2105#issuecomment-660157011
