### ISSUE TITLE
Current items in route

### ISSUE THREAD

**Issue by yerzhik** [google/or-tools#866]
I want to add constraint that would calculate some value depending on current items already in the route. (Bin packing basically, which requires the knowledge of all items to be packed). The constraints added has the structure of `def demand_evaluator(from_node, to_node):` which doesn't contain previously selected items in the route. Is there a way to get that information?

**Comment by Mizux** [comment]
What's about creating a new Dimension let's call it "Value" dimension to accumulate the value of items like a kind of capacity ?

**Comment by Mizux** [comment]
Yes you are right, otherwise you may be "unfortunately" interested in issue #339

**Comment by lperron** [comment]
No, this is by design not possible.
