### ISSUE TITLE
If SetTimeLimit with a small enough value and no feasible solution is found, it crashes

### ISSUE THREAD

**Issue by BrianBohe** [google/or-tools#867]
Hi, 

I am using _pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING_ with python wrapper to solve a variation of the facility problem.

In some cases with a time limit of 10 minutes no feasible solution is found, and it starts logging a message:

### E1002 12:52:45.596408 18892 linear_solver.cc:1344] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_NOT_SOLVED 

in a infinite loop until the system kills the python process. No exception is thrown.

If the time is enough to find at least one feasible solution, this doesn't happen (I have checked this with other inputs).

I can create an initial feasible solution with an heuristic but I am not able to attached it to the solver. This is not a solution but a temporary fix for my project. Do you know how to do this?

Thanks!

**Comment by coderkd10** [comment]
I'm also facing a similar issue... I'm trying to solve an integer programming problem with 56K variables and 36K constraints using the CBC solver and the time limit I'm setting is not getting honoured.
I set the time limit to 10 hours and even after 52 hours the program doesn't terminate, though I don't get any error logs in the terminal. (Though for smaller problems the time limit is seems to be respected).

Also is there any way to manually instruct the solver to stop and get whatever solution it found until then ?

**Comment by peakning** [comment]
> I'm also facing a similar issue... I'm trying to solve an integer programming problem with 56K variables and 36K constraints using the CBC solver and the time limit I'm setting is not getting honoured.
> I set the time limit to 10 hours and even after 52 hours the program doesn't terminate, though I don't get any error logs in the terminal. (Though for smaller problems the time limit is seems to be respected).
> 
> Also is there any way to manually instruct the solver to stop and get whatever solution it has found until then ?

Have you fix your problem? I am also facing the similar issue. The program does not terminate in the setting time limit.

**Comment by louis925** [comment]
I am facing a similar issue. 
If there is no feasible solution found and I try to run `solver.VerifySolution(0.001, False)`, it will print ```E1228 00:40:22.029615 3053626240 linear_solver.cc:1577] No solution exists. MPSolverInterface::result_status_ = MPSOLVER_INFEASIBLE```
multiples time on the terminal and die.
