### ISSUE TITLE
fzn-or-tools multi threading not working

### ISSUE THREAD

**Issue by leobuettiker** [google/or-tools#868]
I downloaded the or-tools flatzinc binary from https://developers.google.com/optimization/install/cpp/linux. The file is or-tools_flatzinc_Ubuntu-17.10-64bit_v6.7.4981.tar.gz

When I run `./bin/fzn-or-tools -p 4 ./examples/euler_52.fzn` I would expect multiple cores (4) of my machine to be used. But only one core is used.

My Linux is: `Linux ip-172-31-32-152 4.15.0-1023-aws #23-Ubuntu SMP Mon Sep 24 16:31:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

The machine is an aws ec2 m5d.2xlarge instance. It has 8 cores. `lscpu` shows:
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
Stepping:            4
CPU MHz:             3110.260
BogoMIPS:            5000.00
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            33792K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke
```

**Comment by lperron** [comment]
I was not implemented in 6.7
You need 6.9.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 2 oct. 2018 à 20:20, Leo Büttiker <notifications@github.com> a
écrit :

**Comment by frankcheng1991** [comment]
Just curious how to print the info about usage of threads during/after calculation, by or-tools flatzinc binary.

Thanks.

**Comment by lperron** [comment]
There are no specific printed info. You can add --params
log_search_progress:true to get some output.

Le mer. 12 août 2020 à 20:05, frankcheng1991 <notifications@github.com> a
écrit :

**Comment by leobuettiker** [comment]
@frankcheng1991 it's not perfect, but if you have a long runing example you can easly monitor the number of threads with unix tools. You might use ps or top. See: https://stackoverflow.com/questions/268680/how-can-i-monitor-the-thread-count-of-a-process-on-linux
