### ISSUE TITLE
Using variables for indexing in Google OR-tools

### ISSUE THREAD

**Issue by ppallesen** [google/or-tools#869]
In other CP-frameworks such as Minizinc it posible to express a constraint in the following way:
constraint forall(j in jobs)(calendar[j,start_date[j],assignment[j] ]==planed[j]);
where start_date and assignment are variables.
Is this posible in google OR-tools or is there any process of extending the software in that direction?

**Comment by lperron** [comment]
We do support minizinc through flatzinc.
I guess is is expanded into index == some flattening function of (j,
start_date[j], assignment[j])
and then this becomes a standard element.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
