### ISSUE TITLE
SAT solver set parameters num_search_workers

### ISSUE THREAD

**Issue by JohnsonLCS** [google/or-tools#870]
Hi,

I try to run the example on https://github.com/google/or-tools/blob/master/examples/python/scheduling_with_transitions_sat.py
Set the num_search_workers greater than 1, but the status of solver become unknown.
I can only set this parameter to 0 or 1 and it can work normally. Thanks~

![image](https://user-images.githubusercontent.com/43457805/46447173-fb5bbe80-c7b2-11e8-8e48-f9617e6a0c9b.png)
![image](https://user-images.githubusercontent.com/43457805/46447188-10d0e880-c7b3-11e8-9699-6e00c8da5765.png)

Platform: Win10 64 bit
Python version:  I test it in two python version. 3.6.5&3.5.3. Both version have the same problem.
![image](https://user-images.githubusercontent.com/43457805/46447131-d6674b80-c7b2-11e8-86f5-1c15d96c8265.png)
![image](https://user-images.githubusercontent.com/43457805/46447353-d3b92600-c7b3-11e8-8dae-9d7ff53e3304.png)

ortools-6.9.5824

**Comment by JohnsonLCS** [comment]
Is there any method to enable multi-treads solve for python? Thanks~

**Comment by lperron** [comment]
Fixed in the source. Should be out in 6.10.

**Comment by JohnsonLCS** [comment]
Dear Laurent,

Thanks for help. I install from source and it work perfectly now.

**Comment by lperron** [comment]
Great. Thanks for the report.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
