### ISSUE TITLE
Segmentation fault if collector is accessed without calling assignment.Add(<var>)

### ISSUE THREAD

**Issue by lalithsuresh** [google/or-tools#872]
The following code segfaults when the last line is called. This is because solution.Add(myvar) wasn't called right after solver.Assignment().

```python
from __future__ import print_function
from ortools.constraint_solver import pywrapcp

solver = pywrapcp.Solver("bug")
myvar = solver.IntVar(0, 10, "myvar")
solver.Add(myvar == 5)

solution = solver.Assignment()
collector = solver.FirstSolutionCollector(solution)
solver.Solve(solver.Phase([myvar], solver.INT_VAR_SIMPLE, solver.ASSIGN_MIN_VALUE), [collector])
num_solutions = collector.SolutionCount()
print("num_solutions: ", num_solutions)

print(collector.Value(0, myvar))
```

The desired behavior would be to not segfault and throw a reasonable error message first.

**Comment by lperron** [comment]
I agree.

Still, the solver is in maintenance mode. and the new solver (CP-SAT) does not exhibit this behavior.
And patching the SWIG code and the C++ code to fix this is a bit too much work.

So, I will not fix it :-(

**Comment by lalithsuresh** [comment]
Thanks for the response. Right now, a lot of the examples on the website and in the examples/ folder are based on the old CP solver. And it looks like simply replacing the solver does not suffice to migrate to the CP-SAT solver, because a lot of methods have changed (solver.IntVar becomes model.NewIntVar, solver.Max no longer exists etc.). Where can I figure out the python APIs for the CP-SAT solver?

**Comment by lperron** [comment]
https://github.com/google/or-tools/blob/master/ortools/sat/doc/reference.md

and more generally

https://github.com/google/or-tools/blob/master/ortools/sat/doc/index.md

All this is slowly migrated to developer.google.com/optimization, but it
takes time.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 6 nov. 2018 à 18:59, Lalith Suresh <notifications@github.com> a
écrit :
