### ISSUE TITLE
Abort vs. Time limit 

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#873]
After commanding Solve, is there a way to command solver to abort solving?
Or is this only with pre-determined time limit, or via the operating system.

**Comment by lperron** [comment]
Which solver are you using?

**Comment by GuyBenhaim** [comment]
VRP version 6.X

**Comment by lperron** [comment]
/// Callback-based search limit. Search stops when limiter returns true; if
  /// this happens at a leaf the corresponding solution will be rejected.
  SearchLimit* MakeCustomLimit(std::function<bool()> limiter);
