### ISSUE TITLE
C#: Nuget package Google.OrTools-6.9.5839 broken

### ISSUE THREAD

**Issue by supermihi** [google/or-tools#875]
The current version of the nuget package uploaded on October 8 seems to be broken: when trying to run the application, I get the following:

```System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE' threw an exception.
  Source=Google.OrTools
  StackTrace:
   at Google.OrTools.ConstraintSolver.operations_research_constraint_solverPINVOKE.new_Solver__SWIG_0(String jarg1)
   at Google.OrTools.ConstraintSolver.Solver..ctor(String name)
   at OrToolsNugetTest.Program.Main(String[] args) in C:\Users\xxx\source\repos\OrToolsNugetTest\OrToolsNugetTest\Program.cs:line 10

Inner Exception 1:
TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.

Inner Exception 2:
DllNotFoundException: Unable to load DLL 'runtime.win-x64.Google.OrTools.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```
Apparently, the native DLL is not copied / linked correctly?

**Comment by lperron** [comment]
Thanks, we will have a look into it.
It should query Google.OrTools.runtime.win-x64 instead.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 8 oct. 2018 à 15:30, Michael Helmling <notifications@github.com> a
écrit :

**Comment by Mizux** [comment]
hi,

did you clean your local nuget cache to first to be sure ?
```shell
dotnet nuget locals all --clear
```

**Comment by Mizux** [comment]
It seems windows and osx runtime are impacted. Currently rebuilding runtimes deps and testing

**Comment by Mizux** [comment]
Version 6.9.5841 just uploaded should be available by 1 hour...

Tested locally on linux, osx and windows. Will retest once listed on nuget.org

**Comment by Mizux** [comment]
Could you try to add `--runtime <RUNTIME_IDENTIFIER>` e.g. `dotnet publish -r win-x64 <project>.csproj`

ref: dotnet publish --help

**Comment by supermihi** [comment]
Thanks for your response. I noticed that I was actually missing a `-r` in my `cp` command (running inside docker), which turned out to be the root of the problem. Now both runtime-dependent builds (`dotnet publish`) and self-contained builds (`dotnet publish --runtime win-x64`) appear to work. Thanks again!
