### ISSUE TITLE
Or tools will not compile on Windows

### ISSUE THREAD

**Issue by milanboers** [google/or-tools#88]
The most recent commit ebd7b92d3f7762fce5efb745d03745abcdaec5c7 will not compile on Windows anymore. Ambiguous call to MakePhase in routing.cc.

> routing.cc
> src/constraint_solver/routing.cc(3979) : error C2668: 'operations_research::Solver::MakePhase' : ambiguous call to overloaded function

**Comment by furnon** [comment]
Issue fixed (there was a similar error in examples/cpp/network_routing.cc).
