### ISSUE TITLE
Fixed cost for using a vehicle

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#880]
Hello,
I recall an item regarding adding a fixed cost for any vehicle being used but cannot find it. Can anyone direct me to its issue #?
It related to cost on top of the accumulated cost of the vehicle's travel; and for the Solver to include it during the search (as opposed to adding it after the fact).
Thx

**Comment by Mizux** [comment]
Issue don't know but you must want to use:
https://github.com/google/or-tools/blob/master/ortools/constraint_solver/routing.h#L641

**Comment by GuyBenhaim** [comment]
Thx!
And this way the Solver includes this cost before/when it assigns the vehicle?
Or is this reflected only after the fact - after the solver included the vehicle in its solution?

**Comment by Mizux** [comment]
IIRC first all node are unassigned and all route are `start -> end`.
Then little by little solver try to add unassigned node to a route and it evaluate the objective cost taking into account this fixed cost for any non "empty" route. (i.e. route with a least three nodes since start and end are mandatory)

**Comment by GuyBenhaim** [comment]
Seems that vehicle FixedCost is evaluated vs. a single Node's disjunction penalty: if the FixedCost is slightly higher the vehicle is not used and similarly **no vehicle was used and all Nodes were dropped**.

If Solver would have allocated the vehicle, it would server multiple Nodes and reduce penalty substantially.

When FixedCost was even a bit lower than disjunction penalty (of one Node) all necessary vehicles were allocated and served the Nodes.

Looks like the criteria to allocate was just based one vehicle vs. one Node. 
**Odd**.

**Comment by GuyBenhaim** [comment]
Could this be related to the strategy used for First Solution? now it's  ParallelCheapestInsertion
