### ISSUE TITLE
Need help in vrp constraint that is not all points need to be explored

### ISSUE THREAD

**Issue by NinjaKing** [google/or-tools#883]
Hello,
Could anyone pls help me on these constraints:
 1. Not all points need to be explored.
 2. Then the objective function is maximizing the number of points explored
I had known how to limit the distance of a route, but still stuck with the above constraints. 
Thanks so much! I am working with Python.

**Comment by Mizux** [comment]
Just use a `Disjunction`. i.e. Solver try to visit the node (and pay the traveling cost etc...) **or** pay the penalty cost and don't visit the node, knowing that the solver will try to minimize the objective (sum of all cost).
https://github.com/google/or-tools/blob/6a177338f944e09edd007cfddf814bb930454095/ortools/constraint_solver/routing.h#L514-L533

**Comment by Mizux** [comment]
Should work, if it limit to 7 nodes it just means solver didn't find a route with more than 7 nodes which have a distance (i.e. CumulVar at route end node) lower than maximum_distance.

**Comment by NinjaKing** [comment]
@Mizux Thank you, I think I have found the solution, seem like there is problem with float type less than 1, I have converted all data into int, and it works

**Comment by Mizux** [comment]
or-tools which is a C++ library use `int64` ...
