### ISSUE TITLE
VRP with breaks not returning solution

### ISSUE THREAD

**Issue by bcoghe** [google/or-tools#884]
I'm adding breaks in the following way:

```python
time_dimension = routing.GetDimensionOrDie("Time")    
    for vnum in range(nr_vehicles_total):
        # veh = vehicles.veh_input.loc[vnum]
        label = ' '.join(["Break on vehicle", str(vnum+1)])
        
        if vehicle_breaks[vnum] != None:               
                break_interval = routing.solver().FixedInterval(
                    vehicle_breaks[vnum][0],
                    15,
                    label
                )
                routing.AddIntervalToAssignment(break_interval)
                bip = break_interval.MustBePerformed()

                routing.solver().AddConstraint(
                    break_interval.PerformedExpr() == 1
                )

                time_dimension.SetBreakIntervalsOfVehicle([break_interval], int(vnum));
```

Now, without breaks a solution is found in less than 5 minutes. When adding the breaks (that don't even add extra variables I would assume) i'm not getting a solution. I'm using path_cheapest_arc as a first solution strategy. I tried others but it doesn't give a solution in a decent time except for all_unperformed.
The nodes are made optional, so i would always expect a solution.. Am i doing something wrong?

I also tried fixeddurationinterval(start_min, start_max, duration, optional, name)

**Comment by lperron** [comment]
Can you try with the 7.0 API

see https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/samples/cvrptw_break.py
