### ISSUE TITLE
Removing an arc or node from the underlying graph in SimpleMinCostFlow?

### ISSUE THREAD

**Issue by trainINT** [google/or-tools#887]
I see that there's an `AddArcWithCapacityAndUnitCost` function for creating arcs and `SetNodeSupply` for lazily creating nodes but no equivalent ones for removal. 
Is there a way to remove nodes or arcs from the underlying graph?

https://github.com/google/or-tools/blob/d44fb1b423f9d6658c142c041143a4f54b5106d3/ortools/graph/min_cost_flow.h#L220-L233

**Comment by lperron** [comment]
Actually not.

We welcome PR though :-)
