### ISSUE TITLE
Help needed for cloud Deployment on Azure

### ISSUE THREAD

**Issue by nikhilsarvaiye** [google/or-tools#888]
Hi all,

i created code to solve one of our business problem, i am using CP Solver in .Net. The scenario is listed here #698

I am facing one of the issue where API gets stuck which is logged here #831

My guess is it must be because of lack of computation power.

We needed to deploy this on Azure, I needed some help which one I can start with.

I explored couple of options, including Azure functions(10 minute max limit), Azure batch.

I am looking for any suggestions to deploy this and can be scaled automatically/manual.

Please suggest.

**Comment by lperron** [comment]
Sorry, cannot help you there.
