### ISSUE TITLE
Fails on .Net Core & AWS Lambda

### ISSUE THREAD

**Issue by npickup** [google/or-tools#889]
Hi,

Currently having issues with the v6.9 NuGet-packaged version of OR-Tools and AWS Lambda. When it runs it throws out the error "Unable to load shared library 'Google.OrTools.runtime.linux-x64.so' or one of its dependencies", despite the file being present.

Looking into it with ldd, I got the following missing dependencies (repeated for multiple files):
./Google.OrTools.runtime.linux-x64.so: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./Google.OrTools.runtime.linux-x64.so)
./Google.OrTools.runtime.linux-x64.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./Google.OrTools.runtime.linux-x64.so)
./Google.OrTools.runtime.linux-x64.so: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /var/task/libgflags.so.2.2)
etc...

I've tried following the documentation on compiling the NuGet packages for the linux platform from source but get compilation errors when doing "dotnet build" on the applicable native runtime project file along the lines of...
"/ortools/constraint_solver/csharp/ValCstPair.cs(209,19): error CS0246: The type or namespace name 'IntVar' could not be found (are you missing a using directive or an assembly reference?)"

Is there any advice/assistance on what I can do here to get the NuGet packages working in this situation? Many thanks!

**Comment by Mizux** [comment]
do you know which version of GLIBCXX is installed in AWS Lambda image ?

**Comment by npickup** [comment]
An update on this: the `make dotnet` command was the missing link for me, it's now building and packaging fine. I also noticed that it was mentioned in the dotnet readme.md and I somehow overlooked it, apologies!

I've ran a few tests against the recompiled version in AWS Lambda and can confirm it's working. Many thanks for your help!

**Comment by Mizux** [comment]
For next release, I'll try to build the linux runtime from an "old" centos-7 in order to increase ABI compatibility.

Concerning the https://developers.google.com/optimization/install/dotnet/source_linux I'm on my way to fix it, I apologize for the inconvenience.
