### ISSUE TITLE
Unable to get CP-SAT solver to work with Mac OSX mojave

### ISSUE THREAD

**Issue by ashugupt** [google/or-tools#895]
Unable to get CP-SAT solver to work with Mac OSX mojave(10.14)
I'm facing the below error on running the tutorial code

```python
from ortools.sat.python import cp_model

def main():
    model = cp_model.CpModel()
    # Create the variables.
    num_vals = 3
    x = model.NewIntVar(0, num_vals - 1, "x")
    y = model.NewIntVar(0, num_vals - 1, "y")
    z = model.NewIntVar(0, num_vals - 1, "z")

    # Create the constraints.
    model.Add(x != y)

    # Call the solver.
    solver = cp_model.CpSolver()
    solution_printer = SolutionPrinter([x, y, z])
    status = solver.SearchForAllSolutions(model, solution_printer)
    print('\nNumber of solutions found: {}'.format(solution_printer.SolutionCount()))

class SolutionPrinter(cp_model.CpSolverSolutionCallback):
    """Print intermediate solutions."""

    def __init__(self, variables):
        cp_model.CpSolverSolutionCallback.__init__(self)
        self.__variables = variables
        self.__solution_count = 0

    def NewSolution(self):
        self.__solution_count += 1
        for v in self.__variables:
            print('%s = %i' % (v, self.Value(v)), end = ' ')
        print()

    def SolutionCount(self):
        return self.__solution_count

if __name__ == '__main__':
    main()
```

It fails with the following error:
```
libc++abi.dylib: terminating with uncaught exception of type Swig::DirectorMethodException: SWIG director method error. Error detected when calling 'SolutionCallback.OnSolutionCallback'
[1]    3158 abort code.py
```

Below is my conda environment file:
```
name: rlh
channels:
- conda-forge
- anaconda
- statiskit
dependencies:
- python=3.7.0
- numpy=1.15.2
- scipy=1.1.0
- pandas=0.23.2
- pandasql=0.7.3
- matplotlib=2.2.3
- seaborn=0.9.0
- ipython=7.0.1
- notebook=5.7.0
- jupyter=1.0.0
- scikit-learn=0.19.2
- requests=2.19.1
- beautifulsoup4=4.6.0
- xlrd=1.1.0
- cython=0.28.5
- blaze=0.11.3
- openpyxl=2.5.8
- swig=3.0.12
- protobuf=3.6.0
- six=1.11.0
- setuptools=40.4.3
- clang_osx-64=4.0.1
- libcxxabi=4.0.1
- pip=18.1
- pip:
    - ortools==6.9.5824
    - jupyter_contrib_nbextensions
    - autopep8
    - yapf
    - jupyterthemes
```

Also, I'm able to run the example test as mentioned in both python installer and c++ installers.
I'm also able to run old CP solver and GLOP linear optimizer with the same configurations.

**Comment by ashugupt** [comment]
This seems like a regression as I'm able to run new CP_SAT solvers using `ortools==6.8.5452` published on PyPI.
Please fix.

**Comment by ashugupt** [comment]
I've finally able to run the CP-SAT solver with the latest version. Actually the issue is not with libc++abi but the documentation is outdated. As mentioned in the release notes:
https://github.com/google/or-tools/blob/v6.9/ortools/sat/doc/solver.md

I'd have to replace 
```
def NewSolution(self):
        self.__solution_count += 1
        for v in self.__variables:
            print('%s = %i' % (v, self.Value(v)), end = ' ')
        print()
```
with 
```
    def OnSolutionCallback(self):
        self.__solution_count += 1
        for v in self.__variables:
            print('%s = %i' % (v, self.Value(v)), end=' ')
        print()
```
and it starts working.

However, this change has not made to the official documentation which still shows the previous version of the breaking change:
https://developers.google.com/optimization/cp/cp_solver

Please fix or point me if I can raise a PR against the documentation so that it can be fixed.
Please close this issue in case the documentation update needs to be tracked via another issue.

**Comment by lperron** [comment]
There is a lag with the documentation, it is work in progress.

In the meantime, please read the release notes:

https://github.com/google/or-tools/releases/tag/v6.9

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le dim. 21 oct. 2018 à 09:31, Ashu Gupta <notifications@github.com> a
écrit :
