### ISSUE TITLE
SimpleMaxFlow: AddArcWithCapacity only takes integer capacities?

### ISSUE THREAD

**Issue by rajarshd** [google/or-tools#896]
Hi!

Thanks for the great tool!. I am a new user of the library.
I was using the [max_flow solver](https://developers.google.com/optimization/flow/maxflow). On trying to add capacities to an edge which are non-integers, I am getting the following error

```
TypeError: in method 'SimpleMaxFlow_AddArcWithCapacity', argument 4 of type 'operations_research::FlowQuantity'
```
But in a flow network the capacities need not be restricted to just integers. Am I doing something wrong?

**Comment by lperron** [comment]
It depends on the implementation, but this is a push relabel min cost flow,
and it does not work with floating point values.
You can always scale up your floating point values to the desired precision.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le dim. 21 oct. 2018 à 08:23, Rajarshi Das <notifications@github.com> a
écrit :
