### ISSUE TITLE
Python JobShop Solver : Machine Maintenance Time

### ISSUE THREAD

**Issue by avinashbarnwal** [google/or-tools#897]
Hi,

I am trying to solve standard JobShop Problem but machines have maintenance time.I tried looking into https://github.com/google/or-tools/issues/823 but this is for C#. How we can incorporate machine maintenance time in JobShop problem in Python? I tried to declare the machine maintenance time as FixedDurationIntervalVar and added it as Disjunctive Constraints 
[JOB_SHOP_Maintenance.py.zip](https://github.com/google/or-tools/files/2499439/JOB_SHOP_Maintenance.py.zip)
but it treated it as a new job rather than FixedInterval Constraints. Please find the code attached. Any help would be appreciated.

**Comment by avinashbarnwal** [comment]
I did it using Cp_Model.

**Comment by lperron** [comment]
Can you share the code?

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le dim. 21 oct. 2018 à 23:28, Avinash Barnwal <notifications@github.com> a
écrit :

**Comment by avinashbarnwal** [comment]
Hi,

Sorry for being Late. Please find the code. This is very toy code. Here we have constraints over time of jobs and machine blockage.

Please let me know if you want to understand more.
[jobshop_cp.py.zip](https://github.com/google/or-tools/files/2513421/jobshop_cp.py.zip)

Thanks for making wonderful Package.

**Comment by lperron** [comment]
I have pushed a working version.

https://github.com/google/or-tools/blob/master/examples/python/jobshop_with_maintenance_sat.py

In you previous code, you cannot use 'or' or 'and' on a constraint. You
need to create a channeling constraint to link a boolean variable to each
inequality, and add a bool_or on those. See
https://github.com/google/or-tools/blob/master/ortools/sat/doc/channeling.md
.

In my version, I just use a fixed interval. This is a better solution IMO.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le sam. 29 déc. 2018 à 13:08, Avinash Barnwal <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
With the corresponding output:

Optimal makespan: 72


Optimal Schedule

  machine 0:    job_0_0   job_6_0

  machine 1:    job_1_0

  machine 2:    job_3_0

  machine 3:    job_2_0   job_8_0

  machine 4:    job_5_0   job_4_0   job_7_0   job_9_0


Task Time Intervals

  machine 0:    [ 0, 5]   [10,13]

  machine 1:    [ 0,10]

  machine 2:    [ 0,10]

  machine 3:    [ 0, 6]   [ 6, 9]

  machine 4:    [ 0,12]   [12,62]   [62,67]   [67,72]
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by avinashbarnwal** [comment]
Thanks for the reply. I was not aware that we can't use "and" or "or" on constraints. I have looked at the link shared by you https://github.com/google/or-tools/blob/master/ortools/sat/doc/channeling.md about creating channeling constraints to link a boolean variable to each inequality and add a bool_or on those.

I will explain the problem i am trying to solve with maintenance time. We have 3 types of blocking : -

1. Start Time of Job is before the Start Time of Maintenance Time and End Time of Job is after the End Time of Maintenance Time.
2. Start Time of Job is before the Start Time of Maintenance Time and End Time of Job is before the Start Time of Maintenance Time.
3. Start Time of Job is after the Start Time of Block Time and End Time of Job is after the Start Time of Block Time.

I am not super comfortable with channeling constraints. But, based on going through channeling constraints page, it seems that we can only use it for IF-THEN-ELSE condition where we need to have some kind of output. It might sound trivial but how we can incorporate this in maintenance time where we don't have any output variable? Any suggestion will be appreciated.

I have attached the minimalistic code for it.


[job_shop_block.py.zip](https://github.com/google/or-tools/files/2738477/job_shop_block.py.zip)

**Comment by avinashbarnwal** [comment]
Hi,

Can you please re-open this?

Thanks,
Avinash Barnwal

**Comment by avinashbarnwal** [comment]
Hi Laurent,

I have tried the channeling constraints using the following steps but it is getting stopped. 
I replaced old "and" or "or" conditions like this:-

For example:-

For below constraints:-
#model.Add(((all_tasks[(j, k)].start < Machine_Block_time[i][0]) and (all_tasks[(j, k)].end > Machine_Block_time[i][1]))

Using Channel Constraints
literal1[(j,k)] = model.NewBoolVar('literal1_%i_%i' % (j, k))
model.Add((all_tasks[(j, k)].start < Machine_Block_time[i][0])).OnlyEnforceIf(literal1[(j,k)])
model.Add((all_tasks[(j, k)].start >= Machine_Block_time[i][0])).OnlyEnforceIf(literal1[(j,k)].Not())

literal2[(j,k)] = model.NewBoolVar('literal2_%i_%i' % (j, k))
model.Add((all_tasks[(j, k)].end > Machine_Block_time[i][1])).OnlyEnforceIf(literal2[(j,k)])
model.Add((all_tasks[(j, k)].start <= Machine_Block_time[i][0])).OnlyEnforceIf(literal2[(j,k)].Not())

model.AddBoolAnd([literal1[(j,k)], literal2[(j,k)]])

I have not sure how i can add below two more conditions to above conditions mentioned below?
or  ((all_tasks[(j, k)].start > Machine_Block_time[i][1])  and (all_tasks[(j, k)].end > Machine_Block_time[i][1])) or
((all_tasks[(j, k)].start < Machine_Block_time[i][0]) and (all_tasks[(j, k)].end < Machine_Block_time[i][0])))

I have gone through all the documents related to this and also previous issues such as  this
#495. 

I understand you might be very busy. But it would be great if you can help, i have some kind of urgency
to solve this problem.

Please find the code attached. 
[job_shop_block_boolean.py.zip](https://github.com/google/or-tools/files/2755999/job_shop_block_boolean.py.zip)

**Comment by avinashbarnwal** [comment]
Hi Laurent,

I have some suggestion for 
https://github.com/google/or-tools/blob/master/examples/python/jobshop_with_maintenance_sat.py.

We should change the horizon variable to the addition of maintenance time to it. As it will not work with every test case such as 

jobs_data = [  # task = (machine_id, processing_time).
        [(0, 20)],                 # Job0
        [(0, 10)]                 # Job1
    ]

where horizon gets increased due to maintenance time.

Below addition to horizon works fine.
horizon = horizon + 8

**Comment by avinashbarnwal** [comment]
I have been able to solve this.
