### ISSUE TITLE
Java Wrapper

### ISSUE THREAD

**Issue by chenxuanhanhao** [google/or-tools#898]
When using the linear_solver, is it possible for Java users to add CONSTRAINTS in a more natural way similar to Python or CSharp, instead of calling solver.makeConstraint() followed by frequently setCoefficient?

**Comment by lperron** [comment]
No.

Java does not support operator overloading, so it has to be verbose :-(
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by chenxuanhanhao** [comment]
operator overloading

got it and thanks

**Comment by Mizux** [comment]
For a Java-like (and JVM-based) language which does support operator overloading, you could look at Groovy. 

note: I didn't say we will support it in a foreseeable future !!!

**Comment by chenxuanhanhao** [comment]
Comparing to the "define solver -> solver.makeConstraint" way, the  "define a constraint -> add the constraint to a model/solver" way made constraints reusable?

**Comment by chenxuanhanhao** [comment]
> Comparing to the "define solver -> solver.makeConstraint" way, the "define a constraint -> add the constraint to a model/solver" way made constraints reusable?

When the overall model is complex and difficult to solver directly, constraint reuse is usual by iteratively solve two decomposed models with (largely) overlapped constraints.

**Comment by chenxuanhanhao** [comment]
> Comparing to the "define solver -> solver.makeConstraint" way, the "define a constraint -> add the constraint to a model/solver" way made constraints reusable?

When the overall model is complex and difficult to solver directly, constraint reuse is usual by iteratively solve two decomposed models with (largely) overlapped constraints.

Is it possible?
