### ISSUE TITLE
Or-Tools running in IIS crashes

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#899]
The C# program was running fine for quite a while;  until re-installed on IIS ...
(as virtual-application, under Default Web Site).

Every time the app reaches the point: 
```cs
model.AddDimension(manhattan_callback, big_number, big_number, true, "time");
```
it crashes with:
![image](https://user-images.githubusercontent.com/20749469/47357847-9ec43300-d6d0-11e8-9530-21de9a31071e.png)

In VS getting:
Exception thrown: 'System.AccessViolationException' in Google.OrTools.dll

We have seen it a few months back, and I recall the fix related to some 64 bit vs. 32 bit set-up, but cannot recall exactly what we did.  There were also cases VS indicated "unable to start the web server"

Any tips?

**Comment by GuyBenhaim** [comment]
This is really making it hard to use the app.
Any tips?

**Comment by Mizux** [comment]
What is IIS ? is it a `amd64`/`x86_64` application ?

**Comment by GuyBenhaim** [comment]
IIS is Microsoft's Web/Application server, on which the planning application is installed and accessed. It's set to run only 64 bit, as far as I know (...)

Referencing:
OrTools:   or-tools_VisualStudio2015-64bit_v6.4.4495
Protobuf: or-tools_VisualStudio2015-64bit_v6.4.4495

**Comment by GuyBenhaim** [comment]
NuGet provided v.6.9  but I get missing reference errors when runing in VS. Seems I need to add references (like before) but cannot find v6.9 in the list

**Comment by GuyBenhaim** [comment]
OK, went back to Google.OrTools.6.7.4973 with target FW:  net452
Compiles but IIS still crashes when reaches  RoutingModel model = new RoutingModel(....

**Comment by GuyBenhaim** [comment]
Re-installed Visual C++ Redistributable Package
Still IIS/IIS-express crash every time....

**Comment by Mizux** [comment]
For reference issue please look at #900

**Comment by GuyBenhaim** [comment]
Not sure .... In my case, the app builds and runs - until the Solver model is created or called ....
My guess is some us in the way IIS handles some exception

**Comment by GuyBenhaim** [comment]
Conclusion:  my bad, OrTool is cool!
In some odd way, my sw fed the Solver with 0 for a number of Nodes. In these cases, the Solver halts but w/o  returning exception data and apparently cases IIS to halt.

**Comment by GuyBenhaim** [comment]
It would be good to consider how **OrTools generates an exception or another mechanism** so we can implement graceful abort. 
Now it just causes IIS to crash (actually, sometimes even requires to Reset IIS)

**Comment by GuyBenhaim** [comment]
Any plans to provide a 'safety net' for such cases? (see above)

**Comment by lperron** [comment]
Yes,  but I need to understand what causes the crash.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by GuyBenhaim** [comment]
Mostly when any Node index within the vehicle start-point array and/or end-point array exceeded Orders+2*Vehicles-1 or was less than Orders.

**Comment by GuyBenhaim** [comment]
VRPTW C# with different start/end points per vehicle.
Does this answer?

**Comment by lperron** [comment]
No. I need an example that crashes on the command line. I cannot reproduce on Azure.
