### ISSUE TITLE
Problem with disjunction and node prioritization

### ISSUE THREAD

**Issue by mshuffett** [google/or-tools#901]
## Background

I have a working solution to a multi-day TSP with time windows. Each day at the end of the day, there is a node with a long service time and a constraint to be visited at a specific time.

I am using `PARALLEL_CHEAPEST_INSERTION` and `GUIDED_LOCAL_SEARCH`.

## Disjunctions

I also have disjunctions, since the input nodes are sometimes not all visitable within the given timeframe.

```python
    def _add_disjunction(self):
        self.log.info('Adding disjunctions')
        origin_location = self.locations[0]
        base_penalty = 100000
        repeat_nodes = self._nodes_involved_in_repeats()
        for node, location in enumerate(self.locations):
            if (location.is_same_doctor(origin_location)
                    or location in {app.location for app in self.appointments}
                    or node in repeat_nodes
                    or getattr(location, 'is_required', False)
            ):
                self.routing_model.AddDisjunction([node], 100000000)
            else:
                multiplier = getattr(location, 'skip_cost_multiplier', 1)
                penalty = int(multiplier * base_penalty)
                self.routing_model.AddDisjunction([node], penalty)
```

## New features
I am trying to add two new features:

1. Make a node required
2. Add the ability to have prioritization through the `skip_cost_multiplier` seen above.

```python
    def _add_required_constraints(self):
        required_nodes = [node for node, loc in enumerate(self.locations) if getattr(loc, 'is_required', False)]
        for node in required_nodes:
            index = self.routing_model.NodeToIndex(node)
            self.solver.Add(self.routing_model.ActiveVar(index) == 1)
```

## The Problem
The issue is that the solver does not seem to be using the disjunctive cost or objective function in prioritizing its search for the first solution or the guided local search. So, runs end up having high objective cost though a much lower objective cost solution should be easily found, even by removing multiple nodes from the solution and replacing it with one of the high disjunctive cost nodes.

**How do I get either the first solution or search strategy to find paths that optimize the objective cost (dominated by the disjunctive cost) more efficiently?**

With the above code, similarly, the model will not find a place for the required node that has both high disjunctive cost and the Active constraint. 

**How do I efficiently require a node to be visited if different from above answer?**

**Comment by lperron** [comment]
With 7.0 and above, only nodes appearing in a disjunction are optional.
All other nodes are mandatory.

Please try with the latest version.
