### ISSUE TITLE
Linker errors with Gurobi

### ISSUE THREAD

**Issue by Tresmele** [google/or-tools#903]
I have compiled or-tools from the source code to integrate it with the Gurobi solver. I have run the tests and examples and everything seems working properly. 
I have also solved a simple LP problem in C with Gurobi using its C interface. However, when I try to solve the same LP problem with C++, I obtain the following linker errors:

```shell
simple_program.obj : error LNK2019: símbolo externo "public: __cdecl GRBEnv::GRBEnv(bool)" (??0GRBEnv@@QEAA@_N@Z) sin resolver al que se hace referencia en la función "void __cdecl operations_research::RunTest(enum operations_research::MPSolver::OptimizationProblemType)" (?RunTest@operations_research@@YAXW4OptimizationProblemType@MPSolver@1@@Z)
simple_program.obj : error LNK2019: símbolo externo "public: __cdecl GRBEnv::~GRBEnv(void)" (??1GRBEnv@@QEAA@XZ) sin resolver al que se hace referencia en la función "void __cdecl operations_research::RunTest(enum operations_research::MPSolver::OptimizationProblemType)" (?RunTest@operations_research@@YAXW4OptimizationProblemType@MPSolver@1@@Z)
simple_program.obj : error LNK2019: símbolo externo "public: __cdecl GRBModel::GRBModel(class GRBEnv const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0GRBModel@@QEAA@AEBVGRBEnv@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) sin resolver al que se hace referencia en la función "void __cdecl operations_research::RunTest(enum operations_research::MPSolver::OptimizationProblemType)" (?RunTest@operations_research@@YAXW4OptimizationProblemType@MPSolver@1@@Z)
simple_program.obj : error LNK2019: símbolo externo "public: __cdecl GRBModel::~GRBModel(void)" (??1GRBModel@@QEAA@XZ) sin resolver al que se hace referencia en la función "void __cdecl operations_research::RunTest(enum operations_research::MPSolver::OptimizationProblemType)" (?RunTest@operations_research@@YAXW4OptimizationProblemType@MPSolver@1@@Z)
simple_program.obj : error LNK2019: símbolo externo "public: void __cdecl GRBModel::optimize(void)" (?optimize@GRBModel@@QEAAXXZ) sin resolver al que se hace referencia en la función "void __cdecl operations_research::RunTest(enum operations_research::MPSolver::OptimizationProblemType)" (?RunTest@operations_research@@YAXW4OptimizationProblemType@MPSolver@1@@Z)
bin\\simple_program.exe : fatal error LNK1120: 5 externos sin resolver
tools\make: *** [bin/simple_program.exe] Error 2
```

**Comment by Mizux** [comment]
Can we have the linking command line ? I would say there is a missing linkage with gurobi libraries...

**Comment by Tresmele** [comment]
I overwrote the simple_program from the getting started section, so the command I´m using is `tools\make ccc EX=simple_program.cc`. I have tried the flags -L and -l to index the library gurobi_c++md2017.lib but the command prompt keeps responding that it does not recognize them. 

The installation of or-tools with Gurobi does not index its c++ libraries? If so, should I modify the file Makefile.user to include them?

Thanks!

**Comment by Mizux** [comment]
You must define `WINDOWS_GUROBI_DIR` when compiling from source.

We currently use this:
https://github.com/google/or-tools/blob/d44fb1b423f9d6658c142c041143a4f54b5106d3/makefiles/Makefile.win.mk#L131-L143

and
https://github.com/google/or-tools/blob/d44fb1b423f9d6658c142c041143a4f54b5106d3/makefiles/Makefile.win.mk#L166

note: Currently we don't have CI jobs for compiling from source with gurobi support since we can't use it in Appveyor-CI (i.e. proprietary license issue)...

**Comment by lperron** [comment]
Note that the makefile expects gurobi<GUROBI_LIB_VERSION>.lib, no other
name.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Tresmele** [comment]
Yes, I just checked. I defined the constants as follows:

`WINDOWS_GUROBI_DIR = C:\gurobi810`
`GUROBI_LIB_VERSION = 81`

**Comment by lperron** [comment]
Yes but what are the .lib in the gurobi installation?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Tresmele** [comment]
Inside the lib folder of the gurobi installation there are the following .lib files:

```
gurobi_c++md2015
gurobi_c++md2017
gurobi_c++mdd2015
gurobi_c++mdd2017
gurobi_c++mt2015
gurobi_c++mt2017
gurobi_c++mtd2015
gurobi_c++mtd2017
gurobi81
```

**Comment by lperron** [comment]
Tested everything with 7.2.
Should work now/
