### ISSUE TITLE
netcore app 2.1 reference error

### ISSUE THREAD

**Issue by bvkeersop** [google/or-tools#904]
Created a new project and added below version of OrTools with NuGet.
Upon running a simple solver example I get the following error:

```shell
error CS0012: The type 'Solver' is defined in an assembly that is not referenced. You must add a reference to assembly 'Google.OrTools, Version=6.9.5841.0, Culture=neutral, PublicKeyToken=600e580726a33e50'.
```

my csproj contains a reference to OR-tools.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.OrTools" Version="6.9.5841" />
  </ItemGroup>

</Project>
```

netcoreapp2.1 should target .net standard 2.0 right?
Should I not use nuget?

Thanks

**Comment by lperron** [comment]
You should definitely use nuget.

Please look at csproj in examples/dotnet. (I am not an expert on dotnet
mess :-) ).
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 25 oct. 2018 à 21:18, Bart van Keersop <notifications@github.com> a
écrit :

**Comment by Mizux** [comment]
Hi, mm your csproj seems OK. On which platform did you work ? which RID ? did you use `dotnet build` or `dotnet run` ?

**Comment by bvkeersop** [comment]
I'm using windows 10. 

When I used an earlier version of OR-tools I had to change the solution platform to x64 before it would run, now any CPU works apparently, but I'm still setting it to x64.

The application actually solves the problem (it builds and runs), but when I debug it I get this:
![image](https://user-images.githubusercontent.com/10126707/47554675-1fba3f00-d90a-11e8-88e6-d1bf9bf34d95.png)

In another program I was working on, I assumed that was the error, but it turns out I made a mistake elsewhere. I don't know if this message is intended behavior?

Apologies if this is just something wrong with my settings, and  thanks for the help.

**Comment by Mizux** [comment]
1) `Google.OrTools` (GOT) is a native package which will only run on `x64` (BTW ortools does not compile on 32bits anymore -> we can't build 32bits runtime)

2) GOT is published in .Net Debug (i.e. we don't use dotnet/cli "Release" flag yet, on my todo list...), BUT native libraries are built in [`/O2 /DNDEBUG`](https://github.com/google/or-tools/blob/d44fb1b423f9d6658c142c041143a4f54b5106d3/makefiles/Makefile.win.mk#L96) (yes MACRO is call `DEBUG` :confused:)

**Comment by bvkeersop** [comment]
I am indeed using VS Studio 2017, so I'm guessing that must be the problem as the code runs just fine!

**Comment by Mizux** [comment]
Browsing few github issues, it seems `dotnet/cli` (MSBuild ?) "preload" `netstandard2.0` libraries etc. so it can build and run this proj.
On the other side VS still not load all dotnet stuff (and internal builder hacks ?) -> Try to update dotnet sdk/components/support/plugin of VS 2017 to see if it fix the issue...

Sorry for the inconvenience...

**Comment by Mizux** [comment]
could be also related to #928

**Comment by bvkeersop** [comment]
Hi,
Sorry for not replying earlier. I couldn't get it fixed and had to go on.
I was using the latest version of OR-tools at the time. I just updated to the latest version, and I can confirm that the debugger now works properly again!
