### ISSUE TITLE
How to set a MIP initial solution with C# wrapper and CBC solver

### ISSUE THREAD

**Issue by BrianBohe** [google/or-tools#908]
Hi,

Was someone able to use an initial solution (or hint)?

What should I need to do this?

Thanks!

**Comment by Isitar** [comment]
@lperron follow up question:
How to set a MIP initial solution with C# wrapper and SCIP?
I have scip compiled into the or-tools and a running solution with a Google.OrTools.LinearSolver.Solver.
I wasn't able to find a method for it.

**Comment by lperron** [comment]
Implemented in 7.3
