### ISSUE TITLE
CpModel.AddAllowedAssignments return value

### ISSUE THREAD

**Issue by mgritter** [google/or-tools#909]
The documentation for `AddAllowedAssignments` in the `ortools.sat.python.cp_model.CpModel` class says:

```python
    Returns:
      An instance of the Constraint class.
```

But, the function returns None. Looks like a `Constraint` object is created but just not returned.

Version: ortools==6.9.5824

**Comment by Mizux** [comment]
Yes, code seems to return nothing
src:
https://github.com/google/or-tools/blob/d44fb1b423f9d6658c142c041143a4f54b5106d3/ortools/sat/python/cp_model.py#L671-L707

**Comment by mgritter** [comment]
Added a pull request to fix this: https://github.com/google/or-tools/pull/910

**Comment by lperron** [comment]
I fixed it on my side.

Thanks for the report.
