### ISSUE TITLE
Routing library calls cause access violations

### ISSUE THREAD

**Issue by Mumbleskates** [google/or-tools#91]
Windows 64b, Python 2.7.10 64b
ortools 2.3928, installed via easy_install

While it is possible to do some straightforward TSP solving on a weighted graph by assigning the arc weight callbacks, any attempts to add disjunctions to the graph or work with NodeIndex objects result in crashes.

Reproduction:

> import ortools.constraint_solver.pywrapcp as pywrapcp
> routing = pywrapcp.RoutingModel(100, 1)

> routing.IndexToNode(5)  # Crashes with access violation
> routing.IndexToNode(5L)  # Crashes with access violation

> import ctypes
> routing.IndexToNode(ctypes.c_longlong(5))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\ortools-2.3298-py2.7-win-amd64.egg\ortools\constraint_solver\pywrapcp.py", line 3346, in IndexToNode
    return _pywrapcp.RoutingModel_IndexToNode(self, index)
TypeError: in method 'RoutingModel_IndexToNode', argument 2 of type 'int64'

> routing.NodeToIndex(object())  # Crashes with access violation
> routing.AddDisjunction([5, 6, 7, 8, 9])  # Crashes with access violation
> routing.AddDisjunction([5L, 6L, 7L, 8L, 9L])  # Crashes with access violation
> routing.AddDisjunction([5, 6, 7, 8, 9], -2)  # Prints the following, then crashes with access violation

[12:46:59] src/constraint_solver/routing.cc:1357: Check failed: (penalty) >= (0)Penalty must be positive

**Comment by itsmi** [comment]
Hi,
were you meanwhile able to solve the issue? I'm facing the same problem -- whenever I add disjunctions (e.g. routing.AddDisjunction([1,2])), the Kernel crashes.

**Comment by furnon** [comment]
Tracked the issue. Setting a depot (calling routing.SetDepot(0) for
instance) before adding disjunctions (or calling IndexToNode or
NodeToIndex) should fix the issue.
Long story: when using a constructor of RoutingModel without a depot, the
link between variable indices and node indices is postponed until the model
is closed. This is true for all programming languages.

Vincent

**Comment by Mumbleskates** [comment]
Thanks for the info! Had a lot of difficulty with this :)

**Comment by freesunshine0316** [comment]
Interesting, I faced the same problem too. So why they have this issue? Is that a bug? Since or-tools set 0 as the depot by default.
