### ISSUE TITLE
Multiple pickups fo single delivery?

### ISSUE THREAD

**Issue by risinghero** [google/or-tools#913]
Good day. Is it possible to make multiple pickups for one delivery? For example, I have order which consists of multiple items. And items are located on different storehouses.

**Comment by braktar** [comment]
It is possible to model, the solve will depend on the hardness to find a solution.

You can use the same definition used in [this example](https://github.com/google/or-tools/blob/master/examples/cpp/pdptw.cc#L267), with the only difference that you'll have to reference multiple times the same delivery node.

**Comment by risinghero** [comment]
@braktar Thank you.
