### ISSUE TITLE
TimeLimit with RoutingModel?

### ISSUE THREAD

**Issue by tgsmith61591** [google/or-tools#914]
I've been following several examples for routing optimization, and one of the things I'd like to add is global time limits for the solver runtime. It seems like this is possible given the [TimeLimit](https://developers.google.com/optimization/reference/util/time_limit/TimeLimit/) class. However, the only Python examples I'm seeing access the `TimeLimit` attribute of the `Solver` class:

```python
# from https://github.com/google/or-tools/blob/f974064e467cf8a875fcc404164aa56bf4c9463c/examples/python/steel.py#L150
solver = pywrapcp.Solver('Steel Mill Slab')
...
global_limit = solver.TimeLimit(args.time_limit)
```

The `RoutingModel` doesn't seem to have such an attribute:

```python
pywrapcp.RoutingModel.TimeLimit
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# AttributeError: type object 'RoutingModel' has no attribute 'TimeLimit'
```

Can you offer any advice on how to use a `TimeLimit` with the `RoutingModel`? Thanks!

**Comment by Mizux** [comment]
Hi,
For routing, you can specify it using the `search_parameter` object.
see: https://developers.google.com/optimization/routing/routing_options#search-limits

**Comment by dolsup** [comment]
a note for people
see: https://github.com/google/or-tools/commit/3bc57f1aec91a31cb9c34c7a7a6d7a69986225d6
