### ISSUE TITLE
Serialize and deserialize CpModel and CpSolverResponse

### ISSUE THREAD

**Issue by Haukinger** [google/or-tools#915]
I want to run the solver in a different process, accessed through WCF, most likely. Is there an easy way to serialize and deserialize CpModel and CpSolverResponse?

Looking into CpModel, it seems to be just a CpModelProto plus a lookup table, so serialization should be trivial with Protobuf. Is there a way to rebuild the lookup table from a given CpModelProto? If yes, can we get a constructor for CpModel that takes a CpModelProto?

CpSolverResponse should be directly (de-)serializable with Protobuf, correct?

**Comment by lperron** [comment]
If you are talking to a Server that will receive a model and output back a
response, I would use the C++ API (SolveCpModel) to consume the first model
and produce the response.
As both model and response are protobufs, they are directly serializable.

From the CpModel object (in any language), you can always query the
underlying proto.
The only missing API could be evaluating the value of a variable against a
response. It has to be tested.

I hope this helps.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Yes, this is the right way.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
