### ISSUE TITLE
Delayed Constraint

### ISSUE THREAD

**Issue by braktar** [google/or-tools#917]
Hi,

I'm currently trying to add constraint regarding an established route.
So setting the initial Assignment works well, but because of the direct dependency of the constraint to the tours, it is giving a "Failing constraint" while the initialization phase.

Given this context, I tried to delay the application of the constraint using the definition of the Distribute Constraint :

> std::vector<int64> min_cards(size_missions, 0);
> std::vector<int64> max_cards(size_missions, 6);
> BoundedFastDistribute* delayed_distribute = new BoundedFastDistribute(solver, vehicle_vars, min_cards, max_cards);
> Demon* delayed_demon = solver->RegisterDemon(MakeDelayedConstraintDemon0(solver, delayed_distribute, &BoundedFastDistribute::Post,"DelayedDistribute"));
> for(IntVar* vehicle_var: vehicle_vars) vehicle_var->WhenBound(delayed_demon);
> solver->AddConstraint(delayed_distribute);

Did you have some hint on the subject ?

**Comment by lperron** [comment]
This make no sense.
Demons are owned by the constraints. You cannot hijack the protocol to add new events.
To delay a constraint, when it is posted, the constraint decides its priority.

The only thing you can do is copy the constraint code and change the demon macros in the Post.
