### ISSUE TITLE
wish: conda package for or-tools

### ISSUE THREAD

**Issue by petrushy** [google/or-tools#92]
Hi,

I pure wish; conda package for or-tools (win-64)...

Anaconda python is starting to become popular as a python distribution for science and analysis. It has a packaging system called conda.

A conda package for or-tools would ease installation, especially for windows.

https://store.continuum.io/cshop/anaconda/
http://conda.pydata.org/docs/building/bpp.html
https://anaconda.org/

**Comment by hastebrot** [comment]
Definately this. I heard about Anaconda at SciPy 2015 (Keynote: "State of the Tools"). Would be also nice to have a Python 3 version (#63) for Anaconda3.

**Comment by lfiaschi** [comment]
+1

**Comment by lperron** [comment]
Just a comment on this.

I have no time to work on anaconda.
One use proposed to do it, so vote for this wish.

On the python3 front, or-tools now supports python3.
Status:
  ubuntu: install python3 python3-dev, python3-setuptools. Change
UNIX_PYTHON_VERSION to 3.4 (in 14.04), recompile.
  Mac OS X: Install python (3.5.1?), change UNIX_PYTHON_VERSION to 3.5,
tweak manually PYTHON_INC in makefiles/Makefile.unix to reflect the path
(/Library/Framework/...) to the python3 install.
  Windows: Install python 3.5.1 (32 or 64 bit), set the correct path in
Makefile.local

Hopefully, everything should work.

--Laurent

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2015-12-03 5:53 GMT+01:00 Luca Fiaschi <notifications@github.com>:

**Comment by Mizux** [comment]
does pypi package of ortools not sufficient ?

Also it seems there is a way to [wrap pypi package in anaconda](https://stackoverflow.com/questions/29286624/how-to-install-pypi-packages-using-anacaonda-conda-command)

**Comment by jGaboardi** [comment]
@Mizux as for my part regarding:
> "does pypi package of ortools not sufficient ?"

Yes, for me working on my own personal machine it is sufficient. However, I do research in a [secure environment](https://www.census.gov/fsrdc) with a very bureaucratic process for installing new software. They have an `anaconda` license, and thus all `condo install package` requests are automatically approved with any `pip install package` requests needing a long process of justification (which has a good chance not not being approved in the end).

I love using `ortools` and very much appreciate all the work that goes into this project. Being able to get `ortools` into my work environment and use it on my dissertation would be awesome.

**Comment by Mizux** [comment]
it seems that creating a conda package from wheel package is straight forward:

https://github.com/conda/conda-recipes/blob/a796713805ac8eceed191c0cb475b51f4d00718c/python/tensorflow/build.sh

**Comment by dublx** [comment]
+1

**Comment by swayson** [comment]
+1

**Comment by lperron** [comment]
As a conclusion, there may be a process in place to use OR-Tools in Conda. 
And I have report of multiple users doing it.

Still, we only support official python releases.
