### ISSUE TITLE
Capacity value

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#921]
Is there a way to force the cumulative value of Capacity dimension to a certain value at the Start-Node? (else than force to 0)?

Or, should I include a synthetic Node in which the vehicle 'picks' such capacity?

**Comment by Mizux** [comment]
when you create the dimension, don't force the capacity to zero in the constructor:
```python
routing.AddDimension(
    function_callback,
    max_slack, # allow "waiting"
    max_capacity, # maximum capacity per vehicle
    False, # Don't force start cumul to zero. 
    time)
```
src Time dimension example https://developers.google.com/optimization/routing/cvrptw#time
