### ISSUE TITLE
Getting the "Best" of all feasible solutions 

### ISSUE THREAD

**Issue by alexgg94** [google/or-tools#926]
Hi all,

I am using or-tools in an environment of ingredients and nutrients(SolveStigler). Basically you have some ingredients each one of them with a cost and with some nutrients. So, given some constraints about the minimum and maximum amount of each ingredient I have to get the specified nutrients with the minimum price.
The specified nutrients also have a constraint about the minimum amount (but the maximum amout is Infinite).

If I got it right, if the solver returns a Feasible result, means that no optimal solution has been found. So, in this case, means that I have got **N** solutions that accomplish the specified nutrients with the minimum cost.

Now, I would like to chose from all the Feasible solutions, the one with the maximum amount of nutrients.

Is it possible?

**Comment by lperron** [comment]
Change the objective to add a secondary term that is the amount of nutrients produced, or, 

solve once, store the optimal value, change the mode to add a constraint that you cannot degrade the first objective (usually with a small tolerance), then resolve with a second objective that is the amount of nutrients.

**Comment by songzhiyong** [comment]
````
model = cp_model.CpModel()
model.Add(sum([xi*pi for xi, pi in zip(x, p)]) >= min_value)
model.Minimize(sum([xi*int(pi*100) for xi, pi in zip(x, p)]))
````

this is my code ,why the sovler continue running even object value is already min_value and status is FEASIBLE not OPTIMAL

**Comment by lperron** [comment]
This makes no sense in this issue.
