### ISSUE TITLE
[NET] Mismatch PublicKeyToken's in the latest nuget package

### ISSUE THREAD

**Issue by ifle** [google/or-tools#928]
There is the problem with the authoring of the OrTools packages and binaries. 
Mismatch of PublicKeyToken cause to problem with Visual Studio debugger. This is issue confirmed by Visual Studio team
https://developercommunity.visualstudio.com/content/problem/365287/debugger-unable-evaulate-values-of-local-variables.html

**Comment by lperron** [comment]
Thanks for the report.
It is a tough one to fix with multi-platform archives.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
Should be ok with v6.10 release
