### ISSUE TITLE
Change in order of capacity array results in a different solution

### ISSUE THREAD

**Issue by shreyasdivan** [google/or-tools#931]
Hi,

I am running a CVRP problem. I am trying with 4 vehicles with varying capacities. 
I have observed that when I change the order of my capacity array (which is passed as an argument in the method _**AddDimensionWithVehicleCapacity**_), the solution differs.

For eg, 

`capacity = [10,11,12,13]` -> A solution 'X'
`capacity = [13,11,12,10]`  -> A solution 'Y'

Is this an expected behaviour?

**Comment by Mizux** [comment]
I would say yes. Also in you problem does vehicles reach their maximum capacity ? Do you have a fixed cost associated to each vehicle ?
