### ISSUE TITLE
Python employee scheduling does not give any solutions if num_nurses != num_shifts

### ISSUE THREAD

**Issue by pravesh-curefit** [google/or-tools#932]
I have written a simpler version of the employee_scheduling python example.

```python
from __future__ import print_function
import sys
from ortools.constraint_solver import pywrapcp


def main():
    # Creates the solver.
    solver = pywrapcp.Solver("employee_scheduling")

    num_nurses = 3
    num_shifts = 3
    num_days = 1

    # [START]
    # Create shift variables.
    shifts = {}

    for j in range(num_nurses):
        for i in range(num_days):
            shifts[(j, i)] = solver.IntVar(
                0, num_shifts - 1, "shifts(%i,%i)" % (j, i))
    shifts_flat = [shifts[(j, i)] for j in range(num_nurses)
                   for i in range(num_days)]

    # Create nurse variables.
    nurses = {}

    for j in range(num_shifts):
        for i in range(num_days):
            nurses[(j, i)] = solver.IntVar(
                0, num_nurses - 1, "shift%d day%d" % (j, i))
    # Set relationships between shifts and nurses.
    for day in range(num_days):
        nurses_for_day = [nurses[(j, day)] for j in range(num_shifts)]

        for j in range(num_nurses):
            s = shifts[(j, day)]
            solver.Add(s.IndexOf(nurses_for_day) == j)

    # Create the decision builder.
    db = solver.Phase(shifts_flat, solver.CHOOSE_FIRST_UNBOUND,
                      solver.ASSIGN_MIN_VALUE)
    # Create the solution collector.
    solution = solver.Assignment()
    solution.Add(shifts_flat)
    collector = solver.AllSolutionCollector(solution)

    solver.Solve(db, [collector])
    print("Solutions found:", collector.SolutionCount())
    print("Time:", solver.WallTime(), "ms")
    print()

if __name__ == "__main__":
    main()
```

As you can see the only constraints I have kept is the relationships between shifts and nurses.
With num_nurses = 3, num_shifts = 3 and num_days = 1, the solver is able to find 6 solutions. However, if I change num_shifts to 2, the solver returns 0 solutions.
Shouldn't this have 3 solutions as well (assign one nurse, leave the other two unassigned) ?

**Comment by lperron** [comment]
Yes, the model is very restricted as it make this assumption.
I will rewrite it as it creates more problems that actually helps writing
nurse rostering problems.

Please note that you should use the CP-SAT solver is the original CP solver
is deprecated.

see https://developers.google.com/optimization/cp/cp_solver#cp-sat_example

and

https://github.com/google/or-tools/blob/master/ortools/sat/doc/index.md

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 14 nov. 2018 à 15:48, pravesh-curefit <notifications@github.com> a
écrit :

**Comment by pravesh-curefit** [comment]
Oh thanks for clarifying.
What kind of problems can the CP-SAT solver do? Can the employee scheduling problem be modelled for CP-SAT solver?
I do not find many examples of CP-SAT solver in action. Are there more examples of it being used?

**Comment by lperron** [comment]
Yes.

Look for examples/*/*_sat* + the one listed in the doc I sent you. These
samples are in ortools/sat/samples/

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 14 nov. 2018 à 18:13, pravesh-curefit <notifications@github.com> a
écrit :

**Comment by pravesh-curefit** [comment]
Will check it out.
Should we also mark mention this on the example pages of Employee Scheduling and Job Shop till we rewrite this? It'll help others get started quicker.

**Comment by lperron** [comment]
We are in the process of rewriting everything. The jobshop example is here:

https://github.com/google/or-tools/blob/master/ortools/sat/samples/minimal_jobshop.py

Hopefully, in the next 2 weeks, all original CP examples will have been
replaced by CP-SAT versions.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 14 nov. 2018 à 18:30, pravesh-curefit <notifications@github.com> a
écrit :

**Comment by pravesh-curefit** [comment]
Great. Thanks for the update. Will keep an eye out for more.

**Comment by pravesh-curefit** [comment]
If I have to use cp-sat solver for this, I need to use `model.NewIntVar` instead of `solver.IntVar`. Looks like the IntVar are not the same at both places? Once I do that and I try `model.Add(s.IndexOf(nurses_for_day) == j)` I get the error `'IntVar' object has no attribute 'IndexOf'`. I know this is not directly related to the issue I opened but can you please direct me towards a documentation that can clarify this?

**Comment by lperron** [comment]
Indeed, the API are not the same.

You can have a look at ortools/sat/python/cp_model.py. It contains the full
python of the CP-SAT solver.
This is also available at:
https://github.com/google/or-tools/blob/master/ortools/sat/doc/reference.md

in your case, it is

model.AddElement(s, nurses_for_day, j)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 15 nov. 2018 à 01:51, pravesh-curefit <notifications@github.com> a
écrit :

**Comment by pravesh-curefit** [comment]
This should help. Thanks.

**Comment by pravesh-curefit** [comment]
I'm facing the same issue with SAT solver as well.

```
from __future__ import print_function
import collections

# [START model]
# Import Python wrapper for or-tools CP-SAT solver.
from ortools.sat.python import cp_model


def main():
    # Create the model.
    model = cp_model.CpModel()
    # [END model]

    num_nurses = 3
    num_shifts = 3
    num_days = 1

    # Create shifts variables.
    shifts = {}

    for j in range(num_nurses):
        for i in range(num_days):
            shifts[(j, i)] = model.NewIntVar(
                0, num_shifts - 1, "shifts(%i,%i)" % (j, i))

    # Create nurse variables.
    nurses = {}

    for j in range(num_shifts):
        for i in range(num_days):
            nurses[(j, i)] = model.NewIntVar(
                0, num_nurses - 1, "shift%d day%d" % (j, i))

    # Set relationships between shifts and nurses.
    for day in range(num_days):
        nurses_for_day = [nurses[(j, day)] for j in range(num_shifts)]

        for j in range(num_nurses):
            s = shifts[(j, day)]
            model.AddElement(s, nurses_for_day, j)

    solver = cp_model.CpSolver()
    status = solver.Solve(model)

    if status == cp_model.OPTIMAL:
        print("OPTIMAL")
    elif status == cp_model.INFEASIBLE:
        print("INFEASIBLE")
    elif status == cp_model.FEASIBLE:
        print("FEASIBLE")

    solution_printer = SolutionPrinter([shifts, nurses])
    status = solver.SearchForAllSolutions(model, solution_printer)
    print('\nNumber of solutions found: {}'.format(
        solution_printer.SolutionCount()))


class SolutionPrinter(cp_model.CpSolverSolutionCallback):
    """Print intermediate solutions."""

    def __init__(self, variables):
        cp_model.CpSolverSolutionCallback.__init__(self)
        self.__variables = variables
        self.__solution_count = 0

    def OnSolutionCallback(self):
        self.__solution_count += 1
        for v in self.__variables:
            print('%s = %i' % (v, self.Value(v)), end=' ')
        print()

    def SolutionCount(self):
        return self.__solution_count


if __name__ == '__main__':
    main()
```

With num_nurses = 3, num_shifts = 3 and num_days = 1, the solver is able to find 6 solutions. However, if I change num_shifts to 2, the solver returns 0 solutions. :(

**Comment by pravesh-curefit** [comment]
Oh. So till rewritten, there is no way to use or-tools to do a generic employee scheduling?

**Comment by lperron** [comment]
It is possible, but you need to write the correct constraints.
These examples are just here to help you, but they are in no way complete,
or representative of the full scope of employee scheduling.


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 15 nov. 2018 à 07:40, pravesh-curefit <notifications@github.com> a
écrit :

**Comment by pravesh-curefit** [comment]
And is there a documentation explaining how different kinds of constraints can be modelled in or-tools?

**Comment by paultrow** [comment]
You can modify the code to solve the simple problem as follows.  Delete the nurses variables and the code that relates nurses to shifts. Then add the following constraints:

for i in range(num_days):
        for j in range(1, num_shifts):
            solver.Add(solver.Sum([shifts[(k, i)] == j for k in range(num_nurses)]) == 1)

This ensures that exactly one shift is assigned to each nurse. If you then change num_shifts to 2, the program finds three solutions. Here's the complete code:

from __future__ import print_function
import sys
from ortools.constraint_solver import pywrapcp


def main():
    # Creates the solver.
    solver = pywrapcp.Solver("employee_scheduling")

    num_nurses = 3
    num_shifts = 2
    num_days = 1

    # [START]
    # Create shift variables.
    shifts = {}

    for j in range(num_nurses):
        for i in range(num_days):
            shifts[(j, i)] = solver.IntVar(
                0, num_shifts - 1, "shifts(%i,%i)" % (j, i))
    shifts_flat = [shifts[(j, i)] for j in range(num_nurses)
                   for i in range(num_days)]

    for i in range(num_days):
        for j in range(1, num_shifts):
            solver.Add(solver.Sum([shifts[(k, i)] == j for k in range(num_nurses)]) == 1)
  
    # Create the decision builder.
    db = solver.Phase(shifts_flat, solver.CHOOSE_FIRST_UNBOUND,
                      solver.ASSIGN_MIN_VALUE)
    # Create the solution collector.
    solution = solver.Assignment()
    solution.Add(shifts_flat)
    collector = solver.AllSolutionCollector(solution)

    solver.Solve(db, [collector])
    print("Solutions found:", collector.SolutionCount())
    print("Time:", solver.WallTime(), "ms")

if __name__ == "__main__":
    main()

**Comment by lperron** [comment]
Hi,

I have pushed a more complex shift scheduling example here:

https://github.com/google/or-tools/blob/master/examples/python/shift_scheduling_sat.py

I believe it will be more inspiring than the current example.

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by pravesh-curefit** [comment]
Thanks. Will try to understand and follow this.

**Comment by FilJed** [comment]
Hello!

I've tried to make it through all this changes and version of this simple program, but I failed to build my own program. 

I started from here:
https://developers.google.com/optimization/scheduling/employee_scheduling
And end up here when realized the num_nurses != num_shifts problem.

Next step I took was to rewrite this code for my needs:
or-tools/examples/python/shift_scheduling_sat.py
Even after changing code which was not running as this part of code
 ```
ObjectiveSolutionPrinter(cp_model.CpSolverSolutionCallback)
...
```
was moved to or-tools and I could not get latest version of or-tools. Now it can run, but I failed to make right changes. Still I can not force it work my way. Could you please help me?

All I want is to rewrite this program as follows:
1) 6 workers
2) Only 2 shift per day (so only 12-hours night and day shifts)
3) 30 or 31 days (all month long) -- I know the more constraint I have the less possibilities of shifts exist.
4)I have mask of worker's preferences given as mask(shift_number, worker) equals 0, 1 or -1, which means that worker doesn't want to work this shift, wants to work it or no preferences. I want to use it like constraint.
5) All workers must have pretty the same number of night and day shifts -- about 5 day and 5 night shifts per worker.
6) Worker can not work two shifts in row.

Most of this requirements repeat those from original code. But still I've spent two months for nothing.
That is disappointing. Please, help!

**Comment by lperron** [comment]
Look at examples/python/shift_scheduling_sat.py
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by braindeaf** [comment]
This latest shift_scheduling_sat.py is really nice. It's taken me days to find an example to try and manage grouping shifts on consecutive days. Just ensuring shifts are as evenly spread (in time) and my solution is done 👍
