### ISSUE TITLE
Constraint solver beginner questions: can it be multi-threaded? How can I improve speed?

### ISSUE THREAD

**Issue by nemkin** [google/or-tools#933]
Hello,

I am trying to build a university timetable generator program with the constraint solver class. Right now I have around 1000 variables, with a maximum of 300 values each and I have left the solver run for ~21 hours and it's still going.

The log currently reads the following:
I1115 12:34:14.170292 31569 search.cc:244] 7800000000 branches, 77377559 ms, 3899999866 failures, tree pos=312/360/438 minref=262 max=452

Is it possible for this class to use multiple threads for computation? If not, is there another module that I could use for this task that supports multiple threads?

Is it normal for these types of computations to take several days to finish? Should I try to improve my model instead of trying to go parallel?

Is there any way I can estimate the time required to find a solution given the number of variables, values and constraints?

What does the tree pos, minref and max mean in the log line?

Thank you for your time!

Best regards,
Viktória Nemkin

**Comment by lperron** [comment]
use the CP-SAT solver (you will need to rewrite the code though).
This should give you a good boost.

Then, the CP-SAT solver can run in parallel, if needed.

See: https://github.com/google/or-tools/blob/master/ortools/sat/doc/index.md

and

https://developers.google.com/optimization/cp/cp_solver#cp-sat_example

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 15 nov. 2018 à 04:42, Viktória Nemkin <notifications@github.com> a
écrit :

**Comment by nemkin** [comment]
Hello,

thank you for the fast answer, I will try it out!

Best regards,
Viktória Nemkin

**Comment by nemkin** [comment]
Oh my god!

I just finished translating my code to the CP-SAT solver and it ran in 1 second for the same data that was running for 21 hours previously and I did not modify my constraints at all!

Thank you! :)

**Comment by SilvaXiang** [comment]
> Oh my god!
> 
> I just finished translating my code to the CP-SAT solver and it ran in 1 second for the same data that was running for 21 hours previously and I did not modify my constraints at all!
> 
> Thank you! :)

How to run CP-SAT solver in parallel to get all solutions of CSP problem?

**Comment by lperron** [comment]
You cannot inside the solver. You need to parallelize it yourself.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00
