### ISSUE TITLE
Vehicle Routing: Filter Nodes Based on Vehicle parameters

### ISSUE THREAD

**Issue by mateusc42** [google/or-tools#936]
Thanks for the ORTools project, its quite helpful to kick start many of the routing optimizations.

Im using the cvrptw.py sample and modifying it to suit our usecase. In our usecase, we have replaced vehicles with Engineers who need to go to the nodes to service appliances, so its almost fitting to the example. The only challenge I have is that we have skills associated with engineers so all nodes can not be visited by all engineers. Only engineers who meet that skill should service at the respective nodes.

I would need to filter the output so that they do not meet the evaluation criteria (Engineer_skill! = Skill_Needed_For_Node) and are to be removed when evaluating the route for that vehicle.

Any pointers on how to implement the above in python will be very helpful.

Thanks

**Comment by jmarca** [comment]
Coming from using the pickup and delivery problem, I'd suggest using multiple demand and supply dimensions.  In the pickup and delivery problem (see for example the cpp example pdptw.cc) the vehicle pick up items and then eventually drops them off at their destination.  I modified this approach to pickup up heterogeneous packages in vehicles.

Similar case here.  Each engineer provides one or more capabilities.  Suppose Engineer A provides [screwdriver, hammer], and Engineer B provides [screwdriver, saw], and these are defined in some input file.  Then in the program you could do:

```
EngineerA: screwdriver: 1, hammer: 1, saw: 0
EngineerB: screwdriver: 1, hammer: 0, saw: 1
```
Demands are for one or more of these capabilities, and zero if not specified.  So for example,

```
site1: screwdriver
site2: saw
site3: saw, hammer
```

Each of these nodes has a demand of 1 for the requested capability, and a demand of 0 for anything not mentioned.  

Conceptually, each engineer can serve the demands they supply.  So EngineerA can serve node1, EngineerB can serve node2, and nobody can supply the needs of node 3, unless you allow multiple engineers to visit a node.

In pseudo python code that looks good to me but hasn't been run, I'd do something like:

```python
    dim_names = ['saw','hammer','screwdriver']
    demands = [locations.get_demand_callback(d) for d in dim_names]
    capabilities = [engineers.get_supply_array(d) for d in dim_names]
    [routing.AddDimensionWithVehicleCapacity(
        demand_cb,  # demand callback
        null_capacity_slack,
        supply_arr,  # capacity array
        True,
        req) for demand_cb,supply_arr,req in zip(demands,
                                                 capabilities,
                                                 dim_names]
```

As each node "loads" up their demand on the engineer, you'll have to create a corresponding dummy node that directly follows each node that has a corresponding -1 "dropoff" demand.

Does that make sense?  Again, check out the [pdptw.cc](https://github.com/google/or-tools/blob/master/examples/cpp/pdptw.cc) example program.
