### ISSUE TITLE
CP-SAT: Add a constraint on every element of an array of arrays

### ISSUE THREAD

**Issue by Stygmates** [google/or-tools#937]
Hi,
I've been trying to implement the catalog and the adjacency matrices from [http://graphics.stanford.edu/~pmerrell/thesis.pdf](url) but it takes too long on a 10x10 example with a 84x84 RightTransitionMatrix.
I have a 2 dimensionnal array Catalog and I want to apply a constraint such that if an element at index [i][j] of the array equals a certain value, the element at index [i][j+1] must not be equal to another value. 

```python
    Catalog = [[model.NewIntVar(0, len(TransitionMatrixRight) - 1, "Case %i" %(j*width+i)) for i in range(width)] for j in range(height)]
    for i, line in enumerate(Catalog):
        for j in range(len(line)):
            for LineIndex, TransitionRightLine in enumerate(TransitionMatrixRight):
                for ColumnIndex, RightAdjacency in enumerate(TransitionRightLine):
                    if j < (len(line)-1):
                        if(not RightAdjacency):
                            c = model.NewBoolVar("Constraint on %i" %j)
                            model.Add(Catalog[i][j] == LineIndex).OnlyEnforceIf(c)
                            model.Add(Catalog[i][j] != LineIndex).OnlyEnforceIf(c.Not())
                            model.Add(Catalog[i][j+1] != ColumnIndex).OnlyEnforceIf(c)
```
Here is an example of a simple TransitionMatrixRight:
```python
TransitionMatrixRight = [[False, True, False, False], [False, False, False, False], [False, False, False, True], [False, False, False, False]]
```
Is there any way to apply the constraint to the whole array of arrays without a loop, or am I doing it wrong?

**Comment by Stygmates** [comment]
The TransitionMatrixRight I gave is an example, the one I used with the 10*10 example is a 84*84 matrix.

**Comment by Stygmates** [comment]
I don't need them indeed, I have rewritten the code and now it's working as intended, thanks!

**Comment by LUMacKenn** [comment]
Hello @Stygmates , I am currently trying to solve a very similar problem with constraining elements in a 2D grid based on neighboring elements, and I have been using an approach with booleans as suggested by @lperron . I was wondering if you might be able to give a hint as to how you were able to successfully add these adjacency constraints?
