### ISSUE TITLE
Not able to find solution for CVRP (Node cannot be visited by more than one vehicle)

### ISSUE THREAD

**Issue by shreyasdivan** [google/or-tools#938]
Using the python CVRP example, I am not able to find a solution. There are 27 nodes and total demand is approx. 700. 
Even with different combinations of number of vehicles and capacities, it doesn't find a solution. 
I have tried keeping the total capacity of vehicles more than twice, thrice the demand as well. 
Tried using PATH_MOST_CONSTRAINED_ARC as well apart from PATH_CHEAPEST_ARC.

The CVRP did work for smaller number of nodes (12) and lesser demands. 
Also, the solution was found if this problem was downgraded to a pure VRP.  

Can somebody please help?

Here is the [master_distance_matrix.xlsx](https://github.com/google/or-tools/files/2598463/master_distance_matrix.xlsx)

This is the distance matrix that is being used to calculate the distance between two nodes.

Below is the snippet of code which is different from the example:

```python
  def create_data_model():
  """Stores the data for the problem"""
  data = {}
  
  
  distance_matrix = # load the distance_matrix locally
  data["locations"] = distance_matrix 
  data["num_locations"] = len(data["locations"])
  demands = [0,60,67,14,4,27,32,8,34,35,19,28,12,
                   106,5,3,24,5,38,15,14,12,34,5,58,9,7]
  data["demands"] = demands
  capacities = [30]*100   
  data["num_vehicles"] = 100
  data["vehicle_capacities"] = capacities
  data["depot"] = 0
  return data
```
Custom Distance Callback: 

```python
    def create_distance_callback(data):
    """Creates callback to return distance between points."""

    def distance_callback(from_node, to_node):
        """Returns the distance between the two nodes"""
        return distance_matrix[from_node][to_node]

    return distance_callback
```

**Comment by shreyasdivan** [comment]
I checked it further, the problem here is the limitation that a node can only be visited by one vehicle (In reality there are cases wherein certain clusters have a very high demand and hence two or more vehicles could be needed to satisfy the node demand)

Can this be taken as a feature request?

**Comment by lperron** [comment]
You should duplicate nodes that can be visited by 2 vehicles.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by shreyasdivan** [comment]
Yes, that is good workaround if the capacity of all vehicles is equal. I have put equal capacity as of now in the code for test purposes.

For my actual problem however, I have to decide on the different capacities of the vehicles and the quantity of each so that there is a minimum overall cost. 
(For eg, using two 4-capacity vehicles is more expensive than using one 8-capacity vehicle)

So how do I split it? Do I split it so that the demand at the duplicate locations after split is less than the maximum capacity vehicle? Or the median capacity? Or the minimum capacity? Because that would greatly alter the solution.
