### ISSUE TITLE
.NET Core nuget package not working on linux

### ISSUE THREAD

**Issue by supermihi** [google/or-tools#940]
I cannot get the ortools nuget package running on CentOS 7 with .NET Core 2.1 (using `dotnet run`):

![image](https://user-images.githubusercontent.com/102419/48763302-3fe0e200-ecad-11e8-8056-32ec00ab5a67.png)

Looks similar to #875, but now for Linux instead of Win/Mac. I am using the following project (`csproj`) file:
![image](https://user-images.githubusercontent.com/102419/48763431-977f4d80-ecad-11e8-9fe1-964e07b12af8.png)

And a very simple test program:
![image](https://user-images.githubusercontent.com/102419/48763446-a108b580-ecad-11e8-9b21-5e67867dcf06.png)

When running with `LD_DEBUG=files`, I see an error about `CXXABI_1_3_8` not being defined in `/lib64/libstdc++.so.6`. Could the problem be an incompatible `libstdc++` on the system?

**Comment by Mizux** [comment]
nuget package have been generated with my debian for the linux runtime which is a little bit too recent concerning the ABI. Will be fix in the next release, I'll use the centos-7 as linux distro env for building the runtime instead.
cf tools/docker/Makefile `make archive_centos-7` IIRC

**Comment by Mizux** [comment]
Release v6.10 use centos-7 runtime for linux so no more glibc issue IMHO
