### ISSUE TITLE
fzn-or-tools crashed on model with set variables

### ISSUE THREAD

**Issue by DmitryEzhov** [google/or-tools#941]
In win7_64 and MiniZincIDE 2.2.3 fzn-or-tools.exe (from or-tools_flatzinc_VisualStudio2017-64bit_v6.9.5762.zip) crashed on code:
```
include "globals.mzn";

predicate alldiff_part(var int: k, array[int] of var int: vector) = 
 forall (j in 1..k) (sum (i in index_set(vector)) (bool2int(vector[i] == j)) >= 1); 

int: n = 5; int: m = 3*n-2; set of int: M = 1..m; 

array[M] of int: A = array1d(M, [m-abs(i-n) | i in M]); 

array[M, M] of var 1..10: X; 

constraint 
 forall (i,j in M where i>1 /\ i<n /\ j>1 /\ j<A[i]) 
 (alldiff_part(X[i,j]-1, [X[i-1,j-1]] ++ [X[i-1,j]] ++ [X[i,j-1]] ++ [X[i,j+1]] ++ [X[i+1,j]])); 

var int: s = sum (i,j in M where j <= A[i]) (X[i,j]); 

solve maximize s; 

output 
["\ns = \(s)\n"]
```

**Comment by lperron** [comment]
We do not support set natively but use nosets.mzn to to the conversion.
Can you include "nosets.mzn" in your file to try?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 20 nov. 2018 à 06:19, DmitryEzhov <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
Actually, it works fine for me.
How did you translate from the mzn to the fzn? Which include did you use?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by DmitryEzhov** [comment]
Yes, with `include "nosets.mzn";` work fine. Thanks! (In MiniZincIDE from mzn to fzn translate by mzn2fzn.exe)

**Comment by lperron** [comment]
Yes, but you should give a path to the or-tools/share/minizinc_sat path to
mzn2fzn.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 20 nov. 2018 à 08:06, DmitryEzhov <notifications@github.com> a
écrit :
