### ISSUE TITLE
CVRP Question - Multiple Demands at one location

### ISSUE THREAD

**Issue by abdulrk400** [google/or-tools#942]
Hi,

I have been using this tool in Python to identify optimal routes for a few trucks. This is a **delivery only** model. Goods are picked up at **Dock** and delivered on the way till all deliveries are complete and the trucks return to Dock. 

I'll try to simplify the issue I have been facing. 
Let's say I have **5 products** that need to be delivered at **location 'X' and 'Y'** each. Each product has a **weight (KG)** which has been mentioned in the demand part of the code. Here is an overview of how I have shown **multiple demands for ONE location**:

```python
 _locations = [depot,
           location X,   #Product 1
           location X,   #Product 2
           location X,   #Product 3
           location X,   #Product 4
           location X,   #Product 5
           location Y,   #Product 1
           location Y,   #Product 2
           location Y,   #Product 3
           location Y,   #Product 4
           location Y]   #Product 5
```

1. Demand at Dock is 0 because, I would like the program to automatically utilize each truck's **max capacity.** Not sure if that is a good approach.
2. Another reason the Demand is 0 is because if I set demand to **+50KG** to utilize the **max capacity** of a Truck, how do I utilize the **capacities of other Trucks** which have different max capacities?
```python
 demands = [0, # depot
             10,   #Product 1
             30,   #Product 2
             10,   #Product 3
             30,   #Product 4
             20,   #Product 5
             10,   #Product 1
             20,   #Product 2
             20,   #Product 3
             5,    #Product 4
             20]   #Product 5
```
This seems to work fine but I am not sure if this will give me an **optimal** answer. 
3. Firstly, is this method correct or is there a better way to mention **multiple demands for one location**.
4. Lastly, and this is **VERY IMPORTANT** as well. How do I make sure that when a truck visits a location, it **delivers everything in one go**? I did have an issue earlier when **Products 1,2,3,4** were delivered by **Truck A** and **Product 5** was solely delivered by **Truck B**. Due to cost issues, I cannot split the delivery into two Trucks.

Thank you,
Abdul

**Comment by Mizux** [comment]
Hi, 

1) Since you didn't do any delivery a depot/dock setting demand to 0 seems legit.

2) When you create the Demand dimension I would use
```python
routing.AddDimension(
        demand_evaluator,
        0,  # Null slack
        vehicle_capacity, # 50kg
        False,  # don't start cumul to zero
        "capacity")
```
then I would set demand as negative since you unload goods.
```python
demands = [0, # depot
             -10,    #Product 1
             -30,   #Product 2
             -10,    #Product 4
             -30,   #Product 4
             -20,   #Product 5
             -10,   #Product 1
             -20,   #Product 2
             -20,   #Product 3
             -5,     #Product 4
             -20]  #Product 5
```
note: if your vehicles have different capacities you can use:
https://github.com/google/or-tools/blob/7b5f8c6db9ade99d8858818cba0c120242a4673d/ortools/constraint_solver/routing.h#L403-L407

3) Why don't merging multiple demands at the same location if you want one truck to deliver all goods in one step ?

4) You can also force the solver to use the same vehicle for several node using:
```python
constraintActive = routing.ActiveVar(routing.NodeToIndex(A_index)) * routing.ActiveVar(routing.NodeToIndex(B_index))
routing.solver().Add(
  constraintActive * routing.VehicleVar(routing.NodeToIndex(A_index)) == 
  constraintActive * routing.VehicleVar(routing.NodeToIndex(B_index)))
```
see: https://github.com/google/or-tools/issues/847#issuecomment-420608114 for explanation...
note: it doesn't means these nodes will be consecutive in the route solution...

**Comment by emakarov** [comment]
better solution may be to create DemandDimension for every type of product, and do not increase number of locations. Just every location will have multiple demands

**Comment by abdulrk400** [comment]
@Mizux keen to hear your thoughts. Thank you.
