### ISSUE TITLE
[Help pls] VRP Adding different capacity limit each location

### ISSUE THREAD

**Issue by NinjaKing** [google/or-tools#943]
Hello all,
I am trying to add 2 constraints:
1. I would like to add capacity for each location, not each vehicle.
2. I want to reset ComulVar to zero at some specific points.
Is there any body experienced with these kind of constraints? 
Thanks all.

**Comment by Mizux** [comment]
1) Why do you want capacity at location ? Can you explain a little bit more ?

2) You can use a Negative value in the transit function to "reset" the cumulVar with a non zero slackVar so the CumulVar won't be negative.
you can try to look at example https://github.com/google/or-tools/blob/master/examples/python/cvrp_reload.py where node 1 to 5 simulate an offloading at depot...

**Comment by NinjaKing** [comment]
Thanks @Mizux 
My problem is: 1 driver need to go through many locations, in which there are some depots that driver must arrive before continue. Example, start and end from 0, need to go explore 1,2,3,....10, in which location 3 and 7 are depots also. I want to reset the travel time when leave the depots, because there is limited time constraint between depots, for example: driver only have maximum 3 hours after leave depot 0 to reach depot 3, of course he must explore some other locations.

A question, why we need to add disjunction here?
`routing.AddDisjunction([node_index], 0)`

**Comment by Mizux** [comment]
Disjunction make a node optional. i.e. the solve may visit it OR pay the penalty cost.
here it was a attempt to visit the duplicate depot (use for unloading) if not needed.

For your problem you should try to do like in the refuel example in cpp.
I mean create a "Duration" dimension with vehicle having a 3 hours of capacity and a slackvar of 3hours. each time it travel from one node to an other you "consume" time. And at depot, node 3, node 7 you "refill" your duration capacity thanks to a non zero SlackVar at these node (other node you force slackVar to 0).

https://github.com/google/or-tools/blob/60fa2fb2719409a9f2dedc38615117012c399e19/examples/cpp/cvrptw_with_refueling.cc#L118-L135

**Comment by NinjaKing** [comment]
So what is the constraint to ensure the fuel capacity is not < 0 before reach the refuel node?
And how to implement if the time limited between depots are different, for example, if we will have 4 hours to reach node 5 from node 3?

**Comment by Mizux** [comment]
A CumulVar **must** be positive. but you can have negative value.
E.g. max_capacity = 50
```
CumulVar(current) = 15
SlackVar = 45
transit = -10
CumulVar(Next) = CumulVar(Current) + transit(Current, Next) + SlackVar(current)
```

**Comment by NinjaKing** [comment]
Thanks, the last one I would like to ask for the help: I want to add a constraint so that it can balance the travel distance between drivers. Say the longest and the shortest route have different total distance < 10% for example.
And how can I add constraint that force driver must has minimum distance travel?

**Comment by lperron** [comment]
Use soft lower bound and soft upper bound on the driving cumul var at the end of each route.
