### ISSUE TITLE
Evaluating cost by delivery value and not by distance/time

### ISSUE THREAD

**Issue by Dima-Kal** [google/or-tools#944]
Hi,
So far in all of the examples i've seen, the evaluator that was sent to SetArcCostEvaluatorOfAllVehicles was distance or time matrix evaluator.
but i don't want to evaluate the cost by that method... 
I want to evaluate cost by the importance of the delivery type, for example:
1. deliveries that have a time window (that was scheduled with a customer due to a delay or something) are a must have and have a penalty of 999999....(infinite) meaning that there is no way for them to be left out
2. deliveries that are from different suppliers that are more or less valuable and have different costs, so each different delivery has a penalty according to its importance

I already have a Time dimension to calculate transit time for vehicles, and i've tried to make the evaluator to just return the cost value of delivery according to the index that is sent to that evaluator and checking the deliveries array for what type of package is it (regular 1D array) so i'm not using the to_node, only the from_node

that did not work, it wouldnt want to find a solution, so i reverted back to the distance evaluator

I've also tried to add different disjunction in the following way:
```python
    for t_idx in range(1,data.num_locations):
        if data.time_windows[t_idx][0] > 7:
            routing.AddDisjunction([int(t_idx)], 999999999999) # The task have an appointments
            continue
        if data.tasks[t_idx]['CallID'] == 'TF':
            routing.AddDisjunction([int(t_idx)], 2000) # not an important customer, can have a low penalty
        else:
            routing.AddDisjunction([int(t_idx)], 20000) # other task than the previous customer, a more important one
        if data.tasks[t_idx]['Priority'] == '1':
            routing.AddDisjunction([int(t_idx)], 50000) # another type of task that is more important than the previous
```
but that did not work since it would still drop nodes that has time windows, and would put not important tasks instead.

How can I approach this problem? what am I doing wrong?

also, how can show cost of route?
I've tried using:
```python
cost += routing.GetArcCostForFirstSolution(
  node_index,
  routing.IndexToNode(assignment.Value(routing.NextVar(index))))
```

but it returned me the cost from the Time dimension evaluator and not the cost evaluator, and would not show any penalties that were given upon dropping nodes

**Comment by Mizux** [comment]
To have mandatory node prefer to use [`kint64max`](https://github.com/google/or-tools/blob/554cbccaa95b4c11eced13f145de1bf468e1f919/ortools/base/integral_types.h#L115-L116) instead of a big number.
i.e. the solver discard a solution (i.e. must find an other one) if objective overflow i.e. use kint64max otherwise it is legit for the solver to have/return a "sub-optimal" solution of 999999999....
This should avoid the solver to drop "mandatory" nodes

The objective cost should contains the sum of "visited arc" cost + any penalty cost.
```python
print('Objective: {}'.format(assignment.ObjectiveValue()))
```

**Comment by Dima-Kal** [comment]
I've tried with the kmaxint but it couldn't find a solution even though a solution is totally feasible, even if removing all other nodes that have a regular disjunction
I think that there is a bug with the disjunctioning

**Comment by Dima-Kal** [comment]
Using the following code :
previous_index = index
index = assignment.Value(routing.NextVar(index))
cost = routing.GetArcCostForVehicle(previous_index, index, vehicle_id)

Did not retrieve me the cost including penalties 
It looks like the cost that was determined by the dimension evaluator and not the cost evaluator

**Comment by lperron** [comment]
You can have a unary transit, that only depends on the visited node.
