### ISSUE TITLE
ortools package doesn't work on Heroku's standard python buildpack

### ISSUE THREAD

**Issue by supriya-clutter** [google/or-tools#949]
When trying to run a python app with ortools on Heroku, I get the following error:
```python
File "or.py", line 2, in <module>
from ortools.constraint_solver import pywrapcp
ModuleNotFoundError: No module named 'ortools'
```

I am setting up ortools in the post compile script: 
` python -m pip install -U --user ortools`
Logs from the build:
```shell
-----> Running post-compile hook
Collecting ortools
  Downloading https://files.pythonhosted.org/packages/31/ea/7e085dc9add0875e235ac13723d4105977d1d5efaef6423454ef72c67b29/ortools-6.9.5824-cp36-cp36m-manylinux1_x86_64.whl (23.7MB)
Collecting six>=1.10 (from ortools)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting protobuf>=3.6.1 (from ortools)
  Downloading https://files.pythonhosted.org/packages/c2/f9/28787754923612ca9bfdffc588daa05580ed70698add063a5629d1a4209d/protobuf-3.6.1-cp36-cp36m-manylinux1_x86_64.whl (1.1MB)
Collecting setuptools (from protobuf>=3.6.1->ortools)
  Downloading https://files.pythonhosted.org/packages/e7/16/da8cb8046149d50940c6110310983abb359bbb8cbc3539e6bef95c29428a/setuptools-40.6.2-py2.py3-none-any.whl (573kB)
Installing collected packages: six, setuptools, protobuf, ortools
Successfully installed ortools-6.9.5824 protobuf-3.6.1 setuptools-40.6.2 six-1.11.0
```

What else am I missing ?

**Comment by Mizux** [comment]
`--user` will install ortools for one user not system wide. Are you sure the "post-compile hook" and you "or.py" are run by the same user id ?

**Comment by lperron** [comment]
and which platform?  Windows requires some visual studio redistributables
to be installed.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
Answered too fast.

It could be a glibc mismatch. You can try setting PYTHONVERBOSE=1 in your
shell before running the example.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by davidolmo** [comment]
I did mount or-tools on heroku without any problem. If I recall correctly, it DIDN'T work on python 3.7 heroku runtime, but IT DID WORK on 3.6.6

**Comment by supriya-clutter** [comment]
Thanks @davidolmo @Mizux @lperron.

Adding `ortools` in requirements.txt didn't work, and that might be because I was running on python 3.7 heroku runtime. I went around it by running `python -m pip show ortools` in the post_compile script, which worked. Thanks!

**Comment by Mizux** [comment]
I just tested heroku-18
```shell
docker run --rm -it heroku/heroku:18
root@900c723c94bd:/# python --version
Python 2.7.15rc1
root@900c723c94bd:/# python3 --version
Python 3.6.7
root@900c723c94bd:/# python3 -m pip
/usr/bin/python3: No module named pip

root@900c723c94bd:/# apt-get update
root@900c723c94bd:/# apt-get install python3-pip
root@900c723c94bd:/# python3 -m pip install ortools
...
Successfully installed ortools-6.10.6025 protobuf-3.6.1
root@900c723c94bd:/# python3 -c "from ortools.linear_solver import pywraplp"
```

So except that pip is not installed by default :-1: , python3 seems working IMHO
