### ISSUE TITLE
Help needed to add diminishing cost for each node visited by a vehicle

### ISSUE THREAD

**Issue by junquant** [google/or-tools#950]
Hi

I needed to add a diminishing cost for each of the node visited by a specific vehicle. For example, in a graph with 5 nodes [0,1,2,3,4] where [0] is the depot, 

Route for vehicle 0:
 0 -> 2 -> 3 -> 1 -> 0
Base Cost: 100
Cost for [2]: (1 * Base Cost) + Distance traveled from 0 -> 2
Cost for [3]: (0.5 * Base Cost) + Distance traveled from 2 -> 3
Cost for [1]: (0.2 * Base Cost) + Distance traveled from 3 -> 1
Cost for [0]: (0 * Base Cost) + Distance traveled from 1 -> 0

Would greatly appreciate any help in achieving this. I am using Python. Thanks!

**Comment by Mizux** [comment]
You'll need `AddDimensionDependentDimensionWithVehicleCapacity() ` which is not available on Python see #339

**Comment by junquant** [comment]
Thanks!
