### ISSUE TITLE
Get routing fail reason and a subset of solution

### ISSUE THREAD

**Issue by Skullflow** [google/or-tools#952]
Hi, thanks for this amazing library.

I'm working on a Vehicle Routing Problem with Time Windows and i was wondering if exists a method to get the reason of a routing failure (a simple error message) and then get a subset of the optimal solution.

For example if I have 3 deliveries {x1,x2,x3} but x3 is not feasible, i want to remove x3 and get the optimal solution computed on x1 and x2.

Maybe i'm missing something in the documentation...

Thanks!

**Comment by Mizux** [comment]
If you want a solution without x3, you should use a disjunction constraint.

Please see https://github.com/google/or-tools/issues/883#issuecomment-429214756

**Comment by Skullflow** [comment]
And how can I use this constraint in a Python project?

**Comment by Mizux** [comment]
https://github.com/google/or-tools/blob/554cbccaa95b4c11eced13f145de1bf468e1f919/examples/python/cvrptw_plot.py#L674-L679

**Comment by Skullflow** [comment]
Ok, I will read these examples. Thanks!
