### ISSUE TITLE
Conflicting declaration typedef between OR-Tools and OpenCV on ARM

### ISSUE THREAD

**Issue by rjurga** [google/or-tools#955]
I made good progress on the issue #716 but in the process I'm hitting a new issue.

When compiling programs using both OR-Tools and OpenCV, the following conflict happens:
```
/usr/local/include/ortools/base/integral_types.h:38:19: error: conflicting declaration 'typedef long long int int64'
 typedef long long int64;            // NOLINT
```
and
```
/usr/local/include/ortools/base/integral_types.h:53:28: error: conflicting declaration 'typedef long long unsigned int uint64'
 typedef unsigned long long uint64;  // NOLINT
```

Here are the relevant declaration from OpenCV:

```
.../include/opencv2/core/hal/interface.h:61:19: note: previous declaration as 'typedef int64_t int64'
   typedef int64_t int64;
```
and
```
.../include/opencv2/core/hal/interface.h:62:20: note: previous declaration as 'typedef uint64_t uint64'
   typedef uint64_t uint64;
```

Further down the line, this causes the following errors:
```
/usr/local/include/ortools/base/join.h:56:3: error: 'absl::AlphaNum::AlphaNum(int64)' cannot be overloaded
   AlphaNum(int64 i64)  // NOLINT(runtime/explicit)
   ^~~~~~~~
/usr/local/include/ortools/base/join.h:52:3: error: with 'absl::AlphaNum::AlphaNum(long int)'
   AlphaNum(long l)  // NOLINT
   ^~~~~~~~
/usr/local/include/ortools/base/join.h:58:3: error: 'absl::AlphaNum::AlphaNum(uint64)' cannot be overloaded
   AlphaNum(uint64 u64)  // NOLINT(runtime/explicit)
   ^~~~~~~~
/usr/local/include/ortools/base/join.h:54:3: error: with 'absl::AlphaNum::AlphaNum(long unsigned int)'
   AlphaNum(unsigned long ul)  // NOLINT
   ^~~~~~~~
```

All this occurs on ARM AARCH 64 but not on x86_64.

**Comment by Mizux** [comment]
FYI:
OpenCV defined:
https://github.com/opencv/opencv/blob/197285d12a8aa8c5b799f17f41089ac85db5f5bc/modules/core/include/opencv2/core/hal/interface.h#L61-L62

In ortools/base:
https://github.com/google/or-tools/blob/b641696c7ecd90a7259c3c24ae7d38b29c606916/ortools/base/integral_types.h#L35-L39

https://github.com/google/or-tools/blob/b641696c7ecd90a7259c3c24ae7d38b29c606916/ortools/base/integral_types.h#L50-L54

And Protobuf (one of our dependencies) use:
https://github.com/protocolbuffers/protobuf/blob/704037f23a9ede00ec4fcf40d568712ce6200934/src/google/protobuf/stubs/port.h#L137-L157

**Comment by lperron** [comment]
Just created https://github.com/google/or-tools/issues/959
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by lperron** [comment]
I have pushed the change to use int64_t in or-tools to github.
Can you retry?

**Comment by lperron** [comment]
I will close the issue now. Please reopen if you have any problem.
