### ISSUE TITLE
Action followed by Action by another vehicle

### ISSUE THREAD

**Issue by GuyBenhaim** [google/or-tools#956]
Assume we have point A which a vehicle visits and want **another vehicle to visit it later**,  basically by assigning A' at the same geolocation for the later visit.

However, as visit time at A is unknown before planning - can we constrain the solver such that visit time to A' will take place only after the visit to A?

**Comment by Mizux** [comment]
```python
routing.Add(
routing.CumulVar(routing.NodeToIndex(A)) < routing.CumulVar(routing.NodeToIndex(A'))
)
```

?

**Comment by GuyBenhaim** [comment]
Thx! Would this apply for different vehicles in A and A' ?

No. #783 asks for the same vehicle for all Node visits

**Comment by jmarca** [comment]
> **Thx!**
> Would this apply for different vehicles in A and A' ?

Yes.  Unless you constrain the vehicles in some way, all the constraint says is that the "dimension_name" at `a_idx` is less than the value of "dimension_name" at `aprime_idx`.  The constraint by itself does not care about what vehicles serve a and aprime.

> Can we also include integer delay: routing.solver().Add(routing.CumulVar(a_idx, "dimension_name") + DELAY < routing.CumulVar(aprime_idx, "dimension_name"))
> 

Yes, I do that all the time.
