### ISSUE TITLE
Limit the number of locations visited by a vehicle in CVRP

### ISSUE THREAD

**Issue by adri-MASH** [google/or-tools#958]
Hi all,
First of all, thank you for the library, I used the CVRP tutorial successfully to describe a standard CVRP with one depot and multiple vehicles.
I wonder if there is a way to set a constraint on the number of nodes every vehicle can visit, in addition to the capacity constraint? 
For example, if I set the limit to 5, I would not get any routes with more than 5 pickup/drop off locations (not counting the depot).

Thanks for your help!
Adri

**Comment by adri-MASH** [comment]
Hey, I haven't found a solution to my problem.
I am using the Saving heuristic for now and If I understand the algo correctly. It should be possible to add this type of constraint. Probably by preventing the merging of two routes if the number of stops is more than the max authorised. I just want to know if there is a way to incorporate this constraint in the solver.
Thanks!
Adri

**Comment by Mizux** [comment]
Just create a new dimension where each location add 1 and set vehicle capacity to 5 ?

**Comment by adri-MASH** [comment]
Indeed, I never thought of adding another dimension. 
Thanks for your help Mizux, my problem is solved!

**Comment by TeodoraB21** [comment]
How can I set a minimum of stops that each route can have?

**Comment by Mizux** [comment]
Using a dimension which increase by one at each stop (using unary callback for instance) simply add constraint on End(i) node that `routing.Add(dimension.CumulVar(routing.End(vehicle_index)) >= minimum)`

**Comment by TeodoraB21** [comment]
But there is no "Add()" method for RoutingModel.

**Comment by Mizux** [comment]
Sorry, you need to grab the underlying CP solver `routing.solver() ....`

**Comment by TeodoraB21** [comment]
thank you!

**Comment by TeodoraB21** [comment]
I don't have the latest version of the code (I have the version 6), so I can't use RegisterUnaryTransitCallback(lambda index : 1).
So I made a class:

class VehicleStops 
{
public:
	int64 Run(operations_research::RoutingModel::NodeIndex FromNode, operations_research::RoutingModel::NodeIndex ToNode)
	{
		return 1;	//add 1 for each stop added
	}
};
and I added a new dimension:
VehicleStops vehStops;
routing.AddDimensionWithVehicleCapacity(NewPermanentCallback(&vehStops, &VehicleStops::Run), 0, m_vehicles->GetMaxNumberOfStopsForVehicles(), true, "NrStops");
const operations_research::RoutingDimension& nrStopsDimension = routing.GetDimensionOrDie("NrStops");
std::vector<pair<int32, int32>> nrStopsRange = m_vehicles->GetNrStopsRange();
for (int32 i = 0; i < routing.vehicles(); i++)
   nrStopsDimension.CumulVar(routing.End(i))->SetMin(nrStopsRange.at(i).first);

And in the input I specified that:
MinNumberOfStops: 2, 3, 1
MaxNumberOfStops: 3, 7, 3

But the solution is this:
Route nr:0
index 0  distance 0
index 1  distance 58
index 8  distance 1154
index 9  distance 1963
Route nr:1
index 6 distance 0
index 7 distance 351
index 5 distance 1009
index 2 distance 1327
Route nr:2
index 4 distance 0
index 3 distance 957

So why for the first vehicle it puts 4 stops, if I set the maximum to be 3?

**Comment by VisheshArora** [comment]
@adri-MASH and @Mizux , can you please help me with the code of adding a new dimension? Thanks in advance.

**Comment by miguelmarengo** [comment]
> What are you referring as _the capacity constraint_ ? You can have as many dimension as you want.
> 
> i.e. Just create a new dimension where each location (pickup?) add 1 and set vehicle capacity to 5 ?

Hi, how do i add 1 and where, can i see the python code?
