### ISSUE TITLE
Swig for graph decomposition

### ISSUE THREAD

**Issue by pocman** [google/or-tools#96]
Would it be possible to add some java swig interface for the *graph decompositions* ?
In our use-case, we need to find **cliques**.

We would like to avoid the need for an other, not yet identified, library.

**Comment by lperron** [comment]
Hi

Which API would you like to use? (which .h)

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2015-09-29 15:38 GMT+02:00 Thomas <notifications@github.com>:

**Comment by maisa26** [comment]
we will use connectivity.h and cliques.h
