### ISSUE TITLE
C# examples do not compile, RoutingIndexManager missing

### ISSUE THREAD

**Issue by tdsrhh** [google/or-tools#962]
Downloaded the latest source, tried to compile the examples but I get

RoutingIndexManager missing and RoutingModel.RegisterTransitCallback missing.

What am I missing ?

**Comment by Mizux** [comment]
Hi,

Can you give me more details of your setup ? OS ? command you run ? output ?

Thx

**Comment by tdsrhh** [comment]
Visual studio 2017, sample Google.OrTools.Examples.sln in sub folder or-tools-master\examples\dotnet

cscvrptw.cs(67,22,67,41): error CS0246: The type or namespace name 'RoutingIndexManager' could not be found (are you missing a using directive or an assembly reference?)  
cscvrptw.cs(89,13,89,32): error CS0246: The type or namespace name 'RoutingIndexManager' could not be found (are you missing a using directive or an assembly reference?)
cstsp.cs(21,28,21,47): error CS0246: The type or namespace name 'RoutingIndexManager' could not be found (are you missing a using directive or an assembly reference?)
9>cstsp.cs(43,13,43,32): error CS0246: The type or namespace name 'RoutingIndexManager' could not be found (are you missing a using directive or an assembly reference?)

**Comment by tdsrhh** [comment]
Removed all 6.10 from my computer, but still the source gives the same error ...

**Comment by Mizux** [comment]
ok I just bump the version on al .Net proj so you should not have this issue anymore if you pull the master HEAD.

note: You have to build a local package first.
note: sometime you may still have package in the nuget cache, I use 
```shell
dotnet nuget locals all --clear
```
to clean it (on unix but should work on any platform dotnet/cli support)

**Comment by tdsrhh** [comment]
OK, thanks.

How do I build a local package ? Do I have to install python compiler or something like that ? I am not to familiar with python tools …

Regards

**Comment by Mizux** [comment]
You can follow https://developers.google.com/optimization/install/dotnet/source_windows
Basically we are using a Makefile-based build using the windows command prompt shipped by VS.
note: `make.exe` is provided in `tools`...

Otherwise you can try examples using the [`v6.10.x`](https://github.com/google/or-tools/tree/v6.10.x) branch  or the `v6.10` tag

**Comment by tdsrhh** [comment]
Ok, Thanks a lot. Now I got it working. Great !

**Comment by Muhammad-Altabba** [comment]
Why the installed version at https://developers.google.com/optimization/install/dotnet/windows, is not the latest? It is 6.10, and for this, it is not compatible with the code examples at the website (https://developers.google.com/optimization/introduction/overview).

**Comment by Mizux** [comment]
The latest **stable** version is `v6.10`.
`master` is our dev branch and currently it is just a v7.0-beta ...
website should be in sync with the v6.10 can you give us the url containing a samples, not working with v6.10 ?

Thanks

**Comment by Muhammad-Altabba** [comment]
Sorry, the website samples are compatible with `v6.10`. While, the incompatible documentation and code with v6.10 are those at github like in: https://github.com/google/or-tools/blob/master/ortools/constraint_solver/samples/VrpTimeWindows.cs which is mentioned here: https://github.com/google/or-tools/blob/master/ortools/constraint_solver/doc/vrp.md
Actually, It is sound to have the latest samples on github according to the latest version, even if it is not the stable. But, adding a comment specifying the compatible version will be valuable.

**Comment by lperron** [comment]
Agree  on the comment, but it is reasonable to assume that if you look at
head on github, it requires to compile the code from there.
FYI, we have created a 'stable' branch on github that will always contain
the latest stable branch.

Doc on devsite will always point to this branch.


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le lun. 4 févr. 2019 à 07:51, Muhammad Altabba <notifications@github.com> a
écrit :
