### ISSUE TITLE
Problem with building OR-Tools with SCIP

### ISSUE THREAD

**Issue by jerviedog** [google/or-tools#963]
Deal all,

I wanted to build or-tools with scip enabled. 

I have installed scip. According to the guide, I edited the Makefile.local and did "make third_party". All went ok.

While I "make cc", an error occured: 
g++: error: /opt/scip/lib/libscip.a: No such file or directory
g++: error: /opt/scip/lib/libscipopt.a: No such file or directory
g++: error: /opt/scip/lib/libsoplex.linux.x86_64.gnu.opt.a: No such file or directory
makefiles/Makefile.cpp.mk:185: recipe for target 'lib/libortools.so' failed

There were no libscip.a, libsciopt.a, or libsoplex.linux.x86_64.gnu.opt.a in the lib directory. There are files in the directory:
libgcg.so
libgcg.so.3.0
libgcg.so.3.0.0.0
libscip.so
libscip.so.6.0
libscip.so.6.0.0.0
libsoplex.a
libsoplex-pic.a

Can any one give me a hint on how to modify the makefile so that libscip.so, instead of libscip.a is linked?

**Comment by lperron** [comment]
Did you compile SCIP with the following command line:

make GMP=false READLINE=false ZIMPL=false TPI=tny USRCFLAGS=-fPIC
USRCXXFLAGS=-fPIC USRCPPFLAGS=-fPIC
make install INSTALLDIR=<path to install to specifiy in Makefile.local>
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
**/!\ WARNING not supported /!\\**
If you want to use SCIP as dynamic look at:
https://github.com/google/or-tools/blob/13c82b0bd4b44b2040387ee1f155fce0c1d9ffa5/makefiles/Makefile.unix.mk#L200-L207

**Comment by jerviedog** [comment]
> Did you compile SCIP with the following command line: make GMP=false READLINE=false ZIMPL=false TPI=tny USRCFLAGS=-fPIC USRCXXFLAGS=-fPIC USRCPPFLAGS=-fPIC make install INSTALLDIR=<path to install to specifiy in Makefile.local>

Yes, I tried this once again. Still, there were libscip.a, libscipopt.a, etc.

**Comment by jerviedog** [comment]
Mizux, 

Yes, I knew these lines in or-tools/makefiles/Makefile.unix.mk. I just didn't know how to modify it:(

By hints from lines below, should I change the SCIP_LNK variable to:
-Wl,-rpath $(UNIX_SCIP_DIR)/lib -L$(UNIX_SCIP_DIR)/lib -m64 -lc -ldl -lm -lphread -lscip
?

I did this, and there seemed to be no error. The test seemed ok too. Here is the several lines of the test output containing SCIP:
I1207 10:55:50.642125  6767 integer_programming.cc:73] ---- Integer programming example with SCIP ----
I1207 10:55:50.649621  6767 integer_programming.cc:44] Number of variables = 2
I1207 10:55:50.649646  6767 integer_programming.cc:45] Number of constraints = 2
I1207 10:55:50.652020  6767 integer_programming.cc:52] Solution:
I1207 10:55:50.652045  6767 integer_programming.cc:53] x = 3
I1207 10:55:50.652055  6767 integer_programming.cc:54] y = 2
I1207 10:55:50.652061  6767 integer_programming.cc:55] Optimal objective value = 23
I1207 10:55:50.652070  6767 integer_programming.cc:56]
I1207 10:55:50.652078  6767 integer_programming.cc:57] Advanced usage:
I1207 10:55:50.652088  6767 integer_programming.cc:58] Problem solved in 9 milliseconds
I1207 10:55:50.652099  6767 integer_programming.cc:59] Problem solved in 0 iterations
I1207 10:55:50.652109  6767 integer_programming.cc:60] Problem solved in 1 branch-and-bound nodes
make[1]: Leaving directory 

Is this ok?

**Comment by Mizux** [comment]
I would say yes, it seems to be running. Good Job ! :+1: 

this `SCIP_LNK` is include later in `DEPENDENCIES_LNK`:
https://github.com/google/or-tools/blob/58288b25abc16c753a9719ac5a31eec32facb166/makefiles/Makefile.unix.mk#L257

which is use when compiling ortools:
https://github.com/google/or-tools/blob/58288b25abc16c753a9719ac5a31eec32facb166/makefiles/Makefile.cpp.mk#L163-L192

**Comment by rlloretb** [comment]
Got this fixed in 7.1 and SCIP 6.0.0? I get the same error as the OP.
