### ISSUE TITLE
Get objective value of routing problem

### ISSUE THREAD

**Issue by tgsmith61591** [google/or-tools#965]
I've been trying to create an objective value callback for my routing problem similar to this [`CPSolver` example](https://developers.google.com/optimization/cp/cp_solver). CP example callback code:

```python
class VarArraySolutionPrinter(cp_model.CpSolverSolutionCallback):
    """Print intermediate solutions."""

    def __init__(self):
        cp_model.CpSolverSolutionCallback.__init__(self)
        self.__solution_count = 0

    def on_solution_callback(self):
        self.__solution_count += 1
        print(self.ObjectiveValue())

    def solution_count(self):
        return self.__solution_count
```

How can I similarly get the objective value from a routing problem in a callback? Something like:

```python
routing = pywrapcp.RoutingModel(n_locations,
                                n_vehicles,
                                start_locations,
                                end_locations)

routing.AddAtSolutionCallback(VarArrayAndObjectiveSolutionPrinter().on_solution_callback)
```

This obviously doesn't work. Is there a method in the routing class that I'm missing somewhere?

**Comment by Mizux** [comment]
Note the `on_solution_callback` change its syntax in v6.9 IIRC.

here you a re using the new syntax which only work with a recent version of ortools

**Comment by tgsmith61591** [comment]
Calling `routing.solver()` is helpful, thanks. But it doesn't look like the solver has an `ObjectiveValue` method. Is there a different way to get the value?

Thanks for the help on this.

**Comment by lperron** [comment]
You need to store the objective var in the callback, and call Value() on it, while at the leaf.

**Comment by AndreasH96** [comment]
@tgsmith61591 @lperron  @Mizux 

 Hi, I'm having the same problem currently. I'm trying to get either the current created routes at the callback or the values of the added dimensions I've added with .AddDimension() to a routing model. Did you succeed to solve your problem?  Or how could this be done?

Best Regards

**Comment by lperron** [comment]
The callbacks are stateless. You cannot query a (partial) solution when it
is called.
In fact, it is usually cached, and called before the search actually
happens.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
