### ISSUE TITLE
how to get intervalvar element's name in python?

### ISSUE THREAD

**Issue by morruth** [google/or-tools#967]
i've tried to add breaks in cvrptw solver, using [cvrptw_with_breaks.cc](https://github.com/google/or-tools/blob/c52e9d95b94c9af5cfde91542567ec2e6cbd0757/examples/cpp/cvrptw_with_breaks.cc#L154-L190) as reference

```python
break_intervals=[solver.FixedDurationIntervalVar(5000,10000,10,False,'Break for vehicle 0')]
time_dimension.SetBreakIntervalsOfVehicle(break_intervals, 0)

```
seems really adding break, but i can't get break's name in solution
the next loop get elements from intervalVarContainer and shows
is it activated and prints this break's start time and duration
```python
    # Solve displays a solution if any.
    assignment = routing.SolveWithParameters(search_parameters)
    if assignment:

      intervals= assignment.IntervalVarContainer()
      for intrvlind in xrange(intervals.Size()):
        print dir(intervals.Element(intrvlind))
        
        print intervals.Element(intrvlind).PerformedValue()
        print intervals.Element(intrvlind).DurationValue()
        print intervals.Element(intrvlind).StartValue()
```

but when I try to use intervals.Element(intrvlind).name()
as in CPP example

https://github.com/google/or-tools/blob/37776ddc6f1c12daa5426b7fc9b954f492ba97fd/examples/cpp/cvrptw_with_breaks.cc#L203-L213

it says  «AttributeError: 'IntervalVarElement' object has no attribute 'name'»

and print dir(intervals.Element(intrvlind)) shows

['Activate', 'Activated', 'Deactivate', 'DurationMax', 'DurationMin', 'DurationValue', 'EndMax', 'EndMin', 'EndValue', 'PerformedMax', 'PerformedMin', 'PerformedValue', 'SetDurationMax', 'SetDurationMin', 'SetDurationRange', 'SetDurationValue', 'SetEndMax', 'SetEndMin', 'SetEndRange', 'SetEndValue', 'SetPerformedMax', 'SetPerformedMin', 'SetPerformedRange', 'SetPerformedValue', 'SetStartMax', 'SetStartMin', 'SetStartRange', 'SetStartValue', 'StartMax', 'StartMin', 'StartValue', '__class__', '__del__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattr__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__swig_destroy__', '__swig_getmethods__', '__swig_setmethods__', '__weakref__', '_s', 'this']

there is no 'name' in this list

BTW, DebugString is also can't be used

**Comment by lperron** [comment]
This is just a storage for the values of the solution. 
You can get the name with element->Var()->Name().

**Comment by morruth** [comment]
> This is just a storage for the values of the solution.
> You can get the name with element->Var()->Name().

In C++ - yes.
But I don't see Var() method in python interface
(looks like this is intervals.Element(index), but there is no Name() method in returned object)

**Comment by Mizux** [comment]
`IntervalVar` should inherit from `PropagationBaseObject`
https://github.com/google/or-tools/blob/b8fe719ce0a4145cd96701481d8c111d3025c77d/ortools/constraint_solver/constraint_solver.h#L4218

and `PropagationBaseObject` has a `name()` method
https://github.com/google/or-tools/blob/b8fe719ce0a4145cd96701481d8c111d3025c77d/ortools/constraint_solver/constraint_solver.h#L3145-L3151

which seems to be binded in python
https://github.com/google/or-tools/blob/b8fe719ce0a4145cd96701481d8c111d3025c77d/ortools/constraint_solver/python/constraint_solver.i#L1273-L1280

**Comment by morruth** [comment]
but how extract it from routing solution?

**Comment by Mizux** [comment]
For `IntervalVarElement`:
https://github.com/google/or-tools/blob/b8fe719ce0a4145cd96701481d8c111d3025c77d/ortools/constraint_solver/constraint_solver.h#L4538
https://github.com/google/or-tools/blob/b8fe719ce0a4145cd96701481d8c111d3025c77d/ortools/constraint_solver/constraint_solver.h#L4545

Seems to be ignored by swig.
https://github.com/google/or-tools/blob/b8fe719ce0a4145cd96701481d8c111d3025c77d/ortools/constraint_solver/python/constraint_solver.i#L1772-L1779

**Comment by Mizux** [comment]
-> need to check why this is ignored i.e. not binded in python

**Comment by morruth** [comment]
then reopen this issue until you check it, please

**Comment by morruth** [comment]
is this changes already in 6.10.6025 version accessible from PyPi, or i should rebulid it from git myself?
