### ISSUE TITLE
Additional vehicle cost based on total distance or time traveled

### ISSUE THREAD

**Issue by ConnerWestover** [google/or-tools#969]
I'm using Google Or Tools in C# and have a question that is essentially the title. Is there a way to add an additional cost to a vehicle if it is taking stops that would break a certain amount of distance or time? Whether the solution is 'At 100 miles they get an additional cost of 100' or 'cost for additional time is doubled at 4 hours' it would be great. I'm currently using the RoutingModel.SetVehicleCost() function to calculate cost now. Any help is appreciated.

**Comment by GuyBenhaim** [comment]
Hi,
I will be glad to see such capability, or at least get some state information provided to the call-backs.

BTW, I could not find  .SetVehicleCost() in the Routing.h  -is it the same as SetArcCostEvaluatorOfVehicle() ?

**Comment by Mizux** [comment]
1) `RoutingModel.SetVehicleCost()` is a deprecated method in v6.10 which must be replaced by `SetArcCostEvaluatorOfVehicle()`.
see:
https://github.com/google/or-tools/blob/b275b56ff658bc7eb294221dc32639345eddbfee/ortools/constraint_solver/routing.h#L962-L968

On master, which will be the 7.0 this method has been removed since you need first to register callback then use the generated callback index here and there.

2) Basically, you'll need `AddDimensionDependentDimensionWithVehicleCapacity()` #339

**Comment by ConnerWestover** [comment]
Thanks for the responses. I guess I need to update my Or Tools package. I'm still a little confused on how AddDimensionDependantDimensionWithVehicleCapacity() can solve my question. Purely how this fucntion/dimension would affect the cost created in SetArcCostEvaluatorOfvehicle. Could anyone point me to some more documentation outside of this github related to the methods above? Or explain it a little more? Anything done is much appreciated.

**Comment by Mizux** [comment]
Sorry, it won't add cost to `SetArcCostEvaluatorOfvehicle`, it will create a new dimension with its own constraint but you can set a coefficient on span cost for any dimension using:
https://github.com/google/or-tools/blob/b70c189167a5f7d584262aa2f7e153f1a739c347/ortools/constraint_solver/routing.h#L1665-L1679

Thus it will be added to the objective function, by default it is set to zero.
note: you can see the `SetArcCostXXX()` as a method used to define a transit callback of a hidden dimension with span cost coefficient of 1.

**Comment by GuyBenhaim** [comment]
Interesting. Is there an example for that one?

**Comment by Mizux** [comment]
For `GlobalSpanCost ` you can see the effect here: https://github.com/google/or-tools/tree/mizux/doc/doc#vehicle-routing-problem
without solver use one vehicle -> kind of Tsp, with globalSpanCost all four vehicles are used....

**Comment by GuyBenhaim** [comment]
So, this basically 'penalizes' the objective function for vehicle idles times, in case Solver adds slack to meet certain time/time-window constraints?  Is this per vehicle?

**Comment by Mizux** [comment]
`GlobalSpanCost` is one cost since it use `Min()`, `Max()`, `SpanCost` is for one route/vehicle.

**Comment by GuyBenhaim** [comment]
Thx. 
How can one determine which dimension GlobalSpanCost or SpanCost applies to?  
(Several dimensions are likely to exist: time, distance, capacity)

**Comment by Mizux** [comment]
well you set the [Global]SpanCostCoefficient on a Dimension object using the methods:
https://github.com/google/or-tools/blob/0d8f52397810a022d149a7dc082017f88e8e8762/ortools/constraint_solver/routing.h#L1660-L1674
so it seems obvious....

**Comment by GuyBenhaim** [comment]
Just another clarification: if our ArcCost was proportional do distances across all the arcs traveled (in one route or in all routes) then, span cost will also add cost for the time on all the arcs traveled;  i.e. penalize twice?

**Comment by Mizux** [comment]
yes.

note: you can see `SetArcCost...()` like a method calling `SetSpanCostCoefficientForAllVehicles(1);`  on a hidden primitive dimension...

**Comment by VitamintK** [comment]
what does `span` mean?  Is it a synonym of `arc`?
