### ISSUE TITLE
[Help Wanted] Reducing latency for convex constraint optimization

### ISSUE THREAD

**Issue by kunaltyagi** [google/or-tools#970]
### Background

I'm working with a convex constraints. The solver has to solve the optimization problem multiple in a time constraint environment. The optimization problem is to bring a design point to the closest possible valid region. If it is inside the valid region, no change should occur. 

My model looks something like 
```
Solution = minimize distance(solution_point, design point) subject to constraints
```

### Problem

Reduce the time taken from when the design point is received till the optimized point is found.

### Current Design

The design point is modeled as an additional constraint. All constraints activated are saved in a deque. Design point changes at magnitudes faster than the constraints (usually 1-2 magnitude difference)
1. Long term constraints are added to the solver
2. Design point is added to the solver
3. Optimization is run
This approach allows me to dynamically add or remove constraints at the end of each cycle.

### Design aims
I've the following design in mind to reduce the latency:
1. Maintain a list of active and inactive constraints. 
    * When a request to add a constraint arrives, active list is checked to see of any constraint is same or rendered inactive by the new one. Inactive list is checked for duplicate constraint before it is added.
    * When a request to remove a constraint arrives, if it's in inactive list, remove it. Else remove from active list, and check all inactive constraints.
2. Check if the point needs to be optimized.
3. Optimize it.

I don't know if this
* gives me the reduced latency. Especially 2 and 3. 
    * Might be cheaper and more reliable to just optimize every point (hot path execution, Icache and Dcache benefits)
    * Most of the design points are close to border inside the constraints (based on domain knowledge), so if checking is faster, it might give an overall win.
* is feasible, especially checking if a constraint is active/inactive and removing it from solver.

I'm a relative beginner to OR Tools and thus might be missing the "correct way" to use it. I'm trying to do what I've experience as useful when working with other optimization tools.

And yes, benchmarking is the only way to know for sure, but I need to know how and what to change before I can do a comparison.

PS: I hope this is a good place to ask questions.

**Comment by lperron** [comment]
Frankly, or-tools is not meant for this use case.
