### ISSUE TITLE
CP-Sat solver doesn't optimize objective function

### ISSUE THREAD

**Issue by gregy4** [google/or-tools#971]
I try to minimize capacity of cumulative constraint for a scheduling problem with around 2 thousand jobs. First solution is found very quickly (in few seconds) but than I see nearly no future progress. When I changed upper limit of capacity variable to lower value, first solution is found again very quickly. For the example it was no problem to find a solution in interval 150 ... 200.

Since described behavior is not good for my needs when sum of capacities over cumulative constraints will be optimized I want to know it is a bug or not yet optimized case for  CP-Sat solver so I can decide to implement / not implement my complete scheduling problem.

Thanks,
Jan

[example.zip](https://github.com/google/or-tools/files/2662882/example.zip)

**Comment by lperron** [comment]
Interesting :-)

Adding parallelism helps a little:

solver = cp_model.CpSolver()
solver.parameters.num_search_workers=10
solution_printer = cp_model.ObjectiveSolutionPrinter()
solver.SolveWithSolutionCallback(model, solution_printer)

outputs:

Solution 0, time = 8.033745 s, objective = [150, 10] Solution 1, time =
12.224240 s, objective = [149, 10] Solution 2, time = 15.476527 s,
objective = [148, 10] Solution 3, time = 18.573410 s, objective = [147, 10]
Solution 4, time = 21.726396 s, objective = [146, 10] Solution 5, time =
26.161401 s, objective = [145, 10] Solution 6, time = 30.520608 s,
objective = [144, 10] Solution 7, time = 33.868861 s, objective = [143, 10]
Solution 8, time = 37.089386 s, objective = [142, 10] Solution 9, time =
40.100520 s, objective = [141, 10] Solution 10, time = 43.296578 s,
objective = [140, 10] Solution 11, time = 46.506000 s, objective = [139,
10] Solution 12, time = 49.685793 s, objective = [138, 10] Solution 13,
time = 52.969709 s, objective = [137, 10] Solution 14, time = 56.172730 s,
objective = [136, 10] Solution 15, time = 60.789545 s, objective = [135,
10] Solution 16, time = 65.476366 s, objective = [134, 10] Solution 17,
time = 69.326066 s, objective = [133, 10] Solution 18, time = 74.343236 s,
objective = [132, 10] Solution 19, time = 76.687988 s, objective = [129,
10] Solution 20, time = 81.556761 s, objective = [128, 10] Solution 21,
time = 86.442065 s, objective = [119, 10] Solution 22, time = 91.478462 s,
objective = [118, 10] Solution 23, time = 95.965267 s, objective = [117,
10] Solution 24, time = 97.101844 s, objective = [116, 10] Solution 25,
time = 101.974791 s, objective = [108, 10] Solution 26, time = 104.984996
s, objective = [107, 10] Solution 27, time = 110.034418 s, objective =
[106, 10] Solution 28, time = 110.605319 s, objective = [105, 10] Solution
29, time = 115.283544 s, objective = [104, 10] Solution 30, time =
120.026350 s, objective = [103, 10]
*...*
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
