### ISSUE TITLE
How to add custom constraints C++

### ISSUE THREAD

**Issue by Nassimbelmecheri** [google/or-tools#972]
I would like to create my own constraint and then wrap it in python can someone please give me a link to some documentations.
Thank you

**Comment by Mizux** [comment]
to wrap C++ code to python we are using swig, you can look at the Makefile(s) or CMakeLists.txt to see how to do it. but it's not so easy...

for SWIG you can find documentation here: http://www.swig.org/Doc3.0/SWIGDocumentation.html

**Comment by Nassimbelmecheri** [comment]
what about creating a custom constraint in c++ i couldn't find any
documentation on that , there was one but it didn't show anything on how to
create a custom constraint. please help

**Comment by lperron** [comment]
Look at examples/cpp/dobble_ls.cc
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 11 déc. 2018 à 10:18, Nassimbelmecheri <notifications@github.com> a
écrit :

> what about creating a custom constraint in c++ i couldn't find any
> documentation on that , there was one but it didn't show anything on how to
> create a custom constraint. please help
>

**Comment by lperron** [comment]
Closing
