### ISSUE TITLE
Running multiple instances of CBC in parallel [Java]

### ISSUE THREAD

**Issue by smpawlowski** [google/or-tools#974]
Hi!

I'm trying to run multiple instances of MPSolver / CBC_MIXED_INTEGER_PROGRAMMING concurrently on a single JVM. It works, but the work load doesn't seem to be distributed across multiple cores. On a 16 core machine CPU utilization looks worse than running a single instance of MPSolver.

I use OR-TOOLS v 6.10 on Windows built from src with default flags.

Can you advise?

Best regards
Slawomir

**Comment by smpawlowski** [comment]
Thanks for response! I gave it plenty of memory and it's 16 physical cores. I'm just using fixed thread pool in Java and I did not put any threading settings into or-tools. Looking at CPU utilization I thought there is some synchronization happening down the line. I will investigate more.

**Comment by smpawlowski** [comment]
I have tested on 2 cases:
1) Test case. DietMIP example (small problem) with CBC. I run 50_000 problems in parallel using Executors.newFixedThreadPool. If solver.delete() is called after solver.solve() parallel performance is great. I didn't use solver.delete() before, in which case CPU utilization is high at the beginning and then radically drops. It doesn't seem to be memory related as both jvm and system show less than 50% of physical memory utilized. Using more threads than physical cores doesn't seem to be a significant problem in this case.

2) Real case: problem has 18_502 binary variables, 528 continuous variables, 288 constraints. I'm running about 20 of those in parallel. I'm calling solver.delete() after each solver.solve(). With 3 concurrent jobs I can see 3 cores fully utilized as I would expect. With more than 3 concurrent jobs I can see more cores utilized at a low percentage resulting in overall throughput close to single-threaded. I look at jvm and system memory utilization and both are below 50%.

Case 1 running fine and 2 having problems makes me think that the issue is with CLP. 

I tried to build or-tools with GLPK 4.65 precompiled binaries to test that. I followed
https://developers.google.com/optimization/install/java/source_windows
https://developers.google.com/optimization/support/release_notes#glpk-support
http://or-tools.blogspot.com/2017/03/linking-glpk-with-or-tools-on-unix.html

but I'm getting 
glpk_interface.cc
.\\ortools\\linear_solver\\glpk_interface.cc(38): fatal error C1083: Cannot open
 include file: 'glpk.h': No such file or directory

I'd rather avoid building GLPK from source. Any hints?

Best regards!
Slawomir

**Comment by smpawlowski** [comment]
Thanks a lot for your help!
Looks like I didn't install GLPK correctly. I will build it first and try again.

I just added
WINDOWS_GLPK_DIR=C:\dev\glpk-4.65\w64
to Makefile.local in or-tools
The directory above contains all pre-compiled GLPK 4.65 binaries from
http://winglpk.sourceforge.net/ 
that contain .lib, but not glpk.h. Looking at tools\make print-CFLAGS the folder I tried to use doesn't contain the expected structure of lib, include.

C:\dev\or-tools-6.10>tools\make print-CFLAGS
'python' is not recognized as an internal or external command,
operable program or batch file.
CFLAGS = -nologo  /D__WIN32__ /DPSAPI_VERSION=1 /DNOMINMAX /O2 -DNDEBUG /I. /Ior
tools/gen /I"dependencies\\install\\include" /I"dependencies\\install\\include"
/DGFLAGS_DLL_DECL= /DGFLAGS_DLL_DECLARE_FLAG= /DGFLAGS_DLL_DEFINE_FLAG= /I"depen
dencies\\install\\include" /DGOOGLE_GLOG_DLL_DECL= /I"dependencies\\install\\inc
lude" /I"dependencies\\install\\include" /I"dependencies\\install\\include\\coin
" /I"dependencies\\install\\include" /I"dependencies\\install\\include\\coin" /I
"dependencies\\install\\include" /I"dependencies\\install\\include\\coin" /DUSE_
CLP /I"dependencies\\install\\include" /I"dependencies\\install\\include\\coin"
/I"dependencies\\install\\include" /I"dependencies\\install\\include\\coin" /DUS
E_CBC /DUSE_GLOP /DUSE_BOP /IC:\dev\glpk-4.65\w64\\include /DUSE_GLPK

full trace when I try to build or-tools with GLPK
C:\dev\or-tools-6.10>tools\make java
'python' is not recognized as an internal or external command,
operable program or batch file.
cl /EHsc /MD /nologo -nologo  /D__WIN32__ /DPSAPI_VERSION=1 /DNOMINMAX /O2 -DNDE
BUG /I. /Iortools/gen /I"dependencies\\install\\include" /I"dependencies\\instal
l\\include" /DGFLAGS_DLL_DECL= /DGFLAGS_DLL_DECLARE_FLAG= /DGFLAGS_DLL_DEFINE_FL
AG= /I"dependencies\\install\\include" /DGOOGLE_GLOG_DLL_DECL= /I"dependencies\\
install\\include" /I"dependencies\\install\\include" /I"dependencies\\install\\i
nclude\\coin" /I"dependencies\\install\\include" /I"dependencies\\install\\inclu
de\\coin" /I"dependencies\\install\\include" /I"dependencies\\install\\include\\
coin" /DUSE_CLP /I"dependencies\\install\\include" /I"dependencies\\install\\inc
lude\\coin" /I"dependencies\\install\\include" /I"dependencies\\install\\include
\\coin" /DUSE_CBC /DUSE_GLOP /DUSE_BOP /IC:\dev\glpk-4.65\w64\\include /DUSE_GLP
K    -c .\\ortools\\linear_solver\\glpk_interface.cc /Foobjs\\linear_solver\\glp
k_interface.obj
glpk_interface.cc
.\\ortools\\linear_solver\\glpk_interface.cc(38): fatal error C1083: Cannot open
 include file: 'glpk.h': No such file or directory
tools\make: *** [objs/linear_solver/glpk_interface.obj] Error 2

Best regards!
Slawomir

**Comment by smpawlowski** [comment]
I built or-tools with GLPK included. I tested again with my real-world problem - 18_502 binary variables, 528 continuous variables, 288 constraints, ~20 of those run in parallel.

1. With CBC_MIXED_INTEGER_PROGRAMMING I see low CPU utilization (~8%) across multiple cores. I monitored jvisualvm and taskmgr. I see no GC activity to speak of and memory utilization in both JVM and system is well below 50%.

2. With GLPK_MIXED_INTEGER_PROGRAMMING I see full CPU utilization, however the time to solution seems orders of magnitude slower than CBC_MIXED_INTEGER_PROGRAMMING. Memory consumption and GC are just like 1.

I would like to use CBC_MIXED_INTEGER_PROGRAMMING in parallel mode. Could it be that each CBC instance attempts their own multi-threaded execution and they clash causing slowness? Do you think it might help to include CBC built in single-threaded mode? Each CBC instance should then run in it's own thread? If this is indeed a memory problem could you advice what would be the way to monitor and confirm it?

Best regards
Slawomir
____________________________________________________________________________________________
Just in case it helps someone - to build or tools with GLPK I carried out following steps:
1) Download GLPK source.
2) Build using w64\Build_GLPK_with_VC14.bat -> this will create glpk.lib. I used Visual Studio 2015.
3) Create a directory containing:
a) lib\glpk.lib
b) include\glpk.h
4) The rest as per or-tools build instructions - include WINDOWS_GLPK_DIR = glpk_dir in makefile.local

**Comment by lperron** [comment]
You can.
Not sure it will improve performance.

Anyway, if you use SetNumThreads() on the linear_solver using CBC, it does pass the right parameters to CBC.

And we do compile with CBC support. So if it does use all threads, it is a CBC bug.
