### ISSUE TITLE
I need a vehicle to make multiple trips

### ISSUE THREAD

**Issue by pmvbajpai** [google/or-tools#976]
I am using OR Tools using Python and would like to use multiple trips of a vehicle as the cost of using that vehicle is less compare to other vehicle. Could you please suggest me about the same?

Problem Statement:
1. TS09UA5627 - (Capacity - 20) - (Cost - 5)
2. TS09UB7297 - (Capacity - 50) - (Cost - 100)
3. TS09UA8646 - (Capacity - 75) - (Cost - 150)
4. TS08UV9283 - (Capacity - 80) - (Cost - 160)
5. TS09UA2435 - (Capacity - 85) - (Cost - 170)

I would like to use vehicle 1 many times as cost is saved.

**Comment by pmvbajpai** [comment]
Thanks a lot for the information. I have duplicated the depots as you mentioned. Added last 2 in the attached sheet. 

SetFixedCostOfVehicle was already added in my python script as I am using cvrptw_plot.py to solve my constraints. 

This still is not repeating the vehicle and using the individual vehicles. Could you please let me know what am I doing wrong.  (I have added comments in the CSV file attached below)

Thanks in advance !!

[routeParameters.xlsx](https://github.com/google/or-tools/files/2686027/routeParameters.xlsx)

**Comment by Mizux** [comment]
Are you sure the TW allow one vehicle to travel back to depot then perform the next "trip".
Otherwise the solver has to use other vehicle to be on time at each location...

**Comment by pmvbajpai** [comment]
Yes, I have tried with a large time window of 16 hours for nearby locations but its not working. Also, I can give only time in hours and minutes, I cannot assign dates in time windows - is there a way out please?

**Comment by Mizux** [comment]
Please provide a code source, otherwise take a second look at cvrp_reload.py

**Comment by pmvbajpai** [comment]
Please find the code in the zip format. 

final.py is the file which takes parameters from routeParameters.csv

Thank you for all the help.

[final code.zip](https://github.com/google/or-tools/files/2701568/final.code.zip)

**Comment by pmvbajpai** [comment]
Did you get some time to check the code please?

**Comment by DavidLSmyth** [comment]
I'm also interested in figuring this out, I am trying to plan routes for a heterogeneous (they work with different fuel capacities, operational speeds, service times) fleet of vehicles to visit a set of points, with the ability to return the the depot to recharge and then set out again, with the objective to minimize total time taken to visit all points. A single, well-documented example of how this could be done would help close some related issues (#862, #878). I am close to finding a solution but I'm not sure it's the 'right' way to model it using the tools provided in this repo. 

Thanks for the fantastic work done to create ortools!

**Comment by CognitiveClouds-Prasad** [comment]
Can anybody let me know as to when this would be added?

**Comment by lperron** [comment]
See https://github.com/google/or-tools/blob/master/ortools/constraint_solver/samples/cvrp_reload.py

**Comment by silencemao** [comment]
[](https://github.com/google/or-tools/blob/master/ortools/constraint_solver/samples/cvrp_reload.py)
when run this code, it has the error information like bellow:
Traceback (most recent call last):
  File "/Users/sf/Desktop/code/python/VRP/code/cvrp_reload.py", line 326, in <module>
    main()
  File "/Users/sf/Desktop/code/python/VRP/code/cvrp_reload.py", line 292, in main
    manager = pywrapcp.RoutingIndexManager(data['num_locations'],
AttributeError: module 'ortools.constraint_solver.pywrapcp' has no attribute 'RoutingIndexManager'

**Comment by lperron** [comment]
You should use the latest version of or-tools (7.3).

Le mer. 7 août 2019 à 01:14, kongxiangmao <notifications@github.com> a
écrit :

**Comment by jagratigogia42** [comment]
> You need two things:
> 
> * duplicate the depot to allow reload/multi trip: see https://github.com/google/or-tools/blob/master/examples/python/cvrp_reload.py
> * set a Vehicle fixed cost so the solver has incentive to use the same vehicle to minimize the objective. see https://github.com/google/or-tools/blob/0d93b2079cb0192f151e32a17b336d07ce22dc50/ortools/constraint_solver/routing.h#L697-L705

Hi @Mizux ,
Actually trying to find a workaround for the exact same goal, to be able to use the same vehicle to do multiple trips, i.e. any number of trips that is feasible in the given time window.

Your solution references a code link, but it's broken. Could you update the link or point me to a solution for the problem mentioned here?

Thanks.

**Comment by Mizux** [comment]
@jagratigogia42  moved to ortools/constraint_solver/samples:
https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/samples/cvrp_reload.py

**Comment by ViveK-PothinA** [comment]
Hello @Mizux 

I'm also trying to solve for the same vehicle to do multiple trips feasible in the time window.

I have tried out the cvrp_reload sample: https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/samples/cvrp_reload.py

I have modified it, so that I can handle lat lng in locations and I'm using radial distance instead of manhattan distance.
But I'm getting 0km output for all vehicles, basically the solver is saying there is a solution, but all are 0.

```
Objective: 300000
dropped orders: [6, 7, 8]
dropped reload stations: [6, 7, 8, 1, 2, 3, 4, 5]
Route for vehicle 0:
 0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
Distance of the route: 0m
Load of the route: 0
Time of the route: 0min

Route for vehicle 1:
 0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
Distance of the route: 0m
Load of the route: 0
Time of the route: 0min

Route for vehicle 2:
 0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
Distance of the route: 0m
Load of the route: 0
Time of the route: 0min

Route for vehicle 3:
 0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
Distance of the route: 0m
Load of the route: 0
Time of the route: 0min

Route for vehicle 4:
 0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
Distance of the route: 0m
Load of the route: 0
Time of the route: 0min

Route for vehicle 5:
 0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
Distance of the route: 0m
Load of the route: 0
Time of the route: 0min

Route for vehicle 6:
 0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
Distance of the route: 0m
Load of the route: 0
Time of the route: 0min

Route for vehicle 7:
 0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
Distance of the route: 0m
Load of the route: 0
Time of the route: 0min

Route for vehicle 8:
 0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
Distance of the route: 0m
Load of the route: 0
Time of the route: 0min

Route for vehicle 9:
 0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
Distance of the route: 0m
Load of the route: 0
Time of the route: 0min

Total Distance of all routes: 0m
Total Load of all routes: 0
Total Time of all routes: 0min
```

This is gist link to the modified code: https://gist.github.com/ViveK-PothinA/a85445d79e6ee302129f927b29c55c33

Please help me identify where I'm going wrong. Thanks in advance.

**Comment by abvhove** [comment]
> @jagratigogia42 moved to ortools/constraint_solver/samples:
> https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/samples/cvrp_reload.py
> EDIT: Just fixed the path in the previous post...

Thanks for the link. But can you help in a case where the capacity of the vehicles are different ?
I have 31 vehicles with 4 different capacities. I'm looking for a solution where the vehicles return to the depot when they're empty but can't get the solution ...

**Comment by GeorgeLeucuta** [comment]
> Hello @Mizux
> 
> I'm also trying to solve for the same vehicle to do multiple trips feasible in the time window.
> 
> I have tried out the cvrp_reload sample: https://github.com/google/or-tools/blob/stable/ortools/constraint_solver/samples/cvrp_reload.py
> 
> I have modified it, so that I can handle lat lng in locations and I'm using radial distance instead of manhattan distance. But I'm getting 0km output for all vehicles, basically the solver is saying there is a solution, but all are 0.
> 
> ```
> Objective: 300000
> dropped orders: [6, 7, 8]
> dropped reload stations: [6, 7, 8, 1, 2, 3, 4, 5]
> Route for vehicle 0:
>  0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
> Distance of the route: 0m
> Load of the route: 0
> Time of the route: 0min
> 
> Route for vehicle 1:
>  0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
> Distance of the route: 0m
> Load of the route: 0
> Time of the route: 0min
> 
> Route for vehicle 2:
>  0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
> Distance of the route: 0m
> Load of the route: 0
> Time of the route: 0min
> 
> Route for vehicle 3:
>  0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
> Distance of the route: 0m
> Load of the route: 0
> Time of the route: 0min
> 
> Route for vehicle 4:
>  0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
> Distance of the route: 0m
> Load of the route: 0
> Time of the route: 0min
> 
> Route for vehicle 5:
>  0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
> Distance of the route: 0m
> Load of the route: 0
> Time of the route: 0min
> 
> Route for vehicle 6:
>  0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
> Distance of the route: 0m
> Load of the route: 0
> Time of the route: 0min
> 
> Route for vehicle 7:
>  0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
> Distance of the route: 0m
> Load of the route: 0
> Time of the route: 0min
> 
> Route for vehicle 8:
>  0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
> Distance of the route: 0m
> Load of the route: 0
> Time of the route: 0min
> 
> Route for vehicle 9:
>  0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
> Distance of the route: 0m
> Load of the route: 0
> Time of the route: 0min
> 
> Total Distance of all routes: 0m
> Total Load of all routes: 0
> Total Time of all routes: 0min
> ```
> 
> This is gist link to the modified code: https://gist.github.com/ViveK-PothinA/a85445d79e6ee302129f927b29c55c33
> 
> Please help me identify where I'm going wrong. Thanks in advance.

Hello,
Did you manage to find a solution for this issue?

**Comment by Mizux** [comment]
> 

@GeorgeLeucuta 

1. Your distance callback must return an `int`
```python
    def distance_evaluator(manager, from_index, to_index):
        """Returns the manhattan distance between the two nodes"""
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        dst = int(_distances[from_node][to_node]) # see the cast here
        #print(f'dst: {dst}') # for debug purpose
        return dst
```

2. also all your distance seems to be around 30k-50k so to incentive the solver to avoid to drop the node you need to increase the penalty
```python
    # Allow to drop regular node with a cost.
    for node in range(6, len(data['demands'])):
        node_index = manager.NodeToIndex(node)
        capacity_dimension.SlackVar(node_index).SetValue(0)
        routing.AddDisjunction([node_index], 10_000_000)
```

Then possible output:
```sh
./cvrp_reload_1.py
Objective: 9258964
dropped orders: []
dropped reload stations: [1, 2, 3, 4, 5]
Route for vehicle 0:
 0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
Distance of the route: 0m
Load of the route: 0
Time of the route: 0min

Route for vehicle 1:
 0 Load(0) Time(0,0) -> 8 Load(0) Time(109,120) -> 0 Load(3) Time(233,1500)
Distance of the route: 90956m
Load of the route: 3
Time of the route: 233min

Route for vehicle 2:
 0 Load(0) Time(0,0) -> 7 Load(0) Time(61,120) -> 0 Load(3) Time(137,1500)
Distance of the route: 51538m
Load of the route: 3
Time of the route: 137min

Route for vehicle 3:
 0 Load(0) Time(0,0) -> 6 Load(0) Time(60,120) -> 0 Load(3) Time(100,1500)
Distance of the route: 20870m
Load of the route: 3
Time of the route: 100min

Total Distance of all routes: 163364m
Total Load of all routes: 9
Total Time of all routes: 470min
```
note: I set vehicle to 4 instead of 10 (BTW you only have 3 node other are reload nodes...)

**Comment by GeorgeLeucuta** [comment]
> > 
> 
> @GeorgeLeucuta
> 
> 1. Your distance callback must return an `int`
> 
> ```python
>     def distance_evaluator(manager, from_index, to_index):
>         """Returns the manhattan distance between the two nodes"""
>         from_node = manager.IndexToNode(from_index)
>         to_node = manager.IndexToNode(to_index)
>         dst = int(_distances[from_node][to_node]) # see the cast here
>         #print(f'dst: {dst}') # for debug purpose
>         return dst
> ```
> 
> 2. also all your distance seems to be around 10k-25k so to incentive the solver to avoid to drop the node you need to increase the penalty
> 
> ```python
>     # Allow to drop regular node with a cost.
>     for node in range(6, len(data['demands'])):
>         node_index = manager.NodeToIndex(node)
>         capacity_dimension.SlackVar(node_index).SetValue(0)
>         routing.AddDisjunction([node_index], 10_000_000)
> ```
> 
> Then possible output:
> 
> ```shell
> ./cvrp_reload_1.py
> Objective: 9258964
> dropped orders: []
> dropped reload stations: [1, 2, 3, 4, 5]
> Route for vehicle 0:
>  0 Load(0) Time(0,0) -> 0 Load(0) Time(0,1500)
> Distance of the route: 0m
> Load of the route: 0
> Time of the route: 0min
> 
> Route for vehicle 1:
>  0 Load(0) Time(0,0) -> 8 Load(0) Time(109,120) -> 0 Load(3) Time(233,1500)
> Distance of the route: 90956m
> Load of the route: 3
> Time of the route: 233min
> 
> Route for vehicle 2:
>  0 Load(0) Time(0,0) -> 7 Load(0) Time(61,120) -> 0 Load(3) Time(137,1500)
> Distance of the route: 51538m
> Load of the route: 3
> Time of the route: 137min
> 
> Route for vehicle 3:
>  0 Load(0) Time(0,0) -> 6 Load(0) Time(60,120) -> 0 Load(3) Time(100,1500)
> Distance of the route: 20870m
> Load of the route: 3
> Time of the route: 100min
> 
> Total Distance of all routes: 163364m
> Total Load of all routes: 9
> Total Time of all routes: 470min
> ```
> 
> note: I set vehicle to 4 instead of 10 (BTW you only have 3 node other are reload nodes...)

Hello @Mizux,
 
First of all thank you very much for your support!

Your scenario seems to only work when the vehicle capacity is equal between all the vehicles. In my case the cars have different capacities. It is possible to adapt it to take this factor into consideration? 
Or is it possible to modify the `demand_callback` function so that it sets the vehicle load to 0 for specific nodes(depot)? If so, can you please provide an example? 

Thanks a lot!

**Comment by Mizux** [comment]
yes you'll need to duplicate depot several times i.e. one per "potential reload"

**Comment by GeorgeLeucuta** [comment]
> yes you'll need to duplicate depot several times i.e. one per "potential reload"

@Mizux 
 
Thank you!

Can you please give me an idea on how to approach the first issue?

"Your scenario seems to only work when the vehicle capacity is equal between all the vehicles. In my case the cars have different capacities. It is possible to adapt it to take this factor into consideration?
Or is it possible to modify the demand_callback function so that it sets the vehicle load to 0 for specific nodes(depot)? If so, can you please provide an example?" 

Best regards!
