### ISSUE TITLE
Crash during solving MILP - SCIP

### ISSUE THREAD

**Issue by eliempje** [google/or-tools#978]
Dear all,
I've made a MILP model in OR tools to use with a SCIP solver with python. Have a quite a large problem with 10.449.128
variables and 17.313.896 constraints. Defining the model works fine.
Then executing (or verifying the solution) the solver crashes with the following output:

> [C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\blockmemshell\memory.c:1052] ERROR: Insufficient memory for allocation of 917592 bytes.
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\cons.c:5846] ERROR: Insufficient memory for new chunk.
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\cons.c:5846] ERROR: No memory in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\scip_cons.c:1052] ERROR: Error <-1> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\cons_linear.c:17721] ERROR: Error <-1> in function call
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1217 20:53:33.090278 12464 scip_interface.cc:398] Check failed: SCIP_OKAY == SCIPcreateConsLinear( scip_, &scip_constraint, ct->name().empty() ? "" : ct->name().c_str(), size, vars.get(), coefs.get(), ct->lb(), ct->ub(), !is_lazy, true, true, true, true, false, false, false, is_lazy, false) (1 vs. -1)
*** Check failure stack trace: ***

I use a own compiled version of OR tools to be able to use SCIP solver.

Windows gives a (low) memory error and closed python. Is this a general error due to low memory or a  bug?

**Comment by lperron** [comment]
Low memory. It is not a bug :-)
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by ugrylmz** [comment]
Hello everyone, 
We have tried to solve assignment problem with huge data, with SCIP solver
python: 3.7, ortools: 9.0.9048
64 gb ram, Windows, Intel Xeon CPU E5-2673 v4 2.30 ghz
Number of variables = 7051200
Number of constraints = 50420724,
we faced this error:
```
or-tools scip 7.0.1 block memshell memory c 1059 ERROR: Insufficient memory for allocation of 1048648 bytes.


[C:\Users\or_tools_project\work\or-tools\dependencies\sources\scip-7.0.1\src\blockmemshell\memory.c:1059] ERROR: Insufficient memory for allocation of 1048648 bytes.
[C:\Users\or_tools_project\work\or-tools\dependencies\sources\scip-7.0.1\src\scip\cons_linear.c:879] ERROR: Insufficient memory for new chunk.
[cons_linear.c:879] ERROR: Error <-1> in function call
[cons_linear.c:15788] ERROR: Error <-1> in function call
[cons.c:6438] ERROR: Error <-1> in function call
[prob.c:584] ERROR: Error <-1> in function call
[scip_solve.c:409] ERROR: Error <-1> in function call
[scip_solve.c:2390] ERROR: Error <-1> in function call
[scip_solve.c:2620] ERROR: Error <-1> in function call
WARNING: Logging before InitGoogleLogging() is written to STDERR
E00-1 -1:-1:-1.338378   252 linear_solver.cc:1699] The model has been changed since the solution was last computed. MPSolverInterface::sync_status_ = 1
E00-1 -1:-1:-1.454833   252 linear_solver.cc:1699] The model has been changed since the solution was last computed. MPSolverInterface::sync_status_ = 1
```

**Comment by lperron** [comment]
The problem does not fit in memory.
Not much we can do on our side.

Le mer. 2 juin 2021 à 18:30, Uğur Yılmaz ***@***.***> a
écrit :
