### ISSUE TITLE
VRP: non-travelling node (kind of like a break but without assignment to a vehicle)

### ISSUE THREAD

**Issue by vbezuglyy** [google/or-tools#981]
Is it possible to specify a node so that the distance to and from this node is 0 but traveling through it is not zero? So analogy would be some tasks performed at location. I first thought about breaks, but they are assigned to each vehicle, but I'd rather need a fixed set of such nodes (breaks, or non-travelling nodes) and they should be visited by any vehicles.

**Comment by Mizux** [comment]
what you means by distance vs traveling ?
You may code any TransitCallback for any dimension t oreturn zero for specific nodes, as well as do the same for the ArcCostCallback...

**Comment by vbezuglyy** [comment]
I mean that if I have such node X, that path 1 - X - 2 has the same distance as 1-2, but it's not possible to specify it via callback, because I need to specify distances 1-X and X-2 and I can say that these are 0 but I cannot say that 1-X-2 is some value.

**Comment by Mizux** [comment]
ack, yes, this is not supported.
side note: There is a break API since you can't model a break as a X node (following your example naming convention)...

**Comment by braktar** [comment]
As you can access the routing vars from the callback, you can ask the NextVar of X and if for this NextVar Bound() is true you can define access the Distance From 1 to 2 through X, if not bound my advice is to consider the next node as the ending node.

It is pretty awful and the results are extremely variable.

**Comment by vbezuglyy** [comment]
> As you can access the routing vars from the callback, you can ask the NextVar of X and if for this NextVar Bound() is true you can define access the Distance From 1 to 2 through X, if not bound my advice is to consider the next node as the ending node.
> 
> It is pretty awful and the results are extremely variable.

Could you maybe elaborate? I'm not sure I understood what you mean

**Comment by jmarca** [comment]
Maybe another way is to create a dummy nodes at 1.

So, you said distance (1 - X - 2) == distance (1 - 2),  which I can't see how to do.  But what if you instead required 1 -> X -> 1' -> 2.  

Because 1 and 1' are in the same place, dist(1,2) == dist(1',2).  And travel to and from X to anywhere is 0.  So that fits your requirements.

To make it happen, you'd have to use some sort of conditional constraint, such that if `NextVar (1) == X`, then `NextVar(X) == 1'` (require the trip *back* from X to the colocated 1').

**Comment by vbezuglyy** [comment]
@jmarca Thanks for you input. I thought of dummy nodes but I don't think it'd work in my case because I don't want to stick to a particular node (1 - in this case). What I'd like to think in terms of VRP is that I have some travelling nodes which I have to visit (and they may have demand there as well) and there would be some non-travelling nodes which also maybe have demand on them (so visiting them would not take time to travel but time to serve). I was looking at the example with "stops" in example section but this also does not do it in my case.

**Comment by vbezuglyy** [comment]
@jmarca Thanks, now I seem to get it. I am trying to go in this direction, so I assume that for each "normal" node A there is a a "fake" node A' with the same location. Also I need a "fake" start depot for each vehicle. The condition is a bit more complicated when I originally thought, in fact. It's not just if there is a path "A->some-non-travel node", then there should be a path "some-non-travel-node -> A". There maybe any combination of non-travel nodes in the model between A and A'. Also there should be some condition which restricts A' appearing anywhere else. If I can figure out the way to do it, I'll post the solution.

**Comment by braktar** [comment]
@vbezuglyy my proposition is more or less the following

`int64 Distance(RoutingModel::NodeIndex i, RoutingModel::NodeIndex j) const {
      if (j.value() == X) {
        IntVar* next_var = routing->NextVar(j.value());
        if (next_var->Bound()) {
          return Distance(i, routing->IndexToNode(next_var->Value()));
        } else {
          return Distance(i, Stop());
        }
      }
      return distance_matrix->Cost(RoutingModel::NodeIndex(i.value()),
        RoutingModel::NodeIndex(j.value()));
    }`

**Comment by lperron** [comment]
ANy progress ?
I am closing the issue. Please reopen if needed.
