### ISSUE TITLE
SetCumulVarSoftUpperBound on End node does no effect

### ISSUE THREAD

**Issue by smagafurov** [google/or-tools#983]
Hi! I try to use `SetCumulVarSoftUpperBound` to stimulate each vehicle to have average orders count.

Short example:
```python
avg_done_count = 10
routing.AddConstantDimension(1, 999999999, True, 'total_done')
total_done_dimension = routing.GetDimensionOrDie('total_done')
for route in routes:
    _i = routing.End(route)
    total_done_dimension.SetCumulVarSoftUpperBound(_i, avg_done_count, 1000)
```

And this does not add any value to total cost.

But when i make it for all orders instead of `Ends` it works:

```python
avg_done_count = 10
routing.AddConstantDimension(1, 999999999, True, 'total_done')
total_done_dimension = routing.GetDimensionOrDie('total_done')
for order in orders:
    _i = routing.NodeToIndex(order)
    total_done_dimension.SetCumulVarSoftUpperBound(_i, avg_done_count, 1000)
```

Why it does not work with Ends?
or-tools version: 6.10.6025

**Comment by danmarinescu** [comment]
Ran into the same issue. @smagafurov did you find an answer to your question?

In my case I am trying to a cost to a vehicle "working" during overtime, and the way I thought to do that is to set a soft upper bound on the time dimension of the end node

**Comment by smagafurov** [comment]
> @smagafurov did you find an answer to your question?

No.
My workaround to apply `SetCumulVarSoftUpperBound` on orders instead of `Ends` solves my task.
You can try this workaround too.

**Comment by danmarinescu** [comment]
Thanks @smagafurov , I'm afraid that doesn't work for my use case. 

However, I noticed I am using release 6.10 of ortools which has a method called [SetEndCumulVarSoftUpperBound](https://github.com/google/or-tools/blob/v6.10/ortools/constraint_solver/routing.h#L1010) which does the trick. This method was [removed](https://github.com/google/or-tools/commit/b027e57e95e2f70d17c28d6f6319e57dcbbd46b2#diff-72f6d61ab9adc4958dc30b74a014986f) in the later versions and judging by that commit `SetCumulVarSoftUpperBound` should now also work for `Ends`.

**Comment by lperron** [comment]
Closing now. Reopen if it does not work with 7.3
