### ISSUE TITLE
Signing of .NET assemblies not working

### ISSUE THREAD

**Issue by sorensenmatias** [google/or-tools#985]
When I compile .NET dlls using tools\make dotnet, I see that it is attempted to sign the assemblies using the keyfile or-tools.snk.
However, this is not working for some reason. When referencing the dlls in a context which requires them to be signed, an error is thrown: "Referenced assembly 'Google.ORTools.dll' does not have a strong name".

I have worked around it by not signing the dlls by editing the files `Google.OrTools.csproj` and `Google.OrTools.runtime.win-x64.csproj` with the following changes:

SignAssembly>false</SignAssembly>
<DelaySign>false</DelaySign>
Remove PublicSign attribute

**Comment by lperron** [comment]
Should be fixed. We use the same snk files for all our runtime builds.
