### ISSUE TITLE
There is an example does not work

### ISSUE THREAD

**Issue by maxnilz** [google/or-tools#986]
Hi, I'm learning the python code, and I found there is an example does not work:
https://github.com/google/or-tools/blob/master/examples/python/flexible_job_shop_sat.py

It shows an error:
```
$ python flexible_job_shop_sat.py 
Horizon = 40
terminate called after throwing an instance of 'Swig::DirectorMethodException'
  what():  SWIG director method error. Error detected when calling 'SolutionCallback.OnSolutionCallback'
Aborted (core dumped)
```

Python version:
```
Python 3.7.0 (default, Aug 24 2018, 20:15:24) 
[GCC 5.4.0 20160609] on linux
```

Or-tools version:
```
$ pip list|grep ortools
ortools                  6.9.5824
```

**Comment by lperron** [comment]
Please upgrade to 6.10.

The name of the method has changed since then, and the example reflects the
new name.

Thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by maxnilz** [comment]
Thanks very much, it works when I upgrade to 6.10

**Comment by Mizux** [comment]
@maxnilz you can use `pip show ortools`
