### ISSUE TITLE
TypeError: in method 'RoutingModel_AddDimension', argument 4 of type 'int64'

### ISSUE THREAD

**Issue by abduakhatov** [google/or-tools#989]
According to [multi-capacity constraint](https://developers.google.com/optimization/routing/cvrp#example_python) it is possible to add several capacities for the car as constraint (Routing problem with capacity constraint). But When I do this, the error received: 
`TypeError: in method 'RoutingModel_AddDimension', argument 4 of type 'int64'`
Code:

```capacity = "Capacity"
    routing.AddDimension(
        demand_evaluator,
        0,  # null capacity slack
        [15,15,15],  # vehicle maximum capacity
        True,  # start cumul to zero
        capacity)
```

As long as I replace: ` [15,15,15]` above to single capacity `15` it is working. Strange. 

p.s. I casted to `int(i)` each element, still not working.

**Comment by Mizux** [comment]
Because you were using:
https://github.com/google/or-tools/blob/769d9d3ff4773869c3420029d0109c0f0e3936b1/ortools/constraint_solver/routing.h#L405-L406
while you wanted to use:
https://github.com/google/or-tools/blob/769d9d3ff4773869c3420029d0109c0f0e3936b1/ortools/constraint_solver/routing.h#L410-L413

**Comment by SomagecDji** [comment]
I'm facing the same problem, could you please elaborate your solution ?

**Comment by lperron** [comment]
Please don't revive year's old issues.

Most likely, you are passing an argument which is not an integer.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le mer. 16 juin 2021 à 12:30, SomagecDji ***@***.***> a
écrit :
