### ISSUE TITLE
Missing dependeny? com.google.ortools.sat.CpModelProto

### ISSUE THREAD

**Issue by espre05** [google/or-tools#993]
https://github.com/google/or-tools/blob/9fbc6ca6a6da7126cc120643f67712a679e733df/ortools/com/google/ortools/sat/IntVar.java#L16

Where can I find this dependency in this codebase? 
![image](https://user-images.githubusercontent.com/731599/50380784-07804b00-0641-11e9-9f92-ca647d995102.png)

**Comment by lperron** [comment]
It is generated in ortools/gen/com/google/ortools/sat
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
