### ISSUE TITLE
Routing Capacity no result for bigger max capacity and demand capacity with same ratio

### ISSUE THREAD

**Issue by abduakhatov** [google/or-tools#995]
Hello @Mizux )) Thank you for support!

Copy pasted [example](https://developers.google.com/optimization/routing/cvrptw). With same data working perfectly. However, there is big but, when I change sample data: 
from: 
``` 
  demands = [0, # depot
             1, 1, # row 0
             2, 4,
             2, 4,
             8, 8,
             1, 2,
             1, 2,
             4, 4,
             8, 8]
  capacities = [15, 15, 15, 15]
```

to (multiply to 10, ex)
```
demands = [0, # depot
             10, 10, # row 0
             20, 40,
             20, 40,
             80, 80,
             10, 20,
             10, 20,
             40, 40,
             80, 80]
  capacities = [150, 150, 150, 150]
 ``` 
The solver is thinking too much and not stopping, even without error. For this purpose I set time limit to = 10 seconds, and result is None.

Please note, I have not changed ratio between demand and capacities of vehicle, so no result.
Also, I have increased capacities to more larger values, still not working.

P.S. This is example is for testing purpose. In actual code of mine which is similar case.

**Comment by Mizux** [comment]
This example use capacity **and** Time Windows.
Time dimension use a arc cost i.e. transit callback computed as:
`Transit(A, B) = ServiceTime(A) + TravelTime(A, B)` 
and... service time is computed as `data['time_per_demand_unit'] * data['demand'][index]`
with `data['time_per_demand_unit'] == 5 min` IIRC.

So when you increase demands by `10x` -> you increase service time by `10x` -> no solution can be found -> solver seems to hang searching for a while for an impossible solution Q.E.D.
